### ISSUE TITLE
Tiefschreitertumor 

### ISSUE THREAD

**Issue by nightblizard** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1000]
http://datenbank.welli-it.de/?item=6082 dropt fälschlicher Weise bei http://datenbank.welli-it.de/?npc=741 anstelle von http://datenbank.welli-it.de/?npc=4686 bzw. http://datenbank.welli-it.de/?npc=4687

Siehe Kommentare:
http://www.wowhead.com/item=6082/green-whelp-blood

**Comment by Gnomorus** [comment]
Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

**Comment by hraesvelgr** [comment]
liegt daran, dass die quest redesigned wurde. nat+rlich sollten die tiefenschreiter auch die tiefenschreitertumore droppen. mit 2.2.3 wurde das dann entfernt, und welplinge sollten welplingblut droppen, um die quest zu beenden.


>Patch 2.2.3 (2007-10-09):  Deepstrider Tumors are no longer an objective of this quest, eliminating the need for players to switch continents for a quest objective. The tumors were replaced with Green Whelp Blood. In his description, Apothecary Faustin would say Now the hard part will be locating a Deepstrider tumor from far-off Desolace. Very rarely the giants there become ill and a tumor forms instead of mentioning the Whelps. The Progress text, As for the Deepstrider tumor, they are terribly difficult to find. But the chemical reaction I can draw from it is second to none was simply removed.

**Comment by Slimmer2** [comment]
@Gnomorus Willst du echt einen der DEVs vorschreiben wie er es posten soll?

**Comment by Rushor** [comment]
muss halt alles einheitlich sein ^^

**Comment by Gnomorus** [comment]
@Slimmer2 Ich will nur, dass sich jeder an die Regeln hält. Gerade die Leute, die diese Regeln aufgestellt haben.

**Comment by Wosser** [comment]
Kein Bugreport wird abgelehnt weil den Devs die Foramtierung nicht gefällt. Alles was die Devs wollen ist eine Quelle und Links aus unserer Datenbank, NICHTS anderes.

**Comment by Gnomorus** [comment]
Ah okay. Dann spar ich mir demnächst die Beschreibung, was falsch läuft und wie es eigentlich richtig sein müsste, poste einfach ein paar Zahlen und ein paar Links und hoffe auf ein Wunder.

**Comment by Sabbaer** [comment]
er wird es selber fixen und braucht deshalb sich nicht an die vorlage halten, die für uns alle gilt.
er bräuchte auch garnichts hier posten und das einfach fixen, er postet das nur der vollständigkeit halber, damit das nicht doppelt reportet wird. 
Also ihr müsst das einem developer schon lassen, wie er sich das selber postet. Warum wir der vorlage folgen müssen ist doch klar, sonst weis der dev nicht, was überhaupt das problem ist.
er muss sich ja nicht selber erklären was nicht funktioniert Oo

**Comment by dagochen** [comment]
ich glaube nightblizard wollte nur den fame für den 1000. bugreport für sich beanspruchen :P

**Comment by nightblizard** [comment]
Uff, hier ist ja tierisch was los! Auch wenn das der falsche Ort für solche Diskussionen ist, so kläre ich das dennoch kurz auf:
Der Report beinhaltet alles was ich brauche, um einen Fehler zu beheben. Ich weiß nach dem Lesen was nicht richtig läuft, wie es richtig laufen sollte und habe eine Quelle zum Nachschlagen. Im Grunde ist das nichts anderes als die Informationen im Formular, welches wir euch zur Verfügung stellen, nur in Kurzform. Das Formular ist eine Hilfestellung von uns an euch, damit ihr wisst was wir benötigen, um einen Fehler zu beheben. Ihr könnt diese Informationen prinzipiell posten wie ihr wollt, aber sollten Informationen fehlen oder wir werden nicht schlau aus eurem Text, dann wird der Bugreport einfach geschlossen.

**Comment by dagochen** [comment]
Ich denke das wird den meisten eh klar sein @nightblizard  :) war 99% Trollerei und 1% Kritik, weil der Report halt komisch aussah :P

**Comment by TheTrueAnimal** [comment]
https://github.com/classicdb/database/issues/632
Das Item muss einfach umbenannt werden.

UPDATE `locales_quest` SET `Details_loc3` = 'Mir schwebt genau das richtige Serum vor. Es wird die Wahrheit genau so behandeln, wie die Wahrheit behandelt werden sollte.$B$BFür dieses Gebräu brauche ich mehrere Schattenpantherherzen aus dem Sumpf. Außerdem brauche ich den verzauberten Fungus des Morastlords, der dort haust. Ich bin sicher, jemand, der so tüchtig ist wie Ihr, $N, kann ihn überreden, sich von einigen zu trennen.$B$BDer schwierige Teil wird sein, einen Tiefenschreitertumor im weit entfernten Desolace zu finden. Diese Giganten werden nur selten krank und bilden Tumore.$B$BUnd jetzt fort mit Euch!', `Objectives_loc3` = 'Apotheker Faustin im Bettlerschlupfwinkel braucht 5 Schattenpantherherzen, Morastlordfungus und einen Tiefenschreitertumor.' WHERE `entry` = 1383;
UPDATE `locales_item` SET `name_loc3` = 'Tiefenschreitertumor' WHERE `entry` = 6082;

**Comment by nightblizard** [comment]
Das ist so nicht richtig. Name und Questtext sind korrekt, nur dropt das Item einfach beim falschen NPC.

**Comment by TheTrueAnimal** [comment]
Ah, mist, hatte mich verlesen -.-

**Comment by StardustIrving** [comment]
Hi! Damit sollte das Thema dann erledigt sein. Muss vielleicht noch an Eure Datenbankstruktur angepasst werden.
```SQL
DELETE FROM `creature_loot_template` WHERE entry='741' AND item='6082';
INSERT INTO `creature_loot_template` VALUES (4686,6082,-100,0,1,1,0), (4687,6082,-100,0,1,1,0);
```
