### ISSUE TITLE
Magier: Hervorrufung

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1001]
y0 b!tch3s, hervorrufung http://datenbank.welli-it.de/?spell=12051 macht manchmal 3 ticks http://datenbank.welli-it.de/?spell=12051, manchmal vier. Es sollte eig. 4 ticks http://datenbank.welli-it.de/?spell=12051 machen.

peace out  \ | /

**Comment by Sabbaer** [comment]
aber sonst ist alles klar bei dir oder?

**Comment by Gnomorus** [comment]
O.g. Fehler tritt auch bei Gelassenheit auf. http://datenbank.welli-it.de/?spell=740 http://datenbank.welli-it.de/?spell=8918 http://datenbank.welli-it.de/?spell=9862 http://datenbank.welli-it.de/?spell=9863

**Comment by ircfelix** [comment]
#isso

**Comment by nightblizard** [comment]
Bitte Schritte zur Reproduzierung angeben, falls vorhanden, ansonsten wird das hier gaaaaaaaanz nach hinten angestellt, da das ein schlechter Versuch ist mich nachzumachen.

**Comment by dagochen** [comment]
Zum Reproduzieren: Magier sein, Mana leer machen und dann Hervorrufung zaubern.

**Comment by ircfelix** [comment]
Im Endeffekt das was dagochen gesagt hat.

**Comment by Larnak1** [comment]
Da ist sicher was dran. Hervorrufung erhöht ja einfach nur die "normale" Manareg, die es normal alle 2 Sekunden geben sollte. Je nachdem, wann also nun Hervorrufung gezündet wird (direkt nach dem letzten Tick, direkt vor dem nächsten o.ä.) ergibt sich dadurch vermutlich, dass entweder 3 oder 4 dieser Manareg-Zicks innerhalb der Hervorrufungs-Zeit liegen.
Normalerweise müsste das egal sein, da innerhalb von 8 Sekunden normalerweise immer 4 Manareg-Ticks sein müssten. Aber wahrscheinlich gibts da irgendwelche Verzögerungen o.ä., die unter bestimmten Umständen verhindern, dass ein Tick aus der Castzeit herausfällt.

Wenn das ein allgemeines Problem ist, könnte auch Anregen (http://datenbank.welli-it.de/?spell=29166) betroffen sein.

**Comment by wahaxlekuke** [comment]
Quelle fehlt, die Fähigkeit macht exakt das, was im Tooltip steht.

**Comment by ircfelix** [comment]
"Normalerweise müsste das egal sein, da innerhalb von 8 Sekunden normalerweise immer 4 Manareg-Ticks sein müssten."

**Comment by ircfelix** [comment]
Es is halt einfach so, dass innerhalb der 8 Sekunden Kanalisierungszeit vier Ticks (2x4 = 8) kommen müssten (sofern die Info stimmt, dass alle 2 sek. ein manareg tick kommt).

Angenommen man fällt mit Beginn von Hervorrufung genau 1ms hinter den letzten manareg tick, dann siehts so aus:
1,999s
3,999s
5,999s
7,999s

angenommen man bekommt genau bei castbeginn den neuen manareg tick siehts so aus:
2s
4s
6s
8s

angenommen man ist 1 ms vor dem nächsten manareg tick siehts so aus:
0,001s
2,001s
4,001s
6,001s

In allen drei Fällen sollte man 4 Ticks bekommen, manchmal sinds einfach nur 3, auch wenn noch 1/3 castzeit oder so übrig ist.

**Comment by ircfelix** [comment]
Mir ist noch schon länger noch etwas aufgefallen: wenn man durch wasser und Brot reggt, dann kommen die "Schübe" in denen sich die Mana- und Hpbalken auffüllen unregelmäßig. Wenn ich daheim bin versuche ich mal dasmitzustoppen. Vielleicht hängt das ja auch mit den Ticks von Gelassenheit und Hervorrufung (oder allen kanalisierten Zaubern?) zusammen.


Ist von Devseite zur Funktionsweise von Manareg Ticks etwas sachdienliches bekannt und zu erfahren bzw. habt ihr das schonmal unter die Lupe genommen? 

Beste Grüße!

**Comment by Gnomorus** [comment]
Mit /combatlog kann man meines Wissens eine millisekundengenaues Log in eine Textdatei extrahieren. Ob man das vorsortieren kann oder nicht weiß ich leider nicht - die Regeneration steht vllt auch drin. Und eine Angabe mit einer höheren Genauigkeit als Sekunden ist wohl eine Voraussetzung dafür, dass man dem Fehler auf den Grund gehen will.
