### ISSUE TITLE
[Loot] Zwielichtmeister(Game) - Meister des Schattenhammers(DB)

### ISSUE THREAD

**Issue by Amasov** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1002]
Welches Verhalten wird beobachtet?
-- > NPC 11883 droppt kein Rare-Loot.

Wie sollte es sich verhalten?
--> NPC 11883 sollte Rare-Loot droppen.

Schritte zur Reproduzierung
--> NPC 11883 mehrfach .killen

Zusätzliche Informationen (Screenshots, Videos, etc.)

![zwielichtmeister](https://cloud.githubusercontent.com/assets/11898994/9566332/c61b8458-4f01-11e5-9092-9520046068a4.jpg)

Als Vergleich hier der Zwielichträcher / Rächer des Schattenhammers (NPC 11880):

![zwielichtraecher](https://cloud.githubusercontent.com/assets/11898994/9566339/f1761956-4f01-11e5-9df3-2172f894e60d.jpg)

Links aus unserer Datenbank (hier gehts zur Datenbank)

- Zwielichtmeister / Meister des Schattenhammers: http://datenbank.welli-it.de/?npc=11883
- Zwielichträcher / Rächer des Schattenhammers: http://datenbank.welli-it.de/?npc=11880

**Comment by nightblizard** [comment]
Nicht reproduzierbar, du wirst einfach Pech gehabt haben. Hier ein Auszug aus dem Loot bei 1.000.000 mal simulierten Looten:
![Bild](http://puu.sh/jTEdL/66d7516e9c.jpg)

Die Näherungswerte sind ziemlich nah am erwarteten Wert und bei einer größeren Anzahl an Simulationen werden sie gegen die in der Datenbank angegebenen Werte laufen.

**Comment by Amasov** [comment]
Ok, war auch letztendlich nur die Frage ob da was schiefgelaufen ist ;)

Danke für die Info :)
