### ISSUE TITLE
Artorius der Verhängnisvolle - Movement Speed

### ISSUE THREAD

**Issue by Flako123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1003]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version: 1.2.0

Wie sollte es sein?
Artorius sollte langsamer als der Jäger mit Aspekt sein.

Wie ist es?
Artorius ist genauso schnell wie der Jäger, Berg hoch sogar schneller.

Quelle:
https://www.youtube.com/watch?v=qaq--USdpRQ
https://www.youtube.com/watch?v=Enf397YLiSY
http://wow.gamona.de/forum/threads/noch-ein-epic-guide.70542/
http://wow-pro.com/class_guides/hunter_epic_quest_hunt_rhok039delar

Anmerkung:
Das Movementspeed von Atorius müsste um ca. 10% verlangsamt werden. Ich habe auch einige Guides gelesen in denen steht, dass man darauf achten müsste nicht außer range zu laufen, was hier nicht möglich ist (ohne e. Insbesondere in dem guide von wow-pro ists gut beschrieben: "If you see him go out of range for your weapons let him catch up!" Hier auf dem Server läuft man nicht außer range, es sei denn man nutzt Erschütternder schuss (von dem in dem guide nicht die rede ist).

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Haudraufinix** [comment]
5) if you are running up hill at all [even a very very slight grade, such as the one that is on the road south to the crossroads over winterspring] he is faster than you and 'flys' to catch up. you must be ready to cunc shot him at this point. otherwise, you will just die.
http://www.wowhead.com/npc=14535/artorius-the-doombringer#comments

**Comment by Flako123** [comment]
Ich hab den Mob geschafft, nur musste ich selbst auf der Straße Erschütternder Schuss benutzen um minimal Abstand zu gewinnen (mit geskilltem Aspekt des Geparden). Normal läuft man ihm auf der Straße ohne geskillten Aspekten davon und muss aufpassen nicht zu weit außer Range zu laufen.

**Comment by Haudraufinix** [comment]
Der Movement Speed von Artorius ist Korrekt. Das einzige was an dem Herren möglicherweise nicht funktioniert (Kann ich nicht sagen obs noch so ist, mein eigener Kill ist über ein Jahr zurück) ist, dass Schlangenbiss auf unserem Server möglicherweise den Wutanfall nicht entfernt, der ihn schneller werden lässt.

Das Grund- Lauftempo hingegen ist I.O.
