### ISSUE TITLE
Wieso laufen die Spielercharaktere auf einmal alle zu schnell???

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1004]
Die haben ja fast als Normaltempo das Tempo drauf, das man normalerweise als Geist haben sollte, was bei euch zumindest vor ein paar Monaten nicht der Fall war. Also dass man als Geist ein erhöhtes Lauftempo hat. Euren ahnungslosen Spielern scheint nichts davon aufzufallen als hätten sie niemals in ihrem Leben WoW und erst recht nicht WoW-Klassik auf einem Originalserver gespielt. Da ihr offensichtlich keine Fehler behebt, sondern stattdessen neue einbaut, nehme ich an, dass das immer noch nicht behoben wurde und weiterhin als richtig betrachtet wird.

Mich stellen sich da natürlich einige Fragen. Ihr zieht hier ein Projekt hoch, das theoretisch sogar strafrechtliche Konsequenzen für euch bedeuten kann. Geht also ein gewisses Risiko ein. Ihr seid - zumindest behauptet ihr das - professionelle Programmierer, das heißt ihr könnt den Quellcode des Privatservers, den ihr nutzt ändern, aber ihr seid weder in der Lage einfache Fehler in der Datenbank zu lösen noch scheint ihr sonderlich viel von WoW zu halten, offenbar hat keiner aus eurem Team jemals aktiv gespielt und ihr habt auch nicht so die Ahnung wie das Spiel damals eigentlich aufgebaut war. Ihr wollt stattdessen für jede bekannte Tatsache nen Beleg haben.

Also ich finde das irgendwie seltsam und nicht konsistent. Ich persönlich kann ein wenig programmieren. Rein hobbymäßig allerdings. Ich kann beispielsweise kleine AddOns mit Hilfe von Lua und der WoW-API programmieren oder bestehende AddOns an meine Bedürfnisse anpassen, aber ich kann natürlich nicht einen Servercode direkt mit C++ korrigieren oder erweitern. Allerdings weiß ich, dass die euch als so ungeheure Arbeitsbelastung betrachteten Datenbankänderungen keine große Hürde darstellen. Vor einigen Monaten habe ich in einer halben Stunde ein Programm geschrieben, das Dateien mit SQL-Anweisungen erzeugt, die genau die Änderungen vornehmen, die ich in der Mangos-Datenbank haben wollte. Und zwar an tausenden Datensätzen - vollautomatisch. Arbeitsaufwand war wie gesagt ne halbe Stunde. Ihr betreibt den Server hier seit Jahren und habt bis jetzt noch nicht einen einzigen Datenbankfehler behoben.

Zum Beispiel die Elite in den Pestländern, die nicht Elite sein dürften. Um diesen Fehler zu beheben muss man eine Zahl in der Datenbank ändern. Nur eine mickrige, kleine Zahl für ein paar Dutzend Einträge. Als ich angefangen hatte euch sogar Schritt für Schritt zu erklären wie man einige Fehler löst, beispielsweise, dass Mor'ladim seine gewohnte Patrouille läuft anstatt stur an einer sehr ungünstigen Stelle starr zu stehen oder wie der Altar der Tiefen in einer Instanz die Gruppe zurück nach Darnassus teleportiert. habt ihr mich aus dem Forum gebannt. 

Für mich bedeutet das entweder ihr habt überhaupt keine Ahnung von dem, was ihr da macht und müsst auf die Arbeit von anderen warten, weil selbst behebt ihr ja keine Fehler oder ihr trollt eure Spieler absichtlich.

Ich hab den Eindruck, dass ihr gar keine Ahnung habt, aber das so hinstellen wollt, als hättet ihr Ahnung. Es gibt allerdings einige sehr gute Dinge auf eurem Server. Zumindest im Vergleich zu anderen Servern. Beispielsweise halte ich euch für besser als Nostalrius. Einmal weil ihr einen deutschen Server habt und zum anderen weil eure Bewegungen zwischen NPCs und Spielern besser sind im Kampf. Wenn ihr das wirklich so programmiert habt, dann habt ihr das gut gemacht. Es ist natürlich auch nicht so wie es auf dem Original war, aber besser als auf den anderen Servern. Und das bedeutet eine Menge.

Nur finde ich, man könnte auch, wenn ihr wirklich dazu in der Lage seid original Quellcode zu verbessern, dann müsste das ja ein Klacks für euch sein, die Datenbank mal ein bisschen auf Vordermann bringen. Eigentlich dürfte es beispielsweise nicht eine einzige Quest geben, die nicht mehr funktioniert auf eurem Server. Oder ich hab euch ja auch damals gesagt, wie man es schafft, dass die NPCs keine weißen Würfelchen mehr als Wurfwaffe werfen, sondern die Originalwaffe, habt ihr bestimmt auch noch nicht korrigiert. Weil den Fehler müsste man in der Datenbank beheben und die tastet ihr offensichtlich nicht an.

Ich kann es wie gesagt nicht nachvollziehen, um ehrlich zu sein. Aber wie gesagt die Spielercharaktere sind plötzlich viel zu schnell vom Bewegungstempo her, leitet das mal dem Typen weiter, der das hier für euch macht, weil ihr selbst scheint ja die Ahnungslosigkeit in Person zu sein. Und von WoW selbst scheint euer ein Programmierer, den ihr vielleicht habt, auch keine Ahnung zu haben, genau wie ihr. Und der eine Programmierer, den ihr vielleicht habt, ist auch der Einzige, der vielleicht Korrekturen vornehmen kann und der konzentriert sich offensichtlich auf Gruppeninhalte, sonst hättet ihr es ja mal geschafft in den paar Jahren wenigstens ein paar Datenbankfehler zu korrigieren. Dafür muss man kein Programmierer sein. Allerdings muss man sich ein paar Stunden in die Thematik einarbeiten und ein paar kostenlose Programme wie HeidiSQL herunterladen. Scheint euch allerdings zu überfordern.

**Comment by wahaxlekuke** [comment]
Hallo Ernie, 

weil ich deine Beiträge teilweise sehr unterhaltsam finde, bekommst du jetzt einmal eine (halbwegs) ernstgemeinte Antwort von mir.

> Euren ahnungslosen Spielern scheint nichts davon aufzufallen als hätten sie niemals in ihrem Leben WoW und erst recht nicht WoW-Klassik auf einem Originalserver gespielt.

Als ich darmals Classic gespielt habe, hab es es _leider_ versäumt zu notieren, ob man als Geist mit 100% oder 125% Geschwindigkeit rumläuft... zum Glück gibt es tatsächlich Leute, die das getan haben:
http://wowwiki.wikia.com/wiki/Death?oldid=192198
> Run speed is increased while you are a spirit and you are able to walk on water. 

Das ist sogar von der offiziellen Anfänger-Guide übernommen, aber was weiß Blizzard schon - deine Erinnerung ist bestimmt _viel_ zuverlässiger.

> ihr seid weder in der Lage einfache Fehler in der Datenbank zu lösen noch scheint ihr sonderlich viel von WoW zu halten, offenbar hat keiner aus eurem Team jemals aktiv gespielt 

Nur weil die von dir gemeldeten DB-Fehler nicht behoben werden, sind wir offensichtlich nicht in der Lage? Wenn dein iPhone nicht geht und Appel dir nicht sofort helfen kann, haben die wohl auch keine Ahnung, wie man das repariert, oder wie?
Bist du schon mal auf die (abwegige) Idee gekommen, dass deine Tickets einfach genau wegen Sätzen wie diesen nicht bearbeitet werden? 

> ihr habt überhaupt keine Ahnung von dem, was ihr da macht 
> Ich hab den Eindruck, dass ihr gar keine Ahnung habt, aber das so hinstellen wollt, als hättet ihr Ahnung. 

Auch wenn dein Ticket einfach nur furchtbar respektlos gegenüber dem Team ist und nicht ansatzweise der Vorlage entspricht möchte ich einer Sache klären:

> Nur eine mickrige, kleine Zahl für ein paar Dutzend Einträge.

Bei den Untoten in den westlichen Pestländern sind das z.B. hp, mana, min-schaden, max-schaden, attackpower, elite-flag, was angepasst werden muss. Und das bei mindestens drei verschiedenen Gegner-Typen... natürlich sind das alles für sich genommen Kleinigkeiten, aber es gibt eben hunderttausende dieser Kleinigkeiten und dazu noch die Recherchearbeit. Das dauert dann einfach trotzdem ewig. (Abgesehen davon, nehme ich jede Woche immer wieder kleine DB-Fixes vor, die einfach so unbedeutend sind, dass die normalerweise nichtmal in den Patchnotes stehen.)
