### ISSUE TITLE
Goldzahn gehört in die Minen

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1005]
Jeder, der das Spiel schon mal gespielt hat, zumindest wenn er von Anfang an dabei war, weiß, dass Goldzahn immer in der Mine gewesen ist. Dort hat er noch zwei Level 7er in der Nähe. Das ist ne sehr schwere Stelle, wo man häufig wenigstens einmal stirbt, wenn man die Chose solo macht.

Ihr habt ihn hingegen dort platziert, wo er seit Cataclysm steht. Nämlich einsam und allein außerhalb der Mine in der Nähe des einen Hofes dort. Ihr behauptet doch ihr seid ein Klassikserver oder nicht? Also was soll das?

**Comment by nightblizard** [comment]
lol

**Comment by dagochen** [comment]
Das ist nen Datenbankfix. Ich denk du bist so gut Ernie? Dann mal los!

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/179

**Comment by nightblizard** [comment]
Duplikat
