### ISSUE TITLE
Zauberkoeffizient Arkane Geschosse 

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1006]
**Welches Verhalten wird beobachtet?**
Der Zauberkoeffizient  bei den Arkanen Geschossen beträgt momentan 0,2857 pro tick.
0,2857 x 5 ticks = 1,42 (142%). 

**Wie sollte es sich verhalten?**
Der Zauberkoeffizient sollte vermutlich für Patchstand 1.12.1 **120%** betragen.
Wenn man ein bisschen googelt bekommt man für Arkane Geschosse unterschiedliche Angaben wie hoch der Zauberkoeffizent den nun sein soll - nämlich 100% , 120% und 142%. Diese Angaben  widerspiegeln m.E. die unterschiedlichen Patchstände in WoW. Die Skallierung von 100% sowie 142% sind einfach erklärt.

++Grundregel in Classic:++
Zauberzeit / 3,5 * Zauberschaden. Classic = Zauberzeitcap bei 3,5 Sek.
Zauberkoeffizient bei den Arkanen Geschossen 100%, obwohl die Zauberzeit  5 Sek.beträgt. 3,5/3,5 = 1,00 (100%)

++Grundregel in TBC:++
In TBC wurde das Cap bei der Zauberzeit entfernt. Neuer Zauberkoeffizent für
Arkane Geschosse: 5/3,5= 1,42 (142%)

http://wow.gamona.de/forum/threads/20-zauberdamage-was-bedeutet-das-beim-hm.88523/#post-1256019

++Ausnahme:++
Mit Patch 1.11 wurde der Mage überarbeitet.Im Rahmen dieser Überarbeitung gab es anscheinend auch neue Koeffizienten. Für Arkanen Geschosse nun 120%.

Hinweise für 120% Zauberkoeffizient:
 1, DMG-Test (Glaub auf den PTR zu 1.11)
      http://www.knightsofotherrealms.com/smf/index.php?action=printpage;topic=683.0
 2, http://forums.elitistjerks.com/topic/6635-frost-mage-spreadsheet/?p=146468
 3, http://forums.elitistjerks.com/topic/8580-kalgan-on-mages/?p=213566

Grüße

**Comment by Gromnir** [comment]
Ahoi,

wenn du dich auf den Forumpost von Nightblizzard beziehst mit den neuen Koeffizienten sind das trotzdem alte Werte. http://community.mmobase.de/updates-changelog/3892-kommende-aenderung-zauberkoeffizienten.html

Hast du das vielleicht mal Ingame getestet?

Satai, der damals einen großteil der Koeffizienten korrigiert hat, hat in seiner letzten Doku 0,24 pro Tick dokumentiert, weshalb ich davon ausgehe, dass dieser Wert auch auf dem Server implementiert ist. Hier der Ausschnitt:
(7268,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 1'),
(7269,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 2'),
(7270,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 3'),
(8419,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 4'),
(8418,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 5'),
(10273,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 6'),
(10274,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 7'),
(25346,0.24,0,0,0,'Mage - Arcane Missiles Triggered Spell Rank 8'),

Also er hat auch die 120% für die Korrektur genommen. Ist halt von 2013. Weiß nicht ob das hier nochmal geändert wurde. Würde mich aber wundern.

**Comment by 0815Priester** [comment]
Nope, habe es nicht ingame getestet,hätte ich wohl tun sollen.
Habe die unter tabelle genommen "neue koeffizienten", dachte das ist die aktuelle. Ich close mal und suche ein mage der das für mich testet.

Danke für den Hinsweis!
