### ISSUE TITLE
Ausdauerbuff Bug

### ISSUE THREAD

**Issue by ichmeldeeinenfehler** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1007]
Hallo liebe Helfer,

ich habe eine Priesterin geskillt auf Disziplin.
Der Ausdauer Buff "Machtwort-Seelenstärke" bufft nach Skillung anstatt 30% mehr (10 Ausauer) weiterhin den normalen Wert ( 8 Ausdauer ).

Ich hoffe ihr könnt den Fehler beheben.

Vielen Dank schonmal :)

Liebe Grüße

**Comment by wahaxlekuke** [comment]
Im Text vom Buff steht immer nur der ungeskillt Wert bei allen Zaubern. Nur bei der Fähigkeit selbst und im Charakter-Fenster kannst du sehen, dass der Effekt tatsächlich um 30% erhöht ist.
