### ISSUE TITLE
Taschendiebstahl ist verbugt

### ISSUE THREAD

**Issue by Xeods** [ClassicWoW/Nefarian_1.12.1_Bugtracker#101]
Hallo ich wolte hier mal einen bug melden der die fähigkeit taschendiebstahl des schurken betrift mann steht 5 meter hintern mob seitlich oder auch von vorne nutzt es aber nichts pasier mann kommt in den kampf es geht auch nichts im lock ab und zu kommt mal wiederstehen das ist auch ok 

aber in den meisten fällen ist es so das mann aus der verstohlenheit geholt wird ohne das was pasiert ist 

mfg

Xedos

**Comment by wahaxlekuke** [comment]
Kann ich nicht reproduzieren. Bei welchem NPC tritt das auf?

**Comment by JoFlo03** [comment]
um es nochmal aufzugreifen: 
Normalerweise sollte der Schurke, wenn man Taschendiebstahl von hinten nutzt, nicht gesehen werden. Außer wenn der Diebstahl wiederstandne wird etc. 
Jedoch steht nichts im Kampflog von Wiederstehen oder ähnlichem. Auch der Mob steht nach wie vor mit dem Rücken zum Schurken. Allerdings wird man aus der Verstohlenheit geholt wenn man zu nahe kommt. Oft kann man nichtmalmehr Taschendiebstahl nutzen sondern steht enttarnt vorm Mob.

Es sollte so sein, das der Schurke Diebstahl nutzt und erfolg hat oder eben Wiederstanden wird. 

Nicht bei einer speziellen "Mobgruppe" vorgekommen. Kommt durch die Bank bei allen vor, sporadisch funktionert es auch wie es soll.

Testen kann man es ganz einfach indem man den Taschendiebstahl bei ein paar mobs probiert.

Grüße Meandros/JoFlo
