### ISSUE TITLE
Arkane Konzentration / Freizauberzustand + Eisbarriere

### ISSUE THREAD

**Issue by Roostar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1011]
**Welches Verhalten wird beobachtet?**
Der Freizauberzustand wird verbraucht wenn Eisbarriere gewirkt wird. Mana wird richtiger Weise trotzdem verbraucht, da Eisbarriere kein Schaden verursachender Zauber ist.

**Schritte zur Reproduzierung**
Magier mit Arkaner Konzentration und Eisbarriere als Talente. -> Schaden verursachende Zauber wirken, warten auf Freizauberzustand, Eisbarriere wirken.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
[gif dazu] (http://gfycat.com/GeneralUnfitKouprey)

**Links aus unserer Datenbank**

*Ice Barriere Rank 4* http://datenbank.welli-it.de/?spell=13033
*Clearcasting* http://datenbank.welli-it.de/?spell=12536 , http://datenbank.welli-it.de/?spell=16246
gibt zwei in der Datenbank, weiß nicht welcher der richtige ist.

**Comment by Sabbaer** [comment]
bitte an die vorlage halten mit quellen

**Comment by Roostar** [comment]
danke für den Hinweis, ist mein erster Beitrag hier, und kenne mich mit Guthub nicht aus.
Hab den Post entsprechend angepasst und hoffe so ist es richtig.

**Comment by nightblizard** [comment]
Ist mit dem nächsten Update behoben.
