### ISSUE TITLE
Jäger schaden

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1012]
Der Jäger Schaden ist mit http://datenbank.welli-it.de/?item=18713 vom Max-Schaden exakt gleich wie http://datenbank.welli-it.de/?item=19107 und der Minimal-Schaden ist niedriger, obwohl der Bogen mehr Max/Minimal-Schaden hat. http://i.imgur.com/10NO7hn.png 
.

Ist also die "Geschwindigkeit" verantwortlich für den Schaden? (2.90 [Bogen]) (3.30[Armbrust]).

**Comment by dagochen** [comment]
Ja.

**Comment by nightblizard** [comment]
Magst du genauer ausführen warum das kein Bug ist? Denn im ersten Moment ist das für mich auch nicht ersichtlich, warum es sich hierbei um korrektes Verhalten handeln soll.

**Comment by Haudraufinix** [comment]
Die Munition die er verwendet verursacht 17.5 DPS
Beim Blutsucher fügt diese Munition also 57.75 Schaden hinzu
Bei Rokh'delar hingegen nur 50.75

Diese 1110 Angriffskraft die der gute Yesac besitzt fügen bei Rokh 229.9 Schaden pro Schuss hinzu
Beim Blutsucher mit 1111 Angriffskraft hingegen sinds 261.9 Schaden pro Schuss

Ergibt: 57.75 + 261.9 + 85 = 404.6 Minschaden für Blutsucher
50.75 + 229.9 + 89 = 369.7 Minschaden für Rokh'delar

Hauen wir nun die +7 Schaden vom Scope drauf sind wir relativ genau an deinen Werten - irgendwo hab ich wohl was kleines Vergessen.

Herzlichen Glückwunsch, du hast rausgefunden wieso langsame Waffen GEIL sind :D

**Comment by Sabbaer** [comment]
sowas bitte ins mmobase forum, damit auch andere hunter in den genuss kommen, dinge über ihre klasse zu erfahren. thx

**Comment by nightblizard** [comment]
Danke, wieder was gelernt!

**Comment by dagochen** [comment]
Danke @Haudraufnix ;)
