### ISSUE TITLE
Quest: Meister der Arena

### ISSUE THREAD

**Issue by Dreischt** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1013]
Ich habe den Questgegenstand nun 12x.
Nun sollte man die Quest durch klicken des Gegenstandes starten.

Doch bei mir kommt:
Ihr erfüllt die Anforderung für diese Quest nicht.

![bug1](https://cloud.githubusercontent.com/assets/14096485/9638480/46798ec2-51a7-11e5-81d1-ad590a9c5e22.JPG)
![12x](https://cloud.githubusercontent.com/assets/14096485/9638481/48ba5108-51a7-11e5-9081-a21ec3734ee8.JPG)

http://wowdata.buffed.de/item/Quest/Meister-der-Arena-18706
soll die Quest starten.
Folgequest:
http://www.wowhead.com/item=19024/arena-grand-master

Bitte um schnelle Lösung als Hexer haste eh schon wenig Platz im Inventar ;)

**Comment by Sabbaer** [comment]
bei silbaer hat das aber funktioniert? er hat das item!

**Comment by Dreischt** [comment]
Vorhin mit nem GM geschrieben der es auch getestet hat:
Selber "Fehler" wie bei mir.
