### ISSUE TITLE
Schurke: Blenden erhöht Waffenfertigkeit

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1014]
Hab im World Channel gelesen das Blenden die Waffenfertigkeit der angelegten Fernkampfwaffe erhöht.
Habe das auch gleich ausprobiert.

In wie weis Blenden als Fernkampf gewertet wird kann ich nicht sagen.
Blenden hat eine Range bis 10 Meter, Fernkampfangriffe gehen ab 8 Meter los.
Ich bin der Meinung das dies nicht so sein sollte.

http://datenbank.welli-it.de/?spell=2094

**Comment by ircfelix** [comment]
What the fuck am I reading?

**Comment by Haudraufinix** [comment]
Was Slimmer versucht zu sagen: Er kann Schusswaffen skillen wenn er Blenden verwendet.
Hat vielleicht etwas mit https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/660 zu tun

**Comment by g3n3a** [comment]
Liegt wohl daran, das der Server das früher als Fernkampfangriff gezählt hat und dem entsprechend auch Munition verbraucht hat. Der Muni-Teil wurde angeblich behoben. Scheint aber noch mehr nachsich zu ziehen als nur das.

**Comment by dagochen** [comment]
Besteht der Bug noch?

**Comment by nightblizard** [comment]
Nicht reproduzierbar

**Comment by dagochen** [comment]
@nightblizard 
das ist durch den Munition-Fix bereits gelöst, vermute ich mal. Deshalb habe ich auch gefragt ob der noch besteht :P
