### ISSUE TITLE
Fengus' Wildheit - fehlende Angriffskraft Erhöhung bei Distanzangriffskraft

### ISSUE THREAD

**Issue by Flako123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1016]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version: 1.2.0

Wie sollte es sein?
Der Buff Fengus' Wildheit sollte +200 Angriffskraft sowohl auf Nahkampf- als auch auf Distanzangriffskraft geben.

Wie ist es?
Der Buff erhöht nur die Nahkampfangriffskraft

Links:
http://datenbank.welli-it.de/?spell=22817

Anmerkung:
Dasselbe Problem ist bei Juju der Macht.
http://datenbank.welli-it.de/?item=12460

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/945

**Comment by Sabbaer** [comment]
^jo, wie im anderen thread schon beschrieben darf es keine fernkampfangriffskraft machen, sry

**Comment by nightblizard** [comment]
Ist leider noch immer kein Bug
