### ISSUE TITLE
BWL - Bugs nach dem Fix 01.09.15

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1017]
Hier zwei Bugs die uns heute in BWL aufgefallen sind.

Was wurde in BWL beobachtet:

1. Chromaggus Timelapse kann durch Zanza-Flask auf Ihn zurückgeworfen werden.
2. Nefarian ruft beim Magiercall den Priestercall aus

Wie sollte es sein:

1. Der Zauber Timelapse darf nicht reflected werden durch Items und Fähigkeiten
2. Nefarian sollte beim Magiercall den Magiercall ausrufen und nicht ebenfalls den Priestercall.

Zur Reproduzierung einfach mal Timelapse mit dem Zanza-Flask testen und Nefarian bekämpfen bis der Magiercall kommt und dann im Chat der falsche Text ausgeworfen wird.

Zanzas Flask:
http://datenbank.welli-it.de/?spell=24417
Timelapse:
http://www.wowhead.com/spell=23310/time-lapse

**Comment by Dotox** [comment]
Hey,

das mit Nefarian konnte ich nicht reproduzieren. Könntet ihr beim nächsten Raid nochmal darauf achten? :)

**Comment by Karmanaz** [comment]
Mache ich, vllt war es auch nur temporär falsch bis zu einem Restart. Sobald wir wieder bei Nef waren und ich es erneut beobachten konnte melde ich mich.

**Comment by Gnomorus** [comment]
Im gestrigen BWL Raid ist der Fehler mit den Klassenrufen auch aufgetreten.

**Comment by Dotox** [comment]
Die Texte stimmen nicht. Der Magiercall wird gerufen, allerdings spricht Nefarian den falschen Text. Nämlich den, der beim Priestercall gesprochen wird.
