### ISSUE TITLE
Hit durch Waffenkunde bei Fernkampfangriffen

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1018]
Kürzlich drängte sich im Forum die Frage auf, wie Waffenkunde für Jäger funktioniert. Da es laut Nightblizzard definitiv nicht im Sollstadium ist, verfasse ich nun ein Ticket dazu. Das genaue Ist-Stadium ist mir nicht genau bekannt. 

(5% basis + (0,24 * (Differenz von WK und Verteidung -5)) = 8.6% Miss

**Wie sollte es sich verhalten?**
Waffenkunde hatte in Classic keinen Breakpoint was Hit anbelangt. Nach folgender Milchbubenrechnung müsste 1 Waffenkunde für Fernkampfangriffe 0.24 Hit gegen Bosse geben.
8.6 - 5 = 315 - 300 Waffenwertung
3.6 = 15 Waffenwertung
0.24 = 1 Waffenwertung

Tests von Elitistjerks im Sommer 2006 belegen diese Theorie.
Link: http://forums.elitistjerks.com/topic/7214-skill-and-ranged-and-you/
*It seems Defense (and thus skill) is more important for pure hit purposes for ranged than melee. If my above guess with 0.24% per level is correct (currently tested difference per level = 0.32% per level), my missrate should hover around 1.64% with setup B.*

**Comment by dagochen** [comment]
Bei 
```c++
float Unit::MeleeSpellMissChance(Unit* pVictim, WeaponAttackType attType, int32 skillDiff, SpellEntry const* spell)
```

an zweiter Stelle, hinter dem PvP-Fall folgendes einfügen:
```c++
 else if (attType == RANGED_ATTACK)
        hitChance = 95.0f + skillDiff * 0.24f;
```
