### ISSUE TITLE
PVP Titel

### ISSUE THREAD

**Issue by bambutscho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1019]
Sers,

Dotox bat mich, diesen EIntrag zur Übersicht zu Verfassen.

Mein Druide war früher mal PvP Rang 11. Mittlerweile ist er zurück auf Rang 1 gefallen.

Da ich nicht mir Rang 1 Grunzer rumlaufen mochte, fing ich an ruchlose Morde zu farmen. Der PvP XP Balken wuchs pro kill um 5%, bis ich das Maximum erreicht hatte, und wieder ohne Rang war.

Als jedoch am Mittwoch die Ehreabrechnung rum war, erhielt ich wieder Rang 1 zurück, ohne PvP gemacht zu haben.

Daraufhin farmte ich wieder ruchlose Morde, bis ich den Grunzer Titel wieder verloren hatte, den Mittwoch darauf hatte ich ihn wieder zurück.

Es sollte auf jeden Fall so sein, dass wenn man kein PVP betreibt, bwz ruchlose Morde farmt, keinen Rang besitzt.

LG

**Comment by ChichiWarrior** [comment]
Rang 1 Späher
Rang 2 Grunzer

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1223
