### ISSUE TITLE
Schalentierfalle

### ISSUE THREAD

**Issue by TheTrueAnimal** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1021]
When clicking on them one of these two things should happen:
- you get an item (works)
- a creature spawns and attacks you (does not work)

GOB: http://www.wowhead.com/object=176582
NPC: http://www.wowhead.com/npc=11562

Sources: 
https://web.archive.org/web/20060313064114/http://wow.allakhazam.com/db/quest.html?wquest=5386
http://www.wowhead.com/quest=5421#english-comments
https://web.archive.org/web/20060515025218/http://wow.allakhazam.com/db/quest.html?wquest=5421
http://www.wowhead.com/object=176582#english-comments

**Comment by Sabbaer** [comment]
ids aus unserer datenbank bitte einfügen!

http://datenbank.classic-wow.org/
