### ISSUE TITLE
Tier heilen bricht ab

### ISSUE THREAD

**Issue by TheTrueAnimal** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1022]
Möchte man den Zauber "Tier heilen" wirken, und von Beginn an ist das Pet außer Reichweite, so wird der Zauber erst angefangen zu casten und dann abgebrochen, anstatt von vornerein zu melden, dass das Ziel zu weit entfernt ist. Mana wird dennoch abgezogen. Es wird auch nicht beim Icon, wie bei anderen Spells, angezeigt, ob die Range ausreichend ist oder zu hoch.

**Comment by Sabbaer** [comment]
http://datenbank.welli-it.de/?spell=18386

**Comment by Haudraufinix** [comment]
Nicht ganz Sabbaer
Pet-Heal kann auch gezaubert werden, wenn das Pet out of Range ist. Es kann also trotz OOR auslösen. Du bezahlst Mana, aber es heilt nicht. Stells dir etwa so vor, du Zauberst heiliger Schock auf ein Ziel ausser Reichweite und es passiert einfach nichts ausser dass du die Manakosten abgezogen kriegst.

Der Link den du gepostet hast stammt im übrigen von der Hexer-Epic Robe. Der richtige Link ist hier:
http://datenbank.welli-it.de/?spell=13547
http://datenbank.welli-it.de/?spell=13544#see-also-ability

**Istzustand**
Tier Heilen vom Jäger kann gezaubert werden, wenn des Pet ausser Reichweite(20m) ist. Der Zauber bricht jedoch ab ohne zu Heilen.

**Sollzustand**
Tier Heilen sollte nicht gezaubert werden können, wenn sich das Pet ausser reichweite befindet.

**Zusatzinfo**
T1 3Teile Bonus erhöht die Reichweite von Tier Heilen um 10 m (http://datenbank.welli-it.de/?spell=23560)

**Comment by Loplin** [comment]
Soeben am Testserver getestet, funktioniert bei mir

**Comment by Haudraufinix** [comment]
Netter fix - macht aber den 3 Teile t1 Boni (+10 m Reichweite auf Tier Heilen) kaputt. Dieser Funktioniert seid dem Fix nicht mehr
