### ISSUE TITLE
Quest: Siegel des Aufstiegs

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1024]
Wenn man bei der Quest http://datenbank.welli-it.de/?quest=4743 den Drachen mit dem Item Kugel der drachischen Energie http://datenbank.welli-it.de/?item=12300 übernehmen will sobald er geschwächt ist, bekommt man immer die Fehlermeldung "Euer Begleiter befindet sich im Kampf"
Es spielt auch keine Rolle ob man einen Begleiter draußen hat oder freigelassen.

Der Drache sollte sich wenn er geschwächt ist übernehmen lassen, damit man das Ungeschmiedetes Siegel des Aufstiegs http://datenbank.welli-it.de/?item=12323 schmieden kann zu Geschmiedetes Siegel des Aufstiegs http://datenbank.welli-it.de/?item=12324

**Comment by Larirawiel** [comment]
Übrigens, diese Meldung "Euer Begleiter befindet sich im Kampf" kommt auch wenn man einen Gegner per Priester Gedankenkontrolle übernommen hat und versucht eine seiner Spezialfähigkeiten zu benutzen.

Hmmm, vielleicht mache ich da ein Ticket auf. Es sei denn, diese Problematik wird damit behoben. Scheint ja grundsätzlich die gleiche Mechanik dahinter zu stecken.


Grüße
