### ISSUE TITLE
Blasted Lands - Intbuff / Buffstacking

### ISSUE THREAD

**Issue by rooty113** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1025]
Hi, wenn ich den Worldbuff aus den Verwüsteten Landen (+25 Int) mit einem Int-Buff von einem Magier kombiniere, zählt nur der Int-Buff des Magiers (31>25), sollten diese nicht stacken, da das eine ein Worldbuff ist?
Beim Lungensaftcocktail funktioniert dies korrekt. Lungensaft + Hp-Flask + Ausdauerbuff + Zanza Buff + Food stackt fehlerfrei.

Grüße

**Comment by Slimmer2** [comment]
Bitte Links zur Datenbank

**Comment by rooty113** [comment]
http://datenbank.welli-it.de/?spell=10692

**Comment by g3n3a** [comment]
Er sollte in der Tat stacken.
