### ISSUE TITLE
Testserver: T0,5 Questreihe Part 1

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1026]
Dropraten von http://datenbank.welli-it.de/?item=21928 liegt bei gefühlt 100% (laut DB 80%). Laut Kommentaren auf http://web.archive.org/web/20070126103528/http://wow.allakhazam.com/db/item.html?witem=21928
sollte die Droprate bei 1/3 bis 1/2 liegen. Unsere ist deutlich zu hoch. Die %-Werte von allakhazam sind natürlich zu niedrig, weil nicht jeder die Quest hatte....

**Comment by ircfelix** [comment]
Seit wann verlässt DU dich auf alte dropraten?

**Comment by dagochen** [comment]
Seit ICH eine vernünftige und rational verständliche / logische Quelle gefunden habe und NICHT wie gewisse andere Leute FALSCHE SCHLUSSFOLGERUNGEN aufgrund von FALSCHEN ANNAHMEN treffe.

**Comment by dagochen** [comment]
@nightblizard push, weil aktuell?!

**Comment by Larnak1** [comment]
Müsste auch http://datenbank.welli-it.de/?item=22381 betreffen
