### ISSUE TITLE
Warlock - Talent Aftermath

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1029]
**Welches Verhalten wird beobachtet?**
Wenn man Hellfire castet, kann es passieren das man selber "opfer" des talent Aftermath wird. Ich bekomme also selber den -daze effect- ab.

Aftermath
http://datenbank.welli-it.de/?spell=18123
Hellfire
http://datenbank.welli-it.de/?spell=11684

**Wie sollte es sich verhalten?**
Als Warlock sollte es nicht möglich sein mich selbst "benommen" zu machen.

**Comment by Dotox** [comment]
Noch aktuell?

**Comment by 0815Priester** [comment]
Keine Ahnung, ich spiele nicht mehr. Habe aber eh keine Quelle dazu gefunden.
