### ISSUE TITLE
Bijous Habseligkeiten

### ISSUE THREAD

**Issue by Mokkaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#103]
BIjou in der Schwarzfelsspitze gibt die Quest Bijous Habseligkeiten zwei mal her, wobei sie nur einmal gemacht werden kann.
Es lässt sich jedoch die gleiche Quest 2 mal im Questlog haben.

Siehe:

![wowscrnshot_110214_221503](https://cloud.githubusercontent.com/assets/9306799/4879921/700b30e6-6333-11e4-8572-e3e6cd3faeb1.jpg)

**Comment by irontonic** [comment]
Scheint als ob Bijou dem Spieler sowohl die Horden- wie die Allianzversion der Quest anbietet - unabhängig von der Fraktionszugehörigkeit des Spielers. Ihre erste Quest (Habseligkeiten aus Lbrs besorgen) kann man deshalb zweimal abschließen. Die Folgequests sind dann allerdings fraktionsspezifisch (Nachricht nach Kargath bzw. Morgans Wacht bringen) und können so zwar angenommen aber nicht für die jeweils andere Fraktion abgeschlossen werden.
