### ISSUE TITLE
procchance sulfuras, hand von ragnaros

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1031]
Welches Verhalten wird beobachtet?
sulfuras, hand von ragnaros hat eine viel zu geringe procchance.

Wie sollte es sich verhalten?
die procchance sollte sich im bereich von 20-25% bewegen. (wie bei tf auch)

Schritte zur Reproduzierung
http://img5.fotos-hochladen.net/uploads/sulfuras1fnolqsb5ek.jpg
http://img5.fotos-hochladen.net/uploads/sulfuras2wnb0px9rth.jpg
300 hits.
3% procchance
nur white hits gemacht, keine skills etc benutzt

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Talk:Sulfuras,_Hand_of_Ragnaros
hier schreibt einer dass er 30%+ proc chance darauf hat
http://wowwiki.wikia.com/wiki/Thunderfury,_Blessed_Blade_of_the_Windseeker?direction=prev&oldid=351349
https://www.youtube.com/watch?v=ovhRqAxnXqg
nach 30 hits hat er schon 7 feuerball procs

Links aus unserer Datenbank
http://datenbank.welli-it.de/?item=17182

**Comment by obipwn** [comment]
Oh, 25%-Wochen bei Dotox!
Ich hätte gern 25% proc chance auf mein Hand of Justice.
Und 25% hit auf dem Band von Accuria !

Hier schreibt jemand, die chance läge bei 5-10%
http://wow.ingame.de/forum/threads/90013-Welche-waffe-ist-besser-Ashkandi-oder-die-Hand-von-Ragnaros
Das sind natürlich alles keine allzu seriösen Quellen, und leider findet man kaum eine,
die das besser aufklären kann.
Vielleicht hat ja jemand die Waffe auf nem live-server und kann ein Video machen.

Den Vergleich mit TF kann ich nicht nachvollziehen. Verschieden Waffen, unterschiedliche procs.

Grüße

**Comment by Sabbaer** [comment]
ich hab dir doch ein video gepostet vom offi server, zähl doch einfach die hits die er auf golemag macht und zähle die procs, die er hat?
Das video wurde übrigens auch hergenommen um andere veränderungen vorzunehmen.
und komm mal von deinem hate-trip runter

**Comment by obipwn** [comment]
"hate-trip"? wo?
Ich habe mein posting lediglich mit nem kleinen joke eingeleitet, sorry wenn du dich dadurch persönlich angegriffen gefühlt hast.
ja, du hast ein video gepostet. mir war bisher nicht bekannt, dass dieser 3,5 min bossfight (in sekunde 36 fängt der dps-wahnsinn an, bei 4:12 liegt der boss) elementar für veränderungen auf unserem server ist.
was ich meinte ist ein test über z.b. 10-30 min autohits an nem dummy, was mmn evtl etwas repräsentativer wäre. 

zeig mir noch bitte, an welcher stelle ich sage, dass 3-5% für mich ok sind. die itemfarbe ist für mich dabei nicht ausschlaggebend, wie oft etwas procen sollte.
ich denke (mehr können wir anscheinend augenblicklich nicht tun), dass eine procchance von 10% realistisch ist. so ist es auch z.t. auf anderen servern zur zeit (google hats verraten).

**Comment by Sabbaer** [comment]
er war elementar für veränderungen zwecks holy resi usw.
du meinst mit 10-30 min von offi server nen video oder wie?
ich hab ja bei uns anhand der screenshots zu sehen das mit 300 hits getestet.
Die procchance lag hierbei bei 3%.

**Comment by ChichiWarrior** [comment]
Geh bitte auf den Testserver, stell dich an einen Dummy und mach roundabout 10.000 Schläge. Dann hast du Aussagekraft.

BE hab ich übrigens damals auch so getestet, bis ich bei einem lieben ehemaligem GM bei 20 Kniesehnespams 16 Proccs hatte.

**Comment by Sabbaer** [comment]
http://forums.jeuxonline.info/showthread.php?t=645195
20-40% laut diesem forum

**Comment by ChichiWarrior** [comment]
In meinen Augen haben 300 Schläge einfach keine Aussagekraft, wenn du das als Beweis mitbringst.

**Comment by Sabbaer** [comment]
der hammer hat ne schlaggeschwindigkeit von 3.7, das wären ja 10 stunden für 10k schläge....
wir sind mittlerweile schon bei 600 und es bleibt bei ca 3% procchance

**Comment by obipwn** [comment]
"du meinst mit 10-30 min vom offi server nen video oder wie?"
-ja. dann sieht man, wie es sein sollte. die procchance wurde mwn nie geändert

"Die procchance lag hierbei bei 3%."
-glaube ich dir, ich bestreite auch nicht dass sie zu niedrig ist.
aber aus blauem dunst eine procchance zu fordern aufgrund von aussagen a là
"mein kumpel hat nen freund dessen hund meint, dass der hammer krass oft proct"
ist halt, naja :)

"http://forums.jeuxonline.info/showthread.php?t=645195
20%-40% ca procchance
denke muss hier nicht weiter posten"
-ich befürchte doch. 2 postings darunter schrieb jemand "C'est dans les 15%, pas plus. "
 ~"ungefähr 15%, nicht mehr"

**Comment by Sabbaer** [comment]
ich habe einen account + den hammer, aber das spiel weder noch installiert noch einen aktiven account.... ;(

**Comment by Loplin** [comment]
Willst du die 3% mit einem Spiel von +/- 1% Bestätigt haben, musst du etwas über 38.000 Schwünge durchführen.

**Comment by Sabbaer** [comment]
obs nun 3% oder 5% oder 7% atm sind, das ist immernoch zu wenig, wäre nice wenn ein dev sich das mal anguggen könnte, wie hoch die proc chance ist, und diese vll gegebenenfalls anpassen könnte.

**Comment by g3n3a** [comment]
Ne andere Quelle bemisst dem Procc ~10 dps zu (http://www.wowhead.com/item=17182/sulfuras-hand-of-ragnaros#comments). Das wäre bei durchschnittlich 300 Dmg vom Proc ca. 2 ppm oder bei 3.7er Attackspeed ne 1/8 Chance zu proccen.

**Comment by Sabbaer** [comment]
definitiv not legit post, orangenes item, just keep that in mind, und dann sone proc chance, das glaub ich nid, so krank war nicht mal blizzard

**Comment by Sabbaer** [comment]
10 dps, ich glaub dir kein wort, was solln das sein, soll ich lachen?

**Comment by Sabbaer** [comment]
das glaub ich dem post nicht

**Comment by dagochen** [comment]
Der Aufriss wird gemacht weil du in deiner Argumentation behauptest, dass Sulfuras auch 25% Chance haben muss, weil TF es auch hat. Diese Argumentation ist komplett sinnlos, sorry, ist aber so.

Nun zu den Fakten:
Bei uns scheint die Procchance ähnlich wie bei mir auf meinem Testserver zu sein, da ist sie bei ca. 6%. Dies ist offensichtlich falsch, da es weniger als bei allen Quellen ist, die wir bisher hier gefunden und genannt haben. Die Angaben schwanken allerdings stark, zwischen 10% und 30%.

**Comment by g3n3a** [comment]
Was sind in dem Golemagg-Video denn für dich Feuerballproccs? Die Boule de feu oder? Das was da sooft bei ihm procct, ist sein Siegel (autorite). Der Boule de feu procct über 3:40 min des Kampfs genau 4x. Macht bei 3,7er Attackspeed (~59 Schläge, wie aussieht hat der Blackhand+ZG-Trinket an, also kein HoJ) ne rund 7% Proccchance. Kommt ja ziemlich na an dein Ergebnis ran.

**Comment by Loplin** [comment]
Dago, hättest du den post aufmerksam gelesen, wüsstest du das er es nicht behauptet, sondern lediglich anmerkt (erkennbar an der Klammer)
Seine Behauptung:
"die procchance sollte sich im bereich von 20-25% bewegen."
Hat er mit quellen hinterlegt die auch in früheren bugfixes akzeptiert wurden.

**Comment by obipwn** [comment]
Loplin, als aufmerksamer Leser kannst du uns dann sicherlich zeigen, wo in seinen Quellen ein Zusammenhang besteht zwischen beiden Waffen bzw. procs, und falls nicht, warum er TF als Referenz genannt hat. Ich fordere ja auch nicht mehr Gromsblut spawns weil es so viele Friedensblumen gibt.
Ebenso sind alle bisher genannten Quellen schlichtweg schwammig. Kein Test, nur gefühlte/geschätzte Aussagen.

Mal von allem abgesehen... LOL. Genea hat Recht, der Pala im Vid hatte im GANZ KAMPF 4 procs. Vier.
womit dann auch die Frage nach "ich glaube es wird hier nur so ein aufriss gestartet weil ich der sabbaer bin und mal wieder was reporte." geklärt wäre ;)
have a nice day

**Comment by Loplin** [comment]
Hast du meinen beitrag überhaupt gelesen?
Keine ahnung wo ihr das alle hernehmt aber weder sabbaer noch ich haben in irgendeiner weise behauptet, dass ein zusammenhang zwischen den beiden Waffen besteht.
Sabbaers aussagen aus dem ersten beitrag waren:
Hammer proct zu 3%
Hammer sollte zu 30% procen
Tf proct zu 25%

Ich kann hier nicht erkennen, dass er geschrieben hat
Tf proct zu 25% also muss es der hammer gebau so machen

Ub diese aussagen stimmen, gilt es anhand der quellen zu klären

**Comment by obipwn** [comment]
"Hast du meinen beitrag überhaupt gelesen?"
-ja.

"Keine ahnung wo ihr das alle hernehmt aber weder sabbaer noch ich haben in irgendeiner weise behauptet, dass ein zusammenhang zwischen den beiden Waffen besteht."
-du nicht, er schon. warum nennt er den vergleich, und warum ist eine Quelle die wiki zum tf? weil dort irgendeine procchance angeführt ist, zu einer anderen waffe mit einem anderen proc?

"Sabbaers aussagen aus dem ersten beitrag waren:
Hammer proct zu 3%
Hammer sollte zu 30% procen
Tf proct zu 25%"
-nein, das hat er so nicht gesagt.

"Ich kann hier nicht erkennen, dass er geschrieben hat
Tf proct zu 25% also muss es der hammer gebau so machen"
-da, in Zeile 5:
"die procchance sollte sich im bereich von 20-25% bewegen. (wie bei tf auch)"
bitteschön.

"Ub diese aussagen stimmen, gilt es anhand der quellen zu klären"
habe wir doch bereits. lies mal aufmerksam den kommentar von g3n3a durch.

**Comment by Loplin** [comment]
Wie ich sehe interpretieren wir das wort "auch" unterschiedlich
Ich hatte alles zum thema tf nur als zusatzinfo verstanden und nicht als zwingenden zusammenhang der beiden waffen

**Comment by Sabbaer** [comment]
genau so war es von mir auch gemeint, als zusatzinfo...

**Comment by dagochen** [comment]
Abgesehen von den unterschiedlichen Verständnisvarianten die ihr gerade erläutert habt, hat das Wort Thunderfury (AUCH TF, Donnerzorn und/oder andere Variationen davon!) nichts, aber AUCH absolut GARNICHTS hier in diesem Bugreport zu suchen. Es geht um SULFURAS, NICHT um Thunderfury/TF/Donnerzorn....

**Comment by obipwn** [comment]
@dagochen dago, es geht doch hier um den proc von Sulfaras, gesegneter Hammer des Feuersuchers.
Ein Verweis äh Vergleich äh Zusatzinfo+Wikilink auf die Zwillingsbruderwaffe ist nur legitim.

Wenn dann aber geklärt ist, wie man "wie bei x auch" verstehen kann, ausser als Vergleich, möchte ich nocheinmal auf den enthüllenden Beitrag von g3n3a hinweisen.

Gute Nacht :*

**Comment by dagochen** [comment]
Joa dann kann ja hier geclosed werden. Außer wilde Spekulationen ist ja nix bei rum gekommen hier....

**Comment by Sabbaer** [comment]
"Was sind in dem Golemagg-Video denn für dich Feuerballproccs? Die Boule de feu oder? Das was da sooft bei ihm procct, ist sein Siegel (autorite). Der Boule de feu procct über 3:40 min des Kampfs genau 4x. Macht bei 3,7er Attackspeed (~59 Schläge, wie aussieht hat der Blackhand+ZG-Trinket an, also kein HoJ) ne rund 7% Proccchance. Kommt ja ziemlich na an dein Ergebnis ran."

es sind 52 schläge die er macht und nicht ungefähr 59 und er hat 4 proccs.

**Comment by Jura500** [comment]
"es sind 52 schläge die er macht und nicht ungefähr 59 und er hat 4 proccs.
über längeren zeitraum wird so wie bei mir auch die prozentzahl ansteigen."

Warum wird sie das?

**Comment by dagochen** [comment]
Wenn alle Quellen das gleiche aussagen würden, könnte man daraus ja einen Schluss ziehen. Aber der eine sagt 5-10%, der nächste 10-15%, 15-20%, über 20% und noch jemand anders ca. jeder 3. Hit. Und dann kommt dazu ein Video mit 52-59 Schlägen, was einfach nicht genug Schläge sind, um daraus irgendwas abzuleiten.

Egal wie es geändert wird aufgrund dieser Beweislage, die Chance das es danach richtig ist, ist sehr gering.

**Comment by Sabbaer** [comment]
so wie es im moment ist, its es aber auch falsch!

**Comment by Seniorash** [comment]
Rechne mal aus wir wahrscheinlich es ist dass bei 52 Hits 4 proccs hat wenn die tatsächliche Chance bei 30% liegt

**Comment by obipwn** [comment]
So ein Satz steht natürlich erstmal wie in Zement gemeißelt. Alle Gegenargumente entwaffnet.

**Comment by g3n3a** [comment]
Es sind übrigens 56 Autoattacks (Verfehlen und Ausweichen gehören nunmal dazu).

PS: Hab einscheinbar nix besseres zu tun mit meinem Leben als autoattacks bei nem kack langweiligem Video zu zählen...

**Comment by Sabbaer** [comment]
ich hab sie gezählt inkl. ausweichen und verfehlen und es sind 52 und ich hab jetzt 3 mal gezählt

**Comment by dagochen** [comment]
Ausweichen und verfehlen könnt ihr rauslassen aus der Zählung, da nur Treffer zu einem Proc führen können. Bitte zählt daher nochmal genau nach, danke!

**Comment by Loplin** [comment]
Is eh hinfällig
Ein Video in welchem man nur 52 hits sieht hat leider wenig Aussagekraft über den tatsächlich proc-wert
bei 52 hits hat man ein Spiel von +-13,5%

**Comment by pdglala** [comment]
so ich habe mal ein bisschen rumgeforscht:

http://wowwiki.wikia.com/wiki/Procs_per_minute
http://vanilla-wow.wikia.com/wiki/Proc

https://vanilla-twinhead.twinstar.cz/?issue=718#comments
Diese Procchancen stimmt ziemlich genau.

Ihr könnt es selber mal nachrechnen.

Der Hammer proc passiert zu selten. Er sollte 10% betragen ppm = 1,6 gerundet
=(10%/60)*60/3,7

Zurzeit ist es so, das der Hammer nicht mal 1 Proc per minute hat, was auf keinen Fall richtig ist.

**Comment by Sabbaer** [comment]
pdglala i love u srsly melde dich ingame bei mir!

**Comment by dagochen** [comment]
Mit dir zu diskutieren Sabbaer ...bringt einfach NULL! Es geht NICHT um deine Person. Du bist nicht so wichtig, wie du denkst. Es hat einzig und allein mit deiner Argumentation zu tun. Diese ist unschlüssig, ungenau und/oder komplett falsch. Das ist das, was ich bei dir jedes mal kritisiere. Und genau aus diesem Grund werden deine Bugreports lang wie die Mauer von China, kein Dev steigt mehr durch (kann man ihnen wohl kaum verübeln, wenn sie sich das nicht mehr antun) und am Ende kommt entweder nichts bei rum, oder irgendjemand anders macht das, was du hättest tun sollen: Eine vernünftige Quelle posten.

**Comment by Testear** [comment]
Ich weiss btw nicht, warum mehrere Posts die von ähnlichne Proccraten sprechen, auch wenn der Bereich recht groß ist, nicht als Quelle gelten sollten.

Wir haben eine Quelle die von 20% bis 40% (1.3) spricht, eine Quelle die von 15% bis 40% (1.4)  spricht, eine Quelle die sagt es sind nicht mehr als 10% (1.4) und eine Quelle die von ca 12,5% spricht (2.1)

Dazu haben wir hier ein ist von 3% bis 7%. Was jawohl klar falsch ist.

Der Rest ist Dev-Sache und ich verstehe nicht warum das öffentlich zur Diskussion steht.


@Dago
Ich bin selber Sabbaers Meinung und denke auch, du solltest mal lernen, wann es angebracht ist besser nix zu schreiben.
Ich erinnere nur an deinen Unsinnspost wo du behauptest hast durch die doppelte Schwunganzahl würde sich die Proccrate von TF erhöhen - wohlgemerkt ohne jede Grundlage bzw Quelle.
Prozentrechnung trifft Kritisch.
Und das ist nicht das einzige an das ich mich erinner wo ich deinen Beitragt suspekt fand. 
Scheinbar kannst du einfach nicht im Unrecht sein.

**Comment by Jura500** [comment]
@Testear Wo wäre es denn hier für Dago angebracht gewesen besser nichts zu schreiben? An der Stelle, an der er sagt, dass es hier nicht darum geht, wer diesen Report geschrieben hat, sondern wie er geschrieben wurde? Oder hätte er doch lieber den Post nicht geschrieben, in dem er sagt, dass die bisher gebrachten Quellen einfach keine brauchbare Aussage liefern?  Oder doch lieber als Sabbaer mal wieder auf dem Trip war, dass alle gegen ihn argumentieren, weil sie ihn nicht mögen?

BTT: Die Quelle von pdglala scheint recht brauchbar zu sein. 10% wirken recht passend und würden den Hammer endlich mal ein wenig aufwerten.

**Comment by Testear** [comment]
"Der Aufriss wird gemacht weil du in deiner Argumentation behauptest, dass Sulfuras auch 25% Chance haben muss, weil TF es auch hat. Diese Argumentation ist komplett sinnlos, sorry, ist aber so.
Nun zu den Fakten:
Bei uns scheint die Procchance ähnlich wie bei mir auf meinem Testserver zu sein, da ist sie bei ca. 6%. Dies ist offensichtlich falsch, da es weniger als bei allen Quellen ist, die wir bisher hier gefunden und genannt haben. Die Angaben schwanken allerdings stark, zwischen 10% und 30%."

Hier steht nix, was nicht schon vorher erläutert wurde, außer dem üblichem Sabbaerflame..

"Abgesehen von den unterschiedlichen Verständnisvarianten die ihr gerade erläutert habt, hat das Wort Thunderfury (AUCH TF, Donnerzorn und/oder andere Variationen davon!) nichts, aber AUCH absolut GARNICHTS hier in diesem Bugreport zu suchen. Es geht um SULFURAS, NICHT um Thunderfury/TF/Donnerzorn...." 

4 Zeilen darüber, dass es hier um den Sulfurasprocc und nicht den TF Procc geht.

"Joa dann kann ja hier geclosed werden. Außer wilde Spekulationen ist ja nix bei rum gekommen hier...."

Aha. Das ist eine glatte Lüge. Warum sieht man 2 Posts über diesem.

Und das sind nur 3 Posts in diesem Thread. Weiter werde ich da nicht drauf eingehen.
Wenn man sich erstmal die Frage stellt, ob der Post denn wirklich nötig ist und einen Beitrag zum Thema darstellt muss man bei allen 3 Posts (auch bei diesem hier) NEIN sagen.

**Comment by obipwn** [comment]
kommt mir vor als würden hier bild-leser mit faz-lesern diskutieren.

ich hab hier immernoch keine verlässliche quelle gesehen.
ihr postet aussagen aus foren, in denen leute schätzungen aus dem bauch abgeben wurden. vielleicht wurde derjenige gerade im av von nem sulfaras-träger aus den latschen gehauen, dann ist die proc-chance natürlich bei mindestens 80%.
dann ein link von nem anderen privatserver posten, wo im thread noch der dev fragt ob das ungefähr so hinkommen kann... seriously guys? :D 

sabber, es geht hier wirklich nciht um dich. ich kenne dich nicht, kann also kaum über dich urteilen, eben nur anhand der beiträge hier. wenn man dann in sarkasmus verfällt hat das sicherlich mit deinen aus der luft gegriffenen forderungen zu tun, ohne vernünftige quellen. das ganze hier lässt dich halt nicht im hellsten paladinlicht erstrahlen...

habt trotzdem einen schönen tag :*

**Comment by ChichiWarrior** [comment]
Ich hätte auch noch was gefunden für dich Sabbaer.

Schau mal ob du dafür Verweundung hast.

https://www.youtube.com/watch?v=caJj2-0Q2ek

**Comment by g3n3a** [comment]
Zusätzlich wäre ich bei der Liste vom Forum des Privatservers dennoch misstrauisch, da nicht alle Proccs auf eine Proc-per-Minute Basis gearbeitet haben. Ne %-Chance ist nicht dasselbe wie ppm (wie auch in einem der Links beschrieben wird). Waffen die auf %-Chance basieren daher einfach nen ppm zuzuschreiben, ist falsch.

**Comment by pdglala** [comment]
ppm ist mit der % proc chance fast gleich, ist egal wie du es rechnest. Das ist ein Fixwert.
Ich bin mir bewusst, das es eventuell eine kleine Abweichung gibt. Doch nichts desto trotz ist der Wert vom Hammer hier falsch. Eine Erhöhung zu dem Fixwert kommt näher zu dem wie es sein sollte und nicht wie es zurzeit ist.

Discuss ende. Es kommt von euch ja sonst nur unsinnige Beiträge.
Im übrigen habe ich mich sehr viele Stunden durch das Web gewühlt und leider gibt es einfach keine "zuverlässigen" Quellen, die exact die Procchance wiedergeben.
Ihr dürft hier wieder etwas posten, wenn ihr andere Quellen gefunden habt und euch aufhört gegenseitig an die Kehle zu gehen.

**Comment by g3n3a** [comment]
Die Änderung von festen Procc-chancen zu PPM hat damals zu WotLK die bevorzugt benutzen Gifte bei Rogues geändert. So einfach sollte man das also nicht nehmen. War die Sulfuras-Waffenprocc-% denn ein fester Wert oder PPM? Gerade für Warris ist das ein Unterschied.

**Comment by Sabbaer** [comment]
wurd ja wieder schön kaputt gemacht der threat, kann ich den schließen und einen neuen eröffnen @ devs? ich frage die devs hier, mir egal was ihr ganzen anderen noch dadrunter postet, kennt sich ja kein mensch mehr aus mittlerweile, und das ist genau das, was ihr erreichen wolltet, keinen buggfix...

deswegen plz devs sagt, was ich nun machen soll, damit das hier voran geht? es ist immerhin ein orangenes item und ich bin auch nicht der einzige der das hat.

**Comment by Dotox** [comment]
Das passt so schon :)

**Comment by dagochen** [comment]
Nochmal: Ob das Item orange, blau, grün oder lila ist, spielt überhaupt keine Rolle.
Dunkelmond-Karte: Maelstrom (http://datenbank.welli-it.de/?item=19289) hat z.B. auch eine geringere Procc-Chance als Herz von Wyrmthalak (http://datenbank.welli-it.de/?item=22321) auf unserem Server. Und das ist laut den Quellen die man dazu findet richtig. Es ist also nicht legitim zu behaupten, ein Item müsse eine höhere Procc-Chance haben als andere Items, weil es orange ist.

**Comment by Testear** [comment]
Nochmal, es sind Quellen gepostet worden - egal ob  du diese als zuverlässig erachtest oder nicht.

Also Poste Gegenquellen oder halt die Finger still.

**Comment by Jura500** [comment]
Es sollte ja noch erlaubt sein über Quellen zu diskutieren und diese anzuzweifeln, oder? 

http://wowwiki.wikia.com/wiki/Talk:Sulfuras,_Hand_of_Ragnaros
Hier ist die Rede von 30%, allerdings ist es sehr fragwürdig wie genau diese Angabe ist, da diese Schätzungen häufig recht subjektiv sind.

http://wowwiki.wikia.com/wiki/Thunderfury,_Blessed_Blade_of_the_Windseeker?direction=prev&oldid=351349
Naja, das ist keine Quelle.

https://www.youtube.com/watch?v=ovhRqAxnXqg
4 Proccs bei 52 hits. macht ca 7,7% und ist leider völlig unbrauchbar, da 52 hits statistisch unbrauchbar sind.

http://wow.ingame.de/forum/threads/90013-Welche-waffe-ist-besser-Ashkandi-oder-die-Hand-von-Ragnaros
In dieser Quelle wird von 5-10% geredet. Keine Ahnung wie verlässlich das ist.

http://teamice.org/forums/showthread.php?t=3480
Laut Sabbaer wird hier von 30% geredet. Allerdings beziehen diese 30% sich auf TF. (Post 6&7)

http://forums.jeuxonline.info/showthread.php?t=645195
Hier gehen die Schätzungen von 15%-40%. Mein Französisch ist leider nicht vorhanden, deswegen kann ich über die Qualität nichts sagen.

https://vanilla-twinhead.twinstar.cz/?issue=718#comments
Leider eine neue Quelle. Hier wird von 10% geredet. Allerdings ist es auch hier fragwürdig woher diese Zahlen stammen.

Von daher sind die geforderten 25% wohl nicht durch Quellen gedeckt. Die Quellen deuten tendentiell auf die 10% hin.

**Comment by dagochen** [comment]
@Testear Folgendes hatte Sabbaer geschrieben:
> 3% procchance ist also für dich ok, bei einem orangenem item, da liegt ja die procchance von kreuzfahrer und von knochenhäschers schneide höher und von allen anderen 2 händern im spiel. D.h. also die beste waffe bis might of menethil ist eigentlich die schlechteste vom proc und ist eigentlich grün, denn sone procchance haben grüne waffen mit effect drauf

Zu dem Punkt, dass du hoffst das ich kein Dev bin: Bin ich nicht, korrekt. Dennoch habe ich hier unzählige Bugs bereits gefixt und nur ein Teil davon ist für die meisten bekannt (durch Danksagungen in den Patchnotes). Kannst also froh sein, dass ich sehr wohl Dinge fixe, obwohl ich nicht offiziell im Team bin, sonst würde vieles noch nicht korrekt funktionieren.

Zu den Beweisen (die ich wirklich nicht brauche, die stehen schließlich schon in jedem Beitrag, den IHR ALLE gepostet habt): Wie von Jura korrekt angemerkt, gibt es zahlreiche verschiedene Aussagen über die Proccchance. Und jede Quelle macht alle anderen unglaubwürdiger, weil sie einfach widersprüchlich sind. Und genau das habe ich angemerkt und kritisiert. Es ist sehr schwer, aufgrund dieser vielen Widersprüche eine Entscheidung zu treffen und die Ursprungsannahme von Sabbaer ist mehr als widerlegt worden.

Mir geht es darum, dass bestimmte Personen mal begreifen, dass ein Bugreport, der innerhalb von nicht mal 24 Stunden derart mit Gegenbeweisen zugemüllt wird schwer zu fixen wird für die Devs und vielleicht VORHER mal genauer recherchiert worden sollte, von der Person, die etwas geändert haben möchte. Hätte Sabbaer alle oben genannten Quellen selber rausgesucht und genannt und dann gesagt "Zwischen 10-30% habe ich alles in den Quellen gelesen, wobei 10% am wahrscheinlichsten ist" wäre viel Zeit und Arbeit gespart worden.

**Comment by Loplin** [comment]
Lieber dago
Der beitrag wurder zwar zugemüllt, jedoch mit keinem einzigen "gegenbeweis"
Es wurden fragwürde quellen mit werten von 10-30% proccchance gepostet
Aber keine quelle in der steht, dass die proccchance bei (noch nicht bestätigten) 3% liegen
Lg loplin

**Comment by Testear** [comment]
und es wird weitergemüllt

**Comment by dagochen** [comment]
@Loplin Aktuell ist die Chance bei ca 6,x%, wenn auf Nef die Mangos-Standard-Werte hinterlegt sind, wovon ich ausgehe. 

@Testear: hatte ich nicht anders erwartet...

**Comment by Sabbaer** [comment]
also tut sich hier nichts mehr? und es bleibt bei den unterirdischen 6,schlagmichtot % procchance des hammers?

**Comment by Dotox** [comment]
Einfach gedulden :)

**Comment by Sabbaer** [comment]
ok, bin gerne geduldig aber trotzdem weiter penetrant, sry ;)

**Comment by dagochen** [comment]
Für die DBC-Korrekturen:
```c++
case 21162: // Sulfuras
    spellInfo->procChance = 10.0f;
    break;
```

Ich habs auf 10% gestellt, weil dass das mindeste ist, was bewiesen wurde. Je höher man es stellt, desto unwahrscheinlicher wird es, dass man den richtigen Wert hat, wobei 15% immer noch vertretbar und realistisch ist. Dabei handelt es sich allerdings auch nur um eine Schätzung, nicht um empirische & fundierte Informationen.

**Comment by Sabbaer** [comment]
wurde da schon dran rumgedrehnt oder passiert doch einfach nix mehr? ka wie ich mich jetzt verhalten soll und will echt nicht nerven?

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1526
wird getaggt und das hier nicht......
