### ISSUE TITLE
Blizzard

### ISSUE THREAD

**Issue by Muchdey** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1034]
Beim bombfarming in Silithus ist JEDEM unserer Magier aufgefallen, dass Blizzard einfach komplett random aufhört zu ticken, teils schon am Anfang vom Cast und teils mittendrin. Ist ziemlich nervig da sehr viel Schaden und Mana unnötig verloren geht. Wäre schön wenn es gefixxt werden könnte bevor ich 80000 weitere Silithidenknochenpanzerfragmente gefarmt habe.

Grüße 
Muchdey

**Comment by nightblizard** [comment]
Nicht reproduzierbar.
