### ISSUE TITLE
Blizzard

### ISSUE THREAD

**Issue by Muchdey** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1035]
Zuerst mal finde ich es bodenlos, dass ich quasi so dagestellt werde als hätte ich Halluzinationen. Man Hätte wenigstens den Thread noch auflassen können falls ich es morgen besser beschreiben könnte oder sich andere Magier zu diesem Thema melden. Mir haben auch schon andere Magier dieses Problem bestätigt.

So nun dazu warum ich den Thread neu eröffne. Ich glaube ich habe herausgefunden was den Bug hervorruft. 2 oder mehrere Magier müssen Blizzard casten und sobald ein Magier Blizzard abbricht, hören die anderen Blizzards auf Schaden zu machen. 

Hat mich nur 10 Minuten gekostet diesen Bug der anscheinend nicht zu reproduzieren war zu reproduzieren.

**Comment by dagochen** [comment]
Betrifft #1034

**Comment by ircfelix** [comment]
Hab zum Blizzard schon nen Report geschrieben...

**Comment by Sabbaer** [comment]
jo, deswegen wurde der andere auch rausgenommen oder?

**Comment by hraesvelgr** [comment]
wenn die devs jedesmal 10 minuten brauchen um einen bug zu reproduzieren, bei mehr als 1000 einträgen...naja, gute nacht, marie.

**Comment by ircfelix** [comment]
Ich denke dass grundlegend was mit kanalisierungsmechaniken nicht funzt, da bei vielen kanalisierungszaubern Fehler auftreten. Sie bugreport magier: hervorrufung.

**Comment by Muchdey** [comment]
Du musst deine Evo nur richtig timen, also bei mir klappts immer ;)

**Comment by dagochen** [comment]
Ich vermute es ist ähnlich bei Arkane Geschosse, nur dass der AoE Zauber weiterläuft, aber sich überschreibt. Können daher mal 2 Magier unterschiedlicher Ränge von Blizzard verwenden, ob das dann auch auftritt?

**Comment by ircfelix** [comment]
@Muchdey: lass die Diskussion über Evo am besten in den Bugreport davon verschieben :-)

**Comment by Muchdey** [comment]
Ich versuchs mit den unterschiedlichen Rängen mal. Danke.

**Comment by Muchdey** [comment]
Loooool. Niedrigere Ränge machen 0(!!!) DMG von Anfang an. Vllt weil ein mächtigerer Zauber aktiv ist?
