### ISSUE TITLE
(Kampf-, Logistik-, Taktik-) Aufträge in Silithus - kein Ruf

### ISSUE THREAD

**Issue by Flako123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1036]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version: 1.2.0

Wie sollte es sein?
Die (Kampf-, Logistik-, Taktik-) Aufträge in Silithus sollten jeweils 50 Ruf bei der Abgabe bringen.

Wie ist es?
Die Quests bringen kein Ruf.

Links:
Beispielhaft für alle Aufträge: http://datenbank.welli-it.de/?quest=8497

Quelle:
http://www.omega-legion.de/viewtopic.php?t=172

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by dagochen** [comment]
Puhhh....die alle raussuchen ist ja mal kacke. Hoffe ich hab keinen vergessen^^

```mysql 
UPDATE quest_template SET RewRepFaction1 = 609, RewRepValue1 = 50 WHERE entry IN (8737,8537, 8536, 8535, 8740, 8538, 8534, 8738, 8739, 8498, 8740, 8497,8804,8540, 8805, 8541, 8806, 8778, 8785, 
8783, 8809, 8779, 8807, 8781, 8786, 8780, 8787, 8782, 8808, 8496, 8810, 8829, 8773, 8539, 8772, 8687, 8774, 8775, 8776, 8777, 8501, 8502, 8770, 8771);
```

**Comment by Dotox** [comment]
Danke @dagochen!
