### ISSUE TITLE
Hexer Talent "Improved Imp" hat keinen Effekt

### ISSUE THREAD

**Issue by donSchoe** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1037]
Bloodpact Stamina +7 mit 30% bonus sollte +9 ergeben. Wird auch beim Skill korrekt angezeigt, aber der "Buff" an sich gibt nur +7. Siehe Screenshot.

![screenshot-56](https://cloud.githubusercontent.com/assets/967319/9782455/86213bc8-579d-11e5-878c-c61bfc311e66.png)

**Comment by Loplin** [comment]
Buffs werden nicht mit den korrekten Werten in der Buffleiste angezeigt. Das ist bekannt
Probier mal ob du in deinem charakterfenster die gewünschte Veränderung bei der ausdauer erkennen kannst, sobald du Blutpakt aktivierst

**Comment by Larnak1** [comment]
Dass die Buffs immer den "ungeskillten" Wert anzeigen, dürfte damals zu Classic auch normal gewesen sein.

**Comment by nightblizard** [comment]
Abgelehnt. Gründe stehen oben.
