### ISSUE TITLE
IronForge Wachen Fehler

### ISSUE THREAD

**Issue by ikkoe** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1039]
Der Wacheneintrag des Schneiders ist mit Inschriftenkunde verbugt

dadurch ist der eintrag zu hoch was sich auf andere einträge auswirkt da Inschriften kunde
höher angelegt wird als Schneider.
Dieser Fehler ist auch in anderen Hauptstäten zu finden:
-Ironforge
-Ogrimar

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451
nur einer von vielen einträgen. sufu bitte verwenden.
