### ISSUE TITLE
Uldaman Archaedas boss fight

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#104]
Welches Verhalten wird beobachtet?
-Archaedas befindet sich noch for dem betätigen des Beschwörungsteins in lebendiger Form und nicht in Steingestalt 

Wie sollte es sich verhalten?
- Archaedas befindet sich in steingestallt also unbeweglich wie alle anderen Kreaturen im raum und wird erst mit bestätigen des Beschwörungssteins lebending und ist ab dann ins Ziel zu nehmen

Schritte zur Reproduzierung
- Nach betätigen des Beschwörungssteins umgibt ein kleiner wirbelsturm Archaedas und er wird lebeding

Zusätzliche Informationen
-  https://www.youtube.com/watch?v=Nn4xe_DcXNw&feature=player_detailpage#t=32

**Comment by Archidamos** [comment]
Konnte ich auch beobachten
