### ISSUE TITLE
Quest: Jarl braucht eine Klinge

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1041]
Übersetzung Falsch oder Text falsch
![unbenannt](https://cloud.githubusercontent.com/assets/8680824/9825262/607685be-58d2-11e5-8775-9d26052d74ea.PNG)

Das Schwert können Schmiede herstellen

Questtext laut Datenbank:
http://datenbank.welli-it.de/?quest=1203

Bringt ein Mondstahlbreitschwert zu Jarl in den Düstermarschen.
    Mondstahlbreitschwert
Beschreibung
Ich habe zu schneiden. Ich kann Euch nicht sagen, was ich schneiden werde, aber...

Ich brauche eine Klinge. Eine ganz bestimmte Klinge...

Manche Leute sprechen von einem Mondstahlbreitschwert. Ich nenne es eine Schwingklinge.

Helft Ihr mir? Vielleicht findet Ihr sie in der Stadt, vielleicht sprecht Ihr mit einem Schmied und er macht sie eigens.

Aber schlaft nicht noch darüber. Was ich schneide, das hält nicht ewig...

**Comment by Gnomorus** [comment]
Die Quest hat mich auch so derbe abgefuckt!

**Comment by Dotox** [comment]
Dann recherchier doch bitte, was genau falsch ist damit wir das anpassen können :)

**Comment by hraesvelgr** [comment]
der questtext von unserem server ist von 2.3+ (PTR only?), die questmechanik und das benötigte item ist bei uns  korrekt. 



Talk:Jarl Needs a Blade

A moonsteel broadsword goes for 5g at the auctionhouse on my server! Is it really worth that much money to complete this quest? --Mozai 22:28, 10 October 2006 (EDT) 
http://wowwiki.wikia.com/wiki/Quest_talk:Jarl_Needs_a_Blade


--------------------

By Redcrosse (5,337 – 2·19·50) on 2007/10/17 (Patch 2.2.3)		
This quest has been changed on the 2.3 PTR. It now simply requires killing Razorspine, a nearby named murloc, and bringing his sword to Jarl. The rewards remain the same.
http://www.wowhead.com/quest=1203/jarl-needs-a-blade#comments

**Comment by Hengstenberg** [comment]
Wie @Slimmer2 schon geschrieben hat, ist der Questtext im Spiel nicht korrekt. In eurer Datenbank ist dieser jedoch richtig: https://datenbank.classic-wow.org/?quest=1203
Ich bin die Tage auch über diese Quest gestolpert und habe leider eine Stunde lang den Kerl aus dem Questtext gesucht, im Internet recherchiert und letztlich mit einem GM von euch geschrieben, der mir dann bestätigt hat, dass der Questtext nicht richtig ist.
Wäre toll für alle nach mir Folgenden den Questtext zu korrigieren, sofern das möglich ist.
Grüße, Hengstenberg
