### ISSUE TITLE
Dämonensklave

### ISSUE THREAD

**Issue by karni186** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1042]
Ich möchte hiermit folgenden Fehler melden.

Wenn man als Hexenmeister die Elite Dämonen in Winterspring übernimmt und diese gegen andere Mobs kämpfen lässt, wird die abgezogene HP nicht angezeigt, sprich der Lebensbalken der übernommenen Mobs bleibt immer bei 100%.

**Comment by ircfelix** [comment]
Vll. Bei anderen mobs noch testen? Evtl. ein allgemeines Problem des Zaubers.

Nutzt du irgendwelche unit frames? Wdb ordner gelöscht?

**Comment by Slimmer2** [comment]
Das gleiche Problem ist auch beim Priester wenn man einen NPC übernimmt. Liegt evtl an der Änderung mit der Anzeige des genauen Lebenswert der Gegner.

**Comment by karni186** [comment]
WDB Ordner wurde gelöscht, alle Addons ausgemacht. Fehler besteht auch dann noch. Und keine im Addon Paket enthaltenen Unit Frames lösen das Problem. Da es aber einmal funktioniert hat (ich war einige Zeit inaktiv) nehme ich wie Slimmer2 an, dass es an der Änderung mit den Lebenspunkten liegt.

**Comment by karni186** [comment]
Gerade bei den Satyrn in Felwood getestet, gleiches Problem.
