### ISSUE TITLE
[Jäger] Eisfalle bringt den Hunter infight

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1043]
Welches Verhalten wird beobachtet?
Zurzeit ist es so wenn ein Spieler durch die Eiskältefalle des Jägern getrapt wird bekommt der Hunter den "in Kmapf" status

Wie sollte es sich verhalten?
Der Jäger solllte nicht infight kommen wenn seine Eiskältefalle getriggert wird. Zumindestens im PvP.  

Schritte zur Reproduzierung
Falle legen > mit nem anderen Char rein laufen

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://nl.proxfree.com/permalink.php?url=s54aaHA%2FaGsaD5vHs0QZLcUclS%2FcUxrnNZwEMCiA0I%2FyqYSMrWZXIhaXPfY24N7P4EnHJYRK3nO937EMCE%2FZKw%3D%3D&bit=1 ab 15:07 kann man es gut sehen. Das Mount rechte leiste ganze oben wird nicht ausgegraut als der Priest getrapt wird.

http://datenbank.welli-it.de/?spell=1499
http://datenbank.welli-it.de/?spell=14310
http://datenbank.welli-it.de/?spell=14311

Ich weiß nicht wie das bei den anderen Fallen sein müsste.

**Comment by dagochen** [comment]
Ich hab es jetzt nur für die Eiskältefalle gemacht. Falls die andern Fallen noch dazu müssen, kann man das aber leicht abändern. 


In der Methode mit der folgender Signatur, ziemlich weit unten:
```c++
void Spell::DoSpellHitOnUnit(Unit* unit, uint32 effectMask, bool isReflected)
```

```c++
if (!(unit->GetTypeId() == TYPEID_PLAYER && realCaster->GetTypeId() == TYPEID_PLAYER && m_spellInfo->SpellFamilyName == SPELLFAMILY_HUNTER && m_spellInfo->SpellIconID == 180))
{
    unit->AddThreat(realCaster);
    unit->SetInCombatWith(realCaster);
    realCaster->SetInCombatWith(unit);
}
```

Für alle Fallen:
```c++
m_spellInfo->SpellFamilyFlags & UI64LIT(0x000020000000001C))
```
anstelle der Variante mit der SpelllIconId.

**Comment by SirBeansen** [comment]
push

**Comment by SirBeansen** [comment]
Das ist leider wieder buggy. Könnte man sich das nochmal ansehen?

**Comment by SirBeansen** [comment]
Bitte nochmal ansehen, der bugt schränkt stark ein :(
