### ISSUE TITLE
TF Procchance nach Patch 01.09.2015 unverädnert

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1044]
Nach dem die Procchance aufgrund des Reports #977 auf 25% geändert werden sollte habe ich diese getestet. Bei 1392 Autohits hatte ich 136 Proccs, was auf eine deutlich niedrigere Procchance schließen lässt.

**Comment by Sabbaer** [comment]
36k hits machen

**Comment by Seniorash** [comment]
Kann meine Beobachtung jemand bestätigen? 
Ich weiß nicht ob der fix auf dem Server ausgespielt wurde. Dort bekam ich an der Puppe mit knapp 3k Hits eine Proccchance von genau 12,5% raus.

**Comment by Loplin** [comment]
Bei 3k Schwüngen und einer procc-chance von 12,5% liegt die tatsächliche chance zu 95% wischen
10,7% und 14,3%
So viel zur Statistik :)
Bestätigen kann ich deine Beobachtung aber nicht, habe ja nicht getestet

**Comment by dagochen** [comment]
Bei mir auf dem Server liegt TF bei 11,6 (Mangos-Standard). Das würde in den von Loplin statistisch wahrscheinlichen Bereich fallen :D

**Comment by Testear** [comment]
Kann Seniorash´s Aussage nur bestätigen.

**Comment by nightblizard** [comment]
Konnte behoben werden und ist mit dem nächsten Update aktiv.
