### ISSUE TITLE
Chromaggus Timelapse

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1045]
Welches Verhalten wird beobachtet?
Nachdem der Tank von Chromaggus durch Timelapse gestunnt wird, verliert er die Aggro und Chromaggus wechselt auf das nächste Ziel in der Aggroliste, welches nicht gestunnt ist. Nachdem der MT wieder aus dem Stun kommt bekommt er die Aggro erst wieder, nachdem er selber Chsomaggus angreift (ob man trifft oder nicht spielt keine Rolle).

Wie sollte es sich verhalten?
Nachdem der Tank aus dem Stun kommt und weiterhin in der Aggroliste ganz oben ist sollte er automatisch von Chromaggus angegriffen werden.

http://www.dailymotion.com/video/x2svesx
Chromaggus rennt zum Offtank und von alleine wieder zurück.

**Comment by dagochen** [comment]
Threatmgr auf dirty setzen, dann sortiert der beim nächsten Servertick die Liste neu und SelectHostileTarget findet den richtigen Tank wieder.

**Comment by dagochen** [comment]
Funktioniert da inzwischen oder wieso hast du geclosed @Seniorash ?

**Comment by Seniorash** [comment]
ich Raide schon lange kein bwl mehr und bin irgendwie davon ausgegangen  dachte bloß ich Räume mal meine issues auf.

**Comment by hraesvelgr** [comment]
nicht einfach irgendws zumachen, was noch nicht die labels "behoben" oder "auf nefarian" hat :)

**Comment by BugsBugs** [comment]
Das funktioniert inzwischen ohne Probleme, könnte man also zumachen?

**Comment by Dotox** [comment]
Jau, das kam vor einigen Wochen oder Monaten.
