### ISSUE TITLE
Golddietrich hergestellt, aber nicht im Inventory

### ISSUE THREAD

**Issue by jemame** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1046]
Habe eben 9 Golddietriche hergestellt (Char: Quarrel, Schmied, Ironfoge), die nicht auffindbar sind. Habe auch WDB etc entfernt. 
Vorgehensweise: Mein Schlüsselbund umfasst 4 Felder, die jeweils mit 20 Silberdietriche gefüllt sind (Schlüsselbund also voll). Nun habe ich erstmal 8 Golddietriche hergestellt, die ich aber nirgends gefunden habe. Goldbarren und Schwere Schleifsteine wurden aber Stück für Stück verbraucht. Habe also die Silberdietriche aus dem Schlüsselbund genommen und habe nochmal einen Schlüssel hergestellt. Es gab keinen Error, trotzdem wurde wieder ein Goldbarren und ein Schleifstein verbraucht. Dennoch ist auch der jüngst hergestellte Golddietrich nicht aufzufinden.

**Comment by Gnomorus** [comment]
Ähnliches verhalten (Edukte verschwinden, von den Produkten fehlt jede Spur, da Inventar voll) gibt es auch beim Hexenmeister.
1. Dafür sorgen, dass das Inventar voll ist.
2. Gesundheitsstein herstellen (wird beim Seelenstein genauso sein)
3. Der Zauber läuft durch, Seelensplitter ist weg und (verständlicherweise) nichts neues im Inventar.

**Comment by Slimmer2** [comment]
Die Dietriche werden im Schlüsselbund abgelegt.
Bei Cassic erweitert sich dieser nicht ab einer belegten Slot Anzahl, sondern mit erreichen eines bestimmten Levels des Charakters.
Die Dietriche werden so in einem noch nicht sichtbaren Slot abgelegt und sind vorhanden

**Comment by Seraphitas** [comment]
Das habe ich bereits auch beim Q abgeben gesehen, meine Taschen waren voll und plobb 4 Belohnungen davon 2 weg :(

Zu testen in Westfall bei der Sanders Q Reihe, einfach mal mit vollen Taschen die Truhe ansprechen und Q abgeben.

**Comment by Slimmer2** [comment]
Das wenn die Taschen voll sind bzw. Nur ein Slot vorhanden ist und sich eine Quest mit mehreren Belohnungen abgeben lässt ist ein anderer Bug. Gehört aber nicht zusammen.

Hier sollte man klären ob die Dietrich überhaupt in den Schlüsselbund abgelegt werden soll, oder in den normalen Taschen.

**Comment by hraesvelgr** [comment]
weiterer bug: lootet man zb den gordokschlüssel in düsterbruch, und der schlüsselbund ist voll, verschwindet der schlüssel einfach.
nebeneffekt: will man ihn ein zweites mal looten (andere id) und hat platz im schlüsselbund, sagt das game, dass man dieses item nur einmal tragen kann (obwohl man ja theoretisch bisher keinen schlüssel hat.

desweiteren: volles inventar, 19 items von einem 20er stack im inventar. 2 items von den gleichen items wie das sstack adden. man bekommt das tack voll. der eine item was über ist verschewindet einfach (9 dunkeleisenerz bei mir *rages*)

**Comment by Ahzeral** [comment]
Grüße,

Ist zwar schon ein etwas älterer Post, aber ich denke, es könnte für andere Spieler mit dem selben Problem hilfreich sein zu wissen, dass dieses kein Bug ist. Die Dietriche werden im Schlüsselbund abgelegt, der auf einer gewissen Stufe von 4 Feldern auf 8 vergrößert wird, bzw. diese Felder erst sichtbar macht. Heißt, die Dietriche sind vorhanden, können nur erst später benutzt werden, wenn der Schlüsselbund erweitert wurde.
