### ISSUE TITLE
Nachfolgende Taktikaufträge und Logistikaufträge + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1047]
Hallo,

Problem
aktuell ist es so, dass manche der Umschläge nichts enthalten. Dies liegt daran, dass die Looteinträge nicht gruppiert sind und einzeln ausgerollt werden. 

Sollzustand
Ich habe im Netz nichts gefunden, was diesen Zustand zu Classiczeiten beschrieben hat. Außerdem liegt die Summe der Einzelwahrscheinlichkeiten bei exakt 100%, was nahelegt, dass diese in einem Wurf ausgerollt werden sollten. 

Fix
```mysql
UPDATE `item_loot_template` SET `groupid` = '1' WHERE `entry` IN (20805, 21386, 21133);
```

**Comment by ircfelix** [comment]
Warum werden dem seine Fixes eigentlich immer ignoriert? Funzen die nich oder was?

**Comment by nightblizard** [comment]
Wurde übernommen, vielen Dank!
