### ISSUE TITLE
Warlock -Spellstone-

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1048]
Salut,

Der Zauberstein vom Warlock [http://db.valkyrie-wow.org/?item=13602] hat folgenden Tooltip.
"When equipped and used, the Major Spellstone removes **all magic effects from the caster** and will absorb 900 magic damage for 60 sec." 

**Welches Verhalten wird beobachtet?**
Momentan kann man diesen nur usen wenn man debuffs auf sich hat.

**Wie sollte es sich verhalten?**
Es sollte beim benutzen alle magischen debuffs und buffs entfernt werden
Man sollte diesen auch benützen können wenn man "nur" buffs auf sich hat. (Stamina, Demon Armor etc.)

http://wow.ingame.de/forum/threads/108567-Zauberstein-Bug-seid-1-11

**Comment by Slimmer2** [comment]
Hier der link zu unserer Datenbank 
http://datenbank.welli-it.de/?spell=17730
http://datenbank.welli-it.de/?spell=17729
http://datenbank.welli-it.de/?spell=128

**Comment by nightblizard** [comment]
Konnte behoben werden, danke
