### ISSUE TITLE
NPC: Falsche Mobresistenzen

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1049]
Die Mobs http://datenbank.welli-it.de/?npc=1812 und http://datenbank.welli-it.de/?npc=1813 haben viel zu hohe Resistenzen gegen alle Magieschulen. Bei mir widersteht jeder zweite Zauber, obwohl die 3-5 Level unter mir sind. Selbst mit 30 Spell penetration ändert sich nichts. Das kann doch nicht wahr sein.

**Comment by dagochen** [comment]
So unwahrscheinlich sind diese hohen Resistenzen nicht, da die Viecher elementarartige Mobs sind, laut wowwiki. Und Eles haben nun mal höhere Magieresis.

http://wowwiki.wikia.com/wiki/Bog_Beast

**Comment by ircfelix** [comment]
Die in ungoro sind auch nicht so abgespaced.

**Comment by Gnomorus** [comment]
haben auch nicht so ein hohes level.

**Comment by Haudraufinix** [comment]
Gerade diese Moosriesen haben in der Regel echt krasse Widerstände - die in den Höhlen des Wehklagens oder in Maraudon waren/sind auch gefühlt 80% Spellimmun

**Comment by nightblizard** [comment]
Die Mobs haben pro Schule entweder eine Resistenz von 57 oder von 114, das stimmt soweit. Was ich jedoch bei meinen Test herausfinden konnte ist, dass bei der Resistenzberechnung von Binary Spells mit dem Level des Ziels gerechnet wird und nicht mit dem des Casters. Das hat zur Folge, dass niedrigstufige Ziele zu oft wiederstehen und Ziele höherer Stufen zu selten.
Ich hatte das vor einer Weile (2 Jahre+) mal für "normale" Zauber behoben, jedoch die Binaries dabei vergessen. Mit dem nächsten Update ist das behoben.

**Comment by ircfelix** [comment]
Danke <3
