### ISSUE TITLE
Uldaman Archaedas Boss fight die 2te

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#105]
Welches Verhalten wird beobachtet?
im Bosskampf mit Archaedas wirkt er die zauber Gewölbewärter Wecken und Irdene wächter wecken dennoch nach wirken auf seine Wächter werden diese nicht lebendig was den boss kampf dann ziemlich easywin macht.

Wie sollte es sich verhalten?
- Archaedas wirkt Gewölbewärter Wecken und Irdene wächter wecken  und castet ein lila stahl auf den ausgewählten beschützer und dieser wird nach kurzer zeit lebending und beginnt den kampf mit der Gruppe

Schritte zur Reproduzierung
-Nach wirken Gewölbewärter Wecken und Irdene wächter wecken  auf die ziele, sollten diese lebeding werden.

Zusätzliche Informationen

- https://www.youtube.com/watch?v=Nn4xe_DcXNw&feature=player_detailpage#t=91
- http://www.wowhead.com/spell=10258
-http://www.wowhead.com/spell=10252

**Comment by Archidamos** [comment]
Konnte ich auch beobachten
