### ISSUE TITLE
Respawn Aggro

### ISSUE THREAD

**Issue by Seraphitas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1050]
Hallo,

ich möchte hier meinen ersten Fehler nennen. Und zwar wenn ein Mob respawnt hat man Instant Aggro, damals auf dem Offi Server hatte man immer n kleinen Moment Zeit wegzulaufen.

Ich hab auch bereits Recherchiert, und zwar müsste das ein Fehler in der Server Conf sein. 5 Sekunden sollten hier glaube ich Standard sein (Selbst getestet mit cMangos 0.12.3 auf meinem PC).

Es macht das spielen einfach unglaublich viel Schwerer wenn man gerade in einer Elite Q ist und plötzlich hinter dir eine Gruppe respawnt die gleich addet.

**Comment by dagochen** [comment]
https://github.com/cmangos/mangos-cata/commit/038a777d0d1018765128face5a38104feb0b06c1

**Comment by hraesvelgr** [comment]
xfurry's fixes.... damit kann man arbeiten.

**Comment by Dotox** [comment]
Den Commit hatten wir schonmal drin und ich kann mich erinnern, dass es damit massive Probleme gab weshlab wir das ganze wieder entfernt haben. Wollten es dann auf dem Testserver anpassen und nochmal testen aber dazu kam es irgendwie nie, weil immer irgendwas anderes wichtiger war.

**Comment by hraesvelgr** [comment]
soviel ich weiß ist das ganze für einen recht neuen core geschrieben?!

**Comment by Dotox** [comment]
Schon möglich, nur unterscheidet sich unsere Version mittlerweile sehr stark von der public variante :)

**Comment by Dotox** [comment]
Ich hab das heute für unsere Server-Version ungeschrieben und angepasst. Der kritische Bug, der damals den Release verhinderte, sollte behoben sein.
