### ISSUE TITLE
Emerald Dragons Spawn Timer

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1051]
(Man vergebe mir die 1:1 Kopie)

Hi,

laut Patch 1.10
"Die vier grünen Drachen sollten jetzt wie ursprünglich geplant spawnen. Sie spawnen jedes Mal gleichzeitig."

Unter: Schlachtzüge und Dungeons
http://wow.gamona.de/aktuelles/patchnotes/live/patchnotes-1-10-de/

Wie bereits in #504 und #897 gemeldet, aber geschlossen. Jetzt ist's ja spätestens soweit, den Timer anzupassen.

**Comment by Dotox** [comment]
Kann mich nicht erinnern, dass wir gesagt haben, dass wir die Inhalte auf 1.10 anpassen.

**Comment by Gnomorus** [comment]
1.12 kommt nach 1.10. Daran kannst du dich aber schon erinnern, oder?

**Comment by dagochen** [comment]
Wär vielleicht dennoch eine gute Idee @Dotox ... aktuell bekommt ein Allianz-Gildenbündnis ca. 80-90% aller Worldbosse. Würden die gleichzeitig spawnen, könnte sich das besser verteilen und andere Gilden hätten auch mal eine Chance, sich einen rauszupicken.

**Comment by Gnomorus** [comment]
Gibt es hierzu noch eine nachvollziehbare Aussage, warum der Spawntimer nicht berichtigt werden sollte?

**Comment by Slimmer2** [comment]
Der Spawntimer blieb aber nach Patch 1.10 unverändert bis 2.0
Deswegen sollten die Drachen auch gemeinsam Spawnen.

**Comment by Dotox** [comment]
Also Nochmal: Wir sind nicht auf dem Patchstand von 1.10 sondern auf 1.9.0 (AQ Opening). Wenn es an der Zeit ist, werden wir das ganze schon so anpassen.
