### ISSUE TITLE
[35] Marschenfroschschenkel - keine Frösche

### ISSUE THREAD

**Issue by Tejoz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1052]
Diese quest in den Marschen von Dustswallow scheint nicht zu funktionieren, da es keine Frösche zu geben scheint. Die einzigen Tiere die dort zu finden sind sind level 1 Nattern und Kröten. Auf YouTube sieht die quest hingegen so aus:

https://www.youtube.com/watch?v=bAjwaokdu6E
Und hier noch der link zu WOW Head: http://de.wowhead.com/quest=27183/marschenfroschschenkel#english-comments

**Comment by Dotox** [comment]
Bitte nutze unsere Datenbank als Verlinkung.

**Comment by Gnomorus** [comment]
Wie man leicht sieht befindet sich der seltene Marschenfrosch um diese Jahreszeit in seinem Winterquartier in dem Steinkrallengebirge: http://datenbank.welli-it.de/?npc=23979
