### ISSUE TITLE
Quests "Der Schattenwächter" und "Der Eiswächter" sind nicht wiederholbar

### ISSUE THREAD

**Issue by Ychap** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1053]
**Welches Verhalten wird beobachtet?**
Die Quests [Der Schattenwächter](http://datenbank.welli-it.de/?quest=9213) und [Der Eiswächter](http://datenbank.welli-it.de/?quest=9211) können nur einmal abgeschlossen werden. Danach aber nicht erneut angenommen werden.

**Wie sollte es sich verhalten?**
Die Quests [Der Schattenwächter](http://datenbank.welli-it.de/?quest=9213) und [Der Eiswächter](http://datenbank.welli-it.de/?quest=9211) sollten wiederholbar sein.

**Schritte zur Reproduzierung**
Die Quests bei Mataus der Zornwirker in der Kapelle des Lichtes annehmen. Diese Quests abschließen und danach versuchen diese erneut anzunehmen.

**Quellen:**
Dieser Bug wurde auch schon in dem Bugtracker der classicDB von CMaNGOS gemeldet und behoben. (https://github.com/classicdb/database/issues/510)
Dort werden folgende Quellen angegeben:
https://web.archive.org/web/20070604071106/http://wow.allakhazam.com/db/quest.html?wquest=9213
https://web.archive.org/web/20071103001520/http://wow.allakhazam.com/db/quest.html?wquest=9211

**Comment by Gnomorus** [comment]
#929 , #667 . "Dieses Problem ist uns bekannt - juckt aber keinen."
