### ISSUE TITLE
Passiver Schaden von Eisklingenaxt

### ISSUE THREAD

**Issue by blubby159** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1054]
http://datenbank.welli-it.de/?item=13952

Der gesonderte Frostschaden (permanent) wird nicht richtig berechnet. Es wird nur reiner physischer Schaden angerechnet. Im Bezug auf Viscidus wäre es sehr hilfreich, wenn man hier eine Waffe hätte, die wie auf dem Offiserver permanenten Frostschaden liefert. Gleiches Problem soll auch bei ThunderFruy auftreten. Zwar proccen die 300 Naturschaden aber die +16-30 Naturschaden der Waffe werden nicht seperat als Naturschaden ausgezeichnet. Wird der Naturschaden hier etwa auf den Waffenschaden addiert und dann komplett als physischen Schaden ausgegeben? Wäre das nicht falsch?

**Comment by Haudraufinix** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/976

**Comment by nightblizard** [comment]
> Ich nehme an du hast das getestet? Denn ich kann das kein Stück reproduzieren. Ich bekomme sowohl resists als auch partial resists in meinen Tests.
Hier Beispielhaft an einem nackten Level 60 Jäger mit 75% Frostresistenz:
> ![IBild](http://puu.sh/jEm6q/929de63e63.jpg)

> Die Waffe:
> ![!Bild](http://puu.sh/jEmcm/2169b8c81c.jpg)

> Die Treffer mit 28 und 29 Schaden stammen von der Grund dps eines nackten Level 60 Orcs.

> Hier auch gerne nochmal an einem Frost immunen Ziel:
> ![Bild](http://puu.sh/jEmj1/5b43484bf4.jpg)

> Hab das eine Stunde lang durchlaufen lassen und es kam kein einziges mal Frostschaden an.

> Ich denke also das wir aneinander vorbeireden oder du nicht gründlich genug getestet hast.

> - https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/976#issuecomment-131705464


Das funktioniert einwandfrei.

**Comment by Seniorash** [comment]
Wird bei vicidus ein Schlag mit der Axt denn als frostangriff gezählt? Darauf kommt es hier ja eigentlich an

**Comment by Haudraufinix** [comment]
Der Schaden wird nicht durch Rüstung sondern durch Frostresistenz verringert, ich nehme mal stark an, dann wirds als Frostschaden zählen.
