### ISSUE TITLE
Desolace - Quest - Buch der Uralten - Statue funktioniert nicht

### ISSUE THREAD

**Issue by Tikka2700** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1055]
Hallo, 

bei der Quest "Buch der Uralten" (http://datenbank.welli-it.de/?quest=6027) kann ich weder das Juwel auf die Statue nutzen noch die Statue selbst anklicken.

Laut Aussagen ging diese Quest gestern. Eventuell ist beim Reset etwas nicht in Ordnung. 
Das ganze mit Relog, Addons an/aus getestet und es ist reproduzierbar.

Grüße Tikka

**Comment by hraesvelgr** [comment]
soll angeblich funktionieren, aber nur einmal. das heißt, wenn dus schonmal versucht hast, müsstest du die quest abbrechen und neu annehmen. 

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/685
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/496
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/340
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/6

**Comment by Gnomorus** [comment]
Funktioniert (wenn überhaupt) nur 1 Mal pro Serverrestart.
