### ISSUE TITLE
Debuff Priorität - Arkane Geschosse

### ISSUE THREAD

**Issue by cowrea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1056]
# edit:
Hierbei handelt es sich nicht um einen Bug. Zu Zeiten von Classic war Arcane Missiles tatsächlich ein unsichtbarer Debuff und folglich kostet dies auch einen der 16 Slots. Da es sich hierbei um einen Channeling Spall handelt scheint dieser auch völlig korrekt höher in der Priorität einzustufen.
* Closed!

# Welches Verhalten wird beobachtet?
Schattenwort: Schmerz wird immer recht schnell entfernt obgleich nicht alle 16 Debuff-Slots belegt sind. Meine Vermutung ist und das wird [hier](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/720) bestätigt, dass [Arcane Missiles](http://db.valkyrie-wow.org/?spell=25346) einen Debuffslot kostet.

# Wie Sollte es sich verhalten?
Da ich auf offiziellen Seiten nichts in Erfahrung bringen konnte dass Arcane Missiles einen Debuffslot kostet vermute ich, dass dem eigentlich auch nicht so sein sollte.

# Schritte zur Reproduzierung
1 Shadowpriest der Dots wirkt und 16 Magier, die gleichzeitig Arcane Missiles wirken sollten alle Debuffs des Ziels entfernen.

# Zusätzliche Informationen:
Siehe Log-File:
~300 Zeilen, beginnend mit Shattenwort Scherz wird gewirkt und endet 7 Sekunden später mit erneutem wirken von Schattenwort: Schmerz.
Zur Erklärung:
Um 9/16 20:34:52.579 wirkt der Shadow Priest sein Shadow Wort: Pain.
2 Sekunden später um "9/16 20:34:56.319" wird es entfernt und "9/16 20:34:56.831" treffen die Arkanen Geschosse ein. diese 600 Millisekunden sind nun entweder die Zeit die der Zauber benötigt um vom Caster zum Boss zu fliegen oder ein lagg. Ich tendiere stark zu ersterem.

# Log-Datei:

#### 9/16 20:34:52.579  Broodlord Lashlayer is afflicted by Shadow Word: Pain.
9/16 20:34:52.722  Rodrick's Frostbolt hits Broodlord Lashlayer for 1023 Frost damage.
9/16 20:34:52.722  Mercutio's Sinister Strike was dodged by Broodlord Lashlayer.
9/16 20:34:52.722  Corrupted Red Whelp hits Biggiesmallz for 206.
9/16 20:34:52.723  Broodlord Lashlayer misses Graveraider.
9/16 20:34:52.945  Pagano begins to cast Flash of Light.
9/16 20:34:52.945  Safana's Shadow Bolt hits Broodlord Lashlayer for 1607 Shadow damage.
9/16 20:34:52.945  Gabby's Arcane Missiles hits Broodlord Lashlayer for 363 Arcane damage.
9/16 20:34:52.945  Brokenblade hits Broodlord Lashlayer for 122. (glancing)
9/16 20:34:52.947  Your Judgement of Light heals Brokenblade for 61.
9/16 20:34:53.039  Devenger begins to perform Shoot.
9/16 20:34:53.040  Sintya begins to perform Shoot.
9/16 20:34:53.041  Barazanthul gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:53.042  Rehush's Sinister Strike hits Broodlord Lashlayer for 392.
9/16 20:34:53.043  Your Judgement of Light heals Rehush for 61.
9/16 20:34:53.044  Evilyne's Sinister Strike hits Corrupted Red Whelp for 288.
9/16 20:34:53.044  Evilyne's Instant Poison VI hits Corrupted Red Whelp for 144 Nature damage.
9/16 20:34:53.045  Evilyne hits Corrupted Red Whelp for 266. (glancing)
9/16 20:34:53.045  Evilyne's Instant Poison VI hits Corrupted Red Whelp for 143 Nature damage.
9/16 20:34:53.046  Graveraider gains 380 health from Findil's Rejuvenation.
9/16 20:34:53.046  Suju's Backstab crits Broodlord Lashlayer for 1184.
9/16 20:34:53.048  Suju hits Broodlord Lashlayer for 143. (glancing)
9/16 20:34:53.254  Spätzli's Flash Heal heals Graveraider for 1270.
9/16 20:34:53.255  Spongie's Flash of Light heals Graveraider for 594.
9/16 20:34:53.256  Corrupted Bronze Whelp hits Evilyne for 214.
9/16 20:34:53.258  Evilyne is afflicted by Dazed.
9/16 20:34:53.358  Icerain's Arcane Missiles hits Broodlord Lashlayer for 421 Arcane damage.
9/16 20:34:53.358  Spieko crits Broodlord Lashlayer for 588.
9/16 20:34:53.359  Spieko's Bloodthirst heals Spieko for 20.
9/16 20:34:53.360  Your Judgement of Light heals Spieko for 61.
9/16 20:34:53.361  Spieko's Holy Strength heals Spieko for 114.
9/16 20:34:53.361  Inovatu hits Broodlord Lashlayer for 105. (glancing)
9/16 20:34:53.361  Suju crits Broodlord Lashlayer for 166.
9/16 20:34:53.363  Blast Wave fades from Bandero.
9/16 20:34:53.364  Blast Wave fades from Mortimas.
9/16 20:34:53.365  Broodlord Lashlayer is afflicted by Deep Wound.
9/16 20:34:53.366  Inovatu gains Clearcasting.
9/16 20:34:53.367  Blast Wave fades from Graveraider.
9/16 20:34:53.367  Spieko gains Flurry.
9/16 20:34:53.367  Spieko gains Holy Strength.
9/16 20:34:53.469  Walado's Arcane Missiles hits Broodlord Lashlayer for 419 Arcane damage.
9/16 20:34:53.471  Heri's Flash of Light heals Graveraider for 899.
9/16 20:34:53.562  Brokenblade's Sinister Strike was dodged by Broodlord Lashlayer.
9/16 20:34:53.562  Brokenblade hits Broodlord Lashlayer for 266. (glancing)
9/16 20:34:53.562  Inovatu's Claw crits Broodlord Lashlayer for 573.
9/16 20:34:53.562  Your Judgement of Light heals Inovatu for 61.
9/16 20:34:53.563  Mercutio hits Broodlord Lashlayer for 127.
9/16 20:34:53.563  Your Judgement of Light heals Mercutio for 61.
9/16 20:34:53.612  Clearcasting fades from Inovatu.
9/16 20:34:53.613  Bandero attacks. Broodlord Lashlayer dodges.
9/16 20:34:53.614  Thyrandius gains 70 Mana from Thyrandius's Illumination.
9/16 20:34:53.614  Thyrandius's Flash of Light critically heals Mortimas for 783.
9/16 20:34:53.703  Mortimas misses Broodlord Lashlayer.
9/16 20:34:53.809  Gantrithor begins to cast Flash of Light.
9/16 20:34:53.810  Aronea begins to perform Shoot Gun.
9/16 20:34:53.810  Gabby's Arcane Missiles crits Broodlord Lashlayer for 544 Arcane damage.
9/16 20:34:53.811  Heimwart hits Broodlord Lashlayer for 171. (glancing)
9/16 20:34:53.811  Spieko hits Broodlord Lashlayer for 117. (glancing)
9/16 20:34:53.811  Spieko hits Broodlord Lashlayer for 285. (glancing)
9/16 20:34:53.811  Spieko's Bloodthirst heals Spieko for 20.
9/16 20:34:53.811  Spieko's Bloodthirst heals Spieko for 20.
9/16 20:34:53.812  Mercutio's Sinister Strike hits Broodlord Lashlayer for 319.
9/16 20:34:53.812  Mercutio's Zulian Slice hits Broodlord Lashlayer for 92 Nature damage.
9/16 20:34:53.812  Mercutio's Instant Poison VI hits Broodlord Lashlayer for 124 Nature damage.
9/16 20:34:53.813  Broodlord Lashlayer hits Graveraider for 1425. (crushing)
9/16 20:34:53.813  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:54.014  Pagano begins to cast Flash of Light.
9/16 20:34:54.014  Heri begins to cast Flash of Light.
9/16 20:34:54.014  Zilak misses Broodlord Lashlayer.
9/16 20:34:54.014  Spongie gains 1044 Mana from Spongie's Restore Mana.
9/16 20:34:54.114  Devenger's Shoot hits Broodlord Lashlayer for 74 Shadow damage.
9/16 20:34:54.114  Graveraider's Heroic Strike hits Broodlord Lashlayer for 331.
9/16 20:34:54.115  Spieko's Whirlwind crits Broodlord Lashlayer for 691.
9/16 20:34:54.115  Spieko's Bloodthirst heals Spieko for 20.
9/16 20:34:54.116  Your Judgement of Light heals Spieko for 61.
9/16 20:34:54.117  Broodlord Lashlayer hits Graveraider for 340. (152 blocked)
9/16 20:34:54.117  Graveraider gains 1 Rage from Graveraider's Shield Specialization.
9/16 20:34:54.117  Graveraider's Greater Blessing of Sanctuary hits Broodlord Lashlayer for 31 Holy damage.
9/16 20:34:54.117  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:54.118  Deep Wound fades from Broodlord Lashlayer.
9/16 20:34:54.118  Broodlord Lashlayer is afflicted by Deep Wound.
9/16 20:34:54.120  Bloodthirst fades from Spieko.
9/16 20:34:54.222  Simtaka gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.222  Fipo gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.222  Inovatu gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.222  Corrupted Red Whelp hits Biggiesmallz for 216.
9/16 20:34:54.436  Icerain's Arcane Missiles crits Broodlord Lashlayer for 631 Arcane damage.
9/16 20:34:54.437  Sintya's Shoot hits Broodlord Lashlayer for 120 Frost damage.
9/16 20:34:54.437  Findil gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.437  Inovatu crits Broodlord Lashlayer for 282.
9/16 20:34:54.438  Your Judgement of Light heals Inovatu for 61.
9/16 20:34:54.438  Mercutio hits Broodlord Lashlayer for 252. (glancing)
9/16 20:34:54.439  Broodlord Lashlayer is afflicted by Mind Flay.
9/16 20:34:54.440  Icerain gains Ephemeral Power.
9/16 20:34:54.497  Anokii's Frostbolt was resisted by Broodlord Lashlayer.
9/16 20:34:54.563  Spongie begins to cast Flash of Light.
9/16 20:34:54.565  Althena's Flash Heal heals Bandero for 1272.
9/16 20:34:54.565  Biggiesmallz's Sinister Strike was dodged by Corrupted Red Whelp.
9/16 20:34:54.567  Shield Block fades from Heimwart.
9/16 20:34:54.659  Thyrandius begins to cast Flash of Light.
9/16 20:34:54.659  Devenger begins to perform Shoot.
9/16 20:34:54.662  Eloryen's Flash Heal heals Graveraider for 579.
9/16 20:34:54.662  Evilyne's Sinister Strike hits Corrupted Red Whelp for 308.
9/16 20:34:54.663  Anokii gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.663  Deep Wound fades from Broodlord Lashlayer.
9/16 20:34:54.663  Thunder Clap fades from Broodlord Lashlayer.
9/16 20:34:54.665  Clearcasting fades from Viivii.
9/16 20:34:54.868  Rodrick gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.868  Gabby gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.868  Icerain gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.868  Sintya gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.868  Viivii gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:54.868  Spätzli gains 1803 Mana from Spätzli's Restore Mana.
9/16 20:34:54.876  Broodlord Lashlayer is afflicted by Rip.
9/16 20:34:55.024  Pagano begins to cast Flash of Light.
9/16 20:34:55.025  Althena begins to cast Flash Heal.
9/16 20:34:55.025  Gabby's Arcane Missiles hits Broodlord Lashlayer for 363 Arcane damage.
9/16 20:34:55.029  Rejuvenation fades from Simtaka.
9/16 20:34:55.030  Rip fades from Broodlord Lashlayer.
9/16 20:34:55.032  Graveraider gains Shield Block.
9/16 20:34:55.200  Unjostlynn's Heal heals Graveraider for 955.
9/16 20:34:55.201  Broodlord Lashlayer attacks. Graveraider parries.
9/16 20:34:55.201  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:55.357  Icerain's Arcane Missiles was resisted by Broodlord Lashlayer.
9/16 20:34:55.434  Eloryen begins to cast Greater Heal.
9/16 20:34:55.434  Gantrithor begins to cast Flash of Light.
9/16 20:34:55.434  Walado's Arcane Missiles crits Broodlord Lashlayer for 628 Arcane damage.
9/16 20:34:55.434  Icerain's Arcane Missiles crits Broodlord Lashlayer for 631 Arcane damage.
9/16 20:34:55.434  Barazanthul's Aimed Shot hits Broodlord Lashlayer for 869.
9/16 20:34:55.434  Evilyne hits Corrupted Red Whelp for 115.
9/16 20:34:55.434  Evilyne's Instant Poison VI hits Corrupted Red Whelp for 144 Nature damage.
9/16 20:34:55.437  Broodlord Lashlayer suffers 475 Shadow damage from Jandarc's Mind Flay.
9/16 20:34:55.437  Broodlord Lashlayer hits Graveraider for 349. (152 blocked)
9/16 20:34:55.438  Graveraider gains 1 Rage from Graveraider's Shield Specialization.
9/16 20:34:55.438  Graveraider's Greater Blessing of Sanctuary hits Broodlord Lashlayer for 31 Holy damage.
9/16 20:34:55.438  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:55.438  Corrupted Bronze Whelp hits Spätzli for 272.
9/16 20:34:55.529  Unjostlynn begins to cast Heal.
9/16 20:34:55.530  You hit Broodlord Lashlayer for 308. (glancing)
9/16 20:34:55.531  Broodlord Lashlayer suffers 497 Shadow damage from Jandarc's Shadow Word: Pain.
9/16 20:34:55.648  Devenger's Shoot was resisted by Broodlord Lashlayer.
9/16 20:34:55.762  Bandero attacks. Broodlord Lashlayer dodges.
9/16 20:34:55.762  Heimwart hits Broodlord Lashlayer for 189. (glancing)
9/16 20:34:55.763  Your Judgement of Light heals Heimwart for 61.
9/16 20:34:55.763  Mortimas hits Broodlord Lashlayer for 146. (31 blocked)
9/16 20:34:55.763  Graveraider's Heroic Strike was dodged by Broodlord Lashlayer.
9/16 20:34:55.764  Corrupted Red Whelp hits Biggiesmallz for 222.
9/16 20:34:55.990  Gabby's Arcane Missiles hits Broodlord Lashlayer for 363 Arcane damage.
9/16 20:34:55.990  Zilak hits Broodlord Lashlayer for 200.
9/16 20:34:55.990  Spongie gains 35 Mana from Spongie's Illumination.
9/16 20:34:55.991  Spongie's Flash of Light critically heals Graveraider for 891.
9/16 20:34:55.991  Evilyne hits Corrupted Red Whelp for 223.
9/16 20:34:55.991  Evilyne's Instant Poison VI hits Corrupted Red Whelp for 143 Nature damage.
9/16 20:34:56.201  Walado's Arcane Missiles hits Broodlord Lashlayer for 419 Arcane damage.
9/16 20:34:56.201  Barazanthul's Auto Shot crits Broodlord Lashlayer for 1031.
9/16 20:34:56.201  Gantrithor gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.201  Heri gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.201  Biggiesmallz's Sinister Strike hits Corrupted Red Whelp for 272.
9/16 20:34:56.313  Thyrandius gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.313  Pagano gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.313  You gain 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.314  Spongie gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.314  Evilyne's Sinister Strike hits Corrupted Red Whelp for 321.
9/16 20:34:56.314  Aronea's Shoot Gun crits Broodlord Lashlayer for 410.
9/16 20:34:56.316  Broodlord Lashlayer suffers 475 Shadow damage from Jandarc's Mind Flay.
9/16 20:34:56.316  Broodlord Lashlayer attacks. Graveraider parries.
9/16 20:34:56.316  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
####  9/16 20:34:56.319  Shadow Word: Pain fades from Broodlord Lashlayer.
9/16 20:34:56.407  Barazanthul begins to perform Auto Shot.
9/16 20:34:56.408  Spongie begins to cast Flash of Light.
9/16 20:34:56.408  Devenger begins to perform Shoot.
9/16 20:34:56.409  Heimwart gains 15 Rage from Heimwart's Bloodrage.
9/16 20:34:56.409  Barazanthul begins to perform Auto Shot.
9/16 20:34:56.411  Heimwart gains Bloodrage.
9/16 20:34:56.462  Sintya's Shoot was resisted by Broodlord Lashlayer.
9/16 20:34:56.633  Heri's Flash of Light heals Biggiesmallz for 723.
9/16 20:34:56.633  Broodlord Lashlayer's Cleave was parried by Bandero.
9/16 20:34:56.633  Broodlord Lashlayer's Cleave hits Graveraider for 877. (152 blocked)
9/16 20:34:56.634  Graveraider gains 1 Rage from Graveraider's Shield Specialization.
9/16 20:34:56.634  Graveraider's Greater Blessing of Sanctuary hits Broodlord Lashlayer for 31 Holy damage.
9/16 20:34:56.634  Broodlord Lashlayer's Cleave hits Heimwart for 1142.
9/16 20:34:56.638  Shield Block fades from Graveraider.
9/16 20:34:56.748  Spätzli begins to cast Flash Heal.
9/16 20:34:56.749  Safana gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.749  Devenger gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.749  Danju gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:56.750  Holy Strength fades from Bandero.
#### 9/16 20:34:56.831  Viivii's Arcane Missiles hits Broodlord Lashlayer for 424 Arcane damage.
9/16 20:34:56.833  Simtaka's Healing Touch heals Zilak for 1506.
9/16 20:34:56.875  Corrupted Bronze Whelp hits Spätzli for 261.
9/16 20:34:56.881  Bloodthirst fades from Bienenstich.
9/16 20:34:57.081  Your Judgement of Command crits Broodlord Lashlayer for 392 Holy damage.
9/16 20:34:57.082  Gantrithor begins to cast Flash of Light.
9/16 20:34:57.083  Heri begins to cast Flash of Light.
9/16 20:34:57.083  Gabby's Arcane Missiles hits Broodlord Lashlayer for 363 Arcane damage.
9/16 20:34:57.084  Graveraider's Revenge hits Broodlord Lashlayer for 49.
9/16 20:34:57.084  Graveraider's Heroic Strike hits Broodlord Lashlayer for 327.
9/16 20:34:57.085  Your Judgement of Light heals Graveraider for 61.
9/16 20:34:57.097  Seal of Command fades from you.
9/16 20:34:57.097  You gain Vengeance.
9/16 20:34:57.106  Graveraider gains Sanctuary.
9/16 20:34:57.182  Simtaka begins to cast Healing Touch.
9/16 20:34:57.183  Anokii begins to cast Frostbolt.
9/16 20:34:57.183  Walado's Arcane Missiles crits Broodlord Lashlayer for 628 Arcane damage.
9/16 20:34:57.183  Corrupted Red Whelp hits Evilyne for 216.
9/16 20:34:57.183  Broodlord Lashlayer's Blast Wave hits Mortimas for 2699 Fire damage.
9/16 20:34:57.184  Broodlord Lashlayer's Blast Wave hits Bandero for 2201 Fire damage. (733 resisted)
9/16 20:34:57.184  Broodlord Lashlayer's Blast Wave hits Heimwart for 2893 Fire damage.
9/16 20:34:57.184  Broodlord Lashlayer's Blast Wave hits Graveraider for 1839 Fire damage. (612 resisted)
9/16 20:34:57.184  Broodlord Lashlayer's Blast Wave hits Zilak for 2106 Fire damage. (701 resisted)
9/16 20:34:57.184  Broodlord Lashlayer's Blast Wave was resisted.
9/16 20:34:57.185  Broodlord Lashlayer's Blast Wave hits you for 691 Fire damage. (2073 resisted)
9/16 20:34:57.185  Broodlord Lashlayer's Blast Wave hits Inovatu for 1477 Fire damage. (1477 resisted)
9/16 20:34:57.188  Bandero is afflicted by Blast Wave.
9/16 20:34:57.189  Heimwart is afflicted by Blast Wave.
9/16 20:34:57.190  Mortimas is afflicted by Blast Wave.
9/16 20:34:57.191  Zilak is afflicted by Blast Wave.
9/16 20:34:57.192  Dazed fades from Evilyne.
9/16 20:34:57.193  Inovatu is afflicted by Blast Wave.
9/16 20:34:57.195  Graveraider is afflicted by Blast Wave.
9/16 20:34:57.415  Rodrick begins to cast Frostbolt.
9/16 20:34:57.415  Danju's Shadow Bolt hits Broodlord Lashlayer for 1460 Shadow damage.
9/16 20:34:57.415  Icerain's Arcane Missiles hits Broodlord Lashlayer for 477 Arcane damage.
9/16 20:34:57.416  Thyrandius's Flash of Light heals Mortimas for 515.
9/16 20:34:57.416  Heimwart gains 1 Rage from Heimwart's Bloodrage.
9/16 20:34:57.417  Broodlord Lashlayer suffers 475 Shadow damage from Jandarc's Mind Flay.
9/16 20:34:57.419  Mind Flay fades from Broodlord Lashlayer.
9/16 20:34:57.420  Icerain gains Clearcasting.
9/16 20:34:57.515  Zilak's Sunder Armor missed Broodlord Lashlayer.
9/16 20:34:57.518  Althena gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:57.524  You gain Seal of Command.
9/16 20:34:57.707  Safana's Shadow Bolt hits Broodlord Lashlayer for 1595 Shadow damage.
9/16 20:34:57.707  Devenger's Shoot hits Broodlord Lashlayer for 81 Shadow damage. (26 resisted)
9/16 20:34:57.708  Bandero hits Broodlord Lashlayer for 156.
9/16 20:34:57.708  Your Judgement of Light heals Bandero for 61.
9/16 20:34:57.708  Jandarc gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:57.710  Pagano's Flash of Light heals Graveraider for 885.
9/16 20:34:57.710  Heimwart's Heroic Strike hits Broodlord Lashlayer for 280.
9/16 20:34:57.711  Your Judgement of Light heals Heimwart for 61.
9/16 20:34:57.711  Spätzli gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:57.711  Unjostlynn gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:57.711  Eloryen gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:57.713  Althena's Flash Heal critically heals Bandero for 933.
9/16 20:34:57.713  Mortimas hits Broodlord Lashlayer for 149. (31 blocked)
9/16 20:34:57.714  Biggiesmallz's Sinister Strike crits Corrupted Red Whelp for 559.
9/16 20:34:57.714  Biggiesmallz's Instant Poison VI hits Corrupted Red Whelp for 136 Nature damage.
9/16 20:34:57.717  Shadow Vulnerability fades from Broodlord Lashlayer.
9/16 20:34:57.831  Safana gains 1147 Mana from Safana's Life Tap.
9/16 20:34:57.831  Viivii's Arcane Missiles crits Broodlord Lashlayer for 636 Arcane damage.
9/16 20:34:57.833  Spongie's Flash of Light heals Graveraider for 592.
9/16 20:34:57.953  Pagano begins to cast Flash of Light.
9/16 20:34:57.953  Rodrick's Frostbolt crits Broodlord Lashlayer for 2009 Frost damage.
9/16 20:34:57.953  Gabby's Arcane Missiles crits Broodlord Lashlayer for 544 Arcane damage.
9/16 20:34:57.953  Bandero's Shield Slam hits Broodlord Lashlayer for 386.
9/16 20:34:57.953  Your Judgement of Light heals Bandero for 61.
9/16 20:34:57.953  Broodlord Lashlayer hits Graveraider for 334. (152 blocked)
9/16 20:34:57.955  Graveraider gains 1 Rage from Graveraider's Shield Specialization.
9/16 20:34:57.955  Graveraider's Greater Blessing of Sanctuary hits Broodlord Lashlayer for 31 Holy damage.
9/16 20:34:57.955  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:58.160  Zilak's Heroic Strike hits Broodlord Lashlayer for 298.
9/16 20:34:58.161  Barazanthul gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:58.267  Spongie begins to cast Flash of Light.
9/16 20:34:58.268  Althena begins to cast Flash Heal.
9/16 20:34:58.268  Walado's Arcane Missiles hits Broodlord Lashlayer for 419 Arcane damage.
9/16 20:34:58.268  Devenger begins to perform Shoot.
9/16 20:34:58.269  Jandarc gains 2097 Mana from Jandarc's Restore Mana.
9/16 20:34:58.269  Broodlord Lashlayer attacks. Graveraider dodges.
9/16 20:34:58.269  Graveraider reflects 22 Nature damage to Broodlord Lashlayer.
9/16 20:34:58.368  Icerain's Arcane Missiles hits Broodlord Lashlayer for 477 Arcane damage.
9/16 20:34:58.368  Heimwart gains 1 Rage from Heimwart's Bloodrage.
9/16 20:34:58.368  Barazanthul begins to perform Auto Shot.
9/16 20:34:58.369  Anokii's Frostbolt hits Broodlord Lashlayer for 1123 Frost damage.
9/16 20:34:58.370  Corrupted Bronze Whelp crits Jandarc for 468.
9/16 20:34:58.721  Aronea begins to perform Shoot Gun.
9/16 20:34:58.722  Sintya's Arcane Missiles hits Broodlord Lashlayer for 436 Arcane damage.
9/16 20:34:58.722  Heimwart's Shield Slam hits Broodlord Lashlayer for 377.
9/16 20:34:58.722  Barazanthul's Auto Shot hits Broodlord Lashlayer for 439.
9/16 20:34:58.723  Corrupted Red Whelp hits Biggiesmallz for 243.
9/16 20:34:58.724  Sintya gains Clearcasting.
9/16 20:34:58.915  Viivii's Arcane Missiles hits Broodlord Lashlayer for 424 Arcane damage.
9/16 20:34:59.056  Thyrandius begins to cast Flash of Light.
9/16 20:34:59.056  Gabby's Arcane Missiles hits Broodlord Lashlayer for 363 Arcane damage.
9/16 20:34:59.056  Graveraider gains 380 health from Findil's Rejuvenation.
9/16 20:34:59.056  Broodlord Lashlayer misses Graveraider.
9/16 20:34:59.265  You crit Broodlord Lashlayer for 964.
9/16 20:34:59.265  Evilyne's Sinister Strike was dodged by Corrupted Red Whelp.
9/16 20:34:59.266  Graveraider's Heroic Strike hits Broodlord Lashlayer for 305.
9/16 20:34:59.267  Your Judgement of Light heals Graveraider for 61.
9/16 20:34:59.317  Safana begins to cast Shadow Bolt.
9/16 20:34:59.317  Walado's Arcane Missiles crits Broodlord Lashlayer for 628 Arcane damage.
9/16 20:34:59.317  Devenger's Shoot hits Broodlord Lashlayer for 87 Shadow damage.
9/16 20:34:59.317  Heimwart gains 1 Rage from Heimwart's Bloodrage.
9/16 20:34:59.319  Spätzli's Flash Heal heals Heimwart for 684.
9/16 20:34:59.319  Findil gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:59.319  Simtaka gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:59.319  Fipo gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:59.319  Inovatu gains 36 Mana from Gantrithor's Greater Blessing of Wisdom.
9/16 20:34:59.321  Corrupted Blue Whelp hits Evilyne for 243.
#### 9/16 20:34:59.325  Broodlord Lashlayer is afflicted by Shadow Word: Pain.

Gruß cowrea

**Comment by cowrea** [comment]
Natürlich ist es schwierig bis unmöglich aus diesem Log die komplette momentane Debuff-Leiste zu erkennen, dennoch könnte dieser kleine Auszug hilfreich sein.

**Comment by dagochen** [comment]
> Da ich auf offiziellen Seiten nichts in Erfahrung bringen konnte dass Arcane Missiles einen Debuffslot kostet vermute ich, dass dem eigentlich auch nicht so sein sollte.

Leider kein Beweis für irgendwas, daher wird es schwer hier was zu machen. Auch, weil der Zauber nun mal so funktioniert wie er funktioniert. Arkane Geschosse setzt einen unsichtbaren Debuff auf dem Ziel, die bewirkt, dass dann die einzelnen Geschosse auch ausgelöst werden können. Ohne diesen Debuff würde der Magier-Zauber nicht funktionieren (was auch der Grund war, warum dieser Zauber lange Zeit nicht funktioniert hat und immer abgebrochen ist, weil eben dieser Debuff überschrieben wurde). 

Und da es sich bei Arkane Geschosse um einen Channeling Zauber mit einem unsichtbaren Debuffslot handelt, ist dieser in Priorität höher angesiedelt als ein Dot wie z.B. Schattenwort Schmerz.

**Comment by cowrea** [comment]
Sorry, ein anderer Tag, ein anderer Browser und vorallem eine elegantere Query und schon findet man eine Antwort darauf. Sofern Ihr [elitejerks.com](http://forums.elitistjerks.com/topic/8888-invisible-debuff-slots-on-mobs/) glauben schenkt und ich tue es, handelt es sich hierbei nicht um einen Bug.
Blizzard hat das Konzept unsichtbarer Debuffslots aus Warcraft 3 übernommen. Mich wundert nur, dass Arkane Geschosse criten kann obgleich es ein Debuff zu sein scheint. Aber das gehört hier nich rein.
