### ISSUE TITLE
Chrommagus - Timelapse zu 100%

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1058]
Hierbei handelt es sich um einen möglichen Bug, welcher aber sehr wahscheinlich scheint.

Seit dem Chrommagus-Patch bzgl. Timelapse hatten wir in 100% der Raids Timelapse + Breath X.
Aus diesem Grund habe ich bei anderen BWL-Gilden nachgefragt und auch dort gab es wohl nur noch Timelapse seit dem Patch.
Daher vermute ich einen Fehler bei der Breath-Rotation.

Was wurde beobachtet:

Timelapse kommt scheinbar zu 100% in der Rotation der Breaths vor.

Wie sollte es sich verhalten:

Timelapse hat die selbe Chance in der Rota zu sein wie die anderen Breaths.

Möglichkeiten zum testen:

Eine höhere Anzahl von BWL-IDs mit Chrommagus testen, ob Timelapse immer dabei ist.

**Comment by ircfelix** [comment]
Bei wie vielen Gilden hast du denn nachgefragt? Bei anorhin hatten wir vergangenen Sonntag doppel Frost oder Feuer.

**Comment by Slimmer2** [comment]
Bei "Die Legion" hat er wohl auch nicht gefragt.

**Comment by Karmanaz** [comment]
Ich hatte gestern Abend soweit auf Hordenseite gefragt, nicht mehr auf Allianzseite. Dann scheint sich der Task hier schon erledigt zu haben. Danke für das Feedback.

**Comment by nightblizard** [comment]
Hier war in der Tat ein Fehler, durch den überwiegend der selbe Breath gewirkt wurde. Zusätzlich überdauerte der Breath nicht einen Servercrash. Das wurde beides behoben.
