### ISSUE TITLE
[QUEST] Der vermisste Kurier

### ISSUE THREAD

**Issue by Seraphitas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1059]
Hallo,

hier nun mein zweiter Bug Report. Die Quest in Feralas mit dem Vermissten Kurier ist nicht machbar da man das Schiffswrack zwar anklicken kann aber dort keine Q abgeben geschweige denn annehmen kann.

Die Q ist gemeint

![wowscrnshot_091815_210616](https://cloud.githubusercontent.com/assets/14287053/9970537/f7151c64-5e55-11e5-9943-1ccf551ed4e0.jpg)

Und hier das Boot wo man sie abgeben/annehmen muss.

![wowscrnshot_091815_210621](https://cloud.githubusercontent.com/assets/14287053/9970553/0b411800-5e56-11e5-9408-1c0d65cf47db.jpg)

http://datenbank.welli-it.de/?quest=4125/Der%20vermisste%20Kurier

sollte die Q http://datenbank.welli-it.de/?quest=4127/Havarie geben.

LG

**Comment by Loplin** [comment]
Du musst zu dem boot, welches unterwasser liegt.
LG Loplin

**Comment by Seraphitas** [comment]
Ok stimmt Boot gefunden im Wasser. Dann sollte aber das am Land nicht anklickbar sein, weil es sehr verwirrend ist, dass beide Boote exakt gleich im Tooltip heißen und anklickbar sind.
LG

**Comment by Slimmer2** [comment]
Das Boot auf dem Land sollte es nicht geben, sondern nur das im Wasser
http://datenbank.welli-it.de/?object=164909

Auf dem Screenshots ist auch nur das Boot im Wasser zu sehen.

**Comment by dagochen** [comment]
@Slimmer2 
Welchen Screen meinst? Ich sehe hier keine Screens die deine Aussage (nur ein Boot, und zwar im Wasser) belegen.

**Comment by Seraphitas** [comment]
Er meint wahrscheinlich das es in der DB nur 1 Boot gibt, und meine Frau hat es gestern noch geprüft, Die Koordinaten aus der DB Stimmen mit dem Boot unter Wasser überein. Sprich das Boot am Land sollte gar nicht vorhanden sein.

LG

**Comment by Slimmer2** [comment]
http://www.wowhead.com/object=164909/wrecked-row-boat

**Comment by Seraphitas** [comment]
Wie man auf dem Screenshot von Slimmer2 sehen kann gibt es auch nur ein Boot dort.

**Comment by dagochen** [comment]
Wenn ein GM dann mal bitte mir die IDs raussucht für das falsche Boot, dann schreib ich den delete der es aus der DB wirft.

**Comment by Seraphitas** [comment]
Hallo,

weiterer Bug innerhalb der Q Reihe gefunden, und zwar später wenn man in den Schwarm bau soll um den Kurier zu suchen bleibt er einfach stehen und nach 5 Sekunden ist die Q fertig.

Normal müsste er laut http://datenbank.welli-it.de/?quest=4265/Flucht%20aus%20dem%20Schwarmbau bis zu einem bestimmen Punkt außerhalb des Schwarm baus laufen und dann erst die Q vervollständigen.

Sprich es ist eine begleit Quest ;)

LG

**Comment by Slimmer2** [comment]
@Seraphitas 
Den Fehler dann separat melden und nicht hier rein, sonst geht er unter.

**Comment by nightblizard** [comment]
Boot wurde entfernt. Die Quest im Schwarmbau funktioniert richtig, es fehlen jedoch die Texte, die der NPC sagen müsste bevor er verschwindet. Bitte gesondert melden.

**Comment by Slimmer2** [comment]
Den Fehler mit der Folgequest Flucht aus dem Schwarmbau kann ich bestätigen.
Mache dazu einen eigenen Report
