### ISSUE TITLE
Uldaman Quest Lösung der Verdammnis

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#106]
Welches Verhalten wird beobachtet?
- Nach dem looten der schrifttafel aus der steinernen Truhe despawnt diese und ist nicht mehr fur andere die diese Quest auch besitzen lootbar. ziemlich blöd beim 5 leuten in der Gruppe 

Wie sollte es sich verhalten?
-  Nach dem looten der schrifttafel aus der steinernen Truhe  schliesst diese sich wieder und bleibt stehen und ist für andere die diese quest auch haben lootbar

Schritte zur Reproduzierung
- despawnen verhindern oder respawn timer verringern auf ein paar sekunden weiss leider nicht genau wie sich das damals verhalten hat. aufjedenfall nicht wie es jetzt ist

Zusätzliche Informationen 
Ich möchte anmerken das dieses Problem so gut wie auf alles zutrifft was man in Instanzen, world etc. looten muss einen hohen respawn timer (truhen, tafeln, kisten, Urnen etc) hat und sehr blöd ist wenn man das mit Gruppen macht die die selben Qs. haben. Ich denke manchmal schon daran vor dem betreten der Instanzen keine loot quests zu teilen weil ich genau weiss das sie nur einer der Leute abschliessen kann pro Run. es ist mir das erste mal in Kloster aufgefallen mit der Buchband Quest  Mythologie der Titanen.
Aber wie ihr alle ja Uldaman kennt besteht das Halbe Questlog daraus Urnen Kisten und truhen zu looten, deswegen schreibe ich das hier mit dieser quest auf und hoffe, nein ich bitte das Dies gefixxt wird sonst muss man ja 5 mal in die Selbe Instanz nur damit jeder diese Quest abschliessen kann.
Deswegen spar ich mir das alle anderen qs mit der selben problematik hier zu listen weil das exakt das selbe problem ist.

**Comment by Archidamos** [comment]
Dieser Bug ist wirklich ärgerlich
