### ISSUE TITLE
Schamane; Angriff der Flammenzunge

### ISSUE THREAD

**Issue by bugreporten** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1060]
Hey, ich habe denke ich einen Bug entdeckt:

Server-Version: 1.2.0

Beschreibung: Beim Kampf gegen manche Gegner kommt es vor, das im Kampflog steht:
Angriff der Flammenzunge trifft Gegner. Schaden: 5 Feuer.
Es wird auch ein entsprechender Effekt-Sound abgespielt.
(Hört sich meiner Meinung nach dem Feuerschlag-Sound des Magiers an)

Ich hatte keine Totems gestellt war aber mit Waffe des Felsbeißers, Mal der Wildnis und Dornen gebufft.

Anmerkung: Ich bin zurzeit LvL 7 und besitze weder ein Totem der Flammenzunge noch eine entsprechende Waffenverzauberung
Der Screenshot entstand nach Ablauf der Buffs aber im Kampflog ist der entsprechende Entrag zu sehen.

![wowscrnshot_092015_120635](https://cloud.githubusercontent.com/assets/14369359/9980284/bd9c090a-5f92-11e5-8247-a1ad0f39978a.jpg)

**Comment by Haudraufinix** [comment]
Effekt tritt bei tieferen Rängen von Felsbeisser auf, nicht jedoch beim Maximalrang
