### ISSUE TITLE
zorn der gerechtigkeit + verbesserter zorn der gerechtigkeit.

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1061]
ich hab das gefühl, dass von zorn der gerechtigkeit (RF) und  verbesserter zorn der gerechtigkeit (IRF) der multiplier falsch berechnet wird ODER der tooltip einfach falsch ist.

laut tooltip sollte zorn der gerechtigkeit 60% mehr aggro durch heiligen schaden entstehen, und dieser wert (60%) wird um 50% erhöht, also +30% (0,5*60), ergo 90% mehr aggro.

soweit steht es auch im tooltip von RF drin, wenn man IRF geskillt hat. 
![rf](https://cloud.githubusercontent.com/assets/9222522/9980799/71a7f4a0-5fa6-11e5-8c9a-3c60c3da0877.png)

das ist laut einigen quellen auch richtig, mit 90%
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/13015-how-do-aggro-threat-work-wow.html
-When the Righteous Fury buff is active, Holy damage causes 1.6 threat, or 1.9 threat if you have 3/3 Improved Righteous Fury.

schaut man sich dann allerdings KTM an, so wird das ganz anders zusammengerechnet:

60% + 50% =110% mehr aggro. 
http://community.mmobase.de/paladin/8038-heiliger-schild-zorn-%3D-aggro.html

ist das nur ein KTM berechnungsfehler, oder ist da was anderes falsch?

edit: wir habens mal getestet, und ktm zeigt es definitiv richtig an. genau am aggro turnpoint hat der andere spieler aggro bekommen durch normale autohits. also würde ich sagen: IRF macht 20% zuviel aggro, da die berechnung falsch ist. 

IRF: http://datenbank.welli-it.de/?spell=20470
RF: http://datenbank.welli-it.de/?spell=25780 (die manakosten im tooltip der DB sind auch falsch)

**Comment by Larnak1** [comment]
Wenn du KTM nicht nachträglich modifiziert hast (oder eine modifizierte Variante benutzt), spiegelt KTM den damaligen Stand wieder, denn es greift ja nicht auf Bedrohungs-Daten vom Server zurück, sondern errechnet die Bedrohung aus dem Kampflog. Wenn also KTM etwas anzeigt oder berechnet, ist es sehr wahrscheinlich, dass das damals auch so geschehen ist, denn andernfalls wäre das KTM damals falsch gewesen.

**Comment by hraesvelgr** [comment]
ja aber was ist dann falsch? der tooltip? blizzards berechnungs-art?

kann ja nicht, sein, dass da steht "90% mehr aggro von heiligem schaden" und tatsächlich sinds aber 110%
da ist einfach der wert falsch.

**Comment by Larnak1** [comment]
Was genau falsch ist weiß ich nicht, ich wollte nur darauf hinweisen, dass die KTM-Berechnung ein Hinweis darauf ist, wie es früher in Classic tatsächlich war unabhängig vom Tooltip

**Comment by Adalbern12** [comment]
ich denke die berechnung erfolgt einfach wie folgt:
60% orginal aggro + 50% geskillte aggro = 110% gesammt.
obs so sein sollte ka

**Comment by hraesvelgr** [comment]
das ist das, was ich bereits gesagt habe... berechnet wird 110%, im tooltip steht 90%, also 20% zuviel. 

ob die 20% zuviel nun blizzlike sind ist die frage, die ich beantwortet haben will

**Comment by dagochen** [comment]
Jo sieht so aus als obs KTM-Fehler ist.
