### ISSUE TITLE
[Item] Dunkelmondkarte: Maelstrom + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1062]
Istzustand
Die Dunkelmond-Karte hat keine feste Proccchance, sondern arbeitet mit PPM.

Sollzustand
Die Dunkelmond-Karte sollte eine feste Proccchance von 1,5% haben.

Quelle
This trinket has about 1.5% proc chance, and it procs from every melee strike, including feral attacks (making this very useful for feral Druids) and free strikes.
http://wowwiki.wikia.com/wiki/Darkmoon_Card:_Maelstrom?oldid=153506

Fix
```mysql
UPDATE spell_proc_event SET ppmRate = '0', CustomChance = '1.5' WHERE `entry` = '23686';
```

**Comment by ircfelix** [comment]
Wie schaut es mit spelldamage scaling aus?

**Comment by nightblizard** [comment]
Wurde übernommen, danke!
