### ISSUE TITLE
[Item] Herz von Wyrmthalak + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1063]
Istzustand
Das Herz von Wyrmthalak hat keine feste Proccchance, sondern arbeitet mit PPM.

Sollzustand
Das Herz von Wyrmthalak sollte eine feste Proccchance von ca. 3-5% haben.

Quellen

> Assuming this thing is on PPM it looks to be about a 0.4 PPM proc. If it is a static chance proc it is about 2%. 
> Data: 
> 3.3 speed weapon 
> 235 swings 
> 5 procs 
> Granted my sample size is fairly small, but I only tried it long enough to realize it is fairly useless to me. 

2%, aber sehr geringe Testmenge (ungenau)

> Yes it does proc in catform and its good in catform with the small fast strike of the paws. 
> Over a sample of 850 hits I recorded 31 flame lashes or about 3.7%

3,7%, geringe Testmenge

> After a day of around 8 hours WoW and nearly 1000000 damage it procced around 3% of the time. 

3%, sehr gute Testmenge

> Using ProcWatch, 4100 dual wielding attacks yielded 139 processes, 1 process every 29.4 swings and 1.5 processes per minute.

3,3%, sehr gute Testmenge

> After testing through a full zg+aq20+bwl+aq40 run, proc rate came out to be 1.9ppm or ~5%. Generally hits for around 150.

5%, sehr gute Testmenge

https://web.archive.org/web/20070331193058/http://www.thottbot.com/i22321

Fazit: Zwischen 3-5 alles dabei. Daher scheinen mir 4% als realistisch.

Fix

``` mysql
UPDATE spell_proc_event SET ppmRate = '0', CustomChance = '4.0' WHERE `entry` = '27656';
```

**Comment by ircfelix** [comment]
Wie sieht es mit spelldamage scaling aus?

**Comment by nightblizard** [comment]
Kannst du bitte die Links zu den Quellen angeben?

**Comment by dagochen** [comment]
Steht doch da: https://web.archive.org/web/20070331193058/http://www.thottbot.com/i22321
