### ISSUE TITLE
tendris warpwood

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1064]
tendris warpwood (http://datenbank.welli-it.de/?npc=11489) onehittet oft einen zufälligen spieler direkt am anfang des kampfes.
es gibt keine meldung im kampflog darüber, was passiert. manchmal wird nichtmal "ihr sterbt" angezeigt, sondern man fällt einfach von 100% auf 0%, ohne irgendeine rückmeldung.

**Comment by Haudraufinix** [comment]
Bei uns gieng er ohne Probleme und ohne Tode (Hordeseite)

Was ich mir vorstellen könnte - eventuell habt ihr nicht alle 6 Treantwächter getötet und die haben dann leute durchn Boden o.ä. geschlagen

**Comment by hraesvelgr** [comment]
wir haben alle 6 wächter getötet. ausserdem gäbs dazu eine meldung im kampflog, wenn man von einem npc gehittet wird.

**Comment by nightblizard** [comment]
Nicht reproduzierbar.
