### ISSUE TITLE
[Raid] Schemengestalten von Jin'do + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1065]
Istzustand
Aktuell greifen die Schemen wie jeder andere Mob auch das Ziel mit der höchsten Aggro an.

Sollzustand
Laut Guides sollen diese aber eine eigene, andere Mechanik haben und bei dem Ziel bleiben, welches verflucht wurde in dem Moment wo sie gespawnt sind. 

Quelle
>The shades do not follow the usual aggro rules, and will not leave their targets when attacked

http://wowwiki.wikia.com/wiki/Jin%27do_the_Hexxer?oldid=301638

Fix
An der Stelle wo die Schemen gesummoned werden die Bedrohung des Ziels einen beliebigen, hohen Wert setzen, damit diese ihr Ziel weiterhin angreifen. 
```c++
pSummoned->AddThreat(pTarget, 50000.0f);
```

**Comment by hraesvelgr** [comment]
nicht, dass jindo diese hohen bedrohungswerte auch cool findet :D

**Comment by dagochen** [comment]
Jeder Mob hat seinen eigenen Aggro-Table. Genau deshalb funktioniert es ;)

**Comment by hraesvelgr** [comment]
ah ok :)

**Comment by nightblizard** [comment]
Konnte übernommen werden, danke!
