### ISSUE TITLE
datenbank: filteroptionen werden ignoriert.

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1066]
sucht man von der startseite der datenbank zb nach:

datenbank > gegenstände > rüstung > platte > hände

so wird der wert "hände" ignoriert, und stattdessen ALLE verfügbaren platte-items angezeigt. 

das scheint bei allen rüstungs-arten so zu sein (stoff, platte, .....)

**Comment by ircfelix** [comment]
Ebenso kann man nicht nach Schmuckstücken suchen.

**Comment by Wosser** [comment]
Außerdem werden bei Quests die Belohnungen nicht angezeigt.

**Comment by ircfelix** [comment]
Wir brauchen Wahax wieder.

**Comment by Dotox** [comment]
Die Datenbank wird (hoffe ich) dieses Jahr noch überarbeitet. Hab die letzten Wochen schonmal ein bisschen angefangen aber das braucht deutlich mehr Zeit als ich dachte.

**Comment by hraesvelgr** [comment]
gut :^)
