### ISSUE TITLE
[Druide] Quest: Prüfung des Seelöwen (Horde) Gegenstand nicht vorhanden

### ISSUE THREAD

**Issue by objectpaddy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1071]
Für die Quest "Prüfung des Seelöwen" müssen 2 Gegenstände gefunden werden. Der eine im Brachland, der andere im Meer westlich des Silberwalds. 
Der Teil im Meer sollte sich westlich von dem gestrandeten Schiff befinden, ist jedoch nicht aufzufinden. Und zwar weder die Schließkassette , in der er sich befinden sollte, noch der blubbernde Felsspalt, der daneben sein sollte.
Hier die Position: http://datenbank.welli-it.de/?object=177790
(habe mich auch an den Koordinaten orientiert, laut diesen befindet sich das Objekt jedoch jenseits der Erschöpfungsgrenze)

**Comment by hraesvelgr** [comment]
das ist die prüfug: du musst weiter als erschöpfungsgrenze. ist auch bei der allianz in westfall so.

**Comment by objectpaddy** [comment]
Aber dann sterbe ich. Ich bin schon über die Grenze hinaus geschwommen, konnte aber das Ding nie sehen o.O
