### ISSUE TITLE
Verbessertes Sprinten

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1072]
Welches Verhalten wird beobachtet?
Sprinten entfernt trotz geskilltem "Verbessertes Sprinten" nicht alle bewegungseinschränkenden Effekte.

Wie sollte es sich verhalten?
Es sollte zu 100% alle Effekte entfernt werden.

Schritte zur Reproduzierung
Unter anderem wird Benommenheit ( von allen Mobs die einen abmounten), Druckwelle ( z.b. Lashlayer oder der trash nach firemaw )  und auch der Nefarian Klassenruf nicht entfernt. ( beim letzten bin ich mir nicht 100% sicher aber ich glaube im Debuff steht das es die Bewegung der Schurken verhindert, Angreifen, Ausweichen usw, kann man noch.
Dies ist nur eine Beispielhafte Aufzählung, bei Bedarf suche ich noch weitere Fähigkeiten wenn dies für einen fix notwendig ist.

**Comment by hraesvelgr** [comment]
hast du eine quelle? denn wenn man anch dem tooltip geht, sollte gottesschild ja auch gegen allen schaden schützen...und trotzdem bekommt man schaden in der lava, oder wird von mr smite gestunnt.
ergo: nur weil da steht "alle" heißt es nicht, dass es auch wirklich "alles" entfernt

**Comment by Haudraufinix** [comment]
Dazzle/Benommenheit von NPCs kann durch nichts entfernt werden, keine Reisegestalt, keine Insignie und auch Sprint nicht - insofern also richtig

Zum rest kann ich mich nicht äussern

**Comment by dagochen** [comment]
http://datenbank.welli-it.de/?spell=30918
Removes snares and roots.

Benommen ist was anderes, wird daher korrekterweise nicht entfernt.
