### ISSUE TITLE
[Warlock] Death Coil Diminishing Return + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1073]
Istzustand
Aktuell unterliegt Death Coil DR.

Sollzustand
Dies wurde erst mit BC eingeführt, sollte also bei uns noch nicht aktiv sein.

Quelle
Patch 2.1.0:
Deathcoil
-Is now subject to diminishing returns in the Horror category. Currently, only Death Coil is in this category.

Das Addon NECB hat keinen Diminishing Return Eintrag für Death Coil.

Fix 

So (oder ähnlich) sollte etwas vorhanden sein, da ich das mit Wahax damals für Frostbite und Entrapment gemacht habe. Dort einfach die 3 Fälle für die Warlock-Spells hinzufügen.

Die Signatur lautet
```c++
DiminishingGroup GetDiminishingReturnsGroupForSpell(SpellEntry const* spellproto, bool triggered)
``` 
```c++
    switch (spellproto->Id)
    {
    case 12494: // Mage Frostbite
    case 19185: // Hunter Entrapment
    case 6789:  // Warlock Death Coil R1
    case 17925: // Warlock Death Coil R2
    case 17926: // Warlock Death Coil R3
        return DIMINISHING_NONE;
        break;
    }
```

**Comment by Amasov** [comment]
Daß Deathcoil keinem DR unterliegt, steht in Patch 1.08:

Death Coil - Cooldown reduced, mana cost increased, and now causes a short Fear effect that is not diminished. https://web.archive.org/web/20101204052255/http://www.worldofwarcraft.com/patchnotes/patch1p8.html

und seitdem tauchts auch nicht mehr in den Patchnotes auf. Ich vermute aber, daß sie den DR stillschweigend in Patch 2.0x eingeführt hatten, als Schneesturm die Realmübergreifenden BG's implementierten. Da meine ich mich zu entsinnen, daß sich einige WL's derbe aufgeregt hatten.

**Comment by Haudraufinix** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.1.0

*Death Coil is now is now subject to diminishing returns in the Horror category. Currently, only Death Coil is in this category. * wie Dago bereits erwähnt hat.

**Comment by Slipru** [comment]
http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by Amasov** [comment]
@Haudraufinix 

Joah .. jetzt hab ich auch endlich den offiziellen Patch dazu gefunden (etwas confused über die Patchbezeichnungen gewesen, denn es gab ja auch einen 2.0.010 .. ). WoW-Wiki traue ich nur so weit ich gucken kann (und das ist nicht unbedingt weit) ;) 

http://us.battle.net/wow/en/game/patch-notes/2-1-0

**Comment by nightblizard** [comment]
Wurde (so ähnlich) übernommen, danke
