### ISSUE TITLE
The War Effort -  zu hoher pro Kopf Farmaufwand

### ISSUE THREAD

**Issue by Hakii** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1075]
Die aktuelle Farmmenge die jeder Spieler in die Öffnung von Ahn'Qiraji stecken muss, steht in keinem Verhältnis.

Dieses Event wurde für eine deutlich größere Spielerzahl entworfen:

Zum 31.12.2005, ein paar Tage vor der Implementierung von dem "The War Effort"- Quest Event betrugen die aktiven Abonnementenzahlen ca. 5,5mio Spieler, verteilt auf Rund 200 Servern.
Demnach betrug die Farmmenge pro Abonnement im Durchschnitt 140 Einheiten eines undefinierten Materials.

Ich bitte die Farmmenge entsprechend anzupassen. Es sollte auch berücksichtigt werden, dass hier mehrere Spieler mehrere Accounts zeitgleich betreiben und die tatsächliche Spieleranzahl nicht der Accountanzahl entspricht.

Sollte der Wert auf die gegannten 140 Einheiten pro Kopf geändert werden, wird das Event stark trivialisiert. 

http://www.statista.com/statistics/276601/number-of-world-of-warcraft-subscribers-by-quarter/
http://wowwiki.wikia.com/wiki/Realm_List

**Comment by dagochen** [comment]
Aktuell sind 986.030 von 3.850.000 Einheiten gesammelt worden. Nach der Rechnung oben wäre das genug für 7043 Spieler. Damit sollten wir doch fertig sein, oder?

**Comment by Hakii** [comment]
Kommt darauf an, welches Blizzlikegefühl in Hinsicht dieses Falles vermittelt werden soll: belebter oder toter Server :-)

**Comment by hraesvelgr** [comment]
ein bisschen farmen schadet nie. und nach dagos rechnung sollte es ja im dezember geschafft sein. oder dauert das den spieler viel zu lang?

**Comment by Hakii** [comment]
Bedenkt man die Feiertage und die nervige Mats wie Raptorfleisch und Fische etc, würde ich definitiv nicht mehr von diesem Jahr ausgehen. Auch gehen immer alle davon aus, dass die Farmgeschwindigkeit konstant bleibt, was einfach nicht passieren wird. Es wird mal bessere, mal schlechtere Wochen geben, aber im Schnitt sollte sich die Farmmenge reduzieren. Ich habe in den letzten 7 Tagen rund 22.000 Mats gespendet (kombiniert auf beiden Seiten). Ich denke nicht, dass ich diesen Kurs so über Wochen hinweg halten kann.

**Comment by dagochen** [comment]
Das sind 12% von dem, was in den letzten 7 Tagen kam. Wenn ein bisschen Hilfe von den Admins kommt und dann Ende November, vielleicht Anfang Dezember als Weihnachtsgeschenk aufgeht freuen sich alle immer noch. Haben jetzt 2 Jahre gewartet, auf 1-2 Monate kommts dann auch nicht mehr an.

**Comment by ircfelix** [comment]
Was hier fehlt ist, dass der Server immer noch nicht an einem Strang zieht. Es wurde schon ganz schön beschrieben, wie man z.B. 500 Leinenstoffe als Einzelperson pro Stunde farmen kann. Ähnlich verhält es sich mit Raptorfleisch und Leder. Mir fallen SPONTAN 4 Spots für 4-5 Personen ein, wo man kontinuierlich Fleisch UND Leder farmen kann.

Wenn nur 20 (3, 3%) von ca. 600 aktiven Spielern so farmen würden wie Hakii, hätte man pro Woche 440.000 Mats und das Event wäre in nicht mal 8 Wochen fertig.

Den Einwand mit der pro Kopf Abgabe verstehe ich, doch sollte man meiner subjektiven Meinung nach die Faulheit der Masse nicht als Ausrede das Event zu ändern nutzen. 

Also: Farmt für das Wohl meines Sohnes!

**Comment by Haudraufinix** [comment]
Das Event umfasste auch für tote Server exakt diese Menge an Materialien. Lediglich griff Blizzard nach einiger Zeit ein, was auch Dotox hier angekündigt hat. Also ist es ziemlich genau Blizzlike.

Aber wenn man das Szepter halt schon fertig hat muss AQ schnellstmglich aufgehen, sonst dürfen sich ja auch noch andere übers Mount freuen

**Comment by ircfelix** [comment]
^

**Comment by Sheed90** [comment]
Genau so absurd ist es aber, wenn eine Gilde mit 5-6 Mounts rumläuft. 

Btt.: Meiner Meinung nach sind es aber nur ein paar Materialien, die einfach zu viel für diesen Server sind.

- Stoffe bzw. Verbände
- Kupferbarren
- Friedensblumen

Und vielleicht noch 1-2 andere Sachen. Sonst sind die Mats aber vollkommen in Ordnung und schaffbar. Was die Gemeinschaft angeht muss ich ircfelix zustimmen. Ich hab auch schon ein paar Stimmen gehört die sagten: "Ich geh doch nicht für die anderen Gilden farmen, blablabla." Aber daran wird sich wohl so schnell auch nichts ändern.

Wenn die Serverleitung wirklich plant, dass die Spieler alle Mats abgeben sollen, dann befürchte ich auch, dass wir erst nächstes Jahr AQ von innen sehen werden...

**Comment by Hakii** [comment]
@Haudraufinix 
Das habe ich ja damit gemeint, welches Spielgefühl hier erzielt werden soll. Nach den Zahlen von oben, waren rund 27500 Accounts in Durchschnitt pro Server aktiv, allerdings sagt diese Zahl weder etwas über die Bereitschaft der Spieler aus, noch ob die Accounts wirklich regelmäßig gespielt wurden. Selbst wenn von diesen 27500 nur die Hälfte aktiv gespielt hat und davon die Hälfte aktiv gespendet hat, betrug die pro Kopf Menge immer noch nur 560. Bei uns auf dem Server müsste jeder aktive Account, ob Vielspieler oder Gelegenheitsspieler, ob Farmpro oder Farmguffel, mindestens 2000 Mats spenden. Aber die Realität sieht nun einmal so aus, dass nicht jeder Spieler bei uns in dem Maße Farmbereit ist.

Für mich persönlich ist eine Öffnung von Ahn'Qiraji Blizzlike nach ~8-10 Wochen, was etwa der durchschnittlichen Öffnungsdauer gesunder Server entsprach. Ich gönne jedem das Mount, welches er in einer entsprechenden Zeit erspielt. Aktuell gibt es schon ein gewaltiges Übermaß an Mounts, also brauchen wir uns auch nicht beklagen.

**Comment by ircfelix** [comment]
@Hakii: nimm folgendes bitte nicht persönlich, aber:

Erspar uns diese Diskussion über diese Aq event Scheiße. Du hast dein Mount und willst jetzt Aq raiden, alles klar. Nur weil es dir nicht schnell genug geht brauchst du hier keinen Jammerbugreport, der an den Haaren herbei gezogen ist, eröffnen. Wenn dein Report eine Woche nach Eventrelease gekommen wäre, wäre es noch halbwegs glaubwürdig, dass du fürs allgemeine Interesse handelst. Aber das hier ist einfach nur egoistisches Handeln l.

**Comment by ircfelix** [comment]
Wer Cellys Prognosenpost verfolgt sieht dass die Releasezeit immer weiter Richtung 2015 rückt. Obwohl nur ne Hand voll Leute aktiv farmt.

**Comment by Hakii** [comment]
Die Prognose von Karmanat sollte nicht außen vor gelassen werden.

**Comment by ircfelix** [comment]
Mit dem kommenden Kräutersystem auf dem Testserver kann man das Zeug totfarmen.

**Comment by Hakii** [comment]
Wie dem auch sei, die Farmmenge pro Spieler ist nicht Blizzlike. Bitte einmal drüberschauen. Danke.

**Comment by dagochen** [comment]
Dann mach mehr Werbung für den Server, damit es mehr Spieler werden und jeder weniger farmen muss?

**Comment by ircfelix** [comment]
Machs wie ich, motivier Leute mit einer persönlichen Leidensgeschichte.

**Comment by nightblizard** [comment]
Es besteht kein Interesse daran die Menge der benötigten Materialien zu senken. Sollte das Event zu lange andauern, dann werden wir wie Blizzard damals eingreifen. Wann das so weit ist entscheiden wir und wenn es soweit gekommen ist, dann lassen wir euch das frühzeitig wissen.
