### ISSUE TITLE
Quest: "Feiner  Goldfaden" hat falsches Mindestlevel

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1079]
**Welches Verhalten wird beobachtet?**

Das Mindestlevel der Quest Feiner Goldfaden (http://datenbank.welli-it.de/?quest=4785) ist 37.

**Wie sollte es sich verhalten?**

Das Mindestlevel der Quest Feiner Goldfaden (http://datenbank.welli-it.de/?quest=4785) sollte 31 sein.

**Quelle**

http://wowwiki.wikia.com/wiki/Quest:Fine_Gold_Thread?oldid=1238469

**Links aus unserer Datenbank**

Quest: Feiner Goldfaden http://datenbank.welli-it.de/?quest=4785

**Comment by hraesvelgr** [comment]
die quest kann man mit 31 annehmen, nur eben erst mit 37 abgeben. 
>By piemanpm (2,416 – 7·14) on 2007/09/25 (Patch 2.2.0)		
For some strange reason, the guy isnt giving me the thread, i cant remember weather or not i got it before, but its showing as 0/1 in my questlog.

>By KillerPenguin (512 – 1·6) on 2006/12/11 (Patch 2.0.1)		
You will have to return to Xizk Goodstitch later on into this chain quest to collect the Fine Gold Thread.

es ist durchaus möglich, dass das blizzlike ist. 
angenehm wäre es aber, wenn man wenigstens eine message bekommen würde "ihr erfüllt nicht die stufenanforderungen" oder so, bis man level 37 ist. das würde einiges erleichtern.

http://wow.gamepressure.com/quest.asp?ID=2238 hier steht die quest auch mit level 37 drin.

**Comment by Gnomorus** [comment]
Wie in http://wowwiki.wikia.com/wiki/Quest:Fine_Gold_Thread?oldid=1238469 zu lesen, ist das Questlevel auch 37. Das MINDESTLEVEL ist jedoch 31.

**Comment by hraesvelgr** [comment]
das ist es doch auch auf unserm server. zum annehmen brauchst du level 31, zum abgeben level 37.
also alles korrekt, oder?

**Comment by Gnomorus** [comment]
Ich kenne bis auf diese ominöse Quest keine, die man mit Level x annehmen und erst mit Level y abgeben kann.
Bei der Molten Core Prequest stimmen die Levelbeschränkungen z.B. auch mit denen von wowwiki überein: http://wowwiki.wikia.com/wiki/Quest%3AAttunement_to_the_Core vs. http://datenbank.welli-it.de/?quest=7487
Benötigte Stufe -> Quest wird annehmbar(und abschließbar), Quest ist rot im Log
Stufe: empfohlene Stufe, Quest ist gelb im Log (oder andere beliebige Farbe einsetzen)

**Comment by hraesvelgr** [comment]
da aber mehrere spieler auch in comments sogar noch zu bc zeiten geschrieben haben, dass man "mit level 37 (bzw später) zu dem questgeber zurückkehren sollte, nachdem man die quest mit level 31 angenommen hat", nehm ich ewirklich an, dass das blizzlike ist.

allerdings: hier zb http://wow.gamepressure.com/npc.asp?ID=4153 steht die quest mit "Begins quest" auf level 37 drin, nicht 31. 

hier wiederum 31/37: http://wow.gamepedia.com/Quest:Fine_Gold_Thread
