### ISSUE TITLE
[Worldboss] Kazzak heilt sich nicht bei Pets / Totem + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1080]
Istzustand:
Kazzak heilt sich nur, wenn ein Spieler stirbt.

Sollzustand:
Stirbt ein Pet (Hunter/Warlock) oder ein Totem von Schamanen, sollte er sich auch heilen.

Quelle:
http://wowwiki.wikia.com/wiki/Lord_Kazzak_(tactics)?oldid=468022

Fix
An der Stelle, wo der Healzauber (http://datenbank.welli-it.de/?spell=21054) gewirkt wird,  folgende Fälle hinzufügen:
```c++
!victim->GetObjectGuid().IsPet() && !(Totem*)victim
```

**Comment by nightblizard** [comment]
Wurde teilweise übernommen. Grund:
"!(Totem*)victim" ist immer true, wenn victim != nullptr. C-Style casts führen keine type checks durch und casten den Typen einfach blind um. Wenn überhaupt müsstest du den Weg über RTTI gehen und hier dynamic_cast benutzen. RTTI ist aber recht teuer im Sinne von Performance, weshalb man das eher mit bedacht nutzen sollte. Die bessere Variante ist hier:
(!victim->GetObjectGuid().IsCreature() || !static_cast<Creature*>(victim)->IsTotem())

Dennoch danke für die Meldung!

**Comment by nightblizard** [comment]
Wurde teilweise übernommen. Grund:
"!(Totem)victim" ist immer true, wenn victim != nullptr. C-Style casts führen keine type checks durch und casten den Typen einfach blind um. Wenn überhaupt müsstest du den Weg über RTTI gehen und hier dynamic_cast benutzen. RTTI ist aber recht teuer im Sinne von Performance, weshalb man das eher mit bedacht nutzen sollte. Die bessere Variante ist hier:
(!victim->GetObjectGuid().IsCreature() || !static_cast<Creature>(victim)->IsTotem())

Dennoch danke für die Meldung!

**Comment by dagochen** [comment]
Danke für die Info ;)

**Comment by Larnak1** [comment]
Mh, dort steht nur "grounding totem", nicht Totems allgemein. Sind Totems nicht grundsätzlich immun gegen derlei AoE-Effekte?

**Comment by dagochen** [comment]
Außer dem Grounding Totem wird wohl keins sterben. Zumindest sind Totems bei mir kein Ziel der Schattenblitzsalve geworden. Ob das nun korrekt oder fehlerhaft ist, könnte ja auch mal wer anders raussuchen :P 

Allerdings hat Kazzak bei mir Totems umgehauen, wenn die Aggro gezogen haben, durch Schaden. Das ist in der Realität aber äußerst unwahrscheinlich, von daher folgt für Schamis nur folgendes: Kein Grounding Totem stellen. Für Hunter / Hexer: Keine Pets draußen haben.

**Comment by Larnak1** [comment]
Ich weiß nur dass wir die letzten Kazzak-Trys immer alle Schamanen angewiesen haben, auf Totems zu verzichten, weil ein Raid wohl mal daran gewipet ist. Da war ich aber nicht bei, mehr kann ich nicht dazu sagen :/
