### ISSUE TITLE
[Item] Dunkelmondkarte: Blauer Drache + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1081]
Istzustand
Aktuell procct der Blaue Drache nur von direkten Zaubern

Sollzustand
Er sollte auch von indirekten Zaubern, wie Hots/Dots proccen, nicht aber von den Ticks. Sprich beim Zaubern allgemein sollte ein Proc möglich sein.

Quelle
> "Spellcast" also seems to mean basically any skill that isn't physical, much like how Clearcast can proc from just about anything, like herbing, switching specs or crafting. It does not however, proc from each tick of a hot or dot.

http://jinxedthought.blogspot.de/2011/09/old-darkmoon-cards.html

Fix
Bei der Methode 
```c++
bool Aura::CanProcFrom(SpellEntry const* spell, uint32 EventProcEx, uint32 procEx, bool active, bool useClassMask) const
````
folgendes einfügen:
```c++
    if (m_spellAuraHolder && spell && m_spellAuraHolder->GetSpellProto() &&
        m_spellAuraHolder->GetSpellProto()->Id == 23688 && // Blue Dragon
       (procEx & (PROC_EX_NORMAL_HIT|PROC_EX_CRITICAL_HIT)))
       return true;
```

**Comment by ferendil** [comment]
der Fix hat zu keinem positiven Ergebnis geführt. 

Das Trinket wird weiterhin nur durch direkte Zauber ausgelöst

**Comment by Loplin** [comment]
Ist auch noch nicht implementiert wenn ich das richtig sehe
Normalerweise bekommen fixes erst das label "auf testserver", dann können sie getestet werden
Wird der fix für funktionierend befunden bekommt der beitrag das label "auf Nefarian" und wird als update aufgespielt.

**Comment by hraesvelgr** [comment]
"möglicher fix" wurde zu ehren von @dagochen eingeführt, und später auch anderer leute, die selber fixes geschrieben haben, die aber noch nicht von der serverleitung abgesegnet bzw eingefügt worden.

**Comment by Loplin** [comment]
Dieser fix ist noch nicht auf Nefarian seh ich das richtig?

**Comment by dagochen** [comment]
Stimmt. Siehe Labels ;)
