### ISSUE TITLE
[Alteractal] 2 Kampfmeister in Ironforge + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1083]
In IF steht ein Kampfmeister zu viel.
Brogun Steinschild soll in Darnassus stehen (tut er auch). Aber er steht ebenfalls in Ironforge und ist dort leider falsch.

Brogun Steinschild: http://datenbank.welli-it.de/?npc=5118

Fix:
```sql
DELETE FROM creature WHERE id = 5118 AND guid != 49937;
```
Der richtige Brogun hat bei mir die guid 49937.

**Comment by ircfelix** [comment]
Vote4celly im devteam. Einfach mal alte Differenzen hinter sich lassen und das Ego zum Wohle des Servers zurückstellen.

<3

**Comment by Larnak1** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1030

**Comment by Dotox** [comment]
Danke @dagochen!
