### ISSUE TITLE
[Alteractal] Drek'Thars Wirbelwind skaliert zu stark mit Waffenschaden + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1084]
Hab bisschen bei mir auf dem Server rumgetestet und festgestellt, dass der Schadensmultiplikator aus der Datenbank auf den normalen Autoangriff und auf Wirbelwind von Drekthar angerechnet wird. Verringert man nur den Multiplikator, würde das auch den normalen Schaden verringern. Die Mechanik in 
```c++
void Spell::EffectWeaponDmg(SpellEffectIndex eff_idx)
```
für alle Zauber zu verändern würde aber auch bedeuten, dass alle Bosse mit "Waffenschaden + x" weniger Schaden machen würden.

Daher habe ich folgenden Sonderfall eingeführt, der problemlos auf Nefarian übertragbar sein sollte. Damit macht der Wirbelwind nur noch 700-1200 Schaden.

Fix (bei Generic hinzufügen):
```c++
if (m_spellInfo->Id == 15589)
            {
                weaponDamagePercentMod *= (1.0f / m_caster->ToCreature()->GetCreatureInfo()->dmg_multiplier);
            }
```

**Comment by ircfelix** [comment]
Das is ein Hund! Der fixt ja freiwillig mehr als Night und Dotox! Würde dem Server sicherlich gut tun wenn er ins Devteam käme.

**Comment by hraesvelgr** [comment]
mich deucht, ihr sitzt heimlich zusammen im TS, plant fixes wie werbung für euch selbst gleichermaßen :D

**Comment by ircfelix** [comment]
Ne, ich bin einfach nur der Meinung dass Celly gute Arbeit leistet. Wenn er den Quellcode dieses Servers, nicht nur den seines eigenen Servers, zur Verfügung hätte (= im dev team wäre), könnte er noch mehr und leichter fixen.
Allerdings habe ich gehört dass die Serverleitung das aus persönlichen Gründen nicht will. Nur is es einfach kontraproduktiv, wenn man einen fähigen und motivierten nicht machen lässt.
Und - Gerüchteküche - es heißt ja auch Wahax wäre mehr oder minder gegangen worden, weil er was an der Serverleitungspolitik ändern wollte.
Zu letzterem möchte ich jedoch nichts weiteres sagen, da ich keine Sicherheit habe ob dieses Gerücht auch so stimmt. Nur hat es eben in der Vergangenheit öfter Fälle gegeben, in denen sich die Serverleitung nicht sonderlich offen, freundlich oder kooperativ gezeigt hat.

Die Frage die sich mir stellt ist, was das soll. Geht es hier um Machtspiele in denen nur Dotox und Night das Szepter halten sollen und kein anderer? Geht es um was größeres? Gründe die man so ohne weiteres nicht kennt? Ich will nichts unterstellen, sondern einfach nur mal eine logisch nachvollziehbare Erklärung, warum man sich gegen zusätzliche und fähige Programmierer so vehement versperrt.

**Comment by nightblizard** [comment]
![Illuminati confirmed](http://i.imgur.com/hkftiQq.gif)

Diskussionen dieser Art sind hier fehl am Platz, dafür ist das Forum da.

**Comment by Dotox** [comment]
Sieht gut aus, können wir gebrauchen. Danke!

**Comment by ircfelix** [comment]
vote 4 new dev!

**Comment by Sabbaer** [comment]
vote against

**Comment by dagochen** [comment]
Der "vote against" ist gut nachvolllziehbar. Ohne mich würde Paladin noch mehr verbuggt sein, als er es aktuell noch ist. Dafür würde er zwar doppelt so viel Schaden machen wie jetzt, wäre aber halt immer noch ein shit dd^^

**Comment by Dotox** [comment]
Diese Kommentare sind einfach herrlich :D

**Comment by dagochen** [comment]
Ja mal ehrlich. Was soll denn das? Ich helfe mit und werde dann geflamed wenn ich beim fixen des Buchbandes rausfinde, dass Palas zu viel Schaden mit x anderen Spells machen....als ob ich das mit Absicht machen würde. Für bereits bestehende Bugs kann ja keiner was....

**Comment by hraesvelgr** [comment]
dont hate the game..hate the player.  oder wie war das?

**Comment by ircfelix** [comment]
Macht lieber mal celly zum dev, dann muss er die scripte nimmer an seinem privaten server ausprobieren sondern kann die auf den server hier angepasst schreiben. -> schnellere und mehr fixes.

**Comment by Dotox** [comment]
Langsam werden deine Beiträge langweilig :(

**Comment by ircfelix** [comment]
Na sag halt mal was außer persönlichen Differenzen dagegen spricht. Wenn du mir stimmige Argumente bringst, kann ich damit mehr anfangen als wenn du Kommentare wie diesen kommentarlos löschst. Ich will euch auch nich stören, sondern nur dass dem Server in Form von nem motivierten möglichen Dev was gutes getan wird.

MfG

**Comment by Dotox** [comment]
Ich hab kein persönliches Problem mit ihm nur ist das Thema bereits seit Monaten gegessen und die Aufnahme wurde abgelehnt. Besonders wichtig ist nicht nur das beheerschen der Programmiersprache und das technische Verständnis, sondern auch viele andere, vielleicht auf den ersten Blick nicht sofort ersichtliche Spezifikationen. Diese zu nennen wäre natürlich falsch, weil sich so jeder Bewerber künstlich verstellen könnte. Und da wurden einige Anforderungen nicht erfüllt.

**Comment by dagochen** [comment]
Wenn das hier schon so breit getreten wird und ich zum 1. mal Auskunft über mögliche Gründe bekomme, würde ich gerne doch noch was dazu sagen: Ich kann nicht nachvollziehen, wie man ohne mit jemandem je kommuniziert zu haben erkennen kann, ob jemand irgendwelche anderen, vielleicht auf den ersten Blick nicht sofort ersichtlichen Spezifikationen, hat oder nicht. Dazu hätte man nämlich unter Umständen einen zweiten Blick tätigen müssen. Da aber selbst der erste Blick nie gemacht wurde....ach lassen wir das. Mir auch egal ob ich im Team bin oder nicht. Solange sich mal wer bequemt und die Fixes von mir einspielt, bevor die hier vergammeln, ist alles gut. Mach das ja hauptsächlich für die Leute die hier spielen (und ja, das Einspielen der Fixes könnte ruhig schneller gehen!)

Und ich wäre froh, wenn diese Diskussion echt mal zu Ende wäre. Danke!

**Comment by dagochen** [comment]
Mein Schurke wurde für über 4000 Schaden von Wirbelwind getötet.

**Comment by Dotox** [comment]
War Drek im Berserk / Enrage?

**Comment by Rushor** [comment]
![GitHub Logo](http://www.geschmeidige-hunde.de/wb/templates/marion/geschmeidige_hunde.gif)

**Comment by dagochen** [comment]
Kann ich grad nicht sagen, werde das am Wochenende mal genauer überprüfen ;)

**Comment by dagochen** [comment]
http://www.twitch.tv/dagochen/v/25919833

Am Ende des Videos sieht man wie er mich mehrfach onehittet. Wirbelwind sollte ca. 1000-2000 Schaden machen, laut Videos von früher und Beschreibungen (wowwiki, av-guides, etc). Selbst in Enrage mit 50% Bonus sind das immer noch keine 4500+ Hits.
