### ISSUE TITLE
[Herbs] Kraut unter der Welt / Erde + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1085]
In den verwüsteten Landen ist ein Gromsblut auf ca. 10 Uhr des Kraters, das nicht abbaubar ist.

Folgender Fix setzt das Kraut 5 Meter nach oben, an die Erdoberfläche ;)
Fix
```sql
UPDATE gameobject SET position_z = 11.50 WHERE guid = 32304;
```

**Comment by hraesvelgr** [comment]
aber das ist doch blizzlike?

**Comment by dagochen** [comment]
Wirklich? Quellen, dass das Kraut oberhalb sein sollte habe ich mir nicht geben lassen, dachte das wäre selbstverständlich in so einem Fall. Wenn jemand was gegenteiliges hat, schließe ich das hier.

**Comment by hraesvelgr** [comment]
ich meine dass da was war, mit diesem einen verfluchten gromsblood. aber da ich keine handfesten quellen ahb, und es in der hinsicht eh sinnlos ist, dass man  es nicht sammeln kann....halt ich mal die klappe :)

**Comment by Sheed90** [comment]
Es handelt sich offensichtlich um einen Bug, sollte also auch gefixed werden.
