### ISSUE TITLE
[Alteractal] Drek'Thars & Kriegsmeister der Icebloodtruppen Linked

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1086]
Momentan sind diese beiden NPC´s linked und somit nicht einzeln pullbar außer durch deinen Hunter.

Dieser Link sollte entfernt werden oder diesen Link bei Vandar + Marshall hinzufügen.

Drek http://datenbank.welli-it.de/?npc=11946
KM Iceblood http://datenbank.welli-it.de/?npc=14773

**Comment by dagochen** [comment]
Was denn nun? Entfernen oder hinzufügen?

**Comment by g3n3a** [comment]
Sollte entfernt werden
Aus den 2.3.0 Patchnotes (http://wowwiki.wikia.com/wiki/Patch_2.3.0):
All Warmasters are linked to each other and their respective Generals and can no longer be pulled individually. 

Impliziert, dass man sie vorher einzeln pullen konnte.

**Comment by Dotox** [comment]
Ich hab das vorhin mal geprüft und bin mir sicher, dass man die damals schon auf keinen Fall einzelnd pullen konnte. Deshalb musste man die Türme und Gebäude zerstören, damit die despawnen.

"Tied to their general, Marshals cannot be pulled separately from Vanndar." Das gleiche gilt auch für Drek.

http://wowwiki.wikia.com/wiki/Marshal?oldid=1016127

**Comment by hraesvelgr** [comment]
also ist der bug, dass  die durch die kaputten türme nicht despawnen?

**Comment by Dotox** [comment]
Es sieht so aus ja. Ich prüf das mal auf dem Testserver - verlinkt müssen die Npc's aber schon sein, keine Ahnung warum da was in dem Patchnotes von 2.3 stand. Eventuell ein Bug, der sich davor irgendwann mal eingeschlichen hat.

**Comment by Loplin** [comment]
also, sollten alle Türme zerstört sein, dann stehen bei Drek noch 2 Kriegsmeister.
Der linke davon ist einzeln pullbar

**Comment by Larnak1** [comment]
Bei Vanndar stehen immer 
Westmarschall: http://datenbank.welli-it.de/?npc=14769
Ostmarschall: http://datenbank.welli-it.de/?npc=14768
Marschall der Eisbluttruppen: http://datenbank.welli-it.de/?npc=14766

Verschwinden mit ihren jeweiligen Türmen tun korrekt:
Südtruppenmarschall: http://datenbank.welli-it.de/?npc=14763
Nordtruppenmarschall: http://datenbank.welli-it.de/?npc=14762
Eisschwingenmarschall: http://datenbank.welli-it.de/?npc=14764
Steinbruchmarschall: http://datenbank.welli-it.de/?npc=14765

Die ersten drei lassen sich einzeln pullen. Bei den anderen kann ich nur sagen, dass der Eisschwingenmarschall gelinkt ist, weil der relativ oft noch steht. Die anderen habe ich noch nicht live erlebt. Außerdem sind die ersten drei vergleichsweise harmlos, ein fieses Spalten macht, was eigentlich alles umhaut, was in der Nähe ist. Keine Ahnung ob das so soll oder ob das der gleiche Fehler wie bei Drek'Thar ist. Das macht nämlich auch das Erobern des Eisschwingenbunkers enorm schwer, weil der Typ dort auch rumsteht.

**Comment by Dotox** [comment]
Danke @Larnak1. Hier liegt tatsächlich ein großer Fehler im gesamten Spawnsystem von AV vor. Ich hab heute damit begonnen, das System zu beheben. Kann allerdings einige Tage dauern. Melde mich dann wieder!

**Comment by g3n3a** [comment]
"also, sollten alle Türme zerstört sein, dann stehen bei Drek noch 2 Kriegsmeister.
Der linke davon ist einzeln pullbar"

Sollten alle Türme zerstört sein und keine Bunker, sollten keine KMs bei Drek stehen. Sollten alle Türme und Bunker zerstört sein, stehen 4 KMs bei Drek.
Das hab ich alles schonmal vor Ewigkeiten in den Bugtracker geschrieben. Geändert hat sich da wenig.

**Comment by Larnak1** [comment]
Ah, jetzt verstehe ich das System :D Ok, dann kann es schon sein, dass die ersten drei korrekt gespawnt werden, wenn die Allianz Türme zerstört. Die sind meistens schon kaputt, wenn wir da sind und ich hab da leider nie genauer drauf geachtet.
