### ISSUE TITLE
götze der unmenschlichkeit loottable

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1087]
http://datenbank.welli-it.de/?item=23198 sollte nur bei magistrat barthilas (http://datenbank.welli-it.de/?npc=10435) droppen

momentan ist es ein random world drop.

**Comment by ircfelix** [comment]
quelle?

**Comment by hraesvelgr** [comment]
naja, seit wann droppen items, die nur bosse droppen random irgendwo in der welt? ist nunmal ein bossdrop, das sagt schon ein blick in atlasloot.

**Comment by dagochen** [comment]
Quellen
https://web.archive.org/web/20070427015711/http://www.thottbot.com/i23198
https://web.archive.org/web/20070216131839/http://wow.allakhazam.com/db/item.html?witem=23198

Die Quellen sprechen auch dafür, bei allen andern ist die Chance 0,001%. Vermutlich fehlerhaftes tracking damals.

**Comment by hraesvelgr** [comment]
http://wowwiki.wikia.com/wiki/Idol_of_Brutality

drops from magistrate barthilas.
