### ISSUE TITLE
Bewegungstempo von den Knochenkonstrukten ist zu schnell

### ISSUE THREAD

**Issue by fearon1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1088]
In Phase 3 von Nefarian erscheinen die Knochenkonstrukte.
http://datenbank.welli-it.de/?npc=14605
Deren Bewegungstempo ist allerdings zu schnell. Teilweise haben diese bis zu geschätzten 500% Movementspeed.

Hier ein Link vom Offi Server.
https://www.youtube.com/watch?v=V5CYef3QVwk

Von unserem Server habe ich bisher noch kein Video gemacht, kann dieses nach Bedarf aber nachreichen.

**Comment by Dotox** [comment]
Ja, pack das Video von Nefarian noch mit rein.

**Comment by Gnomorus** [comment]
Bevor hier was geändert wird: In dem Classicvideo sieht man nur für ne halbe Sekunde oder noch weniger die wirkliche Geschwindigkeit der Konstrukte (und zwar genau dann, wenn sie von links in das Bild rein laufen), dann werden sie schon verlangsamt.
Nicht verlangsamt sind diese auch ziemlich flink. Von daher sollte, wenn überhaupt eine Reduzierung vorgenommen wird, diese nur minimal ausfallen.

**Comment by fearon1** [comment]
Und hier das Video: http://www.vidup.de/v/Mjk13/
Wie man sehen kann, haben die Konstrukte zeitweise 200% Laufspeed, was auch so korrekt ist. Doch regelmäßig legen sie einen "Turbo" ein, wenn sie dem Aggrohalter näher kommen. In diesem Video bzw. bei diesem Nefkill ist dieser Tubro nur einmal kurz. Bei anderen kämpfen sprinten die Konstrukte teilweise komplett in dem Tempo durch den Raum. Für das Abfangen ist dies suboptimal und für 1-2 Healer häufig tödlich.

**Comment by Dotox** [comment]
Ohne das Video gesehen zu haben weiß ich, dass es das beschriebene Problem gibt. Es kommt selten vor, aber wenn, dann ist es ziemlich nervig.
