### ISSUE TITLE
[Schurke] Noggenfoggers Elixier

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1089]
Sobald man als Schurke den Effekt "Ihr fühlt euch leicht" erhält, und los läuft stürzt WoW ab! Bei anderen Klassen funktioniert es wunderbar.

Mögliche Ursache könnte die Fähigkeit "Sicheres Fallen" sein.

Sicheres Fallen http://datenbank.welli-it.de/?spell=1860
Noggenfogger http://datenbank.welli-it.de/?item=8529
Leichter Fall http://datenbank.welli-it.de/?spell=16593

**Comment by Dotox** [comment]
Können das weitere Schurken bestätigen?

**Comment by gsiani** [comment]
Habe das selbe Anliegen.

**Comment by Ilikegyoza** [comment]
Ich habe nun mit einigen geschrieben und alle haben das selbe Problem.

**Comment by Slipru** [comment]
Kann ich auch bestätigen.

**Comment by Dotox** [comment]
Konnte das auf dem Testserver leider nicht reproduzieren. Crasht der Client oder wirst du einfach nur vom Server gekickt?

**Comment by godlike321** [comment]
Ich kann diesen Fehler jederzeit mit fallschirmumhang, noggenfogger, levitieren und halloween-süßigkeiten reproduzieren.

Meiner Beobachtung nach buggt es bei allen Arten von leichter fall/schweben und nur beim UD Rogue.

**Comment by godlike321** [comment]
passiert hier noch was ?

wie gesagt, würde mich für ein paar kurze tests, auch auf dem testserver gerne beriet erklären

**Comment by Dotox** [comment]
Mach mir am besten mal ein Video, ohne Ausrüstung

**Comment by Haudraufinix** [comment]
Habe ein ähnliches verhalten festgestellt. Wenn ich mit meinem Untoten Schurken oder meinem Mensch Paladin (15movespeed NICHT geskillt) und dem Slowfall buff von Noggenfogger kleine Bodenunebenheiten herunterlaufe werde ich nach oben zurückteleportiert, falle 2-3 mal wieder herunter und werde dann vom anti Speedhack tool gekickt
