### ISSUE TITLE
[Arathibecken] Wiederbelegung an getappten Basen

### ISSUE THREAD

**Issue by lysethea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1092]
istzustand:
bei tap einer base im AB wird man nicht mehr zum nächstgelegenen FH geportet

sollzustand: 
nach dem tap sollte man zum nächstgelegenen FH geportet werden

das ist seit dem letzten Patch so auf Seiten der Allianz. Wie es bei der Horde aussieht weiß ich nicht.

**Comment by Dotox** [comment]
Das ist bekannt, da die Mechanik davor zu dauercrashes geführt hat.
