### ISSUE TITLE
Spielmechanik vom Retripaladin

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1093]
Erst mal vorab, ich bin nicht hier, um euch zu ärgern und ich bin auch nicht hier, um mich von geistig Zurückgebliebenen blöd anmachen zu lassen. Sondern ich bin hier, weil ich WoW angefangen habe zu spielen, da waren die meisten hier wahrscheinlich gerade 10 Jahre alt, wenn überhaupt. Und ich war damals schon älter als ihr wahrscheinlich jetzt seid.

Ich kenne natürlich eure Motivation nicht exakt, warum ihr das hier betreibt, weiß ich nicht. Dafür gibts mehrere Möglichkeiten, allerdings bezweifle ich, dass ihr das macht, weil ihr das Spiel spielen wollt, zum Beispiel. Ihr wollt zum Beispiel, dass ich das Spiel spiele oder ihr wollt euch mit der Programmierung beschäftigen, mit dem Aufbau eines Servers usw. vielleicht studiert ihr das ja, weiß ich nicht. Allerdings habe ich ne andere Motivation und ich habe als Spieler auch ne gewisse Erfahrung, die ihr nicht habt. Es wäre also schön, wenn man mir mal zuhören würde und mal darüber nachdenken würde, was ich hier sage.

Und ich muss euch auch keine Spielmechanik beweisen, an die sich kein Mensch mehr erinnern kann, die vor 10 Jahren aktuell gewesen ist. Niemand weiß wie exakt die Spielmechanik damals funktioniert hat, außer eventuell die damaligen Programmierer, falls es die noch geben sollte. Ihr könnt mir auch nicht beweisen, dass eure Spielmechaniken richtig sind. Beweist mir das doch, wo sind denn eure Videobeweise. Dann bin ich sofort still, wenn ihr mir das beweisen könnt.

Ich kann nur sagen, dass ich damals und während ich WoW gespielt habe und das war in jedem AddOn einige Monate lang bis MoP, dann habe ich aufgehört, Vergelter gespielt habe. Also ich verbinde etwas mit dieser Klasse und habe eine gewisse Erfahrung damit. Und mit dem Spiel im Allgemeinen, das heißt nicht, dass ich mit allem Recht haben muss, aber das hat sowieso niemand, allerdings sollte man sich das genauer ansehen und anhören, was ich zu sagen habe. Weil das wichtig ist.

Vor einigen Jahren habe ich das erste Mal auf eurem Server gespielt und ich bin der Auffassung, dass damals bestimmte Spielmechaniken des Vergelters richtiger gewesen sind als aktuell. Und zwar wenn der Vergelter geblockt hat, hat er in der Regel gleichzeitig gekontert. Das kam mir sehr richtig vor, vom Gefühl her, auch wenn ich es natürlich nicht beweisen kann, weil ich vor 10 Jahren keine Videoaufzeichnungen gemacht habe. Ich rede hier von meinem Gefühl als Spieler, der das Spiel fast 10 Jahre lang mit langen Pausen gespielt hat. Das war eine Sache, die war richtiger. Das Siegel des Befehls hatte damals richtig reingehauen. Also da konnten sozusagen Kettenreaktionen geschehen. Das ist heute nicht mehr der Fall, was sich sehr schlecht anfühlt und sehr langweilig. Der Vergelterpaladin war zwar als Schlappschwanz verpönt, aber sein PRoblem war im PVP! eigentlich nicht so sehr, dass er keinen Schaden gemacht hat, sondern, dass er schnell kein Mana mehr hatte. Und dann war das Duell vorbei gegen fast jede Klasse. Außer den Krieger, den hatte der Vergelter immer geschafft, durch seine Schilde und Heilfähigkeiten. Und heute ist es so, dass Siegel des Befehls ne scheiß, langweilige Fähigkeit ist. Ich glaube nicht, dass das so gewesen ist. Ich glaube, dass das vor zwei Jahren besser gewesen ist und richtiger. Und ihr habt den Server ja auch nicht ursprünglich programmiert, sondern das waren ja andere Leute und die hatten sich ja offensichtlich auch n bisschen was dabei gedacht.

Im Moment sehe ich irgendwie nicht, warum der Vergelter mir damals Spaß gemacht haben soll. Vor zwei Jahren war das anders. Da hat er schon manchmal richtig schön reingehauen.

Darüber hinaus ist es so, dass wenn der Vergelter einen Kälteeffekt abbekommt, aufeinmal seine Angriffsanimation abbricht und in eine Animation übergeht, wo er nicht angreift, auch wenn er danach weiter angreift, ist das eine Verzögerung, weil die Animation jedes Mal neu starten muss. Und das nervt. Manchmal macht das Richturteil auch keinen Schaden. WArum weiß ich nicht. Vielleicht denkt er intern, das ist Siegel des Kreuzfahrers oder Ähnliches, behandelt es so, obwohl es eigentlich Schaden machen soll, aber wie gesagt ich steige durch den Programmiercode nicht durch, für mich sind das einfach nur irgendwelche Funktionen und ich habe den Verdacht, dass man das nur wirklich verstehen kann, wenn man verstanden hat wie der Server und der Client miteinander kommunizieren und ich bin kein Profi, ich kann zwar ein AddOn programmieren und bin ziemlich intelligent, aber das übersteigt nicht meine Fähigkeiten, aber das Wissen, das ich darüber habe bei Weitem, wenn ihr das könnt schön für euch, also daran müsste definitiv auch mal gearbeitet werden. Wenn ihr das durchblickt, was da Sache ist.

Nee andere Sache ist, ich betäube manchmal weil ich den vollen Schaden machen möchte mit Siegel des Befehls und dann schlägt er einfach nicht zu. Er wartet und wartet und wartet bis die Betäubung dabei ist und dann schlägt er vielleicht zu, vielleicht gerade gleichzeitig. Das kann nicht stimmen, dass er manchmal so lange braucht bis er zuschlägt. Ich weiß nicht, ob da intern irgendwelche Schlagtimer zurückgesetzt werden wenn ich Hammer der Gerechtigkeit verwende, aber das fühlt sich falsch an. Ich denke mir immer Junge, nu schlag doch mal zu, aber der tut mir den Gefallen nicht. Ich denke, dass wenn ich Hammer der Gerechtigkeit verwende, der Schlagzeit sozusagen eigentlich gestoppt werden müsste und wenn die Betäubung stattgefunden hat, geht die Schlagzeit weiter. Irgendwas stimmt da nicht. Irgendwas ist da nicht richtig.

Und zu guter Letzt habt ihr behoben, dass wenn ich Hammer der Gerechtigkeit benutze, die Gegner nicht plötzlich zum nächsten Verbundeten teleportieren, das habt ihr gut gemacht, aber die laufen nach der Betäubung immer wieder ein paar Meter zurück, also das SToppen der NPCs und die tatsächliche Position, wo sie gestoppt haben, stimmt irgendwie nicht überein, irgendwas ist da falsch - mathematisch. Irgendwas wird da nicht richtig berechnet.

Und wenn ihr das alles korrigieren würdet, dann wäre der Paladin sehr, sehr gut im PvE, würde mir Spaß machen, vom Gefühl her. Dass euer PvP total fehlerhaft ist, ja gut interessiert hier sowieso keinen, weil ja eigentlich kein PvP stattfindet, aber früher war das so, dass Können im PvP ne große Rolle gespielt hat. Die Balance war schlecht, allerdings immer noch besser als alles, was nach WotLK kam. Dennoch kam es auf Können an, bei euch im Moment im PvP, da kommt es nur darauf an, welche Klasse solche Fehler hat, die für PvP von Vorteil sind. Offensichtlich ist das auch nicht so leicht, das richtig hinzubekommen.

Und damit ihr jetzt nicht rumheult, sage ich euch auch gerne, dass der Server Nostalrius oder wie der heißt, obwohl er vielleicht tatsächlich 6 Mal mehr Spieler hat als ihr, der eindeutig schlechtere Server ist, also ihr seid insgesamt fehlerfreier, falls euch das irgendwas bedeutet, aber ich bin nicht hier, um euch Zucker in den Arsch zu blasen und das aufzuzählen, was ihr alles gut macht oder was funktioniert, das nehme ich so hin, mich interessiert das, was nicht funktioniert, wo man was verbessern kann.

**Comment by hraesvelgr** [comment]
wow, nach deiner lebens- und leidengeschichte hast du ganze 2 fehler genannt.

tl;dr: portbug nach CC und reset der AA-animation. und die sind bereits gemeldet. 
 
!vote close.
