### ISSUE TITLE
schwarze perle/lootbug

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1094]
die schwarze perle (http://datenbank.welli-it.de/?item=7971) sollte nur aus truhen, wasserkreaturen oder muscheln droppen. (evtl ist das ein problem mit allen perlen? bin mir da nicht so sicher, beid er schwarzen aber ganz sicher)
sie sollte ausserdem aus allen juwelenbeuteln der drachen (ony, worldbosse) sowie aus den kronjuewelen von thaurissan und den juwelenbeuteln aus dem vault in brd droppen. 

momentan ist sie ein random world drop.
(hab sie bei erdelementaren mitten in der wüste gefunden, kann mir keiner erzählen dass die muscheln zum frühstück hatten...)

http://wowwiki.wikia.com/wiki/Black_Pearl
http://wow.allakhazam.com/forum.html?forum=69&mid=1106423169535755121

**Comment by dagochen** [comment]
Laut dieser Quelle sind es aber schon recht viele Mobs, die das droppen können: http://web.archive.org/web/20060415095243/http://wow.allakhazam.com/db/item.html?witem=7971

Da rauszusuchen, bei welchen es nicht droppen soll und bei welchen schon, ist vermutlich recht viel Recherche und Fummel Arbeit @hraesvelgr . Wenn du mir sagst welche genau aus unserer Datenbank es nicht droppen sollen, dann kann ich damit was anfangen.

**Comment by hraesvelgr** [comment]
naja, man kann theoretisch alle dämonen rausstreichen, von anfang an. was ich mich frage, ist, warum npc-minions, oder auch beschworene diener der npc erz und kräuter droppen. 

8996
8716
6202
2791
8905
11783
2817
2852
15206
4096
504
595
979
1561
1729
2255
2574
2583
2701
2715
2718
2793
4467
4648
4663
5232
5238
5269
5615
5616
5618
5632
5443
5974
6199
7246
11793
36
6147
1488
1791
6116
6117
7861
2850
1809
1551
2043
2659
2680
5286
5268
2926
5307
5308
5856
8761
11741
5423

das wäre jedenfalls die liste der NPC, die das item schwarze perle NICHT(!) droppen sollten, aber laut datenbank dies momentan tun.
