### ISSUE TITLE
Weitere Fehler beim Paladin

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1096]
Erst mal die Anzeigefehler. Aura der Vergeltung macht Heiligschaden und der wird gelb dargestellt. Mit gelben Zahlen, nicht mit weißen Zahlen. Weiße Zahlen stehen für körperlichen Schaden.

Nächster Fehler bei Siegel der Rechtschaffenheit gibt es keine Möglichkeit zu widerstehen. Wenn er trifft, macht er 100%ig den heiligen Schaden. Bei euch kann es widerstehen, was totaler Schwachsinn ist. Es sei denn wir befinden uns im PvP und ein Alchemist hat einen Trank, der Heiligschaden absorbieren kann. Das ist auch die einzige Möglichkeit oder die Worgen in Burg Schattenfang, die sich gegen Heiligschaden immun machen können.

Beim Siegel des Befehls ist es bei euch so, erst wird der Heiligschaden angezeigt, dann der körperliche Schaden. Das muss umgekehrt sein. Zuerst wird der körperliche Schaden gemacht und dann der Heiligeschaden. Und dem Heiligschaden kann man weder parieren noch ausweichen noch widerstehen. WEnn der körperliche Schaden gemacht wurde und der Effekt von Siegel des Befehls ausgelöst wurde, dann macht das Ding auch zu 100% Schaden.

Dann ein allgemeiner FEhler wenn ein Jäger in meiner Nähe ist, dann erhalte ich seine Fähigkeit zum Beispiel andere NPCs auf der Karte zu sehen, selbst wenn ich nicht in seiner Gruppe bin.

Auch wenn es vielleicht nicht so rüber kommt - für euch - aber ich mag euren Server wirklich und ihr habt auch gute Sachen gemacht - wie zum Beispiel, dass man nicht von jedem angegriffen wird, als hätte man gleiches Level. Das habt ihr gut gemacht. Euer Server ist auch sehr stabil. Ich will euch hier nicht fertigmachen oder so. Wenn ihr das glaubt, dann habt ihr ein PRoblem und nicht ich. Ich bin lediglich daran interessiert, das optimale Spielerlebnis zu haben. Deswegen erzähle ich euch das. ich hab euch gestern beispielsweise im Welt-Kanal verteidigt - euren Server, weil da jemand behauptet hat, dass Nostalrius besser wäre, was Schwachsinn ist. Das Einzige was besser ist, dass dort ab und an PvP aufgeht, alles andere ist schlechter. Ihr seid fast in allem besser als die, aber die haben gute Werbung gemacht und offensichtlich viele LEute auf Youtube aus den USA erreichen können. Das ist der einzige Grund, warum die eventuell wirklich so viele Spieler haben.

Leider ist PvP bei euch vollkommen tot, aber das liegt eben auch an den Spielern. Obwohl das mit den Abzeichen habe ich irgendwie anders in Erinnerung. Ich hab das so in Erinnerung, dass ich für meine Gegenstände Abzeichen benötigt habe. Aber ich muss gestehen, ich habe Klassik nur bis Level 58 oder so gespielt, dann hatte ich die Schnauze voll und PvP habe ich, glaube ich, erst so richtig BC gespielt und die Spielmechanik hatte ich damals auch nicht 100%ig verstanden gehabt, weil ich ein Anfänger gewesen bin und es noch keine Anleitungen gegeben hat wie man seine Klasse am besten spielt. Deswegen vielleicht war das damals tatsächlich so beschissen. Und zwar ist es deshalb beschissen, weil man die Rufanforderungen ja praktisch gar nicht erreichen konnte. Weil auch damals hat es ungefähr 10-30 Minuten gedauert bis mal ein BG aufgegangen ist, im Niedriglevelbereich. Also den Ruf, der dafür notwendig ist, niedrige Gegenstände zu holen, konnte man sich gar nicht erspielen, alleine von der Zeit war das gar nicht möglich. Aber wie gesagt vielleicht war das damals ja wirklich so scheiße. Aber so oder so würde vermutlich keiner spielen. Was ich sehr schade finde, weil ich eigentlich immer ein PvP-Spieler war. Ich habe auch gerne gelevelt, die Welt erforscht und meine Ausrüstung verbessert, aber wenn das gemacht war, war es gemacht.

Die Idioten bei WoW haben es eigentlich versäumt ein PvP-System zu etablieren, das für alle eine faire Möglichkeit bietet. Stattdessen haben sie eigentlich seit spätestens MoP PvP komplett aus dem Spiel genommen. Das ist der FEhler generell bei den sog. MMOs, dass viel zu wenig Wert auf PvP gelegt wird. Wenn die nicht so bescheuert wären, könnten die viel mehr Kunden habe. Aber bei euch spielen leider nicht so viele bzw. es spielen nicht so viele PvP. Das ist eigentlich der Hauptmangel auf eurem Server. WEnn ihr den irgendwie beheben würdet, dann würde ich das als ein klassikähnliches Produkt bezeichnen, aber gut PvE ist natürlich ordentlich, aber ohne PvP fehlt natürlich die Hälfte im Spiel. Insbesondere für mich. Und da hilft mir einmal die Woche ein 10-Minuten Alteractal mit fehlerhafter Spielmechanik auf Maximallevel auch nicht weiter.

**Comment by ircfelix** [comment]
Wie findet Ernie die Technikergruppen in Bwl?
