### ISSUE TITLE
leibwache des propheten

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1100]
die eskorte des propheten (http://datenbank.welli-it.de/?npc=15308), welche aus 4 npcs (http://datenbank.welli-it.de/?npc=11880 ?) besteht, führt keine aktionen mehr aus, wenn der prophet tot ist. sie stehen einfach nur rum, teilweise kann man sie nicht mehr ins ziel nehmen. wenn man sie ins ziel nehmen kann bewegen sie sich nicht vom fleck, greifen aber noch an wenn man nah genug kommt. 

alles in allem verhalten sie sich sehr buggy, wenn der prophet tot ist.

**Comment by dagochen** [comment]
Kann ich bestätigen. Hab den Fehler mir auch schon angeschaut, liegt vermutlich an der GroupFormation und dem Verhalten der NPCs. Außerdem sollten die zusammen spawnen und weiterlaufen, was aktuell auch noch nicht der Fall ist. Leider konnte ich den Fehler bisher nicht fixen :( Daher hab ich das noch nicht eingetragen gehabt^^
