### ISSUE TITLE
[Warlock -Sukkubus] Manakosten v. Seduce zu hoch / Manaregeneration zu niedrig

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1101]
**Welches Verhalten wird beobachtet?**

Seduce: http://datenbank.welli-it.de/?spell=6358
Die Manakosten für Seduce kosten 24% Basemana von der Sukkubus. Die Sukkubus hat einen Manapool i.H.v. 1.874. Davon 24% = 449 Mana pro Seduce.

(Datenbank und Manakosten auf dem Server stimmen überein. Wenn man sich aber unten die Videos anschaut, können diese 449 Mana nicht stimmen) 

Manaregeneration:
Die Sukkubus regeneriert momentan 35 Mana alle 5Sek.

**Wie sollte es sich verhalten?**
 Seduce: Die Manakosten für diesen Zauber sollten 362 betragen.
 Manaregeneration: Die Sukkubus sollte alle 5 Sekunden zwischen 99 und 100 Mana regen.

**Quellen**:
  **Drakedog** (0:39-0:57) https://www.youtube.com/watch?v=IJIJLBqSAkY&t=32

  Manapool Succubus  1.874
  1.874 ./. 362 (Seduce) = 1.512 + 100 Mp5 + 99 Mp5 = 1.711 ./. 362 (Seduce)= 1.349 + 100Mp5 + 99   Mp5 = 1.548

   **Lokilo**  (04:52–05:11) https://www.youtube.com/watch?v=kncLlUyTcjQ&index=4&list=PLnW2DXVj2M_QlnPVCZpoVXm2YV5fZ2wK8

 Manapool Sukkubus 1.874
  1.874 ./. 362 (Seduce)= 1.512 + 100Mp5 = 1.612 ./. (Seduce) 362 = 1.250 +99 Mp5 =1.349

**Comment by ircfelix** [comment]
Deine Rechnung mit 100 mp5 die vom Himmel fallen ist nicht nachvollziehbar.

**Comment by 0815Priester** [comment]
warum?

**Comment by Armauskugelbob** [comment]
Das hier sind ja nicht direkt Rechnungen, sondern soll eine Art Timeline darstellen wie sich der Manapool der Sukki während des Kampfes verändert.

**Comment by ircfelix** [comment]
Aaaah!

**Comment by 0815Priester** [comment]
@dagochen 

Frage: Könnte man "wenigstens" den Manareg bei der Sukkubus anheben? Ich denke die Videos zeigen eindeutig das der Manareg bei uns nicht stimmt.

**Comment by dagochen** [comment]
Das 2. Video ist privat und kann ich leider nicht sehen. Bei dem anderen sieht man zwar die höhere Manaregeneration, aber ehrlich gesagt kann das auch jeder chinesische Privatserver der Welt sein. Ich hör mich mal um bei den cmangos Leuten, ob die da mehr wissen.

**Comment by 0815Priester** [comment]
Danke!
Hab noch eins gefunden.
http://www.warcraftmovies.com/movieview.php?id=19304

**Comment by dagochen** [comment]
Ok danke da sieht man es ja genau. Man könnte für Pets die Regen anpassen. Damit es aber dann auf allen Levels passt und nicht für andere Pets falsch ist, wäre es gut wenn wir mehr Werte für verschiedene Level und verschiedene Pets hätten. Könnt ihr da noch mal weiter recherchieren bitte?

**Comment by 0815Priester** [comment]
Moin,

als ich damals den Bugreport erstellt habe, habe ich wirklich viel Zeit in die Recherche investiert. Ich habe nichts aber auch wirklich nichts im Netz gefunden. Weder auf EliteJerks noch in irgendwelche anderen Foren konnte ich herausfinden, wie hoch der Manareg der verschiedenen Pets ist. Auch in den Bugtrackern bei anderen Classic Servern gibt es keine valide Quellen - außer Videos von damals.

Ich befürchte das die Informationen was Manareg/Dmg der Pets betrifft einfach verloren ist. Die einzige Hoffnung die ich noch habe ist, dass du noch über die cmangos leute irgendwas herausfindest.

Grüße

**Comment by dagochen** [comment]
Ja die cmangos Leute wissen von dem Bug und haben den auch aufm Zettel, aber grad keine Zeit/Lust dafür :( 

Klar, man kann die Formel jetzt ändern, aber ich möchte ungern ins Blaue schießen und dann ein anderes Pet damit so viel stärker machen, dass es abused wird in irgendeiner Art und Weise. Kann man auf Videos vllt den Wert von dem Wichtel für Level 60 sehen? Oder irgendein anderes Pet vom Warlock das Mana regeneriert auf irgendeinem Level?

**Comment by 0815Priester** [comment]
*Felhunter Manareg: 108 und 109*

Drakedog 1 Upload 25.04.2005
https://gamefront.online/files/3848814/drakedog.wmv
(Wenn man das Video downloaded erkennt man die Zahlen beim Felhunter gut)

Manapool Felhunter 
1383 + 109 (Manatick) = 1.492 ./. 215 (Devour Magic Rank 4) = 1.277 + 108 (Mantick) =1.385

Das der Felhunter einen höheren Manareg hat als die Sukkubus kann man in diversen Foren nachlesen.
Den stärksten Manareg sollte der Imp haben aka Manabattery i.V.m. Dark Pakt. Ich suche weiter.
