### ISSUE TITLE
Würgetang in Darkshore

### ISSUE THREAD

**Issue by markthetechie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1104]
Welches Verhalten wird beobachtet?
Massen an Würgetang am Strand von Darkshore und dort an Land anstatt im Wasser

Wie sollte es sich verhalten?
Würgetang wächst unter Wasser und in angemessenen Mengen

Schritte zur Reproduzierung
Von Auberdine aus einen Strandspaziergang richtung Süden unternehmen

Kann es sein, dass es allgemein ein Problem mit den Ressourcen in Darkshore gibt? Ich bin das ganze Gebiet einmal abgelaufen und habe kein einziges Kupfervorkommen gefunden.

**Comment by Loplin** [comment]
An der Küste von Ashenvale is noch mehr würgetang.
Denke das liegt daran das das dort nie jemand abbaut, und viel zu viele Spawnpunkte gleichzeitig aktiv sind

**Comment by markthetechie** [comment]
Mittlerweile bin ich ziemlich sicher, dass auch mit dem Kupfererz etwas  nicht stimmt.... noch weitere 2std gestern durch Darkshore gestromert, alle Moonkinhöhlen, die Nagahöhlen, die gesamten Berghänge nach Felwood hin, den gesamten Strand und quer alle möglichen Wege durch die Wälder abgesucht und kein einziges Kupfererz gefunden. 
Pflanzen ohne levelbeschränkung (also peasebloom und silverleaf) hingegen hab ich auch ohne kräutersuche massig gefunden.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/694
