### ISSUE TITLE
Ice Cold Milk - Cooldown 1min

### ISSUE THREAD

**Issue by FlashFire90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1108]
Die Milch löst nen cd von einer minute auf sich selbst und alle anderen manareg getränke aus, durchaus nervig, wenn man in dem levelgebiet am reggen ist, kurz aufstehen muss und danach noch 30-40seks warten muss, um wieder etwas trinken zu können

**Comment by hraesvelgr** [comment]
kann ich nicht bestätigen. hab grad ein stack kalte milch durchgeknallt, innerhalb von wenigen sekunden. 

bei diesem test wurden keine paladine zu testzwecken missbraucht.

**Comment by FlashFire90** [comment]
also ich habs als undead priest geused, evtl nur bei denen nen cd?^^

**Comment by hraesvelgr** [comment]
alle addons ausgemacht und mal den wdb gelöscht?

**Comment by FlashFire90** [comment]
das ganze lag in der tat am wdb ordner also solved :)
