### ISSUE TITLE
Hillsbrad Rathaus

### ISSUE THREAD

**Issue by FlashFire90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1110]
der amtmann und der magistrat in hillsbrad fields respawnen viel zu schnell (zwischen 20 und 30 sekunden), dadurch kann man bei der quest eigentlich nur sterben 
http://datenbank.welli-it.de/?npc=2448
http://datenbank.welli-it.de/?npc=2335

**Comment by hraesvelgr** [comment]
bitte mal das readme lesen:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker
