### ISSUE TITLE
höhlenmutter link + falscher spell.

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1112]
die höhlenmutter in dunkelküste nutzt den spell "ravage" nicht, dafür machen das all ihre begleiter. es sollte allerdings andersrum sein (sonst ist man dauerhaft im stun)

ausserdem sollten alle npcs in der höhle verlinkt sein.

höhlenmutter: http://datenbank.welli-it.de/?npc=6788
bärenjungen: http://datenbank.welli-it.de/?npc=6789
spell ravage: http://datenbank.welli-it.de/?spell=3242

http://www.wowhead.com/quest=2139/tharnariuns-hope#comments:id=65502

**Comment by hraesvelgr** [comment]
frage: in den patchnotes hast du geschrieben, dass die mutter GENAU SO wie ihre kinder den spell jetzt nutzen. heißt, alle bären (kinder und mutter) benutzen den jetzt?

**Comment by dagochen** [comment]
Ja.

**Comment by hraesvelgr** [comment]
das ist eben falsch. hab ja geschrieben dass es andersrum sein soll: also quasi NUR die mutter den spell haben. denn sonst hat man jetzt 5 npcs auf einem, die einen aller 0,5 sekunden stunnen. ohne diminishing return. kannst dir ja denken wie der kampf ausgeht :^)

nur die mutter sollte den spell ravage besitzen, nicht die kleinen.

**Comment by hraesvelgr** [comment]
das ist eben falsch. hab ja geschrieben dass es andersrum sein soll: also quasi NUR die mutter den spell haben. denn sonst hat man jetzt 5 npcs auf einem, die einen aller 0,5 sekunden stunnen. ohne diminishing return. kannst dir ja denken wie der kampf ausgeht :^)

nur die mutter sollte den spell ravage besitzen, nicht die kleinen.
