### ISSUE TITLE
richturteile und resists

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1113]
wie es ist:
alle richurteile die einen debuff auslösen können resistet werden. das ist ein fehler.

wie es sein soll:
die richturteile die einen debuff auslösen sollten auf keinen fall resistet werden können (auch nicht von den heilig-resistenten elementaren die ich so nervig finde)

>Judgements - Judgements that place a debuff on their victim will now all have their duration refreshed when the judging paladin strikes the victim with his or her melee swings. All these debuffs have had their duration decreased to 10 seconds. In addition, Judgements that place debuffs can no longer be resisted. 

patch 1.9.0 (gates of ahn quirai)
http://wowwiki.wikia.com/wiki/Patch_1.9.0

diese richurteile sind:

richturteil des lichts: 
rang 1 http://datenbank.welli-it.de/?spell=20185
rang 2 http://datenbank.welli-it.de/?spell=20341
rang 3 http://datenbank.welli-it.de/?spell=20342
rang 4 http://datenbank.welli-it.de/?spell=20343

richturteil der weisheit:
rang 1 http://datenbank.welli-it.de/?spell=20268
rang 2 http://datenbank.welli-it.de/?spell=20352
rang 3 http://datenbank.welli-it.de/?spell=20353

richurteil der gerechtigkeit: 
http://datenbank.welli-it.de/?spell=20184

richturteil des kreuzfahrers:
rang 1 http://datenbank.welli-it.de/?spell=21183
rang 2 http://datenbank.welli-it.de/?spell=20188
rang 3 http://datenbank.welli-it.de/?spell=20300
rang 4 http://datenbank.welli-it.de/?spell=20301
rang 5 http://datenbank.welli-it.de/?spell=20302
rang 6 http://datenbank.welli-it.de/?spell=20303

richturteil base-spell:
http://datenbank.welli-it.de/?spell=20271 (sollte in kombination mit siegel der weisheit/des lichts/des kreuzfahrers/der gerechtigkeit nicht resistbar sein)
-------------------------------------------

Ps was hat es eigentlich mit diesen dummy-spells auf sich? zb das: http://datenbank.welli-it.de/?spell=1826

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875

**Comment by hraesvelgr** [comment]
oh..verdammt  sry^^

**Comment by hraesvelgr** [comment]
btw, sabbaer, kannst du mal ingame kommenß
