### ISSUE TITLE
reckoning aufladungserzeugung

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1114]
die aufladungen von reckoning sollten NICHT erzeugt werden, wenn man sich hinsetzt und dadurch der nächste autohit des gegners einen crit erzeugt. das gilt nur für autohits, durch fähigkeiten sollten weiterhin aufladungen erzeugt werden. 

grad getestet, ein tankwarri hat mich gehauen als ich saß, (er hat fast keinerlei crit-chance) und ich hab ihm nach 5 crits direkt 5 mal gehauen. (autohit + 4 reckoning aufladungen)

http://blue.cardplace.com/cache/wow-paladin/1069149.htm
>Can I sit down to force a crit and gain a charge?
Charges will not generate off auto attacks or npc attacks by trying to sit down and force a crit. However, ability crits from physical abilities such as Sinister Strike, Hamstring, Auto-shot, Aimed shot, etc will generate a charge if you're sitting

id's: 20177 - 20182
http://datenbank.welli-it.de/?search=reckoning

**Comment by Sabbaer** [comment]
interessant wird hierbei werden, ob sowas mit den nächsten buggfixes gefixed wird, und was mit den ganzen buggfixes ist, die den paladin positiv beeinflussen und seit mehreren jahren reportet sind, und an denen anscheinend nicht mehr gearbeitet wird

**Comment by Dotox** [comment]
Wenns dir zu langsam geht, kannst du uns gerne helfen und einen Fix posten. Wenn dus allerdings nicht kannst, dann musst du dich einfach weiterhin gedulden, bis sich einer von uns die Zeit nimmt :)

**Comment by Sabbaer** [comment]
so war das nicht gemeint, mir fällt nur über die jahre mittlerweile auf, dass wenn was negativ für den paladin ist, wird es z.B. per hotfix aufm server aufgespielt (siehe siegel des befehls fix), wenn es aber um andere dinge, wie relikt o.ä. geht gerät es leider gerne in vergessenheit

**Comment by hraesvelgr** [comment]
bitte nicht wieder eine ewig lange diskussion :-/ wir kennen die standpunkte von beiden seiten zur genüge.

**Comment by dagochen** [comment]
Fix (sorry, dass es so lange gedauert hat....):

In folgender Methode
```c++
void Unit::ProcDamageAndSpellFor(bool isVictim, Unit* pTarget, uint32 procFlag, uint32 procExtra, WeaponAttackType attType, SpellEntry const* procSpell, uint32 damage)
```
ist durch folgende Abfrage, die wenn es nen procSpell gibt, schon mal gewährleistet, dass nur bei Autohits der von mir erstellte else-Zweig ausgeführt wird (der ganz am Ende). Dort prüfen wir einmal, ob es sich um eine Aura handelt, die Reckoning auslösen kann (also Rang 1-5) und ob der Spieler grade sitzt. Ist dies der Fall wird das Aufladen durch "continue" unterbunden.
```c++
if (procSpell)
{
	if (spellProcEvent)
	{
		if (spellProcEvent->spellFamilyMask[i])
		{
			if (!procSpell->IsFitToFamilyMask(spellProcEvent->spellFamilyMask[i]))
				continue;
		}
		// don't check dbc FamilyFlags if schoolMask exists
		else if (!triggeredByAura->CanProcFrom(procSpell, spellProcEvent->procEx, procExtra, damage != 0 || (procExtra & PROC_EX_ABSORB), !spellProcEvent->schoolMask))
			continue;
	}
	else if (!triggeredByAura->CanProcFrom(procSpell, PROC_EX_NONE, procExtra, damage != 0 || (procExtra & PROC_EX_ABSORB), true))
		continue;
}
else if (triggeredByAura->GetSpellProto()->EffectTriggerSpell[EFFECT_INDEX_0] == 20178 && getStandState() == UNIT_STAND_STATE_SIT)
                continue;

```
Sprich nur bei Auto-Attacks, wenn der Pala sitzt, gibts keine Aufladungen mehr. Alles andere bleibt wie gehabt.

**Comment by hraesvelgr** [comment]
>bug ist seit 15 stunden reportet

>9 stunden später kommt fix

>"sry dass es so lange gedauert hat"

ok...

**Comment by hraesvelgr** [comment]
passiert leider immernoch.

**Comment by dagochen** [comment]
grad vor if ausprobiert, funzt korrekt.

autohit im sitzen --> keine reckoning aufladungen
styles im sitzen --> paladin bekommt reckoning aufladungen

alles gut.

**Comment by hraesvelgr** [comment]
hast dus auch im pve probiert? :^)
