### ISSUE TITLE
[Paladin] Richturteil des Kreuzzugs + Buchband der Inbrunst + Schadenkoeffizienten + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1115]
Istzustand
Der Heiligschadenbonus von Richturteil des Kreuzfahrers, die Skalierung von Weihe (und evtl. allen anderen Holy-Spells) oder etwas anderes ist kaputt. 
Weihe macht ohne Richturteil 48 Schaden. Mit Urteil sind es 63 Schaden. 

Sollzustand
Weihe skaliert mit Spelldamage zu 33%, bei 140 Heiligbonus durch das Richturteil und verteilt auf 8 Ticks von Weihe sind das also 140/3/8 = 5,833333 Schaden/Tick. 
Weihe mit Urteil sollten also 53-54 Schaden sein.

Quelle
Addon Theorycraft v.1.06.5 (http://wow.curseforge.com/addons/project-1644/files/) vom 2.11.2006: spelldata.lua , Zeile 375-395
http://forums.elitistjerks.com/topic/9354-damage-coefficients/ (aktuell down)

Fix
Ich lehne mich mal etwas aus dem Fenster und vermute, dass es mit der Berechnung der Koeffizienten und dem Schadensbonus von dem Richturteil zu tun hat, da auch der Bonus vom Buchband der Inbrunst und den PvP-Handschuhen nicht korrekt funktioniert. Leider kann ich auf meinem Server den Fehler nicht reproduzieren, folglich ist bei mir alles richtig. Dort wird in der Methode 

``` c++
uint32 Unit::SpellDamageBonusTaken(Unit* pCaster, SpellEntry const* spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack)
```

der Schaden korrekt berechnet. Auch die Items funktionieren einwandfrei. Daher poste ich hier mal die funktionierende Version der Methode:

``` c++
    if (!spellProto || !pCaster || damagetype == DIRECT_DAMAGE)
        return pdamage;

    uint32 schoolMask = GetSpellSchoolMask(spellProto);

    // Taken total percent damage auras
    float TakenTotalMod = 1.0f;
    int32 TakenTotal = 0;

    // ..taken
    TakenTotalMod *= GetTotalAuraMultiplierByMiscMask(SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, schoolMask);

    // Taken fixed damage bonus auras
    int32 TakenAdvertisedBenefit = SpellBaseDamageBonusTaken(GetSpellSchoolMask(spellProto));

    // apply benefit affected by spell power implicit coeffs and spell level penalties
    TakenTotal = SpellBonusWithCoeffs(spellProto, TakenTotal, TakenAdvertisedBenefit, 0, damagetype, false);

    float tmpDamage = (int32(pdamage) + TakenTotal * int32(stack)) * TakenTotalMod;

    return tmpDamage > 0 ? uint32(tmpDamage) : 0;
```

**Comment by Testear** [comment]
Ich bin Dago - Quellen posten ist unter meiner Würde.

**Comment by dagochen** [comment]
@Testear  Hab welche reineditiert.

**Comment by hraesvelgr** [comment]
http://paladin-guide.blogspot.de/2005/12/other-abilities.html

da habt ihr die tabellen.

**Comment by Sabbaer** [comment]
nein, denn du hast da einen fehler drin.
spelldamage scale auf +holy schaden ist 29% und nicht 20%

**Comment by Sabbaer** [comment]
1ne quelle die man nicht einsehen kann.
du weist aber schon, dass man sotc skillen kann........ Oo

**Comment by dagochen** [comment]
Ergibt mal wieder keinen Sinn was du schreibst Sabbaer.... wofür auch immer deine 29% und 20% sind, hat nichts mit dem Bugreport zu tun. Genauso wenig wie die Tatsache, dass man irgendwas skillen kann oder nicht. in Hraesvelgr's Link stehen sogar die exakten Werte, auf die man mit meinen oben angegebenen Formeln auch kommt, aufgelistet. Und diese stimmen de facto nicht mit unserm Server überein, das habe ich heute auf dem Testserver ausprobiert.

**Comment by Sabbaer** [comment]
ja, wenn man es nicht skillt, wenn man es skillt macht es 15% mehr heiligdmg.... gugg doch mal die tabelle an die ich dir gepostet habe, ach haste nicht angeguggt...

**Comment by hraesvelgr** [comment]
sabbaer, dago hat schon recht, ich habs selber probiert. geskillt und ungeskillt. die koeffizienten sind definitiv falsch. das macht aber wenig, da du in etwa genausoviel dmg wie vorher machst, wenn der buchband für SotC gefixt ist.

**Comment by Sabbaer** [comment]
jo, grad nochmal getestet, kann es sein, dass der soct dmg immer mit den 15% mehr dmg berechnet wird, ob man es skillt oder nicht?

**Comment by dagochen** [comment]
Um genau zu sein habe ich das rausgefunden, als ich den Buchband fixen wollte. Hatte nachdem ich die Reckoning-Stacks so langsam gefixt habe nen schlechtes Gewissen und wollte dem Pala mal was gutes tun....und hab bei mir am Server rumgespielt. Bei mir funzt der Buchband korrekt und der Schaden wird in der oben genannten Funktion angerechnet. Daher denke ich das dort der Fehler für den Buchband liegt. Der Fehler wiederum sorgt dafür, das andere Fähigkeiten exorbitant mehr Schaden machen. Bin mir ziemlich sicher, dass wenn das übernommen wird, Buchband und PvP-Handschuhe sowie die Skalierungen korrekt funktionieren.

**Comment by Sabbaer** [comment]
exorbitant? dann stimmen ja dann die ganzen videos nicht, nach denen die vorherigen fixes hier gemacht wurden? denn der schaden von den videos die als beweis angeführt wurden für andere paladin fixes haben ja dann den gleichen schaden ergeben wie den, den ein paladin hier auf dem server macht?

**Comment by hraesvelgr** [comment]
sabbaer, chill mal ne runde. ich spiele selber pala, und ich würde als tank dadurch garantiwert auch nicht profitieren, wenn die die spelldmg-koeffizienten runterdrehen. trotzdem will ich,d ass es (wenns denn geht) so schnell wie möglich gefixt wird. 

und tust mir einen gefallen? überleg dir mal, warum du paladin spielst... 
und ich hoffe die antwort ist nicht "weil ich damit dmg mache", sondern eher was in die richtung "weils einfach spaß macht".

**Comment by Sabbaer** [comment]
ich will auch, dass alles stimmt hraesvelgr aufm server, ich will aber auch, dass es dann stimmt und nicht falsch ist wie z.B. mit den heilig resistenzen, die z.B. auf untote noch immer nicht funktionieren.
Es ist reportet es wurde versprochen gefixed zu werden, und ich hab immernoch teilresists. das buchband funktioniert nicht, in der bubble bekommt man immernoch schaden wenn opferung auf jmdem ist usw.

**Comment by hraesvelgr** [comment]
aber nichts davon ist ein angriff gegen dich persönlich. das geht "gegen alle paladine" aber da scheiß ich ehrlich gesagt drauf. ich hab mehrfach bewiesen, dass ich meine klasse beherrsche, und ich werds auchmit geringeren koeffizienten imemrnoch können. 
und ich glaube, das wird bei dir auch so sein. also chilln wir alle ne runde, und harren der dinge, die da kommen.

**Comment by Sabbaer** [comment]
würde mich trotzdem brennend interessieren, was genau durch sein script an soct verändert wird und auf welchen grundlagen er das aufbaut, oder ob einfach etwas anderes nicht stimmt!

**Comment by dagochen** [comment]
Wie gesagt bei mir ist es logisch und richtig: 
Weihe: 48 Schaden Basis (verifiziert durch http://paladin-guide.blogspot.de/2005/12/other-abilities.html)
Weihe + Richturteil des Kreuzfahrers: 140 Holyspelldmg * 0.33 / 8 = 53-54 Schaden
W. + RdK + Buchband = 177 Holyspelldmg * 0.33 / 8 = 55-56 Schaden
W. + RdK + B. + PvP-Handschuhe = 197 Holyspelldmg * 0.33 / 8 = 56-57 Schaden

Während bei uns Weihe + Richturteil des Kreuzfahrers bereits bei 63 ist. Das das falsch ist, ist wohl offensichtlich.

**Comment by Sabbaer** [comment]
jo, das steht ja schon ausser frage, die frage ist aber eher, was hier nicht genau stimmt! tritt dies nur auf bei der combination von weihe mit soct oder tritt das auch bei anderen effekten auf

**Comment by dagochen** [comment]
ka ich hab nur weihe testen können, weil weihe halt so schön festen schaden macht. alles andere können mit 100% sicherheit nur leute sagen, die den quelltext von der oben genannten methode auf nefarian kennen, welcher definitiv anders sein muss, als meiner, da dort buchband und pvp-handschuhe angerechnet werden sollten.

**Comment by dagochen** [comment]
Zu der Mechanik im Server:
Sobald der Zauber berechnet wurde mit seinen Basiswerten (Bei Weihe 48), wird der Spelldamage vom Caster angerechnet (Funktion: SpellDamageBonusDone), also z.B. Spelldmg vom Gear. Ist dies angerechnet, wird auf dem Ziel des Zaubers geschaut, ob dort auch Effekte aktiv sind, die den Schaden erhöhen. Dies ist im aktuellen Fall die oben genannte Funktion SpellDamageBonusTaken, welche das Richturteil des Kreuzfahrers findet und ebenfalls mit den gleichen Skalierungen arbeiten solllte, wie SpelldamageBonusDone. Nur das scheint hier nicht der Fall zu sein.

**Comment by Sabbaer** [comment]
was uns immernoch keine antwort darauf gibt, ob was mit weihe soct oder vll anderen dingen nicht stimmt, denn du nimmst ja anscheinend irgendwas von soct weg, oder nicht?

**Comment by dagochen** [comment]
Wie soll ich dir sagen, ob da was "weggenommen" oder sonst was wird. Ich kenne den Source nicht und kann es dir nicht sagen. Ich kann dir lediglich sagen, dass es falsch ist, wie es ist. Und logisches Denken und nachrechnen haben bewiesen, dass es bei mir auf dem Server korrekt angerechnet wird. Wir wissen ja noch nicht mal sicher, ob der Fehler in der Funktion SpellDamageBonusTaken ist, sondern nur, dass es wahrscheinlich ist, weil dort Buchband und Co bei mir angerechnet werden. Da dies auf Nefarian nicht der Fall ist, muss hier irgendwas anders sein. Was genau, kann dir Dotox / Nightblizard sagen. Wenn ich den Quelltext von der Nefarian-Version bekommen würde, könnte ich es sicherlich ausprobieren, wo der Unterschied ist und erklären, aktuell ist dies aber nicht möglich.

**Comment by Sabbaer** [comment]
kk, also auf dev warten ;)

**Comment by Sabbaer** [comment]
ok, ich hoffe dass sich genauso schnell mal wieder um paladin probleme gekümmert wird, die seit 3 jahren reported sind.....

**Comment by dagochen** [comment]
Nen Unterschied zum Schaden ohne Kreuzfahrer-Urteil ist glaube ich nicht zu erwarten. Abgesehen davon macht der Pala in dem Video nur 284 dps (steht bei SWStats oben in der Kopfzeile, ich hoffe ich hab das da richtig abgelesen). Da wirst du wohl locker drüber kommen, oder?

**Comment by Sabbaer** [comment]
er hat nur 1 elixier drinne und kreuzfahrer richtet er am anfang und den 8waffenschadensschleifstein und macht schon gleichen bis höheren sdb schaden als wenn ich ne flask drinne hab

**Comment by dagochen** [comment]
Grad mal mit meinem Priester und nem Paladin ausprobiert. Göttliche Pein macht volle 150 Schaden im Mittel mehr. Also auch hier ist die Skalierung von Richurteil des Kreuzfahrers kaputt.

**Comment by Sabbaer** [comment]
der punkt dago ist eher der, stimmt dann sdb formel nicht mehr, wenn der typ in dem video schon mehr dmg macht ohne flask als ich mit!

**Comment by Sabbaer** [comment]
der thread sollte heißen: kein soc effekt auf sdb!  .....

**Comment by Sabbaer** [comment]
push
