### ISSUE TITLE
Schlachtzug: Ready Check

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1123]
IST:

Der Schlachtzugsleiter ist automatisch nicht bereit.
Trotz bestätigen des JA Button wird dieser nicht akzeptiert, der Ready Check läuft durch und die Mitglieder im Schlachtzug werden als AFK angezeigt.

SOLL:

Der Schlachtzugsleiter sollte als Bereit gemarkt sein.
Ja Button - Spieler ist bereit
Nein Button - Spieler ist nicht bereit
Ready Check läuft durch - Folgender Spieler ist afk

Reproduzieren:

Schlachtzug erstellen und Bereitschaft Button betätigen.

Gruß

Chichi

**Comment by Slimmer2** [comment]
Da stellt sich aber die Frage, ob das nicht eine Funktion ist, die Addons bereitstellen und nicht das Spiel selber.

**Comment by ChichiWarrior** [comment]
Beides getestet, bei beiden das gleiche Problem,

**Comment by rockefaeller** [comment]
Patch 1.11
Raid leaders now have a Ready Check button on their raid interface. This can also be sent with /readycheck from the chat line. A Ready Check sends an "Are you ready?" window with Yes/No buttons to all players in the raid. The raid leader will get feedback in 30 seconds on all the players who were not ready or who did not respond.

http://wow.gamepedia.com/Patch_1.11.0

**Comment by Dotox** [comment]
Wenn ist das auf dem Testserver teste steht nirgends, dass der Schlachtzugsleiter nicht bereit wäre. Wo wird dir das denn angezeigt?

**Comment by ChichiWarrior** [comment]
Hab es auf dem Liveserver mit 5 Leuten spontan getestet. Scheint alles zu funktionieren.

Keine Ahnung woher ich das mit dem Schlachtzugsleiter habe, ist schon lange her.

Wir werden das heute in einem 20er und morgen in einem 40er Raid ausgiebig testen, während wir auch in der Raidinstanz stehen. Das eben war einfach nur in OG spontan getestet.

**Comment by ChichiWarrior** [comment]
Habs gestern in AQ40 getestet.

Die Spieler, die auf JA geklickt haben, hatten keine Probleme.
Die Spieler, die auf NEIN geklickt haben, wurden mit Ready Checks voll gespammt, bis hin zum DC.
Der Schlachtzugsleiter (in dem Fall ich) hatte ein permanentes gespamme unterschiedlicher Messages, die trotz eine Relogs nicht aufgehört haben (Spieler sind afk, Spieler sind nicht bereit)

Nur durch ein erneutes öffnen des Raids hat das Problem aufgehört.

Gruß

Chichi

**Comment by Slimmer2** [comment]
Evtl liegt es an einen Addon

**Comment by ChichiWarrior** [comment]
Da kann ich dir mit ruhigem Gewissen sagen, nein daran lag es nicht

**Comment by Slimmer2** [comment]
Keiner in Raid hatte ein Addon aktiviert?
