### ISSUE TITLE
Instanzenportstein

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1126]
IST:

Man kann seine Gruppenmitglieder an Instanzportsteinen nur porten, wenn sich maximal 4 Mitspieler in der Gruppe befinden.

SOLL:

Man sollte auch an Instanzportsteinen seine Gruppenmitglieder porten können, wenn die Gruppe mit 5 Mitspielern belegt ist.

Gruß

Chichi

**Comment by hraesvelgr** [comment]
*hust*

Soll: 
die instanzen"port"steine sollten niemanden porten, sondern nur die möglichkeit geben, eine gruppe zu finden. dazu muss man sich direkt am stein anmelden, und kann sehen, wer sich  noch angemeldet hat.

**Comment by ChichiWarrior** [comment]
Nene, das kam 100% erst später.

In Classic waren die Portsteine als Support um die mögliche hohe Anreisezeit zu verringern, in dem man alle Mitglieder zum Stein portet.
Vorraussetzung: In dem Portstein-Levelbereich UND ein weiteres Mitglied, um die Beschwörung zu vollenden.

**Comment by hraesvelgr** [comment]
>In patch 2.0.1, Meeting Stones were reworked with the implementation of the new LFG system. They now are used to summon party members to the stone near an instance.

http://wowwiki.wikia.com/wiki/Meeting_Stone

> Patch 2.0.1 (05-Dec-2006): Meeting Stones now function similar to a Warlock Summon spell.

aha? :)

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/452

**Comment by dagochen** [comment]
fail-chichi :P

**Comment by Sabbaer** [comment]
in vanilla gabs die portfunktion noch nid chichi wie hraesvelgr schon richtig gepostet hat

**Comment by ChichiWarrior** [comment]
In der Tat, um eine Erkenntnis schlauer.

Was machen wir jetzt mit den Instanzsteinen?
Report ändern, wie es wirklich war oder versuchen den Port wirklich auf einen 5er Gruppe fixen?

Auch wenn dieser erst mit Patch 2.0.1 kam, find ich die Möglichkeit mit dem Port doch sehr angenehm.

Ich leg das mal in die Hand der Dev's, was sie machen wollen.

Sorry für meine Unwissenheit bezüglich des Reports.

Gruß

Chichi

**Comment by hraesvelgr** [comment]
unwissenheit ist nix schlimmes.

und wie schon erwähnt, wird das wieder eine community-entscheidung sein. ich selbst habe classic schon komplett ohne die portfunktion gespielt, und es war....nicht wirklich anders. 
ich fands total ok, überall hin zu laufen. 

aber die community wird schon aus faulheitsgründe dagegen sein :)

**Comment by Slimmer2** [comment]
Denke ich auch. Auch wenn zwei Leute eh anreisen müssen
