### ISSUE TITLE
Buch der Offenbarung

### ISSUE THREAD

**Issue by DerGrimmigeZwerg** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1128]
Die Questbeschreibungen zur Paladin Stufe 12 Quest der Allianz "Buch der Offenbarung" sind teils auf englisch, teils auf deutsch. Der NSC Stephanie Turner spricht den Paladin zudem mit dem falschen Namen an.

**Comment by ircfelix** [comment]
Etwas genauere Infos,  eine Beschreibung wie es genau sein sollte (mit Zitaten) und Quellen für deine Aussagen müssen her.

Sonst:
- haben die devs viel zu recherchieren,
- können in der Recherchezeit keine Bugs fixen,
- schließen sie diesen Thread hier.

**Comment by Slimmer2** [comment]
Wäre auch nett wenn links zu den quest postest.
