### ISSUE TITLE
Casten möglichen trotz Verbannung

### ISSUE THREAD

**Issue by Armauskugelbob** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1129]
**Problem**

Es ist möglich weiterhin mit dem Hexerpet Zauber zu wirken, obwohl es verbannt wurde, wenn man die entsprechenden Zauber über ein Makro aktiviert. 
Beispiel: /wirken Verführung

**Wie sollte es sich verhalten?**

Wenn ein Hexerpet verbannt wurde, sollte es für die Dauer seiner Verbannung Handlungsunfähig sein und nicht weiterhin über Makros im Stande sein seine Fähigkeiten zu wirken

Edit: gleiches Verhalten lässt sich auch beobachten wenn das Pet gefeart wird.

**Comment by 0815Priester** [comment]
Jungs könnt ihr das bitte fixen? Es nervt einfach wenn ein Spell im PvP komplett useless ist.
Danke.
