### ISSUE TITLE
Fehlerhafte Hit-Berechnung (Rogue)

### ISSUE THREAD

**Issue by Hakii** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1135]
Was habe ich beobachtet:

Seit mehreren Wochen beobachte ich nun mit dem Addon Recap eine Anomalie betreffend der Trefferchance von Autoattacks.

Sowohl als Dagger- als auch als Swordrogue scheint die Chance mit Autoattacks zu verfehlen (Dodge und (un-)möliche Parrys logged Recap nicht als Miss) unverhältnismäßig hoch.

Über mehrere Wochen hinweg habe ich mit 17% Hit und 310 Waffenwertung gespielt (sowohl Dagger als auch Sword) und habe in jeglichem Content (Raids, Instanzen, Farmen) eine Misschance von 13.5-14.5% auf Autoattacks.

Vor zwei Wochen bin ich auf 19% Hit und 310 Waffenwertung gewechselt, seither liegt die Misschance von Autoattacks bei 11.5-12.5%

Wie sollte es sein:

Bei einer Waffenwertung von 310, liegt die Chance gegen ein Ziel mit Lvl 63 (oder Boss) mit einem Autoattack zu verfehlen, bei 24.5% abgeleitet von der Formel:

If the difference between the mob's Defense Skill (level * 5) and your Weapon Skill ([level * 5] + additional bonuses) is less than or equal to 10 then the formula for calculating your base miss rate against that mob is:

    5% + (Defense Skill - Weapon Skill)*.1%
    dual-wielding: 24% + (Defense Skill - Weapon Skill)*.1% 

If the difference between the mob's Defense Skill and your Weapon Skill is greater than 10, then the formula for calculating your base miss rate against that mob is:

    7% + (Defense Skill - Weapon Skill - 10)*.4%
    dual-wielding: 26% + (Defense Skill - Weapon Skill - 10)*.4%

Bei einem Gear mit 17% oder 19% Hit, sollte die Misschance entsprechend bei ~5.5-7.5% liegen.
Natürlich spielt irgendwo auch das RNG mit rein, aber es trifft einfach zu jeder PvE Gelegenheit zu, das dieser Wert um 6-7% verfehlt wird.

Mögliche Ursachen:

- Die Waffenkunde funktioniert nicht

und/oder

- Das Talent des Rogues "Präzision" funktioniert nicht (wobei hier die Misschance gegen Lvl 58-60 Ziele nicht geklärt wäre)

Vanilla WoW Wiki Eintrag
http://vanilla-wow.wikia.com/wiki/Hit

**Comment by dagochen** [comment]
Im aktuellen Standard-Mangos ist es so implementiert wie du oben beschrieben hast. 

Werde aber mit meinem Schurken mal drauf achten. Das Addon Glancingmeter ist für solche Zwecke übrigens ideal geeignet. Recap macht manchmal merkwürdige Sachen^^

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/813

**Comment by Larnak1** [comment]
Bist du sicher dass bei diesen Formeln die *aktuelle* Waffenwertung genutzt wird? Bei manchen dieser Formeln mit Waffen- und Verteidigungswertung wird immer der unmodifizierte Wert genommen. Wenn du hier so rechnest, wären die Werte korrekt.

**Comment by Larnak1** [comment]
Woher sind denn die Formeln? Leider sind die Testpuppen auf dem Testserver immer noch nicht wieder da.

**Comment by Testear** [comment]
Die Misschancefür Dualwilder beträgt 27%, wobei das Hitcap trotzdem 24% bleibt, da die letzten 3% Standardmiss sind. Meinem letzten Stand nach gibt Waffenkunde hier 0,02% Hit Pro Punkt.

"Vor zwei Wochen bin ich auf 19% Hit und 310 Waffenwertung gewechselt, seither liegt die Misschance von Autoattacks bei 11.5%-12.5%."

Nehmen wir an die 5% Hit die der Schurke skillen kann funktionieren nicht wären wir. Miss und Hitchance zusammengerechnet zwischen 25,5 und 26,5.
Was ziemlich genau am Hitcap liegt.

Zuletzt sage ich noch, dass du Quellen zu deinem Report hinzufügen solltest, da er sonst von den Devs nicht angenommen wird.

**Comment by Hakii** [comment]
kannst du mal nachprüfen, ob der server folgende berechnungen zulässt:

https://docs.google.com/spreadsheets/d/1fvHQVDpEHjFdG9ANtAOAk5zR1RaKqMDWi5psRcHvJ_Q/edit?usp=sharing

**Comment by Testear** [comment]
Hab ich deinen Bugreport geschrieben?

**Comment by Hakii** [comment]
http://vanilla-wow.wikia.com/wiki/Hit

Die Quelle. Entspricht deinen Zahlen in keinerlei Hinsicht.

**Comment by Testear** [comment]
Wie wäre es, wenn du dir ne Quelle suchst, die nicht jeder editieren kann. wtf

http://vanilla-wow.wikia.com/wiki/Hit

"testear edited here"

**Comment by Larnak1** [comment]
Vanilla wow ist keine gute Quelle da das wiki erst nachträglich erstellt worden ist und meistens keine Primärquellen angegeben werden. So ist komplett unklar woher diese Infos stammen. In einigen Artikeln steht dort ziemlicher Unfug.

**Comment by Hakii** [comment]
Du kannst jede Eintragsänderung nachvollziehen und auf die alten Originalseiten zugreifen:

Beispielsweise der Originaleintrag von Emhilradim der die ersten Klassikeinträge gemacht hat und Founder der Seite ist

http://vanilla-wow.wikia.com/wiki/Hit?oldid=21705

**Comment by Larnak1** [comment]
"October 16, 2012" und keinerlei Primär-Quelle angegeben, daher weitgehend wertlos :/

**Comment by Hakii** [comment]
Woher stammen die Zahlen von Testar wenn ich fragen darf?

**Comment by dagochen** [comment]
Benutzt lieber das Original WoW-Wiki und greift dort über die History auf alte Seiten zu oder nehmt direkt andere Quellen (Elitistjerk, etc.). 

Hab jetzt nicht jeden Fall in der Tabelle angeschaut, aber stichprobenartig passt es mit meinem Server zusammen. Wie es auf Nefarian ist, kann ich wiederum nicht sagen.

**Comment by Testear** [comment]
Ich habe diesen Beitrag geschrieben:

http://community.mmobase.de/talk-und-allgemeines/6947-waffenwertung-skaliert-zu-hoch.html

Da sind im ersten Post ein Haufen links zum Thema Waffenwertung und ein paar in denen auch über Hit geredet wird.

http://wowwiki.wikia.com/wiki/Attack_table

Den Link mit dem Zwischenraum 24%-27% Hit finde ich gerade nicht, vllt ist er aber auch im oben genannten Thread dabei.

**Comment by Hakii** [comment]
Was ich bisher gefunden habe:

http://wowwiki.wikia.com/wiki/Weapon_skill?oldid=870672

See Weapon Skill Adjustment Discussion and the thread it's part of. People have done hours' worth of testing using Venoxis, accumulating a LOT of data to back up the 9% claim (and more significantly to show how getting to +5 weaponskill, even from +4 already, is a big win against bosses if you don't yet have sufficient +hit to cancel the miss chance).

--Athan 10:38, 13 September 2007 (UTC) 

In Classic und Burning Crusade funktionierte die Weaponskill-Mechanik identisch, bis auf den Punkt:

Patch 2.0.1 (05-Dec-2006): Weapon skill will no longer reduce the percentage damage lost due to glancing. The player will gain 0.1% to their critical strike rating per weapon skill against monsters above their level.

Im November 2007 wurde der Gearstat Weapon-Skill aus dem Spiel entfernt.

**Comment by Testear** [comment]
Je nach Lust und Laune werde ich später vielleicht mehr dazu schreiben.

Aber aktuell lehne ich mich mal aus dem Fenster und behaupte, dass das Problem nicht das Hit durch Waffenkunde ist - pro 5 Punkte 0,2% - sondern ,dass das Skillbare Hit nicht gewertet wird oder, dass es wieder einen Bug gibt, durch den Ausweichen und Parieren als Verfehlen gewertet werden - wäre nicht das erste mal, dass es sowas gibt (siehe Execute Bug vor einem Jahr oder so). 

Und jetzt habe ich genug ,dass vergewaltigt....

**Comment by Seniorash** [comment]
Das mit dem Hit durch Waffenkunde ist kaum bemerkbar, weil es maximal 0,6% ausmacht. Um das festzustellen bräuchtest du schon eine sehr große Anzahl. Alternativ kannst du schauen ob du mit 0 Waffenkunde und 15 Waffenkunde lvl 63er noch verfehlst, während du keine Offhand angelegt hast.
Zu der Hitberechnung wurden viele Zahlen genannt, ohne diese wirklich zu belegen. Z.B. die 3% Miss die man angeblich nie wegbekommt, höre ich zum ersten Mal. 1% Basemiss bleibt nur bei Castern.
Die 24% gelten nur für gleichstufige Ziele. Bei einer höheren Stufe kommt neben der höheren Deffwertung noch die LvL-Differenz dazu.
Bei 2H sind sich alle einig, dass das Hitcap bei 8,6% liegt. Das kommt durch 5% + 3% durch 3 LvL-Differenz und 0,6 durch die Waffenkunde-Verteidigungsdifferenz zustande. Diese Addition muss bei DW genauso gelten. Damit ergibt sich eine Misschance für DW angriffe gegen Bosse ohne Waffenkunde zu 27,6% (8,6%+19%).
Vielleicht hilft dir das bei deiner Recherche und beim weiteren Testen weiter.

**Comment by Hakii** [comment]
Ich werd Dagos Rat zu Herzen nehmen und noch mit anderen Programmen und Kampflogauswertungen mein Anliegen nachprüfen.

**Comment by Hakii** [comment]
Nach einigen Test kann ich das Problem eindeutig auf die Waffenkunde zuschieben. Da es ein klassenübergreifendes Problem ist, möchte ich diesen Thread bitte löschen/schließen lassen, um das Problem in den nächsten Tagen in einem neuen Thread genauer und sauberer darzustellen.

**Comment by Sabbaer** [comment]
du kannst selber den thread schließen, du hast ihn eröffnet und einen neuen machen ;)
