### ISSUE TITLE
Mysterien der Titanen nicht von allen lootbar.

### ISSUE THREAD

**Issue by Adalbern12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1138]
Guten Tag, ich war mit einer Gruppe im Kloster, dort konnten die ersten das Buch looten, aber bei den 
letzten 2 Leuten ging es nicht mehr. Der Curser veränderte sich nicht mehr zum Rädchen.
Und so verlohren wir die Ep.
Grüsse.

**Comment by hraesvelgr** [comment]
da die quest bisher bei allen anderen ging nehme ich folgendes an:

wdb ordner nicht gelöscht. 
quest nicht im log
das buch ist nicht respawnt (ca 30 min respawn)

**Comment by Adalbern12** [comment]
also in meiner Gruppe gings bei mindestens 2 Leuten nicht , das Buch auf das ich mich beziehe ist an GENAU dem Platz wieder gekommen an dem das Richtige buch sein sollte, zu der Zeit angabe,
wir haben danach mehrere Räume Ge-cleart also ist einiges an Zeit verstrichen aber wie lange es genau war bis wir zum Enboss kamen und obs lang genug war ka.hab ned geguckt..
das mit dem WDB Ordner ist schön und gut aber das liest man erst hier und das kann mir gestern nix geholfen haben.
Grüsse.

**Comment by Larnak1** [comment]
Das hier ist aber auch keine Supportplattform sondern ein Bugtracker :)

**Comment by hraesvelgr** [comment]
wir können dir nichts ersetzen. und ein wirklicher bug, der auf alle spieler zutrfft scheint es ja auch nicht zu sein. geh einfach nochmal kloster. macht spaß, und fördert das soziale leben auf dem server.
