### ISSUE TITLE
Deathmines Boss vor schiff Buggt zuviele Adds

### ISSUE THREAD

**Issue by Adalbern12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1139]
der Boss der aussieht wie ein grosser Taure  und einen Stunt an dem Aufgang zum schiff, hat statt 2 Adds , wie im Orginal 4 Adds dabei, und ist somit im Ersten Anlauf ohne wipe bisher für mich so nicht schaffbar.

**Comment by Gnomorus** [comment]
Willkommen im ClassicWoW 1.12.1 Bugtracker!

    Vor dem Melden
    Leere oder lösche den WDB Ordner bevor du das Spiel startest
    Starte das Spiel ohne Addons
    Einige (Sammel)Quests können durch das Beenden und erneute Annehmen doch abgeschlossen werden
    Schaue im Bugtracker nach, ob der Fehler nicht bereits gemeldet wurde
    Nur ein Fehler pro Fehlermeldung
    Sucht NPCs, Quests, Objekte, usw. in der Datenbank raus und verlinkt sie


Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

Zusätzliches

    Wir akzeptieren nur Quellen, die sich nachweislich auf classic wow beziehen
    Meldungen, die das geforderte Format nicht einhalten, können kommentarlos geschlossen werden
    Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!


Vielen Dank für deine Meldung!

**Comment by Slimmer2** [comment]
Hier eine Info wie der Boss zu BC war:
Zum Aufgang des Schiffes wartet bereits der nächste Boss: ein Taure namens Handlanger Pein mit zwei (zunächst unsichtbaren) Gehilfen, welche aber unmittelbar angreifen, sobald die Gruppe sich dem Steg zum Boot nähert. Bei 75% und 25% seiner Lebenskraft gönnt Handlanger Pein sich eine kurze Ruhepause – und durch seine Fähigkeit Peins Stampfen den Gruppenmitgliedern gleich mit, denn diese sind jeweils 10 Sekunden betäubt.

Sobald die Betäubung nachlässt, geht die Gruppe wieder zum Angriff über und schickt Handlanger Pein ins Jenseits. Dieser droppt nach seinem Ableben einen von drei blauen Items: mit einer Wahrscheinlichkeit von 38% Peins Häscher, mit 37% die Diebesklinge und mit 18% Peins mächtiger Hammer.
Quelle: http://www.wowknowhow.de/2009/01/14/instanzen/instanzguide-die-todesminen/


Hier steht bei einen der Bilder das 2 Adds aus dem Schatten springen
http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/die-todesminen/

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/291

**Comment by Adalbern12** [comment]
der abschnitt 291 ist vom 17.12.14 
also wäre genug zeit gewesen es zu fixen.......
vil ganz gut das ichs nochmal frisch in Erinnerung bringe
und ich habe diese 3-4 sachen zusammen geschrieben ich werd versuchen eure vorgaben besser ein zu halten thx eine weiterer hinweis sollte nicht nötig sein.
grüsse
