### ISSUE TITLE
Stark erhöhte Spawnrate der Mobs

### ISSUE THREAD

**Issue by Adalbern12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1140]
Guten tag, ich stelle fest das die Respawnrate aller Mobs stark erhöht ist, und viele Sachen die man 
zu erledigen hat , dadurch deutlich schwerer sind als im orginal, das wäre nicht so schlimm , aber 
da die Chars noch an das alte Spiel angepasst scheinen (Mana durstigkeit , viele reggpausen)
kommt das einer ziemlichen Erhöhung der spiel Schwierigkeit gleich.
Ein Bsp. im Rotkam, gibt es eine Burg , in der man zb. die Quest Gathll zogg etc.. erledigen muss,
wenn man sich einmal durch den Hof gekämpft hat, sind die Mobs wieder neu da, das war früher eindeutig nicht der Fall.
Der Schwierigkeits grad ist so vieler Orten so hoch, das man sie nicht in dem lvl bereich schaffen kann für den sie gedacht sind. (nochmal Rotkam, der bereich ist bis lvl 25 ausgewiesen, aber selbst eine
4-5 Mann Gruppe schafft diese Burg Quest nicht).
´noch ein Bsp. in Nordhain bei den Anfänger Questen, zb. mit Milys wein auf dem Feld, manchmal räumt man sich gerade ein Stück frei und wenn man den Wein looten will, und nicht sehr schnell macht, sind die Defias wieder da und hindern einen daran, oder ,man kanns ich so im gegensatz zu früher in der Tiefenschachtmine einschliessen einfach weil nix für ne kleine weile frei bleibt.
ok ich hoffe das waren genug Bsp.
Grüsse

**Comment by Sabbaer** [comment]
quellen bitte.... was soll ein deff damit anfangen. ich glaube eher, dass dich deine wahrnehmung trübt

**Comment by Adalbern12** [comment]
An welche Quellen hast du da so gedacht?
Ich bin ja nicht der einzige der damals gespielt hat. Der Pala war mein erster Char , also hab ich mit ihm die geschichte intensiv erlebt und ich war Quasi soloplayer weil ich zuerst alles so entdecken wollte,
ich weiss noch was ich alles solo geschafft hab. Und hier biste schnell mal umstellt wos frühe rnicht der fall war , aber bewise und Quellen... hm woher soll ich die bekommen?
dann leg ich se gern vor. hab damals leider noch ned wissen können das ich hier Video material brauchen könnte.=)
Grüsse

**Comment by Larnak1** [comment]
Quellen, die nachweisen, wie hoch die Respawnrate damals war. Außerdem werden Datenbank-Links zu den betroffenen Gegnern benötigt. 

Siehe readme:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by Sabbaer** [comment]
deine burgquests sind grp quests und waren damals nicht einfach, ich kann mich noch sehr gut daran erinnern, dass ich die in vanilla als kleiner paladin auch probiert hab und dort von den mobbs und dem respawn in den boden gestampft wurde. Also ka ich hab mal bisschen gegoogelt, dazu genaue sachen zu finden ist schwer. hatte da vorhin so nen lvl bericht von einem gefunden, der meint dass man da unbedingt als gruppe hinsollte usw...

**Comment by hraesvelgr** [comment]
's is  hoid classic!

**Comment by dagochen** [comment]
Naja früher gab es einfach deutlich mehr Spieler, wodurch man nicht jeden Mob selber töten musste. Das wird vermutlich der Grund dafür sein, dass du dich von deinen Erinnerungen hast täuschen lassen.

**Comment by Adalbern12** [comment]
Hi nochmal , wer genau gelesen hat, weiss das ich geschrieben habe die Burgmission ist nicht mal MIT EINER 4-5 MANN GRUPPE auf lvl 25 zu schaffen , also die max zahl auf dem fürs gebiet max lvl.
grüsse

**Comment by hraesvelgr** [comment]
aber alle anderen schaffen es....was machen die dann anders?

**Comment by Adalbern12** [comment]
alle andern ? ich hab von mehreren mit spielern gehört das es nicht machbar ist, und die "andern" 
(komisch das du weisst was "alle andern " so ausser dir schaffen) schaffen es ja, mit einem 60 er! der hilft.

**Comment by hraesvelgr** [comment]
hachja... wenn ich mir jetz ne grp suche, und die mobs einfach lege, und unter level 25 bin.... dann hau ich dir sämtlichen loot den ich finde solange um die ohren, bis du aufhörst dich zu beschweren :)

**Comment by Adalbern12** [comment]
nur zu^^ ich bin gespannt auf dein video, dann darfst du haun und ich bin auch sofort friedlich^^
wenn du willst entschuldige ich mich sogar dafür das ich an dir gezweifelt hab, habe andernfalls in obigen posts alles gesagt und warte darauf das du es tust , mit beschriebenen vorraussetzunen.
grüsse
