### ISSUE TITLE
Zeichen gehen schnell verlohren

### ISSUE THREAD

**Issue by Adalbern12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1141]
Guten Tag, als Gruppenleader markiere ich Ziele mit Totenkopf etc......
es kommt oft vor das schon nach einem Angriff die Zeichen wieder weg gehen.
p.s. mit welchen Tool soll man Video beweise aufnehmen ? und wie bekommt man sie dann zu euch?
Grüsse

**Comment by Larnak1** [comment]
Gibt' schon:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1122

**Comment by Gnomorus** [comment]
Willkommen im ClassicWoW 1.12.1 Bugtracker!

    Vor dem Melden
    Leere oder lösche den WDB Ordner bevor du das Spiel startest
    Starte das Spiel ohne Addons
    Einige (Sammel)Quests können durch das Beenden und erneute Annehmen doch abgeschlossen werden
    Schaue im Bugtracker nach, ob der Fehler nicht bereits gemeldet wurde
    Nur ein Fehler pro Fehlermeldung
    Sucht NPCs, Quests, Objekte, usw. in der Datenbank raus und verlinkt sie


Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

Zusätzliches

    Wir akzeptieren nur Quellen, die sich nachweislich auf classic wow beziehen
    Meldungen, die das geforderte Format nicht einhalten, können kommentarlos geschlossen werden
    Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!


Vielen Dank für deine Meldung!

**Comment by Slimmer2** [comment]
Zu deiner Frage http://community.mmobase.de/hilfe-und-support/7103-support-anfragen-ingame-und-forum-beweisbilder-video.html
