### ISSUE TITLE
[Movement] Fehlerhafte Ausrichtung / Position von Mobs / Geschwindigkeit

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1142]
Istzustand:
Seit ein paar Wochen ist es der Fall, dass Mobs für Spieler nicht angegriffen werden können, weil sie
a) außer Range stehen, obwohl der Mob aus Sicht des Spielers direkt neben ihm steht
b) Fähigkeiten, die erfordern dass man hinter einem Mob steht, nicht möglich sind.

Ich habe es hauptsächlich bei Stuns/Slows/etc. beobachtet, dass ich diese Fehlermeldungen bekommen habe. Weiterhin besteht das Problem, dass einige Mobs die letzte Distanz zum Ziel in erhöhter Geschwindigkeit zurücklegen, ähnlich wie bei einem Charge, obwohl diese gar keinen Charge haben. 

Da ich allein nicht alle Mobs zusammen bekomme, die das betrifft, bzw. bei welchen Situationen die oben genannten Probleme auftreten (zwecks Reproduktion für die Devs), bitte ich alle, die eine Idee, oder ein Video davon haben, wo man das Problem sieht, dies hier zu melden und zu dokumentieren. Ich würde dann daraus einen richtigen Bugreport machen.

Danke,
dago

**Comment by hraesvelgr** [comment]
rangefinding  problem?
ich wurde letztens von einem npc verfolgt, über die halbe map. er war sogar komplett aus meinem target raus, weil ich ih  nicht mehr gesehen habe. am andern ende der map hat er mich doch noch eingeholt. er hat mich angechargt, und ist sofort wieder abgehauen/resettet. sieht so aus, als hätte das rangefinding system ihn dazu gewzungen, den spell doch noch auszuführen, obwohl ich extrem weit weg war. 

genauso das plötzliche zurennen auf einen gegner. irgendwas scheint die npcs zu zwingen, den spell/angriff sofort auszuführen, obwohl sie nicht in reichweite sind. 
da wird wohl der abstand zwischen den hitboxen falsch berechnet.

**Comment by Sabbaer** [comment]
das habe ich leider auch schon häufiger beobachten dürfen, häufig bei stun effekten, der mobb steht gefühlte 3-4 meter weiter weg, von seinem eigentlichen standort

**Comment by Larnak1** [comment]
Mein Eindruck ist, dass es *alle* Mobs betrifft. Sie scheinen gestunnt einfach nicht tatsächlich dort zu sein, wo man sie sieht, sondern ein wenig verschoben. Wenn man ein wenig hin und her probiert, findet man meist so 5 Meter entfernt eine Position, wo der Angriff "von hinten" möglich ist.

"genauso das plötzliche zurennen auf einen gegner."
Das macht den Huntern in BWL gern mal das Leben schwer beim Kiten :/

**Comment by markthetechie** [comment]
Kann das Verhalten wie von dagochen beschrieben bestätigen. Vor allem als Täuschungsschurke mitunter deprimierend :)

**Comment by Dotox** [comment]
Ich hab mir die Mühe gemacht und versucht, die Fehler zu beheben. Testen könnt ihr es auf dem Testserver.

**Comment by dagochen** [comment]
@Dotox 
Kannst du das nicht direkt aufspielen? Da wir immer noch nicht genau wissen, unter welchen Umständen es überhaupt zu diesem Fehler kommt, ist es halt nicht zuverlässig reproduzierbar und damit auch nicht zu testen.

**Comment by Dotox** [comment]
Leider nicht. Die Änderungen waren zu umfangreich.

**Comment by dagochen** [comment]
Testserver stürzt permanent ab :(

**Comment by Dotox** [comment]
Ist kein Absturz und hat nichts mit dem Update zu tun :) Müsste gleich wieder Online sein.

**Comment by dagochen** [comment]
Also die 2-3 Minuten die ich jetz probieren konnte bisher hat das Problem weiterhin bestanden. Bei Stuns drehten sich die Mobs einfach um oder in irgendeine andere Richtung. Hängt glaube ich davon ab, ob sie sich während des Stuns bereits am bewegen waren oder still standen oder einen andere Bewegung gemacht haben. Sprich die Übergange zwischen den MovementGeneratoren stimmt nicht korrekt, bzw. sie senden dem Client noch eine Information, die aber nicht korrekt ist, wodurch es auf den Clients falsch aussieht.

**Comment by Dotox** [comment]
Ja, was das Problem ist, ist mir schon klar. Ich konnte das nur teilweise Reproduzieren und das ist nach dem Fix / Update nicht mehr aufgetreten. Von daher dachte ich, dass es behoben ist :/ Mit welchen Zauber und NPCs hast du es getestet?

**Comment by dagochen** [comment]
Ich hab meine Tests mal aufgenommen. Hier die Videos.

http://www.twitch.tv/dagochen/v/21312415
http://www.twitch.tv/dagochen/v/21308334

**Comment by Dotox** [comment]
Also ich hab mir deine Videos angesehen und konnte nicht wirklich irgendwas merkwürdiges erkennen. Daraufhin hab ich das selber mit nem Schurken Ingame getestet und bei mir drehen sich die NPC's nicht in eine andere Richtung. Ich kann nach einem Stun auch ohne Probleme hinter den NPC laufen und Hinterhalt nutzen. Auch Ablenken funktioniert. Über einen zweiten Client hab ich alles beobachtet und konnte keine Abweichungen feststellen.

**Comment by hraesvelgr** [comment]
das problem tritt vor allem bei extremen movement auf. angenommen vor dir rennt ein spieler her. du knalslt ihm als pala einen hammer drauf, stellst dich direkt in nahkampfreicheweite.... und er sagt "ausser reichweite". 
dann gehst du ausser nahkampfreichweite und plötzlich geht es´, obwohl man definitiv ausser reichweite steht.

**Comment by dagochen** [comment]
In den 2 Videos sind 5-6 Szenen in denen es aufgetreten ist. Passiert nicht immer. Das sind jetzt knapp 20 Minuten Video, die man sich einfach mal anschauen müsste. Soll ich dir jetzt noch nen Timetable machen, damit du es erkennst!?

**Comment by Dotox** [comment]
Ich lass das mal so, bis du lernst in einem richtigen Ton mit mir zu sprechen.

**Comment by dagochen** [comment]
Mach halt Source zugänglich ich fix das ...?

**Comment by Faeleen** [comment]
Okay, ich glaube ich hab ein mögliches Missverständnis entdeckt.
Dago hat in seinem ersten Post das Problem angesprochen, dass die Anzeige und das was auf dem Server eigentlich passiert nicht immer übereinstimmen. (Ist mir auch schon aufgefallen, vor allem bei den Magiern und Legionären in BWL.) Also, dass man einen laufenden (!) Mob stunnt und jenen dann als Melee nicht mehr schlagen kann, obwohl der Mob in der Anzeige vor einem steht.
Allerdings hat er in seinem Video ein anderes Problem beschrieben. Nämlich, dass Mobs sich zum Spieler drehen, wenn man sie stunnt. (Passiert eben vor allen Dingen bei Rogues, wenn sie im Stealth einen Mob von hinten mit Fieser Trick stunnen.) Man kann natürlich hinter den Mob rennen und dann Schaden machen, aber soweit ich das mitbekommen habe, war das früher anders. Ein Mob blieb so stehen, wie man ihn gestunnt hatte und man musste nicht um ihn herumlaufen um (als Schurke) zu Meucheln. (Habe hier keine Quelle, aber falls jemand eine hat, kann er sie ja gerne noch liefern.)
Ich vermute, dass Dotox deshalb nichts merkwürdiges in dem Video aufgefallen ist, weil Dago Letzteres nicht explizit als Problem hier benannt hat und davon ausgegangen ist, dass jeder "den Fehler" automatisch bemerkt.

**Comment by hraesvelgr** [comment]
mir ist eute beim farmen aufgefallen, dass es vor allem an sehr abschüssigen gelände nahezu imemr zu solchen fehler kommt. in dem fall haben wir in den schwarmbauten in silithus gefarmt. in den sehr abschüssigen gängen, bei den gegnern mit großen hitboxen, gab es fast immer fehler bei der ausrichtung der gegner, wenn ich sie mit dem pala-hammer gestunnt habe. 

sind die gegner aus dem stun herausgekommen standen sie plötzlich immer ein, zwei meter neben der position, wo sie eigentlich vorher waren.

also..abschüssiges gelände vllt der fehler?

**Comment by dagochen** [comment]
Movement-System komplett löschen und vom aktuellen cmangos übernehmen :P Problem solved.

**Comment by hraesvelgr** [comment]
dann können wir wahrscheinlich 20 weitere bugs begrüßen...

**Comment by dagochen** [comment]
vermutlich ja :D

**Comment by Dotox** [comment]
Okay danke dir. Hab die Woche wieder mehr Zeit. Ich schau mir morgen mal das beschriebene Problem an.

**Comment by Dotox** [comment]
@hraesvelgr Kannst du mir vielleicht deinen nächsten Farm-Run aufnehmen (in dem man das Problem erkennen kann) und im Forum den Link schicken?

**Comment by hraesvelgr** [comment]
kann ich machen
