### ISSUE TITLE
übler tutor, fehlender spell

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1147]
der üble tutor sollte den spell dark whispers besitzen/nutzen und auf befreundete ziele (oder sich selber) im kampf casten.
npc: http://datenbank.welli-it.de/?npc=8548
spell: http://datenbank.welli-it.de/?spell=16587

http://wowwiki.wikia.com/wiki/List_of_mind_controllable_mobs
Vile Tutor - Located in EPL - Have the Dark Whispers buff which increases damage done by shadow spells by 35 for 10 minutes.

**Comment by dagochen** [comment]
@hraesvelgr magst du bitte hier einen extra post für das übernehmen machen? Bin grad sehr busy mit den fehlenden Zaubern ;) Das mach ich dann extra.
