### ISSUE TITLE
Hexenmeister T2 3er Bonus

### ISSUE THREAD

**Issue by Jura500** [ClassicWoW/Nefarian_1.12.1_Bugtracker#115]
Welches Verhalten wird beobachtet?
Trage ich 3 T2 Teile und ziehe eines der Teile an und wieder aus (also verliere und gewinne einmal den Bonus), ist mein Zauberschaden um 46 verringert (2x der T2-Bonus).
Wiederhole ich dieses Vorgehen, dann ändert sich der Zauberschaden nicht weiter.
Nach einem Relogg ist der Zauberschaden wieder so hoch wie er sein sollte.

Wie sollte es sich verhalten?
Wenn ich den Bonus verliere und wieder gewinne, sollte mein Zauberschaden so hoch sein wie voher.

Schritte zur Reproduzierung
3 T2 Teile tragen und eines davon aus- und anziehen.

**Comment by wahaxlekuke** [comment]
Das Problem scheint nicht mehr zu bestehen. Zumindest kann ich es nicht reproduzieren.

**Comment by wahaxlekuke** [comment]
Scheint doch nocht relevant zu sein. Ich habe ausversehen das T1 anstatt das T2-Set getestet.
