### ISSUE TITLE
fear buff hat manchmal keinen effekt

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1150]
jeglicher cc der klasse fear hat manchmal keinen effekt, obwohl der buff noch drauf ist. es laufen die ersten sekunden des buffs an, aber ich kann mich nach diesen 2-3 sekunden wieder frei bewegen, casten, etc. visuell bin ich immernoch im fear (schreiender totenkopf über mir), ich habe auch noch den debuff drauf, aber es zeigt keinerlei wirkung.
https://youtu.be/JyKYl3zlGQU?t=45 in dem video sieht amn, dass ich zwar gefeart bin, aber nur wenige sekunden , danach ist der buff noch aktiv, aber ich kann weiter rumrennen. und casten (den cast brech ich absichtlich ab)

liste der spells die scheinbar vorzeitig abbrechen, trotz sichtbarem buff (under construction)

ramsteins knockout https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1117
fear des hexenmeisters http://datenbank.welli-it.de/?spell=5782 , http://datenbank.welli-it.de/?spell=6213 , http://datenbank.welli-it.de/?spell=6215
dunkeleisenpulverisierer http://datenbank.welli-it.de/?spell=15283

**Comment by Loplin** [comment]
Die Frage aller Fragen.
Woran liegt das und wie ist es reproduzierbar?

**Comment by hraesvelgr** [comment]
bisher hat es wahrscheinlich gereicht, einfach loszulaufen, wenn man gefeart wurde, oder einen cast zu beginnen. manchmal funktioniert es, und manchmal nicht

**Comment by Dotox** [comment]
Ich denke das wurde mit dem Update hier: http://community.mmobase.de/updates-changelog/8198-update-16-10-2015-%5Balteractal-patch%5D.html behoben. Das ist mir auch schon aufgefallen. Wäre super, wenn du das auf dem Live-Server mal beobachten könntest.

**Comment by hraesvelgr** [comment]
ich werds mal beobachten, plus die palabug-fixes. wo ist eigentlich sabbaer, der sich für die positiven palafixes bedankt? :D

**Comment by Loplin** [comment]
Beim heutigen Nacht-ZG (17.11/2:00-3:30) raid wurde der Tank immer noch von Berserkern gefeart, trotz Furchtschutzzauber. Das ganze is mindestens 3 mal vorgefallen

**Comment by Dotox** [comment]
Hat nix mit diesem Thema zu tun :)
