### ISSUE TITLE
Herbeigezaubertes Essen und Wasser

### ISSUE THREAD

**Issue by Alphacka** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1151]
Das herbeigezauberte Essen und Wasser erhöht sich in regelmäßigen abständen. nach einigen Stunden stellt der Zauber nicht 2 sondern 10-20 Muffins, Wasser usw. her. Kann ziemlich nervig werden wenn man irgendwann jedes mal mit diesem Zauber 100 Wasser bekommt und sein Inventar leeren muss.

**Comment by Slimmer2** [comment]
Welches Level hat der Charakter mit dem du das festgestellt hast

**Comment by Sabbaer** [comment]
aehm, nein.... um so höher dein lvl wird, umso höher wird auch die anzahl, die du herbeizauberst....

**Comment by ircfelix** [comment]
Das ist vollkommen normal. Je höher dein Level, desto mehr kosten deine Zauber und desto mehr mana musst du reggen. Deshalb stellst du mit höherem level mehr vom low wasser her.

**Comment by Alphacka** [comment]
Bin jetzt level 9 und kann mittlerweile 12 Wasser mit einem Zauber herstellen.
falls das normal ist dann ok aber das sollte beim Zauber stehen, dort steht nämlich immernoch dass ich 2 Waser herstelle. Ich hatte einfach angst dass das irgendwann zu viel wird.. danke für die Antworten +1:

**Comment by hraesvelgr** [comment]
bitte schließ dann den beitrag :)
