### ISSUE TITLE
Kürbisdrops der Schlotternächte

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1152]
Die Kürbisdrops der Schlotternächte sind zurzeit nur für die Horde kaufbar.

Sie sollten auch für die allianz bei Katrina Schimmerstern in Ironforge zu kaufen sein. Ihr platz ist bei 33,67 neben der bank.

http://datenbank.welli-it.de/?item=20557 Kürbisdrops der Schlotternächte

http://datenbank.welli-it.de/?npc=15353 Katrina Schimmerstern

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1134
fehlt auch in der item-table.
