### ISSUE TITLE
Frenzy + Einlullender Schuss + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1153]
Istzustand
Aktuell schwanken die Timer für den einlullender Schuss bei Flammenmaul zwischen 8-10 Sekunden und bei Chromaggus ca. 10-15 Sekunden. 

Sollzustand
Beide Bosse hatten früher feste Timer.
Chromaggus: 15 Sekunden Intervall
Flammenmaul: 10 Sekunden Intervall

Quelle
Addon: SimpleTranqShot (simpletranqshot-2-0-beta28)
Im Quelltext des Addons sind explizit diese Zeitwerte hinterlegt.

Videos
Chromaggus: https://www.youtube.com/watch?v=75nYhpWkGA8
Die Frenzy-Warnung kommt exakt alle 15 Sek.

Flammenmaul: https://www.youtube.com/watch?v=D7gdwGwfBTY
Die Frenzy-Warnung kommt exakt alle 10 Sek.

Fix für Chromaggus:
m_uiFrenzyTimer = 15000;

Fix für Flamegor:
m_uiFrenzyTimer = 10000;

**Comment by Sabbaer** [comment]
http://wow.gamepedia.com/Chromaggus
Chromaggus frenzies every ten to fifteen seconds throughout the fight and must be kept tranquilized by hunters
http://wowwiki.wikia.com/wiki/Flamegor
Flamegor will enrage every 10 to 15 seconds
leider nicht richtig dago

**Comment by Rushor** [comment]
m_uiFrenzyTimer = urand(10, 15) * IN_MILLISECONDS;
m_uiFrenzyTimer = urand(10, 15) * IN_MILLISECONDS;

**Comment by dagochen** [comment]
Sabbaers Quellen sind vom  13:40, 7 June 2015 und vom 21:29, March 7, 2015. Geht man in der History zurück auf 2006, stehen keine festen Timer drin. Schaut man sich die Videos komplett an, kommt der Enrage auf die Sekunde genau. In 2 Videos nicht ein einziges mal, wo es von den 10 bzw. 15 Sekunden abweicht, obwohl es random sein soll, halte ich für sehr unrealistisch. Aber ich kann euch gerne noch 10 weitere Videos raussuchen, um es zu widerlegen...?

**Comment by Dotox** [comment]
Habs schon übernommen :)
