### ISSUE TITLE
Fehlender "Fischbot 5000"

### ISSUE THREAD

**Issue by DarkMueke** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1161]
Der Fischbot 5000 http://datenbank.welli-it.de/?npc=15079, welcher ab Patch Stand 1.11.1 hinzugefügt wurde (http://de.wowhead.com/npc=15079/fischbot-5000), ist in Booty Bay nicht verfügbar.

Die Fische die man für die  3 Quests (siehe Datenbank) von ihm bekommt, kann man aber angeln.

Die Belohnungen für diese Quests,

Nat Pagles Extremanglerstiefel - http://datenbank.welli-it.de/?item=19969
Extremgetestete Eterniumangelschnur - http://datenbank.welli-it.de/?item=19971
Glücksangelhut - http://datenbank.welli-it.de/?item=19972

sind folge dessen auch nicht erhältlich.

Wäre man in der Lage diese Items zu erhalten, würde man +15 Angelskill erhalten, was doch ein guter Bonus wäre im Angeln.

Bitte darum diesen NPC ins Spiel ein zu fügen.

Vielen Dank DarkMueke

**Comment by hraesvelgr** [comment]
bin mir ziemlich sicher,d ass ich den angelhut und die eternium angelschnur schon gesehen habe. 

ich denke, der bot spawnt einfach nur zu einer absolut schwachsinnigen zeit, die dadurch noch verrückt wird, weil es serverdowns gibt, und dadurch die timer zurückgesetzt werden?

**Comment by Rushor** [comment]
sollte doch nur während dem event spawnen oder nicht?

https://db.rising-gods.de/?event=15 - sry für falschen db link

**Comment by hraesvelgr** [comment]
ja soltle er. es gibt feste zeiten für seinen spawn. 
http://wowwiki.wikia.com/wiki/Stranglethorn_Fishing_Extravaganza

**Comment by DarkMueke** [comment]
Stimmt das war der Hacken ;)

Ich teste es diesen Sonntag 14:00 - 16:00 Server time und werde n Kommentar dazu machen.

lg

**Comment by dagochen** [comment]
Ich denke es wird hier ähnlich wie bei den Worldbossen sein. Wir sind vom Content her bei Patch 1.09. Wenn das erst mit 1.11 hinzugefügt wurde, wie du geschrieben hast, dann sollte das später bei uns freigeschaltet werden, um die Timeline einzuhalten.

Und bevor wieder welche jammern, dass Zauber und so auch zurückgepatch werden müssen auf 1.09: Das ist nicht möglich, da Talentebäume und co CLIENTSEITIG nicht verändert werden können.

**Comment by hraesvelgr** [comment]
das event scheint gerade in gange zu sein, jedenfalls hat ein spieler einen "eventfisch" gefangen. der fishbot fehlt allerdings in BB

**Comment by DarkMueke** [comment]
Die Fische hab ich in Massen^^

**Comment by Rushor** [comment]
wegen der zeitumstellung evtl eine stunde später nochmal reinschauen immer

**Comment by Slimmer2** [comment]
Fishevent sollte wenn vorhanden nur Sonntags sein

**Comment by shagu** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/849

Die Fische droppen immer, das Event scheint es aber nicht zu geben. Jedenfalls habe ich
als ich den Issue erstellt habe, Samstag sowie Sonntag zwischen 11:00 und 16:00 in Booty Bay nachgeschaut.
