### ISSUE TITLE
[Onyxia] Aggro Range zu gering

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1162]
Aktuell kann man bei Onyxia um sie rumlaufen und schon in Position gehen.

Dies sollte nicht so sein. 

Quelle

> When everyone is ready, the Main Tank charges in with everyone else following about two or three seconds behind. The main tank runs straight past Onyxia, pulling her to the far north side of the room so that she faces the wall. The best positioning takes a little practice and is a few steps in front of the wall. This is so that the main tank's back is to the wall to limit the effectiveness of her Knock Away ability and so that the main tank is the only one in front of her when she breathes fire.
> Everyone else must charge in two or three seconds after the main tank. If they wait longer, there is a danger of attracting attention from a freshly-spawned Onyxian Warder. If they go sooner, they run the risk of getting hit by Onyxia's Flame Breath attack. Don't get ahead of her!

http://wowwiki.wikia.com/wiki/Onyxia_(original)?oldid=1990078

> Wenn man das Ende des Lairs erreicht hat sieht man Onyxia in einem großen Runden Raum am Ende der Wand liegen und schlafen - man sollte jedoch den Aggro Radius nicht unterschätzen und am Eingang des Raumes warten und sich auf den Kampf vorbereiten (Allerdings nicht zu weit oben, damit man nicht im Respawn von Wächtern steht!)

http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/Onyxias%20Horst/onyxiaguide2.htm

**Comment by Rushor** [comment]
```diff
bool CheckCombatState()
        {
            if (!me->IsInCombat())
            {
                Map::PlayerList const& players = me->GetMap()->GetPlayers();
                for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                {
                    Player* player = itr->GetSource();
                    if (player->IsAlive() && !player->IsGameMaster() && player->IsWithinDist2d(me, 35.0f))
                    {
                        // Player entered Triggerarea
                        me->SetInCombatWith(player);
                        me->AddThreat(player, 1.0f);
                        player->SetInCombatWith(me);
                        me->SetInCombatWithZone();
                        AttackStart(player);
                        return true;
                    }
                }
            }
            else
            {
                Map::PlayerList const& players = me->GetMap()->GetPlayers();
                for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                    if (itr->GetSource()->IsAlive() && !itr->GetSource()->IsGameMaster())
                        return true; // Return when at least one player is alive

                EnterEvadeMode();
            }
            return false;
        }

        bool CheckInRoom() override
        {
            if (me->GetDistance2d(me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY()) > 95.0f)
            {
                EnterEvadeMode();
                return false;
            }
            return true;
        }

        void UpdateAI(uint32 diff)
        {
            //! UpdateVictim() replacement
            if (!CheckCombatState() || !CheckInRoom())
                return;
```

haben wir mal so gefixt damals

35 yards sollte eig ok sein, evtl gibts dafür aber auch noch nen areatrigger, dann könnte man es mit nem areatriggerscript fixen so wie bei der schlachtwache sartura in aq40

**Comment by dagochen** [comment]
Geht auf Nefarian wesentlich leichter, weil Wahax da was geschrieben hatte, sodass man für den Mob einfach nur die Aggrorange erhöhen muss. Ich wusste jetzt nur nicht mehr, obs in der DB war oder im Script beim Laden der Kreatur. Aber das wird er wohl dokumentiert haben, sodass es wirklich nicht so schwer sein sollte ;)

**Comment by Rushor** [comment]
evtl kann man dann ja gleich mal das 

```c++
bool CheckInRoom() override
        {
            if (me->GetDistance2d(me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY()) > 95.0f)
            {
                EnterEvadeMode();
                return false;
            }
            return true;
        }
```

mit einbauen, bei den meisten servern kann man ony ja durch die ganze inni ziehen :D

**Comment by Dotox** [comment]
@Rushor Ich glaube fast, dass wir das mit drin haben - bin mir aber grad nicht sicher. Schau mir das später mal an - vielleicht ist der Trigger auch falsch plaziert oder gar nicht vorhanden :D

Danke schonmal!

**Comment by dagochen** [comment]
Wenn ein Spieler so weit weg ist bzw. wegzulaufen versucht, sollte Onyxia wie viele andere Bosse auch, den oder die Spieler zu sich porten, laut den oben genannten Quellen. Resetten sollte sie also nicht, sprich das EnterEvadeMode wäre falsch :(

**Comment by Rushor** [comment]
stimmt zu 1.x war es so, kann man bei wowwiki in der history nachlesen. das hatte ich leider ganz vergessen.
auf dem aktuellen retail (6.x) resetet sie aber tatsächlich wenn man die haupthöhle verlässt

**Comment by dagochen** [comment]
In ScriptDev gibt es sowas: 
```c++
void ScriptedAI::DoTeleportPlayer(Unit* pUnit, float fX, float fY, float fZ, float fO)
```
Das ist genau dafür da ;)
