### ISSUE TITLE
NPC Varian Wrynn fehlt auf der Insel Alcaz

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1165]
Welches Verhalten wird beobachtet?
Der NPC Varian Wrynn ist nicht vorhanden.

Wie sollte es sich verhalten?
Der NPC Varian Wrynn sollte sich im Keller auf der Insel Alcaz aufhalten.

Schritte zur Reproduzierung
Hingehen und gucken, man sieht ihn nicht.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://vignette2.wikia.nocookie.net/wowwiki/images/c/cc/VarienWrynnKingofStormwind.jpg/revision/latest?cb=20091218121922

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?npc=11699

Quellen:
http://wowwiki.wikia.com/wiki/Varian_Wrynn - mit STRG + F nach "alcaz" suchen. Dort steht, dass er in classic auf der Insel steht.

**Comment by Rushor** [comment]
By Fruitcase (4,142 – 1·4·18) on 2008/08/24 (Patch 2.4.3)		
King Varian Wrynn used to be in Alcaz Island in the tunnel underground , until patch 1.9 ( AQ opening ) he was removed and an Elite naga toke his place , his current place is Unknown but he will apear in Wotlk

some proof for this

**Comment by Sheed90** [comment]
Dann ist das wohl leider hinfällig, kann geclosed werden. :-(

**Comment by Dotox** [comment]
:(
