### ISSUE TITLE
npc schlagen mehrfach zu

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1167]
heute beim kampf mit marli musste ich für wenige sekunden als tank einspringen. ich wurde von ihr mit scheinbar einem schlag getötet.

allerdings hat das kampflog 3 angriffe angezeigt, zu je 2000+ schaden
das waren alles normale autohits, und alle kamen innerhalb von milisekunden, bzw in der animation eines (1) angriffs.

ähnliches haben die untoten auf dem friedhof in den WPL mal gemacht, aber das wurde glaube ich gefixt. 
tl;dr: manche npc scheinen mehrfach mit einem hit zuzuschlagen, ähnlich dem windfury des schamanen.

**Comment by Dotox** [comment]
Marli hat auch den Spell: http://datenbank.welli-it.de/?spell=3391

**Comment by hraesvelgr** [comment]
laut http://wow.ftpi.de/showtopic.php?threadid=124

sollte sie diesen skill aber nicht haben. ich habe auch sonst nichts dazu gefunden, dass sie mehrfach angreift. 
 in der db ist der spell auch nicht eingetragen http://datenbank.welli-it.de/?npc=14510#abilities

**Comment by Dotox** [comment]
Ne - Die Datenbank und deren Spell-Einträge haben keine wirkliche Aussagekraft. Es gibt ein simples System, bei dem man die Spells einfach in der Spalte des jeweiligen NPCs einträgt und schon wird es Ingane genutzt. Ohne wirkliche Timer und weitere Funktionen. Allerdings werden hunderte Kreaturen über C++ Scripte gesteuert, in denen die Spells eingetragen sind. Diese werden nicht in der Datenbank-Ansicht angezeigt. Das hab ich glaub ich schonmal irgendwo so deutlich versucht zu erklären. Daher kann und sollte die Datenbank-Ansicht nicht als Richtwert für irgendwelche Informationen bezüglich Spells und deren Kreaturen (Bosse) gelten.

Für ganz einfache NPCs, für die kein C++ Script vorhanden ist (z.B. irgendwelche NPCs in Westfall oder Brachland, die keine besondere Funktion haben) kann das verwendet werden, aber nicht für Bosse oder dergleichen.

Ob der Spell jetzt falsch eingetragen ist, müssen wir recherchieren.

**Comment by hraesvelgr** [comment]
ich denke er ist schon falsch eingetragen. hab mir mehrere bosstaktiken durchgelesen, aber nirgendwo wird darüber gesprochen. das einzige,w as bei marli zu beachten war, ist das einnetzen verbunden mit dem aggrowipe, sowie der giftblitz. über plötzlichen burst-dmg wird nichts gesagt.

**Comment by Dotox** [comment]
Auf HordeGuides.de war das glaube ich mal zu lesen. Ich schau später / morgen mal bei archive.org

**Comment by dagochen** [comment]
strike-us-if-you-can hat nix über den Zauber.
Quelle: http://www.strike-us-if-you-can.de/main/frame/raidhighlvl.htm

**Comment by g3n3a** [comment]
Trash ist allgemein ne sehr weit verbreitete Fähigkeit. Ist immer wieder lustig bei den 3 Drachen in BWL.

**Comment by hraesvelgr** [comment]
bei drachen und so versteh ichs ja...aber bei priesterinnen? das passt einfach absolut nicht in die lore. 

zumnal ich auch denke,d ass der heal von mar'li viel zu gering ist. 
in den guides schreiben die von einem "enormous amount of hp"... in der db steht ein wert von 3,5k heal. das beißt sich irgendwie.

**Comment by g3n3a** [comment]
Mit Lore kannst du sowas nicht begründen. Mobs mit 'Henker' und 'Skalpierer' im Namen haben die Execute-Fähigkeit. Bei Mobs mit 'Töter' im Namen haben das aber nur einige wenige und nicht entweder alle oder keiner.

**Comment by dagochen** [comment]
Warum closed?

**Comment by Rushor** [comment]
hraesvelgr schrieb:

>bei drachen und so versteh ichs ja...aber bei priesterinnen? das passt einfach absolut nicht in die lore.

>zumnal ich auch denke,d ass der heal von mar'li viel zu gering ist.
>in den guides schreiben die von einem "enormous amount of hp"... in der db steht ein wert von 3,5k heal. das beißt sich irgendwie. es war im kamüpf auch nie nötig sie zu kicken.

**Comment by hraesvelgr** [comment]
ich mach evtl mal einen neuen dazu, der sich speziell auf marli bezieht. hier ist zuviel diskussion und zuviel unfug von mir  drin. deshalb close :)

**Comment by dagochen** [comment]
möche in bastion haben den thrash zauber sogar 2x :)

**Comment by hraesvelgr** [comment]
auf die spells in den dbs verlass ich mich nicht mehr so gern. gerade bei wowhead steht da verdammt viel unsinn drin, und auch ungerechtfertigt doppeltes. zumal bei marli der spell ja auch nicht eingetragen ist, und sie in trotzdem nutzt. (hatte dotox ja auch mal erklärt,d ass das über evantAI läuft)
trotzdem weiger ich mich zu glauben, dass ein spinnen/humanoider boss so etwas nutzt. bei thekal oder arlokk würd ich das total legitim finden, aber nicht bei marli.
