### ISSUE TITLE
[Quest] Die ultimative Täuschung`+ FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1168]
Die Quest ist bei uns aktuell nicht wiederholbar, wodurch man sich für ein Item der Folgequest "Schlachtrüstung des Gefolgsmanns" entscheiden muss.

Eigentlich sollte sie wiederholbar sein. Die Quellen sind in http://community.mmobase.de/hilfe-und-support/7471-felszornarmschienen-quest-mehrfach-machbar.html zitiert.

FIX:
```sql
UPDATE quest_template SET SpecialFlags = 1 WHERE entry = 8829;
```

**Comment by nightblizard** [comment]
Wurde übernommen, vielen Dank!
