### ISSUE TITLE
Seduce wirkt obwohl Gottesschild aktiv ist

### ISSUE THREAD

**Issue by lysethea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1170]
Istzustand:
Wenn die Sukku Seduce auf den Pala wirkt und man während dem Cast Bubble anschmeißt wird man in der Bubble seduced. Macht man die Bubble an bevor die Sukku den Cast beginnt ist man korrekterweise immun.
![seduce bubble](https://cloud.githubusercontent.com/assets/14354192/10676486/ce377726-7906-11e5-9722-b897a2a71c58.jpg)

Sollzustand:
Wie im Tooltipp von Gottesschild steht, sollte man gegen Zauber 12 Sekunden lang immun sein.
Sprich auch wenn man während des Cast Gottesschild zündet, sollte man immun gegen den Cast sein. 

Reproduzierbar ist es indem man in einem Duell während dem casten von Seduce Gottesschild nutzt.

**Comment by hraesvelgr** [comment]
das kann durchaus mit dem serverlag zu erklären sein. was hier wirklich fehlen würde wäre ein entfernen alelr schadenszauber, die gottesschild entfernen würde, und das ganze nochmal eine halbe sekunde nachdem gottesschild gewirkt wurde. so kann man wenigstens den debuffs entgehen. direkte schadenszauber können aber weiterhin, kurz nachdem gottesschild oben ist, töten

**Comment by dagochen** [comment]
Wird auch ähnlich sein wie die Ingi-Reflektoren, die nur funktionieren wenn sie vor "Abflug" des Pyros aktiviert werden. Zauber die bereits "unterwegs" sind, gehen durch, weil die Berechnung, ob sie treffen oder widerstanden oder reflektiert werden, bereits durch ist.

**Comment by hraesvelgr** [comment]
wahax hatte es doch mal so geändert, dass schadenszauber (also direkte) erst dann berechnet werden, wenn der spell tatsächlich trifft. zumindest für den gottesschild.

**Comment by lysethea** [comment]
Die Bubble habe ich ja vor dem "Abflug" des Seduce gezündet

**Comment by dagochen** [comment]
Naja Seduce hat nicht wirklich ne Flugzeit oder? Gibt also 3 Möglichkeiten: Entweder wird der Zauber nicht korrekt geblockt von Gottesschild oder es ist Clientseitig zu spät zu sehen, dass der Zauber gewirkt wird oder es ist einfach das die Sukki total buggy ist :)

**Comment by Ilikegyoza** [comment]
Das gleiche gilt auch für #1103

**Comment by dagochen** [comment]
Den hatte ich noch garnicht gesehen. Damit ist es dann wohl ein Sukki-Problem.

**Comment by lysethea** [comment]
Jo, da haste Recht. Gibt nicht wirklich ne Flugzeit. Ist nur sehr nervig :>

**Comment by lysethea** [comment]
Noch nicht mal ein Label? :( 
Wird es dann einfach hingenommen "weil isso"?
