### ISSUE TITLE
hallows end /apfelbottich

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1171]
die apfelbottiche zum event "hallows end" sollten nach anklicken bis zu 5 äpfel (http://datenbank.welli-it.de/?item=20516) ins inventar adden.

momentan haben sie keinerlei effekt

apfelbottich: http://datenbank.welli-it.de/?object=180523 

http://wowwiki.wikia.com/wiki/Apple_Bob

**Comment by Loplin** [comment]
Frage am Rande:
Kann man Fehler bezüglich der Datenbank auch hier melden?
mir sind einige Objekte (vor allem erze und Kräuter) untergekommen, bei denen die Seite einfach nicht geladen wird.

**Comment by hraesvelgr** [comment]
dotox will die DB eh mal überarbeiten
find den beitrag zu seinem comment grad nicht.
