### ISSUE TITLE
alterac: beschwörung von ivus /druiden

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1173]
die druiden beschwören zwar momentan korrekt den stein, stehen danach aber brainafk in der gegend herum. 

sie sollten anfangen an dem stein genau den gleichen spell zu casten, wie die spieler. 

anders kann ivus nicht beschworen werden, da es die druiden + 10 spieler braucht. 

druiden: http://datenbank.welli-it.de/?npc=13443
erzdruide: http://datenbank.welli-it.de/?npc=13442
kreis des rufens: http://datenbank.welli-it.de/?object=178670

note: werden die druiden beim casten unterbrochen, resetten sie aber casten nicht weiter. das wäre blizzlike, wurde aber allgemein als bug beschrieben.
blizzlike bug einfügen oder nicht, eure entscheidung.

**Comment by Dotox** [comment]
Die Druiden werden nicht benötigt, um den Boss zu beschwören. Das ist nur visual. Schaus mir aber gerne nochmal an :)

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/npc=13419/ivus-the-forest-lord#comments:id=291500
hier steht dass die druiden mit-channeln, und eben unterbrochen werden können, wodurch oben genannter bug entsteht.

**Comment by Schmoha** [comment]
Mag vllt hilfreich sein:
https://youtu.be/shNu2gJyVd8?t=14m32s

https://youtu.be/HFiveTjFY9g?t=4m48s

Grüner spell danach nix.

**Comment by hraesvelgr** [comment]
level 100...

nicht sicher ob offi oder privatserver. sry, aber das sagt nahezu nix aus.

**Comment by Rushor** [comment]
es gibt keinen vernünftigen wod privatserver mit nem fix dazu :D das kann nur vom offi sein

**Comment by hraesvelgr** [comment]
aich denke langsam, ihr habt recht. hab mir mehrere videos angeschaut (bc) und auch auf einigen blogs scheint es so zu sein: hier die version für horde: http://wowrampus.tumblr.com/post/69305782376/the-summoning-of-lokholar-the-ice-lord-in-alterac
die primalistin steht nur in dem kreis und macht nichts, während die spieler channeln.

ich versteh aber nicht ganz, wie das unterbrechen der druiden nach dem setzen des kreises noch auswirkungen haben soll, wie es so oft als bug beschrieben wurde.
