### ISSUE TITLE
spawn von DM büchern / container 

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1174]
momentan sind die spawnpunkte der bücher in dm so, dass es in dm ost, nord und westinsgesamt 9 feste spawns gibt, die immer da sind.

es sollte jedoch 9 spawnpunkte geben, von denen nur einer belegt ist. 
ergo: in jeder instanzen-ID von dire maul sollte es nur 1 buch(container) geben, das an einer der spawn 9 locations in dire maul liegt.
>Although all of these books can drop from all of the bosses in Dire Maul. they can also drop from A Dusty Tome. This tome can be found on fixed locations throught Dire Maul. the spawn of the tome however is random at one of the fixed locations.
http://vbd.fr.yuku.com/topic/177/farming-forors-compendium-and-all-class-specific-books#.Vi4GICsSn4Y

zweite sache: oft kommt es vor, dass man die container doppelt looten kann/zwei container an einem platz liegen, ineinander. auch droppen zT mehrere bücher aus einem container. (wir haben aus einem spawn 4 bücher rausgelootet, das ist definitiv zuviel)

ausserdem scheint es den "staubigen folianten" zweimal zu geben (http://datenbank.welli-it.de/?search=verstaubter+foliant), einen mit und einen ohne forors compedium? ich hoffe, der mit forors liegt in dm, und der andere existiert ingame garnicht. 

staubiger foliant: http://datenbank.welli-it.de/?object=179547

**Comment by hraesvelgr** [comment]
frage: ist die dm nord-id die gleiche wie die für dm west (oder dm ost)? oder sind das unterschiedliche instanzen?

**Comment by Dotox** [comment]
Sind unterschiedliche :)

**Comment by hraesvelgr** [comment]
was trennt dann zb die dm west id von der dm nord id, da man sich ja ohne durc ein portal zu durchschreiten von west nach nord bewegen kann ?!

also vom west-portal kommt man bis zum dm nord endboss.

**Comment by dagochen** [comment]
Betrifft ja nicht nur die DM-Bücher. Das liegt am gesamten Spawnsystem. Rares spawnen alle 20 Minuten, Kräuter und Erze sind verbuggt und neben den Büchern in Düsterbruch betrifft das Problem noch die Hoodoohaufen in ZG, die Kräuter in ZG, die Wucherborken-Pflanzen in Düsterbruch, alle Erze in Instanzen und Kisten in Inis und der offenen Welt.

**Comment by Bananendieb** [comment]
Zur DM id: Nord und West sind direkt verbunden ohne Instanzportal, und den König der Gordok-Debuff bekommt man sogar in Ost. Außerdem wird DM als eine Instanz zurückgesetzt durch ResetInstances() . Wie können das unterschiedliche ids sein?
