### ISSUE TITLE
Item: Tunnelhacke ( Grün )

### ISSUE THREAD

**Issue by berion1982** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1176]
Ist mit folgendem Verweis belegt:

"Dient auch als Spitzhacke"

Allerdings stimmt dies nicht, sprich egal ob man die Spitzhacke im Inventar hat oder angelegt hat das Ergebnis bleibt das Gleiche.

Link zur DB: http://datenbank.welli-it.de/?item=756

**Comment by Loplin** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/40

(Bitte Suchfunktion nutzen)

**Comment by berion1982** [comment]
Mh sry zu diesem Item hab ich nichts gefunden und das kürchnern und minen das gleiche ist wusste ich nicht...

**Comment by Loplin** [comment]
Kein Problem
Immer fleißig am reporten bleiben :)
