### ISSUE TITLE
Druide Wilde Attacke

### ISSUE THREAD

**Issue by bambutscho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1177]
sers,

beim druiden klappt die wilde attacke nicht richtig. gegner kann zwar angecharged werden,
es unterbricht dann aber keine 4sek jegliches zauberwirken wie es sein müsste.

quelle : siehe tooltip

bitte um fix.

lg bambi

**Comment by dagochen** [comment]
Grad Dudu im Duell gegen Pala, hat problemlos gefunzt.

**Comment by bambutscho** [comment]
mehrere duelle gegen magier gemacht, die konten nach dem charge problemlos nova zünden u blinken, also funzt es nicht!

**Comment by Sabbaer** [comment]
klärt mich auf, es sollte doch bloß silencen, wenn derjenige einen cast macht in dem moment, und nur die zauberschule?

**Comment by bambutscho** [comment]
sollte so sein wenn du zb lichtblitz castest, in dem moment angecharged wirst, sollte kein lichtblitz mehr möglich sein. klappt aber iwie nicht so wirklich. videos müsste ich mal auf youtube suchen..

**Comment by dagochen** [comment]
Es sind diese 2 Spells: http://datenbank.welli-it.de/?spell=16979 und http://datenbank.welli-it.de/?spell=19675

Der 2. wird durch den 1. ausgelöst und hat den Effekt Interrupt. Interrupt macht folgendes:

```c++
void Spell::EffectInterruptCast(SpellEffectEntry const* /*effect*/)
{
    if (!unitTarget)
        return;
    if (!unitTarget->isAlive())
        return;

    // TODO: not all spells that used this effect apply cooldown at school spells
    // also exist case: apply cooldown to interrupted cast only and to all spells
    for (uint32 i = CURRENT_FIRST_NON_MELEE_SPELL; i < CURRENT_MAX_SPELL; ++i)
    {
        if (Spell* spell = unitTarget->GetCurrentSpell(CurrentSpellTypes(i)))
        {
            SpellEntry const* curSpellInfo = spell->m_spellInfo;
            // check if we can interrupt spell
            if ((curSpellInfo->GetInterruptFlags() & SPELL_INTERRUPT_FLAG_INTERRUPT) && curSpellInfo->GetPreventionType() == SPELL_PREVENTION_TYPE_SILENCE )
            {
                unitTarget->ProhibitSpellSchool(GetSpellSchoolMask(curSpellInfo), GetSpellDuration(m_spellInfo));
                unitTarget->InterruptSpell(CurrentSpellTypes(i), false);
            }
        }
    }
}
```

Und genau das mit Heal habe ich vorhin probiert und der Paladin konnte für 4 Sekunden keine Holyzauber benutzen. Irgendwas musst du da anders gemacht haben bambi ;)

**Comment by Sabbaer** [comment]
vll hat der gegner dich ja gefake casted bambu? also hab das jetzt auch mal getestet und klappt immer. ich kann dann 4 sek lang nichts mehr machen als pala

**Comment by Loplin** [comment]
Eine weitere frage die es zu klären gilt:
Wird der silence und auch der unbeweglichkeitszauber erst aktiv, wenn man am Gegner dran is., oder sobald man feral charge wirkt.
mir ist schon des öfteren passiert, dass ich zB einen Hexer angecharged habe, welcher gerade am fear casten war. Ergebnis: hexer hat den silence debuff auf sich und ich lauf gefeard davon.
Is das auf den server delay zurückzuführen? Sollte ja entweder das eine, oder das andere durchgehen.

**Comment by dagochen** [comment]
ist mir auch schon aufgefallen. Ich weiß nur leider nicht ob es zu Classic schon so war, aber man konnte z.b. Krieger die gecharged sind mit Streuschuss im Charge aufhalten. Demnach müsste der Fear den Charge unterbinden (und damit auch den Root-Effekt + Silence).
