### ISSUE TITLE
Krieger: Sturmangriff

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1179]
Sturmangriff sollte das Ziel 1 Sekunde stunnen und man sollte eine Charge Animation erhalten und auch Wut bekommen

Stellenweise hat man keine Animation und steht bei drücken des Spells direkt am Gegner, als würde man hin geportet werden und der Gegner bekommt keinen Stun ab und man bekommt auch keine Wut.

Im PvP ist das nicht so toll da bei auftreten des Bugs, der Gegner den man ancharget nicht gestunt wird und wenn er einen Cast ausführt, dieser auch nicht unterbrochen wird.

http://datenbank.welli-it.de/?spell=11578

**Comment by Loplin** [comment]
Hat der Gegner vl Trank der freien Aktion drin oder ähnliches?
Is dir aufgefallen wann der Fehler genau auftritt/wie er zu reproduzieren is
Vl hilft ja ein video von solchen charges

**Comment by Slimmer2** [comment]
Das Tritt nicht nur bei PvP auf und wenn dann sollte man Wut bekommen und auch nicht instant am Gegner stehen.

**Comment by Loplin** [comment]
Bugs die nicht reproduzierbar sind, sind denk ich sehr schwer zu fixen, da keiner weiß, wie sie zustande kommen.
Ein Video wär da sicher nicht verkehrt...

**Comment by Dotox** [comment]
Genau, einfach ein Video anhängen, dann ist es für uns einfacher :)

**Comment by Slimmer2** [comment]
Werde das dem Reporter weitergeben.

**Comment by Dotox** [comment]
Hab das auf dem Testserver getestet und konnte nichts feststellen. Das einzige was mir aufgefallen ist, ist dass der Stun ziemlich oft wiederstanden wird. Animationsprobleme o.Ä hatte ich nicht. Am besten mal das Video posten, wenn ihr Zeit habt.

**Comment by Slimmer2** [comment]
Das Problem tritt erst seit dem Letzten großen Serverpatch auf.
Wenn man knapp vor Kampfbeginn die Fertigkeit used tritt der Bug auf.
Könnte evtl auch an Delay liegen.

**Comment by Testear** [comment]
"Das Problem tritt erst seit dem Letzten großen Serverpatch auf."
Das ist nicht korrekt. Den Bug gibt es schon länger. Ich habe nur nie einen Report verfasst, weil ich diesen Bug nicht reproduzieren konnte.

**Comment by Slimmer2** [comment]
Kann auch nur das schreiben was mir weitergegeben wird.

**Comment by Dotox** [comment]
Ich konnte vorhin das Problem bei einer Änderung, welche mit dem letzten großen Update aufgespielt wurde, beobachten. Hatte leider keine Zeit mehr, werde es aber morgen beheben.

Möglich wäre auch, dass es verschiedene Ursachen für das Problem gibt - eine war zumindist in dem letzten großen Update enthalten.
