### ISSUE TITLE
Krieger: Abfangen

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1180]
Abfangen sollte das Ziel 3 Sekunde stunnen und man sollte eine Charge Animation erhalten und auch Wut verkommen

Stellenweise hat man keine Animation und steht bei drücken des Spells direkt am Gegner, als würde man hin geportet werden und der Gegner bekommt keinen Stun ab.
Ob Wut auch verbraucht wird wenn der Bug auftritt, weis ich nicht.

Im PvP ist das nicht so toll da bei auftreten des Bugs, der Gegner den man ancharget nicht gestunt wird und wenn er einen Cast ausführt, dieser auch nicht unterbrochen wird.

Es wird dann auch kein Colldown ausgelöst

http://datenbank.welli-it.de/?spell=27577

Evtl gleicher Fehler wie bei https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1179

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1179
