### ISSUE TITLE
rep robot aus brd

### ISSUE THREAD

**Issue by Schnuefffelstueck** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1182]
es ist doch schon bekannt das man den nicht aufheben kann den plan.
ich habe einen sceenshot davon gemacht als beweis. wo kann ich den jetzt hochladen?

**Comment by Slimmer2** [comment]
Das müsste der Bauplan sein der bei dem Boss in den Raum liegt.
Den kann man auch nicht aufheben sondern, dort können nur Inigs den Bauplan direkt erlernen.

**Comment by Schnuefffelstueck** [comment]
ja nun habe ich ihn

**Comment by Sabbaer** [comment]
gz ;)

**Comment by dagochen** [comment]
ticket schließen nicht vergessen ;)
