### ISSUE TITLE
Jäger autoshoot

### ISSUE THREAD

**Issue by stormDE** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1185]
Guten Tag,

ich wollte ein Problem des Jägers zu Thema bringen.
und zwar ist es so dass wenn der Jäger auf Distanz eines Mob ist, nicht automatisch in den Autoshoot wechselt , wenn der Mob mit dem "rechtsklick" fokussiert wird. der Jäger versucht Ihn per Nahangriff anzugreifen was natürlich nicht Funktioniert da mann ja nicht nah genug dran ist. ich muss immer einen fernagriff cast nutzen oder Extra den Autoshoot anklicken damit auf fernangriff übergangen wird.

andersherum besteht das selbe Problem, bin ich im autoshoot und der Mob kommt auf mich zu gerannt, wechselt der Hero nicht in den nah angriff, und möchte den mob weiterhin mit der fernwaffe angreifen was nicht funktioniert das die mindest distanz nicht eingehalten ist. 

ich hoffe ich konnte das Problem verständlich beschreiben

viel Erfolg weiterhin
Mfg Lorus

**Comment by dagochen** [comment]
Gabs diesen automatischen Wechsel zu Classic überhaupt schon?

**Comment by hraesvelgr** [comment]
nope.

TBC Patch 2.0.6 (2007-01-23): Auto Shot will be automatically enabled if the Hunter steps out of melee range while in combat with target.

**Comment by dagochen** [comment]
Bin trotzdem dafür das wir es implementieren. Wir nutzen ja auch allen möglichen anderen Komfort, warum dann nicht auch sowas? Dualspecc, Schnellreise, XP-Boost gabs auch alles erst viel später, dann können wir solche Bequemlichkeiten ruhig auch haben?

**Comment by hraesvelgr** [comment]
es gibt keinen dualspecc, und den komfort der geringen umskillkosten sind damit erklärt, dass wir keine  blizzlike serverpopulation bieten können, weshalb hybridklassen stärker gefragt sind, mehrere speccs zu besitzen, und diese dann einen extremen nachteil gegenüber anderen klassen hätte, zb schurken oder magiern.

ausserdem wirkt sich so eine veränderung der spielmechanik auch aufs pvp aus. wir wollen doch nicht, dass die hunter noch mehr abgehen als ohnehin schon...
