### ISSUE TITLE
kathrina schimmerstern /eventverlinkung

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1186]
siehe : https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1152

die gute ist jetzt dauerhaft da und nicht ans event gebunden.

**Comment by Dotox** [comment]
Schon behoben nur ist der Server noch nicht neugestartet worden :)

**Comment by hraesvelgr** [comment]
aso :)
