### ISSUE TITLE
molten metal vs segen der freiheit

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1187]
wenn man den debuff von "geschmolzenes metall" auf sich trägt, und "segen der freiheit" castet, wird der debuff nicht dispellt. 

da der debuff ein "normaler" verlangsamungszauber ist (verringert angriffstempo und lauftempo um x), sollte er auch dispellt werden.

molten metal http://datenbank.welli-it.de/?spell=5213
segen der freiheit http://datenbank.welli-it.de/?spell=1044

**Comment by Sabbaer** [comment]
also auf dem offi server geht es nicht mit segen der freiheit weg... ka ob das so richtig ist, ob es zu vanilla auch so war. jedoch hab ich jede woche solo bwl gemacht ab wotlk und da kann man mit segen der freiheit den debuff durch die fallen nicht wegmachen

**Comment by hraesvelgr** [comment]
ist es denn der gleiche spell? den  spell den ich meine ist von smoldar aus searing gorge

**Comment by Sabbaer** [comment]
ah ok, scheint doch ein anderer debuff zu sein, kk ich hab gedacht, dass sei der selbe.
sry

**Comment by Loplin** [comment]
Hab es versucht zu testen, konnte Soldar http://datenbank.classic-wow.org/?npc=8278 aber nicht vorfinden da es ein Raremob is
