### ISSUE TITLE
ZG Gahz'ranka Massive Geyser

### ISSUE THREAD

**Issue by Loplin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1191]
Welches Verhalten wird beobachtet?
Gahz'ranka's Spell Massive Geyser macht zu viel Schaden.
Er macht in etwa 1,5k - 2k dmg

Wie sollte es sich verhalten?
Der kick sollte maximal 500 Schaden machen. im schnitt macht er nur 250 (siehe Quellen)

Zusätzliche Informationen (Screenshots, Videos, etc.)
Gahz'ranka
http://wowwiki.wikia.com/wiki/Gahz'ranka

Achtung laut!!! und schlechte Quali. trotzdem gut zu sehen kick bei 1:17 und 2:22 http://www.myvido1.com/gWwIleWFTOy4UbKBXYX9WP_gahz-ranka

Video vom 26.9.2006, kick bei 0:36, noch ein kick bei 1:16 (man beachte auch den Grp-dmg) sowie 1:57
https://www.youtube.com/watch?v=QcYVN9iz5oI

Auf unserem Server:
Video vom 26.10.2015 - Kick macht 1,5k - 2k dmg
kick sehr gut zu sehen bei 0:38 0:52 1:07 1:21 1:38 1:55
https://www.youtube.com/watch?v=ll4WjO2KRLE

**Comment by dagochen** [comment]
Zauber des Massiven Geysir: http://datenbank.welli-it.de/?spell=22422
Massiver Geysir: http://datenbank.welli-it.de/?npc=14122

Die Zauber im wowwiki sind vertauscht. Der Slam schleudert einen hoch und wiped die Aggro temporär (und macht bei uns zu viel Schaden). Das Problem ist das gleiche wie bei Drek'Thar, da bei uns der Slam mit dem Waffenschaden skaliert und ebenfalls von dem Multiplikator profitiert. Dadurch steigt der Schaden abnormal stark an.

**Comment by Loplin** [comment]
Versteh ich das richtig?
beim oben beschriebene Problem handelt es sich um den Graz'Rankha Slam und nicht um den Geysir?

**Comment by dagochen** [comment]
Jep. 

Slam = Weit nach oben kicken und extrem viel Schaden + Aggro Wipe für paar Sekunden

Geysir = Kleiner knockback um die Stelle wo der Geysir blubbert ohne Aggro Wipe. 

In wowwiki ist es genau falsch rum drin. Wenn man sich Videos von damals anschaut sieht man auch das der Boss direkt nach dem hochkicken des Tanks durch die Gegend irrt, ein Ziel außerhalb des Hochkick-Effekts sucht und nach wenigen Sekunden wieder zum Maintank zurückschwimmt. 

Aus diesem Grund steht in Guides auch drin, dass sich alle den Kick abholen sollen, damit der Tank die Aggro eben nicht verliert. Selbst Hunter sollen sich den holen, oder durch Totstellen die Aggro direkt wieder verlieren.
