### ISSUE TITLE
Wiederbeschaffende Schätze

### ISSUE THREAD

**Issue by mighty2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1195]
Hi,

die Truhe für den Familienschatz der Garrets hat einen viel zu langen respawn Timer. Die Truhe soltle garnicht despawnen wenn man lootet, damit man mit einer Dungeon Gruppe die Quest reihum erledigen kann. So war das früher jedenfalls. 

http://datenbank.welli-it.de/?quest=1360

**Comment by hraesvelgr** [comment]
ich konnte da auch keine flamebeiträge von spielern finden.

**Comment by Slimmer2** [comment]
Dies betrifft alle lootbaren Questitem, wie das Manuskript in Bft oder das Buch in Kloster

**Comment by hraesvelgr** [comment]
dann kann ich wohl eher auf https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1174#issuecomment-152732793 verweisen. hängt wohl damit zusammen.

**Comment by mighty2** [comment]
Den ersten comment verstehe ich nicht, der zweite comment verweist auf einen thread der rein garnix mit meiner Problemschilderung zu tun hat....

**Comment by hraesvelgr** [comment]
das macht nix :)

**Comment by dagochen** [comment]
Nein sind 2 verschiedene Dinge. Das eine ist Spawn von Dingen, wo aus einer möglichen Anzahl an Spawns (n) nur eine bestimmte Menge an Spawns (m) aktiv sein darf, mit m < n.

Während der Respawn von Gameobjects wie bei den Questitems einfach nur zu hoch eingestellt ist.

**Comment by mighty2** [comment]
ja dann fixt das mal wenn es alle questitems auf dem server betrifft man ist als 5er gruppe einfach nur gearscht wenn jeder die quest hat und man über 2 stunden warten müsste bis es 4 mal respawnt ist -.-

**Comment by hraesvelgr** [comment]
@dagochen (diesmal richtig) wieder was gelernt.

die frage ist ja nur: wie einfach ist es den respawntimer zu verändern?

**Comment by dagochen** [comment]
Ich brauche folgende Info: 
Die ID am Ende von dem Link hier http://datenbank.welli-it.de/?object=124388

Daraus wird dann folgende SQL-Anweisung, die einmalig auf dem Server ausgeführt wird und die Respawnzeit von 5 Min auf 5 Sekunden ändert:

```sql
UPDATE `gameobject` SET``spawntimesecs` = '5' WHERE `id` = 124388 ;
```

**Comment by nightblizard** [comment]
Wurde übernommen, vielen Dank!
