### ISSUE TITLE
BWL Razorgore Kugel

### ISSUE THREAD

**Issue by Derop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1196]
Heyho,

Die Kugel zum Kontrollieren von Razorgore buggt ab und an und sorgt für Wipes/ Chaos.

Die Kugel funktioniert manchmal einfach gar nicht und man bekommt den Debuff, welche einem nicht erlaubt kontrolle über Razorgore zu erlangen. In jedem guten Raid steht ein oder zwei Backups bereit, welche schnell einspringen können/müssen. Dies verhindert aber auch keinen Wipe wenn der Fehler auch bei der Reserve auftritt.

Es ist wie russisch Roulette. Manchmal klappt es 3 mal hintereinander und manchmal auch 3 mal hintereinander (neulich sogar 6 mal) NICHT und man bekommt nur den debuff.

Es wurde sich weder bewegt(kanalisierung abgebrochen) noch irgendwas gecastet noch Aggro von herumlaufenden Mobs.

Danke und Gruß

DerOP

**Comment by Slimmer2** [comment]
Die Kugel sollte auch nicht von unten anklickbar sein.

**Comment by Derop** [comment]
dies wurde auch nicht getan. Man stand auf dem Podest.

**Comment by ircfelix** [comment]
@Slimmer : wie kommst du zu der Aussage? Es gibt Videos und Guides wo Leute sie von unten klicken können/sollen.

**Comment by Slimmer2** [comment]
Dann poste die Guides und Videos wo man das sieht.

**Comment by ircfelix** [comment]
Ne du musst deine behauptung auch belegen da sie von dir zuerst kam.

**Comment by Slimmer2** [comment]
Dann ging es auch unten.
wir haben auf den Offi den ORB immer oben angeklickt

**Comment by ircfelix** [comment]
Tolle Quelle!

**Comment by Dotox** [comment]
Beobachtet das ganze bitte bei eurem nächsten Raid und meldet euch, falls es noch immer vorkommen sollte.
