### ISSUE TITLE
Die Säulen im Suppression Room

### ISSUE THREAD

**Issue by Derop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1197]
Hallo,

Folgende Situation:
Lashlayer ist getötet. Nun disconnectet der Server. Firemaw steht noch.

Die Säulen (Slowen und erhöhen Castzeit enorm) welche vor dem Töten von Lashlayer nach einer bestimmten Zeit wieder aufploppen funktionieren soweit richtig.
ABER: Nachdem er getötet wurde sollten alle Säulen unten bleiben. Dies funktioniert nur sogut bis der Server einen Crash hat oder einfach mal disconnectet. Danach funktionieren die Säulen urplötzlich teilweise wieder, was das Kiten von Trashmobs(drakes) sowie Bosskämpfe (Firemaw) erschwert und zudem äußert nervig ist.

Gerne kann ein Screenshot bei nächster Gelegenheit eingereicht werden, welche die teilweise wieder funktionierenden Säulen zeigt.

Gruß DerOP

**Comment by Slimmer2** [comment]
Kann ich bestätigen

**Comment by Derop** [comment]
Perfekt. Heute wieder Lashlayer down und jetzt Server restart. Vorher/ Nachher Fotos kommen.

**Comment by Dotox** [comment]
Ohje, das ist echt ägerlich. Schau ich mir sobald ich Zeit hab an.

**Comment by ircfelix** [comment]
Etwas wie 

If (broodlord == dead) {
Säulen runter
}

das beim kill vom brutlord triggert bräuchte man.

Und die Säulen an sich müssten irgendein event oder nen timer haben durch den sie hoch gehen. Auch hier müsste man so etwas wie die Bedingung if broodlord == dead { Säulen runter } einbauen.

**Comment by Dotox** [comment]
Genau, sowas haben wir schon eingebaut (funktioniert ja) nur wenn der Server gecrasht ist, muss das nochmal gefragt werden :)

**Comment by ircfelix** [comment]
Wenn jemand die Inni betritt (relogg/zoning) könnte man das auch abfragen.

**Comment by Larnak1** [comment]
Wenn ich es richtig in Erinnerung habe, sind es nur 2 oder 3 Säulen, die *nicht* unten bleiben. Bei allen anderen funktioniert es korrekt.

**Comment by Derop** [comment]
das hab ich doch oben geschrieben. Ob ich teilweise oder 2-3 schreibe ist doch gehopst wie gesprungen :D
brauchst du noch Screenshots oder nicht, dotox?

**Comment by Larnak1** [comment]
Es ist aber ein Unterschied, ob es zufällig irgendwelche Säulen sind oder immer die selben :)

**Comment by Dotox** [comment]
Nein Danke @Derop - konnte das selber gut reproduzieren und arbeite schon an einer Lösung :)

**Comment by ircfelix** [comment]
Letzten Sonntag hats funktioniert :)
