### ISSUE TITLE
Paladin Weihe flaggt nicht

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1198]
Welches Verhalten wird beobachtet?

-Wenn man als Paladin  Weihe bei einem PvP geflaggten Hordler benutzt wird man nicht geflaggt und ist somit immernoch nicht angreifbar.

Wie sollte es sich verhalten?

-Sobald es bei einem Hordler tickt sollte man PvP geflaggt werden.

Schritte zur Reproduzierung

-Weihe bei einem PvP geflaggten Hordler benutzen.

**Comment by hraesvelgr** [comment]
hm, aber ich weiß, dass es vor noch garnicht so langer zeit funktioniert hat, da mich ein magier beim farmen in silithus genau deswegen abgezogen hat. 
das müsste vor dem alterac-patch gewesen sein.

**Comment by Slimmer2** [comment]
Wenn man selbst kein PvP an hat und in der Range ein Spieler anderer Fraktion PvP an hat, sollte man wenn man einen AOE macht nicht PvP flagt werden. Der andere Spieler sollte auch keinen Schaden erhalten.
Sprich nur wenn man den anderen Spieler Direkt angreift sollte man gefalgt werden.

**Comment by Testear** [comment]
Selbiges funktioniert mit Blizzard auch. Gegner erleidet Schaden. Blizzard-caster wird nicht geflaggt.

@ Slimmer: Das habe ich noch nie gelesen oder gehört und ist ohne Quellenangabe nur eine Behauptung.

**Comment by Rukachi** [comment]
Neuer Erkenntnis: Wenn man es bei Humanoiden benutzt z.B. Bankier der Gegnerischen Spieler tickt Weihe zwar aber man wird nicht angegriffen und der Mob heilt sich wieder hoch.

**Comment by Sabbaer** [comment]
na dann kommt das hoffentlich auch für blizzard, feuerregen usw.

**Comment by hraesvelgr** [comment]
neutrale npc kommen nicht in combat, durch aoe, sondern heilen sich einfach hoch.
