### ISSUE TITLE
Movementspeed von Mobs zu hoch

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1199]
Wenn Mobs geslowed, gestunned oder auch nicht von einem dieser Effekte betroffen sind, kann es vorkommen das diese mit 10x-Speed auf einen zu rasen und einen angreifen. Dies sollte offensichtlich nicht so sein und tritt seit ungefähr 3-4 Monaten auf. Leider wurde das Problem nicht durch den letzten Patch behoben.

**Comment by Dotox** [comment]
Das Problem gibt es schon immer, wir saßen da schon etliche Stunden dran - ohne Erfolg. Selbst das reproduzieren klappt nicht immer was die Fehlersuche noch schwieriger macht.

**Comment by dagochen** [comment]
Ich glaub es hat was mit den Models zu tun, da es bei "nicht-Humanoiden", bzw großen Mobs schlimmer ist und da hängst es dann mit der Combatreach und der Mechanik zusammen, die Wahax damals geändert. Ich glaub die denken zu früh sie können zuhauen und dafür müssen die ja an einer bestimmten Stelle stehen, wodurch dann dieser "Charge"-ähnliche Effekt auftritt.

**Comment by Slipru** [comment]
Normalerweise müsste es in bwl bei den Drachen nach Vael gut reproduzierbar sein. Diese porten und chargen bei uns eigentlich jede ID.

**Comment by Larnak1** [comment]
Jo, die "chargen" nach dem Pull + Runterspringen auch gern mal vom Balkon durch die Luft in den Vael-Raum, was vermutlich der gleiche Effekt ist.
