### ISSUE TITLE
shade of eranikus, event, sunken temple

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#12]
>das event wird, dadurch dass man jammalan nicht erreichen kann, nicht gestartet

hier nochmal eine kleine übersicht, wie es ablaufen sollte (zu testzwecken):

(Edit: die beiden bosse morphaz (http://datenbank.welli-it.de/?npc=5719) und hazzaz (http://datenbank.welli-it.de/?npc=5722) sollten nicht an einer stelle verharren, sondern in ihrer kammer im kreis fliegen, recht dicht beieinander 
http://www.almarsguides.com/Almar%27s%20Stuff/WoW/Instances/Sunken%20Temple/Morphaz%20and%20other.jpg)

mit dem tod des propheten (http://datenbank.welli-it.de/?npc=5710) wird das event um den shade of eranikus aktiviert. 

beim tod des propheten wird das tor vor eranikus geöffnet, es sollte ansonsten geschlossen sein. (momentan ist es noch geöffnet)
der drache liegt auf dem boden, wenn man ihn angreift, erhebt er sich langsam. 

greift man den drachen an, kommen alle drachkin, die sich in  der instanz befinden, ihm zu hilfe.
eranikus castet einen 15 sekunden sleep auf sein derzeitiges ziel, dieser spell ist nicht dispellbar, auch nicht mit gottesschild oder insignien, kann aber mit einem grounding totem abgefangen werden (wowwiki). ein gesleeptes ziel bekommt einen aggroreset. 
Eranikus hat nur einen emote , beim beginn des kampfes (leider konnte ich hierzu keine  genauen angaben oder quellen  finden, es hat aber irgendwas mit "children" zu tun, und bezieht sich auf die drachkin in der instanz, es scheint auch keine soundfile dazu zu geben
EDIT: "This evil cannot (be allowed?) to enter this world! Come, my children!" als emote?)

**Comment by Gnomorus** [comment]
Kleiner Nachtrag: Die in der Instanz verbleibenden Drachkin kommen Eranikus nicht zur Hilfe, sobald man ihn angreift. Der dazugehörende Schrei funktioniert jedoch korrekt.

**Comment by Haudraufinix** [comment]
Ich habe vorgestern Eranikus mit meinem Hunter angegriffen. Gewisse Trashpacks sind mit Eranikus verlinkt ( ich glaube die im Gang auf dem Weg zu ihm) aber nicht alle.
