### ISSUE TITLE
Deserteuer Debuff

### ISSUE THREAD

**Issue by godlike321** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1200]
Wenn man einem Schlachtfeld beitritt welches voll ist wird man nun korrekterweise wieder zum Anmelder gesetzt.
Leider erhält man dabei den Deserteur Debuff welchen man eigentlich nur für die Aufgabe eines Schlachtfeldes erhalten sollte.

Anbei ein Screenshot

![unbenannt](https://cloud.githubusercontent.com/assets/15720612/11023299/30d24872-8675-11e5-9918-4655a6d6d724.png)

**Comment by 0815Priester** [comment]
/push
Ich weiß ihr macht fixes nach lust & laune,ist ja auch ok aber bitte diesen bug fix auf prio setzen.Danke

**Comment by Dotox** [comment]
Habs schon behoben, kommt mit dem nächsten Update :)

**Comment by godlike321** [comment]
Top ! Schränkt nämlich schon sehr ein wie ich die letzten Tage beobachtet habe.

Bedankt ! :>

**Comment by 0815Priester** [comment]
merci.
