### ISSUE TITLE
Ingenieur - Gnomen-Net-o-Matik-Projektor

### ISSUE THREAD

**Issue by Crainh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1203]
Hallo zusammen,

bei dem unten gezeigten Ingenieurstrinket kommt es bei **jedem** einloggen zur Fehlfunktion, ohne jedoch einen CD auf dem Trinket zu haben (man ist selber für 18 Sekunden im Netz gefangen).

[Gnomen-Net-o-Matik-Projektor/ wowhead](http://de.wowhead.com/item=10720/gnomen-net-o-matik-projektor)

[Gnomen-Net-o-Matik-Projektor/ classic datenbank](http://datenbank.welli-it.de/?item=10720)

[Screenshot](http://www.directupload.net/file/d/4166/be3wrenp_jpg.htm)

Ich habe keine Quelle gefunden, die aussagt, dass es beim Einloggen passieren kann, daher gehe ich davon aus, dass dies so nicht normal ist.

**Comment by hraesvelgr** [comment]
was sagt das combatlog?

**Comment by dagochen** [comment]
Grad mit meinem Hunter getestet und tritt bei mir nicht auf.

**Comment by hraesvelgr** [comment]
am besten mal alle addons ausmachen und dann nochmal einloggen, @Crainh

**Comment by Sabbaer** [comment]
den wdb ordner haste zwischenzeitlich schonmal gelöscht? reine vermutung?
