### ISSUE TITLE
Database - HTML Serverfehler

### ISSUE THREAD

**Issue by MRudey** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1204]
Welches Verhalten wird beobachtet?
Die Datenbank meldet einen Serverfehler für die Objekte mit den IDs:
1734 - Goldvorkommen (http://datenbank.welli-it.de/?object=1734)
2040 - Mithrilablagerung (http://datenbank.welli-it.de/?object=2040)

Wie sollte es sich verhalten?
Die Standorte etc. sollte angezeigt werden wie z.B. für http://datenbank.welli-it.de/?object=150079

Schritte zur Reproduzierung
Links anklicken.

**Comment by Rushor** [comment]
das ist aber kein ingamebug :>

**Comment by MRudey** [comment]
Das stimmt, aber ich dachte das passt hier noch am ehesten hin...

**Comment by hraesvelgr** [comment]
man sollte vllt mal einen sammelthread machen dazu

**Comment by dagochen** [comment]
Wird inzwischen korrekt angezeigt. Ich mach daher mal zu.
