### ISSUE TITLE
Mobs drehen sich bei Stuns

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1205]
Es kommt weiterhin vor, dass Mobs bei einem Stun-Effekt ihre Blickrichtung verändern. Dies sollte nicht so sein. Ein Mob der gestunnt wird sollte in die Richtung schauen, in die er im Moment des Stuns geschaut hat und sich nicht random in eine Richtung drehen.

**Comment by Dotox** [comment]
Einfach so kann ich nicht das nicht reproduzieren. Da muss vorher irgendwas anderes passieren was das auslöst. z.B wird die Kreatur abgelenkt und anschließend gestunnt (war das letzte Mal der Fall und wurde behoben). Gibts da noch irgendwas, was vielleicht hilfreich sein könnte?

**Comment by dagochen** [comment]
Hab heute in BRD Mobs abgelenkt und dann Fieser Trick gemacht. Da kam es meistens (aber auch nicht immer) vor.

**Comment by Rushor** [comment]
aggroreset während stunn oder taunt während stunn vlt mal versuchen, ob das was ändert

**Comment by dagochen** [comment]
Naja Ablenken + Fieser Trick war der Opener, da haben die ja noch keinen Aggrotable.

**Comment by Dotox** [comment]
Echt, immernoch bei Ablenken? Merkwürdig. Waren das Kreaturen mit Wegpunkten oder ähnliches?

**Comment by dagochen** [comment]
Wir haben den Fall zuverlässig reproduzieren können und auch rausgefunden, in welche Richtung die gucken beim Stun. Sie schauen wieder in ihre "normale" Blickrichtung", zumindest clientseitig. Serverseitig stehen sie richtig. 

Im folgenden Video sieht man es einmal aus meiner Sicht (Schurke der stunnt + ablenkt).
http://www.twitch.tv/dagochen/v/26098760

**Comment by nightblizard** [comment]
Fehler gefunden und behoben. Der Server hat einen aus der Verstohlenheit geholt bevor der Zauber gewirkt wurde (das passiert zwar alles in wenigen Millisekunden und damit für uns gleichzeitig, aber für den Server macht das gewaltige Unterschiede).

**Comment by dagochen** [comment]
Das tritt aktuell auch noch auf, wenn Mobs wie die Elementare in MC am chargen sind und währenddessen einen Stun bekommen.
