### ISSUE TITLE
Fehlerhafte Angel-Zeiten + FIX

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1206]
Winterkalmar sollte tatsächlich nur im Winter zu angeln sein. Sommerbarsch nur im Sommer.
Sonnenschuppenlachs nur tagsüber und Roher Nachtflossenschnapper nur nachts.

FIX
```sql
-- Winterkalmar
UPDATE fishing_loot_template SET lootcondition = 12, condition_value1 =  97  WHERE item = 13755;

-- Sommerbarsch
UPDATE fishing_loot_template SET lootcondition = 12, condition_value1 =  98  WHERE item = 13756;

DELETE FROM game_event WHERE entry = 89;

INSERT INTO `game_event` (`entry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`)
VALUES ('89', '2013-02-01 12:00:00', '2020-12-31 11:59:59', '14400', '720', '0', 'Tag beginnt');

-- Sonnenschuppenlachs
UPDATE fishing_loot_template SET lootcondition = 12, condition_value1 =  89  WHERE item = 13760;

-- Nachtflossenschnapper
UPDATE fishing_loot_template SET lootcondition = 12, condition_value1 =  27  WHERE item = 13759;
```sql

**Comment by Rushor** [comment]
weist du zufällig welche event_id für winter/sommerzeit von blizz verwendet wurde?

**Comment by dagochen** [comment]
In Bezug auf Angeljahreszeit? Von Blizz: kA. Auf Nefarian sind es die 97 und 98.

**Comment by Rushor** [comment]
yo genau, thx :)

**Comment by dagochen** [comment]
Das Event "Tag beginnt" wird übrigens benötigt, da in der Version von Nefarian keine logischen Operatoren für Lootbedingungen, so wie du es vllt von trinity und dem aktuellen cmangos kennst,implementiert sind.

**Comment by hraesvelgr** [comment]
gibt es nicht schon das event "nigths"? in stranglethorn zb schlafen die tiger und panther dann. also sollte es das event "tag beginnt" ja in der theorie auch geben, denn woher wissen die sonst wann sie aufwachen sollen? :D

**Comment by Dotox** [comment]
@hraesvelgr Die Tiger wurden per Script so programmiert und benötigen nur die Serverzeit. Andere Events hingegen benutzen Einträge aus der Datenbank damit sie korrekt funktionieren. "Tag beginnt" fehlt bei uns.

**Comment by hraesvelgr** [comment]
hm, wohl ein grund warum zb das mondbruchevent nicht so wirklich funktioniert.

**Comment by Wosser** [comment]
Nur in Nacht und Tag zu unterteilen reicht nicht. Von 0 bis 6 Uhr sollte man nur Nachtflossen angeln können in den entsprechenden Gebieten, von 6 bis 12 Uhr Nachtflossen und Sonnenschuppen zu jeweils 50%, von 12 bis 18 Uhr nur Sonnenschuppen und von 18 bis 24 Uhr wieder 50/50

**Comment by dagochen** [comment]
@Dotox "Tag beginnt" hab ich mir ausgedacht. Keine Ahnung ob es nicht doch noch eine elegantere Variante gibt. Habe "Nacht beginnt" kopiert und nur die Zeiten um 12 Stunden geshiftet.

**Comment by nightblizard** [comment]
Wurde gemäß der Wiki Quelle angepasst.

**Comment by dagochen** [comment]
Wie haste das jetzt gemacht? Mehr als eine Condition geht ja nicht in euerm Core, und die Lootchancen müssen ja auch varieren. Hast du ne Gruppe draus gemacht und für jede Tageszeit nen eigenen Eintrag + eigene Condition gemacht oder wie?
