### ISSUE TITLE
Große Robuste Truhe in  Instanzen Respawn 

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1208]
Welches Verhalten wird beobachtet?

-Beim Farmen in Stratholme alleine bin ich an einer Großen Robusten Truhe angekommen nachdem ich sie geleert habe und kurze Zeit afk war ist mir aufgefallen das die Kiste innerhalb so 4-5 Minuten genau weiß ichs net respawnt. Hab einen Gm gefragt und es soll wohl nicht so sein.

Wie sollte es sich verhalten?

-Die Truhe sollte pro ID nur einmalig Lootbar sein!

Schritte zur Reproduzierung

-Truhe Leeren und abwarten

Links aus unserer Datenbank 

-http://datenbank.welli-it.de/?object=153464

Wenn noch einer genauere Links dazu findet dann bitte posten. Ich finde gerade nichts

**Comment by Rushor** [comment]
UPDATE`gameobject` SET `spawntimesecs`=86400 WHERE  `guid`=87906;

**Comment by dagochen** [comment]
@Rushor leider falsche guid :) Und 7200 Sekunden sind 2 Stunden, was glaube ich in Inis die Standard-Spawnzeit sein sollte (hab mir nur paar Kisten und co angeschaut)

```sql
UPDATEgameobject SET spawntimesecs=7200 WHERE guid=27871;
```

**Comment by Rushor** [comment]
joa das kam nur aus der tc-db :D

**Comment by nightblizard** [comment]
Fix wurde übernommen. Vielen Dank!

**Comment by Rukachi** [comment]
Jo die Truhe hinter dem Boss Magistrate Barthilas, der bei dem Baron run kurz vorm Event steht respawnt wieder mehrmals. Vor ner Weile entdeckt aber voll verpeilt es zu melden. Bei der nächsten Gelegenheit mal bitte nachsehen, wenn es nicht schon gefixt ist.
