### ISSUE TITLE
Automatische Auffüllung der Resourcen für Ahn'Qiraji

### ISSUE THREAD

**Issue by just4aq** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1209]
Nach folgenden Quellen:

Die Öffnung Ahn'Qirajs wird aus zwei Teilen bestehen: Erstens die Questreihe, mit der man das Szepter erschafft. Zweitens die Sammlung der Rohstoffe.

Nach 4 Wochen werden die Rohstoffvorräte automatisch steigen. Die Questreihe MUSS allerdings auf jedem Server vollendet werden, um AQ zu öffnen.

(Quelle: http://forums-en.wow-europe.com/thre...en&t=35085&p=1

"Correct. After a month, the server will begin automatically accumulating resources. However, it's still up to players to craft the scepter and open the gates.") 

http://wow.ingame.de/forum/threads/87201-AQ-Das-Szepter-der-Sandst%C3%BCrme-Zusammenfassung)

Sicher fragen sich viele Spieler auf den neuen und weniger bevölkerten Servern, wie sie alle die Materialien für die Kriegsbestrebungen sammeln sollen. Wie vielleicht einige schon wissen, beginnen die Server nach einem Monat automatisch damit, Materialien zu sammeln. Diese werden also mehr, selbst wenn niemand irgendetwas bei den NPCs für die Kriegsbestrebungen abgibt. Dies wurde jetzt noch mal von Tigole bestätigt.

After a month, the server will begin automatically accumulating resources. However, it's still up to players to craft the scepter and open the gates.

http://wow.gamona.de/forum/threads/automatische-anh%C3%A4ufung-von-kriegsmaterialien.75430/

Re: Ahn'Quiraj
Datum: 18. Januar 2006 09:52

Worldevent

Viele denken, dass die Spieler auf neuen Servern keine Chance haben Ahn'Qiraj zu betreten, da die Rohstoffsammlung fast unmöglich ist. Doch diese Spieler können aufatmen, denn der Server fängt automatisch nach einen Monat an die Rohstoffe selber zu sammeln. Dies wurde auch von Tigole im US Forum Raid & Dungeons[forums-en.wow-europe.com] bestätigt.

After a month, the server will begin automatically accumulating resources. However, it's still up to players to craft the scepter and open the gates.

Trotzdem wird es eine Weile dauern bis auch auf den neueren Servern das Tor offen ist, da man noch in den Geschmolzenen Kern und in den Pechschwingenhort muss.

Quelle: Forenthread US[forums-en.wow-europe.com]

http://www.blutbanner.net/forum/read.php?16,13639

Automatic accumulation of war materials

Sure, many players ask to the new and less populated servers, how to collect all the materials for the war effort. Like maybe some already know, the server automatically start after a month of work to collect materials. These are more so, even if no one gives anything at the NPCs for the war effort. This has now been confirmed again by Tigole.

After a month, the server will begin Automatically Accumulating resources. HOWEVER, it's quiet up to players to craft the scepter and open the gates.

To ensure that all materials are indeed eventually collected, the gates open but only when the scepter was restored. And the only players on the server do you. Since you this but must in the Molten Core and Blackwing Lair, it will take a long time before the newer servers benefit from, to enter Ahn'Qiraj.

Thanks for pointing to Dwarrows.

Thread in the US Community Forum

http://www.icyvpn.com/115273/

sollte eindeutig hervorgehen, dass sich die Resourcen für das War Effort Event nach 4 Wochen periodisch von selbst erhöht haben. Der Blue Post eintrag wird teilweise in den genannten Quellen verlinkt, führt verständlicherweise aber zu keinem Eintrag, da schon längst veraltet.

Leider wird auch kein Wert genannt, in welchem Ausmaß die periodische Erhöhung stattfindet. Als Vorschlag möchte ich folgende Rechnung unterbreiten:

Release des AQ Events 03.01.2015
Release von Naxxramas 20.06.2015

Zwischen diesen beiden Ereignissen liegen 168 Tage. Bieten wir dem Server die Möglichkeit über diesen Zeitraum hinweg die Resourcen selbst zu organisieren. Entsprechend der Rechnung 100/168 füllt sich jede unterschiedliche Resource zu 0,595% am Tag selbst.

Ich hab bewusst auf die Verzögerung von 4 Wochen verzichtet, da der Zeitraum vom 03.02. bis zum 20.06. kleiner ist und somit der tägliche serverseitige Eigenzuwachs höher wäre (0,73% am Tag).

Ich bitte die automatische Auffüllung rückwirkend zum 21.09.2015 vorzunehmen, da es somit der Blizzlike-Mentalität treu bleiben würde. Somit würden die aktuellen Resourcen einen Schub von ca. 35% erhalten und für jeden Folgetag weitere 0,595%

MFG

**Comment by just4aq** [comment]
Wenn man exakt rechnen würde, sprich vom 31.01.2006 (exakt 4 Wochen nach AQ Release) bis zum 20.06.2006 (Naxx-Release), wären das 140 Tage und entspricht exakt 5,00% pro Woche automatische Füllung pro Resource. Welch ein Zufall....

**Comment by just4aq** [comment]
Q. What is your reaction to how the efforts to open Ahn'Qiraj are going?

A. This is the first time that we've really put all of the power in the hands of players. So you see some really interesting things going on. In some places, you see multiple über-guilds that have treated each other with respect, or who have called a truce, and are engaged in some massive collective farming. You see a lot of guilds setting up contests to encourage others to participate. The event really comes down to the politics and diplomacy on each realm. But we don't want to punish players on realms that aren't cooperating, so in a week or two the resources will start to just come in on their own. So we gave just enough time to let all of the servers show their feathers and strut their stuff; this is the time to see which servers can really put in the effort.

Q&A aus einem NYT Interview http://www.nytimes.com/2006/01/28/sports/othersports/28vide.html?pagewanted=all&_r=0

**Comment by Hakii** [comment]
http://blue.cardplace.com/cache/wow-general-en/843374.htm
http://blue.cardplace.com/cache/wow-general/6928337.htm

Dem Eintrag spende ich mal die von unserem Früchtchen bereitgestellten Blue Posts. Ich denke damit hat sich die Diskussion erübrigt und eine automatische Auffüllung längst überfällig.

**Comment by Sabbaer** [comment]
anwort @developers?

**Comment by dagochen** [comment]
mit dem @Sabbaer  muss man hier aufpassen, da developers wieder jemand anderes ist^^

**Comment by hraesvelgr** [comment]
hassmails incoming :D

**Comment by Sabbaer** [comment]
na dann

**Comment by just4aq** [comment]
Schade das bisher noch nicht reagiert wurde.

**Comment by hraesvelgr** [comment]
chillt mal, leute. ihr seid ja fast schlimmer als die, die 5 mal am tag fragen, wann denn endlich ihr premiumaccount freigeschaltet wird. und die haben wesentlich mehr recht dazu, da sie ja eine gegenleistung gebracht haben. 
übt euch in geduld.

**Comment by just4aq** [comment]
ich habe einen premium account, darf ich den jetzt als 13-Euro-Jocker-Ersatz nehmen?

**Comment by Sabbaer** [comment]
ein bisschen information bezüglich eurer entscheidung würde mich sehr freuen, denn es werden immer mehr, die die szepter quest abschließen und es sollte doch etwas besonderes bleiben....

**Comment by dagochen** [comment]
Ich hab grad in meine Glaskugel geguckt und die Antwort ist "Nein."

**Comment by Rushor** [comment]
![Img](http://i.imgur.com/IgmBrvn.jpg)

**Comment by just4aq** [comment]
seit wann wird bei blizzlike wirkürlich entschieden :>?
