### ISSUE TITLE
localization- Übersetzungsfehler

### ISSUE THREAD

**Issue by harleth** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1210]
Ironforge=Eisenschmiede sowohl auf der Karte und im Video nicht Deutsch
Stormwind= Sturmwind -"-
Besudeltes Memorandum (Hexerquest bei Hexenmeister Lehrer Alamar Grimm) komplet in Englisch
Das Coldridgetal? die Sprache heißt wohl Denglisch, gibts aber nicht ^^
Eisklammtal und die festung heißt Ambossar und nicht Anvilmar ^^ Das wars für den Start xD
Classic ist geil, aber die Übersetzung muss stimmen, sonst stört es den Spielfluss und die Fantasie ist nicht mehr stimmig

**Comment by harleth** [comment]
Anfänge" quest von Alamar Grimm, die genannten Feinde, wo man die Feder holen soll, heißen Frostmähnen und nicht Frostmane.

**Comment by harleth** [comment]
Felix Windenbolz, Dilemma eines Flüchtlings- Ambosar und nicht Anvilmar

**Comment by dagochen** [comment]
Kannst du bitte Quellen nennen, die belegen, dass diese Namen zu 1.12 bereits übersetzt/nicht übersetzt waren? Blizzard hat das damals ja schrittweise während Classic gemacht, nun stellt sich die Frage, wie weit sind die damals gekommen? War mit 1.12 schon alles übersetzt?

**Comment by harleth** [comment]
soweit ich mich erinnern kann schon, da ich zu der Zeit angefangen habe. ich suche mal nach quellen, die das belegen

**Comment by Slimmer2** [comment]
http://wow.4fansites.de/patchnotes-2-0.php
Hier wurde Eisenschmiede, Sturmwind, Coldridgetal und Ambossar  lokalisiert

**Comment by harleth** [comment]
@ Slimmer2 ich habs nicht im Detail gefunden, um dies auch wirklich zu überprüfen. Es steht nur, das einige behoben wurden.

**Comment by Slimmer2** [comment]
Um genauer zu sein Patch 2.0.1

**Comment by harleth** [comment]
vielen dank! du hast recht. 
/closed

**Comment by dagochen** [comment]
Du kannst den Beitrag selbst schließen @harleth :)
