### ISSUE TITLE
Edelstein der Felsspitzoger / Gluthauer / Blutäxte

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1211]
Die 3 Edelsteine haben eine zu hohe Dropchance.
Edelstein der Felsspitzoger ist 87%
Edelstein der Gluthauer ist 86%
Edelstein der Blutäxte ist 89%

Sollte sein Siehe Bilder
Edelstein der Felsspitzoger http://datenbank.welli-it.de/?item=12336
Edelstein der Gluthauer http://datenbank.welli-it.de/?item=12335
Edelstein der Blutäxte http://datenbank.welli-it.de/?item=12337

![wowscrnshot_111715_193803](https://cloud.githubusercontent.com/assets/8680824/11224065/6dac74a2-8d73-11e5-8336-fff7f84af7ce.png)
![wowscrnshot_111715_193746](https://cloud.githubusercontent.com/assets/8680824/11224100/8d32321c-8d73-11e5-81a5-20fa96b7e2e3.png)
![wowscrnshot_111715_193733](https://cloud.githubusercontent.com/assets/8680824/11224124/ad8974e4-8d73-11e5-965a-450976c9ca49.png)

**Comment by hraesvelgr** [comment]
und wie verlässlich ist das? "weils in einem addon steht" glaub ich nicht, seit ich weiß, dass einige der skills in ktm vollkommenen unfug anzeigen :)

**Comment by dagochen** [comment]
naja 29%, 21% und 15% sind näher an den 15% drop rate die du gelinkt hast @hraesvelgr, als es auf unserm server ist :D

**Comment by hraesvelgr** [comment]
ist es. wollt halt nur  noch eine quelle mehr reinwerfen .

**Comment by Slimmer2** [comment]
Aber die Dropchance ist zu hoch sieht man an deiner Quelle auch.
Und http://datenbank.welli-it.de/?item=12219 Unverziertes Siegel des Aufstiegs hat bei uns 100%.
Nach deiner Quelle sollte das auch deutlich weniger sein

**Comment by dagochen** [comment]
FIX
```sql
UPDATE creature_loot_template SET ChanceOrQuestChance = 15 where item in (12335,12336,12337);

UPDATE creature_loot_template SET ChanceOrQuestChance = 0.5 where item = 12219;
```
