### ISSUE TITLE
Kernwüterich bei Golemagg der Verbrenner

### ISSUE THREAD

**Issue by CptAzgar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1212]
Hallo Zusammen.

**Welches Verhalten wird beobachtet?**
DIe Kernwüterich bei Golemagg haben keine roten Hörner wenn sie zu nahe an Golemagg sind.

**Wie sollte es sich Verhalten?**
Solange die Kernwüterich zu nahe an Golemagg stehen, sollten sie einen Buff haben, der ihnen 50% Angriffsgeschwindigkeit gibt und 500 mehr Schaden machen lässt.

**Zusätzliche Informationen**
http://wowwiki.wikia.com/wiki/Golemagg_the_Incinerator
http://sbruederschaft.bboard.de/board/ftopic-31942183nx8201-77.html
http://de.wowhead.com/npc=11988/golemagg-der-verbrenner#screenshots:id=144
https://www.youtube.com/watch?v=ovhRqAxnXqg

**Links aus unserer Datenbank**
http://datenbank.welli-it.de/?npc=11672   <--- Kernwüterich
http://datenbank.welli-it.de/?spell=20556   <--- Evtl. der Buff "Aura" von Golemagg

Leider finde ich keine Hinweise darauf wie weit die Hunde von Golemagg entfernt sein müssen, damit der Buff entfernt wird.

Kann auch gut sein, das die Range von Golemagg "Aura" nicht richtig ist.

MfG
Azgar

**Comment by Dotox** [comment]
Ist bereits implementiert - soeben nochmal nachgesehen.
