### ISSUE TITLE
flucht durch verstolenheit /questscript

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1214]
bei der quest "flucht durch verstohlenheit" (http://datenbank.welli-it.de/?quest=995) rennt der zu rettende npc (http://datenbank.welli-it.de/?npc=3692) einfach los und greift die umstehenden gegner an. ausserdem wird die quest instant abgeschlossen. 

er soltle beim annehmen der quest den buff http://datenbank.welli-it.de/?spell=6298 bekommen, und zum weg in der nähe des npc grimmklaue laufen (keine verlinkung zum spieler, er läuft von alleine) dabei sollte er für den spieler weiterhin sichtbar bleiben. 

ist er am weg angekommen, soll die quest abgeschlossen werden.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/361
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/758

**Comment by hraesvelgr** [comment]
hm., also ich hab sie automatisch abgeschlossen bekommen. sie war nie fehlgeschlagen.

vllt muss man dazu sagen: 
diese quest sollte nur von druiden und schurken annehmbar sein
