### ISSUE TITLE
[Quest - Darkshore] "Gesucht: Gurgelbacke!" - NPC spawnt nicht

### ISSUE THREAD

**Issue by Nyrante** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1217]
Der Murloc "Gurgelbacke" sollte bei ca. 36/76 spawnen, nachdem das dort befindliche Dorf durch einen Spieler angegriffen wird.

Das passiert leider nicht, die Quest ist nicht abzuschließen. Nach Rücksprache mit mehreren Spielern konnte niemand diese Quest absolvieren.

Quest:
http://datenbank.welli-it.de/?quest=4740

**Comment by Slimmer2** [comment]
Würde bereits gemeldet. Kann es nicht verlinken, die mobile Seite die Funktion nicht hat.

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/quest=4740/wanted-murkdeep laut den comments sollte man das camp erst clearen müssen und sich dann in dem camp befinden.

**Comment by Nyrante** [comment]
Das führt leider nicht zum Spawn der Kreatur. Bitte als Developer selbst 
checken - das Event ist verbuggt.

Am 19.11.2015 um 18:08 schrieb hraesvelgr:

**Comment by Rushor** [comment]
der close erfolgte, weil es dazu schon ticket gibt. dies findest du hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/335

**Comment by hraesvelgr** [comment]
ist bei uns normal: wenn der report zu einem früheren verlinkt wird, erfolgt meist automatisch der close, wenn der report nicht etwas vollkommen anderes sagt.
