### ISSUE TITLE
Fliehende Mobs nicht slowbar

### ISSUE THREAD

**Issue by grindbox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1218]
hallo,

mir is jetz öfters als jäger aufgefallen, dass ich die fliehenden humanoiden mobs nicht mit dem slow shot oder zurechtstutzen verlangsamen kann. ihr tempo ist beim fliehen zwar langsamer als wenn sie angerannt kommen, aber normalerweise sollten sie dennoh lansamer werden nach einem slow.

mfg

**Comment by dagochen** [comment]
Hatte ich auch schon mal, hab ich aber nicht reproduzieren können wenn ich es versucht habe. Wann tritt das bei dir denn auf?

**Comment by grindbox** [comment]
eigtl immer. sobald der mob zu fliehen beginnt, versuche ich vergebens zu slowen. sein tempo bleibt das gleiche
