### ISSUE TITLE
"Deserteur-Debuff" 2.0

### ISSUE THREAD

**Issue by godlike321** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1221]
Hey, erstmal vielen Dank fürs schnelle fixen :)

Der Deserteur-Debuff bleibt nun aus, allerdings kann man die Warteschlange des jeweiligen Schlachtfeldes nicht mehr verlassen.
Es wird einem angezeigt man wäre noch drin obwohl man bereits vorm Anmelder steht.
Ich war zu dem Zeitpunkt auch für Alterac und Arathi angemeldet, Warsong wurde mir allerdings nicht angezeigt so dass ich es nicht hätte verlassen können.
![bug1](https://cloud.githubusercontent.com/assets/15720612/11319785/64872c2e-9083-11e5-960f-3076c50b0140.jpg)

**Comment by Dotox** [comment]
Tritt das Problem noch auf?

**Comment by godlike321** [comment]
Wenn du seit letzter Woche nichts geändert hast ja, musste letzte Woche noch reloggen um mich erneut anzumelden
