### ISSUE TITLE
"Gemeinsames Bestreben" keine Ehre mehr.

### ISSUE THREAD

**Issue by Rehush** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1225]
Ich habe leider das Problem, dass die PvP-Quest "Gemeinsames Bestreben" mir nach Abgabe keine Ehre mehr gibt. Zuvor waren es etwa 2,4k. Bei anderen Spielern tritt dieses Problem allerdings nicht auf.
Auch nach mehrmaligem Relog und Löschen des WDB Ordners hat sich nichts geändert.

Mfg Rehush

**Comment by ChichiWarrior** [comment]
Quest:
http://datenbank.welli-it.de/?quest=8371

**Comment by Rehush** [comment]
danke Chichi!

**Comment by dagochen** [comment]
Da es sich hier wohl um einen Einzelfall handelt, der kein allgemeines Problem mit der Quest beschreibt, schließe ich das hier mal.
