### ISSUE TITLE
Schließkasetten wieder verschlossen

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1228]
Hi,

soeben habe ich mir einen Haufen Schließkasetten von nem Schurken aufschließen lassen. Nach nem Relogg waren die Dinger wieder zu.

Sollte so nicht sein.

Reproduzierbar durch Schließkasette aufschließen, nicht öffnen/looten und dann reloggen.

**Comment by Slimmer2** [comment]
Das war aber auf dem Offiserver auch so.

**Comment by dagochen** [comment]
Ich hab grad mal geschaut und ich finde auch nix, wo man den Zustand (opened/locked) in der DB findet, wenn die Dinger irgendwo im Inventar/Bank sich befinden. Ich vermute das wurde einfach nicht gespeichert. Hab aber auch net lange gesucht, vielleicht gibts doch was...?

**Comment by hraesvelgr** [comment]
dazu müsste es ja eine opened/closed flag geben. die er für jede schließkassette speichert.

**Comment by ircfelix** [comment]
Konnte man offene Kassetten nicht auch per Post rumschicken?

**Comment by hraesvelgr** [comment]
suche er quellen :^)
