### ISSUE TITLE
Totengräber Mordo

### ISSUE THREAD

**Issue by mighty2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1230]
Hallo der NPC "Totengräber Mordo" http://datenbank.welli-it.de/?npc=1568 steht an der falschen Stelle. Er müsste eigentlich in der Gruft stehen in der man sich befindet wenn man einen Untoten neu erstellt. Er steht eigentlich genau vor einem. Zurzeit steht er draußen vor der Gruft, nich weiter wild wollte es aber trotzdem reporten ;)

**Comment by hraesvelgr** [comment]
das kam mit patch 3.3, dass er direkt in der gruft stehen sollte. 

By Morghera (911 – 1·9) on 2009/12/09 (Patch 3.3.0)		
Moved with 3.3 he is now right in front of where you spawn

**Comment by mighty2** [comment]
Mhh dann passt der Questtext aber nicht

**Comment by mighty2** [comment]
er sagt nämlich man solle die treppen aus der Gruft hochlaufen...

**Comment by hraesvelgr** [comment]
das ist was anderes :)

**Comment by mighty2** [comment]
soll ich also nochmal Issue aufmachen und den Questtext erwähnen oder an dieser Stelle so stehen lassen?

**Comment by hraesvelgr** [comment]
mach einfach einen neuen report....aber wichtig ist, dass wir den alten questtext auch bekommen. alte screenshots evtl?
