### ISSUE TITLE
Beherrschen der Pantherjagd (Abschluss der Reihe)

### ISSUE THREAD

**Issue by b2410** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1232]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
1.2.5

Wie sollte es sein?

Pullen, es spawnen zwei Adds, alles töten. Fangzahn Looten

Wie ist es?

Gruppe (zwei Spieler)

Beim ersten Try kammen vier statt zwei Adds.

Beim zweiten Try sind nur die beiden gespawnt jedoch konnte keiner der Spieler den Elite looten.

Links:
http://datenbank.welli-it.de/?quest=193

Vielen Dank.

**Comment by hraesvelgr** [comment]
kann das jemand bestätigen`?

**Comment by b2410** [comment]
Ich bitte vielmals um Entschuldigung. Es handelt sich um einen Fehler meinerseits!

Bitte schließen.
