### ISSUE TITLE
NPC Kategorisierung

### ISSUE THREAD

**Issue by Snottie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1235]
Diverse Wildtiere, vor allem sämtliche Bären, werden nicht als solche gekennzeichnet und können somit nicht von Jägern gezähmt werden.

**Comment by hraesvelgr** [comment]
dann wären uns säntliche hunter schon aufs dach gestiegen...gibts genauere infos? wo hast dus beobachtet, hast du vorher mal den wdb gelöscht, das spiel ohne addons gestartet?

**Comment by Dotox** [comment]
WDB löschen hilft.
