### ISSUE TITLE
Kein Leder bei Raptoren

### ISSUE THREAD

**Issue by grindbox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1236]
Bei Blutsumpfraptor http://datenbank.welli-it.de/?npc=4351#drop und Blutsumpfkreischer http://datenbank.welli-it.de/?npc=4352
kommt zu ca. 30-40% kein leder raus wenn man kürschnert

**Comment by hraesvelgr** [comment]
warst du in einer grp?

**Comment by grindbox** [comment]
nein

**Comment by Rushor** [comment]
wer sagt denn, dass sie immer leder enthalten müssen?

**Comment by hraesvelgr** [comment]
wenn ic mir so die loottable anschaue, aknn ich mir schon denken, dass kürschnerbare mobs IMMER leder enthalten müssen, da die zusammengerechneten dropchancen des leders  immer 100% betragen.

**Comment by grindbox** [comment]
und so ganz nebenbei, hatten alle anderen mobs von lvl 5 bis 40, die ich gekürschnert habe, immer leder, außer eben diese beiden mobtypen

**Comment by dagochen** [comment]
UPDATE skinning_loot_template SET groupid = 1 where entry in (4352,4351);

Die Summe der Chancen ist bereits bei exakt 100%. Allerdings fehlt die Gruppierung. Aktuell wird für jedes Leder und jeden Balg ein neuer Würfel geworfen. Ist jeder der 4 Würfe zu hoch, ist garkein Loot drin.

**Comment by hraesvelgr** [comment]
würfe zu hoch? zu niedrig? :D was denn nun?

**Comment by dagochen** [comment]
https://github.com/cmangos/issues/wiki/loot_template#groupid

Da ist es gut erklärt ;)

**Comment by hraesvelgr** [comment]
>If group chance is greater than 100 then some entries will lost a part of their chance (or even not be checked at all – that will be the case for all equal-chanced entries) whatever value takes the roll R. So for some items chance to drop will be less than their ChanceOrQuestChance. That is very bad and that is why having group chance > 100 is strictly prohibited.

ah :) wieder was gelernt

**Comment by dagochen** [comment]
Das was du da kopiert hast @hraesvelgr ist übrigens der Fall mit den T2-Krieger Armschienen, die nicht droppen konnten ;)
