### ISSUE TITLE
Onyxia spammt den Chat zu

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1238]
Nach einem Wipe spammt Ony permanent im Chat.

"Was für ein Zufall. Normalerweise....bla bla". 

Und die Adds respawnen permanent.

**Comment by hraesvelgr** [comment]
tragischer einzelfall?

**Comment by dagochen** [comment]
Musste raus und die Ini resetten (raid neu aufmachen).

**Comment by dagochen** [comment]
Habs bis heute nie wieder erlebt das dies aufgetreten ist und lässt sich auch nicht reproduzieren :(
