### ISSUE TITLE
Hexerpets nach Stuns inaktiv

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1239]
Hallo!
Wenn Hexerpets durch Fähigkeiten wie zB dem Solarplexus von Jadefeuerschurken http://datenbank.welli-it.de/?spell=13579 gestunnt werden und der Mob danach zum nächsten in der Aggroliste läuft, bleibt das Pet auch nach Ablaufen des Stuns auf der Stelle stehen und macht nichts. Befiehlt man ihm per Strg 1 wieder anzugreifen, ignoriert er das auch, nur wenn man auf Folgen drückt kommt er zu einem und greift danach erst wieder an.
Bleibt der Mob in der Meleerange des Pets, tritt das Problem nicht auf.

**Comment by Ghulfang** [comment]
Das selbe trifft auch auf Jägerpets zu.
