### ISSUE TITLE
Quest: Marschenfroschschenkel

### ISSUE THREAD

**Issue by Kelturion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1240]
Hallo :)

Bei der Quest "Marschenfroschschenkel" aus den Marschen von Dustwallow wird seltsamerweise ein komplett falsches Item verlangt. Nach etwas Stöbern in der Datenbank (wo ich leider nicht alles gefunden habe) scheinen hier zwei Quests durcheinander geraten zu sein.

Die Quest selber nennt sich "Marschenfroschschenkel" und wird von Sumpfauge Jarl vergeben (http://datenbank.welli-it.de/?npc=4792). Kurioserweise kann ich die Quest hier in der Datenbank auch gar nicht finden. Auf dem offiziellen Blizzzard Server gabs die zu Classic Zeiten aber definitiv: http://de.wowhead.com/quest=1218/marschenfroschschenkel

Kurioserweise erwartet er hier aber die Items von der Quest "Feine Gewürze" (http://datenbank.welli-it.de/?quest=1218), nämlich: http://datenbank.welli-it.de/?item=3713.

Irgendeine Idee, was da schief läuft? Zur Veranschaulichung hab ich einen Screenshot angehangen.
![mashup](https://cloud.githubusercontent.com/assets/14249816/11459471/72b9dc24-96d7-11e5-82b3-da253255a31a.png)

**Comment by Slimmer2** [comment]
Wäre interessanter welcher Questtext stimmt der in der Datenbank
Laut Comments bei WOWhead wurde das bei 2.3 PTR geändert und man musste davor Feine Gewürze abgeben

**Comment by Kelturion** [comment]
Die selben Diskrepanz hat die Endquest der selben Questreihe "Jarl braucht eine Klinge": http://datenbank.welli-it.de/?quest=1203

Der Quest-NPC erwartet hier ein Crafting-Item: http://datenbank.welli-it.de/?item=3853

Der im Spiel auftauchende Questtext suggeriert allerdings, dass man einen NPC namens Messerklinge töten und looten, siehe folgender Text: http://de.wowhead.com/quest=27186/jarl-braucht-eine-klinge

Irgendwie scheint es wohl so, dass Client und Server hier mit komplett unterschiedlichen Daten arbeiten.

**Comment by Slimmer2** [comment]
Die Endquest wurde bereits gemeldet

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/511
