### ISSUE TITLE
[Druide] Gegnerische Jägerfallen während des Schleichens in Katzengestalt sichtbar

### ISSUE THREAD

**Issue by Tuary** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1249]
Titel:
[Druide] Gegnerische Jägerfallen während des Schleichens in Katzengestalt sichtbar

Welches Verhalten wird beobachtet?
Während des Schleichens in Katzengestalt können bereits gelegte Fallen von gegnerischen Jägern gesehen werden.

Wie sollte es sich verhalten?
Da der Druide keine Fähigkeit zum Entdecken von Fallen besitzt, sollten Fallen von gegnerischen Jägern nicht sichtbar sein. 

Schritte zur Reproduzierung:
Einen Jäger der gegnerischen Fraktion eine Falle legen lassen, in Katzengestalt wechseln und Schleichen aktivieren.

~~Spontaner Einfall:
Vielleicht sind auch die PvP Handschuhe dafür verantwortlich, da mit denen die Stealth Detection ein wenig erhöht wird. Da ich die im PvP aber immer trage, hab ich das jetzt gar nicht getestet. Ich schau es mir nochmal an und meld mich, falls sich was ergibt.~~

Zusätzliche Informationen:
Screenshot: https://www.dropbox.com/s/8b8pb14vrmjttqs/druid_hunter_traps.jpg?dl=0

Links aus der Datenbank:
Katzengestalt: http://datenbank.welli-it.de/?spell=768
Schleichen: http://datenbank.welli-it.de/?spell=9913
~~PvP Handschuhe Horde:~~
http://datenbank.welli-it.de/?item=16496
http://datenbank.welli-it.de/?item=16555
~~PvP Handschuhe Allianz:~~
http://datenbank.welli-it.de/?item=23280
http://datenbank.welli-it.de/?item=16448

Ande'thoras-ethil

EDIT: Okay, die PvP Handschuhe kann man wohl ausschließen, da die Fallen auch sichtbar sind, wenn ich die diese nicht trage.

**Comment by Loplin** [comment]
Eigentlich dachte ich die Fallen können alle Klassen sehen, sofern der Jäger die Animation des Fallenstellers durchführt
Ich meine mich zu erinnern, dass einige Jäger die animation früher mit hinsetzen während dem fallen stellen unterdrückt haben und somit die Falle dann nicht mehr sichtbar war.

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/forums&topic=190303/do-enemies-see-the-freezing-trap

**Comment by soda09** [comment]
Die Quelle is ja aus Patch 4.1.0. Bissel zu neu für 1.12. oder? 
Wenn man da außerdem mal logisch rangeht, wäre dann ja das Talent "Fallenaufdecken" des Schurken komplett nutzlos. Daher sollen nur Schurken, die entsprechendes gelernt haben, Fallen sehen können.
