### ISSUE TITLE
vaelastraz gibt debuff nur an mana klassen

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1256]
Welches Verhalten wird beobachtet?
vaelastraz gibt debuff nur an mana klassen
Wie sollte es sich verhalten?
der debuff sollte auf alle kommen können
Schritte zur Reproduzierung
vaelastraz seit release killen und aufpassen

datenbank
http://datenbank.welli-it.de/?npc=13020
http://datenbank.welli-it.de/?spell=18173

**Comment by Rushor** [comment]
quellen hierfür?

**Comment by Sabbaer** [comment]
ups, das ist sogar legit so ;) hahahh 
Vael only casts Burning Adrenaline in two scenarios: He will cast it on random mana users throughout the fight and he will cast it on the current tank every 45 seconds.

**Comment by Rushor** [comment]
:)
