### ISSUE TITLE
Schamanen Quest "Ruf des Feuers" nicht erneut annehmbar

### ISSUE THREAD

**Issue by suddenrage** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1258]
Die Schami Quest "Ruf des Feuers" ist bei mir nicht mehr annehmbar.

Ich hatte sie aus Platzgründen aufgegeben und nun kann ich sie beim Start NPC Searn Feuerwächter nicht mehr annehmen.

Ich bitte um eure Hilfe !

Link: http://datenbank.welli-it.de/?quest=1522

**Comment by hraesvelgr** [comment]
schon ein ticket geschrieben?

**Comment by suddenrage** [comment]
Ja, im Spiel unter "Hilfe" mit der Unterkategorie "Quest's".

**Comment by suddenrage** [comment]
Wichtig: Bitte schließen, ich konnte sie nun bei einen der Quest Reihen NPC's erneut annehmen ! :)

**Comment by Rushor** [comment]
du kannst das ticket alleine schließen mit "comment und close"
