### ISSUE TITLE
Patch 8.12.15: Totstellen beim Hunter funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1259]
Stellt man sich als Hunter tot, fällt man nicht mehr zu Boden und liegt rum. Außerdem startet der CD-Timer sofort, was er eigentlich erst sollte, sobald man wieder aufsteht.

**Comment by Faleen** [comment]
Ist mir auch aufgefallen.
Ich habe keine Sterbeanimation mehr. Die 6 Minuten, die ich normalerweise liegenbleiben würde, sind dementsprechend auch nicht mehr vorhanden. Da man dann stehen bleibt, kommt man auch direkt wieder infight. CD Timer wird auch bei mir sofort nach Ausführen der Fähigkeit gestartet.
Es wäre sehr schön, wenn da bis Sonntag bitte jemand mal schauen könnte, ob man das wieder hinkriegt.
Danke.

**Comment by dagochen** [comment]
Ja ist für Raids und Co ja schon recht wichtig @Dotox @nightblizard

**Comment by Faeleen** [comment]
(So nochmal, jetzt mit dem richtigen Account.)
Ist mir auch aufgefallen.
Ich habe keine Sterbeanimation mehr. Die 6 Minuten, die ich normalerweise liegenbleiben würde, sind dementsprechend auch nicht mehr vorhanden. Da man dann stehen bleibt, kommt man auch direkt wieder infight. CD Timer wird auch bei mir sofort nach Ausführen der Fähigkeit gestartet.
Es wäre sehr schön, wenn da bis Sonntag bitte jemand mal schauen könnte, ob man das wieder hinkriegt.
Danke.

**Comment by nightblizard** [comment]
Wurde behoben!

**Comment by Faeleen** [comment]
So schnell? Vielen vielen vielen Dank! (auch im Namen meiner anderen Hunterkollegen ^-^)
