### ISSUE TITLE
Richturteil des Befehls macht zu viel Schaden

### ISSUE THREAD

**Issue by Paripar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1260]
Welches Verhalten wird beobachtet?
Der Schaden durch das Richturteil ist höher als der bei der Zauberbeschreibung angegebene Wert.
Beispiel: 
Richten bei aktiviertem Siegel des Befehls Rang 1 macht z.B. anstatt 46-51 Schaden  zwischen 90-100 Schaden. Dies ist auch bei höheren Rängen der Fall, einzig bei Rang 5 bewegen sich die Schadenswerte im Rahmen der angegebenen Werte ( statt 187 maximalem Schaden kann das Richturteil bis zu 200 Schaden verursachen, der Schaden für ein gestunntes Ziel scheint aber korrekt zu sein) . 

Wie sollte es sich verhalten?
Das Richturteil sollte Schaden gemäß der Zauberbeschreibung machen.

Schritte zur Reproduzierung
-Char nackig machen, oder keine Items mit Zauberschaden angelegt haben und keine weiteren Modifikatoren aktiv haben
-Siegel des Befehls aktivieren und Richturteil zaubern

Anmerkung:
Die Datenbankeinträge stimmen nicht mit den Zauberbeschreibungen ingame überein:
z.B. für Siegel des Befehls Rang 1:
http://datenbank.welli-it.de/?spell=20375
93-102 Schaden normal, was ca. den Werten entspricht die ich beobachtet habe, der selbe Wert steht für gestunntes Target aber liegt ingame um die 140 
(anstatt 46-51 und 93-101 schaden wenn gestunnt laut Beschreibung ingame).

Ich habe das mit zwei unabhängigen lvl 60 Palas "getestet", der "Probenumfang" war jetzt auch nicht bei hunderten Richturteilen, vllt kann das ja jemand auch testen und seine Erfahrung dazu hier veröffentlichen.

**Comment by hraesvelgr** [comment]
@Sabbaer

**Comment by dagochen** [comment]
@Sabbaer haha :D ich mach morgen mal nen fix :P

**Comment by Sabbaer** [comment]
@dagochen http://community.mmobase.de/bugtracker-archiv/3055-richturteil-des-befehls.html
da wurde wohl bloß rang 5 "gefixed"

**Comment by Dotox** [comment]
Der Zauber skaliert mit dem Level, daher macht Rang 1 auf 60 mehr Schaden als beispielsweise auf Stufe 20. Das hat Blizzard vermutlich, wie bei vielen anderen Spells auch, dazu benutzt, das leveln etwas angenehmer zu gestalten, da man so mit jedem level etwas mehr Schaden macht.
