### ISSUE TITLE
Richturteil des Befehls profitiert nicht vom Bonusheiligschaden vom gerichteten Siegel des Kreuzfahrers

### ISSUE THREAD

**Issue by Paripar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1261]
Welches Verhalten wird beobachtet?
Der Schaden des Richturteils des Befehls bleibt gleich, wenn man vorher Richturteil des Kreuzfahrers gerichtet hat

Wie sollte es sich verhalten?
Da das Richturteil einen Spelldamagekoeffizienten von 0,43 hat (http://paladin-guide.blogspot.de/2005/12/stats.html) müsste man durch Richturteil des Kreuzfahrers 60,2 Schaden dazubekommen ( 140 Heiligschaden *0,43 = 60,2 , http://datenbank.welli-it.de/?spell=20303)

Schritte zur Reproduzierung
Char ohne Items mit Zauberschaden oder wahlweise nackt Richturteil des Kreuzfahrers auf einen Mob zaubern lassen und dann Richturteil des Befehls benutzen.

**Comment by dagochen** [comment]
Dies hängt mit #1115 zusammen.
