### ISSUE TITLE
räudige silbermähne spellbug

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1262]
der spell http://datenbank.welli-it.de/?spell=8139 sollte bei dem npc http://datenbank.welli-it.de/?npc=2923 kein cast sein, sondern eine "on next swing" flag bekommen.

**Comment by dagochen** [comment]
Reicht vermutlich dem Mob folgenden Spell zu geben, da dieser den oben gennanten Spell triggert:

http://datenbank.welli-it.de/?spell=18847

**Comment by Rushor** [comment]
By Adross (3,299 – 1·12·35) on 2008/01/24 (Patch 2.3.3)		
When killing them you have a chance of getting "Fevered Fatigue" It will reduce your Int and Spirit.

**Comment by Rushor** [comment]
```sql
-- Mangy Silvermane SAI
SET @ENTRY := 2923;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,6,0,50,0,0,0,0,0,11,8139,2,0,0,0,0,2,0,0,0,0,0,0,0,"Mangy Silvermane - On Just Died - Cast 'Fevered Fatigue'");
```

**Comment by hraesvelgr** [comment]
@rushor ah ok, gut zu wissen

**Comment by dagochen** [comment]
immer diese smart scripts von trinity :( die gehen doch bei uns nicht :(

**Comment by Rushor** [comment]
:'(

**Comment by Rushor** [comment]
aber event_ai_scripts gibts oder?

**Comment by dagochen** [comment]
@Rushor 
Ne...aber event_scripts. Vielleicht ist das nen Vorgänger von dem was du meinst? Musst mal gucken. Datenbank-Architektur von Nefarian ist halt bisschen älter schon. Viele Änderungen der letzten 3-4 Jahre sind nicht mit eingeflossen.

```sql
INSERT INTO `mangos_nef`.`event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, 
`datalong3`, `datalong4`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, 
`comments`)
VALUES ('id', 'delay', 'command', 'datalong', 'datalong2', 'datalong3', 'datalong4', 'data_flags', 
'dataint', 'dataint2', 'dataint3', 'dataint4', 'x', 'y', 'z', 'o', 'comments');
```
