### ISSUE TITLE
Combatlog & Ausweiden

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1264]
Beim Benutzen der Schurkenfähigkeit Ausweiden (http://datenbank.welli-it.de/?spell=31016) wird manchmal im Kampflog ein -Ausweichen- angezeigt, obwohl die Fähigkeit den Gegner normal trifft.

http://www.pic-upload.de/view-29091981/AusweidenCmbtlg.jpg.html

Scheinbar wird aus irgendeinem Grund der Anwender selbst von Ausweiden betroffen, bekommt jedoch nie selbst den Schaden ab. Dennoch wirkt der Ausweichenwert auf dieses Ereignis.

**Comment by Mafyo** [comment]
Dies ist auch bei Geisterhafter Stoß zu beobachten, allerdings wenn man seinen eigenem Stoß an dem Mob ausweicht bekommt man den buff nicht

**Comment by Maxwill** [comment]
Ich glaube dieser Bug tritt im Zusammenhang mit dem Talent "Relentless Strikes" auf, das quasi der +25 energy gain von einem gedodged wird.

**Comment by dagochen** [comment]
Korrekt und behoben worden.
