### ISSUE TITLE
[Quest] In den Träumen

### ISSUE THREAD

**Issue by b2410** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1265]
Hallo Classic Team,

Ich habe einen Bug gefunden.

Serverversion: 1.2.6

Es handelt sich um die Quest "in den Träumen". 

Welches Verhalten wird beobachtet?

Bevor der NPC "Hochlord Taelan Fordring" von seinem Platz in der Burg losläuft sagt er das man die Verkleitung (Buff) ablegen soll damit er euch nicht angreift.

Macht man das nicht, greift er nur die NPC's an und erkennt mich nicht als Feind.

Das heißt, behält man den Buff tötet er alle allein, stirbt unten am Turm, kommt als Geist wieder und tötet den Rest.
Außerdem kann er wärend des laufens aufmounten!

Wie sollte es sich verhalten?

Der Hochlord nimmt den Player (mit Buff) als Feind war und greift Ihn an.

Quest (In den Träumen): http://datenbank.welli-it.de/?quest=5944
NPC (Hochlord Taelan Fordring): http://datenbank.welli-it.de/?npc=1842

**Comment by dagochen** [comment]
Falsch. Kein Bug.

**Comment by hraesvelgr** [comment]
warum?

**Comment by Slimmer2** [comment]
Bevor der NPC "Hochlord Taelan Fordring" von seinem Platz in der Burg losläuft sagt er das man die Verkleitung (Buff) ablegen soll damit er euch nicht angreift.

Steht doch da man soll die Verkleidung ablegen

**Comment by hraesvelgr** [comment]
und wenn man es nicht tut, greift er einen nicht an sondern nur alles andere. das wäre der bug.

**Comment by Slimmer2** [comment]
Ah, Ok.
Dann machen ja viele bug use zu ihren Vorteil

**Comment by dagochen** [comment]
Ist kein Bug. Sucht bitte einfach mal nach der Quest oder schaut euch die letzten Reports dazu an....da steht drin, dass man die Quest allein machen können soll indem man die Verkleidung anbehält. Das war damals so und ist bei uns auch absolut richtig so!

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/693
Steht da in den eingefügten Kommentar von WoWHead auch, das man keine Aggro bekommt.

Gehe aber davon aus das dies trotzdem ein Bug ist, den Blizzard nicht gefixt hat

**Comment by dagochen** [comment]
Blizzard hat viele Bugs damals nicht gefixt, wenn wir uns jetzt aber dazu entschließen Blizzard-Bugs, die teilweise Kern der Spielmachnik von damals waren, zu fixen....dann bewegt sich das ganz schnell hier in eine Richtung, die mit Classic nicht mehr viel zu tun hat, sondern eher mit BC oder einem späteren Addon.

**Comment by hraesvelgr** [comment]
najaa, in dem puunkt find ichs schon ok, weils ein wichtiger bestandteil der lore ist. kommt halt imemr komisch, wenn man einen questtext liest, und dann passiert genau das gegenteil von dem, was drinsteht.

**Comment by b2410** [comment]
Leute, jetzt mal ernsthaft.

Die Quest war anscheind schon immer bugy, ja.

Jedoch ist es sich auf irgendwelche Kommentare zu stützen und zu argumentieren das man "Spielmechaniken" zerstört, etwas wirr, und am Ende Bugusing.

In den Kommentaren steht auch das es eine Folge- beziehungsweise Abschlußquest ist.

Dem ist nicht so. Ich habe schon einige Quests beendet und jedesmal wenn ich auf "Quest beenden" klickte wurde mir eine eventuelle Folgequest sofort angezeigt.
Besagte Quest "In den Träumen" ist jedoch eine Einzelquest, welche erst Verfügbar ist wenn die anderen Quests erledigt wurden.
Des weiteren ist die Quest als Elite gekennzeichnet.

Bei den Items sollte spätestens klar sein, das man mehr machen muss als nebenherzulaufen.
Die sind imba(!) für richtig classic.

**Comment by ary1** [comment]
Quest funktioniert im Moment so wie sie soll, leider bleibt Taelan nach seinem Tod einfach beim Turm liegen. 
Ein abgeben der Quest "Scharlachrote Täuschung" und annehmen der Quest "In den Träumen" ist somit nur nach Serverneustart möglich.

**Comment by Dotox** [comment]
Sollte mittlerweile korrekt respawnen
