### ISSUE TITLE
AQ20: General Rajax Event

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1268]
Hi,

die Waves kamen nach Ansprechen des General Lieutnant Andorov nicht automatisch, deshalb war es möglich die Mobs automatisch zu pullen. Als wir das versuchten, gab es immer kurz bevor ein Mob starb, einen Serverdown.

Grüße

**Comment by nightblizard** [comment]
Dürfte mit dem nächsten Update behoben sein - bitte weiter beobachten!

**Comment by ircfelix** [comment]
Merci! Kanns heut ned beobachten da ich jetz ne ID habe. Aber wann anders dann :-)

**Comment by Drachling** [comment]
Zwei neue Fehler:
- wenn die NPCs mit Verbänden geheilt werden, greifen diese die Mitglieder des Schlachtzuges an, sind aber nicht angreifbar.
- Die Gruppen kommen zu langsam, sobald der Hauptmann stirbt sollte direkt die nächste Gruppe kommen, und man kommt zwischen den Gruppen "Out of Fight" und kann rezzen und Mana reggen.

**Comment by g3n3a** [comment]
Letzter Punkt: Nein, ich hatte die Aura auch ohne Respektvoll beim Zirkel.
