### ISSUE TITLE
drohnen außerhalb benutzbar

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1269]
wenn man in aq ist und auf seine drohne aufsteigt, der server dc hat und die raidgruppe aufgelößt wurde steht man aufgemountet vor aq und kann überall hinreiten

**Comment by Slimmer2** [comment]
Aber draußen kann man es nicht benützen, oder?

**Comment by Sabbaer** [comment]
richitg, grad nochmal getestet, man kann drinnen aufmounten, und dann einfach rauslaufen und bleibt auf dem mount
