### ISSUE TITLE
Spawn Zeit von "Leutnant Benedict"

### ISSUE THREAD

**Issue by Wedivierzig** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1271]
Der NPC "Leutnant Benedict" befindet sich Durotar/Klingenhügel/Burg Tiragarde und seine respawn Zeit ist viel zu hoch. Ich habe ihn gerade gekillt, da spawnte er nach evt. 20sec wieder

**Comment by Slimmer2** [comment]
20Sek. ist zu hoch?
Laut Datenbank hat er 25 Sek.

**Comment by Rushor** [comment]
5 min default wert sollte es sein
