### ISSUE TITLE
AQ20 - Ossirian: Widerstände

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1274]
**Welches Verhalten wird beobachtet?**
Ossirian hat gegen alle Zauberschulen (mit Ausnahme von Arkan) extrem hohe Widerstände (es war von Widerständen von 1000 die Rede bei uns im Raid), so dass damit kaum Schaden gemacht werden kann. Dies ändert sich auch nicht, wenn er mit einem Kristall geschwächt wird und er gegen eine Zauberschule anfällig wird.

**Wie sollte es sich verhalten?**
Der Widerstand der Zauberschule gegen welche er gerade anfällig ist, sollte nicht so hoch bleiben, damit Caster mit Spells aus dieser Zauberschule deutlich erhöhten Schaden anrichten können. Gleichzeitig sollten die Widerstände nach Ablauf der Anfälligkeit wieder auf den Ursprungswert angehoben werden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://wowwiki.wikia.com/wiki/Ossirian_the_Unscarred
>  crystals will pop up around the zone that when activated will debuff him and make him weak to a particular school of magic.

http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Die-Ruinen-von-AhnQiraj-791238/8/
> Diese Pylonen machen Ossirian auch anfällig für jeweils eine Art von Magieschaden - gegen alle anderen hat er außergewöhnlich hohe Resistenzen.

http://www.tentonhammer.com/node/26629
> His resistance to spells of
this type drops significantly and all casters should try to focus on that type of damage.

Video aus Sicht eines Warlocks: https://www.youtube.com/watch?v=qb0zZ3xkKLk
Video aus Sicht eines Mages: https://www.youtube.com/watch?v=W6Ovud6fCwI

**Links aus unserer Datenbank**
Ossirian: http://datenbank.welli-it.de/?npc=15339
Fire Weakness: http://datenbank.welli-it.de/?spell=25177
Frost Weakness: http://datenbank.welli-it.de/?spell=25178
Nature Weakness: http://datenbank.welli-it.de/?spell=25180
Aracane Weakness: http://datenbank.welli-it.de/?spell=25181
Shadow Weakness: http://datenbank.welli-it.de/?spell=25183

**Comment by Slimmer2** [comment]
Bei Arkan hat er nur 75 Ressi

**Comment by xorann** [comment]
Funktionierte heute einwandfrei.
