### ISSUE TITLE
AQ20 - Ossirian: Ossiriankristall

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1275]
**Welches Verhalten wird beobachtet?**
Bevor der Kampf gegen Ossirian gestartet wird, ist kein Ossiriankristall im Raum vorhanden.

Anmerkung: Beim ersten Pull ist nachdem der Boss gepullt worden ist in der Mitte des Raumes ein Kristall gespawned. Bei jedem weiteren Versuch waren die Kristalle deutlich weiter weg.

**Wie sollte es sich verhalten?**
Es sollte in der Mitte des Raumes ein Ossiriankristall vorhanden sein, noch bevor der Boss gepullt worden ist. Erst danach sollten die Kristalle zufällig im Raum erscheinen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://wowwiki.wikia.com/wiki/Ossirian_the_Unscarred
>  Before the pull ... Have the tanks stand up by the first crystal, behind it, ...

http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Die-Ruinen-von-AhnQiraj-791238/8/
> ... auf einem Reittier gepullt und zu dem ersten Kristall gezogen. Ein anderer Spieler betätigt den Kristall einige Zeit bevor Ossirian am Fuß der Treppe ist ...

Video bei welchem der Kristall vor dem Pull sichtbar ist: https://www.youtube.com/watch?v=qb0zZ3xkKLk#t=0m14
Weiteres Video welches kurz nach dem Pull beginnt: https://www.youtube.com/watch?v=W6Ovud6fCwI

**Links aus unserer Datenbank**
Ossirian: http://datenbank.welli-it.de/?npc=15339
Ossiriankristall: http://datenbank.welli-it.de/?object=180619

**Comment by Dotox** [comment]
Nicht ganz, das kam erst mit 1.11.0

Ossirian the Unscarred - There is a new crystal that will be visible before the encounter begins. Players can use this crystal just like any other crystal in the encounter, but it cannot come back up during the encounter. 

http://wowwiki.wikia.com/wiki/Patch_1.11.0

**Comment by Garlesh** [comment]
Ist es denn gewollt, dass immer nur 1 Kristall da ist? Im normalfall sollten mehrere Kristalle gleichzeitig da sein, zumindest soweit ich mich entsinne. Wir hatten teilweise Kristalle so weit auseinander, dass es unmöglich war ihn innerhalb von 45 Sekunden von A nach B zu bekommen.

**Comment by dagochen** [comment]
Mit 1.11 kam auch die Mechanik, dass man infight nicht mehr reinlaufen kann. Dies ist aktuell leider nicht möglich, da die Meldung kommt, dass man die Instanz während eines Bosskampfes nicht betreten kann. Also bitte entweder oder, aber nicht mal hü und mal hott.
