### ISSUE TITLE
Suntarasteine

### ISSUE THREAD

**Issue by grindbox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1276]
Bei der Quest (http://datenbank.welli-it.de/?quest=3367/Suntarasteine) steht der zu begleitende Quest-NPC nicht auf, sprich die Eskorte fängt nicht an. Sehr schade, weil die Questreihe eigtl ganz toll ist, ^^

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/642
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/147

**Comment by grindbox** [comment]
hab ich in der suche nich gefunden

**Comment by hraesvelgr** [comment]
bei github ist die sufu manchmal bisschen abgedreht. du musst nach dem gesamten wort suchen (suntarateine). nur nach "suntara" zu suchen bringt keine ergebnisse :-/
