### ISSUE TITLE
Kanalisierte Zauber LoS

### ISSUE THREAD

**Issue by dreezyc** [ClassicWoW/Nefarian_1.12.1_Bugtracker#128]
Kanalisierte Zauber, wie zum Beispiel Arkane Geschosse, sollten auch außerhalb des Sichtfelds Schaden verursachen.

Im Moment wird der Zauber weiterhin gewirkt, aber kein Schaden verursacht.

Schritte zur Reproduktion:
1. Kanalisierten Zauber auf einen Gegner wirken.
2. Den Gegner außerhalb des Sichtfelds gehen lassen.
3. Beobachten, wie kein Schaden mehr verursacht wird.

Getestet habe ich dies nur für Arkane Geschosse, es handelt sich jedoch vermutlich um ein allgemeines LoS issue, wie man am frost trap report sieht.

**Comment by wahaxlekuke** [comment]
Funktioniert. Mit Arkane Geschosse und Gedankenschinden ausprobiert.
