### ISSUE TITLE
AQ20 - Buru the Gorger : Phase 2

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1280]
Welches Verhalten wird beobachtet?
Der Boss fixiert in Phase 2 immer noch zufällige Spieler und muss von diesen gekitet werden.

Wie sollte es sich verhalten?
Der Boss sollte in dieser Phase normal tankbar sein.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=JrQflmHhxdg in p2 kassieren die Targets normale hits und der Boss zeigt das normale Aggroverhalten: Reset bei Todstellen/Eisblock und er ist tankbar, 
https://www.youtube.com/watch?v=rqZplJOeSx0
wenn auch nicht spottbar.

Links aus unserer Datenbank
Buru the Gorger: http://datenbank.welli-it.de/?npc=15370

**Comment by Garlesh** [comment]
Ich schmeiß mal folgendes mit rein:

Phase 2 starts around 20%, Buru will start shaking and his shell will burst off. He now will do a debuff 
to everyone which does massive damage. You have more or less 30 seconds to kill him or it will be a wipe. At this point, he hits for far less damage (750 to cloth) and lacks the Dismember bleed effect. He also has a standard aggro list (although Phase 2 is an aggro wipe,) however, it is not advisable you try to tank him. 

Wär super, wenn nochmals untersucht werden würde, ob die Bleeding in p2 gewollt ist, die er zu Zeit macht.

**Comment by Horim** [comment]
Ist zumindest im zweiten Video nichts von ner Blutung zu erkennen, da der Tank bei weitem nicht den dmg der Blutung kassiert.

**Comment by Drachling** [comment]
Folgende Fehler sind uns aufgefallen:
- wir haben den Boss "per Hand" von 27% auf 24% vor dem letzten Ei gehauen, dann das Ei scheinbar nicht genau getroffen und der Boss hatte nach dem Ei noch 22%, hat aber trotzdem seine Schädelplatte weg gesprengt, dies sollte aber erst unter 20% passieren.
- wenn Buru seine Schädelplatte weg sprengt sollte eine kurze Animation kommen, die dem Raid und dem Tank 1-2 Sek geben sollte, sich zu positionieren.

**Comment by g3n3a** [comment]
Bei uns resettete Buru's stackende Bewegungserhöhung nicht in P2. Er wurde einfach immer schneller und konnte daher mit der derzeitigen Untankbarkeitsmechanik nicht getötet werden.

**Comment by Dotox** [comment]
Die Animation wird leider durch irgendwas unterbrochen. Rest fixed
