### ISSUE TITLE
AQ20 - Ossirian: Anzahl Ossiriankristalle

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1281]
**Welches Verhalten wird beobachtet?**
Während mehreren Versuchen haben wir immer nur einen Ossiriankristall gleichzeitig finden können.

**Wie sollte es sich verhalten?**
Es sollten immer mehrere Ossiriankristalle gleichzeitig vorhanden sind.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
In diesem Video sind einmal drei Kristalle gleichzeitig zu sehen:
Kurz im Hintergrund bei 4m38: https://www.youtube.com/watch?v=Je2USKK2qhs#t=4m38
Im Vordergrund bei 4m41: https://www.youtube.com/watch?v=Je2USKK2qhs#t=4m41
Wieder im Hintergrund wird bei 4m52 ein Kristall aktiviert (auf der anderen Seite im Vergleich zum ersten Kristall): https://www.youtube.com/watch?v=Je2USKK2qhs#t=4m52

Bei 0m07 ist hier im Voice Chat von einem zweiten Kristall die Rede: https://www.youtube.com/watch?v=alnrFsaPsq8#t=0m07
Nochmals bei 0m42: https://www.youtube.com/watch?v=alnrFsaPsq8#t=0m42

**Links aus unserer Datenbank**
Ossirian: http://datenbank.welli-it.de/?npc=15339
Ossiriankristall: http://datenbank.welli-it.de/?object=180619

**Comment by dagochen** [comment]
Waren immer 2 auf einmal.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1275#event-490320631

**Comment by dagochen** [comment]
Mit 1.11 kam auch die Mechanik, dass man infight nicht mehr reinlaufen kann. Dies ist aktuell leider nicht möglich, da die Meldung kommt, dass man die Instanz während eines Bosskampfes nicht betreten kann. Also bitte entweder oder, aber nicht mal hü und mal hott.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1275#issuecomment-164193196

**Comment by Bonfuzius** [comment]
Die Quelle aus den Patch Notes von 1.11 besagt lediglich, daß der Kristall zum Start des Kampfes noch nicht da war. Hier geht es darum, daß mehr als en Kristall gleichzeitig da sein sollte.

Hier ist eine Quelle vor Patch 1.11, die sich auf das eigentliche Thema dieses Issues bezieht: https://www.youtube.com/watch?v=6JOT5zZ2xNE

Man sieht gleich beim Pull, daß sofort zwei Kristalle spawnen und bei 4:55 erkennt man durch den Kameraschwenk auch wieder zwei ziemlich nah beinander.

Momentan ist es gefühlt einfach so, daß lediglich ein Kristalle genau auf der gegenüberleigenden Seite erscheint und es manchmal sehr schwierig ist es vor dem Supreme Mode dorthin zu schaffen.
