### ISSUE TITLE
Heldenhafter Stoß - Wutverlust

### ISSUE THREAD

**Issue by uggeluggel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1283]
aufgrund von willkür geschlossen
wenn die serverleitung klare bugs nicht fixxen will brauch ich auch nix schreiben

**Comment by Slimmer2** [comment]
Wieso steht in der Datenbank das es 150 Mana benötigt?

**Comment by uggeluggel** [comment]
Schurkenfähigkeiten werden auch mit Mana verrechnet. Ich nehme an um keine zweite bzw dritte Energieressource eintragen zu müssen.   ¯\_(ツ)_/¯

**Comment by uggeluggel** [comment]
Bitte auch markieren. Gibt keine Patchnotes die sagen, dass es geändert wurde.

**Comment by Schmoha** [comment]
Vielleicht könnte das hier hilfreich sein in diesem Thema:
https://vanilla-twinhead.twinstar.cz/?issue=2687

**Comment by uggeluggel** [comment]
Spalten dazueditiert. Siehe oben.

**Comment by uggeluggel** [comment]
Habe bisher keine Quellen fürs Spalten gefunden. Wird sich denke ich auch nicht ändern.

**Comment by testear** [comment]
Hat irgendjemand eine Ahnung was genau hier stand?
