### ISSUE TITLE
Heldenhafter Stoß - Zu wenig Wut

### ISSUE THREAD

**Issue by uggeluggel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1284]
aufgrund von willkür geschlossen
wenn die serverleitung klare bugs nicht fixxen will brauch ich auch nix schreiben

**Comment by Horim** [comment]
Kann ich mich nur anschließen, es ploppt am Ende des Swingtimers die Meldung "Nicht genug Wut" auf und der Autohit setzt aus. Ist ein wenig unbehaglich den Skill vor Ende des Swingtimers mit Esc zu deaktivieren.

**Comment by Horim** [comment]
Das Gleiche tritt auch bei Spalten auf.
