### ISSUE TITLE
Raid & Server Dc = Id vertauscht

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1285]
Hi, 

Wenn man raidet und Währenddessen der Server einen Dc hat, kriegen alle Spieler im Raid eine neue Id. Dies ist sehr von Nachteil für das realmplayers raidtracking, da ein raid je nach Dc-Verhalten teilweise sogar nur in einzelne Bossfights gesplittet aufgezeichnet wird. Das hat wiederrum zur Folge, dass die Raidstats nicht richtig funktionieren. Ich habe schon mit dem dev der Seute kommuniziert und er sagt das Problem ist von seiner Seite aus nicht lösbar.

Tldr: raid id ändert sich nach server Dc, sollte nicht so sein.

Danke im Vorraus für den fix,

Felix

**Comment by nightblizard** [comment]
Mehr Informationen für die Zukunft:
Zur Zeit werden nach jedem Serverneustart (ob gewollt oder ungewollt) die IDs von 1 auf neu angeordnet. Wir könnten dieses Zurücksetzen deaktivieren, um das angesprochene Verhalten zu unterbinden, dabei sollte jedoch vorher unbedingt darauf geachtet werden wie viele Bytes wir zur Darstellung der IDs haben, da sonst mit ungewollten Überläufen zu rechnen ist.

**Comment by ircfelix** [comment]
Danke dass ihr das in Angriff nehmt! :-)

**Comment by Dotox** [comment]
Wir werden die Mechanik nicht ändern
