### ISSUE TITLE
Katzen im Stealth

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1286]
Hallo,

seit kurzem bricht Stealth bei Katzen (vllt auch bei Schurken?) nicht mehr, wenn sie Kräuter einsammeln. Es bricht aktuell erst, wenn das Kraut bereits eingesammelt wurde. Dies sollte wieder so sein, wie vorher, als es bei Beginn des Einsammelns gebrochen wurde.

**Comment by Haudraufinix** [comment]
laut gildenkollege auch bei Schurken, wirkt auch auf sachen wie Kisten öffnen!

**Comment by dagochen** [comment]
Wie ist es im PvP beim Tappen im Arathi? Geht das auch? Wenn ja, bitte mit erhöhter Prio bearbeiten.

**Comment by Haudraufinix** [comment]
Hab ich nicht getested, ich denk aber mal das würd auch gehen

**Comment by ChichiWarrior** [comment]
Push!
