### ISSUE TITLE
AQ 40: Wächter des Anubisath

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1287]
Die erste Gruppe von Wächtern des Anubisath in AQ 40 Respawnt, sobald wir die zweite Gruppe bzw. den Obsidianauslöscher gepullt wird. Laut Bossmods sollten die Wächter des Anubisath 30 Minuten Respawn Timer haben.

**Comment by Drachling** [comment]
Dazu kommen die Fehler:
- die Wächter haben teilweise die gleichen Fähigkeiten und daher hat der letzte nur 2-3 Skills und die Gruppe ist einfacher.
- die Fähigkeiten nicht weiter geben werden, wenn die anderen Mobs LoS gezogen werden.
- Der Manaburn zieht so gut wie kein Mana ab.

**Comment by g3n3a** [comment]
Wir habens auch mit LoS versucht. Manchmal übernehmen die letzten Wächter einfach die Fähigkeiten der vorherigen nicht. Unterschiedliche Fähigkeiten hatten sie bei uns alle.
