### ISSUE TITLE
AQ 40: Prophet Skeram

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1288]
Wenn Skeram sich portet und sein neues Ziel nicht in Range hat, macht er seinen Erdschock ca. im 0,5 Sekunden Takt. Das macht ca. bei jedem Teleport ca. einen Toten.

**Comment by Haudraufinix** [comment]
Das ist richtig, darum muss ihn ein Tank sofort an sich binden ;)

**Comment by hraesvelgr** [comment]
naturresi!!!!

**Comment by Drachling** [comment]
Der Boss sollte den Erdschock auch nur spamen, wenn KEIN Spieler im Nahkampf ist.
Das ist in diesem Video sehr gut zu sehen bei 1:17, da rennt Skeram einmal komplett druch die Caster OHNE einen Erdschock, weil immer jemand in Melee-Reichweite ist.
https://www.youtube.com/watch?v=l8D1N1jlM1I

**Comment by hraesvelgr** [comment]
also sollte er kein festgelegtes, neues ziel haben, sondern einen aggroreset bekommen, und den nächstbesten spieler angreifen. @Drachling

**Comment by ircfelix** [comment]
@hraesvelgr: Das hat er nicht geschrieben.

Meinetwegen kann er ja Erdschock auch machen, aber alle 0,5s KANN einfach nicht richtig sein.

**Comment by Haudraufinix** [comment]
Doch, das ist Richtig, der macht etwa 4k Naturschaden pro Sekunde, was 2 Erdschocks entspricht. Ist sogar heute aufm Offi noch so.

**Comment by Garlesh** [comment]
Man wird als tank, wenn man mit vollem movementspeed den Boss mit sich zieht, einfach vom Erdschock gekillt. Scheint mir auch ein bisschen fragwürdig.

**Comment by nightblizard** [comment]
-Prophet Skeram spammt seinen Erdschock nicht länger ganz so schnell, wenn sein Ziel nicht in Nahkampfreichweite ist (behebt auch den von @Garlesh genannten Fehler, da Skeram nun hinterherrennen kann)
-Prophet Skeram und seine Illusionen suchen sich nicht länger nach dem Teleportieren ein zufälliges Ziel im Raid aus, sondern das naheliegenste. (Hinweis: Der Aggroreset findet trotzdem statt, sie laufen jedoch einfach nicht mehr Amok, wenn ein Dps Stop stattgefunden haben sollte)

**Comment by ircfelix** [comment]
<3

**Comment by hraesvelgr** [comment]
immer schön testen und rückmeldung geben

**Comment by Garlesh** [comment]
Vielen Dank für den schnellen Fix, wird es sicher nächste ID angenehmer machen.:)

**Comment by xsicht** [comment]
also die Änderungen scheinen heute NICHT funktioniert zu haben

**Comment by Haudraufinix** [comment]
Xsicht bitte beachte, dass wenn ein Zauber fliegt, wenn sich Skeram gerade teleportiert, dieser unmittelbar nach dem blink einschlägt und du damit "initialaggro" erhälst. Ist bei uns im Raid auch passiert, aber er schien gestern rein vom Gefühl her zu funktionieren.

**Comment by ircfelix** [comment]
Der Erdschock kommt jetzt nur noch im Sekundentakt, was tatsächlich bei versehentlichem Aggro ziehen Überlebenschancen lässt.

**Comment by xsicht** [comment]
ich weiss nicht wies den anderen gilden ging aber mMn funktionieren folgende elementare punkte nicht:
- Aggroreset nach Blink funktioniert nicht richtig (kA ob nur manchmal oder immer), noch fliegende casts von zuvor würde ich ausschliessen, weil teils einfach skeram weiter an einer person bleibt, auch wenn man schildschlag, hs und noch paar andere sachen drauf hat
- skeram sollte keinen erdschock machen, solange jemand in melee range steht, es scheint als würde der erdschock nur ausbleiben, wenn derjenige mit aggro in meleerange steht
- die hitbox von skeram ist viel zu klein

zusammen mit den teils extremen serverlaggs ist dieser encounter echt extrem mühsam
