### ISSUE TITLE
AQ 20 Ayamiss der Jäger

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1289]
Welches Verhalten wird beobachtet?
Ayamiss befindet sich vor dem Pull vor seinem Altar.

Wie sollte es sich verhalten?
Ayamiss sollte bevor er gepullt wird genau über seinem altar schweben.

Schritte zur Reproduzierung
Ayamiss richtig platzieren,

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=0VrfjbaQ7AU

**Comment by Rushor** [comment]
mit wotlk wurde er iwann mal vor den altar gemoved, die position ist wohl zu aktuell :D

**Comment by hraesvelgr** [comment]
warum hat der ne baumgestalt? pre tbc patch?

**Comment by Mafyo** [comment]
wahrscheinlich, aber alle anderen Videos zeigen ihn auch oben auf dem Altar, war nur die beste Qualität, alle anderen wurden mit einem Toaster aufgenommen...

**Comment by nightblizard** [comment]
Ayamuss spawnt nun auf dem Podest.

**Comment by Rushor** [comment]
ein aya MUSS für jeden raider :D
