### ISSUE TITLE
Mac OS Fähigkeiten-Ränge

### ISSUE THREAD

**Issue by bmwc** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1291]
Hallo,

Wenn ich von einer Fähigkeit einen neuen Rang erlerne, dann muss ich ihn am Mac vom Zauberbuch manuell mit dem alten Zauber in der Aktionsleiste austauschen.
Am Windows-Rechner allerdings geht dieser Vorgang automatisch.

Lg

**Comment by Slimmer2** [comment]
Die Zauber muß man auch bei Windows manuell austauschen.
Bei Klassen Schurke und Krieger trifft das nicht zu, da diese immer nur den höchsten Rang haben.

**Comment by bmwc** [comment]
Ah okey danke! Dann lag es am Schurken.

**Comment by hraesvelgr** [comment]
working as intended und close :)
