### ISSUE TITLE
Juju Might + Winterfall Firewater

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1292]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen

Server-Version: [1.2.6]

[Juju Might]  (40 AP)  http://datenbank.welli-it.de/?item=12460   
und 
[Winterfall Firewater] (35 AP)  http://datenbank.welli-it.de/?item=12820

Wie ist es? -- Wenn ich beides nehme wird mir beides angerechnet an Attackpower

Wie sollte es sein? -- Nur eins sollte angerechnet werden

Quelle: Ticket aufgemacht und gefragt ob es erlaubt ist, antwort: nein.
.

**Comment by uggeluggel** [comment]
Falsch. Sollte stacken.

http://www.wowhead.com/item=12451/juju-power

By Falcore (2,560 – 6·24) on 2006/11/24 (Patch 1.12.2)		
Stackable with Winterfall Firewater and JuJu Might.

**Comment by Sabbaer** [comment]
seit wann? wizo sollte das nicht erlaubt sein, antwort eines devs und gms wäre sehr interessant, meine information ist da anders

**Comment by uggeluggel** [comment]
Juju Might = AP  Juju Power= Stärke

**Comment by dagochen** [comment]
vorhin hatte mal wer folgendes gepostet (wurde aber wieder gelöscht? nur warum?):

>Falsch. Sollte stacken.
>
>http://www.wowhead.com/item=12451/juju-power
>
>By Falcore (2,560 – 6·24) on 2006/11/24 (Patch 1.12.2)
>
>Stackable with Winterfall Firewater and JuJu Might.

Was stimmt denn nun?

**Comment by Seniorash** [comment]
Melee AP und ap?

**Comment by dagochen** [comment]
gibt beides nur melee ap :)

**Comment by Seniorash** [comment]
Nein

**Comment by uggeluggel** [comment]
Das ist richtig Senorash, dennoch sollte es nicht mit Firewater stacken.

**Comment by dagochen** [comment]
> Nein. Juju gibt auch range ap
Falsch.

**Comment by Seniorash** [comment]
Was soll das einem sagen? Bein feuerwasser steht explizit melee AP und beim anderen ap

**Comment by dagochen** [comment]
Was im Tooltip steht, ist komplett irrelevant. Das einzige was zählt, ist der Effekt des Zaubers.

**Comment by hraesvelgr** [comment]
feuerwasser soll laut wowhead auch ranged ap erhöhen, auch wenn melee ap draufsteht.

**Comment by Slimmer2** [comment]
Kam da später ein Patch der dies änderte?

**Comment by dagochen** [comment]
Ja. Zu Classic war ALLES an BUFFS Melee-AP only. Einzigste Ausnahme: Volltreffer-Aura vom Hunter.
Angriffskraft auf Gear gibt beides. Hab da ewig rumgesucht und mehrere Quellen gefunden die das so belegen, da ich mir gewünscht hatte das Hunter z.B. auch von Onybuff, DMNord-Buffs und co profitieren, was leider alles nicht für uns Hunter funzt.

**Comment by hraesvelgr** [comment]
http://wow.allakhazam.com/forum.html?forum=243&mid=116255807757703971
der sagt, dass das juju auch ein guter buff für den hunter ist, ABER!:
Juju Might - Does not add to RAP, but still handy for the Demons where melee is required.


https://web.archive.org/web/20060614014938/http://www.thottbot.com/?i=38651



>
    auch ganz brauchbar:

    http://www.thottbot.com/?i=38651 



    nein nutzlos da die +ap nur im nahkampf zählen

    bis mittwoch sind die elementar wetzsteine noch super

**Comment by Horim** [comment]
Generell stacken die Effekte auf unserem Server weil es nicht die gleichen Buffs sind:
- Feuerwasser 35 Melee-AP (hier aufm Server)
- JuJu 40 AP (hier aufm Server)

Falls das nicht gewollt ist, wäre ein Statement von offizieller Seite hilfreich.
Dann kann man aufhören sich beide buffs zu schmeißen. 

Wir haben das bereits in ähnlicher Form für die Dunkelmondbuffs:
Ingame stacken diese Buffs, jedoch liegt diesbezüglich ein Statement vor, das man diese Buffs nicht stacken darf und es wird dementsprechend auch nicht gemacht

**Comment by uggeluggel** [comment]
Gibt doch schon ein offizielles Statement dazu.

http://community.mmobase.de/talk-und-allgemeines/5376-welche-buffs-stacken-erklaerung.html

Q: Wie siehts denn mit den Jujus aus Winterspring aus? Bilden diese eine eigene Kategorie oder gehören sie zu Elixieren bzw. Zaubern?
A: Jujus zählen als Elixiere.

**Comment by Horim** [comment]
Mein Vorschlag bezüglich eines Statements bezog sich nicht auf die Zuweisung für Elexiere,
sondern ob es gewollt ist das es Melee-AP (Feuerwasser) und AP (Juju) gibt und ob das dann stacken darf. Pauschal sind es zwei verschiedene Elexiereffekte, die Frage ist also ob es zwei verschiedene Effekte sein sollen und ob in dem Fall das stacken erlaubt ist.

**Comment by uggeluggel** [comment]
https://www.youtube.com/watch?v=5MRdRvkCU6U

Ist bisschen schwer zu erkennen, aber in der Buffleiste links sieht man das grüne Fläschchen vom Winterfall Firewater nicht jedoch den Juju Might buff. Bei den anderen beiden Rogues in seine Gruppe sieht man den Firewater Buff aber kein Juju Might. Hätte es gestackt hätte der Schurke in dem Video das mit Sicherheit ausgenutzt.

**Comment by Horim** [comment]
Naja das fehlen beweist leider erstmal gar nichts. Falls es den Spielern im Video um Maxbuffs ginge, hätten diese sicherlich 40 AP Jujus statt 35 AP Feuerwasser benutzt, da anscheinend auch das 30 Stärke Juju statt der 25 Stärke Elexiere benutzt wurden. Keine Ahnung ob die das Juju einfach nicht kannten oder was auch immer. Interessanter wären Ausschnitte auf denen man das AP-Juju aber kein Feuerwasser sieht =(

**Comment by uggeluggel** [comment]
Hier stehts zwar nicht wirklich, aber es wird angedeutet, dass es stacken sollte. Bzw bei den Dingen die nicht stacken sind Kommentare hinterlegt.

http://wow.allakhazam.com/forum.html?forum=243&mid=116255807757703971
