### ISSUE TITLE
anti fear, häufig kein effekt

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1295]
Welches Verhalten wird beobachtet?
anti fear vom zwerg priester hat manchmal keinen effekt obwohl es auf dem target ist
Wie sollte es sich verhalten?
anti fear sollte immun gegen fear effekte machen
Schritte zur Reproduzierung
raids zuguggen mit anti fear auf dem tank, ony bugg trio nefarian weltenbosse etc.

Zusätzliche Informationen (Screenshots, Videos, etc.)
leider keine versuche das noch aufzunehmen

dies ist 100 prozent so und ist nicht nur 1 mal vorgekommen in den letzten 2 jahren sondern sehr häufig

Links aus unserer Datenbank
edit von hraesvelgr: http://datenbank.welli-it.de/?spell=6346
"fear ward". nicht "fearward" :D
edit sabbaer: danke

**Comment by hraesvelgr** [comment]
heute beim zg raid wurde nahezu kein fear der berserker widerstanden obwohl immer antifear drauf war.

**Comment by g3n3a** [comment]
Was ich so gesehen habe kann das unter anderem Auftreten wenn gleichzeitig ein zweiter Antifeareffekt (z.B. Berserkerwut) aktiv ist. Der Fear Ward wird dann zwar verbraucht, aber der Buff nicht entfernt.

**Comment by Garlesh** [comment]
Ich hatte das mal getestet und es kam dann immer vor, wenn man einen 2ten Immunisierungseffekt benutzt, wenn ein erster schon aktiv ist.
Heißt zB. ich habe Feaward auf mir und benutze danach Berserkerwut. Dann überschreibe ich den Fearward Immunisierungseffekt und bin nach der Wut nicht mehr Immun. Der Fearward ist dann nutzlos. Muss also theoretisch weggeklickt und neu vergeben werden.
Ich weiß nicht, wie es in Classic war, aber ich könnte mir vorstellen, dass man nach der Wut durch den Fearward wieder Immun sein sollte.
An die Devs: Soweit wir das getestet hatten überschreiben sich einfach die Auren und die Fearward Aura wird nicht neu platziert wenn die Wut ausläuft. Vielleicht hilft euch das.
Grüße,
Garlesh

**Comment by dagochen** [comment]
Fix
```c++
void Unit::ApplySpellImmune(uint32 spellId, uint32 op, uint32 type, bool apply)
{
	if (apply)
	{
		for (SpellImmuneList::iterator itr = m_spellImmune[op].begin(), next; itr != m_spellImmune[op].end(); itr = next)
		{
			next = itr; ++next;
			if (itr->type == type)
			{
				m_spellImmune[op].erase(itr);
				next = m_spellImmune[op].begin();
			}
		}
		SpellImmune Immune;
		Immune.spellId = spellId;
		Immune.type = type;
		m_spellImmune[op].push_back(Immune);
	}
	else
	{
        bool deleted = false;
		for (SpellImmuneList::iterator itr = m_spellImmune[op].begin(); itr != m_spellImmune[op].end(); ++itr)
		{
			if (itr->spellId == spellId)
			{
				
			    for (SpellAuraHolderMap::iterator holder = m_spellAuraHolders.begin(); holder != m_spellAuraHolders.end(); ++holder)
                {
                    for (uint32 i = 0; i < MAX_EFFECT_INDEX; ++i)
                    {
                        // If there is another SpellAura with same Effect still active after removing the current immunity, apply that one
                        if (spellId != holder->second->GetSpellProto()->Id && 
                        ((holder->second->GetSpellProto()->EffectMiscValue[i] == type) && (holder->second->GetSpellProto()->EffectApplyAuraName[i] == SPELL_AURA_MECHANIC_IMMUNITY))) 
                        {   
				            m_spellImmune[op].erase(itr);
                            deleted = true;
                            SpellImmune Immune;
		                    Immune.spellId = holder->second->GetSpellProto()->Id;
		                    Immune.type = type;
		                    m_spellImmune[op].push_back(Immune);
                        }
                    }
                }
                if (!deleted)
                    m_spellImmune[op].erase(itr);
               
            } 
            break;


		}
   	}
}
```

**Comment by Dotox** [comment]
>heute beim zg raid wurde nahezu kein fear der berserker widerstanden obwohl immer antifear drauf war.

Ich denke, dass ich da etwas gefunden habe. Kannst du mir die Zauber mal bitte verlinken damit ich das testen kann?

**Comment by dagochen** [comment]
Das Problem ist, dass ein Bersiwut einen Antifear überschreibt und sobald die Bersiwut ausläuft, kein Priester-Antifear mehr auf "aktiv" gesetzt wird. Genau das wird durch meinen Fix aber getan. Er schaut zu erst, ob es einen Buff gibt der den gleichen Effekt hat wie der grad ausgelaufene. Dann aktiviert es den Buff wieder und fügt die Immunität wieder hinzu. 

Fearward: http://datenbank.welli-it.de/?spell=6346
Bersiwut: http://datenbank.welli-it.de/?spell=18499
Tollkühnheit: http://datenbank.welli-it.de/?spell=1719
Todeswunsch: http://datenbank.welli-it.de/?spell=12328

**Comment by soda09** [comment]
Hey, das Problem tritt immer noch auf und zwar bei allen Klassen, nicht nur bei Tanks.

**Comment by dagochen** [comment]
Wie soll es denn bei anderen Klassen auftreten? Bei Kriegern ist es ja klar wodurch das Problem ausgelöst wird, aber bei anderen Klassen gibt es da noch keine Infos...

**Comment by soda09** [comment]
Egal welche Klasse den fearward hat, ab und an wird man trotzdem gefeard, obwohl der Buff oben ist. Bei Kriegern fällt es halt nur viel öfter auf.

**Comment by dagochen** [comment]
Screenshot würd halt auch nix bringen, man bräuchte wohl schon bisschen Videomaterial um den Zusammenhang und Reproduzierbarkeit zu erkennen ;)

**Comment by soda09** [comment]
Ja schon klar. Aber dann glaubst du es mir, dass es bei anderen Klassen auch auftritt^^
Falls ich es reproduzieren kann, mache ich gerne ein Video aber ich lauf bestimmt nicht 24/7 umher und nehme zeitgleich auf^^.
Bei Kriegern tritt der Bug immer noch auch, also ist es wohl nicht 100% klar was diesen Bug verursacht.

**Comment by Baraz** [comment]
Evtl. [sowas](http://datenbank.classic-wow.org/?item=10418) genutzt?

**Comment by Slimmer2** [comment]
Dann hätte man doppelten Schutz, das man nicht gefeart wird

**Comment by dagochen** [comment]
Und wenn eins ausläuft, geht das andere nicht mehr....

**Comment by soda09** [comment]
Hier mal nen Link zu nem Screen aus mKampflog: https://www.pic-upload.de/view-32747115/FearwardBug.png.html
Ich hatte Fearward, wurde gefeart und erst dann wurde mein Fearward despellt. Habe es leider nicht rechtzeitig geschafft n Screen von der Buffleiste zu machen, daher Kampflog.
