### ISSUE TITLE
siegel der rechtschaffenheit korrekte schadensformel

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1296]
wie es ist: siegel d er rechtschaffenheit verursacht bei jedem hit schaden zwischen wert x und y wobei x<y. der schaden des siegels wird durch den schaden des individuellen waffenagriffs beeinflusst.

wie es sein sollte: der schaden des siegels wird nur durch waffentempo und spelldmg-koeff beeinflusst, und hat dadurch einen absolut konstanten wert an schaden.
koeffizienten sollten sein:
bei einhandwaffen: waffenspeed * 10%
bei zweihandwaffen: waffenspeed * 12%

das ganze wird nach folgender formel für rang 8 berechnet:

einhand = (22 * (WSP - 1,5)) + 20 + (spelldmg * 0,1)
zweihand = (22 * (WSP - 1,5)) + 20 + (spelldmg * 0,12)

danke an dago für seine anteilnahme :)

btw: soll ich zu jedem rang die korrekte formel hinschreiben?

falsches beispiel: 
![wowscrnshot_121515_094308](https://cloud.githubusercontent.com/assets/9222522/11806053/bc6d0126-a310-11e5-968c-bf15f734f9a1.jpg)

**Comment by dagochen** [comment]
> wie es sein sollte: das siegel sollte einen festen schadenswert verursachen, welcher durch den waffenschaden, die waffengeschwindigkeit und spelldmg beeinflusst wird. der schaden sollte bei jedem hit jedoch absolut gleich sein (ausgenommen teilresists oder andere verringerungen)

>momentan scheint es so zu sein, als ob die berechnung des siegelschadens fast schon random ist, ähnlich wie beim verursachten waffenschaden. es gibt ein minimum und es gibt ein maximum.

Schon bisschen widersprüchlich. Du sagst es soll mit Waffenschaden skalieren, aber ein fester Schadenswert rauskommen, der unabhängig vom Waffenschaden ist...?

Waffenschaden ist nun mal zufällig, hängt von der Waffe, dem Tempo der Waffe, den AP und Auren/Buffs ab, die diese Schadensart beeinflussen.

Was ich mir vorstellen könnte, wäre, dass bei dem Siegel der Schaden gemittelt wird und dadurch ein fester Wert entsteht. Milchmädchenvariante: (min+((max-min)/2)

Aber dafür gibts keine Quellen oder?

**Comment by hraesvelgr** [comment]
nene, das hab ich nie geschrieben :D 

ich sagte, dass der schaden vom siegel so berechnet wird, wie der waffenschaden berechnet wird, nämlich random zwischen einem minimum und einem maximum. 

aber er sollte vom waffenschaden abhängig sein, und zwar durch einen mittelwert. und der mittelwert ist fest, eine zufällige zahl zwischen minimum und maximum jedoch nicht. 
zugegeben, das stimmt nicht. es wird anscheinend nur der ap-wert berechnet. 
ich wollte damit nur ausdrücken, dass konstante werte genutzt werden, und nicht, wie momentan, random werte.

[MWS * (0.022 * AP + 0.044 * SPH)] 
http://wowwiki.wikia.com/wiki/Seal_of_Righteousness_%28old%29?direction=prev&oldid=1975577

also [waffenhand-waffenspeed * (0,022 * angriffskraft + 0,044 * spelldamage)]

wenn ich das sph richtig deute.

**Comment by dagochen** [comment]
>[MWS * (0.022 * AP + 0.044 * SPH)] 
http://wowwiki.wikia.com/wiki/Seal_of_Righteousness_%28old%29?direction=prev&oldid=1975577

Ist von 2009.

Seal of Righteousness on a one-handed weapon. 22 + (2 * (WeaponSpeed*10) - 30) = Damage per Second

Seal of Righteousness on a two-handed weapon. 33 + (2.3 * (WeaponSpeed*10) - 34.5) = Damage per Second

http://wowwiki.wikia.com/wiki/Seal_of_Righteousness_(old)?oldid=346376

Ist von November 2006

**Comment by hraesvelgr** [comment]
welche formel wird auf dem server genutzt?

**Comment by dagochen** [comment]
Bei uns wird der auf dem Tooltip angegebene Wert zufällig zwischen einer Range berechnet. Diese Range wird anhand des Waffentempos ermittelt. Sprich bei einer 1.3 Speed Waffe, hast du eine Range von 20-30 (ungefähr), bei einer 4.0 Waffe zwischen 50-70. *
                
*Werte für Rang 8

**Comment by hraesvelgr** [comment]
meiner meinung nach sollte es aber ein absolut fester wert sein, und kein wert von x bis y

**Comment by dagochen** [comment]
und das hast du woher?

**Comment by hraesvelgr** [comment]
eigene erfahrung? ich werd da sicher noch was raussuchen. aber momentan hab ich wenig zeit für eine intensivsuche^^

**Comment by dagochen** [comment]
Also die Rechnung ist schon ziemlich abenteuerlich was der Server da macht und ich hätte es anders gemacht vermutlich, aber ob das nun 20-30 oder exakt 25 Schaden macht, spielt doch keine Rolle oder?

**Comment by hraesvelgr** [comment]
hier gehts ums prinzip!!!!!!!1111!

**Comment by dagochen** [comment]
Du bist auch so nen Zufall....ehhh Reinfall :P

**Comment by hraesvelgr** [comment]
den tollsten den du finden kannst :)

so, hab jetz noch bisschen gesucht, was die ausssagen etwas eindämmen dürfte:

>Faster weapon will add damage close to lower limit, while slower weapons will deal damage closer to upper limit.
http://paladin-guide.blogspot.de/2005/12/seals.html
impliziert, dass es ein fester wert ist

> Seal of Righteousness - depends on weapon and weapon speed:

      Quote
    Coefficients are 9.2% per 1.0 Speed for 1H and 10.8% per 1.0 Speed for 2H

    Seal of Righteousness with +198 spell:

    Rank 8 (58 - 1.6 Speed 1H) | 36- 37 | 65- 66 | +29 | 15%

    Rank 8 (58 - 2.2 Speed 1H) | 47- 47 | 86- 87 | +40 | 20%

    Rank 8 (58 - 3.2 Speed 2H) | 95- 96 | 164-165 | +69 | 35%

    Rank 8 (58 - 3.7 Speed 2H) | 118-119 | 197-198 | +79 | 40%
http://forums.elitistjerks.com/forums/topic/9354-damage-coefficients/
hier schwankt der dmg gradmal um einen punkt. innerhalb der berechnung, und nicht um bis zu 30 punkte wie auf dem server. auch geil: verlässliche dmg koeffizienten!

**Comment by hraesvelgr** [comment]
aktuelle dmg range bei einer waffe von 2,4 schaden, einhand: 31-47 
schaden mit +39 spelldmg, laut der elitist jerk liste also +6,38 schaden pro hit: 34-50

also wäre der spelldmg koeff schonmal falsch, und anscheinend nur halb so groß, wie er sein sollte.

**Comment by hraesvelgr** [comment]
https://youtu.be/ogg-GpY-fPc
bei 1:00 bis 1:10 (bei 0,25 videospeed) sieht man, wie er mehrfach exakt  219 siegelschaden macht, mit einer 2,10 speed waffe.

**Comment by dagochen** [comment]
> This was recorded on a 2.4 private server reliving wow. 

Ungültige Videoquelle ;)

**Comment by hraesvelgr** [comment]
mit patch 3.0.2 wurde die ap skalierung eingeführt. davor war es nur waffenspeed und spelldmg. da beides konstant ist..... 

http://wowwiki.wikia.com/wiki/Patch_3.0.2

http://www.gamefaqs.com/boards/534914-world-of-warcraft/45997523

**Comment by dagochen** [comment]
* Old Seal of Righteousness coefficients are 10% for 1H and 12% for 2H. WoW 2.0 coefficients are 9.2% per 1.0 Speed for 1H and 10.8% per 1.0 Speed for 2H, so for example, for a hypothetical 3.0 Speed 1H weapon, it should get around 27% (9.2% * 3.o) of +spell when you use SoR.

Quelle: http://forums.elitistjerks.com/forums/topic/9354-damage-coefficients/?page=2

Sprich, das was du oben gepostet hast ist für BC, nicht für Classic :)

**Comment by hraesvelgr** [comment]
ist halt schwierig die schwelle zwischen bc und 1.12.1 zu finden. ändert aber nix daran,d ass es auf dem server definitiv falsch ist, dass es anscheinend den verursachten schaden des treffers als wert nimmt.

**Comment by dagochen** [comment]
tut es nicht.

**Comment by hraesvelgr** [comment]
https://youtu.be/ajs1iV28eQE
172 schaden ohne rache, 198 schadne mit rache (was 15% entspricht). mehrfach, zwsichen 3:50 und 4:20.

**Comment by dagochen** [comment]
Ich glaub dir ja das der Schaden immer gleich sein soll. Das habe ich von Anfang an. Nur die Quellen, die du dafür genannt hast, waren halt nicht legitim. Und du als Hauptverantwortlicher für den Bugtracker, solltest das, was ich hier gemacht habe, eigentlich selbst tun. Du solltest von alleine erkennen, dass ein Youtube-Video von einem privaten Server zu einem anderen Patchstand nicht zulässig ist. Du solltest von alleine erkennen, dass eine wowwiki-Quelle von 2009 nicht zulässig ist. Das letzte Video ist übrigens eine gute Quelle ;)

**Comment by hraesvelgr** [comment]
das mit dem privatserver war ein fehler. den seh ich ein :P 

aber ja, bei der pala mountquest sieht mans gut, da die mechanik der gegner so war, dass sie nur gegen ein siegel anfällig, und gegen alles andere immun war. das dritte siegel war siegel der rechtschaffenheit, in der reihe. deshalb MUSS bei jedem dieser events und  videos siegel der rechtschaffenheit genutzt werden. 
jetzt ist nurnoch die frage, wie der grund-dmg festgelegt wird.

**Comment by dagochen** [comment]
vermutlich die langsamste waffe bekommt 75 schaden, die schnellste 20. und alles dazwischen wird skaliert. sprich ne waffe mit 2,65 speed liegt in der mitte bei 47,5 dmg. und wenn man den grundwert ausgerechnet hat kommen halt noch so ne holy-dmg boni und so was halt rauf.

**Comment by hraesvelgr** [comment]
das ergibt wohl sogar sinn. das schnellste ist 1,5, das langsamste ist 4,0?

**Comment by dagochen** [comment]
jo das sind dann 2,2 schaden pro 0,1 waffentempo über 1,5..

![image](https://cloud.githubusercontent.com/assets/5236186/11855544/343b1b44-a44b-11e5-9c64-1c20f682713b.png)

**Comment by Acolatronico** [comment]
wäre echt nice wenn das überarbeitet wird damit man als pala tank etwas bessere chancen hat beim single target aggro halten :)

**Comment by hraesvelgr** [comment]
bleibt im endeffekt fast gleich, nur der dmg wird nomalisiert.
