### ISSUE TITLE
Schurke/Druide (Katzenform) Energie Rückerstattung

### ISSUE THREAD

**Issue by Schmoha** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1297]
Hi, die Energie vom Schurken und dem Katzenform des Druiden sollten Energie zurück erstatten bei Schadensvermeidungen.

Das letzte mal als ich hier gespielt hatte auf Nefarian war das noch fehlerhaft, ich weis nicht ob das bereits behoben ist, deshalb melde ich das mal ohne mich einloggen zu können.

Ich hab hier was vom anderen Server:
https://vanilla-twinhead.twinstar.cz/?issue=3180

Sollte 80% vom energie zurück erstatten wenn verfehlt, geblockt, ausgewichen, parriert, wiederstanden und wenn das Ziel immun ist.

Wichtig: Finishing-Moves zählen nicht zu Energie-Rückerstattung, wenn man da verfehlt, verliert man die Energie.

Wer zweifel hat, kann die Videos von dem link anschauen oder jegliche andere oldschool schurken / druiden videos angucken und sich selbst überzeugen :)

Man kann die 80% rückerstattung selbst rechnen indem man die bilder von nem video speichert mit vor- und nacher bild um das bild auszuschneiden und sehen wieviel zurück erstattet wird. Es gibt noch 1-2 quellen im internet die auch die 80% nennen, nur müsste man bissl suchen.

Kommentar:
Ich weis noch als Schurke auf Nefarian, ich hab den Gegner Hinterhalt gegeben und direkt danach Meucheln. Beides hat verfehlt und ich konnte nix anderes machen als warten bis die Energie sich gefüllt hat, bis dahin war ich auch schon fällig. Wäre wirklich nice mit diesem bugfix zu spielen.

**Comment by Dotox** [comment]
Dann bitte teste es erst und erstell dann einen Bugreport :)

**Comment by Schmoha** [comment]
Ich copy paste das hier dann falls es verbuggt ist, ist das ok ?

Wäre es dann auch hilfreich alle fähigkeiten vom schurken und druiden hier aufzulisten die energie zurückerstatten sollten?

**Comment by Haudraufinix** [comment]
http://datenbank.welli-it.de/?spell=26107

Setbonus vom Druiden der genau das macht, Wenn das so sein sollte, regeneriert man mit Wilder Biss bei Verfehlen 63 Energie, kann ich mir irgendwie kaum vorstellen

**Comment by hraesvelgr** [comment]
>Wichtig: Finishing-Moves zählen nicht zu Energie-Rückerstattung, wenn man da verfehlt, verliert man die Energie.

wilder biss ist ein finisher

**Comment by Haudraufinix** [comment]
Ah pardon, hab ich nicht genau gelesen

**Comment by hraesvelgr** [comment]
@schmoha lass einfach alles raus, was du findest :)

**Comment by Schmoha** [comment]
Yup würd ich gern, im moment gehts aber net, aber sobald ich kann werd ich gucken was ich machen kann. Wird länger dauern zb müsste man austesten ob man energie zurück gewinnt für Blenden verfehlen oder wenns das noch gibt ausweichen. Wäre gut wenn man aufm testserver das befehl haben könnte um Cooldown zu reseten unendlich mal.
