### ISSUE TITLE
Man hat manchmal passive Fähigkeiten, die man gar nicht gelernt hat.

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1299]
Welches Verhalten wird beobachtet?

Man hat aus irgendeinem Grund sporadisch Fähigkeiten, die man gar nicht haben dürfte weil man sie z.B. nicht gelernt hat. Bei mir war es Waffe der Flammenzunge vom Schamanen. Er kann das mit Level 6 gar nicht haben und trotzdem kommt es vor, dass das einfach mal procct.

Schritte zur Reproduzierung

Reproduzieren lässt sich das schwer. Einfach mal einen Schamanen erstellen und spielen. Ab und zu werden Angriffe der Flammenzunge auftauchen.

Zusätzliche Informationen

Siehe Screenshot, dass das auch im Kampflog auftaucht.
![wowscrnshot_120715_143611](https://cloud.githubusercontent.com/assets/13087478/11814489/4a084b90-a347-11e5-8fe6-a2592b239d0d.jpg)

Grüße

**Comment by hraesvelgr** [comment]
ist ein reiner schamibug.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1060
