### ISSUE TITLE
Aderlass verursacht Aggro

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1300]
Hallo!
Seit einigen Monaten erzeugt der Zauber Aderlass vom Hexer Aggro, und zwar keine Initialaggro, sondern einen festen Wert an Aggro. Wenn ich meinen Voidwalker auf einen Mob schicke, ihn nach seinem ersten Taunt auf passiv stelle und nicht mehr angreifen lasse und mit 100% Mana und HP und ohne Healthreg durch Dämonenrüstung oä. anfange Life Tabs zu casten, habe ich nach dem dritten mal die Aggro, ohne einen Punkt Dmg auf den Mob gemacht zu haben. Hab über Google nichts finden können was darauf hindeutet, dass es in Classic oder irgendwann mal so war und es erscheint mir auch sehr unlogisch, da der Spell zwar wohl so gescriptet ist, dass es ein Schadenszauber gegen sich selbst ist, aber wenn man an einem Mob Schaden verursacht, erzeugt das ja auch keine Aggro bei einem anderen Mob. Von daher gehe ich davon aus, dass es ein Bug ist und bitte um einen möglichst schnellen fix, wir Hexer kämpfen so schon genug mit der Aggro =(

http://datenbank.welli-it.de/?spell=11689
http://datenbank.welli-it.de/?spell=11688
http://datenbank.welli-it.de/?spell=11687
http://datenbank.welli-it.de/?spell=1456
http://datenbank.welli-it.de/?spell=1455
http://datenbank.welli-it.de/?spell=1454

**Comment by uggeluggel** [comment]
Rofl. Natürlich verursacht aderlass  Aggro. Gibt dir doch Mana. Aderlass verursacht sogar durch die fehlerhafte Spelldmgskalierung mehr Aggro als es eigentlich sollte - Aber das ist eine andere Geschichte.

**Comment by Wosser** [comment]
Selbst wenn man bei 100% Mana Aderlass benutzt, verursacht es Aggro.

**Comment by uggeluggel** [comment]
Ja und? Heilung verursacht auch Aggro, auch wenn sie nicht heilt. Manareg verursacht auch Aggro, wenn du trinkst. Wutreg verursacht Aggro.

**Comment by Wosser** [comment]
Das wäre mir neu.

**Comment by uggeluggel** [comment]
Frag mal einen Fury der Blutrausch zu früh nutzt ob das Aggro verursacht.

**Comment by Larnak1** [comment]
Nein, das ist nicht das gleiche in grün, da der Blutrausch in aller Regel tatsächlich auch Wut erzeugt, da der Wutbalken nicht voll ist, wenn es gezündet wird, während Wosser den Aderlass mit vollem Mana getestet hat, wo es also effektiv kein Mana erzeugen kann.

@Wosser: Schau mal in alte Aggro-Meter-Addons was da für Aderlass hinterlegt ist. Das dürfte eine relativ zuverlässige Quelle sein.

**Comment by hraesvelgr** [comment]
überheilung sollte keine aggro erzeugen, da sie einfach keinerlei effekt hat. fügst du dir selber schaden zu, verursachst du nunmal aggro, selbst, wenn du effektiv 0 mana bekommst.

**Comment by Jura500** [comment]
http://www.thehonorempire.org/forums/topic/10238-112-warlock-change/
http://blue.cardplace.com/cache/wow-warlock/1193240.htm

Auf diesen beiden Seiten wir ein Bluepost zitiert:
"Id like to make one additional clarification to quell any arguments that are still raging:

Life Tap does not generate threat.

However! After reading through a lot of the posts arguing this point, we discovered a bug in 1.12.0 only that caused Life Tap to start generating threat, meaning that players on the PTRs may have seen a version of Life Tap that was generating threat on their targets. This bug was never present in any versions prior to 1.12.0. This bug has now been fixed and will be fixed on the PTRs during their next update. It will most definitely be fixed when 1.12.0 goes live.

Thanks for the discussions and speculation on this. Your input as a community has helped us quash yet another nasty bug"

Dieser Bluepost besagt, dass Aderlass keine Aggro produzieren sollte. Es handelt sich um einen Bug, der auf dem PTR aufgetreten ist, allerdings vor dem Aufspielen von 1.12.0 schon geändert wurde.

Wosser liegt also richtit ;)

**Comment by uggeluggel** [comment]
Und darum steht das weder in den dokumentieren noch in den undokumentierten Patchnotes drin.

**Comment by Jura500** [comment]
Natürlich steht es nicht in den Patchnotes, es war ein Bug der nur in einer Version auf dem Testserver vorhanden war. Dieser Bug hat es nie auf den Liveserver geschafft.

**Comment by uggeluggel** [comment]
Ich denke schon, was aber widersprüchlich mit 

elseif powertype == mod.string.get("power", "mana") then
    me.event.threat = amount * mod.data.threatconstants.managain

ist.

**Comment by hraesvelgr** [comment]
wenns aber der bluepost schon sagt, dann wirds so sein, oder? es gibt so einige dinge die extrem verlässlich sind: blueposts und diverse gamerforen, wo es exaktes theorycrafting gibt. 
originaler als öffentliche bekanntmachungen von blizzard gehts eben nicht.

**Comment by Jura500** [comment]
Hab nochmal in der KTM-Version 17.22  gesucht.
Aus der Datei KTM_Combat:

```
	-- Special: abilities which don't cause threat
	if spellid == "lifetap" then
		me.event.threat = 0
	end
```
Damit sollte nun alles klar sein.

**Comment by uggeluggel** [comment]
Das ist nice. Welche Version hast du?

**Comment by Jura500** [comment]
Wie ich schon geschrieben habe: 17.22

**Comment by uggeluggel** [comment]
http://wow.gamona.de/forum/threads/aggro-durch-fluch-der-verdammnis.88775/page-2

Nur Manaregg die auch im Combatlogg angezeigt wird, die normale Aggro durch mp5 und Spi erzeugt keine.

**Comment by 0815Priester** [comment]
Zum Schmökern
https://forum.nostalrius.org/viewtopic.php?f=24&t=16499

**Comment by Sabbaer** [comment]
sdw verursacht auch aggro! btw

**Comment by hraesvelgr** [comment]
dann sollten wir alle warris mit sdw buffen?

**Comment by 0815Priester** [comment]
Kenzo´s Threat Guide
Certain spells are exempt, for example mana from Blessing of Wisdom or a Mana Spring totem doesnt cause threa
