### ISSUE TITLE
Spalten - Zu wenig Wut

### ISSUE THREAD

**Issue by uggeluggel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1303]
aufgrund von willkür geschlossen
wenn die serverleitung klare bugs nicht fixxen will brauch ich auch nix schreiben

**Comment by Horim** [comment]
Selbe Mechanik wie beim Heroic Strike, denke das ist ein Fehler in der Skriptabfrage.
Solange der Swingtimer vom nächsten Schlag nicht beendet ist, scheint das Skript den Befehl für die Fähigkeit anzunehmen und es erfolgt keine erneute Abfrage bei Ende des Swingtimers, wodurch das Spiel versucht den Skill auszuführen ohne zu berücksichtigen das keine Wut da ist. Dann fällt auf das die Wut fehlt und statt den eigentlichen Autohit auszuführen wird's einfach geskipped.

Müsste wahrscheinlich eine zusätzliche Abfrage am Ende des Swingtimers erfolgen, die in etwa so aussieht (in Anlehnung an gängige Programmiersprachen): Beim Befehl für Cleave/Heroic strike
if remaining Swingtimer <= 0,01 s and Rage >= 20 (15)
  -> Cleave (Heroic Strike)
 elseif remaining Swingtimer <= 0,01s and Rage <= 20
 -> Autohit
endif
