### ISSUE TITLE
Aderlass skalierung mit spelldamage auf equip

### ISSUE THREAD

**Issue by dolomit** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1306]
Liebes wow-classic.org team

Aderlass Skalierung mit Spelldamage auf Equip

Welches Verhalten wird beobachtet?
Das auf dem Equip gesammelte Spelldamage erhöht die von Aderlass generierte Manamenge

Wie sollte es sich verhalten?
Nur den von Spelldamage-Buffs erhaltene (Flask, Schattenelixier) Spelldamage darf Aderlass erhöhen.

Schritte zur Reproduzierung
Bei meinem Hexxenmeister ist dies der Fall.

Zusätzliche Informationen (Screenshots, Videos, etc.)
"Aderlass: Dieser Zauber profitiert jetzt von Effekten, die den verursachten Zauberschaden erhöhen. Bei Rang 3 und höher wird der Grundwert der verlorenen Gesundheit und des zugewonnenen Manas um 80% der Zauberschadeneffekte erhöht. Die Ränge 1 und 2 erhalten einen geringeren Bonus."
Hier steht explizit, dass es nur durch Effekte erhöht wird und nicht durch equip.

https://www.youtube.com/watch?v=pHOUPjuOXtE
6min 26sek Aderlass
https://www.youtube.com/watch?v=064mq5RVGio
46 sek aderlass für ca 650 mana, weil er Flask hat.
https://www.youtube.com/watch?v=4WhLf3irAXA
Er hat alle Elixiere und eine Flask sowie Zauberöl in seiner Buffleiste. Das boostet mit den 80% gerechnet seinen Aderlass schön hoch.
https://www.youtube.com/watch?v=UVyy16Lrayg
Gleich am Anfang macht er Aderlass 
Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?search=life+tap

mit freundlichen grüßen
Dolo

edited by hraesvelgr zur besseren lesbarkeit

**Comment by hraesvelgr** [comment]
könntest du noch sagen, aus welchem patch deine quelle stammt=?

**Comment by dolomit** [comment]
http://wow.4fansites.de/patchnotes_1_12.php#Patchnotes-1-12-0

**Comment by hraesvelgr** [comment]
>This addon is simple, it chooses the max appropriate level of life tap so that there is little waste in health or mana. If you are full on mana, running the addon will do nothing. It takes into account your +shadow and +spell damage also.
http://wow.curseforge.com/addons/project-2698/pages/

keine rede von gear oder nur flask-effekten

**Comment by Wosser** [comment]
Kein Spell ingame funktioniert so, wieso sollte das bei Aderlass so sein?

**Comment by uggeluggel** [comment]
Aderlass erzeugt doch auch im Gegensatz zu jedem anderem Spell keine Aggro?

**Comment by Wosser** [comment]
Manareg erzeugt keine Aggro, Overheal erzeugt keine Aggro und Dmg an einem Mob erzeugt keine Aggro bei einem anderen Mob, darum erzeugt Dmg den man sich selbst zufügt auch kein Aggro bei Mobs.

**Comment by uggeluggel** [comment]
Klar Manareg verursache keine Aggro, erklär das mal bitte SdW. Manareg erzeugt Aggro. Habe ich auch durch die KTM Einträge klar nachgewiesen.

**Comment by Wosser** [comment]
Wäre das so, hätte ich in meiner Zeit auf diesem Server zumindest ein mal erleben müssen, dass ein Priester durch einen Tick Manareg Aggro zieht, nachdem der Bogen-Pull vom Tank verfehlt, habe ich aber noch nie gesehen. Wenn Manareg Aggro erzeugen sollte, ist das bei uns vermutlich auch buggy.

**Comment by uggeluggel** [comment]
Natürlich. Alles was dir so passt verursacht keine Aggro.

Am besten fängst du an Alli zu spielen da machst du sogar noch - Aggro dank SDR

**Comment by uggeluggel** [comment]
Ganz einfach dadurch zu erklären, dass jeder vernünftige Tank direkt nach Kampfeintritt Blutrausch verwendet.

**Comment by Wosser** [comment]
Alles klar. Ich böser Flamer...

**Comment by uggeluggel** [comment]
Danke für die Einsicht.
Ziemlich Offtopic aber hier eine Info aus BC zum Thema Aggro durch Manareg:

http://forums.elitistjerks.com/forums/topic/19022-how-to-heal-like-a-pro/

Archimonde: The boss has an aura or pulse that will cause a charge of Water Shield to be consumed at the start of the fight. This can result in the shaman temporarily getting aggro.

**Comment by 0815Priester** [comment]
Drakedog  3 Release iwann 2005
Life Tap Change 09/2006

die anderen Videos schau ich mir mal zu Hause an. Kann mir auch nicht vorstellen das der Life Tap change sich nur auf Buffs sich bezieht.

**Comment by Jura500** [comment]
Release 23.5.2005 http://www.warcraftmovies.com/movieview.php?id=1940
Drakdog 3 Release war also bevor LT geändert wurde, also raus.

https://www.youtube.com/watch?v=064mq5RVGio
Google spuckte mir dieses Video auf warcraftmovies aus, wenn ich nach "Definition wow Darick" suche. http://www.warcraftmovies.com/movieview.php?id=24440 
Leider kann man es nicht sehen, scheint aber wohl dieses Video zu sein. Wär super, wenn jemand mit einem Premium-Account mal nachschauen könnte. 
Falls es das gleiche Video ist, kam es auch vor der LT-Änderung

https://www.youtube.com/watch?v=4WhLf3irAXA
Bei 1:18 nutzt er LT und springt von ca 4,1k auf ca 5,5k Mana. Glaube kaum, dass dieser Wert nur duch Buffs zustande kommt.

https://www.youtube.com/watch?v=UVyy16Lrayg
Privat-Server, also wohl raus.


Ansonsten:
http://forums.elitistjerks.com/forums/topic/7539-fairly-big-warlock-lifetap-changes-on-112/?page=1 
In diesem Tread wird das Gear beim Aderlass eingerechnet.

http://wow.gamona.de/forum/threads/crit-hit-wieviel-spelldamage.88030/#post-1242388
In diesem Post steht auch, dass Gear eingerechnet wird.

**Comment by rockefaeller** [comment]
Englische Patchnotes:
Life Tap: This spell now benefits from effects which increase your spell damage. At rank 3 and above, the base amount of health lost and mana gained will increase by 80% of your bonus spell damage effects. Talents and items can further modify those values. Rank 1 and 2 receive reduced effect.

Steht ja ganz klar drin, dass Items den Life Tap beeinflussen.

Gruß Rockyy
