### ISSUE TITLE
stratholme: baron rivendare, tür 

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#131]
die tür zu baron rivendare (http://datenbank.welli-it.de/?npc=10440) sollte sich beim aggro ziehen schließen
momentan bleibt sie noch offen, wodurch man ausserhalb seiner aura stehen kann.
quelle: 
https://www.youtube.com/watch?v=-5T0RoJKl1o&feature=player_detailpage#t=325 (minute 5:25)

meiner meinung nach wurden auch alle spieler, die sich innerhalb der zigurrat vor der tür befinden in die mitte des raumes geportet, spieler die bereits im raum sind bleiben davon unberührt. das bräuchte allerdings noch quelle und bestätigung.

**Comment by Larnak1** [comment]
Ich hatte neulich eine Gruppe, die bestand darauf, den Baron dort zu tanken, wo normalerweise der Magistrat Barthilas stehen würde, wäre er nicht buggy (#129). Der offensichtlichste Vorteil ist, dass es natürlich sehr einfach ist, außerhalb der Aura zu bleiben, was ja schon durch den Vor-der-Tür-steh-Trick recht simpel ist. Noch "besser" daran, den Baron außerhalb seines Häuschens zu machen, ist aber, dass er die Skelette weiterhin drinnen spawnt und sie nicht rauskommen. Durch dieses Bug-Using ist der Kampf natürlich extrem simpel. 

Wäre daher schön, wenn das Tür-Problem behoben werden könnte, um dem einen Riegel vorzuschieben :) Bisher hat sich das glaube ich noch nicht so sehr verbreitet (Ich hatte bisher erst eine Gruppe, die das so machen wollte, vorher wusste ich gar nicht, dass das möglich ist).
