### ISSUE TITLE
Fluch Der Erschöpfung >Verbesserter Fluch Der Erschöpfung 

### ISSUE THREAD

**Issue by P3rkele** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1310]
es gibt ein bug beim Hexer im Gebrechen Skillbaum mit Verbesserter Fluch Der Erschöpfung er gibt keine 5% mehr Tempoveringerung wie beschrieben.

**Comment by hraesvelgr** [comment]
sicher, dass du das so sehr merkst?

**Comment by P3rkele** [comment]
Fluch Der Erschöpfung bleibt bei 10% efak ob ein punkt oder 2 in Verbesserter Fluch Der Erschöpfung drinne ist

Bitte fixen

**Comment by Slimmer2** [comment]
Bitte fixen und dann Closed machen...
Muss man nicht verstehen oder?

**Comment by hraesvelgr** [comment]
>P3rkele closed this 3 hours ago

also entweder du komsmt mal von deinem hohen ross runter, oider du kriegst direkt nen mute :-/

auf geflame hab ich hier keinen bock.

**Comment by P3rkele** [comment]
Ähh was soll der scheiss hier hab das nicht geclosed??? wollen mich welche hier in die Pfanne hauen 
Ne Ohne mich..

Werde hier nichts mehr reporten ....

**Comment by hraesvelgr** [comment]
wenn du als ersteller des bugreports eine nachricht verfasst, hast du 2 buttons zur auswahl: "send and close" sowie "send". du bist auf den "send and close" button gekommen. 
ich habe als mod auch 2 buttons. "close and comment", bzw "reopen and comment" und "comment".

jetzt stehen wir vor dem 2ten problem: du hast einen fehler begangen, wilslt den aber nicht einsehen. einen fehler sucht man immer zuerst bei sich selbst. das machst du aber nicht, sondern flamest erstmal leute, die dafür nichts können.

iich würde dich bitte, einfach mal 3 oder vllt sogar 4 gänge runterzuschalten, sonst kommt für dich zu dem 2ten problem noch ein drittes hinzu.

**Comment by Dotox** [comment]
Was für ein trottel
