### ISSUE TITLE
Kokelwälder Geschenkpackung = Leer

### ISSUE THREAD

**Issue by P3rkele** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1311]
Habe die Kokelwälder Geschenkpackung geöffnet und es war nichts drin warum??

**Comment by dagochen** [comment]
Weil der Loot keine group_id in der Datenbank hat ;)

**Comment by grindbox** [comment]
bei mir waren nur Leinenstoffballen drin

**Comment by hraesvelgr** [comment]
sei doch mal dankbar für die milden gaben von altvater winter!!!

aber dass nix drin ist, war laut wowhead schon so...nur ist ews eben krass, wie oft nichts drin ist. gefühlt hat 90% unserer gilde ein leeres paket gehabt.

**Comment by P3rkele** [comment]
Ja und wird das Gefixxt und gibt es ersatzt???

**Comment by dagochen** [comment]
Fix: Ja
Ersatz: Nein (es sei denn die GMs sind so nett...)
