### ISSUE TITLE
Uldaman Quest: Wiederbeschaffte Schätze

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1314]
Welches Verhalten wird beobachtet?
Nach dem looten der Truhe verschwindet diese sofort wieder und ist für die restlichen 4 Gruppenmitglieder nicht mehr lootbar. Erst nach unangemessener langer Zeit.

Wie sollte es sich verhalten?
die Truhe sollte nach dem looten direkt wieder spawnen und lootbar sein für die restlichen Gruppenmitglieder

Schritte zur Reproduzierung
Kiste looten

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?quest=2342
http://datenbank.welli-it.de/?object=124388

**Comment by hraesvelgr** [comment]
wie heißt denn die truhe?

**Comment by Mafyo** [comment]
Familientruhe der Garrets

**Comment by grindbox** [comment]
Dieses Verhalten ist mir auch bei anderen Questobjekten aufgefallen, unter anderem auch in Uldaman bei "Krom Stoutarms Truhe". dort war die Respawnzeit auch über 15 min und da das alles vor der Instanz ist, spawnen die Mobs schneller als in der Instanz

**Comment by Mafyo** [comment]
mache eben ein extra report

**Comment by Mafyo** [comment]
links hinzugeügt
