### ISSUE TITLE
T0,5 questline probleme Items umgetauscht und nicht mehr vorhanden -.- 

### ISSUE THREAD

**Issue by Pitbulle** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1316]
guten abend
Folgendes hat sich zugetragen:

ich habe die t0,5 questline fertig gemacht die Abschlussquest wo man schultern,beine,Schuhe umgetauscht bekommt da mein inventar aber fast voll war bekam ich warscheinlich nur die schuhe aber die folgequest und meine andern 2 setteile sind umgetauscht worden und verschwunden.
denke mal es liegt daran das diese Questreihe selbst geskriptet wurde um sie zu implementieren und in dem skript die core nicht erkennt das man die Quest nicht abgeben kann bei fehlenden inventarplätzen wie es bei allen andern Quests normal war.

vielleicht wird es irgendwann mal behoben doch grad bei der t0,5 questreihe ist mir das extrem aufgefallen

lg pit

**Comment by hraesvelgr** [comment]
nicht ganz. das ist ein bekanntes problem auch mit schlüsseln und anderen questbelohnungen.

mach ein screen von den schuhen, eine verlinkung zu der quest (da helf ich dir auch gern) wo man sieht, welche questbelohnungen es gibt, und schreibd as ganze ingame oder im forum an einen gm.,

**Comment by Pitbulle** [comment]
ist schon passiert also das ticket ist draußen trotzdem danke
