### ISSUE TITLE
Uldaman Quest: Lösung der Verdammnis

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1318]
Welches Verhalten wird beobachtet?
Die  **[Uralte Truhe](http://datenbank.classic-wow.org/?object=126260)** kann nur von einem Gruppenmitglied gelootet werden und respawnt erst nach sehr langer Zeit.

Wie sollte es sich verhalten?
die Truhe sollte nach dem looten direkt wieder spawnen damit andere leute die Quest beenden können.

Schritte zur Reproduzierung
KIste looten

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?quest=709

**Comment by Rushor** [comment]
Reproduzierung heißt nachstellbarkeit - nicht fixvorschlag :D

**Comment by Slimmer2** [comment]
Dies betrifft aber alle Questobjekte von den man Questitems looten kann

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage

**Comment by Mafyo** [comment]
links hinzugefügt
