### ISSUE TITLE
Schlangenbiss neuer Rang

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1319]
Auf einem Ziel können immer mehrere Schlangenbisse von verschiedenen Huntern sein. Durch den neuen Rang ist es aktuell aber nicht möglich, da dann die Meldung für die Hunter mit dem alten Rang kommt "Ein mächtigerer Zauber ist bereits aktiv!". Dies sollte nicht so sein, da ein Vergleich mit den Schlangenbissen anderer Jäger nicht stattfinden sollte.

**Comment by Jura500** [comment]
Den gleichen Effekt haben wir auch beim Mana entziehen vom Hexer beobachtet.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/682

Das Problem solltest du beim Leveln auch gehabt haben.
In den Anderen gemeldeten Bug wurde gefragt ob dies auch andere Klassen betrifft.

Also meldet doch mal alle Klassen die das Betrifft. Da es alle Dots betreffen könnte.

**Comment by dagochen** [comment]
Warum close @Dotox ?

Ist halt jetzt aufgefallen wegen den neuen Klassenbüchern. Wusste garnicht von dem andern Fehler bis jetzt.

**Comment by uggeluggel** [comment]
Wie kommst du darauf?
Man kann nicht mehrere Debuffs unterschiedlicher Ränge auf einem Ziel haben. Der stärkste überschreibt alle niedrigeren oder es sind bei gewissen Ausnahmen mehrere des gleichen Ranges drauf.

**Comment by uggeluggel** [comment]
Ist mir neu, dass man Debuffs unterschiedlicher Ränge auf ein Ziel casten kann.
