### ISSUE TITLE
Alteractal - Critical WoW Error bei Sieg

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#132]
Im Moment des Sieges bekommen viele Spieler einen kritischen Wow - Error, der dazu führt, dass man teil die Siegesmarken nicht erhält  sowie  seinen Charakter beim Geistheiler zu beleben, was jedes Mal je nach Ausrüstung bis zu 10 Gold Repkosten nach sich zieht...

**Comment by wahaxlekuke** [comment]
Gibts diesen Bug immer noch?
