### ISSUE TITLE
Frostöl wirkt beim treffen und getroffen werden

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1321]
Servus

Ich habe vorhin einige Duelle mit einem Schurken gehabt, während ich Fröstöl auf meiner Waffe angelegt hatte und da ist mir aufgefallen das der schurke auch verlangsamt wird obwohl ich ihn nicht getroffen habe bzw das Öl procct wenn er mich trifft.

" Gewährt bei Anwendung auf eine Nahkampfwaffe eine Chance von 10%, bei einem Treffer 'Frostblitz' auf den Gegner zu wirken. Hält 30 Minuten lang an" 

Hört sich für mich so an das es nur wirken sollte wenn ich ihn treffe.

http://datenbank.welli-it.de/?item=3829

Vllt findet jemand ja etwas genaueres

**Comment by Dotox** [comment]
Ich konnte das auf dem Testserver nicht reproduzieren. Bei mir proct es nur, wenn ich selber zuschlage. Wenn ich getroffen werde, nicht.
