### ISSUE TITLE
Zul Farrak, Antu'Sul   (boss) 

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1323]
Welches Verhalten wird beobachtet?
der kampf gegen  Antu'Sul  der damals für seine hohe Aggro range bekannt war kann nur gestartet werden in dem man den Boss anschiesst oder seinen bodypull macht.
Wie sollte es sich verhalten?
Der bossfight bzw. das Event sollte starten wenn ein spieler der Höhle zunahe kommt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=J3H-OwhOztw
ab sek  0.41 ca startet das event

**Comment by Slimmer2** [comment]
Gehört zusammen https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1324

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage

**Comment by Mafyo** [comment]
kann gelöscht werden habe es  zusammengefasst :)
