### ISSUE TITLE
AQ20: Käfersammlung

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1329]
- Skarbäuskästen despawnen nicht nach dem Öffnen.
- Sandpirscher des Zaraschwarms sind noch sichtbar wennn sie "stealthen".
- General Rajaxx Event funzt nicht richtig:
Gruppen kommen nicht von alleine wenn man eine fertig hat. 
Man kommt permanent aus dem Kampf und kann essen/trinken.
Greift man Rajaxx oder eine der Grupppen direkt an, kommt Andorov nicht zur Hilfe und wartet brainafk ab.
- Buru müsste schneller an Tempo dazugewinnen in Phase 1.
- Burus Adds despawnen nach dem Kampf nicht.
- Buru macht in Phase 2 seinen Debuff aus Phase 1 (sollte nicht so sein).
- Burus Eier resetten nicht, wenn Buru resettet.
- Moam benutzt den Manadrain zu häufig
- Gladiatoren der Quiraji geben keinen Ruf

**Comment by Hakii** [comment]
General Rajaxx Event funzt nicht richtig: Gruppen kommen nicht von alleine wenn man eine fertig hat. Man kommt permanent aus dem Kampf und kann essen/trinken.

Geduld ist eine tugend :-). Ne, die Zeit zwischen den Wellen dauert schon wirklich sehr sehr lange.

**Comment by dagochen** [comment]
@hraesvelgr Mach mal einzelne Bugreports daraus ;)
