### ISSUE TITLE
hexer mount fehlendes script/fehlende animation

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1330]
https://www.youtube.com/watch?v=WhHHkp_Smac wie man hier schön sieht, kommt beim beschwören des epicmounts eine feuernova. diese fehlt bei uns auf dem server

http://datenbank.welli-it.de/?spell=23161

eventuell fehlt bei anderen mounts auch eine animation?

**Comment by Rukachi** [comment]
https://www.youtube.com/watch?v=a-q10Osev3A

Ab 2:18 
Es ist war nur das 60% mount sollte aber keine Unterschied machen

**Comment by hraesvelgr** [comment]
das leuchten am boden nach dem beschwören fehlt beim palamount^^
