### ISSUE TITLE
Emperor Vek'nilash immune to holy dmg

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1331]
Welches Verhalten wird beobachtet?
Emperor Vek'nilash ist gegen holy dmg immun

Wie sollte es sich verhalten?
Emperor Vek'nilash darf nicht gegen holy schaden immun sein

Schritte zur Reproduzierung
ihn mit holy dmg hauen/ancasten

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://wowwiki.wikia.com/wiki/Twin_Emperors?oldid=272445

Links aus unserer Datenbank 
http://datenbank.welli-it.de/?npc=15275

**Comment by dagochen** [comment]
Da steht nur Priester....und Wands....nix von Palas :)

**Comment by hraesvelgr** [comment]
>don't know if you 'allow' prot paladins in your 60 only guild but that would pretty much trivialize the encounter. Holy damage hits both emperors regardless of which one it is.

http://us.battle.net/wow/en/forum/topic/6147286419
naja, 2012...but you get the idea

**Comment by uggeluggel** [comment]
dago mal wieder nicht richtig gelesen.

The holy wand from BRD, Wand of Eternal Light, can also do damage to Emperor Vek'nilash. 
 
Aus Sabbaers Quelle.

**Comment by dagochen** [comment]
Hab doch geschrieben "nur Priester" (wegen Holy Fire/Smite) und "...und wands" wegen dem Zauberstab. Das es sich dabei um Sabbaer-Getrolle handelte, war vielleicht nicht zu verstehen, sollte es aber sein :/ Hab das sehr wohl gelesen, wenn du aber Sarkasmus auf dem Tablett serviert nicht erkennst, schalt besser das Inet aus. Danke!

**Comment by uggeluggel** [comment]
Lass doch einfach dein sinnloses gebashe. Dann bekommst du auch keine negativen Reaktionen

**Comment by dagochen** [comment]
Sabbaer muss man einfach trollen. Aber das ist immerhin sein 1. guter Bugreport seit ....überhaupt!

Wenn du es nicht lustig findest, dann ignorier es halt. Aber Blödsinn schreiben à la "du hast ja garnicht richtig gelesen....oh doch hast du, aber ich versteh es nicht" ist einfach nur laaaaaangweilig....also schreib einfach garnix mehr danke!

**Comment by uggeluggel** [comment]
danke für deine Bestätigung meiner Meinung über dich =)

**Comment by dagochen** [comment]
Ich versteh dich einfach nicht. Was ist dein Problem. Ich hab die Quelle doch richtig wiedergegeben. Lies du lieber mal meinen Post .... -_-

**Comment by dagochen** [comment]
Das mit den "und Wands" steht da seit 15 Stunden. Raff mal was...

**Comment by ircfelix** [comment]
Hast du schonmal sein Verhalten beobachtet?
Haste ma die Menge die Menge an Holyresi gesehn?

Ich bin sauer weil es um des Bosses Holyresi geht, weil er, angeblich, man sieht es hier was angesprochen wurde, keine Holyresi hat, obwohl, man siehts, es ist Holyresi auf dem Boss!

HALT STOP! 

DAS BLEIBT ALLES SO, WIES HIER IST, UND DA WIRD SICH HIER NICHTS DRAN RÜTTELN, EGAL OB DU HIER BIST UND NICH! WEIßT WAS, DIE RESI WIRD MORGEN NICH SO GEMACHT, DAS MACHT DOTOX SO WIE ER WILL, OBS DIR NUN PASST, ODER NICH, DER BOSS BLEIBT SO, WIE ER IS!

**Comment by hraesvelgr** [comment]
posts aufräumen und wieder öffnen,. @Dotox ?
