### ISSUE TITLE
Prinzessin Yauj: Loot 

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1333]
Allianz und Horde hatten unterschiedliche Loot-Pools bei Yauj.

Horde: http://datenbank.welli-it.de/?item=21684
Allianz: http://datenbank.welli-it.de/?item=21683
Prinzessin Yauj: http://datenbank.welli-it.de/?npc=15543

Beweis: https://web.archive.org/web/20060716183844/http://wow.allakhazam.com/db/mob.html?wmob=15543

Addiert man die einzelnen %-Chancen der 2 Items, kommt man auf die gleiche Chance wie die anderen Items. Dies liegt daran, dass es weniger Horden-Gilden gab als Allianz-Gillden....bla bla gleiche Begründung wie immer. Fix einfach von den 20 anderen Bugfixes copypasten und die IDs ersetzen, danke!

**Comment by Garlesh** [comment]
Das gilt btw für sämtliche mail/ plate loots. Bei der Allianz droppt der Shammy loot einfach nicht, Wär top wenn man alternativ von einem GM ein anderes per Zufall generiertes Item bekommen würde.
