### ISSUE TITLE
AQ20: General Rajaxx

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1339]
- Die Gruppen kommen nicht von alleine wenn man eine fertig hat.
- Man kommt permanent aus dem Kampf und kann essen/trinken. 
- Greift man Rajaxx oder eine der Grupppen direkt an, kommt Andorov nicht zur Hilfe und wartet brainafk ab.

**Comment by Seniorash** [comment]
Die Gruppen kommen von alleine. Jedoch dauert es etwas

**Comment by dagochen** [comment]
Ja, aber sie kommen nicht, wenn man eine fertig hat. Es gibt keinen (erkennbaren) zeitlichen Zusammenhang zwischen Abschließen der einen Gruppe und Erscheinen der nächsten.
