### ISSUE TITLE
AQ20: Buru

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1340]
- Buru müsste schneller an Tempo dazugewinnen in Phase 1 (spätestens nach einer 3/4 Runde sollte er die Spieler merklich einholen)
- Burus Adds despawnen nach dem Kampf nicht (sollten verschwinden)
- Buru macht in Phase 2 seinen Debuff aus Phase 1 und tötet damit Tanks (sollte nicht so sein).
- Burus Eier resetten nicht, wenn Buru resettet (sollten resetten und wieder volle Leben haben).

**Comment by ircfelix** [comment]
Wenn man Buru in Phase 2 bringt schlüpfen aus den Eiern Käfer.  Wenn man dann in Phase 2 wiped, despawnen diese Käfer nicht.
