### ISSUE TITLE
AQ20: Moam

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1341]
Moam benutzt den Manadrain zu häufig. Aktuell ist er mit 3 Hexern, Priestern und Huntern nicht leer zu drainen und explodiert bereits bei 60-80%. Spieler gehen extrem schnell oom.

Früher ließ er sich laut Guides mit 3 Hexern und Priester+Huntern easy leer drainen, ohne das er je explodiert ist.

http://wowwiki.wikia.com/wiki/Moam?oldid=262491

**Comment by hraesvelgr** [comment]
verlink mal bitte die quellen (ich glaub dir aber, wir hatten 3 hexer, 2 hunter und 2 priester.... und er ist fast sofort explodiert)

**Comment by dagochen** [comment]
Außerdem sollte er sich laut http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/AQ/aq-20-2.htm beim Phasenwechsel von Normal -> Steingestalt 50% des maximalen Manas verlieren.

Summon Mana Fiend (Mana-Teufel herbeirufen):
Nach 90 Sekunden ruft Moam 3 Mana-Teufel herbei. Diese Mana-Teufel besitzen ein kleines AoE mit ~1000 Schaden und können gebanned werden. Zieht Moam ca. 50% des gesamten Mana Balkens ab.

**Comment by Slimmer2** [comment]
Taktik anpassen dann Explodiert er auch nicht.

**Comment by dagochen** [comment]
@Slimmer2
Naja ein Taktik die damals ging sollte auch hier gehen....er drained halt 2-3 mal so häufig wie zu Classic....was den Kampf komplett verändert. Man muss also selbst mit idealem Setup (3 Hexer, 2 Priester und 1 Jäger) auf das Manadrainen verzichten und ihn hinter dem Stein machen. Das kann so nicht gewollt sein...

**Comment by dagochen** [comment]
@Dotox 
Bei uns kommt der Manadrain von Moam ca. alle 3-5 Sekunden. Laut Video müssten es 6 sein.

https://www.youtube.com/watch?v=R_eD25lA5x8
