### ISSUE TITLE
Quests: Winterhauchfest

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1343]
Wenn man die Quest letztes Jahr gemacht hat, werden sie einen nicht mehr angeboten.

Die Quest sollten jährlich wiederholbar sein.

**Comment by Dotox** [comment]
Die Quests sind dieses Jahr wiederhohlbar. Welche Quest kannst du denn nicht machen?

**Comment by Slimmer2** [comment]
http://datenbank.welli-it.de/?quest=7025
http://datenbank.welli-it.de/?quest=7062 Evtl auch die Folgequest davon
http://datenbank.welli-it.de/?quest=8762
http://datenbank.welli-it.de/?quest=7042 Evtl auch die Folgequest davon

Ob es mehr sind kann ich gerade nicht sagen.

**Comment by Dotox** [comment]
Hm, ne die wurden alle resettet :/ Ich hab die Quests letztes Jahr gemacht (zum Test) und kann sie nun wieder machen.

**Comment by Slimmer2** [comment]
Komisch das es dann bei mir nicht geht.
Steht evtl in der Datenbank eine Zeit wann abgeschlossen?
Char Hexerina

**Comment by dagochen** [comment]
Bei mir geht es auch nicht.

**Comment by dagochen** [comment]
@Dotox @nightblizard 
Kann man das vllt noch zeitnah fixen, damit das Event nicht vorbei ist wenn ihr es gefixt habt?
