### ISSUE TITLE
weihe dmg auf cthun

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1347]
Welches Verhalten wird beobachtet?
kein weihe schaden auf cthun möglich

Wie sollte es sich verhalten?
weihe sollte schaden auf cthun machen

Schritte zur Reproduzierung
weihe auf cthun casten

links aus datenbank
http://datenbank.welli-it.de/?search=consecr

**Comment by Bladsn** [comment]
Vielleicht Weihe.

**Comment by hraesvelgr** [comment]
@sabbaer quellen? oder ist die hitbox einfach zu klein?

**Comment by Sabbaer** [comment]
is das gleiche problem wie bei ragnaros, dort funktioniert weihe an nur einer ganz bestimmten position.

**Comment by Bladsn** [comment]
Gibt es dazu auch Quellen, dass Weihe die o.g. Bosse auch treffen sollten?

**Comment by Sabbaer** [comment]
warum sollte sie die bosse denn nicht treffen? darf dann blizzard oder feuerregen oder salve dann auch nicht gehen auf bosse?

**Comment by ircfelix** [comment]
Vll. ist die Holyresi zu hoch?!?

**Comment by hraesvelgr** [comment]
es geht nicht um resists, es geht darum, dass es wohl so behandelt wird, als würde der npc ausserhalb der weihe stehen. obwohl sie unter ihm ist...

**Comment by Malize** [comment]
Kann die sehr kleine Hitbox von C'thun bestätigen. Als Krieger musst du in Ihm stehen, um den Boss mit Wirbelwind zu treffen.

**Comment by Dotox** [comment]
Bitte melden, wenn es nach dem nächsten Update nicht besser ist.

**Comment by Sabbaer** [comment]
funktioniert leider noch nicht
