### ISSUE TITLE
Mistelzweig-debuff

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1350]
Auch durch den Fix vom 21.12.2015, bleibt man mit den Debuff im Kampf wenn man NPCs tötet.

Einzige das Hilft ist Ruhestein benützen.

**Comment by ircfelix** [comment]
Sollte der Buff nicht auch mit anderen Buffs (Willenskraft vom Priester) stacken da es ja ein Worldbuff ist?

**Comment by Slimmer2** [comment]
Es geht hier um den Debuff, denn man bekommt wenn man einen Winterfeierden küsst.

**Comment by ircfelix** [comment]
Schon klar, aber man kann ja auch zeitgleich die gruppe unter die der Spirit buff fällt ändern.
