### ISSUE TITLE
keine abfrage der ignoliste beim erstellen des chars. 

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1351]
wenn ein spieler auf der ingoliste eines anderen landet, dann seinen char löscht, und einen neuen char mit einem identischen namen macht, so wird er nicht mehr ignoriert, obwohl sein name auf der ignoliste steht
da sollte eventuell eine abfrage geändert werden, sonst werden spammer nicht effektiv ignoriert. 
alternativ mal einen world-admin einstellen^^

**Comment by Slimmer2** [comment]
Der Spieler Bingoringo hat den Char gelöscht und neu erstellt.
Deswegen war das

**Comment by Dotox** [comment]
Quelle, dass das so sein soll bitte hinterlegen :)

**Comment by hraesvelgr** [comment]
boah, du stelslt anforderungen :D ich würd einfach mal schon aus umanitären und sozialen gründen das so machen, egal obs so war oder nicht...spamprotection für die community halt :p 

oh, und channel-admins gabs wirklich.

**Comment by Slimmer2** [comment]
Es ist halt so. Wenn die Ignorliste der Name vorhanden bleibt wenn der Charname gelöscht wird und irgendwann ein anderer Spieler diesen Namen auswählt. Wird dieser Ignoriert, obwohl der spieler nichts dafür kann.

**Comment by Dotox** [comment]
Ich kann das auf jedenfall sehr gut nachvollziehen allerdings kann ich mich auch noch an eine Meldung erinnern die kurz nach dem Login kam, wenn ein Charakter auf der Freundesliste nicht mehr existierte. Ob das für die Ignorierliste auch gilt weiß ich leider nicht.

**Comment by hraesvelgr** [comment]
wurde der char dann auch wirklich von der fl gelöscht? weil momentan ist es ja so,d ass der char auf der ignoliste vorhanden bleibt, obwohl er gelöscht wurde.

**Comment by Slimmer2** [comment]
Es geht jetzt schon um den Spieler Bingoringo ?

**Comment by hraesvelgr** [comment]
ja... und mir sit auch klar, wie das alles funktioniert, ich bin nur der meinung,d ass es ganz und garnicht so funktionieren sollte

**Comment by dagochen** [comment]
Das mit der Freundesliste gabs erst später.

**Comment by Dotox** [comment]
Hab mir das gestern mal angesehen und es ist leider ohne Weiteres nicht so einfach umsetzbar. Da müsste das Social-System umgeschrieben werden und entsprechend neue Tabellen in der Datenbank angelegt werden. Viel einfacher ist es, wenn ihr die Typen die wiederhohlt spamen/flamen und sich immer wieder einen neuen Char erstellen in einem Ticket meldet.

Den Charakter löschen ist keine Abhilfe gegen eine entsprechende Strafe unsererseits, da alles geloggt wird.
