### ISSUE TITLE
MC: Ragnaros

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1352]
In P1 ist Ragnaros unter der Lava, Sollte aber über bzw. auf der Lava stehen
In P2 wo er abtaucht kommt er kurz hoch.
Nach auftauchen ist er wieder normal.
![wowscrnshot_122215_224204_ergebnis](https://cloud.githubusercontent.com/assets/8680824/11967012/d8c4fcc6-a8ff-11e5-8736-3bd6067a993d.png)
![wowscrnshot_122215_224350_ergebnis](https://cloud.githubusercontent.com/assets/8680824/11967014/d8cb49a0-a8ff-11e5-9e48-848cf4478f94.png)
![wowscrnshot_122215_224457_ergebnis](https://cloud.githubusercontent.com/assets/8680824/11967013/d8c8a61e-a8ff-11e5-8996-f9e0e20b775e.png)
![wowscrnshot_122215_224607_ergebnis](https://cloud.githubusercontent.com/assets/8680824/11967011/d8b91e38-a8ff-11e5-8ff3-64e08a2a5935.png)

**Comment by hraesvelgr** [comment]
das kann auch ein einmaliger fehler im script gewesen sein?

**Comment by Slimmer2** [comment]
Fehler war letzte Woche auch schon

**Comment by Sabbaer** [comment]
kann ich bestätigen, tritt häufiger auf

**Comment by ircfelix** [comment]
Hatte Anorhin auch schon das Problem. Ist das lediglich ein Anzeigeding oder leidet auch die Hitbox darunter?

**Comment by Slimmer2** [comment]
Hitbox leidet nicht darunter.
Auf Bild zwei sieht man das Gedankenschwinden vom Shadow, das geht voll in die Lava.

**Comment by Drachling** [comment]
Uns ist es heute passiert, dass dies auch in UBRS bei einer ganzen Mobgruppe im letzten Raum passiert ist.
Sobald sich die Mobs bewegt haben, waren sie wieder sichtbar.
Das Sleep-Target blieb unsichtbar bis es raus gekommen ist und sich ebenfalls bewegt hat.

Vieleicht hilft dies bei der Fehlersuche.

**Comment by dagochen** [comment]
Funktioniert! Welcome back Raggi!
