### ISSUE TITLE
Skills beim Lehrer trotz Bezahlung auf dem Mount nicht erhaltbar

### ISSUE THREAD

**Issue by Fabsnqt** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1353]
Ich habe heute auf meinem Warlock versucht Skills beim Trainer zu lernen als ich auf dem Mount saß, was darin endete das mir zwar das Gold für den Skill abgezogen wurde, ich jedoch keinen einzigen Skill erlernt oder ein Upgrad auf einen bestehenden erhalten habe.

**Comment by Slimmer2** [comment]
Bei welchen Hexenmeister lehrer kann man aufgemountet sein?
ALLIANCE scheidet aus

**Comment by Fabsnqt** [comment]
Beim Orc in Undercity

**Comment by hraesvelgr** [comment]
seit wann kann man in uc reiten...?

**Comment by Karmanaz** [comment]
@hraesvelgr  Bisher kann man in UC reiten. Ich erinnere mich auch nur das man als Taure auf einem Kodo immer absteigen musste, da das Modell nicht durch die Tür zum Fahrstuhl passte. Und es gab eine ganze Weile lang den nervigen "Fehler", dass man dismountet wenn man in UC reinging (vom Zeppelin aus), da es ein geschlossener Raum war.
