### ISSUE TITLE
Arena der Gurubashi: Uhrzeit

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1355]
Seit der Sommerzeit-Umstellung stimmt die Uhrzeit des Events in der Gurubashi-Arena nicht mehr. Das Event kommt aktuell immer eine Stunde zu früh.

**Comment by Slimmer2** [comment]
War das auf dem Offiserver nicht auch bei allen das Resetet wurde?
Wie Dailys, Instanz IDs.

Zudem musste auch dann bei Zeitumstellung das Event bei Umstellung zur Winterzeit um 3:00Uhr kommen und dann eine Stunde später wieder um 3:00. Das aber so nicht sein sollte.

Das Event kommt alle 3 Stunden und sollte so wie es auch auf dem Offiserver ist/war zur Winterzeit auch alle 3 Stunden kommen.

**Comment by dagochen** [comment]
Ja es sollte zu immer um 0, 3, 6, 9 Uhr kommen. Egal ob Sommer oder Winterzeit.

**Comment by Slimmer2** [comment]
Heißt wenn Umstellung zur Winterzeit ist dann 0, 3 bzw 2 , 5 ,11, 14,17,20, 23 und dann wieder 0 Uhr ?

**Comment by dagochen** [comment]
Ka was du meinst....ist doch auch nicht so schwer zu verstehen was ich meine oder?
Im Sommer: 
0, 3, 6, 9, 12, 15, 18, 21 Uhr.
Im Winter:
0, 3, 6, 9, 12, 15, 18, 21 Uhr.

**Comment by Slimmer2** [comment]
Mein den Tag, an dem die Zeitumstellung ist

**Comment by dagochen** [comment]
Es gibt keine Zeitumstellung. Der Server muss gucken ob es grade 0 Uhr ist, und dann startet das Event. Egal ob Sommer- oder WInterzeit.

**Comment by Slimmer2** [comment]
Sprich, an den Tag wo man die Uhr eine Stunde zurück stellt, kommt das Event 1 mal öfters am Tag

**Comment by dagochen** [comment]
Theoretisch ja, praktisch nein.
Uhr wird um "3 Uhr" umgestellt. Wenn man es richtig implementiert, startet das Event also um beim 1. mal nicht, weil die Uhr von 02:59:999 auf 02:00:00 springt und nicht auf 03:00:00. Dafür würde beim vorstellen dann es tatsächlich einmal weniger kommen. Aber who cares? Hauptsache es kommt zur richtigen Zeit.

**Comment by dagochen** [comment]
@Dotox 
Das Problem existiert außerdem bei dem Zeitpunkt des Zurücksetzen der RaidIDs. Dies sollte um 6 Uhr, nicht um 5 Uhr stattfinden.

**Comment by Slimmer2** [comment]
Bei Raids und Dailys ist es kein Fehler, da dies auch auf den Offiserver so war.
Soweit ich das weis
