### ISSUE TITLE
Winterhauchfest - Mistelzweig

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1356]
Servus

Laut der Datenbank sollten die Mistelzweige über dem AH- und Bank Eingang auch bei einem /Kuss entsprechend reagieren wie im Gasthaus aber die sind bei mir Ingame nicht als Objekte markiert 

http://datenbank.welli-it.de/?object=178554   -> Ironforge

Bei den anderen Hauptstädten hab ich noch nicht geschaut. Ist das nur bei mir so oder ist das gewollt? 
Nichts dramatisches :dancer:

**Comment by Slimmer2** [comment]
Ist die Frage ob die nur Deko ist.
Das mit /Kuss ist nur bei den Winterfeiender http://datenbank.welli-it.de/?npc=15760
