### ISSUE TITLE
Abzeichen der Schwarmwache: Fehlerhafte (viel zu geringe) Procchance

### ISSUE THREAD

**Issue by Ikarium-Nef** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1357]
"Welches Verhalten wird beobachtet?"
Während der Aktivierung des Trinkets "Abzeichen der Schwarmwache" von einem Jäger werden von den maximalen 6 Buffstacks höchstens 2 während der Wirkdauer (30sek) erreicht. Und das trotz der Aktivierung diverser CDs (Schnellfeuer + Aspektproc + Trollracial). Oft werden keinerlei Stacks beobachtet.

"Wie sollte es sich verhalten?"
Fangen wir mal vorne an. Wirkdauer des Trinkets sind 30s, der CD 180s. Das ist soweit korrekt. Bei Aktivierung erhält man den Buff "Badge of the Swarmguard" (https://web.archive.org/web/20060525100804/http://wow.allakhazam.com/db/spell.html?wspell=26480) der das Erhalten eines weiteren Buffs ermöglicht "Insight of the Qiraji" (https://web.archive.org/web/20060313190632/http://wow.allakhazam.com/spell.html?wspell=26481). "Insight of the Qiraji" hat selbst eine Wirkdauer von 30s und kann 6 mal stacken. Beim hochstacken wird die Wirkdauer aufgefrischt auf 30s. Beim Auslaufen von "Badge of the Swarmguard" wird "Insight of the Qiraji" aber auch deaktiviert. Das scheint soweit zu funktionieren wie es soll außer dass die Procchance viel zu klein ist. Laut angehängten Quellen sollte die Procchance bei 80-100% liegen und meist nach ca.10-15s hochgestackt sein. Das scheint mir sinnvoll wen man sich die Funktionsweise des Trinkets ansieht. (Sollte es erst nach z.B. 25s hochgestackt sein hat man den vollen Effekt nur 5s zur Verfügung, und das bei 180s CD.)
Nebenbei: "Insight of the Qiraji": 1Stack verringert die Rüstung eines beliebigen Zieles um 200. Soll mit Rüstung zerreißen, Feenfeuer usw. stacken.

"Schritte zur Reproduzierung"
Allein die Sinnhaftigkeit des Trinkets wird in Frage gestellt wenn die Procchance so gering ist, dass selbst bei aktivierten Cooldowns nicht die volle Anzahl an Buffstacks erreicht werden kann.

Kleine Rechnung: Wir nehmen von 80%-90% Procchance für das Trinket an, BWL Armbrust und Epicköcher: In 12-13Sek in einer Hunterrota gibt man dann ca. 7 Schüße ab (Aimed+Auto-Multi-Auto-Auto-Aimed+Auto). 7 x 0.8=5.6 ; 7 x 0.9 =6.3
Passt also mit dem was die Quellen berichten zusammen.

"Zusätzliche Informationen (Screenshots, Videos, etc.)"
https://www.youtube.com/watch?v=6DQPytnxvlo (Video von 2006: zeigt das Auffrischen von "Insight of the Qiraji und das Verschwinden beider Buffs nach 30s.)
https://youtu.be/gIRCYUnemmU?t=77  (wie oben)

Und so funktioniert es momentan (ein Stack nach ~19 Schüßen): https://www.youtube.com/watch?v=GlGI6ZnQx5c&feature=youtu.be
https://www.youtube.com/watch?v=Dw3uKOb9Cqo&feature=youtu.be (ein Stack nach ~50 Schlägen)

https://web.archive.org/web/20060721062246/http://wow.allakhazam.com/db/item.html?witem=21670 
https://web.archive.org/web/20070711022250/http://www.thottbot.com/i21670
(Quellen die eine Procchance von ~80%+ nahelegen, Danke an @dagochen)

"Links aus unserer Datenbank (hier gehts zur Datenbank)"
http://datenbank.welli-it.de/?item=21670 (Link zum fraglichen Item)

Edit: Eingangspost überarbeitet und vervollständigt. Vielen Dank an @dagochen der mich auf Fehler hingewiesen und Quellen aufgetrieben hat. Danke auch an Haudrauf und Zodd für die Videos.

**Comment by Ikarium-Nef** [comment]
zusätzliche "Quelle":
http://wowdata.buffed.de/item/Ruestung/Verschiedenes/Abzeichen-der-Schwarmwache-21670#comments (Kommentar Nr.4: "procct sehr nice bei Hunter")

**Comment by Haudraufinix** [comment]
Zusätzliche Quelle:

https://youtu.be/gIRCYUnemmU?t=77 (~16 Schläge bis maxstacks)

**Comment by dagochen** [comment]
>kleine Rechnung: Bei Annahme von 25% Procchance für das Trinket, BWL Armbrust und Epicköcher gilt: In 30Sek in einer Hunterrota gibt man im Mittel 23.3 Schüße ab, 10 Aimed + 10 Auto + 3.3 Multi --> 23.3 x 0.25 = 5.825.

Die verstehe ich nicht. In 30 Sekunden kommt man doch nicht auf 10 Aimed? Oder was meinste da? 23,3 Shots in 30 Sekunden ist unmöglich....und daher sind 25% Chance auch zu niedrig angesetzt, oder?

**Comment by Ikarium-Nef** [comment]
@dagochen 
Du hast recht, 10 Aimed sind Quark. Der CD ist 6 Sek. nicht 3 Sek.
Stattdessen sind es 5, dann kommen wir am Ende bei einem Erwartungswert von ~4.6 raus wenn wir wieder die obigen Annahmen verwenden. Das sind immernoch min. 4-5 Stacks ohne CDs pro Aktivierung.

Das spricht meiner Meinung nach auch eher für eine höhere Procchance, sprich eher 35% als 25%.  Denn es würde wohl keiner von einer guten Procchance reden wenn man nicht mal das Ding komplett hochstacken könnte.

Zu den anderen von dir gelinkten Quellen: 100% sind sicherlich nicht richtig.
Im den Kommentaren vom ersten Verweis wird da z.B. direkt widersprochen. Weiterhin sind die Kommentare im Thotbotlink (dem 2.ten) recht neu (kaum älter als ein Jahr) und da das Item mit späteren Addons verändert wurde ist das als Quelle nicht zulässig. In späteren Addons hatte das Ding tatsächlich mal 100% Procchance aber auch einen inneren CD eingebaut.

Den Verweis von Haudrauf miteinbezogen wären wir bei 18 und 16 Schlägen bis Maxstack, sprich 33%-37,5%. Im Mittelwert ~35%, das scheint mir recht vernünftig.

**Comment by Rushor** [comment]
fröhliche weihnachten :christmas_tree:

**Comment by dagochen** [comment]
@Ikarium-Nef 
>Du hast recht, 10 Aimed sind Quark. Der CD ist 6 Sek. nicht 3 Sek.
Stattdessen sind es 5, dann [...]

Immer noch falsch. 6 Sekunden CD + 3 Sekunden Castzeit = 9 Sekunden. Mehr als 3 Aimed Shots wirst du in 30 Sekunden nicht schaffen.


Die Quellen und Kommentare sind von damals. Schau mal auf das Datum, welches oben in der archive-Übersicht steht. Und von diesem Datum musst du dann "kaum älter als ein Jahr" rechnen. 
Sprich wenn da oben 21.07.2006 steht und bei einem Kommentar steht "Yesterday", dann ist damit der 20.7.2006 gemeint und nicht der 23.12.2015.

**Comment by Ikarium-Nef** [comment]
Wieder richtig, dann biste bei ~4.1. Spielt aber keine Rolle weil wie du sagtest das wiederum eher für eine noch höhere (korrekte) Procchance spricht.

Habs bei Thotbot nun auch gesehn, das Datum ganz oben in der Ecke. Aber 80%? Der hat ja weder Daten noch ein Video dazu. Aber ka, vllt findet sich noch was verlässlicheres.

**Comment by dagochen** [comment]
Naja es sind fast 10 Leute, unabhängig voneinander.

**Comment by Ikarium-Nef** [comment]
Joar, ein paar Videos mit Bosskämpfen und mehreren Anwendungen wären natürlich nett. Ist halt die Frage wo man sowas auftreiben soll.

**Comment by Ikarium-Nef** [comment]
https://www.youtube.com/watch?v=GlGI6ZnQx5c&feature=youtu.be 
Test der zeigt wie es momentan funktioniert. Habe nach Aktivierung des Trinets einen Proc bei 19 Schüßen gezählt.
