### ISSUE TITLE
Der Vermisste Diplomat

### ISSUE THREAD

**Issue by goofysdad** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1358]
Die Quest http://datenbank.welli-it.de/?quest=1267 ist nicht mehr annehmbar. Die Weiterleitung von der Späherwacht zu Jaina bleibt aus. Q Geber haben ein blaues Fragezechen auf dem Kopf.

**Comment by Slimmer2** [comment]
Kann ich nicht bestätigen habe die Folgequest problemlos erhalten

**Comment by hraesvelgr** [comment]
@goofysdad  wdb ordner im wow verzeichnis löschen.

**Comment by goofysdad** [comment]
Habe es jetzt bei 2 Accounts mit unterschiedlichen Installationen beobachtet. WDB Ordner und Datei löschen bringt nix.  http://datenbank.welli-it.de/?npc=4967 Steht bei mit in der Späherwacht und im Turm von Theramore. Er hat ein blaues Fragezeichen überm Kopf und ich kann die Q anzeigen lassen aber nicht abgeben - das q abgeben sollte bei Ihm ja auch nicht möglich sein. Ich habe auch mal alle Addons deaktiviert. Keine Besserung.

**Comment by Slimmer2** [comment]
Welche Wiederholbare Quest hat der NPC?
Wende dich doch mal an die GM`s?

**Comment by goofysdad** [comment]
Er zeigt mir den Questtext an den Jaina haben sollte. Wo man am Ende Jainas Siegelring bekommt. http://datenbank.welli-it.de/?quest=1267 
Diesen Text zeigt er in der Späherwacht stehen und im Turm von Theramore an. Jaina im Turm von Theramore zeigt ihn auch an. Ich sehe sogar den gelben abgebe Punkt auf der Minimap, obwohl ich keine Quest dazu im Q Log habe.

**Comment by dagochen** [comment]
Gleiches Problem habe ich mit Twinks bei der Weihnachtsquest. Vermutlich ist irgendwas kaputt gegangen beim Fix was die Questhistory der Spieler angeht. Dadurch sind manche Quests, die man grad gemacht hat, weder annehmbar noch beendbar.

**Comment by dagochen** [comment]
Quest vor kurzem ohne Probleme komplett durchgemacht. Kann hier vielleicht nochmal wer gucken, ob doch irgendwas falsch läuft? Dann mache ich das Ticket gerne wieder auf.

**Comment by WoW-Sid** [comment]
Habe das Quest gerade absolviert: Hendel gibt auf und das Quest wird als "abgeschlossen" markiert. Jedoch spawnen Tervosh und Jaina nicht wie gedacht. Derzeit muss man nach Theramore in den Turm zurück, um das Quest abzugeben.

**Comment by dagochen** [comment]
Sollten die spawnen? Gibts dazu Quellen oder ein Video, dass man sieht wo und wie sich das dann abspielen soll?

**Comment by WoW-Sid** [comment]
Einmal WoWwiki:
http://wowwiki.wikia.com/wiki/Quest:The_Missing_Diplomat_(16)

Und ein Video aus Patch 4.0.1 (pre Shattering, das erst mit 4.0.3 kam)
https://youtu.be/6XeuwJnqSd4?t=7m15s

Vorher sieht man noch, wie Tervosh in den ersten Turm portet (während Vorquest):
https://youtu.be/6XeuwJnqSd4?t=5m9s

**Comment by WoW-Sid** [comment]
Außerdem noch wowhead Kommentare:

Über "Jaina Proudmoore" vom 2006/09/17 (Patch 1.12.0)
"**She only goes to 45, 24 for a quest.** You can find her 99% of the time in Theramore."
http://www.wowhead.com/npc=4968/lady-jaina-proudmoore#comments

Über "Private Hendel" vom 2007/09/30 (Patch 2.2.0)
"I soloed him at level 33 as a protection paladin. **When you attack him the other two guards will attack you.** Just ignore them and focus on him **once you get him down to around 30% npcs will come and the fight will be over** and the other two guards will run off."
http://www.wowhead.com/npc=4966/private-hendel#comments

Über das Quest vom 2007/06/10 (Patch 2.1.1)
"i got the funniest bug, i kited the 3 to the nearby guard tower and the guards helped me to fight them, but before they were dead they started to run and dissapeared, **after i noticed that the guys who show up after quest complete were there and i was able to dinish the quest** and get the rewards without actually killing the missing diplomat :)"
http://www.wowhead.com/quest=1324/the-missing-diplomat#comments:0

Über das Folgequest vom 2007/05/20 (Patch 2.0.12)
"**After completion of the previous quest part, she [Jaina] usually comes to thank you for subduing Hendel, but will quickly despawn and reappear back in the upper level of her tower**. On the two times I've done this quest she usually does it right before I can click complete on the quest fo finish it, which is a pain."
http://www.wowhead.com/quest=1267/the-missing-diplomat#comments

**Comment by Slimmer2** [comment]
Wieso steht im Questtext " Sprecht mit Jaina Proudmore im Sumpf der Düstermarschen." ?

**Comment by Lycanon** [comment]
Hallo,
ich habe nun fast das selbe Problem bei der Questreihe "Der vermisste Diplomat" [https://datenbank.classic-wow.org/?quest=1250/Der%20vermisste%20Diplomat](url). Mit meinem Mainchar habe ich die komplette Questreihe ohne Probleme abschließen können. Doch mit meinem Twink hänge ich an einer stelle im verlauf der Questreihe fest. Den Teil der Quest [https://datenbank.classic-wow.org/?quest=1324/Der%20vermisste%20Diplomat](url) konnte ich noch abgeben. Ich bin also, wie beim Mainchar auch, zurück nach Theramore gelaufen. Über Erzmagier Tervosh [https://datenbank.classic-wow.org/?npc=4967](url), dem eigentlichen Questgeber, 
[https://datenbank.classic-wow.org/?npc=4967](url) ist nun ein blaues Fragezeichen. Wenn ich ihn anklicke kommt der Questtext [https://datenbank.classic-wow.org/?quest=1267/Der%20vermisste%20Diplomat](url) den ich eigentlich nur bei "Lady Jaina Proudmoore" [https://datenbank.classic-wow.org/?npc=4968](url) bekommen sollte. Wenn ich bei ihm auf "Quest Abgeben" klicke, dann kommt nur der "WoW-Quest-Abgabe-Sound" aber sonst passiert rein garnichts. Über "Lady Jaina Proudmoore" ist ein gelbes Fragezeichen. Wenn ich sie anklicke sollte ich eigentlich den kompletten Queststrang abgeben können. Stattdessen sagt sie nur "Seid gegrüßt, Shayleena". 

Ich habe versucht die Quest abzubrechen und sie dann erneut anzunehmen. Allerdings wird mir die Quest gar nicht im Questlog angezeigt. Ich habe daraufhin einen GM angeschieben. Doch auch seine Tipps die Addons zu deaktivieren und den WDB ordner zu leeren hat nichts gebracht. Nun wurde ich von dem GM in dieses Forum verwiesen.

Freundliche Grüße :)

**Comment by Dotox** [comment]
Ich kann das beschriebene leider nicht reproduzieren. Die Quest: https://datenbank.classic-wow.org/?quest=1267/Der%20vermisste%20Diplomat lässt sich problemlos bei Jaina abgeben.

**Comment by Lycanon** [comment]
Sorry das ich mich erst jetzt wieder melde. Hatte meine Email gewechselt und bin deshalb erst jetzt darauf aufmerksam geworden. Fahre morgen in den Urlaub. Danach werde ich mit Shayleena nochmal zu der Quest reisen und ein paar Screenshots beilegen, welche mein Problem zeigen/beschreiben

Grüße 
Lycanon
