### ISSUE TITLE
AQ40: Princess Huhuran

### ISSUE THREAD

**Issue by Troopilol** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1360]
Noxious Poison funktioniert nicht korrekt.

Istzustand: Trifft lediglich Spieler die sich in Nahkampfreichweite zu Huhuran befinden, kann derzeit dispellt werden.

Sollzustand: Jeder Spieler im Raid sollte als Ziel getroffen werden können, sollte nicht dispellbar sein.

Quelle: Noxious Poison - 2900 nature damage over 8 seconds + Silence. Will hit a random person and anyone around her. Cannot be cleansed.

https://www.youtube.com/watch?v=bh_1rpm5KqM

http://datenbank.welli-it.de/?spell=26053

**Comment by ircfelix** [comment]
Da ist die Übersetzung von "around her" schwammig. Rundherum sagt nichts über die Range aus. Auch die Videoquelle von 2012 is so lala.

**Comment by Troopilol** [comment]
huhuran wurde in dem vid am 10.3.2006 um 20:43 gekillt, zudem sieht man in dem vid das keiner das herstellbare nr gear vom cc anhat.

zu Range kann ich derzeit nur 8-15m ohne quellen angeben, werd dazu aber noch was suchen.

**Comment by Dotox** [comment]
Jeder Spieler im Raid sollte als Ziel getroffen werden können,

Such dazu bitte noch Quellen :)

**Comment by Troopilol** [comment]
Oh hatte  vergessen beim qoute denn wowwiki link anzuhängen.
Quelle: Noxious Poison - 2900 nature damage over 8 seconds + Silence. Will hit a random person and anyone around her. Cannot be cleansed.http://wowwiki.wikia.com/wiki/Princess_Huhuran

Die range indem sich andere spieler am getroffen ziel infizieren können beträgt 15m.
Quelle: Ein ansteckender DoT, der das Ziel für acht Sekunden silenced und alle zwei Sekunden 750 Schaden / Tick macht. Jeder der näher als 15 Einheiten an der Person steht bekommt den selben Effekt. Nicht dispellbar.(http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/tempel-von-ahn-quiraj/)
Wird alle 25 Sekunden auf ein zufälliges Ziel gewirkt, das acht Sekunden zum Schweigen gebracht wird. Außerdem gibt's alle zwei Sekunden 750 Schaden. Sämtliche Spieler in 15 Meter Reichweite um das Ziel bekommen denselben Effekt ab.(http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Der-Tempel-von-AhnQiraj-790727/7/)

Anmerkung: Lediglich das Target Ziel vom Noxius Poison ist vom Silence effekt betroffen, spieler die sich "infiezieren" sind vom Silence effekt nicht betroffen, das ganze sieht man in dem vid was ich im öffnungs post verlinkt habe, dort ist der Spieler Mar vom gift betroffen kann aber weitercasten da er sich nur infieziert hat aber nicht das target ziel war, er geht mit dem mouse curser sogar über das dot Icon und im tooltip steht sogar das er gesilenced ist aber dennoch castet er weiter..

**Comment by Slimmer2** [comment]
Deine links sind etwas zu weit nach classic

**Comment by Troopilol** [comment]
was meinst du damit?

**Comment by Slimmer2** [comment]
guide von buffed 10/2009 und WoW Gamona 11/2008

**Comment by uggeluggel** [comment]
Sinnvoll wäre es jetzt die Patchnotes von Ende 2006 bis 2009 nach Änderungen zu überprüfen bevor man die Quelle als nutzlos abstempelt. Btw Yards sind keine Meter sondern Zoll - ist nur irrenführend übersetzt worden von Schneesturm.

http://wowwiki.wikia.com/wiki/Noxious_Poison?oldid=292322

bestätigt die 15 Yards Range.

**Comment by Troopilol** [comment]
Der Gamona guide düfte noch in classic entstanden sein vor patch 1.10 da bei beim C'thun guide erwähnt wird das ihn bisher niemand besiegt hat. Zudem fehlen bei der auflistung von nr items auch die herstellbaren items vom CC.

Danke Luggel für die weiteren quellen. Wie hast du die spell beschreibung in wowwiki gefunden?

**Comment by Slimmer2** [comment]
https://www.youtube.com/watch?v=MAOSpkvyLjQ
