### ISSUE TITLE
AQ40: Bug trio (Princess Yauj)

### ISSUE THREAD

**Issue by Troopilol** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1361]
Greater Heal

Istzustand: derzeit heilt Yauj nur sich selbst.

Sollzustand: Yauji sollte auch Lord Kri und Vem heilen können.

Quelle: Since the last patch, Yauj seems to heal the other 2 bugs as well, regardless of which one you kill first, significantly increasing the difficulty of the encounter. (http://wowwiki.wikia.com/wiki/Three_Bugs)

Videos find ich dazu derzeit leider nicht.

**Comment by Dotox** [comment]
Ich konnte in den Patchnotes auf die schnelle nichts finden. Welcher Patch ist denn mit "last patch" gemeint?

**Comment by Troopilol** [comment]
In den Patchnotes von 1.9-12..2 konnte ich auch nix finden.
Hab aber noch paar andere quellen finden können.
 Princess Yauj: 
Feared in regelmässigen Abständen alle Spieler in ihrer Umgebung. Durch diesen Fear wird die Aggro komplett resetted. Ausserdem versucht sie immer wieder sich, oder einen der anderen Bosse (sofern in Range), zu heilen (kann unterbrochen werden). Sobald sie stirbt spawnen kleine Käfer die getötet werden müssen. (http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/tempel-von-ahn-quiraj/)

Heilung
Heilt sich oder einen der beiden anderen Bosse um ca. 25 % der Lebenspunkte, dies kann mit Schock, Gegenzauber und Kick unterbrochen werden. Seit dem Patch 1.11 ist die Heilung nicht mehr durch eine Reichweite begrenzt, sondern kann durch den gesamten Raum gezaubert werden.(http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Der-Tempel-von-AhnQiraj-790727/4/)

Heilt sich oder einen der beiden anderen um einen sehr großen Betrag (circa 33%) sollten sie in Reichweite sein, kann mit Shield Bash / Kick unterbrochen werden. (http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-2.htm)


Hab zudem auch ein Video gefunden, allerdings nur in matsche grafik.
https://www.youtube.com/watch?v=U3um7_umTbU
bei 0.21-23 sowie 0.45-47 sieht man das Lord Kri geheilt wird, an der animation sowie das er hp dazubekommt.

**Comment by ChichiWarrior** [comment]
Yauj heilt ihre beiden Familienmitglieder trotz Kick.
Die Animation des Casts endet mit Kick, doch der Heal geht trotzdem durch.

Gruß

Chichi

**Comment by Dotox** [comment]
Danke dir! Habe denke ich den Fehler gefunden und behoben.
