### ISSUE TITLE
Prophet Skeram

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1362]
wenn die phase endet, und beide kopien von ihm kaputt gemacht wurden, und spieler sind zu diesem zeitpunkt übernommen, bleiben sie manchmal übernommen, können zwar laufen (selbstständig, also nicht mehr übernommen), werden aber angezeigt wie wenn sie übernommen sind. diese spieler können auch nicht wieder am kampf teilnehmen und bleiben feindlich den restlichen kampf.

http://datenbank.welli-it.de/?npc=15263

**Comment by ircfelix** [comment]
Können Palas das wegbubbeln und Mages wegblocken?

**Comment by Sabbaer** [comment]
nein, man kann keine skills mehr drücken

**Comment by hraesvelgr** [comment]
normal sollte jede art von mc mit bubble weggehen.

**Comment by Sabbaer** [comment]
richtig, wenn man übernommen wird, sollte man bubble drücken können, dies geht auch nicht, oder eisblock!

**Comment by Bonfuzius** [comment]
Ich hatte diesen Effekt gestern auch. Nachdem ich übernommen, gesheept und nach Ablauf des Mind Control dispellt worden bin, wurden alle Mitspieler weiterhin feindlich dargestelt und ich konnte den Boss und seine Abbilder gar nicht mehr ins Target nehmen. 

Das blieb auch so nachdem ich gestorben und wieder in die Instanz gelaufen bin. Erst ein Neustart von WoW (mit Löschen des WDB-Ordners) brachte Abhilfe.

**Comment by Dotox** [comment]
Das liegt nicht direkt an der Bossmechanik sondern eher an der PlayerAI.

**Comment by Dotox** [comment]
Ich hab das selbst auch schon gesehen, allerdings bekomm ich es selbst nicht reproduziert. Ungetestete Änderungen an der Mechanik sind sehr schwierig, da ziemlich viel kaputt gehen kann. Daher kann ich hier vorerst nichts ändern.

**Comment by Dotox** [comment]
Hab mal was versucht, einfach mal drauf achten.
