### ISSUE TITLE
Die Zähmung der Bestie - Quest Bug | Durotar (Trolle, Orks)

### ISSUE THREAD

**Issue by wooshone** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1363]
Der Quest "Die Zähmung der Bestie" in Durotar behinhaltet einen Fehler. Sobald man den Zähmvorgang unterbricht indem man sich bewegt ist die Zähmung trotzdem erfolgreich. Der Quest lässt sich danach nicht mehr beenden. Bitte beheben! Nerviger Fehler...

**Comment by Slimmer2** [comment]
Quest abbrechen, WDB Ordner löschen.
Dann geht die Quest.
Das andere könnte vom Delay kommen

**Comment by Rushor** [comment]
Sobald man den Zähmvorgang unterbricht indem man sich bewegt ist die Zähmung trotzdem erfolgreich. 

liegt daran, dass der removemode der aura nicht gecheckt wird

remove_by_expire check für die aura in spellauraeffect.cpp adden :)
