### ISSUE TITLE
C'Thun Tentacle Party und Riesige Augententakel

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1364]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
21.12.2015 - 1.2.6

Wie sollte es sein?
Augententakel - http://datenbank.welli-it.de/?npc=15726
Riesiges Augententakel - http://datenbank.welli-it.de/?npc=15334

Diese beiden Mobs machen schon während des Spawns ihre Casts. Sprich, 
- die Augententakel um C'thun herum beschießen ihr Ziel bereits während des Spawnens.
- die riesigen Augententakel fangen auch direkt an, den Eyebeam zu casten. 

Wie ist es?
Normalerweise fangen beide o. g. Mobs erst nach ca. 2 Sekunden an zu casten.

Links:
http://datenbank.welli-it.de/?npc=15726
http://datenbank.welli-it.de/?npc=15334

Quelle:
Videos aus den Jahren damals zu finden ist verdammt schwer, da YT damals nicht so populär war.
https://www.youtube.com/watch?v=_j2S1d7Igy4
Augententakel - 2:22 Min

https://www.youtube.com/watch?v=-d3p5hW-zMo
Riesiges Augententakel - 13:13 Min

Vielleicht kann da noch einer was ergänzen, mit Kommentaren aus diesen Jahren. Aber da diese Mechanik damals einfach so war, wird das wohl keiner näher begründen.

Anmerkung:
Wir hoffen auf einen Fix. :-)

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Sabbaer** [comment]
https://www.youtube.com/watch?v=P1tEflLNYy8

**Comment by Sheed90** [comment]
Push

**Comment by Sheed90** [comment]
Danke für den schnellen Fix! :-)

**Comment by Sheed90** [comment]
Ok, die großen Augen (mit Eyebeam) funktionieren, aber die Tentakelparty casten immer noch instant beim Spawn.

**Comment by ocbalf** [comment]
Hallo lieber Dotox,

du hast den BugReport geschloßen aber die Tentakel Raid Party castet nach wie vor instant beim Spawn.

Ist es also die Intention den Encounter "knackiger" zu gestalten oder wird es noch gefixed ?

Vielen Dank für die schnelle Antwort.

**Comment by Slimmer2** [comment]
Es ist noch nicht aufgespielt

**Comment by Dotox** [comment]
Genau, Update auf Nef erfolgt zeitnah :)
