### ISSUE TITLE
Buff: Kreegs Hauwegstarkbier

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1367]
Kreegs Hauwegstarkbier (Spell 22790) sollte mit allen Willenskraftbuffs stacken.

Wenn man den Willenskraftbuff vom Priester hat und das Gesöff trinkt, verliert man zwar 5 Intelligenz, kriegt aber keine 25 Willenskraft dazu.

Item: http://datenbank.welli-it.de/?item=18284
Spell: http://datenbank.welli-it.de/?spell=22790

Quellen:
"This item used to be very sought after by classes such as resto druids, as prior to patch 3.3.0 the Spirit buff stacked with all other food buffs."
http://wow.gamepedia.com/Kreeg's_Stout_Beatdown

"Patch 3.3.0 (08-Dec-2009): The Spirit buff no longer stacks with other food and spirit buffs."
http://wowwiki.wikia.com/wiki/Kreeg's_Stout_Beatdown

Und es wurde früher den Kommentaren auf Thottbot (diese Quelle ist von 2008, aber die Kommentare sind von 2006) nach wohl auch genutzt:

"2.1 years ago
Lovely thing to drink during a long fight just after you've cast your first spell. The -5 intellect doesn't affect you if your mana isn't full and the +25 spirit is great. "
"2.4 years ago
I chug one of these (in battle!) whenever I get an innervate. "

https://web.archive.org/web/20080615042034/http://thottbot.com/i18284

Danke fürs umkathegorisieren des Debuffs und den schnellen Bugfix!

**Comment by Dotox** [comment]
Hmm. Darf das dann auch mit http://datenbank.welli-it.de/?spell=26004 stacken?

**Comment by ircfelix** [comment]
Naja, da das Bier ein Debuff ist und der Mistelzweig (hierfür liegt ein extra Bugreport vor) ein World Buff sein müsste, sollte es funktionieren.
