### ISSUE TITLE
Traumachirurg der Horde

### ISSUE THREAD

**Issue by Taasch** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1369]
Mit meinem Trolljäger, derzeit lvl52, 1.Hilfe auf 225 kann ich die 1.Hilfequest auf Skill 300 nicht beginnen.
Hab in OG beim 1. Hilfelehrer die Quest "Traumachirurg" http://datenbank.welli-it.de/?quest=6623/Traumachirurg%20der%20Horde annehmen können.
Der Doktor in Arathi http://datenbank.welli-it.de/?npc=12920 hat dann auch ein gelbes Fragezeichen über dem Kopf, ich kann ihn aber nicht anklicken.
Wenn ich die Quest abbreche, kann ich den Doktor nicht direkt ansprechen. Quest in OG neu holen bringt ebenfalls nichts.
Addons waren keine geladen, WTF Ordner habe ich auch geleert. Den Ordner WDB gibt es nicht, nur WDB als Datei (sprich Ordner kann nicht angelegt werden).
2 andere Chars (Taurenkrieger bzw. Taurenschamane) konnten die Quest beenden.
Unterschied vom Troll zu den anderen Chats ist der das derzeit ".rate 4" möglich ist. 
Als ich dies schreibe kann ein Orckrieger lvl 40 die Quest machen :-(

Kann dies damit zusammenhängen das auch nur mein Troll alle Flugpunkte kennt, wie hier beschrieben?
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/63

**Comment by Slipru** [comment]
Lösch mal deine WDB Datei und schalte alle Addons aus bevor du dich einloggst.

**Comment by Taasch** [comment]
Ähm, wie bereits geschrieben, habe ich das bereits gemacht. Außerdem erzählen das seit heute viele Leute im World Channel. Bin also nicht der einzige.

**Comment by hraesvelgr** [comment]
mag das noch jemand bestätigen? ein "im world haben drei leute das auch gesagt" reicht mir da nicht

**Comment by Karmanaz** [comment]
Ich habe die Quest vor ca. 4 Tagen gemacht und sie funktionierte einwandfrei. Konnte auch während Rate 4 aus der Gilde keine Stimmen dazu hören.
