### ISSUE TITLE
Verfolgungsdistanz von Mobs

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1370]
Die Distanz über die Mobs einen verfolgen wenn man keinen Schaden macht, ist viel viel viel zu groß. Ich bin grad von einem Castermob in Andorhol bis zur Chillwindspitze verfolgt worden (ich bin durchs Wasser geschwommen, was Skelette schon mal garnicht können sollten!) und kurz vorm Lager durch den 18. Schattenblitz gestorben.

Wenn man nichts macht was Aggro erzeugt, sollten Mobs nach 5-10 Sekunden umdrehen und nicht 1 Minute hinter einem herlaufen.

Für die Klugscheisserfraktion: Kein Dornen, etc....keine Fähigkeiten benutzt nix....

**Comment by dagochen** [comment]
Vermutung, die mir ein kleiner Gnomenkrieger geflüstert hat:
Die Wut die man durch den Schaden des Mobs bekommt, erzeugt Aggro, was den Mob daran hindert die Verfolgung einzustellen.

**Comment by dagochen** [comment]
Grad noch mal mit anderen Chars ausprobiert:
Immer wenn Mobs einen Angnriff ausführen, wird der Timer der sie zum Einstellen der Verfolgung bringen sollte, zurückgesetzt.

**Comment by hraesvelgr** [comment]
kann es auch sein, dass die npc zum casten "gezwungen" werden? ist mit in den epl ebenfalls aufgefallen, bei der leibwache des boten vom scharlachroten kreuzzug. 
die wache verfolgte mich über die halbe map, und ließ erst von mir ab, nachdem ich ihr "erlaubte" mich anzuchargen (ich blieb einfach stehen bis sie in castreichweite war) nach dem charge rannte der npc sofort zurück und war im evade mode.

quasi musste sie erst zwangsweise ihren cast ausführen, und ging erst danach in den evade mode., egal wie weit weg ich war.
