### ISSUE TITLE
Aderlass

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1372]
Der Spell Aderlass vom Hexenmeister skaliert seit patch 1.12 mit Spelldamage.

Wie ist es:
Aderlass profitiert von 100% Spellpower. Sprich 100 SP = 100+Mana 100-Leben

Wie soll es sein:
Aderlass sollte nur mit 80% Spellpower skalieren.  Sprich 100SP = 80+Mana 80-Leben

Quelle:
http://wow.4fansites.de/patchnotes_1_12.php

**Comment by dagochen** [comment]
Hallo @pdglala ,

meinen Infos zufolge ist der Istzustand auf Nefarian mit 80% Skalierung. Hast du vielleicht bei deinen Tests das verbesserte Lifetap (Talent) gehabt? Dort kommen 20% drauf.

**Comment by pdglala** [comment]
das hatte ich auch @dagochen.
420 Leben zu Mana hat Aderlass. Mit der Skillung 504 Leben zu Mana.
Ich habe 504SP und mein Aderlass gibt mir 1002 Mana zurück.
Sprich es sind nicht ganz genau 100% aber ganz knapp drunter.

**Comment by dagochen** [comment]
504 SP * 0.8 = 403 Mana
420 + 403 = 823
823 * 0.2 = 987 Mana

So viel sollte es sein. Schätze da wird noch irgendwas an Boni mit eingerechnet oder so.

Würde er mit 100% Skalierung rechnen, kämen das hier raus (was deutlich höher als deine 1002 ist!):
504 SP * 1 = 504 Mana
420 + 504 = 924
924 * 0.2 = 1108 Mana

**Comment by Slimmer2** [comment]
Ich bekomm 1101 Mana hab aber etwas über 600 spell.

**Comment by dagochen** [comment]
![wowscrnshot_010116_160101](https://cloud.githubusercontent.com/assets/5236186/12071231/f55fbe36-b0a0-11e5-82f2-e8c60b58342b.jpg)

**Comment by hraesvelgr** [comment]
sehr präzise berechnungen...?!

**Comment by Slimmer2** [comment]
Wenn ich meine Hände mit 43 Spell ausziehe bekomme ich 41 mana weniger
Wenn sich das mit der Berechnung hingeht, dann passt der Wert den man hier am Server bekommt

**Comment by dagochen** [comment]
43*0,8*1,2= 41,28

Passt. Alles i.O..

**Comment by pdglala** [comment]
okay ich habe rausgefunden was mich stutzig gemacht hat.

420 mana unskilled
504 mana skilled
diff= 84 Mana

lifetap:
504mana (skilled) +519 SPD
519SPD = 100%
415,2 = 80%

504+ 415,2  = 919 Mana vom Tap
Ich bekomme mit der SPD 1002 Mana
1002-919= 83 extra mana

Imp Aderlass 420 -> 502 = 82 Mana

Sprich: die extra mana werden doppelt dazu gerechnet oder nochmal mit 100% der Spelldamage.

**Comment by dagochen** [comment]
Nein. Du bekommst 20% durch das Talent auf den Basiswert (420*1,2=504) UND den Spelldmg-Anteil (415*1,2=498). Dann addierst du 504 und 498 und kommst, oh wunder, auf 1002 Mana.
