### ISSUE TITLE
[NPC] Wache von Undercity - Falsche Auskünfte

### ISSUE THREAD

**Issue by b2410** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1374]
Fragt man eine Wache von Undercity nach dem Leherer für Bergbau, wird man zum inneren Ring im Schurkenviertel verwiesen.
Richtg wäre der innere Ring im Kriegerviertel.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451 teil dieses fehlers.
