### ISSUE TITLE
AQ40: Bug trio

### ISSUE THREAD

**Issue by Troopilol** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1375]
Fehlender nicht vorhandene Fähigkeit.

Istzustand: derzeit verzehren die noch lebenden bugs die leichen eines gestorbenen bugs nicht und heilen sich demnach auch nicht.

Sollzustand: nachdem ableben eines Bugs rennen die noch leben bugs zur Leiche und verzehren diese, damit regenieren sie ihre HP.

Quelle: Jedes Mal, wenn einer der 3 Bosse stirbt, rennen die verbleibenden Bosse zu dem Kadaver und fressen ihn auf - dadurch regenerieren sie zusätzlich Hitpoints! (http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-2.htm)

Videos: https://www.youtube.com/watch?v=U3um7_umTbU
https://www.youtube.com/watch?v=YAPjGr56rEc
https://www.youtube.com/watch?v=rw5qL72bYJs
https://www.youtube.com/watch?v=RBm0YvKKCJs

Anmerkung: Um welchen Betrag sie dabei geheilt werden weiß ich nicht. Ich vermute mal  das sie sich wieder auf 100% hoch generieren, im letzten vid erkennt man recht gut das Yauj von 97% direkt auf 100% HP springt.

**Comment by Dotox** [comment]
Die Chase-Animation ist etwas umständlicher, aber die eigentliche Funktion (das Heilen) sollte nun funktionieren.
