### ISSUE TITLE
AQ40: Lord Kri und Viscidus

### ISSUE THREAD

**Issue by Troopilol** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1377]
Nicht richtig funktionierender Spell

Istzustand: derzeit ist es anscheinen möglich den dot vom Poison Volley/Toxic Volley  zu resisten.

Sollzustand: der Dot vom Poison Volley/Toxic Volley soll nicht resistbar sein.

Quelle: Poison Volley: SIMILAR to Lord Kri and Princess Huhuran. This volley ignores LoS and has a range of 100 yards, therefore it is very difficult to avoid it. Nature Resist gear can greatly mitigate the direct damage, but the DoT is UNRESISTABLE and therefore highly lethal. Poison curing must be set up for the raid so that no one is hit by more than one tick of the DoT. (http://wowwiki.wikia.com/wiki/Viscidus)

http://datenbank.welli-it.de/?spell=25991
http://www.wowhead.com/spell=25812/toxic-volley

Anmerkung: Laut datenbank besitzt Lord Kri keine Fähigkeiten.
Ob es zudem am resist liegt kann ich nicht 100% sagen, es sind halt nicht alle im Raid nach dem Volley vom Dot betroffen.

**Comment by Troopilol** [comment]
Istzustand: der direkte Schaden des Poison/Toxic Volley ist derzeit nicht resistbar.

Sollzustand: der direkte Schaden des Poison/toxic Volley sollte resistbar sein, ergo der normalen resi mechanic unterliegen, vom Dot ist man ebenfalls beim einem vollständigen resist des volleys nicht betroffen.

Quelle: Poison Volley: AoE spell cast every 10 seconds that hits for ~1500 resistible Nature damage on hit and will apply a dispellable DoT that does ~500 Nature damage every 2 second for 10 seconds. Similar to Lord Kri and Princess Huhuran. This volley ignores LoS and has a range of 100 yards, therefore it is very difficult to avoid it. Nature Resist gear can greatly mitigate the direct damage, but the DoT is unresistable and therefore highly lethal. Poison curing must be set up for the raid so that no one is hit by more than one tick of the DoT.(http://wowwiki.wikia.com/wiki/Viscidus)

The most dangerous ability is an area wide Toxic Volley that hits for ~500 nature damage and DoTs for 125 damage per tick.(http://wowwiki.wikia.com/wiki/Three_Bugs)

Video: https://www.youtube.com/watch?v=XRRE4EM9yT0
Bei min. 2:48-2:49 sieht man wie der Druide den Bolt resisted und den den dot nicht abbekommt, ebenfalls im gesamten video sichtbar das der bolt der normalen resi mechanic unterliegt.

Anmerkung: derzeit ist Viscidus nicht wirklich killbar.

**Comment by Dotox** [comment]
Dass der Schaden unterschiedlich hoch ist, wird wohl daran liegen, dass die Zauber zwei unterschiedliche sind (trotzdem gleich heißen).

**Comment by Troopilol** [comment]
Wie meinen? der zauber von Lord kri heißt etwas anders als der von viscidus

geht halt darum das ich bei 180nr 1600 volleys hit abbekommen hab und keinen unter 1400.

**Comment by Omegaexodus** [comment]
Hallo Entwicklerteam, 

leider muss man sagen, das es momentan nicht möglich ist, weder Bug-Trio noch Viscidus zu töten. 

Das liegt daran, das der Fähigkeit "Giftsalve" nicht widerstanden werden kann (unabhängig der Naturessi). Somit wird immer der maximale Schaden auf alle Spieler durch die Salve zugefügt (Grundschaden). Das einzige was nicht widerstanden werden sollte, ist der von der Salve zugefügt Debuff (Toxisches Gift). Dieser sollte hochstacken und immer maximalen Schaden verursachen können. Natürlich kann dieser, durch Zauber wie "Gift entfernen" aufgehoben werden.

Fähigkeiten:
http://datenbank.welli-it.de/?spell=25991

Quellen:
http://wowwiki.wikia.com/wiki/Viscidus
http://wowwiki.wikia.com/wiki/Three_Bugs

Da beide Bosse, Kri und Viscidus die (annährend) selbe Fähigkeit beherschen und es keine Möglichkeit gibt, den Schaden gegen zu heilen, zu resisten oder anderweitig zu verhindern, sind beide Bosse so momentan nicht tötbar. 

Wir hoffen sehr, das es noch diese ID Anpassungen geben wird.

Mfg Omega :-)

**Comment by Dotox** [comment]
Vielen Dank :)
