### ISSUE TITLE
AQ20/40: Anubisath Guardian/Defender

### ISSUE THREAD

**Issue by Troopilol** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1381]
Shadowstorm

Istzustand: derzeit beträgt die deadzone 0-45yards.

Sollzustand: die Deadzone beginnt bei 20 und hört bei 45yards auf.

Quelle: Shadow Storm is spam of AoE shadow bolts that do ~1000 damage. Shadow resist can reduce the amount of damage taken from this spell. This spell also has a dead zone; meaning the Shadow Bolts can be avoided if you stand close. Shadow Storm has a range of 20-45 yds.(http://wowwiki.wikia.com/wiki/Anubisath_Guardian , http://wowwiki.wikia.com/wiki/Anubisath_Defender)

**Comment by Baraz** [comment]
Es gibt unterschiedliche Mobs, die leicht verwechselt werden können:

1. AQ20 auf der Terasse vor Ossirian [Beschützer/Guardian](http://datenbank.classic-wow.org/?npc=15355)
2. AQ40 vor Skeram [Wächter/Sentinel](http://datenbank.classic-wow.org/?npc=15264)
3. AQ40 zwischen Huhuran und Trash [Verteidiger/Defender](http://datenbank.classic-wow.org/?npc=15277)

Alle drei sollten die Fähigkeit [Schattensturm](http://datenbank.classic-wow.org/?spell=14297) besitzen. Diese, sollte wie hier #1487 und hier #572 aufgezeigt eine Reichweite von 20-45yards aufweisen, d.h. eine Deadzone besitzen. 

Videos, die ich dazu gefunden habe wären noch [hier](https://www.youtube.com/watch?v=QDq10BmaafI) ab ca. 0:50, [Death and Taxes Progress](https://www.youtube.com/watch?v=zoSeBQy4ZuM) (Video von 2008) und [Video von 2009](https://www.youtube.com/watch?v=azzg1d8SsBo).

Es gibt 3 unterschiedliche Shadow Storms in der Datenbank:
1. http://datenbank.classic-wow.org/?spell=14297
2. http://datenbank.classic-wow.org/?spell=26546
3. http://datenbank.classic-wow.org/?spell=26555

Meines Wissens nach nutzt der Wächter/Guardian in AQ20 die richtige Version des Zaubers, im cMangos/mangos-classic-Repo wäre das [hier](https://github.com/cmangos/mangos-classic/blob/5d797e2ea448eec6c7ebefdfd93598a401005dfe/src/scriptdev2/scripts/kalimdor/ruins_of_ahnqiraj/ruins_of_ahnqiraj.cpp) in Zeile 37 der Spell mit der ID 26546.

**Comment by Baraz** [comment]
Die Tage nochmal überprüft: die Beschützer/Guardians in AQ20 nutzen die Variante des Schattensturms, der eine Deadzone von 20m besitzt. Diese sollten auch die Wächter/Sentinel und Verteidiger/Defender in AQ40 nutzen.

**Comment by dagochen** [comment]
Duplikat
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1487
