### ISSUE TITLE
extreme serverlaggs

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1385]
der server fängt ab ca. 1k spieler an massiv zu laggen

**Comment by Slimmer2** [comment]
Aktuell sind ca 1450 Spieler on

**Comment by Sabbaer** [comment]
^richtig, das problem fängt bei 1k spielern an, mehrfrach nun beobachtet

**Comment by rockefaeller** [comment]
Wirklich ganz genau bei 1000?

**Comment by Sabbaer** [comment]
das kann ich nicht genau sagen, aber vor 1k spielern gibt es meistens keine probleme, kann natürlich auch mit etwas total anderem zusammenhängen

**Comment by ircfelix** [comment]
http://cdn.meme.am/instances/500x/66268125.jpg

**Comment by hraesvelgr** [comment]
erinnert mich an das problem der spielübertragungen für zuschauer bei LoL, wo plötzlich keine übertragung mehr stattfand, da die maximale anzahl an unterschiedlichen ID's für alle matchübertragungen erreicht war, und der server keine weiteren id's berechnen konnte.

**Comment by dagochen** [comment]
Naja es wird irgendwo halt ein Nadelöhr geben. Sprich der Server macht etwas, was zu lange dauert und dadurch baut sich dann das Lag auf. Wird ja auch immer schlimmer, je länger der Server läuft. Gibt verschiedene Stellen, an denen die Ursache sein kann. Da es aber beim letzten mal bereits die mysql Schnittstelle war, würde ich da wieder drauf tippen....

**Comment by Dotox** [comment]
Kann 1000 Ursachen haben und die sind leider nicht so einfach herauszufinden. Müssten dazu verschiedene Analyse-Tools während dem Spielbetrieb laufen lassen die diverse Dinge ausführlich tracken.

Die Auslastung der Hardware war in Ordnung, der mySQL-Server hatte zwar einiges zu tun aber dafür ist er ausgelegt. Die massiven Lags damals lagen an der sehr langsamen HDD (mittlerweile auf SSD umgestiegen).

Wir brauchen dazu auf jedenfall einige Tage an denen richtig viel los ist damit wir einiges an Daten sammeln können. Ohne diese Daten wird das nichts. Ist ungefähr so, als würden wir die Nadel im Heuhaufen suchen.

**Comment by Slimmer2** [comment]
Aktuell lags es wieder, sind über 1000 Spieler on

**Comment by Pannndara** [comment]
Keine Ahnung ob es auch weiterhilft, aber nach nem Serverneustart ist es in der Regel meistens keinen Deut besser, bei nem Servercrash geht der Server für ne Weile merkbar besser.

MfG

**Comment by Larnak1** [comment]
Keine Ahnung, ob es hilft, aber hier nochmal ein paar Details zu den Laggs, die mir aufgefallen sind:

Das Problem gibt es ja in geringerem Ausmaß ja schon seit recht langer Zeit, wer sonntags BWL geht kennt das. Wann genau das angefangen hat, kann ich nicht mehr sagen, es müsste irgendwann im Oktober gewesen sein. Meistens war es dann wieder gut, sobald ein Neustart kam. An Nicht-Sonntagen ging es normalerweise auch gut. Mittlerweile ist das Problem aber noch deutlich stärker geworden, gefühlt seit der AQ-Öffnung, was ja auch zu deutlich höheren Spielerzahlen geführt hat. Neustarts helfen seitdem kaum noch. Am Sonntag haben wir in AQ beobachtet, dass es später am Abend (so gegen 22 Uhr?) wieder besser wurde, vermutlich sanken da die Spielerzahlen bereits wieder. Aber auch andere Tage sind jetzt stark betroffen, gestern beispielsweise (Montag).

Auffällig ist, dass die Raidinstanzen sehr viel stärker betroffen sind als alles andere. Während man in der offenen Welt noch quasi lagfrei spielen kann, ist in den Raids schon Land unter. Gestern mussten wir BWL bei Razor nach 2 Stunden abbrechen, weil es einfach nicht möglich war, die Situation zu kontrollieren, wenn die Mobs sich 10 Meter nach vorn oder hinten porten, unter dem Boden, durch Wände oder Hindernisse laufen, nicht auf Beschuss reagieren oder einfach nicht angegriffen werden können, weil man angeblich nicht in die richtige Richtung blickt. Wir sind dann noch zu Ony, wo man die Auswirkung auch sehen konnte. Beim Übergang in P2 ist sie in rasendem Tempo durch ihre Höhle geflattert und der optische Feuer-Effekt ihres Atems kam erst, nachdem sie schon längst wieder auf der anderen Seite ihre Feuerbälle castete. Auch der Chat hatte gestern eine Verzögerung von 2-3 Sekunden.

Was die Daten angeht müsste sich momentan wahrscheinlich fast jeder Tag zum Sammeln eignen, wenn ich mir überlege, wie schlimm es gestern war, was ja ein relativ normaler Montag war.

Wenn wir noch irgendwas tun können, um bei der Fehlersuche zu helfen, sagt bitte Bescheid.

**Comment by Dotox** [comment]
Ich hab auf dem Testserver mal eine Session eingerichtet. Wäre von Vorteil wenn einige von euch dort etwas Zeit mit Duellen, Instanzen, Farmen oder ähnlichem verbingen würden.

**Comment by Larnak1** [comment]
Brauchst du dort eine hohe Auslastung oder reicht es, wenn einfach nur 5 Hansel irgendwas machen?

**Comment by Dotox** [comment]
Würde wohl nicht reichen. Die Tests von heute haben fast nichts hilfreiches ausgespuckt. Wir wiederhohlen das ganze ab morgen Vormittag auf dem Liveserver.

**Comment by Larnak1** [comment]
Das ist wohl besser, ich bin heute daran gescheitert, Leute für Testserveraction zu überreden :/

**Comment by Sheed90** [comment]
Status?

**Comment by Slimmer2** [comment]
Der Server lief gestern wieder gut

**Comment by Sheed90** [comment]
http://community.mmobase.de/hilfe-und-support/8593-lags-ohne-ende-aq-3.html
