### ISSUE TITLE
peitscherwurzel

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1387]
Welches Verhalten wird beobachtet?
man reinigt eine peitscherwurzel und sie verschwindet einfach
Wie sollte es sich verhalten?
nach reinigen der peitscherwurzel sollte man sie looten können und 3-10 http://datenbank.welli-it.de/?item=11951 knollen entstehen
Schritte zur Reproduzierung
son ding im teufelswald reinigen und das 10 mal und nix dafür bekommen
Zusätzliche Informationen (Screenshots, Videos, etc.)
das ganze ist recht ärgerlich, denn man braucht diese knollen für buchband der gier

http://datenbank.welli-it.de/?object=164883 spawnt nicht nach reinigen einer
http://datenbank.welli-it.de/?quest=4443
um http://datenbank.welli-it.de/?item=11951 zu erhalten

**Comment by Slimmer2** [comment]
Ich habe Gestern erst eine gesäubert und es funktionierte ohne Probleme,
Ich habe die bei den Baum nördlicher ist vom NPC von den man die Cenarische Pflanzensalbe gesäubert.
Betrifft das evtl nur einzelne Peitschwurzel?

**Comment by Sabbaer** [comment]
das weis ich nicht ich hab 3 verschiedene mehrfach gereinigt und keins hat was gegeben, und leute aus anderen gilden meinten, bei ihnen funktionierts auch nicht

**Comment by dagochen** [comment]
ich hab ziemlich im süden mal 2 gereinigt die nicht gingen.

**Comment by Sabbaer** [comment]
so es sind mehrere dieser verbuggt, außerdem stimmen die standorte überhaupt nicht mit denen wo sie eigentlich stehen sollten überein
http://images.google.de/imgres?imgurl=http%3A%2F%2Fwww.max666.net%2Fwow%2Ffelwood_pflanzen.jpg&imgrefurl=http%3A%2F%2Fwww.pentakel.de%2Fphpbb%2Fviewtopic.php%3Ft%3D19&h=505&w=760&tbnid=bOyw1AeTFLXOHM%3A&docid=YLFUZNgW5TsI-M&ei=mSmNVpaWIMLCPOHiusAL&tbm=isch&iact=rc&uact=3&dur=783&page=1&start=0&ndsp=30&ved=0ahUKEwjWxovAt5XKAhVCIQ8KHWGxDrgQrQMIKjAD
dort sind die orte wie auf anderen karten auch eingezeichnet

**Comment by dagochen** [comment]
top quelle ;)
