### ISSUE TITLE
AQ40. Port zu den Twins

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1388]
Ist:

Wenn man den t2,5 Kopf und die t2,5 Schultern bei Andorgos abgibt, ist der Port zu den Twins Raum für die Leute nicht mehr anwählbar.

Soll:

Man sollte Andorgos auch nach den zwei Quest weiter anreden können und in den Raum zu den Twins porten können.

**Comment by Dotox** [comment]
Das nächste mal bitte den NPC verlinken :)
