### ISSUE TITLE
Mobs laufen über die ganze Map hinterher -.-

### ISSUE THREAD

**Issue by Hstyle** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1390]
Nicht alle Mobs, aber zumindest die dessen lvl minimum noch in grün angezeigt wird, laufen mir die komplette Map hinterher sobald ich sie einmal gepullt hab. Meistens sterbe ich dann, weil ich dann mehrere gepullt hab ( wenn man mal aus ner Höhle abhauen will ohne alles nochmal zu metzeln z.B. xD) Normalerweise lassen sie einen doch in Ruhe sobald man eine bestimmte Strecke gelaufen ist nach dem Pull oder?? 

Danke schon mal für die Hilfe :)

**Comment by hraesvelgr** [comment]
zuerst einmal möchjte ich, dass du dich fragst: 
>"warum habe nur ich dieses problem? wenn nur ich dieses problem habe, was mache ich falsch?"

das ist der erste schritt zum erfolgreichen bugreport.

hier ein paar szenarien, die dafür sorgen, dass dir npc über die ganze map hinterherlaufen:
-du bist gebufft mit: aura der vergeltung, dornen, feuerschild oder anderen reflektierenden auren
-die npc sind beschworene diener
-du hast dots auf den npc oder machst sonstwie schaden auf sie

**Comment by Hstyle** [comment]
habe nie behauptet ich wäre der einzige bei dem das so ist ^^ 
ja dann wird es am "Dornen" buff liegen. aber selbst damit dürfte es doch nicht passieren oder? selbst wenn ich den gegner schaden zufüge,sollten sie irgendwann wieder umkehren. oder kam dies erst in späteren WoW Erweiterungen? habe bis vor kurzem auf dem Offi Server gespielt.

**Comment by Sabbaer** [comment]
kam erst später

**Comment by Hstyle** [comment]
ah okay, dann vielen dank für die schnellen antworten!

**Comment by Slipru** [comment]
Ist die Funktion korrekt, dass einem alle Diener nach einem pull unendlich verfolgen bis man selbst oder sie sterben?

**Comment by Slimmer2** [comment]
Hatte den Fehler heute auch, mit Dornen Buff

**Comment by Slipru** [comment]
Ich hatte ihn heute bei verschiedenen "Dienern" bzw. "Begleitern" ohne dass sie dmg bekommen haben.
