### ISSUE TITLE
[Quest] Marschenfroschschenkel

### ISSUE THREAD

**Issue by Truncsta** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1391]
Ist-Zustand:
Die für die Quest benötigten Marschenfrösche http://datenbank.welli-it.de/?npc=23979 sind in den gesamten Düstermarschen nicht zu finden. 

Soll-Zustand:
Die Frösche sollten sich im Umfeld um das Haus vom Questgeber "Sumpfauge Jarl" http://datenbank.welli-it.de/?npc=4792 befinden. Einen 1.12.1 Beweis habe ich nicht, aber in folgendem Video aus 2010 sieht man ganz gut wie's ausschauen soll. 
https://www.youtube.com/watch?v=eCdusALCvKs

Danke & Gruß

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1240

**Comment by Truncsta** [comment]
Oh sorry, hatte nur eine gecloste gefunden. Kann dann geschlossen werden.
