### ISSUE TITLE
AQ40: Ouro (Full Bug-Report)

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1392]
Hallo Entwicklerteam, 

dieser Beitrag widmet sich voll und ganz dem Encounter "Ouro" in AQ (40) und beschreibt sämtliche momentan auftretende Fehler und Probleme.

Da es sich um mehrere, teilweise schwerwiegende Fehler handelt, ich aber aufgrund der Übersicht an Issues diese nicht in 4 extra Reports unterteilen möchte, werden alle hier übersichtlich angeordnet und beschrieben.

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 1: Bewegung von Ouro

Wie sollte es sein?
Ouro sollte sich während seiner "Up-Phase" nicht bewegen oder ziehen lassen dürfen. Er hat eine feste Position wie Ragnaros die sich nur nach einer Erdbebenphase (Submerge) ändert.

Wie ist es?
Leider bewegt sich Ouro und kann durch den Maintank durch den Raum zu einer Wand oder ähnlichem gezogen werden. Ouro sollte sich jedoch nur bewegen dürfen, wenn er sich eingegraben hat (Submergephase). 

Quellen: 	       
http://wowwiki.wikia.com/wiki/Ouro

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 2: Sandblast funktioniert nicht richtig

Wie sollte es sein?
Ouro sollte eine Fähigkeit mit dem Namen "Sandblast" einsetzen, die alle Spieler in einem 180 Grad Radius vor Ihm trifft, Ihnen 3,5 - 4,5k Naturschaden (binary) zufügt und Sie 5 sec lang betäubt. Zusätzlich verlieren alle Spieler die von Sand Blast getroffen werden, sämtliche Aggro. Ouro visiert immer die Person mit der momentan höchsten Aggro an. (Range 45 yards)

Wie ist es?
Die entsprechenden Spieler verlieren nicht die Aggro von Sand Blast. Bitte überprüfen, ob die Fähigkeit Binary ist, so dass sie nur komplett oder gar nicht widerstanden werden kann. 

Fähigkeit: 	
http://www.wowhead.com/spell=26102/sand-blast#used-by-npc

Quellen: 	        
http://www.wowhead.com/npc=15517/ouro#comments 
Comment von sirfracas-Wallace/2006)
http://wowwiki.wikia.com/wiki/Ouro

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 3: Ouro Käfer funktionieren nicht richtig

Wie sollte es sein?
Nach dem Ende der Submerge-Phase, kurz bevor Ouro wieder auftaucht, sollten 12 Käfer von Ouro erscheinen. Jeder Käfer verursacht Schaden in Höhe 100 - 300 (Abhängig von der Rüstung). Jeder Käfer wählt sich ein zufälliges Ziel aus und sollte niemals das angewählte Ziel wechseln. (Spott und Aggro Immun) Außerdem verschwinden die Käfer nach genau 45 Sekunde wieder. (auto-despawn)

Wie ist es?
Leider wählen sich die Käfer kein selbstständiges zufälliges Target, sondern gehen nach der Aggro- Liste verursacht durch Heiler etc. . Außerdem sollten sie nicht mehr ihr Ziel wechseln und Spott- sowie Aggro Immun sein. Außerdem despawnen die Käfer nicht wie vorgesehen selbstständig nach 45 sec wieder. (Sie bleiben permanent vorhanden und könnten nur durch das Töten beseitigt werden)

Quellen: 	
http://wowwiki.wikia.com/wiki/Ouro
http://www.wowhead.com/npc=15718/ouro-scarab#abilities

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 4: Erdbeben / Submergephase

<b>Dieser Bug ist schwerwiegend und muss behoben werden, da es sonst unmöglich ist den Boss zu töten!

Wie sollte es sein?
Wenn sich Ouro eingräbt startet die Submergephase. In dieser Phase ist Ouro nicht anwählbar und auch immun gegen sämtlichen Schaden. (Aggro resett included) In dieser Phase verfolgt er mit 4 großen Erdbeben zufällige Spieler. Alle diese Erdbeben verschwinden sobald Ouro wieder aus dem Boden hervorbricht. Aus 3 der 4 Erdbeben kommen insgesamt 12 Käfer von Ouro heraus. Aus dem Letzten kommt Ouro selbst heraus.

Wie ist es?
Das größte Problem ist, das eines der Erdbeben nach der Submergephase nicht verschwindet und die gesamte Zeit über vorhanden bleibt. Es verursacht weiterhin Schaden und führt auf lange Sicht zum Wipe, da pro neue Submergephase +1 Erdbeben hinzukommt. Alle Erdbeben müssen vollständig verschwinden. Außerdem ist der Boss immer noch anvisierbar und angreifbar. Dies sollte auch nicht möglich sein.

Quellen: 	
http://wowwiki.wikia.com/wiki/Ouro
http://www.wowhead.com/npc=15517/ouro#comments 
(Comment von sirfracas-Wallace/2006)

-------------------------------------------------------------------------------------------------------------------------------

Bis lang war es uns noch nicht möglich in die Enragephase ab 20% zu gelangen, da uns die wachsende Anzahl der Erdbeben auf lange Sicht immer vorher getötet hat. 
Hier noch mal ein Video von einem offiziellen Ouro Kill 2006:

(Achtung Musik besser ausstellen) 

https://www.youtube.com/watch?v=ynF2S_Bv1yU

Für weitere Fehleranalysen werde ich Dotox noch ein Video von unseren Trys an Ouro schicken. Dann kann er sich das Ganze noch mal direkter anschauen, um mögliche Fehlerquellen ausfindig zu machen.

Wir hoffen darauf, dass der Boss möglichst schnell mit allen oben genannten Fehlern überarbeitet wird, da er momentan nicht tötbar ist.

Vielen Dank im voraus für das Beheben der obengenannten Fehler/Bugs.

Omega :-)

**Comment by ircfelix** [comment]
Schöner Bugreport. Da die wowwiki Guides sich oft von anderen Guides unterscheiden, würde ich noch andere Guides durchlesen. Wenn es nach den wowwiki guides ginge wäre Aq noch bisschen einfacher als nach anderen guides.

**Comment by Omegaexodus** [comment]
@ircfelix danke für das Feedback.

Leider muss man sagen, das Ouro auf Grund der damaligen niedrigen Priorität in AQ40 nur wenig Aufmerksamkeit und Guides erhalten hat. Die Informationsquellen zu Ihm sind daher begrenzt. 

Dennoch habe ich noch mal einige weitere Quellen zu Ihm herausgesucht um die Datenvielfalt zu erhöhen.

Hier noch mal 2 Datenbankbestände, da ich oben leider die aus dem Orginal wowhead genommen habe: (gilt für Sand Blast und Käfer von Ouro)

Sand Blast: http://datenbank.welli-it.de/?spell=26102
Käfer von Ouro: http://datenbank.welli-it.de/?npc=15718#abilities
Bindungsfähigkeit von den Käfern: http://datenbank.welli-it.de/?spell=20477

Desweiteren noch mal 1 Video von Ouro Kill 2006: 

https://www.youtube.com/watch?v=lSM0dny56JY (Sound ausstellen)


Ich werde die Tage, falls noch Interesse besteht, weitere Datenquellen heraussuchen, momentan nur noch ein weiterer erwähnenswerter Guide: (Scroll zum Ouro Part)

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/1140-ultimate-aq40-guide.html

Da wir bis jetzt nicht noch mal zu dem Encounter gekommen sind (ID Resett) und wir noch nicht überprüfen konnten ob Änderungen vorgenommen worden sind, hier noch mal ein PUSH (just in case).

Wir würden uns sehr darüber freuen, wenn zumindest die Erdbeben (Submergephase) behoben werden kann, damit wir mal bis in die 20% Phase hineinkommen. Wie gesagt, momentan ist der Boss so unlegbar.

Mit freundlichen Grüßen 
Omega :-)

**Comment by Dotox** [comment]
Bis auf den Erdbeben-Punkt hab ich alles überarbeitet. Werde aber das Wochenende noch benötigen, um die Änderungen selbst zu testen da es doch etwas umfangreichere Anpassungen gewesen sind. Ich schätze mal Dienstag sollte das Update auf Nefarian gespielt werden können.

**Comment by Omegaexodus** [comment]
Danke dir Dotox, für die ganze Überarbeitung. :-)

Leider ist gerade der Erdbeben-Punkt einer mit der größten Fehler und Probleme zugleich. Wir haben bereits mehrere Ideen und Strategien gegen Ouro eingesetzt, um das Problem eventuell zu umgehen, können aber die wachsende Anzahl an Erdbeben auf Dauer nicht kompensieren. 

Wäre es für dich möglich da noch mal genauer nachzuschauen? Denn leider wird Ouro so sonst nicht tötbar sein, wenn man nach der dritten Submergephase, schon drei zusätzliche Erdbeben draußen hat, die dann auch noch in der Up-Phase vorhanden sind. :-(

**Comment by Dotox** [comment]
Jau, also wie gesagt, bis Dienstag sollte ich alles behoben und getestet haben (auch der Erdbeben-Bug) :)

**Comment by Omegaexodus** [comment]
Ah ok, dann habe ich das missverstanden. Ich hatte rausgelesen das du diesen Fehler noch nicht beheben konntest. Dann danke schon mal für die Überarbeitung! :-)

Wir würden dann am Dienstag um 19 Uhr mal bei Ouro vorbei schauen. Eventuell würde es ja ganz gut passen, wenn du dir Ouro dann noch mal vor Ort mit uns anschauen kannst, um zu sehen ob es noch weitere Anpassungen geben muss. Wir würden uns auf jeden Fall darüber freuen :-) 

Danke noch mal für den Support!
Lg Omega

**Comment by Omegaexodus** [comment]
Hallo Dotox, 

wir haben heute erfolgreich Ouro getryed und auch gelegt. Leider gab es jedoch immer noch einige alte bzw. neue Fehler/Buggs die aufgetreten sind. Dadurch war der Bosskampf teilweise sehr einfach und auch nicht wirklich so wie er sein sollte.

Ich werde die Fehler noch mal hier mit reinstellen, um eine entsprechende Übersicht zu schaffen. Zusätzlich haben wir den gesamten Kampf noch mal aufgenommen, so das ich dir bei Interesse das Video zukommen lassen kann.

-------------------------------------------------------------------------------------------------------------------------------
<b>Bug/Fehler Nr. 1: Submerge / Erdbebenphase bleibt komplett aus

Wie sollte es sein?
Ouro gräbt sich nach einem zufälligem Timer, welcher zwischen 90 und 120 Sekunden liegt ein, woraufhin die Submergephase startet. In dieser Phase verfolgt er mit 4 großen Erdbeben zufällige Spieler. Alle diese Erdbeben verschwinden sobald Ouro wieder aus dem Boden hervorbricht. 

Wie ist es?
Sehr positiv ist es, das nun alle Erdbeben vollständig verschwinden. Jedoch gab es nach 2-3 Submergephasen den Fall, das Ouro gar nicht mehr untergetaucht ist. Er blieb den gesamten Kampf über draußen und hat die Übergangsphase komplett ignoriert. Dies sollte eigentlich nur ab 20% in der Enragephase der Fall sein.

Fähigkeit:

http://datenbank.welli-it.de/?spell=26104

Quellen:

http://www.wowhead.com/npc=15517/ouro#comments
Comment von sirfracas-Wallace/2006)
http://wowwiki.wikia.com/wiki/Ouro

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 2: Ouro Käfer funktionieren nicht richtig

Wie sollte es sein?
Jeder Käfer wählt sich ein zufälliges Ziel aus und sollte niemals das angewählte Ziel wechseln. (Spott und Aggro Immun) 

Wie ist es?
Erfolgreich ist auf jeden Fall, das alle Käfer nach 45 sec automatisch despawnen. Leider wählen sich die Käfer noch immer nicht ein selbstständiges zufälliges Target, sondern gehen nach der Aggro- Liste, verursacht durch Heiler etc. Auch Spott und Aggro sind weiterhin möglich, so das sie einfach von einem Tank zusammen gezogen werden können. (Auch dies sollte nicht funktionieren)

Quellen:

http://wowwiki.wikia.com/wiki/Ouro
http://datenbank.welli-it.de/?npc=15718#abilities
http://datenbank.welli-it.de/?spell=20477

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 3: Sandblast funktioniert nicht richtig

Wie sollte es sein?
Ouro sollte eine Fähigkeit mit dem Namen "Sandblast" einsetzen, die alle Spieler in einem 180 Grad Radius vor Ihm trifft, Ihnen 3,5 - 4,5k Naturschaden (binary) zufügt und Sie 5 sec lang betäubt. Zusätzlich verlieren alle Spieler die von Sand Blast getroffen werden, sämtliche Aggro. Während Ouro diese Fähigkeit zaubert, visiert er immer die Person mit der momentan höchsten Aggro an. Danach greift er die Person mit der höhsten Aggro in Meelerange wieder normal an. (Range 100/45 yards)

Wie ist es?
Die entsprechenden Spieler haben sämtliche Aggro verloren, das hat soweit gut funktioniert. Jedoch hat Ouro nie wirklich den Spieler mit der höhsten Aggro anvisiert, sondern lediglich die Tanks die vor ihm standen. Range DDs wurden dabei komplett ignoriert. (Beide Fälle sollten abgeändert werden, da der Boss sonst enorm einfach ist)

Fähigkeit:

http://datenbank.welli-it.de/?spell=26102

Quellen:

http://www.wowhead.com/npc=15517/ouro#comments
Comment von sirfracas-Wallace/2006)
http://wowwiki.wikia.com/wiki/Ouro

-------------------------------------------------------------------------------------------------------------------------------

<b>Bug/Fehler Nr. 4: Enragephase funktioniert nicht richtig

Wie sollte es sein?
Sobald das Leben von Ouro auf 20% ist oder darunter, geht er in die Enragephase. Dabei geht er nicht mehr in die Submergephase /Erdbebenphase, bleibt also permanent draußen. Zusätzlich spawnen nun alle 30 Sekunden 4 Käfer und 1 Erdbeben aus Ouro. Außerdem erhält er 150% mehr Angriffsgeschwindigkeit und 100% mehr Angriffsschaden für alle Nahkampfangriffe. Sobald sich kein Tank oder Meele mehr an Ouro befindet (Meelerange) fügt er einem weitentfernten Ziel ca. 6000 Schaden zu, solange bis wieder jemand in Meelerange steht. (Aggroliste wird abgearbeitet).

Wie ist es?
Leider hat Ouro gar nicht auf diese Phase reagiert. Das einzige was zu beobachten war, ist das er merklich schneller zugehauen hat (150% Attackspeed). Es fehlen somit 100% mehr Nahkampfschaden und das zusätzliche spawnen von Käfern und Erdbeben alle 30 Sekunden. Das Nutzen der Rangeattack mit ca. 6k Schaden konnten wir nicht beobachten, da jederzeit Meeles am Boss standen.

Fähigkeit:

http://datenbank.welli-it.de/?spell=26615
http://www.wowhead.com/spell=26616/boulder
http://www.wowhead.com/spell=26615/berserk

Quellen:

http://www.wowhead.com/npc=15517/ouro#comments
Comment von sirfracas-Wallace/2006)
http://wowwiki.wikia.com/wiki/Ouro

-------------------------------------------------------------------------------------------------------------------------------

Trotz dieser ganzen Fehler haben wir Ouro heute töten können. Wobei wir dazu sagen müssen, das der Encounter viel zu einfach dadurch war. 

Wir hoffen darauf das Ouro zu nächster Woche noch mal überarbeitet wird, damit er doch eine größere Herausforderung bietet.

Vielen Dank für die Bearbeitung und den Support!

Mit freundlichen Grüßen
Omega :-)

**Comment by Dotox** [comment]
Meldet euch bitte, wenn ihr ihn einmal mit dem Update 1.2.7 besiegt habt.
