### ISSUE TITLE
(Jäger)begleiter: Angriff versetzt Besitzer nicht in Kampf

### ISSUE THREAD

**Issue by Jessienia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1394]
Welches Verhalten wird beobachtet?
-Wenn man als Jäger sein Pet einen Gegner angreifen lässt, bleibt der Jäger weiterhin außerhalb des Kampfes.
-Wenn man sich als Jäger Totstellt, das Pet aber weiterhin einen Gegner angreift beibt der Jäger auch außerhalb des Kampfes.

Wie sollte es sich verhalten?
Jegliche aggressive Handlung eines Begleiters (z.B. Autohit auf einen Gegner) sollte seinen Besitzer in den Kampf versetzten. Auch nachdem sich der Jäger Totgestellt hat oder während er Totgestellt  ist, sollte er sofort wieder in den Kampf versetzt werden, wenn sein Begleiter weiterhin angreift. (ist das Pet passiv und wird nur von dem Gegner angegriffen, wird der Jäger allerdings nicht in den Kampfstatus gestzt).

Quellen:
Konnte bis jetzt leider keine genauen finden. Wäre schön wenn das jemand der zu Classic Zeiten intensiv einen Jäger gespielt hat, das ganze bestädigen oder sogar verifizieren kann.

Aus meiner Erinnerung weiß ich halt, dass man damals als Jäger sein pet immer erst zurückziehen musste, um z.b. in Instanzen während des Kampfes eine neue Eisfalle legen zu können.

**Comment by hmmkay** [comment]
Ohne Quelle gehört das ja kaum in den Bugtracker ;)

**Comment by Slimmer2** [comment]
Pets sollten auch den Char in Kampf versetzen.

**Comment by Ghulfang** [comment]
ich habs grade mal getestet und es funktioniert wie es sollte.

https://youtu.be/tcCSKLPh41I

**Comment by Jessienia** [comment]
Also bei mit sieht das ganze halt so aus. Pet greift munter den Gegner an und Jäger bleibt aus dem Kampf:
http://www.bilder-upload.eu/show.php?file=8f42ba-1453137194.jpg

**Comment by Schandmaul** [comment]
Is ein Bug und auch teilweise schon in #785 gemeldet.
