### ISSUE TITLE
Jägerbegleiter: Bewegungsunfähig nach Stun im Kampf

### ISSUE THREAD

**Issue by Jessienia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1395]
Welches Verhalten wird beobachtet?
Wird der Begleiter des Jägers im Kampf gestuned bewegt es sich anschließend nicht mehr, egal welche Befehle man ihm gibt. Auf passiv setzten, auf folgen setzten hilft alles nichts. Erst wenn das Pet den Kampf verlässt, bewegt es sich wieder normal.

Wie sollte es sich verhalten?
Sollte klar sein. Nachdem der Stun ausgelaufen ist sollte sich das Pet wieder ganz normal bewegen können.

Schritte zur Reproduzierung
Beispiel wäre der Mob Lavinius in Aszhara: http://datenbank.welli-it.de/?npc=14464#abilities
Stuned dieser das Jägerpet mit seinem <a href="http://datenbank.welli-it.de/?spell=6524">Ground Tremor</a>  , bewegt es sich anschließend nicht mehr. Kann seinen Gegner also auch nicht mehr angreifen, wenn dieser nicht in Schlagreichweite steht.

**Comment by Wosser** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1239
