### ISSUE TITLE
[Trinket] Talisman der Erhabenheit

### ISSUE THREAD

**Issue by aryanef** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1397]
Wie bereits der Titel besagt habe ich eine Frage zu folgendem Trinket: http://datenbank.welli-it.de/?item=22678
Wenn ich das richtig verstehe, dann stapelt sich der Effekt für jeden gewirkten Zauber (Schaden/Heilung) um x bzw y.
Wird dieses Trinket nun in Verbindung mit Chainheal http://datenbank.welli-it.de/?spell=1064 verwendet so frisst jeder Sprung der Heilung eine weitere Aufladung.
Mein Frage nun: Ist das korrekt? Und wenn ja warum bzw warum nicht? Nach welchen Patchnotes wird Chainheal hier berechnet? Springt er schon auf das Target über mit der geringsten HP in range? Wird jeder "Chainhealsprung" einzeln berechnet sprich auch ein potenzieller Crit neu ausgerollt?

Fakt ist momentan, dass 3 Aufladungen (bei vollem Treffer mit Kettenheilung) direkt hochstacken.
Das heißt:

- 1. Target wird mit CH(Grundheilwert 1) + addHeal +75 (trinket) geheilt 
- 2. Target wird mit CH(Grundheilwert 1 x0,5)+ addHeal +150 (trinket) geheilt
- 3. Target wird mit CH(Grundheilwert 2 x0,5)+ addHeal +225 (trinket) geheilt

Da die Mechanik ähnlich bzw. umgekehrt des ZG Trinkets ist sollte dieses Trinket nur 1 Aufladung dazugewinnen egal wieviele Ziele positiv (Heal) oder negativ (Schaden) von einem Zauber getroffen werden.
Gruß arya

**Comment by dagochen** [comment]
mach mal das @ heal weg! Sonst wundert sich die Person, warum sie hier verlinkt wird. Außerdem heißt es ADDHEAL :)

**Comment by uggeluggel** [comment]
http://wowwiki.wikia.com/wiki/Chain_Heal?oldid=362557 so funktioniert dein chainheal. 

Wie im Forum bereits geschrieben steht da nix von Zauber treffen sondern von Zauber wirken, also sollte ein Chainheal. genauso wie ein Frostblitz 1 Stack geben. Egal, ob 1 oder 10 Ziele getroffen werden.

**Comment by aryanef** [comment]
Chain Heal - After the initial target is healed, the healing effect will jump to the most damaged target (by absolute health) within range. In addition, if a raid member is the initial target it will look for valid raid targets to jump to rather than non-raid targets as a priority, making it consistent with group targeted Chain Heals.

Patchnotes 1.12.0 darum geht's mir bei der CH Funktion

**Comment by dagochen** [comment]
Eine Priorisierung nach erlittenem Schaden bzw. Raidmembers ist implementiert.

**Comment by aryanef** [comment]
Gibts nen Update von den Devs? Also wirds gefixxt oder nur mit "gültiger"Quelle?

**Comment by ircfelix** [comment]
Es gab bereits einen fix zum Herz von Hakkar/zg trinket, den vll. Raussuchen

**Comment by Zivou** [comment]
Also ich habe auch ein Problem mit dem Trinket, und zwar funktioniert es nicht richtig mit Schadenszauber vom Schattenpriester (Gedankenschinden und Schattenwort Schmerz). Der einzige Zauber, der das Trinket hochskaliert ist Gedankenschlag... Ich habe alles wie im Treat steht gemacht mit WDB-Ordner löschen und keine Addons. Funktioniert trotzdem nicht richtig. Mit allen anderen Zaubern (Holy Schadenszauber) funkioniert es richtig eben.

**Comment by aryanef** [comment]
Das mit dem Dot und auch Gedankenschinden stimmt so.
Das Trinket aktiviert/verbraucht lediglich eine Aufladung, wenn ein direkter Zauber gewirkt wird.
Das mit dem Zauberstab macht allerdings wirklich keinen Sinn :D

**Comment by ircfelix** [comment]
Eigentlich sollte es bei Gedankenschinden 1x hochstacken.

**Comment by aryanef** [comment]
Über die Funktion ob indirekte Heilungs- und Schadenszauber das Trinket triggern wurde im Link unten schon einmal diskutiert.
Als Quelle wurde u.a. die alte DB von wowwiki genannt:
http://wowwiki.wikia.com/wiki/Talisman_of_Ascendance?oldid=262041
Dort wird die Funktion und mögliche spielerische Taktik genannt.

In dem Bugreport von Vanilla Twinhead wird als Grundlage die Sprache verwendet:
- "Currently the Trinkets react like "land" rather than "cast [...]"  "
- "The trinket description specifies, "Cast" and not "heal/damage" basing it on [...]"

Was ggf. eine Hilfe darstellt ist der dort aufgeführte Vergleich mit dem ZG-Trinket. Zunächst die Problematik (auf unserem Server ZG#fixed ToA#unfixed):
- "On aoe spells such as Rain of Fire, Blizzard or Hellfire it triggers each time it deals damage, in other word's after dealing damage 5 times or to 5 targets with an aoe spell the buff is completely consumed."   Selbiges gilt für Heal.  Chainheal verbraucht beim ZhC EINE Aufladung unabhängig von der Anzahl der geheilten Ziele. ToA verbraucht PRO geheiltem Ziel eine Aufladung.

Hier ein relevanter Auszug der Patchnote 1.10:
- "The trinket will also now burn charges from each casting of a damage over time spell, heal over time spell, and area aura spells such as Blizzard and Consecration. Only one charge will be burned per area spell cast, rather than multiple charges per target hit as was previously the case."

Da die Core Funktion beider Trinket identisch ist sollte es klar sein, dass der Talisman buggy ist.
- "Talisman of Ascendance is a +damage/healing trinket comparable with Talisman of Ephemeral Power or Zandalarian Hero Charm."

Bzgl Mindflay: 
"By Brutus on 18.08.2015 (Content 1.4.0)
Mindflay doesnt trigger a charge aswell."  Frag wäre ist das ein Comment bzgl Bug oder eben nicht.

Die vollständige Diskussion kann unter folgendem Link eingesehen werden. 

https://vanilla-twinhead.twinstar.cz/?issue=2908#comments

Mfg

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md
