### ISSUE TITLE
Silberrute ersetzt nicht Kupferrute

### ISSUE THREAD

**Issue by JudasX** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1398]
Die Silberrute ersetzt nicht die Kupferrute.
Trotz dem angezeigtem Tooltip "Kann auch wie jede geringere runenverzierte Rute verwendet werden", kann die Silberrute nicht als solche eingesetzt werden.
Wenn ich eine niedrige Enchant ausführen möchte, muss ich zuerst die runenverzierte Kupferrute von der Bank holen.

Ähnlich mit items wie "Dient auch als Spitzhacke". Hier funktioniert ausschließlich die beim Händler erworbene gewöhnliche Spitzhacke.

**Comment by hraesvelgr** [comment]
kam erst mit bc. die gelben itemtexte auf dem server sind teilweise nicht korrekt. ist aber ein clientseitiges problem.
