### ISSUE TITLE
Lethon resettet willkürlich

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1399]
Der kleine grüne Drache Lethon hat heute leichte Probleme gehabt, im Kampf zu bleiben. Er ist mehrfach, bei verschiedenen Gilden und mehreren Trys, einfach resettet und wieder zu seiner Ausgangsposition zurückgelaufen. 

Einen Grund konnten wir nicht feststellen, wir vermuten aber es könnte etwas mit der Position und dem Wasser zu tun haben.

Hier der Videolink: http://www.twitch.tv/dagochen/v/34920738

**Comment by armaggedon1** [comment]
Bei Taerar im Dämemrwald heute dasselbe Problem. Der Boss hat sich mehrfach resettet, direkt nach Pull und auch mitten im Kampf (immer bei ca 50%). Ausserdem hat er immer wieder den Mt gekickt. Möglicherweise hängt das mit dem Outfight reggen der Heiler zusammen - Als wir einen Try ohne Regpausen gemacht haben hat es auch geklappt.

**Comment by dagochen** [comment]
Aktuell gibt es mehrere Tickets mit solchen Problemen, wo Bosse oder Gruppen resetten:
#1402 
#1401 

Gibt es da vielleicht ein übergeordnetes Problem?

**Comment by Sabbaer** [comment]
zwar anderes problem aber vll hängt das zusammen: die hitbox von weltendrachen ist "gigantisch".

**Comment by Larnak1** [comment]
Betrifft auch Ysondre und Emeriss, zumindest Berichten nach, die ich in den letzten Tagen gehört habe.

**Comment by dagochen** [comment]
Dieses Problem tritt weiterhin auf. Gestern bei Emeriss... :(

**Comment by armaggedon1** [comment]
Kann ich bestätigen, erst heute wieder bei Lethon passiert.
