### ISSUE TITLE
Schamane - Verlust der Waffenfertigkeit bei Beidhändigkeit

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#14]
Hallo,

bei der Klasse Schamane tritt folgender Bug auf:

Wenn der Charakter eine Verstärker-Skillung verlernt, um seine Talentpunkte neu zu setzen, verlernt er auch das Talent Beidhändigkeit - leider verlernt er aber auch die Waffenfertigkeit (300/300).

Dies wurde bereits im Patch 1.11.0 geändert:
"Two-Handed Axes/Maces (Enhancement Talent) - Skill levels gained with these two weapons will now be retained if you decide to unspend this talent point and return to it later."
Quelle: http://www.wowwiki.com/Patch_1.11

**Comment by ensanguined** [comment]
hallo wollte nur kurz fragen ob sich an dieser front was tut ?:)
