### ISSUE TITLE
AQ40 - Sartura: Aggroverlust beim spotten

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1400]
**Welches Verhalten wird beobachtet?**
Der Tank von Sartura verliert die Aggro, genau in dem Moment wo Spott verwendet wird. Sartura verwendet in diesem Augenblick keinen Wirbelwind.

**Wie sollte es sich verhalten?**
Für die Dauer des Debuffs sollte Sartura den Tank angreifen und der Tank sollte definitiv nicht die Aggro verlieren, sobald er Spott verwendet.

**Schritte zur Reproduzierung**
Dieses Verhalten ist mir bisher nur einmal aufgefallen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://youtu.be/sojnRr2kK1o
Sobald der Wirbelwind fertig ist, hat der Tank Hhodor Aggro. Etwa 3s später verwendet derselbe Tank Spott und in genau diesem Moment verliert der Tank die Aggro (besser zu erkennen in der Zeitlupe am Ende). Anschliessend hat ein Priester Aggro, welcher trotz Verblassen diese nicht mehr los wird.

**Links aus unserer Datenbank**
Sartura: http://datenbank.welli-it.de/?npc=15516
Spott: http://datenbank.welli-it.de/?spell=355
Verblassen: http://datenbank.welli-it.de/?spell=10942

**Comment by dagochen** [comment]
Ist bei uns ständig so. Tritt besonders dann auf, wenn mehrere Tanks spotten, als ob der funktionierende dann von den nachfolgendenen Spotts überschrieben wird.

**Comment by Troopilol** [comment]
könnte evtl. mit der fixate fähigkeit zusammenhängen das der Priester in dem video aggro hat.

Sartura and her adds will occasionally reset aggro for several seconds and start chasing random people for a duration of 5 seconds. After those 5 seconds they will return to the highest aggro target, so as long as you don't pull aggro off of the tank they will go back to him.(http://wowwiki.wikia.com/wiki/Battleguard_Sartura#toc)

**Comment by dagochen** [comment]
Ja aber Spott sollte das fixieren doch überschreiben oder nicht? War zumindest früher die Taktik, dass die Tanks Spott-Rota hatten und man parallel dazu gestunnt hat. Was davon nun tatsächlich zielführend war, kann ich aber auch nicht mehr sagen.

**Comment by Troopilol** [comment]
spott was wärend des fixate gewirkt wird sollte halt funktioeniren, spott das vorm fixate gewirkt wurde halt nicht.

**Comment by Dotox** [comment]
Noch aktuell? Es hab vor einigen Wochen ein Update, welches die Spott-Mechanik verbessert hat.

**Comment by xorann** [comment]
Das Problem wie hier beschrieben ist mir nur dieses eine Mal aufgefallen.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2373
