### ISSUE TITLE
AQ40 - Cthun heilt sich um ca. 30% in der ersten Phase

### ISSUE THREAD

**Issue by Derop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1402]
Was wird beobachtet:
Im Kampf gegen Cthun (Auge 1. Phase) kommt es bei jedem Try vor das er sich entweder um komplett 100% healt oder um 30%. Es befanden sich alle infight. Niemand war auf "entkommen" o.ä. Wir vermuten, es könnte an Totems liegen, welche diesen Bugg verursachen könnte.

Wie sollte es sein:

Der Encounter hat keine Heilfähigkeit. 
Videobeweis sollte nicht nötig sein, ansonsten organisier ich gern Videomaterial.

**Comment by Dotox** [comment]
Er heilt sich ja nicht mit einem Zauber sondern er resettet wohl an einer bestimmten Stelle bzw. wenn ein gewisses (noch unbekanntes) Szenario eintritt.

**Comment by Derop** [comment]
Davon geh ich auch aus. Ich weiß nicht wie es bei den Allianz Gilden ist, ob sie etwaige Probleme bestätigen können.

**Comment by Omegaexodus** [comment]
Ja bei uns waren die Probleme genauso vorhanden. Seit dem wir jedoch permanent mindestens einen Meele an Chtun lassen und kaum Leute sterben, resettet er auch nicht mehr wirklich. Jedenfalls war es bis jetzt bei den beiden Kills und (Trys) so das alles ordentlich läuft. Eines der beiden Ursachen könnte der Grund dafür sein, wobei wir eher davon ausgehen das es an den toten Spielern liegt.

**Comment by Karmanaz** [comment]
Auch wenn ich es noch nicht bestätigen kann, vermute ich das der Fehler auftritt, wenn ein nicht erreichbares Target z. B. hinter den Säulen oder auf den Treppen anvisiert wird. Ggf. sind sogar nur die Treppen durch die Höhenverschiebung das Problem.

**Comment by ircfelix** [comment]
Anorhin hatte das Problem heute auch. Wir konnten aber auch noch nicht feststellen woran es lag.

**Comment by Schnitzelkoenig** [comment]
Selbst nach dem Update kommt es immer noch vor, dass Cthun seine HP wieder hochschraubt.

**Comment by Dotox** [comment]
Liegt bestimmt daran, dass nichts in den Patchnotes steht :)

**Comment by Derop** [comment]
**Update -28.01.16***
Scheint bisher nicht mehr vorzukommen. Bei den letzen P1 Phasen hat er sich NICHT mehr geheilt.

**Comment by ircfelix** [comment]
@Derop: is bei euch in den p1 der letzten Kämpfe wer gestorben? Wäre cool wenn ihr n Video oder so hättet und auswerten könntet, denn dann könnte man tatsächlich einen Zusammenhang zwischen toten und dem resetten herstellen. 

Vermutung: Was hier grundsätzlich möglich wäre ist, dass cthun versucht tote Spieler ins target zu nehmen oder Spieler die ihren Geist freigelassen haben und er sich dadurch heilt.?!

**Comment by Baraz** [comment]
Unsere Vermutung ist, dass C'thun sich heilt, wenn ein von ihm mit dem grünen Laser anvisiertes Ziel außerhalb der Line of Sight steht (z.B. durch Klauententakel hinter eine Säule gekickt). Evtl. könnte man da nochmal prüfen.
