### ISSUE TITLE
AQ40: Hitbox von C'Thun

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1405]
Welches Verhalten wird beobachtet?
WIrbelwind vom Krieger trifft C'Thun nur wenn man fast so nahe an ihm dransteht, dass man weggekickt wird. Autohits und direkte Angriffe gehen auf eine deutlich größere Reichweite.

Wie sollte es sich verhalten?
Wenn Autohits ausgeführt werden sollten, dann sollte das Ziel auch nah genug sein um mit Wirbelwind zu treffen (Wirbelwind hat sogar eine höhere Reichweite von 8m).

Zusätzliche Informationen (Screenshots, Videos, etc.)
Problem wurde bereits in Update 31.12.2015 angegangen
http://community.mmobase.de/updates-changelog/8583-update-31-12-2015-a.html

Zusätzliches
Vermutlich wird dieses Problem auch andere AOE-Fähigkeiten betreffen.

**Comment by Horim** [comment]
Kann ich mich nur anschließen, trotz Melee-Range trifft der Wirbelwind nicht.

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1347

**Comment by Seniorash** [comment]
Update: Das Problem tritt nur in P1 auf (beim Auge von C'Thun) http://datenbank.welli-it.de/?npc=15589

Möglichweise wurde der Fix nur für C'Thun selbst in P2 vorgenommen.
