### ISSUE TITLE
[Trinket] Splitter des gefallenen Sterns

### ISSUE THREAD

**Issue by lysethea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1407]
Die Skalierung von Spelldamage ist beim o.g.Trinket ( http://datenbank.welli-it.de/?item=21891 ) nicht korrekt. Aktuell ist die Skalierung zu niedrig. 
Ich habe 411 Spelldamage und der Meteor macht lediglich 456 Schaden. 
Mit aktivem ZG Trinket ( http://datenbank.welli-it.de/?item=19950 ) was 204 Spelldamage zustätzlich gibt, ist der Schaden des Meteors bei 503 gewesen.

Es sollte zu 100% mit Spelldamage skalieren. Erst in BC wurde es gefixt, dass es gar nicht mehr mit Spelldamage skaliert. 

"Unless this was nerfed, it is 100% affected by spell damage. Best I can figure from what I've seen in videos, it runs roughly 70% coefficient. Note, however, the damage is dispersed amungst all targets. So, if it will deal 1000 damage to a single target, it will deal 500 each to 2 targets."
http://www.wowhead.com/item=21891/shard-of-the-fallen-star#comments

Hier in dem Video sieht man auch wie viel Schaden der Meteor macht. 
Ich habe in etwa das gleiche Gear wie der Pala aus dem Vid, lediglich 2 Items unterscheiden sich. 
Ab 3:26 in dem Duell sieht man es gut. Bei 3:34 ein Richturteil für 788 und hinterher der Meteor für 804 Dmg. 

https://www.youtube.com/watch?v=hoOVlOMErIg 

Bevor jemand kommt mit " das wurde 2011 hochgeladen " für den habe ich das hier : 
https://www.youtube.com/watch?v=cvWFOvGfbH8
Bitte dort einmal die Videobeschreibung lesen. :)

Grüße

**Comment by dagochen** [comment]
Aktuelle Skalierung ist Instant * AoE. Also 1,5/3,5/3 = 0,14 = 14%.
411 Spelldmg * 14% = 58 Bonusschaden + 400 Basisschaden = 458.
Das stimmt mit dem was du gemessen hast jedenfalls überein.
>Ich habe 411 Spelldamage und der Meteor macht lediglich 456 Schaden. 

---

>Hier in dem Video sieht man auch wie viel Schaden der Meteor macht. 
Ich habe in etwa das gleiche Gear wie der Pala aus dem Vid, lediglich 2 Items unterscheiden sich. 
Ab 3:26 in dem Duell sieht man es gut. Bei 3:34 ein Richturteil für 788 und hinterher der Meteor für 804 Dmg.

Der Meteor trifft für 475. Das ist ziemlich nah an dem, was bei dir kam. Aber kann natürlich sein das es der andere war....was mit den 70% hinkommen würde aus dem anderen Kommentar.

**Comment by ghostspirit85** [comment]
>Es sollte zu 100% mit Spelldamage skalieren. 
Nein, es sollte nicht zu 100% mit Spelldamage skalieren, sondern zu 70%. Wenn man dieser Quelle von 2007 (nach BC release) glauben schenken kann. Er sagt nur dass er sich zu 100% sicher ist, dass es skaliert. Allerdings zieht der Autor all sein Wissen aus dem selben Video dass du weiter unten ja auch selbst noch zwei mal verlinkt hast. Persönlich finde ich die Quelle also etwas schwach.

>Erst in BC wurde es gefixt, dass es gar nicht mehr mit Spelldamage skaliert. 
Heißt dass es in BC nicht skaliert hat? Dann müsste es ja einen Patchnote dazu geben. Bitte Verlinken!
Und wenn Du sagst "gefixt" meinst Du dann damit dass es vorher buggy war? Finde eigentlich nicht dass die Devs hier absichtlich Bugs reinpatchen sollten...

**Comment by dagochen** [comment]
Bestimmte Fehler müssen schon sein. Sowas wie "Angriffskraft gilt nicht als Fernkampfangriffskraft" wurde später ja auch gefixt, ist halt schon spielentscheidend.

**Comment by lysethea** [comment]
"Gefixt" war wohl das falsche Wort. Das Trinket wurde in BC generft. Die Skalierung wurde entfernt. Dazu habe ich nichts gefunden. Lediglich das sie bei der Sechsdämonentasche auch entfernt wurde. http://wow.gamepedia.com/Patch_2.2.0
Und die Tasche skaliert hier auf dem Server korrekt mit Spelldamage.

**Comment by Acolatronico** [comment]
die sechsdämonentasche ist auch ein instant trinket mit einem use effekt der damage macht welches auch zuerst zu niedrig skaliert ist, wurde ja bereits gepatcht , wie is den da die aktuelle % skalierung?

**Comment by dagochen** [comment]
Ja wird wohl so gewesen sein, dass bestimmte Items halt nicht wie normale Zauber skaliert haben. Anders sind die Werte im Video ja auch nicht zu erklären. Item das "zaubert" ungleich Spieler der zaubert.

**Comment by Acolatronico** [comment]
wo kann man einsehen mit wieviel % spell damage die 6demonentasche skaliert oder weiß das wer?

**Comment by dagochen** [comment]
Die Skalierung war/ist hier mal bei 0% gewesen, kann aber sein das es inzwischen geändert wurde.

**Comment by Acolatronico** [comment]
patchnotes 19.07.2015 Die Sechsdämonen-Tasche skaliert nun mit Zauberschaden
der splitter des gefallenden sterns sollte ähnlich btw genauso skalieren von %

**Comment by Slimmer2** [comment]
Patchnotes von 2015 ist wohl weit nach classic

**Comment by dagochen** [comment]
Patchnotes von unserem Server ja ;)

**Comment by Acolatronico** [comment]
ja weiß ich doch das es von unsererm server ist xD

**Comment by Acolatronico** [comment]
wird daran noch was geändert ? meine sechsdemonentasche macht 700-800er feuerbälle nach dem sie gefixt wurde und der meteor nur 500 ? in dem video von dernos macht er 800 und würde gleichstark sein wie das sechsdemonentaschen trinket

**Comment by Acolatronico** [comment]
https://www.youtube.com/watch?v=Pk_kHHI0t4o
0:43min->721, 1:26min->1167 crit, 1:36min->698, 2:54min->765, und der pala trägt im dem gear meele waffe, meele ringe im gegensatz zu dernos der full spell damage gear anhat, wie bereits oben geschrieben sollte die skalierung wohl genauso sein wie die sechsdemonentasche
