### ISSUE TITLE
Jäger Quest Stufe 10 Wildtier zähmen buggt

### ISSUE THREAD

**Issue by Schmerztoeter** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1408]
Hi.
Ich hab grade die Q bekommen um zu lernen ein Tier zu zähmen.
Das Problem ist, wenn man ein Tier gezähmt hat, komm ich nicht mehr aus dem Kampf raus. D.H. keine LP Regeneration nach dem zähmen. Auch das "Freigeben" des bezauberten Begleiters funktioniert leider nicht. Das führt dazu das man nicht ausloggen kann /weil im Kampf) und mit dem Tod wenn man die Anwendung beendet (ist aber nötig um weiterspielen zu können)
Passiert ist mir das mit einem Zwergen Jäger Stufe 10 (Grantl) in Kharhanos.
Ist zwar nicht kritisch, aber nervig :-), somit hab ich es mitgeteilt.
Grüßle

**Comment by Sabbaer** [comment]
mal den wdb ordner löschen

**Comment by Schmerztoeter** [comment]
Ich hab ne WDB Datei. Darin steht :"This prevents the WDB folder to be written nor created".
Aber ich wollt das nur melden. Bin mit der Q durch. Wie gesagt nicht kritisch. Von mir aus könnt ihr den Request auch schließen. Danke :-)

**Comment by Slipru** [comment]
Hattest du eventuell den Mistelzweig debuff? Dieser löst einen bug aus mit dem man nicht mehr aus dem Kampf kommt

**Comment by Schmerztoeter** [comment]
Ne. Auf dem Char war nur der Askpect des Falken. Mehr nicht.
