### ISSUE TITLE
Priesterfähigkeit: Krankheit aufheben funktioniert nicht richtig.

### ISSUE THREAD

**Issue by Jessienia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1409]
Welches Verhalten wird beobachtet?
- Wenn man versucht, als Priester den Zauber "Krankheit aufheben" auf ein Ziel zu wirken, welches nicht von einer Krankheit betroffen ist, kann das Zauber nicht ausgeführt werden und es erscheint die Fehlermeldung "Es gibt nichts zu bannen".
- Wenn der "Over Time" Effekt von Krankheit aufheben tickt, also bei 15,10,5 Sekunden und sich keine Krankheit auf dem Ziel befindet, verschwindet der "Hot" sofort und läuft nicht die vollen 20 Sekunden weiter.

Wie sollte es sich verhalten?
- Man sollte Krankheit aufheben auch auf jemanden casten können, der von keiner Krankheit betroffen ist. 
- Der Over Time Effekt sollte immer die vollen 20 Sekunden ticken. Unabhängig davon, ob das Ziel von einer Krankheit betroffen ist. Er sollte also nicht verschwinden, wenn der "hot" bei Sekunde 15.10 oder 5 versucht eine Krankheit zu entfernen, aber das Ziel nicht von einer Krankheit betroffen ist.

==> Genauso wie beim Vergiftung aufheben des Druiden. Das scheint richtig zu funktionieren.

Schritte zur Reproduzierung
Sich von den kranken Wölfe in den westlichen Pestländer schlagen lassen. Versucht Krankheit aufheben bei Sekunde 15 zu ticken, und der Wolf hat die Krankheit nicht auf das Ziel gecastet, läuft der Hot sofort aus. Wenn man mehere pullt, und diese dann die Krankheit rechtzeitig erneuern, tickt  Krankheit aufheben auch länger als 5 Sekunden.

Priest
http://datenbank.welli-it.de/?spell=552
(Druide)
http://datenbank.welli-it.de/?spell=2893

**Comment by dagochen** [comment]
#717 

Gleiches Problem.

**Comment by uggeluggel** [comment]
Da steht "attempt to cure..." und nicht wie beim normalen Dispell "Dispels magic..." weil eben keine Kranktheit bzw kein Gift auf dem Ziel sein muss.  

Es gab aber tatsächlich den Fehler, dass die Fehlermeldung beim Casten von Abolish Disease/ Poison ertönt, das ist erst mit BC entfernt worden.

http://wowwiki.wikia.com/wiki/Patch_2.1.2
Improved Mend Pet, Abolish Disease, and Abolish Poison no longer play sounds when there is nothing to dispel.

**Comment by dagochen** [comment]
@uggeluggel 
Wenn das also erst mit BC entfernt wurde, dass eine Fehlermeldung à la "there is nothing to dispel/cure", dann ist es doch bei uns aktuell korrekt oder?

**Comment by Slimmer2** [comment]
Kann aber auch heißen, der Zauber würde gewirkt und es kam der Sound immer bei einen Tick wo keine Krankheit drauf war

**Comment by Jessienia** [comment]
Ob jetzt eine Fehlermeldung ertönen sollte oder nicht sei mal dahingestellt. Darum  geht es in meinem Bugreport nicht. Sondern darum, dass Krankheit aufheben gar nicht gecastet werden kann bzw. frühzeitig abbricht.

**Comment by dagochen** [comment]
Beim Druiden ging das inzwischen schon meine ich jedenfalls...?

**Comment by Jessienia** [comment]
Zitat aus meinem Bugreport

"==> Genauso wie beim Vergiftung aufheben des Druiden. Das scheint richtig zu funktionieren."
