### ISSUE TITLE
zul farak treppenevent und damit vebundene quests

### ISSUE THREAD

**Issue by bobi12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1410]
hallo allesamt leider musste ich heute feststellen das in zul farak wohl das treppenevent rum bugt

und zwar kann man Oro Eyegouge und Murta Bauchgrimm erst gar nicht angreifen... die stehen einfach nur da werden aber als feindlich markiert

auserdem taucht der Goblin der dann die tür aufsprengt erst gar nicht auf

Unteroffizier Bly kann man zwar machen jedoch drop er nicht für die quest Wünschel-mato-Rute den gengenstand Wünschel-mato-Rute

ebenfalls bekommt man auch nicht Nekrums Medaillon für die quest Nekrums Medaillon von Nekrum der Ausweider der grund dürfte sein weil über 50% vom schaden die npcs verursachen auf den mob sprich die beute gehört denen

sehr schade da gerade die letze quest eine lange vorquest hat und auch noch 2 weitere quests hinter hat ich hoffe das hilft um gefixt zu werden wenn zeit ist :D

**Comment by dagochen** [comment]
Hat bei mir schon mal korrekt funktioniert. Ist aber etwas her. Beim letzten mal beim Levelevent ging die Wünschel-Mato-Rute wunderbar. Tor ist trotzdem nicht aufgesprengt worden.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage

**Comment by bobi12** [comment]
momrntchen warum is es den jetzt geschlossen das problem is ja trotzdem da?

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage

**Comment by Rushor** [comment]
@bobi12 beschreib den fehler in nem neuen ticket mir allen questids etc.

Leere oder lösche den WDB Ordner bevor du das Spiel startest
Starte das Spiel ohne Addons
Einige (Sammel)Quests können durch das Beenden und erneute Annehmen doch abgeschlossen werden
Schaue im Bugtracker nach, ob der Fehler nicht bereits gemeldet wurde
Nur ein Fehler pro Fehlermeldung
Sucht NPCs, Quests, Objekte, usw. in der Datenbank raus und verlinkt sie

Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

Zusätzliches

    Wir akzeptieren nur Quellen, die sich nachweislich auf classic wow beziehen
    Meldungen, die das geforderte Format nicht einhalten, können kommentarlos geschlossen werden
    Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!


Vielen Dank für deine Meldung!

**Comment by bobi12** [comment]
das macht mich jetzt etwas sauer den mein problem wurde anscheinend kaum gelesen und dieses problem habe nicht nur ich und es liegt weder anaddons noch an dem cache seit mir da echt net böse

das problem is das ganze treppenevent nr1 der goblin stirbt vor der tür und die tür sprengt sich dadurch net auf ergebnis aller spieler wir müssen rechts auf der wand hoch springen per wand bug um zum boss zu kommen in jedem einzelnen zf run

problem 2 die diversen npcs sind nur dann lootbar wenn alle sofort auf die besagten npcs für die quests gehen ohne das zuvor die npcs mit helfen beim kampf

problem 3 es bleiben immer 2 oder 3 von den npcs die helfen im kampf nicht angreifbar

warum sollte das was mit addons oder anderem dingen auf meinem rechner zu tun haben wenn das bei jedem spieler so ist und keiner kann mir erzehlen das ich dafür nachweisungen brauche das es in classic nicht so war?

ich wollte das schlieslich für alle die die quests machen wollen schreiben nicht etwa für mich alleine!

**Comment by Rushor** [comment]
trotzdem gibts ohne vernünftige quest/npc verlinkung zur datenbank keinen fix :)

je mehr infos zu lieferst, desto schneller kann es behoben werden

**Comment by bobi12** [comment]
sry aber ich denke ich hab den fehler exakt beschrieben es umfasst eben das ganze treppenevent bzw das verhalten der npcs die einen helfen wirds eben nicht gefixt und werden sich weitere drüber ärgern nur weil ich jetzt keine verlinkung von den zusammenhängenden quests usw mache wenns ohne hin das ganze event betrifft

**Comment by Rushor** [comment]
nö, ohne verlinkung kein fix. oder denkst du, dass die 2 devs die atm noch auf dem server tätig sind bock haben sich alle infos zusätzlich rauszusuchen? da muss schon guter support von den usern kommen
