### ISSUE TITLE
Deadmines Pein/Smite

### ISSUE THREAD

**Issue by Vitaga** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1411]
In der Todesmine pullt Pein/Smite (Der Taure vor dem Schiff) die erste Mobgruppe/Patroullie.

**Comment by dagochen** [comment]
Quelle? Wurde das nicht schon mal reported und abgelehnt, weil es richtig ist wie es ist? Irgendwas war da mal...

**Comment by Slimmer2** [comment]
Ja wurde bereits gemeldet

**Comment by Vitaga** [comment]
Richtig ist es, wenn man ihn oder die Verstohlenen Defias angreift, dass nur er runter kommt. Die Gruppe nicht.

**Comment by NoCutePuppy** [comment]
Korrekt war es wie folgt: 
 - 2 Unsichtbare am Fuß des Aufganges
 - Smite oben

Die unsichtbaren waren relativ schwer zu entdecken, konnten aber durch einen Schurken mit Kopfnuss betäubt werden. Beim Pull waren Smite und die beiden unsichtbaren im Kampf. Die Dreierguppe, die aktuell mitkommt war in Classic nicht in den Kampf involviert. Ob es eine Patroullie war, die versehentlich mitgepullt werden konnte, weis ich nicht mehr, aber im normalen Bosskampf waren definitiv nicht mehr als 3 Gegner: Smite und die 2 Unsichtbaren.

**Comment by NoCutePuppy** [comment]
Zur Untermauerung meiner Behauptung 2 Link zu Guides vor dem Jahr 2008.

2006: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/4397-deadmines-vc-guide.html

2008: http://wow-pro.com/book/export/html/578?dasya=true

In beiden Guides ist nur von 2 Begleitern die Rede. DM war eine Einstiegsinstanz, praktisch die erste für die Allianz. Ein Kampf 5 vs 6(Elite) war selbst für die (großartige, weil nicht Casual-Verwöhnend) Vanilla nicht gedacht.

**Comment by NoCutePuppy** [comment]
Und da der zweite Guide leider beim ersten Abgeschrieben worden ist hier ein Auszug aus einem anderen Guide (26.06.2005).
Auch hier werden nur 2 Begleiter genannt.

Vierter Boss: Mr. Smite
Mr. Smite ist der erste Boss, der nicht seinen Begleitern vorgezogen werden sollte. Sobald sich die beiden Schurken enttarnt haben, stürmt Mr. Smite auf die Gruppe zu und schon hat die Gruppe es mit 3 Gegnern, wenn nicht sogar mehr, zu tun. Bei diesem Gefecht ist es wichtig, sofort die beiden Schurken auszuschalten, denn sollte Mr. Smite einen Teil seiner Lebenspunkte eingebüßt haben, stunt er die gesamte Gruppe für ungefähr 10 Sekunden um sich eine stärkere Waffe zu holen. Dies passiert während des Gefechts 2-mal, unfähr bei 2/3 und 1/3 seiner Lebenspunkte. In der Zeit, in der die gesamte Gruppe gestunt ist, können die beiden Schurken, welche Mr. Smite zur Seite stehen, die gesamte Gruppe aufreiben, somit sollten diese getötet werden bevor sich die Gruppe auf Mr. Smite richtet. Mr. Smite ist ein Elite-Taure der Stufe 20 und ist ziemlich zäh. Sollten seine Begleiter rechtzeitig aus dem Weg geschafft worden sein, so ist das Gefecht schnell überstanden.

(Quelle: http://www.german-defrag.de/marc/wow/)

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1139

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/291
