### ISSUE TITLE
Darkshire - Friedhof Stille Gärten

### ISSUE THREAD

**Issue by Vitaga** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1412]
Der Skelettmagier hat die falsche Ausgabentabelle.
Sätze wie z.B.: "Die Bruderschaft wird eure Taten nicht tolerieren!".

**Comment by dagochen** [comment]
Und was soll ausgegeben werden!?

**Comment by uggeluggel** [comment]
Fehler melden
-Titel (Darkshire Skeleton Mage - Emote)
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?
(Die Skeleton Mages haben eine Emote (Blablabla)

Wie sollte es sich verhalten? 
(Die Skeleton Mages sollten gar keine Emote haben. Siehe http://wowwiki.wikia.com/wiki/Skeletal_Mage kein Emote im Talk oder in älteren Beiträgen aufgelistet.)

Schritte zur Reproduzierung
(Skeleton Mage angreifen)

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank 
( http://datenbank.welli-it.de/?npc=203 )

Entweder so oder gar nicht. Danke.

**Comment by ircfelix** [comment]
Mach nen vernünftigen bugreport, dann wird auch was gefixt. Einfach nur zu schreiben "bla geht nich repariert es" läuft hier nicht.

**Comment by uggeluggel** [comment]
warum mach ich mir die mühe die kacke da oben zu korrigieren wenns dann doch geschlossen wird?

**Comment by ircfelix** [comment]
Mach den Report einfach neu, ordne es systematisch (problem, wie es sein sollte, wie man das problem nachprüfen kann, quellen, links zu mobs/zaubern). Mit nem schönen bugreport sparst du den devs die recherchearbeit (meist der längste Teil des Reports) und es wird schneller gefixt.

**Comment by uggeluggel** [comment]
Hab ich doch schon. Hier in diesem Report. Aber es wird lieber geschlossen als gelesen.

**Comment by Dotox** [comment]
Mach einen neuen Report auf und hör auf hier rumzuheulen. So einen Müll wie der Ersteller hier abgeliefert hat, wird nicht berücksichtigt.

**Comment by uggeluggel** [comment]
Weisst du, Erni hatte Recht. Hättest du Interesse daran das zu fixxen würdest du einfach die Kommentare drunter lesen. Tust du nicht. So far - Ich bin auf Nostalrius.

**Comment by dagochen** [comment]
@Dotox 
Nur weil der Ursprungspost Mist ist, muss man aber doch nicht gleich die Leute, die sich die Mühe gemacht haben den fehlerhaften Bugreport zu korrigieren ans Bein pissen :(
