### ISSUE TITLE
Quest Krone der Erde 2x annehmbar

### ISSUE THREAD

**Issue by Vary1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1415]
Ich (Char Nialee, Level 9) kann bei Corithras Mondzorn auf Teldrassil die Quest Krone der Erde 2x annehmen. Steht auch 2x mit exakt dem gleichen Questtext drin und ich habe auch 2 zu füllende Amethystphiolen bekommen.
Eigentlich sollte die Quest nur einmal annehmbar sein.
Ob es mit anderen Charaktern reproduzierbar ist konnte ich leider nicht testen.
![bug](https://cloud.githubusercontent.com/assets/16765458/12401482/dd54acfa-be26-11e5-9a9f-ca30bc075cfc.png)

**Comment by Slimmer2** [comment]
Verlink mal die Quest

**Comment by Vary1** [comment]
http://datenbank.welli-it.de/?quest=934

**Comment by Slimmer2** [comment]
Die Questreihe hat an der Stelle 2 Folgequest.
Beendet man http://datenbank.welli-it.de/?quest=933/Krone der Erde hat man 1 Folgequest und eine 1 wird geöffnet und zwar http://datenbank.welli-it.de/?quest=7383
Deine verlinkte ist die Folgequest
