### ISSUE TITLE
Segen von Lordaeron

### ISSUE THREAD

**Issue by Soox1991** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1416]
Der Buff "Segen von Lordaeron" bewirkt das sich die Gesundheit in den Pestländern und in Scholomance/Stratholme um 5% erhöht. Wie ich eben bemerkt habe dauert der Effekt auch ausserhalb dieser Gebiete an.

**Comment by Slimmer2** [comment]
Spell verlinken

**Comment by dagochen** [comment]
http://datenbank.welli-it.de/?spell=31906
