### ISSUE TITLE
Maraudon 2 Quests funktionieren nicht

### ISSUE THREAD

**Issue by bobi12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1417]
hallo ich habe festgestellt das 2 quests und der questgeber für den stab in der instanz nicht funktionieren

zum einen die quest Die Anweisungen des Pariahs http://datenbank.welli-it.de/?quest=7067 in dem es darum geht die 5 Kahns Gelk, Kolk, Magra, Maraudos und Veng mit dem gegenstand Amulett der Vereinigung http://datenbank.welli-it.de/?item=17758 dazu zu zwingen das sie angreifbar werden um die edelsteine einzusammeln jedoch passiert beim benutzten des items leider nichts sie sind weiterhin grün... leider würde genau diese quest einen sehr guten schmuck geben Mal der Auserwählten http://datenbank.welli-it.de/?item=17774

dann die quest Das Szepter von Celebras http://datenbank.welli-it.de/?quest=7046 hierbei bekommt man den stab um den mitteleingang der ini nutzen zu können jedoch sobald man das ritual beim npc Celebras der Erlöste  http://datenbank.welli-it.de/?npc=13716 versucht zu beginnen spammt der den chat mit seiner ansprache nur voll wo er immer den selben text ca 3-4 mal pro sekunde raus wirft und es einfach nicht weiter geht weil es immer nur der erste text ist

soll ich die 5 kahns alle einzeln noch mal verlinken?

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/264
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1231

**Comment by bobi12** [comment]
naja ich habs zusammengefasst :D aber danke

**Comment by glorius7** [comment]
Hallo, Issue ist zwar Closed, das Problem besteht aber scheinbar leider noch immer. Wenn Zeit ist, würde mich sehr freuen wenn ihr das beheben könntet, die Questbelohnung die man da bekommen könnte ist wirklich super :)

lg glorius

**Comment by Slimmer2** [comment]
Wo steht das der Issud closed ist?

**Comment by glorius7** [comment]
Auf meinem Schirm, siehe Bild (vielleicht les ich das falsch. mein erster Post hier)

![untitled](https://cloud.githubusercontent.com/assets/22721301/19223494/aff32964-8e71-11e6-8ca8-7b41c8851155.jpg)

Ist auch egal wollte nur meinen Senf dazutun, weil ich die Questbelohnung wirklich gerne hätte =))

lg Glorius

**Comment by Slimmer2** [comment]
Ob der Bug Closed ist steht immer Oben.
Das eine Closed steht für den verlinkten Bug in den Beitrag von mir
