### ISSUE TITLE
Ruf bei Argentumdämmerung gg. Geißelsteine zu hoch

### ISSUE THREAD

**Issue by Kelturion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1418]
Es gibt sowohl beim Chillwindlager, wie auch bei der Kapelle in den östlichen Perstländern je einen NPC, welcher die 3 Dauerquests zur Abgabe von Geißelsteinen anbietet.

NPC im Chillwindlager: http://datenbank.welli-it.de/?npc=10840
mit den Quests:
http://datenbank.welli-it.de/?quest=5408
http://datenbank.welli-it.de/?quest=5407
http://datenbank.welli-it.de/?quest=5404

NPC bei der Kapelle: http://datenbank.welli-it.de/?quest=5510
mit den Quests:
http://datenbank.welli-it.de/?quest=5510
http://datenbank.welli-it.de/?quest=5509
http://datenbank.welli-it.de/?quest=5508

Der NPC bei der Kapelle gibt hier aber fälschlicherweise für die Dauerquests die doppelte Ruf-Menge. Während der NPC im Chillwindlager für jeder Quests korrekterweise 25 Ruf + 1 Marke abwirft, gibt es für die identische Quest bei der Kapelle hingegeng 50 Ruf + 1 Marke, was so nicht korrekt sein dürfte.

siehe auch hier: http://wow.gamona.de/archiv/reputation/die-argentumdaemmerung/ (Absatz Rufsteigerung durch Sammeln)

**Comment by aryanef** [comment]
Das ist lediglich 1 Quelle eindeutig zu wenig.
Des Weiteren sind soweit ich mich nicht komplett täusche die wiederholbaren Quests auf dem Server nicht möglich. Bevor die Repusteigerung rausgenommen wird, sollten das behoben werden.

**Comment by dagochen** [comment]
Das ein und die selbe Quest bei 2 verschiedenen NPCs unterschiedlich viel Ruf gibt ist wohl auch ohne Quelle eindeutig falsch.

**Comment by Slimmer2** [comment]
Quelle, wieviel Ruf sie tatsächlich geben sollte wäre gut.

**Comment by Truncsta** [comment]
Folgende Quelle habe ich noch gefunden. Websiteabbild ist vom 30.03.2007 (Leider gibt es keine Hinweise ob der Guide Post-TBC angepasst/erstellt wurde. Sollte jedoch passen, da die Rufanpassungen auch erst mit Patch 2.2.0 ( September 2007) eingefügt wurden.
https://web.archive.org/web/20070330024521/http://www.rpgguides.de/wow/artikel.php?aid=223
Hier heißt es wie folgt (Zusammengefasst)
Rufstufe Neutral - Respektvoll = 50 für die Abgabe sowie 50 für Benutzen einer Ehrenmarke
Rufstufe Respektvoll - Ehrfürchtig = 25 für die Abgabe sowie 25 für Benutzen einer Ehrenmarke
Ich hoffe der Link funktioniert so. Ansonsten über http://archive.org die Wayback Machine benutzen und folgenden Link eingeben: http://www.rpgguides.de/wow/artikel.php?aid=223
Gruß
Trunc
