### ISSUE TITLE
AQ40 Fankriss

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1419]
Welches Verhalten wird beobachtet?
Die Käfer adds die bei Fankriss spawnen sind auf dem Server Fear Immun.

Wie sollte es sich verhalten?
DIe Käfer sollten fearbar sein

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=vAZjrvK-4DM ab 0:40

**Comment by Ghulfang** [comment]
also ich seh da keinen gefearten wurm in dem video

**Comment by ircfelix** [comment]
Die Käfer oder die Würmer?

**Comment by Mafyo** [comment]
die Käfer

**Comment by ircfelix** [comment]
Sorry stimmt. Hätte ja auch einfach den Video aschaun könne.
