### ISSUE TITLE
Hexer Epic Mount Quest - schattenhafte Tränke können zeitweise nicht gekauft werden

### ISSUE THREAD

**Issue by JBurghaus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1420]
Nachdem man die Quest "Arkanit" angenommen hat, ist es nicht mehr möglich, mit dem NPC zu handeln und schattenhafte Tränke zu erwerben.

Wenn man den NPC anspricht, befindet sich dort nur noch das Fenster, mit dem man die Quest "Arkanit" abgegeben kann. Die Tränke, die man für die Quest "Lord Schattenfluch" benötigt,
kann man in diesem Zwischenstadium nicht erwerben - auch nicht wenn man die Quest abbricht und neu annimmt.
Erst wenn die Quest "Arkanit" abgeschlossen ist, kann man wieder mit dem NPC handeln. Ich weiß nicht, ob das ein Bug ist, jedenfalls lässt sich die Quest "Lord Schattenfluch" nicht beenden, solange die Quest "Arkanit" angenommen wurde und nicht abgeschlossen wurde und man vorher keine Tränke gekauft hat.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage
