### ISSUE TITLE
AQ40 -Cthun Loottable -Vermutung-

### ISSUE THREAD

**Issue by Derop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1421]
Cthun hat meiner Meinung nach einen verbuggten Loottable.

Vorfall: "Vermutung"
Jedes Item hat unterschiedlich geringe Dropchancen. Die [url]http://datenbank.welli-it.de/?item=21134[/url] z.B. hat glaube ich eine 100%tig Chance zu droppen. 3/3 Hordekills und sie war im Loot enthalten. Gut man müsste noch ein paar Wochen abwarten, um es wirklich bestätigen zu können. Es kann auch wirklich nur reiner Zufall sein. 

Eine Bitte nur an die anderen Gilden dies auch im Auge zu halten, da es damals in BWL ähnliche Vorfälle gab, wo einige Items gar nicht im Loottable enthalten waren.

Danke

**Comment by Derop** [comment]
Wie sah es bisher bei den Allianz Kills aus? Hab euren Loot nicht mitbekommen.

**Comment by ircfelix** [comment]
Vorschlag um das schnell zu testen: n gm cthun aufm live server paar zig male killen und den loot abchecken.

**Comment by Omegaexodus** [comment]
Eventuell ist dort wirklich was dran. Wir bei der Ally Seite von Solidcore hatten jetzt 3 mal hintereinander den Ring drin (Ring des Göttertöters). (http://datenbank.welli-it.de/?item=21596) 

Obwohl dieser auch nur eine durchschnittliche % Wahrscheinlichkeit hat. Natürlich kann das Ganze auch nur Zufall sein. Dennoch bitten wir darum, dort mal einen Blick darauf zu werfen und eventuell testen zu lassen.

Mfg Omega

**Comment by Slimmer2** [comment]
Die Devs können das viel leichter testen als die GM's.
Dev's können den Boss simuliert x mal killen.

**Comment by dagochen** [comment]
@Slimmer2 wie soll das gehen? Ich hab bei mir keine Funktion dafür gefunden...

**Comment by Slimmer2** [comment]
Hat doch Nightblizzard mal gepostet bei einen Boss, wo was mit der Loottable nicht gepasst hatte.
Weis aber nicht ob das im Forum oder im Bugtracker war

**Comment by dagochen** [comment]
aso dann haben die sich da selbst was geschrieben schätze ich, was bei mir net drin is :/

**Comment by g3n3a** [comment]
3 Kills ist nicht wirklich ne große Anzahl um da ne Aussage zu treffen.

**Comment by ircfelix** [comment]
Statistisch irrelevant.

**Comment by Seniorash** [comment]
Was spricht denn gegen eine Überprüfung? Wäre nicht der erste Lootable der nicht stimmt.

**Comment by ircfelix** [comment]
Man kanns gerne überprüfen, das schadet ja nicht. Aber von drei Kills pro Fraktion kann man rein statistisch halt keine gewichtige Aussage treffen, da es halt einfach nur ein blöder Zufall sein kann.

**Comment by dagochen** [comment]
Jo und genau deshalb soll ein GM sich 1 Minute hinsetzen und CThun 10x töten. Dann haben wir Gewissheit.
