### ISSUE TITLE
Feign Death funktioniert bei manchen Bossen nicht

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1424]
Welches Verhalten wird beobachtet?
Feign  Death funktioniert bei manchen Bossen nicht. Speziell ist es mir bei Onyxia und Razorgore aufgefallen: Wenn sich der Hunter totstellt, wird er nicht aus dem Kampf genommen.

Wie sollte es sich verhalten?
Der Hunter sollte bei allen Mobs aus dem Kampf genommen werden - jedenfalls für kurze Zeit - sofern er keinen Schaden erleidet und nicht sofort wieder in den Kampf kommen. Somit sollte zum Beipsiel möglichsein bei oben genannten Bossen einen Wipe zu überleben.
(Falls bestimmt Kommentare kommen: Nein es wurde nicht resistet, denn meine Aggro wurde im KTM auf 0 gesetzt und das besagte Problem tritt jedes mal auf.)

Schritte zur Reproduzierung
Boss gegenübertreten und totstellen.

Zusätzliche Informationen 
- Using feign death exits the hunter from combat, allowing for such things as eating, mounting, or other activities not possible while in combat. (http://wowwiki.wikia.com/wiki/Feign_Death)
- dort sind keine Ausnahmen für bestimmt Bossfights angeführt

**Comment by dagochen** [comment]
KTM reagiert einfach nur drauf, dem ist es egal ob du einem einzelnen kleinen Drachen oder sonst was resistest. Das würde KTM auch korrekt anzeigen, wenn FD korrekt im Kampflog angezeigt werden würde, wenn es einem bestimmten Mob resistet. Ist ähnliches Problem wie bei Finte, Ducken #1315

**Comment by hmmkay** [comment]
und was solldas jetzt bedeuten? etwa, dass FD von den beiden Bossen zu 100% resistet wird?

**Comment by SirBeansen** [comment]
Wie kann man bitte in P2 bei razor wipen? Und in p1 muss du allen 40 Orks+12 Drachen + Boss erfolgreich Totstellen was schon sehr unwahrscheinlich ist...aber so oder so killt dich dann der razor overkill.

Aber man kann bei ony + Razor in p1 und p2 outfight kommen mit FD. Schon mehrmals geschaft.

**Comment by Haudraufinix** [comment]
Im zweifelsfall einfach SV skillen, dann gehts sogar zu 90% ;)

**Comment by hmmkay** [comment]
Bei Ony ist nur 1 Mob im Raum. Magst du mri das bitte auch mal ausrechnen;) ? Danke!

Ne zeitlang ging das bei Ony auch, Beansen. Aber mittlerweile geht es nicht mehr. Ich denke mal, dass besagte Encounter die Spieler aktiv bzw. den ganzen Raum dauerhaft in Combat zwingen und es deshalb nicht mehr funktioniert.

**Comment by Haudraufinix** [comment]
*hust* drölf Millionen Dracheneier, die zwar noch nicht ausgeschloffen sind aber zusammen mit dem Boss in den Kampf einsteigen. Damit sie bei Spawn auch tatsächlich auf Spieler losgehen....

**Comment by SirBeansen** [comment]
Die resist chance gegen lvl 63 (Boss lvl) ist hier glaub ich auf 17%. Also so save ist totstellen halt nicht =)

**Comment by dagochen** [comment]
Bevor jemand meint es wäre falsch:
> Die resist chance gegen lvl 63 (Boss lvl) ist hier korrekterweise auf 17%. Also so save ist totstellen halt nicht =)

fyp

**Comment by hmmkay** [comment]
Anderes Beispiel: Firemaw.
Hinter der Mauer also oos hatte ich schon 2 mal (2 RaidIDs) 100% resist auf Totstellen. Das könnt ihr mir nicht erzählen, dass das normal ist....

**Comment by Haudraufinix** [comment]
Geh damit zu RTL

Was sein kann ist wenn du noch Geschosse im Flug hast, einen Dot aufm Mob oder dein Pet am leben ist, dass eines dieser drei Dinge verhindert, dass du aus dem Kampf kommst. Ausserdem besitzt Firemaw wenns mir recht ist Resistenzen - Totstellen ist ein Zauber und kann auch Widerstanden werden(!)

**Comment by hmmkay** [comment]
Keine Geschosse, keine Dots und das pet ist auch oos. LoS hat gerade bei dem Boss sehrwohl einen Einfluss, sogar einen sehr großen! Denn man bekommt durch seine Aura Schaden. Aber die kann nur ticken, wenn man LoS steht. In diversen Guides nachzulesen ;).

**Comment by Haudraufinix** [comment]
Das pet ist aber im Kampf - das Pet bringt dich aber auf unserem Server selbst immer wieder in den Kampf selbst wenn es OOS  ist! - du machst selbst nen Bugreport dazu und das fällt dir nicht auf?

**Comment by hmmkay** [comment]
Nein, das Pet bringt einen, wenn überhaupt nur im PvE in den Kampf, wenn man es aktiv im Kampf nutzt. Passiv sollte es einen auch im PvE nicht infight bringen...
