### ISSUE TITLE
Feign Death lässt Arcane Geschosse nicht abbrechen

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1425]
Welches Verhalten wird beobachtet?
Feign Death lässt Arcane Geschosse nicht abbrechen.

Wie sollte es sich verhalten?
Feign Death sollte jeglcihe Casts abbrechen.

Schritte zur Reproduzierung
Einen Mage Arcane Geschosse auf einen Hunter zaubern lassen und totstellen.

Zusätzliche Informationen 
For PvP encounters, this will cause enemies to drop you as a target. For spellcasters, this means they will have to start casting again...  (http://wowwiki.wikia.com/wiki/Feign_Death)

**Comment by Schandmaul** [comment]
Bei der Gelegenheit am besten nochmal einen Blick auf #655 und #785 werden. Zwei Bugs die seit Jahren bestehen und den Jäger - insbesondere im Pvp - unverhältnismäßig stark machen.

**Comment by booneyclassic** [comment]
Als Zusatz:

Die Strahlen von den kleinen Augententakeln bei C´thun (http://datenbank.welli-it.de/?npc=15726), welche diese Art von Gedankenschinden wirken, können durch das Totstellen auch nicht abgewendet werden.

**Comment by Haudraufinix** [comment]
For PvP encounters, this will cause enemies to drop you as a target. For spellcasters, this means they will have to start casting again... (http://wowwiki.wikia.com/wiki/Feign_Death)

bezeichnet nix zu der Funktionsweise im classic PvE sondern nur PvP, also da denk ich müssten mehr Quellen zu her.

**Comment by dagochen** [comment]
Spellcasters = pve/pvp
pvp encounters = pvp only

**Comment by SirBeansen** [comment]
@Schandmaul  #785 ist schon geändert worden und auch live und #1394 gibt es keine qullen zu. "Aus meiner erinnerung" ist keine Quelle

**Comment by Ilikegyoza** [comment]
#1394 ist völliger Blödsinn. Sollte das zutreffen, dürfte man auch zugedottet nicht nach 6 sekunden outfight kommen.

**Comment by hmmkay** [comment]
/like Ilikegyoza :D
Danke Dotox fürs schnelle Umsetzen! Werde es zeitnah testen.

**Comment by Dotox** [comment]
Kommt erst mit dem nächsten Update, also teste es erst, wenn hier "Auf Nefarian" steht :)
