### ISSUE TITLE
(AQ40) twin emporers

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1427]
Welches Verhalten wird beobachtet?
Emperor Vek'nilash ist entwaffnungsfähig

Wie sollte es sich verhalten?
Emperor Vek'nilash darf nicht entwaffnungsfähig sein

Schritte zur Reproduzierung
Emperor Vek'nilash entwaffnen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Twin_Emperors?oldid=372618
unten wird explizit erwähnt, was man machen kann um den encounter zu legen:

Demoralizing Shout is your greatest friend in this fight. As with other bosses such as Broodlord Lashlayer, attack power calculations are given significant weighting when used with certain strikes (ie. Broodlord's Mortal Strike, Vek'nilash's Unbalancing Strike). However, when using Demo Shout, you need to be careful not to aggro additional neutral bugs. As with other debuffs, a tank is able to demo shout before the emperors port, and the debuff will stay on after the port.
bei anderen encountern wie z.B. general drakkisath uvm. steht explizit in den guides, dass der encounter entwaffnet werden kann.

Links aus unserer Datenbank
http://datenbank.welli-it.de/?npc=15276
http://datenbank.welli-it.de/?npc=15275

**Comment by Haudraufinix** [comment]
Das nicht vorhanden sein einer Information heisst nicht zwangsläufig, dass das gegenteil der Fall ist

**Comment by ChichiWarrior** [comment]
Du kannst hier auf dem Server hunderte Mobs entwaffnen. Hat aber keine Auswikrung, außer das ein Debuff Slot mehr belegt ist :-)

Gruß

Chichi

**Comment by SirBeansen** [comment]
Also das entwaffnen im pve nen unterschied macht ist mir auch noch nie aufgefallen. Besonders weil der Boss ja nicht vom attackspeed der waffe oder vom schaden der waffe berechnet wird sondern ein "festen" wert hat. 

Aber ich glaub wenn man den Twin disarmt kann er nicht mehr den Unbalancing Strike machen.

**Comment by ircfelix** [comment]
Schließe mich Haudraufnixs Meinung an.

**Comment by Garlesh** [comment]
Nur weil du keine Quelle findest, dass man die Twins entwaffnen kann, heißt es nicht, dass man sie nicht entwaffnen kann. Wenn jeder so argumentieren würde..
Den Unbalancing Strike macht er sowieso auch ohne Waffe und ich glaube nichtmal, dass das entwaffnen was bringt.

**Comment by Dotox** [comment]
Entwaffnen bringt bei Raidbossen nichts
