### ISSUE TITLE
Quest Levenanforderung verbuggt

### ISSUE THREAD

**Issue by Ayrill** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1428]
Hallo!

nach meinem ersten Ticket wurde mir gesagt ich soll angeben nach welcher Datenbank ich weiß das die Quest ab level 18 annehmbar ist.

Hier die Feenix 1.12.1 Datenbank: https://www.wow-one.com/database/index.php?search=Raene%27s+Cleansing

Die Questreihe gibt bei der Endquest eine Level 19 Twink Waffe.

>updated by hraesvelgr:
questreihe: http://datenbank.welli-it.de/?search=raenes#quests:0+3+1+2
hier (http://datenbank.welli-it.de/?search=raenes#quests:0+2+3+1) sieht man auch gut, wie die questreihe in chronologischer reihenfolge erst zwischen mindestlevel 18 und 20 hin und herspringt, und dann immer höherstufiger wird. das mindestlevel sollte immer 18 bleiben. 

Die Levelanforderung ist hier leider verbuggt bzw. passt nicht ganz.

Ich würde euch bitten das ihr die Levelanforderung korrigiert, damit ich die Twink Waffe bekommen kann.

Vielen Dank!

MfG

**Comment by Sabbaer** [comment]
-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank
bitte an die vorgabe halten, welche quest, bitte quellen angeben, der feenix server ist keine quelle, du musst quellen aus der zeit von vanilla angeben, bei feenix stimmt aucch extrem viel nicht

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/item=5815/glacial-stone#comments

http://wowwiki.wikia.com/wiki/Glacial_Stone

beide quellen reden von level 19 twinkwaffen

@Ayrill schäm dich, so eine schandseite wie feenix zu posten :P

**Comment by Ayrill** [comment]
Danke fürs ganze verlinken und berichtigen :P war mein erster Post hier gestern :D 
Da das ganze ziemlich schnell geschlossen wurde, habe ich Glück das die Quest berichtigt wurde? Oder ist es einfach unwichtig gewesen und wurde daher geschlossen? ^^ bin leider erst Abends on das ich Ingame nachsehen kann :)

**Comment by hraesvelgr** [comment]
ääääh...ob dotox mich da evtl falsch verstanden hat?^^ ayrill hat schon recht. hier eine weitere  quelle von 2006, die bestätigt, dass die quest, und damit das item auf level 19 verfügbar war:

>I've already commented on this on the official forums so I'll just paste it in here. My post was in response to an Alliance character. If you're making a Horde character you won't be able to use a Glacial Stone, so go with Smite's Mighty Hammer. You also won't be able to use Chausses of Westfall or Beetle Clasps so replace with BoE greens. And you can't get the special ammo pouch / quiver (minor point). Accordingly, Horde warriors are significantly less powerful than Alliance warriors. Kind of unfair but that's the way it is. And Horde have Earthbind. Replace "Wrynn" with "Silvanas." 

http://wow.allakhazam.com/forum.html?forum=243&mid=1148303395196043608

**Comment by Ayrill** [comment]
Hm okay da der Beitrag immer wieder geschlossen wird ohne einen Kommentar wie "wird per Hotfix geändert.." gehe ich davon aus das es nicht gefixt wird.. ^^ 

trotzdem Danke hraesvelgr :)

**Comment by hraesvelgr** [comment]
verstehs auch nicht so ganz o.o

**Comment by Ayrill** [comment]
So :) Habe Dotox direkt geschrieben und wie gewünscht einen Bugreport erstellt nach der Vorlage und verwende keine Links oder Quellen von anderen privaten Server.

Alles Editiert mit seriösen Quellen :) sollte nun also passen um bearbeitet zu werden :D
