### ISSUE TITLE
Krieger - Weitreichende Stöße

### ISSUE THREAD

**Issue by StompBug** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1429]
***EDIT 2:*** SIEHE UNTEN 7. COMMENT

***EDIT 1:*** Gerade den Bug Report hier gefunden: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/909

"http://wowwiki.wikia.com/Patch_1.10.0

Whirlwind - When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack."

Laut diesen Patchnotes sollte das wohl tatsächlich nicht auf Wirbelwind öfter als einmal proccen,
aber beim Skill "Spalten" sollte das dann nicht gelten wenns da nicht erwähnt wird. Ich habs zwar anders in Erinnerung, werde aber mal weiter nach Videos suchen. Es ist nur ziemlich ätzend weils quasi nur PvP Videos gibt und da der Fall ganz selten ist.
***EDIT 1 ENDE***

_

Der Skill "Weitreichende Stöße" vom Krieger funktioniert nicht korrekt, was den AoE-DMG-Output der MS Warris sowohl im PvE als auch im PvP stark einschränkt. Bei einzelnen Mobs irrelevant.
Nach stundenlangen Videos durchschauen die letzten 2 Tage, habe ich endlich die passenden Videos gefunden die die richtige Funtkion des Skills wiedergeben.

ÜBRIGENS: Der Skill hat auf dem Server hier, vor ca. 1-2 Jahren, sehr lange richtig funktioniert.
Wieso sich das geändert hat konnte ich nicht finden. (siehe EDIT)
Es hat sich vor 2 Jahren nur mal der Bug eingeschlichen das Weitrechene Stöße bei Haltungswechsel wieder verschwand.

*WS = Weitreichende Stöße

Welches Verhalten wird beobachtet?
Bei Spalten oder Wirbelwind, wird nur ein weiterer Angriff von WS ausgelöst.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Spalten/Wirbelwind getroffen und kriegen jeweils einmal Dmg. WS wird ausgelöst und nur der Dmg von A wird auf B übertragen.
Insgesamt 3 Hits. 1 Hit ausgelöst durch WS.

Wie sollte es sich verhalten?
Bei Spalten oder Wirbelwind, sollten beide Mobs den Schaden des jeweils anderen durch WS bekommen.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Spalten/Wirbelwind getroffen und kriegen jeweils einmal Dmg. WS wird ausgelöst und Mob A kriegt den Schaden von Mob B, Mob B kriegt den Schaden von Mob A. 
Insgesamt 4 Hits. 2 Hits ausgelöst durch WS.

Schritte zur Reproduzierung
WS aktivieren und Wirbelwind/Spalten benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.):
Dazu die Videos, Video Reihenfolge entsprechend was am aussagekräftigsten ist:

Video 1:
https://www.youtube.com/watch?v=TGEE42Gvv2c
0:08 WS wird aktiviert, rechtsoben in der Buffleiste 5 Stacks
0:20 Wirbelwind wird benutzt, Buffleiste 3 Stacks, 2 Wirbelwind Hits und 2 weitere von WS.

Video 2:
https://www.youtube.com/watch?v=IZNUYSsnAVI
0:06 WS wird aktiviert, Stacks sieht man leider nicht wegen der schlechten Qualität
0:12 Spalten wird benutzt, 2 Spalten Hits und 2 weitere von WS.

Wie bereits geschrieben:
Der Skill hat auf dem Server hier, vor ca. 1-2 Jahren, sehr lange richtig funktioniert.
Vielleicht kann man aus den alten Scripts auf die schnelle was wiederherstellen.

Gruß
Stomp/Saro

**Comment by testear** [comment]
Laber keine Scheiße.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/909

**Comment by Sabbaer** [comment]
1video nostalrius, nicht legit
2video tbc
keine quellen...

**Comment by StompBug** [comment]
Hat aber nicht lange gedauert bis du geantwortet hast ;)
Dann sag mir mal bei welchem Patch der weitere Hit bei Spalten hinzugefügt wurde, wenn das Video aus tbc Zeiten keine Quelle ist. Schließlich muss es ja dann irgendwann eingefügt worden sein.

**Comment by hmmkay** [comment]
Funktioniert doch korrekt hier: sweeping strikes an + Wirbelwind => Jeder Mob bekommt 2x Dmg.

**Comment by testear** [comment]
hmmkay wenn das so ist, dann funktioniert es nicht korrekt. Habe vor ca 1 Jahr den oben verlinkten bugreport geschrieben. 
DIeser Report hier bezieht sich nur aufs Spalten, wobei es fragwürdig ist da ein Video aus BC  bzw eins von Nostalrius als Beweis zu nehmen.

**Comment by hmmkay** [comment]
@testear Zitat:"
Wie sollte es sich verhalten?
Bei Spalten oder Wirbelwind, sollten beide Mobs den Schaden des jeweils anderen durch WS bekommen.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Spalten/Wirbelwind getroffen und kriegen jeweils einmal Dmg. WS wird ausgelöst und Mob A kriegt den Schaden von Mob B, Mob B kriegt den Schaden von Mob A.
Insgesamt 4 Hits. 2 Hits ausgelöst durch WS."

a) "bei.... Wirbelwind" er bezieht sich also doch auf Wirbelwind
b) "Insgesamt 4 Hits. 2 Hits ausgelöst durch WS." genau so - we du es unter "Wie soll es sein" geschrieben hast - ist es doch gerade

**Comment by testear** [comment]
Ich kann lesen, du scheinbar nicht. Lies erstmal den Edit der über dem Report steht bevor du deine Gülle hier verbreitest.

**Comment by StompBug** [comment]
@hmmkay  Nein funktioniert nicht, ich habs mehrfach getestet, hast dus selber ausprobiert?

@testear  Du hast recht das der Nostalrius Server nicht aussagekräftig ist aber das BC Video dient für mich schon als Quelle weil in den gesamten BC Patchnotes keine Änderung diesbezüglich für Sweeping Strikes + Spalten erwähnt wird und in den von dir geposteten Patchnotes wurde nur Wirbelwind gefixt.

Aber ich hab ein weiteres Video gefunden wo Wirbelwind und Spalten benutzt wird.

Video 3:
https://www.youtube.com/watch?v=0j0cVu8h5yQ

3:41 Sweeping Strikes
3:49 Wirbelwind - Ich meine man sieht nur 3 Hits, könnte vllt. korrekt sein wie hier aber (siehe unten)
3:55 Spalten - Er hat vor dem Spalten 57 Wut, danach 37 Wut. Womit man ausschließen kann das er einen weiteren Style als Spalten macht. 
Bei 3:56 ploppen 4 Gelbe Zahlen auf, Gegner A: "670" / "714" Gegner B "654" / "665".

Nächste Szene, selbes Video:

5:52 Sweeping Strikes
Jetzt zieht er sich 3 Mobs zusammen und wartet auf genug Wut...
5:58 Wirbelwind - auf 5:59 stoppen. Laut Wutanzeige sinkt der Wutbalken von 36 auf 11 Wut, also hier nur Wirbelwind benutzt.
Vielleicht funktioniert Wirbelwind bei 3 Mobs anders wie bei 2.
Warum? Wenn man bei 5:59 stoppt dann sieht man dass das anvisierte Target wieder nur 1 Schadenszahl über dem Kopf bekommt, in dem Fall hier "Dodge". Die beiden Mobs rechts von ihm kriegen wieder jeweils 2 Schadenszahlen.
Gegner A: "Dodge" Gegner B: "677" / "876" Gegner C: "577" / "667".
Wie gesagt von 5:58 bis 5:59 Play und Stop spammen, geht alles ziemlich schnell.

Spalten:
Für mich ist das Spalten eindeutig. Weil es weder Patchnotes gibt die das Gegenteil dazu beweisen, und nur explizit Wirbelwind verändert wurde (in welche Richtung, kA siehe unten was aus den Videos ersichtlich war) und weil es im Video eigentlich klar zu sehen ist.

Wirbelwind:
Wirbelwind verhält sich bei 2 Mobs anders wie bei 3 Mobs. 
Aus den Patchnotes ist das nicht erklärbar.
Bei 2 Mobs gibt es insgesamt 3 Hits, das anvisierte bekommt nur den Wirbelwindhit ab.
Bei 3 Mobs gibt es insgesamt 5 Hits, das anvisierte bekommt wieder nur den Wirbelwindhit ab.
Es wurde ja sonst keine weitere Fähigkeit benutzt laut Wutbalken. Vielleicht soll der Wirbelwindhit vom weiteren Mob das anvisierte nicht zurückhitten. Nur ne Vermutung.
Bei Wirbelwind will ich mich auch nicht festlegen das es auf unserem Server falsch ist.

Und verwendet bitte ebenso Quellen um mir das Gegenbeispiel zu zeigen... ich opfere jetzt schon einige Stunden und Tage in Videos suchen, anschauen und wieder in die Tonne schmeißen weil nichts brauchbares da ist und da sind Zweizeiler wenig konstruktiv.

Stomp/Saro

**Comment by testear** [comment]
Ich hab damals den Bugreport geschrieben. Ich habe es nicht nötig mehr Quellen anzugeben als die Patchnotes von 1.10.0. WW funktioniert richtig, das ist alles was ich sagen will. Und in den Reports die ich zu Sweepings geschrieben habe steckt selber Arbeit. 

Spalten ist mir echt egal, das hat im PvP wenig bis keinen Einfluss.

**Comment by testear** [comment]
Sinnvoll wäre es jetzt einen neuen Report zu öffnen in dem nur die Sweeping Strikes Cleave Mechanik behandelt wird. Hier hat kein Dev mehr den Überblick.

**Comment by mukibozz** [comment]
Sweeping Strikes funktionieren leider nicht ganz korrekt im Moment.

Derzeit verursachen Weitreichende Stöße+Spalten bei (2) Gegnern mit jedem Spalten (3) Angriffe.
Das Sekundäre Ziel (nicht im Target) wird von Spalten als auch von weitreichenden Stößen getroffen.
Das primäre Ziel wird nur  von Spalten getroffen.
Pro Spalten geht (1) Aufladung des Weitreichende Stöße-Buff verloren.

Soll-Zustand: 
Weitreichende Stöße+Spalten verursacht bei (2) Gegnern mit jedem Spalten (4) Angriffe.
Pro Gegner jeweils 1xSpalten+1xWeitreichende Stöße. Hierbei gehen (2) Aufladungen von dem Buff verloren.
"Stacks with Cleave, causing four attacks on two enemies every swing, each with a standard critical chance. "
Wowwiki-Eintrag vom 03.11.2006 (http://wowwiki.wikia.com/wiki/Sweeping_Strikes?oldid=308938)

Außerdem können weitreichende Stöße derzeit verfehlen, parriert/geblock/ausgewichen werden. Hierbei gehen sogar aufladungen verloren selbst wenn kein Schaden verursacht wird. 
Dabei sollte nur eine Aufladung verbraucht werden, wenn das Hauptziel+ein weiteres Ziel getroffen werden, wobei das weitere Ziel dem Angriff nicht ausweichen/parrieren/blocken kann. Außerdem sollten weitreichende Stöße nicht verfehlen können. (was aktuell der fall auf nefarian ist) 
"It is worth noting that SS cannot miss, be dodged, parried nor blocked, but as of patch 1.11 can crit."
Sweeping Strikes -Guide vom 17.09.2006 (https://hilbert.wordpress.com/sweeping-strikes-guide/)

**Comment by mukibozz** [comment]
"Whirlwind - When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack." 
Aus den Patchnotes von 1.10 wurde leider falsch verstanden.

Vor diesem Patch konnte Wirbelwind auch vom sekundären Ziel (gegner der neben dem eigentlichen Ziel steht) sweeping strikes auf des Hauptziel auslösen. (Siehe Video von Pat, Maydie). 
Das heißt dass bei zwei Gegnern mit einem Wirbelwind insgesamt (3) Angriffe auf das Hauptziel und (2) Angriffe auf das sekundäre Ziel ausgeführt wurden. Also (2) zusätzliche Hits auf das Hauptziel mit nur einem Wirbelwind. (1) zustäzlicher Angriff auf das Nebenziel. Dabei haben weitreichende Stöße bei zwei nebeneinander stehenden Gegnern also (3) zustäzliche Angriffe auf zwei gegner ausgelöst und auch (3) Aufladungen wurden dabei verbraucht. 

Nach dem Patch konnte Wirbelwind vom sekundären Ziel aus (gegner der neben dem eigentlichen Ziel steht) keine sweeping strikes mehr auf das hauptziel auslösen. Stattdessen wurden insgesamt nur noch (2) Angriffe auf das Hauptziel und (2) Angriffe auf das sekundäre Ziel ausgeführt. Wenn es kein Nebenziel gab hat Sweeping Strikes auch bei einem Ziel trotzdem (2) Angriffe ausgeführt. 1x wirbelwind + 1x weitreichende Stöße.
Genauso wie Weitreichende Stöße+Spalten bei zwei zielen (4) Angriffe ausführen sollte, sollten Weitreichende+Wirbelwind bei zwei Zielen auch (4) Angriffe auslösen und nicht nur (3) oder (2) wie es aktuell auf nefarian ist.

**Comment by testear** [comment]
Die Dritte Aussage wäre zwar noch zu beweisen und widerspricht sich selber. 

Nach dem Patch konnte Wirbelwind vom sekundären Ziel aus (gegner der neben dem eigentlichen Ziel steht) keine sweeping strikes mehr auf das hauptziel auslösen. Stattdessen wurden insgesamt nur noch (2) Angriffe auf das Hauptziel und (2) Angriffe auf das sekundäre Ziel ausgeführt.

**Comment by StompBug** [comment]
Das gehört doch alles in einem, es geht hier um Sweeping Strikes, ich finde wir sollten das nicht aufdröseln weil das noch chaotischer wird, wo die Diskussion dann in 3 Threads unmöglich ist.
Wenn genug zusammengetragen wurde kann man ein neuen sauberen Thread erstellen oder den ersten Post hier bearbeiten, mit allen berechtigten und richtigen Quellen selbstverständlich.

Der Wiki Eintrag ist wohl was Spalten angeht die ziemlich beste Quelle bisher.

**Comment by testear** [comment]
"EDIT 2: SIEHE UNTEN 7. COMMENT"

ähem. Das ist schon ziemlich chaotisch hier. 
Btw sinds 3 Probleme zu einer Fähigkeit. 
Meiner Erfahrung nach buddeln sich die Devs nicht durch jeden Kommentar durch um jeden Bug zu fixxen. Entweder du ordnest den ersten Report richtig mit 3 Kategorien oder du erstelles neue Reports.

**Comment by StompBug** [comment]
@Dotox 
Bedeutet der Close das du einen neuen Thread willst in bereinigter Form oder das der Bug aufgenommen wurde und bearbeitet wird?
