### ISSUE TITLE
(Trinket) Talisman der Überlegenheit bei Shadowpriest

### ISSUE THREAD

**Issue by Zivou** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1431]
Also ich habe bemerkt, dass das Trinket nicht mit Gedankenschinden und Schattenwort Schmerz hochskalliert... Im Tolltip steht jeder Zauber der Schaden verursacht...Bitte beheben! Es hat sehr lange gedaurt bis ich das Teil hatte und will es nicht einfach auf der Bank rumliegen haben.

Gruß
Zivou

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker siehe Vorlage
