### ISSUE TITLE
die quest morbent teufel

### ISSUE THREAD

**Issue by chaoticus1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1432]
der npc der quest "morbent fell" selbst sollte einen schild haben wodurch er immun wird. in der quest bekommt man passend zum schild ein item, dass dieses entfernt. der npc ist jedoch direkt angreifbar wodurch das questitem nutzlos wird.
außerdem kommt es vor, dass wenn man ihn aus dem haus zieht. dass er anfängt durch die luft zu fliegen oder direkt resettet und zurück an seinen spawn-punkt rennt.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker - siehe Vorlage
