### ISSUE TITLE
Schurke - Tödliches Gift

### ISSUE THREAD

**Issue by godlike321** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1433]
Was wird beobachtet ?

Tödliches Gift (getestet mit Rang 5) wird bei einem erfolgreichen Proc sofort wieder aus der Debuff-Leiste gedrückt.
Damit ist es nicht möglich dieses Gift im PvE anzuwenden da sämtliche anderen Debuffs, zumindest augenscheinlich, höher priorisiert sind.
Zum getesteten Zeitpunkt hatte ich das Gift auf beiden Waffen und definitiv genügend Procs.
Das Problem war aber dass das Gift schon nach 1-2 Sekunden sofort wieder aus der Debuff-Leiste verschwindet und gar nicht gestacked werden kann

Wie sollte es sich verhalten ?

Tödliches Gift sollte zumindest die gleiche Priorität haben wie andere DMG-Debuffs damit es durch erneute Procs immer aufrecht erhalten werden kann.

Quelle : https://www.youtube.com/watch?v=mZ1j4N8MYao   <- Hier sieht man recht gut wie der Debuff gestacked und aufrecht erhalten werden kann.

Bei Bedarf kann ich auch ein Video uploaden wie es sich hier bei uns verhält.

Vielen Dank und Happy Fixing :D 

gruß Godlike

**Comment by Slimmer2** [comment]
Denke nicht das dies geändert wird.
Es gibt wichtigere debuff, die mehr sinn machen.
Classic hat auch nur 16debuffslots zur Verfügung

**Comment by testear** [comment]
In dem Video hat man nur eine Tiefe Wunde auf dem Boss. Tiefe Wunde verdrängt tödliches Gift. Da hier jeder DDKrieger Tiefe Wunde skillt hast du keine Chance dein Gift aufrecht zu erhalten.

**Comment by Sabbaer** [comment]
^das ist kein bug...

**Comment by dagochen** [comment]
Doch ist es. Gibt aktuell für das neue Tödliche Gift keinen Prio-Eintrag (die habe ich damals vergessen, weil es das Gift damals noch nicht gab!). Sorry @ Rogues!

Fix:
```sql

INSERT INTO `spell_priority` (`spell_ID`, `priority`, `spellname`, `effect_description`)
VALUES ('25349', '36', 'Schurke - Tödliches Gift V', 'Dot');

```

**Comment by Slimmer2** [comment]
https://docs.google.com/spreadsheets/d/1LaSl-EGHhZr-NsDxPBdQqGhQuwSXvMtP6KLuF_vmyCI/edit#gid=1581221275

**Comment by dagochen** [comment]
Ja, mit der Ausnahme das jeder Rang einzeln drin stehen muss.

**Comment by Slimmer2** [comment]
Das andere Problem ist dann, das ein Höherer Zauber Aktiv ist wenn 1 Schurke Rang 4 und der andere nur Rang 3 hat

**Comment by dagochen** [comment]
Das wiederum hat aber nix mit meinem Prio-System zu tun ;) Aber das hat Dotox ja bis heute auch bei Schlangenbiss und co nicht gefixt, bzw. den Bugreport dazu von mir einfach geschlossen....

**Comment by testear** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1331

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1434

selbes Thema. Einmal geschlossen. einmal bearbeitet. Manchmal handelt Dotox etwas willkürlich.

**Comment by godlike321** [comment]
Danke Dago erstmal dafür, ich selbst kenne mich damit nicht gut genug aus um mich gegenüber den ganzen Kommentaren hier zu behaupten.

Aber Hauptsache Sabbaer hat wieder was sachliches beigetragen, ein Augenschmaus und danke auch dafür Sabb ;)

**Comment by Sabbaer** [comment]
der debuff wird jedesmal vom mob runtergeschmissen, wenn die 16 slots voll sind und etwas mit gleicher oder höherer prio auf den mob kommt. du wirst es eh nie stacken können solange bei bossen die 16 slots voll werden. mag sein das es so nicht richtig implementiert ist, solange du aber allen aus deinem raid nicht beibringen kannst den 16ten slot für dein stack gift freizulassen wirst du es nicht auf den mob bekommen...... richtig wichtig sowas zu fixen, was man eh nie im raid benutzen kann. Aber schön weiter spelldmg abuse bei den giften betreiben (bugabuse) https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/630

**Comment by dagochen** [comment]
@Sabbaer 
Es ist aber schon ein wichtiger Unterschied, ob das Gift überhaupt eine Prio hat oder garkeine. Wenn es die gleiche Prio wie andere Dots hat, dann kann es mit diesen um einen Debuffslot konkurieren, weil es die gleich stark priorisiert wird. Hat es hingegen keinen Eintrag in der DB, wird es selbst von Gedankensicht runtergeworfen :D

**Comment by Slimmer2** [comment]
Im Raid macht man eh Sofortwirkendes Gift drauf, wegen den Debuffslots.

**Comment by godlike321** [comment]
Leute, ich bin ja kein Depp, ich habe in P1 auf Cthun den Debuffslot frei und würde ihn gern nutzen ;)
Ich bin mir über die Gifte, ihre Skalierungen und Anwendungsweise im klaren, danke erstmal dafür.
Wieso ist es Spelldmg-Abuse wenn ich Tödliches Gift Rang 5 nutzen will ?

Ich bin nicht fullraiddmgflasced500critautohit wie unser sabb :D
Cthun Titan > all dude.

**Comment by testear** [comment]
Dir fehlen die Fähigkeitenlinks. So kannst du lange auf nen Fix warten.
