### ISSUE TITLE
Quest "Der leuchtende Splitter" sowie Folgequest "Alptraum" kann nicht von Allianz angenommen werden.

### ISSUE THREAD

**Issue by Ayrill** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1435]
Hallo,

habe folgendes Problem mit einer Quest.

Edit: hatte fälschlicherweise die Folgequest verlinkt nun richtiggestellt.

Welches Verhalten wird beobachtet?
Die Quest "[Der leuchtende Splitter](http://datenbank.welli-it.de/?quest=6981)" kann nicht angenommen werden(als Ally obwohl die Quest für beide Fraktionen ist) und die Levelanforderung für die Folgequest "[Alptraum](http://datenbank.welli-it.de/?item=10657)" stimmt nicht.

Wie sollte es sich verhalten?
Quest sollte mit dem Questitem starten und die Folgequest sollte bei [Falla Weisenwind](http://datenbank.welli-it.de/?npc=8418) ab Level 15 anzunehmen sein.
Abzugeben ist die Quest dann bei [Mathrengyl Bärenfährte](http://datenbank.welli-it.de/?npc=4217) in Darnassus.

Schritte zur Reproduzierung:
Starte die Quest mit einem Level 15+ Charakter durch das Questitem "[Leuchtender Splitter](http://datenbank.welli-it.de/?item=10441#starts)" aus HDW (Gedropt von [Mutanus der Verschlinger](http://datenbank.welli-it.de/?npc=3654) versuche die Quest anzunehmen und bekomme die Meldung "Diese Quest ist für Ihr Volk nicht verfügbar."
Die Folgequest kann in weiterer Folge auch nicht angenommen werden da die Levelanforderung nicht stimmt. 

Zusätzliche Informationen (Screenshots, Videos, etc.):
[WoWHead Quest](http://www.wowhead.com/quest=3370/in-nightmares)
[WoWHead Kommentare aus 2006-2007](http://de.wowhead.com/item=10657/talbarmantel#english-comments)
[WoWWiki Eintrag](http://wowwiki.wikia.com/wiki/Talbar_Mantle) : besagt folgendes "Talbar Mantle is a shoulderpad notable for being a desirable twink item for nearly any class in the level 19-bracket, as very few shoulder pieces are available to characters this low."

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1181

**Comment by Ayrill** [comment]
also die eig. Quest mit dem Questitem geht als Ally garnicht annehmen. Da kommt direkt die Fehlermeldung das sie nicht für das Volk/Fraktion verfügbar ist obwohl sie für beide Seiten eig. gehen muss.. :/ und die Folgequest sollt auch mit Level 15 annehmbar sein ist aber hier am Server warum auch immer ab lvl 23 annehmbar :)

**Comment by hraesvelgr** [comment]
habs mal im originalpost geupdatet, mit richtiger quelle. kleiner tipp beim suchen: 
bei google kansnt du oben, unter der suchleiste "erweiterte suchoptionen" auswählen, dort hast du die möglichkeit eine zeitspanne einzustellen. anfangsdatum freilassen, und enddatum auf 2006 stellen, schon bekomsmt du alle einträge bis 2006. und damit eine wesentlich höhere garantie, sinnvolle quellen., die noch nicht durch patches verändert wurden, zu bekommen.
andere alternative ist die website "wayback-machine"

**Comment by Ayrill** [comment]
geht klar merke ich mir falls ich noch einen Bug finden sollte :) ich würde mich schon freuen wenn die Quest hier berichtigt wird und vl mein zweiter Bugreport (#1428) auch wieder geöffnet wird :)
wie lang denkst du wird es dauern bis die Quests gefixt werden? Dein Post ist ja doch auch schon 3 Monate alt :/

**Comment by hraesvelgr** [comment]
rechne mal mit sofort bis nie
