### ISSUE TITLE
Undercity Wachen & Wegbeschreibungen

### ISSUE THREAD

**Issue by ChaosmikeNefarian** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1441]
die wachen in undercity schicken einen auf die ewige suche wenn man zum beispiel nach dem bergbaulehrer fragt wird man zum kürschnerlehrer geschickt :)

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker siehe Vorlage
