### ISSUE TITLE
Felspirscher fälschlicherweise Elite

### ISSUE THREAD

**Issue by MaddinF** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1442]
die Felspirscher Spinnen (npc=11739) in Silithus sind als Elite markiert und machen dementsprechend auch mehr Schaden (300-450)

Kurzübersicht
    Stufe: 57 - 59
    Einstufung: Normal
    Einstellung: A H
    Fraktion: Beast - Spider
    Gesundheit: 3,753 - 4,204
    Schaden: 100 - 132
    Rüstung: 3,408

![wowscrnshot_012916_231055](https://cloud.githubusercontent.com/assets/16637480/12689792/5ea6c1d8-c6df-11e5-9090-3231703c0d2e.jpg)

**Comment by Dotox** [comment]
Bitte Vorlage benutzen und Quelle angeben.

**Comment by MaddinF** [comment]
Welches Verhalten wird beobachtet?
- Felspirscher Spinne ist Elite

Wie sollte es sich verhalten?
- Felspirscher Spinne sollte Normal sein

Zusätzliche Informationen (Screenshots, Videos, etc.)
- siehe erster Post

Links aus unserer Datenbank (hier gehts zur Datenbank)
- http://datenbank.classic-wow.org/?npc=11739

**Comment by Slimmer2** [comment]
Quelle wie es sein sollte fehlt

**Comment by MaddinF** [comment]
Ich habe keine Ahnung, woher ich die Quelle nehmen soll, wie es sein sollte.

Ich hätte damit gerechnet, dass der Link auf den NPC reicht.
Da stehen ja auch Daten, wie Stufe, Einstellung, Schaden usw.

Wenn ihr mir erklärt wie ich die Quelle finde, reich ich es nach.

**Comment by hraesvelgr** [comment]
es geht darum, dass du uns beweist, dass es zu classic wirklich so war. und momentan gibt es bereits andere reports, die definitiv beweisen,d ass diese spinnen elite waren, zu classic zeiten. 

quellen können sein: alte wowhead-comments bis patch 1.12.1 (in besonderen fällen auch 2.0.4)
wowwiki einträge, sowie diskussionen über besagte einträge
alte forenbeiträge bis ca sommer 2007
videos bis 2007

das ganze findest du bequem über die angeüassten suchoptionen bei google

**Comment by MaddinF** [comment]
Aha ok, dann weiß ich bescheid.
Mir kam das nur etwas spanisch vor, weil sie in der Datenbank auch als Normal angegeben werden.
In manchen Foren hab ich aber nun gefunden, dass sie auch Elite sind, von daher war es etwas verwirrend. :D 

Dann sry für die Unannämlichkeiten und ich weiß fürs nächste mal Bescheid :)
