### ISSUE TITLE
Krieger - Weitreichende Stöße / Spalten

### ISSUE THREAD

**Issue by StompBug** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1443]
Nachdem Bugfix nach diesem Bugreport vor etwa einem halben Jahr: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/909 überarbeitet wurde, funktioniert Sweeping Strikes mit Spalten nichtmehr richtig.

Aus der Diskussion hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1429
Nochmal ein Bug Report mit allen Quellen zusammengefasst:

*WS = Weitreichende Stöße

Welches Verhalten wird beobachtet?
Beim benutzen der Fähigkeit "Spalten" wird nur ein weiterer Angriff von WS ausgelöst.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Spalten getroffen und kriegen jeweils einmal Dmg von Spalten. WS wird ausgelöst und nur der Dmg von A wird auf B übertragen.
Insgesamt 3 Hits. 1 Hit ausgelöst durch WS.

Wie sollte es sich verhalten?
Beim benutzen der Fähigkeit "Spalten" sollten beide Mobs den Schaden des jeweils anderen durch WS bekommen.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Spalten getroffen und kriegen jeweils einmal Dmg. WS wird ausgelöst und Mob A kriegt den Schaden von Mob B, Mob B kriegt den Schaden von Mob A.
Insgesamt 4 Hits. 2 Hits ausgelöst durch WS.

Schritte zur Reproduzierung
WS aktivieren und Spalten benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.):

Video:
https://www.youtube.com/watch?v=0j0cVu8h5yQ

3:41 Sweeping Strikes
3:55 Spalten - Er hat vor dem Spalten 57 Wut, danach 37 Wut. Womit man ausschließen kann das er einen weiteren Style als Spalten macht.
Bei 3:56 ploppen 4 Gelbe Zahlen auf, Gegner A: "670" / "714" Gegner B "654" / "665".

Dazu noch ein Auszug aus dem wowwiki zum Skill in Verbindung mit Spalten, gepostet im alten Bug Report (https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1429) von mukibozz:

"Stacks with Cleave, causing four attacks on two enemies every swing, each with a standard critical chance. "

Wowwiki-Eintrag vom 03.11.2006 (http://wowwiki.wikia.com/wiki/Sweeping_Strikes?oldid=308938)

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by StompBug** [comment]
Sorry aber ich verstehe dein Verweis auf die ReadMe Datei nicht.
Welche Anforderung daraus ist nicht erfüllt?
