### ISSUE TITLE
Krieger - Weitreichende Stöße / Wirbelwind

### ISSUE THREAD

**Issue by StompBug** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1444]
Nachdem Bugfix nach diesem Bugreport vor etwa einem halben Jahr: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/909 überarbeitet wurde, funktioniert Sweeping Strikes mit Spalten nichtmehr richtig.

Aus der Diskussion hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1429
Nochmal ein Bug Report mit allen Quellen zusammengefasst:

*WS = Weitreichende Stöße

Welches Verhalten wird beobachtet?
Beim benutzen der Fähigkeit "Wirbelwind" wird nur ein weiterer Angriff von WS ausgelöst.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Wirbelwind getroffen und kriegen jeweils einmal Dmg von Wirbelwind. WS wird ausgelöst und nur der Dmg von A wird auf B übertragen.
Insgesamt 3 Hits. 1 Hit ausgelöst durch WS.

Wie sollte es sich verhalten?
Beim benutzen der Fähigkeit "Wirbelwind" sollten beide Mobs den Schaden des jeweils anderen durch WS bekommen.
Beispiel, 2 Mobs: WS wird aktiviert. Mob A und B werden mit Wirbelwind getroffen und kriegen jeweils einmal Dmg. WS wird ausgelöst und Mob A kriegt den Schaden von Mob B, Mob B kriegt den Schaden von Mob A.
Insgesamt 4 Hits. 2 Hits ausgelöst durch WS.

Schritte zur Reproduzierung
WS aktivieren und Wirbelwind benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.):

Video:
https://www.youtube.com/watch?v=0j0cVu8h5yQ

5:52 Sweeping Strikes
Jetzt zieht er sich 3 Mobs zusammen und wartet auf genug Wut...
5:58 Wirbelwind - auf 5:59 stoppen. Laut Wutanzeige sinkt der Wutbalken von 36 auf 11 Wut, also hier nur Wirbelwind benutzt.
Das anvisierte Target erhält ein Damage in dem Fall "Dodged" der Gegner. Die beiden Mobs rechts von ihm kriegen jeweils 2 Schadenszahlen.
Gegner A: "Dodge" Gegner B: "677" / "876" Gegner C: "577" / "667". 3 Mobs, 5 Hits.
Von 5:58 bis 5:59 Play und Stop klicken da dass etwas schnell geht im Video.

**Comment by testear** [comment]
http://www.warcraftmovies.com/movieview.php?id=9199

4:23 3 Gegner, WW + SW= 6 Schläge. Sommer 2005. Das Video von Drakkus ist vor 1.10.0 gemacht worden.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker
