### ISSUE TITLE
Weitreichende Stöße verfehlen/ vermeiden

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1445]
Wie sollte es sich verhalten?
Weitreichende Stöße sollten verfehlen und parieren, blocken oder ausweichen nicht zulassen dürfen.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://datenbank.welli-it.de/?spell=12292 

"It is worth noting that SS cannot miss, be dodged, parried nor blocked, but as of patch 1.11 can crit."
Sweeping Strikes -Guide vom 17.09.2006 (https://hilbert.wordpress.com/sweeping-strikes-guide/)

http://wowwiki.wikia.com/wiki/Patch_1.11.0_

Sweeping Strikes: This spell has a number of fixes: When used in conjunction with Execute and the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage; If the ability you are using does not deal damage, it will not use a charge of Sweeping Strikes; The extra attack it generates when used with Whirlwind now has the correct damage range; The additional attacks generated by this ability will now properly take into account the armor of the second target.

Ty mukibozz

Anhang für andere zum Testen bei Interesse (KEIN TEIL DES REPORTS):

Wenn allerdings eine Fähigkeit zusammen mit Weitreichenden Stößen gewirkt wird und keinen Schaden verursacht (parieren oder ausweichen) sollten Weitreichende Stöße weder Schaden verursachen noch eine Aufladung verbrauchen. .
Der execute Teil funktioniert. Der Teil mit dem Aufladungen verlieren hat als ich noch aktiv war glaube ich nicht funktioniert.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by testear** [comment]
*checked*

**Comment by Kraftprotz** [comment]
haallooooo

**Comment by Kraftprotz** [comment]
bump

**Comment by Kraftprotz** [comment]
push

**Comment by Daimudda** [comment]
PUSH
