### ISSUE TITLE
aq40 Bugtrio

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1446]
Lord Kri

Istzustand:

Lord Kri http://datenbank.classic-wow.org/?npc=15511 verschießt viel zu oft den Toxic Volley http://datenbank.classic-wow.org/?spell=25812. Zurzeit ist es so das er ca. alle 2-3 Sek den Volley verschießt und er jede 2 Sec tickt. Ist nicht gegenzuheilen! Außerdem kann der Volley nicht mehr Resisted bzw Teilresisted werden.

Sollzustand:

Lord Kri sollte alle 10 sec seinen Volley abschießen, und den dot der alle 2 sec für bis zu 150 tickt sollte ebenso Teilresisted werden und dispelled werden können. Außerdem sollte LoS bei dem Volley funktionieren.

Zur Replikation:
Boss pullen und einfach ne zeit lang zuschauen.

Princess Yauj

Istzustand:

Princess Yauj http://datenbank.classic-wow.org/?npc=15543 castet Great Heal 2 Sec casttime http://datenbank.classic-wow.org/?spell=25807 ist zurzeit nicht Kickbar.

Sollzustand:

Der Great Heal sollte Kickbar sein, sowie mit Effekten wie Fluch der Sprachen die Castzeit erhöhen.

Zur Replikation:
Boss pullen und ihn versuchen zu kicken.

Beweiße:
https://www.youtube.com/watch?v=TBds2lpSSQk
http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-2.htm

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1377
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1361
