### ISSUE TITLE
aq40 Viscidus

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1447]
Istzustand:

Viscidus http://datenbank.classic-wow.org/?npc=15299#abilities verschießt seinen Poison Bolt Volley http://datenbank.classic-wow.org/?spell=25991. Der Volley ist nicht Resistbar.

Sollzustand:

Der Poison Bolt Volley sollte mit bisschen Naturresi Teilresistbar sein.

Reproduktion:
Boss pullen mit NR

Quelle:
https://www.youtube.com/watch?v=Kc8yIFZjV6s
http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-5.htm

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1377
