### ISSUE TITLE
stratholme: der herdsinger 

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#145]
der neutrale npc herdsinger forresten (http://datenbank.welli-it.de/?npc=10558#abilities) ist zwar ein rarmob, sollte jedoch in jeder id anwesend sein, nur eben an einem von 4 verschiedenen spawnpunkten, welcher zufällig ausgewählt wird
karte seiner möglichen spawnpunkte: 
http://www.wowhead.com/maps?data=2017:858289599285845446647242

(edit: spell enchanting lullaby nutzt er korrekt. )

>redback on 2008/04/09 (Patch 2.4.1)
He is up every time, but he has a large number of spawn points.

>By Blafflamm (201 – 2) on 2014/05/05 (Patch 5.4.7)		
Warning, don't make the same mistake i did. Did not read the comments and assumed that Hearthsinger Forresten was a rare spawn like any other!
Forresten IS in the instance every run but spawns at different locations, i learned this the hard way and only checked the area where he is marked on the map from beyond the gate that closes with the rats and thus not noticing the other spots he might be at. Anyhow, the hearthsinger is usually fairly close to the marked spot on the map.

**Comment by Malize** [comment]
Wurde das mal gefixt? Weil heute wieder drin gewesen. Und wir haben Ihn nicht gefunden.

**Comment by hraesvelgr** [comment]
kein "behoben"-label :)

**Comment by timohausmann** [comment]
Bestätige. Soweit ich das bewerten kann, spawnt er nur an einem der vierte Punkte, also wahrscheinlich zu 25% der Zeit (Punkt 84, 44 auf der Wowhead-Karte). Zum Farmen am Besten den Dienstboteneingang benutzen, /tar Herd ... wenn er nicht gefunden wird, Ini reseten und erneut probieren.
