### ISSUE TITLE
AQ20 Generalleutnant Andorov

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1451]
Welches Verhalten wird beobachtet?
[Generalleutnant Andorov](http://datenbank.classic-wow.org/?npc=15471) lässt zurzeit leider nicht mit sich handeln man bekommt immer die Nachricht diesr NPC mag euch nicht

Wie sollte es sich verhalten?
Nachdem das Rajaxx event erfolgreich beendet wurde und Der General überlebt hatt sollte man ihn ansprechen können um mit ihm zu handeln. Er sollte 2 Schmiedekunst Rezepte verkaufen und unter anderem:
 5x [Erheblicher Manatrank](http://datenbank.classic-wow.org/?item=13444)
 4x [Erheblicher Heiltrank](http://datenbank.classic-wow.org/?item=13446)
18x [Schwerer Runenstoffverband](http://datenbank.classic-wow.org/?item=14530)
- http://datenbank.classic-wow.org/?item=22221
- http://datenbank.classic-wow.org/?item=22219

Schritte zur Reproduzierung
Adorov ansprechen und handelsfenster öffnen

Zusätzliche Informationen (Screenshots,  Videos, etc.)
http://www.wowhead.com/npc=15471/lieutenant-general-andorov#sells

**Comment by Slimmer2** [comment]
> 
By enotrai (1,467 – 3·14)  on 2006/12/06 (Patch 2.0.1)   

Keep this guy alive while you're fighting General Rajaxx. 

1: He has an aura for anyone above neutral with the Cenarion Circle that lowers casting times and restores your life. This is essential for the last part of the encounter which involves heavy AoE damage.

2: He can be used to tank General Rajaxx (even if you don't want him to, he probably will).

3: He does a LOT of damage.

4: After the fight he sells some epic patterns, Major Healing and Mana Potions, and bandages.

Steht auch unter Comment

**Comment by Dotox** [comment]
Für das Handeln wird ein gewisser Ruf-Wert benötigt.

**Comment by Mafyo** [comment]
Er mag mich trotzdem nicht obwohl ich Ehrfürchtig bin. Eig sollte man mit dem Ruf Neutral nicht mit ihm Handeln können sondern erst ab Freundlich. Die Schmiedekunst Rezepte sollten erst ab Respektvoll/Ehrfürchtig erwebbar sein. Außerdem sollte er nach 5 min nach dem Rajaxx Event despawnen.

**Comment by ChichiWarrior** [comment]
Mit dem lieben Andorov lässt sich jetzt zwar handeln, doch leider verkauft er immer noch nichts :-(

**Comment by dagochen** [comment]
Ich schau grad mal nach ;)

**Comment by Archidamos** [comment]
Also ich wollte ihn anhandeln und er hatte nix im Inventar. Also gleiches Problem wie bei Chichi, noch nicht behoben.

**Comment by Archidamos** [comment]
/push weil nicht behoben, heute wieder getestet

**Comment by dagochen** [comment]
Ist ja auch noch nicht aufgespielt ;)

**Comment by Archidamos** [comment]
Ah danke ;)

**Comment by Gipsyjodler** [comment]
Funktioniert nicht auf Nefarian.

**Comment by Koringar** [comment]
Wie schon geschrieben, hat er immer noch nichts zu verkaufen

Zwei Videos, als Beweis:
https://plays.tv/s/LGRbQL-shhGC
https://plays.tv/s/LGRbVYxGOdzx
