### ISSUE TITLE
Bossfight: wiederbeleben von Druiden

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1452]
Welches Verhalten wird beobachtet?
Wenn man im Bosskampf Wiederbeleben auf einen Spieler wirkt, der den Geist freigelassen hat, wird er zwar wiederbelebt steht aber vor der Instanz.

Wie sollte es sich verhalten?
Wenn ein Druide einen Spieler während eines Bosskampf einen Toten Spieler wiederbelebt der den Geist freigelassen hat, sollte er wiederbelebt werden und an der Stelle stehen wo der Druide den Zauber gewirkt hat.

Schritte zur Reproduzierung
Während eines Boss sterben und Geist freilassen und sich wiederbeleben lassen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=20484
http://datenbank.classic-wow.org/?spell=20739
http://datenbank.classic-wow.org/?spell=20742
http://datenbank.classic-wow.org/?spell=20747
http://datenbank.classic-wow.org/?spell=20748

Edit: Betrifft nur Raidinstanzen die man während eines Bosskampf nicht betreten kann

**Comment by Dotox** [comment]
Danke! Dein edit hat mich einfach zur Ursache bzw. zur Problemlösung geführt :)
