### ISSUE TITLE
Aussehen und Geschlechtsänderung

### ISSUE THREAD

**Issue by he4dy2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1453]
Leider ist die Geschlechts- und Aussehensänderung (Aussehen 2500g) nicht möglich, ohne auch einen Code eingeben zu müssen.

**Comment by Slimmer2** [comment]
Erstellt euch einen Charakter nach den oben genannten Kriterien und sucht anschließend mit eurem Charakter, dessen Aussehen ihr ändern möchtet, Zas'Tysh und Tharl Steinblut in Orgrimmar oder Ransin Donner und Garel Rotfels in Ironforge auf. Sprecht sie an und wählt die Option "Aussehen (2500 Gold)" aus, wenn ihr mit ingame Gold zahlen möchtet oder nur "Aussehen", wenn ihr einen Gutscheincode eintauschen möchtet. Solltet ihr euch für letzteres entscheiden, dann gebt in dem nun erscheinenden Textfeld euren Code ein oder lasst es leer, wenn ihr über Gold bezahlen möchtet. Wenn ihr alles richtig gemacht habt, dann müstet ihr nun eine "Permanente Täuschungskugel" im Inventar liegen haben!
 Wenn ihr dieses Item nun mit einem Rechtsklick benutzt, dann werdet ihr über ein neues Fenster dazu aufgefordert die Aktion zu bestätigen, da es kein Zurück mehr gibt, wenn ihr euer Aussehen erst einmal geändert habt! Wenn ihr damit einverstanden seid, dann drückt auf "Weiter" und gebt in dem Textfeld, das jetzt erschienen ist, den Namen eures Vorlagencharakteres ein und bestätigt die Eingabe.
 Wenn ihr euch nun aus- und wieder einloggt, dann hat euer Charakter das gewünschte Aussehen übernommen und ihr könnt den Vorlagencharakter bedenkenlos löschen!


Bist du so vorgegangen?

**Comment by he4dy2** [comment]
Natürlich

**Comment by he4dy2** [comment]
Zwischen "Aussehen per Gutscheincode" und "Aussehen (2500g)" besteht anwendungstechnisch kein Unterschied.

**Comment by Slimmer2** [comment]
Du hast ein Vorlagen Charakter erstellt der gleichen Rasse?

**Comment by he4dy2** [comment]
Jop

**Comment by Slimmer2** [comment]
Kommt da eine Fehlermeldung?

**Comment by he4dy2** [comment]
Bitte Gutschein-Code eingeben.

**Comment by Slimmer2** [comment]
> Solltet ihr euch für letzteres entscheiden, dann gebt in dem nun erscheinenden Textfeld euren Code ein oder lasst es leer, wenn ihr über Gold bezahlen möchtet.

**Comment by he4dy2** [comment]
"GutscheinCode konnte nicht überprüft werden"
