### ISSUE TITLE
Die Anweisungen des Pariah, Maraudon Quest 

### ISSUE THREAD

**Issue by LHFoxx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1454]
Welches Verhalten wird beobachtet?

Nachdem die Zentauren einzeln in den Fokus genommen wurden und das Amulett der Geister auf sie angewendet wurde, lassen sich diese nicht angreifen und werden weiterhin als freundlich / grün angezeigt.

Wie sollte es sich verhalten?

Nachdem die Zentauren einzeln in den Fokus genommen wurden und das Amulett der Geister auf sie angewendet wurde, müssten diese einen angreifen bzw. angreifbar sein. 

Schritte zur Reproduzierung

Es sind keine möglich, da ohne eine Möglichkeit die Zentauren anzugreifen die Quest nicht lösbar ist. 

http://datenbank.classic-wow.org/?item=17781
http://datenbank.classic-wow.org/?item=17761
http://datenbank.classic-wow.org/?item=17762
http://datenbank.classic-wow.org/?item=17763
http://datenbank.classic-wow.org/?item=17764
http://datenbank.classic-wow.org/?item=17765
http://datenbank.classic-wow.org/?item=17774
http://datenbank.classic-wow.org/?npc=12240
http://datenbank.classic-wow.org/?npc=12239
http://datenbank.classic-wow.org/?npc=12241
http://datenbank.classic-wow.org/?npc=12242
http://datenbank.classic-wow.org/?npc=12243
http://datenbank.classic-wow.org/?item=17757

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/264
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1417
