### ISSUE TITLE
AQ40: Hitbox von Auge von C'Thun

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1457]
Welches Verhalten wird beobachtet?
WIrbelwind vom Krieger trifft C'Thun nur wenn man fast so nahe an ihm dransteht, dass man weggekickt wird. Autohits und direkte Angriffe gehen auf eine deutlich größere Reichweite.
Aktuell funktioniert die Hitbox nur bei C'Thun selbst in Phase 2.

Wie sollte es sich verhalten?
Wenn Autohits ausgeführt werden sollten, dann sollte das Ziel auch nah genug sein um mit Wirbelwind zu treffen (Wirbelwind hat sogar eine höhere Reichweite von 8m).

Zusätzliche Informationen (Screenshots, Videos, etc.)
Problem wurde bereits in Update 31.12.2015 und 31.01.2016 angegangen

Zusätzliches
Vermutlich wird dieses Problem auch andere AOE-Fähigkeiten betreffen.
Auge von C'Thun: http://datenbank.classic-wow.org/?npc=15589

**Comment by Horim** [comment]
Kann mich nur anschließen. Am Sonntag in P1 erneut erfolglos mit Wirbelwind am Boss.

**Comment by Seniorash** [comment]
Falls es wirklich schon auf Nefarian ist: Ist immernoch buggy

**Comment by Dotox** [comment]
Erst nach dem Serverneustart aktiv

**Comment by Horim** [comment]
Kurzes Update: 

Die Skills treffen das Auge von C'thun nach wie vor nicht bei max Melee-Range, auch wenn man nicht mehr im Boss stehen muss um bspw. Wirbelwind zu wirken. Range wurde also angepasst, wenn auch noch nicht vollständig =)

**Comment by Dotox** [comment]
Hab nochmal etwas geändert :)

**Comment by Horim** [comment]
Kurzes Update:

Mit der Änderung passt die Hitbox für Wirbelwind, allerdings ist diese jetzt so groß, das #1513 entsteht.
