### ISSUE TITLE
Erste Hilfe Lehrer auf der Hordenseite nicht Ansprechbar/Anklickbar

### ISSUE THREAD

**Issue by Nisaaru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1459]
Grüße,
wie in der Überschrift erwähnt, lässt sich der Erste-Hilfe Lehrer auf der Hordenseite nicht ansprechen und auch nicht anklicken. Erste Hilfe Skill ist auf 225 und die Quest aus OG ist im Questlog.

Quest: http://datenbank.classic-wow.org/?quest=6623
NPC: http://datenbank.classic-wow.org/?npc=12920

Zum Thema wie es ablaufen sollte:
Man müsse den NPC anklicken können, das Questfenster sollte sich öffnen, danach die Quest abgeben können und das Quest-Event mit den verwundeten Soldaten sollte starten.

Ich kann aber nicht sagen ob das Problem nur am NPC liegt oder gänzlich die ganze Quest verbuggt ist.

**Comment by Rushor** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md

lesen und infos pls adden :)

**Comment by Ghulfang** [comment]
Habe gerade die Quest ohne Probleme abgeschlossen mit lvl 36 und einem von Skill 225. Char Tauren Krieger. 

Anderes Problem: Ein schwer verletzter Soldat (Trollversion) wurde nur mit einem schwarzen Skin dargestellt. http://datenbank.classic-wow.org/?npc=12924

Screen: http://imgur.com/89HWu6m

**Comment by Nisaaru** [comment]
Der NPC konnte nun tatsächlich angesprochen werden und man konnte die Quest problemlos abgeben und das Event abschließen. Das mit dem schwarzen Trollskin von einem "Ein schwer verletzter Soldat" kann ich bestätigen. Es handelt sich aber nur um den weiblichen Trollskin, die männlichen wurden richtig dargestellt.

**Comment by Rushor** [comment]
> Ein schwer verletzter Soldat (Trollversion) wurde nur mit einem schwarzen Skin dargestellt.

maximal pigmentiert xD

**Comment by Phuzak** [comment]
Der NPC ist wie oben beschrieben nicht ansprechbar/anwählbar ergo verbugt.
