### ISSUE TITLE
Quest: Mehr Befestigungen

### ISSUE THREAD

**Issue by Dunkelbaron** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1460]
Quest: Mehr Befestigungen
Ort: Östliche Pestländer
Problem: Turm der Kronenwache wurde nach der Einnahme nicht im Questlog gezählt und auch auf der Map nicht angezeigt. Kurz zuvor gab es wohl ein Reset der bereits eingenommenen Türme.

**Comment by Loplin** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md
