### ISSUE TITLE
Verderbnis Rang 7 -Debuff Priorität

### ISSUE THREAD

**Issue by Derop** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1461]
Was wird beobachtet:

Seitdem ich den neuen Rang per Buch aus AQ20 "Verderbnis" (Rang 7) erlent habe,
funktioniert die alte Debuff-Priorität, welche vor Erlernen gut funktioniert hat, nicht mehr.
Das heißt: Jede "Tiefe Wunde-Dot", jeder "Feuerball-Dot" löscht bzw dispellt den feindlichen Mob.

Wie sollte es eigentlich sein:

Die Debuff Priorität sollte deutlich höher liegen als die beiden oben genannten. Die 30/00/21 Skillung der Hexer ist im Raid, in denen Firemages und Off-Warris sind nicht mehr spielbar.

**Comment by testear** [comment]
i like

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md
