### ISSUE TITLE
Kampf entfliehen

### ISSUE THREAD

**Issue by Soox1991** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1462]
Ich bin mir nicht ganz sicher ob es sich dabei um einen Bug handelt.

Folgendes: Wenn mich jemand (PVP) angreift und ich direkt beim Flugmeister bin, kann ich dem Kampf entgehen indem ich an einen anderen Ort  per schnellreise fliege (Premium). Soviel ich weiss sollte ich den Flugmeister im PvP Kampf nicht nutzen können.

**Comment by dagochen** [comment]
Dafür benötigst du Quellen von damals.
