### ISSUE TITLE
AQ40: C'thun (Riesiges Augententakel)

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1464]
Hallo Entwicklerteam, 

dieser Beitrag richtet sich an den Encounter C'thun in AQ40 und umfasst einen Bug, welcher schnell zum Wipe innerhalb des Kampfes mit C'thun führen kann. Dabei handelt es sich um eine der erscheinenden "Riesiges Augententakel" in Phase 2.

---

Wie sollte es sein?
Jede Minute beschwört C'thun (Phase 2) ein "Riesiges Augententakel", welches zufällig an einem Standort eines momentan stehendes Spielers erscheint. Sie verursacht ca. 3.000 - 4.000 durch die Spawnerruption und fängt nach einem kurzen Delay an, "Augenstrahl" auf einem zufälligen Spieler zu zaubern.

Wie ist es?
Leider erscheint das große Augententakel an einer zufälligen Position mittem im Raum. Das Ganze war bereits schon so unglücklich, dass das Auge sogar an der oberen Treppe am Eingang, fast innerhalb der Mauer oder im Boss (C'thun) selbst erschienen ist. Dabei war es dann teilweise unmöglich für die Meeles Schaden zu verursachen, geschweige den es zu kicken oder zu unterbrechen. (Das Auge sollte nur unterhalb eines Spielers erscheinen dürfen, der sich in dem Zeitraum innerhalb des Raumes aufhält)

Quellen: 
http://wowwiki.wikia.com/wiki/C'Thun_%28tactics%29
http://datenbank.classic-wow.org/?npc=15334

---

Leider hat vor allem die Spawnposition in C'thun, das eine oder andere Mal zum Wipe geführt. Wir würden uns sehr darüber freuen, wenn dies nicht mehr möglich ist.

Vielen Dank für den Support!

Mit freundlichen Grüßen
Omega :-)

**Comment by ircfelix** [comment]
Hier kann man noch dir großen und kleinen Augententakel ergänzen, die einen beim Spawn zwar weg kicken, aber im gleichen Atemzug noch instant einen Meleeschlag an das näheste Ziel raushauen. Für Stoffies ist das vor allem bei den großen Klauententakeln relevant, die durch ihren Kick 2-3k Naturschaden machen und einen dann noch für 2-3k noncrit schlagen. Hat man dort keinen Naturschutztrank, ist man im Prinzip dem Risiko eines one-hits ausgesetzt.
Leider habe ich keinen Beweis das es so sein sollte, aber es würde aus meiner Erfahrung schon der Blizzard Logik widersprechen wenn ein Encounter nach Zufallsprinzip Leute oneshotted.

Eine Lösung wäre hier, dass der riesige Klauententakel mit seinem Meleeangriff 1-2 sek. wartet bis die gekickten Spieler außer seiner Meleerange sind.

**Comment by Seniorash** [comment]
Die Spawns entstehen nach unseren Beobachtungen immer unter Spielern. Spawns in der Mitte oder ganz am Rand können vorkommen, wenn ein Spieler gerade aus dem Magen kommt.
Wir hatten sogar einen Spawn bei einem Spieler im Magen.

**Comment by Horim** [comment]
Kann mich Korash nur anschließen:

Die große Augententakel spawnt immer unter einem zufälligen Spieler. Dementsprechend kann es passieren das eine große Augententakel genau im Boss spawnt, wenn der zugehörige Spieler aus dem Magen kommt. Was jedoch nicht passieren darf, aber dennoch auftritt, ist der spawn der großen Augententakel im Magen von C'Thun.

**Comment by Dotox** [comment]
Die Spawns stimmen soweit, was aber nicht passieren darf, ist dass die im Magen erscheinen. Dafür existiert allerdings auch eine Abfrage. Welche der spawnenden Monster konntet ihr denn bisher im Magen entdecken?

**Comment by Seniorash** [comment]
Bisher nur ein großes Augententakel.
