### ISSUE TITLE
Krieger: Swingtimer Skills bei zu wenig Wut

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1469]
Die Probleme bezüglich Spalten und Heldenhafter Stoß bestehen nach wie vor, daher eröffne ich die Runde erneut mit Verweis auf die eigentlich Bugreports.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1303
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1284

**Comment by testear** [comment]
Tu mir doch den Gefallen und lies die beiden reports nochmal. Falls du dich erinnern kannst was genau drin stand kann man die ja neu aufarbeiten. Ich glaube aber nicht, dass das in dieser Form jemals geändert wird.

**Comment by Horim** [comment]
Ich verstehe leider nicht warum ich das neu aufarbeiten soll, wenn die Reports einfach kommentarlos geschlossen wurden. Das Essentielle stand bereits in den vergangenen Reports und an der Thematik hat sich seit Jahren nichts, aber auch gar nichts geändert.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md

**Comment by testear** [comment]
"Das Essentielle stand bereits in den vergangenen Reports"

Genau das ist die richtige Form (Vergangenheit) - Es steht eben nicht mehr da.
