### ISSUE TITLE
Spawn-verhalten Erze/Kräuter #694

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1470]
#694 

Hallo Dotox, das System ist aktuell noch nicht auf Nefarian, richtig?

**Comment by Dotox** [comment]
Nein, siehe Label :)

**Comment by Sheed90** [comment]
Alles klar, danke für die super schnell Antwort. :-)

Dürfen wir es uns nochmal auf dem Testserver angucken?

Gruß

**Comment by EisenhowerSC** [comment]
Hallo Dotox,

leider ist das System auf Nefarian zur Zeit nicht entsprechend der Spielerzahl angepasst. Als ihr das jetzige System implementiert habt, hatten wir einer Spielerzahl von ~600. Nun haben wir zu Spitzenzeiten ~1,5k und die Kräuter reichen nicht mehr. Zusätzlich beobachte ich täglich wie Stellen mit vielen Kräutern gecampt werden. Das sollte nicht möglich sein. 

Man merkt wie viele Spawns, sowohl Kräuter als auch Erze einfach abgecampt werden. Weil sie festen Resawnzeit haben.


Gibts schon ein ungefähres Datum, wann das neue System auf Nefarian aufgespielt wird?
Sollte es noch nicht fertig sein, haben wir in der Gilde eine gruppe, die bereit sind es noch Ausführlich zu testen. 

MFG
Eisenhower

**Comment by dagochen** [comment]
Entsprechend dem Spawnverhalten von "damals" müssten es WENIGER Spawns sein.

**Comment by EisenhowerSC** [comment]
Entsprechend dem Spawnverhalten von "damals" müssten es VIEL SCHNELLER respawnen

**Comment by dagochen** [comment]
Instant-Respawn halt ;) Irgendwo im gleichen Gebiet.

**Comment by EisenhowerSC** [comment]
sign  :)

**Comment by ircfelix** [comment]
Quelleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?

**Comment by Sheed90** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/694 -.-

**Comment by EisenhowerSC** [comment]
Quelle? Life Server!

**Comment by EisenhowerSC** [comment]
Es ist nun mal Fakt, dass das aktuelle Kräuter Spawn/respanwn System nicht mehr für die Spieleranzahl aufm Server passt. Mag ja gut sein, dass Manche hier noch ein Vorrat aus den Goldenen Zeiten haben, neue Spieler hingegen haben aber Probleme, da teilweise um 4 uhr morgens kein Traumblatt zu finden ist. Wie es ab 16 uhr nachmittags aussieht, kannst man sich natürlich auch denken....

**Comment by ircfelix** [comment]
Quelle bzgl. ein respawntes Kraut pro Gebiet und Minute.

Ich sehe nämlich schon ganze raids auf ein Gebiet verteilt die Kräuter auf cooldown abfarmen.

**Comment by Sabbaer** [comment]
ja, genau das haben wir damals aufm offi häufiger gemacht!

**Comment by ircfelix** [comment]
Versteht mich nicht falsch, so ein einfaches System würde jedem zu gute kommen und ich würde auch profitieren. Das einzige warum ich dagegen bin es einzuführen ist, das es sich nicht einbürgern soll das Nefarian noch mehr zu einem "widde widde witt, ich mach mir den Server, wie er mir gefällt"-server wird (siehe umskillkosten, boss"hp").

**Comment by Slimmer2** [comment]
Testet Lieber mal das System das auf dem Testserver, als dauernd hier rumzumeckern

**Comment by EisenhowerSC** [comment]
Würden wir gerne. Wir hoffen der Testserver ist bald wieder erreichbar

**Comment by dagochen** [comment]
Es würde insgesamt nicht dazu führen, dass man MEHR KRÄUTER farmen kann. Es würde lediglich dazu führen, dass man IMMER Kräuter farmen kann, auch wenn andere bereits am farmen sind. Der aktuelle Fall, dass man NICHTS findet, weil grad alles weggepflückt ist, würde dann nicht mehr möglich sein. 

In der Summe müsste man dann statt bei gespawntem Gromsblut im Teufelswald einmal durchzureiten und 2-3 Stacks zu machen, mehrfach hoch und runter reiten, bis man die gleiche Menge gefarmt hat.

**Comment by aryanef** [comment]
Man findet immer Erze und Kräuter nur muss man mal mehr als 10min vor die eigene Haustür gehen...

**Comment by Larirawiel** [comment]
Das Farmen der Kräuter kostet mich derzeit rund 10 Stunden die Woche an Zeit. Und ja, ich habe es nachgemessen. 4 Fläschchen der destillierten Weisheit, 15 - 20 Manapots, 10 Magierblutelixiere etcpp., da braucht man um die 200 Traumblatt. Nur so zum Drübernachdenken was die derzeitige Spielmechanik für Konsequenzen hat für Leute später angefangen haben, die keine 400 Fläschchen auf irgendwelchen Bankchars bunkern.


Grüße

**Comment by Derop** [comment]
Geschweige denn der explodierte Preis für Traumblatt/Gromsblut und Bergsilber. 35-40g pro Stack(20STÜCK oO) geht Gromsblut  teilweise raus. Das der Kräutler allen anderen Berufen finanziell gesehen viel Gold bringt war schon immer so, aber so heftig übervorteilt wie zur Zeit war er noch nie. 

und @aryanef : klar findet man immer Kräuter aber wenn du in allen TB spawnenden Gebieten zu drei verschiedenen Uhrzeiten gerade mal eine Flask gefarmt hast(wenn überhaupt), ist das schon sehr bitter. Oft sind diese auch verbuggt: Man kräutert sie und im Lootfenster ist nichts->Kraut despawnt. Yeah

**Comment by Seniorash** [comment]
/push
Bitte zum testen auf testserver oder Nefarian freigeben

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/694
