### ISSUE TITLE
Sturmangriff resultiert in "Durchfallen" durch Boden

### ISSUE THREAD

**Issue by Maredoran** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1471]
Bug: Sturmangriff des Kriegers resultiert im "Durchfallen" durch den Boden mit anschließender Landung in den Todesminen

Ort: Westfall - Dolchhügel

Ein paar Meter nach dem Questgeber "Schnapsbart Donnerbräu". Wenn man Richtung Westen das Gefälle runterläuft.
Sturmangriff Richtung Nordwesten gegen einen Defias (Abschlussquest "Volksmiliz") ausgeführt. Ich war ziemlich nah an der Hügelkette.

**Comment by Haudraufinix** [comment]
Von diesen Stellen gibts tonnenweise - am besten über keine Erhöhungen Drüberchargen ;)

**Comment by Slimmer2** [comment]
Gibt mehrere dieser Stellen, aber ohne Report werden die wohl nicht gefixt

**Comment by Maredoran** [comment]
Ja ich weiss. Hab das damals auch in den "Original" Classic Zeiten im Brachland mit "Blinzeln" erlebt.
Was mir aber in den Dolchhügeln aufgefallen ist:
Ich bin ja das Gefälle runtergechargt. Also nicht in die Erhöhung rein.
