### ISSUE TITLE
Dunkelmondjahrmarkt

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1472]
**Welches Verhalten wird beobachtet?**
Der Jahrmarkt hat vor dem erscheinen keine Aufbau Animation und kommt nicht wie vorgesehen an den Tag wo er sollte.
im Januar war er schon Sonntags aufgebaut, obwohl er erst am Montag um 4 Uhr früh stehen sollte.
Gab auch schon ein Monat wo er eine Woche zu früh stand oder erst nach nachfragen kam.

**Wie sollte es sich verhalten?**
Der Jahrmarkt sollte am ersten Freitag im Monat mit dem Aufbau beginnen und am Montag um 4 Uhr damit fertig sein und sollte seine Zelte nach 1 Woche wieder abbauen. 
der Jahrmarkt sollte jeden Monat dann seinen Standort wechseln Einmal Wald von Elvyen und Monat drauf Mulgore

> Starting on the first Friday of each even-numbered month, the Faire sets up in a field in Elwynn 
> Forest (south of Goldshire); on the first Friday of odd-numbered months, it sets up in Mulgore at the base of Thunder Bluff. Setup takes the carnies three days, and the Faire officially starts early that Monday at 4:00 AM server time. 
> 
> Once it is complete, the Faire will remain there for one week. The following month it will appear in the opposite location.

**Schritte zur Reproduzierung**
Erstes Wochenende abwarten und an den Standorten wo er eigentlich kommen sollte nachschauen.
**
Zusätzliche Informationen (Screenshots, Videos, etc.)**

http://datenbank.classic-wow.org/?faction=909
http://wowwiki.wikia.com/wiki/Darkmoon_Faire_(old)?oldid=365271

**Comment by Slimmer2** [comment]
Der Jahrmarkt steht eine Woche zu früh

**Comment by dagochen** [comment]
Schon erledigt ;) Ab März sollte es nun endgültig stimmen ;)

**Comment by Slimmer2** [comment]
Der Jahrmarkt steht aktuell nicht bis Montags 4:00 Uhr, sondern schließt bereits Sonntags gegen 23:59
