### ISSUE TITLE
[Allgemein] Feedback zu Serverupdates

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1473]
Hier eine Ansammlung aus dem Forum zu den Serverupdates, die nicht funktionieren wie beschrieben.

- Die Hitbox von Auge von C'thun ist immernoch zu klein für Wirbelwind - http://datenbank.classic-wow.org/?npc=15589
- Viscidus kann ohne Blob getötet werden - http://datenbank.classic-wow.org/?npc=15299
- Der Trash zu Ouro respawned obwohl dieser tot ist (Hier weiß ich nicht sicher ob das so sein soll, jedenfalls macht der Teleport zu Ouro keinen Sinn, wenn der Trash wieder da ist.)
- Twins Trash (leider weiß ich gerade nicht welche das genau sind) verbuggen, wenn man sie auf große Range pullt, die Krieger/Schlachtwachen spawnen und bleiben stehen.

Wenn der Eintrag nicht passt, Close. Ansonsten werde ich nach und nach hier weiter editieren.
Alles nur auf Serverupdates bezogen.

Gruß

Chichi

**Comment by dagochen** [comment]
- Bei Viscidous kommt ein Blob zu wenig, wenn er also unter 5% ist kommt kein Blob mehr nach dem Einfrieren und der Encounter verbuggt.

- Bei den Twins stimmt die Position des Caster-Twins nicht. Er rennt wild durch die Gegend und macht es so nahezu unmöglich den Boss zu tanken.
