### ISSUE TITLE
Schurke Kombopunkte

### ISSUE THREAD

**Issue by kharox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1475]
Wenn man auf einem Ziel Combopunkte aufbaut und dann das Ziel wechselt OHNE es anzugreifen, dann verliert man die Combopunkte auf seinem eigentlichen Ziel.
Dass man die Combopunkte verliert, wenn man das zweite Ziel angreift, ist ja klar. Aber das passiert momentan halt auch wenn man das zweite Ziel einfach nur im Target hat.

**Comment by testear** [comment]
Patch 1.4.0 (2005-05-05): Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.
As of Patch 2.0.3, the rogue will not lose Combo Points upon switching targets until a point has been added to another target.

**Comment by Slimmer2** [comment]
Ist kein Bug
