### ISSUE TITLE
Staubwolke von Aufseher des Anubisath

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1478]
Welches Verhalten wird beobachtet?
Der NPC macht eine AE Names Staubwolke die, die Trefferchance um 85% reduzieren soll.
Dieser Debuff hat kein Einfluss auf die Trefferchance

Wie sollte es sich verhalten?
Der Debuff sollte die Trefferchance um 85% reduzieren

Schritte zur Reproduzierung
Aufseher des Anubisath pullen warten bis er Staubwolke macht und dann Schaden machen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?npc=15311
http://datenbank.classic-wow.org/?spell=26072

**Comment by ChichiWarrior** [comment]
Kann ich so nicht bestätigen. Bei uns funktioniert das einwandfrei

**Comment by Slimmer2** [comment]
Wie ich den Debuff hatte, hat jeder cast getroffen.
Und das kann nicht stimmen wenn der debuff 85% Trefferchance verringert.

**Comment by testear** [comment]
Vermutlich beeinflusst es nur Meleehit.

http://wowwiki.wikia.com/wiki/Anubisath_Warder

**Comment by Rushor** [comment]
einige spells die die Trefferchance verringern in wow betreffen nur meleeattacken (siehe auch der debuff der falschen bei professor putricide in icc).

generell sind solche daten (also ob der debuff nun spells oder meleeattacken betrifft) in den dbc hinterlegt und sollten auch immer korrekt sein

**Comment by Slimmer2** [comment]
Im Tooltip vom Debuff steht halt: Trefferchance um 85% verringert
Und da steht nicht von melee

**Comment by Omegaexodus** [comment]
Wer halt lesen kann ist klar im Vorteil:
" Apply Aura: [Mod Melee & Ranged Hit Chance %]
Wert: -85%
Radius: 45 Meter"
Da steht nicht Spellhit chance!

Damit ist der Beitrag leider überflüssig. Und ja es ist die Variante nur für Meeles, um deren Schaden zu veringern, da die großen Aufseher des Anubisath zwei spezifische Eigenschaften haben können. Einmal Silence für die ganzen Caster und einmal Trefferchance reduzieren für die ganzen Meeles (Hunter).

Mfg Omega :-)

**Comment by Slimmer2** [comment]
Caster sind ja keine Range DD's...

**Comment by Slimmer2** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8680824/13100709/4f3a7310-d540-11e5-8f81-ddeb93126d90.PNG)
Dann muss aber der Tooltip nach euren Aussagen Falsch sein.
Das hat mich schon stutzig gemacht

**Comment by ChichiWarrior** [comment]
Um dir das auf verständlichem Deutsch zu erklären.

Blizzard unterscheidet Trefferchancen in zwei Kategorien.

Kategorie 1: Trefferchance
Kategorie 2: Zaubertrefferchance

Neben der um 85% verringerten Trefferchance, haben diese Aufseher einen Silence für die Caster um auch die Heiler "zu treffen".

Jeder Tooltip auf dem Equip wäre falsch, wenn man nach deiner Argumentation geht.

Ich hoffe du konntest jetzt aufgeklärt werden.

Gruß

Chichi
