### ISSUE TITLE
AQ40 Vollstrecker der Qiraji

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1479]
Welches Verhalten wird beobachtet?
Die [Vollstrecker der Qiraji](http://datenbank.classic-wow.org/?npc=15250#abilities) benutzen DIe Fähigkeit [Wirbelwind](http://datenbank.classic-wow.org/?spell=13736) nicht [Wirbelwind](http://datenbank.classic-wow.org/?spell=15589) (2 spells in der Datenbank)

Wie sollte es sich verhalten?
Die Vollstrecker sollten Die Fähigkeit Wirbelwind nutzen. Diese Mbbs sind zurzeit eher ein Witz da sie kaum schaden verursachen.

Schritte zur Reproduzierung
Vollstrecker angreifen

Zusätzliche Informationen (Screenshots, Videos, et)
http://wowwiki.wikia.com/wiki/Qiraji_Slayer

**Comment by Mafyo** [comment]
kann gelöscht werden hab ich mich geirt

**Comment by Slimmer2** [comment]
Dann Close es hauch
