### ISSUE TITLE
ZG Trash Fehlerhaft

### ISSUE THREAD

**Issue by pocketpair125** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1480]
Hallo,
ich wollte mitteilen, dass der Zul'Gurub Trash fehlerhaft ist. Am Anfang im Wasser rechts sind keine Krokodile damals gewesen, auf Nefarian ist dies aber der Fall. Dazu kommt das zwei Schlangen auf einem Hügel stehen, die dort nicht sind. Außerdem sind in dem Wasser vor Hakkar's Tempel auch keine Krokodile gewesen, sondern nur die Frenzy Fische. Dazu kommt ein Berserker direkt vor dem Tempel von Hakkar der bis zur Brücke patroulliert, dies war ebenfalls nicht der Fall.
Quellen:
Video Nr. 1/2:
https://www.youtube.com/watch?v=biF5J8JRW4k

Wenn man das erste Video bei 0:09 anhält sieht man das ganz hinten die Schlangen nie da waren. Folgt man dem Video weiter sieht man, dass sich der Magier frei im Wasser bewegen kann ohne das dort Krokodile sind die Ihn angreifen.
Folgt man dem Video ab 5:40 weiter, sieht man an der Stelle wo er von dem Wasserfall in das Wasser springt nur die Frenzy Fische und keine Krokodile.

Video Nr. 2/2:
https://www.youtube.com/watch?v=16l2kJPM0D0&

Startet man das Video bei 0:25 kann man genau zuschauen, dass kein Berserker auf der offenen Grünfläche vor dem Tempel patroulliert. Bei 1:00 kann man ihm auch zuschauen wie er die Krokos schön zusammen zieht.

Hoffe auf eine Antwort :)

**Comment by Slimmer2** [comment]
Video 1 aus 2008
Video 2 GEMA

**Comment by pocketpair125** [comment]
dann musst du die gema umgehen :D

**Comment by Mafyo** [comment]
Video 2 hatt keine Gema mehr^^
