### ISSUE TITLE
Kreegs Hauwegstarkbier funktioniert nicht richtig!

### ISSUE THREAD

**Issue by Nightfly385** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1481]
Welches Verhalten wird beobachtet?:
Bei der Einnahme des alkoholischen Getränks wird nur der Int-Wert um 5 verringert. Die Willenskraft wird jedoch nicht erhöht.

Wie sollte es sich verhalten?
Der Wille-WErt sollte sich wie angegeben um 25 erhöhen und nicht stagnieren

Schritte zur Reproduzierung:

Hauwegsstarkbier trinken und Stats ansehen...

Link zur Datenbank:
http://datenbank.classic-wow.org/?item=18284

Zusatz:
Da es ein alkoholisches Getränk ist sollte der Buff definitv funktionieren. Und NEIN ich hatte keinen Rumsey Rum schon eingeworfen. Es hieß hier das ein alkoholisches Getränk zum buffen immer funktionieren würde.

Liebe Grüße
Night

**Comment by Slimmer2** [comment]
Gerade getestet.
Bei mir funktioniert der Debuff korrekt.

**Comment by Nightfly385** [comment]
Oo
Ich teste es gleich mal ob der Willebuff evtl. den Bierbuff überschreibt

**Comment by Slimmer2** [comment]
Überschreibt es nicht, das hab ich mit getestet

**Comment by ircfelix** [comment]
Also bei mir hat es neulich schon immer geklappt. Ich werds auch nochmal beobachten.
