### ISSUE TITLE
Kreegs Hauwegstarkbier mit anderen Alkohol Buffs

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1482]
Welches Verhalten wird beobachtet?
[Kreegs Hauwegstarkbier](http://datenbank.classic-wow.org/?item=18284) kann man mit anderen Alkohol Buffs gleichzeitig aktiv sein

Wie sollte es sich verhalten?
Es sollte immer nur 1 Alkohol Buff aktiv sein können. Wenn man den Debuff von Kreegs Hauwegstarkbier noch hat sollte man sich keinen anderen Alkohol Buff bekommen können.

Schritte zur Reproduzierung
Kreegs Hauwegstarkbier trinken und dann Rumsey Rum

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?search=rumsey

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by ircfelix** [comment]
Kreegs Bier ist ein DEBUFF und nicht wie etwa der altgediente Rumsey Rum ein BUFF.

**Comment by testear** [comment]
Dann beweis, dass es stacken sollte Felix.
Alkohol und Alkohol sollten sich in WoW aufheben. (because fuck logic)

**Comment by Slimmer2** [comment]
Es Darf nicht Stacken, Extra bei den GM's nachgefragt.

**Comment by ircfelix** [comment]
Und welchen Beweis haben die Gms?

**Comment by Slimmer2** [comment]
Weil nur 1 Alkohol Buff Aktiv sein darf.

**Comment by ircfelix** [comment]
Ich verstehe deinen Argumentationsansatz, doch halte ich ihn nicht für korrekt, da es sich hier wie gesagt nicht um einen Buff, sondern um einen DEBUFF handelt.
Wenn es darum ginge z.B gesegneten Sonnenfruchtsaft von der Argentumdämmerung oder die Nachtflossensuppe mit Rumsey Rum zu stacken, hättest du meiner Meinung nach sehr wohl recht, da es sich bei allen dreien um BUFFS handelt, aber nicht wie hier um DEBUFFS.

In dem Bugreport zum Hauwegstarkbier waren mehrere Quellen die besagten das Zeug getrunken zu haben. Das hätten sie vermutlich für -5 Int und +25 Wille nicht getan, wenn sie dadurch z.B. ihre 8 mp5 Nachtflossensuppe verloren hätten. 

Schade das bei wichtigeren Bugreports nicht ebenso fleißig argumentiert wird wie hier.

**Comment by ircfelix** [comment]
P.S. Du hast immer noch keine Quelle von 2005/2006 geliefert. Auch wenn Ruljin in Sachen Buffstacking sehr kompetent ist, ist er genau so wenig wie du und ich eine Quelle von damals.

**Comment by testear** [comment]
Felix du hast auch keine Quelle geliefert. Wer verlangt muss auch selber liefern können! Kannst du das?

**Comment by Slimmer2** [comment]
Und ich hab zudem die Aussage von der GM Leitung Ruljin, das dies nicht gehen soll.

**Comment by ircfelix** [comment]
Versteht ihr den Unterschied zwischen Buff und Debuff? Da das hier ein Debuff ist, KANN er gar nicht mit anderen Buffs stacken.

Übrigens hast du den thread eröffnet also musst DU die Quelle bringen, nicht ich. So lange du keine Quelle hast wäre ein Fix hiervon Malen nach Zahlen.

**Comment by Slimmer2** [comment]
Sehen wir dann eh welches Label Dotox hier anhängt.
Es bleibt trotzdem ein Alkohol, der gewollt einen Wert erhöht und einen verringert.

**Comment by Loplin** [comment]
Video: Gummo von Curse hat 2 Rum-buffs
https://www.youtube.com/watch?v=9-6K-IDhOdA

**Comment by Dotox** [comment]
Kreegs Hauwegstarkbier kann stacken, solange es nicht mit einem anderen Alkohol stackt, die die gleichen Werte besitzen.
