### ISSUE TITLE
AOE flaggt Spieler mit PVP

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1483]
**Welches Verhalten wird beobachtet?**
Wenn man AOE macht und in der Range des Effekt ein Spieler mit aktiven PVP steht, wird man PvP geflaggt.
**
Wie sollte es sich verhalten?**
Man sollte nicht PvP geflaggt werden, wenn Spieler mit aktiven PvP in AOE steht. Und der Spieler mit aktiven PvP sollte auch keinen AOE schaden abbekommen, von den Spieler **ohne** aktivierten PVP.

**Schritte zur Reproduzierung**
Einen AOE machen und einen Spieler mit aktiven PvP in der AOE Range/Fläche stehen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Hier bitte ich andere Klassen ihre AOE Spells in den Comments einfügen, die noch fehlen.
**Druide:**
Hurricane
http://datenbank.classic-wow.org/?spell=16914
http://datenbank.classic-wow.org/?spell=17401
http://datenbank.classic-wow.org/?spell=17402

**Hexenmeister:**
Rain of Fire
http://datenbank.classic-wow.org/?spell=5740
http://datenbank.classic-wow.org/?spell=6219
http://datenbank.classic-wow.org/?spell=11677
http://datenbank.classic-wow.org/?spell=11678
Hellfire
http://datenbank.classic-wow.org/?spell=1949
http://datenbank.classic-wow.org/?spell=11683
http://datenbank.classic-wow.org/?spell=11684
Howl of Terror
http://datenbank.classic-wow.org/?spell=5484
http://datenbank.classic-wow.org/?spell=17928

**Magier:**
Arcane Explosion
http://datenbank.classic-wow.org/?spell=1449
http://datenbank.classic-wow.org/?spell=8437
http://datenbank.classic-wow.org/?spell=8438
http://datenbank.classic-wow.org/?spell=8439
http://datenbank.classic-wow.org/?spell=10201
http://datenbank.classic-wow.org/?spell=10202
Blizzard
http://datenbank.classic-wow.org/?spell=10
http://datenbank.classic-wow.org/?spell=6141
http://datenbank.classic-wow.org/?spell=8427
http://datenbank.classic-wow.org/?spell=10185
http://datenbank.classic-wow.org/?spell=10186
http://datenbank.classic-wow.org/?spell=10187
Flamestrike
http://datenbank.classic-wow.org/?spell=2120
http://datenbank.classic-wow.org/?spell=2121
http://datenbank.classic-wow.org/?spell=8422
http://datenbank.classic-wow.org/?spell=8423
http://datenbank.classic-wow.org/?spell=10215
http://datenbank.classic-wow.org/?spell=10216

**Krieger**
Thunder Clap
http://datenbank.classic-wow.org/?spell=6343
http://datenbank.classic-wow.org/?spell=8198
http://datenbank.classic-wow.org/?spell=8204
http://datenbank.classic-wow.org/?spell=8205
http://datenbank.classic-wow.org/?spell=11580
http://datenbank.classic-wow.org/?spell=11581
Demoralizing Shout
http://datenbank.classic-wow.org/?spell=1160
http://datenbank.classic-wow.org/?spell=6190
http://datenbank.classic-wow.org/?spell=11554
http://datenbank.classic-wow.org/?spell=11555
http://datenbank.classic-wow.org/?spell=11556

**Priester:**
Holy Nova
http://datenbank.classic-wow.org/?spell=15237
http://datenbank.classic-wow.org/?spell=15430
http://datenbank.classic-wow.org/?spell=15431
http://datenbank.classic-wow.org/?spell=27799
http://datenbank.classic-wow.org/?spell=27800
http://datenbank.classic-wow.org/?spell=27801
Psychic Scream
http://datenbank.classic-wow.org/?spell=8122
http://datenbank.classic-wow.org/?spell=8124
http://datenbank.classic-wow.org/?spell=10888
http://datenbank.classic-wow.org/?spell=10890

**Paladin:**
Consecration
http://datenbank.classic-wow.org/?spell=26573
http://datenbank.classic-wow.org/?spell=20116
http://datenbank.classic-wow.org/?spell=20922
http://datenbank.classic-wow.org/?spell=20923
http://datenbank.classic-wow.org/?spell=20924

**Schamane:**

**Jäger:**

**Schurke**

Es gibt auch Rassen-/Volksfertigkeiten

**Comment by testear** [comment]
Krieger bitte noch hinzufügen.
Weitreichende Stöße
http://datenbank.welli-it.de/?spell=12292 
Spalten
http://datenbank.classic-wow.org/?spell=845 
http://datenbank.classic-wow.org/?spell=7369
http://datenbank.classic-wow.org/?spell=11608
http://datenbank.classic-wow.org/?spell=11609
Wirbelwind:
http://datenbank.welli-it.de/?spell=1680

**Comment by Loplin** [comment]
Sorty aber die obligatorische frage muss kommen

Quelle?

**Comment by Slimmer2** [comment]
Hier die Quelle mehr oder weniger http://community.mmobase.de/hilfe-und-support/8755-gegner-mit-absicht-pvp-flaggen.html#post61709

**Comment by Bladsn** [comment]
Jäger: 
- Salve
- Mehrfachschuss
- alle Fallen

**Comment by testear** [comment]
damit die Pappenheimer aufhören zu meckern, dass hier ohne Quelle gefixt wird:

http://wow.gamona.de/archiv/pvp/der-kampf-spieler-gegen-spieler/

**Comment by Slipru** [comment]
Schurke:
Klingenwirbel
