### ISSUE TITLE
Chromaggus Timelaps Life reduce

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1484]
**Welches Verhalten wird beobachtet?**
Die HP Reduzierung von Timelaps kann wiederstanden werden, wodurch der Tank nach ablauf von Timelaps 100% mehr Life hat als normal.

**Wie sollte es sich verhalten?**
Gibt mehrere Möglichkeiten. 
Die HP Reduzierung sollte nicht widerstanden werden oder die HP Reduzierung kann widerstanden werden.
Weis nicht welche Stimmen sollte. Auf alle Fälle sollte der Tank nach Ablauf von Timelaps auf seine Normale HP gesetzt werden und nicht Doppelt Soviel haben wenn er die HP reduce widerstanden hat.

**Schritte zur Reproduzierung**
Chromaggus pullen und warten
Reproduzieren wird Schwer da man den HP Reduce widerstehen muss und das kam seit wir BWL gehen das erste mal vor

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Workaround: Schild oder Waffe kurz ablegen und man hat wieder die normale Gesundheitswerte

http://datenbank.classic-wow.org/?npc=14020
http://datenbank.classic-wow.org/?spell=23310
http://datenbank.classic-wow.org/?spell=23311
http://datenbank.classic-wow.org/?spell=23312

**Comment by testear** [comment]
Reproduzieren ist recht einfach: Arkanresi ist das Stichwort.
Durch die Schulter-, Umhangverzauberung und MdW habe ich dem in meiner aktiven Zeit recht häufig widerstanden. 
Diesen Bug gabs da allerdings noch nicht.
