### ISSUE TITLE
Priester: Schattenverwundbarkeit

### ISSUE THREAD

**Issue by Arkona1988** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1485]
Hallo,

Welches Verhalten wird beobachtet: Schattenverwundbarkeit kommt erst zum Schluss von Gedankenschinden auf den Mob, was meines Wissens am Anfang passieren sollte.

https://www.youtube.com/watch?v=L0OOMntF01Y
Bei Minute 2:45-2:48 wird der Debuff beim Start des Kanalisierens auf den Mob gewirkt.
Bitte überprüft das doch mal :-)

Schattenverwundbarkeit: http://datenbank.classic-wow.org/?search=shadow+weaving
Gedankenschinden: (http://datenbank.classic-wow.org/?search=mind+flay)

Liebe Grüße

**Comment by 0815Priester** [comment]
"kleiner reminder"

**Comment by Fnaticshadow** [comment]
Hallo,

Welches Verhalten wird beobachtet: Schattenverwundbarkeit kommt sowohl bei Start als auch zum Schluss von Gedankenschinden auf den Mob, was. Somit also 2 Stacks pro Mind Flay. Es sollte aber nur 1 Stack bei Start des Mind Flays gewirkt werden.

Schattenverwundbarkeit: http://datenbank.classic-wow.org/?search=shadow+weaving
Gedankenschinden: (http://datenbank.classic-wow.org/?search=mind+flay)

Gruß Fnatic
