### ISSUE TITLE
PvP Infight-Modus buggy

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1486]
Welches Verhalten wird beobachtet?
Wenn man alle Gegner, mit denen man sich im Kampf befindet, im PvP tötet, kommt man nicht sofort aus'm Kampf.

Wie sollte es sich verhalten?
Wenn man alle Gegner, mit denen man sich im Kampf befunden hat getötet hat, sollte man sofort aus'm Kampf kommen.

Schritte zur Reproduzierung
1on1 im BG - Gegner töten - registrieren, dass man nicht sofort ausm Kampf kommt.

Zusätzliche Informationen 
"In PvP, a player will leave combat if they have not attacked or been attacked for 6 seconds, or all the enemy characters that have attacked you are killed." (Quelle: http://wowwiki.wikia.com/wiki/Combat)

**Comment by Sabbaer** [comment]
steht doch dran, nach 6 sekunden?

**Comment by hmmkay** [comment]
Ist ein langer Artikel. Was soll da wo stehen?

**Comment by Sabbaer** [comment]
eben, es steht nichts dran, ist der gleiche thread nur vom datum des patchstandes den wir grad spielen, auch in allen pvp videos ist es so, dass der spieler 6 sek braucht um ooc zu kommen, auch wenn er den spieler tötet

**Comment by testear** [comment]
Das ist wohl ein Bug. 

https://www.youtube.com/watch?v=0j0cVu8h5yQ
6:10 bis 6:19 ein Kampf gegen einen Gegner im PvP. Drakkus verlässt direkt nach Töten des Gegners den Kampf.

**Comment by hmmkay** [comment]
Danke. Er kommt wirklich nach jedem Kampf direkt ausm Combat-Modus. Das Video wurde zwar 2011 hochgeladen aber die Fähigkeiten sehen nach Classic aus.

**Comment by testear** [comment]
Du bist ja fast so hart wie Dago. Drakkus ist einer der bekannteren Krieger die schon in Classic Videos gemacht haben. Wenn du mehr suchst wirst du bestimmt auch den Original Upload finden. Die Mühe hab ich mir jetzt nicht gemacht.

**Comment by hmmkay** [comment]
https://www.youtube.com/watch?v=aDXXr3ad3is
Ab 4:30 sieht man, dass der Schurke sofort, nachdem er seinen Gegner getötet hat, ausm Kampf kommt.
