### ISSUE TITLE
Verteidiger des Anubsiath

### ISSUE THREAD

**Issue by fearon1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1487]
Der Schattensturm der NPCs Verteidiger des Anubisath http://datenbank.classic-wow.org/?npc=15277 hat fälschlicherweise keine 10 Meter Safe-Zone, sondern wirkt auf alle Spieler, egal wie nah man am Mob steht.

http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/AQ/aq-40-7.htm

**Comment by Slimmer2** [comment]
Wo steht da was von Safe-Zone

**Comment by 0815Priester** [comment]
AoE Shadow Bolt:
~2000 Schaden - Trifft nur Spieler, die weiter als 10y vom Mob entfernt stehen!

**Comment by Loplin** [comment]
In der Datenbank unserer Servers sind leider keine Fähigkeiten vorhanden
http://datenbank.classic-wow.org/?npc=15277

Fremde Datenbank
http://db.vanillagaming.org/?npc=15277#abilities
http://db.vanillagaming.org/?spell=14297


Aus WoWwiki
http://wowwiki.wikia.com/wiki/Anubisath_Defender

_Set 2: Shadow Storm or Thunderclap

Shadow Storm is spam of AoE shadow bolts that do ~1000 damage. Shadow resist can reduce the amount of damage taken from this spell. This spell also has a dead zone; meaning the Shadow Bolts can be avoided if you stand close. Shadow Storm has a range of 20-45 yds._

**Comment by Slimmer2** [comment]
http://datenbank.classic-wow.org/?spell=14297

**Comment by Slimmer2** [comment]
Laut euren Patchnotes habt ihr das mit der Falschen Range gefixt

**Comment by dagochen** [comment]
Nein. Je neuer die Quellen sind, desto größer ist die angegebene Range. Die Angaben fangen bei 10 Metern in Guides aus 2006 an und hören bei 20 Metern irgendwann auf. Wann genau die Änderungen kamen, ist schwer zu sagen. Wenn da aber noch jemand was genaueres findet mit exakten Datumsangaben, dann kann man da einfach an der Zahl drehen ;)

**Comment by Baraz** [comment]
In diesem Post vom [28.03.2006](http://wowwiki.wikia.com/wiki/Anubisath_Defender?oldid=112003) 19:30 Uhr wird zum ersten Mal eine konkrete Zahl für die Deadzone mit 25-45 yards angegeben, davor hieß es nur, dass eine Deadzone existiert. 
Ab dem [04.04.2006](http://wowwiki.wikia.com/wiki/Anubisath_Defender?oldid=114565) sind dort 20-45 yards eingetragen. 
Dies ändert sich für den Artikel auch nicht mehr. 
Hier stehen sich also die Aussagen von wowiki und dem Strike-us-if-you-can-Guide gegenüber.
