### ISSUE TITLE
Dropchance AQ40 Götzen

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1488]
Hallo! Ich kann nicht sagen wie es damals in Classic genau war, aber was mir hier auf dem Server komisch vorkommt, ist dass Götzen der Sonne, Nacht, Lebens und Weisen deutlich öfter droppen als die andren vier, welche so wenig droppen, dass sie den Bedarf nicht decken. Mit Google konnte ich nichts zum Thema unterschiedliche Dropraten finden.

Wenn man in die Datenbank schaut, sieht man, dass 
http://datenbank.classic-wow.org/?item=20875#dropped-by 
http://datenbank.classic-wow.org/?item=20874#dropped-by
http://datenbank.classic-wow.org/?item=20877#dropped-by und
http://datenbank.classic-wow.org/?item=20879#dropped-by

zum einen genau bei einem Mob eine sehr hohe Dropchance haben und zum andren als Questitems markiert sind, was bei den andren nicht der Fall ist. 
Wir haben inzwischen etwa 10 Leute die ihr Token nicht einlösen können, weil die Götzen dazu nicht droppen, kan man da vllt. was machen oder machen wir was falsch?
Die andren vier:
http://datenbank.classic-wow.org/?item=20878#dropped-by
http://datenbank.classic-wow.org/?item=20881#dropped-by
http://datenbank.classic-wow.org/?item=20882#dropped-by
http://datenbank.classic-wow.org/?item=20876#dropped-by

**Comment by Larnak1** [comment]
Das mit dem Markieren als Questitem hat außerdem die Folge, dass die Drops spielerspezifisch erfolgen, das heißt jeder Spieler, der die Quest hat, bekommt diesen Loot spezifisch für sich. Der PM kann diese Götzen weder sehen, noch zuweisen, unabhängig von der eingestellten Seltenheitsschwelle.

**Comment by Ataraia** [comment]
Die Götzen sollten auch immer eine Chance haben, in den Skarabäuskästen vorhanden zu sein. Das sieht man auch anhand der Datenbank, wenn man "Enthalten in" anklickt. Bisher konnten wir aus den Kästen aber immer nur die grünen Skarabäen rausziehen.

Das ganze Problem ist übrigens auch in AQ20 der Fall. Auch da haben wir Probleme, den Bedarf der Leute für ihre Tokens zu decken, weil manche Götzen überdurchschnittlich oft droppen und unsere Bank zumüllen, während andere Götzen so selten sind, dass an die 10 Leute auf der Warteliste hocken. Auch in AQ20 sollte man aus den Skarabäuskästen Götzen looten können, soweit ich das aber bis jetzt mitbekommen habe, war da auch noch nie eine drin.

Mit der Bitte um eine schnelle Antwort! Diese Probleme mit dem Loot hatten wir damals in BWL auch (Krieger T2-Armschienen) und da ist erst nach über 1 Jahr darauf reagiert worden. ;-)

**Comment by Ychap** [comment]
Dieser Bug wurd auch schon in der ClassicDB von CMaNGOS für die AQ20-Götzen gemeldet und behoben. ([classicdb/database#498](url))
Dort lag der Fehler wohl darin, dass das Feld [ChanceOrQuestChance](http://docs.getmangos.com/en/latest/database/world/creature-loot-template.html#chanceorquestchance) negativ war.

**Comment by godlike321** [comment]
Wäre halt schön wenn man sich dem annehmen könnte anstelle gar keiner Reaktion.

Gibt da atm. sicher um die 300+ Raider (aq40/aq20) die unzufrieden mit der Götzensituation sind.

**Comment by rockefaeller** [comment]
Gibt es hierzu auch ein Statement?

**Comment by 0815Priester** [comment]
Servus ,

kurz Frage, betrifft die Anpassung des Loots auch AQ40 oder nur AQ20?. Soweit ich es mitbekommen
habe passt es für AQ20. Sonntag in AQ40 sind aber halt wieder nur die üblichen Götzen gedropt. (Kann natürlich auch nur Pech gewesen sein)

Gruß

**Comment by Wosser** [comment]
Situation hat sich nicht gebessert, haben die letzten 2 IDs jeweils 2 seltene Götzen bekommen.

**Comment by Dotox** [comment]
In AQ40? Dann muss ich dort nochmal drüberschauen

**Comment by Dotox** [comment]
Hab nochmal was geändert, hoffe dass es nun funktioniert :)

**Comment by Seniorash** [comment]
Test folgt am Sonntag :+1:

**Comment by Wosser** [comment]
03.04.: Insgesamt 2 seltene Götzen, eine Götze des Todes aus ner Truhe, eine aus nem Mob. Gelootet hat ein Warri der nur die Quests für die seltenen Götzen im Log hat. Es fehlen uns inzwischen 69 seltene Götzen um alle vorhandenen Token einzulösen.

**Comment by Sheed90** [comment]
Hallo Dotox,

der Bug scheint weiterhin zu bestehen. Wir haben einfach viel zu wenig seltene Götzen, die Tokens häufen sich bei den Spielern und es wird ja nicht besser.

Laut Aussage (Ja, ich weiß, dass das keine zuverlässige Quelle ist) von früheren Spielern, waren damals nicht die Götzen, sondern die Tokens das "Problem".

Ich habe schon mit Omega gesprochen, er wollte noch ein paar Quellen dazu raussuchen, wenn welche vorhanden sind.

Gruß
