### ISSUE TITLE
AQ40: Bug Trio Bug

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1489]
Hi,

der kleinste der drei Bugs ist bei uns gestern im Raid ständig aus dem Raum gelaufen und hat dann wahllos Leute zu sich geportet. Diese wurden dann wieder von anderen Bossen zurück geportet. Das ganze ging so lange hin und her, bis einige Leute tot waren bzw. bis alle drei Käfer einfach resettet haben.

Habe mir dann nen Stream von SolidCore angesehen, da die den Encounter ja gelegt hatten. Der einzige Unterschied den ich feststellen konnte war, das SC lediglich einen Tank und einen Heiler an dem Boss dran hatten und ihr gesamter Schaden auf den Giftspuckerboss ging.
In unserer Aufstellung gingen die Range DDs auf den Giftspuckerboss und die Melees auf den kleinsten der drei Käfer.

Vermutlich hat das Problem mit der An-den-Boss-Teleport-wenn-out-of-range-Mechanik zu tun, da in meinem alten Raid der kleinste Boss zwar auch kurz aus dem Raum lief, aber wieder kam ohne das was passierte.

Grüße

**Comment by ChichiWarrior** [comment]
1. richtig schlechter Bugreport
2. Keine Regelmäßigkeit erkennbar
 - bei uns <who cares> lief alles so ab, wie es von Dotox gewollt ist.
3. Gibts nicht

Gruß

Chichi

**Comment by Karmanaz** [comment]
"der kleinste Boss" am "Giftspuckerboss"... ich bin erstaunt über die Präzision dieses Bugreports.
Ich hatte beim lesen das Gefühl sofort dabei zu sein und selbst ohne Datenbank-Kenntnisse das Problem sofort erkennen und lösen zu können.

**Comment by ircfelix** [comment]
Hab euch auch lieb

**Comment by Karmanaz** [comment]
Hier ein Video um etwas Licht in den Report zu bringen:
http://www.twitch.tv/dagochen/v/46844142 
Beginn des Kampfes ca ab Minute 5

**Comment by ircfelix** [comment]
Beitrag wird editiert außer die devs kommen so damit klar.
