### ISSUE TITLE
Quest: Kopfgeld für die Trollhalsketten nicht wiederholbar

### ISSUE THREAD

**Issue by Mathaas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1490]
Hallo,

ich habe mir damals in Classic - ich war Schüler & hatte viel Zeit - den Spaß gemacht die Wildhammerzwerge in Aerie Peak auf Ehrfürchtig zu farmen. Dazu gab es eine wiederholbare Quest - Kopfgeld für die Trollhalsketten. Ich habe mich nun mit mehreren Spielern unterhalten, die mir bestätigt haben, dass die Quest nicht wiederholbar ist. 

Außerdem droppten die Halsketten auch ohne die Quest und konnten z.b. im AH gekauft werden. 

Ich hab hier noch nie einen Bug gemeldet, bzw. einen Fehler. Habe aber mal einen Link rausgesucht und kuck gerade auch die Changelogs von Blizz durch.

Quelle: http://de.wowhead.com/quest=2880/kopfgeld-fur-trollhalsketten#english-comments
Quest in der DB: http://datenbank.classic-wow.org/?quest=2880
Item: http://datenbank.classic-wow.org/?item=9259

**Comment by Rushor** [comment]
beweis: http://www.wowhead.com/quest=2880/troll-necklace-bounty#comments:id=390426

**Comment by Slimmer2** [comment]
Folgequest heißt [geld für Trollhalsketten](http://datenbank.classic-wow.org/?quest=2881) und die sollte wiederholbar sein. Die wo du gepostet hast sollte nicht wiederholbar sein.
Steht auch im Questtext drin

> You've done it already, but we will continue to accept any troll tribal necklaces you find and are willing to turn in

**Comment by Mathaas** [comment]
Hallo Slimmer2,

Wir habens ingame getestet, man konnte die Quest nicht wiederholen. Außerdem sollten die Ketten auch ohne die Quest droppen.
