### ISSUE TITLE
Taelan Fordring spawnt nicht nach, warte seit 1 std

### ISSUE THREAD

**Issue by Cleavy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1491]
Taelan Fordring spawnt nicht nach, warte seit 1 std

**Comment by Loplin** [comment]
Bitte an die Vorlage halten
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md

außerdem is der Bugtracker meist nur für Langzeit fixes.
Wenn du sofortige Hilfe brauchst sei so gut und schreib ein ingame ticket.
