### ISSUE TITLE
Schamane Totemreichweite T1 3er Bonus und Totembeherrschung stacken

### ISSUE THREAD

**Issue by ventilb** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1492]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
[05.02.2016] Version: 1.2.7

Wie sollte es sein?
Die Beschreibung der Effekte T1 3er Bonus und des Talents Totembeherrschung besagen sinngemäß "Der Radius wird auf 30m erhöht". Ich hätte erwartet, dass die beiden Effekte nicht stacken und somit die Totems einen Radius von 30m haben. Leider habe ich dazu widersprüchliche Angaben im Internet gefunden (siehe Quellen).

Wie ist es?
Sind beide Effekte aktiv, erhöht sich der Radius auf etwa 40m. Der Radius des Totems des Erdstoßes ist sogar 50m. Auch die Skillbeschreibungen zeigen die erhöhte Reichweite an.

Links:
- 

Quelle:
http://www.wow-one.com/forum/topic/15129-the-egregious-guide-to-resto-shaman/
> 30 yards without the talent or 40 yards with the talent or T1 3 piece *(the talent and set bonuses stack on this server so it is possible to have a range of up to 40 yards)*. 

https://community.mmobase.de/schamane/5581-wiederherstellungs-schamane.html
> Totembeherrschung: ist mit T1 Setboni wirkungslos, da beides die Reichweite der Totems auf 30 Meter und nicht um 30 Meter erhöht.

Anmerkung:
Mir geht es darum zu erfahren, ob es ein gewollter Effekt ist oder es sich dabei um einen Bug handelt, bevor ich wegen Bugusing gebannt werde.

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Badorr** [comment]
Das ist kein gewollter Effekt. In Classic hat das definitiv nicht gestackt. Die Basisreichweite der meisten Totems beträgt 20 yards und kann durch das Talent **oder** den T1 3er-Bonus auf 30 yards angehoben werden. Beide Effekte überschreiben sich gegenseitig. 

Auch das Erdungs- und Erdstoßtotem (Basireichweite 30 yards) kann dadurch nicht auf eine höhere Reichweite geskillt werden.

Quellen:

1) http://wow.gamona.de/2006/05/19/weitere-nderungen-an-den-talenten-des-schamanen)

2) https://web.archive.org/web/20070904080144/http://thottbot.com/?set=207

  Report  Reply Question
Score 0.39     Vote: [-] [+] by Sould@ncer, 1.0 year ago
This set expands radius of friendly totems to 30 yds, but I already have the talent that does this. Does this mean the radius expands to 40?
Thanks for insights. 

      Report  Reply doesnt stack.
    Score 0.92     Vote: [-] [+] by Radikaal, 1.0 year ago
    no, so if u have the set bonus, put ur talent point to better use =).

3) http://wow.gamona.de/forum/threads/weitere-%C3%84nderungen-an-den-talenten-des-schamanen.82438/

Die Argumentation von Devs eines anderen Privatservers über dieses Thema (2. Post):

https://vanilla-twinhead.twinstar.cz/?issue=2943#comments
