### ISSUE TITLE
Cleave/ Heroic Strike/ Maul - zu wenig Wut

### ISSUE THREAD

**Issue by testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1493]
Welches Verhalten wird beobachtet?
Führt man Cleave, Heroic Strike oder Maul aus und hat wenn der Swingtimer abgelaufen ist zu wenig Wut für die Attacke wird der modifizierte Autohit nicht ausgeführt und man muss einen vollen Swingtimer warten bis man wieder ein Autohit ausgeführt wird.

Wie sollte es sich verhalten?
Wenn ein Cleave, Heroic Strike oder Maul aufgrund von zu wenig Wut beim zuschlagen nicht gewirkt werden kann sollte ein normaler Autohit ausgeführt werden.

Heroic Strike:
http://datenbank.classic-wow.org/?spell=78
http://datenbank.classic-wow.org/?spell=284
http://datenbank.classic-wow.org/?spell=285
http://datenbank.classic-wow.org/?spell=1608
http://datenbank.classic-wow.org/?spell=11564
http://datenbank.classic-wow.org/?spell=11565
http://datenbank.classic-wow.org/?spell=11566
http://datenbank.classic-wow.org/?spell=11567
http://datenbank.classic-wow.org/?spell=25286

Cleave:
http://datenbank.classic-wow.org/?spell=845
http://datenbank.classic-wow.org/?spell=7369
http://datenbank.classic-wow.org/?spell=11608
http://datenbank.classic-wow.org/?spell=11609
http://datenbank.classic-wow.org/?spell=20569

Maul:
http://datenbank.classic-wow.org/?spell=6807
http://datenbank.classic-wow.org/?spell=6808
http://datenbank.classic-wow.org/?spell=6809
http://datenbank.classic-wow.org/?spell=8972
http://datenbank.classic-wow.org/?spell=9745
http://datenbank.classic-wow.org/?spell=9880
http://datenbank.classic-wow.org/?spell=9881

Für andere Reporter:
Falls es noch andere beim nächsten Swing ausgeführte Attacken (Jäger hat glaube ich welche) gibt sind die wahrscheinlich auch davon betroffen. Ich hab nicht die Möglichkeit das zu testen. Falls das der Fall ist einfach die DB Links in die Comments schreiben - Ich editiere den Report dann entsprechend.

**Comment by hmmkay** [comment]
Das würde dann ja auch den Druiden mit Zermalmen betreffen. Sollte die selbe Mechanik sein.
http://datenbank.classic-wow.org/?spell=9881

**Comment by testear** [comment]
Sollte dieselbe Mechanik/ denselben Bug haben oder ist es aktuell so?

**Comment by hmmkay** [comment]
Keine Ahnung, das sollte dann am besten mal ein Druidenspieler testen.

**Comment by Horim** [comment]
Vorweg erstmal danke das du den Report erneut geöffnet hast.

Problem betrifft bei Klassen mit Wut-Ressource alle "on next swing" Attacken. Die interne Abfrage ob am Ende des Swings ob die Wut noch da ist und dementsprechend die Unterscheidung "Ja -> Style ausführen" oder "Nein -> Autohit ausführen" scheint leider zu fehlen, bzw. nicht richtig zu funktionieren. Wenn die Wut fehlt wird der autohit auch als Bär einfach ausgelassen.

**Comment by Seniorash** [comment]
gibts da eine möglichkeit das auch zu testen? oder wird das von gms/devs übernommen? aktuell kommt man nicht auf den testserver

**Comment by Horim** [comment]
Kleines Update: Es funktioniert auf dem Testserver nicht. 

Zum Beispiel: 
Bei 30 Wut wird für den nächsten Swing HS/Cleave angesetzt. Bevor der Swing durchgeht, verbraucht man via MS/BT 30 Wut und hat zu wenig Restwut für HS/Cleave -> der Autohit wird nach wie vor übersprungen.

**Comment by Dotox** [comment]
Jau, hab gestern den Testserver neu aufgesetzt. Die Änderung ist leider noch nicht drin, mach ich aber gleich - meld mich dann nochmal :)

**Comment by Dotox** [comment]
Okay, ist Online und aufgespielt.

**Comment by Seniorash** [comment]
Kann ich bestätigen, das Problem tritt auf dem Testserver immernoch auf.

**Comment by Horim** [comment]
und nochmal /push
Wäre echt nice wenn man den Bug gefixed kriegen könnte, erleichtert sowohl das Schaden machen als auch das Tanken, und zwar enorm !

**Comment by Slimmer2** [comment]
Push ist nicht erlaubt, wurde zu mir gesagt.
Hier wurde zwei Mal dass gemacht.

**Comment by Loplin** [comment]
Viele dinge sind nicht erlaubt, werden aber trotzdem nicht geahndet
hier im Buchdrucker gibt es meines Wissens nach keine "strafen" sondern nur Banns, und das auch nur wenn du richtig dummen Müll verzapfst.
Und auch den ganzen Text hier hätte ich mir sparen können, da ich nichts zum Thema beizutragen hab
Aber Leute ankreiden is auch nicht produktiv.

**Comment by Horim** [comment]
Sollte jedenfalls kein Troll sein,
der Bug als solches wurde bereits zahlreiche Male gemeldet, jedoch immer wieder nach mehreren Wochen kommentarlos geschlossen. Ich wollte verhindern das hier der Eindruck entsteht das Thema sei unwichtig oder nichtmehr aktuell um dem entgegen zu wirken.

Also bitte locker bleiben ;)

**Comment by Gipsyjodler** [comment]
Danke Dago :)

**Comment by Loplin** [comment]
Beim Drunten in Bärengestalt ersetzt Zermalmen nun nicht mehr den nächsten Autohit sondern wird parallel dazu durchgeführt. Das soll natürlich nicht so sein.
Mein level 45 Druide macht nun doppelt so viel schaden.
ich denk das is ein recht erheblicher fehler.
Kann jemand ähnliches bei Krieger bestellen?

**Comment by testear** [comment]
Beim Krieger ist alles richtig. Bitte einen neuen Report dafür eröffnen @Loplin

**Comment by Horim** [comment]
Auch von mir besten Dank, das Gameplay hat sich damit zu Gunsten aller Krieger wesentlich verbessert ;)
