### ISSUE TITLE
Heroic Strike - parieren, ausweichen, verfehlen

### ISSUE THREAD

**Issue by testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1495]
#Welches Verhalten wird beobachtet?
Wird Heroic Strike pariert, ausgewichen oder verfehlt verliert man Wut.

Wie sollte es sich verhalten?
Wenn Heroic Strike pariert oder ausgewichen wird bzw. verfehlt sollte man keine Wut verlieren. Wut sollte nur ausgegeben werden wenn getroffen oder geblockt wird.

http://wowwiki.wikia.com/wiki/Heroic_Strike?oldid=189356 
No Rage is expended if Heroic Strike is parried or dodged. Rage is expended if Heroic Strike hits or is blocked. 

Heroic Strike:
http://datenbank.classic-wow.org/?spell=78
http://datenbank.classic-wow.org/?spell=284
http://datenbank.classic-wow.org/?spell=285
http://datenbank.classic-wow.org/?spell=1608
http://datenbank.classic-wow.org/?spell=11564
http://datenbank.classic-wow.org/?spell=11565
http://datenbank.classic-wow.org/?spell=11566
http://datenbank.classic-wow.org/?spell=11567
http://datenbank.classic-wow.org/?spell=25286

**Comment by Sabbaer** [comment]
Heroic Strike is a 15 Rage attack that replaces your next melee hit. If your melee timer comes up while this is active and there are no targets, you must reactivate it. No Rage is expended if Heroic Strike is parried or dodged. Rage is expended if Heroic Strike hits or is blocked.

http://wowwiki.wikia.com/wiki/Heroic_Strike?oldid=264472
patch 1.12.1 

das da oben ist nicht 1.12.1
sry testear but <3

**Comment by testear** [comment]
KEKSE! KEKSE!

**Comment by testear** [comment]
Danke für den schnellen Fix.
Habe es jetzt getestet. Man verliert nun keine Wut mehr beim verfehlen, aber beim parieren oder ausweichen bekommt man die Wut dazu die man für einen normalen Autothit bekommen würde!

**Comment by testear** [comment]
Ich eröffne auch gerne einen neuen Report. Habe nur gedacht da dieser hier noch offen ist kommentieren ich das erstmal nur.
