### ISSUE TITLE
Hunterpet flaggt den Jäger als infight

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1496]
Welches Verhalten wird beobachtet?
Wenn das Hunterpet von einem anderen Spieler angegriffen wird oder das Pet einen anderen Spieler angreift, versetzt dieses den Besitzer in den Kampfmodus.

Wie sollte es sich verhalten?
Aktionen, die sich auf das Hunterpet beziehen, sollten den Besitzer nicht in den Kampfmodus versetzen.

Schritte zur Reproduzierung
Mit dem Hunterpet einen anderen Spieler oder einen Spieler das Pet angreifen lassen. Z.B. im Duell oder auf dem Schlachtfeld.

Zusätzliche Informationen
https://www.youtube.com/watch?v=B8grtYurXAI
Das Video stammt aus 2006, ist also eindeutig zu Classiczeiten aufgenommen worden.

Ab Minute 1:38 sieht man sehr schön, dass der Hunter selbst dann nicht infight kommt, als sein Pet den Gegner angreift. Er befindet sich erst ab dann im Kampf, als er von sich aus aktiv den Gegner mit einer seiner Attacken angreift (siehe 1:30 oder 1:46).

~~Zusatz:
Ich denke mal, dass sich dieser Sachverhalt nur auf PvP-Interaktionen bezieht und es sich im PvE anders verhält. Dazu konnte ich allerdings nur das hier finden: "All pets, with the exception of non-combat pets, will set their owner in combat when they pull aggro. ...  This is true even if the owner mounts, which will dismiss the pet and send any attacking mobs into Evade." (http://wowwiki.wikia.com/wiki/Pet). Der Eintrag bezieht sich allerdings auf einen Patch nach Classic denn Erstens ist hier davon die Rede, dass das Pet beim Aufmounten verschwindet und Zweitens ist dieser Eintrag in der WoW-Wiki Version von 2006 nicht vorhanden.~~

P.S.: Das im Video gezeigte Verhalten ist natürlich nicht ganz so nett :P

**Comment by godlike321** [comment]
Also sollen Hunter mit ihrem Pet kämpfen dürfen und selbst unbehelligt bleiben ?

Faceroll - Open pvp is going to die

**Comment by Schandmaul** [comment]
Der Hunter im Video kommt nicht in den Kampf weil der Gegner sowie das Pet  zu weit entfernt stehen.

**Comment by hmmkay** [comment]
Es steht in Schussreichweite... und das sogar deutlich, denn der Hunter hat den Gegner im Target (Spells sind rot) läuft rein, Spells sind nicht mehr rot, läuft weiter, schießt und ist dann erst im Kampf.

**Comment by hmmkay** [comment]
@Dotox 
Kannst du bitte ein kurzes Statement abgeben, was dir fehlt , dass du dich mit dem Thema befasst? Ich recherchiere gerne noch ein wenig aber momentan ist da Einiges nicht in korrekt. Man kommt z.B. als Hunter, wenn man das Pet draußen hat, 2 Sekunden später ausm Kampf als andere Klassen. Das zeigt doch eindeutig, dass da etwas nicht in Ordnung ist.

Schritte zur Reproduzierung:
Duell mit dem Hunter starten, aufs Pet klopfen, wegrennen. Die andere Klasse kommt 2 Sek. früher ausm Kampf als der Jäger.

**Comment by Dotox** [comment]
> Kannst du bitte ein kurzes Statement abgeben, was dir fehlt , dass du dich mit dem Thema befasst?

Zeit :)

**Comment by hmmkay** [comment]
Ein weiterer Punkt der für o.g. Verhalten spricht:
Das Hexerpet bringt den Hexer auch nicht infight. Sogar dann nicht, wenn der Hexer direkt daneben steht. Daher gehe ich mal davon aus, dass das Hunterpet den Hunter auch nciht in Fight setzen sollte. Egal in welcher Entfernung.
Dieses gilt sowohl für PVE als auch für PVP.

**Comment by Dotox** [comment]
Ich kann das auf dem Testserver nicht reproduzieren. Ich werde weder in den Kampf versetzt, wenn mein Pet von einem Spieler angegriffen wird oder mein Pet einen anderen Spieler attackiert.

**Comment by hmmkay** [comment]
Auf Nefarian ist es aber so, wie oben beschrieben. Vllt unterscheiden sich die Server diesbezüglich? Früher hat das Pet den Hunter nämlich infight versetzt und urplötzlich war das aufm Server geändert (ohne Patchnotes, Bugmeldung, etc.)

**Comment by Dotox** [comment]
Kannst du es zur Sicherheit noch auf dwm Testserver versuchen? Der Fehler kann auch auf meiner Seite liegen wobei daran ja nicht viel falsch zu machen ist :)

**Comment by hmmkay** [comment]
Habe es wie folgt (auf dem Testserver) getested: Duell starten, das Pet den Gegner angreifen lassen oder das Pet des Hunters angreifen.
Ergebnis: Beide male wird der Jäger in den Kampf versetzt.

Ich habe sogar die Situation in Westfall nachgestellt. Dafür das Pet abstellen, weit weglaufen und mit einem anderen Char das Pet angreifen und dann mit dem Hunter zum Pet laufen. Sobald das Pet angegriffen wird, wird auch der Jäger in den Kampf versetzt.

(Hast du das mit einem Hexer oder einem Jäger ausprobiert?)

**Comment by Dotox** [comment]
Ich hab es mit einem Jäger getestet, allerdings nicht in einem Duell da es im Video auch kein Duell ist. Die Mechaniken sind bei einem Duell nochmal etwas anders und nicht immer mit PvP zu vergleichen. Vielleicht liegt es daran, da ich so eben wie gewollt nicht in den Kampf versetzt werde.

**Comment by hmmkay** [comment]
OK, habe es jetzt auch noch mal sowohl auf Nefarian als auch auf dem Testserver mit openworld-pvp probiert (danke an den netten Gegenpart!): Das Hunterpet setzt den Hunter definitiv infight und hält ihn auch im Kampf.

**Comment by Dotox** [comment]
Hm, blizz vielleicht nicht aber die private server szene ist nochmal was anderes. Ich versteh nur nicht, warum das bei mir nicht passiert.

**Comment by hmmkay** [comment]
Wie gesagt, das war hier auch mal anders. Es gab Zeíten, da hat das Combatverhalten des Hunterpets so funktioniert, wie oben im Video zu sehen. Wenn ihr euren Code über GitHub verwaltet, könnte man rausfinden, wann das geändert wurde und dann ggf. auch nachvollziehen wodurch.
Oder man kopiert diesbezüglich den Code fürs Hexerpet. Die zählen ja ebenfalls als Combatpet und deren Combatverhalten stimmt soweit: http://www.pic-upload.de/view-30302861/HexerCombat.png.html

**Comment by hmmkay** [comment]
Haha Dotox, ich hab des Rätsels Lösung! Du wirst lachen:
Also die Hunter bzw. deren Pets auf Hordenseite funktionieren korrekt. Auf Alliseite jedoch nicht. Wie kann das denn sein :D

**Comment by Dotox** [comment]
Okay, dann hab ich wenigstens richtig getestet! :) Ist ein guter Ansatz, warum weiß ich nicht aber das lässt sich sicherlich rausfinden.

**Comment by hmmkay** [comment]
Könntest du evtl. das Label "Kein Bug" ändern? Nicht, dass das untergeht. Das Pet ist eine sehr wichtige Komponente des Jägers und bildet somit eine sehr essentielle Spielmechanik.

**Comment by Rushor** [comment]
@Dotox

**Comment by hmmkay** [comment]
push

**Comment by soda09** [comment]
Das betrifft wohl nur Nachtelfen. Mein Zwerghunter wird nicht durchs Pet infight gebracht, mein Level 11 Nachtelf-Jäger-Twink allerdings schon.

**Comment by soda09** [comment]
Wird daran denn noch was gemacht, wenn der andere Thread geschlossen wurde? Ich meine "Kein Bug" als Label ist schon nicht ganz aktuell, oder?

**Comment by soda09** [comment]
Funktioniert nicht, wie gewollt.

**Comment by Dotox** [comment]
Lad bitte ein Video hoch, wir können das Problem nach dem Patch nicht mehr reproduzieren.

**Comment by soda09** [comment]
Ok, ich habe das etwas länger getestet (kann kein Video hochladen). Es verhält sich momenten so, dass der Char in den Kampf kommt, wenn das Pet z.B. von einem Gegner angegriffen wird (oder bei anderen Interaktionen). Nach ca. 2 Sek kommt man kurz für ca. 0.5 Sek. aus dem Kampf und wird dann gleich wieder infight gesetzt.

**Comment by Dotox** [comment]
Wie gesagt, lad bitte ein Video hoch auf dem deine Ausrüstung und deine aktiven Spells / Auren zu sehen sind.

**Comment by soda09** [comment]
Hey Dotox, daran liegts: http://datenbank.classic-wow.org/?spell=21927
und http://datenbank.classic-wow.org/?spell=28757 ist dann wohl auch betroffen.

**Comment by soda09** [comment]
kurzes Feedback: Funktioniert noch nicht.

**Comment by Dotox** [comment]
Funktioniert wunderbar. Wenn es bei dir nicht geht, lad bitte ein Video hoch.

**Comment by soda09** [comment]
Hattest du beim Testen auch T1/ T2 an?

**Comment by Dotox** [comment]
Ja, hatte deinen Charakter auf dem Testserver zum reproduzieren genutzt. Aufnehmen kannst du z. B. mit OBS.

**Comment by hraesvelgr** [comment]
https://obsproject.com/download

**Comment by soda09** [comment]
https://www.youtube.com/watch?v=5QzsKUjGLuE 
Habs, wie gesagt, schon getestet: Wenn ich das T2 Set ausziehe, komme ich nicht infight. Siehe die beiden Links oben.

**Comment by dagochen** [comment]
Ich hab grad mit einem anderen Jäger gesprochen und er kommt auch infight.

**Comment by soda09** [comment]
kurzes Feedback: Funktioniert noch nicht.

**Comment by soda09** [comment]
Hey, im Forum steht, dass der Bug behoben wurde. Das Pet setzt mich aber immernoch infight, wenn ich T2 anhabe.

**Comment by dagochen** [comment]
Geduld ;)

**Comment by Dotox** [comment]
Hab nochmal was geändert.
