### ISSUE TITLE
Item: Wasser der Heiligen Quelle

### ISSUE THREAD

**Issue by VoodooDoc** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1498]
Hallo, an der Quelle (Nek´maniquellbrunnen coords: 29,62) im Schlingdornental sollte ein Item lootbar sein Namens Holy Spring Water (ID: 737) oder auf deutsch, Wasser der Heiligen Quelle. Dieses Item war auch ohne Quest lootbar! Es konnte permanent im Rucksack getragen werden und es hatte eine cooldowntime von 5 Minuten. Es hatte sich nicht verbraucht und es stellte Mana und HP wieder her! Es Teilt sich dann die Abklingzeit mit den anderen Tränken. Aber hier auf dem Server scheint es nur versuchen etwas zu bannen. Ich kann nur nicht sagen was es bannen will ob Magie, Flüche oder evl. Gifteffekte.
Hier der Link aus eurer Datenbank.
http://datenbank.classic-wow.org/?item=737

Hier ein link wo man in den kommentaren nachlesen kann was das Teil wirklich macht
http://www.wowhead.com/item=737/holy-spring-water#comments

Mfg VoodooDoc

**Comment by testear** [comment]
Der Grund warum dein letzter Report geschlossen werden ist, dass keine Quelle vor oder von 1.12.1 vorhanden ist sondern erst eine von 2.1.1 bzw von einem anderen PrivatServer. 
Wenn du willst, dass dieser Report offen bleibt solltest du die Patchchanges vom Wasser der Heiligen Quelle recherchieren. Wenn du keine findest könntest du damit argumentieren, dass das nie geändert worden ist. 
Aber so (wie es jetzt ist) wird deine Quelle als nicht zulässig angesehen.

**Comment by VoodooDoc** [comment]
Danke, wenigstens ist das jetzt mal ein vernünftiges Statement! Ich such dann mal ob ich etwas finde. Der andere Privatserver läuft übrigens auch auf dem Patchstand 1.12.1 .

**Comment by VoodooDoc** [comment]
So ich wurde fündig!
Hier stehen zwar keine Patchnotes allerdings sind die Kommentare aus dem Jahr 2006 und das entescheidende Kommentar  Zitat : " **#3 Gast im August 2006**
es bringt ca:300hp und mana is sehr nice es hat zwar 5min cd und benutzt auch trank cd aber wenn man aufm bg is oder farmt oder inner instanz is auhc hilf reich
Ps: das wassser hat 5min cd und die tränke haben trozdem nur 2min cd is echt nice" 

http://wowdata.buffed.de/item/Quest/Wasser-der-Heiligen-Quelle-737#comments 
bedeutet das es noch der Patchstand 1.12.1 ist oder sogar noch vor 1.12.1 und es wurde anscheinend soim Jahr 2007 so abgeändert, dass dieses Item nun verbrauchbar gemacht wurde.


Hier ein Link der die Releasedaten preis gibt.
26. September 2006 
http://wowwiki.wikia.com/wiki/Patch_1.12.1

13. Oktober 2006 kam dann 1.12.2
http://wowwiki.wikia.com/wiki/Patch_1.12.2

**Comment by Dotox** [comment]
Sehr gut! Jetzt noch ohne fremden privat Server link und der Bugreport wird wieder geöffnet :)

**Comment by VoodooDoc** [comment]
So besser ? ^^
