### ISSUE TITLE
AQ20 Generalleutnant Andorov

### ISSUE THREAD

**Issue by Umkaluabo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1499]
Der Generalleutnant Andorov lässt immer noch nicht mit sich handeln und man kann keine Rezepte von ihm kaufen.
Wenn man das Handelsfenster öffnen möchte steht nur immer dort: Dieser Händler mag euch nicht obwohl ich beim Zirkel des Cenarius bereits Respektvoll bin.

![wowscrnshot_022616_195332](https://cloud.githubusercontent.com/assets/17509816/13371600/67572212-dd2a-11e5-9d22-f9e3dc1bfcad.jpg)

Die Pläne: Obsidianpanzertunika sollte man ab Ehrfürchtig kaufen können.
http://datenbank.classic-wow.org/?item=22221

Die Pläne: Gezackter Obsidianschild sollte man ab Respektvoll kaufen können
http://datenbank.classic-wow.org/?item=22219

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1451
