### ISSUE TITLE
Maraudon / Das Szepter von Celebras

### ISSUE THREAD

**Issue by Brezlor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1501]
Ich habe gerade versucht in Maraudon das Szepter-Quest zu vollenden aber der NPC, der dazu ein Ritual abhalten muss, buggt und spamt "For so long I have drifted in my cursed form. You have freed me... Your hard work shall be repaid." bis er dann letztendlich despawnt.

Das Event wird nicht beendet und somit kann die Quest für das Szepter nicht abgeschlossen werden!

**Comment by Slimmer2** [comment]
Wurde bereits gemeldet
