### ISSUE TITLE
Felspirscher in Silithus falsche Einstufung

### ISSUE THREAD

**Issue by Veek4y** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1502]
Welches Verhalten wird beobachtet?
Felspirscher haben die Einstufung elite und teilen dementsprechend Schaden aus.
Wie sollte es sich verhalten?
Felspirscher sollten die Einstufung normal haben.
Schritte zur Reproduzierung
Wenn man die Mobs angreift haben sie die Einstufung elite, machen auch Schaden eines Elite-Mobs, haben aber das Leben eines Normal-Mobs.
Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?npc=11739

edit: hoffe das war mit "Vorlage" gemeint ;)

**Comment by Slimmer2** [comment]
Halte dich an die Vorlage.

**Comment by ircfelix** [comment]
Damit deine Bugreports bearbeitet werden können, musst du sie mit Quellen von damals versehen, die deine Thesen unterstützen.

**Comment by hraesvelgr** [comment]
soweit es die diskussion bisher gab:  es ist korrekt, wie der derzeitige ist-zustand ist... kann die diskussion aber grad nicht...
