### ISSUE TITLE
Flächenzauber beachten nicht die Line of Sight (LOS)

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1503]
Welches Verhalten wird beobachtet?
Flächenzauber die vom Zaubernden ausgehen wie Höllenfeuer, Frostnova oder Arkane Explosion treffen gegnerische Ziele durch Objekte (Wände, Bäume, etc.) hindurch. 

Wie sollte es sich verhalten?
Da Objekte die LOS unterbrechen und man keine Zauber (Frostblitz, Schattenblitz, etc.) durch sie hindurch wirken kann, sollten auch keine Flächenzauber durch besagte Objekte hindurchgehen.

Schritte zur Reproduzierung
Spieler A stellt sich hinter ein Objekt (z.B. eine Wand) und Spieler B castet (auf der anderen Seite der Wand) einen AoE Zauber. Spieler A erleidet Schaden.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Das wurde schon in #68 teilweise behoben. Aber nur für AoE Spells, die von oben kommen, also deren Wirkbereich vom Zaubernden ausgewählt werden kann.
Beispiele für AoE-Spells:
http://datenbank.classic-wow.org/?spell=11684
http://datenbank.classic-wow.org/?spell=10230
http://datenbank.classic-wow.org/?spell=10202

**Comment by ircfelix** [comment]
Quelle?

**Comment by hmmkay** [comment]
Naja, da es in #68 als Bug angesehen wurde, sollte es Zugeständnis genug sein.

**Comment by ircfelix** [comment]
Dort fehlen auch jegliche Quellenangaben.

**Comment by hmmkay** [comment]
Wozu braucht man 'ne Quelle, wenn die Dev's es als Bug angesehen haben?

**Comment by testear** [comment]
Nein. Du brauchst eine Quelle, weil das inhttps://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/68 ein ganz anderer Fall war. Da ging es um AEs deren Wirkungsbereich man selber auswählt. Hier geht es um AEs deren Wirkungsbereich und den PC herum ist und du keine LoS zum wirken brauchst.

**Comment by testear** [comment]
https://www.youtube.com/watch?v=YRD0p0oV54w
ab 1:08

guckste da... der Multi geht durchn Baum
