### ISSUE TITLE
Autoattack beachtet nicht die Line of Sight (LOS)

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1504]
Welches Verhalten wird beobachtet?
Automatische Angriffe beachten nicht die LOS. Sie können durch Objekte wie z.B. Bäume und Wände hindurch ausgeführt werden.

Wie sollte es sich verhalten?
Da Objekte die LOS unterbrechen und man keine Fähigkeiten wie z.B. Heroischer Schlag durch sie hindurch wirken kann, sollten auch keine automatischen Angriffe durch besagte Objekte hindurch getätigt werden können.

Schritte zur Reproduzierung
Spieler A stellt sich hinter ein Objekt (z.B. eine Wand) und Spieler B (auf der anderen Seite der Wand) greift ihn mit dem automatischen Angriff an. Spieler A erleidet Schaden.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Beispiele für meele Spells:
http://datenbank.classic-wow.org/?spell=11567

**Comment by Sabbaer** [comment]
quellen?

**Comment by testear** [comment]
Tauren konnten in der Arena sogar durch Säulen durchschlagen. 

Nur mal so nebenbei.

**Comment by Seniorash** [comment]
#227

**Comment by ircfelix** [comment]
Genau die Quelle mit Chroma kam mir auch in den Sinn.

**Comment by hmmkay** [comment]
Aufm Offi ist das mit den Objekten so: "Terrain (that is, dirt and trees) only block Line of Sight indoors. All dirt and most trees do NOT block spells or abilities when fighting outdoors." (http://wowwiki.wikia.com/wiki/Line_of_sight). Entweder wird das komplett gefixt, dass nichts durchgeht oder es muss alles durchgehen.

**Comment by testear** [comment]
"Entweder wird das komplett gefixt, dass nichts durchgeht oder es muss alles durchgehen."

Warum? Ich habe doch eine Quelle gepostet die klar dafür spricht, dass es eben nicht so ist wie du denkst.

Und 2008 war es immer noch nicht anders:
http://www.arenajunkies.com/topic/19398-tauren-swing-range-all/

**Comment by hmmkay** [comment]
Hier ist anscheinend die Philosophie, dass Spells nicht durch Objekte gehen. Warum dann Autoattacks? Entweder es dürfen auch keine Autoattacks durch Wände/ Bäume gehen oder es muss alles (Zauber & Schüsse) durchgehen können.

**Comment by ircfelix** [comment]
Warum ist die Banane krumm? Weil niemand in den Urwald zog und die Banane grade bog.

In Vanilla wow hat leider nicht alles einen Sinn. Da gabs einfach auch komplett hirnrissige Sachen. Da der Server möglichst nah am Original dran sein soll, werden Sachen halt so gefixt wie es damals war und nicht wie man es sinnvollerweise gerne hätte.

**Comment by hmmkay** [comment]
Kommt drauf an, wie Dotox jetzt entscheidet. Entweder er sieht es als "Bug" und fixt es oder nicht. Entscheidet er sich für letzteren Fall, dann bedeutet es, dass Attacken durch Objekte hindurch getätigt werden dürfen/ können. Demzufolge wird der nächste Bugreport sein, dass es nicht für alles (Zauber & Schüsse) gilt. hab dazu gerade nen Video gefunden. 
Ich denke nur, dass es leichter wäre ersteres zu fixen.

**Comment by testear** [comment]
Channeled Spells gehen auch hier durch Objekte, weil der LoS Check in der Sekunde des Wirkens ausgeführt wird und dannach nicht mehr. Jeder andere Spell (auch Meleespells) haben eine LoS Abfrage. Für Autoattack und Autoshot gilt aber was für Channeled Spells gilt.
Da ist kein Bug. Darum gibt es da auch nix für Dotox zu entscheiden.

**Comment by hmmkay** [comment]
https://www.youtube.com/watch?v=YRD0p0oV54w
ab 1:08

guckste da der Multi... geht durchn Baum

**Comment by testear** [comment]
Raff mal, dass es unterschiedliche Spells gibt, die unterschiedliche LoS Eigenschaften haben.
Channeled Spells haben am Anfange des Castens eine LoS Abfrage, dannach nicht mehr. Deshalb kannst du Mindflay nicht durch LoS laufen countern.
Wird aber ein Frostbolt gecastet und du rennst während des Castens aus der LoS findet wenn der Zauber gewirkt wird ein LoS Check statt und sagt NEIN.
Da ist kein Bug. 

Das mit dem Multishot gehört in deinen anderen Report und widerlegt diesen ja schon!

**Comment by hmmkay** [comment]
Ich hab auch nicht von "Channeled Spells" gesprochen sondern allg. von Zaubern. Mir ging es mit diesem Bugreport darum, dass eine Sache geblockt wird, die andere nicht. Und wie bereits erwähnt ist es sicher einfacher das so zu fixen, dass nichts durchgeht.

**Comment by testear** [comment]
Es interessiert aber nicht ob es einfacher oder schwieriger ist. Es interessiert ob es richtig ist.

**Comment by hmmkay** [comment]
Auf allen anderen Privatservern, auf denen ich gespielt habe ist es so, dass Objekte KEINE LOS unterbrechen (sprich man kann durch Objekte schießen). Wenn es hier anders ist, stelle ich mir doch die Frage: Warum?. Ich bin mir sicher, dass Dotox und die Devs schon mal auf anderen Servern unterwegs waren und dieses ebenfalls festgestellt haben. Daher habe ich mir gedacht, dass es zur Serverphilosophie gehört.

**Comment by testear** [comment]
Wie mein alter Lehrmeister gesagt hat:
Du denkst zu viel.

**Comment by ircfelix** [comment]
Es sollte ned drauf ankommen wie dotox entscheidet,  sondern ob die Quellen legit sind und was sie sagen. Alles andere wäre malen nach Zahlen

**Comment by Loplin** [comment]
Du meinst so wie beim beitrag ob AoEs leute flaggen sollte?
Nach meiner nachfrage nach einer quelle wurde ein beitrag aus unserem forum verlinkt

**Comment by testear** [comment]
Das ist ein unangebrachter Vergleich.
In besagtem Report geht es darum, dass Spieler gegen ihren Willen zum PvP gezwungen werden können. Und da hat bereits ein GM bestätigt, dass es Bugusing ist und auch bestraft werden kann!
Also ist es logisch das zu entfernen. 
Diese Problematik ist hier gar nicht gegeben.

**Comment by Ilikegyoza** [comment]
"Terrain (that is, dirt and trees) only block Line of Sight indoors. All dirt and most trees do NOT block spells or abilities when fighting outdoors." (http://wowwiki.wikia.com/wiki/Line_of_sight)."

War hier auf dem Server schon mal aufgespielt, wurde aber wieder geändert!

**Comment by ircfelix** [comment]
Old id vll. Von dem Beitrag?
