### ISSUE TITLE
Quest: Der Spinnengott nicht abschließbar - Tafel von Theka ohne Interaktion

### ISSUE THREAD

**Issue by Phuzak** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1505]
Server-Version: 

1.12.1 (5875)

Beschreibung:

Die Quest "Der Spinnengott" lässt sich nicht abschließen. Die Schrifttafel von Theka in Zul Farrak lässt sich zwar anklicken, jedoch geschieht nichts.

Links:

http://datenbank.classic-wow.org/?quest=2936

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Slimmer2** [comment]
Ist bereits gemeldet. Übers Handy kann ich leider nicht linken

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/676

**Comment by Phuzak** [comment]
Alles klar. Hab zwar nach Spinnengott gesucht, es aber wohl übersehen. Kann ein GM den Questfortschritt freischalten?
