### ISSUE TITLE
Priester Gedankenkontrolle ->Krieger  (Battlegrounds)

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1507]
**Welches Verhalten wird beobachtet?**
Wenn ein Priester einen Krieger im BG Mind Controled verbugged er die Fähigkeiten des Kriegers.
Das führt dazu das der Krieger z.b. nicht mehr anstürmen kann oder kein Mortal Strike/Overpower etc.
wirken kann. Der Fehler kann nur durch einen WOW-Restart behoben werden. Dieser bug tritt nur im BG auf. 

Mind Control:
http://datenbank.classic-wow.org/?spell=10912

**Wie sollte es sich verhalten?**
Der Krieger sollte natürlich nachdem Mind Control alle Fähigkeiten nutzen können.

Gruß

**Comment by Sabbaer** [comment]
nicht nur, dass man einige fähigkeiten nicht mehr benutzen kann(betrifft nicht nur den krieger), auch fällt die hp in der zeit der übernahme auf unerklärliche werte herunter und das ui verbuggt vollständig auch ohne addons aktiv

**Comment by Dotox** [comment]
Als ich die Skeram-Mechanik überarbeitet hab, konnte ich hier einen Fehler finden, der das beschriebene Problem eventuell beheben würde. Müsste man, wenn es aufgespielt wird, mal darauf achten.

**Comment by Gipsyjodler** [comment]
Das beschriebene Verhalten stimmt nicht.
Der Krieger kann sehr wohl seine Fähigkeiten noch benutzen, allerdings lösen nun alle Fähigkeiten die keinen "Global Cooldown" haben einen "Global Cooldown" aus.

z.B. Sturmangriff -> Berserkerhaltung -> "Fähigkeit ist noch nicht bereit"
oder beliebige Haltung wechseln und dann aufs Mount. gleiche Fehlermeldung.

Beides Aktionen ohne "Global CD" bzw mit gesondertem "Global CD".

Bug ist noch nicht gefixed, bitte anpassen. Andere Klassen haben auch Probleme nach dem Mind Control aber weiss nicht ob das dort die selben sind. Hab gehört manche können dann wirklich keine Fähigkeiten mehr nutzen. Kann ich aber leider nicht bestätigen bzw testen, ist aber noch ein aktuelles Problem.
Sorry, dass der Report so spät kommt war lange nicht mehr im bg ;)
