### ISSUE TITLE
NPC: Wucherborkenstampfer macht bis zu drei Schläge pro Sekunde

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1508]
Hi,

der NPC http://datenbank.classic-wow.org/?npc=11465 macht bis zu drei Schläge pro Sekunde. Das ist wohl der gleiche oder ein ähnlicher Bug wie damals bei den Elitemobs in den westlichen Pestländern.

Reproduktion: Nach DM Ost gehen, Wucherborkenstampfer angreichen und sich schlagen lassen.

Grüße

**Comment by hraesvelgr** [comment]
http://datenbank.classic-wow.org/?npc=11465#abilities "thrash"

**Comment by ircfelix** [comment]
Oh, danke! Werde das künftigen Reports genauer unter die Lupe nehmen, bevor ich dann so nen Report eröffne!

Grüße
