### ISSUE TITLE
Items: Sammlung von Items und Setboni, die nach dem Tod nicht mehr funktionieren. 

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1511]
Moin,

aktuell ist es so, das manche Items und evtl. auch Setboni (letzteres ist nur eine Vermutung, dafür aber eine naheliegende), nach dem Tod nicht mehr funktionieren wie gewollt. Diese Items muss man dann erst ablegen und dann wieder anlegen.
Es wäre schön, wenn hier eine Liste mit betroffenen Items entsteht und jeder, der etwas weiss dazu beiträgt.
Hier mal die ersten drei, die mir spontan einfallen:

Machtreaktive Scheibe (Proc funktioniert nach Tod nicht mehr) http://datenbank.classic-wow.org/?item=18168
Rune der Dämmerung (keine Geißelsteine mehr lootbar nach Tod) http://datenbank.classic-wow.org/?item=19812
Anstecknadel der Argentumdämmerung (keine Geißelsteine mehr lootbar nach Tod) http://datenbank.classic-wow.org/?item=12846

Grüße

**Comment by Sabbaer** [comment]
http://datenbank.classic-wow.org/?item=13965

**Comment by MukiDaBoss** [comment]
Elementarwetzsteine: http://datenbank.classic-wow.org/?item=18262 
Nach einem Tod funktioniert der Crit-Bonus auf der Offhand erst wieder wenn die Waffe neu equipt wurde. Bei der Mainhand scheint es zu funktionieren. 
Siehe auch #467 und #64

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/266
