### ISSUE TITLE
Datenbank: Questbelohnungen werden nicht angezeigt.

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1512]
Hi,

wenn man auf http://datenbank.classic-wow.org/?item=17759 klickt und unter Belohnung von über das Icon des Items fährt, fehlt zunächst der richtige Icon für das Item und der Link stimmt mit /?item=undefined auch nicht.
Klickt man auf die Quest Weh dir, Andorhal, so fehlt auch dort ganz unten bei den Belohnungen das Icon und der Link zur Questbelohnung.

So funktioniert das anaolog bei allen anderen Questitems auch.

Grüße

**Comment by ChichiWarrior** [comment]
Ließt du deine Bugeinträge, bevor du sie abschickst?

Schrecklich.

**Comment by Slimmer2** [comment]
Man soll kein Alkohol intus haben, wenn man Einträge schreibt.
Außerdem wird bei keiner Quest die Belohnung angezeigt, in der Datenbank

**Comment by ircfelix** [comment]
Was is euer Problem? Der Report enthält nur Wahrheit. #lerntlesen

**Comment by ircfelix** [comment]
Der Unterschied ist das ihr meckert weil ich ircfelix bin und ihr mich aus ominösen Gründen nerven/flamen wollt. Ich dagegen meckere, wenn der Bugreport falsch ist.
Sucht euch ein Hobby ihr lästigen Zecken.

**Comment by Rushor** [comment]
the hate is real :>

**Comment by ChichiWarrior** [comment]
Du bist nicht so wichtig, dass man sich Gedanken machen müsste, wer den Eintrag schreibt.
Es geht um die Qualität des Reports.

Entspricht nicht der Vorlage und deine Erklärung ist schrecklich.
Ich erinnere gerne an deinen Bug Fam Report

Gruß

Chichi

**Comment by ircfelix** [comment]
Wo, mein lieber Chichi, warst du bei all den anderen unsäglichen Bugreports? Immer musste ich deine Rolle des Bugtracker-Cops übernehmen! Und jetzt kriege ich von dir dafür aufs Mowl! Echt nich okay hey.... :-1:

**Comment by Horim** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker war das erste was ich gelesen hab als ich den Bugtracker entdeckt habe. @ #lerntlesen

**Comment by hraesvelgr** [comment]
ausserdem hat dotox bereits gesagt, dass ihm das problem bekannt ist, und er es bei einem kompletten overhaul der db fixen will.
