### ISSUE TITLE
AQ40: C'thun (Hitbox Bug)

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1513]
Hallo Entwicklerteam,

dieser Beitrag richtet sich an den Encounter C'thun in AQ40 und umfasst einen Bug, welcher die Klasse "Jäger" stark negativ beeinflusst, sowie das Ausnutzen von Rangefähigkeiten diverser anderer Klassen zu folge haben könnte. Dabei handelt es sich um die Hitbox von dem Boss C'thun.

-------------------------------------------------------------------------------------------------------------------------------

Wie sollte es sein?
C'thun sollte eine normale Hitbox besitzen, welche maximal bis zur animierten schwarzen Bodentextur von C'thun reicht. Diese sollte es grundsätzlich möglich machen, das alle Nahkämpfer (Krieger, Schurken, Paladine, Druiden und Schamanen) Ihre Fähigkeiten ohne Probleme von Reichweite, innerhalb dieser Zone, nutzen können. (Spalten, Weihe etc.)

Wie ist es?
Leider ist die Hitbox momentan so groß, das der gesamte Raum und auch der Vorraum innerhalb der Hitbox liegen. Das hat zu Folge, dass Jäger gar nicht mehr auf Ihn schießen können (Fähigkeiten inklusive) und man als Fernkämpfer (Magier, Hexer, ...) von überall in dem Raum auf C'thun Fähigkeiten einsetzen kann. (Keine Range Begrenzung) Vor allem die Jägerklasse ist dadurch sehr stark negativ beeinflusst. 

Quellen:
http://wowwiki.wikia.com/wiki/C'Thun_%28tactics%29
http://datenbank.classic-wow.org/?npc=15727

-------------------------------------------------------------------------------------------------------------------------------

Es gab sogar den Fall, das man durch das Laufen gegen die Wand, im Vorraum, den Boss automatisch in Kampf versetzen kann, da der eigene Charakter einen Autoattack auf diesen automatisch ausführt, weil man sich in dessen Hitbox hinein bewegt hat. Das Ganze führt daraufhin zum sofortigen "Wipe". 

Wir hoffen, das deser Bug möglichst schnell behoben wird, da es zu einer starken Benachteiligung für die Jäger führt.

Vielen Dank für den Support!

Mit freundlichen Grüßen
Omega :-)

**Comment by hmmkay** [comment]
Am Eingang zu stehen und Meelehits auf C'Thun zu machen ist schon geil =)

**Comment by hmmkay** [comment]
Danke für den Fix! Kann, denke ich mal /closed werden. Dann ist wieder ein Bugeintrag weniger da ;P
