### ISSUE TITLE
Demoshout – Aggro-Verhalten bei mehreren Mobs

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1515]
**Welches Verhalten wird beobachtet?**

Der Demoshout des Kriegers verursacht bei mehreren Mobs zu wenig Aggro. Es ist unmöglich diesen zum tanken von sehr vielen Mobs zu verwenden.  Der Aggro Wert von Demoshout ohne Aggro-Modifikator (oAM) beträgt 43 Aggro und wird bei Verwendung durch die Anzahl der Mobs geteilt statt bei jedem Mob den Basiswert an Aggro zu erzeugen.

**Wie sollte es sich verhalten?**

Die Aggro von Demoshout sollte im Unterschied zum Battleshout nicht durch die Anzahl der Mobs geteilt werden, sondern bei jedem Mob 43 Aggro (oAM) erzeugen. 

Z.B.: Bei 10 Mobs erhält man derzeitigt 4,3 Aggro (oAM)  auf jedem Mob, anstelle von 43 Aggro (oAM).

**Schritte zur Reproduzierung**

Mit einem Krieger in Startgebieten mehrere Mobs per Demoshout pullen und anhand des Schadens eines LvL 1 Charakters die Aggro messen. Bei mehreren Mobs wird man nur einen Bruchteil des notwendigen Schadens benötigen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

* http://datenbank.classic-wow.org/?spell=11556 das erwähnte Talent

* https://www.youtube.com/watch?v=Fy1uk0k73YA<- eindeutiger geht es nicht, trotz reflekt-gear.
Der Krieger Tank im Video bekommt direkt mit max. 2 maliger Nutzung die Aggro der Heiler und zwar unabhängig von der Anzahl der Käfer.

* http://wowwiki.wikia.com/wiki/Kenco's_research_on_threat?diff=172247&oldid=166191 <- Leider nur ein Quote zum Patchstand 1.9 (Januar 2006) als Revision im Juni 2006 

* https://forum.nostalrius.org/viewtopic.php?f=24&t=16499 <- Leider nur ein Quote im Nosta Forum zum Patchstand 1.11 (Ende July 2006) , da dieser jedoch sehr große Gemeinsamkeiten aufweist steht es allen frei diese Quelle als un-/zuverlässig zu interpretieren
_On the other hand, Demoralizing Shout gives 43 threat to **each** affected mob. As long as there are 6 or more mobs affected, it will hold aggro as well or better than Sunder Armor_

Edit: Sorry der Basiswert ist richtig. Der Fehler liegt bei mehreren Mobs.

**Comment by Sabbaer** [comment]
den genauen wert der hier implementiert ist, müsste ein dev nachguggen.

**Comment by 0815Priester** [comment]
@hreasvelgr, walte deines Amtes und gib den Bugreport den wohlverdienten "tag" :)

**Comment by 0815Priester** [comment]
Top! Übernimmt ihr das testen oder können wir uns iwann auf den Testserver logen und testen?

**Comment by Seniorash** [comment]
Bekommen wir dann noch die Möglichkeit die Sachen auf dem Testserver zu testen?

**Comment by Dotox** [comment]
Der Testserver ist momentan immer wieder online, einfach mal versuchen darauf zu verbinden, wenn ihr grad Lust habt :)

**Comment by 0815Priester** [comment]
Besteht die Möglichkeit sich ein LvL 1 Char zu machen? Momentan sind alle neu erstellen Chars LvL 60.

**Comment by Dotox** [comment]
Ja, hab ich eingestellt

**Comment by Horim** [comment]
Es klappt leider immer noch nicht, bei 2 Mobs bekommt jedes nur die Hälfte der Aggro, bei 3 nur ein Drittel etc.

**Comment by Dotox** [comment]
Hm, hast du jede Kreatur mit einem Hit in deine Aggro-Liste hinzugefügt und anschließend den Zauber gewirkt?

**Comment by Horim** [comment]
Das ist nicht möglich, da die Monster zum Testen instant sterben, wenn ich nach "Schritte zur Reproduzierung" gehe. Die Mobs werden direkt per Demoshout gepullt oder auch mit Bodypull.

**Comment by Dotox** [comment]
Okay, danke. Ich hab das System umgeschrieben, nun sollte es wie gewollt funktionieren!

**Comment by Horim** [comment]
Erstmal Danke und wieder ein kurzes Update:
In Bersi/Battlestance funktioniert es optimal bei den getesteten Mobs (2er oder 3er Gruppen), erst ab 43*0,8~35 Aggro switchen die Mobs.
In Def-Stance wird der Aggro-Modifikator jedoch mit >1,3 angesetzt. Die "Messungen" ergaben einen Wert von knapp 62 Aggro und damit folgich einen Modikator >1,4 ohne Skillpunkte im Defftree zu benutzen.

Von daher ist der Demoshout wahrscheinlich gefixed, der Aggro-Modifikator in Def-Stance ist ein anders Thema

**Comment by Horim** [comment]
So, funktioniert wie auf dem Testserver, vielen Dank :+1:
