### ISSUE TITLE
Vipernbiss bricht Streuschuss

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1517]
Welches Verhalten wird beobachtet?
Wenn ein Gegner von dem Effekt des Streuschusses (Scatter Shot) betroffen ist, wird dieser durch den Manaentzug des Vipernbisses unterbrochen.

Wie sollte es sich verhalten?
Der Desorientierungseffekt vom Scatter Shot sollte nicht durch Vipernbiss gebrochen werden.

Schritte zur Reproduzierung
Vipernbiss auf den Gegner casten und Streuschuss hinterher.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://pashtosongs.com.pk/watch/uUgCR7k6PvI/invasion-2-resurrection-hunter-pvp.html (ab 2:26)
Das Video wurde 2006 hier: http://www.warcraftmovies.com/movieview.php?id=13305, hochgeladen aber ist leider nicht mehr verfügbar und wurde später auf "pashtosongs.com" erneut veröffentlicht.

Der Gegner hat einen Vipernbiss drauf und noch 24 Mana, bekommt dann einen Streuschuss ab und verliert danach die restlichen 24 Mana, wobei der Effekt des Streuschusses nicht gebrochen wird.
Der Streuschuss zählt nicht als "richtiger" CC und sollte deshalb nicht durch Manaentzug gebrochen werden.

Scatter Shot:
http://datenbank.classic-wow.org/?spell=19503
Viper Sting:
http://datenbank.classic-wow.org/?spell=3034
http://datenbank.classic-wow.org/?spell=14279
http://datenbank.classic-wow.org/?spell=14280

**Comment by ircfelix** [comment]
Ccs sollten doch generell auch nur durch damage unterbrochen werden können. vipernbiss macht doch keinen damage sondern mana drain only, odr?

**Comment by hmmkay** [comment]
Joa, aber das wurde hier geändert.

**Comment by hraesvelgr** [comment]
@ircfelix eisfalle ist richtiger cc, wird aber durch vipernbiss gebrochen (blizzlike) 

denke mal da ist was global gelöst worden, als das gefixt wurde.

**Comment by hmmkay** [comment]
Habs eben mal auf dem Testserver getestet: funktioniert nicht wie gewollt.

**Comment by hmmkay** [comment]
push
