### ISSUE TITLE
Dev Team buggy/hohe Latenz/überlastet? !?!

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1518]
*Welches Verhalten wird beobachtet?*
Es sind über 1500 Bugreports offen, wöchentlich kommen neue hinzu und sie werden nur sehr schleichend gefixt. Anscheinend ist das Devteam überlastet. 
Eröffnet man einen Bugreport, so dauert es oft Bruchteile von Jahrhunderten, bis ein Fix dazu kommt.
Durch dieses Problem werden Leute, die gerne viel für Fixes recherchieren und somit dem Team helfen wollen, in ihrer Motivation gehemmt.

*Wie sollte es sich verhalten?*
Es sollten pro Woche wenigstens einige wenige Bugs gefixt werden, was vermutlich durch eine Aufnahme von neuen devs möglich wäre. 

*Schritte zur Reproduzierung*
1. Bugreport erstellen und Wetten darauf abschließen, in welchem Jahrzehnt der Fix dazu kommt.
2. Abwarten

Zusätzliche Informationen (Screenshots, Videos, etc.)
Leider konnte ich keine Quellen von 2005-2006 finden, doch ich bin mir ziemlich sicher das Bugs damals schneller gefixt wurden.

Nothing for ungood, ich kann echt verstehen dass ihr das in eurer Freizeit macht und auch nicht immer Zeit, Muse und Lust dazu habt, aber dann *nehmt doch verdammt nochmal Leute ins Team auf, die was machen wollen*.
Ich finds sehr schade, dass die Zahlen wie viele Leute premium haben (tippe allein auf den Leuten die ich mit premium kenne als Basis darauf das mehrere Hundert Spieler hier Premium haben) geheim gehalten werden. So erweckt es nämlich bei gleichzeitig sehr geringer Fixrate den Eindruck, dass der Server bei minimalem Arbeitsaufwand wie eine Cashcow gemolken wird. Kritik am ganzen wird eh IMMER mit "du weisst nicht was intern hier los ist" oder "sei nicht so undankbar, wir sind die Götter, die dir gnadenvoll gestatten hier zu spielen und wir machen sehr viel für den Server" zum verstummen gebracht, weil ja keiner hier seine Chars mit über 100 Tagen played opfern will (meist bringen ja die Leute die schon lange hier sind die berechtigte Kritik). 

Das ganze ist so untransparent gehalten, dass man nicht weiss wodurch der Server z.b. letztens so instabil lief (was ja den Göttern sei dank gefixt wurde) und so kann man schonmal ins Grübeln kommen, wie viel Arbeit
dahinter steckte.
Irgendwann werden sich immer mehr Spieler, die mit dem "Tempo" das hier vorgelegt wird unzufrieden sind, zusammenrotten und den Server verlassen, bis er ausgestorben ist. Das war in den vergangenen fünf Jahren bei drei sehr populären Feenix Servern so und ich für meinen Teil fände es sehr schade, wenn hier was ähnliches passiert. Der Server ist im deutschsprachigen Raum aufgrund seiner Größe und Community etwas besonderes und sollte es auch bleiben.

Ich glaube keiner kritisiert die Arbeit die ihr bisher an dem Projekt geleistet habt. Wer das täte, wäre ein Narr. Nein, es geht einzig und alleine um das Potenzial das ihr durch eure "wir machen das alles familiär und klein und lassen niemanden ins Team auch wenn er/sie fähig ist"-politik verschenkt.

Grüße

**Comment by Dotox** [comment]
Ich hab hier 450 offene Bugs stehen, wovon die hälfte sowieso nicht richtig ausgefüllt ist. Aber ok. 1500. Du tust immer so als ob du die mega connections im Bereich Entwickler hast. Dann sollen sie sich doch einfach bewerben und dir nicht nur das blaue vom Himmel erzählen, dass ist bei Leuten, die nämlich keinen Plan von der Materie haben sehr einfach :) Es gibt auch keine Entwickler-Bewerbungen im Forum.

Ich hab letztes Jahr das Kräuter-System in Wochenlanger arbeit umgeschrieben, keine Sau hat es interessiert. 2-3 Leute haben dann irgendwann mal angefangen zu testen. Und jetzt soll alles zack zack gehen oder was? Nur um das mal als Beispiel zu nehmen.

Außerdem: Null Dankbarkeit, nur gemecker, nur Forderungen, außer Shagu keine eigeninitiative und das könnte ich ewig weiter ausführen. Ist doch völlig verständlich dass wir unsere freie Zeit, die durch das Berufsleben sowieso schon sehr begrenzt ist, lieber in andere Projekte stecken, die deutlich mehr Spaß machen und in denen die Arbeit nicht mit Füßen getreten wird.

**Comment by Dotox** [comment]
Die letzten Wochen gab es durchgehend Updates aber keine Patchnotes weil ich es leid bin, Stunden zu investieren, die gefixten Sachen aufzuzählen, wovon sich dann 5 Leute bedanken obwohl es rund 1000 Leute gelesen haben. Wo sind wir denn mittlerweile angekommen? Ist es zu schwer, sich in einem kurzen Beitrag zu bedanken oder was?

Was ich damit sagen will, der großteil sieht es als selbstverständlich an, dass es Classic-WoW gibt und dass wir auch nach 4 Jahren immernoch versuchen, den Spielern ein möglich authentisches Feeling zu bieten. Und das ist ein großer Fehler, der dem gesamten Projekt 'schadet'.

Wahax ist student oder sowas in die Richtung. Er konnte am Tag locker 8 Stunden oder sogar mehr nur für den Server aufbringen, deshalb sind viele auch noch so verwöhnt davon und begreifen nicht, was für eine zeitintensive Arbeit dahinter steckt die andere eben nicht aufbringen können weil sonst die Miete am monatsende nicht gezahlt werden kann. und wenn das hier so viel geld bringen würde, würde ich das liebendgerne hauptberuflich machen gerne 14 stunden am tag. aber das ist weit weg von der realität. es gehen paypal gebühren und steuern ab, da bleiben von 4,99 ungefähr 3€ übrig und bei serverkosten von mehr als 300 euro im monat müssen schon einige premium hohlen damit das überhaupt funktioniert.

**Comment by Omegaexodus** [comment]
Ich kann Ircfelix zwar verstehen, aber dieser Vorwurf ist fraglich, was neue "schnelle" Devs im Entwicklerteam angeht. Dotox ist der alleinige Inhaber dieses Servers und er alleine sollte entscheiden, mit wem er arbeiten will und mit wem nicht. 

Wenn es doch soviel Interessiert gibt, die gerne mehr Zeit in das Project "Wow" investieren wollen, dann sollten Sie es tun und sofort Ihre Bewerbungen rausschicken! Zuerst sollte man sich aber schon mal so einige Bug-Reports hier anschauen. Wenn ich so überlege, was hier an Unprofessionalität schon gezeigt wurde und genau solche Leute dann "ständig" Änderungen erwarten oder selber wohl sich als "Developer" sehen, dann zeigt mir das nur eins, das diese Personen keine Ahnung von der Materie haben. 

Erzählen können alle immer, aber wirklich was auf dem Kasten haben dann die wenigsten, wenn es darauf ankommt. An sich muss ich Dotox vollkommen zustimmen. Viele Leute denken, es sei immer einfach und schnell gemacht, Bugs und Änderungen im System innerhalb von einigen Stunden vorzunehmen. Wie viel Arbeit und eigene Zeit (auch Ausdauer) dann aber dahinter steckt, wissen halt die wenigsten. Und genau da liegt das Problem. Erst mal selber informieren, wie man richtig ein System leitet, aufbaut und auch wartet. (Und das dauerhaft) Aber die Einsicht dazu, erst mal sich selber in den Schatten zu stellen, damit man neue Erkenntnisse gewinnt, fehlt leider vielen. 

Und auch das sich viel zu wenig dafür bedankt wird bzw. der Respekt kommt, dass diese ganze Arbeit freiwillig vollzogen wird, ist zu beanstanden. An sich muss man sich schon Fragen, wo diese Undankbarkeit herkommt?! Wenn den Leuten wirklich was an dem Server liegt, dann hört auf zu meckern und tut was, in Form von ordentlichen Bugreports und Support für die Developer!

In diesem Sinne, vielen Dank für den ganzen Support!
Mfg Omega

**Comment by Horim** [comment]
Immerhin hat der ircfelix sich die Mühe gemacht die Vorlage zu nutzen... gutes Verhalten soll man ja loben :+1: 

Zum Thema: Die wichtigsten Sachen werden relativ schnell angegangen, das Quest xy oder was auch immer mal länger buggy bleibt, stört einen Großteil der Community nicht, von daher thanks 4 the troll und in diesem Sinne mein Dank an unser Dev Team.

PS: Vielleicht in Zukunft den Bugtracker für seinen eigentlich Zweck verwenden und seinen Frust anders zur Geltung bringen ;)

**Comment by ircfelix** [comment]
Dotox, mit Leuten die Interesse zeigen meine ich z.B. dago. Klar, wir haben beteits darüber geschrieben, aber man kann ihm halt auch kleine (sichere) Aufgaben geben und ihn in deine C++ Art bugs zu fixen ein wenig einführen. Damit wäre immer noch mehr gewonnen als ihn abzuweisen, zumal du selbst das Arbeiten mit dem Server hier auch erst lernen musstest.
Selbiges gilt für meine Person. Ich habe nun sicher schon 5-6x wohl überlegt Hilfe angeboten, die auch was bringen würde, wenn man sie annähme. Natürlich müsstest du auch mich an die Art Bugs zu fixen erst heran führen. Aber nein, dann heißt es "in der Vergangenheit war dies, das und jenes" und man weist jemanden ab, der auch einfache Arbeiten ausführen könnte. Man kann halt auch nicht einfach warten bis in den Weiten des Internets zufällig der perfekte Dev (Stichwort wahax) angeschneit kommt.  Und genau diese Haltung kritisiere ich eigentlich.

Übrigens bedanken sich schon immer ein großer Batzen Leute bei den Patchnotes. Und - hatte ich Night auch schon angeboten - es können auch Leute die des Deutschen mächtig sind Patchnotes schreiben. Nur bedarf es dafür natürlich einer Zusammenarbeit beider Seiten.

**Comment by Sabbaer** [comment]
lern doch selbst mal scripten felix, wirste schnell sehen dass deine behauptungen unfug sind! finde es sehr erschreckend wie auf den devs hier rumgemeckert wird! ich glaube ich kann behaupten, einer der längsten spieler hier auf dem server zu sein, und dass der server ständig verbessert wird und ständig neue änderungen kommen, die den server deutlich verbessern. leider wird immer nur gemeckert wenn etwas nicht geht, wenn alles geht ist das selbstverständlich. danke sagen ist leider heutzutage nicht mehr so in mode, da wird lieber hass und bößwilligkeiten gestreut. sowas ist überall zu sehen, die annonymität des internets ist mehr fluch wie segen.

**Comment by godlike321** [comment]
Außerdem: Null Dankbarkeit, nur gemecker, nur Forderungen, außer Shagu keine eigeninitiative und das könnte ich ewig weiter ausführen. Ist doch völlig verständlich dass wir unsere freie Zeit, die durch das Berufsleben sowieso schon sehr begrenzt ist, lieber in andere Projekte stecken, die deutlich mehr Spaß machen und in denen die Arbeit nicht mit Füßen getreten wird.

Also ist der Server schon aufm Abstellgleis ?

**Comment by Dotox** [comment]
Felix, du hast den Grund immernoch nicht verstanden. Ich habs dir damals schon geschrieben und ich werde das Thema nicht nochmal aufrollen. Hätte man nach der ersten Absage einfach die Klappe gehalten und versucht, sich richtig nach außen zu geben bzw. sich richtig und seriös zu verhalten würden wir schon lange zusammenarbeiten. Aber jedes mal hier und überall rumzuheulen wie ein kleines unbefriedigtes Mädchen hat das Thema sowas von auf ein Abstellgleis gebracht.

Das Projekt wird sicherlich auch in Jahren noch bestehen oder solange wie es sich halt finanzieren lässt. nur wie es sich bis dahin entwickelt liegt nicht an mir oder dem Team sondern an der Community. Mittlerweile ist ein großteil schon so verwöhnt und meckert, wenn ein Bug gefixt wurde der ihnen nicht in den Kram passt. Wie kann man nur so unverschämt sein? Die Prioriäten sind klar und die Stabilität steht an erster Stelle. Das haben wir wunderbar in den Griff bekommen. Gab es irgendwie Rückmeldung in der man die Stunden an Arbeit lobt? Kaum bis gar nicht. Das ist einfach zu wenig Leute. Wer hier seit Beginn spielt weiß, dass es eine unglaubliche Entwicklung in sachen Stabilität gab. Alles andere wird nach verfügbarer Zeit, Lust und umfang des Bugs angegangen. Natürlich muss und soll auch niemand auf Knien uns anbetteln und danken, dass wir sowas anbieten und es kann gerne auch verbesserungsvorschläge und kritik geben nur eben in einem richtigen Ton und vorallem mit einem gewissen Respekt unserer Arbeit gegenüber.

Dass es auch viele gibt, die still und leise dankbar sind ist, ist mir auch bewusst nur ist diese Haltung der Personen eher kontraproduktiv. Die Community muss sich gemeinsam an die Seite des Teams stellen und gegen solche Idioten 'vorgehen' bzw. den Standpunkt vertreten, den ich gerade angesprochen hab. Es gibt schon eine Hand voll Leute, die das machen aber der andere Teil ist leider stäker weshalb man auch nur die Gülle liest, den die fabrizieren. Die Community bestimmt das Spiel, ganz einfach. Und wenn die Community nur aus kindern und undankbaren idioten besteht, gibt es langfristig keine Zukunft und es endet wie auf dem Offi mit dem Unterschied dass sich Blizzard ins Fäustchen lacht, weil sie milliarden machen und wir eben nicht, ansonsten wärs mir auch egal.

**Comment by Rushor** [comment]
du sprichst mir aus der seele <3

**Comment by ircfelix** [comment]
Mein lieber Dotox,

erstens heule ich nicht rum wie ein Mädchen, sondern versuche durch die meisten meiner Beiträge zur Blizzlikeheit des Servers beizutragen (**im Gegensatz zu anderen**, denen hier alles zu schwer ist weil man die Epics fürs Nasenbohren nicht hinterher geworfen kriegt). Genau wie die, die alles einfacher haben wollen, äußere ich hier meine Interessen. Also von daher finde ich deine Aussage deplaziert.

Aber ich glaube da sind wir generell beim Kern des Problems: Es gibt hier Spieler (zu denen ich mich zähle), die würden gerne noch mehr aus dem Projekt rauskitzeln und für dich ist das aktuelle Tempo anscheinend - das soll jetzt keine Wertung sein, sondern eine Bestandsaufnahme - okay.
Hier treffen halt zwei Welten aufeinander. Den einen reicht es wenn sie hier bisschen farmen können und dort etwas raiden oder dass hier einfach jetzt aktuell 1000+ Spieler pro Abend online sind. Den anderen ist es aber eben nicht egal, dass gewisse Sachen seit Ewigkeiten nicht (richtig) funktionieren oder es keine Patchnotes zu fixes gibt (letzteres trägt übrigens auch zu dem Eindruck das aktuell nicht so viel geschieht bei und fördert Undankbarkeit).

Desweiteren finde ich persönlich es absolut nicht wichtig, ob man z.B. zum korrigieren oder verlinken von Datenbankeinträgen, Schreiben von einfachen Fixes oder sonstigen Arbeiten **für den Server** von der Community oder der Serverleitung gefeiert oder gehasst wird (der Datenbank und dem Server ist das glaube ich auch egal). Hauptsache der Server wird weiterhin verbessert. Das ist das einzige was zählt und das hast du - meiner Meinung nach - auch noch nicht verstanden, sonst würdest du auch manchen Leuten eine Chance geben sich hier einzubringen. Mit Sicherheit wird nicht jeder - auch ich nicht - sofort die perfekten Lösungen anbieten können, da jeder (auch du und night) einmal klein und unerfahren mit der ganzen Materie angefangen hat. Aber du könntest es doch auch mal so auffassen, das es hier Leute gibt die was machen wollen und nicht dürfen. Ist das nicht schon ein großer Dank und ein großes Kompliment, das hier welche deine bisherige Arbeit und dein Projekt so sehr schätzen, das sie mit dran arbeiten wollen?

Grüße

**Comment by 0815Priester** [comment]
Ach diese Geschichte mit Dago kann man jetzt auch mal gut sein lassen. DIe beiden können sich nicht riechen und Ende. Wenn du Felix, noch ein paar Devs an der Hand hast sollen die sich bewerben. Patchnotes brauch auch kein Mensch - einfach den Bugtracker checken und gut ist.

Ich gehöre auch zu der Fraktion denen das fixen von Bugs zu langsam geht. Bei Wahax hat halt das reporten spass gemacht weil er unglaublich schnell war mit dem fixen. Kein wunder wenn er lt. Dotox Student war/ist. Es ist nunmal ein Freizeitprojekt und da hat man kein Recht darauf das dieser oder jener Bug schnell behoben wird.

**Comment by Dotox** [comment]
Das was du als "Wut" interpretierst ist einfach nur eine nüchterne Ansicht der aktuellen Lage, ohne groß auf die Aussprache zu achten.

Ich spar mir weitere Zeilen, da du ein Mensch bist, der es offentsichtlich (wie ich in meinem Beitrag vorhin schon erwähnt habe) einfach nicht verstehen möchte, warum wir gewisse Entscheidungen treffen, obwohl die Gründe dafür mehrfach genannt wurden. Über deine "Art" in Form von Beiträgen mit uns zu kommunizieren, solltest du als erstes nachdenken und dich darin verbessern, bevor wir jemals wieder in irgendeiner Weise Kontakt haben, geschweige denn deine "Hilfe" annehmen werden.

**Comment by Sabbaer** [comment]
ich hoffe dieser ganze bullshit von felix ist somit beendet und hat keine auswirkungen auf den effort und elan den du dotox und dein komplettes team hier reinsteckst. habe mit einigen leuten v.a. aus unserer gilde darüber geredet und alle, wirklich außnahmslos alle haben gesagt, dass sie sehr zufrieden sind, v.a. wie schnell die fehler in aq40 behoben wurden war erste sahne! lasst euch bitte nicht von so vereinzelten leuten den spass nehmen, der großteil der spieler ist nunmal nicht im forum aktiv und schon garnicht im buggtracker.
in diesem sinne nochmal ein rießen dankeschön an den geilsten vanilla server betreiber und sein team!

**Comment by ircfelix** [comment]
Rutsch ned auf deiner schleimspur aus sabbaer.
