### ISSUE TITLE
Frischer Tannenzweig

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1519]
Welches Verhalten wird beobachtet?
Frischer Tannenzweig kann auch außerhalb des Winterevents benutzt werden.

Wie sollte es sich verhalten?
Es sollte nur während des Events benutzbar sein.

Schritte zur Reproduzierung
Außerhalb des Events das Item benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Item: http://datenbank.classic-wow.org/?item=21212
Zauber: http://datenbank.classic-wow.org/?spell=25860
Quelle: http://wowwiki.wikia.com/wiki/Fresh_Holly

**Comment by Slimmer2** [comment]
das wurde erst später geändert.siehe History 12/2009
http://wowwiki.wikia.com/wiki/Fresh_Holly?action=history

**Comment by Slipru** [comment]
Gibt es dann zu unserem Patchstand den konservertierten Tannzweig nicht oder hat blizz es damals einfach nur spät gefixt?

**Comment by Slimmer2** [comment]
Um welches Item geht es hier eigentlich? Mistelzweig das du verlinkt hast oder doch um Konservierter Tannenzweig?
http://datenbank.classic-wow.org/?item=21212
http://datenbank.classic-wow.org/?item=21213
http://datenbank.classic-wow.org/?spell=25860

**Comment by Slipru** [comment]
Ich hatte den falschen link drin sry es geht um den frischen Tannenzweig http://datenbank.classic-wow.org/?item=21212 der normalerweise eine Lebensdauer von 14 oder 7 Tage hatte.
Deshalb gibt es den konservierten Tannenzweig http://datenbank.classic-wow.org/?item=21213 mit unbegrentzter Lebensdauer für nach dem Event.

**Comment by Slimmer2** [comment]
Die haben beide keine Lebensdauer. Einer davon ist BOP und der Andere handelbar

**Comment by Slipru** [comment]
Siehe oben aufgeführte links

**Comment by Slimmer2** [comment]
Hier mit Lebenszeit 17/12/2009 http://wowwiki.wikia.com/wiki/Fresh_Holly?oldid=2144306
hier 12 Tage später 29/12/2009 ohne Lebenszeit aber Event erforderlich http://wowwiki.wikia.com/wiki/Fresh_Holly?oldid=2153629
Hier Januar 2007 ist nicht mal was von Lebensdauer zu lesen http://wowwiki.wikia.com/wiki/Fresh_Holly?oldid=428449

Es muss also eine Änderung zwischen Juni 2008 http://wowwiki.wikia.com/wiki/Fresh_Holly?oldid=1439954 und Juli 2008 http://wowwiki.wikia.com/wiki/Fresh_Holly?oldid=1524188 gewesen sein mit der Lebensdauer

**Comment by Slipru** [comment]
Die Änderung war dann wohl nach Classic mein fail :o

**Comment by testear** [comment]
Soso - nur, dass zum Fresh Holly gar keine Patchnotes existieren.

**Comment by Slipru** [comment]
Ich bin der Meinung das die frischen schon immer eine Lebensdauer haben, allerdings finde ich leider keine Quelle.
