### ISSUE TITLE
Wundgift

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1520]
Welches Verhalten wird beobachtet?
Das Symbol von Wundgift hat das Symbol vom Verkrüppelndem Gift.

Wie sollte es sich verhalten?
Es sollte das gleiche Symbol wie Gromsblut haben

Schritte zur Reproduzierung:
Gift erstellen und Symbol anschauen

Zusätzliche Informationen (Screenshots, Videos, etc.)
Quelle: http://wowwiki.wikia.com/wiki/Wound_Poison
Items Wundgift: http://datenbank.classic-wow.org/?search=wundgift

**Comment by Slimmer2** [comment]
Etwas zu neu die Quelle
http://wowwiki.wikia.com/wiki/Wound_Poison?action=history

**Comment by Slipru** [comment]
Dein link bestätigt nur das zu jedem Patchstand das Symbol anders war^^

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1521
