### ISSUE TITLE
Verkrüppelndes Gift

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1521]
Welches Verhalten wird beobachtet?
Das Symbol vom Verkrüppelndem Gift ist falsch.

Wie sollte es sich verhalten?
Das Symbol vom Verkrüppelndem Gift sollte wie in der Quelle beschrieben sein.

Schritte zur Reproduzierung:
Gift herstellen

Zusätzliche Informationen (Screenshots, Videos, etc.):
Quelle: http://wowwiki.wikia.com/wiki/Crippling_Poison
Item: http://datenbank.classic-wow.org/?search=verkr%C3%BCp

**Comment by Slimmer2** [comment]
http://wowwiki.wikia.com/wiki/Crippling_Poison?action=history
Etwas zu neu die Quelle

**Comment by Slipru** [comment]
Dein link bestätigt nur das zu jedem Patchstand das Symbol anders war

**Comment by hraesvelgr** [comment]
die symbole sind clientseitig. da kann man nix fixen. ist zumindest meine info.

**Comment by Dotox** [comment]
Was mich daran stört ist, dass das Symbol des Zaubers ebenfalls dem des Items entspricht. Und die Zaubersymbole werden direkt aus dem Client bzw. den DBCs geladen.
