### ISSUE TITLE
Heldenhafter Stoß - Parieren u. Ausweichen

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1522]
Welches Verhalten wird beobachtet? Updated:
Wird Heroic Strike pariert oder ausgewichen erhält man die Wut, die man für den Heroic Strike ausgeben würde (12/ 13/ 14/ 15 Wut).

Das passierte durch den Fix von https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1495

Wie sollte es sich verhalten?
Wenn Heroic Strike pariert oder ausgewichen wird sollte man man weder Wut erhalten, noch Wut verlieren.

http://wowwiki.wikia.com/wiki/Heroic_Strike?oldid=189356
No Rage is expended if Heroic Strike is parried or dodged. Rage is expended if Heroic Strike hits or is blocked.

Heroic Strike:
http://datenbank.classic-wow.org/?spell=78
http://datenbank.classic-wow.org/?spell=284
http://datenbank.classic-wow.org/?spell=285
http://datenbank.classic-wow.org/?spell=1608
http://datenbank.classic-wow.org/?spell=11564
http://datenbank.classic-wow.org/?spell=11565
http://datenbank.classic-wow.org/?spell=11566
http://datenbank.classic-wow.org/?spell=11567
http://datenbank.classic-wow.org/?spell=25286

**Comment by testear** [comment]
Beim verfehlen verliert man auf dem Testserver jetzt wieder Wut. (siehe: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1495)

Beim Ausweichen oder Parieren verliert oder erhält man keine Wut. Top.

**Comment by Dotox** [comment]
Man verliert aber nicht mehr die volle Wut, sondern nur noch 3 Punkte. Das sollte man dazu erwähnen.

**Comment by testear** [comment]
Ich kanns dir gerne auf Video geben._

**Comment by Dotox** [comment]
Passt schon, ist mir nur vorhin aufgefallen als ich es nochmal geprüft hab. Gestern ist es mir nicht aufgefallen. Merkwürdig
