### ISSUE TITLE
"Schaden" wird in rot angezeigt

### ISSUE THREAD

**Issue by ChewingGumm** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1524]
Hey, 

habe eben einen Bug und seine Ursache gefunden:
Die "Schaden" Anzeige im Charakter Menü wird manchmal in rot dargestellt obwohl man 'x100%' hat.
Soweit ich das herausgefunden habe passiert das, wenn man durch einen Grund (Bei meinen Tests war es das Talent "Wutanfall" ) über 100% des Schadens kommt und danach wird auf 100% gesetzt wird. An dem Punkt wird es in rot dargestellt statt wie es sollte in weiß.

MfG & Frohe Ostern

**Comment by Slimmer2** [comment]
Das sollte nur ein Anzeigefehler sein

**Comment by ChewingGumm** [comment]
Hab ich doch geschrieben das es nur falsch dargestellt wird.
