### ISSUE TITLE
Nefarian - Corrupted Healing

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1527]
Welches Verhalten wird beobachtet?
Wenn man als Schattenpriester den Debuff [Corrupted Healing](http://datenbank.classic-wow.org/?spell=23401) bekommt und man [Vampir Berührung](http://datenbank.classic-wow.org/?spell=15286) aktiv hat, löst man den Debuff aus und killt somit die komplette Gruppe in der man sich befindet.

Wie sollte es sich verhalten?
Der Debuff [Corrupted Healing](http://datenbank.classic-wow.org/?spell=23401) sollte nur bei direkte Heilung ausgelöst werden und nicht bei passiven wie Vampir Berührung

Schritte zur Reproduzierung
Nefarian pullen und warten bis der Klassen Call Priester kommt und dann Schaden machen wenn Vampir Berührung aktiv ist.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Zusätzliches
Im Tooltip steht auch nur Direkte Heilung ist schädlich ist, und Vampir Berührung ist passiv.
Weis nur nicht ob [Erneuern](http://datenbank.classic-wow.org/?spell=139) auch zu den Passiven gehört.
http://www.wowhead.com/spell=23401/corrupted-healing#see-also-ability

•Wir akzeptieren nur Quellen, die sich nachweislich auf Classic-WoW beziehen
•Meldungen, die das geforderte Format nicht einhalten, werden kommentarlos geschlossen
•Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!

**Comment by testear** [comment]
Nein:

https://www.youtube.com/watch?v=Z3BNXjW1txA 

2:22 ca

**Comment by Slimmer2** [comment]
Vampir Berührung ist aber kein Direkter heal, sondern nur passiv.

**Comment by testear** [comment]
Du machst aktiv Schaden um zu heilen. Meiner Auffassung nach funktioniert passive Heilung nach der Aktivierung ohne, dass man Einfluss darauf nehmen kann.

Ansichtssache.

**Comment by Larirawiel** [comment]
Andererseits steht Vampirumarmung hier nicht auf der Liste:

http://www.wowhead.com/spell=23401/corrupted-healing

Grüße

**Comment by testear** [comment]
Ach. Binding Heal steht auch nicht drauf. Und erzähl mir nicht, dass der passiv wäre.
