### ISSUE TITLE
Healing Way/Pfad der Heilung - mehrfach auf ein Ziel setzbar

### ISSUE THREAD

**Issue by Badorr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1528]
**Ausgangslage**

Durch Skillen des Resto-Talents 'Healing Way', kann ein Schamane mit seiner Welle der Heilung einen Buff auf das Ziel setzen, der seinen Healing Output mit weiteren Wellen der Heilung um 6%  erhöht. Dreimal stackbar auf bis zu 18%. Der Buff hat denselben Namen wie das Talent.

**Welches Verhalten wird beobachtet?**

Momentan ist es so, dass der Buff dieses Talents mehrfach auf ein Ziel gesetzt werden kann. Und zwar von jedem Schamanen einmal. Jeder Schamane kann also seinen eigenen Buff auf das Ziel setzen und bis auf 3 Stacks hochstacken, wobei sein Healing Output gleichzeitig von den hochgestackten Buffs der anderen Schamis profitiert. 

**Wie sollte es sich verhalten?**

Es sollte nicht möglich sein, den Buff 'Healing Way' mehrfach auf ein Ziel zu setzen, sondern nur einmal. Mehrere Schamanen sollten sich einen Buff teilen und hn gemeinsam auf die genannten 3 Stacks bringen können, aber es darf nicht mehr als einen Buff geben. Dies hat früher auf dem Server wohl auch so funktioniert (siehe Quelle Nr. 2).

**Schritte zur Reproduzierung**

Man nehme z.B. 6 Schamanen, lasse sie das Talent Healing Way skillen und alle ein Ziel mit Welle der Heilung heilen. Sobald sich z.B. 6 Buffs à 3 Stacks von Healing Way auf dem Ziel befinden, schlagen mit gutem Gear und Trinkets bis zu 16k crits mit dem höchsten Rang von Welle der Heilung auf dem Ziel ein.

### Quellen: 

1) https://www.worldofcorecraft.com/content/did-shamans-heal-during-vanilla

"Healing Way was quite good since with so many healers in a 40 man the 3 stack should have nearly always been on the tank which made it competitive enough"

2) http://www.youtube.com/watch?v=7WIDKJo0vdw&t=3m40s

Curse-Video von Instructor Razuvious. Es ist nie mehr als ein Healing Way Buff auf dem Mob, das man für den Encounter per Mindcontrol tanken lässt. 

3) https://community.mmobase.de/bugtracker-archiv/3901-pfad-der-heilung.html

"Tatsächlich sollten alle Schamanen, die das Talent geskillt haben, sich einen Stack teilen, den sie auf maximal 3 stack counts (18%) bringen können. Haben das Talent alle auf dem höchsten Rang, funktioniert der Zauber richtig."

4) Diskussion von einem anderen Privatserver

http://www.wow-one.com/forum/topic/10734-healing-way/

**Spells:**

http://datenbank.classic-wow.org/?spell=25357
http://datenbank.classic-wow.org/?spell=29203
http://datenbank.classic-wow.org/?spell=29202

**Comment by Sabbaer** [comment]
heftiger bugg, jahrelang abused, palas dürfen ja auch keinen sdl mehrfach auf spieler machen, find ich extrem hart, dass sowas nicht reported wurde..... ich bin schon ein bisschen sprachlos

**Comment by Badorr** [comment]
Der Bug war ja nicht schon immer da, siehe meine Quelle. Ähnlich wie mit dem Bug beim T1-Set #1492, zu dem ich Quellen herausgesucht hab. Den Bug gab es offensichtlich früher, dann wurde er gefixt und ist seit einiger Zeit wieder da. Ich bin nocht nicht so lange auf dem Server und habe nicht miterlebt, wie das damals war. Mir wurde es nur so berichtet. 

Ich besitze auch keinen tieferen Einblick in Programmierkenntnisse und weiß nicht, warum ein gefixter Bug plötzlich wieder auftritt. Mann kann es nur reporten, wenn es einem auffällt und dazu mehr oder weniger gute Quellen gefunden hat :)

**Comment by Sabbaer** [comment]
sollte aber doch sehr schnell auffallen, wenn der tank auf einmal 4 so buffs auf sich hat....

**Comment by Bladsn** [comment]
Beweis uns erst mal, dass so ein heftiger Bug jahrelang abused wurde, bevor du große Töne von Dir gibst. 
Nur weil er vorhanden ist, heißt es nicht, dass jeder Schamane es automatisch mitgeskillt hat. 

Einfach mal einen Gang zurückschalten, bevor die Bannkeule geschwungen wird.

**Comment by ChichiWarrior** [comment]
Deswegen lassen wir seit jeher die Schamanen unterschiedlich skillen, damit das nicht passiert.

**Comment by testear** [comment]
Hauptsache nix konstruktives hinzufügen.

*pfeif* just like me
