### ISSUE TITLE
AQ40 1. Boss Skeram disconnect bug

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1529]
NPC: http://datenbank.classic-wow.org/?npc=15263

Moin, uns ist aufgefallen, dass bei dem Boss einige Leute aus dem Spiel fliegen, nachdem sie übernnommen wurden (Fähigkeit nicht aufgelistet).

Und zwar passiert das ganze, wenn die Leute sich NACH dem übernehmen bewegen. Man wird dann 3x an eine ehemalige Position zurückgesetzt und fliegt dann aus dem Game.

Ich bin mir ziemlich sicher, dass das mit dem AntiCheat Schutz zusammen hängt.
Das Problem tritt scheinbar nicht bei jedem auf, aber ihr könnt das ja mal nachprüfen.

Gruß

Sheed

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1362

**Comment by ChichiWarrior** [comment]
Passiert, wenn der, der übernommen wird diesen resistet.

**Comment by Seniorash** [comment]
Auf dem Testserver sind die Raidbosse schwierig zu testen, weil man selten einen Raid dafür zusammen bekommt. Wäre ein Testen mit einen GM/Dev möglich? Wäre auch eine Alternative Buff NPCs vor die innis zu stellen, sodass man beispielsweise genug HP hat um ohne Heilung zu überleben. Geht hierbei ja nur um das Testen einzelner Mechaniken.

**Comment by Dotox** [comment]
Denke es wäre zu viel verlangt, nur zu hoffen, dass sich ganze Raids auf dem Testserver versammeln und einen Fehler bzw. einen Bugfix testen. Bis auf Ouro kann ich das meiste mit mehreren offenen Clients selbst ausprobieren :) Große Änderungen müssten allerdings von ganzen Gruppen getestet werden. Dazu würde ich mich aber melden oder es anmerken.

Sind ja noch viele Bugfixes mit dem Label 'Dev Behoben' offen, die getestet werden können :)

**Comment by Slipru** [comment]
Der bug wurde hinsichtlich des DC bei resists gefixt, allerdings besteht der bug weiterhin wenn man nach dem mc sich sofort bewegt.
Wie im Anfangspost beschrieben wird man nach 5m Bewegeung 3 mal an die Ausgangstelle zurückgeportet und hat anschließend einen DC.

**Comment by rooty113** [comment]
Keine Ahnung ob ihr nochmal was geändert habt speziell, aber wir sind gerade mehrfach an Skeram gewiped weil in etwa jeder 2. Mindcontroll einen Disconnect verursacht hat. Ein Muster war nicht wirklich zu erkennen. Waren auch 2x in der dritten Splittphase, ab dann waren schon ~20+ Mann disconnected. Ziemlich frustrierend sowas. Video, bzw Ausschnitte kann ich nachliefern.

**Comment by orkwarrior** [comment]
hallo,

habe seit heute regelmäßig DCs nach Intercept oder Charge. Mache beides ohne Makros / Scripts. Eventuell hängt es ja mit dem Movement-Speed zusammen? Im MC in AQ bewegt man sich ja auch deutlich schneller. Vll kommen die DCs daher?

**Comment by rooty113** [comment]
Bei Hakkar im Mindcontroll das selbe Problem.

**Comment by Badorr** [comment]
Bei Hakkar dasselbe Problem. Der Boss ist noch schaffbar, falls nicht sofort einer der Tanks disconnected. Aber Skeram ist damit definitiv nicht legbar, weil nach und nach alle Tanks und Melees rausfliegen. Bitte dringend fixen!

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1645
