### ISSUE TITLE
scholomance: alexei barov

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#153]
die wachen (http://www.wowhead.com/npc=10486 ?) um alexei barov (http://datenbank.welli-it.de/?npc=10504 ) herum kann man momentan solo pullen, solange der heiler keine aggro erzeugt (ergo nicht heilt)

alle 3 npcs sollten verlinkt sein

>wowwiki:
During the fight itself he has 2 guardian mobs with him. Don't even try pulling them separately, as the three are linked.

**Comment by nightblizard** [comment]
Nicht reproduzierbar
