### ISSUE TITLE
zigurats stratholme

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1530]
Welches Verhalten wird beobachtet?
die npcs in den zigurats in stratholme greifen nicht an wenn man sie betritt bleiben "festgewurzelt" auf ihrer position stehen und machen keinen schaden
Wie sollte es sich verhalten?
alle npcs aus dem zigurat sollten aggro werden und die grp oder person angreifen und ihre position verlassen, sobald man den raum betritt
Schritte zur Reproduzierung
stratholme gehen, zigurat betreten

links kommen wenn ich die namen der npcs rausfinde, vll kann mir jmd helfen

**Comment by Slipru** [comment]
http://datenbank.classic-wow.org/?npc=10399

**Comment by Slipru** [comment]
#158
