### ISSUE TITLE
cthun tentakle raid party

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1531]
Welches Verhalten wird beobachtet?
tentakle raid party ist nicht stunbaer
Wie sollte es sich verhalten?
die tentakeln der tentakel raid party sollten stunbaer sein
Schritte zur Reproduzierung
stun auf die tentakeln 
Zusätzliche Informationen (Screenshots, Videos, etc.)
0:59 sec stunned der pala die kleine tentakel der party
https://www.youtube.com/watch?v=P1tEflLNYy8
bevor hier wieder irgendwelche behauptungen von 2012upload datum kommen, es ist der world 10th kill btw
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15727

**Comment by ChichiWarrior** [comment]
Todesmantel / Streuschuss und viele andere "Unterbrechungsfähigkeiten" funktionieren nicht.

Fehlt nur noch eine Auflistung ;-)

**Comment by Badorr** [comment]
Liegt das eventuell daran, dass die Augententakeln hier auf dem Server Bosslevel haben? Zumindest zeigen mir das sowohl das X-Perl Targetframe als auch die Standardnameplates von Blizzard das so an. Im verlinkten Video von Sabbaer kann man sehen (erahnen), dass das gestunnte Auge nur Lvl60 hat und das stimmt mit anderen C'Thun-Kill-Videos aus Classic überein.

**Comment by dagochen** [comment]
@Sabbaer @ChichiWarrior 
1. Sind http://datenbank.classic-wow.org/?npc=15726 diese hier gemeint?
2. Welche Immunitäten sollten diese haben? Oder nicht haben (je nachdem was einfacher zu sagen ist^^)
![image](https://cloud.githubusercontent.com/assets/5236186/17451824/0810bab6-5b6a-11e6-87d5-0261855ccb0d.png)

**Comment by Sabbaer** [comment]
jepp, das ist die richtige tentakel
disoriented silence stun freeze, wie auch im video zu sehen, bleed infected interruuupt daze discovery 

ich denke, das sollten alle sein

**Comment by Mafyo** [comment]
Hier gabs zu unseren Trys auch erhebliche Probleme vor alllem bei den Schurken Stuns, Nierehieb, Solarplexus und Fieser Trick hatten keine Wirkung weil Immun
