### ISSUE TITLE
Trinket Cooldowns

### ISSUE THREAD

**Issue by cyberenix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1533]
Wenn ich das Trinket "Sechdämonentasche" benutze, aktiviert sich automatisch der Cooldown von dem Trinket "Erdschlag" und dieser ist dann sogar länger als normal.

**Comment by testear** [comment]
Und mit welcher Begründung/ Quelle kommst du auf die Idee, dass es anders sein sollte und wie sollte es überhaupt deiner Meinung nach sein?
Abgesehen von fehlenden Links zur Datenbank.

So wird sich niemand um deinen "Report" kümmern. Schau dir mal die Vorlage https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker an und versuchs dann nochmal.
