### ISSUE TITLE
C'thun visiert Totem an statt Schamane

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1535]
Hier noch kurz und knapp der Bugreport bzgl. des optischen Fehlers, welcher im Forum in den letzten Tagen mehrfach erwähnt wurde.

**Ereignis:**
Bei C'thun wird der Beam in P1 nicht auf den Schamanen direkt, sondern auf eines der Totems abgefeuert. Dabei handelt es sich um einen optischen Fehler bzw. einen Fehler in der internen Rotation/Tabelle des Bosses bei der Targetauswahl. Der Schaden wird dann vom Totem auf den Eigentümerschamanen weitergeleitet. Dort werden dann Schaden und Reichweite des Beams aus unserer Sicht korrekt berechnet.

Eine Erhöhung der Wahrscheinlichkeit um den Faktor 4, dass ein Schamane getroffen werden kann, da alle Totems + Schamane in der Tabelle aufgenommen werden, konnten wir nicht feststellen.

**Wie sollte es sein:**
Die Totems sollte nicht in der Spielerliste für den Eyebeam auftauchen und den Spell auch nicht auffangen bzw. weiterleiten. 

**Quelle**
Eine Quelle kann ich dafür nicht direkt finden, jedoch gibt es keine Guides welche auf Totems hinweisen oder diese als nützlich bzgl. Eyebeams ausweisen. Weiterhin kann ich mich aus persönlicher Erfahrung auf dem Offi-Server zu Classic-Zeiten nicht daran erinnern, dass Totems von diesem Skill betroffen waren.

Fähigkeit:
http://www.wowhead.com/spell=32950/eye-beam
Dort steht auch: Can only target the player

**Comment by Dotox** [comment]
Es macht keinen Unterschied, ob der Beam auf ein Totem oder auf einen Spieler geht, da der Schaden IMMER zum Eigentümer umgeleitet bzw. an ihm berechnet wird (außer Pets). Das hab ich mit Wahax damals noch getestet.

**Comment by Karmanaz** [comment]
Für uns ist es auch kein Problem, da nur optischer Bug. Ich wollte es aber der vollständigkeithalber reporten, da es ja immer wieder im Forum auftaucht.

**Comment by Horim** [comment]
Es ist nichtmal der Eigentümer der getroffen wird, sondern derjenige Spieler, welcher am nächsten zum Totem steht. Ist mir mit meinem Krieger passiert als eines von Zahos Totems am Boss anvisiert wurde, der Beam ging auf mich und nicht auf Zaho, da ich anscheinen näher drann stand.

**Comment by hmmkay** [comment]
Bugabuse? :O

**Comment by Badorr** [comment]
Ich glaube Horim hat Recht. Bin einige meiner Videos durchgegangen und es gibt eine Stelle, wo ein Mage näher als jeder andere an einem anvisierten Totem steht und dann den Beam kassiert.

**Comment by Seniorash** [comment]
soweit ich weiß gibt es mehrere encounter die totems als Spieler erkennen (wie  beispielsweise baron geddon lange mit der Bombe ). so werden beispielsweise auch totems von sartura während des wirbelwinds oder vom Geröll bei ouro verfolgt. scheint sich also um ein grundsätzliches Problem zu handeln.

**Comment by Dotox** [comment]
Der Anzeigefehler sollte nicht mehr vorkommen.

**Comment by SirBeansen** [comment]
Also das Totem sollte wohl generell keine spells abfangen. Auch nicht den Mindflay bei den adds. 

http://badforums.com/index.php?topic=1203.0

"Grounding totems don't work in any boss encounter in the game."

"Not to be picky, but grounding totems do work on the trash during the Razorgore encounter. Of course, that's the only time they do work..." 

"Fair enough, I suppose I never noticed... naturally as you pointed out, they still don't work on the boss part of the boss fight."

Grounding Totem soll wohl damals am anfang bei huhuran den dot abgefangen haben...weil das zu stark war hat blizzard das wohl geändert...was wohl dazu führte das es bei mehreren bossen nicht mehr zu gebrauchen war.

**Comment by Seniorash** [comment]
Das Totems iwas nicht abfangen sollten ist total Offtopic
