### ISSUE TITLE
Gepullte Mobs triggern keine Aggro weiter

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1536]
**Fehler:**
Um Abkürzungen und das überspringen von Mobgruppen in Instanzen zu vermeiden, war es auf den offiziellen Servern so, dass aggressive Mobs, aktuell noch passive Mobs welche auf dem Weg zwischen Mob und Spieler standen automatisch in den Kampf (auf aggressiv) versetzt haben.
Dies ist aktuell nicht der Fall. 

**Beispiel:**
In Scholomance ist es im Reliquarium zu Beginn der Instanz möglich die Ghule unter der Brücke zu pullen und diese nach oben zu locken. Dadurch kann man einen großen Teil der Instanz umgehen und muss nicht das eigentliche Risiko eingehen die Brücke hinunter zu springen.

**Wie sollte es sein:**
z. B. müssten die Mobs aus Scholo alle noch passiven Mobs welche auf ihrem Weg zum Spieler liegen in den Kampf versetzen und dadurch müsste eine enorme Menge an Mobs auf die Gruppe zukommen.

**Quelle:**
Neben der eigenen Erfahrung das z. B. so nicht abgekürzt wurde in Scholo, sondern wenn dann die Gruppe runter gesprungen ist, konnte ich bisher nur Videos finden:

Beispiel vom Offiserver - leider bisher nur ein gutes TBC Beispiel.
https://www.youtube.com/watch?v=Fqs6DThBIlI

**Comment by testear** [comment]
Selbiges geht auch in Ubrs vor der Arena. Wenn man sich zu Awbee stellt und die Mobs an der Brücke pullt.

**Comment by Haudraufinix** [comment]
Zu erwähnen sei hierbei noch, dass der Bug in Scholo bei der Brücke nicht so reporduziert werden kann, weil da noch ein anderer Bug reinspielt (https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/802). Gibt aber genug andere inis wo man eine hintere Mobgruppe mit weitreichenden Angriffen pullen kann und alles auf dem Weg mitziehen sollte.

**Comment by Dotox** [comment]
@Haudraufinix kannst du mir das ganze vielleicht mal auf dem Testserver demonstrieren? Schreib mir einfach im Forum eine Nachricht wann du Zeit hast.

**Comment by Haudraufinix** [comment]
Habs gerade nochmal getested - scheint n undokumentierter Change zu sein, das gieng nämlich vor ein Paar Monaten noch nicht

**Comment by Haudraufinix** [comment]
Habs gerade in Scholo getested, dort tritt der bug 802 nicht mehr auf. Da wurde wohl was geändert aber nicht dokumentiert. Ich werd mich mal auf die Pirsch machen und testen, ob der überall behoben wurde ;)

**Comment by ChichiWarrior** [comment]
Ich war vor einer Woche in Scholomance und habe Flask im Labor hergestellt.

Da ich das nebenbei gemacht habe und relativ lange gebraucht habe, hatte ich Trashrespawn in der Instanz.

Meine beiden Chars waren AFK geflaggt und sind am Alchilabor gesessen. Als der Trash respawned ist, hat mich dieser nicht angegriffen, obwohl ich in den Mobs gesessen bin.
Konnte ohne Probleme im Sitzen meinen Homestone benutzen ohne Mobs zu triggern.

Gruß

Chichi
