### ISSUE TITLE
Schaden der Treantverbündeten (Steinkrallengipfel) zu hoch

### ISSUE THREAD

**Issue by Regorsen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1537]
Wie sollte es sein?
ein Sohn des Cenarius hat immer 2 dieser Begleiter bei sich, normal sollten diese Begleiter sehr moderaten Schaden machen

Wie ist es?
der Range des möglichen Schadens ist riesig und übertrifft den des Sohn des Cenarius bei weitem, dass liest sich dann ungefähr so:

Treantverbündeter trifft Euch für 17 Schaden.
Treantverbündeter trifft Euch für 67 Schaden.
Sohn des Cenarius trifft Euch für 24 Schaden.
Treantverbündeter trifft Euch für 15 Schaden.
Treantverbündeter trifft Euch für 70 Schaden.
Sohn des Cenarius trifft Euch für 23 Schaden.
Treantverbündeter trifft Euch für 19 Schaden.
Treantverbündeter trifft Euch für 73 Schaden.
Sohn des Cenarius trifft Euch für 22 Schaden.
Treantverbündeter trifft Euch kritisch: 170 Schaden.

wenn man mit etwa 800-900 Leben auf Stufe 25 rechnet kann man sich vorstellen wie schnell man hier im Dreck liegt

**Comment by Slimmer2** [comment]
Bitte Links zu den NPC und Quellen wie es sein sollte

**Comment by Dotox** [comment]
Und direkt ne Quelle. Bei 800/900 Leben ist es durchaus legitim 50+ Hits zu bekommen.

**Comment by hraesvelgr** [comment]
aber nicht von einem npc plus 2 begleiter die nichtmal elite sind.

ergo sind das dann ja 150 schaden pro x(<2) sekunden. da liegt man locker nach 5-6 sekunden im dreck. umgehen kann mans auch nicht, weil linked.

**Comment by Regorsen** [comment]
ich hab keine Quellen ... woher auch ... normal sollte der Schaden der Begleiter einem normalen Mob auf dem entsprechenden Level entsprechen, also in etwa dem des Sohnes den sie begleiten, das weicht aber wie oben gut zu sehen oft um den Faktor 3 ab 

die Schadenszahlen oben hab ich in Bärenform auf Level 26 eingesteckt ... den Crit in Katzenform

**Comment by Dotox** [comment]
Wenn du uns die Kreaturen aus unserer Datenbank verlinkst, können wir mal nachsehen :)

**Comment by Rushor** [comment]
http://datenbank.classic-wow.org/?npc=4057
http://datenbank.classic-wow.org/?spell=7993
http://datenbank.classic-wow.org/?npc=5806

**Comment by Larirawiel** [comment]
Dürfte der gleiche Grund sein wie hier:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1317

Ich habe mal einige Kreaturen mal rausgesucht und werde sie dann posten.

Grüße

**Comment by dagochen** [comment]
https://www.youtube.com/channel/UC40HrotSv1gfUX1dcZliDHA
3 Videos von dem offiziellen WoW-Server Ravencrest aus dem Jahr 2007/2008. Es handelt sich um TBC-Videos, aber er meckert auch darüber, dass der Schaden der Treants so hoch ist und "buggy" sei. Daher würde ich sagen, dass es sich nicht um einen Fehler handelt.
