### ISSUE TITLE
Brachland: Quest Gegenangriff!

### ISSUE THREAD

**Issue by testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1539]
Welches Verhalten wird beobachtet?
Die Quest Gegenangriff! funktioniert nicht, da kein Gegner spawnt sobald man die Quest annimmt.

Wie sollte es sich verhalten?
Wenn man die Quest annimmt sollten 4 oder 5 (bin nicht sicher) Verteidiger der Horde und ca 20 Eindringlinge der Kolkar spawnen und sich prügeln.
Der Spieler muss zusammen mit den Verteidigern der Horde 20 Zentauren erschlagen und dann sollte Kriegsherr Krom'zar spawnen. Dieser muss dann getötet werden und spawnt die Flagge, die man zum Abschließen der Quest aufheben muss.
Die Quest sollte ein Zeitlimit von 20 Minuten haben.

Zusätzliche Informationen:

https://community.mmobase.de/bugtracker-archiv/818-gegenangriff-elite.html
https://www.youtube.com/watch?v=710FEegH13Y ca ab 2:55
http://wowwiki.wikia.com/wiki/Quest:Counterattack! (Das ! Ausrufezeichen muss mit in den Link gesetzt werden sonst funktioniert er nicht)

http://datenbank.classic-wow.org/?quest=4021 (Die Quest Gegenangriff)
http://datenbank.classic-wow.org/?npc=9524 (Eindringling der Kolkar)
http://datenbank.classic-wow.org/?npc=9457 (Verteidiger der Horde)
http://datenbank.classic-wow.org/?npc=9456 (Kriegsherr Krom´zar)
http://datenbank.classic-wow.org/?object=164690 (Die Flagge von Krom´zar)
http://datenbank.classic-wow.org/?item=11227 (Der Loot der Flagge)

**Comment by Wosser** [comment]
Du musst den NPC nochmal ansprechen nachdem du die Quest angenommen hast.

**Comment by testear** [comment]
ups :D
