### ISSUE TITLE
Sturmwind-Greifenmeister-Disconnects on mass!

### ISSUE THREAD

**Issue by Shadoweath** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1540]
Wie der Titel bereits erwähnt scheint das Fliegen nach Sturmwind per Greifenmeister zu einer Reihe von disconnects und Wow-Errors zu sorgen. Dies scheint aber nur zu passieren wenn in SW ziemlich viele Spieler sind, wie z.B. beim Ony Buff. 

Sobald man landet sieht es so aus als ob der Server einen DC hat. Es tut sich nichts mehr aber man kann sich weiterhin bewegen. Loggt man sich aus und wieder ein wird man instant gekickt vom Server. Meist kommt auch eine Fehlermeldung wie sie beim fahren von einem Schiff auftritt. Was aber sehr seltsam ist, ist das sobald man runter in den Teich springt neben der Brücke, in SW, und das Spiel ausmacht und wieder anmacht kommt man raus aus den Disconnects bzw. den Fehlermeldungen.

Ich schätze er tritt nur auf bei einer Masse an Spielern. Es trifft sowohl Spieler mit Premium als auch ohne. Der Bug tritt nur in SW beim Greifenmeister auf. Sonst habe ich ihn nirgends gesehen. Wir hatten einen weiteren Fall bei einem Spieler im BWL Raid aber ich schätze dieser wurde durch den Rollback vorher verursacht. 

Vielleicht häufen sich die Meldungen bei anderen Spielern an anderen Orten. Gut möglich, dass der Bug Global auftritt. Ich reiche bei Gelegenheit ein Video nach, sofern ich diesen Bug noch einmal auslösen kann. Diesen würde ich dran drunter pinnen oder an den jeweiligen GM übers Forum schicken (Youtube-Link)

Liebe Grüße
Shadoweath

**Comment by Dotox** [comment]
Wäre super, wenn das auch noch die ganzen anderen Spieler in Stormwind bestätigen könnten :)

**Comment by Shadoweath** [comment]
Das Problem tritt nur bei einer hohen Spielerzahl in Sturmwind auf. Sonntag/Montag mache ich ein Video davon wenn möglichst viele Spieler in Sturmwind auf den Ony-Buff warten. "Hoffentlich" löse ich ihn erneut aus. Ich melde mich frühstens Montag nochmal mit einem Video.

**Comment by Loplin** [comment]
Könnte möglicherweise mit dem ZG uff zusammenhängen den sich viele Spieler davor abholen
Dieser erhöht die Laufgeschwindigkeit (http://datenbank.classic-wow.org/?spell=24425)
Allzu oft getestet hab ich es noch nicht, aber ich meine bei mir treten die disconnects nur auf wenn ich den ZG uff habe

**Comment by Shadoweath** [comment]
Durchaus möglich @ Loplin. Ich für meinen Teil hatte bei allen Vorkommnissen bisher keinen ZG-Buff aktiv aber vielleicht gibt es mehrere Möglichkeiten ihn auszulösen.

**Comment by Dotox** [comment]
Ich mach hier mal zu, wenn es noch viele andere Spieler betrifft, wäre es hilfreich, wenn sie sich melden würden. Ansonsten gehe ich davon aus, dass das Problem bei dir liegt.

**Comment by Slimmer2** [comment]
Hatte eben auch DC wie ich nach SW geflogen/geportet bin. Hab Premium.
