### ISSUE TITLE
[Druide] Talent: Urfuror

### ISSUE THREAD

**Issue by Saguno** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1542]
Spell-ID: 16961
_Welches Verhalten wird beobachtet?_
Bei einem ausgeführten kritischen Treffer regeneriert der Spieler 5 Wutpunkte.
_Wie sollte es sich verhalten?_
Laut Tooltip sollten bei einem erhaltenen kritischen Treffer 5 Wutpunkte regeneriert werden.
_Schritte zur Reproduzierung_
Mit einem Druide inkl. geskilltem Talent, Mobs kritisch treffen.
_Zusätzliche Informationen (Screenshots, Videos, etc.)_
http://fs5.directupload.net/images/160411/rcv27v2q.jpg

**Comment by hmmkay** [comment]
Erhalten bedeutet in dem Fall, dass du einen landest. Ließ dir mal englische Guides durch, dann wird das klarer.

**Comment by Saguno** [comment]
Okay also ist das einfach schlecht übersetzt(?) Für mich heißt "to get a" bekommen/erhalten.
Kannst einen der Guides verlinken - ich werde irgendwie nicht fündig...

**Comment by hmmkay** [comment]
Ist schon ewig her. Aber da wird z.b. beschrieben warum der Druide ein guter Offtank ist. Er braucht nämlich nicht so viel Hits wie ein Krieger zu kassieren, um Wut zu generieren. Die kommt nämlich zu einem großen Teil über seinen Dmg und vorallem auch Krits, die er landet.

**Comment by Sabbaer** [comment]
link @hmmkay sonst geh ich davon aus, dass die mechanik wie bei pala und krieger funktioniert

**Comment by hmmkay** [comment]
Wieso muss ich was linken? Der Post enthält 0 Quellen :D

**Comment by testear** [comment]
http://www.ign.com/faqs/2005/world-of-warcraft-druid-faq-674483

You need to put 3 Talent points on Sharpened Claws before you can 
use this talent, anyway, your critical chances of your Bear 
attacks will give you an additional 5 Rage points. Max this one, 
too.

**Comment by Saguno** [comment]
Danke dir! Also wirklich nur eine unklare Übersetzung.
Damit /closed
