### ISSUE TITLE
Kräuterpopulation Ashenvale

### ISSUE THREAD

**Issue by Azilut** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1543]
Am Strand von Ashenvale gibt es eindeutig viel zu viele Würgetang. Dort sollten sich eigentlich Kisten für den Schurken zum Schloßknacken-Skillen befinden aber es gibt dort nur 1 Kiste. Anscheint ist da eine Verwechslung aufgetreten.

**Comment by Wosser** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md
