### ISSUE TITLE
Kalimdors Rache 2.

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1544]
Welches Verhalten wird beobachtet?
die waffe kalimdors rache http://datenbank.classic-wow.org/?item=21679 wurde vor kurzem gefixt https://community.mmobase.de/updates-changelog/9408-update-10-04-2016-a.html die proc chance passt jetzt aber von einer spell damage skalierung ist nix zu bemerken bei knapp 500 spd mit aktivem zg trinket 
http://www.wowhead.com/item=21679/kalimdors-revenge#comments (With 446 spell damage it crits for roughly 700-750.)

**Comment by dagochen** [comment]
Grad ausgiebig getestet. Funktioniert einwandfrei und wir sind auf vergleichbare Ergebnisse gekommen.
