### ISSUE TITLE
Reitlehrer-Bug

### ISSUE THREAD

**Issue by Shadoweath** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1545]
Reitlehrer Bug-DC vom Server

Ich kratze mir gerade irgendwie nur am Kopf... Wollte an sich nur ein neues Reittier kaufen aus Darnassus, als Zwerg, und habe ausversehen den Reitlehrer-Heinz angesprochen und werde, siehe Video, auf lustige Art und Weise des Servers verwiesen xD

Wie es sich wohl verhalten sollte... hmmm. Vermutlich sollte es keinen Spieler, wenn man ihn mit Reittier anspricht, vom Server kicken.

Wenn man den Bug auslösen will reitet man einfach mal mit einem Mount zu ihm und klickt ihn an. Ich denke das reicht.

Ein Video kommt in wenigen Minuten dazu. Es sieht aufjedenfall sehr lustig aus, kann ich sagen :clap:

**Comment by Shadoweath** [comment]
http://imgur.com/Y1XnHkN

Ok das ist sicher nicht normal. Ich reite, laut Buffleiste, auf 5 verschiedenen Mounts...
Ein weiterer Spieler kam dazu und hat gleiches getestet. Bei ihm ging es nicht. Ich habe sämtliche Szenarien daraufhin durch gespielt. Mit Addons, ohne Addons, WDB Order gelöscht und den alten später wieder rein geschoben. Das Ergebnis blieb das gleiche.

**Comment by Dotox** [comment]
Hey, hast du einen Zauber neben dem Rudel aktiv, der deine Geschwindigkeit beeinflusst?

**Comment by Shadoweath** [comment]
Nein. Man löst ihn nur auf einem Reittier aus. Der gute lässt einen ja absatteln, sodass es dazu kommt.
Er ist auch nur über ein Reittier auszulösen. Dann kann man aber wenn man will die gesamte Buffleiste mit Reittieren füllen. 
Dazu sei aber gesagt, dass dieser Fehler nur bei ganz wenigen auftaucht.

**Comment by Dotox** [comment]
Das muss an einem passiven Zauber z. B durch ein Setbonus passieren. Deswegen ist es auch nicht bei allen so.

**Comment by Shadoweath** [comment]
Am Setbonus liegt es nicht. Das habe ich gerade getestet.
http://imgur.com/A3Q1Izn

Scheint wohl an mir zu liegen. Mit meinem Druiden habe ich selbiges getestet. Auch beim Druiden geht es wunderbar. Ich meine solange keiner den Bug ausnutzt, sofern ihn überhaupt 1% der Spieler haben, kann die Lösung, wenn es eine gibt, auch warten.

**Comment by Gipsyjodler** [comment]
Habe das selbe Problem bemerkt. Ich habe folgendes Verhalten beobachtet: Ich bin auf dem Mount und spreche einen Lehrer für Berufe an(Ingi IF). Dann werde ich abgemounted sobald ich "Ich benötige eine Ausbildung" drücke. Jedoch habe ich immernoch den Mount Buff. Bewege ich mich dann ein paar Meter hab ich lags und ich bekomm einen disconnect. Entferne ich den Mount Buff habe ich keinen disconnect. Hab auch die Sets gewechselt und hab auch keine sonstigen Buffs als Krieger^^
Sollte man beim ansprechen vom Mount fliegen? Kann ich mir nicht vorstellen.

Hoffe ich konnte euch damit helfen 
MfG Gipsy

**Comment by Dotox** [comment]
Danke @Gipsyjodler! Das bringt mich auf eine Idee. Melde mich demnächst wieder.

**Comment by Sheed90** [comment]
Der Bug scheint weiterhin zu bestehen. Ich hab dazu mal ein Video gemacht.

https://youtu.be/_01mN28guew

Gruß

**Comment by Dotox** [comment]
@Sheed90

Kann das leider nicht reproduzieren - mich wirft's wie vorgesehen, vom Mount und entfernt den Buff.

**Comment by Sheed90** [comment]
Kein Ding, das scheint sich inzwischen durch einen anderen Bugfix gefixed zu haben. :-D
Vote4close

**Comment by dagochen** [comment]
Dem komme ich gerne nach.
