### ISSUE TITLE
Fehler beim entpacken der Zip-Datei.

### ISSUE THREAD

**Issue by Donkogan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1547]
Ich habe den "DOWNLOAD: Classic-WoW 1.12.1 Client Windows (Windows)" bereits mehrmals heruntergeladen. Bei jedem extrahieren erscheint ein anderer Fehler. Da ich die vorigen 2 Male den Ordner komplett gelöscht habe, finde ich beim letzten Mal folgenden Fehler:

CRC-Fehler in Datei "World of Warcraft 1.12.1\Data\patch.MPQ"

Bis jetzt ist es mir nicht gelungen, das Spiel erneut zu installieren.

Update: Beim erneuten extrahieren erscheint ein neuer Fehler:
"Extrahiere World of Warcraft 1.12.1\Data\patch.MPQ 	Fehler: In Ausgabedatei kann nicht geschrieben werden"

Update2: Nach dem 4. herunterladen und ersten entpacken konnte die oben erwähnte Datei erfolgreich entpackt werden. Dann kam folgender Fehler:
"Extrahiere World of Warcraft 1.12.1\Data\terrain.MPQ 	Fehler: CRC-Fehler in Datei "World of Warcraft 1.12.1\Data\terrain.MPQ" im Archiv "C:\Users\Computer\Downloads\ClassicWoW1.12.1DEWin.rar""

**Comment by Dotox** [comment]
Hat eigentlich nichts im Bugtracker zu suchen. Du lädst die Datei einfach nicht vollständig herunter. Achte darauf, dass der Browser nicht geschlossen wird und der PC nicht in den Ruhemodus wechselt.

**Comment by Slimmer2** [comment]
GM Sinau hat auch einen Mirror in der Signatur.
