### ISSUE TITLE
Priester Gedankenkontrolle

### ISSUE THREAD

**Issue by desert2k** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1548]
Welches Verhalten wird beobachtet?
1)Das Leben von übernommenen NPCs bleibt auf 100%, wenn man mit ihnen kämpft und sie schaden bekommen. Sie verlieren es dann schlagartig, wenn man dem übernommenen NPC selbst schaden zufügt, nachdem Gedankenkontrolle ausgelaufen ist.

2) Wenn man 2 NPCs mithilfe von Gedankenkontrolle miteinander kämpfen lässt, kämpfen diese manchmal weiter, nachdem man Gedankenkontrolle abbricht oder es ausläuft.

3)Manchmal kann man die Spells von den übernommenen NPCs nicht benutzen, weil stattdessen versucht wird die eigenen Spells zu benutzen - als folgedessen steht dann da, es wird bereits eine andere Aktion ausgeführt, was auch bleibt nachdem Gedankenkontrolle abbricht oder ausläuft. Das heißt, man kann danach auch nichts mehr selbst Casten, da wiederum die Meldung kommt, dass bereits etwas anderes ausgeführt wird.

Getestet und Beobachtet mit Gedankenkontrolle Rang 1
Mind Control:
http://datenbank.classic-wow.org/?spell=10912

Wie sollte es sich verhalten?
1) Das übernommene NPC sollte ganz normal sein Leben verlieren.

2) Nachdem Gedankenkontrolle ausläuft, sollten beide nicht mehr weiter kämpfen sondern man sollte selbst die aggro auf sich haben.

3) Man sollte ganz normal die Spells von dem NPC benutzen können und danach auch seine eigenen.

**Comment by Jessienia** [comment]
1) Ist lediglich ein Anzeigebug.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1507
