### ISSUE TITLE
Wachen geben Falsche infos

### ISSUE THREAD

**Issue by vollkommenegal** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1549]
Habe gerade eine Wache in Kharanos angesprochen um zu erfahren wo ein Berbau leher ist. Beim Fragen nach Bergbau antwort er mit Kürschner, beim Fragen nach Kürschner mit Schneider usw.

**Comment by testear** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

Beachten oder Close.

Nebenbei:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451
