### ISSUE TITLE
Schlachtruf der Drachentöter

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#155]
Welches Verhalten wird beobachtet?
- Wenn man den Ony Kopf abgibt in sw/og bekommt man als Hunter nicht die 140 attack power auf range angerechnet.

- Nefarian erzeugt gar kein Schlachtruf der Drachentöter buff beim abgeben.

Wie sollte es sich verhalten?
- Man sollte auch als Hunter auf range die attack power bekommen.

- Nefarian Kopf sollte auch einen buff geben.

Schritte zur Reproduzierung

Ony/Nef kopf abgeben.

Zusätzliche Informationen (Screenshots, Videos, etc.)

**Comment by SirBeansen** [comment]
push

**Comment by dagochen** [comment]
@Dotox close pls
