### ISSUE TITLE
Quest "Säuberung der Höhlen" geht nicht

### ISSUE THREAD

**Issue by tedbash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1551]
Server-Version:
Aktuell?

Wie sollte es sein?
Quest sollte da sein.

Wie ist es?
Quest ist nicht da.

Links:
http://de.wowhead.com/quest=26870/sauberung-der-hohlen

Quelle:
Wowhead, Classic Database, Spielerwissen

**Comment by Slimmer2** [comment]
Seht hohe Quest ID, glaube nicht das es die zu Classic schon gab.
Ist auch nicht in unserer Datenbank vorhanden.
Und Laut WOWhead, jetzt halt dich fest.
Hinzugefügt zu Patch 4.0.3
