### ISSUE TITLE
AQ40 Götzen die 2. #1488 

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1552]
#Moin, Weiterführung von: #1488

Welches Verhalten wird beobachtet?
Aktuell enthält der große Skarabäuskasten viel zu wenig Götzen. Die Chancen bitte [diesem](http://datenbank.classic-wow.org/?object=180690) Link entnehmen. 

Es ist immer eine Skarabäustasche + maximal **1** Götze von jedem Typ, von dem der Looter des Kastens die Quest hat. 

Die Chancen sind aktuell zu gering für folgende Götzen

- [Götze der Wiedergeburt](http://datenbank.classic-wow.org/?item=20878) 8 %
- [Götze des Lebens](http://datenbank.classic-wow.org/?item=20879) 11 %
- [Götze des Krieges](http://datenbank.classic-wow.org/?item=20882) 11 %
- [Götze der Weisen](http://datenbank.classic-wow.org/?item=20877) 16 %
- [Götze des Kampfes](http://datenbank.classic-wow.org/?item=20881) 19 %
- [Götze der Sonne](http://datenbank.classic-wow.org/?item=20874) 24 %
- [Götze des Todes](http://datenbank.classic-wow.org/?item=20876) 24 %

Außerdem kann jede Götze maximal 1x enthalten sein.

Die Kiste verschwindet nach dem Looten nicht, da wahrscheinlich noch Götzen enthalten sind, die der Looter nicht sieht, weil er keine Quest hat, die diese Götzen fordert.

Die Kiste wird nicht aufgeschlossen, sodass immer nur der Looter, der zuvor einen Schlüssel hatte reingucken kann.

Wie sollte es sich verhalten?
Der Kasten sollte immer eine Skarabäusetasche + **1-3** der folgenden Götzen enthalten.

- [Götze der Wiedergeburt](http://datenbank.classic-wow.org/?item=20878) 28 %
- [Götze des Lebens](http://datenbank.classic-wow.org/?item=20879) 28 %
- [Götze des Krieges](http://datenbank.classic-wow.org/?item=20882) 28 %
- [Götze der Weisen](http://datenbank.classic-wow.org/?item=20877) 28 %
- [Götze des Kampfes](http://datenbank.classic-wow.org/?item=20881) 28 %
- [Götze der Sonne](http://datenbank.classic-wow.org/?item=20874) 28 %
- [Götze des Todes](http://datenbank.classic-wow.org/?item=20876) 27 %
- [Götze der Nacht](http://datenbank.classic-wow.org/?item=20875) 27 %

Wichtig! Die Götze sollte **KEIN** Questitem sein. Der Looter der Kiste sollte **ALLE** Götzen sehen können. 
Außerdem sollte der Kasten verschwinden, wenn er komplett leer ist. 

Die Kisten dürfen nicht mehr zugeschlossen sein, wenn man 1x geöffnet hat.

Schritte zur Reproduzierung
Schlüssel vom Trash looten und Kiste öffnen, wenn:
- man keine Quest hat (dann kriegt man wahrscheinlich gar keine Götzen raus)
- man die Quests für die Setteile hat, sieht man nur die Götzen, die in der Quest gefordert werden. 

Zusätzliche Informationen (Screenshots, Videos, etc.)
Es ist schwierig noch zusätzliche Quellen außer:
http://www.wowhead.com/object=180690/large-scarab-coffer#contains
zu finden, da scheinbar niemand über die Chancen der Götzen in einem Forum diskutiert hat. 
Wenn jemand was findet, bitte schreiben!

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Kiste:
http://datenbank.classic-wow.org/?object=180690
Götzen
- [Götze der Wiedergeburt](http://datenbank.classic-wow.org/?item=20878) 
- [Götze des Lebens](http://datenbank.classic-wow.org/?item=20879) 
- [Götze des Krieges](http://datenbank.classic-wow.org/?item=20882) 
- [Götze der Weisen](http://datenbank.classic-wow.org/?item=20877) 
- [Götze des Kampfes](http://datenbank.classic-wow.org/?item=20881) 
- [Götze der Sonne](http://datenbank.classic-wow.org/?item=20874) 
- [Götze des Todes](http://datenbank.classic-wow.org/?item=20876) 
- [Götze der Nacht](http://datenbank.classic-wow.org/?item=20875) 

Zusätzliches
Auch wenn es nicht unbedingt als feste Informationsquelle genutzt werden kann, hier noch folgendes:
Video aus dem aktuellen WoW, wo ich 2 Götzenkästen aufmache:
https://youtu.be/IXyMN1SELkM

Und ein Screenshot, wie viele Götzen ich aus einem Run gezogen habe (Trash + 7 Kisten):
http://puu.sh/oCfgh/1992d8a54f.jpg

Wie bereits oben beschrieben konnte ich jegliche Götzen aus den Kästen looten, ich hatte **keine** Quest.

Gruß

Sheed
SolidCore

**Comment by testear** [comment]
Wie man hier sehen kann sollten die Götzen alle generell sehr niedrige Dropchancen haben:
http://de.wowhead.com/item=20875/gotze-der-nacht
http://de.wowhead.com/item=20874/gotze-der-sonne
http://de.wowhead.com/item=20877/gotze-der-weisen
http://de.wowhead.com/item=20879/gotze-des-lebens
http://de.wowhead.com/item=20878/gotze-der-wiedergeburt
http://de.wowhead.com/item=20881/gotze-des-kampfes
http://de.wowhead.com/item=20882/gotze-des-krieges
http://de.wowhead.com/item=20876/gotze-des-todes

**Comment by ChichiWarrior** [comment]
Definiere zu wenig seltene Götzen.

Es droppen an bestimmten Stellen immer die gleichen Götzen, z.B. die Skorpione auf dem Weg zu Huhuran immer 1-2 Götzen der Nacht oder Sonne.

Es lässt sich auch beeinflussen, welche Götzen in den Skarabäentruhen sind.

Fakt ist, gefühlt droppen wirklich zu wenig Götzen. Wir haben Wartelisten, da müssen Leute nach jetzigem Stand ca. 2-3 Monate warten um ihr T2,5 Item zu bekommen.


Gruß

Chichi

**Comment by Sheed90** [comment]
@testear 
Das sind leider die Zahlen aus dem heutigen WoW, ob die noch dem damaligen Stand übereinstimmen, darf bezweifelt werden.

@ChichiWarrior 
Also die Stellen, wo die Götzen droppen, mag vollkommen richtig sein. Aber die Anzahl scheint viel zu gering zu sein.

Gruß

**Comment by testear** [comment]
Sheed dann hast du doch gewiss die Patchnotes mit der Änderung bezüglich der Dropraten der Götzen überprüft.
Ich habe es getan und festgestellt: Da gab es nie eine Änderung.

**Comment by Seniorash** [comment]
Wenn die Warteliste so lang ist wie die Dauer des Contens erschließt sich ganz von alleine, dass etwas nicht stimmt. Die seltenen Götzen droppen seit der Änderung definitiv öfter, jedoch hab ich den Eindruck dass es immer noch weniger sind als Tokens.
Dass die Dropchance anfangs viel zu niedrig war hat nun mal bewirkt, dass sich ein starkes Ungleichgewicht Tokens/Götzen eingestellt hat. Vielleicht kann man nachträglich einige Götzen nachreichen. Als in BWL anfangs der Trash noch respawnte und abgefarmt werden konnte wurde das Elementium auch nachträglich wieder entfernt.

**Comment by Wosser** [comment]
Letzte ID 2 seltene Götzen, die beiden IDs davor jeweils 4 bei Who Cares

**Comment by Hakii** [comment]
Die meisten Götzen sollten über die Kisten reinkommen. Die Dropwahrscheinlichkeiten sind so hoch, dass es im Regelfall immer 1-2 Götzen pro Kiste geben sollte. Da man aber nur die Götzen looten kann, für die man eine Quest im Log hat, geht die ganze Sache leider nicht auf. In AQ20 scheint das mit den Götzen ja zu funktioniere, da man hier teilweise sogar 3-4 Götzen aus einer Kiste rausziehen kann.

Also wir konnten uns damals auf dem Offiserver mit den AQ40 Götzen erschlagen, eine Warteliste gabs damals bei uns nicht ^^.

**Comment by Sheed90** [comment]
https://community.mmobase.de/talk-und-allgemeines/9488-aq40-g%F6tzen-eure-erfahrungen.html

**Comment by Sheed90** [comment]
http://www.wowhead.com/object=180690/large-scarab-coffer#contains

Hier sieht man, dass die Kiste immer einen Beutel mit Skarabäen enthält und jeweils eine Chance von 27-28 % eine Götze JEDEN Typs zu einer Stückzahl von 1-3 enthalten kann.

**Comment by Hakii** [comment]
Man munkelt sogar, es gebe Warteschlangen die so lang sind, dass einige Spieler im Jahr 2016 wohl nicht mehr glücklich werden mit T2,5... wenns so bleibt :)

**Comment by Sheed90** [comment]
Das st natürlich bitter und es ist gerade mal Anfang Mai.

Daher bitte ich die Devs, sich dieser Sache dringend anzunehmen.

Die Entscheidung, ob es einen Götzenausgleich der bisherigen Raids gibt, liegt wohl alleine bei Dotox.

Gruß

**Comment by Dotox** [comment]
Ich überarbeite das Loot-System für die angesprochenen Items. Das dauert leider noch etwas :)

**Comment by Seniorash** [comment]
Falls die bisher fehlenden Götzen ausgeglichen werden sollten wäre eine mögliche Lösung für eine ID die entsprechenden Tokens ohne Götzen eintauschen zu können? So als Idee am Rande.

**Comment by Bladsn** [comment]
Nein.

**Comment by Seniorash** [comment]
Wer fragt dich denn ;-)

**Comment by Sheed90** [comment]
Wie bereits oben erwähnt, ist das kein Forum hier.

Bitte hier diskutieren: https://community.mmobase.de/talk-und-allgemeines/9488-aq40-g%F6tzen-eure-erfahrungen.html

Gruß

**Comment by Dotox** [comment]
Ich hab einige Änderungen an dem Skarabäuskasten vorgenommen. Bitte beobachten :)

**Comment by Sheed90** [comment]
Alles klar, werden wir am Sonntag beobachten.

Danke!

**Comment by ChichiWarrior** [comment]
Es sind 1-3 Götzen drin. Hatte aber leider nur 3 unterschiedliche Götzen drin. Mag wohl Pech gewesen sein.
Kisten verschwinden immer.

Sieht gut aus.

Gruß Chichi

**Comment by Sheed90** [comment]
Feedback 08.05.2016

Hallo Dotox, hallo Chichi,

wir konnten fast alle Kisten öffnen, daher kann ich gutes Feedback geben.

Also wir hatten
4x Nachtgötzen (zwischen 1-3)
3x Todesgötzen (zwischen 1-3)
1x Sonnengötzen (2 Stück) 

Die Götzen sind nun definitiv Questunabhängig, da ich als Schurke ebenfalls Todesgötzen looten konnte. 

Ich nehme an, dass du Chancen so gelassen hast, wie sie in der [Datebank](http://datenbank.classic-wow.org/?object=180690) sind, oder Dotox? 

Es wäre schön, wenn die Götzen die Chancen aus dem 1. Post hätten. 

Götze der Wiedergeburt 28 %
Götze des Lebens 28 %
Götze des Krieges 28 %
Götze der Weisen 28 %
Götze des Kampfes 28 %
Götze der Sonne 28 %
Götze des Todes 27 %
Götze der Nacht 27 %

Gruß

**Comment by Wosser** [comment]
In jeder Kiste waren 1 bis 3 Götzen drin, haben insgesamt aber wieder nur 2 seltene Götzen rausgeholt. Uns fehlen inzwischen über 80 seltene Götzen.

**Comment by ChichiWarrior** [comment]
Hey Sheed90,

ich hatte wenige mehr drin. Zu deinen drei Genannten, hatte ich noch Wiedergeburt gelootet.
Müsste man noch 2-3 ID's beobachten.

Gruß Chichi

**Comment by Dotox** [comment]
Die Web-Datenbank wird nicht täglich aktualisiert, daher sind darin noch die falschen Werte (drop-raten) eingetragen. Ich würde das ganze gerne den nächsten Raid abwarten und anschließend eventuell nochmal etwas verändern.

**Comment by Sheed90** [comment]
Hi,

ja, definitiv sollte man das nochmal beobachten. Wenn es gewünscht ist, stelle ich mich auch gerne als Tester auf dem Testserver zur Verfügung. Mithilfe eines GM's kann man das natürlich viel schneller testen.

Fassen wir zusammen.
Die Götzen sind nun questunabhängig, d. h. es ist egal, wer die Kiste öffnet.
Die Kiste verschwindet nach dem Looten, d. h. sie ist auch wirklich leer.

Weder ich noch Omega haben keine nennenswerte Quellen gefunden, die wirklich widerspiegeln, wie es damals war. Wir können uns nur nach dem richten, was bei wow-head steht, oder nach dem gehen, wie es aktuell auf dem Retail Server ist. 

Ich habe 2 Lösungsvorschläge für das Problem.

1. Lösung:
Die Chancen für Götzen, die in den Kisten sein können, werden angepasst. (Sonst werden seltene Götzen noch seltener) Alles andere bleibt wie es nun ist. Das heißt aber auch, dass maximal 1 Sorte in der Kiste sein kann. Dafür aber gleich bis zu 3 Stück.
Götze der Wiedergeburt 28 %
Götze des Lebens 28 %
Götze des Krieges 28 %
Götze der Weisen 28 %
Götze des Kampfes 28 %
Götze der Sonne 28 %
Götze des Todes 27 %
Götze der Nacht 27 %

2. Lösung:
Wie es aktuell auf dem Retail Server ist. (Video: https://youtu.be/IXyMN1SELkM )
Dort sind immer verschiedene Sorten von Götzen in den Kisten drin. Maximal 1 pro Sorte.
Minimum 2 verschiedene. Bis zu einem Maximum von 4 oder 5 verschiedene Sorten (?).

Wie seht ihr das?

Gruß

**Comment by ChichiWarrior** [comment]
Da wir hier leider nicht bei "Wünsch dir was" sind, muss und werden wir die Lösung von Dotox akzeptieren.

Das einzige Anliegen, dass ich noch habe.
Einen Ausgleich für die fehlenden "seltenen" Götzen. Da ist jede Gilde weit hinterher.
Keine Ahnung ob sich dafür eine Lösung finden lassen kann.

Ansonsten. Vielen Dank für die Änderung Dotox. Die Veränderung lässt uns hoffen die Liste nicht noch länger werden zu lassen

Gruß Chichi

**Comment by Sheed90** [comment]
Dieses mal nur ein kleines Feedback.
Wir hatten am Sonntag
7 Götze der Wiedergeburt
6 Götze des Lebens
2 Götze des Todes

aus den Kisten gezogen. Wir warten noch 1-2 Wochen ab, aber ich denke, dass das Problem jetzt gefxied sein sollte! Danke! :-)

Wäre cool, wenn die anderen Gilden ihre Ergebnisse noch posten könnten.

Gruß

**Comment by ChichiWarrior** [comment]
Feedback Donnerstag

**Comment by Sheed90** [comment]
Bei dieser ID waren die Götzen aus den Kisten leider wieder sehr eintönig..

Kiste 1: 3x Sonne
Kiste 2: 1x Weisheit
Kiste 3: 1x Weisheit
Kiste 4: 2x Sonne
Kiste 5: 2x Weisheit

für mehr Kisten gabs leider keine Schlüssel.

Gruß

**Comment by Wosser** [comment]
Who Cares hatte 6 Götzen des Todes und eine Götze des Krieges.

**Comment by Sheed90** [comment]
Heute haben wir folgende Götzen gelootet:

Kiste 1: 3x Sun
Kiste 2: 2x Sun
Kiste 2: 3x Wiedergeburt

**Comment by Badorr** [comment]
Inheritance hatte diese Götzen drin: 

4x Tod
3x Kampf
Ein paarmal je Sonne und Nacht

**Comment by ChichiWarrior** [comment]
who cares Kisten:

3x Wiedergeburt
3x Nacht

**Comment by Wosser** [comment]
Uns sind in den letzten Wochen sehr viele Götzen des Todes gedroppt und ein paar Wiedergeburt, Kampf und Krieg fast gar keine.

**Comment by Sheed90** [comment]
Diese Woche sah es so aus:

Kiste 1: 1x Todes
Kiste 2: 1x Weisheit
Kiste 3: 1x Todes
Kiste 4: 1x Todes
Kiste 5: 2x Sonne
Kiste 6: 2x Todes

Ich persönliche finde die Chance für Kriegs- und Kampfesgötzen etwas zu low. Vielleicht sollte man da noch etwas schrauben?

Gruß

**Comment by Hakii** [comment]
Das Ungleichgewicht, besonders bei Kriegs/Kampfgötzen sollte inzwischen mehr als ersichtlich sein

**Comment by Badorr** [comment]
Wir hatten bisher folgende Götzen drin:

1x Wiedergeburt
1x Krieg
3x Tod
2x Sonne
2x Nacht

**Comment by ChichiWarrior** [comment]
Wir hatten leider nur einen Schlüssel:

1x Götze der Nacht

**Comment by Sheed90** [comment]
Kannst du uns ein kurzes Feedback geben, ob du noch etwas an den Chancen ändern möchtest, Dotox?

Wie bereits oben erwähnt, werden viele Ihre Tokens bis Ende 2017 nicht einlösen können, da die Listen mittlerweile sehr lang sind. 

Hier mal ein Screenshot, wie es derzeit bei SolidCore aussieht:

http://puu.sh/pme0S/7afe023551.png

Wie man sieht, ist bei den anderen Götzen alles in Ordnung, nur eben Kampf und Krieg nicht. :(

Gruß

**Comment by Wosser** [comment]
Götzen des Todes droppen nun mehr als gebraucht werden. Götzen der Wiedergeburt droppen manchmal, passt aber eigentlich. Kampf und Krieg droppen nach wie vor überhaupt nicht.

**Comment by Sheed90** [comment]
Heutige Götzen:

Kiste 1: 2x Todes
Kiste 2: 2x Todes
Kiste 3: 1x Sonne
Kiste 4: 1x Weisheit
Kiste 5: 1x Todes
Kiste 6: 3x Sonne
Kiste 7: 3x Todes

**Comment by Wosser** [comment]
Diese ID eine Götze des Kampfes vom Trash gedroppt, ansonsten keine Kampf- Krieg- oder Wiedergeburt-Götzen. Pls halp.

**Comment by Sheed90** [comment]
Während des Trashes hatten wir heute echt viel Glück.
- 2x Kampf
- 1x Krieg

In den Kisten waren aber wieder die üblichen Verdächtigen:

Kiste 1: 2x Sonne
Kiste 2: 1x Todes
Kiste 3: 1x Sonne
Kiste 4: 3x Weisen
Kiste 5: 3x Weisen
Kiste 6: 1x Weisen
Kiste 7: 3x Sonne
Kiste 8: 2x Weisen

Gruß

**Comment by ChichiWarrior** [comment]
Auch diese ID haben waren es mal wieder nur 3 unterschiedliche Götzen, sowohl beim Trash, wie auch in den Kisten.

Todes / Weisen / Sonne

Zur Abwechslung 1x Leben

Die gebrauchten Götzen droppen noch immer nicht, bzw. viel zu schlecht.

Kampf / Krieg / Wiedergeburt

Bitte weiterhin um Nachbesserung!

Gruß

Chichi

**Comment by Wosser** [comment]
Diese Woche hatten wir 1 Wiedergeburt, 1 Kampf und 2 Krieg.

**Comment by ChichiWarrior** [comment]
Leider trotzdem zu wenig, um die Liste nur ansatzweise abarbeiten zu können.

**Comment by Hakii** [comment]
Ich glaub die letzten Kampf- bzw. Kriegsgötzen aus Kisten hatten wir (Solidcore) irgendwann Mitte bis  Ende April. Seither schauen wir kistenmäßig in die Röhre. Wir benötigten aktuell 36 Kampfgötzen und 20 Kriegsgötzen. Nach aktueller Dropfrequenz werden einige zu Lebzeiten nicht mehr in den Genuss dieser Setteile kommen.

Auch wenn einige wenige Kistendrops der Kampf- bzw. Kriegsgötzen bei der einen oder anderen Gilde auftauchen, so sollte doch inzwischen die enorme Verschiebung zwischen den verschiedenen Götzen mehr als nur deutlich ins Auge fallen.

**Comment by dagochen** [comment]
Funktioniert das nun korrekt? Keine leeren Kisten mehr? Alle Götzen theoretisch/praktisch verfügbar?

**Comment by Sheed90** [comment]
Nein.

**Comment by dagochen** [comment]
Sehe ich das richtig das lediglich die Prozentchancen beim Trash und bei den Kisten fragwürdig sind?
Also beispielsweise http://datenbank.classic-wow.org/?item=20879 80% Dropchance? Während es für Kriegs und Kampf-Götzen nur Chancen < 1% gibt?

**Comment by Sheed90** [comment]
Dotox weiß doch über die Problematik bescheid. Wenn man sich alles oben geschrieben durchliest, sollte klar sein, wo das Problem liegt. Das brauchen wir hier nicht nochmal alles aufwühlen.

**Comment by ChichiWarrior** [comment]
Wenn man den ganzen Report ließt, sollte klar sein wo das Problem im Moment ist.

Wir schreiben wöchentlich unsere Drops der Götzen rein, falls zum testen was geändert wurde.

**Comment by Hakii** [comment]
Bitte schenke uns jemand den Segen der Götzen! Auf das die Gildenbbanken vor Götzen aller Art explodieren mögen!

**Comment by Sheed90** [comment]
Hallo Dotox, hallo Dago, 

sind [die Dropchancen ](http://datenbank.classic-wow.org/?object=180690)wie sie in der Datenbank stehen nun live auf Nefarian?

Gruß

**Comment by dagochen** [comment]
Da Dotox das Label nicht geändert hat und soweit ich es weiß, ja. Hat denn schon jemand Erfahrungsberichte?

**Comment by Sheed90** [comment]
**Vorher** wars noch wie oben beschrieben:

Götze der Wiedergeburt 8 %
Götze des Lebens 11 %
Götze des Krieges 11 %
Götze der Weisen 16 %
Götze des Kampfes 19 %
Götze der Sonne 24 %
Götze des Todes 24 %

Nun steht in der Datenbank bei jeder Götze 13 %

Wir und auch viele andere Gilden gehen erst Sonntag rein. 

Gruß

**Comment by dagochen** [comment]
>Götze der Wiedergeburt 8 %
Götze des Lebens 11 %
Götze des Krieges 11 %
Götze der Weisen 16 %
Götze des Kampfes 19 %
Götze der Sonne 24 %
Götze des Todes 24 %

Das waren die Werte, bevor Dotox die ersten Veränderungen vorgenommen hatte (als man noch die Quest haben musste).

Danach konnten leider nur 5 von 8 Götzen in den Kästen sein und jetzt mit den neuen Wahrscheinlichkeiten, sollte es korrekt funktionieren. Feedback dazu ist gern gesehen.

**Comment by Sheed90** [comment]
Scheint alles zu klappen. :-)

Loot diese Woche:

3x Todes
2x Todes
1x Leben
2x Krieges
1x Krieges
3x Krieg
1x Weisheit
3x Kampf
1x Weisheit

Danke und Gruß

**Comment by Wosser** [comment]
Nach wie vor kein Kampf Götzen bei uns.

**Comment by Wosser** [comment]
Diese Woche eine Kampf Götze vom Trash, Krieg droppen jetzt auch gut, Kampf und Wiedergeburt nach wie vor gar nicht aus Kisten, dazu droppen recht wenig Schlüssel, wir können nicht immer alle Kisten aufmachen.

**Comment by Sheed90** [comment]
Also bei uns läuft jetzt alles

**Comment by Badorr** [comment]
Inheritance hatte heute:

4x Kampf
2x Krieg
2x Wiedergeburt
1x Leben

etwa 4 Schlüssel gelootet

**Comment by Wosser** [comment]
Nach wie vor keine Kampf Götzen, können wir bei nem GM andere Götzen gegen die 50 Stück, die uns inzwischen fehlen eintauschen?

**Comment by dagochen** [comment]
12,5% ... :( Ist halt nicht so viel, wenn man die restlichen 87,5% nicht will :(

**Comment by ChichiWarrior** [comment]
Aber nicht über mehrere Monate. =(

**Comment by Ataraia** [comment]
Problem besteht weiterhin bei Kampf-, Krieg- und neuerdings auch wieder bei Todesgötzen, bei denen die Warteliste wieder mal anschwillt.

Momentane Situation bei Who Cares:
Krieg: "nur" 9 Personen auf Warteliste
Kampf: 23 Personen auf Warteliste
Todes: geht wieder hoch auf mittlerweile 6 Personen auf Warteliste

**Comment by Wosser** [comment]
Hey, Krieg und Kampf droppen inzwischen gut, aber seit dem letzten Fix droppen kaum noch Todesgötzen, plz NOCH MAL DRAN ARBEITEN...

**Comment by dagochen** [comment]
Haben alle die gleiche Chance :(

**Comment by Loplin** [comment]
Dann sinds wohl nurnoch statistische ausreißer
Geben wir dem fix noch 1-2 wochen :)

**Comment by Wosser** [comment]
Diese ID wieder keine, letzte ID eine. Nach dem ersten Fix sind die Todesgötzen mit am meisten gedroppt, seit dem Kriegs- oder Kampfgötzen Fix droppen sie am seltensten. Da der letzte Fix jetzt auch schon ein paar Monate her ist und sie seitdem schlecht droppen ist es sehr unwahrscheinlich, dass es einfach nur Pech ist. Könnt ihr das BITTE nochmal fixen? Seit 10 Monaten klappt das mit den Dropraten nicht. Nörgel...

**Comment by dagochen** [comment]
100 Große Skarabäuskästen haben wir befragt...nennen sie eine Götze, die es in AQ40 gibt.

![wowscrnshot_110716_193233](https://cloud.githubusercontent.com/assets/5236186/20070523/fb323198-a520-11e6-91ca-5791410db72d.jpg)

**Comment by Wosser** [comment]
Dann lass einfach generell mehr Götzen droppen. Wir clearen seit bald 10 Monaten wöchentlich AQ40, viele Tokens bleiben liegen weil sie keiner mehr braucht, aber wir haben immernoch 30 Tokens die wir nicht einlösen können, weil uns dafür die Götzen fehlen, also was genau machen wir falsch?

**Comment by Wosser** [comment]
Update: Nach inzwischen über nem Jahr AQ40 fehlen uns immernoch etwa 30 Kampfgötzen um die restlichen Tokens einzulösen, dazu sind uns jetzt auch die Götzen der Weisen ausgegangen, weil die seit dem Kriegsgötzen-Fix auch kaum noch droppen.

**Comment by Wosser** [comment]
Btw, wenn auf dem Bild da oben der Loot von 100 Kästen zu sehen ist, dann droppen generell zu wenig Götzen, oder? Um 100 Kästen zu öffnen braucht man elf Clearruns, dabei droppen 110 Tokens, für die 220 Götzen benötigt werden. Wenn man Ouro und C'thun nicht schafft sind es zwar nurnoch 132 Götzen für 66 Tokens, auf der anderen Seite kommt eine Gilde die die Twins nicht schafft quasi an gar keine Götzen weil die Schlüssel (fast?) nur beim Trash nach den Twins droppen. Auch so können wir nicht immer alle Kisten aufmachen, weil die Droprate der Schlüssel recht knapp ist. Ist das wirklich so gewollt dass das Farmen der Götzen so ein Krampf für die Gilden ist?

**Comment by dagochen** [comment]
Du bekommst 1-3 Götzen aus jeder Kiste, also im Mittel 2. Bei 100 Kisten macht das ca. 200. Ich hab mit meinen knapp 160 halt Pech gehabt was die Anzahl angeht. Ich weiß ehrlich gesagt nicht, was ich hier sonst noch schreiben soll, da ich davon ausgehe, dass alles korrekt funktioniert (solange keine Quellen von früher ein anderes Dropverhalten oder andere Lootchancen belegen).
