### ISSUE TITLE
Lvl 20 Questreihe "Foliant der Ehre"

### ISSUE THREAD

**Issue by Wendefix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1553]
Welches Verhalten wird beobachtet?
Der zweite Teil der Lvl20er-Reihe (Paladin) in Westfall kann nicht angenommen werden, da lt. unserer Datenbank diese Quest mit Lvl 24 Mindestvoraussetzung ausgestattet ist. Die dann folgenden Quests haben aber wieder eine Mindestbeschränkung von Lvl 20, was in sich nicht schlüssig ist.

Wie sollte es sich verhalten?
Die zweite Quest aus "Der Foliant der Ehre" sollte auch mit Lvl20 annehmbar sein. Als Quelle zitiere ich hier [wowhead](http://www.wowhead.com/quest=1651/the-tome-of-valor) sowie Diskussionen aus dem [Classic-Forum](https://community.mmobase.de/bugtracker-archiv/672-paladin-klassenquests.html) und auch [rising-gods](https://tbcdb.rising-gods.de/?quest=1651).
Darüber hinaus erscheint es nicht sinnvoll, eine Questlinie über fünf Quests zu haben, die alle bis auf eine einzelne in der Mitte die Zugangsvoraussetzung bei Lvl 20 zu setzen.

Schritte zur Reproduzierung
Siehe unsere Datenbank bzw. sich mit einem lvl 20 Pala an den Quest-NPC stellen ;)
http://datenbank.classic-wow.org/?quest=1651

**Comment by Wendefix** [comment]
Zur Ergänzung, ich habe gerade bei wowwiki vanilla noch gefunden, dass die oben genannte Quest "soloable at lvl 20" sei.
http://vanilla-wow.wikia.com/wiki/Paladin/Quests

**Comment by betz0r** [comment]
#push da nach mehr als 6 monate noch nicht gefixt. quellen und fehlverhalten lliegen bei.

**Comment by Slimmer2** [comment]
Ersten Push nicht gestattet.
Zweitens sind es erst 5 Monate
