### ISSUE TITLE
AQ40 Wespenhautstulpen

### ISSUE THREAD

**Issue by lordgusi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1554]
Der Gegenstand kann anscheinend bei der Horde nicht droppen. 12 x Allianz 0 x Horde

http://datenbank.classic-wow.org/?item=21617

http://realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21617

**Comment by ChichiWarrior** [comment]
Hallo Dotox,

falls du daran was geändert haben solltest, die sind gestern bei <who cares> gedroppt.

Gruß

Chichi
