### ISSUE TITLE
Taerar bewegt sich während der Schemen-Phase

### ISSUE THREAD

**Issue by Gipsyjodler** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1556]
Welches Verhalten wird beobachtet?
Ich habe Taerar getankt, dabei hat er sich in den ersten beiden Schemen-Phasen hinter mir her bewegt. Er war zwar verblasst und hat keinen Schaden gemacht, aber man konnte ihn neu positionieren. In der letzten Phase war das Verhalten wieder normal. Da blieb er wie üblich einfach stehen und war verblasst.

Wie sollte es sich verhalten?
Normalerweise sollte der Drache dort stehen bleiben, wo er in die Phase versetzt wird.

Schritte zur Reproduzierung
Leider konnte ich nicht erkennen wie der Bug verursacht wurde und habe auch kein Video aufnehmen können.

**Comment by Dotox** [comment]
Hey,

bitte nochmal beobachten und ggf. nochmals melden, falls das Problem nochmal auftritt. Konnte es nicht reproduzieren.

**Comment by Gipsyjodler** [comment]
Heute ist es schon wieder passiert, aber auch nur einmal. Haben ein Video davon gemacht. Ich link es später.

**Comment by Gipsyjodler** [comment]
https://www.youtube.com/watch?v=TdTELjQOwTg&feature=youtu.be
Hier ist das Video wie sich der Boss während der Schemen Phase bewegt.
Mfg Gipsy

**Comment by Ulva-Anorhin** [comment]
Heute war es wieder der fall bei einer anderen Gilde.
Ich habe daruf hin mal meine Videos durchsucht und auch noch ein 2. video dazu gefunden. Man sieht ebenfalls wie er in der Phase verbuggt ist.

https://youtu.be/HGYg0Ozv1wA

**Comment by Ulva-Anorhin** [comment]
Heute wieder der Fall.
Es wurde mal ein Patch aufgespielt indem es hieß "Taerar kann seine Phase nicht mehr resisten".
War anscheinend nicht der Grund.
