### ISSUE TITLE
Npcs drehen sich im stun (IMMER NOCH)/ Keine Erschöpfung

### ISSUE THREAD

**Issue by Zaccar20** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1557]
Hallo,
NPCs drehen sich immer noch manchmal im stun (Solaplexus, Nierenhieb), manchmal nur visuell, manchmal aber auch obwohl sie eigentllich noch in die richtige Richtung sehen wie zu beginn des stuns.

Außerdem geht die Erschöpfungs-Anzeige wieder weg wenn man soweit wie möglich westlich (am Kartenrand) schwimmt von der Feste Feathermoon/Feralas aus.
Mfg Zaccar

**Comment by Dotox** [comment]
Lade bitte mal ein Video hoch, in dem das beschriebene zu erkennen ist.

**Comment by Zaccar20** [comment]
ok mach ich

**Comment by Dotox** [comment]
Tritt das Problem nach dem Update (13.07.2016) immer noch auf?
