### ISSUE TITLE
Quest "Marschenfroschschenkel" fehlen benötigte Mobs

### ISSUE THREAD

**Issue by 51MON-STER2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1558]
### Was:
Die Quest "Marschenfroschschenkel", erhältlich in den Marschen von Dustwallow (55 | 27) kann angenommen, aber nicht abgeschlossen werden. Die Quest erfordert das Töten von "Riesiger Marschenfrosch", der dann "Marschenfroschschenkel" droppt.
(Nachzulesen hier: http://de.wowhead.com/quest=27183/marschenfroschschenkel).

### Ist:
Die Level 1 Tiere "Riesiger Marschenfrosch" existieren aktuell nicht. Selten findet man mal "Kröte", die das Item nicht droppt.

### Sollte:
Die Level 1 Tiere "Riesiger Marschenfrosch" sollen sich überall um das Haus bei den Koordinaten aufhalten.

**Comment by Rushor** [comment]
duplikat https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1240 ?

**Comment by 51MON-STER2** [comment]
Oh sorry, hab's mit der Suche nicht gefunden. Kann dann wohl geschlossen werden :)
