### ISSUE TITLE
[Raid/AQ40] Wormscale Blocker / Wurmschuppenblocker

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1560]
Möglicherweise haben wir hier das gleiche Problem wie mit den Handschuhen bei Huhuran.

Horde 0x
Allianz 6x

http://realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21610

Item:
http://datenbank.classic-wow.org/?item=21610

Gruß

Chichi

**Comment by Horim** [comment]
Leider wahr, auch wenn es enormes Pech sein kann

**Comment by Dotox** [comment]
Ist es bisher gedroppt? Die Datenbankeinträge scheinen richtig zu sein.

**Comment by ChichiWarrior** [comment]
Bei who cares noch nicht.

**Comment by rooty113** [comment]
Bei Inheritance bisher auch Null Drops.

**Comment by Horim** [comment]
Nach wie vor kein Schild auf Hordenseite

**Comment by ChichiWarrior** [comment]
Heute erster Drop.

**Comment by hraesvelgr** [comment]
also bad luck?

**Comment by ChichiWarrior** [comment]
Oder es wurde was dran gemacht, wir hatten auch noch nie so viele Götzendropps, von denen die wir brauchen (Kampf, Wiedergeburt und Krieg)

**Comment by Dotox** [comment]
Nein, keine Änderung von uns.

**Comment by ChichiWarrior** [comment]
Dann wohl monster bad luck. Erster Kill war Januar und jetzt haben wir Juli.
Vielleicht lag es auch an anderen Dingen. Dropchance usw.
Droppen jede Woche eh die gleichen Items.

Bezüglich dem Schild kann hier geschlossen werden, da es auf Hordenseite gedroppt ist und somit auch droppen kann.

Gruß

Chichi
