### ISSUE TITLE
Stratholme Baron Event

### ISSUE THREAD

**Issue by KlatuVerataNectu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1561]
Hi,

das Baron Event mit den Wellen der Monstrositäten ist immer unterschiedlich. Teilweise kommt nur ein Mob alleine der fix down geht, beim nächsten run/id stehen dann 3-4 Mobs vorm Tank + gespawnte Schleime was unschaffbar ist auf dem Equiplevel (komplett blau inkl. 4 t0 Teile). Bei Nichtschaffen des Events war bei uns das Tor zum Hof nicht mehr anwählbar und die Instanz nicht mehr zu betreten.

Gruß, Klatu

**Comment by Sheed90** [comment]
Das Event war damals, wie auch heute, nicht einfach. 

Den einzigen Bug, den ich rauslese ist, dass nach einem Wipe das Event nicht ordnungsgemäß zurückgesetzt wurde.

Gruß

**Comment by KlatuVerataNectu** [comment]
Hätte es hier auch nicht gepostet, wenn mich ein GM nicht darauf hingewiesen hätte. Also so ganz zu funktionieren scheint es nicht. Sonst hätte er mit direkt sagen können: "learn your class" ;)

**Comment by Slimmer2** [comment]
Geht wohl eher darum das das Event bei Wipe, nicht resetet und das Tor geschlossen bleibt

**Comment by Sabbaer** [comment]
wie wärs mit: "die Vorlage benutzen"!
Vor dem Melden
Leere oder lösche den WDB Ordner bevor du das Spiel startest
Starte das Spiel ohne Addons
Einige (Sammel)Quests können durch das Beenden und erneute Annehmen doch abgeschlossen werden
Schaue im Bugtracker nach, ob der Fehler nicht bereits gemeldet wurde
Nur ein Fehler pro Fehlermeldung
Sucht NPCs, Quests, Objekte, usw. in der Datenbank raus und verlinkt sie

Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Zusätzliches

Wir akzeptieren nur Quellen, die sich nachweislich auf Classic-WoW beziehen
Meldungen, die das geforderte Format nicht einhalten, werden kommentarlos geschlossen
Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!

**Comment by hraesvelgr** [comment]
das gate setzt manchmal nicht zurück. das kann aber an einem nicht ausgeführten script liegen. es ist einfach kein reproduzierbarer fehler, da das script an sich korrekt ist, aber manchmal, aus gründen, wenn sonne, mond und mars in einer linie zu jupiter stehen, das script eben nicht korrekt ausgelöst wird. das tor an sich kann man auch nicht anwählen, es öffnet automatisch wenn sich keine lebenden spieler mehr im hof befinden, oder rammstein tot ist.  (übrigens ist es das rammstein-event, und nicht das baron-event *klugscheiß*)
