### ISSUE TITLE
Bluthornsensenklauen dreifacher Autoattack

### ISSUE THREAD

**Issue by orkwarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1563]
Bluthornsensenklauen im Brachland führen regelmäßig dreifache Autohits aus.

**Comment by Slimmer2** [comment]
Bitte an die Vorlage halten

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by Haudraufinix** [comment]
http://datenbank.classic-wow.org/?npc=3256#abilities Hier ist der Link zum Mob und der besitzt tatsächlich "Trash" - was +2 Angriffe auf den nächsten Nahkampfangriff verursacht -> Kein Bug
