### ISSUE TITLE
Sturmangriff im Orkstartgebiet

### ISSUE THREAD

**Issue by orkwarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1564]
Wenn man im Orkstartgebiet im Teil der Höhle Sturmangriff benutzt, in dem "Thazz'ril's Pick" zu holen ist, chargt man auf das Gebirge oberhalb der Höhle. Mehrfach ausprobiert, selbes Resultat.

**Comment by Slimmer2** [comment]
Bitte an die Vorlage halten
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker
