### ISSUE TITLE
Schurke Verstohlenheitsbug

### ISSUE THREAD

**Issue by Zaccar20** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1565]
Hallo,
mir ist heute im BG passiert, das ich mich nach einem tot nicht mehr unsichtbar machen konnte.
Als Fehlermeldung kam: Fähigkeit ist noch nicht bereit.
Obwohl ich weder im Kampf war, kein Feenfeuer auf mir war oder die Fähigkeit auf Abklingzeit war.

Wie es sich verhalten sollte: Ich sollte außerhalb des Kampfes unsichtbar werden können :)

Wie man den Bug auslöst ist mir selber ein Rätsel :/ Die ganze Zeit in der ich Schurke spiele ist es mir erst 2x passiert. Dieses mal habe ich gegen einen Krieger gekämpft, Verschwinden benutzt & lag eine halbe Sekunde später tot am Boden als hätte mich noch einer seiner Angriffe getroffen. Eventuell hat es auch etwas mit Verschwinden zutun.

Der Bug ist für Spieler nur durch Ausloggen oder Verschwinden benutzen behebbar.

https://www.youtube.com/watch?v=xfN5WA0tKPY&feature=youtu.be

**Comment by pdglala** [comment]
Hallo @Zaccar20 ,
Dieser Bug tritt auf wenn du Vanish im selben Moment benutzt wenn du stirbst.
Du hast den Vanish CD und stehst am Geistheiler. Wenn du dich wieder belebst kannst du dadurch nicht in Stealth gehen, da das Spiel denkt das du noch im Stealth bist weil Stealth nicht gebrochen worden ist nach deinem Ableben.
Das einzige was du dann noch machen kannst ist bis zu deinem nächsten Vanish CD zu warten.
Wenn du dann Vanish drückst, funktioniert wieder alles einwandfrei.

**Comment by Dotox** [comment]
Danke @pdglala!

Natürlich schwer zu testen, ob die Änderung nun das Problem beheben kann - wenn das Problem nochmal auftreten sollte, bitte melden.

**Comment by Ichnixwissen** [comment]
Besteht weiterhin, gestern 2x im Bg passiert, Relogg oder auf den nächsten Vanish cd warten ist die einzige Option.
