### ISSUE TITLE
Wegweiser - Grunzer von Klingenhügel

### ISSUE THREAD

**Issue by laedron** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1566]
Wenn man die Grunzer von Klingenhügel nach dem Lehrer für Bergbau fragt, verweisen diese einen auf einen Kürschnerlehrer in Ogrimmar. (Obwohl es in Klingenhügel Krunn al Bergbaulehrer gibt)

Wenn man sie nach Lederverarbeitung befragt verweisen sie auf den Bergbaulehrer Krunn in Klingenhügel.

**Comment by testear** [comment]
Wenn man die Leute auf die Vorlage ( https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker )  anspricht und, dass sie Report nach diesen Standards entwerfen sollen, reagieren diese meistens mit Missachtung und der Report wird geschlossen.
Abgesehen davon, dieser Report ist schon vorhanden.

**Comment by laedron** [comment]
Von dem Standard wusste ich nichts. Schließlich landet man wenn man im mmobase-Forum auf Bugtracker klickt auf Github in der Lasche Issues. Und die Lasche Code klingt nicht gerade wie "So wird's gemacht Bürschchen" ;), also gibt es keinen Anlass auf sie zu klicken.
Denn Report würde ich mir gerne mal anschauen. Ich habe nach Klingenhügel gesucht, aber nichts diesbezüglich gefunden. Deshalb mein Ticket.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451
wurde schon oft reportet, jedoch nur für hauptstädt. ist aber anscheinend in jeder ortschaft/vielen ortschaften so.
