### ISSUE TITLE
Taerar

### ISSUE THREAD

**Issue by Chroume** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1568]
Hallo, haben heute ggn 15.00 6x versucht Taerar zu legen (40 Mann raid), allerdings war das nicht möglich weil der Boss zu unterschiedlichen Hpprozenten immer nach einem Fear ohne Grund resetted hat. Haben extra darauf geachtet dass kein Spieler an irgend einer "verbuggten" Stelle stand oder sowas. Der Boss hat einfach nach dem Fear aggro verloren und ist auf deine Startposition gelaufen und war wieder auf 100 %.

**Comment by Sabbaer** [comment]
Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Zusätzliches

Wir akzeptieren nur Quellen, die sich nachweislich auf Classic-WoW beziehen
Meldungen, die das geforderte Format nicht einhalten, werden kommentarlos geschlossen
Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!
