### ISSUE TITLE
Quest: Berührung der Schwäche

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1569]
Welches Verhalten wird beobachtet?
Berührung der Schwäche ist beim NPC Dunkler Kleriker Beryll 2 mal aufgeführt/annehmbar

Wie sollte es sich verhalten?
Die Quest sollte nur einmal vorhanden sein.

Schritte zur Reproduzierung
NPC mit einem lvl 10 UD Priester anlabern.

Zusätzliche Informationen
Quest http://datenbank.classic-wow.org/?quest=5663
NPC Dunkler Kleriker Beryll http://datenbank.classic-wow.org/?npc=2129

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md

**Comment by Slipru** [comment]
Sie sollte nur einmal vorhanden sein.
NPC mit einem lvl 10 UD Piester anlabern.
Bei so einem offensichtlichen mini bug spammt die Vorlage nur den Report zu^^
