### ISSUE TITLE
Fear bricht nicht durch Schaden

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1571]
Was wird beobachtet:
Nach wie vor ignorieren die FearZauber der Priester  und Hexenmeister  Schaden, welcher den Fear mit einer gewissen Chance brechen sollte

..stattdessen rennen die Gefearten meist die volle Fearzeit herum, während die Priester und Hexer sowie andere Klassen Schaden machen können, ohne dass der Fear bricht.

Betroffene Zauber:
http://datenbank.classic-wow.org/?spell=10890   -  Psychischer Schrei Priester

http://datenbank.classic-wow.org/?spell=6215    - Fear des Hexenmeisters

Wie sollte es sich verhalten:
Die Anpassungen von 2015 scheinen leider nicht wirklich zu funktionieren, da wir überwiegend weit mehr als 1100 Schaden nehmen..und der Fear zumeist durchläuft.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/615

daher die Bitte, dies noch einmal zu überprüfen u. ggf anzupassen.

MfG  Frost

**Comment by Slimmer2** [comment]
Der Fear hat nur eine Höhere Chance zu brechen. Les dir das andere Ticket mal durch

**Comment by Frostlatte** [comment]
Ich bin durchaus fähig zu lesen...nur besteht diese erhöhte Chance auf unserem Server scheinbar nicht bzw. kaum.. ich habe es mal mit anderen alten pvp Videos verglichen. Bei uns kann man meist 4k HP verlieren und stirbt im Kampf...in den Videos ist dies nicht einmal zu beobachten...im Gegenteil..meist sieht man, wie der Fear beim ersten Shadowbolt bricht..

lies..ich meine schau sie selbst mal durch und teste es mal bei uns...und sprich auch mal mit versierten Hexern wie Wosser oder Rockey ...ich würde behaupten, dies können das bestätigen ;)

https://www.youtube.com/watch?v=_bn4sKaAfvU ...2.50 min , 9:50

https://www.youtube.com/watch?v=QV_U9136PPM   bsp.. 3:00 Fear bricht bei Shadowbolt schaden

https://www.youtube.com/watch?v=_gzyyXfBPjA    Vanilla Gaming...

**Comment by Slimmer2** [comment]
Deine 3 Videos sind von anderen Privat Servern. Und sind nicht gerade ein Beweis das es Damals auch so war.
Hier ein Video wie es bei uns ist. https://www.youtube.com/watch?v=1wZiRM1mj5k
Und da sieht man das der NPC auch beim ersten Treffer rauskommt und nicht die komplette Fearzeit wegläuft

**Comment by Frostlatte** [comment]
Mag sein, dass es bei NPC funktioniert. Dein Video zeigt deutlich, wie es ein sollte. Im PvP ist es leider nicht so, wie in Deinem Video. 

Teste es bitte doch mal im PvP und zeige mir das Ergebnis :D

**Comment by SirBeansen** [comment]
Der Fear ist zurzeit wirklich viel zu stark und nicht so wie früher. Zurzeit kann jeder warlock den gegner einfach fearen, in ruhe seine dots (inklusive feuerbrand) setzen, dabei sein pet auf den gegner schicken und noch 1 schadowbolt casten und dabei den 2 noch ansetzen, weil der erste noch fliegt (oder refearen) oder dabei in gefahr zu geraten das der fear zu früh bricht. Teilweiße können sogar 2 gegner auf einen drauf hauen ohne das es bricht.

Jeder CC muss leicht zu breachen sein sonst ist es einfach zu op. Der hexer fear bricht gefühlt erst nach 3k damage und wenn man bedenkt das man dann auch noch voll gedottet ist, ist es einfach zu stark.

Bei dem video https://www.youtube.com/watch?v=DlJz8anjW28 sieht man das ab 3.20 als er gegen einen anderen warlock kämpft, der fear jedes mal bricht wenn er nen längeren cast auf ihn wirkt.
Auch bei 6.00 gut zu erkennen.

**Comment by Slimmer2** [comment]
PVP ist was anderes. Da ich kein PVP spiele

**Comment by Frostlatte** [comment]
push   

nervt weiterhin stark  : - /

**Comment by dagochen** [comment]
Bei ca. 1200 Schaden bricht der Fear garantiert. Dots und Treffer die weniger Schaden verursachen haben nur eine Chance, den Fear zu brechen. Diese Chance liegt ca. bei:
Schaden / 1200 

Bei einem Dot der für 300 tickt wäre die Chance also bei 25% für jeden Tick. Soweit ich mich da eingelesenen habe und meine Erinnerungen der Erklärungen, wie es funktioniert von Wahax, noch da sind, scheint dies so korrekt zu sein, oder?

**Comment by Sabbaer** [comment]
gestern wieder 4k dmg bekommen im fear von hexxer mage und feral druide die alle munter fröhlich auf mich einprügelten während ich ca 4-5 sek im fear war und über 4k dmg gefressen hab - tot danach und der fear bis zum schluss auf mir

**Comment by dagochen** [comment]
Ja genau so ist es. 
Sprich wenn du 10x 500 Schaden erleidest, sind das insgesamt 5000 Schaden. Du hast aber bei jedem Treffer/Tick nur eine Chance von 500/1200 (=~41%), dass du aus dem Fear kommst. 

Bin jetzt aufgrund der Hinweisen und Quellen in dem alten Bugreport davon ausgegangen, dass es so korrekt ist. Sollte dem nicht so sein, bitte ich euch nochmal zu recherchieren, wie es korrekterweise sein sollte.

**Comment by Loplin** [comment]
Heißt das ich habe bei 2 ticks, also insgesamt 1000 dmg den ich erhalten habe 82% oder doch nur 66% Wahrscheinlichkeit aus dem fear zu kommen?

**Comment by dagochen** [comment]
Je nachdem, wie viel Schaden welcher Tick gemacht hat. Wenn der 1. Tick 200 DMG macht, dann ist da die Chance bei 300/1200 = 1/4 = 25% und bei dem 2. Tick dann folglich 700 DMG und 700/1200 = 7/12 = 58%. Dabei ist der 1. Tick völlig unabhängig vom 2. Tick und vice versa.

**Comment by Loplin** [comment]
Achso ja so hab ich das gemeint
Hätt ich vl den rechenweg dazuschreiben sollen sorry

**Comment by SirBeansen** [comment]
Dago hab mal ne Frage ist "Note that Fear continues to be roughly three times as likely to break on player targets as on non-player targets. In addition, Intimidating Shout now follows that player versus non-player distinction, while previously it did not. " (http://wowwiki.wikia.com/wiki/Patch_1.11.0) in der Rechnung enthalten? Also im pvp komm ich eigentlich immer erst sehr sehr spät aus dem fear (nach ne menge dots + 2 schadow bolts)

**Comment by dagochen** [comment]
Siehe oben :)

**Comment by Slimmer2** [comment]
Fear auf Spielern hat eine 3 mal höhere Chance unterbrochen zu werden als bei NPC.
