### ISSUE TITLE
When Smokey sings, I get violent

### ISSUE THREAD

**Issue by Luggasch90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1572]
http://datenbank.classic-wow.org/?quest=6041/When%20Smokey%20Sings,%20I%20Get%20Violent

Habe mit dem Questitem an mehreren Gebäuden versucht die Sprengladung zu legen.(direkt an den Markierungen)

Hat schlichtweg nicht funktioniert

**Comment by Slimmer2** [comment]
Halte dich an die Vorlage.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md

**Comment by Cassedy** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/872
