### ISSUE TITLE
Verbessertes Mal der Wildnis Buffleiste

### ISSUE THREAD

**Issue by Metalhead94** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1573]
Der erhöhte Rüstungswert von Verbessertes Mal der Wildnis wird nicht richtig in der Buffleiste angezeigt. In der Zauberbeschreibung steht beispielsweise der Wert "87" und im der Buffleiste nur "65".

**Comment by Slimmer2** [comment]
Fehler ja, behebbar nein da Clientseitig
