### ISSUE TITLE
Quest "Jarl braucht eine Klinge" in den Düstermarschen funktioniert nicht wie beschrieben

### ISSUE THREAD

**Issue by Krotus1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1574]
Die Quest "Jarl braucht eine Klinge" in den Düstermarschen hat einen nicht möglichen Questtext. 
Hier ein Foto des Ingame Questtext: 
http://i.imgur.com/4J8sVzl.png

Der Questgeber spricht hier von einem Murloc namens "Messerwirbel" der dieses Schwert mit sich führen soll. Aber in der Datenbank ist dieser Mob überhaupt nicht vertreten und auch eine längere Suche mit /target brachte keine Ergebnisse. Anscheinend kann man die Quest nur abschließen, wenn man das Schwert von einem Schmied herstellen lässt oder im AH kauft. Dies passt natürlich überhaupt nicht zur Questbeschreibung.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1041

**Comment by hraesvelgr** [comment]
sufu nutzen
