### ISSUE TITLE
Gnomeregan

### ISSUE THREAD

**Issue by Quakhek** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1575]
In Gnomeregan sind die Minen der Zwerge im Gang vorm Endboss verbugged

Früher war es so das die Zwerge diese Minen niederlegten gleich den Fallen eines Jägers und Sie wurden genauso aktiviert sprich wenn ein Spieler in die Nähe kam wurden Sie aktiviert und kurze Zeit später explodierten diese vorallem konnte man sie nicht angreifen 

Nun ist es so das diese Minen eher als Belgeiter zu bezeichnen sind man kann sie angreifen und sie verfolgen die Spieler vorallem den Heiler da der Tank die Heilaggro wenn sie spawnen nicht direkt gegentanken kann und da diese Minen sehr viel Schaden ist es quasi nicht möglich die Gegner mit einer dem Dungeon gerechten Gruppe zu töten

Ich kann leider nur aus meiner Erfahrung von früher berichten und keine andere Quelle nennen.

Ich hoffe Ihr schaut euch das mal an und berichtigt diesen Bug

MfG Quakhek

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/820
