### ISSUE TITLE
Kloster Kathedrale Whitemane Bug

### ISSUE THREAD

**Issue by Tharandel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1576]
Hi,
waren gerade im Kloster beim Endboss und normalerweise kommt ja whitemane aus dem raum um morgraine wiederzubeleben.

Bei uns blieb sie im Raum und konnten sie nicht töten. Ihre HP blieb bei 60.

konnten demnach nicht die quest abschließen und bekamen keinen Loot.

Danke 
Grüße Tharandel

**Comment by hraesvelgr** [comment]
bitte an die posting-regeln halten. damit kann keiner was anfangen.
war wohl ein einzelner fehler bei euch,d a sich bisher niemand anderes darüber beklagt hat. sowas kann auf den besten servenr passieren.

**Comment by testear** [comment]
Ähnliches habe ich auch schon erlebt. Das kann passieren wenn man Whitemane Morgraine nicht rezzen lässt, bzw Whitemane zu schnell runter-dpst. Lässt sich aber sehr einfach umgehen.
Bitte die Datenbanklinks hinzufügen bzw den Report mit der Anleitung verbessern.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker
