### ISSUE TITLE
Warlock Imp. Drain Soul 2/2 funktioniert nicht

### ISSUE THREAD

**Issue by vorticone** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1578]
1/2 sollte 50% Procrate sein, 2/2 sollte 100% Procrate sein, siehe ingame Spellbeschreibung. Wenn ich einen grünen Mob mit Drain Soul töte, bekomme ich aber nicht jedes Mal den Siphon Soul Buff, den ich bei 2/2 Imp Drain Soul bekommen sollte.

(Sorry, mein erster Bug Report; hoffe das reicht euch so!)

**Comment by Slimmer2** [comment]
Bitte an die Vorlage halten

> Willkommen im ClassicWoW 1.12.1 Bugtracker! 
> 
> Vor dem Melden •Leere oder lösche den WDB Ordner bevor du das Spiel startest
> •Starte das Spiel ohne Addons
> •Einige (Sammel)Quests können durch das Beenden und erneute Annehmen doch abgeschlossen werden
> •Schaue im Bugtracker nach, ob der Fehler nicht bereits gemeldet wurde
> •Nur ein Fehler pro Fehlermeldung
> •Sucht NPCs, Quests, Objekte, usw. in der Datenbank raus und verlinkt sie
> 
> 
> Fehler melden
> -Titel
>  Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst
> 
> -Format
>  Eine Fehlemeldung sollte das folgende Format haben:
> Welches Verhalten wird beobachtet?
> 
> Wie sollte es sich verhalten?
> 
> Schritte zur Reproduzierung
> 
> Zusätzliche Informationen (Screenshots, Videos, etc.)
> 
> Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
> 
> Zusätzliches
> •Wir akzeptieren nur Quellen, die sich nachweislich auf Classic-WoW beziehen
> •Meldungen, die das geforderte Format nicht einhalten, werden kommentarlos geschlossen
> •Sollte ein Bug zu schwerwiegende Folgen haben, dann meldet sie bitte bei einem Entwickler im Forum per PM!
> 
>  Vielen Dank für deine Meldung!

**Comment by Slimmer2** [comment]
Tritt das auf wenn du in Gruppe bist oder Solo unterwegs bist?
