### ISSUE TITLE
Schlingendorntal - Schlingendornfieber 45

### ISSUE THREAD

**Issue by Firelayer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1579]
**Schlingendorntal - Schlingendornfieber 45**

**Welches Verhalten wird beobachtet?**
Die Wellen der Gorillas kommt ganz normal. Als dann der Gorilla Mokk auftaucht, der gekillt wird, ist seine Leiche gleich weg. Verschwindet instant, looten ist nicht möglich! Mit zwei Gruppen versucht, dann die Quest abgebrochen! 

**Wie sollte es sich verhalten?**
Die Leiche von Mokk soll einige Zeit liegen bleiben, damit gelootet werden kann.

**Comment by Slimmer2** [comment]
http://datenbank.classic-wow.org/?npc=1514
http://datenbank.classic-wow.org/?item=2797
http://datenbank.classic-wow.org/?quest=348

**Comment by Sheed90** [comment]
Kann ich bestätigen

**Comment by Agorass** [comment]
Same here, Wollte ich gerade auch machen. Funktioniert nicht Mokk verschwindet instant.

**Comment by Bronag** [comment]
Problem besteht immer noch. Mokk despawnt instant im Moment des Kills, gar keine Chance zu looten.
