### ISSUE TITLE
Treffen in Stormwind

### ISSUE THREAD

**Issue by Emmi-r2d2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1580]
Hallo,

Stehe am Eingang von Stormwind, Windsor und der Knappe stehen im Eingang,
keinen von beiden kann ich ansprechen, Questabbruch und neuannahme der Quest hab ich auch schon gemacht.

es läuft auch gerade kein event mir dieser quest

brauche da hilfe, komm einfach nicht weiter

**Comment by Sabbaer** [comment]
der buggtracker ist nicht für gm tickets... schreib ein ticket und warte auf einen gm
