### ISSUE TITLE
[Raid/AQ40] Raidbosse - WoW Crit Error

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1581]
Der Kampf gegen die Bug Fam in AQ 40 verursacht einen Crit Error.

Welches Verhalten wird beobachtet?
Während dem Bosskampf führt eine Aktion zu einem Crit Error von bis zu 20 Spielern.

Wie sollte es sich verhalten?
Der Kampf sollte ohne Fehlermeldungen ablaufen

Schritte zur Reproduzierung
Leider konnte keine Regelmäßigkeit festgestellt werden.

Zusatz
Weder die Spieler waren die Gleichen, noch lag es an einem Addon. (Null Addons aktiviert)
Der Crit Error kam aber jedesmal beim Kampf gegen Yauj (http://datenbank.classic-wow.org/?npc=15543#abilities)
Sowohl beim Kampf gegen Yauj, wie auch kurz nach dem Tod. (Addspawn)

Haben vielleicht andere Gilden ähnliche/gleiche Probleme beobachten können?

Gruß

Chichi

**Comment by Dotox** [comment]
Ich schau mal, ob ich das irgendwie reproduzieren kann.

**Comment by ChichiWarrior** [comment]
Könnte was damit zu tun haben, wenn ein Bossfight resettet. Ob beabsichtigt, oder wie bei den Bugs unbeabsichtigt, da es dort ja immer noch Probleme gibt. Vielleicht hilft dir das beim reproduzieren.

Gruß

Chichi

**Comment by ChichiWarrior** [comment]
Wir hatten Sonntag 03.07.2016 bei Ouro einen Crit Error von ca 30 Leuten ohne erkennbaren Auslöser.
Müsste so gegen 21:15 Uhr gewesen sein.

Gruß

Chichi
