### ISSUE TITLE
Gnomeregan: Quest Eine schöne Bescherung

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1582]
Was wird beobachtet: Nach Annahme der Quest bleibt der NPC Kernobee einfach liegen.

Was sollte sein: Kernobee sollte aufstehen und sich zum Instanzeingang begleiten lassen

Reproduktion des Fehlers: In Gnomeregan Quest bei Kernobee annehmen

[Kernobee](http://datenbank.classic-wow.org/?npc=7850#starts)
[Eine schöne Bescherung](http://datenbank.classic-wow.org/?quest=2904)

**Comment by Slimmer2** [comment]
Editiere den Titel das er Passt

**Comment by dwilhelms** [comment]
Done! :)

**Comment by dwilhelms** [comment]
9.07.2016: Anderer Charakter ingame, bug immer noch vorhanden wie oben beschrieben

**Comment by hraesvelgr** [comment]
@dwilhelms bitte unterlass das hinweisen auf bereits bekannte bugs. die bugs werden gefixt, wenn sie gefixt werden, und dann mit einem entsprechendem label versehen

**Comment by dwilhelms** [comment]
Ja Tschuldigung, wollte ja nur sagen, dass es auch mit einem anderen Charakter so ist. Kein Grund, gleich unfreundlich zu werden.

**Comment by hraesvelgr** [comment]
das war direkt, nicht unfreundlich. aber wir haben hier öfter mal "mimimi" über bugs die nach der meinung einiger spieler UUUUUUNBEDINGT!!! gefixt werden soll (aber eigentlich nicht spielentscheidend sind)
