### ISSUE TITLE
Gnomeregan: Agent der Dunkeleisenzwerge dropt nicht Schmutzverkrusteter Ring, gleichnamige Quest deshalb nicht machbar

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1585]
Was wird beobachtet: Die [Agentrn der Dunkeleisenzwerge](http://datenbank.classic-wow.org/?npc=6212) dropen nicht [Schmutzverkrusteter Ring](http://datenbank.classic-wow.org/?item=9326) für die gleichnamige [Quest](http://datenbank.classic-wow.org/?quest=2945).

Wie sollte es sein: Einer der NPCs sollte den Ring fallen lassen

Reproduktion: Gnomeregan-Run

**Comment by Slimmer2** [comment]
Das sind die Zwerge, die im letzten Gang vom Endboss sind.
Von denen sind alle vorhanden.

**Comment by dwilhelms** [comment]
Stimmt, mit dem Rare verwechselt. Nichtsdesotrotz droppen Sie das Questitem nicht. Ich habe den Eintrag entsprechend korrigiert.

**Comment by dwilhelms** [comment]
9.07.2016: Anderer Charakter ingame, bug immer noch vorhanden wie oben beschrieben

**Comment by dwilhelms** [comment]
Heute ist das item in Gnomeregan gedropt.
