### ISSUE TITLE
Gnomeregan: Es droppen keine Schmutzverkrusteten Objekte, Quest somit nicht möglich

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1586]
Was wird beobachtet: In der gesamten Instanz droppt kein einziges [Schmutzverkrustetes Objekt](http://datenbank.classic-wow.org/?item=9308), somit sind die Quests [Der Funkelmat 5200!](http://datenbank.classic-wow.org/?quest=2951) und [Mehr Spaß mit dem Funkelmaten](http://datenbank.classic-wow.org/?quest=2953) nicht machbar.

Wie sollte es sein: Sämtliche NPCs sollten eine Dropchance auf  [Schmutzverkrustetes Objekt](http://datenbank.classic-wow.org/?item=9308) haben.

Reproduktion: Gnomeregan-Run

**Comment by Cassedy** [comment]
Ich kann den Fehler bestätigen - hab gestern/heute 2x alle Agenten der Dunkeleisenzwerge gelegt aber kein drop. Die Dropchance sollte laut Datenbank bei 100% liegen.

http://datenbank.classic-wow.org/?item=9326

http://datenbank.classic-wow.org/?npc=6212

**Comment by dwilhelms** [comment]
9.07.2016: Anderer Charakter ingame, bug immer noch vorhanden wie oben beschrieben
