### ISSUE TITLE
Quest: Sully Balloos Brief - Item zum Start droppt nicht

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1587]
Was wird beobachtet: Bei der Zwergenleiche im Arathi-Hochland, im Wasser, unter dem Thandolübergang, kann man zwar den [durchnässten Brief](http://datenbank.classic-wow.org/?object=2656) anklicken, erhält aber dann das nicht das Item zum Start der Quest [Sully Balloos Brief](http://datenbank.classic-wow.org/?quest=637): [Durchnässter Umschlag](http://datenbank.classic-wow.org/?item=4433#starts)

Wie sollte es sein: Beim Öffnen des durchnässten Briefs sollte man das Item durchnässter Umschlag looten können.

Reproduktion: Zur Zwergenleiche schwimmen und den durchnässten Brief anklicken

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by dagochen** [comment]
Funktioniert.
