### ISSUE TITLE
Steinkrallengebirge/ Spiel absturz

### ISSUE THREAD

**Issue by potpan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1588]
Moin
Bin im Steinkrallengebirge gestorben und nun stürzt das Spiel sofort ab wenn ich beim Geist/Friedhof bin. Auch nach einem neu start des Spiels stürzt es sofort ab nach dem einloggen/laden. Ich muss sogar meinen ganzen PC neu starten weil ich nicht mehr auf den Desktop komme. Ich kann im Moment nichts machen bzw spielen. Wäre nett wenn ihr meinen Char woanders hin telepotiert oder sowas.
Charactername: potpan (Krieger level 28)

MfG

**Comment by Slimmer2** [comment]
Das hier ist der Bugtracker Probleme im Forum melden.
Logge man ohne addons ein. Sollte es nicht gehen schreib dein Problem im Forum
