### ISSUE TITLE
Questbug: Krone der Erde

### ISSUE THREAD

**Issue by Ioreynus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1590]
Ab einem gewissen Punkt der Questreihe konnte ich plötzlich zweimal die gleiche Quest Krone der Erde bei Corithras Mondzorn annehmen. Ich musste bei beiden Quests dieselben Phiolen (auch zweimal) am selben Ort füllen, es gab allerdings ein paar Unterschiede beim Questtext und die eine Quest endete beim Abgeben in Englisch.
Außerdem hab ich nach dem Füllen 2 verschiedene Phiolen bekommen, nämlich eine Phiole mit gesegnetem Wasser und eine Gefüllte Amethystphiole. Es lassen sich beide Quests abgeben aber die Folgequest konnte ich erst annehmen nachdem ich die in Englisch endende Quest abgegeben hatte.
Btw wie verlinke ich Items und Quests richtig?

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues?utf8=%E2%9C%93&q=krone
