### ISSUE TITLE
Fischschwärme und Wrackteile

### ISSUE THREAD

**Issue by Ioreynus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1591]
Nabend zusammen,

Es gibt ein Problem mit den beiden oben Genannten und zwar spawnen die doppelt an der selben Stelle. Ich habe bis jetzt nur an der Dunkelküste geangelt ist aber bestimmt nicht nur dort so. Wenn man beides abgeangelt hat respawnen sie nach etwa 3 Minuten wieder.

Es sollte nur einen Schwarm bzw. Schwimmende Wrackteile an einer Stelle geben.

Kann man immer wieder machen einfach an der Dunkelküste angeln gehen ;)
Nicht bugusen ist praktisch unmöglich man müsste das Angeln in Schwärmen ganz sein lassen.

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by Dotox** [comment]
Um welche Fischschwärme handelt es sich in deinem Fall?

**Comment by Ioreynus** [comment]
Kleiner Weisenfischschwarm, Kleiner öliger Schwarzmaulschwarm und Schwimmende Trümmerteile sieht man an der Dunkelküste übereinander herumdümpeln. Ich nehm aber mal ganz dreist an, dass es ein globales Problem ist, weil es im Sumpfland auch nicht anders ist.

**Comment by Larirawiel** [comment]
Hi, das ist im Schlingendorntal in den Schwärmen großer Weisenfische exakt genau so. Da liegen der Schwarm großer Weisenfische und die Treibenden Wrackteile übereinander.

Links zur Datenbank:
http://datenbank.classic-wow.org/?object=180684
http://datenbank.classic-wow.org/?object=180685

Grüße
