### ISSUE TITLE
Magier Talent: Magische Vereinnahmung / magic absorption

### ISSUE THREAD

**Issue by lumpiewolf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1593]
Um dieses Talent geht es: http://datenbank.classic-wow.org/?spell=29447
Es sollte je nach investierten Skillpunkten 1-5% Mana pro komplett widerstandenem Zauber wiederherstellen. 
Bei Firemaw funktioniert das auch einwandfrei, bei einigen Zaubern in der Welt allerdings leider nicht.

**Comment by lumpiewolf** [comment]
Um das nachzumachen, einfach viel Naturresi anziehen, in Sili die Elemente im Nordosten aufsuchen und das Talent skillen.

**Comment by Slimmer2** [comment]
Zählt das nicht bei Widerstandenen(Verfehlten) Zauber ohne ressi?

**Comment by lumpiewolf** [comment]
Ich verstehe nicht genau was du meinst. Also bei Firemaw hat man auch viel Resi an und bekommt ganz normal Mana zurück, wenn man einem Zauber widersteht. weshalb man in dem Kampf eigentlich immer volles Mana hat.

**Comment by hraesvelgr** [comment]
ein spell kann auch verfehlen, und wird trotzdem als resist angezeigt. ergo würde in der anzeige da "resist" stehen, du würdest aber kein mana zurückbekommen, da der spell ja verfehlt hat, und nicht wirklich resistet.

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by lumpiewolf** [comment]
Ja das stimmt, aber wenn man das was ich meine mal ausprobiert fällt einem auf, das man gar kein Mana zurück bekommt und das kann einfach nicht sein.

**Comment by testear** [comment]
Ausgehend davon, dass du die Staubstürmer meinst: Ich denke nicht, dass du einer Blitzwolke, die alle paar Sekunden in einem festgelegten Bereich tickt komplett resisten kannst. Das wäre so, als würdest du bei einem auf dich gewirkten Dot jeden Tick einzeln komplett widerstehen (kein Manareg, weil der Debuff ja da ist) , statt direkt den Dot komplett zu resisten (Manareg weil kein Debuff da ist).

Da ich aber leider nicht wissen kann ob du wirklich besagten Mob mit besagter Fähigkeit meinst ist das nur eine Vermutung.

**Comment by Kriptyk** [comment]
> ein spell kann auch verfehlen, und wird trotzdem als resist angezeigt. ergo würde in der anzeige da "resist" stehen, du würdest aber kein mana zurückbekommen, da der spell ja verfehlt hat, und nicht wirklich resistet. <

Zauber treffen, werden teilweise resisted oder komplett resisted. Zauber können nicht "verfehlen".
Magische Vereinnahmung buggt in der Hinsicht, dass es bei einigen Spells einfach nicht proct trotz eines kompletten Resists.
