### ISSUE TITLE
Quest: Eine Brühschleimerprobe... funktioniert nicht

### ISSUE THREAD

**Issue by Papuelspapals** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1597]
http://datenbank.classic-wow.org/?quest=4293
Welches Verhalten wird beobachtet?
Wenn man <a href="http://datenbank.classic-wow.org/?item=12230">Teufelswaldschleimprobe</a> gesammelt hat um es mit <a href="http://datenbank.classic-wow.org/?object=174848">Testausrüstung</a> zu benutzen um <a href="http://datenbank.classic-wow.org/?item=12234">Verderbte Teufelswaldprobe</a> zu erhalten, wird einfach nur Seid gegrüßt, Spielername angezeigt. Diese Quest und alle Folgequests sind damit nicht abschließbar. Ingame wird die quest übrigens seltsamerweise "eine schleimprobe..." genannt.

Wie sollte es sich verhalten?
Man sollte von <a href="http://datenbank.classic-wow.org/?object=174848">Testausrüstung</a> <a href="http://datenbank.classic-wow.org/?item=12234">Verderbte Teufelswaldprobe</a> durch das Abschließen der Quest <a href="http://datenbank.classic-wow.org/?quest=4661">Test für Verderbnis - Teufelswald</a> damit man <a href="http://datenbank.classic-wow.org/?quest=4293">Eine Brühschleimerprobe...</a> abschließen kann.

Schritte zur Reproduzierung:
Die Quest bei <a href="http://datenbank.classic-wow.org/?npc=10136">Chemiker Brenner</a> annehmen Proben sammeln und versuchen mit der Ausrüstung zu benutzen

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/947 ?

**Comment by Papuelspapals** [comment]
Toll das Ticket ist fast 'n Jahr alt :D

**Comment by Slimmer2** [comment]
Es ist aber nicht closed

**Comment by Papuelspapals** [comment]
und wie soll das jetzt gefixt werden?

**Comment by Slimmer2** [comment]
Kannst du Aufhören, das immer zu closen und reopen

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by Papuelspapals** [comment]
Man kanns auch übertreiben, ich möchte nur dass das gefixt wird.

**Comment by warbeidenaffenjungs** [comment]
Papuelspapals ist klar

**Comment by Papuelspapals** [comment]
könnt ihr den bitte entfernen?

**Comment by warbeidenaffenjungs** [comment]
NA LOS TRAUT EUCH DDOS INCOMMING

**Comment by warbeidenaffenjungs** [comment]
!!!!!!!!

**Comment by warbeidenaffenjungs** [comment]
Warum kommt nichts?

**Comment by warbeidenaffenjungs** [comment]
Habt ihr angst

**Comment by warbeidenaffenjungs** [comment]
fh

**Comment by warbeidenaffenjungs** [comment]
fhg

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
h

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
papüspapals

**Comment by warbeidenaffenjungs** [comment]
h
