### ISSUE TITLE
Quest: [55] Eine Plage komme über euch

### ISSUE THREAD

**Issue by Xgna** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1599]
Quest Gebiet: Westliche Pestländer
2. Quests in der Reihe.
Mann kann in dem Holz Lager nicht das Fass mit Termiten abstellen. 

MfG Xgna

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/456

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by Slimmer2** [comment]
@warbeidenaffenjungs hab dich gemeldet bei Github selbst...

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by warbeidenaffenjungs** [comment]
aber ich hab doch recht

**Comment by Slimmer2** [comment]
du machst unnötig Arbeit.

**Comment by warbeidenaffenjungs** [comment]
Das will ich ja auch

**Comment by warbeidenaffenjungs** [comment]
bester support hier ganz ehrlich, bugs die ordentlich reportet werden und nicht nach einem jahr gefixt werden. scheiß server ganz ehrlich ertränkt euch in eurer eigenen kackpisse und launcht nen ordentlichen server ihr seid eine schande für WoW.
gefickte grüße
warbeidenaffenjungs

**Comment by warbeidenaffenjungs** [comment]
Der Anfang des Textes stimmt 100%
