### ISSUE TITLE
Buff: Attacke des Direktors stackt nicht

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1600]
**Welches Verhalten wird beobachtet?**
Der Buff [Attacke des Direktors](http://datenbank.classic-wow.org/?spell=18264) den man von der Waffe [Attacke des Direktors](http://datenbank.classic-wow.org/?item=13937) bekommt stackt nicht mit Arkane Intelligenz

**Wie sollte es sich verhalten?**
Die zwei Buffs sollten Stacken

**Schritte zur Reproduzierung**
Arkane Intelligenz buffen dann den Buff der Waffe buffen

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://wowwiki.wikia.com/wiki/Headmaster%27s_Charge?oldid=406778
[Arcane Intellect](http://datenbank.classic-wow.org/?spell=1459#see-also-ability)
[Arcane Brilliance](http://datenbank.classic-wow.org/?spell=23028)

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/item=13937/headmasters-charge#comments:id=63

dachte ehrlich gesagt auch, dass er NICHT stackt

**Comment by Slimmer2** [comment]
Naja das sind 2 Aussagen und in Wikia steht es auch das es stackt.
Für Raids wird es eh nicht relevant sein, da man mit dieser Waffe eh keinen Kampf machen wird.
Der Buff Verschwindet ja nach ablegen der Waffe.

**Comment by hraesvelgr** [comment]
ööh wieso unzureichend? wir haben doch 2 quellen genannt, die sagen, dass es so ist, wie der TE es sagt

**Comment by Slimmer2** [comment]
> The buff stacks with the Arcane Intellect buff from mages; however the staff must remain equipped or the buff will disappear. 
Das steht im Wikia beim Datum Revision as of 04:05, January 7, 2007
