### ISSUE TITLE
Quest: "Eine Plage kommt über euch" Zweiter Teil

### ISSUE THREAD

**Issue by Zoffr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1601]
http://datenbank.classic-wow.org/?quest=5904

Die Termiten lassen sich im Sägewerk nicht aussetzen. Die Kiste kann zwar angeklickt werden und es erscheint ein Text, aber das Quest geht nicht weiter. 

Fehler im [Forum ](https://community.mmobase.de/search.php?searchid=424951)schon mehrach gemeldet, aber hier noch nicht.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/456

**Comment by Zoffr** [comment]
Grml, Hab mit dem falschen Suchfeld gesucht. Jetzt finde ich es auch. Danke.
