### ISSUE TITLE
Boss: Abgesandter Roman'khan Quest: Die Anrufung

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1602]
**Welches Verhalten wird beobachtet?**
Soviel ich erfahren habe, macht der Boss seine Fertigkeiten nicht und macht nur Autohit

**Wie sollte es sich verhalten?**
Der Boss Sollte seine Fertigkeiten benützen
[Wilt](http://datenbank.classic-wow.org/?spell=23772)
[System Shock](http://datenbank.classic-wow.org/?spell=23774)
Explode
Drain Life 

**Schritte zur Reproduzierung**
NPC angreifen

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://www.youtube.com/watch?v=ugTBeDCwa6I
https://www.youtube.com/watch?v=jXv0C-JzKPM
http://wowwiki.wikia.com/wiki/Emissary_Roman%27khan?oldid=454496
[Die Anrufung](http://datenbank.classic-wow.org/?quest=8315)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1116

**Comment by Faeleen** [comment]
Zu dem Thema habe ich dieses Video gefunden:
https://www.youtube.com/watch?v=tXTWDwQPSuA
in den Kommentaren wird noch angemerkt, dass es dieser Spell sein soll http://datenbank.classic-wow.org/?spell=23773 den er wirkt wenn er 100% Mana erreicht, was dann dem "Explode" entsprechen würde, wenn ich mich nicht irre.
