### ISSUE TITLE
[Horde/Raid/AQ40] Plattenheiler Items

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1603]
**Welches Verhalten wird beobachtet?**
In AQ40 droppen auf Hordenseite zahlreiche Platten-Heiler Items (selbst "Klasse : Paladin" ).
Diese erfüllen derzeitig keinerlei Funktionen ausser Verkauf/Entzaubern, da die Stats auf den Items unbrauchbar sind. Es beinhaltet teilweise einen enormen Frustfaktor, wenn man beispielsweise bei den Twins, Woche für Woche, den halben nicht-Set-Loot entzaubern darf.

**Wie sollte es sich verhalten?**
Es sollte keinen unbrauchbaren Plattenloot auf Hordeseite geben und damit der potentielle Loottabel zugunsten aller Klassen verbessert werden. Es erscheint natürlich subjektiv inwieweit ein Item unbrauchbar für einen Krieger sein kann, jedoch erfordert das Legen der Bosse bereits deutlich bessere Items und dieser Loot ist keine Belohnung.
"Klasse : Paladin" Items sollten definitiv nicht auf Hordenseite in Raid vorzufinden sein.

**Schritte zur Reproduzierung**
Trashmobs oder Bosse farmen bis die genannten Items auf Hordeseite dabei sind.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Leider keine zuverlässigen Quellen bezüglich der Looteilung von Horde/Allianz 
zu Classic WoW vorhanden. Es ist diesem Sinne eher ein Apell an Logik beim Loot, 
selbst wenn dies nicht 100% blizzlike zu vanilla sein könnte, da alle profitieren.

Liveserver Einträge sind hierbei nicht hilfreich, da dieses Problem mit TBC gelöst wurde.

- http://datenbank.classic-wow.org/?item=21667 Palahosen von Sartura
- http://datenbank.classic-wow.org/?item=21606 Gürtel von den Twins
- http://datenbank.classic-wow.org/?item=21623 Hände von Viscidus
- http://datenbank.classic-wow.org/?item=21683 Schultern vom Bug-Trio
- http://datenbank.classic-wow.org/?item=21704 Stiefel von Skeram
- http://datenbank.classic-wow.org/?item=21889 Hände vom Trash (Klasse:Paladin)

**Zusätzliches:**
Ich weiß das hier keine Quelle vorliegt, also bitte keine Trolls/Mimimis etc.
Wenn es sich tatsächlich nicht um einen Bug handeln sollte, so habe ich mein Möglichstes getan ;)
Für Allyseite und Schami-Mail Items kann ich hierbei nichts berichten, da ich nicht AQ40 auf Allyseite raide.

**Comment by ChichiWarrior** [comment]
Gleiches zählt auch für den Schamanen Loot bei der Allianz, was man so hört bezüglich der Dropps.

Gruß

Chichi

**Comment by Badorr** [comment]
Der Bug, dass z.B. auf der Hordeseite kein Pala T1 oder T2 droppen sollte, ist in der Tat logisch. Dieser Bug kam in Classic in MC vor und wurde, soweit ich weiß, schnell gefixt. Man beachte hierbei, dass diese Setitems aber auch eine klar definierte Klassenbeschränkung haben.

Es gibt genau ein Offsetitem mit Klassenbeschränkung in AQ 40 und zwar die oben verlinkten Plattenhandschuhe vom Trash. Ansonsten sind alle Items ohne Klassenbeschränkung und sollten daher bei beiden Fraktionen droppen können. Schließlich können Paladine ja Schwere Rüstung tragen und einige der "für Schamanen gedachten" Items sogar gebrauchen. Ob das fair ist, sei mal dahingestellt. Ein Bug ist es meiner Meinung aber nicht.

**Comment by ChichiWarrior** [comment]
Die "Schamanen" Items, die bei der Allianz droppen, werden genauso gedisst, wie die Paladin Plattenitems die bei der Horde droppen.

Bossloot war neben den Tier Sets noch nie Klassenspezifisch. Schon immer nur der Trashloot. Wurde irgendwann geändert.

Ein Item, dass absolut keinen Verwendungszweck hat (siehe Platten Healgürtel bei Twins), kann nicht beabsichtigt bei einer Fraktion droppen und andersrum.

Ich hab das Internet etwas durchforstet, doch leider findet man keine aussagekärftige Quelle, da die Items durch die fortlaufenden Addons modifiziert wurden.

Ich kann mich Horim nur anschließen, auf eine Quelle von jemanden hoffen und an den Menschenverstand appellieren.

Gruß

Chichi

**Comment by Badorr** [comment]
http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21668
http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21607
http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21626

Werden getragen und benutzt, auch von den Kollegen mit den pinken Namenstafeln
 
Habe damals auch schon auf Hordeseite geraidet und bin mir ziemlich sicher, dass im TS während AQ 40 immer mal wieder über 'Palaloot' gestöhnt wurde. Solange niemand mein Langzeitgedächnis mit einer eindeutigen Quelle des Irrtums überführt, würde ich diesen Pain auch gerne so in Erinnerung behalten. 

Und das mit dem gesunden Menschenverstand ist auch so eine Sache. Wenn das Dropsystem in Classic mit gesundem Menschenverstand entworfen worden wäre, würden mindestens 15 Items pro Boss droppen.

**Comment by Horim** [comment]
Diese Pain hat keinerlei Sinn, denn diese Items sind bis auf den Verkaufswert oder Nexuskristalle wertlos. Ich verstehe nicht inwiefern es Spieler benachteiligt oder Ihnen ein falsches Spielgefühl vermitteln soll, wenn dieser Frust zukünftig erspart bleiben sollte. 

Die einzigen Nachteile die sich hieraus ergeben: 
- es wird weniger entzaubert (OH NOES!)
- "Retrofrust" – falls es ihn überhaupt gab – entfällt (OH NOES!)

Zur Allianz Seite zu der ich nicht viel sagen kann:
- http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21668 für Palatwinks sicher nützlich oder wenn man versucht jemanden nach zu gearen
- http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21607 schön das auch nützliche Retri-Mail-items existieren
- http://www.realmplayers.com/ItemUsageInfo.aspx?realm=NEF&item=21626 Resi-Items sind jetzt nicht das beste Beispiel, die Hose ist leider BiS was die Naturresi angeht

Die Items die ich aufgezählt habe sind hingegen auf Hordeseite alle gegen rare Gear aus 5er Instanzen eintauschbar. Dein Vergleich zum Menschenverstand ist mir leider nicht verständlich, ich habe keine radikale Veränderung des Spielerlebnisses gefordert, sondern lediglich darum gebeten Items fraktionsspezifisch zu streichen weil diese keine Belohnung sind.

**Comment by Badorr** [comment]
'Dieser Pain hat keinerlei Sinn'

Es gibt viele Dinge in Classic, die etwas pain sind. Craftbare tems, für die der Char eine Minute lang rumsteht. Zwecks Umskillen jedes Mal zum Klassenlehrer rennen, von denen es pro Kontinent teilweise nur einen gibt. Einen Flugpunkt pro Gebiet. Spärlich verteilte Briefkästen. Instanzen, deren eigentlicher Eingang sich erst hinter Horden von Elitemobs befindet. Ein immens zeitfressendes und zehrendes PvP-System, bei dem der ein oder andere schon eine Art WoW-Burnout davontragen hat. Tränke und Elixiere, die auf beeindruckende 5 Einheiten pro Stack begrenzt sind. Mit 40 Mann raiden und dann pro Boss oft nicht mehr als 2 Drops als Belohnung erhalten. 

Den Sinn von Classicfeatures kann man in mannigfaltiger Weise anzweifeln und zu jedem der oben genannten Punkte könnte man sicher stichhaltige Argumente für eine Änderung liefern. Und du hast hier natürlich völlig Recht, würde man die Plattenheileritems rausnehmen, wäre der Loottable ausgreifter. Optimiert. Was möchtest du als Nächstes optimiert haben? 
Horim stört dieses mehr, Badorr stört jenes mehr. Und Ghichi nervt was völlig Anderes. Alle kommen zu Dotox und möchten es optimiert haben. Aber alle kennen die Regeln: ohne Quellenangabe läuft nichts.

**Comment by Horim** [comment]
Du drängst nach Quellenangaben und gibts selbst Sachen von dir wie: 
"Habe damals auch schon auf Hordeseite geraidet und **bin mir ziemlich sicher ...** ".  

Wie soll man bei solchen Aussagen auf ernsthafte oder auch konstruktive Debatten hoffen?
Sorry, inwiefern hat deine Aufzählung von Unzulänglichkeiten auch nur das geringste mit dem Thema zu tun? Davon steht hier nichts, nicht im Titel und auch nicht im Eröffnungspost. 

Wenn du deinen Frust zu Classic WoW abbauen willst, kannst du gerne eigene Posts im Bugtracker machen und auf das beste hoffen, anstatt andere damit voll zu jammern.

Bevor ich mich hier noch reinsteigere, komme ich lieber zurück zum Thema:

Zur Sartura Hose: 
- http://wowwiki.wikia.com/wiki/Legplates_of_Blazing_Light (Alliance ONLY)
- http://wowwiki.wikia.com/wiki/Legplates_of_Blazing_Light?diff=168359&oldid=138446 
Hier einmal eine Revision aus 2006

Auch ganz interessant:
http://wowwiki.wikia.com/wiki/Talk:Legplates_of_Blazing_Light
Anscheinend soll es ein System gegeben haben, welches die Plattenhose auf Hordenseite durch die Mail Hose ersetzt hat. Ohne weitere Quellen ist es natürlich sehr weit hergeholt, das auf alle "Pala" oder "Schami" Dropps in AQ40 zu beziehen. Von daher wäre ich jedem verbunden der hierzu etwas beitragen kann, statt wegen jedem Mist zu jammern ;)

**Comment by Badorr** [comment]
Der Status Quo ist, das diese Items droppen. DU musst beweisen, dass diese Items NICHT droppen sollten. Ich muss NICHT beweisen, dass sie droppen KÖNNEN. Das ist ein eklatanter Unterschied.  Und du musst es mit eindeutigen Quellen beweisen. Da du zu Anfang gar keine Quellen hattest (warum man auch immer auf die Idee kommt, einen Bugtrackerpost überhaupt gänzlich ohne Quellen zu erstellen), haben wir ein wenig darüber spekuliert und philosophiert.

Aber was du oder ich darüber denken, warum Plattenheileritems droppen sollten oder nicht, was logisch sei und was nicht, was Sinn hat und was nicht, tut im Endeffekt aber nichts zur Sache. Da kann man ewig drüber streiten und das kann man auch auf ganz andere Gebiete ausweiten. DAS wollte ich dir mit meinen Beispielen nahe bringen, aber das hast du offensichtlich nicht begriffen. Sieht man daran, dass jetzt der Meinung bist, ich würde darüber jammern. Himmel....

Immerhin gibt es jetzt ein paar Quellen. Damit kann man doch arbeiten

**Comment by Horim** [comment]
Deine "Beispiele" hatten leider nichts mit dem Thema zu tun. 

Die subjektive Wahrnehmung vom Wert des Loots, ist etwas worüber sich streiten lässt. 
Aber warum du meinst, das zu wenige Flugpunkte und Briefkästen in der Welt sind, wenn ich über Troll-Loot schreibe, verstehe ich nicht. Es erschließt sich mir auch nicht, inwieweit dein Langzeitgedächtnis mit der Situation hier auf dem Server korreliert. Ich habe zu keinem Zeitpunkt behauptet, das ich mir _ziemlich sicher sei_, das die Loottables falsch sind, sondern gehofft auf positiven Anklang zu stoßen -> Alleine für jedes Item zu Suchen, dafür ist mir meine Freizeit doch zu schade.

Wenn ich bedenke, wie viel Zeit man mit der Diskussion der Loottables verschwendet, weil man:
- immer in der Bringschuld ist und
- Trollen für die Gegenseite bequemer ist, als sich **einmal die Mühe zu machen** Gegenbeweise zu liefern, 

dann frag ich mich wozu ich das hier mache. 

"Haha du hast keine Quelle, damit ist das hier alles Zeitverschwendung" -> Man das ist doch Klasse!
#1626 ist sehr schnell mit hieraus entstanden, weil mich ein paar bei der Recherche unterstützt haben. 

BWL ist schon wie lange auf diesem Server, 2 Jahre? Und in 2 Jahren hat sich keiner  die Mühe gemacht, einfach mal nach zu schauen und es hier zu hinterlegen.

In diesem Sinne _Danke_ für deinen sinnvollen Beitrag. :+1:

**Comment by Badorr** [comment]
Wenn du etwas geändert haben möchtest, bist du nun mal in der Bringschuld. Dafür kannst du dich gerne selbst bemitleiden, aber so ist es halt. Und dir auch ein Danke für deinen indirekten Trollvorwurf. Sehr reifer Diskussionsstil.

Wir reden scheinbar völlig aneinander vorbei und dafür ist mir meine Zeit auch zu schade :)

**Comment by soda09** [comment]
Heißt dass jetzt, dass Plattenitems mit +Spell drauf auf Hordenseite doof sind, weil sie keiner nutzen kann und diese deshalb nicht droppen dürften? Und schlussfolgernd daraus, dürften dann keine Schwere-Rüstungsitems mit +Spell auf Alliseite droppen, obwohl sie jemand tragen könnte?

**Comment by ChichiWarrior** [comment]
> Heißt dass jetzt, dass Plattenitems mit +Spell drauf auf Hordenseite doof sind, weil sie keiner nutzen kann und diese deshalb nicht droppen dürften? Und schlussfolgernd daraus, dürften dann keine Schwere-Rüstungsitems mit +Spell auf Alliseite droppen, obwohl sie jemand tragen könnte? 

Nein, so wie der Loot im Moment ist, ist er bewiesen falsch.

Gruß

Chichi

**Comment by Horim** [comment]
Einzige Frage die sich stellt, falls/sobald dieses Problem angegangen wird:
Was passiert mit den Mail/Platte Items die tatsächlich bei der Gegenfraktion getragen werden?
Einfach Umtauschen gegen das Platte/Mail äquivalente Item, wie bei T1/2 ?

**Comment by Slimmer2** [comment]
Seit wann wird t1/t2 umgetauscht?

**Comment by Horim** [comment]
Als noch Pala T2 auf Hordenseite gedroppt ist, konnte man es gegen Schamanen T2 eintauschen lassen.

**Comment by ary1** [comment]
Hi, 
wollte mal nachfragen wie es bei diesem Thema im Moment aussieht.
Was bedeutet hier das Dev behoben ?

Es dropen weiterhin auf Hordeseite jede Menge Pala-Heiler Items.

**Comment by dagochen** [comment]
Ja der Fix hat nicht so geklappt wie geplant. Auf dem Testserver ist bereits eine verbesserte Version, die das Problem soweit ich es jetzt getestet habe behoben hat. Da wir diesmal aber auf Nummer Sicher-Sicher gehen wollen, dauert es noch einen Moment ;)

**Comment by ChichiWarrior** [comment]
Es droppen weiterhin Plattenheiler Items bei der Horde

**Comment by dagochen** [comment]
Beispiel?

**Comment by ChichiWarrior** [comment]
http://realmplayers.com/RaidStats/FightOverview.aspx?Raid=49477&Fight=4

http://datenbank.classic-wow.org/?item=21606 Gürtel von den Twins

**Comment by dagochen** [comment]
Alle guten Dinge sind 3....

Stellt mich an den Pranger :( Ich schäm mich so :(

**Comment by Horim** [comment]
Danke =)
