### ISSUE TITLE
Hexerquest: Komponenten für die verzauberte Goldblutrobe

### ISSUE THREAD

**Issue by ralffechner** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1608]
Char Kundry. Xizk Gutstich ist nur als Händler ansprechbar. Er gibt den feinen Goldfaden leider nicht raus. Die anderen Komponenten sind vorhanden.

**Comment by Slimmer2** [comment]
Die Quest bekommt man erst mit Level 37.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1079
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/998
