### ISSUE TITLE
Quest: Der geistesabwesende Ausgrabungsleiter Schritt 3

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1611]
Was wird beobachtet: Abgabe der [Quest](http://datenbank.classic-wow.org/?quest=942) nicht möglich, obwohl ich das [Questitem](http://datenbank.classic-wow.org/?item=4654) im Inventar habe. Der [Quest-NPC](http://datenbank.classic-wow.org/?npc=2911) hat auch kein Fragezeichen über dem Kopf und der gelbe Punkt auf der Minimap ist ebenfalls nicht da.

Wie sollte es sein: [Quest-NPC](http://datenbank.classic-wow.org/?npc=2911) sollte gelbes Fragezeichen über dem Kopf haben und die Questabgabe akzeptieren, dann die [Folgequest](http://datenbank.classic-wow.org/?quest=943/Der%20geistesabwesende%20Ausgrabungsleiter) geben.

Schritte zur Reproduktion: Questreihe bei [Chefarchäologe Grauflaum](http://datenbank.classic-wow.org/?npc=2912) beginnen, führt über Dunkelküste und folgende Quests:

[Ärger in Dunkelküste](http://datenbank.classic-wow.org/?quest=730)
[Der geistesabwesende Ausgrabungsleiter](http://datenbank.classic-wow.org/?quest=729/Der%20geistesabwesende%20Ausgrabungsleiter)
[Der geistesabwesende Ausgrabungsleiter](http://datenbank.classic-wow.org/?quest=731)
[Der geistesabwesende Ausgrabungsleiter](http://datenbank.classic-wow.org/?quest=942/Der%20geistesabwesende%20Ausgrabungsleiter)

Im Bugtracker wurde bereits ein Problem bei der Abgabe von S[chritt 4](http://datenbank.classic-wow.org/?quest=943/Der%20geistesabwesende%20Ausgrabungsleiter) gemeldet, bei mir buggt es aber schon vorher, da ich Schritt 4 gar nicht erst annehmen kann.

**Comment by hraesvelgr** [comment]
wdb ordner mal gelöscht? ohne addons abgeben versucht?

**Comment by dwilhelms** [comment]
Ja, alles: keine Addons, WDB sauber, Ausloggen/Einloggen, neu annehmen.....bringt alles nix.

**Comment by dwilhelms** [comment]
Heute hat es wieder funktioniert. Ich konnte die Quest abgeben und die neue annehmen.
