### ISSUE TITLE
Teleport der Twins in AQ40 wählt tote Spieler an.

### ISSUE THREAD

**Issue by Gipsyjodler** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1612]
Welches Verhalten wird beobachtet?
Die NPCs Imperator Vek'nilash (http://datenbank.classic-wow.org/?npc=15275#abilities) und Imperator Vek'lor (http://datenbank.classic-wow.org/?npc=15276#abilities) wählen beim Teleport auch tote Spieler an, die den Geist nicht frei gelassen haben. Die Folge daraus ist, dass die 3000 Initialaggro die der nächste Spieler bekommen sollte verschwinden und die Twins ein zufälliges Ziel auswählen und nicht den nächsten Spieler. Außerdem werden die Twins dann falsch angezeigt. Also sie werden an einer anderen Stelle angezeigt, wo sie normalerweise stehen sollten. Beim nächsten Teleport steht der Twin ungefähr wieder an der richtigen Stelle. 

Wie sollte es sich verhalten?
Die Twins wählen beim Teleport den nächsten Spieler an und dieser bekommt 3000 Initialaggro. Tote Spieler sollten dabei nicht angewählt werden können, da sie nichtmehr im Kampf sind.

Schritte zur Reproduzierung
Ein Toter Spieler muss einfach als nächstes an den Twins liegen und den Geist nicht freilassen. Danach wird beim Teleport ein zufälliger Spieler (meistens Heiler, wegen Healaggro) angewählt und angegriffen.

Hier erkennt man leider nicht genau wie der Bug abläuft aber, nachdem ein Krieger am Boss stirbt fangen die Twins an zu laufen anstatt sich zu teleportieren und befinden sich nicht an der Stelle wo sie angezeigt werden. Hier ist das Imperator Vek'lor, der dann zu laufen beginnt nach dem Teleport.

https://www.youtube.com/watch?v=suUGF3i9plQ&feature=youtu.be

**Comment by ChichiWarrior** [comment]
Könnte man das bitte ausgiebig und gezielt testen?

Mir ist derartiges noch nicht aufgefallen, bzw. kann ich das so nicht bestätigen.

Bitte erst nach ausgiebigen Tests und Quellen irgendwas am Boss verändern, denn bis auf unwichtige Kleinigkeiten funktioniert der Bossfight einwandfrei und ohne Probleme.

Gruß

Chichi

**Comment by Gipsyjodler** [comment]
Kannst du testen indem du einen toten Spieler der den geist nicht freilässt als nächstes am Boss liegt. Nachdem dieser Spieler den Geist frei lässt funktioniert der Boss wieder Normal, da er nicht mehr angewählt werden kann. Meistens tritt der Bug dann auf wenn ein Meele DD 2x hintereinander den Uppercut bekommt und stirbt, da er dann direkt am Boss liegt.
Außerdem hat dieser Bug nichts mit dem Boss an sich zu tun. Palabuffs werden z.B. auch auf Tote Spieler gebufft die den Geist nicht frei gelassen haben. Zumindest sieht man da die Animation auf den Spielern. Ist aber das gleiche Prinzip.

**Comment by ChichiWarrior** [comment]
Wie gesagt, kann ich nicht bestätigen. Der Boss ist bei uns auch ohne Toten schon gelaufen.

Und der Boss selbst steht an der Teleportstelle...er läuft nur optisch.

Deswegen bitte ausgiebig testen, denn so wie der Boss im Moment läuft, gibt es nichts was man ändern müsste.

**Comment by Gipsyjodler** [comment]
Ja das mit dem Laufen anstatt Teleportieren hat damit denke ich nichts zu tun, da dabei der Aggrowechsel trotzdem noch Funktioniert. 
Ich versuche noch eine bessere Aufnahme davon zu bekommen. Leider konnten wir die Twins erst Vorgestern wieder zum ersten mal killn, deshalb erst jetz der Bugreport :)

**Comment by Badorr** [comment]
Mir ist ein Zusammenhang auch noch nie aufgefallen, daher habe ich mal ein paar meiner Twinsvideos rausgekramt. Sind leider kaum eine handvoll. Denen zufolge kann ich den genannten Bug nicht bestätigen, allerdings stammen die Videos teilweise noch von Januar/Februar/März.

Was immer zu passieren scheint wenn ein toter, in der Leiche befindlicher Spieler neben dem Castertwin liegt: er spammt seine Arkane Explosion.

**Comment by Gipsyjodler** [comment]
Natürlich ist es wichtig dabei zu beobachten ob der Tote Spieler beim Teleport wirklich der nächste in der Hitbox ist. Wenn sich der Tank dann noch näher in die Hitbox stellt sollte natürlich wieder dieser ausgewählt werden. 
Wenn es wirklich so ist wie beschrieben sollte es ja leicht sein den Bug zu reproduzieren.

**Comment by ChichiWarrior** [comment]
Wurde schon getestet? Oder kommt diese Woche noch jemand zum testen?

**Comment by Gipsyjodler** [comment]
https://www.youtube.com/watch?v=vOiSfTkfI2E
In diesem Video sieht man beim Aggrowechsel bei 0:55 und 1:25 dass sich ein toter Spieler am nächsten am Boss befindet. 
Nach dem Wechsel bei 0:55 hat zufällig der Magier Aggro und nicht der Hexenmeister. Der Hexenmeister bekommt allerdings die Aggro sofort da der Magier nicht die 3000 Initialaggro erhalten hat. 
Bei dem Wechsel bei 1:25 hat sofort ein Heiler Aggro. Dieser steht aber wesentlich weiter entfernt als der Krieger. 

Nachdem die 2 Spieler den Geist frei gelassen haben oder der Tank näher als die Leiche am Boss liegt funktionieren die Aggrowechsel wieder wie gedacht. Wie oben bereits gesagt, geht es hier nicht um das Laufen beim Teleport sondern NUR um den Aggrowechsel.
