### ISSUE TITLE
Ketana Dabyries (Quest : Von Dieben stehlen)buggy?!

### ISSUE THREAD

**Issue by Urmelli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1613]
Die gute Damen (Position 56,5 36.0 laut ShaguDB im Arathihochland) entwaffnet ca alle 2-6 Sekunden,spätestens nach 10
. Es ist quasi als Meele unmöglich irgendwelchen Schaden zu machen oder Skills zu benutzen, da man permanent entwaffnet wird/ist.

**Comment by hraesvelgr** [comment]
an die post-form halten. das kann nichtmal ansatzweise als bugreport verwendet werden, zumal du den namen der frau falsch geschrieben hast. (musste erstmal rausfinden, wen du überhaupt meinst)
