### ISSUE TITLE
Schwadroneur der Blutsegelbukaniere flüchtet nicht

### ISSUE THREAD

**Issue by Dynaevil** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1614]
Die Schwadroneur der Blutsegelbukaniere an der südlichen Küste vom Schlingendorntal flüchten nicht richtig. So wie es aussieht stellen die nur den Angriff ein, laufen auf den Angreifer zu und warten.

**Comment by hraesvelgr** [comment]
an die vorlage halten...
