### ISSUE TITLE
Stealth der Syndikatschurken im Arathihochland

### ISSUE THREAD

**Issue by r4yn0r** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1617]
Die Schurken auf der Farm links oben im Arathihochland des Schurkentyps stealthen nicht standardmäßig beim Spawn.

Sie stealthen erst, nachdem man sie engaged, wegläuft, sodass "leaving combat" erscheint.

Im Alteractal ist es das gleiche mit den Stealth Einheiten des Syndikats.

**Comment by Slimmer2** [comment]
Bitte an die Vorlage halten

**Comment by hraesvelgr** [comment]
abgelehnt weil wie slimmer sagte.
