### ISSUE TITLE
Kräuterpopulation + Trümmerfelder + Weisenfischschwärme Ratchet

### ISSUE THREAD

**Issue by carrassonne** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1619]
Südlich von Ratchet befindet sich südlich auf den Klippen vermehrt Würgetang. Zudem ist der Steg in Ratchet "voller" Trümmerfelder/Weisenfischschwärme mit "sehr schneller" Spawnzeit.

**Comment by hraesvelgr** [comment]
bitte an die vorlage halten. suchfunktion nutzen. und nur ein problem pro report.
