### ISSUE TITLE
Druide: Wolfskopfhelm funktioniert nicht korrekt

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#162]
Welches Verhalten wird beobachtet?
Durch den Helm sollte ein Druide 20 zusätzliche Energie beim Shiften erhalten. Dies ist jedoch nicht der Fall. Für Wut funktionierts.

Wie sollte es sich verhalten?
Druide mit Ingrimm 5/5 sollte mit dem Helm zusammen auf 60 Energie (not working) und 15 Wut (working) kommen.

Schritte zur Reproduzierung
Wolfskopfhelm anlegen und in Katze wechseln.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www.twitch.tv/dagochen/c/5476547

**Comment by dagochen** [comment]
Dann kann der hier zu.

**Comment by drgrey** [comment]
Ich habe nochmal über den Wolfskopfhelm (http://datenbank.welli-it.de/?item=8345) recherchiert.
Laut http://www.wowwiki.com/Wolfshead_Helm, sind a) die Stats anders und b) kann ich nach belieben keinen CD für die Fertigkeit finden (auch keine Patchnotes). Ich weiß leider nicht mehr welcher GM das damals getestet hat, aber vllt könnte derjenige sich dazu noch mal äußern und seine Quellen verlinken? Den Thread kann ich leider auch nicht mehr finden. Der wurde wohl gelöscht...

**Comment by dagochen** [comment]
Das mit den Stats war früher so und ist bei uns auf dem Server richtig. 

Proof: http://www.wowwiki.com/Wolfshead_Helm?direction=next&oldid=534382

**Comment by drgrey** [comment]
Danke dir :)
Ich war zu doof die HIstoryfunktion zu nutzen :D
