### ISSUE TITLE
Jägerbegleiter versetzt Jäger in den Kampf

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1623]
Welches Verhalten wird beobachtet?
Mein Begleiter versetzt mich (Level 23 Nachtelfjäger) in den Kampf.

Wie sollte es sich verhalten?
Mein 60iger (Zwerg-)Jäger wird nicht in den Kampf versetzt. So sollte es sein.

Schritte zur Reproduzierung
Nur den Begleiter einen Gegner angreifen lassen.

**Comment by Haudraufinix** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1496

kannste closen
