### ISSUE TITLE
Falsche Castzeit: Gezielter Schuss 

### ISSUE THREAD

**Issue by Donf4b** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1625]
**Welches Verhalten wird beobachtet?**

Der Gezielte Schuss braucht ohne Angriffstempo Boni 4 Sekunden, statt der im Tooltipp angegeben 3 Sekunden. 
Selbst gemessen. Von anderen Jägern bestätigt. 
Angriffstempo Boni skalieren richtig. Mit 15% Köcher Bonus braucht der Gezielte Schuss ca. 3,5 Sekunden. Mit zusätzlichem Schnellfeuer 40% Angriffstempo Bonus ca. 2,5 Sekunden.

DB: http://datenbank.classic-wow.org/?spell=20904

**Wie sollte es sich verhalten?**

Die Castzeit sollte ohne Boni 3 Sekunden betragen. 
Mit Köcher sollte sie **2,6** _(3s / 1,15)_ und 
mit zusätzlichem Schnellfeuer  **1,86** _[3s / (1,15 * 1,4)]_ Sekunden betragen.

**Schritte zur Reproduzierung**

Ohne/mit Boni Timer und Gezielten Schuss starten.

**Comment by Slimmer2** [comment]
Quellen?

**Comment by booneyclassic** [comment]
Habe es auch probiert und kann es bestätigen.
Alle Tempoerhöhungen skalieren korrekt, jedoch auf den falschen Wert von 4 anstatt 3 Sekunden, wie es ja auch angegeben ist.


MFG
Booney

**Comment by soda09** [comment]
Das kann man sich alles ausrechnen. So wie es oben beschrieben ist, ist es korrekt: 
3/1.15=2.6 (so sollte es beim Beispiel mit dem Köcher sein)

**Comment by Sheed90** [comment]
Den Bug kann ich so bestätigen. Wenn man Big Trouble nutzt sieht man, dass die Castzeit (mit Köcher) bei ca. 3,3 Sek. anfängt.

Mich wundert nur, dass das vorher nie aufgefallen ist. Der Bug ist schon ziemlich tiefgreifend.

Gruß

**Comment by Donf4b** [comment]
Hallo nochmal,
die castzeit mit dem Köcher beträgt immernoch um die 3,5 sekunden und ohne 4 sekunden.
Fehler besteht also leider immernoch.
lg

**Comment by dagochen** [comment]
@Donf4b Kann man dich ingame irgendwie erreichen?

**Comment by dagochen** [comment]
Hallo Jägersleute,

ich versuche mal etwas Licht ins Dunkel zu bringen. Dazu werde ich einmal beschreiben, wie es vor dem Bugfix war, wie es jetzt ist und warum wir es so gemacht haben, wie wir es gemacht haben.

Wie war es vorher?
Bei der Berechnung der Castzeit vom Gezielten Schuss wurden alle Geschwindigkeitsboni einbezogen. Dadurch wurde die Basis-Castzeit von 3 Sekunden durch einen Köcher auf ca. 2,6 Sekunden verringert. Anschließend wurde diese um 0,5 Sekunden erhöht. Die 0,5 Sekunden kommen von der Castzeit für den Mehrfachschuss, welcher eine Basis-Castzeit von 0 Sekunden hatte und daher erhöht werden musste, damit dieser kein "Instant-Cast" ist. 
Fazit:
Gezielter Schuss: 3,1 Sekunden oder höher (je nach Köcher. 
Gezielter Schuss: profitierte von ALLEN Geschwindigkeitsbonis).
Mehrfachschuss: 0,5 Sekunden (profitierte von KEINEM Geschwindigkeitsbonis)

Wie ist es jetzt?
Gezielter Schuss ignoriert den Köcherbonus und profitiert lediglich von anderen Tempo-Bonis.
Die Basiscastzeit von 3,0 Sekunden gilt also immer, wenn ihr grad kein Schnellfeuer oder Schnelle Schüsse aktiv habt. Der Mehrfachschuss macht also die Castzeit des Gezielten nicht mehr "kaputt", da die jetzt unabhängig von einander berechnet werden. Dafür profitiert auch der Mehrfachschuss von Schnellfeuer,etc.
Fazit:
Gezielter Schuss: 3,0 Sekunden (profitiert von allen Tempo-Bonis, außer dem Köcher)
Mehrfachschuss: 0,5 Sekunden (profitiert von allen Tempo-Bonis, außer dem Köcher)

Warum genau so und nicht anders?
In den Hunterguides der letzten 10 Jahre wird stets darauf hingewiesen, dass die Armbrust aus BWL, Ashjre'tul, die ideale Waffe für die Hunterrotation sei. Die Waffe hat ein Tempo von 3,4 Sekunden, welches durch einen Köcher mit 15% auf 2,96 Sekunden verringert wird. Diese knapp 3 Sekunden sind der Grund, weshalb die Waffe so ideal ist. Ihr Autoschusstimer läuft genau dann ab, wenn der Gezielte Schuss durch ist. Weiter gehen alle Berechnungen in den Guides und Spreadsheets von 3 Sekunden für einen Gezielten Schuss aus. Daher würde ein Anrechnen des Köchers auf den Gezielten diesen Quellen widersprechen. Auch würde es andere, schnellere Waffen gegenüber Ashjre'tul stark aufwerten. Habe ich beispielsweise einen Bogen mit einem Tempo von 2,9 Sekunden, durch Köcher dann 2,52 Sekunden, dann muss der Automatische Schuss fast eine halbe Sekunde warten, bis der Gezielte Schuss fertig ist. Würde der Köcher auf den Gezielten Schuss angerechnet werden, müsste man nur 0,2 Sekunden warten, was die schnelle Waffe signifikant besser machen würde.

TL;DR
Gezielter Schuss brauch bisschen weniger Castzeit. Mehrfachschuss profitiert von Schnellfeuer und Schneller Schüsse. 

Bei weiteren Fragen, Problemen oder Unklarheiten einfach nochmal melden. Hoffe ich habe alle (Un-)Klarheiten beseitigt *g*

**Comment by Sheed90** [comment]
Sieht gut aus auf dem Testserver!

**Comment by Dotox** [comment]
Testserver = Live-Server Version

**Comment by Donf4b** [comment]
Heißt also, dass ich durch die gemessenen 3,45s eine Latenzverzögerung von 0,45s habe. Bei einem Ping von 12ms.

Ohne Köcher bleibt es bei dieser Zeit. 
Mit Schnellfeuer reduziert sie sich dementsprechend richtig auf ca. 2,5s.
Mit Schnelle Schüsse reduziert sie sich dementsprechend richtig auf  ca. 2,7s.

Die Trollfähigkeit Berserker (http://datenbank.classic-wow.org/?spell=20554) scheint jedoch nicht damit zu skalieren (gemessen mit vollem Leben --> 10%).

Danke erstmal für die Erklärung. Allerdings sehe ich im Bezug auf die perfekten 3sekunden die Rotation etwas anders. Da sich der automatische Schuss um 0,5s nach dem Abfeuern des gezielten Schussen verzögert, kommt man nun auf eben mindestens diese Zeit als Verzögerung des nächsten automatischen schusses (minimum 0,54s vorrausgesetzt autohit und gezielter würden gleichzeitig starten, dementsprechend in der realität etwas höher).
Als der gezielte Schuss noch vom köcher profitierte konnte man diese verzögerung um 0,4s reduzieren, womit es eindeutig besser zum nächsten autohit passt.

Nach diesem Prinzip läge das optimale waffentempo bei ca. 3,6s ( 3,1s mit köcher = 2,6s gezielter schuss + 0,5s verzögerung). _(vorrausgesetzt autohit und gezielter würden gleichzeitig starten, dementsprechend in der realität etwas höher)_

Das ideale Waffentempo bei aktuellem stand liegt dementsprechend sogar noch höher (bei ca. 4s --> durch köcher autohit alle 3,5s = Gezielter schuss 3s + 0,5s verzögerung). _(vorrausgesetzt autohit und gezielter würden gleichzeitig starten, dementsprechend in der realität etwas höher)_

Im Bezug auf die "Endgame" Waffen aus Naxxramas, welche ein tempo von 2,9 und 3,2 aufweisen, scheint ein optimales tempo von 4s doch etwas sehr hoch.

Ich meine das alles schon relativ gut verstanden zu haben, deshalb würde ich mich über eine antwort sehr freuen. gerne auch per pm

lg

**Comment by dagochen** [comment]
In der Theorie mag es richtig sein, dass eine noch langsamere Waffe tatsächlich besser für die Rotation wäre, aber es gibt sie einfach nicht. Daher ist die Praxis nun mal so, wie sie ist ;) Die Verzögerung ist bei allen gleich, Server- und Netcode-bedingt, es sei denn du sitzt auf der anderen Seite der Welt vor deinem PC. Gibt also nicht wirklich etwas, was man da noch machen könnte. 

Zum Berserker: Guck ich mir mal an.

**Comment by Donf4b** [comment]
Also der Mehrfachschuss hat die rotation eigentlich nie wirklich unnötig verzögert, auch ohne boni. :p 
und der gezielte schuss ist jetzt natürlich 0,5sekunden schneller. wenn er vom köcher profitieren würde wäre natürlich mehr drin, sehe auch keinen grund warum er nicht von ALLEN angriffstempo boni profiteren sollte. Alle entsprechenden boni erhöhen wortwörtlich das (Distanz-)Angriffstempo.

Die aussage der hunterguides die armbrust aus bwl sei perfekt deckt sich aber doch eher mit der rechnung, bei der ein tempo von 3,6 optimal wäre als die aktuelle, bei der ein tempo von 4,0 optimal ist.

ich bin natürlich glücklich mit den gewonnen 0,5sekunden aber nicht vollends zufrieden.^^
Vielleicht ist es auch nur der tiefe wunsch den DPS des jägers anzuheben :)

**Comment by dagochen** [comment]
Wie kann man dich denn erreichen..?

**Comment by Donf4b** [comment]
ach hier kann man garkeine private nachrichten schicken.
discord? https://discord.gg/YmBrc
