### ISSUE TITLE
[Raids / Loottable] "Pala/Schami" - Items

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1626]
In Anlehnung an #1603:

**Welches Verhalten wird beobachtet?**
In ZG, AQ20 und BWL droppen auf Hordenseite zahlreiche Platten-Heiler oder Retri Items.
Diese erfüllen derzeitig keinerlei Funktionen ausser Verkauf/Entzaubern, da die Stats auf den Items unbrauchbar sind. 

**Wie sollte es sich verhalten?**
Es sollte keinen unbrauchbaren Plattenloot auf Hordeseite geben, bzw. auch keinen unbrauchbaren Mailloot auf Allianzseite, damit der potentielle Loottabel zugunsten aller Klassen verbessert wird.

**Schritte zur Reproduzierung**
Bosse farmen bis die genannten Items auf Horde/Allianzseite dabei sind.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Die Quellen sind unvollständig, jedoch könnte man annehmen, das Blizzard beim Loottable der gennanten Raids konsequent war. Die Items treten immer als Paarung auf (z.B. Platte+Mail Hände) um sich im Loottable zu ersetzten.Die jeweiligen ZG-Bosse haben zu den genannten Quellen auch meist neben dem Settoken 1 Item  "mehr" im Loottable.

**ZG:**
Jeklik
- http://datenbank.classic-wow.org/?item=20262 Mail Stiefel 
- http://wowwiki.wikia.com/wiki/Seafury_Boots?oldid=269634 Horde only (Oktober 2006)
- http://datenbank.classic-wow.org/?item=20265 Platten Stiefel 
- http://wowwiki.wikia.com/wiki/Peacekeeper_Boots?oldid=269711 Alliance only (Oktober 2006)

Hakkar
- http://datenbank.classic-wow.org/?item=20264 Platten Handschuhe
- http://wowwiki.wikia.com/wiki/Peacekeeper_Gauntlets?oldid=381921 Ab 2.01 bei beiden Fraktionen (Dezember 2006, bereits Patchstand 2.01)
- http://datenbank.classic-wow.org/?item=20257 Mail Handschuhe

Thekal
- http://datenbank.classic-wow.org/?item=20266 Platten Hose
- http://datenbank.classic-wow.org/?item=20260 Mail Hose

**AQ20:**
Buru:
- http://datenbank.classic-wow.org/?item=21486 Platten Handschuhe
- http://wowwiki.wikia.com/wiki/Gloves_of_the_Swarm?oldid=276566 Alliance only (Oktober 2006)
- http://datenbank.classic-wow.org/?item=21487 Mail Hände

Moam:
- http://datenbank.classic-wow.org/?item=21476 Mail Hose
- http://wowwiki.wikia.com/wiki/Obsidian_Scaled_Leggings?oldid=323896 may be Horde only (November 2006)
- http://datenbank.classic-wow.org/?item=21475 Plattenhose

Ossirian:
- http://datenbank.classic-wow.org/?item=21454 Mail Schultern
- http://datenbank.classic-wow.org/?item=21453 Platten Schultern

Ayamiss:
- http://datenbank.classic-wow.org/?item=21482 Mail Stiefel
- http://datenbank.classic-wow.org/?item=21481 Platten Stiefel

**BWL:**
Chrommagus:
- http://datenbank.classic-wow.org/?item=19392 Platten Gürtel
- http://wowwiki.wikia.com/wiki/Girdle_of_the_Fallen_Crusader?oldid=268220 Alliance only (September 2006)
- http://datenbank.classic-wow.org/?item=19393 Mail Gürtel
- http://wowwiki.wikia.com/wiki/Primalist%27s_Linked_Waistguard?direction=next&oldid=259926 Horde only (Oktober 2006)

Firemaw:
- http://datenbank.classic-wow.org/?item=19402 Platten Hose
- http://wowwiki.wikia.com/wiki/Legguards_of_the_Fallen_Crusader?oldid=329524 Alliance only (November 2006)
- http://datenbank.classic-wow.org/?item=19401 Mail Hose
- http://wowwiki.wikia.com/wiki/Primalist%27s_Linked_Legguards?oldid=254842 Horde only (September 2006)

**Comment by Horim** [comment]
Vielen Dank :+1: , 
bin schon gespannt auf die nächsten Loottables =D

**Comment by dagochen** [comment]
Falls noch ein Item auftaucht wo es nicht hingehört, bitte Bescheid geben.

**Comment by Horim** [comment]
Die Palahose von Moam war heute in AQ20 bei der Horde dabei.

**Comment by dagochen** [comment]
Danke, wird erledigt!

**Comment by Horim** [comment]
Erneut die Pala Hose bei Moam.

**Comment by dagochen** [comment]
@Horim Vermutlich noch nicht aufgespielt ;) Das kann ab und zu mal paar Tage dauern, wurde also nicht vergessen^^

**Comment by Horim** [comment]
Ok sorry, muss geduldiger werden ;)

**Comment by Horim** [comment]
Die Palahandschuhe von Viscidus heute in AQ40 bei der Horde

**Comment by Horim** [comment]
Zur Abwechslung ein mal die Allyseite: Schamihose bei Thekal

**Comment by Horim** [comment]
Und Palagürtel heute bei den Twins in AQ40 auf Hordenseite.

**Comment by dagochen** [comment]
Ich glaub ich weiß worans liegt ;)

**Comment by ChichiWarrior** [comment]
Darfst wieder auf machen.

Viscidus letzte Woche Platte Handschuhe für Paladin gedroppt
Twins gestern Platten Healbelt für Paladin gedroppt

Gruß

Chichi

**Comment by Larnak1** [comment]
Huhu,
wollte nochmal daran erinnern, dass
http://datenbank.classic-wow.org/?item=21606
immer noch auf Horde-Seite droppt :)

**Comment by Horim** [comment]
http://datenbank.classic-wow.org/?item=21889 hatten wir zur Abwechslung beim Trash auf Hordenseite =)

**Comment by Horim** [comment]
Mal wieder die Palahände bei Buru http://datenbank.classic-wow.org/?item=21486
