### ISSUE TITLE
NSC for first aid in Theramore dont response

### ISSUE THREAD

**Issue by earthballquake** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1628]
the ! on head is ther but no quest for me.
Sounds like " welcoe" played by click on it, but no Window open to start the quest.
Relog and wait until sleep ~6h an relog are no help

Das Ausrufezeichen ist zu sehen. aber der Kerl lässt sich nicht anquatschen.
Der Sound wird abgespielt, aber das Fenster öffnet sich nicht.
Auch ein relog und das Warten übern Schlaf hat nichts gebracht.

**Comment by Slimmer2** [comment]
Hast du Skill 225?
Wenn ja schreib ein Ticket!
