### ISSUE TITLE
[Quests/Raid/AQ40] Imperiale Qirajiwaffe/Insignie

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1630]
**Welches Verhalten wird beobachtet?**
Die Quests bezüglich der Imperialen Qirajiwaffe/insignie sind nicht wiederholbar. 
Somit kann jeder Charakter maximal 1 Item aus den zugehörigen Quests erhalten.

**Wie sollte es sich verhalten?**
Die beiden Quests sollten wiederholbar sein.

**Schritte zur Reproduzierung**
Nach Abgabe einer der beiden Quests erneut zu den Questgebern gehen, die abgeschlossene Quest wird nichtmehr da sein.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
- http://datenbank.classic-wow.org/?item=21237 Imperiale Qirajiinsignie
- http://datenbank.classic-wow.org/?quest=8790 die zugehörige Quest
- http://datenbank.classic-wow.org/?item=21232 Imperiale Qirajiwaffe
- http://datenbank.classic-wow.org/?quest=8789 die zugehörige Quest

**Quellen**
- http://www.wowhead.com/quest=8789/imperial-qiraji-armaments#comments Erster Kommentar, Patchstand 1.12.2 November 2006: _Note that the War Axe and the Pugio aren't "unique", and **the quest is also repeatable**, so you can dual-wield either if you're lucky enough with the Armamaments._ 
- Der letzte Kommentar (6.12.2006 2.01 Release) deutet auf ähnliches : _Seen a fury duel wield the Blessed Qiraji War Axe :] - Loots really cool and the dmg he was doing was CRAZY :)_
- http://wowdata.buffed.de/quest/Ahn-Qiraj/Imperiale-Qirajiwaffen-8789 Kommentarbereich 46-55 (1.12.2), gab anscheinend vereinzelt Charaktere mit 2 Items aus den Quests, bzw. nach Abschluss konnte man diese erneut annehmen.
- Leider mit dem Zeitstempel 2008 
http://wowwiki.wikia.com/wiki/Quest:Imperial_Qiraji_Armaments?direction=next&oldid=477093 Repeatable : Yes

**Comment by Horim** [comment]
Die Quests sind beide nach wie vor nicht erneut annehmbar.

**Comment by Slimmer2** [comment]
Liegt daran das es noch nicht aufgespielt ist.

**Comment by dagochen** [comment]
So ist es, erst wenn "Auf Nefarian" dran steht.

**Comment by Horim** [comment]
Sorry, mein Fehler ;)
