### ISSUE TITLE
NPC: Agathelos der Tobende

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1631]
Welches Verhalten wird beobachtet?
Der NPC benutzt dauerhaft vermutlich seinen spell http://datenbank.classic-wow.org/?spell=8260 und  macht dadurch keinen Schaden.

Wie sollte es sich verhalten?
Der NPC sollte diesen spell nicht dauerhaft benutzen sondern auch Schaden machen.

Schritte zur Reproduzierung
NPC angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
NPC:http://datenbank.classic-wow.org/?npc=4422
Spell der vermutlich den bug auslöst: http://datenbank.classic-wow.org/?spell=8260

**Comment by hraesvelgr** [comment]
https://www.youtube.com/watch?v=hJAtTdfK3Do hier sieht man gut, dass der den charge nur einmal macht, und zwar beim pull (ergibt irgendwo auch sinn)

**Comment by Rushor** [comment]
> https://www.youtube.com/watch?v=hJAtTdfK3Do 
- ist das eine blizzquelle oder von einem anderen privatserver?

**Comment by hraesvelgr** [comment]
ich weiß es nicht,d as wird nicht erwähnt.

aber wie gesagt, es ergibt sinn. 
blizzard, bzw die programmierer und designer denken sich ja was bei der erstellung der skills und npc. 
ein skill der lauftempo erhöht und "charge" heißt, wird wohl kaum infight bei x % eingesetzt werden, da der npc da sowieso still und direkt am gegner steht.

**Comment by Slipru** [comment]
Momentan ist der mob auf jeden Fall verbugt, weil er quasi nichts macht außer einen skill ohne wirkung

**Comment by Ychap** [comment]
Da der Boss immer noch buggy ist, wie ihn Slipru beschrieben hat, wäre dies hier ein möglicher Fix:
```
UPDATE creature_ai_scripts
SET event_type=4, event_inverse_phase_mask=0, event_chance=100, event_flags=0, event_param1=0, event_param2=0, event_param3=0, event_param4=0, action1_param2=0, action1_param3=1, action2_type=0, action2_param1=0, action2_param2=0, action2_param3=0, action3_type=0, action3_param1=0, action3_param2=0, action3_param3=0, comment='Agathelos the Raging - Cast Rushing Charge'
WHERE creature_id=4422 and action1_type=11 and action1_param1=8260;
```

**Comment by dagochen** [comment]
Da hängt nen c++-Skript dran (wie bei fast allen Bossen in Instanzen), daher entfällt das cai-skript hier leider ;)
Der Fix von mir ist ja auch nicht aufgespielt :P
