### ISSUE TITLE
einfaches Lagerfeuer erhöht Willenskraft nicht

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1634]
Einfaches Lagerfeuer (http://datenbank.classic-wow.org/?spell=818) erhöht die Willenskraft nicht. Diese sollte laut Tooltip um 4 erhöht werden.

**Comment by hraesvelgr** [comment]
protip: funktioniert nur manchmal. evtl ein LOS problem?
