### ISSUE TITLE
Shaman lvl10 do not get skill two handed axe

### ISSUE THREAD

**Issue by Ylanna** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1638]
Shaman lvl10 can learn every weapon skill for the class except two handed axes. The requirement: level 10 seems to be fittig. (not red) but the skill, though offered, remains red.

Nochmal auf deutsch: Obwohl mir beim Waffenmeister für meinen lvl 10 Ork SchamanenZweihand-Äxte als Skill angeboten word, kann ich es nicht lernen. Die Voraussetzung (level 10) ist erfüllt aber der Skill bleibt nicht verfügbar (rot)

**Comment by Badorr** [comment]
You need this talent http://datenbank.classic-wow.org/?spell=16269 in order to be able to equip 2H axes and 2H maces as a Shaman. This means it's not possible to do that as a lvl10 Shaman.  

In addition, please note that there is a template for creating bugtracker issues.

**Comment by Ylanna** [comment]
Thank you very much for your help.
