### ISSUE TITLE
paladin: resist von richturteilen/siegel des lichts verschwindet nicht

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1643]
simpel gesagt: wenn ein paladin ein richturteil ausführt (in dem speziellen fall richturteil , während siegel des lichts aktiv ist), und der gegner das richturteil resistet, dann verschwindet das siegel nicht. 

http://datenbank.classic-wow.org/?spell=20271 richturteil

edit: ist tatsächlich nur so, wenn man richturteil benutzt, während siegel des lichts aktiv ist. alle anderen funktionieren normal.

**Comment by testear** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875

Erstmal sollte Richturteil resisten generell nicht gehen. Zweitens denke ich, dass wenn 875 gefixt ist das Überschreiben von einem Richturteil durch ein anderes kein Problem darstellt.
Drittens, warum sollte ein Debuff der resistet wird einen anderen Debuff überschreiben? (Das ist eine ernst gemeinte Frage.)

**Comment by hraesvelgr** [comment]
es geht darum,d ass der siegelbuff auf dem spieler nicht verschwindet. ergo kann man, ohne neue manakosten zu bezahlen (aussser die vom richturteil) das gleiche siegel erneut richten, da man es nicht wieder aktivieren musste

**Comment by soda09** [comment]
Also bei mir verschwindet das Siegel, wenn dem Richturteil wiederstanden wird.

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1115
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875

**Comment by hraesvelgr** [comment]
ich weiß jetzt nicht genau, woran das liegt, jedoch funktioniert es manchmal und manchmal nicht. den report hab ic gescrieben, nachdem wir den trash vor einem der weltbosse gelegt haben (die grünen wyrmkin). sie haben prinzipiell JEDES richturteil resistet. nach dem resist hatte ich den siegelbuff aber immernoch aktiv. bei anderen npcs ist mir das noch nicht passiert, bis jetzt.

**Comment by Sabbaer** [comment]
ist mir schon 1 mio mal passiert. wie in den videos von mir gezeigt, kann man das mit jedem anderen siegel widerholen. es geht extrem viel schaden verloren und es steht nichtmal im kampflog. hier stimmt was gewaltig nicht. kann es sein, dass das richturteil parriert/ausgewichen werden kann? ich hab keine anderen erklärungen dafür.

**Comment by Dotox** [comment]
Hängt eventuell mit https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875 zusammen. Bitte um Rückmeldung wenn das neue Update veröffentlicht wurde.

**Comment by Sabbaer** [comment]
immernoch vorhanden videos benötigt?

**Comment by dagochen** [comment]
ja bitte

**Comment by Sabbaer** [comment]
https://www.twitch.tv/videos/121863792 in dem video vom sonntag dem 12.02.2017 gibt es noch viele stellen mehr wo es passiert. 2min.08 sek. kurz darauf passiert es. es ist absolut unverständlich warum das passiert es ist gerade keine gegenstände im weg, keine kanten nichts. es gibt noch viel mehr stellen, hab das jetzt mal gehighlightet

**Comment by Sabbaer** [comment]
auch in meinem letzten raid auf meinem kanal zu sehen sind sehr vieler dieser richturteile. ich habe das immer erwähnt jeweils, es sind soviele das es schon komisch ist.
