### ISSUE TITLE
Falleneffekt Einfangen setzt Jäger in den Kampf

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1644]
Welches Verhalten wird beobachtet?
Das Talent Einfangen (http://datenbank.classic-wow.org/?spell=19390) versetzt den Jäger in den Kampf.

Wie sollte es sich verhalten?
Falleneffekte, die keinen Schaden verursachen, sollten den Jäger nicht infight setzen.

Schritte zur Reproduzierung
Talent skillen, Trap setzen, Rest sollte klar sein.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Ähnliches wurde schon in https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1043 gefixt. 
In den Patchnotes zu 2.1.2 steht: "This talent will no longer causes Hunter to stand up or stop eating and drinking when it procs." (http://wowwiki.wikia.com/wiki/Entrapment). Das bedeutet, dass man schon vor diesem Patch ausm Kampf kam und trinken konnte, allerdings während des Proccs immer aufgestanden ist.

**Comment by hraesvelgr** [comment]
zusatz: nur im pvp?!

**Comment by soda09** [comment]
Ich denke mal ja: nu im PvP, da Eisfalle einen im PvE auch in den Kampf setzt.

**Comment by dagochen** [comment]
Ich verstehe den Bugreport glaube ich nicht richtig. 

Du sagst, dass Jäger aktuell in den Kampf kommen auf Nefarian, obwohl sie es nicht sollten. Und in den zusätzlichen Informationen steht, dass der Effekt Jäger nicht mehr in den Kampf versetzt (und aufstehen lässt bzw. essen unterbricht), doch das wurde erst mit 2.1.2 gefixt seitens Blizzard. Demnach wäre es ja bei uns aktuell noch richtig, wie es ist oder?

**Comment by soda09** [comment]
Man kam vorher schon ausm Kampf. In dem Bugfix wurde nur behoben, dass man immer von Trinken aufsteht.
