### ISSUE TITLE
DCs während diversen Bossfights

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1645]
Hi,

seit einiger Zeit stimmt etwas nicht mit diversen Bossfähigkeiten im Spiel.

Hakkar -> http://datenbank.classic-wow.org/?spell=24327 Übernehmen verursacht beim Übernommenen öfter mal ein DC. Durch das beschleunigen der Spieler denke ich mal dass das Anti Hack Programm sich aktiviert.

Nefarian -> Das Fear von Nef verursacht bei allen Schurken einen DC.

Skeram -> Das Übernehmen verursacht bei manchen Spieler einen DC.

Wie soll es sich verhalten:
Bei allen Bossen sollten keine DCs vorkommen, wie es vor ca. einer Woche noch der Fall war. Das Problem Mit Skeram besteht ja schon seit Release aber ich wollte dies auch nochmal aufführen.

Mit freundlichen Grüßen

**Comment by Dotox** [comment]
Hallo,

das Problem ist uns bekannt und wir arbeiten bereits an einer Lösung.

**Comment by Badorr** [comment]
Danke fürs fixen! :)
