### ISSUE TITLE
Kristallkraft stackt mit Göttlicher Willen

### ISSUE THREAD

**Issue by Pannndara** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1647]
Welches Verhalten wird beobachtet?
Der Buff "Kristallkraft" aus dem Un'gorokrater stackt mit dem Buff Göttlicher Willen vom Priester

Wie sollte es sich Verhalten? 
Die beiden Zauber sollten nicht stacken.
Siehe dafür eure eigenen Serverregeln hier:
https://community.mmobase.de/talk-und-allgemeines/5376-welche-buffs-stacken-erkl%E4rung.html

Demnach sollte Kristallkraft, genau wie Göttlicher Willen, als Zauber gewertet werden und demnach auch nicht stacken.

Wege zur Reproduktion
Göttlicher Willen buffen und dann Kristallkraft benutzen.

Links aus der Datenbank:
http://datenbank.classic-wow.org/?spell=15231

**Comment by Slimmer2** [comment]
Das fällt aber eher unter Worldbuff, so wie Juju's

**Comment by Pannndara** [comment]
Nein, Laut Serverregeln fallen Jujus und Kristallkraft unter Zauber.

**Comment by Pannndara** [comment]
Die Serverregeln sind da sehr wiedersprüchlich, aber als Worldbuffs zählen sie wohl nicht.

Q: Wie siehts denn mit den Jujus aus Winterspring aus? Bilden diese eine eigene Kategorie oder gehören sie zu Elixieren bzw. Zaubern?
A: Jujus zählen als Elixiere.

Q: Die Kristallteile aus Un Goro zählen auch unter die gleiche Kategorie, wie die Jujus oder ?
A: Ja, diese zählen als Zauber.

Fällt mir jetzt erst auf, dass sich diese beiden Aussagen ja irgendwie wiedersprechen, sollte die Serverleitung nochmal drüberschauen,

**Comment by hraesvelgr** [comment]
kristallkraft ist ein normaler magischer buff, der willenskraft erhöht. damit macht er das gleiche wie "göttlicher wille" und kann somit nicht gestackt werden. sind beides magische buffs die den gleichen wert (und nur den wert) beeinflussen

**Comment by Slimmer2** [comment]
Wenn du beides gebufft hast ist der Wert auch um beides erhöht oder nur um einen der Werte?
Hast du da nachgeschaut oder nur gesehen dass die Buffs in der Buffleiste sind?.
Bei machen kann man sich beide Buffs in der Leiste haben, aber es wird nur ein Wert dem Charakter angerechnet.

**Comment by Pannndara** [comment]
Ja, der Willenskraftwert ist um beides erhöht, sonst würde ich es ja hier nicht reinschreiben.

**Comment by Dotox** [comment]
Darf stacken, da es ein Worldbuff ist. Darf allerdings nicht mit anderen "Worldbuffs" stacken, die z. B. von Questbelohnungen sind.
