### ISSUE TITLE
Druiden können Fallen entdecken

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1650]
Welches Verhalten wird beobachtet?
Druiden in Katzengestalt können, wenn sie schleichen, Fallen von gegnerischen Jägern sehen.

Wie sollte es sich verhalten?
Druiden besitzen keine Fähigkeit zum Entdecken von Fallen, daher sollten sie Fallen auch nciht sehen können.

Schritte zur Reproduzierung:
Duell starten, Falle legen, usw.

**Comment by soda09** [comment]
Fehlt was? Eure eigenen Bugreports labelt ihr immer sofort.

**Comment by hraesvelgr** [comment]
nein. es beeinflusst nur pvp. von einer klasse gegenüber einer anderen.

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1249

**Comment by soda09** [comment]
Ja, hraesvelgr, und das enorm :D
