### ISSUE TITLE
Teufelsunhold: falscher Loottable

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1652]
Welches Verhalten wird beobachtet?
1.) Teufelsunhold kommt in Pflanzen außerhalb des Teufelswaldes vor.
2.) Teufelsunhold kommt in Traumblatt und Bergsilberweisling vor. 

Wie sollte es sich verhalten?
Teufelsunhold sollte nur innerhalb des Teufelswaldes, aus bestimmten Pflanzen, lootbar sein.

Schritte zur Reproduzierung
Leuchtfeuer besorgen und Pflanzen looten

Zusätzliche Informationen (Screenshots, Videos, etc.)

- Questtext: "... When you gather herbs in Felwood, ..." (http://datenbank.classic-wow.org/?quest=5889) -> es sollte also nur in Felwood erähltlich sein!

- Sollte laut DB nur in Gromsblut, Arthas Träne und Pestblüte vorkommen (http://datenbank.classic-wow.org/?item=11514)

- für andere Berufe ist der Sachverhalt noch zu überprüfen

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/949

**Comment by soda09** [comment]
ok :(
