### ISSUE TITLE
ozzie wechselvolt/falsches modell/npc doppelt vorhanden

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1653]
der npc http://datenbank.classic-wow.org/?npc=1268 sollte eigentlich ein gnom mit roter brille sein. auf unserem server ist er ausserdem zweimal da. 
der korrekte platz ist in seinem haus in  kharanos, und nicht vor der großen schmiedehalle in kharanos. 

http://wowwiki.wikia.com/wiki/Ozzie_Togglevolt

**Comment by hraesvelgr** [comment]
war heut mit meinem zwergen da unterwegs. hab garkeinen von beiden gesehen. ist er nun ganz weg?

**Comment by Dotox** [comment]
Er war nach dem Update kurzzeitig weg, sollte nun aber am richtigen Ort stehen.

**Comment by hraesvelgr** [comment]
jap, geht.
