### ISSUE TITLE
Schattenwort: Schmerz Rang 1-3 - Zauberkoeffizient (LvL60)

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1654]
**Welches Verhalten wird beobachtet?**
Die Ränge 1-3 ska­lie­ren nicht mit 100% des Zauberschadens.  Das liegt wohl an dem Patch 2.0.1
*Low-level spells cast by high-level players will receive smaller bonuses from +healing and +spell damage.*
(http://wowwiki.wikia.com/wiki/Patch_2.0.1)

**Wie sollte es sich verhalten?**
Auch die niedrigen Ränge sollten mit 100% des Zauberschadens skalieren.
Spells:
http://datenbank.classic-wow.org/?spell=589
http://datenbank.classic-wow.org/?spell=594
http://datenbank.classic-wow.org/?spell=970

Koeffizient: 
18Sec/15 =1,2 (Cap = 1,0)

**Comment by soda09** [comment]
Lowlvl-spells haben ne %-Schranke. Deswegen kann z.b. als Dudu auch nur bis R3/4 HT sinnvoll downranken. Das gillt für alle Spells.

**Comment by Horim** [comment]
_Lowlvl-spells haben ne %-Schranke. Deswegen kann z.b. als Dudu auch nur bis R3/4 HT sinnvoll downranken. Das gillt für alle Spells._

Das gilt für Lowlvl-Spells deren Castzeit durch kleinere Ränge verkürzt wird, da zu Classic die Zauberkoeffizienten von der Castzeit abhängen. 100% Skalierung gibt es nur bei 3,5 sec : 

HT R1 -> 2 sec Basis Cast-Zeit -> 57% Skalierung
HT R2 -> 2,5 sec Basis Cast-Zeit -> 71% Skalierung
HT R3 -> 3 sec Basis Cast-Zeit -> 85% Skalierung
HT R4 -> 3,5 sec Basis Cast-Zeit -> 100% Skalierung

Beim Paladin-Heiler haben alle Ränge von HL (71%) und FoL (43%) den gleichen Zauberkoeffizienten, da selbst bei R1 die Cast-Zeit wie bei Max-Rank ist. 

_Das gillt für alle Spells_, **deren Zauberzeit durch Downranking beeinflusst wird!**

Schattenwort Schmerz hat jedoch immer die gleiche "Cast-Zeit" und folglich immer den gleichen Zauberkoeffizienten.

**Comment by dagochen** [comment]
Moin Moin!

Mit der Zauberzeit hat das in diesem Fall wohl nichts zu tun.

Zauber erhalten eine "Strafe", eine sogenannte LevelPenalty, wenn der gewirkte Zauber einen niedriger Rang ist, auf den Spelldamagekoeffizienten. Diese berechnet sich aus dem Level des Zaubers und dem Level des Spielers, der den Zauber wirkt. Die SpellLevels von Gedankenwort: Schmerz Rang 1 bis Rang 3 sind: Level 4, 10 und 18.

Die genaue Formel dazu findet ihr hier (Abweichungen von Nefarian möglich): 
https://github.com/cmangos/mangos-classic/blob/29bdc0bc150a6ccb7766a68dea19cec5a55245fb/src/game/Unit.cpp#L2362

Ob das ganze zu Classic wirklich exisitiert hat, kann ich aktuell noch nicht sagen. Vielleicht findet ihr ja da etwas? Ich such gleich mal. Die Patchnotes von 0815Priester deuten aber schon darauf hin, dass es wirklich erst mit BC kam.

**Comment by 0815Priester** [comment]
Ok, das erklärt warum Mind Flay kein Penalty hat aber dafür Shadoword Pain und Mind Blast.

Im Wiki Artikel  wird der LvL 20 Penalty am **18 Juni 2007** erwähnt. Dort steht auch
*Shortly before the release of the 2.0 content patch*

Ob jetzt kurz vor 2.0 und somit noch 1.12.1 oder erst mit 2.0.1 kann ich nicht sagen. Will da jetzt auch kein Fasse aufamechen. Sollen die Devs entscheiden.

**Comment by dagochen** [comment]
Im offiziellen cmangos-Repository habe ich dazu folgenden PR gefunden: 
https://github.com/cmangos/mangos-classic/pull/173/files

Und als Quelle das es so war (Oktober 2006): 
http://wow.gamepedia.com/index.php?title=Spell_power&direction=prev&oldid=298315#Penalty_Rules

**Comment by 0815Priester** [comment]
Alles Klar, danke für deine Mühe. Ich close dann mal.

**Comment by dagochen** [comment]
Naja hier muss ja schon was gemacht werden, falls das bei uns noch nicht so auf dem Server implementiert ist.

**Comment by 0815Priester** [comment]
Hm, für deinen Github link bin ich zu blöd. Bei deinen Gamepedia link steht ja das es ein Lvl 20 Penalty gab. Und genau diesen Penalty habe ich bei Schattenwort Schwerz und Mind Blast.

**Comment by dagochen** [comment]
Ja, aber bei einem Lvl 18 Spell (Shadowword: Pain Rank 3) ist die Penalty bei 2x3,75%*(18+6)/60. Und sie sollte lediglich 2x3,75% hoch sein. Das andere kam erst mit BC.

**Comment by Badorr** [comment]
Addons wie Theorycraft zeigen einem diese Koeffizienten relativ genau an. Sehr zu empfehlen.

**Comment by Wosser** [comment]
Haben Heal Spells nun auch eine Penalty oder nicht?

**Comment by dagochen** [comment]
>Haben Heal Spells nun auch eine Penalty oder nicht?

Ja, haben sie.
