### ISSUE TITLE
auktionshaus: suchen nach zufälligen suffixen nicht möglich

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1658]
Welches Verhalten wird beobachtet?
wenn man gegenstände "xxxx des arkanen/heiligen/feurigen/.... zorns" im ah sucht, zeigt das ah nur "keine einträge gefunden" an.
ich habs mit "zorn", "wrath", "arkan", heilig", und anderen eingaben versucht, englisch und deutsch. es hat nie ein item angezeigt. sucht man dann mit der diekten suche (zb. alle umhänge anzeigen) bekommt man einträge angezeigt 

beispiel nach testen (auch bei mehreren spielern):
im ah befindet sich das item "weidencape des heiligen zorns"
suche nach "zorn" bringt keine ergebnisse"
suche nach "weidencape" zeigt ein ergebnis (das cape eben)
sucht man nur in der kategorie umhänge wird es auch angezeigt

bei "armschienen des tiefen zorns" funktioniert die suche nach "zorn" ohne probleme

Wie sollte es sich verhalten?
man sollte alle items per eingabe des namens oder eines teil des namens finden

Schritte zur Reproduzierung
ah absuchen.

**Comment by hraesvelgr** [comment]
edit: hab nochmal mit anderem getestet. zb findet man den "geistwandlerschild des wals" auch nicht, wenn man nach "wal" sucht.

es scheint so, als würde das suchen nach random suffixes nicht möglich sein.

**Comment by dagochen** [comment]
Das liegt vermutlich daran, dass die Suffixes durch "permanente Verzauberungen" auf die Items kommen. Diese werden beim Drop zufällig ausgewählt, wodurch es unterschiedlich viel +heal auf Zauberstäben geben kann zum Beispiel. Ich könnte mir vorstellen, dass diese Verzauberungen nicht als "Text" gespeichert sind und daher nicht einfach mit der Suchmaske verglichen werden können. Ich kann aber mal nachschauen was ich da finde.

**Comment by hraesvelgr** [comment]
ach, dann mach mir pls mal einen +40 holy spelldmg schild :D

**Comment by dagochen** [comment]
Ich mach das mal zu, weil ich grad gesehen habe, das der Server die Enchantbezeichnungen wie "des arkanen Zorn", etc. überhaupt nicht einliest aus den DBC-Dateien.

**Comment by hraesvelgr** [comment]
heißt also, es gibt keine chance gezielt nach den suffixes im ah zu suchen?

**Comment by dagochen** [comment]
Doch, hab es grad hinbekommen. In Englisch funktioniert es schon. Die deutsche Variante bastel ich grad auch noch.

**Comment by dagochen** [comment]
Ging leichter als ich gedacht habe. Happy @hraesvelgr ?
![wowscrnshot_072116_002604](https://cloud.githubusercontent.com/assets/5236186/17005396/3fe78fd8-4eda-11e6-93b4-1496ecce7471.jpg)
![wowscrnshot_072116_002557](https://cloud.githubusercontent.com/assets/5236186/17005398/3fe7ba58-4eda-11e6-9b0c-acee456ba096.jpg)
![wowscrnshot_072116_002620](https://cloud.githubusercontent.com/assets/5236186/17005397/3fe7ba62-4eda-11e6-8125-6f284f6f9ae2.jpg)

**Comment by hraesvelgr** [comment]
schick. kann man auslesen wie hoch der maximalwert an spelldmg auf einem item mit zufälligen suffixen sein kann? ich such schon länger einen schild mit mehr als 33 dmg :)
