### ISSUE TITLE
Quest Fragmente der Vergangenheit

### ISSUE THREAD

**Issue by earthballquake** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1661]
Welches Verhalten wird beobachtet?
Der Düsterteich in der Elderethgasse füllt meine Phiole nicht mit Wasser.

Wie sollte es sich verhalten?
Bei Verwendung der Phiole bei dem Teich(Vase) sollte sie mit dem Wasser aus dem Teich gefüllt werden.

Schritte zur Reproduzierung
Hab es auch ohne Addons mal probiert ohne Erfolg.
Das Ticket gibt's es schon aber ein GM hat mir gesagt ich soll ein Screenshot machen damit ich die Phiole bekomme.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Auf dem Sreenshot hatte ich den Verzauberten Barren noch nicht. aber inzwischen schon

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=16973
![dusterteich](https://cloud.githubusercontent.com/assets/20264498/17021541/f4185f00-4f48-11e6-98ed-5eac087fa42a.JPG)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/237 sufu nutzen!
