### ISSUE TITLE
Post einfach weg nach 2 Tagen !

### ISSUE THREAD

**Issue by shiix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1663]
Hallo habe mir vor kurzen ein 2 Handschwert aus dem AH gekauft,
diese dann über den Postweg einen RL-Kumpel geschickt der sie mir mit +7 Waffenschaden berzauberte und mir anschließend zurückschickte. Das Schwert kam an ich hatte aber vergessen dieses aus dem Postkasten zu nehmen und nach 2Tagen ist es weder im Inventar noch grau hinterlegt im Postkasten.

würde gerne Wissen wo mein Schwert hin ist?kann man das irgendwie verfolgen?

Mfg Shiix

Betroffene Charaktere : ørganspender, Shorr, Shiix

**Comment by Slimmer2** [comment]
Schreib dazu ein Ticket und nicht hier im Bugtracker.
