### ISSUE TITLE
Keine Frösche in Hexenhügel/Dustwallow

### ISSUE THREAD

**Issue by Ylanna** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1664]
Die Quest: "Marschenfroschschenkel" in Dustwallow ist nicht machbar, weil keine Frösche im Questgebiet zu finden sind. Es gibt dort auch keine Mobs. Soweit ich mich erinnere, waren dort Geister, die einen bei der "Arbeit" behinderten.
Jetzt ist dort alles tot.

Liebe Grüße

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1558
