### ISSUE TITLE
[NPC/Silithus/Loottable] Baggerbrecher ohne Loot

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1665]
**Welches Verhalten wird beobachtet?**
Die Baggerbrecher in Silithus haben keinen Loottable mehr.

**Wie sollte es sich verhalten?**
Es sollte der gewohnte Loot droppen.

**Schritte zur Reproduzierung**
Im Süden von Silithus Baggerbrecher abfarmen, es wird kein Loot vorhanden sein

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Dieser Bug betrifft nicht die Baggerschläger.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
- http://datenbank.classic-wow.org/?npc=11741 Baggerbrecher
- http://datenbank.classic-wow.org/?npc=11740 Baggerschläger

**Comment by testear** [comment]
Dasselbe gilt auch für die Silbermähnenpirscher. http://datenbank.classic-wow.org/?npc=2926

**Comment by hraesvelgr** [comment]
fehler in dem bugreport mit der schwarzen perle vllt?

**Comment by dagochen** [comment]
Omg omg omg omg :( Ich schäm mich so :( *stellt sich in die ecke*

**Comment by hraesvelgr** [comment]
du hats nicht wirklich die gesamte loottable entfernt, statt nur 1 item aus der table?^^

**Comment by dagochen** [comment]
Ehmm ja :( Aber Dotox hat die Daten gerettet und wieder eingespielt. Mit Neustart sollten die Einträge wieder da sein!

**Comment by hraesvelgr** [comment]
aus fehlern wird man klug, deshalb sit einer nie genug O:-)
