### ISSUE TITLE
Emote von anderem Spieler keine Soundausgabe.

### ISSUE THREAD

**Issue by Agorass** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1666]
Welches Verhalten wird beobachtet? - **Bei Sprachemotes wird kein Sound abgespielt ( Sprache ), höre nur mich Selbst..**

Wie sollte es sich verhalten? - **Sprachemotes von anderen Spielern sollten gehört werden.**

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
**\- Weiß leider nicht, wie ich Emotes verlinken soll ;D**

**EDIT:
Anscheinend ist dieser Bug Zonen abhängig! Da es an manchen Stellen Funktioniert.

**Comment by hraesvelgr** [comment]
kann ich bestätigen.

**Comment by dagochen** [comment]
Funktioniert nur, wenn man sich in einer Gruppe befindet ;)
