### ISSUE TITLE
Priesterquest Renner für einen höheren Zweck

### ISSUE THREAD

**Issue by Schnegge** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1667]
Es geht um die Priesterquest[ Renner für einen höheren Zweck](http://datenbank.classic-wow.org/?quest=8255) 
Die Gegner [Mosshufrenner](http://datenbank.classic-wow.org/?npc=8761) in Aszhara droppen gar nichts.
Sie sollten den Gegenstand [Gesunde Rennerdrüse](http://datenbank.classic-wow.org/?item=20027) droppen.

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1665

Hing damit zusammen, inzwischen gefixt.
