### ISSUE TITLE
Jäger-Klassenquest: Gehörnte Renner [H]

### ISSUE THREAD

**Issue by jeremiquo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1670]
Welches Verhalten wird beobachtet?
Die Quest [Gehörnte Renner](http://datenbank.classic-wow.org/?quest=8153) ist Teil der lvl 50 Jägerklassenquestreihe, also jene wo man am Ende, wie bei allen anderen Klassen in den Tempel muss.
Im Zug der Quest, sollen [Perfektes Rennergeweih](http://datenbank.classic-wow.org/?item=20017)e gesammelt werden. Wenn man nun in der Datenbank, unter gedroppt von nach sieht, kommt man auf die Mobs: [Mooshufrenner](http://datenbank.classic-wow.org/?npc=8761). Hier das Problem, in der Datenbank scheinen diese Mobs keinen Loottable zu haben, was man im Spiel auch beobachten kann, also sie droppen nichts, somit auch die Q-Items nicht.
Das in der Datenbank einfach der falsche Mob verlinkt wurde, möchte ich ausschließen, da der Q-Text eindeutig von den Rennern spricht und andere P-Server den selben Mob verlinkt haben [(vanillaGaming)](http://db.vanillagaming.org/?item=20017) bzw hier [(buffed/kommentare von pre-cata/offi. server)](http://wowdata.buffed.de/npc/Mooshufrenner-8761#comments) erwähnt wird, dass die Geweihe bei besagten Gegnern droppen.
Weiters habe ich die lvl 50 Priesterklassenq [Renner für einen höheren Zweck](http://datenbank.classic-wow.org/?quest=8255/Renner%20für%20einen%20höheren%20Zweck), welche Drops von den selben Mobs benötig, seinerzeit hier auf diesem Server abschließen könnten, also haben die Renner schon mal einen Loottable besessen.

Wie sollte es sich verhalten?
[Mooshufrenner](http://datenbank.classic-wow.org/?npc=8761) sollten einen Loottable haben, welcher unter Anderem auch [Perfektes Rennergeweih](http://datenbank.classic-wow.org/?item=20017) enthält

Schritte zur Reproduzierung
Besagte Mobs töten und nichts looten.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Das Problem tritt bei allen Mobs auf, die vorher eine schwarze Perle gedroppt haben und dies eigentlich nicht sollten. An einer Lösung wird bereits gearbeitet.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1665
