### ISSUE TITLE
Teleport zum Flugmeister anderer Fraktion

### ISSUE THREAD

**Issue by madbatwithhat** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1672]
Welches Verhalten wird beobachtet?
Man kann zum Flugmeister der Allianz porten

Wie sollte es sich verhalten?
Flugpunkte der Allianz sollten als Hordespieler 

gar nicht angezeigt werden

Schritte zur Reproduzierung
Zum Flugmeister gehen und ihn ansprechen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Hab Premium

![wow_2016-07-30_12-00-54](https://cloud.githubusercontent.com/assets/20738597/17269641/5c1422fe-564e-11e6-848b-610192cc71fa.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by testear** [comment]
Suchfunktion nutzen.  Close.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/63
