### ISSUE TITLE
Druide - Maul und Autohit

### ISSUE THREAD

**Issue by testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1674]
Beim Druiden wird wenn man Maul ausführt parallel zum Maul ein Autohit ausgeführt, statt den Autohit zu ersetzen. Es sollte entweder nur der Autohit (zu wenig Wut vorhanden wenn der Schlagtimer ausgelaufen ist) oder Maul (genug Wut vorhanden wenn der Schlagtimer abgelaufen ist) ausgeführt werden. 

Siehe hier: 
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1493 
Kommentar von Loplin

http://datenbank.classic-wow.org/?spell=6807
http://datenbank.classic-wow.org/?spell=6808
http://datenbank.classic-wow.org/?spell=6809
http://datenbank.classic-wow.org/?spell=8972
http://datenbank.classic-wow.org/?spell=9745
http://datenbank.classic-wow.org/?spell=9880
http://datenbank.classic-wow.org/?spell=9881

Bei Heroic Strike und Cleave funktioniert alles korrekt.

**Comment by Dotox** [comment]
Heute selbst getestet?

**Comment by testear** [comment]
Nur wiedergegeben von Loplin. Der hats gestern getestet. Den Krieger habe ich vor dem Report getestet.

**Comment by Dotox** [comment]
Sollte seit gestern Abend schon behoben sein

**Comment by testear** [comment]
Läuft ja grad bei euch.

**Comment by Loplin** [comment]
Sorry vergessen bescheid zu geben
Wurde nach knackigen 3 Stunden nach dem auftreten gefixt
Nochmals danke für die schnelle reaktion an dieser stelle :)

**Comment by dagochen** [comment]
Wir bedanken uns auch für die schnelle Meldung für den etwas unfreiwilligen Druidenbuff :P Sehr löblich das direkt zu melden ;)
