### ISSUE TITLE
stealth von npcs

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1676]
manche npc  haben ihre stealthfunktion und nutzen diese teilweise, jedoch meistens garnicht.

kundschafter des ashenvale: http://datenbank.classic-wow.org/?npc=12856
ist dauerhaft sichtbar, sollte jedoch von anfang an stealthy sein. (out of combat-> go into stealth)
aus irgendeinem grund hat dieser npc dauerhaft reduzierte geschwindigkeit (egal ob rennend oder idle)
http://www.wowhead.com/npc=12856/ashenvale-outrunner#comments

eindringling der verlassenen: http://datenbank.classic-wow.org/?npc=3804
einige dieser npc nutzen den stealth, andere scheinbar nicht. ich habe beide angetroffen (stealthy und sichtbar). kann evtl damit zusammenhängen, dass sie nicht wieder stealthy werden, sobald sie out of combat sind. 
http://www.wowhead.com/npc=3804/forsaken-intruder#comments

dunkelpirscher der verlassenen: http://datenbank.classic-wow.org/?npc=3808
nutzt seinen stealth, jedoch nicht wenn er wieder out of combat ist.
http://www.wowhead.com/npc=3808/forsaken-dark-stalker#comments

schattentatzenpanther haben garkeinen eingetragegen spell in der richtung, und scheinen dauerhaft sichtbar. sie sollten eine normale form von stealth besitzen. 
http://datenbank.classic-wow.org/?search=schattentatzenpanther
http://wowwiki.wikia.com/wiki/Shadowmaw_Panther

**Comment by dagochen** [comment]
Die Panther habe ich tagsüber tatsächlich im Stealth gefunden. Aber sobald sie resetten und wieder aus dem Kampf kommen, benutzen sie den Zauber nicht erneut. Allerdings finde ich dazu grad den Fehler nicht. Bei den anderen funktioniert es auf dem Testserver jetzt.
