### ISSUE TITLE
[Quest] Eine schöne Bescherung

### ISSUE THREAD

**Issue by Codiy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1677]
Welches Verhalten wird beobachtet?
Nach annehmen der Quest in Gnomeregan passiert nichts.

Wie sollte es sich verhalten?
Es sollte eine Eskortquest innerhalb der Instanz sein.

Schritte zur Reproduzierung
/

Zusätzliche Informationen (Screenshots, Videos, etc.)
Der NPC ist in Gnomeregan neben der "Sicheren Zone" in einer der oberen Nieschen (Mitte) auf dem Boden (sieht aus wie tot)
 [Screenshot](http://quickdungeon.com/wp-content/uploads/2014/07/Kernobee-NPC.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Quest](http://datenbank.classic-wow.org/?quest=2904)
[NPC](http://datenbank.classic-wow.org/?npc=7850)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues?utf8=%E2%9C%93&q=bescherung
