### ISSUE TITLE
[Quest] Fehlende Quest: Totenwaldfelle des Nordens

### ISSUE THREAD

**Issue by Truncsta** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1679]
Welches Verhalten wird beobachtet?
Die Quest "Totenwaldfelle des Nordens" ID=6221 von Nafien fehlt gänzlich.

Wie sollte es sich verhalten?
Die Quest sollte von Nafien vergeben werden. Auch bei einem Feindseligen Ruf bei der Holzschlundfeste sollte er die Quest verfügbar haben.

Schritte zur Reproduzierung
Mit einem feindseeligen Ruf Nafien ansprechen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Video aus einem Classic Speedrun (Lt. Videoangaben Patch 1.10) Dort sieht man wie die Quest angenommen wird.
https://youtu.be/Iis-scUq9bg?t=1h3m32s
WoWWiki vom 17.10.2006
http://wowwiki.wikia.com/wiki/Quest:Deadwood_of_the_North?oldid=288584

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Nafien - http://datenbank.classic-wow.org/?npc=15395
Quest (Nicht in der Datenbank aufgeführt) - http://datenbank.classic-wow.org/?quest=6221

**Comment by dagochen** [comment]
http://datenbank.classic-wow.org/?quest=8461

**Comment by 51MON-STER2** [comment]
Welches Verhalten wird beobachtet?
Die Quest "Totenwaldfelle des Nordens" ID=8461 von Nafien kann nicht abgegeben werden.

Wie sollte es sich verhalten?
Die Quest sollte nach Erledigung bei Nafien abgegeben werden können.

Schritte zur Reproduzierung
Nach Erledigen der Quest Nafien ansprechen (Ruf: Unfreundlich).

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Nafien - http://datenbank.classic-wow.org/?npc=15395
Quest  - http://datenbank.classic-wow.org/?quest=8461

**Comment by Slimmer2** [comment]
Laut Datenbank hat die Quest auch keinen Questgeber zum annehmen

**Comment by dagochen** [comment]
Mist das Quest Ende habe ich wohl verschlafen :(

**Comment by Slimmer2** [comment]
Die Wiederholbare Quest zum Abgeben der Items Kopfputzfedern der Totenwaldfelle lässt sich auch nicht mehr abgeben.
http://datenbank.classic-wow.org/?quest=8467
http://datenbank.classic-wow.org/?item=21377
