### ISSUE TITLE
Onyxia hat ein falsches Modell

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1681]
**Welches Verhalten wird beobachtet?**

Onyxia hat das Modell eines Caster Drachen-Trashmobs in der Quest "The great masquerade".

**Wie sollte es sich verhalten?**

Onyxia sollte das Modell haben, welches sie in ihrer Höhle auch hat.

**Schritte zur Reproduzierung**

Die Zugangsquests für Onyxia machen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Videos:
https://www.youtube.com/watch?v=fRHLCXRXa-I
Ist zwar 2008 hochgeladen worden aber da hat sich an der Questreihe nichts geändert gehabt.

https://www.youtube.com/watch?v=noTZXpl1fIA
Das ist von 2005 und da sieht man es bei 9:24 ganz kurz die Transformation.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

http://datenbank.classic-wow.org/?npc=10184
http://datenbank.classic-wow.org/?npc=12756

http://datenbank.classic-wow.org/?quest=6403

Grüße

**Comment by hraesvelgr** [comment]
ööööh...sicher? als ich die quest gemacht hab (ist schon 2 jahre her oder so) war sie definitv noch groß

**Comment by Larirawiel** [comment]
Ja, sicher. In der Quest siehst sie so aus:

http://666kb.com/i/db8sbc4drdvahpac4.jpg


Grüße

**Comment by dagochen** [comment]
Ja @hraesvelgr korrekt.
Das Ding ist die Quest wurde damals von uns überarbeitet und ich meine es gab irgendein Problem mit dem Zauber, der sie korrekt verwandelt: http://datenbank.classic-wow.org/?spell=17136

**Comment by hraesvelgr** [comment]
verschlimmbesserung also!
