### ISSUE TITLE
Nefarians Fluch (Veil of Shadows / Schattenschleier) nicht auf aktiven Tank gewirkt

### ISSUE THREAD

**Issue by Limeline** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1683]
Hiho
Gestern in BWL ist mir das Folgende aufgefallen:

Welches Verhalten wird beobachtet?
Zieht man in Phase 2 bei Nefarian Aggro und überlebt dank Segen des Schutzes (Blessing of Protection: http://datenbank.classic-wow.org/?spell=5599 ), kommt es vor, dass im weiteren Verlauf des Kampfes der Fluch Schattenschleier / Veil of Shadows (-75% Heilung) regelmässig auf den Spieler gecastet wird, der zuvor Aggro gezogen hatte und nicht mehr (zwingend) auf den aktiven MT. 

Ob der Fluch nach dem kurzen Aggro-Pingpong überhaupt noch auf den Tank gewirkt wurde, weiss ich ehrlich gesagt nicht. Ich habe es selber erst viel später realisiert.
Ich hab den Fluch definitiv mehrmals abbekommen/widerstanden. Leider vergessen Screenshots zu machen. Ich war als Off-Krieger dabei.
KTM funktioniert bei mir generell bei Nef nicht, daher weiss ich nicht, ob es etwas mit dem Aggro Table zu tun gehabt hat.

Schattenschleier / Veil of Shadow: [http://datenbank.classic-wow.org/?spell=22687]
Der Spell ist noch unter weiteren 5 Spell IDs in der Datenbank vorhanden. Der verlinkte Spell hat zumindest dieselbe ID wie in der buffed.de und wowhead Datenbank, wenn man da Nefs Fähigkeiten nachschlägt.

Wie sollte es sich verhalten?
Der Fluch sollte immer auf den MT bzw. das aktuelle Ziel von Nef gecastet werden, auch nachdem der MT die Aggro kurzzeitig nicht mehr hatte (sonst wäre die Mechanik des Fluches irgendwie sinnlos?).

Schritte zur Reproduzierung
Falls es sich reproduzieren lässt, dann so wie oben beschrieben.

Zusätzliche Informationen
Veil of Shadows ist in der Datenbank 6x vorhanden, keiner davon Nefarian zugewiesen, daher keine Ahnung welchen Spell er bei uns In-Game tatsächlich benutzt... Laut unserer Datenbank kann Nefarian nichts oder ich kann die Datenbank nicht verwenden ^.^
Soweit ich weiss, hat die Distanz zu Nefarian nichts damit zu tun, wer den Fluch abbekommt?

Gruss Limeline

**Comment by hraesvelgr** [comment]
hast du den gesamten fight über den spell abbekommen (in der zeit in der er kommen kann), oder nur wirklich knapp (wenige sekunden) nachdem sds  gesetzt wurde?
welche klasse spielst du? hattest du das gefühl, immer hart am aggrolimit zu sein?

**Comment by Limeline** [comment]
War als Off-Krieger dabei.
Den Fluch hab ich erst von da an abbekommen, als ich das erste Mal Aggro gezogen habe. 
Ich muss auch den ganzen Kampf über sehr weit oben in der Aggro gewesen sein, da ich in der Executephase nochmals Aggro gezogen habe (und überlebt ohne sds). 
Bei ca. 3% des Bossfights hatte ich den Fluch sogar widerstanden. Das ware lange nach sds.

**Comment by hraesvelgr** [comment]
naja, man muss imemr dran denken: wählt nef das ziel mit der höchsten aggro dafür aus? oder sein eigenes target? da du als melee auch ein wenig über die tankaggro gehen kannst, ohne wirklich aggro zu ziehen, kanns ja sein,d ass er einfach dich genommen hat, da du grad das target mit der meisten aggro warst, egal wen er grad anvisiert

**Comment by Limeline** [comment]
Das wirds wahrscheinlich gewesen sein. Sollte ja aber trotzdem nicht so sein, weil damit die Mechanik des Fluches übergangen wird.

**Comment by ChichiWarrior** [comment]
Huhuran gibt ihr Gift auch nicht dem Aggrohalter, sondern dem Aggroführenden ihre Stacks.
Vielleicht gibts da Parallelen.

Gruß

Chichi
