### ISSUE TITLE
Dornen + Kristallspitze stacken

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1684]
Welches Verhalten wird beobachtet?
Der Dornen-Buff des Druiden stackt momentan mit dem Kristallspitze-Buff aus dem Un'Goro-Krater.

Wie sollte es sich verhalten?
Diese beiden Buffs sollten nicht stacken. Zitat aus dem [Buffstacking-Thread ](https://community.mmobase.de/talk-und-allgemeines/5376-welche-buffs-stacken-erkl%E4rung.html)

> Q: Die Kristallteile aus Un Goro zählen auch unter die gleiche Kategorie, wie die Jujus oder ?
> A: Ja, diese zählen als Zauber.

Schritte zur Reproduzierung
Einem Spieler Dornen und Kristallspitze buffen und diesen angreifen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Ich habe es nur mit Dornen Rang6 ausprobiert, bei den anderen Rängen müsste man evtl. schauen, ob da etwas anders aussieht.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Dornen (Rang 6)](http://datenbank.classic-wow.org/?spell=16877)
[Kristallspitze](http://datenbank.classic-wow.org/?spell=15279)

**Comment by testear** [comment]
Nature Dmg und Dmg. Warum sollte das nicht stacken?

**Comment by hraesvelgr** [comment]
[Crystal Spire] - Use: A crystal shield surrounds the friendly target, doing 12 damage to anyone who hits them. Lasts 10 minutes. (Cystal Spire does not stack with spells providing damage shields). 

http://wowwiki.wikia.com/wiki/Damage_shield#Enhancements

**Comment by Baraz** [comment]
Außerdem ist beides vom Typ her Naturschaden laut Datenbankeintrag.

**Comment by testear** [comment]
Danke, war mir schon bewusst, als ich oben gefragt hab. Wenn du einfach die Quelle in deinem Report weglässt stelle ich ihn ganz bewusst infrage.
