### ISSUE TITLE
Heiliger Fleischklops: Was das Licht Dir nicht erzählt - Quest funktioniert nicht auf Level 54

### ISSUE THREAD

**Issue by elnarg** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1685]
Welches Verhalten wird beobachtet?
Das Buch mit Level 54 gibt eine Quest die mit Level 54 annehmbar sein sollte.
Das Quest öffnet sich und es kommt die Meldung wenn man auf annehmen klickt:
Ihr erfüllt die Anforderungen für diese Quest nicht.
Wie sollte es sich verhalten?
Quest sollte annehmbar sein
Schritte zur Reproduzierung
Char Level 54 - Buch Quest auslösen und annehmen
Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=18362

**Comment by Baraz** [comment]
Ist auch bei den anderen Buchbänden aus dem Düsterbruch so.

[Schurke](http://datenbank.classic-wow.org/?item=18356)
[Krieger](http://datenbank.classic-wow.org/?item=18357)
[Hexenmeister](http://datenbank.classic-wow.org/?item=18360)
[Magier](http://datenbank.classic-wow.org/?item=18358)
[Paladin](http://datenbank.classic-wow.org/?item=18359)
[Druide](http://datenbank.classic-wow.org/?item=18364)
[Schamane](http://datenbank.classic-wow.org/?item=18363)
[Jäger](http://datenbank.classic-wow.org/?item=18361)
