### ISSUE TITLE
Krieger (Fähigkeit Überwältigen) 

### ISSUE THREAD

**Issue by GasserMarkus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1688]
Welches Verhalten wird beobachtet?
Beim Spielen ist mir aufgefallen das die Fähigkeit sich nur aktiviert wen der Mop Ausweicht... Solte aber auch aktivieren wen er parriert, macht das aber nicht.

Wie sollte es sich verhalten?
Also die Fähigkeit sollte beim Ausweichen des Gegners und beim Parrieren des Gegners aktiviern.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by testear** [comment]
Nein.

http://datenbank.classic-wow.org/?spell=11585 

http://wowwiki.wikia.com/wiki/Overpower?oldid=249192
