### ISSUE TITLE
rumseyrum und schwarzer rumseyrum

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1690]
Rumseyrum und schwarzer Rumseyrum stacken.

Weil beides Alkohol ist sollte es nicht stacken.
(Für die Suche nach der Quelle habe ich grad keine Zeit, wird nachgereicht.)

http://datenbank.classic-wow.org/?item=17048 (Rumsey Rum)
http://datenbank.classic-wow.org/?item=21151 (Schwarzer Rumsey Rum)

**Comment by testear** [comment]
Zu meiner Schande muss ich gestehen, dass ich die Quelle dazu nicht mehr finde.

**Comment by testear** [comment]
<-

**Comment by testear** [comment]
Möglicherweise ist das hier eine Ausnahme, aber für gewöhnlich bin ich einer der ersten Steineschmeißer.

**Comment by Loplin** [comment]
Ich werf mal
Hab ich in einem andern beitrag schonmal verlinkt aber da gings unter
https://m.youtube.com/watch?v=9-6K-IDhOdA
Gummo von der gilde Curse betreibt Rumstacking
Bann pls

**Comment by hraesvelgr** [comment]
@loplin kein namecalling, schick sowas als forenticket.

**Comment by Loplin** [comment]
Bitte video ansehn
das is aus 2006, der genannte typ hat das video gemacht. er spielt nicht auf dem server
die genannte gilde war eine der ersten, die naxx clear hatte
https://www.youtube.com/watch?v=9-6K-IDhOdA

**Comment by dagochen** [comment]
Macht bitte Zeitangaben bei Videos. Ich hab zwar unglaublich viel Zeit, aber trotzdem nicht immer Lust die vollen 5....10 ...oder 20 Minuten Videos mir reinzuziehen ;)

**Comment by dagochen** [comment]
@Loplin 
ich seh da http://datenbank.classic-wow.org/?item=18269 und http://datenbank.classic-wow.org/?item=18284

**Comment by testear** [comment]
Loplin was tut das Video zur Sache? Gummo hat 2 Alkohole drauf die unterschiedliche Werte haben. Noch dazu die aus Düsterbruch, bei denen immer noch nicht klar ist, ob sie denn jetzt Buff oder Debuff sein sollten. Beteilige dich ordentlich, oder gar nicht.

http://datenbank.classic-wow.org/?item=18284 +25 spirit  -5 int
http://datenbank.classic-wow.org/?item=18269 +10 stamina

Ich bin selber der Meinung Quellen gehören dazu. Auch wenn Ruljin in Sachen Buffstacking sehr kompetent ist, ist er genau so wenig wie ihr und ich eine Quelle von damals.

**Comment by Loplin** [comment]
du hast natürlich recht. mein video tut hier nichts zur Sache. Verzeihung

**Comment by dagochen** [comment]
Wieso ist doch gut. 2 Alkohole gehen offensichtlich, stacken allerdings nur dann, wenn sie unterschiedliche Stats geben. Die ganzen Buffstacking-Kombinationen sind programmiertechnisch halt echt nen Alptraum ;)

**Comment by testear** [comment]
Loplin kein Grund sich zu entschuldigen. Möglicherweise war das etwas harsch ausgedrückt, aber unter Garantie war es nicht böse gemeint.

**Comment by testear** [comment]
Bitte auch das Label "unzureichende Quellenangabe" dranpappen.

**Comment by dagochen** [comment]
Serverregeln + Video reichen doch als Quellen. 2 Alkohole mit unterschiedlichen Attributen gehen laut Video und damit ergeben die Regeln auch wieder Sinn. Rolle der Ausdauer + Priesterbuff stacken ja auch nicht. Beide in der gleichen Kategorie mit den gleichen Stats. Alkohole ist eine eigene Kategorie mit der gleichen Verhaltensweise.

**Comment by testear** [comment]
Du bist der Boss. ;)

**Comment by dagochen** [comment]
Hab ich nie behauptet :P Aber wenn du das sagst... 

Ne mal im Ernst. Ich glaube einfach das Blizzard da schon irgendwie ein System gehabt hat, was gestacked hat und was nicht. Und auf Grund der Quellen und Videos ist halt die oben genannte Theorie in meinem Kopf entstanden. Wenn jemand was findet das "mein Kartenhaus" zum Einsturz bringt, bitte, versucht es ;)

**Comment by testear** [comment]
Ich hab kein "Collaborator"  da stehen.

**Comment by testear** [comment]
fett verklickt beim comment deleten, weil er recht sinnfrei war.

**Comment by Slimmer2** [comment]
`Erläuterung Alkohol/Getränke:
Es kann nur ein Alkohol/Getränk genommen werden, egal welches.
`
https://community.mmobase.de/talk-und-allgemeines/5376-welche-buffs-stacken-erkl%E4rung.html

**Comment by dagochen** [comment]
Da das hier mit den DM-Alkoholen vielleicht ein Sonderfall ist, wäre es schon gut, wenn noch paar mehr Quellen dazu kommen als nur die Naxxramas-Videos. Wenn es damals wirklich so ein Sonderfall war, gibts bestimmt etwas.

**Comment by Slimmer2** [comment]
Rumsey Rum bekommt man nur einmalig 5 Stück bei einer Quest.
