### ISSUE TITLE
Weitreichende Stöße - Mainziel weicht aus

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1695]
Manchmal, wenn bei Weitreichenden Stößen das Hauptziel ausweicht werden mit dem nächsten Autohit alle Auflandungen von Weitreichenden Stößen entfernt.

Die Auflandungen sollten normal, nur wenn das Hauptziel getroffen wurde, verbraucht werden.

Weitreichende Stöße nutzen. Es tritt nicht immer auf, habe es bisher auch nur beim leveln beobachten können.
Möglicherweise tritt dieser Bug auch nur in Kombination mit bestimmten anderen Fähigkeiten auf.

http://datenbank.welli-it.de/?spell=12292

Bevor hier markiert wird bitte ich andere Krieger darum das zu testen.

**Comment by Horim** [comment]
Erstmal kleine Kritik: an die Vorlage halten :p

Bin noch nicht dazu gekommen es zu testen, da ich nur noch selten mit Arms-Specc rumlaufe.

Was ich jedoch direkt bestätigen kann: Es gibt Situationen in denen schlagartig alle Aufladungen verschwinden, ohne das hierdurch Schaden verursacht wird -> der Buff verschwindet einfach

**Comment by dagochen** [comment]
Er hat sich doch an die Vorlage gehalten ;) Nur halt die Überschriften entfernt^^

**Comment by testear** [comment]
Das hier erfordert auch noch ausgiebiges Testen. Habe das auch bisher nur ein paar mal so beobachten können. Aber aktuell bin ich froh, wenn ich abends ein bisschen zocken kann.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1445
