### ISSUE TITLE
Npc Handlanger der Defias 

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1697]
Welches` Verhalten wird beobachtet?
Die Handlanger der Defias benutzen keinen Schildschlag oder Schildblock. habe mich einige Zeit lang von denen bearbeiten lassen und sie selber ein wenig gehittet.

Wie sollte es sich verhalten?
Die Handlanger sollte die Fähigkeiten benutzen

Schritte zur Reproduzierung
Handlanger der Defias angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=594#abilities
http://datenbank.classic-wow.org/?spell=3248
http://datenbank.classic-wow.org/?spell=8242

**Comment by dagochen** [comment]
Grad auf dem Testserver ausprobiert. Die NPCs benutzen beide Fähigkeiten bereits.
