### ISSUE TITLE
Rhahk'zor

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1698]
Welches Verhalten wird beobachtet?
Rhahk'zor patroulliert nicht von seinen beiden Wachen weg, damit man ihn ohne seine adds pullen kann ( bekannte Taktik)

Wie sollte es sich verhalten?
Rhahk'zor sollte sich von dem Tor nach vorne in den Raum begeben  sodass seine beiden Wachen nicht mehr in aggro range sind  um dann solo gepullt werden zu können.

Schritte zur Reproduzierung
Den Raum zu Rhahk'zor betreten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
[0:56](https://youtu.be/mLVUYIBKVZ0?t=56)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
TBC-Quellen können leider nicht akzeptiert werden. Wenn du noch einen Guide oder so findest, in dem der Pull beschrieben wird, kann man da was ändern.

**Comment by Mafyo** [comment]
http://wow.gamepedia.com/Rhahk%27Zor Bei Strategy ist der pull beschrieben und einziger Patch war zu 4.0.3a removed

**Comment by hraesvelgr** [comment]
ist trotzdem keine verlässliche quelle. ich hadere auch immernoch mit den spells von dem "brainwashed noble" das erscheint mir alles irgendwie nicht richtig (bis auf den polymorph), und bisher lag ich fast immer korrekt mit meinen annahmen. :D 

http://www.wowhead.com/npc=644/rhahkzor#comments:id=822774 selbst bei patch 3.0.irgendwas wird noch davon geredet, dass man seine wachen sappen sollte, bevor man versucht ihn zu killen

**Comment by dagochen** [comment]
http://wowwiki.wikia.com/wiki/Rhahk%27Zor?oldid=337540

**Comment by Mafyo** [comment]
nur zur verständniss halber sind wowiki links aussagekräftiger als sowas wie wowpedia?

**Comment by dagochen** [comment]
Geht darum, wann der Eintrag erstellt wurde. Alles was aus 2007 und später veröffentlicht wurde, ist nach dem Classic-Zeitalter und daher nur bedingt aussagekräftig.
