### ISSUE TITLE
Jadefeuerschwindler im Teufelswald kann Innerer Fokus aktivieren obwohl dieser nicht geskillt ist

### ISSUE THREAD

**Issue by elnarg** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1700]
Welches Verhalten wird beobachtet?
Jadefeuerschwindler im Teufelswald kann wenn er einen Priester per Gedankenkontrolle übernimmt Innerer Fokus aktivieren obwohl dieser nicht geskillt ist
Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

![wowscrnshot_081416_123337](https://cloud.githubusercontent.com/assets/20861550/17648614/3b6ff3c8-621c-11e6-80cf-dce10dfcaed5.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Haudraufinix** [comment]
Scheint für eine grosse Anzahl von Skills bzw alle zuzutreffen. Beim Jäger hatte ich schon Abschreckung welches aktiviert wurde ohne dass ich es geskillt hatte und mein Schamane hat auch schon instant casts verteilt damit.

**Comment by dagochen** [comment]
Wahax hatte das vor einem Jahr gemacht. Ich meine er hatte auch eine Quelle von 2006 in der jemand geschrieben hatte, dass ihm so etwas passiert ist und sich gewundert hatte. Ich versuch die mal zu finden...
