### ISSUE TITLE
Blut eines grünen Welpen (Quest: Nichts als die Wahrheit)

### ISSUE THREAD

**Issue by Ailjin86** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1702]
Welches Verhalten wird beobachtet?
- nach etwa 1,5 h killen nicht ein einziger Drop des Questgegenstands von http://datenbank.classic-wow.org/?npc=741#drop:0-12+1 oder http://datenbank.classic-wow.org/?npc=740 [die anderen Questgegenstände (http://datenbank.classic-wow.org/?item=6080 und http://datenbank.classic-wow.org/?item=6081) hatten eine Droprate von ~100%].
Wie sollte es sich verhalten?
- ich vermute ähnliche Dropraten wie bei den anderen Gegenständen (selbst bei 10%-Rate könnte ich jetzt im Blut baden).
Schritte zur Reproduzierung
- Drachenwelpen vor Itharius' Höhle killen
Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Verlink mal bitte das Item aus der Datenbank das nicht droppt und die Quest, für die du das Item benötigt.

**Comment by Ailjin86** [comment]
Die Quest ist folgende: http://datenbank.classic-wow.org/?quest=1383/Nichts%20als%20die%20Wahrheit
Allerdings steht im Spiel im Questtext nicht, dass ich den Tiefschreitertumor besorgen soll, sondern das Blut eines grünen Welpen. Das findet sich nicht in der Datenbank. Ich bilde mir aber ein mich erinnern zu können, dass ich mit einem anderen Charakter meines Accounts das Blut schon irgendwann mal von den Welpen bekommen habe. Deswegen bin ich ja so irritiert, dass es auf einmal nicht mehr geht.

**Comment by dagochen** [comment]
Ahhh jetzt weiß ich was hier los ist ;)
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1000

Kann sein, dass das schon auf Nefarian ist, nur noch nicht gelabelt wurde...
