### ISSUE TITLE
Schlüssel für die Gordokhoftür

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1707]
Welches Verhalten wird beobachtet?
der Schlüssel droppt bei normalen mobs in Dire Maul. Ist mir persöhnlich auch schon passiert

Wie sollte es sich verhalten?
Der Schlüssel sollte nur in Fengus Truhe zu finden sein

Schritte zur Reproduzierung
in Der Datenbank sind einige Npc angegeben.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Gordok_Courtyard_Key?oldid=349556

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

[Schlüssel für die Gordokhoftür](http://datenbank.classic-wow.org/?item=18266#dropped-by)
[Fengus Truhe](http://datenbank.classic-wow.org/?object=179516)

	
	
Weiterführende Informationen

**Comment by hraesvelgr** [comment]
typischer fall von falschem tracking in der db.
