### ISSUE TITLE
Dargols Halsberge

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1708]
Welches Verhalten wird beobachtet?
Dieses Item ist momentan ein random Worlddrop

Wie sollte es sich verhalten?

Das Item sollte ausschließlich bei Hauptmann Dargol droppen

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Dargol%27s_Hauberk

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Dargols Halsberge](Dargols Halsberge)
[Captain Dargol](http://datenbank.classic-wow.org/?npc=1658)

**Comment by dagochen** [comment]
http://datenbank.classic-wow.org/?item=3330
