### ISSUE TITLE
Gefüllte Taudrüse zu hohe Dropchance

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#171]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?item=8428 droppt von http://datenbank.welli-it.de/?npc=5481 zu hoch (100%).

Wie sollte es sich verhalten? 
Die dropchance sollte deutlich geringer sein.

Schritte zur Reproduzierung:
http://datenbank.welli-it.de/?quest=2605 machen

Zusätzliche Informationen (Screenshots, Videos, etc.): 
8% ? http://de.wowhead.com/item=8428/gefullte-taudruse

**Comment by Larnak1** [comment]
Noch eins:
http://datenbank.welli-it.de/?item=3477

Kommentare bei WoWhead:
http://de.wowhead.com/item=3477#english-comments
Scheint auf 6% hinauszulaufen, der entsprechende Kommentar scheint die Info aus den damaligen DB-Einträgen genommen zu haben... Aber die Datenlage ist wieder recht dünn.

**Comment by Dotox** [comment]
Dankeschön. Wurde aufgespielt.

**Comment by Larnak1** [comment]
Humberts Schwert ist auch so ein Fall:
http://datenbank.welli-it.de/?item=3693

Die Kommentare:
http://de.wowhead.com/item=3693/humberts-schwert#english-comments
sind sich zwar einig darin, dass die Dropchance mies ist, genaue Werte stehen da allerdings nicht. Es scheint sich aber um Werte um 5% zu handeln.
