### ISSUE TITLE
Npc Leprithus

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1711]
Welches Verhalten wird beobachtet?
Der Npc Spawnt an der falschen stelle zusätzlich sollte er in seinem Loottable 2 besondere items haben

Wie sollte es sich verhalten?
 der Npc sollte in Westfall links neben dem Jangoschacht in einem kleinem umzeunten Grab spawnen und ghulfinger und ghulfangzahn im loottable haben die nur bei dem droppen dürfen .

Schritte zur Reproduzierung
Npc angreifen bzw. entdecken?

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Leprithus

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=572#drop:100-12+1
[Ghulfangzahn](http://datenbank.classic-wow.org/?item=1387)
[Ghulfinger](http://datenbank.classic-wow.org/?item=1314)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/565 sufu nutzen :^)

**Comment by Mafyo** [comment]
oh shit sry mach ich sonst eig. aber jetzt hab ich es vergessen :(

**Comment by dagochen** [comment]
Du wirst wahrscheinlich nie 60 und ich schaffe es dafür nicht die aktuelle Anzahl an Bugs unter 400 zu bekommen :(
