### ISSUE TITLE
Softreset und Gehennas-Adds

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1712]
**Welches Verhalten wird beobachtet?**
Nach einem Softreset von Molten Core standen die Bossadds von Gehennas wieder.
Das sollte so nicht sein.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
[Screenshot](http://www2.pic-upload.de/img/31496266/Gehennas.jpg)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Gehennas: http://www.wowhead.com/npc=12259/gehennas
Feuerschuppenelite: http://datenbank.classic-wow.org/?npc=11664

**Comment by testear** [comment]
Das steht wo in der Quelle? Ich bin mir sicher wir haben alle Lust uns durch belangloses Zeug wie die Herkunft des Namen "Gehennas" zu wühlen.

**Comment by Jessienia** [comment]
Für so was braucht es ja wohl kaum ne Quelle. Sollte logisch sein, dass der halbe encounter nicht nach nem softrest respawnen sollte.

**Comment by dagochen** [comment]
Auch auf die Gefahr mich als totaler Noob zu authen ;) Was ist ein Softreset und wie bewerkstellige ich das im Raid?

**Comment by Slimmer2** [comment]
Das Frage ich mich auch.
Bei einen Reset sollten alle Adds die zum Boss Kampf gehören, auch wieder stehen.
Anders wäre der Kampf zu stark vom Encounter abweichend und deutlich leichter.

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/Instance_reset 
A soft reset is when all party members leave the instance, and then come back in. This puts people out of combat, making mobs run back to their original places. 

Warum sollte wenn man einen Bosskampf mittendrin beendet, der Encounter sich nicht wieder korrekt zurücksetzen? Das wäre zu simpel zu missbrauchen als das man das ohne Quelle verändern sollte.

**Comment by dagochen** [comment]
Sprich die Spieler haben Gehennas getötet und sind dann rausgelaufen, ohne die 2 Adds zu töten?

**Comment by testear** [comment]
Der Report lässt zwar auf umgekehrtes Vorgehen schließen aber im Grunde genau das Dagochen.

**Comment by dagochen** [comment]
Ehrlich gesagt bin ich hier überfragt. Sollte das nicht möglich sein, Adds von Bossen stehen zu lassen? 

Grad oben nochmal gelesen:
> Nach einem Softreset von Molten Core standen die Bossadds von Gehennas wieder.
Demnach wurden die getötet und sind respawned? Das sollte definitiv nicht so sein.

**Comment by testear** [comment]
Die Adds bei Drakkisath respawnen auch.

**Comment by dagochen** [comment]
Nein nein nein^^ glaub wir reden aneinander vorbei. 
Istzustand:
Boss tot -> Wipe -> Adds stehen noch --> In ordnung und korrekt
Adds tot -> Wipe -> Boss steht noch --> Boss resettet -> adds respawnen -> In Ordnung und korrekt
Boss tot -> Adds tot -> softreset (oder server neustart oder oder oder) -> adds respawn -> falsch und muss korrigiert werden

**Comment by Jessienia** [comment]
> Boss tot -> Adds tot -> softreset (oder server neustart oder oder oder) -> adds respawn -> falsch und muss korrigiert werden

So hab ich das zumindest interpretiert.

Zum Thema Sofrest:
testear hat eigentlich den falschen Abschnitt hier reinkopiert. Softrest bedeuted, dass alle aus der Instanz gehen und man sie für 30 min nicht mehr betritt, was bewirkt, dass die aktuelle Instanz aufgelöst wird. Das führt auch dazu, dass Trash respawnt (wenn er es kann) oder oder andere Trashmobs despwnen, wenn der dazugehörige Boss getötet wurde (z.b. Kernhunde).

**Comment by g3n3a** [comment]
Um das mal hier aufzuklären: Wir hatten MC mit allen Bossen bis inklusive Garr gemacht und dann aus Zeitmangel abgebrochen. Die ID wurde dann an einem anderen Tag fortgesetzt (=Softreset). Gehennas wurde ganz normal mit seinen Adds getötet, genauso wie Garr. Die Adds von Garr respawnten nach dem Softreset auch nicht. Nur die Adds von Gehennas standen ohne Boss da.
