### ISSUE TITLE
Teilresists bei Binären Spells

### ISSUE THREAD

**Issue by Kriptyk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1714]
Welches Verhalten wird beobachtet?
Mir ist gestern aufgefallen, dass bei manchen binären Spells trotzdem Teilresists auftreten können.
Als Beispiele habe ich hier Kältekegel und Frostnova beim Magier beobachten können.

Wie sollte es sich verhalten?
Binäre Spells sollten immer ganz oder gar nicht treffen (daher der Name). Teilresists sind bei solchen Spells unmöglich. Beim Frostblitz funktioniert das z.B. einwandfrei.

Schritte zur Reproduzierung
Kältekegel/Frostnova/jeden anderen potenziell verbuggten binären Spell auf einen Mob mit entsprechender Resistenz casten bis ein Teilresists auftritt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Aufgefallen ist mit der Bug bei den etwas größeren Pflanzen in DM-Ost.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Kältekegel: http://datenbank.classic-wow.org/?spell=10160
Frostnova: http://datenbank.classic-wow.org/?spell=122
Frostblitz: http://datenbank.classic-wow.org/?spell=25304

**Comment by Badorr** [comment]
Beim Schami kann ich hinzufügen, dass hier Frostschock ebenfalls von Teilresists betroffen ist, obwohl er die gleiche Mechanik wie der Frostbolt hat (Schaden+Sloweffekt)

**Comment by testear** [comment]
Die Quelle wären ganze 2 Minuten mehr arbeit gewesen und auch, wenn das hier völlig logisch ist gehören Datenbanklinks dazu @Badorr. Die Devs suchen aber bestimmt gerne sämtliche binären Spells raus und überprüfen ob diese richtig resisten.

http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance?direction=prev&oldid=295634

**Comment by dagochen** [comment]
Ne raussuchen wird die sicherlich kein Dev ;) Aber wir können nach Zaubern suchen die zusätzlich zu einem Dmg-Effekt noch einen Slow oder Root Effekt haben und das so relativ generisch programmieren, sodass man ohne jeden Zauber zu kennen trotzdem jeden Zauber erwischt. Trotzdem hilft es natürlich beim überprüfen, ob man wirklich alle erwischt hat, wenn hier ein paar solcher Zauber genannt sind...

**Comment by Badorr** [comment]
Datenbanklinks und weitere Spells hinzugefügt

**Comment by testear** [comment]
klare Worte, schnelle Antwort, mehr Effizienz.

**Comment by hraesvelgr** [comment]
das wurde doch mal gefixt, von wahax?

**Comment by Kriptyk** [comment]
Ich bin auch der Meinung, dass das mal funktioniert hat. Der Bug wäre mir sonst mit Sicherheit früher schon aufgefallen.
Evtl ist einer Änderung aus der jüngeren Vergangenheit dafür verantwortlich.

**Comment by testear** [comment]
Ich glaube das ist nur bestimmte Zauber geändert worden. Thunderfury und Frostbolt finde ich da auf Anhieb.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/978
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/620

**Comment by Badorr** [comment]
Ich kann noch Erdschock zu der Liste hinzufügen. http://datenbank.classic-wow.org/?spell=10414
Ist mir im PvP aufgefallen und vorallem bei den kleinen Augententakeln bei C'thun. Die Dinger können dem Interrupt vom Erdschock widerstehen, aber kriegen den Schaden trotzdem. Und umgekehrt funktioniert das auch.

**Comment by SirBeansen** [comment]
Wie wird das denn berechnet wenn ein Schadens Spell, zum beispiel auch einen Stun effekt hat? Wird dann die 5% ressist chance mit den 5% Stun ressist Chance addiert, sodass mann auf den Sell dann 10% ressist Chance hat?

**Comment by Kriptyk** [comment]
Also mir fällt gerade spontan kein Spell ein der Schaden macht und stunnt aber prinzipiell sollte diese Resist Chance addiert werden und auch nicht mit zusätzlichem Hit reduzierbar sein. 
Es könnte auch sein, dass diese Chance vor der eigentlichen Hit-Berechnung statt findet. Also geprüft wird ob der Stun Resist triggert und wenn nicht wird anschließend berechnet ob der Spell trifft. Oder anders herum. Das sind glaub ich so ziemlich die Möglichkeiten^^. Das müsste ein Entwickler endgültig beantworten.

**Comment by Badorr** [comment]
Beansen meint warscheinlich den geskillten Impact Proc vom Feuerball. Da Feuerball aber kein binärer Spell ist, sollten Schadens- und Stunkomponente separat berechnet werden.

**Comment by Kriptyk** [comment]
In diesem speziellen Fall bedingt der Schaden den Stun. Das wäre also Variante 3: Es wird berechnet ob der Spell trifft und wenn ja, wird berechnet ob der Stun proct.

**Comment by SirBeansen** [comment]
Naja es war nur ein Beispiel. Das gleiche gilt ja auch für Frostnova, Mind Flay, Frostbolt und Frostschock (Schaden + slow). Man kann die Chance Snare effekte zu widerstehen ja erhöhen.

Ich kenne es ja nur so:

Binäre Spells: treffen ganz oder gar nicht (kein teilresist möglich)
während nicht Binäre Spells: teilresisten können z.b Arkane Geschosse und dot ticks

Interessant wäre es auch noch ob im Pve alles richtig funktioniert.

Wrath of Raggy sollte dann zb auch ganz oder gar nicht treffen. Weiß aber nicht wie es aktuell ist.
