### ISSUE TITLE
Strathholme Baroness Anastari

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1715]
Welches Verhalten wird beobachtet?
Der Boss verwendet seine Hauptfähigkeit die diesen Bossfight besonders machen sollte nicht korrekt. Ich Spreche von der Fähigkeit ''Possess''. Es kommt oft vor das diese Fähigkeit nicht eingesetzt wird oder das jemand aus der Gruppe einfach so übernommen wird ohne das der Boss verschwindet.

Wie sollte es sich verhalten?
''Her most powerful ability is to dominate any individual she is touching, actually displacing the soul of her target. This domination temporary places the banshee's spirit within the individual thus affected. At this point, the Anastari is no longer a banshee, but instead becomes a corporeal form of undead. ''

Das Bedeutet das sie ''Possess'' auf einen Random Spieler wirkt und dieser dann übernommen wird, sie verschwindet sozusagen in diese Person, in wowwiki wird beschrieben das sie regelmäßig wichtige CD's der Spieler benutzt weshalb man diese schon vor der ''possess'' phase benutzen sollte. Die Gruppenmitglieder müssen den übernommenen dann auf 50% leben runterhauen sodass die Baroness wieder erscheint. Der zuvor übernommene hatt nach dem Mindcontrol wieder volle HP.

Schritte zur Reproduzierung
Boss angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Baroness_Anastari?oldid=390556
https://youtu.be/IuMTcmUq5tQ hier sieht man schön wie der encounter eigentlich funktionieren sollte
https://youtu.be/dSrFWSP3FJA?t=198 das ist ein video vom Nostal. Server aber hier sieht man das es soweit ganz gut Gescriptet wurde und der Spieler erklärt nochmal schön diese Fähigkeiten.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Baroness Anastari](http://datenbank.classic-wow.org/?npc=10436#abilities)
[Possess](http://datenbank.classic-wow.org/?spell=17244)

**Comment by Suzaru** [comment]
Moin,

seit dem Fix ist es teilweise nicht mehr möglich Baron zu machen.
Die Baroness übernimmt jemanden und dann passieren mehrere Dinge:
1) Das Übernehmen bleibt, auch wenn der Debuff abgelaufen ist
2) Die Baroness despawned und bleibt despawned, auch wenn der übernommene getötet wurde
3) Die Baroness bleibt despawned  bis die ganze Gruppe einmal aus der Instanz gelaufen ist und wieder rein. Beim Wiedereintreten des Übernommenen spawnt die Baroness aus demjenigen und fliegt zu Ihrem Spot.

Die Baroness ist also derzeit nicht killbar, wenn sie ihren Übernehmen Spell nutzt.
Wenn man sie wegflext ohne, dass sie jemanden übernimmt - dann gehts.

Liebe Grüße,
Suzu
