### ISSUE TITLE
Stratholme Thuzadinakolyt

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1716]
Welches Verhalten wird beobachtet?
Die Thuzadinakolyten die in den Zigurats stehen, greifen einen überhaupt nicht an. Sie adden zwar alle gleichzeitig bleiben jedoch alle auf der Stelle stehen und man kann sie einfach umhauen

Wie sollte es sich verhalten?
die Thuzadinakolyten sollte nach dem man einen geadded hat alle chainadden und zu einem hinlaufen und denjenigen angreifen

Schritte zur Reproduzierung
Thuzadinakolyt angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/9QsftBBXd1o?t=267

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Thuzadinakolyt](http://datenbank.classic-wow.org/?npc=10399)

**Comment by Baraz** [comment]
#1530

**Comment by Sabbaer** [comment]
warum wurde der erste eigentlich geclosed?
