### ISSUE TITLE
Stratholme Ramstein der Verschlinger

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1717]
Welches Verhalten wird beobachtet?
Ramstein hatt die Fähigkeit den tank weg zu kicken und 6 sec zu stunnen. dieser stunn wird angezeigt jedoch kann sich der betroffene tank damit bewegen und Fähigkeiten weiter benutzen.
 Er Läuft zu schnell

Wie sollte es sich verhalten?
Ramstein sollte den tank zurück kicken und 6 Sekunden stunnen, gleichzeitig sollte ein kompletter aggro wipe entstehen, zudem Sollte Ramstein auch langsam laufen damit man ihn kiten kann weil er ja ein aggro resett durch den stun hatt.

''after killing your last abomination, Ramstein the Gorger will walk towards you. He hits hard and can take quite a beating. But the most annoying thing about him is that he tosses your tank in the air, stunning it for 3 seconds, and loses aggro. It can't be helped, he will beat on the casters for a few seconds until your tank gets back and taunts him off.

Keine Ahnung warum er hier 3 Skunden stunnt laut Guide vielleicht persöhnlichs gefühl oder alter Patchstand?

Schritte zur Reproduzierung
Ramstein angreifen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Ramstein_the_Gorger?oldid=372277
der Guide : http://wow-pro.com/dungeon_and_raid_guides/4256_jame039s_stratholme_guide

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Ramstein der Verschlinger](http://datenbank.classic-wow.org/?npc=10439#abilities)
[Knockout](http://datenbank.classic-wow.org/?spell=17307)
[Dazed](http://datenbank.classic-wow.org/?spell=1604#see-also-ability)
[Dazed](http://datenbank.classic-wow.org/?spell=13496)

**Comment by Mafyo** [comment]
[#1117](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1117)
[#111](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/111)

**Comment by dagochen** [comment]
Wenn du schon Beiträge findest, wo genau der gleiche Bug reportet wurde, brauchst du keinen neuen dafür machen ;)
