### ISSUE TITLE
Schattenhaftigkeit bricht erst ab nach Vollendung eines Casts

### ISSUE THREAD

**Issue by Faeleen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1718]
Welches Verhalten wird beobachtet?
Ich war mit meinem Nachtelf Jäger farmen und stand in Schattenhaftigkeit in der Nähe des Mobs. Als ich einen Aimed Shot wirkte, kam mein Jäger erst aus dem Stealth als der Schuss fertig gecastet war und auf den Mob zuflog.
Funktioniert genauso beim Aufmounten. Stealth bricht erst ab, wenn der Cast beendet ist und man auf dem Mount sitzt.

Wie sollte es sich verhalten?
Schattenhaftigkeit sollte zu Beginn des Casts abbrechen.

Schritte zur Reproduzierung
In Schattenhaftigkeit gehen und Spell benutzen

Zusätzliche Informationen (Screenshots, Videos, etc.)
Der Link zu den Patchnotes: http://wowwiki.wikia.com/wiki/Patch_1.10.0 
"Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action."

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?search=shadowme
http://datenbank.classic-wow.org/?spell=27632

**Comment by Rukachi** [comment]
Keine Ahnung ob es schon bekannt ist aber sowas ähnliches passiert auch mit meinem Schurken, wenn ich ihn Verstohlenheit anfange Erze abzubauen. Vielleicht das selbe Problem?

**Comment by Badorr** [comment]
Das gleiche gilt dann wohl auch für Unsichtbarkeitspots? Da wird man auch erst nach Vollendung des Casts/der Fähigkeit sichtbar. 

http://datenbank.classic-wow.org/?spell=11392
http://datenbank.classic-wow.org/?spell=3680

**Comment by Dragonshome** [comment]
Hallo,

das die Schattenhaftigkeit während des castens bestehen bleibt war zu Classic so. Nur beim Abbauen von Erz und sonstigem musste es abbrechen, da das ja kein Cast ist. Aufmounten und Aimed Shot ist richtig.

Gruß

**Comment by dagochen** [comment]
Hast du dafür eine Quelle @Dragonshome ? Bisher haben wir die 1.10 Patchnotes die als zuverlässig gelten und auch für die folgenden Patchstände 1.11-1.12 gültig sind.

**Comment by Badorr** [comment]
Stand jetzt können Nachtelfhunter immer noch ausm Stealth den Aimed ansetzen und werden als am Ende der Aktion sichtbar, also wenn das Ziel Schaden bekommt. Dasselbe gilt für Unsichtbarkeitstranks
