### ISSUE TITLE
Totstellen bricht nicht ab beim Pflanzen sammeln

### ISSUE THREAD

**Issue by Faeleen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1719]
Welches Verhalten wird beobachtet?
Ich war mit meinem Jäger Kräuter sammeln und hatte ein Add an mir. Vor dem Krautspawn stellte ich mich tot und lootete das Kraut. Dabei fiel mir auf, dass mein Jäger weiterhin totgestellt liegen blieb. Als der Cast durch war, erhielt ich in roter Schrift ein "Unterbrochen", aber das Kraut wurde trotzdem gelootet und despawnte daraufhin auch ganz normal. Selbes passiert auch beim Aufmounten. 

Wie sollte es sich verhalten?
Totstellen sollte abbrechen, wenn man währenddessen etwas looten oder aufmounten möchte.

Schritte zur Reproduzierung
Totstellen und Kraut looten/aufmounten

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Feign_Death?oldid=322213
Unter Limitations: "Moving or performing any action while feigning death will cancel the spell."

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?search=feign+d

**Comment by Larnak1** [comment]
Das betrifft glaube ich auch immer noch das Einnehmen von Flaggenpunkten im Arathibecken.
