### ISSUE TITLE
Looten während man castet

### ISSUE THREAD

**Issue by Faeleen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1720]
Welches Verhalten wird beobachtet?
Man kann tote Mobs looten, während man einen Spell castet.

Wie sollte es sich verhalten?
Der Spell sollte abgebrochen werden, wenn man eine neue Aktion beginnt.

Schritte zur Reproduzierung
Mob töten, in Range laufen, Cast ansetzen, Mob looten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Habe derzeit keine, wäre aber schön, wenn sich jemand anderes das nochmal ansehen könnte und dann ggf. Quellen hinzuposten würde.

**Comment by Slimmer2** [comment]
Ich bin eher der Meinung, das der Zauber weiter gewirkt werden sollte.
Und eher eine Meldung kommen sollte ihr führt eine andere Aktion aus.

**Comment by Faeleen** [comment]
Okay, da bin ich mir nicht sicher, wie das ursprünglich sein sollte. Ich bin jetzt oben davon ausgegangen, dass Bewegung einen Spell abbricht. Ich gestehe, ich hab kein Video von damals gefunden, in dem man eindeutig sieht, ob der Cast abgebrochen werden sollte oder ob eine Nachricht erscheint.

**Comment by Sabbaer** [comment]
quellen?

**Comment by Slimmer2** [comment]
Wenn man beide Hände zum zaubern benutzt, hat man keine zum looten frei.
Da sollte gesunder Menschenverstand reichen

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/WoW_Constants/Errors?oldid=146379

ERR_LOOT_BAD_FACING 
    You must be facing the corpse to loot it. 

ERR_LOOT_NO_UI 
    You can't loot right now. 

ERR_MOUNT_LOOTING 
    You can't mount while looting! 

sind nur ein paar Beispiele der Error-Meldungen. Dort könnte man aber was dazu finden. "You can't mount while looting!" deutet jedenfalls an, dass man beim Looten nicht aufmounten kann.
