### ISSUE TITLE
Rogue, verlassen von Stealth nach SAP.

### ISSUE THREAD

**Issue by Vierhaarejoe** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1722]
Welches Verhalten wird beobachtet?
Nach wirken von Kopfnuss "SAP" geht man automatisch ausm Stealth /Vanish. Was eine außerordentlich Einbuße für die Klasse in Instanzen is, da für diesen CC entweder ein Tank pull folgen muss oder man den Vanish CD benutzen muss.
Wie sollte es sich verhalten?
Im Normalfall sollte der Schurke in Stealth /Vanish bleiben.
Schritte zur Reproduzierung
Sollte leicht Reproduzierbar sein,da alle Schurken davon betroffen sind.
Zusätzliche Informationen (Screenshots, Videos, etc.)
-
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=1784
http://datenbank.classic-wow.org/?spell=6770
http://datenbank.classic-wow.org/?spell=1856

**Comment by Slimmer2** [comment]
Das ist kein Bug.
Das war in Classic so

**Comment by ChichiWarrior** [comment]
Leider ist es weder im englischen, noch im deutschen anständig beschrieben.

Wenn man http://datenbank.classic-wow.org/?search=improved+sap nicht skillt, kommt man automatisch aus dem Stealth nach einem Sap.

Das war in Classic so und ist daher kein Bug.

**Comment by dagochen** [comment]
Danke an meine Vorredner ;) Dem schließe ich mich an.

**Comment by Vierhaarejoe** [comment]
Okay,ging immer davon aus das es nicht normal ist. Danke für die schnelle Rückmeldung.
