### ISSUE TITLE
Der NPC Mushgog portet die Gruppe aus der Instanz

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1724]
**Welches Verhalten wird beobachtet?**

Wenn man den Rare Mushgog angreift dann wird man nach einiger Zeit plötzlich aus der Instanz rausgeportet. Der Bildschirm wird plötzlich grau und man landet lebendig auf dem Friedhof.

**Wie sollte es sich verhalten?**

Man sollte nicht aus der Instanz teleportiert werden wenn man diesen NPC angreift.

**Schritte zur Reproduzierung**

Düsterbruch Ost machen, hoffen dass Msuhgog da ist da es sich um einen seltenen Gegner handelt. Wenn er da ist dann angreifen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Link zum Gegner:
http://datenbank.classic-wow.org/?npc=11447

Grüße

**Comment by testear** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/364

**Comment by dagochen** [comment]
Da es sich hierbei um ein Duplikat handelt, mache ich hier zu.
