### ISSUE TITLE
[NPC] Commendation Officers (Belobigungsoffiziere) fehlen.

### ISSUE THREAD

**Issue by Amasov** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1726]
**_Welches Verhalten wird beobachtet?_**

Es fehlen folgende NPCs (Belobigungsoffiziere) in den Hauptstädten, ergo gibt es keine Möglichkeit mehr noch im Spiel vorhandene Belobigungsabzeichen (Commendation Signets -- http://datenbank.classic-wow.org/?item=21438 // http://datenbank.classic-wow.org/?item=21436) abzugeben.

Allianz:
http://datenbank.classic-wow.org/?npc=15766
http://datenbank.classic-wow.org/?npc=15764
http://datenbank.classic-wow.org/?npc=15762
http://datenbank.classic-wow.org/?npc=15763

Horde:
http://datenbank.classic-wow.org/?npc=15765
http://datenbank.classic-wow.org/?npc=15767
http://datenbank.classic-wow.org/?npc=15761
http://datenbank.classic-wow.org/?npc=15768

**_Wie sollte es sich verhalten?_**

Die NPCs sollten auch nach der Öffnung der Tore von Ahn'Qiraj zur Abgabe der Belobigungsabzeichen noch vorhanden sein.

**_Schritte zur Reproduzierung_**

- 1. Blizzard hat extra in der Exodar und in Silbermond in Patch 2.2.0 für die Draenei- und Blutelfenfraktion Belobigungsoffiziere reingepatcht (http://www.wowhead.com/npc=21971 //  http://www.wowhead.com/npc=21970)
- 2. Die NPCs und Abzeichen wurden undokumentiert mit Patch 3.2.0 entfernt ( Beispiel Offizier Maloof : http://wowwiki.wikia.com/wiki/Officer_Maloof // Abzeichen: http://wowwiki.wikia.com/wiki/Alliance_Commendation_Signet)
- 3. http://www.mmo-champion.com/threads/660490-Patch-details-not-mentioned-in-the-Patch-notes?p=6535326&viewfull=1#post6535326

**Comment by Slimmer2** [comment]
Das ist kein Bug, da aq bereits offen ist.
Deswegen kann man die nicht mehr abgeben.

**Comment by Amasov** [comment]
wahaxlekuke commented on 21 Aug 2015

http://wowwiki.wikia.com/wiki/Quest:Ten_Commendation_Signets?oldid=288676
vom 17. Oktober 2006

    Level Obtained
    Level 60

**Die Belobigungsoffiziere bleiben aber nach Ende des Events noch stehen, du kannst die Abzeichen also aufheben bis du Stufe 60 bist.**

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/995#issuecomment-133375997
