### ISSUE TITLE
Suntarasteine Eskortquest funktioniert nicht

### ISSUE THREAD

**Issue by benib86** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1731]
Welches Verhalten wird beobachtet?
Dorius Steinhüter steht nicht auf und macht nichts nachdem man seine Eskortquest gestartet hat (Suntara Steine http://datenbank.classic-wow.org/?quest=3367/Suntarasteine)
Wie sollte es sich verhalten?
Er sollte aufstehen und den wegablaufen
Schritte zur Reproduzierung
Quest annehmen
Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Suntarasteine http://datenbank.classic-wow.org/?quest=3367/Suntarasteine
Dorius Steinhüter http://datenbank.classic-wow.org/?npc=8284

**Comment by hraesvelgr** [comment]
#642
#147
