### ISSUE TITLE
C'thun Phase 2 Magen: Debuff stackt nicht hoch

### ISSUE THREAD

**Issue by Mesttbash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1732]
Welches Verhalten wird beobachtet? Als ich bei C´thun bei P2 in den Magen geportet wurde, waren beide Tentakeln selbst gerade gestorben, so dass P3 beginnt und ich direkt wieder ausgespuckt wurde. Als P3 dann zu Ende war, wurde ich direkt wieder, ohne einzusaugen, heruntergeportet und hatte den Debuff bekommen. Doch dieser Debuff hat sich nicht hochgestackt, so dass ich durchnuken hätte können. Also war ich nach 30sec. von allein hochgegangen, da es mir merkwürdig vor kam!

Wie sollte es sich verhalten? Der Debuff sollte hochstacken, bzw. man darf gar nicht erst heruntergeportet werden, sobald P2 wieder beginnt.

Schritte zur Reproduzierung: Ich weiß das nicht :-D

Zusätzliche Informationen (Screenshots, Videos, etc.): nicht vorhanden

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Kann man dem Zauber widerstehen? Sollte man ihm widerstehen können?

**Comment by Mesttbash** [comment]
Moin,
Also ich habe den Zauber definitiv nicht widerstanden.
Er hat nicht hochgestackt, ganz klar.
Ob man ihn widerstehen kann, denke ich nicht.

Von meinem iPhone gesendet

**Comment by dagochen** [comment]
Ich vermute mal du wurdest irrtümlicherweise wieder runtergeportet. Dadurch wusste Cthun nicht, dass du den Debuff auch abbekommen solltest (standest nicht auf der Liste der Spieler die im Magen sind) und dadurch wurde der Debuff auf dich auch nicht gecastet.

**Comment by Jessienia** [comment]
Das ganze ist mir auch schon 2-3 mal passiert. Wurde gefressen und im gleichen Moment hat die Schwächephase begonnen. Nach Ende dieser Phase wurde ich wieder direkt in den Magen geportet. Hatte zwar die Aura als Debuff, aber der Dot ist nicht hochgestackt. 

Im Prinzip nicht weiter ein Problem, wenn man direkt wieder aus dem Magen raus geht. Aber wenn man will, kann man es halt auch zum übelsten Bugusen nutzen.

**Comment by Haudraufinix** [comment]
kann das beschriebene Verhalten bestätigen, ist mir Gestern auch gerade passiert

**Comment by Ulva-Anorhin** [comment]
Wir hatten das selbe wie oben beschrieben heute Abend auch (30.07.2017)
