### ISSUE TITLE
Quest: Befehl des Kriegsherrn

### ISSUE THREAD

**Issue by ralffechner** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1733]
Welches Verhalten wird beobachtet? Die Bosse sind getötet, die Blackrockpapiere im Inventar. Der Kriegsherr erkennt die Papiere nicht. ich kann nicht abgeben. Hatte allerdings die Papiere zweimal aufgenommen und im Dungeon eins wieder fortgeworfen.

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Mach den Report so wie es gehört.
Quest auch Mal abgebrochen und neu angenommen?

**Comment by dagochen** [comment]
Leg die Papiere einmal auf die Bank, schließe WoW, lösche den WDB Ordner, starte WoW neu und hol die Papiere aus der Bank. Dann solltest du die Quest abgeben können.
