### ISSUE TITLE
Holzschlundfeste + Gelkisclan

### ISSUE THREAD

**Issue by ralffechner** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1734]
Welches Verhalten wird beobachtet? Bei beiden Fraktionen bin ich z.Z. freundlich, aber es wird im Krieg angezeigt. Kann auch die Runenstoffquest bei Meilosh in der Holzschlundfeste nicht abgeben, da ich nur die Möglichkeit habe ihn anzugreifen.

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Hey Ralf,

du kannst sobald eine Fraktion dir nicht mehr als Feindselig angezeigt wird selbst entscheiden, ob du dich mit einer Fraktion im Krieg befindest oder nicht. Dazu brauchst du nur bei der Checkbox "Im Krieg" das Häkchen zu deaktivieren (siehe Bild).
![holzschlundfeste](https://cloud.githubusercontent.com/assets/5236186/18229755/91f1b4de-7284-11e6-85d7-e59bafa93784.png)

**Comment by ralffechner** [comment]
Vielen Dank!
