### ISSUE TITLE
Greta Mooshuf

### ISSUE THREAD

**Issue by Shelzo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1736]
Greta Mooshuf im Teufelswald beim Smaragdrefugium verteilt den Quest "Streitmacht von Jaedenar". Allerdings wird kein gelbes Ausrufezeichen angezeigt, welches anzeigen könnte, dass dieser NPC eine Quest abzugeben hat.

**Comment by dagochen** [comment]
Wenn du ein zu hohes Level hast, werden dir Quests nicht mehr mit einem Ausrufezeichen angezeigt.
Hier zum Vergleich einmal mit Level 55 und Level 56 ;)
![wowscrnshot_090816_002703](https://cloud.githubusercontent.com/assets/5236186/18330814/0919b948-755b-11e6-9c6b-87e1b87c61b3.jpg)
![wowscrnshot_090816_002710](https://cloud.githubusercontent.com/assets/5236186/18330813/09156776-755b-11e6-9ef9-31de64a0b07b.jpg)

**Comment by Shelzo** [comment]
Besten Dank, dann hab ich da nicht aufgepasst und war insgesamt zu spät da. Danke dir trotzdem fürs prüfen! :)

**Comment by dagochen** [comment]
Gern ;)
