### ISSUE TITLE
Die Reflektoren (Ingenieur Schmuck) funktionieren nicht richtig

### ISSUE THREAD

**Issue by SirSoarin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1738]
Welches Verhalten wird beobachtet?
Die Feuer , Schatten und Eisreflektoren werfen keine Zauber , der entsprechenden zu reflektierenden Art zurück, WENN man sie Aktiviert bei einem angefangenen Gegnerischen Cast ODER der Zauber vollendet wurde und "Auf dem Weg" ist.

Wie sollte es sich verhalten?
Die Reflektoren sollten die Zauber IMMER zurückwerfen , unabhängig davon ob der Zauber angefangen oder vollendet wurde , solange er noch im FLUG ist und einen nicht erreicht hat, ist er Reflektierbar.

Schritte zur Reproduzierung
Reflektor Equippen , Aktivieren bevor Gegner zaubert > Zauber Reflektiert > Funktinoniert
          ´´                  . Aktivieren WÄHREND des zauberns > Zauber nicht Reflekiert > Fail
         ´´´                  , Max Range gehen , Aktivieren während der Zauber auf einen zugeflogen kommt > Fail

Zusätzliche Informationen (Screenshots, Videos, etc.)
Für einen "Auf dem Weg" Zauber reflekt habe ich jetzt keinen Beweis auf die schnelle zur Hand, bin mir aber 1000% sicher das es  funktinionierte , da ich es selber schon auf dem Live Server geschafft habe mehrmals.

https://www.youtube.com/watch?v=bFVkQ4NcrtA

 > 2:16 > Priester wirkt Gedankenschlag > Vurtne aktiviert Reflektor > wird zurückgeworfen > Priester resistet seinen eigenen Spell > er macht Eisblock um die Dots zu Purgen.

> 5:47 > Hexer zaubert Furcht > Vurtne aktiviert Reflektor > Hexer feart sich selbst.

> 8:00 > DAS BESTE Beispiel > Magier castet....Vurtne aktiviert Feuerreflektor > zurück an den Absender!
                                            > Magier castet Frostblitz > Reflektor an > Shoop da Whoop!

Vurtne , der wohl mit Abstand beste Magier seiner Zeit und Vorbild vieler Magier hier , war ein exzessiver Nutzer dieser Schmuckstücke , welches man in seinen Videos sehr gut beobachten kann. Die beweiskraft ist eindeutig da eine Legende von World of Warcraft.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?search=reflektor

**Comment by dagochen** [comment]
Ich verweise hier mal an die kürzlichst stattgefundene Diskussion aus dem offiziellen cmangos-Bugtracker:
https://github.com/cmangos/issues/issues/1015

Wem das zu lang ist hier die gekürzte Version:
Reflektoren funktionieren bei uns, wenn sie vor Abflug eines Casts aktiviert werden. Ich habs grad nochmal in jeglicher Kombination getestet.
>Reflektor Equippen , Aktivieren bevor Gegner zaubert > Zauber Reflektiert > Funktioniert (Ja!)
Aktivieren WÄHREND des Zauberns > Zauber nicht Reflektiert > Fail (Funktioniert auch!)
Max Range gehen , Aktivieren während der Zauber auf einen zugeflogen kommt > Fail (Technisch bedingt nicht möglich)

Weiter funktioniert auch folgender Fall:
Reflektor Aktivieren > Zauber fliegt los > Reflektor geht aus > Zauber wird reflektiert und trifft den ursprünglichen Caster

Technischer Hintergrund: Das Problem an der Mechanik ist, dass es keine Möglichkeit gibt, den Clients zu übermitteln, dass der Zauber der da schon auf sie zufliegt auf einmal doch zurückgeworfen werden und keinen Schaden machen soll. Das wird nämlich in dem Moment festgelegt, wenn der Feuerball (z.B.) losfliegt. Aus genau diesem Grund wurde das Ticket von den cmangos-Jungs geschlossen. In dem Ticket sind weiter Videos verlinkt, die zeigen, dass ein solches Reflektieren zu Classic nicht möglich war.

Und wem das auch noch zu lang ist:
Nein. Nein. Nein.

**Comment by hraesvelgr** [comment]
das ging doch beim gottesschild aber auch? oder ist das eine andere mechanik?
