### ISSUE TITLE
Priesterlehrerin Astarii Sternsucher

### ISSUE THREAD

**Issue by chmuibk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1739]
Welches Verhalten wird beobachtet?

Die Lehrerin Astarii Sternsucher http://datenbank.classic-wow.org/?npc=4090 wird von den Schildwachen an der falschen Stelle angezeigt

Wie sollte es sich verhalten?

Verweis auf die korrekte Stelle

**Comment by Slimmer2** [comment]
Wo sollte der Lehrer den stehen?

**Comment by chmuibk** [comment]
Hallo. Angezaigt werden die Priester (alle, nicht nur Astarii) bei wenn man die Schildwachen fragt in der Terasse der Krieger, sie sind aber im Tempel des Mondes zu finden.
