### ISSUE TITLE
provozierte Krits triggern keine Fähigkeiten

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1740]
Welches Verhalten wird beobachtet?
Fähigkeiten, welche durch erhaltene kritische Treffer ausgelöst werden, werden nicht ausgelöst, wenn man sich hinsetzt und dadurch einen Krit kassiert.
Als Beispiel seien hier Blood Craze und Enrage vom Krieger sowie Redoubt und Reckoning vom Pala genannt.

Wie sollte es sich verhalten?
Alle kritische Treffer sollten besagte Fähigkeiten auslösen.

Schritte zur Reproduzierung
Hinsetzen und schlagen lassen :D

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=16487
http://datenbank.classic-wow.org/?spell=12317
http://datenbank.classic-wow.org/?spell=20127
http://datenbank.classic-wow.org/?spell=20177

**Comment by testear** [comment]
stimmt nicht. siehe hier:

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/968

**Comment by dagochen** [comment]
Alle 4 Zauber haben die gleichen Proc-Flags, wodurch sie sich gleich verhalten.

**Comment by hraesvelgr** [comment]
"Can I sit down to force a crit and gain a charge?
Charges will not generate off auto attacks or npc attacks by trying to sit down and force a crit. However, ability crits from physical abilities such as Sinister Strike, Hamstring, Auto-shot, Aimed shot, etc will generate a charge if you're sitting. "

http://blue.cardplace.com/cache/wow-paladin/1069149.htm
