### ISSUE TITLE
Zerschmettern lässt Autohit neu starten

### ISSUE THREAD

**Issue by DerBauer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1743]
Welches Verhalten wird beobachtet?
Wenn man nach einem Autohit  "Zerschmettern" nutzt, dauert es nach dem Cast noch einmal die normale Dauer des "Angriffstempo", um den nächsten Autohit auszuführen.

Wie sollte es sich verhalten?
Wenn man nach dem Autohit "Zerschmettern" nutzt, und die Castdauer kleiner ist, als die Dauer des "Angriffstempo" der Waffe, sollte auf den ersten Autohit der zweite Autohit ohne Verzögerung durch "Zerschmettern" erfolgen.

Schritte zur Reproduzierung
Krieger am besten mit langsamer Zweihandwaffe ausrüsten und am Mob austesten, entweder mit einem Swing timer oder Zeit zwischen den Angriffen stoppen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Patch Notes 1.2.0:
"Warriors will now resume attacking after performing a Slam attack." (http://wowwiki.wikia.com/wiki/Patch_1.2.0)
Der Krieger startet nach dem Zerschmettern keinen neuen Autohit, sondern führt den Vorherigen fort.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=1464

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/Slam?oldid=303321

"While Slam is without a doubt a good ability, being spell with casting-time, it resets the swing timer of your weapon..."

**Comment by dagochen** [comment]
Danke fürs schnelle Raussuchen @testear :+1:

**Comment by DerBauer** [comment]
Keine Ahnung, ob das noch gelesen wird, aber es ging mir um die hier beschriebene Slam Rotation
http://wowwiki.wikia.com/wiki/Slam_Rotation
Ein Video konnte ich leider nicht in den Jahren 2005-06 finden. Ich hoffe, ich starte keine doofe Diskussion, kann mir sonst jemand sagen, wo man das noch gut nachprüfen könnte?

**Comment by dagochen** [comment]
Slamrotation kam erst mit BC, da dort der Spell komplett überarbeitet wurde, eine andere Castzeit glaube ich sogar bekam und dann den normalen Swingtimer auch nicht mehr zurückgesetzt hat. Hier im Bugtracker gab es dazu auch schon mal eine Diskussion: 
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/624

**Comment by DerBauer** [comment]
Alles klar, danke für die schnellen Antworten👍

**Comment by testear** [comment]
Das ist nicht ganz richtig. Slam hat auch in BC noch den Schlagtimer zurückgesetzt, darum sollte man seinen Slam auch immer so timen, dass er direkt nach einem Autohit gecastet wird.  Der MS-Slammer wurde nur eine kompetitive Skillung durch den Debuff der den Schaden auf dem Boss erhöht hat außerdem wurde das Talent für die Reduzierung der Castzeit verbessert. Wohingegen es in Classic so gut wie nix bringt die Castzeit vom Slam zu skillen (1,5Sekunden GlobalCD sorgen dafür dass der einzige Effekt von Slamskillen ein bisschen schnellerer Autohit ist, was wenig bringt da man auf Proccs angewiesen ist). Im Prinzip kann man auf Hordeseite fast genauso spielen wie zu BC Zeiten. Man braucht nur WF, Hoj und/ oder den Schwertprocc - Ohne diese Proccs, allen voran WF, ist es unmöglich die nötige Wut für eine vernünftige Slamrotation aufzubauen. Außerdem ist die Rota extrem schwer aufrechtzuerhalten sobald die Encounter wirklich Movementlastig werden. Achja, man sollte Raidbuffed mindestens auf 40% Crit und 1200 AP kommen und halbwegs mithalten zu können.

**Comment by dagochen** [comment]
Dann kam die Swingtimer Änderung noch ein Addon später erst?

**Comment by testear** [comment]
Genau.  Siehe dazu den aktuellsten SlamPost bei WowWiki. 3.0.2  "Slam now suspends the weapon swing timer rather than resetting it."
