### ISSUE TITLE
[Quest/Gnomeregan] Eine schöne Bescherung

### ISSUE THREAD

**Issue by Apimius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1744]
Wenn ich die Begleitquest in Gnomeregan annehme passiert nichts. Der Goblin bleibt einfach liegen.

Er sollte loslaufen Richtung Ausgang der Instanz

Ich wäre sehr dankbar wenn das gefixt wird

http://datenbank.classic-wow.org/?quest=2904 <- Quest: Eine schöne Bescherung
http://datenbank.classic-wow.org/?npc=7850 <- Kernobee

**Comment by testear** [comment]
Duplikat

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/864
