### ISSUE TITLE
"Steilhanggift" - Questtext falsch

### ISSUE THREAD

**Issue by chmuibk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1746]
Welches Verhalten wird beobachtet?

Beim Quest "Steilhanggift" - http://datenbank.classic-wow.org/?quest=1135 wird für Questgeber Fiora Langohr - http://datenbank.classic-wow.org/?npc=4456 der falsche Text angezeigt:

"Bringt 10 Steilhanggiftbeutel zu Fiora Langohr in Theramore"

Wie sollte es sich verhalten?

Fiora Langorh befindet sich in Auberdine

**Comment by Slimmer2** [comment]
Wie sollte es sich Verhalten?
NPC am Falschen Ort oder Questtext Falsch?

**Comment by Slimmer2** [comment]
Hier mal eine Quelle.
http://wowdata.buffed.de/npc/Fiora-Langohr-4456#comments

**Comment by Slimmer2** [comment]
Bei der Quest http://datenbank.classic-wow.org/?quest=1132 wird man Ingame auch nach Auberdine geschickt und nicht wie es in der Datenbank steht.
