### ISSUE TITLE
AQ40 Ouro Trash

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1747]
Welches Verhalten wird beobachtet?
Wenn man den Boss Ouro getötet hat und einen Tag Später nachschaut ist der Trash von den Boss Respawnt. Wenn man sich dann zu Ouro runterteleportieren lässt, steht man direkt im den Trash und addet diese

Wie sollte es sich verhalten?
Der Trash vor Ouro sollte nach den Bosskill nicht respawnen.

Schritte zur Reproduzierung
Ouro Töten und am nächsten Tag wieder sich runter Porten lassen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by ChichiWarrior** [comment]
Ist mittlerweile mehr Trash der respawnt.
Als letzte Woche jemand hinter C'thun wollte, war der Twins Trash auch wieder da. Selbst habe ich das nicht kontrolliert.

Anmekrung: Wäre nett, wenn der GM den Trash cleared um seine Quest abgegeben zu können und nicht darauf verweist es einfach eine Woche später zu machen.

Gruß

Chichi

**Comment by Slimmer2** [comment]
Evtl hilft das weiter.
Nach dem Kill bleibt man im Kampf.
Evtl. liegt darin der Fehler

**Comment by Horim** [comment]
Der Trash war zwischenzeitlich nichtmehr respawned nachdem C'thun gestorben ist. Ob das so gewollt war ist auch fragwürdig, der Teleport zu Ouru wäre somit Blizzards bester Troll in Classic.
