### ISSUE TITLE
PVP-Items: Gefechts-Tränke auf Horde unter Rang 6 verfügbar

### ISSUE THREAD

**Issue by Jizzl3** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1748]
Bezugnehmend auf den Issue "PVP-Items: Gefechts-Tränke #232" und das Update vom 01.08.2016, sollten die Gefechtspots nur für Spieler erhätlich sein, die bereits den Rang 6 erreicht haben.

**Welches Verhalten wird beobachtet?**

Auf Hordenseite können auch Spieler, die keinen Offiziersrang (< Rang 6) die Pots beim NPC kaufen.
Der NPC heißt Kriegerheld Steinfell <Rüstmeister für Offizierszubehör>. Auf Allianzseite sind die Pots **nicht** mit einem kleineren Rang als 6 käuflich. Dadurch entsteht ein kleines aber dennoch vorhandenes Ungleichgewicht.

**Wie sollte es sich verhalten?**

Horde Spielern mit einem Rang der unter 6 ist, sollten diese Pots nicht zur Verfügung stehen.

**Schritte zur Reproduzierung**

Mit einem Horde Char zum NPC gehen und die Pots kaufen. Habe es mit meinem Horde Char "Jizzle" probiert, der nie Rang 6 erreicht hat. Andere Spieler mit einem ebenfalls zu niedrigem Rang haben mir ebenfalls bestätigt, dass sie die Pots problemlos kaufen können.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links zu den Pots:
http://datenbank.classic-wow.org/?item=18841
http://datenbank.classic-wow.org/?item=18839

Link zum NPC:
http://datenbank.classic-wow.org/?npc=12793

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
quellen?

**Comment by dagochen** [comment]
Brauch man keine Quellen, die NPCs sind vertauscht ;) Der NPC mit Offizierszubehör steht bei der Allianz in der Offiziersmesse (SKANDAL!!!!) und der andere vor der Messe. Bei der Horde ist es exakt andersrum :P Kümmer ich mich drum^^

**Comment by Frostlatte** [comment]
Edit: Sollre es sich dabei nicht wie mit den anderen PvP Items verhalten? Jene können erworben werden, wenn man den Rang inne hat und einmal hatte.  Wenn der PvP Verkäufer entfernt wird, sollte auch gewährleistet sein, dass ehemalige Offiziere die Messe auch weiterhin betreren können?! So war es m.M. nach auf dem Offi auch. Auf unserem Serve ist das meiner Erfahrung nach nichf der Fall.

**Comment by dagochen** [comment]
Klingt plausibel, aber mir wäre eine Quelle von damals lieber ;)
