### ISSUE TITLE
Zul'Farrak Event bleibt hängen

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#175]
Welches Verhalten wird beobachtet?
Das event auf der pyramide, das durch http://datenbank.welli-it.de/?item=8444 gestartet wird, funktioniert nicht. Nachdem die NPCs nach unten zum brunnen sind, bleibt es hängen.
http://datenbank.welli-it.de/?quest=2768 ist deshalb nicht abschließbar.

Wie sollte es sich verhalten? 
Die NPCs, die man gerade befreit hat, müssten einem unten am brunnen nach einer diskussion feindlich gegenüber gesinnt werden.

Schritte zur Reproduzierung:
event machen

Zusätzliche Informationen (Screenshots, Videos, etc.): 
(wie https://www.youtube.com/watch?v=GKgpiBVIxMA#t=7m40s (nicht mehr vanilla))

**Comment by Cleptomaniac** [comment]
hab die quest in der letzten zeit 3 mal mit unterschiedlichen gruppen gemacht und es hat nie funktioniert. kann zwar leider nichts konstruktives zur fehlerquelle beitragen, aber der NPC Sergeant Bly wird nicht feindlich, nachdem man ihn anspricht.
