### ISSUE TITLE
Falle entschärfen buggy

### ISSUE THREAD

**Issue by padomu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1751]
Im PvE:

Fallen entschärfen geht, wenn man den Skill anklickt und dann die Falle.

Bug 1: Rechtsklick geht nicht

Im PvP:

Bug 2: Falle entschärfen per Rechtsklick geht nicht
Bug 3: Falle entschärfen per Skill geht nicht

Es gibt hier nicht viel dazu zu sagen sonst. :) Ich hoffe es gibt den Bugreport nicht schon da der Bug ja sehr bekannt ist. Ich fande nichts.

**Comment by dagochen** [comment]
Bug 1&2 sind keine Bug, das ging in Classic net ;)

Was ist bei 3. genau das Problem? Kommt eine Fehlermeldung?

**Comment by padomu** [comment]
Bitte reopen. Ich habe folgendes getestet:

Fallen entschärfen funktioniert in folgenden Situationen:
Duell mit Horde/ally
Instanzen

Es geht nicht im BG. Ich hab dazu noch n Video wo ich ca. 10 mal entschörfe immer: Fehlversucht, dazu kommt, dass man noch den Rechtsklickbutton hat -> BC Version. Ich kann das Video gerne Raufladen sobalds geht. Beim Rechtsklick kommt: Brauch Entschärfen 300.

**Comment by dagochen** [comment]
Das mit dem Rädchen wurde glaube ich schon mal gemeldet:https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/774

**Comment by padomu** [comment]
Es ist halt schwer zu testen aber ich kenn keinen Schurken [alles BG Rogues]die jemals eine Hunterfalle entschärft haben. Ich probier es aber gern mal aus mit jemandem.
