### ISSUE TITLE
Schwarzer lotus am Naxx Eingang

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1752]
Welches Verhalten wird beobachtet?
der Schwarze Lotus am Naxxramaseingang spawnt unter dem zigurat Portal sodass er nicht lootbar ist

Wie sollte es sich verhalten?
Der Schwarze Lotus sollte direkt auf dem Fundament des portals spawnen und lootbar sein

Schritte zur Reproduzierung
Östliche Pestländer Naxxramas Portal besuchen als Kräuterkundler

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?object=176589

**Comment by dagochen** [comment]
Da der Lotus immer unter dem Naxxeingang nicht anwählbar ist, habe ich ihn mal paar Meter neben den Eingang verschoben.

**Comment by Glenndun** [comment]
Es scheint als hätte das verschieben nichts gebracht.
Der Schwarze Lotus ist weiterhin nicht kräuterbar.

Lustig ist das der Gelbe Punkt beim ranzoomen sogar von der Minimap verschwindet.
https://puu.sh/rw4NL/14b73d5faf.jpg
https://puu.sh/rw4SV/434e2bd626.jpg
https://puu.sh/rw4Tp/1b6b5402cc.jpg

**Comment by ulle182** [comment]
@ Glenndun Kann ich bestätigen, habe am 3.10. (nach dem neuen Update) den Lotus nicht looten können, und beim reinzoomen verschwindet der gelbe Punkt von der Minimap. 

Vor ca. einer Woche (direkt nach dem großen Kräuterpatch) konnte ich den jedoch looten, da stand er ganz normal auf dem gepflasterten Grund am Rand des Naxx Eingangs (ganz normales Verhalten)
