### ISSUE TITLE
Kalteisenhacke

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1756]
Welches Verhalten wird beobachtet?
Dieses Item ist momentan ein worlddrop

Wie sollte es sich verhalten?
Die Hacke sollte nur bei Skelletminenarbeiter Droppen

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Cold_Iron_Pick?oldid=417364

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=1959
http://datenbank.classic-wow.org/?npc=623#drop

**Comment by Ychap** [comment]
Möglicher Fix:
```
DELETE FROM creature_loot_template WHERE item=1959;
DELETE FROM reference_loot_template WHERE item=1959;

INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount)
VALUES (623, 1959, 5, 0, 1, 1);
```
