### ISSUE TITLE
Kopfputzfedern der Totenwaldfelle

### ISSUE THREAD

**Issue by Agorass** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1760]
**Welches Verhalten wird beobachtet?**
Kopfputzfedern können nicht mehr bei Nafien ( 65,8 ) abgegeben werden. Stattdessen vergibt er erneut die Quest Totenwaldfelle des Nordnes, die eigentlich als Vorquest für die Federn dient. Federn können nur noch bei Grazle ( 51,85 ) abgegeben werden. 

**Wie sollte es sich verhalten?**
Federn sollten auch bei Nafien ( 65,8 ) abgegeben werden können und nicht nur bei Grazle ( 51,85 )
Nafien sollte nicht die Quest Totenwaldfelle des Nordens erneut vergeben, wenn diese schon abgeschlossen war.

**Schritte zur Reproduzierung**
Nach farmen von 5 Kopfputzfedern sollte man diese bei Nafien ( 65,8 ) abgeben können.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://fs5.directupload.net/images/160930/525xlxxf.jpg

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
**Nafien** http://datenbank.classic-wow.org/?npc=15395
**Grazle** http://datenbank.classic-wow.org/?npc=11554
**Federn** http://datenbank.classic-wow.org/?item=21377
**Quest** http://datenbank.classic-wow.org/?quest=8466

**Comment by dagochen** [comment]
Schon behoben, nur noch nicht aufgespielt.

**Comment by Slimmer2** [comment]
Label bitte
