### ISSUE TITLE
Gastwirtin Allison in Sturmwind zeigt falsches Auswahlmenue

### ISSUE THREAD

**Issue by Thorval** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1764]
Welches Verhalten wird beobachtet?
Die Gastwirtin [Allison ](http://datenbank.classic-wow.org/?npc=6740) im Gasthaus "Die Güldene Rose" zeigt beim Anklicken ein falsches Auswahlmenue:
Neben dem oberen Symbol für Handeln steht der falsche Text "Ich möchte dieses Gasthaus zu meinem Heimatort machen."
Neben dem unteren Symbol, um das Gasthaus zum Heimatort zu machen, steht der richtige Text "Make this inn my home.", der vielleicht ins Deutsche übersetzt werden könnte.

Wie sollte es sich verhalten?
Beim Anklicken sollte die Gastwirtin neben dem Symbol für Handeln ein Handeln anbieten.

Neben dem unteren Symbol, um das Gasthaus zum Heimatort zu machen, steht der richtige Text "Make this inn my home.", der vielleicht ins Deutsche übersetzt werden könnte.
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)
![allison](https://cloud.githubusercontent.com/assets/22572769/19019958/8d49c490-889a-11e6-8500-f3b7e7639a8e.png)

**Comment by Slimmer2** [comment]
Vorlage wird automatisch eingefügt beim Fehler melden und dann sollte man sie auch benützen.
