### ISSUE TITLE
Schlachtruf erzeugt Aggro

### ISSUE THREAD

**Issue by Reiner88** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1765]
Beispiel: 2 Spieler in einer Gruppe, Spieler A pullt 2 Mobs, Spieler B macht Schlachtruf, Spieler B bekommt die Aggro.

Es sollte keine Aggro erzeugen.

Schlachtruf verwenden.

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://datenbank.classic-wow.org/?spell=6673

**Comment by Slimmer2** [comment]
Bitte Quellen angeben wie es sein sollte

**Comment by Reiner88** [comment]
http://de.wowhead.com/spell=69305/schlachtruf

**Comment by testear** [comment]
bullshit

http://leftoversraiding.org/index.php/topic/856/1/nefarian-phase-1-easy-mode.html

What we do is called Battle Shout tanking. In the main group, you have your #3 Tank(the BS tank), a warlock, and 3 hunters with their pets out. The entire raid stands on the throne of Nef, dps casters in the back, healers in range of the tanks, and all melee at the base of the ramp. Assign healers to your 3 main tanks before hand, so when Nef lands and the 2 tanks leave to start controlling him the healers know who they are and can move into their position while the rest of the raid takes care of mobs. The hunters in the tank group need to make sure their pets are in range of BS before you start to ensure effectiveness.

**Comment by Reiner88** [comment]
Was soll der Tonfall? Ich schieb euch geld in den Hintern und dann so ne Art und Weise.. Tz unfassbar.

**Comment by Slimmer2** [comment]
Welcher Tonfall, ist doch alles normal geschrieben

**Comment by testear** [comment]
Erstmal. Mir schiebst du kein Geld in den Hintern. Das hier ist mein Hobby. Mehr als hier Bugs reporten oder klarstellen und zocken mache ich nicht. Dafür fehlt mir sowohl das Wissen als auch das Können. 
Zweitens: Sehr amüsanten Coming Out für nen Troll. Machs ordentlich oder verzieh dich wieder.

**Comment by dagochen** [comment]
Hallo Reiner,

sorry das ich nicht noch was dazu geschrieben habe und einfach das Ticket zu gemacht habe. Den Quellen von @testear war leider nichts mehr hinzuzufügen. Alle Spieler und Teammitglieder nehmen an dem Classic-WoW-Projekt aus Spass teil und machen dies ehrenamtlich in ihrer Freizeit.

Für die zukünftige Recherche kann ich dir (und allen anderen) folgende Ratschläge geben:
- Bei wowwiki.com die History-Funktion benutzen und zu Beiträgen aus den Jahren 2005 oder 2006 wechseln
- Zauber-IDs wie z.B. bei dem Link von dir (http://de.wowhead.com/spell=69305/schlachtruf) sollten die 30000 nicht überschreiten (mit wenigen Ausnahmen), da eine höhere ID für ein neues Addon steht
- Quellen lassen leichter finden, wenn bei archive.org oder bei der Google-Suche ein Zeitraum eingestellt wird, z. B. vor "1.1.2007"

Viele Grüße
dago

**Comment by testear** [comment]
=( Manche Leute brauchens ehrlich @dagochen

**Comment by dagochen** [comment]
Dont feed the trolls ;) Ich versuchs mir das Trollen abzugewöhnen, da brauchen wir keinen Nachfolger :P

**Comment by Reiner88** [comment]
Wenn ich jemand sagen will, formulier ich das netter und nich so großkotzig, ich bin kein WoW Kiddie, sondern jemand der "versucht hat" den Server mit Bug Report zu supporten.
"Das ist so nicht richtig, wenn du dir folgenden Link mal anschauen magst, dort wird der nutzen von Schlachtruf beschrieben."
So kann (sollte) man das angehen.
Dann wundert euch nicht, wenn dann mal keiner mehr supported. Der Ton macht die Musik.

**Comment by testear** [comment]
Warum sollte ich das tun? Ist weder die Mühe noch die Zeit wert. Was juckt mich was Reiner88 aus dem Internet von mir denkt?

**Comment by dagochen** [comment]
@Reiner88 Mir geht es hier weniger um die Ausdrucksweise, sondern mehr darum das du auch einfach vor deinem Post 5 Minuten in Recherche hättest stecken können. Dann hätte nicht jemand anderes das für dich tun müssen. Im schlechtesten Fall müssen wir Entwickler nämlich die Recherche machen, und jede Minute Recherche ist eine Minute weniger Fehler-Behebung, was letztendlich dazu führt das der Server niemals bugfrei sein würde :( Das Problem ist dabei auch, dass man diese Ratschläge und Erklärungen so oft gegeben hat und immer wieder kommt jemand, und ignoriert alle Vorschläge, Vorlagen und Hilfestellungen. Das dadurch manch eine Diskussion schnell hitzig, Dinge hässlich und weniger nett rübergebracht werden als man es eigentlich möchte weiß vermutlich keiner besser als ich - auf Grund meiner wenig glorreichen Vergangenheit :(

Aber ich möchte dich und alle anderen bitten, weiter Bugs zu reporten, nur so kommen wir voran!
Danke!
