### ISSUE TITLE
Ony Pre (Horde)

### ISSUE THREAD

**Issue by Kreuzfeld** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1766]
ich hänge in der Quest-Reihe fest
nach dem ich bei Myranda der Vettel das Amulett der drachischen Subversion bekommen habe bin ich mit diesem zu Aschenschwinge, habe es benutzt und wollte die Quest abschließen.
das ging aber nicht, ich konnte nicht mit dem Drachen reden und keine Folge-Quests starten.
Auch konnte ich die Quest nicht neu starten durch abbrechen oder entfernen des Amuletts aus dem Inventar, ich weiß nicht mehr weiter.

bitte um Hilfe

Vielen Dank
Kreuzfeld

**Comment by Slimmer2** [comment]
1. Vorlage verwenden, die normal automatisch angefügt wird.
2. Links zur Datenbank
3. Myranda der Vettel ist in der Datenbank nicht vorhanden, sondern Myranda die Vettel

**Comment by Kreuzfeld** [comment]
ja genau um diese Quest geht es

**Comment by Slimmer2** [comment]
Das Item hast du angelegt und im Aschenschwinges Bau benützt?
Bei mir geht es.

**Comment by Kreuzfeld** [comment]
der Punkt is der das ich die Quest abgebrochen habe um diese neu zu starten und ich das Amulett aus meinem Inentar geschmissen habe.
wenn ich jetzt aber wieder zu Myranda der Vettel gehe ich die Quest nicht mehr starten kann

**Comment by Slimmer2** [comment]
Dann erstell ingame ein Ticket das dir ein GM weiterhilft

**Comment by Kreuzfeld** [comment]
ah okay, wusste nicht sicher ob das Ticket System auf dem Server funktioniert

Danke soweit

**Comment by dagochen** [comment]
Ich mach hier dann mal zu ;) Viel Erfolg beim nächsten mal mit der Quest!
