### ISSUE TITLE
Zul Farrak. Der Goblin nach dem Treppenevent sprengt das Tor nicht auf

### ISSUE THREAD

**Issue by DerQuast** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1767]
Welches Verhalten wird beobachtet? 
Der Goblin rennt nach dem Treppenevent nicht zum Tor um davor eine Bombe zu legen um sie aufzusprengen. Er rennt einfach ins Nirvana und das Tor bleibt verschlossen

Wie sollte es sich verhalten?
Wenn man den Boss anspricht soll der Goblin zum Tor laufen eine Bombe davor legen und dann aus der Inztanz rennen

Das wars schon. 
Danke 
DerQuast

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Seraphitas** [comment]
Hallo, leider ist der Bug immer noch nicht behoben. Wir waren gestern ZF aber der Gnom macht noch immer nicht das was er soll :/

**Comment by Bulli** [comment]
Bug ist immer noch nicht behoben :(
