### ISSUE TITLE
Quest NPC (Connor Bach)  nicht vorhanden

### ISSUE THREAD

**Issue by pinfi32** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1768]
Welches Verhalten wird beobachtet?
NPC http://datenbank.classic-wow.org/?npc=5081#starts sollte in SW folgende Quest geben http://datenbank.classic-wow.org/?quest=1301

Wie sollte es sich verhalten?
NPC befinden sich nicht im blauen Eremiten wo er gemäß der Kommentare stehen sollte http://db.vanillagaming.org/?npc=5081#wh-comments

Schritte zur Reproduzierung
Mehrfach gesucht, auch direkt nach Serverneustart aber nie angetroffen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/Connor_Rivers?oldid=341469


Bitte lesen:
https://community.mmobase.de/guides-zu-classic-wow-1-12-1/10128-nur-ein-toter-bug-ist-ein-guter-bug-oder-wie-man-richtig-bugs-reportet.html
