### ISSUE TITLE
Cooldowns: Buffs aus verwüstete Lande

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1771]
Welches Verhalten wird beobachtet?
Wenn man die Buffitems aus den verwüsteten Landen holt und eines davon benutzt, bekommt man eine Stunde CD auf die anderen Buffitems. Nach einem Relog verschwindet der CD und man kann sich theoretisch alle Buffs gleichzeitig haben (meine Vermutung auch buggy Buffstacking da Worldbuff selber Kategorie, vielleicht hat wer von euch eine Quelle dazu für einen zusätzlichen Bugreport).
Wie sollte es sich verhalten?
Es verschwinden keine CDs durch einen Relog.

Schritte zur Reproduzierung
Buffen und reloggen

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=8412
http://datenbank.classic-wow.org/?item=8411
http://datenbank.classic-wow.org/?item=8410

**Comment by dagochen** [comment]
Dachte die überschreiben sich gegenseitig? Ist das überhaupt richtig, dass die einen CD auslösen?

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/Lung_Juice_Cocktail?oldid=354718
http://wowwiki.wikia.com/wiki/Ground_Scorpok_Assay?oldid=292849

ja der CD ist richtig. Ob sie sich den CD teilen sollten erfordert mehr Recherche als ich nebenbei betreiben kann.

**Comment by dagochen** [comment]
Die Cooldowns werden nicht korrekt angezeigt, aber sind da (jedenfalls für den Buff, den man vorher auch genommen hat). Für die anderen Zauber lässt sich das Problem aber gut reproduzieren.

**Comment by Loplin** [comment]
Und wie ist das nun?
Die buffs sollten sich gegenseitig überschreiben?
Oder könnte man theoretisch einen gegenstand nehmen, eine stunde ausloggen und dann einen anderen gegenstand benutzen?

**Comment by dagochen** [comment]
Du nimmst einen Gegenstand, bekommst 60 Min CD. Loggst du dich aus, läuft der Buff und der Cooldown nicht weiter. Loggst du dich wieder ein, läuft beides weiter. Dadurch kannst du garkeinen anderen Buff aktivieren. Bisher laufen alle Cooldowns soweit ich es mir angesehen habe weiter (was für die meisten auch völlig korrekt ist, Salzstreuer, Mondstoff, Arkanitbarren....) aber in diesem Fall natürlich stark ausnutzbar ist. Schau ich mir am Wochenende mal genauer an. Weitere Quellen wären sehr hilfreich...^^

**Comment by Seniorash** [comment]
Der CD läuft nicht nur weiter sondern wird einfach zurückgesetzt

**Comment by dagochen** [comment]
Nein und Ja. Für das, was man vor dem Login eingeworfen hat, hat man auch nach dem neu Einloggen einen CD. Für die anderen Buffs jedoch nicht. Und da liegt der Fehler ;)
