### ISSUE TITLE
Freezing Trap des Jägers - Aktivierung fehlerhaft

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1772]
_Welches Verhalten wird beobachtet?_
Die Freezing Trap des Jägers friert das Ziel innherhalb von 5 Metern sofort / instant ein

_Wie sollte es sich verhalten?_
Die Falle besitzt einen gewissen Timer zur Aktivierung von ca. 1 Sek bevor das Ziel eingefroren wird.

_Schritte zur Reproduzierung_
Duell mit einem Jäger- Falle legen - Aktivierungszeit überprüfen.

_Zusätzliche Informationen (Screenshots, Videos, etc.)_

In dem Video von 2006 sieht man sehr deutlich, dass die Falle das Ziel nicht instant einfriert, sondern erst nach ca. 1 - 1,5 sec.

https://www.youtube.com/watch?v=ACM3yXuz0Hw#t=108.894162

2005.. ein Pet des gegnerischen Hunters läuft in den 5 Meter radius und die Falle löst nicht instant aus, sonder ebenfalls erst nach ca. 1 - 1,5 sec    Video  3:50 folgend

https://www.youtube.com/watch?v=5yURd-g3xRs

und ebenfalls in diesem Video eine Aktivierung von ca 1 - 1,5 sec. nach dem betreten des 5 Meter radius
Video:  1:58    sowie  4:00.

https://www.youtube.com/watch?v=W9zIhXgsgzk

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://datenbank.classic-wow.org/?spell=14311

Da die Fehler der Falle erst kürzlich gefixt wurden, wäre es sehr fair, dies ebenfall richtig zu stellen, da ein 5 Meter Radius mit Instantfreeze besonders im PvP keinerlei Möglichkeiten bietet, der Falle zu entgehen.

Mit besten Dank und Grüßen

Frost

**Comment by soda09** [comment]
Welches Video?

Das was du meinst, kam erst mit dem BC Patch (http://wowwiki.wikia.com/wiki/Patch_2.0.1).

**Comment by testear** [comment]
Jaaah. Postet euer Zeug so, dass wir uns das alles selber raussuchen müssen!

**Comment by testear** [comment]
Wo steht das da im Forum? Und wo ist das Video? Fragen über Fragen.

https://community.mmobase.de/guides-zu-classic-wow-1-12-1/10128-nur-ein-toter-bug-ist-ein-guter-bug-oder-wie-man-richtig-bugs-reportet.html

**Comment by dagochen** [comment]
@soda09 Wo steht in den Patchnotes was dazu, ich kann da nix finden?
@Frostlatte Kannst du vielleicht nochmal nach ein paar Quellen posten?

Wie ich bereits in dem anderen Report sagte, ist der Grund dieses Delays eher die schlechte Internetverbindung und eine andere Tickrate der Server von Blizzard. Die Mangos-Server ticken mit einer Zeit von ca. 0,1-0,2 Sekunden. Sprich wenn man in den Bereich der Eiskältefalle rennt wird der Server spätestens nach 0,2 Sekunden das bemerken und den Zauber der Falle, also das Einfrieren, auslösen. Die Blizzard-Server hatten damals höhere Tickraten, je nach aktiver Spielerzahl. Hinzu kommt das nicht jeder damals DSL + Fastpath oder ähnliches hatte, um flüssig zu spielen und der beschriebene Netcode von WoW nicht auf Genauigkeit ausgelegt ist (wie auch, bei so vielen Spielern). Es handelt sich halt nicht um einen 10-Mann-Counterstrike-Server.

**Comment by Frostlatte** [comment]
So, Nachtrag:

Sorry, der VideoLink ist wohl beim Editieren untergegangen. Ich habe den Post entsprechend überarbeitet und mit weiteren Belegen aus der Zeit versehen.

@dagochen  Ein Delay wäre eine Erklärung, jedoch sind die Videos von unterschiedlichen Servern mit sicher unterschiedlichen Populationen und es ist nach meinen "Zählungen" immer ca. die gleiche Zeit.  
Zudem ist zu sehen, dass die Gegner deutlich den 5 Meterradius der Falle betreten und die Falle sowohl erst 1 - 1,5 sec später und die Gegner deutlich weiter weg vom eigentlichen Auslösepunkt eingefroren werden.. was m.M. nach nicht für ein Delay spricht, sondern einen Aktivierungstimer. 

@soda09  Nein, was Du meinst, ist die Änderung, dass die Falle im Kampf mit einer 2 Sec CastZeit gelegt werden kann... das meine ich nicht.

**Comment by soda09** [comment]
@dagochen 
"Traps can be set while in combat, but require a 2 second arming time."

@Frostlatte 
Ich dachte, dass du die Zeit (s.o.) meinst. 

Ich hab mir jetzt mal das Viedeo rausgeguckt: https://www.youtube.com/watch?v=5yURd-g3xRs
Da wird bei 3:50 das gegnerische Pet instant getrappt und die Falle liegt da auch schon länger.

https://www.youtube.com/watch?v=W9zIhXgsgzk 
1:58 Würde auch sagen, dass es nen kleiner Delay ist. Aber kann hier sehen, was du meinst.
4:00 Die Falle liegt da auch schon länger. Kann also in keiner Art und ein Aktivierungstimer sein.

**Comment by SirBeansen** [comment]
-Naja wenn man sich Frostlattes video anschaut und mal dne kompletten kampf gegen den warri sieht kann man aber auch deutlich erkenenn das der warri lagt und sich hin und her portet...also kann es sehr wohl delay sein.

-Der 2sec aktivierungs timer kam erst mit tbc.

-Und Frostlatte du solltest wissen das es kein 5 m radius ist, sondern ein 2,5m radius. Der durchmesser der trap ist 5m. Vorher lag der radius bei 2m.

**Comment by soda09** [comment]
Ja, wie gesagt:  Der Aktivierungstimer kam mit dem BC Patch. Davor ist nichts davon vermerkt, dass es einen Aktivierungstimer gibt. Nefarian laggt einfach nicht genug :D
