### ISSUE TITLE
Ansturm/Abfangen ignoriert den swing timer

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1773]
Welches Verhalten wird beobachtet?
-Wenn man als Krieger ein ziel schlägt und dann direkt ein anderes zeil anstürmt wird der swing timer ignoriert und man haut direkt nochmal zu.

Getestet mit Zin´rokh 3,80 speed.

Schritte zur Reproduzierung:
Duell machen > ziel mit einer langsamen waffe hauen > dann das gleiche ziel abfangen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Hängt wohl mit dem bug fix von https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/67 zusammen.

http://datenbank.classic-wow.org/?spell=100
http://datenbank.classic-wow.org/?spell=6178
http://datenbank.classic-wow.org/?spell=11578

http://datenbank.classic-wow.org/?spell=20252
http://datenbank.classic-wow.org/?spell=20616
http://datenbank.classic-wow.org/?spell=20617

**Comment by testear** [comment]
Wobei bitte zu beachten ist, dass es völlig richtig ist wenn man den Autoattack startet (Beginn des Kampfes bzw Rechtsklick) der erste Hit sofort kommt.

**Comment by Seniorash** [comment]
Kamst du ein Video hochladen? Am besten mit Swing Timer addon. Ich kann das nicht reproduzieren

**Comment by Horim** [comment]
Kann ich soweit bestätigen, auch wenn es beim charge etwas schwierig zu testen war, da man dafür ooc sein muss.

**Comment by Horim** [comment]
Hierfür eine Quelle zu finden halte ich für unmöglich.
Es gibt keine so alten Videos in denen man so ein Verhalten getestet hat oder sehen könnte.
Und eine Quelle a la wowwiki wird sicherlich nicht schreiben: 
- Charge/Intercept does not reset the swingtimer oder
- Charge/Intercept resets the swingtimer

**Comment by SirBeansen** [comment]
Der bug ist ein folge Fehler durch einen anderen charge bug den ich mal reportet habe. Damals konnten kriegen während des anstürmen obwohl sie 15m weg waren schon einen auto attack machen und dann wenn sie am Ziel waren noch einen, weil oft der swing timer bis dahin ressetet war. 
Anscheind wurde das sehr unschön gefixt und einfach nur ein reset des swing timers eingebaut wenn man charge, was uns zu dem aktuellen problem führt.

Siehe https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/67

**Comment by Horim** [comment]
Merke es erst jetzt: 

_Damals konnten kriegen während des anstürmen obwohl sie 15m weg waren schon einen auto attack machen und dann wenn sie am Ziel waren noch einen, weil oft der swing timer bis dahin ressetet war._ 

Kann eigentlich nicht sein, weil der Charge nur 1 Sekunde geht und keine (2h)Waffen mit so schnellen Swingtimer existieren. Scheint eher, das der Charge/Intercept schon die ganze Zeit den Swingtimer resetet hat und es nicht aufgefallen ist, bzw. es wurde nicht gemeldet.

**Comment by testear** [comment]
Das galt nur fur Charge mit Slow-Effekten.

**Comment by SirBeansen** [comment]
Der Charge geht nicht immer nur 1 Sekunde. Kommt auf die Distanz und den Weg an,sowies ob du von einem snare effekt betroffen bist. 
Aber das könnte Der Grund sein warum der Stun effekt in den videos immer mal direkt oder Später kommt, weil das Spiel eventuell den Weg so berechnet das der Stun effekt immer zum gleichen ergebnis kommt, damit du nur "1 sekunde" anstürmst.

**Comment by Horim** [comment]
Der Glitch ist bekannt, es stand nur nichts davon in dem von mir zitierten Abschnitt...
Mein Fehler ;)

**Comment by SirBeansen** [comment]
Kann man sich das nochmal ansehen? War der Meinung das war mal gefixt, aber der Fehler ist seit längerem schon wieder vorhanden.

**Comment by Horim** [comment]
Oder generell die Probleme mit der Charge Mechanik 🤦🏼‍♂️

**Comment by dagochen** [comment]
Wenn denn jemand weiß was genau wie falsch ist und wie es genau richtig ist, ja. Aber da jeder was anderes in den Bugreports dazu geschrieben hat bleibt das so wie es ist....
