### ISSUE TITLE
Abfangen Damage kommt zu spät

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1775]
Welches Verhalten wird beobachtet?
Wenn man ein Ziel abfängt kommt der Schaden durch abfangen zu spät. Erst bei erreichen beim Ziel umd gleichzeitig mit dem autoattack.

Wie sollte es sich verhalten?
Der abfangen Schagen sollte schon deutlich früher sein. Bevor man das ziel erreicht. Bei uns ist es sogar so das der autoattack Schaden vor dem abfangen Schaden im kampflog auftaucht.

Zusätzliche Informationen (Screenshots, Videos, etc.)

https://www.youtube.com/watch?v=-eZ6vAQK1Sc 

Ab minute 2 kann man sehr gut in pixliger form erkennen, dass  das die 58 abfangen schaden schon während des anstürmens gemacht werden.

**Comment by Badorr** [comment]
Das ist vielleicht ein bisschen nitpicking, aber (da es sich ja um auch um ein eher triviales Thema handelt): Bei dem Krieger im Video procct ein paar mal Second Wind. Das ist aber ein BC Talent, d.h. das Video wurde erst nach dem Pre-BC Patch aufgenommen und nicht mit Patchstand 1.12.

**Comment by SirBeansen** [comment]
Achso okay danke, darauf hab ich nicht geachtet...suche dann nochmal ein anders raus

**Comment by dagochen** [comment]
Naja wenn die Swingtimer-Sache geändert wird, dann sollte das hier auch korrekt sein.

**Comment by SirBeansen** [comment]
wieso sollte es dann auch korrekt sein?

**Comment by dagochen** [comment]
naja wenn der hit autohit sich verzögert, ist er danach hoffentlich nach dem abfangen?

**Comment by SirBeansen** [comment]
wieso sollte er verzögert sein wenn der autohit noch gar nicht gelandet wurde und man noch gar kein damage gemacht hat? 

In viele videos sieht man das der abfangen damage deutlich vor dem erreichen des Zeils gemacht wird und hier erst beim ankommen an dem gegner.

Der bug verhindet das zb das abgefangene Schaf nicht weg blinzeln kann um den auto attack zu umgehenm, wenn es sich um einen mahe handelt. 
Der bug verhndert das man ein totem abfangen und killen kann ohne einen autohit zu verbrauchen.

https://www.youtube.com/watch?v=ILNnSAFU32Y gut zu sehen ab minute 6 das der abfangen schaden früher kommt als bei uns.

**Comment by testear** [comment]
Video 2011 gilt nicht. Gilt bei mir schließlich auch nicht.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/67

**Comment by soda09** [comment]
Wenn Abfangen den Swingtimer nicht mehr zurücksetzt erreicht das doch genau das, was du forderst: Dmg vom Abfangen.... Pause.... Autohit

**Comment by SirBeansen** [comment]
Nein du versteht nicht den sinn des abfangen damages. Der soll nicht erst dann dmg machen wenn man am ziel dran  sondern schon vorher. Welchen unterschied dieser bug aus macht hab ich oben beschrieben....nur ist dieser bug natürlich nicht super wichtig. Doch trotzdem kann ein dev das ja fixen wenn er lußt dazu hat?

Wenn du zb ein totem abfangen würdest und der swing timer ready ist dann würdest du anstatt nur den 65 abfangen damage auch noch ein auto hit verschwenden auf das totem.

**Comment by Horim** [comment]
Der Fehler besteht nicht darin das der Schaden zu spät kommt, sondern das der Abfangen Effekt zu spät einsetzt. Das selbe gilt bei Ansturm, in beiden Fällen sollte das Ziel bereits bei Nutzung der Fähigkeit gestunnt werden und nicht erst wenn man das Ziel erreicht:

https://www.youtube.com/watch?v=gUPkQUMoSgU : Es ist mehrfach erkennbar das die Ziele gestunnt werden bevor diese erreicht werden. Bei 3:06 wird der Hunter direkt durch Ansturm gestunnt, bei 3:20 direkt durch Abfangen.

Dieser Bug ermöglicht es den Zielen sich noch während des Abfangens/Ansturms zu bewegen oder gar Skills zu nutzen. Es ist schon mehrfach im PvP vorgekommen das ich trotz Max-Range (25m) Charge auf halbem Wege einen Streuschuss (21m) kassiere, obwohl es gar nicht möglich sein sollte, da ich bei Charge-Beginn nicht in Range bin und mein Ziel sofort gestunnt sein sollte. Gleiches gilt für Zauber die dadurch zu spät unterbrochen werden: Solange man nicht in Melee-Range ist, kommt kein Stun und der Cast geht einfach durch (Sheep ftw -_-').

**Comment by SirBeansen** [comment]
Das was du beschreibst ist nicht richtig, auch wenn die Quelle jetzt fehlst ist es möglich doppel zu cc´en. In dem falle scatter shot + dein charge, da viele CC´s einen delay haben. Ausderdem denke ich nicht das es den zu späten damage durch abfangen behebt.

**Comment by Horim** [comment]
Der Damage von Abfangen kann erst autreten wenn Abfangen wirkt, inwiefern glaubst du, das es hierbei keinen Zusammenhang gibt ? =)

**Comment by testear** [comment]
Viel interessanter finde ich gerade eigentlich dass der Jäger bei 1:49 die Falle legt und der Krieger die Falle für 1 Sekunde sieht. Ich bin mir ziemlich sicher, dass das auf Nefarian nicht so funktioniert.

**Comment by Horim** [comment]
Geb ich dir Recht, aber das kann daran liegen das dies nicht Patchstand 1.12 war.
Die zweite Falle kann man z.B. gar nicht sehen.

**Comment by SirBeansen** [comment]
Das ist das problem...man weiß nie wann die szenen aufgenommen wurden und auch in classic gab es immer bugs die zb durch hot fixes behoben wurden, die aber nie von blizzard gepostet wurden. Eventuell sollte man die falle sehen und das er später die nicht sehen konnte war nur ein bug?

**Comment by testear** [comment]
Ich werd auch keinen Report nur auf Grundlage einer Szene in einem Video eröffnen.

**Comment by hraesvelgr** [comment]
@horim es gibt aber eben auch videos, die zeigen, dass der stun erst am ende des chargens kommt. zb, https://youtu.be/-eZ6vAQK1Sc bei 0:45, als er den mage ancharged.

**Comment by Horim** [comment]
Und das beweist erstmal genau so wenig wie mein Video, nur das man bei zu späten stun noch von Latenz oder Lags reden kann. Bei sofortigem stun ist es .... der Server der zu schnell reagiert?

**Comment by SirBeansen** [comment]
Naja Horim du hast 1 video gepostet von den selben Spieler, während wir verschiedene warry video´s verlinkt haben die den späteren stun beweißen. Auserdem kann man anhand des gear standes immer hin ein Zeitraum bestimmen.

**Comment by soda09** [comment]
Man sieht ja wohl, wenn ein Krieger den Jäger anchargen will. Daher kann man das mit ein bisschen Skill provozieren, indem man dem Krieger entgegenläuft, bis dieser in Scatterreichweite ist. Jetzt drücken der Krieger und der Jäger gleichzeitig auf Charge bzw. Scatter und siehe da: beide sind CCt... Ist auch kein Hexenwerk aber klappt nicht immer.
Läuft beim Charge aufn Mage übrigens genauso. Manche Mages bekommen den Blink sogar so hin, dass sie nichtmal den Whitehit nachm Charge abbekommen.

**Comment by Horim** [comment]
Soda09 es tut mir leid, jedoch hast du mein Problem beim Scatter nicht verstanden. Es geht mir nicht darum, das beides gleichzeitig eintritt, weil beide in range zueinander stehen, sondern um den Fall, in dem ich aus 25m Charge und de facto nicht in Range für Scatter bin.

**Comment by Horim** [comment]
Beansen ich habe das erste Video genommen, das ich für 2006 gefunden habe. Und darin wird deutlich das der stun nicht erst bei erreichen Triggern sollte / bei uns zu spät triggert (wann genau ist ein anderes Thema). Um das Gegenteil zu beweisen müsste in jedem Video und jeder Charge Szene der stun erst später einsetzen, was aber de facto nicht zutrifft. Das es in einzelnen Szenen von einzelnen Videos anders ist, kann ich nicht ändern. Nur fällt es mir dahingehend leichter die Situation als Lag oder Delay zu deuten, weil diese nicht immer auftritt. Wie bereits oben beschrieben finde ich es durchaus interessanter wenn das Gegenteil eintritt: Wie kann es kommen das der Stun quasi direkt getriggert wird? Lag oder Delay sicher nicht, und überschnelle Serverreaktion halte ich ebenso für unwahrscheinlich... ist es wirklich reiner Zufall das es immer wieder solche Szenen bei 2006er Videos gibt?

**Comment by Seniorash** [comment]
sorry die frage aber: welche  auswirkungen hat dieser "bug" im spielgeschehen?

**Comment by dagochen** [comment]
wär gut wenn ihr die diskussionen außerhalb des bugtrackers abhandeln könntet, weil ihr hier alle probleme bzgl. charge und abfangen vermischt, durcheinander bringt und es für uns unmöglich ist, wichtiges aus dem ganzen geschwafel rauszufischen :( setzt euch in goldshire ins gasthaus, redet miteinander und wenn ihr dann wisst, was falsch ist und wie es richtig sein soll, meldet euch bitte wieder ;)

**Comment by soda09** [comment]
Das ist ein Video von 2006, das 2012 neu hochgeladen wurde: https://www.youtube.com/watch?v=QAk1r4ax3gA

Es zeigt (ab ca. 0:38), dass der Schaden von Abfangen noch außerhalb der Meelerange, evtl. mit Serverlags sogar kurz nach Cast der Fähigkeit, das Ziel trifft.

**Comment by Horim** [comment]
In Beansens Video (https://www.youtube.com/watch?v=ILNnSAFU32Y) bei 6:07/6:08 ist bereits zu erkennen das der Damage kurz vor dem Stun kommt (ca. 1-2 "Schritte" vorher).
