### ISSUE TITLE
[Klasse/Krieger] Abfangen/Ansturm Stun setzt zu spät ein

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1777]
In Anlehnung an #1775

**Welches Verhalten wird beobachtet?**
Der Stun-Effekt von Abfangen und Ansturm setzt erst ein wenn das Ziel in Melee-Range ist. Das Ziel kann während des "Sprints" noch Zauber wirken und sich bewegen. Dadurch tritt auch der Schaden von Abfangen zu spät auf.

**Wie sollte es sich verhalten?**
Der Effekt sollte direkt bei Wirken des Zaubers einsetzten.

**Schritte zur Reproduzierung**
Ziele Abfangen/Anstürmen und auf die Debuffleiste + Bewegung/Zauber des Ziels achten, vor allem im PvP sehr leicht zu sehen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://www.youtube.com/watch?v=gUPkQUMoSgU : Es ist mehrfach erkennbar das die Ziele gestunnt werden bevor diese erreicht werden. Bei 3:06 wird der Hunter direkt durch Ansturm gestunnt, bei 3:20 direkt durch Abfangen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
- http://datenbank.classic-wow.org/?spell=11578 Ansturm
- http://datenbank.classic-wow.org/?spell=7922 Ansturm Stun
- http://datenbank.classic-wow.org/?spell=20617 Abfangen
- http://datenbank.classic-wow.org/?spell=20615 Abfangen Stun

Edit: Melees können durch diesen Bug sogar noch hits durchbekommen, obwohl diese gestunnt sein sollen. Viele Grüße an meine Roguefreunde aus vielen Duellen :P

**Comment by SirBeansen** [comment]
Das wurde glaube ich so mit absicht gemacht da sonst der warry sonst nie die richtige Ziel position angestürmt hat.  Eigentlich ist der spätere stun ja sogar ein vorteil, aber das vohrige Anstürmen war einfach nicht gut.

Hier nochmal ein video wie es wohl sein sollte: https://www.youtube.com/watch?v=1qHsxM4lz2E

**Comment by Horim** [comment]
Bei 2:43 kann ich kein Delay zwischen Charge-Beginn und Charge Stun erkennen. Bei 5:03 wird der Nachtelf im Sprung gestunnt, im Sprung, auch wenn die Szene leicht laggy ist.

Bezüglich des "Vorteils" durch zu späten stunn, verweise ich auf 4:54. Bitte ganz genau angucken...
Ja es ist möglich, das das Target während des Charges aus dem Stun kommt und sich bewegt, aber wie man sieht charged der Charakter auch an die neue Position. Kein Spaß, guck dir genau an wie der Charge ca. 3-4 m weiter geht als die Position des Hunters bei Chargebeginn.

Das ist jedoch sicherlich schwieriger zu implementieren, da es auf den ersten Blick kein 0815 Pathfinding mehr ist.

**Comment by SirBeansen** [comment]
Meiner meinung nach ist auch da ein kleiner delay drin (kann mich auch täuschen) das es eventuell weg abhängig sein könnte.

Und das mit dem ziel richtig nach chargen ist auch richtig wie im video, weil jeder warry charge sonst durch snare effekte ausgekonter werden würde.

Den vorteil den ich meinte durch einen späteren Stun ist der, dass du dann die volle 3 sec stun dauer benutzen kannst, anstatt die nur 2 sec. Besonders bezogen auf dem dimishing return.

Wie gesagt finde ich den aktuellen warry charge/intercept schon sehr gut und nah an classic like auch wenn ich die videos dazu sehe, weil es vorher sehr viel schlimmer war.

**Comment by Horim** [comment]
Die 5. Minute finde ich witzig, da diese anscheinend auch laggy ist. Der Charge beginnt im Sprung des Ziels, das Ziel landet und wird gestunnt auf die Position im Sprung zurückgesetzt ^^

Scheint eher ein Lag des Ziels zu sein, da es erst nach kurzer Zeit an der richtigen Position (im Flug) zurücksetzt. Dennoch eine schöne Szene im Rahmen der verpixelten 2006 Videos ^^

**Comment by SirBeansen** [comment]
Stimmt da hast du recht, der warri hat auch nen gelben latenz balken. Kann schon richtig sein das der Charge effekt hier auf dem sever einfach doch noch zu spät kommt, owbohl ich meine es wurde extra mal geändert.

**Comment by Horim** [comment]
Ich frag mich was für ne Quelle von 2006 ich finden soll, die nicht vollkommen verpixelt ist... -_-'

**Comment by Horim** [comment]
http://wowwiki.wikia.com/wiki/Charge?oldid=304465 October 31, 2006
_While Charge is extremely fast, the one-second stun only keeps the target in place long enough for you to get there. It's useful to interrupt spells when running into a battle that's already taking place, but if ..._
Bei uns gibt es keinen Interrupt da man zu spät stunt und "only keeps the target in place long enough for you to get there." ist wirklich interessant, wenn man erst stunt sobald man das target erreicht.
_Charge is currently glitchy in respects to using it while under the effects of a movement-altering skill. If you are moving slower than normal (any slowing effect, such as Daze) and/or your target is moving faster than normal (on a mount), you will tend to either go farther or not far enough. This is usually seen in PvP battles where overshooting a target and not getting your hit in means death. This glitch also affects Intercept._ 
Wenn sich das Target ohnehin bewegen kann, weil man erst bei Ankunft stunt, dann ist dieser Hinweis irwie sinnfrei.

**Comment by dagochen** [comment]
@Horim 
Das was du da beschreibst war genauso, wie in deiner englischen Quelle beschrieben auf Nefarian, und wurde aufgrund von Reports geändert!

**Comment by soda09** [comment]
Als Ork kann man dem Chragestun ja wiederstehen. 
Wenn man angecharged wird, und dem Charge wiedersteht, kann man einfach ganz normal weiterlaufen. Der chargende Krieger befindet sich dann NICHT an dem Spieler dran. Ich hatte daher immer den Eindruck, dass der Server den Stun schon zum Startzeitpunkt berechnet.

**Comment by Horim** [comment]
Soda09 auch hier muss ich dir widersprechen:
Wenn der Stun widerstanden wird ist es egal wann dieser triggert, da dieser überhaupt nicht greift, egal ob zum Beginn oder Ende vom Charge, das Target wird immer weiterlaufen. Der Unterschied betrifft die Fälle in denen kein Resist stattfindet:

- Zauber die nicht unterbrochen werden
- Meleetargets die sogar noch Meleehits durchkriegen, z.B.:
  Duell gegen Rogues, man schafft es irwann mal ein Intercept durchzubringen und kassiert noch 2 Meleehits vom Rogue, bevor dieser gestunt wird, weil der Stun erst in Meleerange greift. Gleiches gilt für Hunter Wing Clip etc., Sachen die eigentlich nicht gehen sollten, da das Target gestunt ist.
- Das Scatter-Problem, wenn man auf Maxrange charged

**Comment by Horim** [comment]
@ Dago
Ich muss einfach mal so dreist fragen: Auf welcher Basis wurden die Reports geschrieben?
Soweit ich weiß, müssen wir erst zeigen das es ein Bug ist, bevor man überhaupt an einen Fix denken kann. Und soweit ich es sehen kann, war das Verhalten als solches kein Bug und ich hege starke Zweifel daran, das es damals eine zuverlässige Quelle zu dem Thema gab. 

Unzufriedenheit das Targets beim Chargen weglaufen, weil Slow oder Stunresist sehe ich nicht als haltbare Begründung an, schließlich sind wir hier nicht bei Wünsch dir was. Die Targets laufen auch jetzt noch weg, wenn der Stun widerstanden wird oder der Krieger beim Chargen verlangsamt ist, nur das man jetzt noch zusätzlich keine Casts unterbricht und das Ziel noch Styles/Autohits ausführen kann.

PS: Das soll kein Troll sein, ich verstehe nur nicht warum es damals einen "Fix" gab, wenn es allem Anschein nach kein Bug war.

**Comment by Seniorash** [comment]
#434

**Comment by Horim** [comment]
Dem ist zu entnehmen das die Aussage _"While Charge is extremely fast, the one-second stun only keeps the target in place long enough for you to get there."_ bei uns nicht zutraf, da die eine Sekunde nicht ausgereicht hat um das Ziel zu erreichen. Stellt sich dann die Frage ob der Charge-Sprint zu langsam war oder der Input Lag einen Strich durch die Rechnung macht. 

Schwieriges Thema, von daher wieder im Bereich der Mutmaßung.

Bei uns funktionieren jedoch weder:

_While Charge is extremely fast, the one-second stun only keeps the target in place long enough for you to get there._ 

noch

_It's useful to interrupt spells when running into a battle that's already taking place, but if ..._

der Glitch hingegen funktioniert, wie es soll.

Für beides habe ich eine Quelle mit Zeitstempel aus 2006 gefunden. Hierbei ohne lagbehaftete oder verpixelte Videos.

Und für die Videos gilt ohnehin: nur weil man etwas im Video nicht sieht, beweist es nicht das es nicht existiert hat. Hier haben wir Videoszenen in denen mal "zu spät" oder "zu früh" gestunnt wird, wobei man "zu spät" begründen kann, "zu früh" bleibt ohne Begründung.

**Comment by Seniorash** [comment]
Ist es überhaupt richtig, dass charge durch verlangsamende Effekte verlängert wird? Das war eins der Probleme.

**Comment by Horim** [comment]
Ja Korash, das wurde erst mit 2.1 geändert. Diesen Glitch muss es geben.

**Comment by soda09** [comment]
Das ist ein Video von 2006, das 2012 neu hochgeladen wurde: https://www.youtube.com/watch?v=QAk1r4ax3gA

Es zeigt (ab ca. 0:38), dass der Stun erst in Meelerange rausgeht. Bringt das vllt Licht ins Dunkele?

**Comment by Horim** [comment]
Bringt leider so viel wie die bisherigen Videoszenen: Mal kommt der stun quasi beim Chargen, mal erst am Ende. Eine wirkliche Konsistenz ist hierbei nicht zu erkennen. Wie in anderen Videos sind auch hier eine Vielzahl an Szenen laggy. Deine Szene bei ca. 40 Sekunden ist auch hart laggy, was man am Stance-Dance nach dem Charge sieht.

Bei 1:33 haben wir einen direkten stun, bei 2:45 vor Meleerange, bei 4:37 ist das Target nichtmal in LoS und wird definitiv lange vor Meleerange gestunnt. 6:19 auch früher, bei 9:46 kommt der stun viel zu spät, weil die Szene unfassbar laggy ist.
-> Genau so hilfreich wie die bisherigen Videos: Verpixelt, laggy und inkonsistent
-> Meine Frage bleibt: Wieso kommt der stun teilweise deutlich früher? Später können auch Lags sein, aber früher?

**Comment by soda09** [comment]
Bei 1:33 wird angestürmt. Das ist nen anderer Skill. Da muss man evtl. unterscheiden.
2:45 ebenso...
4:37 ... ka was das ist :D
6:19 da kommt es früher, haste Recht
Aber dann darf man nichts ändern, bis es einen vernünftigen Beweis gibt, weil, wie du sagst, die Videos ungeeignet sind. Vieles ist nur leider nicht aufgeschrieben und dann bleiben einem "nur" die Videos. Falls man doch etwas in Foren findet muss man da auch aufpassen, weil Viele 2006 das Spiel immernoch nicht verstanden haben.

**Comment by SirBeansen** [comment]
Ja ich stimme Horim da zu das man nicht wirklich sagen kann, wann der Stun denn nun kommen soll. Und wenn man den Stun nun wieder früher macht, chargen bald die ganzen warry´s wieder nur daneben.

Die Szene bei 4:37 ist classic like, da die Bäume in classic nicht LoS geblockt haben. (Nur richtige Wände, Zäune und sowas)  Aber wer will sowas spielen, wo man nichtmal mehr sehen kann ob man gerade von der anderen Seite gebruzelt wird.

**Comment by Horim** [comment]
Hatte gehofft, das das Wiki relativ eindeutig ist: 
http://wowwiki.wikia.com/wiki/Charge?oldid=304465 October 31, 2006

_While Charge is extremely fast, **the one-second stun only keeps the target in place long enough for you to get there.** It's useful to interrupt spells when running into a battle that's already taking place, but if ..._

Die Frage, die sich dann stellt: Warum hat es vorher nicht gepasst? Die eine Sekunde hat bei uns anscheinend nicht ausgereicht um unter "Normalbedingungen" (ohne Slow etc.) beim Target anzukommen. Der Charge/Intercept-Glitch aus dem Wiki funktioniert exakt wie es sollte:

_Charge is currently glitchy in respects to using it while under the effects of a movement-altering skill. If you are moving slower than normal (any slowing effect, such as Daze) and/or your target is moving faster than normal (on a mount), you will tend to either go farther or not far enough. This is usually seen in PvP battles where overshooting a target and not getting your hit in means death. This glitch also affects Intercept._

**Comment by hraesvelgr** [comment]
also ist es bei uns blizzlike?

**Comment by Horim** [comment]
Der Glitch ja, aber der Stun nicht. Schließlich werden unsere Targets nicht gestunt bis wir da sind, sondern gestunt sobald wir da sind.

**Comment by soda09** [comment]
Habs einige male ausprobiert. Der Stun setzt für das Target immer während des Charge ein. Der Debuff kommt manchmal etwas zu spät aber wenn man jemanden anchraged, kann dieser Spieler schon während des Chargens keine Fähigkeiten mehr ausführen oder sich bewegen und nicht erst, wenn der Krieger "an ihm dran steht". 
Und da DoppelCC anscheinend möglich war (siehe Beansens Video im Forum) ist es hier wohl so, wie gewollt, dass man während des Charges noch sheepen, etc kann. Wenn man das Sheep verhindern will, sollte man ggf. nicht 0.1 Sek bevor der Cast beendet ist anchargen.

**Comment by Horim** [comment]
@ Soda : 
_Der Stun setzt für das Target immer während des Charge ein. Der Debuff kommt manchmal etwas zu spät aber wenn man jemanden anchraged, kann dieser Spieler schon während des Chargens keine Fähigkeiten mehr ausführen oder sich bewegen und nicht erst, wenn der Krieger "an ihm dran steht"._ 

Merkwürdig das der Stun bei Maxrange Charge/Intercept meist erst nach dem Autohit (in Meleerange) im Kampflog aufgeführt wird. 

_Wenn man das Sheep verhindern will, sollte man ggf. nicht 0.1 Sek bevor der Cast beendet ist anchargen._

Alle Spells die weniger als 1 Sekunde übrig haben, werden nicht gekickt, weil es eine Sekunde dauert in Meleerange zu kommen. Somit muss man zum Interrupten von 1,5 Sekunden Casts in der ersten halben Sekunde reagieren.  Im Klaxtext: deine 0,1 Sekunden sind in der Praxis 1,0 Sekunden.

"einige male ausprobiert" scheinen mir deutlich zu wenig und niemals auf maximaler Reichweite.

**Comment by soda09** [comment]
Manchmal, wenn ich sterbe und ziemlich viel Dmg kassiere ( z.b. Mortal Strike und Hinrichten) steht das nicht´mal im Kampflog. Ich verlasse mich da nicht so drauf, was da wann steht.

habs auch auch Maxrange ausprobiert....

**Comment by SirBeansen** [comment]
Sodas09

Das mit dem Doppel CC und dem delay ist halt nur eine theorie und muss nicht wirklich so stimmen.

Horim

Das manchmal der Stun im kamplfog später, erst nach dem autoattack angezeigt wird, liegt an dem BUG das krieger noch immer während des chargen zu hauen (nicht immer). Wurd auch schon neu reportet.

Ich stimme Horim zu das der Stun hier wohl zu spät kommt, aber sollte er nicht direkt mit wirken der Fähigkeit eintreten. Sieht man auch in den videos das die Krieger immer erst ein paar Schritte gehen bis der Stun effekt eintrifft.

https://www.youtube.com/watch?v=NzA_viBDly4 ab minute 3:55. Da stürmt der Kriger gerade ein Ziel an und der Stun effekt auf dem Gegner läuft dann aus als er erst am Ziel dran ist, was hier auf dem Server gar nicht möglich ist, da der Stun effekt deutlich später kommt.

**Comment by Horim** [comment]
Der Eye-Beam von großen Augen in P2 von C'thun ist übrigens auf Max-Range auch nicht kickbar, dank der vorliegenden Problematik.

**Comment by Kraftprotz** [comment]
wie closed???

**Comment by Loplin** [comment]
Es gibt für Intervention einen Sammelthread
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1778

Darum is der hier closed, wird aber noch genutzt um das oben beschrieben Thema zu diskutieren

**Comment by Horim** [comment]
Kann mir jemand sagen wie lange der "Sprint" von Charge/Intercept genau dauert?
Die derzeitige Funktion (Stun am Ende) ist definitiv nicht richtig. Wenn wir wegen #434 unsere Targets in der Zeit nicht erreichen konnten, kann man einfach die "Sprint"-Zeit nehmen und den stun-timer entsprechend setzen, damit der stun beim Ziel ausläuft.

Zum Beispiel: 1,3 Sekunden "Sprint"-Zeit -> stun setzt nacht 0,3 Sekunden ein und läuft bei Erreichen des Ziels aus

Bringt halt nichts das timing anhand von 2006er Videos abzuschätzen.
Wenn jemand verlangt das anhand der Videos exakt zu beweisen... naja s.o. das wird nicht zielführend sein. Die Begründung "Alles bleibt wie es ist, weil keiner zeigen kann wie genau es sein sollte" finde ich mehr als fragwürdig, wenn offensichtlich ist, das es hier nicht richtig funktioniert.

Das Wiki Zitat (_While Charge is extremely fast, the one-second stun only keeps the target in place long enough for you to get there. It's useful to interrupt spells when running into a battle that's already taking place, but if ..._ ) ist das einzige was hierbei deutlich ist und ich sehe keine Abweichung vom Wiki wenn _mein Vorschlag_ umgesetzt wird. Schließlich würde der Charge dann genau den Angaben aus dem Wiki entsprechen. Für Intercept müsste man es dann nur konsequent übernehmen.

**Comment by SirBeansen** [comment]
Horim ich stimme dir zu das der Stun zu spät kommt, aber ich bin mir zu 100% sicher das der Stun nicht direkt kommt so wie du es gerne hättest. Es ist ein minimaler delay drin. 1-3 Char schritte, was man auch in deinen videos erkennen kann. Einfach bei deinem ersten video die video geschwindigkeit auf 0.25 setzen.

Wäre der delay nicht vorhanden, dann wäre doppel Charge zweier warris nicht mehr möglich, was aber zu classic ging. 
Hier ist der delay oder wie auch immer das programiert ist...halt zu spät.
Denke der Fix wird eventuell etwas mehr Zeit beanspruchen, weil duch den früheren stun, der Warri die gegner nicht mehr richtig ancharged und nicht wieder 5m hinter ihm steht.
