### ISSUE TITLE
AQ20: Rajaxx Event

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1780]
Welches Verhalten wird beobachtet?
Wenn man eine Add Welle Down hat kommt man aus den Kampf. Und die Nächste Welle kommt auch nicht instant sobald eine Tod ist, sondern es vergeht eine gewisse Zeit.

Wie sollte es sich verhalten?
Man sollte Zwischen den Add Wellen nicht außer Kampf kommen.
Sobald eine Add Welle down ist, sollte die Nächste adden bzw. der Boss nach der Letzten.

Schritte zur Reproduzierung
Event starten und Adds töten

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=dy3qwDueC0U
https://www.youtube.com/watch?v=Vpjl7KnOu-Q

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Loplin** [comment]
Danke für den report wurde auch mal zeit :)
Nachdem nun quellen da sind, könnte sich mal ein GM dazu äußern ob das rezzen/trinken zwischen den wellen nicht vorgesehn ist und als abuse gilt?

**Comment by Slimmer2** [comment]
Das dies Buguse ist sollte klar sein! Da es zudem den Event/Bossmechanik durch trinken und wiederbeleben massiv beeinflusst und erleichtert, könnte die Strafe härter ausfallen.
Zumindest ist das die Meinung von mir, ob das GM Team auch so sieht ... wer weis.

**Comment by ChichiWarrior** [comment]
Wir hatten vor vielen Monaten schon nachgefragt, da sich der GM selbst nicht sicher war, wurde dies an oberster Stelle nachgefragt.
Sagen wir es so. Es wird geduldet, weil es eben nicht 100% funktioniert.
Achja. Der Report besteht schon mindestens ein halbes Jahr.
Lieutenant General Andorov ist bis heute nicht ansprechbar um die beiden Formeln kaufen zu können.

Gruß

Chichi

**Comment by Loplin** [comment]
Chichi ich glaube dir, dass dir ein Gm das gesagt hat
Selbst so umsetzen würd ichs nur wenn ein GM sich hier durchringen könnte um das schriftlich zu gebrn

**Comment by dagochen** [comment]
Ich hatte dies damals* auch mal erfragt und mir wurde mitgeteilt, dass sitzen/rezzen etc. verboten ist und klarer Fall von Bugabuse sei. Die beste Lösung wäre wohl, bevor wir hin und her-rätseln ob es erlaubt oder nicht erlaubt ist, das Bossevent zu fixen ;)

*weit vor meiner Zeit als externer Mitarbeiter

**Comment by ChichiWarrior** [comment]
Dann müsste man alle Charaktere bannen, die jemals in AQ20 waren.
Ich will hier keine Diskussion starten, ob es i.O. ist oder nicht. Ich wollte lediglich meine erfragten Informationen weiter geben.

Ja, dass wäre die beste Lösung, genauso wie Andorov zum verkaufen seiner Formeln zu zwingen.

**Comment by dagochen** [comment]
Weißt doch diese Russen sind immer bisschen kompliziert :P

**Comment by Slimmer2** [comment]
Laut Dotox sollte er seine Waren verkaufen. Aber das gehört nicht zu diesen Bug

**Comment by Loplin** [comment]
Sagt ja keiner irgendwen rückwirkend zu bannen
Was ich mir wünsche wär ein klares Statement 
Ja reggen wird geduldet
Oder
Nein wird nicht gesuldet

Damit die ewigen Diskussionen im raid aufhören weil immer einer dabei is der wen kennt der wen kennt der aus erster hand weiß das es erlaubt/verboten is

**Comment by Slimmer2** [comment]
Es ist als Bug gemeldet und in den zwei Videos ersichtlich das man im Kampf bleibt.
Also ist es Bug use und verboten.
Da braucht man jetzt auch kein Statement von einen GM.

**Comment by ChichiWarrior** [comment]
Das wussten wir schon vor 6 Monaten Slimmer2 und es wurde trotzdem geduldet.

Andorov gehört zum Event, denke das ist kein Problem das hier zu erwähnen.
Nein, er verkauft noch immer keine Rezepte

**Comment by ChichiWarrior** [comment]
Netter Versuch. Der Bug war bereits bekannt und gemeldet. Ein doppelter Report war daher nicht notwendig ;-)

**Comment by Larnak1** [comment]
Laut der Patchnotes vor kurzem soll hier gefixt worden sein, dass man zwischen den Phasen outfight kommt:
"Spieler sollten während des Events mit Rajaxx nicht mehr aus dem Kampf kommen."
https://community.mmobase.de/updates-changelog/10284-update-23-11-2016-a.html

Meiner Erfahrung nach funktioniert das sehr oft nicht. Ich habe zur Zeit keine Ahnung, woran es liegt, aber in den Trys, die ich seitdem gemacht habe (2), bin ich nur nach 1 oder 2 Phasen pro Try nicht aus dem Kampf gekommen. Allerdings wurde natürlich sofort von Seiten der Raidleitung darauf hingewiesen, dass das auf keinen Fall zum Reggen genutzt werden darf :) Im TS wurde auch von andereren angemerkt, dass der Fix ihrer Erfahrung nach auch in anderen AQ20-Raids schon nicht funktioniert habe.

**Comment by Slimmer2** [comment]
Outfight kommt man nicht mehr aus dem Kampf.
Aber nachdem eine Addwelle tot ist addet die nächste nicht instant
