### ISSUE TITLE
Tod und Feststecken

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1781]
Welches Verhalten wird beobachtet?
Wenn man tot ist und als Geist feststeckt und den Befehl feststecken macht wird man zum Gasthaus geportet wo der Ruhestein gebunden ist.

Wie sollte es sich verhalten?
Wenn man als Geist Feststecken benützt sollte man zum Geistheiler in er Nähe seiner Leiche geportet werden. Nur man lebt sollte man zum Gasthaus geportet werden wo der Ruhestein gebunden ist.

Schritte zur Reproduzierung
Sich sterben/töten lassen Feststecken benützen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

PS: Evtl. ist es ja nur ein Schönheitsfehler. Aber es ist nicht sehr angenehm wenn man zB. in Silitus stirbt feststecken benützt und dann im Gasthaus von Stormwind steht, dann bis zu seiner Leiche mindestens 30 Minuten laufen muss.

**Comment by dagochen** [comment]
Du kannst als Geist doch zu jedem Geistheiler laufen. Sprich auch Stormwind vor die Tore gehen und dich dort rezzen.
