### ISSUE TITLE
Falscher Questtext " Die Rettung von OOX-22/FE "

### ISSUE THREAD

**Issue by pinfi32** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1782]
Welches Verhalten wird beobachtet?
Die Rettung von OOX-22/FE http://datenbank.classic-wow.org/?quest=2767 zeigen einen Questtext der einer WoW Version nach 2.0 entspricht, dass Eskortenziel ist aber das korrekte Klassikziel.

Wie sollte es sich verhalten?
Die Quest sollte erwähnen, dass die Eskorte bis zum Dock in Feralas geht und nicht zur Hauptstraße wie aktuell.

Schritte zur Reproduzierung
Questtext lesen ;)

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Loplin** [comment]
inwiefern sollte der q text anders sein?

**Comment by pinfi32** [comment]
Kleines Update:

Selbiges Problem besteht auch für die beiden anderen OOX Quests in Tanaris http://datenbank.classic-wow.org/?quest=648 und im Hinterland http://datenbank.classic-wow.org/?quest=836 . Der Datenbank Eintrag ist korrekt der Ingametext nicht.

**Comment by dagochen** [comment]
Kannst du die korrekten Texte irgendwie auffinden?

**Comment by pinfi32** [comment]
Der Questtext in der Datenbank ist der korrekte. Im Spiel wird aber ein anderer angezeigt ähnlich wie hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1041
Ich nehme einfach mal an mit 2.0 wurden die Quests etwas vereinfacht und der Questtext stammt aus der Version und nicht aus pre 2.0.
