### ISSUE TITLE
Gizeltons Karawane u. Leibwache zu mieten in Desolace

### ISSUE THREAD

**Issue by SnuSnu18** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1784]
Welches Verhalten wird beobachtet?
Die Karawane in Desolace rennt vereinzelt auf der Route durch die gegend, ist zwar ansprechbar aber triggert die Quests nicht.

Wie sollte es sich verhalten?
Die Karawane sollte in geschlossener Formation laufen und gemeinsam bei den Kolkarzentauren und Mannorocs Koven stoppen, so dass man diese eskortieren kann. Die Quests starten also nicht und wie Karawane bittet nicht um hilfe oder bleibt an den trigger points stehen.

Schritte zur Reproduzierung
Karawane sollte gemeinsam laufen und die Quests triggern

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://datenbank.classic-wow.org/?npc=11625
http://datenbank.classic-wow.org/?npc=11564
http://datenbank.classic-wow.org/?npc=11626
http://datenbank.classic-wow.org/?npc=12246

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1246
