### ISSUE TITLE
Verblassen generiert Aggro nachdem es abläuft

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1785]
**Welches Verhalten wird beobachtet?**
Wenn Verblassen abläuft, erhält der Priester Aggro, auch wenn er diese vor dem benutzen nicht hatte.

**Wie sollte es sich verhalten?**
Der Priester sollte nachdem Verblassen ausläuft, genau gleich viel Aggro haben wie vor dem Benutzen des Skills (sofern in der Zwischenzeit nicht weiter Aggro aufgebaut wird).

**Schritte zur Reproduzierung**
1) Mit einem belieben Charakter einen Gegner pullen und keine Fähigkeiten verwenden
2) Den Priester ebenfalls in den Kampf bringen und keine weiteren Fähigkeiten verwenden
3) Verblassen verwenden
4) Sobald Verblassen ausläuft, hat der Priester die Aggro
siehe Video unten

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://youtu.be/fRIo2TExsEk

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Verblassen (Fade): http://datenbank.classic-wow.org/?spell=10942

**Comment by Slimmer2** [comment]
Mit der Vorgehensweise muss der Priester Aggro bekommen. Da du Manareg hast und der zweite Charakter keine Aggro gemacht hat

**Comment by xorann** [comment]
> Mit der Vorgehensweise muss der Priester Aggro bekommen. Da du Manareg hast und der zweite Charakter keine Aggro gemacht hat

No, just ... no
https://youtu.be/iQAw2-PdyaM

Manaregeneration der Ausrüstung generiert keine Aggro.

**Comment by Loplin** [comment]
Außerdem bekommt der krieger wut was ja auch aggro erzeugt und so gegebenenfalls aggro durch den mana reg ausgleichen
Der verblassen skill scheint deutlich mehr aggro zu erzeugen

**Comment by dagochen** [comment]
Ich kann das hier aufklären. Wut und Manaregeneration erzeugt nur dann Bedrohung, wenn es durch eine Fähigkeit oder ein Item erzeugt wird. Der Priester bekommt hier so viel Bedrohung, weil Verblassen den aktuellen Wert um x verringert und anschließend um x wieder erhöht. x ist dabei der Wert, der bei dem Spell in der Datenbank steht Wert: -820. Da Bedrohung bei 0 gecapped ist (negative Bedrohung gibt es nicht) wird folgendes gerechnet:
0 - 820 = 0 (beim cast)
0 + 820 = 820 (beim auslaufen)

**Comment by Loplin** [comment]
Das ergibt natürlich Sinn
KTM zeigt halt einen Wert von -820 beim nutzen an das führt in die irre

**Comment by dagochen** [comment]
Laut KTM kann es keine Bedrohung unter 0 geben. Vielleicht ist das in KTM aber ein Sonderfall, die haben das damals sicherlich getestet, dann müssten wir das entsprechend im Server anpassen.

**Comment by xorann** [comment]
Gerade noch kurz mit dem Priester T2 5er Bonus (Reactive Fade) getestet, dort tritt das selbe Phänomen auf.

http://datenbank.classic-wow.org/?spell=21853
