### ISSUE TITLE
Thunderclap und Thunderfury stacken

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1786]
http://datenbank.classic-wow.org/?spell=11581 und http://datenbank.classic-wow.org/?spell=21992 stacken.

Es sind die gleichen Debuffs in unterschiedlicher Stärke. Sie sollten nicht stacken. Thunderfury sollte Thunderclap überschreiben. Gilt für die Ränge 1 bis 6.

The attack speed slowing effect from Thunderfury has been reduced to 20%, and no longer stacks with other such effects such as Thunderclap. The rate at which the weapon procs has also been lowered.

http://wowwiki.wikia.com/wiki/Patch_1.9.0

**Comment by Horim** [comment]
Sicher das auch tatsächlich durch beide Spells der Swingtimer verlängert wird? Oder werden nur beide Debuffs auf dem Boss angezeigt und der Stärkere wirkt? Das konnte ich bisher nicht testen =(

**Comment by testear** [comment]
Nie getestet. Ändert aber nix daran, dass einer das andere Überschreiben sollte.

**Comment by hraesvelgr** [comment]
"close and comment" ist der button für die leute, die sich nach dem "ich mach hier mal zu" schreiben nicht noch mehr arbeit machen wollen

**Comment by Seniorash** [comment]
The attack speed slowing effect from Thunderfury has been reduced to 20%, and no longer stacks with other such effects such as Thunderclap. The rate at which the weapon procs has also been lowered.

http://wowwiki.wikia.com/wiki/Patch_1.9.0
