### ISSUE TITLE
"Knalliger Apfel" Löst keinen Satt-Buff aus

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1787]
**Welches Verhalten wird beobachtet?**
Beim Essen des Items kommt es nicht zum Sättigungs-Buff

**Wie sollte es sich verhalten?**
Nach 10sek. Essen sollte man einen Buff erhalten, der Wille und Ausdauer erhöht.

**Schritte zur Reproduzierung**
Apfel essen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
keine

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
http://datenbank.classic-wow.org/?item=20516

**Comment by dagochen** [comment]
Kommt mit nächstem Neustart der Fix.

**Comment by Slimmer2** [comment]
Jetzt wird zwar der Satt Buff ausgelöst kommt aber instant nach dem man essen anfängt und nicht erst nach 10Sekunden wie es im Tooltip steht.

**Comment by dagochen** [comment]
Du hast immer noch Äpfel von den Schlotternnächten??? :)

Ja, das mit dem 10 Sekunden Delay hatte ich damals auf die schnelle nicht hinbekommen, da der Fehler erst während des Events aufgefallen ist.

**Comment by Slimmer2** [comment]
Ja ich hatte immer noch was. Als Hexe hat man auch andere Wege um genug zu reggen um zum Farmen. Inis sowieso

**Comment by Rushor** [comment]
ein Hoch auf die äpfel!

**Comment by Slimmer2** [comment]
Sattbuff bekommt man immer noch instant und nicht erst nach 10 Sekunden essen

**Comment by dagochen** [comment]
Der ist doch bestimmt schon schlecht :P
