### ISSUE TITLE
Server-Crash nach Inztanz-Reset

### ISSUE THREAD

**Issue by toho3000** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1789]
Welches Verhalten wird beobachtet?
Befindet man sich in der Instanz "Hügel der Razorfen" im Kampf, läuft durch das Instanzportal hinaus und resettet dann die Instanz, crasht der Server. (Ist insgesamt 3x heute passiert, als ich Infight mit der Mobgruppe (vom Eingang aus nach rechts, Abkürzung Richtung Endboss) war. Wenn man sich nicht im Kampf befindet, rausläuft und dann resettet, passiert nichts.

Wie sollte es sich verhalten?
Der Server sollte nicht crashen.

Schritte zur Reproduzierung
In die Instanz "Hügel der Razorfen" laufen, einen Boss oder Mobs töten, oben genannte Mobgruppe pullen, rauslaufen, die Instanz mit dem Befehl "/script ResetInstances();" resetten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Leider keine vorhanden. Heute (19.10.16) insgesamt 3x passiert, stehe zur Reproduzierung gern zur Verfügung. Eventuell bei anderen Instanzen auch testen.

LG Fieruna/Jaqenhgar

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Ich konnte das Problem auf dem Testserver bisher nicht reproduzieren. Unter welchem Namen und zu welcher Uhrzeit trifft man dich am ehesten ingame an?
