### ISSUE TITLE
Charge/Intercept: Falsche Rangeberechnung

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1791]
Welches Verhalten wird beobachtet?
Wenn ein Krieger anstürmt oder abfängt kann er von seinem Ziel oder  danebenstehenden Spielern geschlagen werden bevor er in Nahkampfreichweite ist.

Wie sollte es sich verhalten?
Der chargende Krieger als auch seine Feine sollten erst Nahkampfangriffe aufeinander ausführen können nachdem sie in Meleerange sind.

Schritte zur Reproduzierung
Chargen, Fehler tritt auf bevor der zeitverzögerte Stun einsetzt oder das Ziel stunimmun ist.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Der Fehler ist sicherlich der gleiche wie aus #67, der falsch gefixt wurde und zu #1773  führte.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=20252
http://datenbank.classic-wow.org/?spell=100

**Comment by soda09** [comment]
Quellen?

**Comment by testear** [comment]
http://wowwiki.wikia.com/wiki/Melee?oldid=336214
World of Warcraft typically defines 'Melee Range' as 5 Yards or closer. 

Charge und Intercept haben eine Reichweite von 8 bis 25 Yards. 

http://www.warcraftmovies.com/movieview.php?id=26232#moviesum
Schon direkt zu 1:20. Swifty wirkt Intercept kriegt aber keinen Schlag ab.

**Comment by Seniorash** [comment]
Manche Sachen sind so offensichtlich...einfach den Kopf einschalten. Achne jetzt versteh ich das "doof" ;-)

**Comment by soda09** [comment]
Kann den Fehler nicht reproduzieren.

**Comment by soda09** [comment]
Kann das nicht reproduzieren. Wenn ich einen Gegner ancharge, ist es ihm nie möglich auch nur eine Meelefähigkeit zu wirken.

**Comment by testear** [comment]
Nahkampfangriffe ungleich Fähigkeiten.

**Comment by testear** [comment]
Nahkampfangriffe ungleich Fähigkeiten

**Comment by Seniorash** [comment]
Gibt es da noch eine offizielle Rückmeldung? Sofern das Reportpaket angegangen wird, sollte es dann halt auch richtig gemacht werden.

**Comment by dagochen** [comment]
Kannst du das Problem vllt etwas genauer beschreiben? Was für Fähigkeiten meinst du? Wann wird die Fähigkeit vom angechargten Spieler angefangen? Wenn es sich nicht um Nahkampfangriffe handelt, dann sind es wohl Fähigkeiten mit einer Range größer als die Meleereichweite, und demnach auch völlig korrekt das die Spieler die schon auf dich machen können, während oder bevor du chargst. Daher schließe ich erstmal, bis es hier was neues gibt.
