### ISSUE TITLE
"Soul Siphon" des Hexenmeisters funktioniert nicht zu 100%

### ISSUE THREAD

**Issue by Eiersalat** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1793]
Welches Verhalten wird beobachtet?
Trotz zweier Talentpunkte in "Improved Soul" erhält man den  "Soul Siphon"-Buff nicht immer. Häufig (aber nicht ausschließlich) ist dieses Verhalten zu beobachten wenn das "Seele entziehen" recht knapp angewendet wird.

Wie sollte es sich verhalten?
Man sollte den Buff bekommen.

Schritte zur Reproduzierung
Gegen Ende eines Kampfes bei geringer Lebenspunktzahl "Seele entziehen" wirken. Darauf achten ob man einen Seelenstein erhält (zeigt dass der Spruch noch funktioniert hat) und beobachten ob man den Buff "Soul Siphon" erhält.

**Comment by Slimmer2** [comment]
Ist das Problem oft wenn du alleine unterwegs bist?

**Comment by Eiersalat** [comment]
Ja, ist es. Also nicht ganz alleine, habe ja noch meinen Dämonen. :)
[http://datenbank.classic-wow.org/?spell=8288](url)
[http://datenbank.classic-wow.org/?spell=18372](url)

**Comment by hraesvelgr** [comment]
du musst den killing blow machen, nicht dein dämon, damit das talent funktioniert.

**Comment by Eiersalat** [comment]
Oh man... Wer lesen kann ist besser dran...
