### ISSUE TITLE
Druide "Heart of the Wild" erhöt nur Intelliegenz

### ISSUE THREAD

**Issue by Eiersalat** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1794]
Welches Verhalten wird beobachtet?
Dem Anschein nach erhöt oben genanntes Talent nur die Intelligenz und keine weitere Eigenschaft (Stärke/Ausdauer).

Wie sollte es sich verhalten?
Das Talent sollte die Intelligenz erhören und zusätzlich je nach Gestalt eine weitere Eigenschaft (Bär=Ausdauer/Katze=Stärke).

Schritte zur Reproduzierung
Das Talent erlernen/steigern und die Eigenschaften beobachten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://imgur.com/a/mrvLP
http://imgur.com/a/ZqvmF

Edit: Bilder korrigiert.

**Comment by hraesvelgr** [comment]
relog gemacht? wdb gelöscht?

**Comment by Eiersalat** [comment]
Jawohl, beides versucht.

**Comment by dagochen** [comment]
Die Ausdauer und Stärke werden angerechnet sobald man mit dem geskillten Talent in die Bären- oder Katzenform wechselt.
