### ISSUE TITLE
Bug Trio - Respawn nach Tod

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1796]
Wie verhält es sich?
Wenn 2 der 3 Bugs getötet sind, respawnen diese direkt wieder.

Wie sollte es sich verhalten?
Die getöteten Bugs sollten tot bleiben.

Schritte zur Reproduktion:
Bug-Trio pullen, 2 davon töten (Reihenfolge scheint egal zu sein). Nachdem der 2te Bug stirbt, sollten die getöteten Bugs respawnen (tritt afaik nicht zu 100% auf, allerdings bei uns die letzen 4/4).

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=cbbgFLQkUz8&feature=youtu.be
Falls gewünscht kann ich auch noch ein Video, in dem wir eine andere Reihenfolge machen, hochladen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15511
http://datenbank.classic-wow.org/?npc=15543
http://datenbank.classic-wow.org/?npc=15544

**Comment by hraesvelgr** [comment]
ist das einmalig aufgetreten? oder wiederholt?

**Comment by Loplin** [comment]
ja würd mich auch interessieren

die 4/4 mal die das bei euch der fall war, war das an einem raidabend oder an unterschiedlichen?
in welcher Reihenfolge habt ihr die getötet?

**Comment by Nifexx** [comment]
Mehrmalig aufgetreten. Ja auch an unterschiedlichen Abenden. Der Bug ist auch schon älter, wie gesagt, er tritt nicht zu 100% ein. Die Tries waren in der Reihenfolge Kri->Yauj->Vem und Yauj->Vem->Kri. Bei beiden, bzw allen letzten 4 tries, respawnen die Bosse, nachdem 2 getötet werden.

**Comment by Badorr** [comment]
Ja, das scheint völlig random zu sein, kommt immer mal wieder vor und ist seit AQ40 Release so. Habe kein Muster erkennen können. Falls in dem Moment, wo z.B. Yauj stirbt, noch irgendein Cast auf sie zufliegt, wird er auf die neu spawnende Yauj umgelenkt und dann greifen beide respawnten Bugs sogar wieder in den Kampf ein und man muss resetten.

**Comment by ChichiWarrior** [comment]
Wurde schon 3x reportet, leider kann man das in nicht reproduzieren.
Es scheint als seid ihr an der Reihe. Bei uns laufen die Bugs seit Wochen problemlos.

**Comment by Nifexx** [comment]
Tatsache Chichi, hab das alte Thema leider nicht gefunden, dann hätte ich mir das natürlich gespart. Alter Report #1401
