### ISSUE TITLE
Swing timer wird bei procc´s nicht zurückgesetzt

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1798]
### Welches Verhalten wird beobachtet?

Wenn man durch das Windfury totem oder dem Talent: Schwert Spezialisierung oder Hand der Gerechtigkeit einen Extra Schlag bekommt wird bei der main hand waffe der Schlag timer nicht zurück gesetzt.
### Wie sollte es sich verhalten?

Extra Waffen hits wie: Windfury, Hoj, Schwert procc und Reckoning sollten den  swing timer der Main hand zurücksetzen.
### Schritte zur Reproduzierung

Windfury totem stellen lassen > Autoattack starten > Als schurke angreifen und windfury proccen lassen durch fähigkeiten. 
Oder Als Krieger mit einer langsamen 2hand > zu schlagen > aber der hälfte Kniesehne casten > wf proc auslösen > procc und sehen das der autoatack trotzdem mit dem alten timer ausgeführt wird.
### Zusätzliche Informationen (Screenshots, Videos, etc.)

http://roguecrap.blogspot.de/2006/05/more-on-sword-spec-modeling.html 
(Sword spec proc is an normal mainhand attack and will cancel attack-in-motion and resets your MH attack timer.)

http://leftoversraiding.org/index.php/topic/2574/1/sword-spec-rogues-read-this.html
(Because BB (2.5 speed) is only just BARELY slower than CTS (2.6), and so nearly all of your mh swing time gets wasted when your oh procs sword spec and resets the mh swing timer.)

http://blue.cardplace.com/cache/wow-realm-test/40837.htm
(Because reck. resets the swing timer, 5 points in the talent provide only 1%-99% of a free swing, depending on when in the swing cycle you are crit.)

http://forums.elitistjerks.com/forums/topic/8508-hand-of-justice-understanding-this-trinket/?page=2
(Posted 29 Sep 2006 - patch 1.12
Basically HoJ resets your MH swing timer enabling one extra auto-attack (just like sword spec or windfury). The extra attack can proc a weapon enchant, just like a "normal" attack can. Your combat log just says you gain an extra attack through windfury/sword specialization/hand of jusice, then the next line of the combat log will have the normal autoattack sequence. There's nothing that identifies the extra attack as being any different from a normal autoattack. Because this is a normal attack, it can crit, miss, etc. and most importantly it is subject to glancing blows.

Where things get kind of wacky is when you have a chain proc of sword spec, HoJ, and/or windfury (one procs off the other). Because all of these reset your swing timer, you only get the benefit of one of them, even if you had a chain proc (checking my combat log it looks like I'm only getting one attack, not a chain of 2-3). In this situation you would have been better off with 1% more crit or even 1% hit rather than the 1% extra attack. Ideally the "extra attack" would just be instant damage every time you get an extra attack, which it sort of is, but not when multiple things give you an extra attack (edit: this means with wf you get 27% more extra attack damage, not a compound 1.02_1.05_1.20 = 29%). This is sometimes cited as one of the reasons sword spec isn't quite as good as it could be. Personally, I don't see this as that big a deal and the incidences of it happening are rare. Sword spec can still be superior to dagger/fist in some special situations because it doesn't impact your crit cap and has a similar impact on dps.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.http://datenbank.classic-wow.org/?item=11815 Hoj
Schwertproc: http://datenbank.welli-it.de/?spell=16459
Schwertspezialisierung: http://datenbank.welli-it.de/?spell=13964
Reckoning proc: http://datenbank.classic-wow.org/?spell=20178
Reckoning  Talent: http://datenbank.classic-wow.org/?spell=20182
Windfury Totem: http://datenbank.classic-wow.org/?spell=27621

**Comment by Seniorash** [comment]
er wird denitiv zurück gesetzt. einfach mal mit einem attack timer addon genauer angucken (und staunen :))

**Comment by SirBeansen** [comment]
Eben nicht, da dein attack timer addon den swing timer zurück setzt, weil es so programiert ist bei jeden white hit damage. 
Einfach drauf achten beim addon, dass der nächste schlag nicht komplett durch läuft. Oder einfach den Kampflog auswerten wo man die unregelmäßigkeiten auch erkennen kann.

**Comment by Horim** [comment]
Hmm dann wird man die Wirkungsweise von Heroic Strike für DW Krieger ggf. anpassen müssen.
Wenn es normale Autohits sind, die den Swingtimer resetten, werden die Extrahits als Heroic Strike ausgeführt, falls der Skill für den nächsten Swing vorgesehen war, sofern ich der Argumentation richtig folgen konnte.

Betrifft natürlich nur Offhand HoJ proccs und WF Proccs durch alle Waffenskills die Schaden machen und nicht "on next Swing" sind.

**Comment by SirBeansen** [comment]
Ja stimmt da hast du Recht.

Und nicht nur Heroic Strike ist ein on-next-swing skill, sondern auch Spalten und Raptorstoß.

http://wowwiki.wikia.com/wiki/Patch_1.9.0
- On-next-swing abilities will no longer cause multiple weapon procs on a single swing.

Vielleicht hilft das ja noch.

**Comment by Horim** [comment]
Bei Rogues kam der Schwert-Spec "Fix" erst mit 2.1.
Auch wenns keinem Rogue gefällt: Leider wahr, der Swingtimer muss resettet werden.

**Comment by SirBeansen** [comment]
Der bug betrifft auch das Warri Schwert talent Horim.

Und in 1.3.0 wurde auch für Krieger "Added a visual to Sword Specialization "proc" that will now show up in the combat log as well." eingeführt.

**Comment by Horim** [comment]
Hab erstmal nur nach rogue geguckt weil mich warri Schwert nur unwesentlich interessiert, schließlich Spiele ich nicht mit WF-Kniesehne ;)

**Comment by Horim** [comment]
So, nachdem man mal die Zeit gefunden hat:
HoJ und Schwertspezialisierung stellen gegenüber Windfury eine andere Form von Extra-Hit dar, denn bei den ersten beiden wird der Extra-Hit immer mit der Mainhand verursacht, unabhängig davon mit ob die Mainhand oder Offhand den Extra-Hit auslöst. 

Windfury ist ein kurzzeitiger Waffenbuff, dessen Extra-Hits nur von der jeweilig verzauberten Waffe ausgeführt werden können. Darin liegt der erste Unterschied.

Desweiteren sollten alle Formen von Extra-Hits im Kampflog gekennzeichnet sein, damit das Spiel die Extra-Hit-Sequenzen erkennen und eliminieren kann.
Zum Beispiel: Autohit->Wf->Schwertprocc->HoJ
Das Spiel wird sich schwer tun diese Sequenz zu unterbinden, da es derzeitig nicht unterscheiden kann welcher hit was ist. Theoretisch sollten Einträge wie [hier](http://i.imgur.com/LUFCW29.png) möglich sein, wodurch nur einer der beiden Extra-Hits ausgeführt wird.

Was mich beim Windfury stört: Es gibt unterschiedliche Einträge durch Windfury im Kampflog.
Viele kennen sicherlich noch den guten alten [George](https://www.youtube.com/watch?v=apgkI-0tOB4). Der hatte sich damals die Mühe gemacht, seinen Kampflog anzuzeigen:

Der eine Eintrag:
 _You gain 1 extra attack through Windfury Attack_ (z.B. 1:46)
Der Eintrag kommt immer vor dem eigentlichen Hit der den WF-Hit auslöst und scheint ein sofortigen Wf-Hit auszulösen. Die Schlagsequenz im Video ist : 
- 229 OH Crit
- _You gain 1 extra attack through Windfury Attack_
- 364 MH Crit <- der Auslöser
- 449 MH Crit <- Der WF hit
Soweit bei Autohits.

Bei Cleave kommt der Extra-Hit im Kampflog sogar vor dem Cleave (z.B: 0:30).

Bei ca. 1:12 bis 1:15 kann man sehen, das WF durch ein Whirlwind ausgelöst wird und tatsächlich den Swingtimer resettet, da wir sonst 3 normale MH Swings sehen sollten. Zu sehen ist jedoch : 

- Cleave parry (MH Swing)
- _You gain 1 extra attack through Windfury Attack_ 
- 207 MH Hit (43 blocked) <- Der WF-Hit
- 471 WW Crit <- der Auslöser, da das erste Cleave zu weit zurück liegt.
- 268 OH Crit
- Doppelcleave 640+570 (MH Swing)

Es fehlt der MH Hit zwischen WW und dem Doppelcleave.
Des weiteren sieht man auch hier: Der WF Hit kommt vor dem Style, welcher diesen erzeugt.

Btw: Bei HoJ (2:48) kommt gibt es auch einen Eintrag im Kampflog _You gain 1 extra attack through Hand of Justice_ 

Der andere Eintrag ist : 
_You gain Windfury Attack_
Ehrlich gesagt finde ich diesen nur bei 2h/MS Kriegern und die Suche ist etwas beschissen:
https://www.youtube.com/watch?v=GuPkZJpIn04&feature=youtu.be
Der MS wird gewirkt und _You gain Windfury Attack_ ploppt auf, z.B 9:07:

- 375 Hit (9:08)
- _You gain 1 extra attack through Windfury Attack_
- 448 Hit <- der Extrahit
- **_You gain Windfury Attack_ <- Was ist das?**
- Your Mortal Strike hits *target* for 450 damage. <- Wahrscheinlicher Auslöser
- _You gain 1 extra attack through Windfury Attack_ 
- 407 Hit (9:10) <- der Extrahit
- 577 WW Crit <- Wahrscheinlicher Auslöser

Aufgrund des Stuns und Extrahits durch WW ist es leider nicht bewertbar, ob durch den "MS-Windfury" der Swingtimer resettet wurde oder nicht. Ich würde nur gerne verstehen, was die Mechanik von _You gain Windfury Attack_ ist. Bei  George, dem Fury DW, gibt es diesen Eintrag nicht.

-> Wäre genial, falls noch wer was zu den verschiedenen Einträgen findet.

**Comment by SirBeansen** [comment]
Nice arbeit Horim. 

Es könnte sein das der Windfury effekt bei Styles erst beim nächsten Waffenschwung ausgelößt wird und bei autoattacks direkt. Aber eine genaue quelle die das belegt hab ich dazu noch nicht.

**Comment by Horim** [comment]
Quelle kann ich bislang auch nicht finden.
Zumindest bei WW und Kniesehne sind in den Videos sofortige Proccs zu sehen.
Warum der MS hierbei anders agiert, bleibt zunächst ungeklärt.
Für Slam kann ich überhaupt nichts finden (2006 wohl eine Nische), wobei hier der unmittelbare Procc naheliegt, da Slam ohnehin den Swingtimer resetet.

**Comment by Horim** [comment]
Zumindest als Bug könnte man es mal markieren/anerkennen.
Es geht klar hervor, das es auf Nefarian nicht richtig funktioniert, nur wie es sein soll, ist (noch) nicht zu 100% geklärt.

**Comment by SirBeansen** [comment]
Horim hat nur den Kampflog von alten videos so gut es ging ausgewertet um damit zu zeigen wie es sein sollte.
Der bug das man durch Schwert proccs keinen MH reset bekommt ist aufjedenfall vorhanden.
Diskutiert wird hier darüber wie es sein sollte, besonders wegen den on next swing attacks.

Ich kann mich nähmlich noch dran erinnern, wo jeder Schwert, HoJ und WF procc erst auf den nächsten Autoattack ausgeführt wurde. Das wurde dann behoben und führt wohl nun zu diesen Fehler, dass die MH dabei nicht ressetet wird. 

Wenn man sich diesen thread anschaut https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/203 steht da vom ersteller:

**Wiesollte es sich verhalten?
Beide "Proccs" setzen den Swingtimer zurück und geben keine "Aufladungen". Machte man Heldenhafter Stoß > bekam Schwert Anrgiff > griff man sofort wieder an (Swingtimer reset)**

Quelle wurde gar nicht angeben. 

Dann steht nochmal weiter unten

**Die Mechanik des Proccs (funktioniert nicht):

    Unabhängig davon, ob mit Main- oder Offhand der Procc ausgelöst wird, wird der aktuelle Timer der Mainhand vollendet. D.h. es wird ein Schlag mit der Mainhand ausgeführt und dessen Swingtimer auf 0 gesetzt. Es handelt sich also in dem Fall um eine Beschleunigung und um keinen zusätzlichen Hit in dem Sinne. Nur wenn es beim Autoswing procct, kommen tatsächlich 2 Schläge auf einmal.
**

Darau lese Ich, das der swing Timer reset schon funktioniert hatte, aber fälschlicherweise "geifxt" wurde, wegen dem damaligen problem das Spalten und Heroric Strike die proc Fähigkeiten geschluckt hat.

**Comment by Horim** [comment]
Bezüglich der Skills die auf den nächsten Swing folgen (HS, Cleave, Raptor Strike):
Bei [0:44](https://www.youtube.com/watch?v=apgkI-0tOB4) haben wir ein Doppelcleave (=2x unmittelbar hintereinander) dank HoJ, die Annahme, das die Skills direkt als Extrahit ausgeführt werden, scheint zu stimmen.

**Comment by Seniorash** [comment]
Ihr vermischt hier einiges. Die Fehler mit WF und hoj/sword Proc waren jeweils andere (dazu gab es auch 2 einzelne Reports). Was beansen zitiert bezieht sich nur auf hoj und Schwert proccs wozu man auch Quellen finden kann. Zu WF ist mir keine Quelle bekannt.

**Comment by Horim** [comment]
Kann ich nur bedingt zustimmen, bei WF Hits durch WW wird bei George der Swingtimer zurückgesetzt =(

**Comment by Sabbaer** [comment]
zu reconning:

Is this intentional? I surmise this problem came about a few patches ago when Thrash and Windfury were changed to reset the swing timer. But because those extra attacks occur instantly after your swing, no time is actually lost.

 ich hoffe, das wurde auch beachtet beim fixen. steht nämlich direkt drunter.
deßweiteren würde mich noch interessieren ob ich jetzt den auto attack stoppen muss nach der änderung um aufladungen zu generieren

deßweiteren sind das nur fragen die dieser user stellt zu reconning, er postet keine screenshots und nichts weiteres?! is ja kein bluepost sondern nurn reply zu nem anderen post

**Comment by dagochen** [comment]
Extra Attacks werden immer erst mit dem nächsten Nahkampfangriff "abgearbeitet". Für 2Hand-waffen ändert sich folglich nichts, weil es keine Offhand gibt, die diese Extra-Angriffe auslösen kann und so den Swingtimer der Mainhand zurücksetzt.

**Comment by Sabbaer** [comment]
ok nice, dann passt ja alles ;)
