### ISSUE TITLE
Jäger Pet: Erhöhte Tiergeschwindigkeit funktioniert nicht

### ISSUE THREAD

**Issue by hauerfratze** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1799]
Welches Verhalten wird beobachtet?
Trotz Talent "Erhöhte Tiergeschwindigkeit" keine erhöhte Laufgeschwindigkeit beim Angreifen eines Gegners

Wie sollte es sich verhalten?
+30% Geschwindigkeit

Schritte zur Reproduzierung
Es wurde mehrfach berichtet, dass das Problem erst nach dem Relog auftritt. Deshalb beim testen bitte einmal reloggen. 

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Kann ich nicht reproduzieren, wenn möglich mehr Input und oder Videos
