### ISSUE TITLE
DM Buffs

### ISSUE THREAD

**Issue by WEberus12** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1800]
Welches Verhalten wird beobachtet?
Sobald de Endboss getötet wurde im Tributrun bekommt jede der sich in der Ini befindet den Ogerbuff(woman die Bosse ansprechen kann), auch Spieler die nicht beim Kill dabei waren, kriegen den Buff

Wie sollte es sich verhalten?

die Spieler die den endboss erfolgreich gelegt haben müssen  Mizzle ansprechen um den Ogerbuff zu kriegen und dann spawnt die Truhe  - und nur die sollten den Buff auch Kriegen und nicht jeden.

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://wowwiki.wikia.com/wiki/Dire_Maul_tribute_run

**Comment by hraesvelgr** [comment]
http://wowwiki.wikia.com/wiki/Mizzle_the_Crafty

so wie ich das verstanden habe (durch diesen chaotischen satz) ist es momentan so, dass mizzle sofort den buff gibt, ohne gossip, man diesen aber erst durch den gossip mit ihm erhalten sollte.

**Comment by dagochen** [comment]
https://www.youtube.com/watch?v=AND-5oZBPc4

**Comment by Loplin** [comment]
Patch 1.4.0 (2005-05-05): Mizzle the Crafty in Dire Maul shouldn't be so repetitive in proclaiming a new king if the player cycles through gossip too quickly.

Bezieht sich dieser text nur auf die geschwindigkeit mit der man den gossip durcharbeitet oder auf die anzahl der spieler die in zu kurzer zeit mit ihm sprechen und sich zum könig krönen lassen

Wäre zweiteres der fall, würde das bedeuten, dass man die Id wohl wie bisher weitergeben kann, nur wohl nicht ohne nen umweg zum endboss sowie an ganze raids die sich innerhalb weniger minuten die buffs abholen

**Comment by Slimmer2** [comment]
Hier der Deutsche Patchnote
Mizzle der Gewiefte im Düsterbruch wird jetzt nicht mehr so oft einen neuen König ausrufen, wenn sich der Spieler schneller seines Geplappers entledigen möchte.

http://wow.4fansites.de/patchnotes_1_4.php#Patchnotes-1-4-0

**Comment by Loplin** [comment]
Danke für die Deutsche Quelle :)

_"...nicht mehr so oft einen neuen König ausrufen..."_
lässt ja auf die Anzahl der Spieler schließen, wobei
_"...wenn sich der Spieler schneller seines Geplappers entledigen möchte."_
dann wieder auf die Geschwindigkeit des durchklickens Bezug nehmen könnte

**Comment by BugsBugs** [comment]
Habt ihr hier schon geplant wie es weiter geht? Besonders in Bezug auf Naxx wäre es interessant, ob es weiterhin die Möglichkeit geben wird auf DM-Buffs zugreifen zu können oder nicht.

Eine Änderung auf den Blizzlike Zustand (also bis zu Mizzle laufen und wie zurück), würde wohl dazu führen, das man sich das Prozedere endlich sparen kann, da es einfach zu Zeitintensiv wäre.
