### ISSUE TITLE
Quest: Verraten (Horde / Aszhara) Falsches Anforderungs-Level

### ISSUE THREAD

**Issue by hauerfratze** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1801]
**Welches Verhalten wird beobachtet?**

Die letzte Quest der Kette "Verraten" (http://datenbank.classic-wow.org/?quest=3507) hat ein höheres Anforderungslevel (54) als der Rest der Kette, dabei ist es nur die Abholung der Belohnung. 

**Wie sollte es sich verhalten?**
Das Anforderungslevel sollte bei 49 liegen.

_Das gleiche Problem gab es bei den Quests "Lieferung an ..." und der jeweiligen Folge "...'s Bezahlung an Jegida" (z.B. http://datenbank.classic-wow.org/?quest=3541). Das wurde bereits gefixt._

**Comment by hauerfratze** [comment]
Ja klar, unzureichende Quellenangabe. Das habt ihr letztes Mal auch gesagt als ich das mit den Jegida-Quests gepostet habe, inzwischen ist es gefixed. Ich kann euch leider keine Quelle liefern. Aber gesunder Menschenverstand reicht in diesem Fall aus. 

Vielleicht sollte sich das derjenige anschauen, der auch die Jegida-Quests gefixed hat - Offensichtlich gab es irgendwo eine Quelle.

**Comment by dagochen** [comment]
Das Problem ist hier das jede Quest ein anderes Level hat. Da ist es dann nicht klar, welches von 4 verschiedenen Mindestlevels ich nehmen muss. Bei der anderen waren 3 mal das gleiche Level und 1 mal ein anderes. Da kann man dann ein Muster erkennen. Hier ist das nicht der Fall.

**Comment by hauerfratze** [comment]
Achso. Ja da hast du Recht, das ist mir noch nicht aufgefallen. Da aber die erste Quest Lvl 50 benötigt und die folgenden weniger, ist es ja unerheblich. Man kann also die ganze Kette ab lvl 50 machen, bis auf die Rückkehr zum Questgeber - deshalb würde ich es eben auch auf 50 machen. Ich verstehe dass das nicht so einfach ist.

**Comment by hraesvelgr** [comment]
find dazu auch nichts. wowwiki schwankt zwsichen level 44 und 49, andere databases schwanken zwischen 49 und 53...

es gibt keine verlässliche quelle.

aber: dass es quests gibt, bei denen die endquest zum abgeben der reihe ein höheres level hat, als die reihe davor, ist nicht ungewöhnlich.

**Comment by Mafyo** [comment]
wowwiki von 2007
http://wowwiki.wikia.com/wiki/Quest:Betrayed_(4)?oldid=780942

**Comment by dagochen** [comment]
1. Quest: Level 44
http://web.archive.org/web/20050425062845/http://wow.allakhazam.com/db/quest.html?wquest=3504
2. Quest: Level 44
http://web.archive.org/web/20050414065248/http://wow.allakhazam.com/db/quest.html?wquest=3505
3. Quest: Level 46
http://web.archive.org/web/20050227131453/http://wow.allakhazam.com/db/quest.html?wquest=3506
4. Quest: Level 50
http://web.archive.org/web/20050119140639/http://wow.allakhazam.com/db/quest.html?wquest=3507

Fix inc ;)
