### ISSUE TITLE
C'thun; keine Tentakeln im Magen

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1802]
Welches Verhalten wird beobachtet?
Die Tentakeln im Magen, die getötet werden müssen um ihn in die Phase zu bringen fehlen.

Wie sollte es sich verhalten?
Sollten natürlich da sein.

Schritte zur Reproduzierung
Tritt nicht zu 100% auf, von daher den Boss solange tryen bis es auftritt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=MCz60Pt-Wos

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15727
http://datenbank.classic-wow.org/?npc=15802

Anmerkung:
Ich würde hier gerne erwähnen, dass C'thun immernoch tote Spieler anwählen kann wodurch er sich in P1 heilt und in P2 diese in den Magen befördert. #1402 #1763

**Comment by Badorr** [comment]
Die Magententakeln sind die ganze Zeit über nicht gespawnt? Noch nie gesehen sowas

**Comment by hraesvelgr** [comment]
"den boss solange trien bis es auftritt"..

naja dann ist das kein bug sondern ein nicht ausgeführtes script. und dagegen kann man fast garnix machen (ausser unendlich viele loops einzubauen)

**Comment by Nifexx** [comment]
@Badorr Sieht nicht danach aus. Wir brechen idR direkt ab wenn wir sehen, dass keine Tentakeln im Magen sind. Das würde sonst zu viel Zeit kosten.
@hraesvelgr Es ist halt einfach ärgerlich wenn man Worldbuffs holt und dann damit konfrontiert wird :( 
Außerdem wüsste ich sonst keine Schritte wie man es reproduzieren kann :/

**Comment by hraesvelgr** [comment]
was noch gut zu wissen wäre: wie oft tritt es ca auf? dein report klang so, als hättest du das bei 100 tries vllt zweimal erlebt. aber scheint ja doch öfter zu sein. ist das bei anderen gilden genauso?

**Comment by Sabbaer** [comment]
ich war so ziemlich bei fast allen cthun kills sowie allen trys bei uns dabei, das habe ich noch nie gehört oder gesehen

**Comment by Badorr** [comment]
Also seit Dezember '15 waren wir in so ziemlich jeder ID bei C'thun und sowas hab ich noch nie gesehen oder gehört. Das einzige was jemandem aus der Gilde mal passiert ist, dass die Magententakeln noch nicht da waren, als er als Erster in den Magen gesaugt wurde. Da war das Script leicht verzögert oder so was.

**Comment by hraesvelgr** [comment]
scheint also wirklich ein simpler lag/script -fehler zu sein.

**Comment by xorann** [comment]
Das erste Mal ist es bei uns am 29.9. passiert. Da war ich zwei Minuten nach Beginn von P2 im Magen, ohne dass ein Tentakel da war. Von daher ist es nicht einfach nur eine leichte Verzögerung. Seither ist dieses Phänomen leider immer wieder mal aufgetreten.

**Comment by Slimmer2** [comment]
Mit 1 Monat Verspätung gemeldet?

**Comment by Wosser** [comment]
Auch who cares ist das in 11 Monaten AQ40 noch nie passiert.

**Comment by Badorr** [comment]
Wenn der Bosstry ausweglos ist, lasst ihr euch dann generell alle sterben und auswipen oder gibts welche die regelmäßig rausporten um Pots/Buffs zu behalten?

**Comment by xorann** [comment]
Lassen sich immer alle sterben. Rausporten wird geahndet und bei C'Thun auch jedesmal explizit angesagt, dass es nicht getan werden soll.

**Comment by Slimmer2** [comment]
Wieso soll das geahndet werden?

**Comment by Badorr** [comment]
Weil es den Boss verbuggen kann, bis hin zum Punkt wo man ein Softreset der Instanz durchführen muss (d.h. 30 min warten)

**Comment by Slimmer2** [comment]
Das der Boss dadurch verbuggt ist mir schon bewusst. Aber es wird seitens der GM's nicht geahndet.

**Comment by Loplin** [comment]
vl meint er durch den Raidlead geahndet....

**Comment by Slimmer2** [comment]
Dann soll er/sie auch so schreiben. So könnte man meinen das es von GM's geahndet wird.

**Comment by Badorr** [comment]
Der Kontext des Satzes war eigentlich klar auf den Raidlead bezogen. Weiß nicht wo du da GMs rausgelesen hast ;)

**Comment by Loplin** [comment]
Weil hier keiner irgendwas auf seinen Raidlead bezieht. Wenn hier wer das wort ahnden nutzt, dann tatsächlich im Bezug auf GMs

ich kann die Verwirrung also verstehen^^
