### ISSUE TITLE
[Quest] "Frischfleisch", Mobs können nicht getötet werden (entkommen)

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1807]
**Welches Verhalten wird beobachtet?**
Um die Quest "Frischfleisch" erfolgreich zu beenden, muss man "Monströser Kriecher" töten.
Die Mobs entkommen aber beim angreifen und sind somit untötbar.

**Wie sollte es sich verhalten?**
Die Mobs sollten nicht entkommen und tötbar sein.

**Schritte zur Reproduzierung**
"Monströser Kriecher" in Sümpfe des Elends angreifen

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
keine

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Quest: http://datenbank.classic-wow.org/?quest=1430
Mob: http://datenbank.classic-wow.org/?npc=1088

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1673
