### ISSUE TITLE
Ouro: Man bleibt im Kampf nach dem Kill

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1809]
*Welches Verhalten wird beobachtet?*
Nachdem Ouro besiegt wurde und alle Käfer getötet/despawned sind, bleibt man weiterhin im Kampf.

*Wie sollte es sich verhalten?*
Nachdem der Boss und alle Käfer getötet wurden oder despawned sind, sollten alle aus dem Kampf kommen

*Schritte zur Reproduzierung*
Boss töten.

*Zusätzliche Informationen (Screenshots, Videos, etc.)*
Ist uns bisher in allen drei Kills passiert.

*Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.*
http://datenbank.classic-wow.org/?npc=15517
http://datenbank.classic-wow.org/?npc=15718
http://datenbank.classic-wow.org/?npc=15957
http://datenbank.classic-wow.org/?npc=15717

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1747
