### ISSUE TITLE
Quest (Krieger): Feuergehärteter Panzer - Questitem im Sumpfland dropt nicht

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1811]
Welches Verhalten wird beobachtet?

Die Spinnen ([Höhlenpirscher](http://datenbank.classic-wow.org/?npc=4040) und [Egelpirscher](http://datenbank.classic-wow.org/?npc=1111)) im Sumpfland droppen nicht mehr die [versengten Spinnenfangzähne](http://datenbank.classic-wow.org/?item=6838) für die Quest [Feuergehärteter Panzer](http://datenbank.classic-wow.org/?quest=1701). Ich hatte die Quest angefangen und auch schon welche gesammelt (nicht genug), jetzt wollte ich den Rest besorgen, keine drops mehr. Ich hab mich 2x durch die ganze Höhle geprügelt und auch davor (ca. 70 mobs). Sonst war mal zwischendurch eine Spinne ohne Fangzähne, aber die meisten hatten welche.

Wie sollte es sich verhalten?

Die Spinnen sollten 1-2 Fangzähne droppen.

Schritte zur Reproduzierung

Kriegerquest annehmen, Spinnen töten

**Comment by Slimmer2** [comment]
Hast du den WDB Ordner schon mal gelöscht und die Quest neu angenommen?
Evtl. hilft auch wegwerfen der Questitems, zumindest versuch es das du nur 1 wegwirft.

**Comment by dwilhelms** [comment]
danke
