### ISSUE TITLE
BWl Brutwächter der Todeskrallen

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1813]
Welches Verhalten wird beobachtet?
Diese mobs in bwl sind zurzeit nicht cc immun sie können durch scatter und stuns etc. von casten gehindert werden, außerdem kann man ihre Fähigkeit Flammenstoß unterbrechen die bewirkt das die Aura Wachsende Flammen gewirkt wird da es sich hierbei und die Kernfähigkeit dieses mobs handelt die diese besonders gemacht hatt.

Wie sollte es sich verhalten?
Diese mobs sollten nicht ccbar und interruptbar sein

Schritte zur Reproduzierung
Bwl Supressionroom Brutwächter angreifen, ccn, unterbrechen

Zusätzliche Informationen (Screenshots, Videos, etc.)
in keinem Bwl guide wird beschrieben das diese mobs einfach unterbrochen werden können stattdessen wird davor gewarnt sie in der Gruppe zu tanken und sie so schnell wie möglich umzuhauen. Es wird nur erwähnt das die Orcs im Supression room sheepbar sind

[ Einige “Death Talon Hatcher” laufen durch den Raum, die eine relativ unangenehme Aura mit einem stackenden Debuff haben. Zuletzt gibt es Dreiergruppen sheepbare “Blackwing Taskmaster”
Die Orks werden möglichst gesheept und der Reihe nach bearbeitet, während die Hatcher immer möglichst ein Stück von der Gruppe entfernt getankt werden. 
](http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/der-pechschwingenhort/nach-vaelastrasz/)

desweiteren ist der Debuff Wachsende flammen bis 100 mal stappelbar was dafür spricht den mob asap. umzuhauen, wenn man das jetzt mal logisch betrachtet wieso benutzt blizzard so eine Fähigkeit die dann noch so einfach durch cc und interrupt auszuhebeln ist?
[Drachen, die an Ziele in ihrer unmittelbaren Umgebung den Debuff Wachsende Flammen verteilen. Der Debuff fügt alle zwei Sekunden 50 Feuerschaden zu und ist bis zu 100 Mal stapelbar.](http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/Pechschwingenhort-791247/2/)

["Death Talon Hatcher" laufen durch den Raum, die eine relativ unangenehme Aura mit einem stackenden Debuff haben. Zuletzt gibt es Dreiergruppen sheepbare "Blackwing Taskmaster"](http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-end/bwl-1.html)

[Death Talon Hatcher: Single dragonkin that cannot be crowd controlled and will stack Growing Flames on the raid. Must be taken down quickly. Respawns after 10 minutes.](http://www.wowhead.com/npc=12017/broodlord-lashlayer#comments)

Ein Kommentar aus 2006 wo erwähhnt wird das die Brutwächter tanks bis zu 200 feuerresi stacken sollten wegen der Debuff Aura:
Broodlord Lashlayer
[1. The Road to the Brood: Hatcher tanks should use some FR, 200 is a decent number. This keeps healing down. Other warriors should gaurd the casters and be ready to pick up spare hatchers and orcs.
](http://www.wowhead.com/npc=12017/broodlord-lashlayer#comments)

[Death Talon Hatchers - Each room contains approximately 5-6 of these dragonkin, which are moderately tough level 61+ mobs with ~90k HP. They patrol back and forth in set paths across the width of each room. Apart from their physical attacks, they also have an AoE aura which applies a debuff called "Growing Flames". Once one of these mobs is aggro'd, its aura will pulse every few seconds. The debuff causes 50 damage every 2 sec for 6 sec, but can stack up to 100 applications (5000 dmg/2 sec). Hatchers cannot be CC'd. Hatchers must be pulled singly and tanked by a warrior at least 15 yds away from the body of the raid group, so that the raid is not continuously affected by Growing Flames. Hatchers respawn in approx. 10 minutes.
](http://leftoversraiding.org/index.php/topic/772/1/blackwing-lair-summary---pt.-1-(intro-razorgore-vaelastrasz-broodlord).html)

[Brutwächter verfügen über eine Fähigkeit namens lodernde Flammen, die auf dem ersten Blick einem flächendeckenden Feuerschlag ähnelt. Der in einem 15 Meter Radius gewirkte Zauber stapelt sich bis zu 99 Mal. Während der erste Zauber noch 50 Schadenspunkte pro Tick anrichtet, arbeitet er sich in Kürze auf 1000 und mehr hoch. 
](http://wowgilden.net/odins-legion/page_11338.html)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Brutwächter der Todeskrallen](http://datenbank.classic-wow.org/?npc=12468#drop)
[Flamestrike](http://datenbank.classic-wow.org/?spell=22275)
[Growing Flames](http://datenbank.classic-wow.org/?spell=22442)

**Comment by hraesvelgr** [comment]
eine aura sollte generell imemr ticken, egal ob der mob castet oder nicht. das casten der aura ist also unabhängig vom cc.

**Comment by Mafyo** [comment]
ja aber dieser Flamenschlag wird ja gezaubert der dann erst die Aura anfängt zu stacken. wird so zumindest beschrieben

**Comment by hraesvelgr** [comment]
nein., aura und flammenschlag sind unabhängig voneinander.

**Comment by Mafyo** [comment]
These hatchers aren’t as easy as the whelps, they have and ability called Growing Flames - it’s a short [proximity area of effect flamestrike, with one difference. It doesn’t do that much damage in the beginning (around 50 fire damage) but stay in the affected area and it will climb up to 1000+ damage per tick very fast, so tank the hatchers a few yards away from the ranged dps and healers. The melee based classes will have to be affected by the growing flames so the faster you kill the hatcher the better.](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/745-guide-bwl-complete-guide.html)

**Comment by hraesvelgr** [comment]
Flamestrike
Dauer 	8 Sekunden
Effekt #1 	School Damage (Fire)
Wert: 456
Radius: 5 Meter
Effekt #2 	Persistent Area Aura: Periodic Damage
Wert: 96
Radius: 5 Meter 
Intervall: 2 Sekunden 

da steht nichts von irgendeiner applyten aura. also sind es entweder andere spells, die die haben sollten, oder deine quelle ergibt einfach keinen sinn. in dem fall sprechen die effekte der spells gegen deine quelle.

**Comment by Mafyo** [comment]
https://youtu.be/pyYAR_eCQ9w?t=28
 hier in dem video sieht man den Pala wie er zu dem Brutwächter hinläuft und dort stehen bleibt, er bekommt keine Aura ab erst als der Flammenschlag auf dem boden erscheint er läuft kurz zurück um aus den Flammenschlag rauszukommen aber wir wissen ja alle das die Area meistens größer ist als angezeigt und der debuff stackt hoch. Das musste dann ja bedeuten er hätte die Aura schon bekommen müssen bevor Flammenschlag gezaubert wurde. Wenn  ich das Video jetzt langsamer abspiele weil es ja erhöhte geschwindigkeit ist und die Aura alle 2 sekunden aufgetragen wird und ab da zähle wo er stehen bleibt als der mob gestorben ist wird keine Aura auf ihn gewirkt erst als der Flammenschlag erscheint.

**Comment by hraesvelgr** [comment]
ich will nicht behaupten,d ass das falsch ist, nur seh ich eben keine verbindungen zwischen den beiden spells ausser eben deinen videobeweis. 

@dagochen erklärs mir :D ich finde auch in QTspellworks keine verbindung dieser beiden spells. sie werden unabhängig voneinander aufgelistet. ist das wieder so ein eventAI ding?

**Comment by Mafyo** [comment]
ja ich glaube ich habe mich  geirrt hie rim video stackt das auch ohne flamenstoß hoch tut mir leid.
https://www.youtube.com/watch?v=-C4-1MPEPF0
dennoch wird der Flammenstoß nirgends unterbrochen oder erwähnt das es möglich ist.

**Comment by dagochen** [comment]
Die 2 Zauber sind völlig unabhängig voneinander. Das eine ist eine passive Aura, die bei Spielern in der Nähe hochstacken sollte (tut sie bei uns aktuell nicht immer, weil der Debuff manchmal schon ausläuft bevor er neugecastet wird), das andere ist der Flammenstoß den der Mob einfach so macht. Die passive Aura wird aktuell nicht benutzt, sondern "manuell gecastet", was nicht korrekt ist. Mafyo hat hier glücklicherweise genau den Spell gefunden, der dieses hochstacken verursachen sollte (http://datenbank.classic-wow.org/?spell=22441). Dadurch kann ich das fixen ;)

BTT: Wogegen sollen die jetzt alles immun sein?

**Comment by Mafyo** [comment]
gegen jeglichen cc

**Comment by Mafyo** [comment]
Kurzes feedback:
das mit dem cc immun funktioniert wunderbar allerdings die flammenaura kommt irgendwie gar nicht. Heute in bwl war ich an jedem Drachen und keine gab mir einen stackenden flammen debuff. Dort müsste nochmal rübergeguckt werden

**Comment by dagochen** [comment]
Ja ist mir auch schon im Raid aufgefallen. Die Korrektur ist schon fertig und wird demnächst aufgespielt. Typischer Fall von "1 Sache gefixt und 2 kaputt gemacht" :(
