### ISSUE TITLE
Wässriger Eindringling beim Kel´Therilsee in Winterspring sind verschwunden.

### ISSUE THREAD

**Issue by Hitzee** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1814]
Wässriger Eindringling und Prinzessin beim Kel´Therilsee in Winterspring sind verschwunden.
[http://datenbank.classic-wow.org/?npc=14458](url)

**Comment by hraesvelgr** [comment]
aus gründen.

**Comment by Loplin** [comment]
Falls du dich fragst, warum dein Beitrag mit so wenigen Worten geschlossen wurde, kann ich dir das sagen:
Eine Vorlage die beim Erstellen automatisch da is, is aus gründen da.
ohne ausgefüllt Vorlage führt dein Beitrag zu nem close.

und die Eindringe sind weg weil:
_Die Elementare Invasion hat teilweise begonnen! In Winterspring, Un'goro-Krater, Azshara und Silithus patrouillieren die Bosse nun mit ihren Begleitern in ihrem Gebiet umher.
**Die Respawnzeit wurde angepasst, sodass nur noch alle paar Tage eine erneute Invasion startet.** Die Portale und das Spawnen der kleinen Elementare macht aktuell noch ein paar 
Probleme, wird aber sobald es funktioniert nachgereicht._

https://community.mmobase.de/updates-changelog/10220-update-04-11-2016-a.html

**Comment by Slimmer2** [comment]
http://forscherliga.wikia.com/wiki/Elementare_Invasion
