### ISSUE TITLE
Falsche Funktion von Hervorragendem Zauberöl

### ISSUE THREAD

**Issue by entenwahn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1817]
### Welches Verhalten wird beobachtet?

Hervorragendes Zauberöl bewirkt einen Bonus auf Heilung.

### Wie sollte es sich verhalten?

Es sollte (auch laut Item-Beschreibung) nur einen Bonus auf Zauberschaden geben.

###Schritte zur Reproduzierung

Auf Waffe auftragen und heilen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://datenbank.classic-wow.org/?item=20749 - Hervorragendes Zauberöl

**Comment by dagochen** [comment]
Der Zauber: http://datenbank.classic-wow.org/?spell=25113 

Du schreibst "auch laut Item-Beschreibung". Hast du noch andere Quellen die dies belegen? Der Zauber wie ich ihn gepostet habe ist von niemandem verändert worden und existiert so seit 2006, was dafür spricht, dass es auch Heilung erhöht hat auf den Servern von Blizzard.

**Comment by 0815Priester** [comment]
Ich denke das soll so sein. Zumindest beim 30 Spellenchant auf der Waffe gibt es folgende Notes:

http://wowwiki.wikia.com/wiki/Patch_1.12.0   **Items**

+30 Spell Damage Enchantment: Fixed a bug with this enchantment which was preventing it from benefiting healing spells.
