### ISSUE TITLE
Eine Plage komme über Euch [da seid BWL Testphase immer noch nich gefixxt]

### ISSUE THREAD

**Issue by Nwardho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1818]
Serverversion: 1.4.2

**Welches Verhalten wird beobachtet?**

Kiste wird angeklickt, Text erscheint.

**Wie sollte es sich verhalten?**

Wenn Item nicht vorhanden: Kiste wird angeklickt,  Text erscheint
Wenn Item vorhanden: Termitenfass spawnt auf der Kiste.

**Schritte zur Reproduzierung**

Einbinden: Beim anklicken von http://datenbank.classic-wow.org/?object=177490 wenn Item http://datenbank.classic-wow.org/?item=15044 vorhanden, muss http://datenbank.classic-wow.org/?object=177491 gespawnt werden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Es reicht auch, sich auf die Kiste zu stellen und .gobject add 177491 einzugeben. Hauptsache, die Quest kann nach all den Jahren mal beendet werden. Nach dem adden des Gameobjects reicht es schon, das Termitenfass anzuklicken.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/456

**Comment by Nwardho** [comment]
Habs vor Jahren schonmal gepostet. Aber scheint ja so schwer zu sein :P

**Comment by Rushor** [comment]
wenn keiner da ist um es zu fixen, geht es halt nicht schneller ;)

**Comment by Nwardho** [comment]
Is ne 2 Minuten Sache

**Comment by Nwardho** [comment]
Du kannst nem Klumpen alles fixxen,AQ oder Naxx... aber ohne Feinschliff bleibts ein Klumpen.

**Comment by Loplin** [comment]
GMs haben auch nur 2 Hände wie jeder andere auch.
Alles gleichzeitig geht nicht.
Der fix kommt, wenn er kommt :)

**Comment by Nwardho** [comment]
Nur das nicht die GM's fixxen. Die sind für was anderes zuständig.
Trotzdem bleibt die Frage wieso ne Sache von 2 Minuten seit der Erwähnung damals [mit Lösungsvorschlag] bei der ersten BWL Testphase noch immer nix getan wurde.

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/456

fixed ;) 

Aber denkt bitte nicht, dass mehrfaches Erstellen von Bugreports dazu führt, dass etwas schneller bearbeitet wird. Sowas führt in der Regel eher dazu, dass wir es links liegen lassen. Und um die Sache zu komplettieren: Es war vergleichsweise kompliziert den genauen Fehler zu finden und hat ~2 Stunden gedauert, zusätzlich kamen noch 30 Minuten Recherche, was diese Quest mit BWL zu tun haben soll...
