### ISSUE TITLE
Zeppelin spawnt am Anleger und fährt sofort ab

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1823]
Welches Verhalten wird beobachtet?
Der Zeppein (in diesem Fall UC -> GG) spawnt plötzlich am Anleger und fährt sofort los, sodass man keine Chance hat, den Zeppelin zu betreten.

Wie sollte es sich verhalten?
Der Zeppelin fährt an den Anleger heran, wartet dort eine Weile und fährt wieder ab.

Schritte zur Reproduzierung
Leider ungewiss, da das Phänomen nicht immer auftritt. Ich beobachte jedoch des Öfteren, dass der Zeppelin nicht anfährt, sondern einfach spawnt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
keine

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Kann das jemand bestätigen?

**Comment by Slimmer2** [comment]
Hast du den WDB Ordner schon mal gelöscht?
Evtl. behebt das dass Problem

**Comment by Pexus6** [comment]
Das halte ich für unwahrscheinlich. Ein Kollege hat das Szenario ingame auch beobachtet.

**Comment by dagochen** [comment]
Du hast nicht zufällig nen Mac-Client? Die haben ja öfter mal Probleme mit Schiffen und Zeppelinen?

**Comment by Pexus6** [comment]
Ne, ganz normaler Windows Client.

**Comment by dagochen** [comment]
Wie oft tritt das denn auf? Jedes 2x mal? Einmal in der Woche? Einmal im Monat? Einfach um die Relevanz festzulegen ;) 

Oder kannst du irgendwie ein Muster oder Auffälligkeiten feststellen, wann es auftritt, sprich wie man es reproduzieren kann?

**Comment by Pexus6** [comment]
Also in der extremen Form ist es mir erst 1x aufgefallen. Dass das Schiff einfach spawnt, aber noch wartet tritt so 1-2x die Woche auf, würde ich sagen. Ein Muster kann ich leider nicht feststellen.

**Comment by ulle182** [comment]
Kann ich bestätigen, ist allerdings schon ca. 3-4 Monate her und habe es auch nur ein einziges mal beobachtet, als ich mal gefühlt ewig auf den Zeppelin gewartet habe (inzwischen Premium).
