### ISSUE TITLE
Ouro Erdbeben

### ISSUE THREAD

**Issue by armaggedon1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1824]
Welches Verhalten wird beobachtet?
Die Erdbeben bei Ouro bewegen sich seit heute wesentlich schneller als sonst. Es ist somit unmöglich wegzulaufen. Am Sonntag ging das noch problemlos

Wie sollte es sich verhalten?
Es sollte möglich sein vor den Erdbeben wegzulaufen
so wie hier:
https://www.twitch.tv/airwolf80/v/100879811
ab ca 02:56:50

Schritte zur Reproduzierung
Ouro pullen, warten bsi er untertaucht udn versuchen die Erdbeben zu kiten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.twitch.tv/airwolf80/v/101449354
ab ca 21:00

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15517
http://datenbank.classic-wow.org/?spell=26093 (sollte das richtige sein)

**Comment by Badorr** [comment]
Das hier sollte der Beschwörungsspell(?) sein http://datenbank.classic-wow.org/?spell=26058

**Comment by pdglala** [comment]
Früher war es auch nicht möglich vom Erdbeben davon zu laufen.
Das ist weniger ein Bug, als das dies angepasst worden ist.
Jedoch macht das Erdbeben wesentlich mehr Schaden als es früher der Fall war. Deswegen ist diese Kombination tödlich.
Jetzt stellt sich die Frage was genau angepasst werden sollte.

https://www.youtube.com/watch?v=xar0Lf_oC-k
https://www.youtube.com/watch?v=wWqgy_aXEaI
600-700er ticks macht das Erdbeben.

https://www.youtube.com/watch?v=REmX3uRTFkQ
Das Video zeigt den Encounter sehr gut. Ab 2:30 beginnt das Erdbeben.

BTW: Das ganze hat keine 10 Min an Recherche gebraucht. Wenn Ihr schon ein Ticket aufmacht, dann macht das auch Richtig!

P.S.: Dotox, seit wann sind Streams von dem Server als Quelle zureichend?

**Comment by armaggedon1** [comment]
Nun es hat bisher auf dem Server so funktioniert und nun auf einmal nicht mehr, ich bin einfach davon ausgegangen, dass es so auch sein soll. Aber Gottseidank haben wir ja die Bugtrackerelite...

**Comment by armaggedon1** [comment]
Ausserdem was heisst hier "Ihr", den Bugreport hab ich allein verbrochen.

**Comment by Badorr** [comment]
Stimme armageddon1 absolut zu. Der Boss funktioniert in Bezug auf die Erdbeben jetzt schon fast 1 Jahr lang genau so. Auf einmal funktioniert es anders, offensichtlich aufgrund einer beabsichtigten(?) Änderung, die nicht im Geringsten nach außen hin kommuniziert wurde. Oder wie darf ich pdglala in dieser Hinsicht verstehen?

**Comment by Dotox** [comment]
Gab einige Movement-Änderungen die sich offensichtlich negativ auf den Bosskampf ausgewirkt haben. Geplant war das allerdings nicht.

**Comment by Badorr** [comment]
Das mit den Erdbeben sieht jetzt ok aus, dafür wirft der Boss ab der Enragephase jtzt ständig Steine auf irgendwelche Leute, auch wenn Spieler in Meleerange sind.

**Comment by Mafyo** [comment]
Das mit dem Stein wurf hab ich auch von eingien Castern gehört vielleicht dazu einen extra Reort eröffnen?
