### ISSUE TITLE
Kristallstachelschlägel nicht erhältlich

### ISSUE THREAD

**Issue by thedancebear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1825]
Welches Verhalten wird beobachtet?

Ist auf nefarian  nicht erhältlich

Wie sollte es sich verhalten?

Sollte im beutesack (sack of spoils) in silithus als rnd drop erhältlich und verkaufbar sein

Schritte zur Reproduzierung
-
Zusätzliche Informationen (Screenshots, Videos, etc.)
Hier ein Link den ich dazu gefunden habe:
http://shoot.tauri.hu/?item=20696
http://www.wowhead.com/item=20696/crystal-spiked-maul (ab 1.11.1 zu bekommen)
http://db.vanillagaming.org/?item=20696

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://datenbank.classic-wow.org/?item=20696

**Comment by thedancebear** [comment]
Hier noch der Link zum Beutesack in unserer Datenbank: http://datenbank.classic-wow.org/?item=20601#contains erhältlich bei Bor Wildmähne in Silithus für 3 Wappen.

Viele Grüße und Danke fürs Prüfen.
Thedancebear.
Ps:
Leider gibt es die alten throttbot links nicht mehr, sonst könnte ich mehr beweise und dropchancen finden.

**Comment by Rushor** [comment]
versuchs ma hiermit https://archive.org/web/ @thedancebear

**Comment by dagochen** [comment]
auch nur schwer oder garnix zu finden, da allakhazam loot aus items nicht immer getracked hat.

**Comment by thedancebear** [comment]
Hallo Rushor, 
Danke für die Hilfestellung. Leider habe ich es auch dort schon versucht. Aber es ist trotzdem sehr schwer solche alten Datenbanken auszuleseb bzw zu finden.

@Dago: heißt dev behoben, dass der bug gefixt wird? Oder brauchst du noch mehr Informationen? Dann begebe ich mich direkt ins Netz...

**Comment by dagochen** [comment]
Da es auch ein Rare Item ist habe ich die Chance von den anderen Rare Items in dem Beutel leiten lassen, da ich selbst nach längerer Recherche keine Werte von damals finden konnte. Falls du doch noch was findest wär das natürlich besser, aber nicht zwingend notwendig. Das Item wird so oder so sehr sehr selten bleiben, sprich ob es jetzt 0,1% oder 0,5% oder 1% Chance hat, macht nicht wirklich einen großen Unterschied.
