### ISSUE TITLE
Rarmob Kommandant der Schattenschmiede

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1827]
Welches Verhalten wird beobachtet?
er droppt kein grünes items

Wie sollte es sich verhalten?
er sollte mindestens ein grünes item droppen

Schritte zur Reproduzierung
Kommandant der Schattenschmiede angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
[He roams the top level of the Angor Fortress, where the plane hangars are. Rare NPC on a fairly long timer, 12-24 hours or so. Almost always drops a green item.](http://de.wowhead.com/npc=2744/kommandant-der-schattenschmiede#english-comments)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=2744#drop

**Comment by dagochen** [comment]
"almost" :P und TBC....
