### ISSUE TITLE
NPc Gruftwandler

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1832]
Welches Verhalten wird beobachtet?
Der Mob benutz seine Fähigkeit Cripple nicht

Wie sollte es sich verhalten?
er sollte sie benutzen

Schritte zur Reproduzierung
Gruftwandler angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=8556#abilities
http://datenbank.classic-wow.org/?spell=20812

**Comment by hraesvelgr** [comment]
dazu konnte ich leider garkeine quellen finden. er npc hat nichtmal einen wowwiki eintrag.

**Comment by Rushor** [comment]
dachte der sollte web usen?

```sql
-- Crypt Walker SAI
SET @ENTRY := 8556;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,1000,3000,10000,15000,11,745,0,0,0,0,0,5,0,0,0,0,0,0,0,"Crypt Walker - In Combat - Cast 'Web'");
```

**Comment by Mafyo** [comment]
web macht er

**Comment by dagochen** [comment]
Das Cripple passt irgendwie auch besser zu den anderen Mobs in dem Gebiet oder?

**Comment by Mafyo** [comment]
Cripple machen diese Kultisten dort. Auf wowhead hat der Gruftwandler auch eine Gift Attacke anstatt
