### ISSUE TITLE
Npc Verfluchter Magier

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1833]
Welches Verhalten wird beobachtet?
er benutz die Fähigkeit Tainted Mind nicht

Wie sollte es sich verhalten?
er sollte die Fähigkeit einsetzen wenn er stirbt und einen Fluch auf einen zaubern die einem die Intiligenz um 20% senkt

Schritte zur Reproduzierung
Magier angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Cursed_Mage?oldid=2087576

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=8524#abilities
http://datenbank.classic-wow.org/?spell=16567

**Comment by Rushor** [comment]
in cai umwandeln:

```sql
-- Cursed Mage SAI
SET @ENTRY := 8524;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,0,0,3400,4800,11,20829,64,0,0,0,0,2,0,0,0,0,0,0,0,"Cursed Mage - In Combat - Cast 'Arcane Bolt'"),
(@ENTRY,0,1,0,6,0,100,1,0,0,0,0,11,16567,7,0,0,0,0,2,0,0,0,0,0,0,0,"Cursed Mage - On Just Died - Cast 'Tainted Mind' (No Repeat)");
```
