### ISSUE TITLE
Animationen Fehlerhaft

### ISSUE THREAD

**Issue by Elathar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1834]
Steinkrallengebirge  ( Der Steinkrallengipfel) + Scherwindklippe 
Gegner die mit Fernkampfwaffen schießen, verschießen anstatt Munition blau/weiße Quadrate

**Comment by dagochen** [comment]
Welche Mobs? Bitte verlinken.

**Comment by Pexus6** [comment]
Möglicherweise das hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1837

**Comment by dagochen** [comment]
Ich nehm mal den 1837, der ist besser dokumentiert ;) und mach hier zu.
