### ISSUE TITLE
'Holzarbeiter der Venture Co.' (ID: 3989) wirft mit unbekanntem Objekt

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1837]
Welches Verhalten wird beobachtet?
Beim Pull aus der Distanz wirft der Mob mit einem Weiß-blau-karierten Würfel.

Wie sollte es sich verhalten?
Beim Pull aus der Distanz wirft der Mob mit einem Beil.

Schritte zur Reproduzierung
Mob aus Distanz (z.B. mit Bogen) pullen

Zusätzliche Informationen (Screenshots, Videos, etc.)
keine.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=3989

**Comment by Rushor** [comment]
creature_equip_template fehlt sicherlich
