### ISSUE TITLE
Quest 'Weitere Instruktionen' hat zu hohes Anforderungslevel

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1838]
Welches Verhalten wird beobachtet?
Die Quest 1094 kann erst ab lvl 21 angenommen werden.

Wie sollte es sich verhalten?
Die Quest 1094 kann ab lvl 17 angenommen werden.

Schritte zur Reproduzierung
Quest 'Ziz Fizziks' abschließen, Quest 'Superschnitter 6000' abschließen, Versuchen, Quest 'Weitere Instruktionen' mit lvl <21 anzunehmen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Kann den Fehler leider nicht aus offizieller Quelle bestätigen.
Die Tatsache, dass sich die Folgequest 'Weitere Instruktionen' (1095) aber wieder ab lvl 17 annehmen lässt, lässt auf einen Fehler schließen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?quest=1094/Weitere%20Instruktionen

**Comment by Slimmer2** [comment]
Blizzard hat mehrere solche Quest gemacht
