### ISSUE TITLE
Bewegungsunfähige Kreaturen greifen nicht an

### ISSUE THREAD

**Issue by r4yn0r** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1839]
Welches Verhalten wird beobachtet?
Wird ein Zauber verwendet, welcher Bewegungsunfähigkeit bei Kreaturen verursacht, so wechseln diese das Ziel auch dann nicht, wenn es außer Reichweite ist auf den nächsten Spieler, sondern stehen still und tun nichts.

Wie sollte es sich verhalten?
In dem Moment, wo die Kreaturen bewegungsunfähig sind und das anvisierte Ziel der Kreaturen nicht in Reichweite ist, sollten sie unmittelbar Jedes Ziel in Reichweite alternativ angreifen.

Schritte zur Reproduzierung
Einfach mit einem Krieger eine Kreatur antanken und anschließend den Zauber Frostnova (http://datenbank.classic-wow.org/?spell=10230) mit einem Magier benutzen, mit dem Magier in Reichweite stehen bleiben und mit dem Krieger außer Reichweite laufen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
In diesem Gluth Video sieht man sehr schön, dass kein Magier in Reichweite steht, wenn die Adds gefreezed werden, bevor sie alle mit Blizzard und Feuerregen gebombt werden.
https://www.youtube.com/watch?v=Qm8XFai_T4g
2 Min 40 sec

Leider habe ich nach mehreren Stunden Suche auf Youtube kein Video gefunden, in welchem die Spieler, die an den bewegungsunfähigen Kreaturen dranstehen geschlagen werden. Vielleicht kann ja Jemand bei der Recherche helfen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Bei welchen Kreaturen hast du das Problem denn beobachtet, damit man es reproduzieren kann?

**Comment by Slimmer2** [comment]
Evtl. Ist es ja kein Fehler. Wenn du nicht mal ein Video findest, das es so sein sollte wie du beschreibst.

**Comment by r4yn0r** [comment]
Der Punkt ist halt, man findet lediglich nur noch Videos von Top Gilden in größeren Raidinstanzen. Diese sieht man nie Zauber wie Arkane Explosion (http://datenbank.classic-wow.org/?spell=10202) verwenden. Denke das hat mit Sicherheit einen Grund.

Kann man auf allen Videos immer beobachten, wenn gebombt wird.

**Comment by r4yn0r** [comment]
Habe noch weiter Videos durchgesucht - hier sieht man zumindest, dass die bewegungsunfähige Herren der Atal´ai den Spieler sofort schlägt, welcher in Reichweite ist, wenn man genau darauf achtet:
https://www.youtube.com/watch?v=63t9EXBfc44
1h 23 min 40 sec

**Comment by dagochen** [comment]
Das ist aber von einem anderen Privat-Server :)

**Comment by r4yn0r** [comment]
ich sehe es gerade, steht darunter von kronos :)

**Comment by Loplin** [comment]
Hab jz mal 10min Videos gesucht.
das is das beste das ich bisher gefunden hab:

https://www.youtube.com/watch?v=101yB_D9gzs

bis Minute 2:57
viel gebombe

Minute 2:58
Frostnova 

Minute 3:00
Priester bekommt von 7 Mobs schläge/effekte
Erkennbar im chatlog (rote Schrift) sowie am Charakterbild. Mal 102 dmg mal 82.
Außerdem drehen sich nahezu alle mobs zu ihm, scheinbar weil er am nähesten steht.

Minute 3:07
Freeze bricht

Minute 3:10
Mobs wieder eingefroren
Die beiden hintersten drehen sich zum Priester.

**Comment by dagochen** [comment]
Vllt noch eine zweite, bessere Quelle?

**Comment by Mafyo** [comment]
[A rooted mob that has no ranged attacks will be unable to attack its current aggro target. However, if players are standing in melee range, it will attack the player that has the highest threat level. Thus, it is not wise to stand near a rooted mob. Also, it is not wise to root a mob next to a player that has some threat on it, as it might get him killed. ](http://wowwiki.wikia.com/wiki/Root?oldid=997084)

allerdings aus BC

**Comment by Mafyo** [comment]
[If certain abilities impair the access of the mob to its higher threat-ranked targets (e.g. root spells), the mob will attack the highest threat-ranked target in its ability range (usually visible for melee mobs or silenced casters, which have a combat range of 5 yards) ](http://wowwiki.wikia.com/wiki/Aggro?oldid=386035)
 

wowwiki 2006
