### ISSUE TITLE
Blut von Helden looten fehlerhaft

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1842]
**Welches Verhalten wird beobachtet?**

Wenn man den Gegenstand Blut von Helden looten will dann wird man von einem Zauber namens "Absitzschlag" getroffen. Dieser bricht den Lootvorgang ab und wirft den Spieler nach hinten. Danach spawnen 2 Elite-Gegner und greifen den Spieler an.

**Wie sollte es sich verhalten?**

Man sollte das Blut von Helden ganz normal looten können, ohne dass man vom Zauber "Absitzschlag" getroffen wird. Nachdem man das Blut gelootet hat sollten 2 Elite-Gegner spawnen und den Spieler angreifen.

**Schritte zur Reproduzierung**

Ein Blut von Helden looten.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Leider scheint es kein Video mehr aus dem Jahre <= 2006 zu geben welches das richtige Verhalten zeigt. Ich habe eins gefunden, was aber aus BC-Zeiten zu sein scheint:
https://www.youtube.com/watch?v=Y47w5nh6jOE

Auf wikia.com stehen auch Strategien wie man das Ding looten kann. Und da gibt es keinerlei Hinweise darauf, dass man beim Looten zurückgeschleudert wird.

http://wowwiki.wikia.com/wiki/Blood_of_Heroes?oldid=368729

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

http://datenbank.classic-wow.org/?item=12938
http://datenbank.classic-wow.org/?npc=10996

Edit: Beim "Absitzschlag" scheint es sich um diesen Zauber zu handeln:
http://datenbank.classic-wow.org/?spell=18396

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/spell=18396/dismounting-blast#comments
scheint es nur bei den trollen in ZF zu geben.

**Comment by Larnak1** [comment]
Mh, ich hab da gerade gestern auch welche gelootet. Aus einem kam ein Geist raus, aus einem anderen gar keiner. Zwei Geister habe ich da gar nicht gesehen.

**Comment by dagochen** [comment]
Das ist Random @Larnak1

**Comment by Larirawiel** [comment]
Mir geht es weniger um die Mobs, die da spawnen sondern um den Zauber "Absitzschlag"/Dismounting Blast. Weil der sorgt dafür, dass man das Ding unmöglich looten kann. Denn bevor das Lootfenster aufgeht wird man davon getroffen und zurückgeschleudert. Und selbst die Pala-Bubble hilft dagegen nicht.

Grüße

**Comment by dagochen** [comment]
Ich konnte bisher mit Shiftloot immer looten. Aber nichtsdestotrotz gehört der Spell da natürlich nicht hin^^
