### ISSUE TITLE
NPC 'Quetschzahn' gibt beim Einreichen von Blutsplittern keine Buffs

### ISSUE THREAD

**Issue by mbecker6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1843]
Welches Verhalten wird beobachtet?
Der NPC bietet versch. Daylies an. Beim Einreichen von Blutsplittern bekommt man div. Buffs.
Zwar kann man die Quests abgeben und die Blutsplitter verschwinden aus dem Inventar, jedoch bekommt man keine Buffs.

Wie sollte es sich verhalten?
Man bekommt bei Questabgabe einen Buff.

Schritte zur Reproduzierung
Quest abgeben

Zusätzliche Informationen (Screenshots, Videos, etc.)
Beispielquest: http://datenbank.classic-wow.org/?quest=5043
Beispielbuff: http://datenbank.classic-wow.org/?spell=17013

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=3430

**Comment by Slimmer2** [comment]
Hast du bei der Questabgabe einen Buff bereits aktiv der Beweglichkeit erhöht?

**Comment by Pexus6** [comment]
Nein

**Comment by Pexus6** [comment]
Hat mit keinem Buff funktioniert

**Comment by dagochen** [comment]
https://github.com/cmangos/mangos-classic/pull/230

**Comment by robinsch** [comment]
Ja wurde genau desswegen gecoded.

**Comment by dagochen** [comment]
@robinsch Wenn man den Käfig aber auf macht, müsste er ja eigentlich LOS haben. Oder erkennt der beim Zaubern nicht den aktuellen Zustand eines GO?

**Comment by robinsch** [comment]
Funktioniert wie du beschrieben hast leider nur bei einigen Gameobject Typen.
