### ISSUE TITLE
Procrate Ironfoe

### ISSUE THREAD

**Issue by imbaan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1844]
Welches Verhalten wird beobachtet?
Die Chance der Waffe Ironfoe ( http://datenbank.classic-wow.org/?item=11684 ), dass die zusätzlichen 2 Waffenschwünge ausgeführt werden ist zu niedrig (liegt derzeit bei ~ 5%).

Wie sollte es sich verhalten?
Die Procrate sollte höher sein, wobei die Werte im Netz sehr stark variieren (10-20%).
Schritte zur Reproduzierung
Über Procwatch Daten sammeln und das zu beobachtenden Event ( engl. Fury of Forgewright) angeben. 
Zusätzliche Informationen (Screenshots, Videos, etc.)
Gestern Abend habe ich einen Aq40 Raid damit aufgezeichnet und habe folgende Daten erhalten:

Total Hits: 2900
Procs: 147
Hits/Proc: 19.7
Procs/Min: 1.5

Das ergibt den oben angegebenen Wert von ~5%.

Quellen bzgl Procrate Vermutungen:

http://wowdata.buffed.de/item/Waffe/Streitkolben/Eisenfeind-11684#comments
#12 Gast im May 2006
"Wenn man Streitkolben 300 hat mit ca. 10%
Überraschenderweise bei Streitkolben 299 nichteinmal halb so oft (WTF ?)"

http://www.wowhead.com/item=11684/ironfoe#comments
By Eeolya (1,404 – 1·12) on 2008/05/14 (Patch 2.4.2)
"Few people know about this but the proc isn't 2 extra attacks.

I have had this weapon with my warrior since level 56. Thats close to three years ago.

The proc is a repetition of the attack it proced on. I still use Ironfoe in BT/MH and Sunwell. As a Fury warrior once the boss gets under the 20% range I swap Ironfoe and get TRIPLE 3k executes. This weapon still pumps out severe DPS even at level 70 when used in the correct situation.

The proc isn't a PPM either. Procwatch is queasy about it. It ranges from 10 to 18% oddly. However there is no internal CD. Meaning that under Flurry, DST and a haste potion it's proc galore."
 
Viele weitere Kommentare beinhalten eine sehr hohe Procrate, auch wenn keine konkreten Zahlen genannt werden - trotz späterer Patches, in denen die Procrate reduziert wurde.

http://www.wow-one.com/forum/topic/23044-about-ironfoe/
"First of all, I'd appreciate it if someone who uses Ironfoe in PVE (MC/BWL/AQ40) would respond :)

I saw that they did some changes on Ironfoe and I would like to know if it stil procs the same or close to what it used to proc. And no, I don't think it's bugged since even on retail it didn't have an internal CD and proc rate was 16-20% from what I remember. Thank you."

https://vanilla-twinhead.twinstar.cz/?issue=718
items Waffenproc
PPM = (%/100) * 60 / weapon speed

Weapon Chance on Hit procs:
Ironfoe = 10%; ppm = 2,5

Als eine weitere Quelle die über eine andere Berechnung die Procrate herbeileitet.

Über eine rege Diskussion, Meinungen und gerne auch weitere Quellen würde ich mich sehr freuen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Und wie ist es jetzt richtig?

**Comment by imbaan** [comment]
Naja die 5% die derzeit bestehen scheinen ja definitiv falsch. Welche der genannten Quellen die hier zulässigen Gütekriterien erfüllt weiß ich nicht.

**Comment by Larnak1** [comment]
Der einzige als Quelle brauchbare Kommentar ist wohl der erste, und der ist sehr schwammig und deutet auf irgendwas zwischen 5 und 10% hin.

**Comment by imbaan** [comment]
Ich weiß jetzt nicht welche Quelle du gelesen hast  aber 5% steht nirgends, das ist lediglich der Wert den unser Server verwendet. Die Frage wäre mMn eher 10% oder mehr? Sprich auf 10% hochsetzen und dann gucken ob evtl. noch weitere Quellen gefunden werden, die genauere Daten/Werte liefern.
Außer das Team sagt, dass sie einer Quelle mehr Vertrauen schenken als Anderen und folgend eben jener.

**Comment by Larnak1** [comment]
Dein erstes Zitat spricht von einer Erfahrung, bei dem der Auto einerseits 10% und andererseits "nicht einmal halb so viel" beobachtet hat.

**Comment by Rushor** [comment]
such vlt. mal hier nach weiteren quellen:

https://www.google.de/search?q=Ironfoe+proc&biw=1680&bih=941&source=lnt&tbs=cdr%3A1%2Ccd_min%3A06.06.2004%2Ccd_max%3A06.06.2006&tbm=

**Comment by imbaan** [comment]
Das steht ja bei Waffenskill 299 - das sind ja unterschiedliche Ausgangspositionen.
Quellen auch alte habe ich bereits alle durch und leider nichts hilfreiches gefunden.

**Comment by Larnak1** [comment]
Mir wäre nicht bekannt, dass Waffenskill eine Auswirkung auf Proc-Chancen haben sollte. In jedem Fall bleibt die Aussage sehr schwammig und uneindeutig

**Comment by Kraftprotz** [comment]
interessante info: Auf Kronos war/ist die Proccchance 10%, womit Ironfoe sowohl DPS als auch TPS-technisch gesehen mit Worldbuffs  eine der, oder die stärkste Einhandwaffe ist. 

Das hat dann dazu geführt, dass sich jeder das Ding in BRD farmen wollte, schwieriges Thema

**Comment by imbaan** [comment]
Wüsste nicht was daran schwierig sein sollte. Wenn die 10% denn blizzlike sind, dann sollte eben jener Wert auch angesetzt werden. Über know-how heute zu damals müssen wir denke ich nicht reden. Das eine Waffenkombination aus IF + x getragen werden kann und diese Dps technisch viable bis nach Naxx ist, ist kein Geheimnis. Mit den derzeitigen 5% ist sie es nicht.

**Comment by rooty113** [comment]
Aus dem Allakhazam-Webarchiv, klingt zumindest brauchbar.
War zwar zu Patch 1.11.2, aber sofern in 1.12.1 nichts mehr geändert wurde, könnt es wohl gelten:

[http://web.archive.org/web/20070821131917/http://wow.allakhazam.com/item.html?witem=11684](vorletztes Kommentar dort)

"After some testing on a Servant mob in the Blasted Lands, I have a more accurate idea of the proc rate. All testing was done on the same level 53 "Servant of Grol" wielding Ironfoe along with a shield. All attacks were either auto-attacks, Bloodthirst or Revenge (all of which I believe are capable of triggering Chance on Hit effects). I used no other equipment that granted extra attacks, although I did have Crusader enchanted and enough Heroism equipped for the "chance on hit to heal" set bonus.

In all I attacked the mob 3,226 times with Ironfoe, and recieved 87 extra attack procs (counting the combatlog message "You gain 2 extra attacks from Fury of Forgewright." as a single proc). 42 of those attacks were partially blocked (but still did damage), 62 were dodged, 32 were parried, and none missed.

This would make the proc rate 2.70%, or 0.675 procs per minute. For comparison, Crusader is believed to be approximately 1 proc per minute (I found 1.07 procs per minute in my testing). It should be noted that "procs per minute" refers to how often it would be expected that a Chance on Hit activates for a character simply auto-attacking without using any special abilities, or attack speed increases - in practice the proc rate will be higher.

So basically, the weapon seems to have approximately a 2.70% chance on each attack to cause you to gain two further attacks.

This test was performed on the live WoW servers, under version 1.11.2"

**Comment by Umkaluabo** [comment]
Kann ich noch ein paar Quellen einfügen und es wird wieder geöffnet?

**Comment by dagochen** [comment]
klar

**Comment by Umkaluabo** [comment]
http://wowdata.buffed.de/item/Waffe/Streitkolben/Eisenfeind-11684#comments
Bei #12 meinte auch einer dass der Proc bei 10% ist, was jedoch auch zu Anfangs schonmal geschrieben wurde

https://www.wow-freakz.com/spells.php?spell=15641&name=ironfoe
http://de.wowhead.com/spell=15641/eisenfeind
http://db.wowraider.net/spell/15641/de/Eisenfeind
Procchance 10% ist zwar auf dem aktuellen Patch, aber dazu kommt im Anschluss noch eine Quelle

https://eu.battle.net/forums/en/wow/topic/12618563175
Ylsor schrieb hier im Forum auch, dass sie jede Menge Waffen geändert haben, jedoch Eisenfeind nicht, deshalb findet man auch keine geänderten Patchnotes zu Eisenfeind, ergo ist die aktuelle Procchance auch die zu Vanilla

http://www.wow-one.com/forum/topic/49737-ironfoe-nerfed-or-not/
Hier im Forum war der Proc auf einem anderen Server zu hoch und framerate schrieb, dass er auf 10% gepatched wurde.

http://www.4players.de/4players.php/download_info/Downloads/Download/45381/World_of_WarCraft/Patch_v1110_-_v1111.html
Auf WoWHead steht, dass er mit dem Patch Hinzugefügt in Patch 1.11.1.5462 hinzugefügt wurde.
Vielleicht kann man hier dann auch die Procchance auslesen?

Ich kann beim besten Willen keine Quelle finden, bei der die Procchance niedriger als 10% ist. :-)
Alles was ich immer gefunden habe, ist dass er keinen interen CD hat und bei jedem Waffenschwung ausgelöst werden kann, auch bei seinem eigenen.
