### ISSUE TITLE
High Priest Venoxis

### ISSUE THREAD

**Issue by imbaan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1846]
Welches Verhalten wird beobachtet?
Der genannte Boss in Zul'Gurub ( http://datenbank.classic-wow.org/?npc=14507 ) castet seine Fähigkeit Heiliger Zorn obwohl die Vorraussetzung dafür nicht erfüllt ist.

Wie sollte es sich verhalten?
http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-ZulGurub-791242/7/

"Heiliger Zorn
Wenn zu viele Schlachtzug-Mitglieder an Venoxis stehen, fühlt dieser sich bedrängt und lässt eine Schockwelle los, welche die ganze Schlachtgruppe auslöschen kann. Deswegen dürfen maximal fünf Teilnehmer in den Nahkampf: Haupt-Tank + vier andere. Aber keine Jäger-Pets!"

Schritte zur Reproduzierung
Nach ZG gehen und den Boss pullen, dabei einen weiteren Melee mit dem Tank an Venoxis stellen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Von wann ist der Guide den du da zitierst?

**Comment by imbaan** [comment]
Hallo Dago, 
Der Guide ist von 2009 allerdings fasst dieser die Raids zusammen und bezieht sich ausschließlich auf damalige Tatsachen. Für weitere Quellen bzgl dieser Taktik:
http://wowwiki.wikia.com/wiki/High_Priest_Venoxis_(original)

"Holy Wrath can be avoided. If you keep no more than three people meleeing him (or anywhere near him for that matter), he will not spazz out and cast Holy Wrath."

"only 5ppl in melee range from boss else he might AoE and wipe some raid members. so if your more then 5 melee classes tell them who is going to stand in raid using ranged weapon (pref. a def tank is somehow the boss gets loose for backup"

"Regardless, it is perfectly possible to do Venoxis with no mana draining - and almost certainly easier, in fact. Keep only 2-3 characters in melee range in phase 1, and the rest at 20 yards+ and he will not use Holy Wrath at all."

**Comment by pinfi32** [comment]
Ich habe eher den Eindruck das der Holy Wrath Spell komplett fehlt, zumindest ist er in der Datenbank nicht als Fähigkeit erwähnt.

Lauf dem Wowwiki Artikel soll er 3 Fähigkeiten Offensive Fähigkeiten in Phase 1 haben. 
Holy Fire = Heiliges Feuer castet er aktuell auf ein beliebiges Raidmitglied, der buffed Guide behauptet er castet es nur auf den Maintank, der Wowwiki Artikel spezifiziert nicht auf wen es gecastet wird. Funktioniert vermutlich wie beabsichtigt.

Holy Nova = Heilige Nova castet er aktuell nur wenn zusätzliche Melees neben dem Tank am Boss stehen, funktioniert also wie es eigentlich bei Holy Wrath beschrieben ist. Ob das nun korrekt ist oder nicht ist aus keinem der Guides ersichtlich, der Buffed Artikel erwähnt den Spell nichtmal, der Wowwik Artikel erwähnt ihn erwähnt aber nicht unter welcher Vorrausetzung er benutzt wird.

Holy Wrath = Heiliger Zorn ist der Spell übereinstimmend als gefährlich beschrieben wird und nur gecastet wird wenn mehr als  3 ( wowwiki) oder 5 (buffed) in Meleerange stehen. Dieser Spell verdoppelt seinen Schaden mit jedem Sprung, springt max 10 Meter/Yards weit und funktionert im wesentlichen wie der C'thun Spell in Phase 1. Er taucht in der Datenbank aktuell aber gar nicht auf und ist möglicherweise gar nicht vorhanden.

**Comment by imbaan** [comment]
Wenn ich das richtig sehe, dann verhält es sich wie folgt:

- Wenn bereits nur ein weiterer  Nahkämpfer am Boss steht fängt er an Holy Nova zu casten. Diese trifft die Spieler unmittelbar in seiner Nähe und dabei würde es auch bleiben....aber....
- Wenn nun weitere Nahkämpfer zu nah stehen (Yard Angabe), dann fängt eben jener Spell an zu linken (Holy wrath ist dann ein instant) sprich es existiert derzeit nur ein Spell in der Datenbank, weil jene gekoppelt sind und zwar scheinbar mit folgender Verknüpfung:
Wenn mehr als ein Spieler am Boss steht, dann castet er HolyNova, welche direkt zu HolyWrath wird sofern die Range es erlaubt

**Comment by dagochen** [comment]
> Poison cloud CAN be cured!! However, there are some warnings. If you stand in the cloud while being cured, the cloud will repoison you. Furthermore, if you are depending on the Poison Cleansing Totem, you are bound to run out of the reach by the time it could have saved you. The best advice would be for one healer to be on curing duty and he/she should cure only when the tank has gotten out of the cloud. This should save at least 2.5K health (500dmg per second, 10 second buff), and can make a big difference (in theory).

Das funktioniert auch noch nicht oder?
