### ISSUE TITLE
Jäger: Nahkampfangriffskraft skaliert nicht mit Stärke

### ISSUE THREAD

**Issue by xsicht** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1847]
**Welches Verhalten wird beobachtet?**
Stärke erhöht beim Jäger die Angriffskraftwertung nicht
**Wie sollte es sich verhalten?**
Die Angriffskraft sollte sich erhöhen, sobald ein Item angelegt-, oder ein Buff mit Stärke gewirkt wird
**Schritte zur Reproduzierung**
Item mit Stärke anziehen, Stärkebuff wirken
**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Tooltop Stärke beim Hunter

Ich konnte leider keine Quellen finden, wie viel 1 Stärkepunkt bringen sollte, ich denke aber, dass es 2 Attackpower sein sollte. Es ist schwierig, Quellen zu finden, da damals wohl niemand auf die Idee kam, einen Hunter im Nahkampf zu spielen. Ich denke aber, dass die Nahkampfangriffskraft auf jedenfall mit Stärke skalieren müsste, da es auch im Tooltip steht

**Comment by dagochen** [comment]
Funktioniert bei mir einwandfrei.
![wowscrnshot_120816_183207](https://cloud.githubusercontent.com/assets/5236186/21020406/a93312b0-bd74-11e6-8ca6-d6380e986cf5.jpg)
![wowscrnshot_120816_183153](https://cloud.githubusercontent.com/assets/5236186/21020407/a9336d14-bd74-11e6-981e-fb1e89186c78.jpg)

**Comment by hraesvelgr** [comment]
1 stärke = 1 ap. skaliert halt grottig, fällt ingame deshalb fast nicht auf.

**Comment by Slimmer2** [comment]
Ist 1 Stärke nicht 2 melee-AP

**Comment by hraesvelgr** [comment]
nicht beim hunter. ist bei den klassen ja unterschiedlich

**Comment by Slimmer2** [comment]
Bei Items wird AP nicht erhöht
![unbenannt](https://cloud.githubusercontent.com/assets/8680824/21023288/23da753e-bd80-11e6-961c-3d2930c132b0.PNG)

**Comment by hraesvelgr** [comment]
schaust du bei angriffswertung oder bei angriffskraft?
