### ISSUE TITLE
Fischschwarm unendlich lootbar

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1848]
Welches Verhalten wird beobachtet?

Es ist einem möglich den Fischschwarm die ganze Zeit zu Angeln. Mehr wie Friedensblume ist da aber  nicht drin 

Wie sollte es sich verhalten?

Es sollte auch despawnen. Ich gehe halt einfach mal davon aus. Ich hab dazu nichts im Internet gefunden aber es sollte wohl nicht so sein, dass man da ewig Angeln kann.

Schritte zur Reproduzierung

Angeln

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://fs5.directupload.net/images/161209/9mmm6vkr.jpg 
(hier sieht man die stelle. Auf normalem weg kommt man da zwar nicht hin aber es ist möglich)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?object=180184

**Comment by hraesvelgr** [comment]
*gebt.

**Comment by Rukachi** [comment]
Musste gerade selbst Überlegen was du damit meinst...werde ich beim nächsten mal beachten :D
