### ISSUE TITLE
Schmiedekunst Quest

### ISSUE THREAD

**Issue by Vobos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1849]
Die Quest "Habt Ihr das verloren? http://datenbank.classic-wow.org/?quest=3321"
für die "Gleißende Mithrilinsignien http://datenbank.classic-wow.org/?item=10418" ist bei 
Trenton Lichthammer http://datenbank.classic-wow.org/?npc=7804 
trotz aller notwendigen Pre-Quests :
http://datenbank.classic-wow.org/?quest=2756/Die%20alten%20Traditionen
http://datenbank.classic-wow.org/?quest=2757/Auf%20nach%20Beutebucht!
http://datenbank.classic-wow.org/?quest=2760/Der%20Mithrilorden
http://datenbank.classic-wow.org/?quest=2761
http://datenbank.classic-wow.org/?quest=2762
http://datenbank.classic-wow.org/?quest=2763
http://datenbank.classic-wow.org/?quest=2771
http://datenbank.classic-wow.org/?quest=2772
http://datenbank.classic-wow.org/?quest=2773
nicht erhältlich.

Wie sollte es sich verhalten?

Er sollte einem nach einer kurzen Wartezeit ab Annahmen der Qeust das Item ohne weiteres zutun aushändigen.
Schritte zur Reproduzierung?

Schmiedekunst 225  und erfüllte PreQuests

**Comment by hraesvelgr** [comment]
warst du level 40?

**Comment by Slimmer2** [comment]
Das Item ist eine Questbelohnung, die man erst nach beenden der Quest bekommt.
Hast du schon mal einen GM kontaktiert?

**Comment by Slimmer2** [comment]
Du schreibst ja schon das du die Quest [Mithril-Kid](http://datenbank.classic-wow.org/?quest=2773) nicht bekommst, die aber Voraussetzung für die Quest [Habt Ihr das verloren?](http://datenbank.classic-wow.org/?quest=3321) ist

**Comment by Vobos** [comment]
Ich bin lvl 60 habe ALLE Vorquests erledigt.. eventuell hab ich mich in nem link vertan .. aber erledigt ist es definitiv

**Comment by hraesvelgr** [comment]
siehs mal so: bei allen anderen hat es funktioniert, also muss das problem eher mit dir zusammenhöngen, als mit einem bug. da kannst du dich nur an einen gm wenden, gefixt werden kann da kaum was.

**Comment by Vobos** [comment]
Jo klar kann das natürlich nur an mir liegen... da der GM mich an den Buggtracker verwiesen hat.. aber danke für den super schlauen Spruch..

**Comment by hraesvelgr** [comment]
nicht gleich zynisch werden. gm's sind auch keine götter. und bevor die irgendwas wiederherstellen oder beenden oder sonstwas, verweisen sie erstmal an den bugtracker und die damit entstehende diskussion zum problem. 
problem erkannt, problem kann gelöst werden. wenn du so schlau wie meine sprüche bist, kannst du sogar diesen thread hier mit im ticket verlinken, und dir die quest abschließen, sowie das item adden lassen.

**Comment by Vobos** [comment]
Auch dafür danke das Ticket war das erste nachdem ich den Post erstellt habe.. aber naja ich mach mich mal auf die Suche nach Themen zu denen ich ebenfalls "sinnvoll" meinen Senf geben kann.
