### ISSUE TITLE
Angelhaken des Anglermeisters verwandelt einen in das falsche Objekt und gewährt nicht alle Effekte

### ISSUE THREAD

**Issue by Heri7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1852]
Welches Verhalten wird beobachtet?
Wenn man den Angelhaken des Anglermeisters benutzt wird man in ein Schwein verwandelt und bekommt Unterwasseratmung. Zauber unterbrechen den Effekt nicht.

Wie sollte es sich verhalten?
Wenn man den Angelhaken des Anglermeisters benutzt sollte man in einen Fisch verwandelt werden, Unterwasseratmung und eine leicht Schwimmtempo Erhöhung bekommen (+35%). Zauber sollten den Effekt unterbrechen.

Schritte zur Reproduzierung
Das Item Angelhaken des Anglermeisters benutzen (muss im Wasser benutzt werden). Einen Zauber wirken.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Hook_of_the_Master_Angler
http://de.wowhead.com/spell=24347/anglermeister

Itembeschreibung: Use: Turns you into a fish giving water breath and increasing your movement speed, but attacking or casting while in this form breaks the effect. Does not work out of water or at the water's surface.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=19979 (Item: Angelhaken des Anglermeisters)
http://datenbank.classic-wow.org/?spell=24347 (Spell: Master Angler)
http://datenbank.classic-wow.org/?npc=51754 (Sollte die Fischform sein ?)

**Comment by Rushor** [comment]
best ticket seit langem :D 

http://de.wowhead.com/npc=51754/frenzy hat wohl noch eine 2. modelid xd

**Comment by dagochen** [comment]
Schwimmende Schweine ;)

Bei uns fehlt der http://datenbank.classic-wow.org/?npc=15118 hier.
