### ISSUE TITLE
Magier Arkane Geschosse bei Zauberverlangsamungs Debuff

### ISSUE THREAD

**Issue by nimmzwo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1855]
Welches Verhalten wird beobachtet? Arkane Geschosse werden bei einem Zauberverlangsamungs Debuff nicht verlangsamt. Sie casten ganz normal weiter. Aus der Vergangenheit bin ich der Meinung , das diese genauso entsprechend dem Debuff verlangsamt werden.

Wie sollte es sich verhalten? 
Aus der Vergangenheit bin ich der Meinung , das diese genauso entsprechend dem Debuff verlangsamt werden.
Schritte zur Reproduzierung
Z.b. Beobachtet in MC bei den Kernhunden, diese produzieren einen Magie Debuff der Verlangsamt.
Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=25346 Arkane Geschosse Rang 8.
http://datenbank.classic-wow.org/?spell=19365 Ancient Dread

**Comment by Jessienia** [comment]
> Aus der Vergangenheit bin ich der Meinung , das diese genauso entsprechend dem Debuff verlangsamt werden.

Derartige Sätze werden hier nicht als ausreichende Quelle angesehen.
