### ISSUE TITLE
MC Ragnaros

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1857]
Welches Verhalten wird beobachtet?
Ragnaros sollte die Fähigkeit Melt Weapon besitzen. Die Haltbarkeit der Nahkampfwaffe die Ragnaros beschädigt sollte verringert werden

Wie sollte es sich verhalten?
Immer wenn man Ragnaros  mit einer Nahkmapfwaffe trifft besteht eine Chance das die Haltbarkeit der Waffe sinkt

Schritte zur Reproduzierung
Ragnaros angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
[Melt Weapon - A very nice gold sink that Blizzard implimented is that every time you hit Ragnaros your weapon is damaged. The only way around this is to be prepared, if you are melee bring spare weapons and ensure the raid has a repair-bot for between every few attempts.](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/323-molten-core-guide-pictures.html)

http://wowwiki.wikia.com/wiki/Ragnaros_(tactics)?oldid=629395

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=11502
http://datenbank.classic-wow.org/?spell=21387
http://datenbank.classic-wow.org/?spell=21388

**Comment by dagochen** [comment]
Das funktioniert doch schon...oder etwa nicht? Ich hab es jedenfalls schon paar mal beobachtet.

**Comment by Mafyo** [comment]
hab heute einen Schurken für mich testen lassen er hatte nach dem fight volle Haltbarkeit

**Comment by dagochen** [comment]
Glück gehabt ;)
