### ISSUE TITLE
Aq40 Obsidianauslöscher

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1858]
Welches Verhalten wird beobachtet?
Der Obisidianauslöscher zieht zu wenig Mana momentan sodass man nicht gegenleechen muss und macht die ganze Kampmechanik sinnlos. Außerdem fehlt der Visuelle Effekt der den Drain anzeigt.

Wie sollte es sich verhalten?
Der Obsidianauslöscher sollte soviel mana ziehen das man mit Mana Burn und Mana Saugen gegen halten muss, denn wenn er 100% erreicht explodiert der raid und setzt alle auf 1% hp und entfernt alle Buffs auf den Spielern. Kombiniert mit der Feuernova vom Anubissath=Raidwipe
Sowie es aussieht benutzen Alle Obsidiane die selbe Drain Mana Fähigkeit wie Moam das heisst sie saugen alle 500 Mana von Spieler ein und erhalten dafür 1000 Mana. Moam wirkt es auf 6 Spieler. In Aq40 allerdings auf 16 Spieler dafür nehmen wir einmal die wowwiki eintrag von den Obsidian Eradicator der auch ein drain Mana besitzt

[they can drain mana from all mana users in range. It seems that they choose 16 candidates to drain mana from as soon as aggro is aquired.](http://wowwiki.wikia.com/wiki/Obsidian_Eradicator?oldid=265891)

Schritte zur Reproduzierung
Obsidianauslöscher angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Obsidian_Eradicator?oldid=265891

Ein video aus 2014 das zeigt wie Drain Mana Funktioniert von den Zahlen her, finde Leider kein video aus der Zeit die genaue zahlen zeigt. wie zu sehen ist Drain mana -500 Beim Hexer=1000 für den Obsidianauslöscher
https://youtu.be/bJgOUmXJi7s?t=1317

https://youtu.be/V4byvWsejM8?t=194 hier sieht man wie der Mob gespielt werden sollte, auch schön zu sehen der Visuelle Effekt des Drains.

http://wowwiki.wikia.com/wiki/Obsidian_Nullifier?oldid=337430

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15312

http://datenbank.classic-wow.org/?spell=25671
http://datenbank.classic-wow.org/?spell=26639
http://datenbank.classic-wow.org/?spell=26559 keine Ahnung ob er dazu gehört
http://datenbank.classic-wow.org/?spell=25157 ebenfall keine Ahnung nur der einzige Verweiss darauf das dort 1000 steht und mit 500 ziehen 1000 erhalten zusammenhängen kann.

**Comment by Slimmer2** [comment]
Wenn wir kein Manasaugen bei den Add, geht der bei uns hoch.

**Comment by Mafyo** [comment]
ja geht es auch aber ziemlich langsam

**Comment by Sabbaer** [comment]
also bei uns ist er schon 3 mal explodiert was ein wipe jeweils war

**Comment by Mafyo** [comment]
also reden wir hier wirklich von dem trash nach den Twins und nicht die beiden vom skeram trash, wo wir übrigens auch  mana saugen müssen und schonmal gewipt sind. Das sind nämlich andere.

Wir müssen bei denen gar nicht leechen. da stehen dann ein paar caster in range und joa heilen oder machen schaden. Ich habe davon auch Videos gemacht. Ich sehe auch das der Manabalken steigt allerdings so langsam das es keine Gefahr darstellt.  Also entweder kann man deren Fähigkeit hart outrangen was damals keiner oder wenige wussten sodass diese mobs einfach wirklich nur noch ''Trash'' sind oder sie ziehen zu wenig mana und deren Range in der sie es einziehen ist zu gering . In keinem fall tritt es so auf wie in den videos wo dann alle hexer manasaugen und Priester Manabrand einsetzen.
