### ISSUE TITLE
Hunter Pet: Passive Skills nicht verfügbar

### ISSUE THREAD

**Issue by D4rkw1ng** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1861]
Welches Verhalten wird beobachtet?

Kann meinem Pet keine passiven Skills beibringen (Widerstände etc.), da diese weder in der Wildtierausbildung noch im Zauberbuch des Pets aufgeführt werden. Ausbildungspunkte sind vorhanden, die Skills wurden beim Pet Trainer bereits gelernt.

Wie sollte es sich verhalten?

Auflistung der Skills in der Wildtierausbildung --> Erlernen durch Einsetzen von Ausbildungspunkten -->
Auflistung im Zauberbuch des Pets

Schritte zur Reproduzierung

-

Zusätzliche Informationen (Screenshots, Videos, etc.)

-

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Jessienia** [comment]
Hast du vielleicht mal in Supportforum im Hilfe gebeten, oder andere Spieler gefragt?  WDM Ordner mal gelöscht?  WTF Ordner entfernt (Addons ausgemacht).
Denn für individuelle Probleme ist dieser Bugtracker eigentlich nicht gedacht. Und danach schaut es für mich eher aus. Ich selber hatte noch nie ein derartiges Problem und von anderen wäre es mir auch nicht bekannt.

Und wenn doch, wäre ein paar mehr Informationen bestimmt hilfreich. Hast du versucht, die Skills deines Pets zurückzusetzt? Um welches Pet handelt es sich? Welches Level, usw....

**Comment by dagochen** [comment]
Funktioniert bei mir aufm Live-und Testserver problemlos.
