### ISSUE TITLE
Friedensblume

### ISSUE THREAD

**Issue by Tobiasludovici** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1873]
Welches Verhalten wird beobachtet?
Wenn ich als Kräuterkundler eine Friedensblume im Wald von Elwyn oder Westfall öffne, dann kriege ich einen Skillpunkt, aber keine Friedensblume - das Plündermenü ist in 100% der Fälle leer

Wie sollte es sich verhalten?
Es sollten 1-3 Friedensblumen drin sein

Schritte zur Reproduzierung
Mit einem Kräuterkundler dahin gehen wo Friedensblumen wachsen... ich habe mit anderen Kräuterkundlern gechattet, die haben das gleiche Problem.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Da ist mir ein kleiner Fehler bei einer anderen Fehlerbehebung passiert. Ist schon korrigiert, muss nur aufgespielt werden ;)
