### ISSUE TITLE
Quest: Gobliningenieurskunst

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1882]
Welches Verhalten wird beobachtet?
Eine der ganzen Spezialisierungsquest kann man mit Level 30 annehmen. Alle anderen kann man erst mit Level 47 annehmen.

Wie sollte es sich verhalten?
Man sollte alle Startquest für die Spezialisierung mit den gleichen Level annehmen können.
Denke es sollte Level 47 sein.

Schritte zur Reproduzierung
Char mit Level 30 erstellen und Quest annehmen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Gobliningenieurskunst](http://datenbank.classic-wow.org/?quest=4181) die ist Level 30
[Übersicht der Spezialisierungsstartquest](http://datenbank.classic-wow.org/?search=ingenieurskunst#quests)

**Comment by dagochen** [comment]
http://web.archive.org/web/20060526121836/http://wow.allakhazam.com/db/quest.html?wquest=3633
http://web.archive.org/web/20060526184414/http://wow.allakhazam.com/db/quest.html?wquest=4181

**Comment by Slimmer2** [comment]
http://web.archive.org/web/20071118033452/http://wow.allakhazam.com/db/quest.html?source=live;wquest=3630&locale=enUS
Hier die Gomeningi Quest. die ist auch ab Level 30, bei uns sind alle Gnomeningi ab Level 47
