### ISSUE TITLE
keine Regenanimation !! 

### ISSUE THREAD

**Issue by Latarnia79** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1884]
Welches Verhalten wird beobachtet?   Ich höre den Regen, aber sehe keinen.

Wie sollte es sich verhalten? der Regen sollte zu sehen sein.

Schritte zur Reproduzierung    Ich habe reloggt, den Client neu installiert, einen anderen Client versucht, ich habe es ohne AddOns versuchst.

Zusätzliche Informationen (Screenshots, Videos, etc.) 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Bitte mehr Informationen angeben. Wir können keine individuellen Fehler beseitigen, die durch Treiber, fehlerhafte Spieldateien oder andere Dinge verursacht werden, die wir nicht kontrollieren können.

**Comment by Latarnia79** [comment]
treiber sind bei mir alle aktuell, spieldateien defekt nehme ich jetzt mal nicht an, da ich es auch mit einem anderen Client (nem englischen) probiert habe ... meine Hardware sollte ausreichend sein (ich spiele wow auch live, Legion) und habe dort keine Probleme mit den wetteranimationen. 

hier angaben zu meinem PC : quadcore  4 x 3,40 ghz
                                                 8gb ram ddr3
                                                Grafikkarte : Radeon R9 270x  (6 Monate alt)
                                                 fp : 1tb (ca 2 Monate alt)

**Comment by dagochen** [comment]
Wie gesagt, da können wir in der Regel wenig machen. Es gibt immer mal merkwürdige Dinge, die vereinzelt auftreten, die wir aber nicht lösen können.

**Comment by Latarnia79** [comment]
kann ich speziell die wetterdatei irgendwoher bekommen ??

**Comment by dagochen** [comment]
Das Problem ist doch nicht clientseitig und ich denke wir können es vielleicht lösen ;) Ein bisschen Geduld noch^^
