### ISSUE TITLE
(Paladin) Schaden in Verbindung mit Aura und Siegeln passt nicht

### ISSUE THREAD

**Issue by nuckdani** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1889]
Welches Verhalten wird beobachtet?

Wenn man Aura der Heiligkeit aktiv hat und Verbessertes Richturteil des Kreuzfahrers wirkt und im Anschluss Hammer der Gerechtigtkeit in Verbindung mit Richturteil des Befehls wirkt, macht das weniger Schaden als es eigentlich sollte.

Wie sollte es sich verhalten?

Hammer der Gerechtigkeit mit Richturteil des Befehls (360 Heiligschaden)
Verbessertes Richturteil des Kreuzfahrers (Erhöht Heiligschaden um bis zu 161)
Aura der Heiligkeit (10% mehr Heiligschaden)

Bei Anwendung in Richtiger Reihenfolge sollte es durchschnittlich eigentlich so sein:
V.R.d.K.                     161 +
H.d.G. mit S.d.B.       360 +
A.d.H. 10%                 52 =
Gesamtschaden       573!

# ## **Das Problem ist das trotz der ganzen Prozedur nur ca. 360 Standartschaden rauskommen.**

Ich hoffe Ihr könnt helfen und bedanke mich schon mal im voraus.

Mit freundlichen Grüßen

**Comment by Sabbaer** [comment]
aehm, dir ist bekannt das es zauberkoeffizienten gibt?
http://pastebin.com/2EuNW40i

ka ob die noch aktuell sind auf dem server, aber wenn du ein paar erklärungen brauchst bin ich ingame oder im teamspeak unter sabbaer zu erreichen. ich empfehle dir dringend meinen  https://community.mmobase.de/paladin/6367-ret-paladin.html ret paladin guide

liebe grüße im voraus sabbaer
