### ISSUE TITLE
NPC Spion Des Syndikats

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1891]
Welches Verhalten wird beobachtet?
Diese npc's nutzen ihre Stealth Fähigkeit nicht sodass sie sichtbar rumstehen.

Wie sollte es sich verhalten?
Die Npc's sollten die ganze Zeit in der Verstohlenehit sein und erst sichtbar werden sobald sie in Aggrorange von jemanden sind.

Schritte zur Reproduzierung
Spion im Alteracgebirge angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=1R1JvOJKGHY
Man sieht das die Npc's im Stealth sind aber schon vorher sichtbar sind für den Schurken der offensichtlicht deep Sub geskillt ist mit + Stealth detection

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=2242#abilities
http://datenbank.classic-wow.org/?spell=22766

**Comment by Slimmer2** [comment]
Sie sollten wenn sie Reseten auch wieder in Steahlt gehen

**Comment by Mafyo** [comment]
Habe hier was komisches bemerkt heute am patchday. Diese Mobs stehen noch sichtbar rum aber wenn sie aus dem Kampf fliehen kommt sofort die Stealth animation sind kurz ausm target, kommen dann wieder und stehen dort dann in so einer Art Geisterform, ein bisschen durchsichtig. Aber keine Schleich Animation und auch keine richtige Verstöhlenheit

selbe erscheinung wie hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1450

**Comment by dagochen** [comment]
Ist das Sneak was die haben. Bei Kurzens Kommandosoldaten ist es genauso. Bei mir sind die aber im Stealth (in 99% der Fälle, das 1% kann ich leider nicht herausfinden worans liegt). Und gehen auch wieder in den Stealth wenn ich sie resetten lasse.
