### ISSUE TITLE
MindControl in AQ 40

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1899]
Welches Verhalten wird beobachtet?
Es ist letztens vorgekommen das sich 2 Übernommene gegenseitig attackiert haben bis letzten Endes einer von beiden gestorben ist.

Wie sollte es sich verhalten?
Es sollte eigentlich nicht vorkommen das sich 2 übernommene gegenseitig attackieren weil wenn sie übernommen sind zählen sie ja eigentlich für die Fraktion der Npc's  als Verbündete das heisst auch untereinander wenn man es mal logisch betrachtet.

Schritte zur Reproduzierung
Keine Ahnung ob es Reproduzierbar ist aber es kam bei Skeram und den Willensbrecher Gruppen vor

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Skeram:
http://datenbank.classic-wow.org/?npc=15263
http://datenbank.classic-wow.org/?spell=785
http://datenbank.classic-wow.org/?spell=26589
http://datenbank.classic-wow.org/?spell=2313
http://datenbank.classic-wow.org/?spell=26525
http://datenbank.classic-wow.org/?spell=26526

Willensbrecher:
http://datenbank.classic-wow.org/?spell=26079
http://datenbank.classic-wow.org/?spell=26079#see-also-ability

**Comment by jinthaalor** [comment]
Anmerkung: Es passiert oft, dass die Mindslayer ihren Mindflay auf den Tank casten (teilweise mehrere Mobs gleichzeitig). Wenn der Tank nun übernommen wird, brechen die Mindflays nicht ab, und der nicht mehr heilbare Tank (da feindlich) stirbt. Ist das so gewollt?

**Comment by Dotox** [comment]
@jinthaalor Ich denke das soll nicht so sein. Möglicher Fix ist auf dem Testserver und wird von uns noch etwas intensiver getestet.

**Comment by Nifexx** [comment]
Hier sollte noch mal drüber geschaut werden. Übernommene können immernoch von Mindflay getroffen werden und gestern haben beim Trash vor den Bugs die Guardians einen unserer Spieler, der übernommen war, angegriffen und getötet.
