### ISSUE TITLE
Einwohner von Caer Darrow, Ambiente

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#190]
auf der kleinen insel,. wo die instanz scholomance ist, sieht es momentan recht leer aus. nutzt man das item spektrale essenz (http://datenbank.welli-it.de/?item=13544) sollte man einige der anwohner sehen, wie sie  ihren täglichen geschäften nachgehen, als wären sie weder tot, noch geister.

momentan sieht man nur wichtige npcs, wie questgeber oder händler. 
es gibt jedoch einige npcs, die fehlen. sie sind eigentlich nur für ambiente da , und laufen einfach nur herum, spammen emotes, oder haben textpanels, wenn man sie anspricht
diese npcs sind: http://datenbank.welli-it.de/?search=darrow#npcs sowie einige spezielle script-npcs

routen: 
reiter von darrowehr (es gibt 2, die nacheinander reiten): http://www.youtube.com/watch?v=3DZ3p8VdkeU
herumlaufender bürger 1: http://www.youtube.com/watch?v=5KplwEDKdQc
herumlaufender bürger 2: http://www.youtube.com/watch?v=CsyIL5bcqqQ

NPC locations und routen als karte:
reiter: http://s14.directupload.net/images/141115/mw9tvgjw.jpg
alle npcs: http://s14.directupload.net/images/141115/kg9f3cll.jpg

einer der bürger  liegt direkt auf (s)einem skelett am rande des wasser und scheint da zu schlafen, 
http://s14.directupload.net/images/141114/kjwtxqbp.jpg

texte der bürger: http://www.wowwiki.com/Caer_Darrow_Citizen

kanonier von CD (http://datenbank.welli-it.de/?npc=11280) sollte an einer kanone rumbasteln, die auf CD steht. es gibt je einen für jede kanone auf den türmen, insgesamt 3
http://wow.zamimg.com/uploads/screenshots/resized/40032.jpg

gardist von CD (http://datenbank.welli-it.de/?npc=11279) je einer sollte an den pfosten an der treppe zur scholomance wache halten, sowie am tor zur aussenmauer: http://www.directupload.net/index.php?mode=upload
texte beim ansprechen: http://www.wowwiki.com/Caer_Darrow_Guardsman
(reiter und wachen haben die gleichen texte)

sammy (http://datenbank.welli-it.de/?npc=11283) und melia(http://datenbank.welli-it.de/?npc=11282): 
zwei junge geister-npcs, die aller 1-3 minuten  ein wettrennen um den brunnen haben
http://www.youtube.com/watch?v=Fi-b8BBcqdY
http://www.wowwiki.com/Sammy

joseph dirte (http://datenbank.welli-it.de/?npc=11316):
 wo er exakt stehen soll weiß ich leider nicht, eventuell find ich es noch. vor irgendeiner größeren tür http://wow.zamimg.com/uploads/screenshots/normal/40335.jpg

bäcker meistersohn (http://datenbank.welli-it.de/?npc=11287)
sollte in einem der häuser stehen (exakte location ist mir leider unbekannt) 
http://wow.zamimg.com/uploads/screenshots/resized/159545.jpg

magistrat marduk http://datenbank.welli-it.de/?npc=11286 : 
momentan normal sichtbar, man sollte ihn nur sehen können, wenn man die spektrale essenz (http://datenbank.welli-it.de/?item=13544) oder das auge der schatten angelegt hat 
-> http://datenbank.welli-it.de/?spell=17622 

>http://www.wowhead.com/npc=11277/caer-darrow-citizen#comments

**Comment by hraesvelgr** [comment]
danke für den fix. was noch fehlt zum endügltigen fix:

die kinder die das wettrrennen machen. 
die reiter
bei 65/78 sollte ein mann liegen (momentan steht da eine frau)
generell ein paar bewohner im inneren der festung (und igrnedwie sind alle nur weiblich)
die wachen vor dem eingang der scholomance

**Comment by Rushor** [comment]
https://github.com/classicdb/database/commit/1c904c64f5fdf29db65a862578433948abc5da23
