### ISSUE TITLE
Quest 'Eine seltsame Anforderung' falscher Questtext

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1900]
**Welches Verhalten wird beobachtet?**
Der Questtext schickt den Player zu 'Xerash Feuerklinge'. Dieser Mob wurde aber erst in 3.2 hinzugefügt.
In der DB steht auch der Richtige Questtext, in dem man zu Neeru Feuerklinge in OG geleitet wird.
Auszug aus Wowhead kommentaren zum NPC vom 20.08.09 (http://de.wowhead.com/npc=36208/xerash-feuerklinge#english-comments):

> This NPC must've been added in patch 3.2.
Prior to this, you had to talk to Neeru Fireblade in Orgrimmar for the first leg of the A Strange Request questline, started by Witch Doctor Uzer'i.

**Wie sollte es sich verhalten?**
Ingame sollte der Text aus der DB angezeigt werden

**Schritte zur Reproduzierung**
Quest annehmen, Questtext lesen

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
keine

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
http://datenbank.classic-wow.org/?quest=3121

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/516
