### ISSUE TITLE
Aq40 Schlachtwache Sartura

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1903]
Welches Verhalten wird beobachtet?
Ich glaube Satura benutz den falschen Enrage ab 20% denn laut Datenbank besitz sie 2, was auch volkommen richtig ist aber ab Patch 1.10 wurde der 20% enrage gebufft weil der vorherige zu Lasch gewesen ist

Wie sollte es sich verhalten?
Satura sollte ab 20% eine stärkeren enrage benutzen als in der Datenbank

Schritte zur Reproduzierung
Satura angreifen auf 20% bringen

Zusätzliche Informationen (Screenshots, Videos, etc.)

[Enrage:
Ab 20% (oder nach 10 Minuten) wird Sartura Enraged und erhöht ihren Schaden und Angriffsspeed. Seit 1.10 sind beide Enragefähigkeiten gleich - vor 1.10 war das 20% Enrage schwächer als das nach 10 Minuten. 
](http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-3.htm)
iirt sich leider ein wenig denn wenn beide gleich sein würden wäre der boss nicht mehr legbar :P

[Fixed a bug that was causing Battleguard Sartura's low-health enrage to have very little effect. ](http://wowwiki.wikia.com/wiki/Patch_1.10.0)

Revision as of 10:19, August 26, 2006 
[Enrage - At 20% she will become enraged, buffing her attack.
Enrage: +63 physical damage, +30% attack speed ](http://wowwiki.wikia.com/wiki/Battleguard_Sartura?oldid=222572)

Revision as of 15:44, August 26, 2006
[Enrage - At 20% she will become enraged, buffing her attack.
Enrage: +124 physical damage, +60% attack speed ](http://wowwiki.wikia.com/wiki/Battleguard_Sartura?oldid=223113)

es müssten nochmal 61 Physical dmg dazu gerechnet werden der Attackspeed stimmt ja

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15516#abilities
http://datenbank.classic-wow.org/?spell=8269 momentan.
 Ich finde den Enrage in der Datenbank nicht der genau diese werte hatt...

**Comment by dagochen** [comment]
Kein Bug, der Zauber hat noch eine Level-Abhängige Komponente. Sprich 50 (Basis)+ Level * Dmg, wodurch er auf den korrekten Schaden kommt.

**Comment by Mafyo** [comment]
achso  dann entschuldige

**Comment by dagochen** [comment]
Keine Ursache, dafür nicht ;) Geht ja aus der DB auch garnicht heraus.
