### ISSUE TITLE
Quest: Erde von Un'Goro 

### ISSUE THREAD

**Issue by austria89** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1907]
Quest kann nicht abgegeben werden.

Hatte das Quest-Item (Un'Goro Erde) 27x im Inventar, ging nicht, also 7 Stück zerstört damit nur genau 20 drin sind - funktioniert allerdings trotzdem nicht,
Fragezeichen über dem Questgeber ist silber

**Comment by dagochen** [comment]
Pack die Erde bitte einmal in die Bank, brich die Quest ab und nimm sie neu an.

**Comment by austria89** [comment]
wow - das ging schnell!
Hab ich gemacht - hat funktioniert, vielen Dank!
