### ISSUE TITLE
MC Garr Immunitäten

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1908]
Welches Verhalten wird beobachtet?
Garr ist Blutungs immun
Garr ist nicht immun gegen Gifte 

Wie sollte es sich verhalten?
Garr sollte nicht Immun gegen Blutung sein
Garr solte immun gegen Gifte Sein

Das gleiche gilt auch für seine Adds

Schritte zur Reproduzierung
Garr angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/ypB8r9nje58?t=80 Rupture und Tiefe Wunden auf Garr
[Nearly all Elementals are natively immune to their own spell school
](http://wowwiki.wikia.com/wiki/Immune)
Garr ist ein Erdelementar und daher der Natur Aspekt.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=12057
http://datenbank.classic-wow.org/?npc=12099#abilities

**Comment by hraesvelgr** [comment]
naja, auf ein "nearly" sollte man sich nicht verlassen. der boss in brd ist ja auch ein elementar ist ist so ziemlich gegen alles immun, bzw reduziert den dmg auf ein minimum. vllt findest du ja mal das video eines ele-schamanen gegen garr?

**Comment by Mafyo** [comment]
Ich glaube du hast  Recht sollte dann nur für Gifte gelten sehe dort auch Donnerknall(ist auch natur oder?) und ein Ele der wild Blitze spammt ^^
https://www.youtube.com/watch?v=27KG2n1P7Ig

Aber diskussion über Molten core von Rogues:

[Sharpening stone for most boss mobs. (they're immune to poison) and poisons for trash mobs. (most mobs cept elementals are not immune to poison.) it's expensive to keep switching so you might as well use sharpening stones.](http://wow.allakhazam.com/forum.html?forum=243&mid=116196815012860486)

aber weiter unten im thread sagt wieder einer das Instant Poison gehen würde aber Deadly nicht, wenn die beiden jetzt noch unterschieden werden in ihrer Spell shool, ganz schön verworren. 
Aber im thread ist ja alles nur persöhnliches empfinden 

 Momentan brauch man ja keine Wetzsteine in MC

**Comment by Mafyo** [comment]
ich edditiere den Beitrag eben

**Comment by Gipsyjodler** [comment]
Garr ist nicht gegen Naturzauber immun. Damit der Fix auch wirklich nur für Gifte gilt ;D
https://www.youtube.com/watch?v=vBLTCYRydKM
