### ISSUE TITLE
Diverse NPC's mit zu großen hitboxen

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#191]
die hitbox von blutrippe (http://datenbank.welli-it.de/?npc=11622) ist momentan zu groß, weshalb man als melee nicht von seiner fähigkeit "war stomp" betroffen wird, wenn man weit genug weg steht. man kann den boss trotzdem noch angreifen. 

ausserdem sollte blutrippe laut kommentaren auf wowhead spottimmun sein. (immune against spellbased aggroturns)
>http://www.wowhead.com/npc=11622#comments

update: gleiches gilt für könig gordok (http://datenbank.welli-it.de/?npc=11501) . auch seine hitbox ist zu groß, sodass man seinen abilities entkommen kann.

**Comment by Sabbaer** [comment]
Nefarian geht aus extremst weiter entfernung zu schlagen

**Comment by Larnak1** [comment]
[Hakkar](http://datenbank.welli-it.de/?npc=14834) und [Gahz'ranka](http://datenbank.welli-it.de/?npc=15114) leiden auch an dieser mysteriösen Boss-Krankheit^^

**Comment by dagochen** [comment]
Die Worldbosse haben das Problem ja auch, wie siehts mit weiteren Fällen aus?

**Comment by hmmkay** [comment]
Also das Problem tritt immer noch/ schon wieder auf. Bei ca. 20-25 Yards Entfernung zum Tank kann man als Meele immer noch den Mob attackieren.

**Comment by dagochen** [comment]
Kannst du bitte Beispiele / Mobs nennen, damit das Problem angegangen werden kann? Ohne konkrete Informationen ist es schwer, etwas zu verändern. Danke!

**Comment by hmmkay** [comment]
Das Problem ist noch nicht vollständig behoben/ bzw. tritt wieder auf. Gerade bei den Worldbossen (Albtraumdrachen) ist die Hitbos so groß, dass man als meele entspannt 20m weit wegstehen kann und als Caster sogar soweit wegstehen kann, dass man nach jedem Cast ausm Kampf kommt. Das wird auch von vielen ausgenutzt und macht diese Bosse aggrotechnisch zu einem Witz.

**Comment by Slimmer2** [comment]
Das hatte ich schon mal an einen der Dev's geschrieben

**Comment by hmmkay** [comment]
push
