### ISSUE TITLE
Schmiedekunst Bug - Mit 1 Skillpunkt direkt Geselle (150)

### ISSUE THREAD

**Issue by Powfty** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1910]
Welches Verhalten wird beobachtet?
Beim erlernen vom Schmiedekunst, kann man mit einem Skillpunkt direkt auf Geselle Skillen, das war bei Schmiedekunstlehrer - Therum Tiefenschmied in Sturmwind (weiß nicht ob der bug auch bei anderen schmiedemeister gilt)

Wie sollte es sich verhalten?
Man Benötigt 50 von 75 Skillpunkte um es auf geselle upgraden zu können.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://drive.google.com/file/d/0B0sQdy6HGUPHVFdDbEVWQlFKV1U/view?usp=sharing

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=2018

**Comment by Ychap** [comment]
Der Spell um den es geht ist http://datenbank.classic-wow.org/?spell=3100.
Dieser wird einem durch den Spell http://datenbank.classic-wow.org/?spell=2021 beigebracht.

Wenn der Eintrag in der Datenbank fehlt, würde folgender Fix helfen:
```
UPDATE npc_trainer
SET reqskillvalue=50
WHERE spell=2021;
```
