### ISSUE TITLE
Mc Golemagg the Incinerator

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1911]
Welches Verhalten wird beobachtet?
Golemagg benutzt seine Fähigkeit Earthqauke und Attract Rager nicht

Wenn Golemag stirbt kommt kurz eine Eartquake animation es wackelt alles und wirft alle Meeles zu boden allerdings ohne Schaden dauer ca. 1 Sek.

Attract Rager sollte die Aggro erhöhen konnte im Ktm aber nichts erkennen im Script steht + 4000 ?

Wie sollte es sich verhalten?
Golemagg sollte ab 10% Earthquake einsetzen was overheal auf tanks benötigt und alle Melees auf range gehen solten

Ab 10% sollte er noch Attract Rager einsetzen was allen Mitgliedern im Raid außer den tanks von den Kernhunden die Aggro erhöht.

Schritte zur Reproduzierung
Golemag auf 10% bringen

Zusätzliche Informationen (Screenshots, Videos, etc.)
zwar anderer Privat server aber beste Quali um zu sehen wie es sich verhält
https://youtu.be/2mFiKanoGzc?t=147

At 10% health Golemagg will also start casting earthquake doing damage to all around him and begin attacking much faster. 

Golemagg will also cast 'Attract Rager' onto every member of the raid when he reaches 10% health. This ability addes a certain amount of agro to all in the raid except for the warriors tanking the Core Rager. 

http://wowwiki.wikia.com/wiki/Golemagg_the_Incinerator?oldid=387745

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=11988
http://datenbank.classic-wow.org/?spell=19798
http://datenbank.classic-wow.org/?spell=20544

**Comment by dagochen** [comment]
Das umschubsen des Raids beim tot fehlt, aber das Erdbeben und der Schaden sind ja da oder? Ist es das gleiche umschubsen wie beim ZG Buff?

**Comment by Mafyo** [comment]
also das Erdbeben zeigt sich nur wenn er stirbt 1 sek als Animation ohne Schaden nicht ab 10%

**Comment by Mafyo** [comment]
es sieht so aus als ob es zu spät getriggered wurde

**Comment by dagochen** [comment]
Ich mein der Schaden ab 10% funktioniert... kann aber gern nochmal drauf achten ;)

**Comment by Mafyo** [comment]
also wenn ich mir mein video angucke ist da kein zusätzlicher schaden für Nahkämpfer.
Bei uns dauert die 10% phase auch nur 6 sek aber schaden bekomm ich nur von dem feuerdot.

Das alles wackelt und umwerfen erst als er gestorben ist sozusagen als letzter Wille^^

**Comment by Mafyo** [comment]
liegt es daran das er zu schnell stirbt?

**Comment by Dotox** [comment]
Danke Mafyo, tolle Reports von dir! <3

**Comment by jinthaalor** [comment]
Ist es gewollt, dass der Golemagg-Tank für die Dauer des Knockdowns die Aggro verliert?
