### ISSUE TITLE
Item: Muster: Robe des Erzmagiers

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1912]
Welches Verhalten wird beobachtet?
Das [Muster: Robe des Erzmagiers](http://datenbank.classic-wow.org/?item=14513) dropt mehrmals pro Instanz Run und hat eine zu hohe dropchance.
Laut Datenbank 18%

Wie sollte es sich verhalten?
Die Dropchance sollte niedriger sein
NPC [Pyromant der Feuerbrand](http://datenbank.classic-wow.org/?npc=9264) töten

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www.wowhead.com/item=14513/pattern-robe-of-the-archmage#comments 6,70% Dropchance
http://wowdata.buffed.de/item/Rezept/Muster-Robe-des-Erzmagiers-14513 7.19% Dropchance
http://www.wowdb.com/items/14513-pattern-robe-of-the-archmage 6% Dropchance

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Bessere Quellen nicht gefunden

**Comment by Ychap** [comment]
Möglicher Fix:
```
UPDATE creature_loot_template SET ChanceOrQuestChance=7 WHERE entry=9264 and item=14513;
```
Hierbei wird die Dropchance auf 7% angepasst.

**Comment by dagochen** [comment]
http://web.archive.org/web/20060522083907/http://wow.allakhazam.com/db/item.html?witem=14513
12%

**Comment by Ychap** [comment]
Kannst auch 12% darein schreiben ;)
