### ISSUE TITLE
Ruf bei Shen'dralar - kein Ruf durch Buchbände

### ISSUE THREAD

**Issue by BeautiBeautiful** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1917]
Welches Verhalten wird beobachtet?
Bei der Abgabe des Buchbandes der Schnelligkeit gab es keinen Ruf. Ich gehe
mal davon aus dass die anderen beiden Buchbände ebenfalls keinen Ruf
bringen.

Wie sollte es sich verhalten?
Pro Abgabe sollte man 250 (Menschen 275) Ruf erhalten

Schritte zur Reproduzierung
Abgabe der nötigen Items für das Buchband der Schnelligkeit 
2*Großer glänzender Splitter
2* Blut von Helden
1* Makelloser schwarzer Diamant
1* Buchband der Schnelligkeit

Zusätzliche Informationen (Screenshots, Videos, etc.)
Mehr habe ich im Netz nicht gefunden ;-)    
http://www.mortalken.com/reputation/shendralar/
http://www.mmo-champion.com/threads/1258403-The-most-pointless-and-annoying-faction-in-WoW

der Zweite Link gibt den Hinweis auf die 250 Ruf

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
500 bekommt man beim Abgeben der Klassenbücher

**Comment by BeautiBeautiful** [comment]
500 Ruf gabe es später als der "Wahnsinnige" eingeführt wurde und 
Shen'dralar noch dazu gehörte. Deshashalb sollen 250 zu zeiten von 
Classic richtig sein ... 

Hmmm mein Mage hat 500 Rufe bekommen für das Klassenbuch, mein 
Priesterchen nur 200 ... da schein also noch mehr nicht richtig zu sein :-)

**Comment by dagochen** [comment]
Eine Liste aller Quests wär hilfrein @BeautiBeautiful

**Comment by Ychap** [comment]
Laut eines Kommentars von http://web.archive.org/web/20070116010938/http://www.thottbot.com/?qu=7484 sollte der Ruf 200 sein:

> I noticed i got 220 (so 200 normally, since im human) with the Shen'dralar faction.

Möglicher Fix für die 3 Buchbänder:
```
UPDATE quest_template SET RewRepFaction1=809, RewRepValue1=200
WHERE entry>=7483 and entry<=7485;
```
Für den Ruf für die Klassenbücher vor TBC hab ich leider keine eindeutige Quelle gefunden.
Da aber anscheinend einige Klassen nur 200 Ruf bekommen, würde folgender Fix den Ruf aller Klassenquests auf 500 setzen:
```
UPDATE quest_template SET RewRepFaction1=809, RewRepValue1=500
WHERE entry >= 7498 and entry <= 7506;
```

**Comment by BeautiBeautiful** [comment]
./clap   -> Go 4 it

**Comment by Baraz** [comment]
Die drei Quests aus dem Düsterbruch wären folgende:

http://datenbank.classic-wow.org/?quest=7483
http://datenbank.classic-wow.org/?quest=7484
http://datenbank.classic-wow.org/?quest=7485
