### ISSUE TITLE
Waffenproccs beim Ausweichen

### ISSUE THREAD

**Issue by cyberenix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1919]
Welches Verhalten wird beobachtet?
Wenn man Autoattacks ausweicht, proccen Effekte wie "[Sofortwirkendes Gift](http://datenbank.classic-wow.org/?spell=11346)" trotzdem.
Wie sollte es sich verhalten?
Die Effekte sollte nur bei Treffern ausgelöst werden.

Mfg

**Comment by Sabbaer** [comment]
quellen? erklärungen? videos von früher?

**Comment by cyberenix** [comment]
Ich halte es für sehr unwahrscheinlich, dass Proccchancen so funktionieren sollten. Nach Quellen hab ich gesucht aber leider gar nichts gefunden. Trotzdem hätte ich selbst nichts dagegen wenn es so bleibt, weil ich selbst davon profitiere :P
