### ISSUE TITLE
BRD Fackelraum

### ISSUE THREAD

**Issue by cyberenix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1922]
Welches Verhalten wird beobachtet?
Wenn auf einer Seite gleichzeitig von 2 verschiedenen Leuten gleichzeitig die [Fackeln ](http://datenbank.classic-wow.org/?item=11885) benutzt werden, öffnet sich das Tor direkt.
Wie sollte es sich verhalten?
Eigentlich sollte auf beiden Seiten jeweils 1 Fackel benutzt werden um das Tor zu öffnen.

**Comment by dagochen** [comment]
Duplikat: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1691

**Comment by cyberenix** [comment]
sry :x
