### ISSUE TITLE
C'thun bewegt sich in p2

### ISSUE THREAD

**Issue by jinthaalor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1925]
Welches Verhalten wird beobachtet?
C'thun kann in der Schwächephase in p2 vom "Aggrohalter" rumgezogen werden. (Er hat aber kein Target angezeigt)
Wie sollte es sich verhalten?
C'thun sollte sich nicht bewegen
Schritte zur Reproduzierung
C'thun in p2 in die Schwächephase bringen
Zusätzliche Informationen (Screenshots, Videos, etc.)
Edit: http://puu.sh/tfHRE/818d77c102.jpg
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://db.vanillagaming.org/?npc=15727

**Comment by Dotox** [comment]
wtf

**Comment by Slimmer2** [comment]
C'thun hat sich bei uns nicht bewegt, aber die Großen Tentakel und das Große Augententakel.

**Comment by Badorr** [comment]
Scheint aber nicht jedes Mal so zu sein. In einem Try hat er sich gar nicht bewegt und ist brav stehen geblieben.
