### ISSUE TITLE
Geschenkpapier

### ISSUE THREAD

**Issue by Thay-skill3d** [ClassicWoW/Nefarian_1.12.1_Bugtracker#193]
Das Geschenkpapier scheint nicht richtig zu funktionieren. Ob es vom Geschenkpapier abhänig ist oder von dem Item, welches verpackt wird weiß ich nicht genau. In meinem Fall war es der Teufelsherzgürtel.

Geschenkpapier:
http://datenbank.welli-it.de/?item=5048 blau
http://datenbank.welli-it.de/?item=5042 rot

Item:
http://datenbank.welli-it.de/?item=16806

Ablauf und Fehler gem. Screenshots

![1](https://cloud.githubusercontent.com/assets/9324743/5055874/f1615f30-6c6b-11e4-956c-f7f24f8805f3.jpg)
Item 1

![2](https://cloud.githubusercontent.com/assets/9324743/5055875/f7e626ce-6c6b-11e4-89fd-c0dfbbf54851.jpg)
Item 2

![3](https://cloud.githubusercontent.com/assets/9324743/5055878/fd59ea1e-6c6b-11e4-8c21-487587183b18.jpg)
Bei Anwendung

Der Gürtel ist natürlich noch nicht verpackt.

LG

**Comment by dagochen** [comment]
@Thay-skill3d 
Das ist hier ja schon bisschen eingestaubt und bisschen älter. Ich hab grad mal rumprobiert und kein Problem gehabt etwas einzuwickeln. Falls hier doch noch handlungsbedarf besteht bitte nochmal melden, dann mache ich das hier wieder auf.
