### ISSUE TITLE
Kohlenpfanne(n?) des Wahnsinns

### ISSUE THREAD

**Issue by cyberenix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1932]
Welches Verhalten wird beobachtet?
Es stehen 2 [Kohlenpfannen ](http://datenbank.classic-wow.org/?object=180327) in Zul Gurub.
Wie sollte es sich verhalten?
Es sollte sich nur eine dort befinden. 
http://fs5.directupload.net/images/170109/6icapq7g.jpg
Linke Kohlenpfanne bereits gelöscht, die Rechte vor der Treppe sollte nicht da sein.

**Comment by cyberenix** [comment]
Ps: Manchmal ist nur eine da

**Comment by dagochen** [comment]
Ja liegt an diesem Problem: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1924
