### ISSUE TITLE
C'thun Riesiges Klauententakel

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1934]
Welches Verhalten wird beobachtet?
Die riesigen Klauententakel setzen momentan ihren Ground Tremor nicht ein ein kleines Erdbeben das einen niederwirft
Wie sollte es sich verhalten?
Die riesiegen Klauen sollen gelegentlich Ground Tremor wirken woraufhin alle die das Tentakel in melee Range bekämpfen zu boden wirft.

Schritte zur Reproduzierung
Großes Klauententakel angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/M_hiu3sqe2A?t=503 kurzer Blick zur großen Klauen in dem moment alle Meeles werden umgeworfen

https://youtu.be/M_hiu3sqe2A?t=412 der druide ist von Ground tremor betroffen
http://de.wowhead.com/npc=15728/riesiges-klauententakel besitzt diese Fähigkeit noch auf dem Live Servern

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15728
http://datenbank.classic-wow.org/?spell=6524

**Comment by jinthaalor** [comment]
Bei https://youtu.be/M_hiu3sqe2A?t=560 sieht man zudem noch eine Kniesehne auf Druidentank, diese wird nach Aussage unserer Tanks ebenfalls nicht gezaubert. 

http://datenbank.classic-wow.org/?spell=26211 sollte der Spell sein.
