### ISSUE TITLE
C'thun Riesiges Klauententakel(möglicher Bug)

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1935]
Welches Verhalten wird beobachtet?
Ich vermute das die Klauententakel keine Thrash Fähigkeit nutzen quasi 2 zusätzliche attacken
Ich kann mich hier nur auf hörensagen verlassen den Tanks fällt sowas im Regelfall nicht auf und achten auf sowas auch nicht.

Wie sollte es sich verhalten?
Die Klauen sollten eine Thrash Fähigkeit besitzen die ihnen immer 2 extra angrife gewähren sollten und gefährlich für alle nicht tanks macht

Schritte zur Reproduzierung
Riesiges Klauententakel angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)
[They also have a Thrash ability (two extra attacks), meaning they will one-shot anyone who doesn't have a very high armor rating.]( http://wowwiki.wikia.com/wiki/C%27Thun_(tactics)?oldid=1914144)

https://youtu.be/sTZVV582uBs?t=434 oben auf das Portrait achten bam bam 2 schnelle attacken hintereinander.

http://de.wowhead.com/npc=15728/riesiges-klauententakel#abilities auf dem Live Server noch wie damals
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15728
http://datenbank.classic-wow.org/?spell=3391
hier ist noch einer mit einem trigger spell fals euch das was sagt:
http://datenbank.classic-wow.org/?spell=3417

**Comment by Nifexx** [comment]
Hier auf dem Server bekommt man auch direkt beim Auftauchen einen Hit mit. Da muss man aufpassen weil ansonsten alles one-hit werden kann. Das sollte dann definitiv nicht so sein.

**Comment by Dotox** [comment]
Hey, die großen Klauententakel besitzen den Zauber bzw. die Fähigkeit bereits.

**Comment by Mafyo** [comment]
Ok super :)
