### ISSUE TITLE
Berserkerwut Krieger

### ISSUE THREAD

**Issue by Allenmd** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1936]
Welches Verhalten wird beobachtet?

Berserkerwut 2/2 soll 10 Wut erzeugen,es wird auf einmal 10 Wut erzeugt aber des öfteren ist der Krieger zu schnell ausm Kampf das die erzeugte Wut sich sofort auf 9 oder 8 Wut reduziert. Zauber wie Ansturm oder Schlachtruf sind somit nicht castbar am Anfang eines Kampfes.

Wie sollte es sich verhalten?
Berserkerwut sollte sich so verhalten das die erzeugte wut "länger" auf 10 wut steht.

**Comment by dagochen** [comment]
Naja wenn man die Fähigkeit so benutzt, ohne im Kampf zu sein, dann verliert man die halt wieder. Wüsste jetzt nicht was da das Problem ist...? Und Ansturm geht eh nicht infight und auch nicht in Bersihaltung.

**Comment by Allenmd** [comment]
also nochmal! Berserkerwut mit skillung hat die Aufgabe 10 Wut zu erzeugen! wenn aber die 10 Wut des öfteren nicht erzeugt wird weil der abbau der Wut zu schnell greift dann ist es ein Fehler! da ich auf offis. angefangen habe weiß wie ich wie es normal reagieren sollte.
Ansturm gibt es ja auch nicht in wow classic sondern abfangen! das sollte man aber wissen das dies gemeint wurde von mir!

**Comment by dagochen** [comment]
Das du Abfangen meinst, ist mir inzwischen auch schon eingefallen. Schreibs einfach nächstmal direkt, dann gibts keine Missverständnisse. Und was ist jetzt der Bug und wie sollte es sein? Gibt es dazu Quellen und Beweise von früher?

**Comment by Allenmd** [comment]
**Wie sollte es sein**: Berserkerwut löst bei der Nutzung ein globalcooldown aus,**nach dem** globalcooldown sollte der Spieler die Möglichkeit haben alles was 10 Wut kostet zu nutzen. Natürlich ist das Zeitfenster sehr begrenzt weil der Krieger sich nicht im Kampf befindet.

**Fehler**: Berserkerwut löst bei der Nutzung ein globalcooldown aus,**innerhalb** des globalcooldowns springt die Wut von 10 auf 8/9 wut,teilweise so schnell das die 10 Wut nur eine Millisekunde erscheint. Wie gesagt alles passiert innerhalb des globalcooldowns. 

Beweise: keine
quellen: keine
Aber ich kann mich ma schlau machen vll. finde ich was

**Comment by Slimmer2** [comment]
Blutrausch ftw

**Comment by dagochen** [comment]
Alternativ: Addon das den Regentimer anzeigt. Für Schurken gibts sowas ja, also sicherlich auch für andere Klassen. Dann einfach Bersiwut dann zünden, wenn der Timer nicht grad kurz vorm ablaufen ist.
