### ISSUE TITLE
Item Elemental Ember

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1937]
Welches Verhalten wird beobachtet?
momentan Worlddrop.

Wie sollte es sich verhalten?
Sollte nur Bei Baron Glutarr droppen.

Schritte zur Reproduzierung
Datenbank gedroppt von ansehen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Elemental_Ember

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=18672
http://datenbank.classic-wow.org/?npc=14461

**Comment by Ychap** [comment]
Möglicher Fix:
```
DELETE FROM creature_loot_template WHERE item=18672;
DELETE FROM reference_loot_template WHERE item=18672;

INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id)
VALUES (14461, 18672, 53.59, 0, 1, 1, 0);
```

Die Drop Chance von 53,59% habe ich von http://web.archive.org/web/20070919125428/http://wow.allakhazam.com/db/item.html?witem=18672 übernommen.
