### ISSUE TITLE
Item Verhärtetes Steinband

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1938]
Welches Verhalten wird beobachtet?
Momentan Worlddrop

Wie sollte es sich verhalten?
Sollte nur ebi Lavinius droppen

Schritte zur Reproduzierung
Datenbank gedroppt von ansehen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Hardened_Stone_Band

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=18674
http://datenbank.classic-wow.org/?npc=14464

**Comment by Ychap** [comment]
Möglicher Fix:
```
DELETE FROM creature_loot_template WHERE item=18674;
DELETE FROM reference_loot_template WHERE item=18674;

INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id)
VALUES (14464, 18674, 41.64, 0, 1, 1, 0);
```

Die Drop Chance von 41,64% habe ich von http://web.archive.org/web/20060524065126/http://wow.allakhazam.com/db/item.html?witem=18674 übernommen.
