### ISSUE TITLE
Willensbrecher/Gehinrwäscher der Qiraj

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1939]
Welches Verhalten wird beobachtet?
Der Mind Flay der Mobs springt nicht wie ein Kettenblitzschlag über

Wie sollte es sich verhalten?
Der Mind Flay der Mobs sollte wie ein Kettenblitzschlag überspringen
mir ist das erst aufgefallen als ich auf Thottbott Arhive ein Kommentar zu denen gesehen habe das ab Patch 1.12 der Mind Flay dieser mobs jetzt überspringen soll. Kann das auch anhand videos belegen aber in den patchnotes steht nichts dazu.

ich weiss auch nicht wie viele immer Linken , den Videos zu urteilen ist das immer Random

Schritte zur Reproduzierung
Willensbrecher/Gehirnwäscher angreifen zu 2

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/fHsQ6ZeBTi4?t=20 erster Mind Flay Link auf 3 Leute
https://youtu.be/aAesGsJomGM?t=368 oben Rechts in der Ecke ein Link
https://youtu.be/frCwt9tyHrQ?t=171 Gehirnwäscher mob mit Link auf 5 Leute gleichzeitig

[mindflays chain as of 1.12, lolz! ](https://web.archive.org/web/20071112155538/http://thottbot.com/c15246)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15246
http://datenbank.classic-wow.org/?npc=15247#abilities

http://datenbank.classic-wow.org/?spell=26044

**Comment by Mafyo** [comment]
woop woop 
gerade noch eine Interessante info gefunden bezüglich des Effekts
[As of patch 1.12 she now does a Chain Mind Flay in her human form that can wipe a raid if not counterspelled quickly. That means not only to keep an eye out and counterspell for her great heal, you must also be able to counterspell the chain mind flay. ](http://wowwiki.wikia.com/wiki/High_Priestess_Jeklik)

https://youtu.be/krzXy1yt_RI?t=232 chain Mindflay bei Jeklik

Denn das sie einen Chain Mindflay ab 1.12 besitzen sollte genau wie oben erklärt auch die Willensbrecher was momentan auf unserem Server nicht der Fall ist. Das würde bedeuten es ist ein und das selbe Problem bzw. Patcherweiterung die hier nie aufgespielt wurde

Ich eröffne deswegen einen seperaten Report.

**Comment by dagochen** [comment]
Bei uns werden regelmäßig mehrere Spieler gemindflayed. Kann es sein das nur der visuelle Effekt fehlt?

**Comment by Mafyo** [comment]
Kann es ein das du Eventuell den Manabrand meinst? oder den Mindblast? bei uns läuft immer nur einer vom Mindflay durch die Gegend während du vom Mindflay betroffen ist kannst du ja nicht agieren.

**Comment by dagochen** [comment]
Ne, Mindflay ist der Spell der feart. Und bei uns werden wenn dann immer mehrere erwischt davon.

**Comment by Mafyo** [comment]
Da müssen wir dann unterscheiden, ich z.b habe noch nie auf meinen videos gesehen das der Mindflay mehrere trifft immer nur den Aggrohalter, der Manaburn ist ein AOE feear von denen der auch auf nicht manaklassen geht und keinen Schaden verursacht solange er läuft der Mindflay dagegen ist auch eine Art Fear oder Desorientierungseffekt wobei man allerdings Schaden erleidet.

Ich bin mir sicher das du den Manabrand verwechselst der lässt auch alle wie in Furcht rumlaufen ohne icon über dem Kopf

**Comment by Mafyo** [comment]
https://datenbank.classic-wow.org/?spell=26049

**Comment by dagochen** [comment]
https://datenbank.classic-wow.org/?spell=26044 ist bei denen eingetragen. welcher letztendlich gecastet wird, muss ich selbst nachfragen ;)

**Comment by Mafyo** [comment]
wo du dieses Thema hier gerade ansprichst hab da eine Quelle gefunden die sagt das der Manabrand nur gecastet wird wenn der Willensbrecher kurz vorm sterben ist bzw. wenn er stirbt mmomentan castet er ihn wenn genug manaklassen um ihn herum stehen

**Comment by Mafyo** [comment]
Update:
AQ 40:
[- Trash in AQ after twins - Mindslayers - can mindflay like 4 people at once, which means at the hard pack u get half of your raid being mindflayed at all times. Indeed the trash after twins was in need of a buff to make it worthwhile.](http://ladder.ru/archive/index.php/t-25534.html) undocmuented changes 1.12

**Comment by Slimmer2** [comment]
Das heißt das wurde erst mit Naxx eingeführt?
Dann sollte das auch erst mit Naxx geändert werden
