### ISSUE TITLE
Blue Murloc Egg

### ISSUE THREAD

**Issue by Perfida** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1942]
Welches Verhalten wird beobachtet?
Die Tanzanimation von Murky wird nicht gestartet.
Wie sollte es sich verhalten?
Murky sollte gelegentlich anfangen zu Tanzen.
Schritte zur Reproduzierung
-
Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/wiki/Blue_Murloc_Egg
https://www.youtube.com/watch?v=8Osw9bPwMjA

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
http://datenbank.classic-wow.org/?item=20371
