### ISSUE TITLE
Zauber widerstehen funktioniert nicht richtig

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1944]
Welches Verhalten wird beobachtet?
Wenn ein Zauber widersteht macht er trotzdem Schaden an den NPC

Wie sollte es sich verhalten?
Wenn ein Zauber widerstanden wird, sollte dieser auch keinen Schaden an den NPC machen

Schritte zur Reproduzierung
Beliebigen NPC mit beliebigen Zauber angreifen und solange auf ihm zaubern bis einer widersteht.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
In der Kampflog schön zu sehen. Zauber widerstanden und dennoch Schaden gemacht.

![unbenannt](https://cloud.githubusercontent.com/assets/8680824/21963738/11a64360-db40-11e6-9c6c-a18dc8a0cac8.PNG)
![unbenannt1](https://cloud.githubusercontent.com/assets/8680824/21963739/11a75dfe-db40-11e6-9959-99cf1ee296f9.PNG)

**Comment by Dotox** [comment]
Benötigt mehr Tests, konnte es nicht reproduzieren.

**Comment by Larirawiel** [comment]
Hi, war bei meinem Schamanen auch so. Ich liefere heute Abend mal Screenshots nach. Es tritt auch nur sehr sporadisch auf.

Grüße

**Comment by ParkerSchnabel** [comment]
Aus Mage Sicht tritt dies z.B. bei Frostnova auf. 
Es kann sein, dass der Nova widerstanden wird, diese aber trotzdem Schaden macht. Oder es ist passiert, dass der Nova nicht widerstanden wird und sie Schaden macht aber der Effekt nicht eintritt. Vielleicht hilft die Info, LG

**Comment by Slimmer2** [comment]
Kann es bei den Gleichen Adds auch nicht reproduzieren. Evtl. hat der Neustart am Sonntag den Fehler behoben

**Comment by Slimmer2** [comment]
Heute wieder den Bug gehabt.

**Comment by Larirawiel** [comment]
http://666kb.com/i/dfx440s8ihn39uxec.png

Der Blitzschlag hat widerstanden und trotzdem getroffen. Und nein, ein Schamanen-Blitzschlag hat keinen Zweiteffekt ala Slow oder Stun, dem man widerstehen könnte.

Grüße

**Comment by Dotox** [comment]
Hm, okay sehr interessant. Mal sehen, ob wir da irgendwas finden.

**Comment by Badorr** [comment]
Ist doch nur ein Anzeigebug oder? Zumindest in Raids passt die Quote an verfehlten Casts zu meiner Hitwertung.

**Comment by Slimmer2** [comment]
Eher weniger, da der NPC den Schaden auch bekommt. Oder meinst du Anzeigebug das der Zauber widerstanden hätte?
@Badorr Du hast die Bilder der Kampflog gesehen?

**Comment by Badorr** [comment]
Bei binären Zaubern liegt es definitiv daran, dass Ziele hier auf dem Server offenbar einem Effekt widerstehen können (z.b. dem Sloweffekt vom Frostschock), aber den Schaden trotzdem bekommen. Das funktioniert auch umgekehrt, sollte natürlich nicht so sein. https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1714

Shadowbolt ist kein binärer Spell, hat aber den Critdebuff, wenn man das entsprechende Talent skillt. Eventuell ist es der Effekt, dem der Mob widersteht.

**Comment by Kriptyk** [comment]
Habe den selben Bug gerade beim Fire Blast(http://datenbank.classic-wow.org/?spell=10199) beobachten können. Der Spell hat definitiv keine separate Komponente der widerstanden werden kann und dennoch trat der Bug wie oben beschrieben auf (Spell resisted und trifft gleichzeitig). Habe leider verpennt in dem Moment nen Screenshot zu machen vom Combatlog, wollte es aber trotzdem als Erfahrungsbericht hier hinzufügen.

**Comment by Kriptyk** [comment]
Seit ich von diesem Bug weiß habe ich verstärkt darauf geachtet und er tritt ziemlich regelmäßig auf.
Der beste Weg das zu reproduzieren der mir gerade einfällt:
Magier (ungeskilltes Versengen) oder Hexer (Sengender Schmerz) spielen und einfach dauercasten auf einen NPC. Dabei ein SCT-Addon verwenden, das einem EXAKT anzeigt was an DMG-Output im Kampflog auftaucht. Es sollte dann jedes mal wenn der Bug auftritt sowohl einen Resist als auch den Schaden des Spells anzeigen. Geht auch ohne Addon in dem man das Kampflog genau im Auge behält oder es einfach aufzeichnet und anschließend analysiert.
