### ISSUE TITLE
Razorgore, Eier zerstören

### ISSUE THREAD

**Issue by pinfi32** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1945]
Welches Verhalten wird beobachtet?

Seit dem heutigen Patch kann der Controller bei Razorgore die Fähigkeit "Ei zerstören" nicht mehr benutzen. Es erscheint die Meldung "Diese Fähigkeit kann im Kampf nicht verwendet werden". Damit ist der Boss aktuell nicht machbar.

Wie sollte es sich verhalten?

Die Fähigkeit sollte wie zuvor auch im Kampf nutzbar sein.

Schritte zur Reproduzierung

Razorgorekampf beginnen und Controller versuchen lassen Eier zu zerstören.

**Comment by Dotox** [comment]
Könnte an dem Update Problem heute gelegen haben. Habs versucht zu reproduzieren aber bei mir hat es funktioniert.

**Comment by pinfi32** [comment]
Ja, nach dem Restart funktionierte es wieder tadellos. Ist somit wohl behoben.
