### ISSUE TITLE
Worldbuff Sayge's Dark Fortune of Damage buff

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1946]
Welches Verhalten wird beobachtet?
der Buff gibt immer konstant 10% dmg erhöhung

Wie sollte es sich verhalten?
Der Buff sollte eine Zufällige chance haben den Schaden um 1-10% zu erhöhen

Schritte zur Reproduzierung
Buff am Dunkelmondjahrmarkt abholen

Zusätzliche Informationen (Screenshots, Videos, etc.)
[Sayge's Dark Fortune of Damage buff now only increases damage from a randomly determined range of 1-10%.](http://pl.wow.wikia.com/wiki/Patch_1.9.0)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=14822
http://datenbank.classic-wow.org/?spell=23768
http://datenbank.classic-wow.org/?spell=23770

**Comment by jinthaalor** [comment]
Der Schaden ist zufällig, schau im Charakterfenster beim Waffenschadens-Multiplikator. Nur der Buff-Tooltip zeigt immer 10% an.

**Comment by Mafyo** [comment]
achso ok :)
