### ISSUE TITLE
NPC Monströse Seuchenfledermaus

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1949]
Welches Verhalten wird beobachtet?
Nutzt Schallexplosion nicht

Wie sollte es sich verhalten?
Sollte Schallexplosion einsetzen

Schritte zur Reproduzierung
Fledermaus angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)ä

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=8602#abilities
http://datenbank.classic-wow.org/?spell=8281

**Comment by Ychap** [comment]
Wurde genauso wie #1950 schon in der Classic-DB von CMaNGOS gefixt.

Möglicher Fix daher:
```
INSERT INTO creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment)
VALUES (860201, 8602, 0, 0, 100, 1, 4000, 7000, 16000, 19000, 11, 8281, 0, 0, 'Monstrous Plaguebat - Cast Sonic Burst');
```
