### ISSUE TITLE
NPC Eitriger Schriller

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1950]
Welches Verhalten wird beobachtet?
Benutzt Schallexplosion nicht

Wie sollte es sich verhalten?
Sollte Schallexplosion einsetzen

Schritte zur Reproduzierung
Schriller angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=8535#abilities
http://datenbank.classic-wow.org/?spell=8281

**Comment by Ychap** [comment]
Mit der aktuellen Classic-DB von CMaNGOS funktioniert dieser Spell, da dieser in 'creature_ai_scripts' eingetragen wurde.

Möglicher Fix daher:
```
INSERT INTO creature_ai_scripts (id, creature_id, event_type, event_inverse_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action1_type, action1_param1, action1_param2, action1_param3, comment)
VALUES (853501, 8535, 0, 0, 100, 1, 5000, 8000, 16000, 24000, 11, 8281, 0, 0, 'Putrid Shrieker - Cast Sonic Burst');
```
