### ISSUE TITLE
Pechschwingenhort - Lootbug bei Razorgore

### ISSUE THREAD

**Issue by BugsBugs** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1955]
Welches Verhalten wird beobachtet?

Wenn man in Phase 1 bei den Adds bei Razorgore eines der Adds lootet, spawnt direkt ein neues Add.

Wie sollte es sich verhalten?

Looten von Adds sollte keine Auswirkung auf die Anzahl der Adds im Raum haben.

Schritte zur Reproduzierung

Event bei Razorgore starten, getötete Adds looten und Anzahl der sich im Raum befindenden Adds überprüfen. Bzw. Ecken im Auge behalten.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Also ob das 1 zu 1 so passiert lässt sich von mir schwer beurteilen, da ich bei jedem Razorgore Try ziemlich beschäftigt bin und das auch nicht absichtlich ausprobieren will, um die Gruppe nicht zu wipen.

Allerdings hatten wir jedesmal wenn jemand gelootet hattet deutlich mehr Adds(wie gesagt schwer zu verifizieren ohne Admin power :)) im Raum .

Wäre sehr cool wenn sich das mal jemand anschauen würde.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Die Orks droppen doch garnix, nicht einmal Gold/Silber/Kupfer (wurde vor paar Wochen gefixt). Wie könnt ihr die also looten?

**Comment by BugsBugs** [comment]
Achso okay, dann gehts nur um die 3 Orcs zu Beginn die oben auf der Plattform stehen, diese sind immer noch lootbar.

Müsste man mal ausprobieren, die töten, direkt looten und schaun ob sich im folgenden was beim Spawnen der anderen Adds tut, und als 2. erst looten nachdem der Spawn in den Ecken begonnen hat.

**Comment by Dotox** [comment]
Wohl kaum, da die 2 Adds nicht an das Script gebunden sind.

**Comment by BugsBugs** [comment]
Alles klar, super dann kann man sich die Ansage sparen :) danke fürs Kommentieren.

**Comment by dagochen** [comment]
Das Problem, was den Respawn ausgelöst hat beim Looten ist seit über einem Jahr behoben ;) Sprich man konnte die paar Kupfer tatsächlich looten, ohne einen zusätzlichen Respawn zu erzeugen. Erst nachdem reportet wurde, dass diese Mobs kein Money droppen sollen, wurde auch dies gefixt ;)
