### ISSUE TITLE
Lootbug - Shift-Loot vs. Normal-Loot

### ISSUE THREAD

**Issue by Healchen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1957]
Welches Verhalten wird beobachtet?

Ein NPC "Oger der Felsfäuste" [http://datenbank.classic-wow.org/?npc=2562], im Aratihochland bei den Koordinaten 33,40, konnte nicht regulär geplündert werden. Das Fenster zum Plündern ging auf und es wurden 61 Kupfer und 3 Wollstoff angezeigt. Bei einem Klick auf den Wollstoff, bzw. das Kupfer passierte nichts.
Anschließend versuchte ich den NPC mit Shift-Loot zu plündern. Im Chat wurde angezeigt, dass ich 61 Kupfer geplündert hatte. Da ich jedoch einen Doppelklick mit der rechten Maustaste machte, wurde mir angezeigt, dass ich 2x 61 Kupfer geplündert hätte, jedoch kein Wollstoff. Um die Grenzen des Bugs auszuloten, versuchte ich es erneut und konnte insgesamt 6x 61 Kupfer (laut Chatfenster) plündern. Ich bin der Meinung, allerdings nicht sicher, dass ich den Betrag jedes Mal gutgeschrieben bekam.
Den Wollstoff konnte ich bei diesem NPC nicht plündern.

Wie sollte es sich verhalten?

Ich sollte den NPC nicht 6x Plündern können und die Items, bzw. das Kupfer sollte bei einem Normal-Loot plünderbar sein.

Schritte zur Reproduzierung

- Ich konnte es nicht Reproduzieren. Ich schrieb direkt ein Ticket, und ein GM nahm Kontakt zu mir auf. Dieser meinte, dass ich solle den Bug hier melden, er sei zwar selten, ich solle ihn jedoch reporten.

Zusätzliche Informationen (Screenshots, Videos, etc.)

- Habe ich dummerweise versäumt zu machen. Ich  hoffe aber, dass die hier beschriebenen Begebenheiten 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Nicht reproduzierbar. Bitte Video anfertigen ;)
