### ISSUE TITLE
Sound Fehler wenn man nach AQ20 reitet/geht

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1959]
Welches Verhalten wird beobachtet?
Wenn man vom Eingangstor von Ahn'Qiraj nach AQ 20 oder AQ40 reitet oder läuft bekommt man einen Soundfehler.
Man bekommt dann dauernd "habe kein Ziel" in dauerschleife zu hören

Wie sollte es sich verhalten?
Man sollte wenn man da hin reitet diesen Fehlerausgabe bekommen

Schritte zur Reproduzierung
Von Eingangstor von Ahn'Qirij nach AQ20 oder AQ40 reiten oder laufen 

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Larirawiel** [comment]
Hi, das passiert in anderen Zonen auch. Wenn man z.B. per Ruhestein nach Darnassus portet dann bekommt man öfter das Blizzard-Geräusch vom Magier in einer Dauerschleife.

Was hilft ist Darnassus verlassen und wieder rein.

Grüße

**Comment by dagochen** [comment]
Tritt der noch auf?

**Comment by Slimmer2** [comment]
Ja, tritt noch auf

**Comment by dagochen** [comment]
Immer noch?

**Comment by Slimmer2** [comment]
Tritt nicht mehr auf
