### ISSUE TITLE
Quest Suntara Steine (Escortquest) defekt

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1960]
Dorius Steinhüter steht nicht auf und macht nichts nachdem man seine Eskortquest gestartet hat (Suntara Steine http://datenbank.classic-wow.org/?quest=3367/Suntarasteine)

Er sollte aufstehen und den Weg ablaufen.
Außerdem liegt der Brief, den er fallen lässt für die Folgequest, schon da rum, wo er eigentlich im Laufe der Begleitquest stirbt. Er sollte den Brief aber erst am Ende fallen lassen.

Suntarasteine http://datenbank.classic-wow.org/?quest=3367/Suntarasteine
Dorius Steinhüter http://datenbank.classic-wow.org/?npc=8284
Angesengter Brief http://datenbank.classic-wow.org/?item=10443

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/642
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/147
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1731

**Comment by Glenndun** [comment]
Quest funktioniert nicht. Warum closed?

**Comment by Slimmer2** [comment]
Weil das öfters gemeldet ist und es reicht wenn davon eins offen ist

**Comment by MaweriP** [comment]
Hey,

die Quest funktioniert weiterhin nicht. Der nette Zwerg bleibt halb tot liegen, wenn man die Quest annimmt.

Best,
Pirewam
