### ISSUE TITLE
Merkwürdiges NPC-Laufverhalten

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1961]
**Welches Verhalten wird beobachtet?**

Es passiert, dass NPCs, die sich recht weit vom Spieler befinden und regelmässige Routen ablaufen plötzlich stehen bleiben. Nach einer Weile oder wenn man sich diesen NPCs nähert dann fangen sie an zu rennen.

Ich vermute mal, es liegt daran, dass die Position weit entfernter NPCs nicht mehr zwischen dem Server und dem Client korrekt synchronisiert wird. Und erst wenn sich die NPCs näher am Spieler befinden dann wird die Diskrepanz korrigiert und die NPCs rennen.

**Wie sollte es sich verhalten?**

Die NPCs sollten ganz normal ihre Routen ablaufen.

**Schritte zur Reproduzierung**

Sich mal vor die Bank in Darnassus stellen und die Beschützer von Darnassus beobachten. Speziell diese bei der Enklave des Cenarius.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

http://datenbank.classic-wow.org/?npc=4423
http://datenbank.classic-wow.org/?npc=10878

Ist halt mehr ein ästhetischer Bug und keiner, der das Spiel sonst irgendwie stört.

Grüße

**Comment by dagochen** [comment]
Vielleicht hängt das mit den folgenden Fehlerbeschreibungen zusammen:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1088
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1199

**Comment by Dotox** [comment]
Ich denke das liegt daran, dass die Kreaturen, die aus der Sichtweite eines Spielers sind vom Client nicht mehr aktualisiert werden. Der Server verarbeitet die Wegpunkte allerdings trotzdem weiter. Sobald die Kreatur wieder in Sichtweite eines Spielers gerät, wird der Client wieder mit Paketen versorgt, worauf eine Synchronisation stattfindet, welche dann das beschriebene hervorruft.

**Comment by Larirawiel** [comment]
Hi, nein, diese Kreaturen sind noch in Sichtweite. Ich sehe sie ja. Es tritt auch nicht immer auf. Sehr oft verschwinden die NPCs einfach wenn sie ausser Sichtweite sind. Nur manchmal bleiben sie halt stehen und ihre Standanimation wird abgespult. Wenn man sich denen nähert dann fangen sie an zu rennen.

Grüße

**Comment by Dotox** [comment]
Die Sichtweite eines Spielers ist relativ. Es tritt auf jedenfall ab einer bestimmten Entfernung auf.
