### ISSUE TITLE
Quest: Disharmony of Flame kann nicht angenommen werden(?)

### ISSUE THREAD

**Issue by austria89** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1962]
Ich kann den Quest Disharmony of Flame (http://db.vanillagaming.org/?quest=3906#wh-comments) nicht annehmen, der Questgeber (Thunderheart) gibt mir keinen Quest.

Brauche ihn aber um mit der Commander Gor'shak Questreihe zu beginnen.
Bin schon Level 60 und habe auch im Spiel schon jemanden mit der Belohnung aus dem letzten Quest der Reihe gesehen, dürfte also schon einmal funktioniert haben.

Haben Overmaster Pyron auch erst gestern Abend gelegt, konnte aber auch nix looten (d.h. is ned nur ein Anzeigebug o.Ä. vom Questlog).

**Comment by Slimmer2** [comment]
http://datenbank.classic-wow.org/?quest=3906
http://datenbank.classic-wow.org/?npc=9084
An Vorlage halten, naja lassen wir das mal...

**Comment by austria89** [comment]
Verzeihung, ich werd mir das zu Herzen nehmen und falls ich wieder mal einen Bug finden sollte nach der Vorlage gehen, versprochen!

**Comment by austria89** [comment]
Hab jetzt mittlerweile einen 2. Charakter hochgespielt, der kann den Quest ohne irgendwelche Probleme annehmen. War zum 1. Mal in Kargath und konnte gleich Disharmonie der Flamme (und sogar auch den Folgequest Disharmonie des Feuers - http://datenbank.classic-wow.org/?quest=3907/ - startet beim selben Questgeber) annehmen, obwohl der ja eigentlich erst verfügbar sein sollte wenn der Flammenquest abgeschlossen wurde, siehe Screenshot:

![image](https://cloud.githubusercontent.com/assets/24939514/22467094/879be586-e7c3-11e6-8d7c-592f2802adfe.png)


Jetzt weiß ich ned so recht was ich noch machen/testen könnte.(?)

**Comment by Slimmer2** [comment]
Schreib mal welche Rasse und Klasse es funktionierte und bei welcher nicht.

**Comment by austria89** [comment]
funktioniert nicht bei: Taure, Druide (60)
funktioniert bei: Untot, Magier (54 derzeit)
