### ISSUE TITLE
Blutblütengift

### ISSUE THREAD

**Issue by Yeromandrake** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1963]
Das Dropverhalten der [Gorishistachel](http://datenbank.classic-wow.org/?item=22435) aus der Druiden-Quest [Blutblütengift](http://datenbank.classic-wow.org/?quest=9052) stimmt nicht. Laut Datenbank sollte sie 15% betragen, allerdings droppt bei 20-30 Mobs gerade einmal einer, wenn überhaupt. Dieses Problem besteht schon seit einigen Monaten, weshalb ich die Quest immer wieder abgebrochen habe, weil es Stunden dauert sie zu sammeln.

Würde mich sehr freuen, wenn das mal überprüft wird. 

Vielen Dank!

**Comment by Dotox** [comment]
Hey, unsere Webdatenbank ist nur ein Richtwert und keine genaue Garantie.

**Comment by Yeromandrake** [comment]
Lieber Dotox,
das ist mir schon bewusst, allerdings ist die Droprate wirklich extrem gering, sodass ich mir nicht vorstellen kann, dass sie auch nur ansatzweise der des ursprünglichen Vanillaservers entspricht. Und auch, wenn es nur Richtwerte in der Datenbank sind: Zwischen 15 % und einer 0,xx % Wahrscheinlichkeit besteht einfach ein zu großer Unterschied meiner Meinung nach.

Ich danke euch trotzdem!

**Comment by dagochen** [comment]
Hallo Yeromandrake!

Schau dir auf folgendem Link mal bitte die Kommentare an (besonders die vor 2007 sind für uns relevant)
http://web.archive.org/web/20071013222211/http://wow.allakhazam.com/db/item.html?witem=22435

Die Prozentchancen dort sind bereits die erhöhten :)
