### ISSUE TITLE
Quest: "Was der Wind erzählt" (Onyxia-Prequest) kann nicht abgeschlossen werden

### ISSUE THREAD

**Issue by austria89** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1964]
Quest: http://datenbank.classic-wow.org/?quest=6566
startet bei Thrall: http://datenbank.classic-wow.org/?npc=4949

Kann den Quest annehmen, Thrall sollte dann eine Geschichte erzählen nach der man den Quest abgeben kann.
Hatte den Quest jetzt mehrere Tag im Questlog, konnte immer noch nicht abgeben, Thrall sagt nur man soll sich noch etwas gedulden:
![image](https://cloud.githubusercontent.com/assets/24939514/22352891/5043c002-e41e-11e6-9106-dc999cc21d50.png)

WDB/Interface Ordner temporär verschoben, hat auch nix geholfen.
Quest abgebrochen und neu angenommen hat auch nix geholfen.

Ist Teil der Onyxia Prequest-Reihe, also bissl blöd wenns da nicht weitergeht :/

**Comment by armaggedon1** [comment]
Schon mal den Questtext gelesen? ;)

**Comment by austria89** [comment]
ich hab jetzt sehr lange gesucht bis ich die Lösung für mein "Problem" gefunden hab - vielleicht stolpert ja jemand anderer darüber.

Wenn man den Ragefirequest noch nicht gemacht hat (und daher dieser Quest auch noch von Thrall angeboten wird), wandert die Sprechblase zum Fortsetzen dieses Quests soweit nach unten, dass sie ohne zu scrollen nicht mehr sichtbar ist.
