### ISSUE TITLE
HP Regeneration

### ISSUE THREAD

**Issue by Throndar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1967]
**Welches Verhalten wird beobachtet?**
Die Lebenspukteregeneration, welche durch Hp5 erzeugt wird, ist zu hoch. Das Leben wird pro Tick, anstatt alle 5 Sekunden wiederhergestellt.

**Wie sollte es sich verhalten?**
Hp5 sollte wie Mp5 auf den Tick heruntergerechnet werden

**Schritte zur Reproduzierung**
Hp5-Gegenstand anlegen (z.B. Talisman mit Onyxiablut: (http://datenbank.classic-wow.org/?item=18406)) , oder Dämonenrüstung vom Hexenmeister nutzen, oder Trollbluttrank trinken. Infight gehen, Schaden nehmen und die Regeneration betrachten. Geht gut mit dem Schild vom Priester, da weiterer Schaden vermieden wird.

**Comment by Kriptyk** [comment]
Ich bin mir nicht ganz sicher ob Hp5 nicht tatsächlich nur alle 5 sec ticken sollte.
Alle 2 sec denn vollen 5 sec Tick zu bekommen ist aber definitiv ein Bug.

**Comment by hraesvelgr** [comment]
>Despite this, items either say "Restores X health [every|per] 5 sec." or "+X Health Regeneration" (some TBC items) will regenerate health at all times (even during combat). One point of "Health Regeneration" is the same as 1 health every 5 seconds. 

http://wowwiki.wikia.com/wiki/Health_regeneration
