### ISSUE TITLE
ZG buff übern tot

### ISSUE THREAD

**Issue by ebdrakas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1968]
Welches Verhalten wird beobachtet?
ZG Worldbuff verschwindet nach dem tot.

Wie sollte es sich verhalten?
ZG buff bleibt nach dem tot weiter bestehend.

Schritte zur Reproduzierung
ZG Buff holen und damit sterben.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/34ba7rg0gdc?t=783
https://youtu.be/S0zm3MjU1HU?t=208

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=24425

**Comment by Nifexx** [comment]
Wurde mit 1.11 leider geändert. http://wowwiki.wikia.com/wiki/Patch_1.11.0
