### ISSUE TITLE
Schamanentotems (zum anlegen) ersetzen nicht die Totems in der Tasche

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1969]
Welches Verhalten wird beobachtet?
Obwohl man als Schamane ein Totem angelegt hat, welches die Totems in der Tasche ersetzen sollen, sind diese weiterhin nötig, um Totems zu stellen.

Wie sollte es sich verhalten?
Sobald man ein Totem, z.B. http://datenbank.classic-wow.org/?item=23199 anlegt, muss man die Totem-Items nicht mehr in der Tasche haben

Schritte zur Reproduzierung
Totem anlegen, ein totem item aus der tasche nehmen und entsprechendes totem stellen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Klingt für mich, ohne es genau zu wissen grad, nach einer Änderung die auch erst mit einem späteren Addon kam. Daher: Quellen?

**Comment by Pexus6** [comment]
Es steht im tooltip vom totem.
http://datenbank.classic-wow.org/?item=23199

**Comment by Badorr** [comment]
Die Tooltips aus deinen Links sind genau gleichlautend und wo liest du daraus, dass es eines der Totem-Items in der Tasche ersetzen sollte? Und welches Element sollte das verlinkte Totem darstellen? Welches Element haben dann die anderen anlegbaren Totems? Quelle?

**Comment by dagochen** [comment]
Ah mist jetzt habe ich das andere schon gefixt. 
Siehe #1970
