### ISSUE TITLE
Schamanentotems ersetzen nicht die Totems in der Tasche, mit ingame Screenshot

### ISSUE THREAD

**Issue by Pexus6** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1970]
Edit: Wäre auch möglich, dass das Tooltip falsch ist. auf jeden Fall ist was faul.

**Welches Verhalten wird beobachtet?**
Obwohl man als Schamane ein Totem angelegt hat, welches die Totems in der Tasche ersetzen sollen, sind diese weiterhin nötig, um Totems zu stellen.

**Wie sollte es sich verhalten?**
Sobald man ein Totem, z.B. http://datenbank.classic-wow.org/?item=23199 anlegt, muss man die Totem-Items nicht mehr in der Tasche, z.B. http://datenbank.classic-wow.org/?item=5177 haben. (Siehe Tooltip-Screenshot)

**Schritte zur Reproduzierung**
Totem anlegen, ein Totem Item aus der Tasche nehmen und entsprechendes Totem stellen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
![unbenadannt](https://cloud.githubusercontent.com/assets/19672290/22542870/3dd6091a-e92e-11e6-8191-8f97eefe5573.PNG)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1969

**Comment by dagochen** [comment]
Der Tooltip ist falsch und wurde angepasst.
