### ISSUE TITLE
Dunkelmondjahrmarkt: Handwerksquests nicht vorhanden

### ISSUE THREAD

**Issue by dwilhelms** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1971]
Welches Verhalten wird beobachtet?

Ich kann am Jahrmarkt lediglich bei Rinling hergestellte Dinge  abgeben (Ingenieurszeugs). [Chronos](http://datenbank.classic-wow.org/?npc=14833) lässt mich meine [gekräftigte Lederrüstung ](http://datenbank.classic-wow.org/?item=2314) nicht los werden (Quest [Jahrmarktswämser](http://datenbank.classic-wow.org/?quest=7882)), [Yebb Nabetand](http://datenbank.classic-wow.org/?npc=14829) nimmt meine [kleinen pelzigen Tatzen](http://datenbank.classic-wow.org/?item=5134) nicht (Quest: [Kleine pelzige Tatzen](http://datenbank.classic-wow.org/?quest=7899)). Die NPCs haben schlicht keine Quests. Gleiches gilt für [Kerri Hicks](http://datenbank.classic-wow.org/?npc=14832): Die sollte die Quest [Grober Gewichtsstein](http://datenbank.classic-wow.org/?quest=7889) haben, bietet aber nichts an. 

Wie sollte es sich verhalten?

Die o.g. NPCs sollten die o.g. Quests anbieten.

Schritte zur Reproduzierung

Char erstellen, Jahrmarkt besuchen.

**Comment by dagochen** [comment]
Kann es sein, dass du bereits einen bestimmten Ruf hast? Dann geht es nämlich nicht mehr die "kleinen" Quests abzugeben. 

>I'm at level 44, and I turned in 20 copper modulators, got about 20% of a bar of reputation with the faire and 4 tickets and then they wouldn't let me turn in any more. Time to go make Whirring Bronze Gizmos.

http://web.archive.org/web/20060416014549/http://wow.allakhazam.com/db/quest.html?wquest=7894

**Comment by dwilhelms** [comment]
Nein, ich stehe bei 0/3000 neutral, hab noch nie was bei denen abgegeben. Geht mir übrigends auf allen chars so, vom lvl 12er bis lvl 56er.

**Comment by Slimmer2** [comment]
Muss man da evtl. den Beruf auch haben?

**Comment by dagochen** [comment]
Ich probiers nachher mal aus aufm Testserver.

**Comment by dwilhelms** [comment]
Ja, komisch, bei mir mit keinem Charakter....und der, der die ingiequests sehen konnte, ist lederer, also am beruf kann's net liegen. Ich hab alle addons aus gemacht, was könnte ich denn sonst noch versuchen?

**Comment by dwilhelms** [comment]
Also, wir haben das nochmal mit verschiedenen Chars unterschiedlichen Levels und mit unterschiedlichen Berufen auf 4 separaten Accounts ausprobiert. Der Bug stellt sich wie folgt dar:

Rinling hat immer alle Abgabequests für Ingenieurszeugs, je nach Level des Chars verschiedene viele, für Chars über 50 alle 5 Quests (Voraussetzung natürlich immer, der Ruf ist nicht zu hoch).

Chronos hat gar keine Abgabequests für Lederzeug. Lediglich beim Char mit Level 56 hatte er ein graues Ausrufezeichen. Er sollte haben (je nach Levelbereich): [Der Krokilisken-Junge und der bärtige Murloc](http://datenbank.classic-wow.org/?quest=7884), [Der größte Gnom der Welt!](http://datenbank.classic-wow.org/?quest=7883), [Jahrmarktsstiefel](http://datenbank.classic-wow.org/?quest=7881), [Jahrmarktswämser](http://datenbank.classic-wow.org/?quest=7882), [Rüstungssets](http://datenbank.classic-wow.org/?quest=7885).

Yebb Nabetand hat lediglich die Abgabequest für [böse Fledermausaugen](http://datenbank.classic-wow.org/?quest=7903), und auch nur für Chars mit entsprechender Levelstufe (bei uns nur für den 56er). Die Abgabequests für niedrigstufigere Level gibt er nicht: [Kleine pelzige Tatzen](http://datenbank.classic-wow.org/?quest=7899), [Zerrissene Bärenpelze](http://datenbank.classic-wow.org/?quest=7900), [Weiche buschige Schwänze](http://datenbank.classic-wow.org/?quest=7901), [Leuchtendes Skorpidblut](http://datenbank.classic-wow.org/?quest=8222), [Farbenprächtige Federbüsche](http://datenbank.classic-wow.org/?quest=7902)).

Kerri Hicks hat lediglich die Abgabequest für [Rituale der Stärke](http://datenbank.classic-wow.org/?quest=7893), und auch nur für Chars mit entsprechender Levelstufe (bei uns nur für den 56er). Die Abgabequests für niedrigstufigere Level gibt sie nicht: [Grober Gewichtsstein](http://datenbank.classic-wow.org/?quest=7889), [schwerer Schleifstein](http://datenbank.classic-wow.org/?quest=7890), [grüne Eisenarmschienen](http://datenbank.classic-wow.org/?quest=7891), [großer schwarzer Streitkolben](http://datenbank.classic-wow.org/?quest=7892).
