### ISSUE TITLE
Aquadynamischer Fischanlocker falsche "Buffzeit" ?

### ISSUE THREAD

**Issue by Thefiveoh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1972]
Welches Verhalten wird beobachtet?
Wenn man sich den Köder Aquadynamischer Fischanlocker http://datenbank.classic-wow.org/?item=6533 auf eine Waffe / auf die Angel verzaubert - wirkt dieser für 10min.

Wie sollte es sich verhalten?
Die Verzauberung sollte wie laut Tooltip nur 5 min anhalten.

Schritte zur Reproduzierung
Eine Waffe / Angel mit Aquadynamischer Fischanlocker verzaubern.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Es gab einen Zeitraum auf den Offis da war es so wie hier. Laut Tooltip nur 5min - aber gehalten hat er dennoch 10min. Hier zu bin ich alte Kommentare durchgegangen und bin auf folgende dinge gestoßen:

http://wow.gamepedia.com/Aquadynamic_Fish_Attractor

"Until 2.3 the item tooltip stated that the enchant lasted 5 minutes, but at 2.3(?) the tooltip was corrected to 10 minutes."

http://wowdata.buffed.de/item/Verbrauchbar/Aquadynamischer-Fischanlocker-6533#comments
im April 2007:

"Die Teile halten ja leider nur 5 min und sind beim angeln von grimmigen Flusskrebsen ja schon so gut wie Pflicht ^^"

 im June 2007

"Neuerdings halten die 10 Minuten lang statt 5 Minuten. Trotz der Beschreibung."

Allerdings bin ich auch auf diesen Eintrag gestoßen:
http://www.wowhead.com/item=6533/aquadynamic-fish-attractor#taught-by-npc
"Added in patch 1.11.1.5462"

Gerne kann dieser "Bug" auch als unzureichende Quellenangabe markiert werden - denn entweder ist die Bufftime falsch - oder das Tooltip. Vielleicht findet sich ja jemanden mit einer genauen Quellenangabe.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?item=6533
http://datenbank.classic-wow.org/?spell=8089

**Comment by dagochen** [comment]
Duplikat: #1762
