### ISSUE TITLE
Kräuterkunde spwans

### ISSUE THREAD

**Issue by Gismok89** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1974]
Welches Verhalten wird beobachtet?
Spawns sind grafisch nicht zu sehen .

Wie sollte es sich verhalten?
Sollten eigl. nicht nur auf der mini map zu erkennen sein
Schritte zur Reproduzierung
restat, probiert grafik umgestellt alles half nicht
Zusätzliche Informationen (Screenshots, Videos, etc.)

![wowscrnshot_020417_180922](https://cloud.githubusercontent.com/assets/25552673/22620212/18c32240-eb07-11e6-8c1f-d4c37904b308.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Evtl. ist das Kraut unter der Erde.

**Comment by dagochen** [comment]
Kannst du vielleicht mir die Ingame-Koordinaten zur Verfügung stellen? Oder einen Screenshot von der Map?
