### ISSUE TITLE
Beschwörungen Windsteine

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1975]
Welches Verhalten wird beobachtet?
Wenn man ein Wappen bei den Beschwörungen benutzt erscheint ein random Boss. Das Wappen wird nicht verbraucht. Nur für die mittleren Windsteine getestet. Sollte aber für die kleinen/großen auch so sein.

Wie sollte es sich verhalten?
Es sollte der dem Wappen entsprechende Boss spawnen. Das Wappen sollte dabei verbraucht werden.

Schritte zur Reproduzierung
Bosse mit einem Wappen beschwören.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/80lqzLVJxfs

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Bosse:
kleine:
http://datenbank.classic-wow.org/?npc=15209
http://datenbank.classic-wow.org/?npc=15211
http://datenbank.classic-wow.org/?npc=15212
http://datenbank.classic-wow.org/?npc=15307
mittlere:
http://datenbank.classic-wow.org/?npc=15206
http://datenbank.classic-wow.org/?npc=15208
http://datenbank.classic-wow.org/?npc=15220
http://datenbank.classic-wow.org/?npc=15207
große:
http://datenbank.classic-wow.org/?npc=15203
http://datenbank.classic-wow.org/?npc=15204
http://datenbank.classic-wow.org/?npc=15205
http://datenbank.classic-wow.org/?npc=15305

Wappen:
http://datenbank.classic-wow.org/?item=20420
http://datenbank.classic-wow.org/?item=20416
http://datenbank.classic-wow.org/?item=20419
http://datenbank.classic-wow.org/?item=20418
Siegel:
http://datenbank.classic-wow.org/?item=20433
http://datenbank.classic-wow.org/?item=20432
http://datenbank.classic-wow.org/?item=20435
http://datenbank.classic-wow.org/?item=20436
Szepter:
http://datenbank.classic-wow.org/?item=20448
http://datenbank.classic-wow.org/?item=20447
http://datenbank.classic-wow.org/?item=20449
http://datenbank.classic-wow.org/?item=20450

**Comment by dagochen** [comment]
Duplikat: #1914
