### ISSUE TITLE
Rezept: BKP-Geschoss 'Einschlag'

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1976]
Welches Verhalten wird beobachtet?
Man kann beim Ingenieur Lehrer dieses Rezept, aber es taucht nicht im den Fertigkeiten des Berufs auf.
In der Datenbank ist das Item auch Falsch, aber die ID ist evtl. richtig.

Wie sollte es sich verhalten?
Wenn man das Rezept lernt sollte es auch in den Fertigkeiten auftauchen und herstellbar sein

Schritte zur Reproduzierung
Ingenieur lernen bis 180 skillen. Das Rezept erlernen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[BKP "Impact" Shot](http://datenbank.classic-wow.org/?spell=4020) Zauber für erlernen
[Deprecated BKP "Impact" Shot](http://datenbank.classic-wow.org/?spell=3964) Zauber zum Item erstellen
[Gerillte Brustplatte](http://datenbank.classic-wow.org/?item=3034) Item was falsch in der Datenbank ist
[Deprecated BKP "Impact" Shot](http://www.wowhead.com/item=3034/deprecated-bkp-impact-shot) WOWhead Link mit dem Richtigen Item
Könnte evtl. den Fix enthalten bzw. nur angepasst werden
https://github.com/TrinityCore/TrinityCore/commit/2ece847ceb3a7938b9adbe80c660f11ac475d1ab

**Comment by dagochen** [comment]
Was für nen Item ist nun richtig?

**Comment by Slimmer2** [comment]
Das von WOWhead bzw. wie im TrinityCore link
