### ISSUE TITLE
AQ40 Große Skarabäuskästen buggy

### ISSUE THREAD

**Issue by MisterMarax** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1978]
Welches Verhalten wird beobachtet?
Die Großen Skarabäuskästen in AQ40 bleiben nicht offen, wenn man sie einmal mit einem Großen Skarabäusschlüssel aufgeschlossen hat. Werden die Kästen mit einem Schlüssel geöffnet und man schließt das Lootfenster wieder, bevor alles herausgenommen wurde bzw. wenn noch etwas in den Kästen liegt, sind sie wieder verschlossen. Sie despawnen außerdem ca. 5-10min nach dem Öffnen, wenn noch Items darin liegen.

Wie sollte es sich verhalten?
Die Kästen sollten offen bleiben, wenn sie einmal aufgeschlossen worden sind und sollten nicht despawnen nach einmaligen Öffnen. Dies war auch bis vor kurzem bereits der Fall hier auf dem Server. Vielleicht hat ein neuer Patch diesen Bug aus Versehen wieder eingeführt.

Schritte zur Reproduzierung
Nach AQ40 gehen, Kästen aufschließen, Loot drin lassen, Loot-Fenster schließen und die Kiste ist wieder verschlossen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Habe kein Videoprogramm, deshalb leider keine Videos.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Großer Skarabäuskasten: http://datenbank.classic-wow.org/?object=180690
Großer Skarabäusschlüssel: http://datenbank.classic-wow.org/?item=21762

**Comment by dagochen** [comment]
Kann es sein, dass dies alle Kisten inkl. Schließkassetten betrifft?

**Comment by MisterMarax** [comment]
Da beim Cast des Öffnens (http://datenbank.classic-wow.org/?spell=26588) steht, dass der Key die Truhe öffnet, denke ich sie sollte offen bleiben, da dies auch bei Schließkassetten und verschlossenen Truhen der Fall ist, wenn sie einmal (!) geöffnet wurden durch einen Schurken oder mittels Dietrich.

In dem Eintrag von Sheed90 wird dieser Punkt ebenfalls erwähnt: 
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1552

Zudem blieben vor dem Update am 15.01.2016 die Kisten nach einmaligem Öffnen offen und despawnten nicht nach kurzer Zeit, obwohl noch Loot enthalten war. Da dieser Punkt nicht in den Update-News aufgeführt war, nehme ich an, dass sich dieses Verhalten ungewollt beim Patchen eingeschlichen hat.
