### ISSUE TITLE
Richturteil des befehls damage 

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1981]
Welches Verhalten wird beobachtet?
Gefühlt seit dem letzten update wird der schaden des paladin spells "richturteil des befehls" nicht mehr erhöht wenn zuvor "richturteil des kreuzfahrers" gerichtet wurde. mein paladin hat ca 300 spell damage und rank 5 richturteil des befehls macht ca 330 damage auf das ziel und der damage erhöht sich nicht wenn kreuzfahrer gerichtet wurde, auch hat das skillen des talentes" verbessertes siegel des kreuzfahreres keinen unterschied gemacht egal ob geskillt oder nicht, komischer weise merkt man bei anderen heilig spells wie holy shock oder richturteil der rechtschaffenheit ( im schnitt ohne debuff 320 damage, mit kreuzfaherer 400damage) einen deutlichen damage anstieg wenn kreuzfahrer gerichtet wurde.

Wie sollte es sich verhalten?
der spell richturteil des kreuzfahreres sollte alle heiligschadenspells auf das ziel bis zu 161 erhöhen, also auch das richturteil des befehls betreffen.

Schritte zur Reproduzierung
ein ziel mit richturteil des befehls angreifen, danach das selbe nochmal nur das man vorher richturteil des kreuzfahrers richtet.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
1. Keine Quellen über die Skalierung von Richturteil des Befehl
2. Ein einziger Satz als Beschreibung des Problems. Bitte versuch es so zu schreiben, dass man den Text nicht 10x lesen muss.

**Comment by Sabbaer** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1261

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1982
