### ISSUE TITLE
Richturteil des befehls

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1982]
Welches Verhalten wird beobachtet?
Gefühlt seit dem letzten update wird der schaden des paladin spells "richturteil des befehls" nicht mehr erhöht wenn zuvor "richturteil des kreuzfahrers" gerichtet wurde. mein paladin hat ca 300 spell damage und rank 5 richturteil des befehls macht ca 330 damage auf das ziel und der damage erhöht sich nicht wenn kreuzfahrer gerichtet wurde

Wie sollte es sich verhalten?
der spell richturteil des kreuzfahreres sollte alle heiligschadenspells auf das ziel bis zu 161(geskillt durch talent) erhöhen, also auch das richturteil des befehls betreffen.

Schritte zur Reproduzierung
ein ziel mit richturteil des befehls angreifen, danach das selbe nochmal nur das man vorher richturteil des kreuzfahrers richtet.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=20920
http://datenbank.classic-wow.org/?spell=20308 
http://paladin-guide.blogspot.de/2005/12/judgements.html skalierungen von damals

**Comment by Sabbaer** [comment]
nicht vergessen, es sind viele ränge von sdb, nicht wieder nur 1 fixen ;)

**Comment by Acolatronico** [comment]
gibt es schon neuigkeiten hierzu da der bug seit februar vorhanden ist :/

**Comment by Acolatronico** [comment]
/push für alle raidenden retris da es einer unserer haupt angriffe dadurch weniger schaden machen

**Comment by Dotox** [comment]
Kann das mal jemand auf dem Testserver testen und mir eventuell richtige Zahlen liefern, mit denen ich das korrekt reproduzieren kann?

**Comment by Acolatronico** [comment]
wie meinst du das mit richtigen zahlen ?, auf dem test server ist es wie auf dem live server, wenn ich richurteil des kreuzfahreres auf mein ziel bringe und danach richturteil des befehls wirke, wird dieser damage nicht erhöht was er aber sollte, da das richturteil des kreuzfahreres allen heilig schaden auf das ziel um 198 damage erhöhen sollte.
mit dem spell weihe kann man das gut testen da der weihe tick damage fix ist und korrekt mit dem richturteil des kreuzfahrers debuff erhöht wird

**Comment by hraesvelgr** [comment]
du solltest eine korrekte berechnung liefern. dass richturteil des kreuzfahrers zu wenig spelldamage gibt und die formel falsch ist, ist allgemein bekannt. aber wie ist es richtig? was ist die korrekte formel für 1.12.1? 

ausserdem: +198 schaden ist so nicht ganz richtig, denn dies ist der absolute maximalwert. 
dazu kommt aber dann noch der zauberschaden koeffizient, welcher in % angibt, wieviel dieser 198 (in diesem beispiel) eigentlich genutzt werden.
