### ISSUE TITLE
PvP Flag beim töten von Greifenmeistern

### ISSUE THREAD

**Issue by absdr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1983]
Welches Verhalten wird beobachtet?
Man wird durch das Töten von Greifenmeistern der gegnerischen Fraktion nicht PvP geflaggt. Tritt z.B. bei den Greifenmeistern in Gromgol und Everlook auf.

Wie sollte es sich verhalten?
Man sollte PvP geflaggt werden, da die Greifenmeister Mitglied der gegnerischen Fraktionen sind. (z.B. Fraktion Darnassus)

Schritte zur Reproduzierung
Ohne PvP Flag Greifenmeister in Everlook töten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Hier mal der in Everlook von der Allianz den ich eben zum Testen gekillt habe.
http://datenbank.classic-wow.org/?npc=11138

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=11138

Ich hab natürlich nicht alle greifenmeister getestet...

**Comment by Sheed90** [comment]
Quelle?

**Comment by absdr** [comment]
Nun ja ist ja eig ein offensichtlicher bug aber ok...

http://wowwiki.wikia.com/wiki/PvP_flag#Putting_up_your_flag

Sollte wohl für classic gelten da es nur eine änderung zu 1.6 gab welche ausschließlich das /pvp beim fliegen betrifft

**Comment by absdr** [comment]
http://m.imgur.com/a/ZNuvm

Original Spielhandbuch.

**Comment by dagochen** [comment]
Wie sieht es mit Wachen aus? Funktioniert es da?

**Comment by absdr** [comment]
Gerade getestet an Schildwache von Astranaar  http://datenbank.classic-wow.org/?npc=6087 obwohl die Wachen das PvP Zeichen besitzen und als PvP angezeigt werden wird keine PvP Flag aktiviert.
