### ISSUE TITLE
Ruf Mondfest

### ISSUE THREAD

**Issue by Schallwelle90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1985]
Welches Verhalten wird beobachtet?
Die Quests der Urahnen sollten Ruf für die Horde geben, allerdings wird der Ruf bei keiner Hordenfraktion gutgeschrieben.
Wie sollte es sich verhalten?
Der Ruf sollte entsprechend der Anzeige um 75 Punkte erhöht werden.
Schritte zur Reproduzierung
Quest abgeben
Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Ist kein Bug. Ist ein eigenständiger Ruf den man erst mit BC sichtbar sieht
