### ISSUE TITLE
Feindliches Duell: Totem wirken weiter

### ISSUE THREAD

**Issue by padomu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1986]
Hallo,

wenn ich (Schurke) ein Duell mit einem Hordler mache (Schamane), wobei ich einen PvP-Account habe und der Hordler einen PvE [die einzige ausprobierte Kombination] und wir ein Duell machen, dann greifen mich die Totems nach dem Duell weiter an, wobei ich sie jedoch nicht angreifen kann.

Ich denke, die Totems sollten das nicht machen.

**Comment by hraesvelgr** [comment]
"greifen dich weiter an".... bedeutet das, dass sie dauerhaft aggressiv dir gegenüber sind und mehrfach casts auf dich zaubern (i.e. totem der verbrennung (oder so)), oder flog zuffällig nach ende des duells noch ein cast auf dich, der noch grad so gewirkt wurde, bevor das duell zuende war? 

generell klingt es fast logisch, dass totems einen pvp geflaggten spieler angreifen, jedoch ist es wohl falsch, dass das totem (bzw der angreifende spieler) das auch tut, wenn er/es selber nicht geflaggt ist

**Comment by padomu** [comment]
Die casten bis sie verschwinden. Wenn mich das Totem angreift, sollte dann nicht der Spieler PvP-Markiert sein? So wie wenn ich als PvP flagged Spieler in nen AoE von nem PvE Spieler renne und er dann flagged ist?

**Comment by dagochen** [comment]
Quellen?
