### ISSUE TITLE
AQ40 - Caster Tank hat nach Port Aggro vom Melee Twin

### ISSUE THREAD

**Issue by Denson87** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1987]
Welches Verhalten wird beobachtet?

Wir hatten gestern Abend in AQ40 mehrmals in Folge bei den Twins das Problem, das nach dem Teleport der Twins der Warlock Tank auf der anderen Seite Aggro vom Melee Twin hatte der sich auf die andere Seite geportet hatte. Zweimal wurde der linke WL vom nach rechts geporteten Melee umgehauen und einmal der rechte WL vom nach links geporteten Melee.

Wie sollte es sich verhalten?

Nach dem Port sollte derjenige Initialaggro haben der sich am nächsten zum Twin befindet.

Schritte zur Reproduzierung

Wüsste ehrlich gesagt nicht wie. 

Zusätzliche Informationen (Screenshots, Videos, etc.)

https://www.twitch.tv/videos/121640839
Zu sehen ab 2:21:30 und ab 2:42:20 und ab 2:57:30 sehr schön das er einfach nach dem Port rüberläuft und den Hexer angreift.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=15276
http://datenbank.classic-wow.org/?npc=15275

**Comment by Dotox** [comment]
> Wüsste ehrlich gesagt nicht wie.

Hier das gleiche. Ohne Hinweise zur Reproduzierung können wir nichts machen.

**Comment by ChichiWarrior** [comment]
Leider ist im Video nicht ersichtlich wen der Meleetwin direkt nach dem Port im Target hat, desweiteren wäre interessant zu wissen, ob er bei der Positionsverschiebung vom Meleetank abgefangen wird.

Mehr Informationen, bzw. eine bessere Sichtweise könnte bei der Analyse helfen.

Im Vergleich zu den Teleports und der Anzahl der Gilden, die beim Boss waren, könnte es auch einfach an den Spielern gelegen haben. #nooffense

**Comment by Denson87** [comment]
Er hat nach dem Port als erstes den Hexer Tank auf der anderen Seite im Target und rennt direkt auf Ihn zu und greift ihn an. Er läuft einfach durch den Warri Tank durch der am nächsten nach dem Port dran steht um ihn abzufangen. 

Fehler von Spielern würde ich zu 99% ausschließen weil es jede Woche die gleichen Tanks machen. Der Try vor den 3 buggy Trys ging ja ohne Probleme bis zum enrage. Komisch war euch das die Twins bei den 3 Trys zum Start 101% HP hatten. Vllt war das aber auch nur ein Anzeigefehler. 

Zur Reproduktion würde ich vorschlagen mit 4 Tanks rein und den Teleport so oft testen bis der Bug auftritt. Bin da etwas ratlos aber ich versuch noch mehr Infos zu beschaffen in der Gilde

**Comment by Badorr** [comment]
Das ist ein Bug, der rein gar nix mit dem spielerischen Vermögen von Spielern oder Gilden zu tun hat@Ghichi 8-)
Es hat sehr wahrscheinlich damit zu tun, dass tote Spieler im Boss liegen. Da diese beim Port am Nahesten beim Boss sind, buggt die Initialaggro und der Twin rennt auf die andere Seite zum vorherigen Aggrohalter. Diese Spieler also einfach battlerezzen oder sie auffordern, den Geist freizulassen. Pets auch unbedingt rezzen!

**Comment by Larirawiel** [comment]
Das wäre jetzt auch mein Tipp gewesen. Wenn ein Spieler in der Nähe der Twins tot liegt dann soll er auf jeden Fall den Geist frei lassen oder ein Druide soll ihn wiederbeleben. Ansonsten versucht das Spiel diesem Spieler die Initialaggro zu geben was aber nicht klappt weil er tot ist. Es könnte auch Pets oder Totems betreffen.

Grüße

**Comment by Dotox** [comment]
Tote Spieler werden nicht von der Funktion beachtet.

**Comment by Denson87** [comment]
Bug ist bisher nicht mehr aufgetreten da wir nun versuchen tote Pets und Spieler zu ressen oder dem Geist freilassen. 

Ein anderer Fehler der gestern Abend auftrat war das der Melee Twin nach einem Port auf Evade ging und sich auch nicht mehr entbuggen ließ. Er stand nach jedem weiteren Port einfach rum und machte nix mehr. Führte dann zum Wipe da der Dmg nur auf den Caster nichtmehr bis zum Enrage gereicht hätte und wir ja kein bugusing betreiben wollen.

**Comment by jinthaalor** [comment]
Tote Spieler und Pets werden definitiv (Stand 26.2.) noch von den Twins anvisiert. Solange eine Leiche unter dem Caster liegt, wird die AE gespammt, und sollte beim Teleport eine Leiche näher als ein Spieler an der Teleportposition sein, verpufft der Initialaggro-Effekt.

**Comment by Dotox** [comment]
> Tote Spieler und Pets werden definitiv (Stand 26.2.) noch von den Twins anvisiert.

Kann ich, wie bereits geschrieben, nicht reroduzieren. Könnt ihr davon eventuell bei Gelegenheit ein Video hochladen in dem das eindeutig zu sehen ist?
