### ISSUE TITLE
AQ40 - Bug Trio respawned komplett nachdem der zweite Bug gekillt wurde

### ISSUE THREAD

**Issue by Denson87** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1988]
Welches Verhalten wird beobachtet?

Wir hatten gestern Abend und auch schon mehrmals davor das Problem, dass die 2 schon gekillten Bugs instant respawnen sobald der zweite Bug gekillt wird. 

Beispiel: Kri wird zuerst gekillt, alles funktioniert wie gewollt. Dann wird die Prinzessin gekillt, Kri und die Prinzessin respawnen instant und Vem bleibt dort stehen wo er aktuell getankt wird. Das selbe passierte auch schon wenn Vem als zweites gekillt wird.

Wie sollte es sich verhalten?

Die Bosse sollten nacheinander egal in welcher Reihenfolge zu killen sein ohne das Teile des Bug trios respanwnen.

Schritte zur Reproduzierung

Wüsste nicht wie.

Zusätzliche Informationen (Screenshots, Videos, etc.)

https://www.twitch.tv/videos/121640839
Zu sehen ab 3:27:20 und 3:37:05

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://datenbank.classic-wow.org/?npc=15511
http://datenbank.classic-wow.org/?npc=15543
http://datenbank.classic-wow.org/?npc=15544

**Comment by Dotox** [comment]
> Wüsste nicht wie.

Genau das ist das Problem. Ohne Hinweise zur Reproduzierung können wir da fast nichts machen.

**Comment by ChichiWarrior** [comment]
Wie man klar erkennen kann, fliegen Bolts NACH dem sterben von Yauj auf den Respawn.

Ich vermute, dass durch den fliegenden Bolt und dem nicht beendeten Kampf, der Encounter den jeweiligen toten Boss respawnen lässt.

Seitdem wir nur noch "direkten" Schaden machen, bevor der jeweilige Boss stirbt, hatten wir keinen Respawn mehr.
Mit "direktem" Schaden meine ich Meleehits oder Cast im Sinne von Scorch oder Searing Pain.

Vielleicht hilft das weiter.

Gruß

Chichi

**Comment by Denson87** [comment]
Dann würde ich zur Reproduktion den Post von Chichi aufgreifen und vorschlagen den Boss einmal zu killen während zB ein Feuerball noch auf das Ziel zufliegt. Also zB nen Warri killt den Boss während ein Mage nen Feuerball fliegen lässt. 

Es fällt mir etwas schwer etwas vorzuschlagen weil ich zB nicht weiss mit wievielen Spielern ihr da zur Reproduktion rein geht.

**Comment by Badorr** [comment]
Kann das so bestätigen. Es liegt definitiv daran, wenn ein Cast auf den Boss fliegt während er stirbt. Einfach ab ~15% Dmgstop für die Caster ansagen. Seitdem hatten wir den Bug auch nicht mehr.

**Comment by Denson87** [comment]
Haben es gestern Abend mal nach den Tipps hier versucht und wir hatten keine Probleme mit Respawn.

**Comment by Seraphitas** [comment]
Dann gibt es ja schritte zur reproduzierung des Bugs ;)

**Comment by dagochen** [comment]
Danke, konnte auf dem Testserver das Problem reproduzieren ;) 1 Schritt näher an einer Lösung also^^

**Comment by dagochen** [comment]
Tritt bei einigen Gilden immer noch auf.

**Comment by Denson87** [comment]
Seitdem wir die letzten 5% der Bosse immer nur durch direkte Melee Hits umhauen lassen und nicht mehr durch Caster und Hunter hatten wir bisher keinen Respawn mehr

**Comment by Dotox** [comment]
Nochmal was geändert. Mit 1.5.4 aktiv.
