### ISSUE TITLE
Arathibecken: Die Arbeiter an der Mine halten Dolche (Allianz)

### ISSUE THREAD

**Issue by padomu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1989]
Arathibecken: Die Arbeiter an der Mine halten Dolche (Allianz)

Der Titel sagt alles. Die hauen mit Dolchen auf Steine. :p

**Comment by Slimmer2** [comment]
wo ist die eingefügte Vorlage und Link zu den NPC?
http://datenbank.classic-wow.org/

**Comment by dagochen** [comment]
Und was sollten sie stattdessen halten? Hammer? Spitzhacke? Schaufel?
