### ISSUE TITLE
Quest Feurige Plattenstulpen nicht anehm/ machbar

### ISSUE THREAD

**Issue by Zahul** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1990]
Welches Verhalten wird beobachtet?
Bei der folgenden Quest .
http://datenbank.classic-wow.org/?quest=5124 bekommt man eine Meldung, Quest ist für deine Fraktion/klasse nicht annehmbar. 
Die Vorquest http://datenbank.classic-wow.org/?quest=5103/Hei%C3%9Fer,%20feuriger%20Tod ist machbar
Weiterhin sind die Stulpen http://datenbank.classic-wow.org/?item=12812 in Lbrs anscheinend nicht Lootbar. 
Der Behälter ist zwar vorhanden http://de.wowhead.com/quest=5103/heisser-feuriger-tod#screenshots:id=177376,  aber man bekommt immer ein leeres Fenster
.
 
Wie sollte es sich verhalten?
Da es sich um eine Quest für die Schmiedekunst handelt, und ich auch kein hinweis darauf gefunden da es nicht so ist. 
Sollte die Quest http://datenbank.classic-wow.org/?quest=5124 für Beide Fraktionen/ alle Klassen die Schmiedekunst ( evtl nur Rüstungsschmiede ) haben machbar sein.
Und da http://datenbank.classic-wow.org/?item=12812 die Stulpen vorraussetzung für die 2. Quest sind müssen diese auch zu einen Zeitpunkt Lootbar sein, nach meinen Quellen müssten die ehr bei der 1. Quest lootbar sein 

Schritte zur Reproduzierung
http://de.wowhead.com/quest=5103/heisser-feuriger-tod
http://www.wowhead.com/quest=5124/fiery-plate-gauntlets
http://de.wowhead.com/quest=5124/feurige-plattenstulpen
http://wowdata.buffed.de/quest/Winterquell/Feurige-Plattenstulpen-5124#dropped

Zusätzliche Informationen (Screenshots, Videos, etc.)
Ein Screeshot hab ich leider nicht, da ich aber versucht habe die Quest mit ein 300er Rüstungsschmied anzuehmen, wäre die evtl vorraussetzung vorhanden gewesen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by ChichiWarrior** [comment]
Hmm...ich kann die und hatte keine Probleme mit der Quest.

Ist aber schon 2-3 Monate her.

**Comment by Rukachi** [comment]
Ich kann die auch aber nur mithilfe eines GMs. 
Ich hatte das selbe Problem wie du. Möglicherweise ist die Folgequest nur für Horde verfügbar?

**Comment by Haudraufinix** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/983
