### ISSUE TITLE
Interrupts sorgen für GCD auf allen Spell Schools

### ISSUE THREAD

**Issue by Kriptyk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1991]
Welches Verhalten wird beobachtet?
Wird man während des Castens von einem Interrupt getroffen, wird auf allen Zaubern ein GCD ausgelöst.

Wie sollte es sich verhalten?
Es sollte auf der getroffenen Spell School ein CD entsprechend des Interrupt Effekts ausgelöst werden. Z.B. 10 Sekunden bei Counterspell. Alle anderen Spell Schools sollten verfügbar bleiben.

Schritte zur Reproduzierung
1. Casten
2. Interrupt auf den Castenden (z.B. Counterspell)
3. Beobachten ob School Lockout wirkt (wenn ja: gut)
4. Beobachten ob GCD auf allen anderen Schools getriggert wird (wenn ja: schlecht)

Zusätzliche Informationen (Screenshots, Videos, etc.)
Screens oder Videos habe ich keine sollte aber trivial sein das zu reproduzieren.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Alle Interrupt Effekte die mir gerade einfallen:
Couterspell(Mage): http://datenbank.classic-wow.org/?spell=2139
Earth Shock (Schamane): http://datenbank.classic-wow.org/?spell=8042
Kick (Rogue): http://datenbank.classic-wow.org/?spell=1766
Pummel (Warri): http://datenbank.classic-wow.org/?spell=6552
Spell Lock (Felhound, Hexer Pet): http://datenbank.classic-wow.org/?spell=19244

Quelle: Counterspell hat noch nie einen GCD auf andere Spells als die getroffene Spell School ausgelöst. Gibt auch keine Patchnotes die das Hinzufügen oder Entfernen einer solchen Mechanik zum Inhalt haben. Es kann also davon ausgegangen werden, dass das noch nie so war und mehr oder weniger jedes X-beliebige PvP Video als Quelle genommen werden.

**Comment by dagochen** [comment]
Dann mal her mit den x-beliebigen PvP Video Quellen ;)

**Comment by Kriptyk** [comment]
http://www.warcraftmovies.com/movieview.php?id=247254

Bei 13:10 frisst der Priest einen Kick auf Manaburn und castet instant danach Power Word: Shield.

**Comment by dagochen** [comment]
Arena gabs in Classic nocht nicht...

**Comment by Kriptyk** [comment]
Da du meine Argumentation zur Quelle anscheinend nicht verstanden hast hier der zweite Versuch:
Counterspell (oder andere Interrupts) haben noch NIE, in KEINER VERSION VON WOW, JEMALS einen GCD ausgelöst.
Allgemeine Interrupt Patchnotes: http://wow.gamepedia.com/Interrupt#Patch_changes
Du kannst dir also auch einen Livestream vom aktuellen WoW anschauen und das als Quelle nehmen. Sowas gab es schlicht und ergreifend NIE.

**Comment by armaggedon1** [comment]
Steht bei jedem Spell im Tooltip btw,

"interrupts spellcasting and prevents any spell in that school from being cast for 4 sec."

Also eindeutiger gehts ja wohl net.

**Comment by Kriptyk** [comment]
Eindeutiger im Bezug auf was? Ich hab nie behauptet dass der Lockout an sich buggt.

**Comment by armaggedon1** [comment]
Oh, lesen sollte man allerdings vorher :D

**Comment by dagochen** [comment]
Also ich kann im Quellcode nix finden, dass bei einem Spell Interrupt den Global Cooldown auslöst. Bevor ich mich jetzt noch weiter totsuche, wär mir halt wirklich eine Video-Quelle von damals lieb, anhand derer man sieht, dass ein Interrupt keinen GCD auslöst, da wenn es nix im Quellcode gibt dieser clientseitig ausgelöst wird durch den Interrupt und von uns garnicht gefixt werden kann.

**Comment by Kriptyk** [comment]
Das Problem an Quellen aus Classic WoW ist a) es gibt nicht viele die tatsächlich verifizierbar sind und b) es handelt sich dabei eigentlich ausschließlich um Highlight reels...und wer zeigt da schon gerne wie er sich nen Interrupt einfängt? Ich hab heute 2h Videos durchgesucht und keine einzige Szene gefunden in der im Ansatz zu erkennen wäre ob es so war oder nicht während ich die oben verlinkte Quelle nach nicht ein mal 5 Minuten hatte.

Wenn im Quellcode nichts entsprechendes zu finden ist...woher kommt dann die beobachtete Mechanik? Irgend jemand muss zu irgend einem Zeitpunkt ja mal gedacht haben, dass das so korrekt ist und es entsprechend implementiert haben.

**Comment by Kriptyk** [comment]
Da man ja anscheinend jetzt mit "ist auf dem Liveserver so und wurde nie geändert" argumentieren darf (https://community.mmobase.de/updates-changelog/10634-update-31-03-2017-a-2.html#post74439)

reopen plz?

Auch relatiert mit der selben Argumentation: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1996

**Comment by Dotox** [comment]
Wäre super wenn du aufhörst irgendwelche Einträge zu verlinken, die überhaupts nicht miteinander zu tun haben.

**Comment by Kriptyk** [comment]
Kann gerne unter beide Posten, wenns unerwünscht ist das so zu erledigen.
Dachte mir nur so spart es allen Beteiligten ein paar Klicks.

**Comment by dagochen** [comment]
@Kriptyk Dir ist schon klar das mein Kommentar im Forum darauf bezogen war, dass jemand behauptet hat, dass Blizzard angeblich das durch die Wand hauen irgendwann behoben hätte (oder auch nicht, weil es so nie war) und das durch die Baumstümpfe angeblich seit einiger Zeit nicht mehr durchgeschossen werden kann, weil es ein Bug seitens Blizzard gewesen wäre. Beides lässt sich durch den aktuellen Zustand auf den Live-Servern widerlegen.

Zu deinem Bugreport: Finde Quellen oder lass es. Im Server wird lediglich der Spellschool-Cooldown ausgelöst. Vermutlich wird der GCD vom Client ausgelöst, wenn er den Cooldown auf die Magieschule empfängt. Ob man das durch Servercode unterbinden kann ist fraglich und kann dir vermutlich keiner sagen. Würde klar sein, ob dieses Verhalten von unserem Server wirklich falsch ist, könnte man an der Stelle tatsächlich Zeit investieren und es versuchen zu lösen. Vorher werde ich da aber nicht auf gut Glück Zeit investieren...

**Comment by Kriptyk** [comment]
Hab mir lange überlegt was ich dazu sagen soll aber ich bin mittlerweile zu dem Schluss gekommen, dass es egal ist. Es wird sowieso alles so ausgelegt, dass es dir in den Kram passt Dago.

> oder lass es
Gute Idee. Auf diesem Niveau hat das sowieso keinen Sinn.
