### ISSUE TITLE
Hunter Flare Dauer zu hoch / Cd zu niedrig

### ISSUE THREAD

**Issue by Ichnixwissen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1992]
Welches Verhalten wird beobachtet?
Laut der Datenbank ist die Dauer von Flare bei 30 Sekunden und der Cd nur bei 15 Sekunden.

Wie sollte es sich verhalten?
Laut einer schlauen Seite http://wow.gamepedia.com/Patch_1.7.0, geht man etwas runter zu dem Bereich Hunter, dort sucht man das Wort Flare und siehe da dort seht folgendes. 20 sec Cooldown und 20 sec dauer.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=1543

**Comment by Dotox** [comment]
Bitte im Spiel testen. Die Datenbank ist in diesem Fall keine Quelle.

**Comment by dagochen** [comment]
Cooldown
15 seconds

Reveals any stealthed unit within 30 yards for 30 seconds.

October 2, 2006 
http://wowwiki.wikia.com/wiki/Flare?oldid=269907
