### ISSUE TITLE
Kälteeinbruch setzt nach Zonenwechsel(Loadscreen) CDs nicht zurück

### ISSUE THREAD

**Issue by Kriptyk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1995]
Welches Verhalten wird beobachtet?
Siehe Titel

Wie sollte es sich verhalten?
Der CD aller Frostzauber sollte wie beschrieben zurückgesetzt werden.

Schritte zur Reproduzierung
1. Kälteeinbruch skillen
2. Frostzauber mit CD verwenden (Eisblock bietet sich an, da langer CD)
3. Zone wechseln (Instanz oder Schlachtfeld betreten z.B.)
4. Kälteeinbruch verwenden

Zusätzliche Informationen (Screenshots, Videos, etc.)
Video: https://youtu.be/9ssQkUreWEE

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Kälteeinbruch: http://datenbank.classic-wow.org/?spell=12472
Eisblock: http://datenbank.classic-wow.org/?spell=27619

**Comment by Slimmer2** [comment]
Kann ich bestätigen

**Comment by Kriptyk** [comment]
Der Bug scheint auch beim Schurken mit Vorbereitung zu existieren: #1172
