### ISSUE TITLE
Stealth Mechaniken sorgen für 100% Spell Resist

### ISSUE THREAD

**Issue by Kriptyk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1996]
Welches Verhalten wird beobachtet?
Sämtliche Mechaniken die es einem erlauben zu Stealthen sorgen dafür, dass Casts die sich bereits in der Luft befinden zu 100% resisted werden.

Wie sollte es sich verhalten?
Spells die sich bereits in der Luft befinden sollten Schaden machen auch wenn das Ziel sich während der Flugzeit in Stealth begibt.

Schritte zur Reproduzierung
1. Duell beginnen
2. Cast mit Flugzeit abfeuern
3. Während sich der Cast in der Luft befindet Stealthen
4. Combat Log beobachten: Der Spell wird resisted oder tut gar nichts.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Video für Shadowmeld: https://youtu.be/FtwhoATmCFs
Video für Unsichtbarkeitstrank: https://youtu.be/WC-PFv7knuY
Bug tritt in gleicher Form auch bei Totstellen auf.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Shadowmeld: http://datenbank.classic-wow.org/?spell=20580
Rogue Stealth: http://datenbank.classic-wow.org/?spell=1787
Vanish: http://datenbank.classic-wow.org/?spell=24699
Totstellen: http://datenbank.classic-wow.org/?spell=5384
Druiden Stealth: http://datenbank.classic-wow.org/?spell=9913
Unsichtbarkeitstrank: http://datenbank.classic-wow.org/?spell=11392
Geringer Unsichtbarkeitstrank: http://datenbank.classic-wow.org/?spell=3680

**Comment by Kriptyk** [comment]
Grade noch ein paar alte Patchnotes ausgegraben und für Vanish scheint diese Mechanik explizit so gewollt zu sein. Ich mein zwar, dass das in classic buggy war und nicht funktioniert hat aber dafür habe ich im Moment keine Quelle. Bei allen anderen aufgelisteten Mechaniken ist es definitiv ein Bug.

Patchnotes Vanish: http://wow.gamepedia.com/Vanish
Patchnotes 1.1.0: http://wow.gamepedia.com/Patch_1.1.0
Patchnotes 1.1.0 alternativer Link: https://www.engadget.com/2011/05/10/wow-archivist-world-of-warcraft-patch-1-1/

**Comment by Slimmer2** [comment]
Also ist es kein Bug?
Wenn ein Ziel unsichtbar wird kann man es nicht mehr sehen.
Wenn man was nicht sieht kann man es auch nicht Treffen.

**Comment by Seniorash** [comment]
Ja und wenn man einen Schritt zur Seite geht wird man auch nicht getroffen >.<

**Comment by dagochen** [comment]
?!

**Comment by dagochen** [comment]
Also für Vanish scheint es ja richtig zu sein. Für alle anderen Spells ist es "unklar"?

**Comment by Kriptyk** [comment]
Wenn es für Vanish EXPLIZIT reingepatcht wurde ist es automatisch für alle anderen Stealth Mechaniken die völlig anders funktionieren auch so? Was genau ist an der Stelle "unklar"?

**Comment by dagochen** [comment]
Du hast bisher nur nachgewiesen, dass es für Vanish so sein soll, wie es ist. Und bitte unterlass das Capslock, das kommt so passiv-aggressiv rüber, da verliert man schnell die Lust. Das gilt übrigens für alle deine Bugreports, danke! 

Mir ist schon klar, dass Stealth eine andere Mechanik als Vanish ist und es vermutlich so sein soll, wie du schreibst. Aber allein auf 

>Ich mein zwar, dass das in classic buggy war und nicht funktioniert hat aber dafür habe ich im Moment keine Quelle.

basierend, können und werden wir nichts ändern. Dann kommt morgen jemand anderes und "glaubt sich zu erinnern das es vielleicht doch ganz anders gewesen sein könnte" und wir müssen nochmal was ändern.

**Comment by Kriptyk** [comment]
Damit meinte ich, dass Vanish buggy war. Nicht alles andere.
