### ISSUE TITLE
Fear Ward funktioniert nicht immer einwandfrei

### ISSUE THREAD

**Issue by soda09** [ClassicWoW/Nefarian_1.12.1_Bugtracker#1998]
Welches Verhalten wird beobachtet?
Ab und zu, kann man gefeard werden, obwohl man einen "Fear Ward" auf sich hat.

Wie sollte es sich verhalten?
Solange der Zauber "Fear Ward" aktiv ist, sollte man nicht gefeared werden können.

Schritte zur Reproduzierung
Ich habe leider keine Ahnung, wann genau dieser Bug auftritt oder wodurch er ausgelöst wird. Er tritt bei allen Klassen auf.

http://datenbank.classic-wow.org/?spell=6346

**Comment by dagochen** [comment]
Duplikat: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1295
