### ISSUE TITLE
AQ20 Generalleutnant Andorov

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2001]
Welches Verhalten wird beobachtet?
Generalleutnant Andorov lässt zurzeit leider nicht mit sich handeln man bekommt immer die Nachricht diesr NPC mag euch nicht

Wie sollte es sich verhalten?
Nachdem das Rajaxx event erfolgreich beendet wurde und Der General überlebt hatt sollte man ihn ansprechen können um mit ihm zu handeln. Er sollte 2 Schmiedekunst Rezepte verkaufen und unter anderem:
5x Erheblicher Manatrank
4x Erheblicher Heiltrank
18x Schwerer Runenstoffverband

http://datenbank.classic-wow.org/?item=22221
http://datenbank.classic-wow.org/?item=22219
Schritte zur Reproduzierung
Adorov ansprechen und handelsfenster öffnen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www.wowhead.com/npc=15471/lieutenant-general-andorov#sells

Ist zwar einmal als Behoben gekennzeichnet. Es geht aber weiterhin nicht.

**Comment by jinthaalor** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1499 :>

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1451
