### ISSUE TITLE
Käpt'n Sanders versteckter Schatz

### ISSUE THREAD

**Issue by Kunstbongo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2003]
Welches Verhalten wird beobachtet?
Beim Abgeben der Quest bekommt man seine Belohnung nur, wenn das Inventar nicht voll ist, beenden kann man die Quest aber trotzdem. Und angezeigt bekommt man, das man alle Items erhalten hat.
Wie sollte es sich verhalten?
Wenn Inventar voll, dann ist ein Abgeben der Quest nicht möglich.
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

![wowscrnshot_022217_202020](https://cloud.githubusercontent.com/assets/25964247/23229291/0fb06914-f940-11e6-9dd7-b976568883ce.png)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Das Problem Käpt'n Sanders' Hemd kann man dann nicht mehr über die Quest bekommen, was ziemlich doof ist.

**Comment by dagochen** [comment]
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/782
