### ISSUE TITLE
Ausweichen hinter dem Mob

### ISSUE THREAD

**Issue by Seraphitas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2004]
Welches Verhalten wird beobachtet?

Wenn ich als Druiden Katze hinter einem Mob stehe kann dieser Ausweichen

Wie sollte es sich verhalten?

Mobs dürfen nicht Ausweichen wenn man hinter Ihnen steht.

Schritte zur Reproduzierung

Einfach als Nahkämpfer hinter einem Mob schaden verursachen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by jinthaalor** [comment]
Das ist schon korrekt so, hinter dem Mob stehen verhindert lediglich das Parieren. Ausweichen ist, abhängig von deiner Hitchance und dem Gegnerlevel, durchaus auch von hinten möglich, solange das Ziel nicht gestunnt ist.

**Comment by Haudraufinix** [comment]
"Note that when a player attacks a mob from behind, the mob can still dodge. However, when a mob attacks a player from behind, the player cannot dodge. Therefore, it's important that players always face mobs that are attacking them."

http://wowwiki.wikia.com/wiki/Dodge?oldid=1777222 ist leider aus 2009. Find das nicht aus classic Dokumentiert, müsste meines Wissens nach allerdings schon in classic so gewesen sein.
