### ISSUE TITLE
Erste Hilfe ab Skill 225 nicht möglich da Quest verbuggt ist

### ISSUE THREAD

**Issue by Seraphitas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2005]
Welches Verhalten wird beobachtet?

Die Quest http://datenbank.classic-wow.org/?quest=6624 kann man nach abbrechen nicht erneut annehmen. Der NPC ist für mich nicht mehr ansprechbar.

Wie sollte es sich verhalten?

Der NPC http://datenbank.classic-wow.org/?npc=12939 sollte nach Abbruch der Quest erneut ansprechbar sein.

Schritte zur Reproduzierung

Q Annehmen und wieder abbrechen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Ein anderer Spieler mit dem ich in einer Gruppe war kann die Quest ebenfalls nicht mehr annehmen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Seraphitas** [comment]
Update: Am nächsten Tag war die Quest dann Solo machbar. Bitte aber trotzdem nach dem Problem schauen.

**Comment by dagochen** [comment]
Wurde der Server zwischen den Versuchen neugestartet? Hast du dein WDB gelöscht? Vermutlich nicht mehr herauszufinden woran es lag, da es doch schon recht lange her ist :( Sorry^^

Daher mache ich mal zu...
