### ISSUE TITLE
AQ40 - C'Thun: Tentakelportale verschwinden nicht bei einem Wipe

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2006]
**Welches Verhalten wird beobachtet?**
Wenn man bei C'Thun wiped, bleiben die Tentakelportale (schwarze Kreise unterhalb aller Tentakeln) aller zum Zeitpunkt des Wipe bestehenden Tentakeln sichtbar.

**Wie sollte es sich verhalten?**
Die Tentakelportale sollten zusammen mit den Tentakeln bei einem Wipe despawnen.

**Schritte zur Reproduzierung**
Bei C'Thun wipen während Tentakel vorhanden sind.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://www.youtube.com/watch?v=yxz39w7P1SA&feature=youtu.be

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Augententakel: http://datenbank.classic-wow.org/?npc=15726
Riesiges Augententakel: http://datenbank.classic-wow.org/?npc=15334
Klauententakel: http://datenbank.classic-wow.org/?npc=15725
Riesiges Klauententakel: http://datenbank.classic-wow.org/?npc=15728

Tentakelportal: http://datenbank.classic-wow.org/?npc=15904
Riesiges Tentakelportal: http://datenbank.classic-wow.org/?npc=15910

**Comment by Dotox** [comment]
Sind sie denn noch vorhanden, wenn ihr einen neuen versuch startet?

**Comment by Nifexx** [comment]
Ab dem ersten Wipe sind sie dauerhaft vorhanden.

**Comment by jinthaalor** [comment]
Nach einem Softreset der Instanz sind sie wieder weg, falls das hilft^^
