### ISSUE TITLE
AQ40 - C'Thun: Fehlendes Emote am Anfang der Schwächephase

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2007]
**Welches Verhalten wird beobachtet?**
Kein Emote am Anfang der Schwächephase.

**Wie sollte es sich verhalten?**
C'Thun sollte am Anfang der Schwächephase ein Emote benutzen. 
deDE: "C'Thun ist geschwächt"
enUS: "C'Thun is weakened"

**Schritte zur Reproduzierung**
C'Thun in die Schwächephase bringen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Fleischtentakel wird gekillt: https://youtu.be/34ba7rg0gdc?t=6m12s 
C'Thun wird rosa: https://youtu.be/34ba7rg0gdc?t=8m31s
Deutsches Emote: http://www.strike-us-if-you-can.de/main/plain/includes/instanz/high-level/aq-40-10.htm

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
C'Thun: http://datenbank.classic-wow.org/?npc=15727
Fleischtentakel: http://datenbank.classic-wow.org/?npc=15802

**Comment by dagochen** [comment]
Ich hab noch nie beobachtet, dass da ein Emote kommt (zumindest im deutschen Client). Vielleicht kann da jemand noch was zu schreiben, ansonsten mach ich das hier zu da es wohl kein Fehler ist...?

**Comment by Nifexx** [comment]
https://www.youtube.com/watch?v=M_hiu3sqe2A&feature=youtu.be&t=326
bei 7:28. Außerdem wird es auch in dem von Dorann geposteten Guide erwähnt. Und du kannst das Emote auch nicht gesehen haben, weil es ja nicht auf dem Server ist. Deshalb ja der Beitrag.

**Comment by xorann** [comment]
Ich habe doch oben extra Quellen dazu gepostet? Wie dem auch sei, hier noch ein paar mehr.

Hier noch ein paar mehr:
https://youtu.be/46yJL8eFxaQ?t=10m1s
https://youtu.be/FJVaHYPxdQM?t=6m31s

BigWigs: https://github.com/BigWigsMods/BigWigs_Classic/blob/master/AQ40/Cthun.lua#L51
C'Thun Warner: https://github.com/ericraio/vanilla-wow-addons/blob/master/c/CThunWarner/CThunWarner.lua#L19

Für den deutschen Client hab ich nur dieses Video gefunden. Leider hat er die Emotes im Chat deaktiviert, aber er hat das Addon "C'Thun Warner" am laufen, das nur auf das Event reagieren kann, wenn es existiert:
https://youtu.be/FbZ-UswNxTQ?t=3m50s

**Comment by dagochen** [comment]
Aso....dann wars ein Missverständnis :(

>Wie sollte es sich verhalten?
Kein Emote am Anfang der Schwächephase.

Klang für mich so, als ob es eins gäbe und falsch wäre.
