### ISSUE TITLE
AQ40 - Anubisath Defender: Shadow Storm

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2010]
**Welches Verhalten wird beobachtet?**
Die Fähigkeit Shadow Storm der Anubisath Defender (Trash zwischen Huhuran und Twin Emperors) trifft auch Spieler in Nahkampfreichweite.

**Wie sollte es sich verhalten?**
Shadow Storm sollte eine Mindestreichweite von 20 (wowwiki) oder 25 (unsere datenbank) yards haben. 

**Schritte zur Reproduzierung**
Anubisath Defender angreifen der die Fähigkeit Shadow Storm benutzt und in Nahkampfreichweite stehen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://wowwiki.wikia.com/wiki/Anubisath_Defender
In der Beschreibung des Skills steht 25 feet mindestrange: http://datenbank.classic-wow.org/?spell=14297

Spieler welche sich nahe am Mob befinden, werden nicht getroffen: https://youtu.be/KF1KeJKQ1a0?t=38s

Shadow Storm wird vom Bossmod angekündigt: https://youtu.be/J510uRghX9M?t=43s
... selbes Video. Man kann immer wieder die Animation erkennen, aber es fliegt kein einziger Shadow Bolt: https://youtu.be/J510uRghX9M?t=1m10s

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Verteidiger der Anubisath: http://datenbank.classic-wow.org/?npc=15277
Shadow Storm: http://datenbank.classic-wow.org/?spell=14297

**Comment by Baraz** [comment]
#1487

**Comment by xorann** [comment]
Danke für den Hinweis. Dann schliesse ich dieses Ticket wieder.
