### ISSUE TITLE
AQ40 - Anubisath Sentinel: Shadow Storm

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2011]
**Welches Verhalten wird beobachtet?**
Die Fähigkeit Shadow Storm der Anubisath Sentinels (Trash vor Prophet Skeram) trifft auch Spieler in Nahkampfreichweite. 
Zudem richtet die Fähigkeit gar keinen Schaden mehr an, wenn sie durch den Tot des Sentinels mit der Fähigkeit Shadow Storm an die verbleibenden Sentinels vererbt wird. Die Shadow Bolts fliegen zwar durch die Gegend, aber verursachen einfach keinen Schaden.

**Wie sollte es sich verhalten?**
Shadow Storm sollte eine Mindestreichweite 25 yards haben. Wenn man in Nahkampfreichweite steht, richtet der Spell zwar keinen oder kaum Schaden an, es sollte aber eigentlich kein Shadowbolt losfliegen.

Zudem sollte Shadow Storm Schaden verursachen, wenn die Fähigkeit vererbt wird und man nicht in Nahkampfreichweite steht.

**Schritte zur Reproduzierung**
Anubisath Sentinel angreifen der die Fähigkeit Shadow Storm benutzt und in Nahkampfreichweite stehen.

Anubisath Sentinel mit der Fähigkeit Shadow Storm töten während mindestens noch ein weiterer Sentinel am leben ist und warten bis dieser die Fähigkeit Shadow Storm verwendet.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://wowwiki.wikia.com/wiki/Anubisath_Sentinel
In der Beschreibung des Skills steht 25 feet mindestrange: http://datenbank.classic-wow.org/?spell=14297

Vermutlich die selbe Fähigkeit, welche auch von den Anubisath Defender verwendet wird.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Wächter des Anubisath: http://datenbank.classic-wow.org/?npc=15264
Shadow Storm: http://datenbank.classic-wow.org/?spell=14297

**Comment by dagochen** [comment]
Wurde zusammen mit den anderen Shadowstorm-Spells behoben. Die Reichweite ist etwas strittig, da gibt es Werte in Foren und Beschreibungen die zwischen 10 und 20 schwanken. Vermutlich wurde das von Blizzard öfter geändert und im Tooltip nie aktualisiert.
