### ISSUE TITLE
Critical Error beim verwenden des Teleportmeisters

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2013]
**Welches Verhalten wird beobachtet?**
Wenn man sich mit einem Spieler in einer Gruppe befindet, welcher auf dem Zeppelin steht, das zwischen Orgrimmar und Grom'gol pendelt, und beide Spieler in der selben Zone sind (Stranglethorn Vale oder Durotar), so wird beim Verwenden der Option "Bringt mich nach Orgrimmar." bzw. "Bringt mich nach Grom'gol." des Teleportmeisters ein Critical Error verursacht.

Das selbe Verhalten tritt auch auf der Route zwischen Orgrimmar und Undercity und zwischen Booty Bay und Ratchet auf.
Die Route zwischen Undercity und Grom'gol ist von diesem Problem nicht betroffen.

**Wie sollte es sich verhalten?**
Es sollte kein Critical Error verursacht werden.

**Schritte zur Reproduzierung**
siehe oben.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
OG -> UC: http://datenbank.classic-wow.org/?npc=90100
OG -> GG: http://datenbank.classic-wow.org/?npc=90102
GG -> OG: http://datenbank.classic-wow.org/?npc=90103
UC -> ??: http://datenbank.classic-wow.org/?npc=90101
BB -> R: http://datenbank.classic-wow.org/?npc=90104
R -> BB: http://datenbank.classic-wow.org/?npc=90106

**Comment by Dotox** [comment]
Kann ich leider nicht reproduzieren.

**Comment by xorann** [comment]
Gerade noch einmal getestet. Ich bekomme jedesmal einen critical error. Getestet mit und ohne Addons, mit deutschem und englischen Client, WDB Ordner gelöscht.

http://imgur.com/a/XJDJI

Gibt es sonst noch irgendetwas woran das liegen kann? Ich habe das selbe Problem auch schon von Gildenkollegen gehört, ich bin also zumindest nicht der einzige.

**Comment by Herlot** [comment]
Ich habe das Problem auch manchmal, ich denke es hängt mit dem Schiff zusammen. Meine Vermutung ist, dass nur bei Ankunft des Schiffs der critical error erzeugt wird. Sonst kann ich auch ohne Einschränkung den Teleport nutzen.
