### ISSUE TITLE
Dire Maul Arena - Mushgog, Skarr The Unbreakable und The Razza

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2014]
**Welches Verhalten wird beobachtet?**
Mushgog, Skarr The Unbreakable und The Razza sind nicht in der Arena zwischen den drei Dire Maul Instanzen anzutreffen. Mushgog ist teilweise in DM East anzutreffen. 

**Wie sollte es sich verhalten?**
Alle sechs Stunden sollte Mushgog, Skarr The Unbreakable oder The Razza in der Arena in Dire Maul spawnen.

Zudem sollten zusammen mit den Rares diverse Highlevel Kräuter (Black Lotus, Dreamfoil, Purple Lotus, Ghost Mushrooms, Gromsblood, Golden Sansam, Mountain Silversage) in der Arena spawnen. 

**Schritte zur Reproduzierung**
In der Dire Maul Arena warten. DM East resetten bis Mushgog spawnt.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://github.com/TrinityCore/TrinityCore/issues/5882
http://wowwiki.wikia.com/wiki/Dire_Maul_East#Dire_Maul_East
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/51771-dire-maul-arena-farming.html
http://fin.instinct.org/bits/Herbalism%20-%201-300%20guide.txt
https://translate.google.com/translate?hl=en&sl=no&u=http://pingx.net/quakenet/wow.no/2005/10/22/5&prev=search
http://renegade-legion.org/archive/index.php/t-1437.html

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Mushgog: http://datenbank.classic-wow.org/?npc=11447
Der Razza: http://datenbank.classic-wow.org/?npc=11497
Skarr der Unbezwingbare: http://datenbank.classic-wow.org/?npc=11498

**Comment by Baraz** [comment]
#1804

**Comment by xorann** [comment]
Danke für den Hinweis. Dann schliesse ich dieses Ticket wieder.
