### ISSUE TITLE
MC - Golemagg: Totems werden angegriffen

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2015]
**Welches Verhalten wird beobachtet?**
Bei etwa 10% greift Golemagg statt dem Tank Totems an, bevor er sich kurz danach wieder umbesinnt und den Tank angreift.

**Wie sollte es sich verhalten?**
Golemagg sollte beim Tank bleiben und nicht Totems angreifen

**Schritte zur Reproduzierung**
Totems aufstellen und Golemagg auf unter 10% bringen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Fire Resistance Totem und Tranquil Air Totem werden angegriffen: https://www.youtube.com/watch?v=7sPawLyb99E&feature=youtu.be

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Golemagg: http://datenbank.classic-wow.org/?npc=11988
Fire Resistance Totem: http://datenbank.classic-wow.org/?spell=10538
Tranquil Air Totem: http://datenbank.classic-wow.org/?spell=25908

**Comment by Baraz** [comment]
#1911

**Comment by Larirawiel** [comment]
In Classic wirkten Stuns auf die Aggro ähnlich wie Furchteffekte. Solange der Tank davon betroffen war rutschte er in der Aggro-Liste runter und die Gegner hatten sich andere Spieler geschnappt. Ob das bei Golemagg auch so sein darf weiss ich nicht. Woebei das schon merkwürdig ist, dass er dann Totems angreift. Die dürfte in der Aggroliste weit unter den DDs und Heilern sein.

Grüße

**Comment by absdr** [comment]
Ragnaros nimmt auch oft für einen kurzen Augenblick ein Totem ins Target wenn dieses in Meleerange steht und der Tank gekickt wird.

**Comment by dagochen** [comment]
Bei Ragnaros wird es daran liegen, dass er immer zu erst versucht etwas in Nahkampfreichweite zu finden. Bei Golemagg fällt mir da jetzt nix ein, dass dies verursacht. Passiert dies denn immer oder nur sehr selten?

**Comment by xorann** [comment]
Tritt bei Golemagg jede Woche auf und immer bei etwa 10% HP des Bosses.

**Comment by Dotox** [comment]
Noch aktuell?

**Comment by xorann** [comment]
Ja, tritt nach wie vor auf.
