### ISSUE TITLE
C'thun: Verlassen des Magens verursacht Schaden

### ISSUE THREAD

**Issue by jinthaalor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2022]
Welches Verhalten wird beobachtet?
Beim Verlassen des C'thun-Magens bekommt der Spieler momentan ~1000 Naturschaden durch den Spell "spit out".

Wie sollte es sich verhalten?
Der Spieler sollte beim Verlassen des Magens keinen zusätzlichen Schaden erleiden.

Schritte zur Reproduzierung
C'thun Magen verlassen (Trampolin)

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/34ba7rg0gdc?t=742 der Magier verlässt den Magen, kein "spit out" oÄ verursacht Schaden. Gleicher Vorgang bei den anderen beiden Teleports aus dem Magen bei 6:29 und 9:46.
https://youtu.be/-d3p5hW-zMo?t=382 ebenfalls kein Schaden beim Verlassen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?spell=25383 (Spit Out)
http://datenbank.classic-wow.org/?npc=15727 (C'thun)

**Comment by Mafyo** [comment]
Dieser Zauber spitout sieht aus wie der Spell den die Fleischjäger in Aq20 machen sollten was sie momentan nicht tun allerdings gibt es keine Hinweise dadrauf das es genau der Spell sein soll. Bei den Fleischjägern in AQ20 benutzen sie den Zauber Consume aber der enthält nicht den Spitout effekt obwohl ich den videos belegen kann. Habe auch schon einen Bugreport dazu gemacht damals. Könnte sein das dort was verwechselt wurde.

[Spit Out](http://datenbank.classic-wow.org/?spell=25383)


https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1448
