### ISSUE TITLE
Hinterland - NPC Ortho Mojiko Quest nicht annehmbar trotz notwendigem lvl

### ISSUE THREAD

**Issue by Snarfus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2023]
Account Snarfus
Charakter Aknath

Welches Verhalten wird beobachtet? Ich kann den Quest aus der Questreihe Message to the Wildhammers nicht annehmen, obwohl ich den notwendigen lvl, 55 btw. habe und es keine pre quest gibt. Der NPC zeigt mir ein silbernes Ausrufezeichen, welches meiner Meinung nach zu weit ueber ihm schwebt.
Quest http://datenbank.classic-wow.org/?quest=7841
NPC http://datenbank.classic-wow.org/?npc=14738

Wie sollte es sich verhalten? Questreihe ab lvl 44 annehmbar

Schritte zur Reproduzierung Ich habe ingame es bereits einem GM gemeldet. Er meinte ich solle mich an den Bugtracker wenden. Vielen Dank!

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Es handelt sich hierbei um eine PvP-Quest, da du die Allianz (Wildhammer) angreifen sollst. Daher darfst du maximal das Mindestlevel der Quest + 9 haben. Sprich diese Quests funktionieren genau wie die Schlachtfelder, die ja auch von 40-49, 50-59, etc. gestaffelt sind. Dies hat den Grund, dass Spieler höheren Levels natürlich nicht bevorteilt sein sollen gegenüber Low-Level-Charakteren.
