### ISSUE TITLE
Erste Hilfe Quest für >225 in Gruppen defekt

### ISSUE THREAD

**Issue by Kelturion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2024]
Welches Verhalten wird beobachtet?

Die Quest http://datenbank.classic-wow.org/?quest=6624 scheint nicht korrekt zu funktionieren, wenn man diese in einer Gruppe erledigt. Die Aufgabe ist es ja, 15 der insgesamt (20 oder 25? bin nicht ganz sicher) spawnenden verletzten Patienten zu verbinden.

Das Problem ist hier aber, dass die verazteten Patienten offenbar nur für denjenigen gezählt werden, der diese behandelt, nicht aber für die gesamte Gruppe.

Das hat natürlich zur Folge, dass die Quest mit mehr als einem Spieler faktisch unlösbar ist, da die NPC-Menge selbst bei einer Trefferquote von 100% nicht ausreicht.

Wie sollte es sich verhalten?
Die verarzteten NPCs sollten natürlich für alle Gruppenmitglieder zählen.

Schritte zur Reproduzierung:
Mit 2 Spielern in eine Gruppe gehen, quest gemeinsam starten, alles verarzten was spawnt, feststellen, dass die Quest fehlgeschlagen ist.

**Comment by Slimmer2** [comment]
Das ist eine Single Quest und sollte auch nicht in Gruppe gehen.
Wenn man die Quest annimmt, startet ein Script. Erst wenn das Script zurückgesetzt ist sollte die Quest für andere annehmbar sein.

**Comment by dagochen** [comment]
Also ist der Fehler das Popup?

**Comment by Kelturion** [comment]
Das ist eben die Frage. Nur so wie es jetzt ist, ist es sicher nicht richtig.

**Comment by dagochen** [comment]
Gibts dazu vllt Quellen von damals? Magst du vielleicht mal recherchieren?

**Comment by Slimmer2** [comment]
http://wowwiki.wikia.com/wiki/Quest:Triage/Artisan_First_Aid_quest_guide
Ganz unten steht es.
Einer mit Fehlgeschlagener oder abgeschlossenen Quest mit übrigen Aufladungen kann einen anderen helfen
