### ISSUE TITLE
Cold Snap - Ice Block CD nicht reseted

### ISSUE THREAD

**Issue by Polymorphin3** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2025]
**Welches Verhalten wird beobachtet?**
Die Fähigkeit "Kälteeinbruch" sollte alle cooldowns der Kategorie "Frost" reseten.
Immer wieder wird der "Eisblock" nicht mit reseted und behält seinen cooldown-timer bei.
(Das der "improved counter-spell" im Video kein Effekt hatte ohne resist Meldung ist übrigens nebensächlich ;P)

**Schritte zur Reproduzierung**
Sollte ich ein Muster erkennen, werde ich ein Update geben + Video.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
https://youtu.be/8tcKA9xEPQU

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
http://datenbank.classic-wow.org/?spell=12472

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1995
Hast du kurz davor einen Ladebildschirm?

**Comment by Polymorphin3** [comment]
Nein hatte ich nicht. Auch bei den anderen Situationen mit gleichem Problem, hatte ich keinen Ladebildschirm davor. Die anderen Vorfälle habe ich leider nicht auf Video.

**Comment by dagochen** [comment]
Sollte mit dem Update vom 31.03. nicht mehr auftreten, ansonsten bitte mit nochmals aufnehmen damit wir versuchen können ein Muster zu erkennen, woran es liegen könnte.
