### ISSUE TITLE
Teufelswald: Abgeben von "Teufelsunhold" und "Besudeltes Vitriol"

### ISSUE THREAD

**Issue by Tobiasludovici** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2027]
Welches Verhalten wird beobachtet?
Ich habe die Quest von Arathandris Silberwolke mit den 15 Blutharz gemacht. Nun kann ich "Salbe durch Jagd" machen. Ich bin Kräuterkundler und Bergbauer. Ich sammele im Teufelswald "Teufelsunhold" und "Besudeltes Vitriol". Bei mir erschient aber bei Arathandris Silberwolke nicht die wiederholbare Qeust, um "Teufelsunhold" und "Besudeltes Vitriol" abgeben zu können. Andere Spieler mit denen ich gewhispert hab können dies anscheinend. Ich habe gar keine Mods.

Wie sollte es sich verhalten?
Man sollte bei ARathandris Silberwolke Teufelsunhold und Besudeltes Vitriol abgeben können im Tausch gegen Cenarische Pflanzensalbe.

Schritte zur Reproduzierung
Probieren... Wobei es klappen kann bei Chars welche das schon lange machen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Man kann nur mit einem Beruf die Salbe bekommen. Dazu muss man eine Quest machen.
Durch jagt geht immer.

**Comment by Tobiasludovici** [comment]
Stimmt nicht: ich mache ja die ganzen letzten Tage erfolgreich "Salbe durch Jagd".

Nur die Sachen welche ich durch Berufe kriege - Teufelsunhold und Besudeltes Vitriol - kann ich eben nicht in Salbe umwandeln.

**Comment by Tobiasludovici** [comment]
Ich habe die Quest gemacht mit den 15 Blutharz, seitdem mache ich "Salbe durch Jagd" und sammele Teufelsunhold und Besudeltes Vitriol. 2004 in Classic-Zeiten konnte ich Teufelsunhold und Besudeltes Vitriol abgeben. Jetzt macht es keinen Sinn, daß ich sammeln aber nicht abgeben kann. Es wäre möglich daß es für den Server Nefarian ein Problem ist, daß ich Kräuterkundler und Bergbauer gleichzeitig bin.

**Comment by dagochen** [comment]
WDB Verzeichnis gelöscht?

**Comment by Tobiasludovici** [comment]
Hallo Daniel!

Ich habe gar kein WDB-Verzeichnis im Ordner wo WoW-Classic ist. Ich habe nur “WTF”. Ich habe wirklich gar keine Addons. Oder ist WDB unsichtbar? Bin über 40^^ Danke für die Hilfe. mfg, Tobias

**Comment by dagochen** [comment]
Mindestlevel?

**Comment by Tobiasludovici** [comment]
Hallo! Mein Level ist 56. 

Früher 2004 konnte ich gleich nach der Quest mit dem Blutharz alle Sammelqeusts gegen Salbe tauschen.

Das Problem ist seit gestern behoben. Ich bin nicht sicher woran das lag, ob Ihr was an der Programmierung geändert habt, oder daran daß ich “der finale Schlag” abgegeben habe. mfg, Tobias

**Comment by Slimmer2** [comment]
Die Quest zum Sammeln sind Level 55 bei Bergbau und Kräuterkunde.
Bei Kürschner und Verzauberer Level 48.

**Comment by Slimmer2** [comment]
Laut WowWiki sind die Quest ab Level 48 annehmbar und als Level 55 markiert sein. Ist generell bei diesen Quests.

http://datenbank.classic-wow.org/?search=salbe+durch
Die Wiki Einträge sind von 2009. Nichts älteres gefunden, auch nichts das es geändert wurde
[Salve via Gathering](http://wowwiki.wikia.com/wiki/Quest:Salve_via_Gathering?oldid=1981786) Quest ID: 4105, 4110, 5884 und 5889
[Salve via Skinning](http://wowwiki.wikia.com/wiki/Quest:Salve_via_Skinning?direction=next&oldid=1586801) Quest ID: 4106, 4111, 5884 und 5890
[Salve via Disenchanting](http://wowwiki.wikia.com/wiki/Quest:Salve_via_Disenchanting?direction=next&oldid=818747) Quest ID: 4107, 4112, 5885 und 5891
[Salve via Mining](http://wowwiki.wikia.com/wiki/Quest:Salve_via_Mining?direction=next&oldid=1094143) Quest ID: 4104, 4109, 5883 und 5888
[Salve via Hunting](http://wowwiki.wikia.com/wiki/Quest:Salve_via_Hunting?direction=next&oldid=1563449) Quest ID: 4103, 4108, 5882 und 5887

**Comment by dagochen** [comment]
Danke @Slimmer2  für die entscheidenden Informationen! Fix incoming!
