### ISSUE TITLE
AQ40 Skeram Teilung - Add hat original resistance und 100% HP

### ISSUE THREAD

**Issue by Irasfrostwolfclan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2028]
Welches Verhalten wird beobachtet?
Nach einer Teilung kam es mehrfach vor das Skeram ein Add spawnte das 100% HP hat und sich vom Schaden nehmen her genauso verhalten hat wie der Boss. Dies führte dann dazu das man zwei Bossmobs anstatt einen + Kopie hat. 

Wie sollte es sich verhalten?
Skerams Kopien sollten von der HP her auf 75% 50% 25% sein und wesentlich mehr Schaden als das Original nehmen. 

Schritte zur Reproduzierung
Leider keine Reproduzierung möglich da kein generisches Verhalten beobachtet wurde. 
Fehler tritt zufällig auf.

**Comment by babadoslim** [comment]
Hier auf Band, hoffe es hilft evtl.

[https://www.youtube.com/watch?v=elLk3fduzvo&t=32s](url)
