### ISSUE TITLE
Hakkars Herz Quest

### ISSUE THREAD

**Issue by Tobros85** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2029]
Ich kann die Herz von Hakkar Quest mit meinem Schami Tobros nicht abgeben. Molthor auf der Insel Yojimba hat einfach kein Fragezeichen auf dem Kopf. Weder Abbruch der Quest und Neuannahme noch relog brachte was. Gibt mehrer die das gleich Problem haben. 

Bitte wenn es geht fixen.

Mit freundlichem Gruß

Tobros

**Comment by Slimmer2** [comment]
[Das Herz von Hakkar](http://datenbank.classic-wow.org/?quest=8183) Quest
[Herz von Hakkar](http://datenbank.classic-wow.org/?item=19802) Item zum starten der Quest
[Molthor](http://datenbank.classic-wow.org/?npc=14875) NPC zum Abgeben.

Fehler liegt darin das dass Script  in einer Endlosschleife, nach dem Ersten abgeben der Quest nach Serverneustart hängen bleibt.

**Comment by Tobros85** [comment]
Also muss ich auf Server Neustart warten? Oder kann man das script zurückzusetzen?

**Comment by Slimmer2** [comment]
Man kann die Quest wenn der NPC an einer bestimmten Stelle ist abgeben.

**Comment by Tobros85** [comment]
Ähm ok, stand gestern knapp 10 min da rum und er bewegte sich keinen Zentimeter.
