### ISSUE TITLE
Schwert Spezialisierung des Kriegers Fehlerhaft / Hand der Gerechtigkeit Fehlerhaft

### ISSUE THREAD

**Issue by SirSoarin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#203]
Welches Verhalten wird beobachtet?
Hand der Gerechtigkeit und Schwert Spezialisierung geben dir 1ne extra Aufladung für den nächsten White Hit der Frei auf weitere Gegner übertragbar ist sollange man nicht Automatisch angreift.
Der Extra Schlag wird nur von einem White Hit ausgelöst und von Spalten sowie Heldenhafter Stoß überschrieben , welche Schwert Spez und HOJ im PvE (und PvP) Sinnlos machen.

Wie sollte es sich verhalten?
Beide "Proccs" setzen den Swingtimer zurück und geben keine "Aufladungen". Machte man Heldenhafter Stoß > bekam Schwert Anrgiff > griff man sofort wieder an (Swingtimer reset)

Schritte zur Reproduzierung
Duell machen / Trainingspuppe auf dem Testserver und Attacken spammen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Noch keine aber in den Feenix Foren und in alten Kommentaren habe ich es herauslesen können was die beiden Proccs bewirkten , klingt auch Logisch

**Comment by SirSoarin** [comment]
Zum besseren Verständnis geupdated , wird daran noch gearbeitet?

**Comment by SirSoarin** [comment]
Push*

**Comment by Seniorash** [comment]
Gibt es noch Unklarheiten? Die Mechanik beider Proccs ist die gleiche und der auftretende Fehler ist gleich, weshalb ein Bugreport für beide zusammen geschrieben wurde. Vielleicht noch einmal wie es sein sollte:
- Der Procc soll durch alle Attacken ausgelöst werden können (funktioniert)
- Die Mechanik des Proccs (funktioniert nicht):
 - Unabhängig davon, ob mit Main- oder Offhand der Procc ausgelöst wird, wird der aktuelle Timer der    Mainhand vollendet. D.h. es wird ein Schlag mit der Mainhand ausgeführt und dessen Swingtimer auf 0 gesetzt. Es handelt sich also um eine Beschleunigung und um keinen zusätzlichen Hit in dem Sinne. Nur wenn es beim Autoswing procct, kommen tatsächlich 2 Schläge auf einmal.

**Comment by Schnitzelkoenig** [comment]
Push

**Comment by Seniorash** [comment]
Ich füge hier mal noch die Quellen und Links ein:
http://forums.elitistjerks.com/topic/8508-hand-of-justice-understanding-this-trinket/page-2

Hand der Gerechtigkeit: http://datenbank.welli-it.de/?item=11815
Eisenfeind: http://datenbank.welli-it.de/?item=11684 (nicht erwähnt aber selbes Problem)
Schwertproc: http://datenbank.welli-it.de/?spell=16459
Schwertspezialisierung: http://datenbank.welli-it.de/?spell=13964
