### ISSUE TITLE
Schurken GifteQuest Allianz Lvl 20 buggy

### ISSUE THREAD

**Issue by Xain13** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2030]
In Westfall am Turm (südöstlich) kann die Dämmerwaldtruhe nicht geöffnet werden, trotz vorhandenem Schlüssel.
Habe bereits mehrfach Relogs versucht. Auch Quest abgebrochen und neu gestartet, doch Truhe lässt sich nicht öffnen.

**Comment by Slimmer2** [comment]
Du hast einen Schlüssel zum Turm geklaut und nicht einen Schlüssel der Truhe.
Und du bist Schurke der gewisse Fertigkeiten hat, also benütze diese

**Comment by dagochen** [comment]
Also kein Bug?
