### ISSUE TITLE
NPC Wilde Eulenbestie Häutbar

### ISSUE THREAD

**Issue by Faeleen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2035]
Welches Verhalten wird beobachtet?
Die Primitiven Eulenbestien im Hinterland sind nach ihrem Tod häutbar.

Wie sollte es sich verhalten?
Da sie Humanoide sind, sollten sie nicht kürschnerbar sein.

Schritte zur Reproduzierung
Ins Hinterland reisen, Primitive Eulenbestie töten, kürschnern.

Zusätzliche Informationen (Screenshots, Videos, etc.)
![1 eulenbestie humanoid](https://cloud.githubusercontent.com/assets/15186110/24565326/1a348104-1655-11e7-8e43-e512f200f024.jpg)
![2 eulenbestie hautbar](https://cloud.githubusercontent.com/assets/15186110/24565363/3f07192e-1655-11e7-9ccf-1b152121dc91.jpg)
Bei den Wahnsinnigen Eulenbestien in Winterspring verhält es sich richtig.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?npc=2928
http://datenbank.classic-wow.org/?npc=7452

**Comment by Faeleen** [comment]
Zusätzlicher Edit.: Wilde Eulenbestie (http://datenbank.classic-wow.org/?npc=2929) und Heimtückische Eulenbestie (http://datenbank.classic-wow.org/?npc=2927) sind davon natürlich auch betroffen.

**Comment by Faeleen** [comment]
Quelle kann gerne noch reingeschrieben werden, falls jemand eine findet. Auch wenn jemand einen Beweis findet, dass sie es sein sollten. Dann sollten allerdings auch die in Winterspring kürschnerbar sein.

**Comment by Mafyo** [comment]
ist zwar keine Quelle von damals aber Wowheadf steht neben den loot noch eine Kategorie *skinning* die gibt es bei den Eulenbestien nicht http://www.wowhead.com/npc=2929/savage-owlbeast
allerdings bei einem Wolf schon http://www.wowhead.com/npc=1817/diseased-wolf#skinning
