### ISSUE TITLE
Priester: Schattenverwundbarkeit

### ISSUE THREAD

**Issue by Fnaticshadow** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2036]
Hallo,

Welches Verhalten wird beobachtet?
Seit dem Patch am 31.03.17 wird Schattenverwundbarkeit sowohl bei Start als auch zum Schluss von Gedankenschinden auf den Mob gewirkt. Somit also 2 Stacks pro Mind Flay.

Wie sollte es sich verhalten?
Es sollte aber nur 1 Stack bei Start des Mind Flays gewirkt werden.

Schritte zur Reproduzierung:
Mind Flay wirken und den vollen Channel abwarten.

Schattenverwundbarkeit: http://datenbank.classic-wow.org/?search=shadow+weaving
Gedankenschinden: (http://datenbank.classic-wow.org/?search=mind+flay)

Gruß Fnatic

**Comment by dagochen** [comment]
Danke für die Rückmeldung ;) Hab ich auch grad schon bemerkt. Wir arbeiten dran!

**Comment by Slimmer2** [comment]
Push, sonst muss ich wegen Buguse meinen Priester auf Abstellgleis stellen
