### ISSUE TITLE
ZG Hohepriester Venoxis

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2038]
Welches Verhalten wird beobachtet?
In Phase 2 benutzt der Boss seine Fähigkeit Giftspucke und Parasitic Serpent (Schmarotzende Schlangen) nicht.

Wie sollte es sich verhalten?
Wenn Phase 2 Startet sollte der Boss kontinuirlich Giftspucke und 
Schmarotzende Schlangen wirken
( ein Debuff der wenn komplett ausgelaufen eine kleine minischlange spawnt in der Größe eines Pets. Die normales Aggro verhalten aufweist daher nicht gebunden an die Person die vom Debuff betroffen ist. Die erst verschwindet wenn sie getötet wurde. So wie es aussieht kann die Schlange den Debuff weiter tragen wenn sie ein anderes Ziel attackiert https://youtu.be/U0-KUZ8_P7s?t=167 der Tank hatt de Debuff auf sich und als die minischlange in attackiert resettet der Timer des debuffs.)

Schritte zur Reproduzierung
Venoxis angreifen und in P2 bringen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Venom Spit (Giftige Spucke):
Eine AoE Spell, fügt 1000 Naturschaden zu und hinterlässt einen starken Naturdot (200 Schaden/5sec über 20 Sekunden - kann bis zu 3x stacken!). Muss so schnell wie möglich gesäubert werden!

Parasitic Serpent (Schmarotzende Schlangen):
Venoxis ruft kleine Schlangen (sehen aus wie die Haustiere) herbei, die Schaden beim Raid verursachen.

(http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/ZulGurub/zulgurubguide2.htm)

https://youtu.be/U0-KUZ8_P7s?t=111 hier beginnt P2 wo man erkennt das Venoxis Venom spit verschiesst einmal als instant auf den Tank und einmal angezigt in der Castbar auf ein random Mitglied im Raid. Desweiteren sieht man hier schön die spawnenden minischlangen und den dazugehörigen debuff

https://youtu.be/U0-KUZ8_P7s?t=138 als der Debuff ausläuft spawnt unter dem Tank eine kleine schlange die von ihm wegläuft.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Hohepriester Venoxis](http://datenbank.classic-wow.org/?npc=14507)
http://datenbank.classic-wow.org/?spell=25053 in guides ist die Rede von 20Sekunden dauer aber laut meinem Video ist es 30 Sekunden, passt auch mit der Spell verlinkung überein

[Schmarotzerschlange](http://datenbank.classic-wow.org/?npc=14884)
http://datenbank.classic-wow.org/?spell=23865
http://datenbank.classic-wow.org/?spell=23867
http://datenbank.classic-wow.org/?spell=23866

[High Priest Venoxis Transform Visual](http://datenbank.classic-wow.org/?npc=14877)

**Comment by ChichiWarrior** [comment]
Dafür spawnt er bei uns Giftwolken, gefühlt im Sekundentakt.
