### ISSUE TITLE
Windstein

### ISSUE THREAD

**Issue by Heri7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2043]
Welches Verhalten wird beobachtet?
Das Beschwören eines speziellen Fürsten mit Hilfe eines Siegel der Anrufung funktioniert nicht.
Es spawnt bei beiden Sprach Optionen ein Zufälliger Fürst.

Wie sollte es sich verhalten?
Wenn man ein Siegel der Anrufung im Inventar dabei hat sollte man über die zusätzliche Sprachoption den entsprechenden Fürsten beschwören (erzwingen) können.

Schritte zur Reproduzierung:
Windsteine mit angelegten Set und Standesmedallion und Siegel der Anrufung im Inventar ansprechen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.).
Ich habs mit dem Siegel der Anrufung: Feuer festgestellt, evtl funktionieren die anderen.
Bei den großen Windsteinen hat das erzwingen bisher immer geklappt.
http://wowwiki.wikia.com/wiki/Wind_stone (You can specify which Duke you wish to summon by acquiring the appropriate Signet of Beckoning)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Schattenhammer-Set:
http://datenbank.classic-wow.org/?item=20408 
http://datenbank.classic-wow.org/?item=20406
http://datenbank.classic-wow.org/?item=20407
http://datenbank.classic-wow.org/?item=20422
Siegel der Anrufung:
http://datenbank.classic-wow.org/?item=20433
http://datenbank.classic-wow.org/?item=20432
http://datenbank.classic-wow.org/?item=20435
http://datenbank.classic-wow.org/?item=20436
Fürsten:
http://datenbank.classic-wow.org/?npc=15206
http://datenbank.classic-wow.org/?npc=15208
http://datenbank.classic-wow.org/?npc=15220
http://datenbank.classic-wow.org/?npc=15207
Summon Duke:
http://datenbank.classic-wow.org/?spell=24768
http://datenbank.classic-wow.org/?spell=24765
http://datenbank.classic-wow.org/?spell=24770
http://datenbank.classic-wow.org/?spell=24772

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1914
