### ISSUE TITLE
[Quest] KKäpt'n Sanders Versteckter Schatz Teil 4

### ISSUE THREAD

**Issue by Zahtu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2046]
Beim Abschluß der Quest "[Käpt'n Sanders Versteckter Schatz](http://datenbank.classic-wow.org/?quest=140)" in Westfall werden die Items (insg. 4) nicht dem Inventar des Spielers hinzugefügt. Dies war zu beobachten, wenn das Inventar des Spielers voll ist (k.a. ob davon abhängig oder nicht). Dennoch wird die Quest abgeschloßen und auch im Chat so protokolliert (Erhalten: ...) 

Der Abschluß sollte nicht möglich sein, wenn das Inventar voll ist bzw. die Items korrekt dem Inventar hinzugefügt. Die Items sind (das 4te ist mir entfallen):

- [Käpt'n Sanders Schärpe](http://datenbank.classic-wow.org/?item=3344) 
- [Käpt'n Sanders Beutetasche](http://datenbank.classic-wow.org/?item=3343)
- [Käpt'n Sanders Hemd](http://datenbank.classic-wow.org/?item=3342)

Aufgetreten auf einem Mage in Westfall am 06.04.2017 um ca. 21:35.

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/782
