### ISSUE TITLE
Dun Morogh - Mehrmaliges Abbauen von Kupfererzen

### ISSUE THREAD

**Issue by Arthoron** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2049]
Welches Verhalten wird beobachtet?
Man kann nach dem Abbauen und Plündern einer Kupferader, welche danach nicht despawnt, diese noch bis zu dreimal abbauen. Danach verschwindet sie jedoch.

Wie sollte es sich verhalten?
Erze gleichwie Kräuter sollten nach dem Abbau-/Sammelprozess und der vollständigen Plünderung der enthaltenen Items despawnen und erst nach einem zufälligen Zeitraum wieder neu erscheinen.

Schritte zur Reproduzierung
1. Nach Dun Morogh reisen.
2. Kupfererzvorkommen abbauen und komplett ausbeuten.
3. Erneut dasselbe Kupfererzvorkommen abbauen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

![wowscrnshot_040917_205737](https://cloud.githubusercontent.com/assets/27155420/24840322/64748fd0-1d6b-11e7-9bf7-dd6bcdf81434.jpg)
(Das Erzvorkommen zu Beginn)

![wowscrnshot_040917_205747](https://cloud.githubusercontent.com/assets/27155420/24840324/6703a6d2-1d6b-11e7-828d-20819d85660d.jpg)
(Das Erzvorkommen, nachdem es bereits direkt davor abgebaut worden war)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
http://datenbank.classic-wow.org/?object=3763

**Comment by Slimmer2** [comment]
Man kann Erze bis zu 4-mal abbauen.
Das ist kein Bug
