### ISSUE TITLE
Spielerposition wird nicht immer korrekt gespeichert beim Logout

### ISSUE THREAD

**Issue by Adebryn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2050]
Welches Verhalten wird beobachtet?
Ich hatte mich in AQ40 wollte ich nach dem eintreten in die Ini schnell reloggen, aber nach dem einloggen stand ich wieder mitten in Silithus, das gleiche ist mir mit nem disconnect in Zul Gurub passiert, da stand ich dann in Dunkelhein

Wie sollte es sich verhalten?
Man sollte wieder in der Instanz stehen

Schritte zur Reproduzierung
In einem Raid aus und einloggen (ist aber leider nicht immer)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Ja, hatte ich gestern auch. Mal gucken ob wir raus finden wie es dazu kam. Falls das noch öfter passiert, gerne hier rein posten mit Datum+Zeit und von wo nach wo eure Position verändert worden ist.

**Comment by Sabbaer** [comment]
am letzten sonntag hatten das einige spieler bei uns die in aq40 ausgeloggt haben und dann im schlingendorntal und in if nach einloggen waren, ich versuche mal rauszufinden welche charaktäre das waren.

**Comment by Dotox** [comment]
Dürfte nun nicht mehr vorkommen.

**Comment by dagochen** [comment]
Dann mach ich hier erstmal zu. Wenn doch noch so ein Fall vorkommt, bitte hier reinschreiben, dann mach ich den Report wieder auf.
