### ISSUE TITLE
Angeln: Helle Schmuckstücke nirgendwo erhältlich

### ISSUE THREAD

**Issue by WoW-Sid** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2052]
### Welches Verhalten wird beobachtet?
Der Köder "Helle Schmuckstücke" (+75, 10 min) ist nirgendwo käuflich erwerbbar.

### Wie sollte es sich verhalten?
Der Köder "Helle Schmuckstücke" sollte bei jedem Händler verfügbar sein, der auch "Nachtkriecher" führt. Also Handwerkswaren und Fischhändler.

### Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Helle Schmuckstücke: https://datenbank.classic-wow.org/?item=65321
Nachtkriecher: https://datenbank.classic-wow.org/?item=6530#sold-by
http://wowwiki.wikia.com/wiki/Bright_Baubles

**Comment by dagochen** [comment]
Liegt an der Item-ID 65321 :( Die korrekte ist 6532....fix inc! Danke für die Meldung!
