### ISSUE TITLE
Timelapse und Chromaggus

### ISSUE THREAD

**Issue by pinfi32** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2056]
Welches Verhalten wird beobachtet?

Wenn Chromaggus in BWL Timelapse als Atem hat verliert der MT manchmal willkürlich, ohne ersichtlichen Grund, seine gesammte Aggro.

Wie sollte es sich verhalten?

Der Tank sollte durch Timelapse nur temporär die Aggro verlieren und nach Ablauf des Atems sie wiederbekommen.

Schritte zur Reproduzierung

Der Aggroverlust hängt nicht direkt mit Timelapse zusammen, tritt aber nur auf, wenn Chrommagus in der ID Timelapse castet. Die eigentliche Timelapsemechanik funktioniert wie sie sollte, Tank verliert während des Stuns die Aggro, Chrommagus läuft zum Ziel mit der höchsten Aggro das nicht gestunnt ist, Chrommagus läuft nach Ablauf des Stuns zurück zum eigentlichen Tank. Der Aggroverlust tritt scheinbar völlig willkürlich auf und der MT ist auch im KTM plötzlich an letzter Stelle. Da wir bisher lediglich 2 IDs mit Timelapse hatten ist unsere Erfahrung etwas begrenzt, das Problem trat aber in beides IDs je mindestens einmal auf.

http://db.vanillagaming.org/?spell=23312

**Comment by Haudraufinix** [comment]
Um mal ein paar mögliche Anhaltspunkte zu gewähren:
Könnte es mit dem Positioning des Tanks zusammenhangen? NPC's schmeissen Spieler die 1. in der Aggroliste sind, aber nicht in Hitreichweite sind unter gewissen umständen Raus (Evade Mechanik).
Kriegertank, Bärchen oder Paladin?
Hat es mit Blutrausch vom Krieger/Wutanfall vom Bärchen zu tun? diese beiden Spells haben Einfluss auf den in Kampf Status eines Spielers.
Kamen Segen des Schutzes zum Einsatz?

Für schnelles debugging könnte auch ein Video aus Tanksicht sehr hilfreich sein (idealerweise mit Kampflog)

**Comment by ChichiWarrior** [comment]
Wir hatten gestern Timelaps und keine Probleme

**Comment by Jessienia** [comment]
Nein, vermutlich kein Bug.

Mal vorweg: Es sollte doch jemandem klar sein, dass KTM nicht immer Aussagekräftig ist. Wenn jemand einfach so aus dem KTM fällt ist dies oft einfach nur ein Addon Bug. Passiert mit z.b. ständig.
Außerdem berechnet KTM die Bedrohung anhand der Werte, die vom Addon Programmierer vorher festgelegt wurden. Diese müssen nicht unbedingt mit der Wirklichkeit übereinstimmen. Teilweise werden manche Effekte gar nicht berücksichtigt. Und dies ist bei Chromaggus der Fall:

Zusätzlich zu dem Stun, der kurzzeitig zum Aggroverlust führt, reduziert Time Lapse nämlich auch die Bedrohung um einen bestimmten Wert. Heißt: Wenn der MT nicht genug TPS fährt, bzw. die DDs "zu viel DPS" und diese sich nie vom Time Laps treffen lassen, wird der MT früher oder später die Aggro dauerhaft verlieren. Entweder an die DDs oder den Time Laps Tank.
Ich würde ja drauf wetten, dass dieses "willkürlich" passiert, während der Boss gerade die entsprechende Verwundbarkeit hat :). Oder aber einer der Range DDs, der sich schon auf über 110% der Tank bedrohung geballert hat, gerät in Melee Range zum Boss.

**Comment by pinfi32** [comment]
Die Theorie es handle sich um keinen Bug kann ich fast mit 100% ausschließen, da sich Chromie in den beiden Versuchen auch gemütlich durch die Heiler gefuttert hat und der MT somit in der Tat die Aggro völlig verloren hat. Segen des Schutzes fällt damit auch flach.

Am wahrscheinlichsten halte ich das er kurzzeitig evadet sein muss, da der Tank ihn hin und wieder richtig positionieren musste. Da es zweimal vorkam und sich der Tank nur im "Durchgang" aufhielt, gibt es möglicherweise dort eine Position an der Chromie der Meinung ist er könne den Tank nicht mehr angreifen und schmeißt ihn somit aus der Aggro.

Am nächsten Tag ließ er sich ohne zicken töten, wir lassen jetzt aber immer eine Aufnahme mitlaufen sollte er wieder Timelapse kriegen und es wieder auftritt.

**Comment by Slimmer2** [comment]
Wie kannst du Chromie in den Schmutz ziehen, ist ja nur eine harmlose Gnomin

**Comment by dagochen** [comment]
Das Problem sollte durch die letzten Änderung an Taunt und Aggro Verhalten vermutlich beseitigt sein.
