### ISSUE TITLE
Falsch platzierter NPC: Fiora Langohr

### ISSUE THREAD

**Issue by Kelturion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2058]
**Welches Verhalten wird beobachtet/Wie sollte es sich verhalten?** 

Der NPC "Fiora Langohr" sollte sich auf dem Steg in Auberdine befinden, so wie es auch der zugehörige Questtext und unsere Datenbank wiedergibt: https://datenbank.classic-wow.org/?npc=4456

Der NPC steht auf unserem Server aber seltsamerweise stattdessen im Gasthaus in Theramore (66,45).

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.):**

Die Quest kann ich seltsamerweise in unserer Datenbank nicht finden (es gibt nur eine gleichnamige Quest, aber mit völlig anderem Textinhalt). Daher hier der Wowhead-Link und ein Screenshot von mir: http://de.wowhead.com/quest=1132/fiora-langohr

![quest](https://cloud.githubusercontent.com/assets/14249816/25309696/11d351b2-27d4-11e7-8d55-f81a63424348.jpg)

**Comment by dagochen** [comment]
http://web.archive.org/web/20060515023427/http://wow.allakhazam.com:80/db/quest.html?wquest=1132

**Comment by Slimmer2** [comment]
Dann muss der Questtext falsch sein. 
Da das Bild den Ingame Questtextz ist und in der Datenbank von uns der Text anders ist, sollte der Questtext angepasst werden.

https://datenbank.classic-wow.org/?quest=1132

> Sprecht mit Fiora Langohr in Theramore.
> Beschreibung
> 
> Ach, wieder auf See zu sein! Den Kuss des Windes zu spüren und mich von den Wellen wiegen zu lassen wie vor langer Zeit von meiner gesegneten Mutter! 
> 
> Oh, hätte ich doch nur Euer Glück, <Klasse>, denn ich sehe das Meer in Eurer Zukunft! 
> 
> Meine Aufgabe ist es, eifrige Seelen nach Kalimdor zu bringen, in das Land der unbegrenzten Möglichkeiten! Wenn Ihr Euer Glück in Übersee machen wollt, dann reist von hier mit dem Schiff in den wunderschönen Hafen Theramore. Sprecht mit meiner Partnerin, der Elfin Fiora Langohr. 
> 
> Sie wird Euer Abenteuer in Kalimdor beginnen lassen! 
>

**Comment by dagochen** [comment]
Ja ich mach den Text fertig ;) Braucht dafür nix neues aufmachen^^
