### ISSUE TITLE
Rabatt von PvP Stufe 3 wird nicht mehr angerechnet bei höherem PvP Rang

### ISSUE THREAD

**Issue by Manixer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2060]
Welches Verhalten wird beobachtet?
Auf PvP Stufe 3 erhält man einen 10% Rabatt bei allen Händlern. 
Sobald man einen höheren PvP Rang bekommt verschwindet der Rabatt.

Wie sollte es sich verhalten?
Der Rabatt sollte auch nach erreichen eines höheren Rangs immer noch vorhanden sein.

Schritte zur Reproduzierung
Preise bei Händlern vergleichen auf PvP Rang 3 und 4

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://wowwiki.wikia.com/wiki/Honor_system_(pre-2.0)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Gipsyjodler** [comment]
Hast du davon Screenshots?
Hab das nämlich gerade mal mit meinem Schamanen (Rang 7) getestet und da funktioniert alles korrekt.
https://datenbank.classic-wow.org/?item=18798
Der Wolf kostet 80g, bin wohlwollend bei Orgrimmar.
Also 10% von der Fraktion + 10% durch den Rang
Außerdem steht in deiner Quelle: 10% discount on all goods and repairs from your faction's NPCs
Sollte also auch nur bei NPCs der eigenen Fraktion Rabatt geben und nicht bei allen Händlern.

**Comment by Manixer** [comment]
Also habs gerade nochmal überprüft.
Der Rabatt auf die Gegenstände funktioniert noch das stimmt.
Lediglich die Repkosten funktionieren nicht.
Hier Bilder dazu:
[http://i.imgur.com/4nKCNFa.jpg](url)
[http://i.imgur.com/WcsuYl9.jpg](url)

**Comment by dagochen** [comment]
wie heißt das addon? damit ich paar werte kontrollieren kann bei mir?

**Comment by Manixer** [comment]
Titan Panel Haltbarkeit v1.07
Lads dir auch gern iwo hoch!

**Comment by dagochen** [comment]
Hey! 

Ich hab zwar das Addon, aber eine Anzeige wie bei dir kriege ich nicht dargestellt. Eine kleine Hilfe wäre gut. 

Ansonsten komme ich nämlich überall auf die korrekten Prozente auf dem Testserver.

**Comment by Manixer** [comment]
Hier mal der Code vom Addon bei Pastebin: https://pastebin.com/0xkEURNh
Wenn du's komplett haben willst sag bescheid dann lad ichs dir bei Epic im TS hoch oder wo anders.

Ich teste mal NPC's durch!

**Comment by dagochen** [comment]
Wie gesagt, ich hab das Addon, aber es zeigt die Repairkosten völlig anders an.

**Comment by Manixer** [comment]
Also ich habe mal alle Händler und Fraktionen getestet bei denen ich mind. Wohlwollend bin und über alle wird mir nur die erste Stufe des Rabatts gewährt. 

Auf dem Testserver wird mir keiner der Rabatte gewährt.

Hier mal die Einstellungen fürs Panel: [Link](http://i.imgur.com/hCej6Ja.jpg)
