### ISSUE TITLE
MC Garr

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2065]
Welches Verhalten wird beobachtet?
Garr lässt seine adds nicht explodieren wenn seine hp langsam runter geht.

Wie sollte es sich verhalten?
Wenn Garr angegriffen wird und seine hp sich verringert sollte er mit einem Emote ankündigen das er eines seiner adds explodieren lässt, er lässt aber nur adds explodieren die sich nicht im Banish befinden.

Wenn sich jetzt z.B beim Kampf um Garr nur noch ca. 3 adds am leben befinden die sich im dauerbanish befinden und der Raid auf Garr umschwenkt und seine Hitpoints sinken versucht Garr immer wieder einen seiner Adds zum explodieren zu bringen, wenn jedoch die adds im banish sind ist dieser Zauber in die Leere gesprochen aber sollte es passieren das in der Zeit des rebanishens der Zauber von Garr gewirkt wird, explodiert das Add.
Garr lässt seine adds nicht explodieren wenn er noch volle hp hatt.
Desweiteren ist die explosion die Garr auslöst stärker als diese Wenn die Adds von sich aus sterben.

Emote:
''Garr Forces one of his Firesworn minions to erupt''

Schritte zur Reproduzierung
Garr angreifen und töten, adds ingnorieren

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/mRK7fKEw9VQ?t=354 im chat wenn man bisschen genauer hinschaut erscheint ein zum ersten mal in dem Kampf ein emote das Garr beginnt seine Adds hochzujagen Leben vom Boss ca. 80%?

https://youtu.be/mRK7fKEw9VQ später im Video erwischt Garr mit seinem Errupt ein Add außerhalb vom banish der Prietser erleidet sofort 3.5k dmg und ist tot während in Guides die explosion der adds auf 1500-2000 dmg angegeben wird. ein Beweis dafür das der Errupt den Garr auslöst mehr schaden verursacht.

noch ein Video wo man sieht das Garr am beginn des Kampfes und die erste hälfte des Videos kein Emote erscheint erst ab der 2ten hälfte des Videos beginnen die Emotes.
https://www.youtube.com/watch?v=W6vtgnVM0vs

Artikel aus dem Blizzard dungeon Guide. Interessant anzumerken ist hier noch das Garr wenn alle adds tot sind er kleine mini Adds beschwört. Was sogut wie nie auf Video oder in Guides festgehalten wurde weil diese Taktik, alle adds vor Garr zu töten nie gefahren wurde und diese immer bis zum Kampf ende gebanished wurden. 
Ein Guide geht nur wage dadrauf ein.
[And if Garr explodes the last add, bad bad 
things happen.](https://www.gamefaqs.com/pc/945229-world-of-warcraft-battle-chest/faqs/42533)
![grafik](https://cloud.githubusercontent.com/assets/9504938/25582617/72eaa534-2e8e-11e7-9f95-e20744c2fc59.png)

Elysium project hatt diese Fähigkeit auch reingepatcht.
[Garr's adds can no longer resist Massive Eruption](https://elysium-project.org/updates)

Je weiter ich bei wowwiki zurück gehe desto skuriler werden die Fähigkeiten von Garr wo bschrieben wird das er seine adds immmer explodieren lassen kann unabhänging seiner HP. und das er angeblich alle banishes ab 50% automatisch rausholen kann. Ab einem bestimmten Zeitpunkt fliegt dann auch aus dem wiki die Sache das er Adds hochjagen kann raus. Obwohl videos dieses belegen können. in keinem Patch wurde angegeben das Garr in classic irgendeine änderung seiner Fähigkeiten erhalten hatt.
Hier der Link:http://wowwiki.wikia.com/wiki/Garr?oldid=78781
 
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=12057
https://datenbank.classic-wow.org/?npc=12099

https://datenbank.classic-wow.org/?spell=20483 der Spell den Garr wahrscheinlich auf die adds castest.
Frage: Effekt3 Instakill. bezieht sich das auf das Add auf das dieser Zauber gecastet wird ?

https://datenbank.classic-wow.org/?spell=19497 normale Eruption der adds.
https://datenbank.classic-wow.org/?spell=20482

**Comment by Mafyo** [comment]
hab da was gefunden anscheinend wurden einige Fähigkeiten von Garr irgendwann einmal enfernt ohne in den Patchnotes aufzutauchen. Ein Video wie Garr mal ganz am Anfang funktioniert hatt. Voller Enrage mit den kleinen adds die spawnen. 

[This video is awesome, it shows Garr in his full enrage mode, which happens when all his adds are killed. He spawns little adds that blow up. This was removed from his abilities at some point, quite a long time ago, so its cool to see ](https://www.youtube.com/watch?v=HGeeM17pGv0)

Meine Frage an die devs: Wollt ihr den Boss mal umändern wie er ganz am Anfang war oder soll ich den Report schließen, denn anscheinend ist die Fähigkeit die ich beschreibe auch entfernt worden?
wäre cool den boss mal so zu machen :D

**Comment by jinthaalor** [comment]
"Meine Frage an die devs: Wollt ihr den Boss mal umändern wie er ganz am Anfang war oder soll ich den Report schließen, denn anscheinend ist die Fähigkeit die ich beschreibe auch entfernt worden?
wäre cool den boss mal so zu machen :D"

Das klingt doch nach nem Hardmode mit 1% mehr chance auf ne Fessel! :D

**Comment by dagochen** [comment]
Kann man sich ja mal merken für etwaige Events ;)
