### ISSUE TITLE
Item Herz der Schuppe

### ISSUE THREAD

**Issue by Ryanstekken** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2066]
Welches Verhalten wird beobachtet?
Item ist in der Datenbank vorhanden aber nicht zugeordnet.
Wie sollte es sich verhalten?
Das Trinket Herz der Schuppe sollte Oberanführer Wyrmthalak zugeordnet sein.
Schritte zur Reproduzierung
Datenbank kontrollieren.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://web.archive.org/web/20070118235027/http://wow.allakhazam.com:80/db/item.html?witem=13164
http://wow.gamepedia.com/Heart_of_the_Scale
http://www.wowhead.com/item=13164/heart-of-the-scale - wurde mit patch 1.11.1.5462 hinzugefügt und mit 4.0.3a erst entfernt.
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=13164 - Trinket
https://datenbank.classic-wow.org/?npc=9568 - NPC

**Comment by Slimmer2** [comment]
http://wowwiki.wikia.com/wiki/Heart_of_the_Scale
