### ISSUE TITLE
Druide: Wolfskopfhelm hat fälschlicherweise ICD

### ISSUE THREAD

**Issue by jinthaalor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2068]
Welches Verhalten wird beobachtet?
Der Wolfskopfhelm verfügt über einen Internen Cooldown, der verhindert, dass man bei jedem Shift Energie bzw Wut bekommt.

Wie sollte es sich verhalten?
Der Wolfskopfhelm sollte bei jedem Shift in Katze Energie bzw in Bär Wut geben.

Schritte zur Reproduzierung
Helm anziehen, in Katzen-/Bärform wechseln.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Nach ausgiebiger Recherche bin ich zu dem Ergebnis gekommen, dass der Helm von Vanilla bis zum Patch 3.1 über keinen internen Cooldown verfügte. Ebenfalls hatte er in diesem Zeitraum Willenskraft anstatt Beweglichkeit als Attribut, was hier auf dem Server auch korrekt ist. Allerdings werden aktuell die beiden Versionen des Items vermischt: Interner Cooldown und Beweglichkeit, oder kein ICD und Wille sind die beiden Möglichkeiten.
Quelle1: http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/158212-improve-your-feral-dps-level-40-helmet.html (August 2008)
"However when you shift with this helmet you get instant 60 energy, cutting out the 2 second energy tick wait, making 3 shreds take 3 seconds instead of 9." <- kein interner CD, da bei jedem Shift die Extra-Energie erhalten wird (3x in drei Sekunden)
Quelle2: http://www.wowhead.com/item=8345/wolfshead-helm#comments:id=628392 (März 2009)
Erwähnt die Veränderung der Stats, die allerdings weder in den Patchnotes, noch in den undocumented changes auftaucht. Meiner Meinung nach wurde mit diesem Update auch der ICD eingebaut, im Einklang mit Blizzards Politik, alte Items aus vorherigen Addons für das aktuelle Addon unbrauchbar zu machen. (Schleifsteine zB wurden auch in diesem Zeitraum für Itemlevel über 165 gesperrt, etc)
Quelle3: http://fluiddruid.net/forum/viewtopic.php?t=729&p=7464#p7465 (2012)
"Wolfshead Helm powershifting in WotLK (before Blizzard broke it)."
Quelle4: http://wow.gamepedia.com/index.php?title=Powershifting&oldid=2159813 (Januar 2010)
"This was an advanced technique used by many skilled or knowledgeable feral dps players in The Burning Crusade while chain-drinking Mana Potions (!) in order to squeeze out as much energy and therefore dps as possible, sometimes also while using the infamous level 40 (!)  [Wolfshead Helm]. This technique was nerfed in Patch ___ toward the end of The Burning Crusade and will not return, according to Blizzard posters on the Official Forums - as it was never intended and caused some rather strange behaviour." Entweder bezieht sich der Autor auf einen anderen Nerf für Powershifting gegen Ende BC, oder verwechselt Ende BC mit dem oben genannten Patch 3.1, in beiden Fällen ist das Powershiften mit dem Wolfskopfhelm vorher möglich gewesen. Niemand würde einen Helm, der keinerlei sinnvolle Stats hat, anziehen, um jede Minute 20 Energie extra zu bekommen.

Zusammenfassung: Die Vanilla-Version des Helms besaß keinen ICD.

Da der Helm eine massive Schadenssteigerung für Ferals ausmacht, wäre eine zeitnahe Änderung super :> 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=8345 (Wolfshead Helm)
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/162 gleiches Thema

**Comment by dagochen** [comment]
Zur Erklärung:
Wir verwenden hier die Classic-Version des Zaubers 17770. Dieser ist aus dem Classic-Client extrahiert worden. In diesem Zauber stehen die 60 Sekunden Cooldown, wie von mir in #162 beschrieben, genauso drin wie auf wowhead. Es gibt zwar immer mal einen Zauber, der auf unserem Server nicht korrekt funktioniert und angepasst werden muss, dafür bedarf es dann aber Quellen aus 2005/2006, idealerweise zum korrekten Patchstand 1.12. Daher können wir hier nix machen.

**Comment by Haudraufinix** [comment]
Ich greif das ganze mal wd auf.
In ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/162 meinst du selbst, du seist dir nicht sicher, dass ob das ein hieb und stichfester beweis wäre, dass der helm in classic schon nen CD hat.

Der OP hat aber ziemlich gute Quellen. Hier scheint mir das Flag kein Bug sehr voreilig.
Ist tatsächlich extrem blöde das die Quellen aus BC sind. Aber es würde für Blizz definitiv keinen sin machen dieses Item zum Start von BC zu Buffen, indem sie zeitweise den CD entfernen. Nun ist Blizz nicht gerade für Logik bekannt, dennoch bleibt hier etwas unstimmig.

**Comment by dagochen** [comment]
Das liegt daran, dass ich damals noch nicht in die Classic-DBC-Dateien schauen konnte. Es ist damals für mich ungewiss gewesen, weil wowhead vermutlich neuere Client-Dateien ausgelesen hat. Aber da in denen vom Classic-Client ebenfalls bereits der CD drin ist, stellt sich diese Frage nicht mehr und die Sache ist klar. Ohne Beweis, dass man in 1.12 auch Power-Shiften konnte, geht da nix...
