### ISSUE TITLE
Gilden-Mitglieder-Beschränkung 

### ISSUE THREAD

**Issue by Rashick** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2074]
Welches Verhalten wird beobachtet?
Bei einer Mitgliederanzahl von 585-600 Mitglieder gibt es massive Probleme bei den Spielern aus der Gilde. 
* Gildeninformationen (O) lassen sich nicht mehr aufrufen.
* Client stürzt ab
* Char wird gekickt

Wie sollte es sich verhalten?
* Naja, ich denke mal, dass es nicht so geplant ist, dass es durch zu viele chars in einer Probleme dieser Art geben sollte. 
 
Schritte zur Reproduzierung
* So viele Mitglieder einladen, dass die Anzahl zwischen 585 - 600 oder mehr liegt. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
* Das ganze lässt sich nur dann beheben, in dem man mit einem char online kommt und sofort /gquit eingibt. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Das Problem gab es schon mal. Die Anzahl würde dann erhöht.

**Comment by Rashick** [comment]
Naja, es wäre dann aber schön, wenn es eine Grenze gibt, dass man in Game dann ggf. auch nicht mehr Spieler einladen kann als "gesund" ist. 

Aber bis wir das Problem herausgefunden haben sind halt alle möglichen Spieler von uns immer wieder mit einem Disco versehen gewesen was bei Onyxia natürlich Medium spaßig ist.

**Comment by dagochen** [comment]
Schmeisst mal eure Bankchars raus ;)

**Comment by Rashick** [comment]
Auch da, sehe ich nicht dass das die Lösung des Problems ist. 

Ich empfehle die Anzahl zu erhöhen, was möglich ist, auf einen unrealistischen hohen wert... 10.000+

oder aber ein technisches limit in game, welches die "Gilde" davor beschützt solche Probleme zu bekommen. 

Wir haben es auf die Harte tour gelernt, aber ich vermute mal, dass wir nicht die einzige Gilde auf dem Server sind und nicht jeder im Bugtracker jeden Bug auswendig weiß.... Daher wäre die eine oder andere Variante schon eine angenehme Lösung. 

und ja, wir haben die meisten bankchars jetzt auch schon rausgeschmissen ;)

**Comment by Slimmer2** [comment]
Wurde die Anzahl nicht letztes Jahr auf 650 erhöht?

**Comment by Rashick** [comment]
Hm... ich fürchte das ein bissen an einander vorbei geredet wird. 

Ich brauche für uns in unsere Gilde keine temporäre Lösung, die haben wir und da achten wir selber jetzt natürlich auch darauf. 

Aber es gibt diverse Gilden auf dem Server und da es nicht sichergestellt ist, dass alle darüber bescheid wissen, und zukünftige neue Gilden darüber bescheid wissen werden, wär eine der beiden o.g. Lösungen sehr hilfreich. 

Für uns ist das Thema mittlerweile durch, ich wollte nur bescheid geben und Euch die Möglichkeit geben, denn andern Gilden dieses Thema zu vermeiden. :-)

Liebe Grüße 
Rashock

**Comment by Slimmer2** [comment]
Meine Lösung war an die Dev's gedacht,

**Comment by Dotox** [comment]
Eine Gilde ist begrenzt auf 650 Mitglieder. Alles darüber lässt den Client crashen.
