### ISSUE TITLE
Totem der Verbrennung castet zu langsam

### ISSUE THREAD

**Issue by absdr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2075]
Welches Verhalten wird beobachtet?
Totem der Verbrennung castet etwas langsamer als die 2 sekungen.
Wie sollte es sich verhalten?
Alle 2 sek sollte ein cast kommen (siehe Beschreibung des Totems)
Schritte zur Reproduzierung
Totem stellen und einen 2 sekunden timer ablaufen lassen oder casts zählen bis das Totem despawmt
Totem steht 55 sek und castet alle 2 sekunden dadurch müssten sich 27,5 casts ergeben. Das totem castet aber über seine gesamte lebensdauer nur 24 Casts.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?spell=10438

**Comment by Slimmer2** [comment]
https://datenbank.classic-wow.org/?spell=10436
Hier steht Castzeit 2,2 Sekunden
