### ISSUE TITLE
Willensbrecher der Qiraji

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2076]
Welches Verhalten wird beobachtet?
Ist Spottbar

Wie sollte es sich verhalten?
Sollte Spottimmun sein

Schritte zur Reproduzierung
Willensbrecher Spotten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
''The Qiraji Mindlsayer is immune to taunt, so aggro is hard to secure''
aus dem Dungeon Companion Buch Seite 26.
wenn sich das jmd. Downloaden will um nachzugucken: https://drive.google.com/uc?id=0B-_HNCwfg1HeNVg3TjExQUR4UTQ&export=download

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15246

**Comment by Nifexx** [comment]
Hm, dass steht in krassem Gegensatz, dazu was in wowwiki steht. 

> Then that mindslayer's tank moves to the next target and taunts when that mindslayer's tank gets controlled.
(http://wowwiki.wikia.com/wiki/Qiraji_Mindslayer).

Des Weiteren sind die nächsten Zeilen aus dem Buch sehr interessant:

> When the Mindslayer finally falls it unleashes an area effect causing all a slight drain in mana to anyone near and also a fear affect, forcing all nearby players to run around in panic....

Dieser Effekt wird auf dem Server IMMER ausgelöst, solange sich eine Manaklasse in nähe zu dem Target befindet. Und nicht wenn er stirbt (D.h. er wird dann garnicht ausgelöst, wenn keine Manaklasse in der Nähe ist). Selbst der Manaburn auf Targets sollte laut dem Buch nur kommen wenn er stirbt. Dieser trifft auch nur Targets die sich in Range befinden (unterschiedliche Range um Manaburn und den Fear zu triggern)

@Dagochen Muss ich dafür einen extra Report mit extra Quellen schreiben oder reicht das so?

**Comment by dagochen** [comment]
Dann sucht bitte erstmal für das Taunten noch weitere Quellen, ob das nun gehen sollte oder nicht.

**Comment by Mafyo** [comment]
''Upon death, Mindslayers will confuse nearby players, causing them to run aimlessly for a few seconds. They will also perform one final Mana Drain.''  steht auch auf wowwiki da hatt das Buch recht, können wir uns eig. aussuchen ne weitere Quelle zu Spotimmung werden wir wohl kaum finden.

**Comment by Mafyo** [comment]
naja hab doch was gefunden^^

[Qiraji Mindslayer - Immune to taunt](http://bunningswarehouse.shivtr.com/forum_threads/2664695)

**Comment by Baraz** [comment]
Auch in der Quelle findet sich noch einmal der Hinweis auf 

> Each pack consists of one Qiraji Champion and any combination of four Qiraji Slayers and Mindslayers.

welcher hier #1865 schon beschrieben ist. Reine 4er Packs sollten seltener sein.

**Comment by Mafyo** [comment]
der Elysium Server hatt die Willensbrecher auch immun gemacht. Auf welche Quellen sie sich stützen weiss ich leider nicht
[Qiraji Mindslayers are now immune to taunt (added in a previous update) 
](https://forum.elysium-project.org/topic/47461-development-update-24052017/)

**Comment by Nifexx** [comment]
@dagochen Wird das andere Verhalten auch gefixt oder reichen dafür die Quellen nicht? Oder soll ein komplett neuer Eintrag dafür geschrieben werden?

**Comment by dagochen** [comment]
Ja trennt das bitte. Sonst hat man einen Report der verschiedene Bugs enthält, die man dann alle gemeinsam lösen muss, bevor man schließen kann. Das ist manchmal nicht möglich und dann haben wir hier so ne "Bugreport"-Leichen rumliegen ;)
