### ISSUE TITLE
Goblinsponsoring Quest von Baron Revilgaz

### ISSUE THREAD

**Issue by Baghwan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2077]
Welches Verhalten wird beobachtet?
Quest "Bringt die Blaupausen der Treibstoffeinspritzpumpe zu Pozzik in der schimmernden Ebene"
wird nicht vergeben.
Meldung erscheint "Du erfüllst die Voraussetzung für die Quest nicht !
Quest ist weg
die Questreihe "Goblinsponsoring " ist dann LEIDER weg..

war Lv. 36 Jäger Avatar "Baghwan"

Wie sollte es sich verhalten?

Folgequest für "Goblinsponsoring " wir vergeben. 

Schritte zur Reproduzierung

mit der vorquest "Goblinsponsoring " Nr.4 und den "Treibstoffreglerblaupausen" beim Baron abgeben..

http://wowdata.buffed.de/quest/Tausend-Nadeln/Goblinsponsoring-1182

**Comment by Baghwan** [comment]
komisch, n weilchen Später ander Quest abgegeben, war die Annahme der Quest "Goblinsponsoring" möglich... nur so als Tipp für andere ;)

**Comment by Slimmer2** [comment]
https://datenbank.classic-wow.org/?quest=1183
Diese ist ab Level 37

**Comment by Baghwan** [comment]
Ja stimmt, aber komisch ists trotzdem :)

**Comment by dagochen** [comment]
Naja, eine Quest, die mehrere Teile hat und wo zu erwarten ist, dass ein Spieler mal nen Levelup hat....so ungewöhnlich klingt das jetzt nicht für mich, dass da für Folgequests irgendwann ein höheres Level gefordert wird. Falls hier noch Quellen kommen, mach ich wieder auf.
