### ISSUE TITLE
Vem Kill resettet Bossfight BugTrio

### ISSUE THREAD

**Issue by BugsBugs** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2078]
Welches Verhalten wird beobachtet?
Wenn man Vem als zweiten Bug tötet, resettet der ganze Boss fight.

Ingesamt Reihenfolge war bei uns:
Kri -> Vem und dann kam der Reset
Wie sollte es sich verhalten?
Vem sollte ganz normal abnippeln und die Bosse sollten nich resetten
Schritte zur Reproduzierung
Erst Kri killen, dann Vem
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Ja video haben wir gemach ich edier den Link dazu sobald ich ihn habe, aber habens 2x versucht und beides mal hats nicbt geklappt, obwohl wir beim 2. Vem komplett von der Wand wegepullt hatten.
Hatte also nix mit dem bug von damals zu tun als das event resettet hat weil die Bosse durch die wand gebugt sind, sonsern wirklich mit dem Tot von Vem.

Um genau zu sein stirbt er net wirklich sobald er auf 0 HP ist respawnt er direkt bevor er über als tot im log angezigt wird 
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Nifexx** [comment]
Wurde schon reportet (#1988). Lies dir mal die Comments in dem alten Report durch. Hilft euch bestimmt weiter.
