### ISSUE TITLE
( Magier ) Arkane Macht Buff

### ISSUE THREAD

**Issue by Meremox** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2079]
Morgen ! 

Ich mache es kurz , Arkane macht aktiviert ( funktioniert ) sobald man in den 15 seks laufzeit wieder auf Arkane macht klickt ist der Buff sofort aus der Buffleiste verschwunden 

Das ist nicht richtig so 

Mfg

**Comment by Baraz** [comment]
[Arkane Macht](https://datenbank.classic-wow.org/?spell=12042)

**Comment by Slimmer2** [comment]
Kann ich bestätigen.
Bitte an die Vorlage halten

**Comment by Gipsyjodler** [comment]
Da die Manakosten von allen Zaubern nach dem Nutzen von Arkane Macht erhöt sind, könnte es möglich sein, dass diese Funktion des Abbrechens bewusst implementiert wurde, da Manakosten in 2006 viel wichtiger angesehen wurden als Heutzutage. Beispielsweise zu den Zeiten als es noch kein Spelldmg auf den Items gab.^^ 
Finde du solltest dazu nochmal richtig recherchieren auch wenn es schwierig ist dafür eine Quelle zu finden. Allerdings wurde das bestimmt mit irgendeinem Patch geändert. Ab TBC verschwindet der Buff auch nicht mehr, nachdem man die Fähigkeit nochmals anklickt.

**Comment by Nifexx** [comment]
Das ist doch mit Eisblock genau das gleiche. Den konnte man zu Classic auch nur mit Makro brechen. Auf dem Server reicht es die gleiche Taste noch mal zu drücken.

**Comment by dagochen** [comment]
Ja aber das Verhalten des Zaubers, dass man nochmal drückt zum abbrechen, ist ja clientseitig. Es ist meines Wissens nach nicht so, dass der Server an die Clients irgendwas schickt, dass diese dazu bewegt den Zauber "abbrechbar" zu machen.
