### ISSUE TITLE
AQ20: Ossiriankristall

### ISSUE THREAD

**Issue by Gipsyjodler** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2081]
Welches Verhalten wird beobachtet?
Vor Ossirian befindet sich kein Kristall bevor man den Kampf beginnt.
Wie sollte es sich verhalten?
Vor Ossirian sollte ein Pylon stehen, damit man den Supreme Mode mit Beginn des Kampes sofort entfernen kann.
Schritte zur Reproduzierung
Nach AQ20 gehn. Vor Ossirian steht kein Ossiriankristall.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.youtube.com/watch?v=W6Ovud6fCwI
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Ossiriankristall: https://datenbank.classic-wow.org/?object=180619

**Comment by Baraz** [comment]
Wurde hier #1275 schonmal gemeldet und geschlossen.

**Comment by Gipsyjodler** [comment]
Dann sollte man den mal wieder aufmachen...

**Comment by Dotox** [comment]
Nein sollte man nicht, weil es kein Bug ist. Bitte richtig recherchieren.

**Comment by Gipsyjodler** [comment]
Dotox:
Nicht ganz, das kam erst mit 1.11.0

Ossirian the Unscarred - There is a new crystal that will be visible before the encounter begins. Players can use this crystal just like any other crystal in the encounter, but it cannot come back up during the encounter.

http://wowwiki.wikia.com/wiki/Patch_1.11.0
-
Ich meinte damit auch, dass man das im Hinblick auf den kommenden Naxxpatch schon mal fertig macht bevor es dann wieder vergessen wird.^^ Wenn man den Beitrag schließt, denkt man nämlich dass es nie so sein sollte.^^
