### ISSUE TITLE
Quest "Ritus der Kraft" verbuggt Die Mobs droppen keine Gürtel

### ISSUE THREAD

**Issue by KusoJoshi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2082]
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Sehe nur die Vorlage und keinen Report.
Hab es dennoch mal getestet. Hat keine 10 Minuten gedauert dann hatte ich die Quest fertig
