### ISSUE TITLE
 Imperator Vek'lor Und Vek'nilash

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2085]
Welches Verhalten wird beobachtet?
Wenn Beide Sterben kommt kein Soundemote nur der Text im Chat.

Wie sollte es sich verhalten?
Wenn beide Sterben sollte man ein Soundemote hören 
Imperator Vek'nilash schreit: Vek'lor ich spüre deinen Schmerz!
Imperator Vek'lor schreit: Mein Bruder, nein!

Schritte zur Reproduzierung
Imperator besiegen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
in der Patchdatei 1.12sind die Sounds gespeichert.
https://youtu.be/1YrkqoEdvyA?t=648

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15276
https://datenbank.classic-wow.org/?npc=15275

**Comment by Dotox** [comment]
Müsste man irgendwie mal eine Liste der SoundIDs raussuchen. Eingetragen ist ein Sound, eventuell die falsche ID.

**Comment by dagochen** [comment]
8625 und 8636 glaube ich.
