### ISSUE TITLE
Verbesserter Wichtel

### ISSUE THREAD

**Issue by Tinorio** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2087]
Welches Verhalten wird beobachtet? 
Die Talentpunkte für Verbesserter Wichtel scheinen wirkungslos. Bei den Fähigkeiten des Wichtels wird bei zb. [Blutpakt ](https://datenbank.classic-wow.org/?item=16324)(Die Datenbank hat nur das Buch) rang 4, 30 Ausdauer versprochen. Der tatsächliche Buff hat aber nur 27 Ausdauer. 

Schritte zur Reproduzierung
Skillpunkt vergeben und Wichtel beschwören.

**Comment by Slimmer2** [comment]
Die Anzeige vom Buff zeigt immer den Grundwert.
Wenn der Buff geskillt ist, sieht man das nur im Charakterfenster. Dort ohne angelegten Items den geänderten Wert zb. hier Ausdauer betrachten

**Comment by Tinorio** [comment]
Vielen Dank, dort sind es zwar dann +29 aber das entspricht den +10% Super!
