### ISSUE TITLE
Quest "Therzok" nicht mit Level 10 startbar.

### ISSUE THREAD

**Issue by TilmanK** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2089]
Welches Verhalten wird beobachtet?
Kaplak startet Quest "Therzok" auf Level 10 nicht

Wie sollte es sich verhalten?
Quest "Therzok" kann ab Level 10 von Schurken angenommen werden.

Schritte zur Reproduzierung
Schurke auf Level 10 spielen und versuchen, die Quest anzunehmen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Troll, Schurke, Level 10

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Quest: https://datenbank.classic-wow.org/?quest=1859
Questgeber: https://datenbank.classic-wow.org/?npc=3170

**Comment by Slimmer2** [comment]
Du hast nicht folgende Quest gemacht?
[Mennet Carkad](https://datenbank.classic-wow.org/?quest=1885)
Wenn man diese abgeschlossen hat, kann man Therzok nicht mehr annehmen.

**Comment by TilmanK** [comment]
Nein, bisher habe ich keine Schurken-Quest gemacht.

**Comment by TilmanK** [comment]
Die Quest https://datenbank.classic-wow.org/?quest=1885 ist im Übrigen auch nicht verfügbar auf Level 10.
