### ISSUE TITLE
Cooldowns von Manasteinen, Gesundheitssteinen, usw. usf.

### ISSUE THREAD

**Issue by Ataraia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#209]
Da ihr mir das andere Thema gesperrt habt, weil ich keine Quelle reingeschrieben habe, hier noch einmal MIT Quellen... 

Vorweg gesagt: Die Cooldowns vom Zeug ausm Teufelswald, sowie Gesundheitssteinen, Manasteinen, Runen und der Lilienwurzel wurden mit Patch 1.11 angepasst und teilen sich erst ab diesem Patch den CD. 
Da ihr das Buffstacking aber auch an 1.12 festgemacht habt, würde ich mal meinen, dass ihr auch die CDs an 1.12 anpassen solltet.

Also wie gesagt, hier mal ein Auszug aus den Patchnotes von 1.11 unter Items:

We have re-evaluated the mechanics of consumable items in the game and concluded that these should work in a more intuitive manner. As such, most items that can not be equipped with right click abilities have been streamlined into one of three categories. Using an item of a particular category will trigger a shared cooldown among all other items in the same category. The categories break down as follows with category cooldowns as listed.
Potions 2 minutes: This includes items such as Health Potion, Mana Potion, Invisibility Potion and Mighty Rage Potion.
Aggressive 1 minute: This includes items such as explosives, Really Sticky Glue and Discombobulator Ray.
Non-Aggressive 2 minutes: This includes items such as Healthstone, Night Dragon's Breath, Whipper Root Tuber and Target Dummy.

http://www.wowwiki.com/Patch_1.11.0

Hier noch ein Link zu einer Diskussion von Spielern, die sich über den geteilten Cooldown echauffieren ;P 
http://wow.ingame.de/forum/community-forum-5/traenke-cooldown-1-11-a-102071-druckversion/

Laut diesen Quellen teilen sich alle herbeibeschwörbaren Steine sowie das Zeug ausm Teufelswald einen gemeinsamen Cooldown.

Auf Buffed.de hab ich nochmal wegen der Lilienwurzel nachgesehn, um mich zu vergewissern, dass die Lilienwurzel auch in diesen CD reinfällt, da ich nichts offizielles gefunden habe.
Laut den Kommentaren der Spieler hatte die Lilienwurzel vor Patch 1.11 einen eigenen Cooldown, erst danach teilte sie sich den Cooldown mit den oben bereits erwähnten Steinen und dem Zeug aus dem Teufelswald.
Hier der Link: http://wowdata.buffed.de/item/Ruestung/Verschiedenes/Lilienkranz-1315#comments
Kommentare: 40, 38, 36
Gibt auch mehr Leute, die dasselbe reingeschrieben haben, könnt ihr euch gern mal durchlesen, kann mir net vorstellen, dass soviele Leute die Unwahrheit sagen sollten.

Hoffe, das reich euch vorerst mal.

**Comment by Dotox** [comment]
Zauber und alle anderen, wichtigen Elemente verlinken.
