### ISSUE TITLE
Quest "In den Träumen"

### ISSUE THREAD

**Issue by Joda0815** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2090]
Welches Verhalten wird beobachtet?
Beim Begleiten von Taelan Fordring habe ich in den Kampf eingegriffen und wurde folglich getötet. Myranda die Vettel gab am Anfang einen Buff damit man den Bewohnern von Hearthglen freundlich gesinnt ist. Diesen Buff erhalte ich nun nicht mehr von Myranda und nun kann die Quest nicht abgeschlossen werden.

Schritte zur Reproduzierung
wie oben beschrieben

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
keine

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=5944
https://datenbank.classic-wow.org/?npc=11872
https://datenbank.classic-wow.org/?npc=1842

**Comment by Slimmer2** [comment]
Tipp: Quest abbrechen

**Comment by Joda0815** [comment]
Danke für den Tipp.
Nach Questabruch hat mir Myranda den Buff geben können und in Hearthglen konnte ich bei Taelan Fordring den Quest erneut annehmen.
