### ISSUE TITLE
[Naxxramas] Giftpirscher

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2094]
Welches Verhalten wird beobachtet?
Benutzt die Fähigkeit Poison Charge nicht, Der Mob wurde von uns im Kreis gekitet ohne das er einmal gechargt hatt.

Wie sollte es sich verhalten?
Sollte Poison Charge einsetzen  auf eine zufällige Person.
Wirkung: Poison Charge - Charges an enemy and causes poison damage to all within 10 yards of the target. Puts a debuff on players that does 2500 Nature damage every 3 sec for at least 9 sec. Appears to be random target. Combined with the Veil of Shadows from the Dread Creepers and this spells certain doom to anyone not wearing heavy Nature Resistance. Debuff can be cured

Schritte zur Reproduzierung
Giftpirscher angreifen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://wowwiki.wikia.com/wiki/Venom_Stalker?oldid=337992
https://youtu.be/Rp5JNSGkBDA?t=83 man sieht ganz kurz bevor das video in die nächste Szene geht das die große Grüne Spinnen einen schnellen Charge nach hinten macht.( Sorry beste Quelle die ich momentan finde)
https://youtu.be/L205eadaqfE?t=2729 zwar von Kronos aber die Spinne Charged.(Totenkopf Target)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15976#abilities
https://datenbank.classic-wow.org/?spell=28431

**Comment by Dotox** [comment]
Hey,

vielen Dank! Das wurde bereits in der Closed Beta gemeldet, allerdings hab ichs vergessen zu fixen.
