### ISSUE TITLE
[Naxxramas]Aasspinner

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2095]
Welches Verhalten wird beobachtet?
Benutzt den Zauber Spider Web nicht

Wie sollte es sich verhalten?
sollte den Zauber Spider Web einsetzen und einen zufälligen Spieler zu sich heranziehen
in dem Video scheinen die das auch ziemlich häufig hintereinander zu machen. Das heranziehen sollte einem auch nicht auf der Aggroliste nach ganz oben setzen

Schritte zur Reproduzierung
Aasspinner angreifen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/RAZSk8Ryi3U?t=119 die Lila strahlen zeigen den Spider web an.

[Web - Line of purple light shoots out and targets someone within 30 yards. That person is pulled up to the Carrion Spinner's melee range. This does not apparently cause the person to move up on the threat list. It interrupt spells. ](http://wowwiki.wikia.com/wiki/Carrion_Spinner?oldid=306760)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15975
https://datenbank.classic-wow.org/?spell=28434

**Comment by Baraz** [comment]
Bei uns wurde dieser Zauber eingesetzt, 3-4 mal hintereinander auf den pullenden Jäger, sobald die Mobs in Line-of-Sight waren.

**Comment by Mafyo** [comment]
Benutzen sie es auch noch im Fight wenn sie im Nahkampf verwickelt sind auf ein entferntes Ziel?
Bei uns kam es nicht vor.

**Comment by Baraz** [comment]
Auch wenn sie im Nahkampf verwickelt waren haben die das noch auf vereinzelte Range-DDler und Heiler gecastet.

**Comment by Dotox** [comment]
Einen kleinen Fehler gab es noch, ist behoben!
