### ISSUE TITLE
[Naxxramas]Giftiger Huscher , Vanish

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2097]
Welches Verhalten wird beobachtet?
Wenn ich den Spinnenflügel hinunter gehe und die Patroullie von den Giftigen Huschern adde dann aber sofort vanishe wechselt er immer von Beginne Kampf, Verlasse Kampf und Zerstöre deren Patroullienroute sodass sie mich immer kurz in das Target nehmen und dann los laufen. Sie kommen dabei allerdings nicht vorwärts. Wenn ich aus dem Stealth raus gehen Beginne ich den Kampf und sterbe.

Wie sollte es sich verhalten?
Wenn ich vanish benutze sollte die Pat eigentlich wieder auf ihre ausgangsposition laufen und mich ignorieren

Schritte zur Reproduzierung
Spinnenflügel runter gehen Patroulliere adden und sofort vanishen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15977 die npc's heissen in der DB anders als auf dem server o.O

**Comment by Dotox** [comment]
Glaube spontan, dass das bei allen Kreaturen in Naxx ist; hab auch schon die Ursache, schätz ich. Kannst du das mal überprüfen? z. B am Seuchenflügel-Trash.

**Comment by Mafyo** [comment]
bei den Statischen Ghulpacks geht alles wunderbar

**Comment by Mafyo** [comment]
bei den Patroullieerenden Gargoyles funktioniert vanish

**Comment by Mafyo** [comment]
Bei den patroullierenden Gargoyles funktioniert vanish

**Comment by Dotox** [comment]
Okay, habs behoben. Das trat wie ich mir gedacht hab bei allen Mobs auf, aber bei denen war das sehr gut zu sehen weils wohl so viele sind. Danke!!
