### ISSUE TITLE
Waffenkundewertung erhöht die Chance auf einen kritischen Treffer nicht

### ISSUE THREAD

**Issue by Herlot** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2098]
Welches Verhalten wird beobachtet?

Die Waffenkundewertung beeinflusst die Chance auf einen kritischen Treffer anscheinend nicht korrekt. 

Wie sollte es sich verhalten?

Pro Punkt Waffenkunde sollte es 0.04% Chance auf einen kritischen Treffer geben. 

Schritte zur Reproduzierung

Als Nichtmensch eine Waffe mit Waffenkundewertung anziehen und die Chance auf einen kritischen Treffer, vorher und nachher vergleichen (Gäbe es Übungspuppen, könnte man an diesen testen, ob es nur ein Anzeigefehler ist).

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Beim Zwergen-Krieger ändert sich die Chance auf einen kritischen Treffer nicht, wenn er von unbewaffnet auf [Maladath](https://datenbank.classic-wow.org/?item=19351) wechselt:
https://imgur.com/a/YOy3g
(selbes gilt übrigens für eine Streitkolben-Kombination mit dem Kriegshammer der Anubisath)

Beim Menschen ändert sich die Chance auf einen kritischen Treffer, wenn er von einem Dolch auf ein Schwert wechselt:
http://imgur.com/a/EEzC8

Bei einem Zwergen-Jäger ändert sich trotz Rassenbonus beim Wechsel von Armbrust auf Schusswaffe die Chance auf einen kritischen Treffer nicht:
https://imgur.com/a/vEbkO

Hier wird beschrieben: "For each point that your weapon skill exceeds your opponent's defense, you gain the following: ... , Your chance to score a critical hit increases by 0.04%, ..." 
http://wowwiki.wikia.com/wiki/Weapon_skill?oldid=236925

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

[Maladath](https://datenbank.classic-wow.org/?item=19351)

[Kriegshammer des Anubisath](https://datenbank.classic-wow.org/?item=21837)

[+4 Schwerter](https://datenbank.classic-wow.org/?spell=14121)
[+4 Streitkolben](https://datenbank.classic-wow.org/?spell=15760)

**Comment by dagochen** [comment]
Mein Schurke hat ohne die alten Kernlederhandschuhe 31,55% Kritchance. 
1% Krit auf den Handschuhen
15 Agi = 15/29 = 0,5172%
5 WK = 0,2%
Gesamt: 33,26%
![kritchance](https://cloud.githubusercontent.com/assets/5236186/26664623/38af0622-4693-11e7-9c4d-4574646cf203.png)

Das Maladath in der Offhand wird für die Charanzeige nicht für die Mainhand mit einbezogen. Im Kampf bei der Berechnung sollte das aber schon funktionieren. Wenn das nicht gehen würde, würde ja auch der Glancingschaden signifikanter ausfallen und dann hätte längst jemand was gesagt. 
Die Kritchance Anzeige für Jäger hat noch nicht wirklich funktioniert. Das kam erst später.

**Comment by Herlot** [comment]
Schonmal Danke für dein Antwort.

Leider erhöht sich meine Chance auf einen kritischen Treffer auch dann nicht, wenn ich Maladath in die Mainhand nehme (Vote for Trainingspuppen again). Denkst du also, dass es nur ein Anzeigefehler ist? Es gibt leider keine Mobs an denen ich meine Aussage verifizieren kann, da der Prozentsatz so gering ist. Es fragt sich auch, ob es Unterschiede bei der Berechnung der Waffenkunde gibt bezüglich Rassenbonus, Asurüstung und Waffen selbst.

**Comment by Herlot** [comment]
Edit: nach einem relogg oder einem Haltungswechsel, wird die korrekte Chance angezeigt. Die angezeigte Chance im Zauberbuch wird wohl nicht beim Ausrüstungswechsel automatisch aktualisiert. Es wird anscheinend ein Trigger benötigt, damit die Chance aktualisiert wird.
