### ISSUE TITLE
[Naxxramas]Steinhautgargoyle

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2099]
Welches Verhalten wird beobachtet?
die Gargoyles sollte erhöhte unsichtbarkeits entdeckung besitzen, mometan kann ich als Schurke von ganz oben bis zu Noth durch schleichen ohne geskillte Verstohlenheit, gleiches gilt für einen Unsichtbatkeits Trank. Wenn es so bleibt können Schurken ganz einfach die Gefrorene Rune be Noth einsacken und teuer verkaufen. Dies ging in classic zwar auch schon allerdings etwas schwieriger. 

Wie sollte es sich verhalten?
Man sollte nicht zwischen den Gargoyles durch schleichen können. Man solllte aufgedeckt werden im Verstohlenheits modus. 

Schritte zur Reproduzierung
mit Verstohlenheit zwischen den Gargoyles bei Noth durch schleichen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.youtube.com/watch?v=1QximOcF5T8&t=5s

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16168#abilities
https://datenbank.classic-wow.org/?spell=18950 vielleicht dieser?

**Comment by Mafyo** [comment]
Die Gargoyles adden überhaupt gar nicht wenn ich mit stealth durch die schleiche, dass gilt jetzt nur für die Gargoyles die als Statuen an der Treppe sitzen

**Comment by Haudraufinix** [comment]
Bezüglich dem Verkauf der Runen, Blizz hatte mit 1.12 reingepatcht, das man n dropp vom Trash braucht um die Runen aufzutauen.

**Comment by Dotox** [comment]
Item wird auch benötigt. Stealth-Entdeckung fehlt allerdings.

**Comment by Dotox** [comment]
Das Auge über dem Mob, welches die Stealth-Erkennung symbolisieren soll, fehlt allerdings. Das ist ein allgemeines Server-Problem.

**Comment by Baraz** [comment]
Die Verseuchten Gargoyles / Plagued Gargoyles hinter Faerlina Richtung Maexxna konnten auch nicht durch einen Unsichtbarkeitstrank hindurchsehen.
