### ISSUE TITLE
Zauberreflektion_kritische Treffer

### ISSUE THREAD

**Issue by Daimudda** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2101]
## Welches Verhalten wird beobachtet?
-reflektierte Zauber können nicht kritisch treffen und lösen nicht korrekt Debuffs aus

## Wie sollte es sich verhalten?
-reflektierte zauber sollten kritisch treffen können und entsprechende Debuffs auslösen

## Schritte zur Reproduzierung
- Zauber reflektieren

## Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
- ich habe noch nie im BG einen reflektierten zauber critten gesehen und ich habs echt oft benutzt
- heute Duelle mit Feuer-Mage probiert, selbst mit combustion und 70% Crit nicht möglich, demnach auch noch nie ein reflektiertes Ignite gesehen

## kopiert aus dem Kronos Bugtracker
Patch 1.11
Reflection: Effects which cause reflection will no longer reflect triggered effects separately from their base effects (e.g. Impact, Improved Shadow Bolt, Aftermath, etc.)
Patch 1.10
Impact - When a fire spell is reflected back at the caster, the caster will now correctly receive the Impact effect.

Here's a post 1.11 source showing Fire Reflector reflecting Ignite:

Zachary 8 - 19:00

http://www.warcraftmovies.com/movieview.php?id=197373

## Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=23131
https://datenbank.classic-wow.org/?spell=23097
https://datenbank.classic-wow.org/?spell=23132

https://datenbank.classic-wow.org/?spell=24417
https://datenbank.classic-wow.org/?spell=13043

**Comment by Slimmer2** [comment]
Hier mal die Deutsche Patchnotes.
