### ISSUE TITLE
Horde - Erste Hilfe Quest - ab 225

### ISSUE THREAD

**Issue by Edorius88** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2102]
Welches Verhalten wird beobachtet?
Die Quest habe ich in OG im Tal der Geister angenommen und kann sie in Hammerfall bei dem Undead nicht abgeben. Er hat zwar ein gelbes Fragezeichen, jedoch kann ich diesen NPC nicht ansprechen!

Wie sollte es sich verhalten?
Die Quest sollte man abgeben können, damit man im Nachgang die nächste Quest erhält, in der man die Patienten heilen muss.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Troll, Schamane, lvl 48, Erste-Hilfe-Fertigkeit 225
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Ich hoffe um schnelle Hilfe :) vielen Dank! 

LG

**Comment by Dotox** [comment]
WDB leeren sollte Abhilfe schaffen.
