### ISSUE TITLE
[Naxxramas]Anub'rekhans Gruftwache

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2104]
Welches Verhalten wird beobachtet?
Besitzt keinen Enrage und kein Emote dazu

Wie sollte es sich verhalten?
Sollte ab 50% einen Enrage einsetzen
zusätzlich sollte eine Chat emote erscheinen
''Crypt Guard becomes enraged!''

Schritte zur Reproduzierung
Gruftwache angreifen auf 50% bringen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/YgytY8Vu_D0?t=132
https://youtu.be/Nz7LM7YE5go?t=279

Quellen Privat Server: 
http://vanillawowaddons.com/database/?npc=16573
https://www.wow-freakz.com/npc_finder.php?npc=16573&name=crypt-guard auf lvl 81

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16573#abilities
er hatt keinen Enrage gelistet ich kann mich nur an wowhead oder anderen Privat Servern orientieren
https://datenbank.classic-wow.org/?spell=8269

**Comment by Dotox** [comment]
Top!
