### ISSUE TITLE
[Naxxramas] Anub'rekhan Gruftwache

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2105]
Welches Verhalten wird beobachtet?
Die Cleave Attacke macht zu viel Schaden habe ein 5295 Spalten kassiert und habe es nur mit einer Flask überlebt als Schurke

Wie sollte es sich verhalten?
Die Cleave Attacke sollte ca 1000 Schaden anrichten wenn es nach wowwiki geht

Schritte zur Reproduzierung
Gruftwache angreifen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Cleave for ~1000 damage to melee. ](http://wowwiki.wikia.com/wiki/Anub%27Rekhan?oldid=381386)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16573
https://datenbank.classic-wow.org/?spell=15284

**Comment by Mafyo** [comment]
https://www.youtube.com/watch?v=7EoK0WO02is obwohl hier bekommt ein Fury Krieger 2208 dmg vom Cleave

**Comment by Dotox** [comment]
Ja das "to melee" ist etwas schwammig. Kann auch ein Platten-Meele gewesen sein.

**Comment by Mafyo** [comment]
https://youtu.be/qDf--wBOBlA?t=221 1463 an einem Schurken oder wird der Schaden aufgeteilt?

**Comment by Dotox** [comment]
Ne der Schaden wird nicht aufgeteilt.
