### ISSUE TITLE
[Naxxramas] Anub'Rhekan

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2106]
Welches Verhalten wird beobachtet?
Anub'rhekan macht signifikant mehr Schaden im Nahkampf. Getestet durchschnittlich 3873 pro Treffer bei 41 aufgezeichneten Treffern (auf den Tank).

Wie sollte es sich verhalten?
Seine Nahkampftreffer sollten eher zwischen 1k und 1.6k Schaden auf den Tank machen.

Schritte zur Reproduzierung
Anub'Rhekan tanken

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Tank PoV](https://www.youtube.com/watch?v=V7mUxyILiE0) Schaden besser im Porträt als im SCT zu erkennnen.
[MT-Heiler PoV](https://www.youtube.com/watch?v=zDzqh7nBkcc)
[DD PoV](https://www.youtube.com/watch?v=Nz7LM7YE5go) Schaden im Target of Target erkennbar.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Anub'Rhekan](https://datenbank.classic-wow.org/?npc=15956)

**Comment by Mafyo** [comment]
Können wir auch bestätigen unser tank hat 5.8 crushing und einen 4k normal hit in 1 sec bekommen

**Comment by Dotox** [comment]
Ich kann die Schadenswerte nicht auf das Original anpassen. Das haben wir auch bei anderen Raid-Dungeons nicht gemacht, da es sonst schlichtweg zu einfach ist und jeder Blau ausgerüstete Tank Naxxramas tanken kann (was definitiv nicht so sein soll).

Wir tracken während den Tests mehrere Parameter, darunter auch den ausgeteilten Schaden. Sollte hier vermehrt die Meldung gut equipter Gilden kommen, dass der Boss aufgrund des hohen Schadens nicht legbar wäre, würden wir entsprechende Anpassungen vornehmen.

**Comment by Baraz** [comment]
Man muss den Schaden ja nicht komplett runterschrauben, aber gerade aufgrund der Tatsache, dass Anub momentan teilweise 2 Hits in der gleichen Tausendstelsekunde raushaut, kommen hier ca. 8k instant rein. BiS-Tanks inklusiver aller Buffs rangieren im Bereich von 10k HP. Theoretisch also machbar, in meinen Augen aber um einiges schwieriger als es sein müsste für einen Entry-Level Boss.

**Comment by Dotox** [comment]
Ja, das stimmt. Werde es berücksichtigen.

**Comment by Herlot** [comment]
Wenn ich mich recht entsinne ist bei unserem Test  der Tank auch nicht nur Full equipped, sondern auch buffed gewesen, sprich mit allen Mitteln die man als Tank hat: 25 Ausdauer-food, großer Steinschildtrank, Elixier der überragenden Verteidigung, Titanflask, etc. Ich bin ein großer Freund des "tunens" der Bosse, damit diese eine Herausforderung blieben. Trotzdem muss man das gesunde Mittelmaß finden, wie bara schon sagt.
