### ISSUE TITLE
[Naxxramas]Spinnenflügel Trash

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2107]
Welches Verhalten wird beobachtet?
Ich habe ein Spinnenpack gepullt und sofort gevanished. Bin dann aber zu nah an die Gruppe gegangen und wurde aufgedeckt und getötet. Ich bin reingelaufen und bin sofort in den Kampf gekommen die gleiche Gruppe kam sofort auf mich zugelaufen und  hatt mich getötet.
Wie sollte es sich verhalten?
Nach einem Wipe sollte man nach dem reinlaufen nicht sofort wieder in den Kampf verwickelt werden

Schritte zur Reproduzierung
Spinnengruppe adden, Vanish, im stealth adden, sterben, reinlaufen konnte es allerdings nicht nochmal reproduzieren

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15976
https://datenbank.classic-wow.org/?npc=15975
https://datenbank.classic-wow.org/?npc=15974

**Comment by Dotox** [comment]
Wann hast du das getestet?

**Comment by Mafyo** [comment]
vor 1 std ca.

**Comment by Mafyo** [comment]
was rede ich da lol. eEg. genau als ich den report geschrieben habe xD oh man...

**Comment by Dotox** [comment]
Hey, wenn du Zeit hast würde ich mich freuen, wenn du das nochmal testen könntest.

**Comment by Mafyo** [comment]
konnte es nicht nochmal reproduzieren, war ganz komisch

**Comment by Dotox** [comment]
Danke :)
