### ISSUE TITLE
Gotteschild und der Sukkubus

### ISSUE THREAD

**Issue by weedlord100** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2108]
Welches Verhalten wird beobachtet? 
-Trotz Aktivem Gottesschild kann der Sukkubus "verführen" einsetzten
- in seltenen fällen kann während aktivem "verführen" das gotteschild nicht aktiviert werden

Wie sollte es sich verhalten? 
-Gottesschild sollte alles Blocken 
-Gottesschild ist zu jeder zeit einsetztbahr egal unter welchem einfluss man steht. Gottesschild entfernt mit der aktiviereung alle negativen Status effekte

Schritte zur Reproduzierung   
-Als Paladin im BG Gottesschild Aktivieren und durch einen Sukkubus verführen lassen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-Letzter bugtracker eintrag aus dem jahre 2015 als erledigt eingetragen und die restvorfälle als Serverdelay abgetan.
in der hälfte des Gottesschildes ist dies aber bestimmt kein Serverdelay :D 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=642
https://datenbank.classic-wow.org/?spell=6358

**Comment by Dotox** [comment]
Kannst du bitte den letzten Punkt auch ausfüllen? Ohne vollständig ausgefüllten Report wird das hier kommentarlos geschlossen.

**Comment by weedlord100** [comment]
klar sorry done

**Comment by Ryanstekken** [comment]
Die Sukkubus ignoriert sämtliche Fähigkeiten die den Spieler aus dem Kampf nehmen unter anderem auch Vanish.
https://datenbank.classic-wow.org/?spell=1857

**Comment by weedlord100** [comment]
update: in seltenen fällen kann während aktivem "verführen" das gotteschild nicht aktiviert werden

**Comment by Loplin** [comment]
> -Gottesschild ist zu jeder zeit einsetztbahr egal unter welchem einfluss man steht. Gottesschild entfernt mit der aktiviereung alle negativen Status effekte

Gibts dazu auch eine Quelle?
Falls ja, trifft das auf PvE Bossmechaniken auch zu?

**Comment by Ulva-Anorhin** [comment]
Falls es relevant sein sollte...
Bei Lethon bekommt man auch den stun in der Phase ab obwohl bubbel aktiv ist, Bzw man kann sie in der stun Phase nicht benutzen.

**Comment by Loplin** [comment]
Genau darauf wollte ich hinaus, drum habe ich nach der Quelle gefragt.
Ich nehme mal an dafür müsste man nen extra bugreport aufmachen.

**Comment by weedlord100** [comment]
> Gibts dazu auch eine Quelle?
Falls ja, trifft das auf PvE Bossmechaniken auch zu?

quellen kann ich einfügen wenn ich wieder zuhause bin.
das trifft auch auf die PvE Bossmechaniken zu mit einigen wenigen ausnahmen:
-das todesmal von vaelastraz
-das naturmal der 4 alptraumdrachen so wie das von azuregos
weitere solcher Sonderregelungen sind mir nicht bekannt und habe ich auch keine gefunden.

**Comment by Dotox** [comment]
Also ich kann das nicht reproduzieren. Mehr Input wenn jemandem was auffällt.

**Comment by Ryanstekken** [comment]
Nochmal zum refreshen. Hexer mit Sukkubus angreifen dann sollte sie automatisch Verführung casten. Sobald der Cast beginnt auf den Spieler ignoriert die Sukkubus sämtliche Fähigkeiten die einen Spieler aus dem Kampf nehmen. Bei mir aufjedenfall bei Vanish zu 100% der Fall.
