### ISSUE TITLE
Verschiedene Questmaster nicht ansprechber

### ISSUE THREAD

**Issue by klesi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2109]
Welches Verhalten wird beobachtet?
Einige Quests die ich früher mit anderen Chars schon auf dem Server abgeschlossen habe, können nicht mehr angenommen werden.
1. Beispiel: Algaz-Spießrutenlauf https://datenbank.classic-wow.org/?quest=455
-> Quest wird vom Quetsmaster (https://datenbank.classic-wow.org/?npc=1342) nicht angeboten.
2. Beispiel: Der geistesabwesende Ausgrabungsleiter (teil 4) https://datenbank.classic-wow.org/?quest=942
-> Quest kann nicht bei Archäologe Magenbitter (https://datenbank.classic-wow.org/?npc=2911) abgegeben werden

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Beide quests habe ich vor wenigen Tagen mit einem anderen Charakter noch gemacht.

Das problem tritt bei zwei verschiedenen Rechnern auf zwei verschiedenen Accounts auf. Auch nach löschen von WDB und WTF Ordner und deaktivierung alle Interfacemodifikationen.

**Comment by Slimmer2** [comment]
Zu 1: Schreib mal ein Ticket, ob du die Quest evtl. bereits abgeschlossen hast oder evtl. die Quest nur Serverseitig angenommen ist.
Zu 2 Quest abbrechen und neu annehmen sollte helfen.
