### ISSUE TITLE
Precisely Calibrated Boomstick

### ISSUE THREAD

**Issue by nimmzwo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2112]
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Bitte den Report ausfüllen.
Was soll an der Waffe fehlerhaft sein?
