### ISSUE TITLE
Revantusk Village - Gasthaus: Erholung nur im Obergeschoss 

### ISSUE THREAD

**Issue by spearhead83** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2117]
Welches Verhalten wird beobachtet?
Im Gasthaus erhält man im Erdgeschoss, wo sich auch der Gastwirt befindet, keine Erholung, sondern nur im Obergeschoss.

Wie sollte es sich verhalten?
Die Erholung sollte ab Betreten des Erdgeschosses schon einsetzen.

Schritte zur Reproduzierung
Im Erdgeschoss rumlaufen und das eigene Portrait beobachten, ob der Erholungseffekt eintritt.
Ins Obergeschoss gehen und am eigenen Portrait beobachten, wie der Erholungseffekt eintritt.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Bug beobachtet als Male Tauren.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=14731

**Comment by Dotox** [comment]
Clientseitig, wird sich wohl kaum beheben lassen.
