### ISSUE TITLE
[Naxxramas]Anub'rekhan

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2120]
Welches Verhalten wird beobachtet?
Wenn das Tor zu Anub geöffnet wird kommt kein willkommens Soundemote

Wie sollte es sich verhalten?
Anub sollte, wenn seine Tür geöffnet wird ein wilkommens Soundemote abgeben

Schritte zur Reproduzierung
Tor zu Anub öffnen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-Opening Anub'Rekhan's Door

- Ahh... welcome to my parlor. 
- I hear little hearts beating. Yesss... beating faster now. Soon the beating will stop.
- Where to go? What to do? So many choices that all end in pain, end in death. 
- Which one shall I eat first? So difficult to choose... they all smell so delicious. 
- Closer now... tasty morsels. I've been too long without food. Without blood to drink.
http://wowwiki.wikia.com/wiki/Anub%27Rekhan?oldid=381386

 

  
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?object=181195
https://datenbank.classic-wow.org/?object=181126 sind 2 einmal die vordere einmal die hintere keine Ahnung welche welche ist^^
https://datenbank.classic-wow.org/?npc=15956

**Comment by Dotox** [comment]
Das hab ich schon implementiert, weiß nur noch nicht wieso das nicht abspielt, wenn das Tor geöffnet wird. Eventuell schreib ich das Event nochmal um.

**Comment by Mafyo** [comment]
http://prikachi.com/images/959/7869959e.jpg

**Comment by Mafyo** [comment]
momentan werden alle Sounds nacheinander abgespielt, es sollte aber Random 1 davon ausgewählt werden.

**Comment by Dotox** [comment]
Bei mir ist das random, kann zum test aber nochmal den Timer runtersetzen.

**Comment by Mafyo** [comment]
heute kamen alle nacheinander
