### ISSUE TITLE
[Naxxramas] Verseuchter Gargoyle

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2123]
Welches Verhalten wird beobachtet?
Dieser mob ist voll CC bar durch shakle und stuns außerdem ignoriert sein Poison volley kein LoS
Wie sollte es sich verhalten?
Dieser mob sollte eigentlich nicht CC bar sein da es sich quasi um ein exaktes Gegenstück zu denen im Seuchenviertel handeln soll bis auf das es statt dem Acid volley einen Poison volley gibt

Schritte zur Reproduzierung
Gargoyle angreifen, LoS zu einem gehen, shaklen, stunnen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Should be pulled away from each other, because otherwise raid will be getting twice more stacks of poison. Their volley doesn't get affected by LoS, they ignore it. One of the ways to control the fight - is pulling second gargoyle away from main raid and put 2-3 paladins on healing that tank, so they can do divine shield to remove stacks of poison. 

http://wowwiki.wikia.com/wiki/Plagued_Gargoyle?oldid=306677

[These guys were in the pre-BC version of Naxxramas. They were pretty much identical to the standard Stoneskin Gargoyles (Complete with the regeneration ability), except the patrolled the outer ring in pairs.
](http://de.wowhead.com/npc=16446/plagued-gargoyle#english-comments)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16446#abilities
besitzt andere Fähigkeiten in der DB als auf dem Testserver, hier noch den Acid volley Name vom NPC stimmt aber.
Poison Bolt Volley: This stacks and deals some nature damage(~270 per application) per tick. Very large range (more than 40-50 yards).  steht auf wowwiki würde nur der Infrage kommen von der Dmg range: https://datenbank.classic-wow.org/?spell=24099 dann passt aber die angegeben Range nicht mehr

**Comment by Mafyo** [comment]
Warte mal bis du das fixxt es gibt hier bezüglich eine Quelle die ersichtlich zeigt das sie diesen Poison Bolt Volley nicht haben sollten.... dann lügt wowwiki hier...
hier das video:
https://youtu.be/cEsCSdp57d4?t=1065

es ist ganz klar nur der Acid Volley das heisst sie sollen identisch zu denen im Seuchenflügel sein.
Sie sollten auch Stealth detection besitzen. https://youtu.be/cEsCSdp57d4?t=1030 Schurke wird aufgedeckt im Stealth(Totenkopf Target)

- Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?spell=29325 laut DB hatt er die Fähigkeit sogar aber benutzt den Poison Volley o.O
https://datenbank.classic-wow.org/?spell=18950
Schaden laut DB: Schaden: 2,745 - 2,815
Schaden laut Bestiary: Schaden: 3695-4889

Rüstung laut DB: Keine
Rüstung laut Bestiary: Rüstung: 3316

Quelle:
http://abload.de/image.php?img=20170608_2115311qlrpp.jpg unter Plagued Gargoyle der Stoneskin Gargoyle aus dem Seuchenflügel ist dort auch gelistet.

**Comment by Mafyo** [comment]
oops

**Comment by Omegaexodus** [comment]
Ich denke auch das die Fähigkeit "Poison Bolt Volley" nicht existiert, bzw. Blizzard die damals einfach von dem "Steinhautgargoyle" aus dem Seuchenviertel kopiert hat (Dann Namenswechsel, ohne neues Icon?). Oder es scheint, das die Leute bei der damaligen Recherche und dem Notieren der Fähigkeiten, etwas schlampig waren. 

Der Grund ist, ich konnte keine Fähigkeit mit dem Namen "Poison Bolt Volley" in den alten Archiven von Thottbot finden. Und da ist eigentlich alles eingetragen, was damals von Npcs an Fähigkeiten benutzt wurde.

https://web-beta.archive.org/web/20080625201028/http://thottbot.com:80/?s=poison
(Unter Spells = Alle Kategorien durchgehen, mit dem Wort "Poison")

Um es zu vereinfachen und für die Entwickler angenehmer zu gestalten, einfach die selbe Fähigkeit "Acid Volley" für beide Gegnertypen verwenden.

https://datenbank.classic-wow.org/?npc=16446
https://datenbank.classic-wow.org/?npc=16168

https://datenbank.classic-wow.org/?spell=29325
