### ISSUE TITLE
[Naxxramas] Outer Ring Mobs

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2124]
Welches Verhalten wird beobachtet?
es fehlen dort 1 Trashpack direkt wenn man von Faerlina kommt

Wie sollte es sich verhalten?
es sollten 2 Ghulpacks mit jeweils 4 Ghulen sein

Schritte zur Reproduzierung
Outer ring aus der Richtung von Faerlina betreten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Giga liveraid von BC in Naxxramas man sieht 2 Ghulpacks 
https://youtu.be/QtyEoJ6_nZI?t=2617

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16447 nochmal dadrauf hingewiesen, besitzt wieder falsche Fähigkeiten als auf dem Testserver

**Comment by Baraz** [comment]
Die beiden Nekropirscher liefen rum, haben aber eine sehr lange Laufzeit.

**Comment by Mafyo** [comment]
achso ja gut dann editiere ich das

**Comment by Mafyo** [comment]
ist die andere ghul gruppe evtl auch länger auf patroullie?

**Comment by Baraz** [comment]
Das habe ich leider nicht beobachtet.
