### ISSUE TITLE
[Naxxramas]Geist von Naxxramas

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2127]
Welches Verhalten wird beobachtet?
Die Geister die aus seinen Portalen spawnen machen zu wenig Schaden 
Benutzt keine Shadowbolt volley

Wie sollte es sich verhalten?
Die Geister die aus dem Portal kommen sollten wenn sie jemanden erreichen schon onehitten oder wenigstens 2 hitten, wie die Geister die beim Trash im Tempel bei jammal spawnen.
Sollte seine Shadowbolt Volley einsetzen.

Schritte zur Reproduzierung
Geist angreifen, Geister spawnen lassen, von Geistern schlagen lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/QtyEoJ6_nZI?t=2666 Shadowbolt volley vom Geist

[and the ghosts made short work of anyone who ventured near the portals.](http://wowwiki.wikia.com/wiki/Shade_of_Naxxramas?oldid=368359)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16449
https://datenbank.classic-wow.org/?spell=28407
https://datenbank.classic-wow.org/?spell=28389
https://datenbank.classic-wow.org/?spell=28384

**Comment by Dotox** [comment]
Der Geist, der die Portale spawnt, soll die Schattensalve einsetzen oder der spawnende Geist aus dem Portal? Das ist da irgendwie nicht ersichtlich :/

**Comment by Mafyo** [comment]
der Geist der Portale Spawnt, die Geister die spawnen die roamen so rum und sind nicht angreifbar und hitten nur in melee Range

**Comment by Omegaexodus** [comment]
Ich denke ich kann da ein bisschen helfen, was die Namensprobleme und Fähigkeiten angeht. :-)

Im Englischen gibt es einen Unterschied zwischen "Shade of Naxxramas" und "Ghost of Naxxramas".

Im deutschen heißen beide leider gleich übersetzt = Geist/Phantom von Naxxramas, weshalb es daher zu Problemen kommt. Die Fähigkeiten der Schattenblitzsalve und der Beschwörung der Portale werden nur von dem "Shade of Naxxramas" eingesetzt. (Zusätzlich fehlt noch eine weitere Fähigkeit hier)

Shade of Naxxramas hat folgende Fähigkeiten:

https://datenbank.classic-wow.org/?npc=16449

Schattenblitzsalve = https://datenbank.classic-wow.org/?spell=28407
Portal of Shadows = https://datenbank.classic-wow.org/?spell=28384
Beim Tot des "Shade of Naxxramas" = Beleben eines einzelnen "Ghost of Naxxramas" https://datenbank.classic-wow.org/?spell=28389


Ghost of Naxxramas hat keine Fähigkeiten, außer den starken Meele-One-Hit. Zudem ist er nicht Anvisierbar und auch immun gegen sämtlichen Schaden. (Es ist leider nicht ersichtlich, wie lange der "Ghost of Naxxramas" am leben bleibt) 

https://datenbank.classic-wow.org/?npc=16419

Weitere Informationen: 

https://web-beta.archive.org/web/20061125184222/http://wowwiki.com:80/Shade_of_Naxxramas

Mfg Omega :-)

**Comment by Mafyo** [comment]
Danke dir ich muss aber noch was korrigieren.
Die Mobs im Äußeren Ring sind die Mobs die auch in den einzelnen Flügeln vorkommen allerdings mit anderen Namen und manche benutzen ihre Fähigkeiten anders. den wowpedia link den du hast ist der Schemen von Naxxramas den gibt es auch in unserer DB: https://datenbank.classic-wow.org/?npc=16164#drop aber das ist nicht der Geist von Naxxramas der im Äußeren Flügel vorkommt sondern deiner sollte  glaube ich im Militärflügel erscheinen.

Dieser Äußere Ring ist echt ein Grauß, so wenig informationen darüber im wiki man muss echt jede videos peinlich genau untersuchen um unterschiede fest zu stellen die es bekanntlich auch gibt....

[Spirit of Naxxramas: Uses the shade model and patrolled the Outer Ring and had stealth detect](http://wowwiki.wikia.com/wiki/Changes_between_Patch_1.11_Naxxramas_and_Patch_3.0_Naxxramas)

Outer Ring mobs were not mobs from said wing, but rather mobs from every wing (Ghouls, Death Knights, Shades, Skeletal Mages, Necromancers, Plaguehounds, Spiders, etc.). 

Ja un der ''Geist von Naxxramas''(der große) spawnt ''Geist von Naxxramas''(die kleinen) klingt komisch ist aber so

These guys are from the Pre-BC version of Naxxramas. If I recall correctly, these guys had stealth detect and patrolled the outer ring. They are not the ones that are invisible and gank you.

They use your standard shade model (Noticed there was no Screenshot), and they are about the same size as normal shades  http://www.wowhead.com/npc=16449/spirit-of-naxxramas#comments

**Comment by Omegaexodus** [comment]
Danke für deinen Hinweis :-)

Leider glaube ich nicht, das Blizzard damals noch einen zweiten "Geist von Naxxramas /Spirit of Naxxramas" eingebaut hat. Alle alten Einträge und Archive die ich durchgeschaut habe, zeigen, das es nur zwei Versionen dieses Npcs gab. Einmal den "Schemen" als eigentlichen NPC, der dann Portale beschwört und Shadowballs spamt. Und einmal den "Geist von Naxxramas" der aus den Portalen kommt und nicht weiter als Nahkampffähigkeiten hat.

https://web-beta.archive.org/web/20061125184222/http://wowwiki.com:80/Shade_of_Naxxramas

Und der Shade of Naxxramas ist laut Archivedatei die einzige Version, die auch "NUR" in den äußeren Ringen des Militärviertels und aller anderen Viertel vorgekommen ist. Daher wurde das selbe Modell mit genau den selben Fähigkeiten, dann auch in den anderen äußeren Ringen verwendet. (Ich gehe jedenfalls davon aus :D ) 

Da die Archivedatei nur eine Version von "Shade of Naxxramas" hat und es keine weiteren Informationen zu "Spirirt of Naxxramas" gibt (Auch der Artiekl den du verlinkt hast, hat keine weiteren Quellen und Daten dazu). Denke ich das die Informationen zu "Spirit of Naxxramas" nicht wirklich nutzbar sind. Es ist wirklich schwer da eindeutige Daten zu finden.

Vor allem, wäre die Frage, warum Blizzard zwei Npcs mit den selben Fähigkeiten nehmen sollte, aber unterschiedlichen Namen? (ich glaube kaum, das der Unterschied nur der Stealth detect sein soll) oO 

Es kann natürlich auch sein, das die Schreiber der einzelnen Artikel von 2006, die einzelnen Bezeichnungen "Shade, Ghost und Spirit" damals durcheinander gebracht haben und jeder das gleiche meint? -.-

**Comment by Mafyo** [comment]
https://youtu.be/cEsCSdp57d4?t=974 Videobeweis zu ''Spirit of Naxxramas'' und seinem Portal+ Volley. Dieser Raid befindet sich gerade außerhalb des Spinnenflügels am  Anfang des Äußeren Rings bevor die Bosse eingeblendet werden seht ihr das Kill Datum also ein Video aus Classic

Es soll 2 Geister geben einmal ''Shade of Naxxramas'' der im MIlitärviertel sein sollte und einen ''Spirit of Naxxramas'' im äußeren Ring das Problem was wir hier gerade haben ist ein übersetzungs Problem

- ''Spirit of Naxxramas'' lokalisiert ins Deutsche ''Geist von Naxxramas''
- ''Summon Ghost of Naxxramas'' lokalisiert ins Deutsche ''Geister von Naxxramas beschwören''

die kleinen nicht anvisierbaren Geister heissen aber nicht Geist von Naxxramas sondern ''Phantom von Naxxramas''

hier der Zauber von wowhead: http://de.wowhead.com/spell=28389/geister-von-naxxramas-beschworen
Schaut auf den effekt, ''Summon (Phantom von Naxxramas)''

und ''Phantom von Naxxramas'' wird lokalisiert ins Englische ''Ghost of Naxxramas'' 

Links aus unserer Db:
https://datenbank.classic-wow.org/?npc=16419
https://datenbank.classic-wow.org/?spell=28389 Effekt summon Wild ID 16419 stimmt mit dem Phantom überein.

**Comment by Mafyo** [comment]
http://abload.de/image.php?img=20170608_12023016gozf.jpg

Leider die Falsche Portal Fähigkeit gelistet diese die dort steht sollten die Wichtel in ZG benutzen.
aber wir sehen
Link zu unserer DB:https://datenbank.classic-wow.org/?npc=16449
und vergleichen das mit dem Foto sehen wir:
- Schaden sollte auf 2646-3508 erhöht werden
- Leben sollte auf 110040 erhöht werden

**Comment by Omegaexodus** [comment]
> ''Spirit of Naxxramas'' lokalisiert ins Deutsche ''Geist von Naxxramas''
> ''Summon Ghost of Naxxramas'' lokalisiert ins Deutsche ''Geister von Naxxramas beschwören''

Ich denke auch das dies die Beste Erklärung dafür ist. Auch wenn ich mich Frage, warum im englischen kein "Phantom of Naxxramas" auftaucht (Phantom =/ Ghost) . Aber wie du schon vermutet hast, denke ich auch, das es sich hierbei um einen Übersetzungsproblem handelt. Alles andere würde die Thematik unnötig erschweren.

Schließlich macht auch die entsprechende Verlinkung von der Loot-Tabelle nur bei "Spirit of Naxxramas" und "Shade of Naxxramas" Sinn. Da es beim "Phantom of Naxxramas" es keinen Loot gibt. (Geister sind auch nicht tötbar)
