### ISSUE TITLE
[Naxxramas]Grufthäscher

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2128]
Welches Verhalten wird beobachtet?
Sein Spalten macht etwas zuviel Schaden ich habe als meele einen 6k Cleave kassiert ohne flask wäre ich tot gewesen.
Besitzt keinen Enrage.

Wie sollte es sich verhalten?
Sein Spalten sollte etwas weniger schaden machen ich würde mich an dem Spalten der Anub'rekhan Wachen orientieren
sollte einen Enrage besitzen. Ich kann nicht sagen welchen oder ab wieviel % er dies tun sollte da es keine information zu diesem Mob gibt. Nur auf Privat servern

Schritte zur Reproduzierung
Grufthäscher angreifen, Spalten ab bekommen,töten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://www.classicwow.com/database/?npc=15978#abilities feenix Server
https://youtu.be/QtyEoJ6_nZI?t=1928 Enrage der Grufthäscher
im Normalfall würde ich mich an den Anub'rekhan adds halten, ab 50% Enrage
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=8269
https://datenbank.classic-wow.org/?npc=15978
https://datenbank.classic-wow.org/?spell=15284

**Comment by Omegaexodus** [comment]
Ich glaube ich habe da einige interessante Informationen zu gefunden. Diese Daten sind zwar erst ab 2009 / April vorhanden, aber wenn man auf die selbe Verlinkung von "Thootbot" nachgeht, die auf den selben Inhalt abzielen, kann man sehen das der NPC mit den selben Fähigkeiten wohl schon 2007 vorhanden war.

https://web-beta.archive.org/web/20090418162141/http://www.wowwiki.com:80/Crypt_Reaver
https://web-beta.archive.org/web/20071027090715/http://thottbot.com:80/c15978

Laut den Daten von der alten Version macht "Cleave"  110% des normalen Meele-Hits von dem Npc. Was etwas dem 2,1x Schaden entspricht. Kann also schon sein, das wenn er dich mit 2-3k normal hittet, er dich mit bis zu 5-6k Cleaven kann.

Dort sind auch beide Fähigkeiten, Cleave und Frenzy vorhanden: 

https://datenbank.classic-wow.org/?npc=15978

Cleave = Da der normale Cleave nur bis zu 50 Bonusschaden macht, denke ich das noch eine weitere Fähigkeit zum Einsatz kommt. In dem Fall wäre es wohl "Improved Cleave", welches den Schaden um einen bestimmten % Satz erhöht.   -->  https://datenbank.classic-wow.org/?spell=20496

Frenzy = https://datenbank.classic-wow.org/?spell=28371  (Leider kann ich in der Datenbank keinen Frenzy Effekt finden, der 2 Min hält, kann sein, das daher der verlinkte Frenzy-Effekt nicht richtig ist --> 8 Sec Timer)

**Comment by Herlot** [comment]
> Laut den Daten von der alten Version macht "Cleave" 110% des normalen Meele-Hits von dem Npc. Was etwas dem 2,1x Schaden entspricht. Kann also schon sein, das wenn er dich mit 2-3k normal hittet, er dich mit bis zu 5-6k Cleaven kann.

> Inflicts 110% of normal melee damage to an enemy and its nearest allies, affecting up to 3 targets

Wenn ich das richtig interpretiere, dann kommen die 110% nicht auf den normalen Schaden drauf, sondern Cleave macht einfach 1,1*normaler Schaden und das auf bis zu drei Zielen. Wie viel Schaden der Crypt reaver genau macht, müsste man nochmal überprüfen. 

> Cleave = Da der normale Cleave nur bis zu 50 Bonusschaden macht, denke ich das noch eine weitere Fähigkeit zum Einsatz kommt. In dem Fall wäre es wohl "Improved Cleave", welches den Schaden um einen bestimmten % Satz erhöht. --> https://datenbank.classic-wow.org/?spell=20496

Das ist kein Spell, sondern ein Talent, dass man im Furorzweig im Talentbaum skillen kann. Sollte also hiermit nichts zu tun haben.

**Comment by Mafyo** [comment]
Ich habe mir das Bestiary Buch von Brady Games gekauft dort ist fast jeder NPC aus WoW gelistest mit Name, Fertigkeiten, Rüstung, Schaden etc. das Buch wurde für Burning Crusade entworfen also es behinhaltet noch nicht Wotlk Naxx und ist daher nicht wirklich geändert worden. Ich habe diesen Mob dort gefunden und poste mal ein Screen Davon. Unter Crypt Reaver.
http://abload.de/image.php?img=20170608_11235917mo58.jpg
Nach diesem Bild muss der Schaden erhöht werden, leicht die Hp erhöht und der Enrage ist auch gelistet.

es ist der Selbe Enrage wie die Adds bei Anub'rhekan. aber leider ist der momentane Enrage etwas schwächer als der gelistete den gibt es gar nicht in der DB.
https://datenbank.classic-wow.org/?spell=8269 
Effekt #1 	Apply Aura: Mod Damage Done (1) 
                Wert: 50 (muss hier auf 120 erhöht werden)
