### ISSUE TITLE
[Naxxramas]Grabschrecken

### ISSUE THREAD

**Issue by Herlot** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2129]
Welches Verhalten wird beobachtet?
Der Grabschrecken hat zu wenig Leben. Aktuell sogar so wenig, dass die Fähigkeit [Spike Volley](https://datenbank.classic-wow.org/?spell=28615) fast gar nicht zum Einsatz kommt. (Meine Aufnahme dazu ist ziemlich schlecht, Lags wegen Upload und falsche Pixelgröße bei der Aufnahme gewählt - shame on me) Man kann [hier](https://www.twitch.tv/videos/150184298) bei 3:39:40 sehen, wie schnell der Mob umkippt.

Wie sollte es sich verhalten?
Er sollte mehr Leben haben. 

Schritte zur Reproduzierung
Grabschrecken angreifen und Leben überprüfen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Leider nur Informationen von anderen Privatservern. Bei uns hat er aktuell circa 19k HP. Auf den anderen Privatservern hat er circa 110k HP.
[Feenix](http://www.classicwow.com/database/index.php?npc=15979)
[Twinhead](https://vanilla-twinhead.twinstar.cz/?npc=15979#issues)
[Kronos](https://www.youtube.com/watch?v=L205eadaqfE) bei 1:34:24 sieht man in der UI die HP Anzeige.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Grabschrecken](https://datenbank.classic-wow.org/?npc=15979) aus unserer Datenbank
[Tomb Horror](http://wowwiki.wikia.com/wiki/Tomb_Horror?oldid=413850) aus Wowwiki (leider keine HP-Angabe)

**Comment by Omegaexodus** [comment]
Hier noch mal ein entsprechender Nachweis über den Lebenspool von etwa 110k Leben. :-) 

https://web-beta.archive.org/web/20081221163734/http://www.wowwiki.com:80/Tomb_Horror
