### ISSUE TITLE
alteractal: ivus beschwörung:

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#213]
diesen npc kann man im moment nicht beschwören. 

um ivus (http://datenbank.welli-it.de/?npc=13419)  zu beschwören, müssen 10 mitglieder der allianz am circle of calling im alteractal zusammen mit den druiden den boss rufen, ohne unterbrechung

dazu habe ich diese spells gefunden:
http://datenbank.welli-it.de/?spell=21646
(keine ahnung, was es damit auf sich hat: http://datenbank.welli-it.de/?spell=21649
eventuell das rücksetzen des bosses, wenn er sich zu weit entfernt hat?)

der circle (bzw eine art stein) scheint direkt neben dem katapult auf dem feld zu spawnen
https://www.youtube.com/watch?v=e0tfNq_bIdw
https://www.youtube.com/watch?feature=player_detailpage&v=Fwd43lOewVk#t=86
https://www.youtube.com/watch?v=uf6tK-tmpuA

related quests:
http://datenbank.welli-it.de/?quest=7386
http://datenbank.welli-it.de/?quest=6881

ivus sollte der allianz gegenüber freundlich, und der horde gegenüber feindlich sein, jedoch keine horde-npcs angreifen  
momentan ist er beiden gegenüber neutral, und ist anscheinend ein gooblin aus ratchet. (pls fix that, er sollte zu darnassus gehören)
ivus sollte jeden magischen buff akzeptieren und tragen können, der von der allianz kommt. (jedoch keinen dieser buffs: 
http://datenbank.welli-it.de/?search=warcry
http://datenbank.welli-it.de/?spell=23693 )

er hat derzeit auch keinerlei eingetragene abilities. 

abilities die er haben sollte: 
entangling roots: http://datenbank.welli-it.de/?spell=20654
wrath: http://datenbank.welli-it.de/?spell=21667
starfire: http://datenbank.welli-it.de/?spell=21668
moonfire: http://datenbank.welli-it.de/?spell=21669
faerie fire: http://datenbank.welli-it.de/?spell=21670

wenn ivus keinen feindlichen horde-spieler-character in seiner nähe hat, den er angreifen kann, sollte er mit normaler (urtum-)laufgeschwindigkeit daauff dem gebiet, auf dem er beschworen wurde ziellos umherwandern. .
das macht er ca 10 minuten lang, danach läuft er in richtung frostwolfbasis (den weg entlang)
dort bleibt er vor der festung der frostwölfe (wo drek'thar drin ist)  stehen, bis zum ende des bg oder bis er stirbt (solange er keine ziele hat).
seine geschwindigkeit ist normale npc-renn-geschwindigkeit, wenn er ein ziel verfolgt. 

>http://www.wowwiki.com/Ivus_the_Forest_Lord

>By Raimon (148 – 1) on 2008/09/08 (Patch 2.4.3)		
You need to turn in 200 storm crystals (In total from all players) to the arch druids in the alliance base(behind the east bunker) and then escourt the druids to the mid field where you have to click the stone thing thats spawns. 10 ppl is needed to summon him and the druids can bugg if the summon is interupted.

**Comment by Dotox** [comment]
>dort bleibt er vor der festung der frostwölfe (wo drek'thar drin ist) stehen, bis zum ende des bg oder bis er stirbt (solange er keine ziele hat).

Bist du dir da sicher? Despawnt er nicht, wenn er in der Base angekommen ist und dort so ziemlich alles umgehauen hat? Ist es möglich, den Boss mehrmals zu beschwören? Das weiß ich nämlich leider nicht mehr.

**Comment by hraesvelgr** [comment]
nur einmal beschwörbar. ist sozusagen die ultimative waffe. deshalb ist es auch so riskant und schwer, ihn zu beschwäören. sobald der spell für die beschwörung, den die druiden casten,  einmal unterbrochen wird, wars das. spieler können unterbrochen werden und das ganze  auch wieder aufnehmen. nur die druiden sind der knackpunkt. 
und man brauch 10 spieler UND die druiden dafür. ergo reicht schon ein schurke, um das ganze zu versauen. kriegt mans aber hin, hat man eben einen fetten baum/eisriesen, der marodierend durch die gegnerischen massen pflügt. 
ist sozusagen die belohnung für die gute absprache, dass man es schafft, die beschwörung fehlerfrei hinzukriegen. 
http://www.wowhead.com/npc=13419/ivus-the-forest-lord#comments:id=291500
>By Kaali (640 – 2·4) on 2008/05/20 (Patch 2.4.2)		
When the Arch Druid and Druids of the Grove start moving to the middle and after they've started channeling,they must not be interrupted or else it will bug and you can't have another try,since they attack the horde who interrupted their channeling and after that,they just stand next to the circle and won't start to channel. Annoying, isn't it?


zu deiner frage bezüglich despawn: 
> If Ivus reaches the Frostwolf base, he will stand in front of Frostwolf Keep and stay there unless provoked by enemy players, in which case he will give chase until he either leashes back, kills the enemy player, or is killed himself. 

http://wowwiki.wikia.com/wiki/Ivus_the_Forest_Lord

**Comment by hraesvelgr** [comment]
ich würd evtl noch ein paar dinge für lokholar sammeln, wenn du noch was brauchst?!

**Comment by Dotox** [comment]
Lokholar ist schon fertig. Deswegen wollte ich das Script auf Ivus übertragen da im Grunde nur die Spiells, Texte und die Wegpunkte anderst sind. Sonst ist es ja gleich aufgebaut mit der Beschwörung usw. Natürlich alles andere Zauber usw.

Ich denke, dass Lokholar dann auch vor der Base stehen bleibt und nicht despawnt? Weil er ja den Zauber hat, dass er immer einen Buff bekommt, wenn er einen Allianzspieler getötet hat. Das hat Ivus soweit ich das gesehen hab, nicht.

**Comment by hraesvelgr** [comment]
ja, lokholar hat den buff, der ihn stärker macht (was nur 10 mal stackt)

 If Lok'holar successfully reaches the Stormpike base, he will stand in front of the Dun Baldar keep and stay there unless provoked by enemy players, in which case he will give chase until he either leashes back, kills the enemy player, or is killed himself.
