### ISSUE TITLE
Willensbrecher der Qiraji

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2130]
Welches Verhalten wird beobachtet?
Der Mindslayer macht seinen Fear im Moment immer wenn eine Manaklasse/Hunterpet zu nahe an ihm stehen.  

Wie sollte es sich verhalten?
Er sollte die Fähigkeit nur usen, wenn er stirbt.

Schritte zur Reproduzierung
Als Manaklasse zu nahe an einem Willensbrecher stehen. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

> When the Mindslayer finally falls it unleashes an area effect causing all a slight drain in mana to anyone near and also a fear affect, forcing all nearby players to run around in panic....

(https://drive.google.com/uc?id=0B-_HNCwfg1HeNVg3TjExQUR4UTQ&export=download)

> 'Upon death, Mindslayers will confuse nearby players, causing them to run aimlessly for a few seconds. They will also perform one final Mana Drain.'

steht auf wowwiki 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15246

**Comment by Mafyo** [comment]
bisschen schnellerer Einblick http://abload.de/image.php?img=20170608_1413341ybolz.jpg

**Comment by Nifexx** [comment]
Habt ihr etwas an den Fähigkeiten der Mobs verändert? Das mit dem Fear funktioniert, allerdings benutzen sie ihre Fähigkeit Mind Blast unglaublich oft (Gefühlt ist das ein AOE-Spell geworden), sodass man sie nun outrangen muss.
