### ISSUE TITLE
[Naxxramas]Verseuchter Ghul

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2131]
Welches Verhalten wird beobachtet?
Benutzt die Fähigkeiten Rend, Flesh rot und  Enrage nicht
Sie besizten aber korrekter weise einen Chaincleave , da dies die einzige Fähigkeit ist die bei Wowwiki gelistet war ist es mir gar nicht aufgefallen das die eigentlich auch noch die 3 anderen Fähigkeiten haben sollten.
Besitzt Laut Datenbank Schaden: 2,745 - 2,815

Wie sollte es sich verhalten?
Sollte wie die Ghule im Seuchenflügel Rend, Flesh Rot und Enrage einsetzen.
Sollte 2,745-3683 Schaden machen

Schritte zur Reproduzierung
Ghule angreifen, töten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/cEsCSdp57d4?t=951 debuff leiste des Tanks, Enrage kurz vorm sterben
[Strong melee damage Chain-Cleave ](http://wowwiki.wikia.com/wiki/Plagued_Ghoul?oldid=306679)

http://abload.de/image.php?img=20170608_1251171tbqf1.jpg Plagued Ghoul

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16447
https://datenbank.classic-wow.org/?spell=24318
https://datenbank.classic-wow.org/?spell=29915
https://datenbank.classic-wow.org/?spell=13738

**Comment by Omegaexodus** [comment]
Kann es sein das der Wert für die Fähigkeit "Rend" viel zu gering ist? 

https://datenbank.classic-wow.org/?spell=13738

Momentan steht ein Wert von "26" drin, was mal gerade 26 Schaden alle 3 Sekunden entspricht. 

Ich denke eher das es dieser Zauber ist, mit 84 Schaden pro Sekunde:

https://datenbank.classic-wow.org/?spell=18106

Kann man auch gut im Video erkennen ,das der Tank alle 3 Sekunden ca. 80 Schaden bekommt. 

Das selbe, nur andersrum, gilt für "Flesh Rot". Hier ist der Wert zu hoch und sollte eigentlich, laut dem Video bei "525" alle 2 Sekunden liegen. --> 270 jede Sekunde.

https://datenbank.classic-wow.org/?spell=29915

Demnach sollte es dieser Zauber sein: 

https://datenbank.classic-wow.org/?spell=28913

Ich möchte gleich noch darauf hinweisen, das auch der "Infizierte Ghul" im Seuchenflügel, diese 4 Fähigkeiten haben sollte. (Cleave, Flesh Rot, Rend und Enrage) 

Bitte noch mal überprüfen ob alle Zauber ordentlich in der Datenbank verlinkt sind für die beiden Gegnertypen.

Mfg Omega :-)

**Comment by Dotox** [comment]
Die DB bitte nicht als Referenz für benutzte Zauber nehmen, die stehen im Script und können von der Web-DB nicht ausgelesen werden. Werde es sicherheitshalber trotzdem prüfen.

**Comment by Mafyo** [comment]
> Ich möchte gleich noch darauf hinweisen, das auch der "Infizierte Ghul" im Seuchenflügel, diese 3 bzw. 4 Fähigkeiten haben sollte. ([Cleave], Flesh Rot, Rend und Enrage)

[They have some sort of short range AoE. Was unable to get data on it](http://wowwiki.wikia.com/wiki/Infectious_Ghoul?oldid=383695) meint wahrscheinlich den Cleave

Omegaexodus magst du deswegen nen extra Report machen sonst wird das zu unübersichtlich hier. Er benutzt alle Fähigkeiten außer den Cleave
Muss zur Arbeit ;)

**Comment by Omegaexodus** [comment]
Jo packe ich schnell rein. Ein Glück das bei mir auf Arbeit nichts los ist und ich das von hier aus machen kann. :D
