### ISSUE TITLE
[Naxxramas] Großwitwe Faerlina

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2132]
Welches Verhalten wird beobachtet?
Wenn man einen Jünger von Naxxramas opfert sollte Widows Embrace auch auf Spieler übersrpingen die sich in der Nähe des geopferten Jüngers aufgehalten haben.

Schaden laut Datenbank:
Schaden: 5,601 - 6,853

Wie sollte es sich verhalten?
Nach dem opfern eines Jüngers sollte Windows Embrace auch die Spieler betreffen und  nicht nur Faerlinas Enrage beenden. das hatt zu Folge das genau drauf geachtet werden muss das der Jünger nicht im caster camp geopfert wird und alle auf genug Range stehen

Schaden laut Bestiary:
Schaden : 5,492 - 7,281

Schritte zur Reproduzierung
Fearlina angreifen,  Jünger opfern, in der Range zu einem geopferten Jünger stehen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/cEsCSdp57d4?t=735 Debuffleiste Windows Embrace
https://youtu.be/SnoXlPYpg28?t=173 was aussieht wie eine Arkane explosion und alle Melees trifft ist Widows Embrace
http://abload.de/image.php?img=20170608_1325211rgrn7.jpg das Level 73 kommt daher da das Buch aus BC(70) ist und Bosslevel immer 3 level über des eigenen sind.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15953
https://datenbank.classic-wow.org/?npc=16506
https://datenbank.classic-wow.org/?spell=28732
https://datenbank.classic-wow.org/?spell=28797
https://datenbank.classic-wow.org/?spell=28798

**Comment by Omegaexodus** [comment]
Ich möchte dazu noch anmerken, das es sich hierbei nur um den "Reduces casting speed by 25%" Effekt handelt. Man kann deutlich in dem Video erkennen, das alle Heiler und Caster um Faerlina herum, weiterzaubern können. Nicht das nachher noch der "Silence Effect" für die 30 Sekunden übernommen wird. :-)

Apply Aura: Haste - Spells 
Wert: -25	
Radius: 15 Meter

https://datenbank.classic-wow.org/?spell=28732

**Comment by Mafyo** [comment]
Der Effekt sollte auch Dispellbar sein
