### ISSUE TITLE
[Naxxramas] Kultist von Naxxramas

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2136]
Welches Verhalten wird beobachtet?
Die Mobs haben keine AoE-Schattenaura und etwas zuviel HP.

Wie sollte es sich verhalten?
Es sollte eine AoE-Schattenaura vorhanden sein und die HP sollten etwas niedriger sein.

Schritte zur Reproduzierung
Mobs vor Faerlina pullen und beobachten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[22k HP](https://web-beta.archive.org/web/20080522121711/http://www.wowwiki.com:80/Naxxramas_Cultist)
[AE Shadow Aura , ~500dmg](http://wowwiki.wikia.com/wiki/Naxxramas_Cultist?direction=next&oldid=266992)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Kultist von Naxxramas](https://datenbank.classic-wow.org/?npc=15980)
[Unholy Aura](https://datenbank.classic-wow.org/?spell=27988) Evtl. sowas als fehlender Spell?

**Comment by Dotox** [comment]
Wir suchen leider schon seit Tagen nach der Schattenaura als Spellid, nichts gefunden. Unholy-Aura ist es leider nicht.

**Comment by Omegaexodus** [comment]
Das einzige was ich noch dazu gefunden habe, wäre "Curse of Agony" mit den folgenden Daten:

Apply Aura: Periodic Damage 
Wert: 51	
Radius: 45 Meter	
Intervall: 3 Sekunden

Bei 30 sec Laufzeit, mit jeweils 3 Sekunden Intervallen, wären es ca. 500 Schattenschaden. (Was etwa dem Wert entspricht) Es ist leider nicht ersichtlich, in welchen Intervallen die 500 Schaden kommen sollen. :-(

Ansonsten habe ich nichts in alten Archiven gefunden. Die meisten dieser Zauber sind nur auf Unheilige Aura zurückzuführen. 

https://datenbank.classic-wow.org/?spell=18671

**Comment by Baraz** [comment]
Ich habe aber auch noch kein Video gefunden, wo so etwas wie eine Schattenaura zu erkennen wäre (im Kampflog oder so). Möglicherweise war das auch ein kollektives Missverständnis mit den Schattenblitzsalven der Akolyten?

**Comment by Dotox** [comment]
Hm, wahrscheinlich nicht. Es gibt definitiv eine Aura, die steht auch in diversen Guides.

Videos haben wir bereits einige gefunden:

https://youtu.be/FH7ytRnmgDc?t=105

https://youtu.be/Rp5JNSGkBDA?t=1m53s

Kronos:
https://youtu.be/L205eadaqfE?t=4173

**Comment by Baraz** [comment]
[Hier](https://r2---sn-4g5e6nls.googlevideo.com/videoplayback?initcwndbps=942500&signature=254F092860816CF3CBCBBCCEE62D68F9BB7067B0.E3D2217DD5099A6A8440CA23C992374043F129FF&requiressl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&expire=1497056425&itag=22&ei=SfA6WfKnJobEcMqIjZgC&key=yt6&source=youtube&mime=video%2Fmp4&mv=m&mt=1497034661&ms=au&pl=18&lmt=1486426550774788&dur=10749.979&id=o-AKPmIXkPJesLasSjkVQC2TJtGnhzE9GMmOBO5lZADPk2&ipbits=0&ratebypass=yes&mn=sn-4g5e6nls&ip=93.202.225.44&mm=31), auch vom Kronos Testrealm sieht man das Kampflog und keine Erwähnung irgendeines Schattenschadens außerhalb der Volley oder des Shadow Burst.

**Comment by Mafyo** [comment]
wäre nicht das erste mal das Wowwiki falsch Informationen hatt, ich kann in der DB auch nichts passendes entdecken. Ich glaube das dies ein Event von der Großwitwe ist es hatt was mit dem Entrace Emote zu tun irgendwas Lore mäßiges. Aufjedenfall wenn man sich die videos anschaut verschwindet diese ''Aura'' wenn die mobs gepullt werden.

''Your old lives, your mortal desires, mean nothing. You are acolytes of the master now, and you will serve the cause without question! The greatest glory is to die in the master's service!''

Ich habe auch versucht mal einzelne Worte aus dem Zitat in die Db einzugeben bin aber auf nichts gestoßen
Wenn die Bosse in Naxxramas einer Hirachie unterliegen mit Kelthuzad als ober Boss würde es mich nicht wundern wenn genaus dieser Spell namentlich überhaupt gar nichts mit Spinnen zu tun hatt oder Schatten,Unholy oder Poison.

 ''You are acolytes of the master now''
würde mich zummindest auf eine andere Spur bringen
