### ISSUE TITLE
[Naxxramas]Steinhautgargoyle

### ISSUE THREAD

**Issue by Herlot** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2137]
Welches Verhalten wird beobachtet?
Die Giftsalve kommt zu häufig, sie kommt circa alle [4 Sekunden](https://youtu.be/Olzvyf7ccso?t=1h15m). 

Wie sollte es sich verhalten?
Die Salve sollte deutlich seltener kommen, nur circa alle 8-10 Sekunden.

Schritte zur Reproduzierung
Gargoyle pullen und die Frequenz der Salve überprüfen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Hier](https://youtu.be/FH7ytRnmgDc?t=4m) sieht man, dass die Gargoyles die Salve nicht alle 4 Sekunden, sondern mit einer niedrigeren Frequenz benutzen.
[Steinhautgargoyle auf Wowwiki](http://wowwiki.wikia.com/wiki/Stoneskin_Gargoyle?oldid=338320)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16168#abilities
https://datenbank.classic-wow.org/?spell=29325

**Comment by Dotox** [comment]
Ich habe die castzeit vor Monaten bereits recherchiert, finde das Video aber nicht mehr. Eventuell sind die Aufnahmen die du verlinkt hast verlangsamt. Eventuell weitere Quellen finden.

**Comment by Herlot** [comment]
Wenn du dir selbst über die Castzeit sicher bist, dann kannst du hier gerne schließen. Ich bin der Meinung man kann relativ gut erkennen, dass das Video nicht verlangsamt ist? Wenn ich noch eine Quelle finde (habe schon lange gesucht), packe ich sie hier rein. Das Problem ist, dass nie die Frequenz der Fähigkeit beschrieben ist, sondern immer nur der direkte Schaden und der überbleibende DoT. Die Häufigkeit kann man leider nur in Videos sehen und da überhaupt von einem Trashmob was zu finden ist sehr schwer.

**Comment by Dotox** [comment]
Ich weiß, lasse es trotzdem mal offen da ich mir auch nicht mehr ganz sicher bin (finde das Video von damals nicht mehr).

**Comment by Herlot** [comment]
Vielleicht hilft das [Video](https://youtu.be/QtyEoJ6_nZI?t=46m) ja. Vorausgesetzt, beide Gargoyletypen benutzen den selben Spell ([Acid Volley](https://datenbank.classic-wow.org/?spell=29325)).

**Comment by Baraz** [comment]
[Hier](https://youtu.be/9BScPkpUYDM?list=PLIdn8zmmXRUjjsf_A27Auf8dRxnV1UO2b&t=88) wäre noch ein Video von VanillaGaming, ca. alle 8s gecastet.
