### ISSUE TITLE
[Naxxramas] Verseuchter Gargoyle

### ISSUE THREAD

**Issue by Herlot** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2138]
Welches Verhalten wird beobachtet?
Die Giftsalve kommt zu häufig, sie kommt circa alle [4 Sekunden](https://youtu.be/K8F2VRQthVY?t=3h36m50s).

Wie sollte es sich verhalten?
Die Salve sollte deutlich seltener kommen, nur circa alle 8-10 Sekunden.

Schritte zur Reproduzierung
Gargoyle pullen und die Frequenz der Salve überprüfen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Hier (Kronos)](https://youtu.be/L205eadaqfE?t=1h38m) sieht man, dass die Gargoyles die Salve nicht alle 4 Sekunden, sondern mit einer niedrigeren Frequenz benutzen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16446#abilities
https://datenbank.classic-wow.org/?spell=29325

PS: Es werden unterschiedliche Videos benutzt bei beiden Einträgen #2137. Es handelt sich aber um dieselbe Fähigkeit und deshalb auch um dieselbe Unregelmäßigkeit.

**Comment by Herlot** [comment]
#2137 Es handelt sich bestimmt beides Mal um die selbe Fähigkeit und dieselbe Unregelmäßigkeit

**Comment by Dotox** [comment]
Andere Private Server sind nur unter ganz bestimmten Umständen eine Quelle. Außerdem wurde bereits ein Eintrag bezüglich dieses Mobs eröffnet :)

**Comment by Herlot** [comment]
Wollte den Thread da nicht zu müllen. Da in unserer Datenbank beide mit demselben Spell gelinkt sind, dachte ich, dass die Quelle ausreicht. [Hier](https://youtu.be/QtyEoJ6_nZI?t=46m) sieht man nochmal was über die Frequenz, ob es jetzt die Acid Volley ist oder die Poison volley, dafür ist dann wohl der andere Thread da :) #2123
