### ISSUE TITLE
Quest "[Das Szepter von Celebras]" in Maraudon

### ISSUE THREAD

**Issue by balthasar1981** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2139]
Welches Verhalten wird beobachtet? 
Der NPC "Celebras der Erlöste" läuft los und begibt sich zu einem Stein & bleibt in einer Endlosschleife stecken die man nur mit dem abbrechen der Quest beenden kann

Wie sollte es sich verhalten?
Der NPC "Celebras der Erlöste" sollte das Item 
https://datenbank.classic-wow.org/?item=17191 herstellen und an den Spieler übergeben

Schritte zur Reproduzierung
Die Quest annehmen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Baraz** [comment]
#1417 
#1231 
#1501

**Comment by balthasar1981** [comment]
nach wievor nicht behoben, gleicher stand
