### ISSUE TITLE
Hexenmeister Wichtel

### ISSUE THREAD

**Issue by Fayt908** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2140]
Welches Verhalten wird beobachtet?
Beim Wichtel funktionier der Defensiv modus nicht richtig und zwar greift der Wichtel nicht mit an wenn ich angreife oder angegriffen werde
Wie sollte es sich verhalten?
der Wichtel sollte mit angreifen automatisch
Schritte zur Reproduzierung
Bin im Startgebiet der Untoten und kämpfe gegen Skelete aber nach dem ich Schattenblitz benutze greif der Wichtel nicht an, nicht mal wen ich vom Skelet angegriffen werde. er steht auf Defensiv und da sollte er mit angreifen
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Klasse: Hexenmeister 
Klasse: Untoter 
Level: 3
Begleiter: Wichtel

Erledigt nach nem relog geht es

**Comment by Slimmer2** [comment]
Dann schließe den Bug
