### ISSUE TITLE
Loot- oder Anzeigebug BRD Arena

### ISSUE THREAD

**Issue by mandark666** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2142]
Welches Verhalten wird beobachtet?
War mit Schurke und Druide in BRD in der Arena. Boss Ok'thor der Zerstörer hat für Schurken den blauen Gegenstand "Ogerseherfäuste" gedroppt, gleichzeit für Druiden aber den grünen Gegenstand "Ogreseer Fists". Habe dann mit Rogue die blauen gelootet und auch erhalten.
Rouge spielt auf DE-Client, Druide auf EN-Client.
Ogerseherfäuste: https://datenbank.classic-wow.org/?item=11665
Ojkt'thor der Zerstörer: https://datenbank.classic-wow.org/?npc=9030
Die grünen Handschuhe finde ich in keiner Datenbank.

Wie sollte es sich verhalten?
Auch für den Druiden sollten die blauen Handschuhe droppen, mit Ausdauer, Int und Wille, sowie +13 Schaden/Heilung, und nicht die grünen Teile mit Stärke, Intellect und Wille

Schritte zur Reproduzierung
Mit Chars mit unterschiedlichen Sprachclients in die Arena gehen,

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
![screen1](https://user-images.githubusercontent.com/29333330/27002770-e0f051f8-4de9-11e7-95ea-c4ae51ecb01c.png)
![screen2](https://user-images.githubusercontent.com/29333330/27002772-e5b98c7c-4de9-11e7-9517-73dc59a00761.png)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
WDB leeren sollte abhilfe schaffen.
