### ISSUE TITLE
[Naxxramas]Verseuchter Krieger Noth Kampf

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2148]
Welches Verhalten wird beobachtet?
In einem Stream von jemanden habe ich letztens gesehen das im Noth Kampf die Skelette einfach in Gruppen getankt und gebombt worden sind. In der DB. haben diese Skellte ziemlich wenig Schaden,
Schaden: 340 - 492

Wie sollte es sich verhalten?
Diese Krieger sollten ein wenig mehr Schaden verursachen sodass sie ein bisschen mehr vordernd sind. Bitte beim korigieren der Schadenswerte darauf achten das Rüstung den Schaden verringert und das der Schaden etwas höher angesetzt wird als die Zahlen die im Video zu sehen sind

Schritte zur Reproduzierung
Kampf mit Noth beginnen, Krieger beschwören lassen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/yeoCL7paZBg?t=237 ein Stoffie kassiert 2,293 cleave
https://youtu.be/nk-qw18P9u4?t=166 1850 Cleave auf einen Schurken
https://youtu.be/1DxYd-Bvu9Y?t=124 2230 normal hit auf einen Mage
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16984
https://datenbank.classic-wow.org/?npc=15954

**Comment by Dotox** [comment]
Im Video gesehen oder nur über die DB? (DB zählt aktuell nicht als Richtwert)

**Comment by Mafyo** [comment]
ich habe es gearde getestet ich bekomme als Schurke einen 1296 normal hit ab und eine Cleave mit 1255

**Comment by Dotox** [comment]
Der Cleave-Zauber war nicht korrekt, stimmt!
