### ISSUE TITLE
[Naxxramas]Verseuchter Champion Noth Kampf

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2149]
Welches Verhalten wird beobachtet?
zu wenig Schaden laut DB 
Schaden: 340 - 492
Wie sollte es sich verhalten?
sollte etwas mehr Schaden verursachen damit er vordernder wird. Bitte beim korigieren der Schadenswerte darauf achten das Rüstung den Schaden verringert und das der Schaden etwas höher angesetzt wird als die Zahlen die im Video zu sehen sind
Schritte zur Reproduzierung
Kampf mit Noth beginnen, Teleport auf seinen Balkon abwarten, Champions spawnen lassen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/1PIQcgdMcZk?t=299 1335 normal hit auf einen Schurken
https://youtu.be/E-xKuos_Y0E?t=276 1548 und 1332 er hit auf einen Stoffie

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16983
https://datenbank.classic-wow.org/?npc=15954

**Comment by Dotox** [comment]
Im Video gesehen oder nur über die DB? (DB zählt aktuell nicht als Richtwert)
