### ISSUE TITLE
elemental invasions, respawnrate

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#215]
die elementlords und ihre diener spawnen momentan ca jede stunde, was es unglaublich einfach macht, gear und mats zu farmen. 

sie sollten in einem zeitfenster von mindestens 2, bis maximal 3 tage respawnen. 

tempestria: http://datenbank.welli-it.de/?npc=14457
lavinius: http://datenbank.welli-it.de/?npc=14464
windhäscher: http://datenbank.welli-it.de/?npc=14454
glutarr: http://datenbank.welli-it.de/?npc=14461

das gleiche gilt für alle elementare um sie herum, die das gleiche element tragen (feuer, wind, usw). ist der elementlord der jeweiligen invasion tot, spawnen keine neuen elementare mehr, bis der jeweilige lord wieder respawnt ist. 
die lords haben diverse routen. baron glutarr zb läuft um den feuersäulengrat herum, mit seiner eskorte

donnernder eindringling http://datenbank.welli-it.de/?npc=14462 zusammen mit lavinius
lodernder eindringling http://datenbank.welli-it.de/?npc=14460 zusammen mit glutarr
wirbelnder eindringling http://datenbank.welli-it.de/?npc=14455 zusammen mit dem häscher
wässriger eindringling http://datenbank.welli-it.de/?npc=14458 zusammen mit tempestria.

jeder elementlord bekommt eine eskorte aus 3-4 elementaren, die unweigerlich mit ihm verlinkt ist. 
lords und normale elementare spawnen zusammen, als script. 

> http://www.wowwiki.com/Elemental_Invasions
> 
> How often do invasions happen?
> No timetable has yet been determined, though some rumors suggest once every three days.
> It has been shown that at least [60+] Water Princess Tempestria can spawn within a 40-48 hour period. 

ausserdem, für mehr ambiente: die elemtentlords und ihre minions spawnen langsam aus einem portal heraus, das an einem punkt ihrer jeweiligen zone spawnt (an dem derzeitigen stadort der bosse). und dann langsam elementare ausspuckt, die sich  über das gebiet  verteilen. ich nehme an es gibt ein cap (sonst würden ja unendlich viele spawnen) laut wowwiki aber "three times as many elementals in the area" + den lord uns seine eskorte.
in silithus sind momentan auch ohne gescripetet invasion korrekt viele elementare vorhanden, in den anderen regionen nicht. man kann sich also von der mobdichte an silithus orientieren. 
http://old.wowdata.ru/data/userimg/12/12205.jpg

ich nehme an es sind diese portale:
http://datenbank.welli-it.de/?object=179664 erdriss
http://datenbank.welli-it.de/?object=179666 feuerriss
http://datenbank.welli-it.de/?object=179667 luftriss
http://datenbank.welli-it.de/?object=179665 wasserriss
so sieht ein riss wohl aus:
http://nsa37.casimages.com/img/2015/09/06/150906065650341313.png
https://forum.nostalrius.org/viewtopic.php?f=2&t=20743 (damn nostalrius. they ruin everything)
http://i245.photobucket.com/albums/gg54/yeticakes/wipe.jpg

> ich werd mal versuchen, eine karte mit den exakten locations der portale zu finden, und auch, wieviele es insgesamt sind 
> ansonsten spawnen die portale in ungoro zb um den kleinen vulkan im krater herum (feuersäulengrat)
> 
> At the beginning of an elemental invasion, portals will open to the Elemental Plane and invaders will begin to pass through. Thus, during an invasion, you will find two to three times as many elementals in the area, usually slightly higher in level than the standard ones found there. 

wer sich also die mühe machen will, das gesamte event zu scripten... :P

quellen: 

> http://www.bubblesofmischief.com/2012/01/24/elemental-invasions/
> http://wow.gamona.de/forum/threads/invasion-im-ungoro-krater.62695/
> http://www.mmo-champion.com/threads/713925-What-is-this-%28Screen-print%29
> http://www.lurkerlounge.com/forums/thread-6513.html

**Comment by hraesvelgr** [comment]
updated. paar quellen hinzugefügt, paar mehr fotos, und nostalrius scheint auf ihren servern grad das event eingefügt zu haben. 

tse, als ob die auch nur ansatzweise besser wären :D

**Comment by Dotox** [comment]
Oh, stimmt das wollte ich auch mal noch fertig schreiben. Mach ich nach Alterac :)

**Comment by hraesvelgr** [comment]
alterac is echt wichtiger :P

**Comment by Jessienia** [comment]
Huhu

Wie schauts denn eigentlich mit dem Event aus? Wenn das Projekt hier erst mal gestorben ist, wie wäre es dann, wenn man einfach mal den respawn von den 4 Elite Bossen und den dazugehörigen nonelite (z.b. die "Wirbelnder Eindringling"e in Silithus) auf 2-3 Tage setzt, anstatt 15-50 Minuten wie es momentan der Fall ist? 
Die ganzen entsprechenden Mobs sind nun mal eine sehr blizzunlike Quelle für Essenzen, Elementarzeugs, usw...

**Comment by dagochen** [comment]
Ich mach hier schon mal zu, da es fast fertig ist und demnächst aufgespielt werden kann ;)
