### ISSUE TITLE
[Naxxramas] Anub'Rehkan

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2150]
**Welches Verhalten wird beobachtet?**
Anub'Rehkan setzt die Fähigkeit "Aufspießen" nicht richtig ein. Teilweise kam es gestern vor, das niemand von der Welle getroffen wurde, obwohl mehrere Spieler in dieser standen. Auch kam es vor, das es ab und zu niemanden getroffen hatte, obwohl sich der entsprechende Spieler, der anvisiert wurde, in Reichweite befunden hatte. Dabei wurde weder Schaden verursacht, noch wurde der Spieler in die Luft gekickt (Das selbe gilt für nah stehende Spieler). 

Anub'Rehkan setzt die Fähigkeit "Heuschreckenschwarm" nicht richtig ein. Die Fähigkeit wird nicht auf  Pets von Huntern / Hexenmeistern gewirkt. Sie können weiterhin am Boss bleiben und Schaden verursachen, ohne einen nachteiligen Effekt, während der Anwendung. Außerdem funktioniert "Magie entdecken" von den Magiern nicht auf Anub'Rehkans "Heuschreckenschwarm". Sobald er die Fähigkeit "Heuschreckenschwarm" einsetzt, sollte "Magie entdecken" die Aura bei ihm, in Form einen Icons (Buff) anzeigen lassen.

**Wie sollte es sich verhalten?**
"Aufspießen" --> Die Fähigkeit sollte ein zufälliges Ziel wählen, welches sich in der Aggroliste von Anub'Rehkan befindet. Dabei wird eine Welle von Stacheln zum Ziel geschickt, welche alle Spieler auf dem Weg zum Ziel (Und das Zeil selbst --> wenn in Range) in die Luft kickt und ca. 4000 Schaden (Rüstungsabhängig) verursacht. (35 Yards Range, ca. 10 Yards Breite)

Außerdem sollte der Heuschreckenschwarm auch auf Pets von Huntern und Hexenmeistern angewandt werden.

Wenn "Magie entdecken" auf Anub'Rehkan gezaubert ist und er den Zauber "Heuschreckenschwarm" erfolgreich eingesetzt hat, erhält er einen entsprechendes Buff Icon für Auren, welches solange auf ihm zu sehen ist, bis Heuschreckenschwarm ausgelaufen ist.

**Schritte zur Reproduzierung**
Anub'Rehkan mit mehreren Spielern (~40), unterschiedlicher Reichweite, bekämpfen und die Fähigkeit "Aufspießen" genau beobachten. Die Magier verwenden bei dem einsetzen von "Heuschreckenschwarm" "Magie entdecken" auf den Boss.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Es schien das er den Zauber "Aufspießen" zwar ausführt, aber teilweise zu schnell wieder in Richtung Tank dreht und somit den Zauber selbst unterbricht bzw. das Script nur teilweise richtig eingesetzt wird . Dabei wird dann die Animation vollkommen richtig ausgeführt, jedoch wird meistens keiner der Spieler dabei getroffen (Weder Schaden, noch Knockback in der Animation). Das kam in bis zu 80% aller Anwendungen von "Aufspießen" vor. Eine andere Möglichkeit wäre, das nur der Ort, wo "Aufspießen" einschlägt wirklich als AOE Zone geflaggt wird. Der Weg von Anub'Rehkan "Aufspießen" bis zum Ziel, wird nicht als AOE Zone deklariert und hat keine Auswirkungen Effekt mäßig.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
NPC
https://datenbank.classic-wow.org/?npc=15956

Aufspießen
https://datenbank.classic-wow.org/?spell=28783

Magie entdecken 
https://datenbank.classic-wow.org/?spell=2855

Heuschreckenschwarm
https://datenbank.classic-wow.org/?spell=28785
https://datenbank.classic-wow.org/?spell=28786

https://www.youtube.com/watch?v=KygogLz9Okg 
 ~ 1:15 Nachweis über "Magie entdecken"
 ~ 2:40 Nachweis über "AOE Zone von Impale" bis zum Target

**Comment by Dotox** [comment]
Wie man in einigen Videos von damals sehen kann, ist die Animation des Impales nicht immer korrekt. Das lässt sich auch hier nicht immer vermeiden habs allerdings nochmal versucht, etwas zu verbessern.

**Comment by Omegaexodus** [comment]
Was ich vielleicht noch vergessen hatte zu erwähnen, bzw. etwas falsch rübergebracht habe. Es gab auch ab und zu den Fall, das "Aufspießen" nur das Ziel hinten getroffen hatte (+Knockback) aber alle Spieler auf der selben Linie (Vom Boss zum Ziel) blieben vom "Aufspießen" unberührt. 

Wenn der Flügel noch länger als bis Dienstag offen bleiben sollte, könnte man das noch mal entsprechend mit 40 Spielern testen.
