### ISSUE TITLE
[Naxxramas] Anhänger von Naxxramas

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2151]
**Welches Verhalten wird beobachtet?**
Die zwei Adds von Faerlina, mit dem Namen "Anhänger von Naxxramas", sollten die Fähigkeit "Ansturm" besitzen. Jedoch wurde nicht einmal beobachtet, dass sie diese Fähigkeit während des Bosskampfes eingesetzt haben.

**Wie sollte es sich verhalten?**
Die "Anhänger von Naxxramas" setzen die Fähigkeit "Ansturm" regelmäßig ein, was sie in Kombination mit Ihrem "Aoe Silence" für Heiler und Caster deutlich gefährlicher macht. Dies ist auch einer mit der Hauptgründe, weshalb sie am Anfang des Kampfes getötet werde sollten.

**Schritte zur Reproduzierung**
Faerlina pullen und schauen ob die Adds "Anhänger von Naxxramas" die Fähigkeit "Ansturm" einsetzen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Es scheint so, das sie die Fähigkeit nicht anwenden können. Bitte in dem Script nachschauen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npc:
https://datenbank.classic-wow.org/?npc=16505

Charge: 
https://datenbank.classic-wow.org/?spell=22120

Nachweise: 
https://web-beta.archive.org/web/20080124041958/http://thottbot.com:80/c15953 (Comments)
https://www.youtube.com/watch?v=BNKPS_FiOeE
~ 0:06 / Targets Blau und Mond

**Comment by Dotox** [comment]
Funktioniert bei mir ohne Probleme

**Comment by Mafyo** [comment]
Dotox hast du den Charge schon zum berseker charge geändert, mit dem Knockback?

**Comment by Omegaexodus** [comment]
Also wir haben gestern mehrmals Fearlina getestet (3-4 Trys bevor Kill) und es kam so gut wie nicht einmal vor, das sie ein Ziel bei uns angestürmt haben. 

Könnten uns eventuell andere Gilden bestätigen, ob es sich hierbei vielleicht nur um eine Ausnahme bei uns gehandelt hat? Haben andere Gilden etwas anderes bei ihren Testraids beobachtet?

**Comment by Dotox** [comment]
Ich war bei allen Raids anwesend und da hat es funktioniert. Habt ihr die Anhänger vom Raid weg getankt, so dass die eventuell niemanden anstürmen konnten?

@Mafyo Ja, geht aber trotzdem, habs eben getestet.

**Comment by Omegaexodus** [comment]
Wir haben sie nur bedingt woanders hingezogen. Sie waren vielleicht 20 Yards von weiteren Zielen entfernt und wurden sehr zügig umgebracht. Aber wie gesagt, niemand hat in unserem Raid, auch zu Beginn des Pullens, so etwas beobachten können.

Sehr merkwürdig oO

**Comment by Baraz** [comment]
Wir konnten den Charge beobachten, zumindest zu Beginn. Da für Caster/Heiler 30m+ Entfernung angesagt war, konnten wir weitere Charges vermutlich vermeiden. Zusätzlich dazu, dass die meistens zuerst umgehauen werden.
