### ISSUE TITLE
[Naxxramas] Akolyt der Nekropole

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2152]
**Welches Verhalten wird beobachtet?**
Der Akolyt der Nekropole setzt seine Fähigkeit "Schattensalve" falsch ein. Erstmal sollte er die Fähigkeit nur einsetzen wenn https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2147 die Bedingungen für die Anzahl der Spieler in Range erfüllt sind. Außerdem scheint die Fähigkeit momentan überdimensionale Werte in der Scriptanbindung zu haben. Die Schattenblitzsalve verursacht momentan bis zu 2500 Schaden, wird alle ~5 Sekunden eingesetzt und hat zudem unbegrenzte Reichweite + unbegrenzte Anzahl an Zielen. 

**Wie sollte es sich verhalten?**
Die Schattenbliztsalve sollte nur dann ausgelöst werden, wenn die Bedienungen, mit der Anzahl der Spieler in einer gewissen Reichweite, erfüllt sind. Außerdem sollte die Fähigkeit "Schattenblitzsalve" nur ca. 800 Schaden verursachen. (Die Reichweite ist zudem laut alten Infos auf max. 30 Yard Range begrenzt)

**Schritte zur Reproduzierung**
Nach Naxxramas begeben und Akolyt der Nekropole pullen. Dann warten bis er die entsprechenden Fähigkeiten einsetzt.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Momentan sind die "Akolyten der Nekropole" mit eine der schwersten Trashgruppen in Naxxramas. Nur durch eine Kombination aus Los (Gruppenkuscheln) und dem gezielten pullen, sowie dem positionieren von den Tanks, mit den jeweiligen Adds in Ecken, ist es möglich die beiden einzeln zu töten.

Bitte entsprechende SpellId von der Schattenblitzsalve überprüfen. (Wert, Radius, CD, Event)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npc:
https://datenbank.classic-wow.org/?npc=15981

Schattenblitzsalve:
https://datenbank.classic-wow.org/?spell=28448

Informationen:
http://wowwiki.wikia.com/wiki/Necropolis_Acolyte?oldid=233922
https://web-beta.archive.org/web/20061113122311/http://wowwiki.com/Necropolis_Acolyte

**Comment by Mafyo** [comment]
Das mit Der Range was in wowwiki steht ist falsch dokumentiert, Videos wiederlegen diese Behauptung. Es ist mir gestern erst aufgefallen hier ein Video vom Giga Raid diese Mobs setzten die Salve sofort nach Pull ein und eine Range check scheint es nicht zu geben https://youtu.be/QtyEoJ6_nZI?t=2726 das mit dem Schaden und Range stimmt. Und wenn man im Video mal auf den Linken akolyt schaut und beginnt ab der ersten Salve zu zählen, komme auch auf 10-12 Sekunden intervall

https://youtu.be/7zyyzmDn9j0?t=318 dadurch das die Arkane explosion gecastet wird nach dem volley sollte dieser Mob nur aus der Range getötet werden steht auch auf wiki

https://youtu.be/ofbTdgP1pbA?t=692 hier ein Video was Omegas vermutung mit der Range bestätigen könnte guckt mal auf das Rechte Add es macht den Volley diese fliegt aber nur zum gegenüberstehenden Mob auf der Linke Seite zu den Melees das Rangecamp bekommt nichts ab

**Comment by Dotox** [comment]
In dem Video sieht man deutlich, dass die Salve gecastet wird, auch wenn keine Meeles dran sind.

https://youtu.be/QtyEoJ6_nZI?t=45m42s

**Comment by Dotox** [comment]
Hab die Schattensalve vom Schaden her angepasst, allerdings gibt es keine die nur in Meelerange geht. Daher dafault 30 Meter :)

**Comment by Omegaexodus** [comment]
Selbst wenn sie die Salve zaubern sollten, wenn keine Meeles dranstehen (Auf Grund falscher Infos von wowwiki). So sind momentan die Werte von der Salve definitiv falsch. Wir sind gestern 4-5 gewipet, weil sie den Raid innerhalb von 10 Sekunden zerlegt haben. Und ja wir haben die Reichweite auch getestet. Keine Begrenzung. (2500 Schaden etwa)
