### ISSUE TITLE
[Naxxramas] Geist (Spirit) von Naxxramas

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2153]
**Welches Verhalten wird beobachtet?**
Der Geist von Naxxramas wirkt seine Fähigkeit "Schattenblitzsalve" nicht oder nur sehr langsam. 

**Wie sollte es sich verhalten?**
Der Geist von Naxxramas, welcher auch die Portale beschwört für die "Phantome aus Naxxramas", sollte gleich nach dem Pullen, in regelmäßigen Abständen die Fähigkeit "Schattenblitzsalve" wirken. 

**Schritte zur Reproduzierung**
Nach Naxxramas begeben und den Geist von Naxxramas pullen. Dann warten bis er die entsprechenden Fähigkeiten einsetzt.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Bitte berücksichtigen, das wir den Geist relativ zügig, auf Grund des Portals, getötet haben. Nach maximal 20 Sekunden, war der Gegner entsprechend tot. Hat jedoch nicht einmal die "Schattenblitzsalve" gewirkt gehabt.(Kein Kick) Bei entsprechend längerer Kampfdauer, kann es daher schon sein, das er die Fähigkeit einsetzen könnte. (Entsprechende Überprüfung)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npc:
https://datenbank.classic-wow.org/?npc=16449

Schattenblitzsalve:
https://datenbank.classic-wow.org/?spell=28407

Infos:
https://web-beta.archive.org/web/20061125184222/http:/wowwiki.com:80/Shade_of_Naxxramas
https://www.youtube.com/watch?v=QtyEoJ6_nZI&feature=youtu.be&t=44m33s

**Comment by Dotox** [comment]
Sind zusäzlich nun Stunbar.

Quelle: https://www.youtube.com/watch?v=cEsCSdp57d4&feature=youtu.be&t=980
