### ISSUE TITLE
[Naxxramas] Maexxna

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2154]
**Welches Verhalten wird beobachtet?**
Wenn Maexxna ihre Fähigkeit "Spinnennetz" wirkt, sollten alle Spieler im Areal 8 Sekunden lang betäubt werden. Jedoch können Jäger mit ihrer Fähigkeit "Totstellen" diese Betäubung umgehen.

**Wie sollte es sich verhalten?**
Die Fähigkeit "Spinnennetz" sollte auf alle Spieler wirken und nur durch folgende Fähigkeiten negiert werden sollen: 

- Wirklicher Tod eines Spielers
- Wenn sich ein Spieler im Kokon befindet (Web Wrasp)
- Gottesschild des Paladins 
- Verwendung der Steinflask (Flask of Petrification)

--_Cast every 40 seconds incapacitating everyone for 8 seconds, and dealing 1750-2250 Nature damage. This ability cannot be resisted, and the only way to avoid it is to be dead, have Flask of Petrification, have  [Divine Intervention], or be already incapacitated by Web Wra_p._--

**Schritte zur Reproduzierung**
Mit Jägerklasse zu Maexxna begeben und die Fähigkeit Totstellen einsetzen, whärend sie "Spinnennetz" wirkt.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Ich gehe stark davon aus, dass das System denkt, der Spieler sei wirklich tot und daher den Zauber nicht auf Jäger anwendet. (Systemabfrage)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt s**ein.

Npc:
https://datenbank.classic-wow.org/?npc=15952

Jägerfähigkeit:
https://datenbank.classic-wow.org/?spell=5384

Infos:
http://wow.gamepedia.com/Maexxna_(original)

**Comment by Dotox** [comment]
Top!

**Comment by SirBeansen** [comment]
Es ging aber nicht jedesmal. Habe es nur 1 von 3 mal hinbekommen :P. Man kann mit Totstellen auch heign dance umgehen.

**Comment by Baraz** [comment]
[It has been witnessed that with surgical timing Rogues (using Vanish) and Mages (with Iceblock) can avoid the Web Spray and continue to DPS her down during the final Web Spray when they would normally be immobilised. Also, since a Web Wrap takes a half second to be removed after it's been DPS'd down, a player can avoid Web Spray if timed correctly. ](http://wowwiki.wikia.com/wiki/Maexxna?oldid=392278) 
Die gleiche Mechanik sollte auch für Totstellen gelten, bin noch auf der Suche nach einer Videoquelle.

**Comment by Ryanstekken** [comment]
Dein Link bezieht sich auf die Wotlk-Version.

**Comment by Baraz** [comment]
Update: Totstellen habe ich nicht hingekriegt, kann am Timing gelegen haben. Eisblock, Vanish und Gottesschild haben jedoch, wenn vor Web Wrap genutzt, Immunität gewährleistet. Nach obiger Quelle ist das für Vanish/Eisblock korrekt, das Gottesschild sollte jedoch nicht funktionieren.
