### ISSUE TITLE
[Naxxramas] Verseuchter- / Steinhautgargoyle

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2155]
**Welches Verhalten wird beobachtet?**
Die beiden NPCs "Verseuchter Gargoyle" und "Steinhautgargoyle" setzen Ihre Fähigkeit "Steinhautform" nicht richtig ein. Sie setzen bei 30% ihres Lebens immer noch alle Fähigkeiten (Auto-Attack + Giftslave) ein, obwohl sie nun für 6 Sekunden anfangen sollten "Steinhaut" zu wirken. Wenn sie dann Steinhaut gewirkt haben, so erhöhen sie nur einmalig das Leben auf 100%. Danach, wenn man sie wieder bis 30% runterschlägt, setzen sie die Fähigkeit sehr fehlerhaft ein und heilen sich nicht mehr bis zu 100% hoch. (Teilweise 40% oder nur bis zu 70% geheilt)

**Wie sollte es sich verhalten?**
Die beiden Gargoyles sollten alle Fähigkeiten unterbrechen und sofort für 6 Sekunden "Steinhaut" casten, wenn sie nur noch 30% ihres Lebens besitzen. Dabei wird dann der Gargoyle 6 Sekunden lang Immun gegen sämtlichen Schaden und "Erstarrt" für den Zeitraum (Kein Autoattack + Salve). Zusätzlich heilt sich dieser auf 100% des Lebens wieder hoch. 

**Schritte zur Reproduzierung**
Nach Naxxramas begeben und die beiden Gegnertypen pullen. Dann bis 30% Leben runterhauen bis sie die entsprechenden Fähigkeiten einsetzt.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Es scheint so das die Fähigkeit nicht mehr richtig ausgeführt wird, wenn man ihn mehrmals auf 30% des Lebens bringt. Auch die Animation der Erstarrung fehlt teilweise.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npcs:
https://datenbank.classic-wow.org/?npc=16168
https://datenbank.classic-wow.org/?npc=16446

Fähigkeit: 
https://datenbank.classic-wow.org/?spell=28995

Infos:
http://wowwiki.wikia.com/wiki/Plagued_Gargoyle?oldid=306677

**Comment by Mafyo** [comment]
https://www.youtube.com/watch?v=Ri6naPfYHfs

**Comment by Dotox** [comment]
Hm, habt ihr ein Video? Ich kann davon überhaupt nichts reproduzieren :/

**Comment by Omegaexodus** [comment]
Ja haben wir gestern aufgenommen. Ich muss aber erst nachfragen, wer die Aufnahmen bei uns gemacht hatte. Kann ich dir aber wohl erst morgen dann zur Verfügung stellen.

**Comment by Herlot** [comment]
https://youtu.be/Olzvyf7ccso?t=1h21m23s
Schaut man links oben auf die Charakter-Avatar kann man sehen, dass trotz Versteinerung Autohits reinkommen. Das mit dem Gift konnte ich aber nicht beobachten.
