### ISSUE TITLE
[Naxxramas] Noth der Seuchenfürst

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2156]
**Welches Verhalten wird beobachtet?**
Noth setzt in regelmäßigen Abständen "Fluch des Seuchenfürsten" ein. Dieser Fähigkeit wurde mehrmals gestern von Spielern durch Schattenressi widerstanden. 

Noth setzt in regelmäßigen Abständen "Verkrüppeln" ein. Diese Fähigkeit wird direkt nach der weiteren Fähigkeit "Blinzeln" genutzt und zwar an dem Ort, wo er sich hinteleportiert hat. 

**Wie sollte es sich verhalten?**
Der Fähigkeit "Fluch des Seuchenfürsten" kann und sollte nicht mit Schattenressi widerstanden werden können. 

Die Fähigkeit "Verkrüppeln" sollte zwar direkt nach der Fähigkeit "Blinzeln" genutzt werden, aber muss dort angewandt werden, wo der Boss sich zuletzt befunden hatte. Das heißt das die Fähigkeit auf den Bereich verwendet wird, wo Noth sich vor dem "Blinzeln" aufgehalten hatte. (Bei dem Tanks und Melees entsprechend)

**Schritte zur Reproduzierung**
Nach Naxxramas begeben und Noth pullen. Dann warten bis er die entsprechenden Fähigkeiten einsetzt. Entsprechend viel Schattenressitenz tragen und warten bis man dem Fluch resistet. 

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

--_He will cast this every time he blinks, on those around where he blinks **FROM**, doing an AoE debuff that slows movement, attack speed, and strength by 50%. A priest/paladin should be assigned to remove this from the MT as soon as the Blink occurs_--

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npc:
https://datenbank.classic-wow.org/?npc=15954

Fähigkeiten: 
https://datenbank.classic-wow.org/?spell=29213
https://datenbank.classic-wow.org/?spell=29209
https://datenbank.classic-wow.org/?spell=29212

Infos:
https://web-beta.archive.org/web/20080129160534/http://www.wowwiki.com:80/Noth_the_Plaguebringer

**Comment by Ryanstekken** [comment]
Die Fähigkeit Cripple von Noth https://datenbank.classic-wow.org/?spell=29212 kann durch Vanish https://datenbank.classic-wow.org/?spell=1857 denke, dass diese Fähigkeit wirklich nur gereinigt werden sollte. Gegebenenfalls sollte man das geskillte Sprinten vom Schurken auch testen https://datenbank.classic-wow.org/?spell=13875 vermute dadurch, dass die Fähigkeiten Slow entfernen sollen auch Cripple entfernt wird.
Wird auch bei Omegas link nicht unter Counters gelistet https://web-beta.archive.org/web/20080201173257/http://thottbot.com:80/?sp=29212

**Comment by Baraz** [comment]
Wo ist in den Quellen die Information, dass man dem Fluch des Seuchenfürsten nicht widerstehen kann?

**Comment by Omegaexodus** [comment]
> Wo ist in den Quellen die Information, dass man dem Fluch des Seuchenfürsten nicht widerstehen können sollte?

Würde man in der Lage sein, Boss-Mechaniken mit Ressigear widerstehen zu können, so würden sehr viele Encounter absolut keinen Sinn mehr machen. Gerade bei Noth ist der Fluch eine elementare Fähigkeit, die zu einfach zum umgehen werde, wenn sie widerstanden werden könnte.

Mir selber fällt auch gerade kein anderer Boss ein, wo man eine grundlegende Fähigkeit mit Ressi-Gear verhindern kann. (Ausnahme die Breathtypen von den Drachen)

**Comment by Baraz** [comment]
Boss-Mechaniken und Resi-Gear? Ragnaros, Firemaw, Chromaggus, Skeram, Bug-Trio, Huhuran, Twins, Ouro, C'thun, Sapphiron, 4 Horsemen, Faerlina etc. oder zählen die alle nicht? Es mag ja gut sein, dass man gerade diesem Fluch nicht widerstehen können soll, aber generell wurden andere Bugreports in der Vergangenheit die mit der Argumentation "genereller Menschenverstand lässt darauf schließen, dass hier was inkorrekt ist" ohne Quellenangaben doch eher geschlossen.

**Comment by Dotox** [comment]
Bei allen Bossen aus Naxxramas steht auf WoWWiki explizit, dass man den Schaden einer Fähigkeit durch Resi reduzieren kann. Egal ob bei Faerlina, Sapphiron oder 4 Horsemen. Bei Noth steht diesbezüglich aber nichts und wenn man nun den von dir erwähnten Menschenverstand dazu zieht, wird einem klar, dass der Boss dadurch extrem einfach werden würde. Und das wäre mit Sicherheit damals aufgefallen und würde nun irgendwo stehen. Ich mein, bei anderen Bossen, bei denen das der Fall ist, steht es ja auch. BTT: siehe von @Omegaexodus.

Anderes Thema:
Dieses "LOL das war damals anders, rofl alles buggy xoxox" ist für die Entwicklung von Naxxramas extrem kontraproduktiv. Es kostet unheimlich viel Zeit, die heiße Luft, die da von manchen geäußert wird, zu überprüfen. Wer A sagt, muss auch B sagen können und damit meine ich, nachweise für die getätigte Aussage zu liefern und nicht nur ein Artikel, in dem das vielleicht so steht, in Videos und anderen Artikeln/Guides es aber völlig anders dargestellt wird. Nicht alles, was auf WoWWiki steht stimmt, wie Mafyo auch schon rausgefunden hat. Wir sind in Naxxramas gerade was die beiden offenen Flügel angeht, mittlerweile in einer Phase angekommen, in dem manche Mechaniken die da angewendet werden, wirklich so sein sollen und es kein Fehler ist, dass beispielsweise Acid Volley LOS ignoriert und ich nach Closed-Beta + 2 Wochen Open-Beta und unzähligen Tests immernoch von einigen höre, dass das besagte Beispiel flasch sei. Wenn man es anders in Erinnerung hat, alles kein Problem aber dann sucht verdammte Quellen und helft uns damit, Naxxramas zu verbessern. Wenn man darauf kein Bock hat, auf kein Ding, aber dann einfach die Klappe halten und den Leuten, die Naxxramas wirklich verbessern wollen, nicht auf den Sack gehen.

@Baraz der zweite Absatz ist nicht auf dich oder an irgendjemand anderes hier bezogen. Ich möchte das an dieser Stelle einfach mal gesagt haben, da es mich extrem stört, täglich Reports zu bekommen, die halt einfach keine Bugs enthalten weil die Leute nicht richtig recherchieren.
