### ISSUE TITLE
[Naxxramas] Boss Eingänge (Test raid 12.06) 

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2158]
Welches Verhalten wird beobachtet?
Die Boss Eingänge/Tore waren immer wierder verbuggt. Jedesmal als wir ein Boss gekillt haben war der Eingang danach zu, wobei während des Boss kampfes die Eingänge offen blieben. Auch nach einem Wipe blieben die Eingänge einfach zu, aber hatten sich nach einiger Zeit ressetet. 
Es war teilweiße einfach kein Muster zu erkennen. Bei Anub'Rekhan ging das Tor nach dem kill wieder auf, aber nicht sofort, während wir bei Faerlina und Noth eingesperrt wurden. 

Desweiteren konnten sich Mages durch die Spinnenweben, die den Raum im Kampf verschließen hindurch blinzen.

Wie sollte es sich verhalten?
-Die Tore sollten sich beim Boss pull schließen und beim wipe/kill wieder öffnen.

-Blink
Instant
Teleports the caster 20 yd. forward **unless something is in the way**. Also frees the caster from any bonds.

Schritte zur Reproduzierung
-Tja ich weiß nicht ob es sich mit einfachem Boss pullen schon getan hat um den Bug zu repoduzieren. Einer meinte mal dass sich das Tor geöffnet hatte als ein Hunter sich totgestellt hatte.

-Sich nah als Mage ans Tor stellen und durch blinken.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Noth: https: //datenbank.classic-wow.org/?npc=15954
Anub'Rekhan: https://datenbank.classic-wow.org/?npc=15956
Faerlina : https://datenbank.classic-wow.org/?npc=15953
Maexxna: https://datenbank.classic-wow.org/?npc=15952

Blink: https://datenbank.classic-wow.org/?spell=29208

**Comment by Dotox** [comment]
Ich hab fast alle Raids begeleitet und nur bei Anub gab es ein Problem weil man das Tor selbst anklicken konnte. Ich hab also keinen Schimmer, was oder wie ihr das angestellt hab, mehr Informationen dazu wären aber super :D Ich achte die nächsten Raids nochmal drauf.

**Comment by SirBeansen** [comment]
Oha, wir waren davon ausgegangen, dass es bei den anderen Raids auch so war und der Fehler bekannt ist. Deswegen haben wir nicht großartig drauf geachtet, wann das Tor öffnete und schließte.

**Comment by Dotox** [comment]
Ich denke ich hab einen möglichen Fehler gefunden.
