### ISSUE TITLE
[Naxxramas]Spinnen Trash

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2159]
Welches Verhalten wird beobachtet?
Wir haben eine Spinnengrupe direkt am Anfang des Flügels gemacht und haben uns erst um die Aasspinner und Schreckenskrabbler gekümmert, der Giftpirscher wurde um die Ecke getank LoS. Nachdem die kleinen Spinnen tot waren sind alle aus dem Kampf gekommen wobei der Schreckenskrabbler noch gelebt hatt

Wie sollte es sich verhalten?
Man sollte nicht aus dem Kampf kommen wenn sich noch ein Mob des selben Trashpacks am leben befindet

Schritte zur Reproduzierung
Einne Spinnengruppe Pullen und eine davon LoS von der Gruppe tanken

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15975
https://datenbank.classic-wow.org/?npc=15974#abilities
https://datenbank.classic-wow.org/?npc=15976#abilities

**Comment by Dotox** [comment]
Wenn du keinen Schaden an dem Mob gemacht hast, bist du nach dem Ableben eines anderen Mobs auch nicht im Kampf. Bei Bosskämpfen ist das allerdings anders.

**Comment by Mafyo** [comment]
ok
