### ISSUE TITLE
[Naxxramas] Versuechtergargoyle infight bug (Test raid 12.06) 

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2160]
Welches Verhalten wird beobachtet?
Wenn die Gargoyles zu Maexxna ihr Gift auf den Raid spucken wird man nicht in den Kampf gesetzt. Man kann einfach outfight bleiben, bekommt dennnoch den Schaden der Stacks.

Denke der gleiche Fehler wird auch bei den Steinhautgargoyle vorhanden sein.

Wie sollte es sich verhalten?

Man sollte durch offensiv attacken des Gegner infight geraten. Meißten reicht es auch einfach nur in seiner Nähe zu sein.

Schritte zur Reproduzierung

1 Spieler pullt den Gargoyle, während der andere nur die Spits frisst, ohne was zu tun.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Ich hatte jetzt kein video speziell zu den Gargoyles gefunden, aber in dem video kann man ab sekunde 30 erkennen, dass der Priest schon infight kommt bevor er sein shakle auf den Mob wirkt. 

https://www.youtube.com/watch?v=eR5wh1VMZ7o

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Steinhautgargoyle: https://datenbank.classic-wow.org/?npc=16168
Verseuchter Gargoyle: https://datenbank.classic-wow.org/?npc=16446

Acid Volley: https://datenbank.classic-wow.org/?spell=29325

**Comment by Dotox** [comment]
Er kommt infight, nachdem die Castbar auftaucht. Die Quelle ist also nicht wirklich hilfreich wie du schon sagtest, kann sich aber sehr gut um einen Fehler handeln.

**Comment by Herlot** [comment]
Hätte auch ein Video parat, was bestätigt, dass man die Salve abbekommt, ohne infight zu kommen. Ob das jetzt ein Bug ist oder nicht, kann ich leider auch nicht sagen. Quellen dazu zu finden, ist super schwer.

**Comment by Mafyo** [comment]
https://youtu.be/cEsCSdp57d4?t=1032 Der Rogue pullt, die Gargoyles setzen den Volley ein, Treffen den Raid(+combat), Rogue Vanished, Gargoyles fliegen zurück, alle aus dem Kampf(-Combat)

**Comment by Ryanstekken** [comment]
Das Video ist scheinbar weder von den Classicservern damaliger Zeit noch von Nefarian.
In dem Fall hier hat es sich bei uns gestern so verhalten, dass die Gargoyles den Gesamten Raid mit ihrem Spit getroffen haben, die Spieler aber nur während dem "Einschlag" nichtmal eine Sekunde infight waren und sofort wieder raus. Lediglich durch direkte Nähe/Attacken wurdest du in den Kampf versetzt.

**Comment by Mafyo** [comment]
das Video ist aus Classic bevor sie einen Boss Killen siehst du das Killdatum. Wollte damit nur zeigen das es sich so zu verhalten sollte
