### ISSUE TITLE
[Warlock] Eye of Kilrogg nicht verstohlen

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2161]
**Welches Verhalten wird beobachtet?**

Das Eye of Kilrogg ist nach dem Beschwören nicht verstohlen.

**Wie sollte es sich verhalten?**

Es sollte verstohlen sein.

**Schritte zur Reproduzierung**

Als Warlock den Zauber "Eye of Kilrogg" wirken.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Klasse Warlock

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Eye of Kilrogg: https://datenbank.classic-wow.org/?spell=126

**Comment by Slimmer2** [comment]
Quellen bitte

**Comment by stva23** [comment]
Meine Erinnerung wird wohl nicht zählen, aber vielleicht melden sich ja noch andere ehemalige WL Spieler zu Wort.

Im Webarchiv habe ich eine inwow.de Seite von 2005 ausgegraben: https://web.archive.org/web/20060625012047/http://wow.ingame.de:80/skills/show_skills.php?class=6&talent=0

Hier wird explizit von der Verstohlenheit gesprochen.  Auch in diversen Forenthreads die man noch aus dieser Zeit findet, wird auf die Verstohlenheit bezug genommen, z.b.: 
http://wow.allakhazam.com/forum.html?forum=21&mid=1110560639271554945 (Post Nr. 9)

**Comment by dagochen** [comment]
Der Stealth wurde entfernt. Die Frage ist wann genau. Wenn du dazu was findest, das auch noch erklärt, warum bei uns in der Tooltip des Spells schon geändert ist: https://datenbank.classic-wow.org/?spell=126

Dann kann man das nochmal aufmachen.

**Comment by stva23** [comment]
Das Auge hat heute noch Stealth, nur der Text wurde zwischenzeitlich gefixed.

Aber hinzugefügt wurde die Fähigkeit noch in der Beta, siehe: http://wowwiki.wikia.com/wiki/Patch_0.10 *(beim Unterpunkt Warlock)*
Habe mir auch alle Patchnotes bis 1.12.2 durchgesehen, kein Hinweis darauf, das es entfernt wurde (was sich auch mit meiner Erinnerung deckt).

**Comment by Dotox** [comment]
Vielleicht findest du ein Video von damals in dem man den stealth schon/noch sieht.

**Comment by Slimmer2** [comment]
http://wowwiki.wikia.com/wiki/Eye_of_Kilrogg?oldid=304248
Hier ein Link zum wowwiki

**Comment by Haudraufinix** [comment]
War das wirklich stealth, nicht unsichtbarkeit?

**Comment by Slimmer2** [comment]
Es war Stealth mit geringer Aggro range

**Comment by stva23** [comment]
Hier ist ein Video wo man das Stealth deutlich sieht (leider aus TBC): 
https://www.youtube.com/watch?v=Tm4tYTWOdaw

Hier aus Vanilla, wo man auch erkennen kann, dass es einen Stealh haben muss (sonst hätte es viel früher gepullt):
https://www.youtube.com/watch?v=YqYDn56mcyo

Und wie schon gesagt, die 0.10er Patchnotes erwähnen den Stealth effekt, daraufhin wird ein keinem weitern Patchnote erwähnt, dass der Effekt dazu oder weggekommen wäre.

**Comment by Slimmer2** [comment]
Aber wie schon erwähnt hat es eine geringe Aggrorange.
Die Videos hab ich auch gefunden, aber nicht angefügt

**Comment by dagochen** [comment]
Wieso wurde der Text dann geändert?

**Comment by dagochen** [comment]
Vermutlich dieser hier: https://datenbank.classic-wow.org/?spell=2585

**Comment by Slimmer2** [comment]
Ich les da was von Blitzstrahlpulver.
Ich teste das mal schnell
