### ISSUE TITLE
Zu viele Sklavenhändler der Dunkeleisenzwerge

### ISSUE THREAD

**Issue by Glenndun** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2162]
Welches Verhalten wird beobachtet?
Es sind extrem viele Zuchtmeister der Dunkeleisenzwerge auf einem Fleck.
Ich kann mir schlecht vorstellen, dass das gewollt ist.
Zumal man das als levelnder Spieler wohl kaum schaffen kann.

Wie sollte es sich verhalten?
Zuviele Zuchtmeister auf einem Fleck

Schritte zur Reproduzierung
Hinlaufen und anschauen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://puu.sh/wnmcI/59388f2ebb.jpg

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=5846

**Comment by Slimmer2** [comment]
[Sklavenhändler der Dunkeleisenzwerge](https://datenbank.classic-wow.org/?npc=5844) Diese NPC stehen dort.
Und was komisch ist, das die NPC an den anderen Orte einen Respawntimer von 8min 20 sek haben.
Und an den von dir gemeldeten Ort nur etwas über 1 Minute. Da stehen 7 von den NPC und die kann ein Spieler in den Levelbereich nicht alle alleine töten. 
Kann mir da fast vorstellen, wenn ich den 2ten NPC tod habe der Erste respawnt
