### ISSUE TITLE
Keep Stromgarde - Verhalten der Voidwalkerminions (Syndicate Conjuror's Minion)

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2165]
**Welches Verhalten wird beobachtet?**

1. Wenn der Meister stirbt, "unaggroen" die Voidwalker bis man sie erneut angreift. 
2. Wird der Voidwalker gebanished, wird nach dem Ablauf des Banish nicht der Warlock verfolgt, sondern der Voidwalker bleibt an Ort und Stelle. Dies führt auch dazu, dass der WL im Kampf bleibt (auch noch Minuten danach -> man muss zurück den Void töten, oder ALT+F4 (und Friedhof hallo)).

**Wie sollte es sich verhalten?**

1. Wie bei allen anderen Minions sollte der Voidwalker weiterhin den Spieler angreifen.
2. Nach dem Unbanish sollte der Voidwalker kurz den Spieler verfolgen und danach evaden (und der Spieler out of combat kommen).

**Schritte zur Reproduzierung**

siehe *Welches Verhalten wird beobachtet?*

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Getestet mit meinem Warlock, reproduzierbar. Für Tests ingame bin ich gerne zu erreichen (bitte Kontakt über Github E-Mail).

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Ich muss leider aus *wowhead.com* verlinken, da ich in der classic-wow DB keinen Eintrag gefunden habe. 

http://www.wowhead.com/npc=2590/syndicate-conjuror

**Comment by Baraz** [comment]
[Summon Voidwalker](https://datenbank.classic-wow.org/?spell=12746)
[Leerwandlerdiener](https://datenbank.classic-wow.org/?npc=8996)

Das sollten der Zauber und der NPC sein.

**Comment by stva23** [comment]
Jop, das sind sie, danke!
