### ISSUE TITLE
Tentakel Raid Party bei C´thun castet instant ihr "Blitzdingsi"

### ISSUE THREAD

**Issue by ocbalf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2167]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Wie sollte es sein?
Augententakel - http://datenbank.welli-it.de/?npc=15726

Diese beiden Mobs machen schon während des Spawns ihre Casts. Sprich,

die Augententakel um C'thun herum beschießen ihr Ziel bereits während des Spawnens.

Wie ist es?
Normalerweise fangen beide o. g. Mobs erst nach ca. 2 Sekunden an zu casten.

Links:
http://datenbank.welli-it.de/?npc=15726

Quelle:
Videos aus den Jahren damals zu finden ist verdammt schwer, da YT damals nicht so populär war.
https://www.youtube.com/watch?v=_j2S1d7Igy4
Augententakel - 2:22 Min

Vielleicht kann da noch einer was ergänzen, mit Kommentaren aus diesen Jahren. Aber da diese Mechanik damals einfach so war, wird das wohl keiner näher begründen.

Anmerkung:
Wir hoffen auf einen Fix. :-)

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Herlot** [comment]
#1364
