### ISSUE TITLE
Bungle in the Jungle - Droprate stimmt nicht

### ISSUE THREAD

**Issue by TheWreckingball** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2168]
Welches Verhalten wird beobachtet?

Der Questgegenstand hat nicht die korrekte Droprate.

Wie sollte es sich verhalten?

Laut der Datenbank von Classic-wow sollte sie wenigstens zu 8% droppen. Dies tut sie aber auch nicht. Die Droprate liegt bei ~1-2%

https://datenbank.classic-wow.org/?item=11837

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Questname (Englisch) Bungle in the Jungle
Im Süden Un'Goro

**Comment by Slimmer2** [comment]
Ein anderer privat Server ist keine gültige Quelle

**Comment by TheWreckingball** [comment]
Dann lösche ich die Angabe des von Vanillagaming. Aber die 8% werden definitiv nicht erreicht.

**Comment by stva23** [comment]
Hatte die Quest auch kürzlich, droprate kam mir passend vor. Bedenke, für 8% musst du eh schon um die 20 dieser Worker umhauen um auf ne Drapchance von ~20% zu kommen.

**Comment by dagochen** [comment]
Keine Angabe wie es sein soll -> Close
