### ISSUE TITLE
Nefarian Druid Call

### ISSUE THREAD

**Issue by pi7x** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2170]
Welches Verhalten wird beobachtet?
Wenn man bereits in Katzengestalt beim Druidencall ist dann wird man in Normalgestalt verwandelt und man kann sich danach weiterhin nach belieben in alle Gestalten verwandeln während des gesamten Calls.
Ich hab das bis jetzt nur als Feral Katze bemerkt ob man als Healer vor jedem Call kurz in Katze gehen kann damit man dann weiter heilen und entfluchen kann weiss ich leider nicht.

Wie sollte es sich verhalten?
Man sollte während des gesamten Calls in Katzenform gefangen sein unabhängig der aktuellen Form oder Skillung.

**Comment by Mafyo** [comment]
du musst  noch den druiden call von Nef, Nef Selbst und den Shapeshift des druiden verlinken

**Comment by pi7x** [comment]
ich wollt nur den bug melden was die devs damit machen ist ihr ding .... könnt es auch gerne ignorieren falls die form nicht gut genug ist

**Comment by pi7x** [comment]
Falls es wen interessiert gestern einen Try gehabt in dem alles legit war also man war während Druid Call in Katze gefangen. Aber auch einen Try in dem ich aus Katze in Normalgestalt geswitcht wurde im Call und dann weiter hin und her switchen konnte also den Bug hatte. 
Ich werde mal weiter probieren und bescheid geben falls ich ein System dahinter erkenne .....
