### ISSUE TITLE
C'thun Teleport in den Magen

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2171]
Welches Verhalten wird beobachtet?
Es kann vorkommen, dass wenn man von C'thun gefressen wird und in den Magen kommt, man nicht senkrecht nach unten fällt, sondern in eine Richtung fliegt. Falls man Pech hat und auf eine der "Inseln" landet, bekommt man Fallschaden.

Wie sollte es sich verhalten?
Wenn man in den Magen geportet wird, sollte man senkrecht nach unten fallen.

Schritte zur Reproduzierung
Bei der Reproduzierung bin ich mir nicht sicher. Meine Vermutung ist, dass falls man während der Fressen-Animation in Bewegung ist, man nicht senkrecht nach unten fällt. Richtig testen, konnte man das nicht.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Leider kein Video vorhanden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Kannst du das nächste Mal darauf achten, ob es immer noch passiert?

**Comment by Nifexx** [comment]
Klar. Danke für den schnellen Fix :)

**Comment by Nifexx** [comment]
Soweit ich das mitbekommen habe, lief heute alles top!
