### ISSUE TITLE
[Quest] Guardians of the Altar

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2172]
**Welches Verhalten wird beobachtet?**

Am Ende der Quest sollte man als Spieler auf den Alter klicken, wärend die Elfe einen Spell kanalisiert, das klicken ist nicht möglich, somit lässt sich die Quest nicht abschließen.

**Wie sollte es sich verhalten?**

Der Altar sollte klickbar sein.

**Schritte zur Reproduzierung**

Die Quest "Guardians of the Altar" erledigen

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Auf dem Screen leider nicht wirklich erkennbar, da kein Cursor dabei ist, aber der Altar ist eben nicht klickbar. Auch die Grafik ist eigentlich die, des schon aktivieren Altars. Es kann also auch sein, dass die Quest das erste mal funktioniert, und danach der Altar nicht resettet. Die 4 Fakeln, die man zuvor anzünden muss, funktionieren.

![quest_bug1](https://user-images.githubusercontent.com/29486255/27412335-3285d0e8-56f4-11e7-9d75-dfcf89800f99.png)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

https://datenbank.classic-wow.org/?quest=4901

**Comment by Baraz** [comment]
#867

**Comment by stva23** [comment]
Da die Quest doch relativ lange dauert, sollte man sie vielleicht komplett deaktiveren, bis sie gefixed ist. Oder im Questtext eine entsprechende Warnung einbauen.
