### ISSUE TITLE
Faules Holz - Questitem hat nicht die korrekte Droprate

### ISSUE THREAD

**Issue by TheWreckingball** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2175]
Welches Verhalten wird beobachtet?
Bin seit 1h beschäftigt Faule Holz für die Hexerq zu machen.

https://datenbank.classic-wow.org/?item=20613

Laut DB sollen 25% Dropchance geben. Aber dies ist nicht so.

Wie sollte es sich verhalten?

Sollte korrekt droppen, sonst wird die Q zu einem Alptraum.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Schau dir mal die Kommentare bei WOW Head zu den Item an. Die sind zwar nach Vanilla, aber könnten bei Classic auch so gewesen sein
http://www.wowhead.com/item=20613/rotting-wood

**Comment by stva23** [comment]
Ich hab die Quest letzte Woche erst gemacht, da hat sich die Droprate gefuehlt passend verhalten (genaue Statistik hab ich natürlich keine darüber geführt).

**Comment by dagochen** [comment]
Den Kommentaren zufolge ist unsere Dropchance zu hoch oder?
