### ISSUE TITLE
[Warlock] Pet bleibt nach "Flash Freeze" regungslos stehen

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2176]
**Welches Verhalten wird beobachtet?**

In den  Western Plaguelands trifft man auf Mobs Namens Eiskalter Ghul (Freezing Ghul). Dieser hat einen AoE Freeze-Spell. 

Wird das WL-Pet (getestet mit Voidwalker und Succubus) gefreezed, läuft der Mob zum Spieler. Sobald das Pet aus dem Freeze kommt (und von keinem anderen Mob geaggroed wird), bleibt dieses regungslos stehen. Erst ein erneuter Befehl seines Meisters lässt es wieder aktiv werden.

**Wie sollte es sich verhalten?**

Wie bei jedem anderen CC sollte das Pet weiter angreifen, sobald es aus dem Freeze kommt, bzw. zum Hexer laufen, sollte der Mob bereits tot sein.

**Schritte zur Reproduzierung**

In den Western Plaguelands den erwähnten Mob pullen, Pet freezen lassen (man selbst muss also weit genug weg stehen).

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

* Mob: https://datenbank.classic-wow.org/?npc=1796
* Spell: https://datenbank.classic-wow.org/?spell=16803

**Comment by Wosser** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1239

**Comment by stva23** [comment]
Danke für die Verlinkung, ist wohl das selbe Verhalten.
