### ISSUE TITLE
Auge des Wildtieres verbuggt?

### ISSUE THREAD

**Issue by hpiao2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2177]
Welches Verhalten wird beobachtet?
 Hallo,

Auge des Wildtieres scheint verbuggt zu sein oder nur bei mir nicht richtig zu funktionieren.
Folgendes Problem habe ich festgestellt:
Wenn ich mein Pet über genannten Skill an eine Posi stelle, und es dann auf "bleiben" stelle, mir AdW wegklicke - kommt mein Pet direkt wieder zu mir zurück - es sollte allerdings an der Posi stehn bleiben wo ich es ihm gesagt habe.
Gerade in Instanzen wo man zum Teil runter springen muss/möchte um Wege abzukürzen, muss man jedes Mal sein Pet einpacken und rufen, was jedes mal zur Folge hatt das es Zufriedenheit verliert.
Ist vllt keine große Sache aber viel mir halt auf, daher hier die Nachfrage.
Spell: https://datenbank.classic-wow.org/?spell=1002

**Comment by Haudraufinix** [comment]
Quellen:
https://www.youtube.com/watch?v=2JCusIVD0KU (Ohne Auge des Wildtiers, aber Pet rennt an die bleiben Position zurück
https://youtu.be/iN7XK8gE0R4?t=226
