### ISSUE TITLE
Quest:  Wütende Wildekin lässt sich nicht abschließen

### ISSUE THREAD

**Issue by TheWreckingball** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2178]
Welches Verhalten wird beobachtet?
Aufgabe der Quest ist es, so eine Kiste in den Sumpfgebieten zu finden & dort zu Quest abzugeben. Die Quest kann jedoch nicht abgegeben werden.
Nachdem man die Kiste angeklickt hat, "grüßt" sie einen nur.

Wie sollte es sich verhalten?

Die Quest sollte dort abgegeben werden & die Folgequest bereit stehen.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Die Quest bekommt man in Winterquell und muss in die Sumpfgebiete reisen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by stva23** [comment]
Wenn du

https://datenbank.classic-wow.org/?quest=6604/Wütende%20Wildekin

meinst: Diese und alle 3 folge Quests sind in Winterspring abzuschließen.

**Comment by TheWreckingball** [comment]
Das stimmt nicht,

laut Datenbank ist die 2. Quest bei der "Beschädigte Kiste" abzugeben (siehe https://datenbank.classic-wow.org/?quest=4861/W%C3%BCtende%20Wildekin)

und die 3. Quest bei der "Beschädigte Kiste" zu bekommen (siehe https://datenbank.classic-wow.org/?quest=4863/W%C3%BCtende%20Wildekin).

**Comment by stva23** [comment]
Steht doch in der ersten Zeile des von dir verlinkten Eintrages:

> Findet Jaron Steinschleifers ruiniertes Lager samt dessen Vorräte im südlichen Winterquell.

Und bei dieser Kiste kannst du die Quest auch abgeben.
