### ISSUE TITLE
[Naxxramas] Plagued Deathhound / Verseuchter Todeshund

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2183]
Welches Verhalten wird beobachtet?
Der Mob hat momentan 0 Rüstung und nutzt seine Fähigkeit "Forceful Howl" nicht.
 
Wie sollte es sich verhalten?
Der Mob sollte einen korrekten Rüstungswert (vermutlich ~4.6k, ähnlich wie die restlichen Mobs) haben und seine Fähigkeit, ein AoE-Knockback nutzen.

Schritte zur Reproduzierung
Im Spinnenflügel nicht zu Maexxna abbiegen sondern Hunde pullen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Plagued Deathhound: A Plaguehound that appeared in the Outer Ring. Did an AOE knock back howl. ](http://wowwiki.wikia.com/wiki/Changes_between_Patch_1.11_Naxxramas_and_Patch_3.0_Naxxramas) Der Mob wurde beim Wechsel von 1.11 zu 3.0 anscheinend rausgenommen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Verseuchter Todeshund](https://datenbank.classic-wow.org/?npc=16448)
[Forceful Howl](https://datenbank.classic-wow.org/?spell=30121) Deutsche Übersetzung dafür?

**Comment by Herlot** [comment]
Außerdem haben sie zu wenig HP. Da es die Mobs leider sehr selten gibt, gibt es auch kaum Einträge.
Eventuell kann man sich an den beiden Seiten orientieren. Aktuell 19k, tatsächlich sollten sie 69k haben.
[Link1](http://www.classicwow.com/database/?npc=16448) und [Link2](https://vanilla-twinhead.twinstar.cz/?npc=16448)
