### ISSUE TITLE
Swing timer wird bei procc´s nicht zurückgesetzt

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2187]
**Welches Verhalten wird beobachtet?**
Der Fix von #1798 hat nicht ganz geklappt.
Die Schlagsequenz mit mehreren Extrahits sind nach wie vor möglich (HoJ+Schwert+WF).
Der Swingtimer bei 2h Waffen wird nach wie vor nicht über Extrahits durch Fähigkeiten zurückgesetzt. 1h Waffen wurden von mir nicht getestet.

**Comment by SirBeansen** [comment]
Gleiche tifft wohl auch bei Schamanen WF vz zu (meine nicht das Totem). Machen bei einem WF procc 4 hits in folge anstatt nur 3. Aber habe ich noch nicht genau getestet. 

Eventuell hat jemand schonmal das gleiche beobachtet?

**Comment by Haudraufinix** [comment]
@SirBeansen
Sturmschlag zeigt Seinen Schaden oft erst beim nächsten Autohit an. Dadurch kanns gerne wie 4hits aussehen, aber es sind eigendlich nur 3+ n Style.
Ich setz mich heut Abend mal an den Rechner und mach n paar Schwünge

**Comment by testear** [comment]
https://www.youtube.com/watch?v=MVvl_x2CTrA

1:07 hat der Krieger einen Windfuryprocc folgend auf einen Schwertprocc.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/969

**Comment by Horim** [comment]
Hmm in dem Fall verwechsel ich Mehrfach-Procs mit Procs durch sich selbst, sorry.
Den entsprechenden Teil hab ich mal wieder rausgenommen. Der fehlende Swingtimer-Reset sollte jedoch tatsächlich (immer noch) falsch sein. Durch WW, Kniesehne und Execute werden beim Krieger nach wie vor zusätzliche Hits generiert ohne dabei den Swingtimer zu beeinflussen.

**Comment by testear** [comment]
Was du schreibst könnte auch sein. Ich wollte mich eigentlich eher auf den Report beziehen, dass durch einen Schwertprocc HoJ oder Windfury proccen können. Mit der Begründung, dass ein Procc auf den Schwertprocc erst zu 2.2.0 entfernt wurde.

**Comment by Haudraufinix** [comment]
Ich hab nun mal ein paar Swings gemacht mit Windfury Enchant (NICHT Totem). Dabei hatte ich tatsächlich gelegendlich Vierfachhits

**Comment by dagochen** [comment]
Kein Mensch kann sagen, welcher Proc durch welchen Hit in dem Video ausgelöst wurde. Genauso kann das bei uns auf dem Server auch keiner wirklich sagen, was zu erst da war: Windfury Proc oder HoJ Proc. 

Extra-Attacks werden mit Auto-Attacks "abgearbeitet" vom Server. Dadurch kommen die immer alle gleichzeitig. Das zurücksetzen in dem oben verlinkten Eintrag geschieht nur dann, wenn ein Proc von der Offhand ausgelöst wird. Für 2Hand-Waffen hat das also überhaupt garkeine Auswirkung. Mainhand-Swingtimer werden immer dann zurückgesetzt, wenn man damit zuhaut. Haue ich also mit meiner 2Hand-Waffe zu, wird sie zurückgesetzt. Löse ich dadurch einen HoJ-Proc oder Windfury-Proc aus, werden die mit abgearbeitet und der Timer dann zurückgesetzt. 

Sollte es der Fall sein, dass dieses Zurücksetzen des Swingtimers auch bei Procs von der Mainhand auftreten muss/soll, dann liegt tatsächlich ein Fehler vor. Aktuell war ich immer davon ausgegangen, dass nur Offhand-Procs den Swingtimer zurücksetzen, was auch erklärt, warum Schwertschurken mit Schwertspezialisierung Dolche in der Offhand genommen haben zu Classic. Kann das vllt jemand verifizieren, am besten durch Quellen, was nun korrekt ist?

**Comment by SirBeansen** [comment]
Also die procs auf Autoattacks scheinen ja einwandfrei zu funktionieren. 

Es geht ja um die Styles, das wenn man zb Kniesehne spamt ein Wf proc ausgelößt wird, dass dieser auch den Swing timer reseten soll.

Das bezieht sich jetzt auf Style WF procs:

Der Gwinn eines WF proc bei einem Schurken sollte sein das der Schlagtimer verkürzt wird, wenn dieser bereits bei der Hälfte ist. + der agnriffs bonus.
Und nicht das ein extra Hit ausgelößt wird und der Swing timer der Waffe unberührt bleibt.
 
Bei autoattacks funktionierts doch auch so, dass der Timer zurückgesetzt  wird.

--------------------------------------------------------------------------------------

http://roguecrap.blogspot.de/2006/05/more-on-sword-spec-modeling.html
(Sword spec proc is an normal mainhand attack and will cancel attack-in-motion and resets your MH attack timer.)

http://forums.elitistjerks.com/forums/topic/8508-hand-of-justice-understanding-this-trinket/?page=2
(Posted 29 Sep 2006 - patch 1.12
Basically HoJ resets your MH swing timer enabling one extra auto-attack (just like sword spec or windfury). The extra attack can proc a weapon enchant, just like a "normal" attack can. Your combat log just says you gain an extra attack through windfury/sword specialization/hand of jusice, then the next line of the combat log will have the normal autoattack sequence. There's nothing that identifies the extra attack as being any different from a normal autoattack. Because this is a normal attack, it can crit, miss, etc. and most importantly it is subject to glancing blows.


Aber ja was wirklich eindeutiges zu finden ist schon sehr schwer.

**Comment by pi7x** [comment]
Ich verstehe das Problem nicht ganz ... macht doch überhaupt kein Sinn das Procs den Swingtimer zurücksetzten da die ja rein theoretisch gar nicht zeitversetzt sein dürften.  Also so wie ich versteh bekommt man durch WF eben auf den Autohit oder Style ein bzw zwei extra Hits gleichzeitig und nicht nacheinander. Der Sinn der ganzen Procs ist doch einen Zusatzhit zu bekomen und nicht die Zeit zwischen zwei Autohits zu verkürzen.

**Comment by Haudraufinix** [comment]
Naja das hat schon Relevanz. Bei extra Swing Proccs auf einen Autohit gewinnst du 100% eines Zusatzhits. Das ist soweit auch korrekt. Bei Autohits funktionieren Proccs korrekt.

Drücken wir aber nun nem Krieger ne 3.8 Attackspeed Waffe in die hand, und lassen ihn Kniesehne spamen:
0:00 Autohit geht raus -> kein procc
0.10 Kniesehne geht raus -> kein procc
1.60 Kniesehne geht raus -> kein procc
3.10 Kniesehne geht raus -> procc. Hier sollte wegen dem Zusatzhits der Seingtimer vom Autohit zurückgesetzt werden
3.80 Zeitpunkt des nächsten Autos aif unserem Servers
6.90 hier sollte der nächste Autohit kommen.

Dieser Umstand führ dazu, dass gerade Krieger extrem in Wut schwimmen und Kniesehne spam eine der besten Schadenstaktiken auf Hordeseite ist.

Sinnigkeit des ganzen steht auf nem anderen Blatt, aber Quellen belegen, dass Proccs den Seingtimer resetten sollten

**Comment by Horim** [comment]
@dago das sollte auch bei MH Hits passieren. Im alten Report hatte ich das in einem Video bei whirlwind festgestellt bzw gezeigt. Unabhängig von MH und OH müssen extrahits in Classic den swingtimer reseten. Ich suche heute Abend nochmal die Stelle raus, wenn ich nichtmehr im Büro Hocke.

PS: nur weil es uns melees nerft sollten wir das Thema nicht als unwichtig deklarieren

**Comment by Horim** [comment]
@pi7x : der Sinn dahinter ist unwichtig. "Echte" extrahits würden erst mit tbc eingeführt und das hat in Classic nichts verloren. In Classic bedeutet extrahit das dein autohit vorgezogen wird und nicht 1 zusätzlichen Hit in deiner schlagsequenz. Ist zwar dämlich, aber wir reden hier von Classic ;)

**Comment by pi7x** [comment]
Hört sich ein bisschen an wie ein Bug den sie mit TBC entfernt haben den wir wieder einführen ;)
Bedeutet man müsste seine ganzen Styles immer direkt mit dem Autohit machen damit man kein Dmg verliert falls man einen proc bekommt. Wäre beim Shamie jetzt zB machbar aber beim Schurken fast unmöglich  ...

**Comment by Horim** [comment]
Das nennt sich komplexeres gameplay statt brainafk spammen ;-)
Spaß bei Seite, es war kein Bug und der "fix" sorgte für keine extrahit mehr auf Styles... Zumindest beim Krieger konnte wf nur noch auf autohit proccen xD

**Comment by pi7x** [comment]
Das war eh etwas worüber ich mich gewundert habe denn wortwörtlich bedeuten ja die Proccs eigentlich das man einen extra Hit bekommt nicht einen extra Autohit. Also man könnte es auch so verstehen das eine Kniesehne eine zweite Kniesehne auslöst nicht einen Autohit und MS einen zweiten MS zB das würd viel mehr Sinn machen und man bräuchte keinen Swingtimer reset aber ja wird sind bei blizzlike und nicht bei Logik.

**Comment by Horim** [comment]
Wir sind in Classic und nicht bei Logik und ATM hätten melees einen Vorteil den es in Classic nie gegeben hat

**Comment by Horim** [comment]
So, wieder einmal anhand des guten alten Georges: https://www.youtube.com/watch?v=apgkI-0tOB4
TF hat 1,9 Tempo und mit Flurry ca. 1,46 Sekunden. Man würde innerhalb von 3 Sekunden 3 Hits erwarten mit der Schlagsequenz:

- Hit (0 Sekunden)
- Hit (1,46 Sekunden)
- Hit (2,92 Sekunden)

Soweit ist erstmal alles frei von Videos oder Vermutungen.

Bei ca. 1:12 bis 1:15 kann man sehen, das WF durch ein Whirlwind ausgelöst wird und tatsächlich den Swingtimer resettet, da wir sonst 3 normale MH Swings sehen sollten. Zu sehen ist jedoch :

- Cleave parry (MH Swing) 1:12
- You gain 1 extra attack through Windfury Attack 1:13
- 207 MH Hit (43 blocked) <- Der WF-Hit 1:13
- 471 WW Crit <- der Auslöser, da das erste Cleave zu weit zurück liegt. 1:13
   (Man erkennt es auch daran das der WF-Procc im Video-Kampflog immer vor dem eigentlichen Auslöser auftaucht, vgl. #1798)
- 268 OH Crit 1:13
- Cleave 640+570 (MH Swing) 1:15

Es fehlt der MH Hit zwischen WW und dem Cleave. 
Es ist unmöglich, das ohne Swingtimer Debuff (TC/TF etc) ein Hit mit TF mehr als 2 Sekunden dauert!
Ausnahme: Der Swingtimer der Mainhand wird resetet.... oder übersehe ich hier etwas Fundamentales?

PS: Video mit 0,25x Tempo anschauen 

PPS: Dieses Verhalten hatte ich bereits in #1798 genau so erläutert, keine Ahnung wieso das untergegangen ist.

**Comment by 0815Priester** [comment]
Bitte such noch ein Video mit 2H raus, Danke.

**Comment by Horim** [comment]
Camio du bist ein Troll ;)

**Comment by Sabbaer** [comment]
push

**Comment by Horim** [comment]
Irgendeine Rückmeldung wäre schon nice, damit man sonst ggf. weitersuchen soll oder ähnliches.

**Comment by dagochen** [comment]
fix inc

**Comment by Horim** [comment]
Danke =)
Hoffentlich steinigen mich die Horde melees nicht =\

**Comment by Haudraufinix** [comment]
Is ja laut tag noch nicht live, kannst also noch weglaufen ;)

**Comment by Horim** [comment]
Auf die Gefahr hin noch mehr Hass auf mich zu ziehen:
Bei 2H Waffen konnte ich keinen Swingtimer-Reset feststellen, auf WF Proccs durch WW lief der Swingtimer normal durch. War jedoch nur ein MC-Fesselrun und dementsprechend kurz, von daher kann ich mich auch vertun.

Anderes Thema was jedoch direkt damit zusammenhängt:
Die _on-next-swing_ Attacken wie Cleave/HS sollten durch die Extrahits direkt ausgeführt werden, da der Extrahit nur ein vorgezogener Autohit ist. Andernfalls werden die Styles einfach durch Extrahits geschluckt und im "schlimmsten" Fall kann man diese Styles nicht ausführen, weil ständig Extrahits den eigentlich Autohit blockieren. Hab ich bislang jedoch nicht direkt getestet, da ich meine das der Fix nicht ganz geklappt hat.

Hat jemand schon DW diesbezüglich testen können?

**Comment by Horim** [comment]
Gibt's hier sonst schon was neues, bzw. Rückmeldung ob die Angaben ausreichen?
