### ISSUE TITLE
Buchband der Offenbarung

### ISSUE THREAD

**Issue by ralffechner** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2188]
Welches Verhalten wird beobachtet? Das Buchband der Offenbarung ist in Scholo gedroppt, der Paladin Viee, konnte den Buchband nicht sehen und auch nicht darauf würfeln, obwohl er Need hatte. Ich habe den Buchband mit Gier erwürfelt und noch in meinem Inventar (Char: Hrothga). Gibt es eine Möglichkeit dem Paladin den Buchband noch zukommen zu lassen?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Haudraufinix** [comment]
Meldet euch am besten über das ingame Ticket oder im Forum bei einem GM. Am besten mit einem Video oder Screenshots, welche das ganze belegen.

Der Bugtracker ist eher für Bugs im grösseren Sinne gedacht, nicht für individuelle "Schadensfälle"
