### ISSUE TITLE
[Naxxramas] Loatheb / Siegel des Lichts

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2191]
Welches Verhalten wird beobachtet?
Loatheb nimmt sich Siegel des Lichts runter.

Wie sollte es sich verhalten?
Loatheb sollte sich Siegel des Lichts nicht runternehmen.

Schritte zur Reproduzierung
Loatheb pullen, Siegel des Lichts richten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[It's important to have Judgement of Light or Poison Cleansing Totem active at all times since melee must save their consumables to recover damage taken from Inevitable Doom.](http://wowwiki.wikia.com/wiki/Loatheb?oldid=388190)

[Video, ab 0:37](https://www.youtube.com/watch?v=_hC1NYeBv18) wird Siegel des Lichts draufgesetzt und es fliegt nicht runter.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Loatheb](https://datenbank.classic-wow.org/?npc=16011)
[Siegel des Lichts](https://datenbank.classic-wow.org/?spell=20349) Rang 4

**Comment by Omegaexodus** [comment]
Bitte die gesamte Dispel-Mechanik von Loatheb überprüfen. Grundsätzlich sollte Loatheb nur "Flüche" alle 30 Sekunden runternehmen. Dazu zählen keine magischen Debuffs, Gifte oder Krankheiten.

Hier eine Übersicht zu den jeweiligen Debuffs: 

- Flüche (Nur diese sollten entfernt werden)
- Krankheiten
- Magie
- Gifte

https://web-beta.archive.org/web/20071220202456/http://www.wowwiki.com:80/Dispel_type

Fähigkeit die Loatheb anwenden sollte:

https://datenbank.classic-wow.org/?spell=30281

Beweise darüber das Loatheb nur FLüche entfernt: 

https://www.youtube.com/watch?v=2GPRS31bvl0  (ca. 28 sek)
https://web-beta.archive.org/web/20061230202305/http://www.wowwiki.com:80/Loatheb

**Comment by Dotox** [comment]
Dispel wird alle 30 Sekunden angewendet, wenn du was gefunden hast, mach einen neuen Report mit ensprechender Quelle und Videoverweis von einem Test auf.

**Comment by Dotox** [comment]
Ich kann das beschriebene leider nicht reproduzieren. Eventuell beim nächsten Test nochmal genau drauf achten.

**Comment by Baraz** [comment]
Ich konnte es in kleiner Gruppe auch nicht reproduzieren, wenn möglich ein 40er Allianz-Raid nochmal darauf achten.
