### ISSUE TITLE
[Naxxramas] Loatheb, Priesterfähigkeiten und Debuff

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2195]
Welches Verhalten wird beobachtet?
Die Zauber "Göttliche Pein", "Heiliges Feuer" und "Gedankenschlag" erzeugen fälschlicherweise den Silencedebuff "Gedankenverneblung".
Andere Zauber wie z.B. Schattenwort Schmerz, Verblassen, Psychischer Schrei, Inneres Feuer, Innerer Fokus, Levitieren erzeugen richtigerweise keinen Silence-Debuff.

Wie sollte es sich verhalten?
"Göttliche Pein", "Heiliges Feuer" und "Gedankenschlag" sollen den Silencedebuff "Gedankenverneblung" nicht auslösen.

Schritte zur Reproduzierung
Im Kampf gegen Loatheb o.g. Zauber anwenden und auf das Reseten des 1min-Timer achten (siehe auszugsweise für die wichtigsten Zauber die "Nefarian-Videobeweise").

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
In der Zeit, bis Heilpriester erstmals heilen, und während des Ablaufens des 1min-"Silence-Effekt" durch Gedankenverneblung verursachen Heilpriester mit Göttlicher Pein Schaden an Loatheb (siehe Forte-Video).
In der wowhead-Verlinkung ist aufgelistet, welche Zauber und Fähigkeiten beim Priester den Silence-Effekt auslösen. Dazu gehört als einziger Schattenzauber richtigerweise Vampirumarmung (siehe Raidasyl-Video).
Loathebs raidweiter Debuff und der Silence Effekt, der durch diesen ausgelöst wird, heißen beide gleich ("Corrupted Mind" bzw. "Gedankenverneblung"). Für beide Zauber gibt es jeweils klassenspezifische Zauber-IDs.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Loathebs Raidweiter Debuff (Priester!)
- Datenbank: https://datenbank.classic-wow.org/?spell=29185
- wowhead: http://de.wowhead.com/spell=29185

Silence Debuff "Gedankenverneblung" (Priester!):
- Datenbank: https://datenbank.classic-wow.org/?spell=29184
- wowhead: http://de.wowhead.com/spell=29184 (mit Auflistung, welche Klassenzauber den Silence auslösen)

Videobeweise von Nefarian:
- Gedankenschlag/Schattenwort: https://www.youtube.com/watch?v=4RNShsnGLhA
- Göttliche Pein: https://www.youtube.com/watch?v=ym8pNlAm8zw
- Untote fesseln: https://www.youtube.com/watch?v=HfxewQbHvGo

Videobeweise aus Classic bzw. mit "Classic-Naxx":
- "Forte Video": https://www.youtube.com/watch?v=_hC1NYeBv18
(Original von 30.08.2006, via: http://www.warcraftmovies.com/movieview.php?id=26767)
- "Raidasyl-Video": https://www.youtube.com/watch?v=GeyR4Hi97Is
(darin erkennbar, inbs. bei verlangsamtem Wiedergabetempo: nur beim Wirken von Vampirumarmung wird der Silence Debuff ausgelöst bzw. erneuert; Gedankenschlag oder Gedankenschinden lösen den Effekt nicht aus)

**Comment by Dotox** [comment]
Die wowhead verlinkung ist nicht classic spezifisch. vielleicht findet man da noch etwas besseres von damals diesbezüglich

**Comment by Baraz** [comment]
Dann mache ich #2192 mal zu, dort ist nur Smite reportet.
