### ISSUE TITLE
Quest Feuerverzauberungen ( https://datenbank.classic-wow.org/?quest=706 )

### ISSUE THREAD

**Issue by fadd** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2196]
Welches Verhalten wird beobachtet?
Das Quest-Item https://datenbank.classic-wow.org/?item=4612 droppt schlichtweg nicht.
Wie sollte es sich verhalten?
Das Quest-Item https://datenbank.classic-wow.org/?item=4612 sollte droppen!
Schritte zur Reproduzierung
Einen beliebigen Questmob https://datenbank.classic-wow.org/?npc=2725 (Welpe) oder https://datenbank.classic-wow.org/?npc=2726 (Drache) killen. Laut Db sollen sie eine 100 % Chance haben
https://datenbank.classic-wow.org/?item=4612 (Schwarzdrachenherz) zu droppen.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Ich habe es ungefähr 45 Minuten lang veruscht zu farmen. Sowohl die Elite als auch die Non-Elite. Es waren circa 100 Mobs. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
https://web.archive.org/web/20060524072621/http://wow.allakhazam.com:80/db/item.html?witem=4612
