### ISSUE TITLE
Rar encoding drops executable flag for macos release

### ISSUE THREAD

**Issue by yogo1212** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2197]
Hey :-)

Your release is shipped as a rar archive which doesn't preserve executable permissions on the application binary.

A workaround is to go into the unpacked directory, navigating through the `Word of Warcraft.app`, `MacOs`, and `Content` folders, and setting the permission manually using `chmod +x World of Warcraft`.

Maybe you could switch to .tar.gz?

**Comment by stva23** [comment]
At least with my linux version of rar i can create archives preserving unix file permissions. Those archives are also compatible with windows rar and 7zip. So there is no necessity for using .tar.gz (although its the standard unix way, its sometimes problematic for windows users).

**Comment by yogo1212** [comment]
is it important that windows users can extract the macos release?
if you can set the executable flag in a way that it's preserved during extraction on macos, it should be easy to just fix the rar file you already have (don't know about whether you have a release process).

otherwise, you COULD put a shell script `cd "$(dirname "$0")" ; chmod +x World\ of\ Warcraft.app/../World\ of\ Warcraft` in the instructions-file to drag'n'drop into a terminal. that is assuming that the macos release is archived on a windows machine where the executable can't be included.
