### ISSUE TITLE
Kreischergeister lassen sich zu oft beschwören

### ISSUE THREAD

**Issue by weedlord100** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2198]
**Welches Verhalten wird beobachtet?**
Wärend der quest "Kreischergeister" muss man aus den Leichen ihren Geist beschwören, dies kann man an einer Leiche So oft tun bis die Quest fertig ist

**Wie sollte es sich verhalten?**
Aus einer Leiche Sollte nur ein Geist beschwörbahr sein

**Schritte zur Reproduzierung**
Die quest "Kreischergeist" in Tanaris annehmen, in Feralas einen Talkreischer Töten und das quest Item mehrfach einsetzten

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
-

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?npc=5307
https://datenbank.classic-wow.org/?quest=3520/Kreischergeister
https://datenbank.classic-wow.org/?item=10699

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1894
Wurde bereits gemeldet

**Comment by weedlord100** [comment]
mein fehler sry beim suchen nich gesehen :(
