### ISSUE TITLE
Hügel von Razorfen: Tuten'kash

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#220]
Es geht um folgenden NPC: http://datenbank.welli-it.de/?npc=7355

Er ist Teil eines Events, dass zur Zeit überhaupt nicht funktioniert. Nach dem Schlagen des Gongs  (http://datenbank.welli-it.de/?object=148917) despawnt dieser einfach und nichts passiert.
Was passieren sollte:
Beim ersten Schlagen des Gongs spawnt eine Welle aus 8 Grabscheusalen (http://datenbank.welli-it.de/?npc=7349) an den Zugängen zum Bossraum.
Nachdem alle Mobs tot sind, kann man den Gong erneut schlagen und eine zweite Welle aus 4 Grabmalhäscher (http://datenbank.welli-it.de/?npc=7351) spawnt an den Zugängen. Nachdem die Welle erledigt ist, kann man den Gong ein drittes mal schlagen und der Boss selbst erscheint in der Mitte des Raums.
Der NPC ist gerade wegen den droppenden Handschuhen auch für lvl60er interessant.

**Comment by Archidamos** [comment]
Kann ich bestätigen

**Comment by g3n3a** [comment]
#220
#525
