### ISSUE TITLE
Verteidiger des Anubisath - Immun gegen eigene Feuer Explosion

### ISSUE THREAD

**Issue by Rashick** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2200]
Welches Verhalten wird beobachtet?
Dass beim Trash in AQ40 nach Huruan die Verteidiger des Anubisath ab und an gegen ihre eigene Explosion immun zu sein scheinen. 

Wie sollte es sich verhalten?
Naja... Explosion sollte bedeuten, dass die sterben oder nicht?

Schritte zur Reproduzierung
Das ist  uns leider nicht möglich...

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Noch nicht, bei bedarf werden wir das noch versuchen nachzuliefern!

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Herlot** [comment]
https://datenbank.classic-wow.org/?npc=15277 anubisath

**Comment by Rashick** [comment]
Ich glaube es müsste folgender Zauber sein:
 https://datenbank.classic-wow.org/?spell=25698

**Comment by Nifexx** [comment]
Das scheint aber auch bei anderen Mobs aufzutreten. Z.B bei den Twins, kann es passieren, dass die kleinen Käfer explodieren, danach aber noch weiterleben. Vielleicht gibt es da Parallelen, könnte man sich mal anschauen.

**Comment by Ryanstekken** [comment]
Die Verteidiger fallen momentan seit Patch einfach instant um und die Explosion passiert nicht mehr.

**Comment by Dotox** [comment]
Hab nochmal was geändert, ist auf Nef.

**Comment by Nifexx** [comment]
PUSH. Wie schön erwähnt ist das ein generelles Problem. Die Wächter in AQ20 können ihrer Explosion, genauso wie die Käfer bei den Twins, immernoch widerstehen!

https://datenbank.classic-wow.org/?npc=15355 (müssten die AQ20 Mobs sein)

https://datenbank.classic-wow.org/?npc=15316 (müssten die Mobs bei den Twins sein)
https://datenbank.classic-wow.org/?npc=15317
