### ISSUE TITLE
[Warlock] Enslave Demon - Dämon bleibt nach Hexertod

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2201]
**Welches Verhalten wird beobachtet?**

Wenn der WL mit "Enslave Demon" einen Dämon versklaved und danach stirbt, bleibt der Dämon neben dem toten Hexer. Wird der Hexer rechtzeitig (wärend der Dämon noch versklaved ist) wiederbelebt, dient der Dämon weiterhin an seiner Seite.

**Wie sollte es sich verhalten?**

Nachdem der WL gestorben ist, sollte der Dämon resetten und an seinen Ausgangspunkt zurücklaufen.

**Schritte zur Reproduzierung**

Als WL einen Dämon versklaven und sterben.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Von mir in Winterspring an verschiedenen stellen / Dämonen getestet

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

https://datenbank.classic-wow.org/?spell=11725

**Comment by stva23** [comment]
Gerade getestet, leider nicht ganz (jaja ich hab nen Dämonenfetisch): Der Dämon resettet zwar, bekämpft aber weiter andere Mobs. Bei Elitedämonen (und nur da macht der Spell eigentlich Sinn) kann das schon eine Zeit lang dauern, wärenddessen bleibt man auch im Kampf was zusätzlich lästig ist.

**Comment by Dotox** [comment]
Hast du es genau so gemacht, wie du es oben beschrieben hast? Welchen Mob und wo genau?

**Comment by stva23** [comment]
In Winterspring in der Darkwhisper Gorge. Ich weiß jetzt nichtmehr ob ein Slyer oder ein Initiate war, aber einen der beiden habe ich im Eingangsbereich versklaved und bin dann nach hinten. Ich bin gestorben, der Mob hat fröhlich weiter gekämpft und ist nicht resettet. Ich habe den SS genutzt, der Dämon war zwar feindlich geflagged und ich hatte auch keine Kontrolle, aber ich war direkt infight, bis er gestorben ist.
