### ISSUE TITLE
[Naxxramas] Maexnna

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2203]
**Welches Verhalten wird beobachtet?**
Wenn Maexxna ihre Fähigkeit "Spinnennetz" wirkt, sollten alle Spieler im Areal (200 Yards) 8 Sekunden lang betäubt werden. Jedoch können bis zu 4 verschieden Klassen mit ihren Fähigkeiten diese Betäubung umgehen.

Dazu zählen vor allem: 

- (Immer noch) "Tot stellen" vom Jäger
- "Eisblock" vom Magier
- "Vanish" vom Schurken
- "Gottesschild" vom Paladin

**Wie sollte es sich verhalten?**
Die Fähigkeit "Spinnennetz" sollte auf alle Spieler wirken und nur durch folgende Fähigkeiten negiert werden sollen:

- Wirklicher Tod eines Spielers
- Wenn sich ein Spieler im Kokon befindet (Web Wrasp)
- Göttliches Eingreifen des Paladins (Opferfähigkeit)
- Verwendung der Steinflask (Flask of Petrification)

--Cast every 40 seconds incapacitating everyone for 8 seconds, and dealing 1750-2250 Nature damage. This ability cannot be resisted, and the only way to avoid it is to be dead, have Flask of Petrification, have [Divine Intervention], or be already incapacitated by Web Wra_p.--

**Schritte zur Reproduzierung**

Entsprechende Klasse bei Maexxna testen. Genau in dem Moment, wo Maexxna (Timer) die Fähigkeit "Spinnennetz" einsetzt, versuchen mit der Klasse den Effekt zu negieren.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

_It has been witnessed that with surgical timing Rogues (using Vanish) and Mages (with Iceblock) can avoid the Web Spray and continue to DPS her down during the final Web Spray when they would normally be immobilised. Also, since a Web Wrap takes a half second to be removed after it's been DPS'd down, a player can avoid Web Spray if timed correctly._ 

Es gibt zwar Hinweise darauf, das man Eisblock und Vanish benutzen können sollte, um den Effekt in genau der richtigen Sekunde zu negieren, jedoch ist es schwer zu sagen, ob dies überhaupt von Blizzard so beabsichtigt war? Grundlegend, sollte es wohl von niemanden möglich sein, die Fähigkeit zu umgehen. 

Hier stellt sich die Frage, ob es überhaupt von der Mechanik möglich ist, solche Fähigkeiten (Effekt) von den Klassen zu negieren, damit sie "Spinnennetz" nicht umgehen können.

Und es stellt sich die Frage, ob wir es nicht grundsätzlich verbieten sollten, solche Fähigkeiten zum avoiden von der Fähigkeit "Spinnennetz" zu nutzen. Das gilt genauso für "Göttliches Eingreifen", da die Allianz durch diese einzigartige Fähigkeit einen enormen Vorteil während des Kampfes erhält. 

Zusätzlich muss man bedenken, dass das Einsetzen dieser "Avoid"- Fähigkeiten, schlussendlich zum Classstacking führen könnte, da Schurken, Magier und Paladine einen enormen Vorteil gegenüber anderen Klassen in der letzten Phase (ab 30%) hätten.

Leider fehlen hier wirklich deutliche Informationen. Ich denke man kann sich nicht direkt auf Wowwiki von 2006 verlassen. Nach ca. gefühlten 50 Videos, habe ich das Gefühl, das wohl nur Schurken, dies erfolgreich verhindern konnten mit Vanish. (Anderes konnte ich nicht beobachten, weder Magier noch Paladine --> Weitere Recherche nötig)

https://www.youtube.com/watch?v=JYR3VlLlEcI ( ~ ca. 3:57 sieht man den Schurken aus stealth kommen und rumhüpfend auf Maexxna schlagen)

Was demnach nach meiner Recherche nicht funktionieren soll ist: 

- Tot stellen soll 100% nicht funktionieren 
- Eisblock sollte nicht funktionieren (nicht 100% sicher)
- Gotteschild sollte nicht funktionieren  (Selbe Effekt wie Iceblock vom Mage)

https://www.youtube.com/watch?v=lSJvCR2bjzc  (~ ca. 2:30 / 3:58 sieht man das Eisblock wohl nicht funktionieren sollte für die Netzphase, wenn anderer Beweis für Eisblock gebracht werden kann, bitte korrigieren)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Npc:
https://datenbank.classic-wow.org/?npc=15952

Jägerfähigkeit:
https://datenbank.classic-wow.org/?spell=5384

Magierfähigkeit: 
https://datenbank.classic-wow.org/?spell=27619

Schurkenfähigkeit: 
https://datenbank.classic-wow.org/?spell=27617

Paladinfähigkeit:
https://datenbank.classic-wow.org/?spell=19752 (Göttliches Eingreifen)
https://datenbank.classic-wow.org/?spell=642 (Gottesschild)

Infos:
http://wow.gamepedia.com/Maexxna_(original)

https://web-beta.archive.org/web/20061113104104/http://wowwiki.com/Maexxna

https://web-beta.archive.org/web/20080716011107/http://www.wowhead.com:80/?npc=15952

https://web-beta.archive.org/web/20071112224408/http://www.wowhead.com:80/?spell=29484

Verlinkung zu bereits vorhandenem Issue: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2154

**Comment by SirBeansen** [comment]
So hier nochmal die Hunter Sicht: https://www.youtube.com/watch?v=Aujcx3-rj2Q&feature=youtu.be

Also ist habs immer wieder versucht während des Testes, und es nur dieses eine mal hinbekommen. 
Schattenhaftigkeit hab ich jedes mal benutzt, also kann es daran nicht liegen. 
Aber bei dem try hatte ich zum ersten mal ein Naturschutztrank drin. Man sieht auch das ich den Spinnennetzt absorbiere. Eventuell liegt dadrin der Fehler.

Hatte leider auch vergessen zu testen, ob man mit Schattenhaftigkeit sowie einem NR pot, als Nachtelfen heiler das Netz auch umgehen kann.

**Comment by Dotox** [comment]
Ich lass das Thema mal offen, eventuell gibt es über die Tests hinaus noch weitere Informationen.
