### ISSUE TITLE
[Naxxramas] Portale am Ende jedes Flügels (Endboss)

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2204]
**Welches Verhalten wird beobachtet?**
Wenn man die Portale (Augen) am Ende jedes Flügels benutzt, wird man zwar erfolgreich zum Eingang geportet, jedoch nicht die Begleiter und Pets mehrerer Klassen. (Jäger, Hexenmeister)

Die Begleiter rennen danach sofort durch die gesamte Instanz zum Eingang und triggern sämtliche Trashmobs auf dem Weg dorthin. Zusätzlich kommen dann mehrere Spieler nicht mehr aus dem Kampf und müssen sich töten lassen, da die Npcs durch die Begleiter nicht mehr resetten.

**Wie sollte es sich verhalten?**
Wenn man die Portale bei den Endbossen benutzt, sollten auch alle Begleiter teleportiert werden, um weitere Infigth-Probleme zu vermeiden.

**Schritte zur Reproduzierung**
Zu den Portalen gehen mit Begleiter und sich teleportieren lassen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Infigth-Bug + Triggern sämtlicher Trashmobs durch Begleiter

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Keine Verlinkung vorhanden, da Objektnutzung von grafischen Elementen innerhalb von Naxxramas.

**Comment by Dotox** [comment]
Ist mir auch schon aufgefallen, danke!
