### ISSUE TITLE
[Naxxramas] Maexxna - Web Wrap

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2207]
Welches Verhalten wird beobachtet?
Man erhält momentan ~1.1k Naturschaden pro Tick im Web Wrap.

Wie sollte es sich verhalten?
Man sollte weniger Schaden pro Tick erhalten (650-850).

Schritte zur Reproduzierung
Maexxna pullen und sich an die Wand kleben lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[When encased, 650 to 850 Nature damage is done every 2 seconds.](http://wowwiki.wikia.com/wiki/Maexxna?oldid=392278)
[734 pro Tick, erkennbar im Portrait unten links](https://youtu.be/F6cNdwEpN00?t=305)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Maexxna](https://datenbank.classic-wow.org/?npc=15952)
[Web Wrap](https://datenbank.classic-wow.org/?spell=28622)

**Comment by Dotox** [comment]
Hey,

das ist aktuell gewollt. Ich experimentiere hier, da mit einer Flask die Mechanik zum Witz wird.

**Comment by Baraz** [comment]
Das habe ich mir schon gedacht, jedoch halte in einen Anstieg um mehr als 50% mehr Schaden nicht vergleichbar mit flat 1200HP zusätzlich. Aber da wird sich sicherlich ein vernünftiger Wert finden lassen.
