### ISSUE TITLE
Aggroverlust des Tanks bei Weltdrachen [Movement]

### ISSUE THREAD

**Issue by Throndar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2208]
**Welches Verhalten wird beobachtet?**
Sehr selten verliert der Tank bei den vier Smaragddrachen unvorhersehbar beim Pull die Aggro. 
**Wie sollte es sich verhalten?**
Der Tank sollte nicht aus der Aggroliste fliegen.
**Schritte zur Reproduzierung**
Bisher nichts gefunden, was den Aggroverlust auslöst. Bei den letzten ca. 100 Weltdrachen ist das Problem zwei Mal in Feralas aufgetreten, bei Ysondre und Lethon.
_**Edit:** Scheint mit den verschiedenen Movementtypen zusammenzuhängen, dass die Drachen nicht über bestimmte Kanten laufen können. Zur Vermeidung nicht über die Rampengeländer laufen._
**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
https://youtu.be/PnmekSwxX28

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Ysondre - https://datenbank.classic-wow.org/?npc=14887
Lethon - https://datenbank.classic-wow.org/?npc=14888
Smariss - https://datenbank.classic-wow.org/?npc=14889
Taerar - https://datenbank.classic-wow.org/?npc=14890

**Comment by Dotox** [comment]
Benötigen hier mehr Input

**Comment by Throndar** [comment]
Die erhöhten Rampengeländer haben am unteren Ende eine Kante, über die die Drachen im Kampf nicht drüberlaufen können. Dies fällt besonders in Feralas auf, da die Rampe dort sehr kurz ist. Springt der Tank beim Pull auf das Geländer und von dort aus auf den Boden verfolgt der Drache ihn über das Geländer bis unten, dort bleibt er dann hängen (siehe Video, Tank bewegt sich zur rechten Säule, Drache verliert Angriffsanimation). Gelingt es ihm nicht in Meleerange des Tanks zu kommen ignoriert er ihn (schmeißt ihn aus der Aggroliste) und verfolgt dann das nächste Ziel in der Aggroliste. Laut Dago gibt es verschiedene Bewegungsarten von NPCs die auch verschieden programmiert sind. Im "Verfolgungsmovememt" kann er über diese Kante hinweg (siehe Video), im "Combatmovement" nicht.

**Comment by weedlord100** [comment]
https://www.youtube.com/watch?v=j47i9PznZAI

reset 2ma auf Video von 5ma vor 7tagen bei taerar
