### ISSUE TITLE
Loatheb Sporen aus verschiedenen Ecken

### ISSUE THREAD

**Issue by Anorhin-Alane** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2209]
Welches Verhalten wird beobachtet?
Im Bossfight bei Loatheb hatten wir erst Random die Sporen aus den Ecken statt einer Ecke.
Steht Loatheb genau in der Mitte auf dem grünen Teppich haben wir aus gar 4 Sporen Ecken Spawn.
Nachdem wir Loatheb vom grünen Teppich etwas zur Seite bewegt hatten, haben wir "nur" noch aus zwei Ecken die Sporen Spawns bekommen.

Wie sollte es sich verhalten?
Sporen kommen in Classic Vanilla nur aus einer Ecke, Spawnen Loateheb im Rücken, auf der kürzesten Seite.

Beispiel aus Vanilla Zeiten:
https://www.youtube.com/watch?v=hGIDu6_9E0w
https://www.youtube.com/watch?v=kF-rAvoOV7k
https://www.youtube.com/watch?v=bMWKNeIISmo

Erst in WOTLK kommen Sporen aus zwei Ecken.

Schritte zur Reproduzierung
Loatheb Pullen,, eventuell im Raum mooven und an verschiedenen Spots tanken.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Video (Privat an Dotox) per PN.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16011

**Comment by Mafyo** [comment]
also meine Theorie ist das Loatheb 2 spawns hatt an jeweils seiner beiden Beine Links und Rechts schräg hinter ihm, je nachdem wie loatheb jetzt gezogen wird verschiebt sich der Spawnpunkt und sie spawnt immer auf der Seite wo die mesiten Spieler stehen. Das einzige was bei wiki steht ist das: ''on the opposite side of the room from the majority of the raid/Loatheb''. Kannst du das belegen das es immer die kürzeste Seite ist? im 3ten Video ist die kürzeste Seite aber dann genau gegenüber des Raids oder?
Ich blick dort momentan auch nicht wirklich durch....

**Comment by Dotox** [comment]
Ich versteh es aktuell leider auch nicht, da es unterschiedliche Quellen in der Closed-Beta und nun Open-Beta gibt. Daher lass ich es nun so wie es ist und ändere es im Verlauf der Beta nochmal, wenn die Sache etwas klarer ist.

**Comment by Haudraufinix** [comment]
Ausm Dungeoncompanion Vol2 der BC und Naxx umfasst:

> Loathebs Position ist wichtig. Abhängig davon, wo er sich aufhält, erscheinen die Sporen an einem bestimmten Ort. Tanken sie ihn in der nordöstlichen Ecke der Plattform in der Mitte des Raums. Dadurch erscheinen die Sporen in der Südwestlichen Ecke des Raums. Umgekehrt erscheinen sie in der Nordwestlichen Ecke, wenn sie ihn in der Südöstlichen Ecke tanken. Beide Positionen sind Ideal
