### ISSUE TITLE
Quest Der Weg des Jägers für Stufe 10

### ISSUE THREAD

**Issue by Jolaana** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2210]
Was wurde beobachtet?

Die Quest wird gemacht in Dolaanar und besteht aus 3 Teilen: 
- zuerst muss man eine Spinne zähmen, 
- danach einen Pirscher 
- und schlussendlich einen Kreischer. 
Mit jedem dieser gezähmten Tiere muss man zurück zum Questgeber gehen und die Quest abgeben um die Folgequest zu erhalten. 

Das Problem ist: ich bekam jedes mal nach dem Abgeben der Quest einen Disconnect und bin gestorben - beides nahezu gleichzeitig.

All das wurde von einem Gruppenmitglied beobachtet - er erhielt die Disconnect Meldung, sah mich sterben (nicht durch eine Fremdeinwirkung! Ich bin einfach umgefallen) sowie mein gezähmtes Tier böse werden und hat beobachtet wie es von einer Wache getötet wurde. 

Lg
Jola

**Comment by Haudraufinix** [comment]
Bei der Quest handelt es sich um die Nachtelfenversion:
https://datenbank.classic-wow.org/?quest=6073

Der Tod wird wohl auftreten, da man sich wärend der Questdauer mit dem Pet dauerhaft im Kampf befindet und bei DCs im Kampf automatisch stirbt.
Der DC dürfte das einzige Problem sein
