### ISSUE TITLE
Blizzard macht kein Schaden

### ISSUE THREAD

**Issue by humpalum** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2211]
Welches Verhalten wird beobachtet?
Beim Cast von Blizzard kommen keine Schadenszahlen auf, Gegner bekommen auch keinen.
Kommt so ungefähr bei einem von zwei Casts vor.

Wie sollte es sich verhalten?
Blizzard sollte Schaden verursachen.

Schritte zur Reproduzierung
Bin mir nicht sicher wie das 100% Reproduzierbar ist. 
Aber so im allgemeinen ist es ein simpler Cast von Blizzard, nur dass er immer wieder keinen Schaden macht.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
WDB Ordner gelöscht.
Video wird nachgereicht. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=10185

Ist das Problem in irgendeiner Weise bekannt und es gibt schon eine Lösung dafür? Bin ich der Einzige der das Problem in der Form hat?

**Comment by Slimmer2** [comment]
Tritt das Problem in Gruppe/Raid auf oder wenn du solo unterwegs bist.
Wenn in Gruppe/Raid benützt du den höchsten Rang wie die anderen Magier?

**Comment by humpalum** [comment]
Wir waren zu zweit. Der andere Magier hat den höchsten Rang genutzt während ich sowohl Rang 3 als auch Rang 4 nutzte. Bei beiden Rängen war es verbuggt. Der andere Magier hatte keine Beschwerden, dass sein Blizzard kein Schaden macht. 

Wenn der andere Mage später Zeit hat versuch ich mal Videos davon zu machen.

**Comment by Slimmer2** [comment]
Höchster Rang ist 6. 
Wenn ein anderer Mage einen höheren Rang castet ist ein Mächtigerer Zauber aktiv und so macht der eigene Blizzard keinen Schaden

**Comment by humpalum** [comment]
Okay, danke schonmal, wir testen dass dann später nochmal, weil dann sollte ich ja theoretisch nie Schaden machen können.

**Comment by Slimmer2** [comment]
Nur wenn du vor den anderen Magier casten anfängst.

**Comment by humpalum** [comment]
Jo funktioniert so, danke nochmal.
