### ISSUE TITLE
Fallschaden ohne fallen

### ISSUE THREAD

**Issue by Urschwamm** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2212]
nachdem ich im ts kürzlich 2 mal davon gehört hab (1 x davon war ein Spieler irgendwo in Mulgore, nachdem er sich den Jahrmarktbuff geholt hatte), dass leute aus dem heiteren himmel fallschaden bekommen haben, habe ich nun auch eine solche stellte gefunden.

Im Ödland bei 45,67 bin ich heute innerhalb weniger (7-8) runden 2 mal gestorben.
somit ist der bug dort, vermutlich mit etwas glück, reproduzierbar.
die runden dort habe ich in den letzten monaten schon dutzendfach gedreht beim elementarerde farmen ohne zu sterben.
Auch ansonsten ist mir dieses Problemchen in den letzten 2,5 Jahren nirgends vorgekommen.

http://imgur.com/a/gTQr3

ohne nach quellen dazu zu suchen, gehe ich davon aus, dass es sich so nicht verhalten sollte.

**Comment by Horim** [comment]
Ist uns auch in zg vor der Rampe von thekal passiert
