### ISSUE TITLE
Stärkungszauber Sayges dunkles Schicksal des Schadens 

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2213]
**Welches Verhalten wird beobachtet?**
Der Buff kann laut Anzeige beim Waffenschaden auch negative Werte geben.
Bisher konnte ich Werte von -2%, -3%, -5% und -9% feststellen.
Es kann aber auch einfach ein allgemeiner Anzeigefehler sein.

**Wie sollte es sich verhalten?**
Es sollten nur positive Werte von 1-10% möglich sein.

**Schritte zur Reproduzierung**
Beim Dunkelmondjahrmarkt den Buff über die Antwortsequenz 1-1 besorgen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
[Sayge's Dark Fortune of Damage buff now only increases damage from a randomly determined range of 1-10%. ](http://pl.wow.wikia.com/wiki/Patch_1.9.0)
Es könnte sein das der Fehler durch den Fix von vor ein paar Wochen entstanden ist.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
[Der Buff](https://datenbank.classic-wow.org/?spell=23768)

**Comment by Realquicken** [comment]
Hallo zusammen,

ich habe ein bischen rumprobiert mit Priester und Hexer. Ich erhalte immer einen 10% Malus, auf den der rnd Buff vom JM dann wieder draufgerechnet wird. Sprich bei 5% durch den Buff habe ich als rot gekennzeichneten Multiplikator 95% hinter dem Basisschaden.

Um Anzeigefehler auszuschließen habe ich einfach ein paar Dots ticken lassen. Schattenwort Schmerz ohne JM Buff auf dem Healpriest -> 159er Ticks, mit JM Buff x95% nurnoch 144er Ticks. 

Es scheint also einen generellen Malus von 10% zu geben, sobald mal den Buff erhält. Das Problem ist letztes Wochenende nicht aufgetreten!

LG Quicken

**Comment by Horim** [comment]
Auch wenn das Lable Auf Nefarian fehlt, schließe ich den Report mal, da ich keine negativen Werte mehr feststellen konnte. Falls jemand dennoch -% kriegt, bitte melden.
