### ISSUE TITLE
Explosion bei den Anubisath Beschützern AQ40 nach Huhuran

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2217]
Welches Verhalten wird beobachtet?
https://datenbank.classic-wow.org/?npc=15355 sterben bei Nutzung der Explosionsfähigkeit instant

Wie sollte es sich verhalten?
durchcasten, dann explodieren

Schritte zur Reproduzierung
pullen, gucken ob er die Fähigkeit hat, instant tot beobachten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15355
Spell ist leider nicht im mob verlinkt

Gruß

**Comment by Ulva-Anorhin** [comment]
Kann ich bestätigen. War in unserem raid das selbe und haben es an dago direkt weiter geleidet.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2200
