### ISSUE TITLE
Totstellen fix vom 11.07

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2218]
Welches Verhalten wird beobachtet?
- Wenn man bei C-thun in der Dark Glare phase sich totstellt und nicht im strahl ist, bekommt man trotzdem einfach den strahl Schaden ab.
-Wenn man  bei Onyxia, während p3 sich in dem Erdbeben totstellt bekommt man innerhalb 1 Sekunde doppelt den Tick des Fuerschadens.

Es sieht einfach so aus als ob man nun immer den Boss aoe abbekommt...egal ob man nicht im Sichtfeld ist oder direkt im radius steht.
Ich denke man würde nun auch die Schattenflamme in bwl abbekommen, wenn man sich dabei totstellt, obwohl man nur im 180° blickfeld den Schaden bekommen sollte

Wie sollte es sich verhalten?
Totstellen sollte nicht jeden aoe von Bossen auf den Hunter lenken.

Schritte zur Reproduzierung

-C-thun während der Dark Glare phase totstellen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/655

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?spell=5384

**Comment by Donf4b** [comment]
Kann das bestätigen, passiert auch bei Heigan in Naxxramas.

**Comment by Dotox** [comment]
Was passiert bei Heigan in Naxx?
