### ISSUE TITLE
PvP Schlachtfeld Beitreten

### ISSUE THREAD

**Issue by XiamWoW** [ClassicWoW/Nefarian_1.12.1_Bugtracker#222]
Fehler:
Wenn man z.B. WSG joint und AB aufgeht kann man sehr häufig nicht nach Join obwohl das Fenster Aufploppt zum Wechseln.

Wie sollte es sich verhalten?
Man kann das gewünschte BG einfach Join wenn es aufploppt egal wann und wo.

Schritte zur Reproduzierung

Beide BGs anmelden und WSG joinen und danach AB starten und versuchen nach zujoin.

**Comment by dagochen** [comment]
Dieses Problem sollte nicht mehr auftreten, da das Anmelde-System angepasst wurde.
