### ISSUE TITLE
Kürschnern in der Gruppe

### ISSUE THREAD

**Issue by Lainesrulz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2221]
Welches Verhalten wird beobachtet?
Teilweise kann nicht gelootet werden, da angeblich eine Auswürfelung stattfindet. 
Wie sollte es sich verhalten?
Das Material was ich kürschnere sollte zu mir kommen
Schritte zur Reproduzierung
In der Gruppe mehrmals Kürschnern
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Herlot** [comment]
Eventuell kann es helfen sich beim Kürschnern in die hit box des Mobs zu stellen. Das sollte den Fehler beheben.
