### ISSUE TITLE
DM Folianten

### ISSUE THREAD

**Issue by Ichbindasheutemal** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2223]
Ist eher eine Frage als ein Bugreport, wenn die Frage jedoch entsprechend beantwortet wird, ist es doch ein Bug ;). 

Welches Verhalten wird beobachtet?
Es gibt 2 Datenbankeinträge für die Folianten in DM. Einer beinhaltet Forors Kompendium des Drachentötens, der andere nicht. Können beide Einträge auftauchen? Oder nur einer?

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?object=179547
https://datenbank.classic-wow.org/?object=179548

**Comment by dagochen** [comment]
Ingame verwenden wir nur noch noch https://datenbank.classic-wow.org/?object=179548. Dem haben wir das Kompendium jedoch auch hinzugefügt. Die Web-Datenbank ist hier nicht ganz aktuell. Ich schau aber nochmal nach.
