### ISSUE TITLE
Initiand von Hederine benutzt die Fähigkeiten Schattenblitz und Feuerbrand nicht

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2224]
Welches Verhalten wird beobachtet?

Die NPCs Namens Initiand von Hederine benutzen Schattenblitz und Feuerbrand nicht. Sie greifen ausschließlich mit Nahkampfattacken an.

Wie sollte es sich verhalten?

Diese NPCs sollten hauptsächlich Schattenblitz und ab und zu Feuerbrand benutzen. Und wenn das Mana leer ist dann erst in den Nahkampf gehen.

Schritte zur Reproduzierung

Initiand von Hederine angreifen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Das Video wurde leider erst 2010 hochgeladen:
https://www.youtube.com/watch?v=nSk5Y7N1LPk

Aber bei 3:19 bekommt der Spieler Feuerbrand ab was ihn für 499 Schaden trifft. Man sieht bei 3:27, dass es für 159 tickt. Man sieht dann bei 3:36 wie der Initiand von Hederine einen Schattenblitz abfeuert, der für 933 Schaden trifft.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Initiand von Hederine: https://datenbank.classic-wow.org/?npc=7461
Schattenblitz: https://datenbank.classic-wow.org/?spell=21077 Leider gibt es viele Schattenblitze. 
Feuerbrand: https://datenbank.classic-wow.org/?spell=20294 Auch hier leider viele Zauber, die so kategorisiert sind.

Grüße

**Comment by Slimmer2** [comment]
Der Zauber steht doch bei den NPC Fähigkeiten dabei.
https://datenbank.classic-wow.org/?spell=24668

**Comment by stva23** [comment]
Wenn man sie als WL enslaved haben sie den Schattenblitz zur verfügung, er macht dann auch den entsprechenden Schaden. Immolate allerdings nicht.
