### ISSUE TITLE
Reset bei Wordbossen

### ISSUE THREAD

**Issue by Belesar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2225]
1. Welches Verhalten wird beobachtet?

Regelmäßig kommt es bei den 4 Gründrachen zu Resets des Bosses.
Der Drache verlässt den Kampf und kehrt auf seine Spawnposi zurück,
Auffallend oft Tritt das Reseten direkt an der Rampe im Hinterland auf. Bei Lethon ist das zum Beispiel diesen Freitag 2x passiert.

(Dies passiert laut Aussagen im TS häufiger bei Zwergen. Ich hab direkt an der Rampe noch keinen Drachen getankt.)

  2. Wie sollte es sich verhalten?
Der Worldboss sollte an der Rampe nicht resetten.

  3. Schritte zur Reproduzierung
Einen der 4 Alptraumdrachen

  4. Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Videos zeichne ich keine auf aber vom Freitag sollte ich welche auftreiben können.

ähnliches Problem: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2208

Ysondre - https://datenbank.classic-wow.org/?npc=14887
Lethon - https://datenbank.classic-wow.org/?npc=14888
Smariss - https://datenbank.classic-wow.org/?npc=14889
Taerar - https://datenbank.classic-wow.org/?npc=14890

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=14888

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2208

**Comment by Ulva-Anorhin** [comment]
Nein, dass sind 2 verschiedene Tickets.
Bei 2208 hat der Tank die Aggro beim ziehen verloren.
Bei 2225 resettet der Boss oft aus Lust und Laune. Meistens ist es taerar oder Lethon.
Taerar in ashenvale ist häufig ein Problem spawn.

**Comment by Haudraufinix** [comment]
Mobs nicht auf Ecken verschiedener Konturen (in dem Fall  der Fuss der Rampe)  tanken. Wenn er sich bewegt kann seine Hitbox probleme mit dem terrain kriegen und diese spontan Resets begünstigen.

Am besten mal n video davon machen, sollte es wieder vorkommen.

**Comment by weedlord100** [comment]
https://www.youtube.com/watch?v=j47i9PznZAI

reset 2mal vor 7tagen bei taerar
