### ISSUE TITLE
wow error als Plündermeister im Raid

### ISSUE THREAD

**Issue by 2muchmage** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2227]
Welches Verhalten wird beobachtet?
Fungiert man als Plündermeister im 20er/40er Raid kommt es nahezu jedes mal zu einem wow error, wenn der gesamte raid schon weiter gezogen ist. 
Beispiel: lootverteilung bei viscidus in AQ40. Der Pm mountet nach lootvergabe auf und reitet dem Raid hinterher. Bevor man wieder in der standard Ebene eintrifft schließt sich das Spiel. Das selbe gilt bei fast jedem Boss in Zul Gurub. Da dieses Phänomen viele Spieler betrifft könnte das mal überprüft werden.

Wie sollte es sich verhalten?
Das sollte allgemein gar nicht passieren dürfen.

Schritte zur Reproduzierung
-

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
ein Video könnte, sofern erforderlich demnächst ergänzt werden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by weedlord100** [comment]
hmm ich bin jede Woche PM in aq40 und hatte noch nie ein solches Problem. selbst wenn ich noch an den twins stehe und der rest schon bei den bugs ist.
