### ISSUE TITLE
Totstellen verbuggt.

### ISSUE THREAD

**Issue by zievitoy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2228]
**Welches Verhalten wird beobachtet?**

Wenn Hunter Totstellen gemacht hat, und sich nicht bewegt, reset Mob natürlich.
Aber anschließend kommt Mob direkt zum Hunter, der Totstellen in Aggrorange gemacht hat.
Das heißt, dass Totstellenhalten jetzt nicht wie Richtigtot ist, da Mob den Hunter als Ziel nehmen kann.

**Wie sollte es sich verhalten?**

Totstellenhalten sollte wie Richtigtot sein, wenn Mobs vorbei kommen.
Also die Mobs sollten Hunter nicht als Ziel nehmen können.

Schritte zur Reproduzierung

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Jäger, IngameName Teafortwo, wenn ihr bock darauf habt, kann ich euch was mal zeigen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by zievitoy** [comment]
Es ist auf Nefarian nicht auf Testserver....

**Comment by Dotox** [comment]
Nein, der Fix ist auf dem Testserver.
