### ISSUE TITLE
Segen der Könige wird nicht ersetzt

### ISSUE THREAD

**Issue by Soox1991** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2229]
Welches Verhalten wird beobachtet?
Segen der Könige wird nicht durch Grosser Segen der Könige ersetzt

Wie sollte es sich verhalten?
Wenn ich SDK aktiv vom 1. Paladin aktiv habe und mir ein 2. Paladin Grosser Segen der Könige bufft müsste der 1. Buff verschwinden.

Schritte zur Reproduzierung
Segen der Könige selber buffen und dann von einem anderen Paladin Grosser Segen der Könige buffen lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=20217 Segen der Könige
https://datenbank.classic-wow.org/?spell=25898 Grosser Segen der Könige

**Comment by Slimmer2** [comment]
Prüfe bitte mal nach ob sich dadurch die Werte auch erhöhen. 
Es kann nämlich sein das ein Größerer Buff den Kleinen überschreibt, aber in der Buffleiste nur angezeigt wird und nicht stackt.

**Comment by Soox1991** [comment]
Also beim letzten mal meinte ich das ich 2x 10% erhalten habe. Ich bin jetzt aber atm 2 Wochen weg und kanns daher nicht überprüfen vlt kann ein andere Pala das machen? Ansonsten wird ich mich dann wieder melden.

**Comment by weedlord100** [comment]
hab s grad getestet, der buff wird nich ersetzt und die werte werden 2mal um 10% erhöht
hatte 3600hp, nach dem kleinen 3900hp. danach hat mein kumpel den grossen drauf gebufft und dann 4200hp

**Comment by Soox1991** [comment]
Also dann darf ich 2x 10% haben?

**Comment by Dotox** [comment]
Ich konnte das Problem nicht reproduzieren, da es auf dem Testserver bereits funktioniert. Auf dem Testserver befindet sich aktuell aber ein recht großes Update, welches dafür verantwortlich ist, dass das Beschriebene bereits behoben ist oder nicht mehr auftreten kann.
