### ISSUE TITLE
Freizauberzustand: Gelegentlicher Fehler

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#223]
**Welches Verhalten wird beobachtet?**
Mir ist auf dem Testserver ebenso wie auf dem Liveserver aufgefallen, dass es hin und wieder vorkommt, dass ich Wilder Biss bei Omen-Procc (Freizauberzustand) nicht ausführen kann, wenn ich nicht die theoretisch benötigte Mindestenergiemenge (35) habe. "hin und wieder" meint, dass es gefühlt im normalen Kampf zwar spürbar/ störend oft vorkommt, aber gleichzeitig längst nicht immer.

**Wie sollte es sich verhalten?**
Da der Freizauberzustand die Fähigkeitenkosten auf Null reduziert, sollte Wilder Biss immer ausführbar sein, wenn die Mindestenergie nicht vorhanden ist, so wie es auch bei allen anderen Fähigkeiten der Fall ist.

**Schritte zur Reproduzierung**
Leider hab ich es nicht hinbekommen, das in irgendeiner Weise zuverlässig reproduzieren zu können, es passiert einfach hin und wieder ... Im normalen Kampfverhalten gegen Mobs tritt es auf, wenn bei Omen-Procc und niedriger Energie Wilder Biss ausgeführt werden soll. 
Zur Not muss ich das als Video aufzeichnen, bei Bedarf melden :)

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Wilder Biss (Rang 2): http://datenbank.welli-it.de/?spell=22827
Omen der Klarsicht: http://datenbank.welli-it.de/?spell=16864
Freizauberzustand: http://datenbank.welli-it.de/?spell=16870

**Comment by Larnak1** [comment]
"Schreddern" hat das Problem auch, was den Verdacht erhärtet.

**Comment by Larnak1** [comment]
Offenbar liegt es am genutzten Effekt
'Apply Aura: Add % Modifier (14)
Wert: -100 
'
da das oben verlinkte Priester-Problem den auch nutzt.

**Comment by wahaxlekuke** [comment]
Tritt das Problem immer noch auf?

**Comment by Larnak1** [comment]
Muss ich in den nächsten Tagen nochmal drauf achten

**Comment by Larnak1** [comment]
Scheint sich tatsächlich verflüchtigt zu haben^^ Zumindest ist mit in den letzten Tagen als Katze keinerlei derartige Effekte mehr aufgefallen :)
