### ISSUE TITLE
[AQ40] Skarabäus von Ouro wie angewurzelt nach stun

### ISSUE THREAD

**Issue by Heri7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2230]
Welches Verhalten wird beobachtet?
Skarabäus von Ouro bleibt nach einem stun einfach stehen und greift nur noch an wenn man ihm zu nahe kommt (Ich habs nur mit Hammer der Gerechtigkeit getestet).

Wie sollte es sich verhalten?
Skarabäus von Ouro sollte nach dem stun normal weiter kämpfen.

Schritte zur Reproduzierung
Nach AQ40 zu Ouro gehen. Untertauchen lassen damit Erdbeben spawnen aus denen die Skarabäen krabbeln wenn Ouro wieder auftaucht. Einen Skarabäus von Ouro stunen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15718 - Skarabäus von Ouro
https://datenbank.classic-wow.org/?npc=15517 - Ouro
https://datenbank.classic-wow.org/?spell=10309 - Hammer of Justice

**Comment by Sabbaer** [comment]
kann ich so bestätigen
bleiben häufiger auch noch paladin stun einfach an ort und stelle stehen und bewegen sich nicht mehr
