### ISSUE TITLE
Hurtigkeitstrank überschreibt Zanzas Schnelligkeit

### ISSUE THREAD

**Issue by Throndar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2231]
**Welches Verhalten wird beobachtet?**
Wenn man einen Hurtigkeitstrank verwendet überschreibt er den bereits vorhandenen Buff von Zanzas Schnelligkeit.

**Wie sollte es sich verhalten?**
Der Hurtigkeitstrank sollte Zanzas Schnelligkeit nicht entfernen. Er sollte entweder stacken (+70% Lauftempo) oder das Bonustempo von Zanzas Schnelligkeit ersetzen (+50% Lauftempo). 
Leider keine exakten Quellen gefunden, allerdings sollte ein Kampftrank mit 2min CD keine Zanza"flask" die 2h hält entfernen.

**Schritte zur Reproduzierung**
Zuerst Zanzas Schnelligkeit und danach den Hurtigkeitstrank nutzen. Dabei die Buffs beobachten

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Blackrock 27.07.2017
https://youtu.be/LSKaGLFeSPI

http://db.vanillagaming.org/?item=20081#wh-comments
By depthad on 11/26/2006 (Patch 1.12.2)
This is a decent price to pay for such a minimal gain. This stacks with other run speed effects and can be very helpful in any kiting or escape ventures one might face.

Zanzas Schnelligkeit:
https://datenbank.classic-wow.org/?item=20081
https://datenbank.classic-wow.org/?spell=24383

Hurtigkeitstrank
https://datenbank.classic-wow.org/?item=2459
https://datenbank.classic-wow.org/?spell=2379

**Comment by Haudraufinix** [comment]
Movementspeedeffekte stacken in classic leider nicht, es wirkt nur der jeweils höchste Bonus.also sollte man mit beiden Effekten Aktiv (wenn das gehen sollte) tdm nur +50% movespeed haben)
