### ISSUE TITLE
Unsichtbarkeitsbug / Casten aus der Unsichtbarkeit heraus.

### ISSUE THREAD

**Issue by Cazukee** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2232]
**Welches Verhalten wird beobachtet?**
Jeder PvP-Spieler kennt es:
Das casten eines Zaubers/Schusses aus der Unsichtbarkeit heraus. Dies verschafft einigen Spielern im PvP einen enormen Vorteil!
Dies sollte laut den Patchnotes ab Patch 1.10.0 nicht mehr möglich sein.

"_Der Verstohlenheitsmodus und Unsichtbarkeitseffekte werden jetzt aufgehoben wenn eine Aktion eingeleitet wird (Zaubern, Benutzung einer Fähigkeit, etc.), anstatt wie zuvor beim Abschluss der Aktion_."
Quelle:
http://wow.4fansites.de/patchnotes_1_10.php

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Beweisvideo ab Sekunde 17 (aufgenommen Mitte 2006): 
https://www.youtube.com/watch?v=ACM3yXuz0Hw
Screenshots:
https://www.pic-upload.de/view-33640316/WoWScrnShot_073017_140417.jpg.html
https://www.pic-upload.de/view-33640320/WoWScrnShot_073017_140744.jpg.html
https://www.pic-upload.de/view-33640315/WoWScrnShot_073017_140836.jpg.html

**Schritte zur Reproduzierung**
Ganz einfach:
In Unsichtbarkeit bzw. Verstohlenheit gehen - einen Gezielten Schuss oder einen Zauber casten.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Davon Betroffen sind...

Die Nachtelfenfähigkeit (wie auch im Video zu sehen) (konnte in der Datenbank nur die Passive finden):
https://datenbank.classic-wow.org/?spell=21009

Die Unsichtbarkeitstränke:
https://datenbank.classic-wow.org/?item=9172
https://datenbank.classic-wow.org/?item=1257
https://datenbank.classic-wow.org/?item=3823

Die Schurkenverstohlenheit:
https://datenbank.classic-wow.org/?spell=1784

**Comment by Slimmer2** [comment]
Wir haben den Patchstand 1.10 schon auf dem Server.

**Comment by Cazukee** [comment]
Ja, genau deshalb sollte es ja nichtmehr möglich sein.

**Comment by Slimmer2** [comment]
Mich wundert es gerade weil hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1718 fixt ist

**Comment by Cazukee** [comment]
Alle Patchnotes nach 1.10.0 geben keinen Anhaltspunkt, dass es wieder geändert wurde. Ich habe heute mehr als 2 Stunden an den ganzen Classic-Patchnotes gehangen und habe mir alles gründlich durchgelesen.

**Comment by Cazukee** [comment]
Deswegen poste ich es ja nochmal. Garnichts ist fixed. 

Ich könnte nun hier groß Vermutungen aufstellen, das lasse ich aber sein.
Es wäre toll, wenn es denn mal gefixt wird. ^^

**Comment by Cazukee** [comment]
Dazu stelle ich mir die Frage: 
Wieso machen die Leute es weiterhin.. obwohl anscheinend schon lange bekannt ist das hier ein Fehler vorliegen könnte.

Namen kann ich nennen. Möchte ich aber nicht.

**Comment by Cazukee** [comment]
@Dotox @dagochen
