### ISSUE TITLE
[Naxxramas] Zusammengeflickter Golem

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2233]
**Welches Verhalten wird beobachtet?**

Der "Zusammengeflickte Golem" nutzt eine Spaltenfähigkeit, die nur 180 Grad vor Ihnen Schaden verursacht. (Diese Fähigkeit wird durch eine "Zauberanimation" --> Goldene Ketten, angezeigt)

Die Fähigkeit "War Stomp" hat eine zu große Reichweite. Wir hatten gestern das Gefühl, die Fähigkeit hat eine Reichweite von 10- bis 15m Reichweite. (Bitte entsprechend überprüfen)

Die Flickwerkgolems setzen die Fähigkeit "Execute" nicht ein, wenn das Ziel weniger als 20% an Leben besitzt. 

**Wie sollte es sich verhalten?**

Die Spaltenfähigkeit sollte einen 360 Grad-Radius haben, also alle Spieler um den NPC herum treffen (5 Yards). Die Animation und das Ausführen funktionieren soweit ohne Probleme.

Die Fähigkeit "War Stomp" sollte nur eine Reichweite von guten 5m aufweisen!

Die Flickwerkgolems sollten eine Fähigkeit "Execute" einsetzen, wenn das Ziel weniger als 20% Leben besitzt. Diese Fähigkeit sollte den Schaden auf das Ziel (Tank) um bis zu 490+ Schaden pro Treffer erhöhen. 

**Schritte zur Reproduzierung**

Entsprechend die "Zusammengeflickten Golems" pullen. Die Reichweite des "War Stomps" überprüfen. Den Winkel der "Cleave"-Fähigkeit überprüfen. Sich selber auf unter 20% Leben setzen und dann schauen, ob die Fähigkeit "Execute" genutzt wird.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

"_360° Cleave (~3750 damage on cloth) (The Cleave is chain-targeting like C'Thun Eyebeam and looks like a heal being cast when it's being prepared.)_"

https://web-beta.archive.org/web/20070812080923/http://www.wowwiki.com:80/Patchwork_Golem

In der Datenbank ist die Reichweite von "War Stomp" auf 15 Meter gesetzt. Das ist etwas sehr groß. ^^
Bitte entsprechend überprüfen.

Der Beweis für die Execute Fertigkeit ist dem **_"Bestarium"_** zu entnehmen: 

Seite 1 unter Abonimations --> Patchworkgolems

_"Execute: Attempts to finish off a wounded enemy, inflicting normal damage plus 490. Execute can only be used on enemies that have 20% or less health."_

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Zusammengeflickter Golem:
https://datenbank.classic-wow.org/?npc=16017#abilities

Cleave:
https://datenbank.classic-wow.org/?spell=27794

War Stomp:
https://datenbank.classic-wow.org/?spell=27758

Exectue: 
https://datenbank.classic-wow.org/?spell=7160  (Achtung Wert muss auf 490 gesetzt werden)

**Comment by Mafyo** [comment]
15 meter sind schon realistisch hier ein Video: https://youtu.be/VrykhhdPfc4?t=60 sind mehr als 5m definitiv

**Comment by Baraz** [comment]
Das Video ist vom 22.05.2006, 1.11 ging live am 20.06.2006, ist also vom PTR. Inwieweit dies als Quelle genutzt werden kann ist in meinen Augen zweifelhaft.

**Comment by Mafyo** [comment]
[Die zusammengeflickten Golems betäuben Spieler in einem Umkreis von 15 Metern](http://www.buffed.de/World-of-Warcraft-Spiel-42971/Guides/WoW-Guide-Naxxramas-Das-Konstruktviertel-791723/)  ist zwar aus einem guide für wotlk naxx aber zeigt auch das sich hier wahrscheinlich am Original gehalten wird

hier ein Ptr log von Blizzard vom  23.05.06 dies ist die einzige Änderung beim Golem gewesen
[Patchwork Golem: No longer loses aggro on war stomp ](url)
ich habe das zwar noch nicht selber getestet aber dann sollten sie keinen Aggroverlust haben momentan.

**Comment by Omegaexodus** [comment]
Leider ist der Guide nicht wirklich aussagekräftig. Da dort Sachen wie der Cleave falsch beschrieben sind. (In Classic war es nicht möglich, den Cleave hinter dem NPC zu vermeiden).

Zusätzlich möchte ich anmerken, das man im Video zwar sehen kann, das die 5m Range zu gering ist, aber es auch keine 15m sind. (Wahrscheinlich in Richtung 8-10m) Wir konnten bereits am Montag, (letzte Woche) feststellen, das die 15m extrem große Tankflächen beanspruchten, was das positionieren der NPCs sehr schwer machte. (Gerade da man 4 auf einmal hat)

Ich würde demnach die 5m im Zweifelsfall auf 8-10m setzen lassen, wenn man das Video als Quelle nehmen möchte. Aber 15m sind doch etwas sehr viel und auch im Video nicht ersichtlich. Man kann bei unserem Naxx-Test (Dotox-Archiv) sehen, das die Stun-Reichweite deutlich höher war, als im Video.

**Comment by Dotox** [comment]
Aktuell sind es 10 Meter, denke das sollte in Ordnung sein.
