### ISSUE TITLE
[Naxxramas] Grobullus

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2236]
**Welches Verhalten wird beobachtet?**

Es war den Tanks von Grobbulus möglich, der Fähigkeit "Schleimstrahl" zu widerstehen. Dadurch sind auch keine "Fallout Slimes" erschienen.

**Wie sollte es sich verhalten**?

Es sollte nicht möglich sein der Fähigkeit "Schleimstrahl" zu widerstehen. Dies würde zu einer starken Vereinfachung des Encounters führen!

**Schritte zur Reproduzierung**

Naturessi anlegen und Grobullus pullen. Dann warten bis man der Fähigkeit widersteht.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

_"DPS on Grobbulus is ranged, so as to avoid spawning multiple fallout slimes. Only one slime should be spawned at a time(the MT's) which will presumably aggro onto a healer, and should otherwise be pulled to melee classes."_

https://web-beta.archive.org/web/20070106112819/http://www.wowwiki.com:80/Grobbulus

Wäre es möglich der Fähigkeit mit Naturressi zu widerstehen, könnten die Tanks einfach max. Naturressi anziehen. Dadurch würden keine "Fallout Slimes" mehr entstehen, was die Kampfdauer und den Schwierigkeitsgrad drastisch senken würde. (Meeles können permanent an den Boss)

Ich möchte betonen das ich keine Videos gesehen habe, wo "Schleimstrahl" widerstanden wurde. Zusätzlich würde es Quellen darüber geben, wenn man der Fähigkeit mittels naturressi widerstehen könnte. (https://www.youtube.com/watch?v=RSauHKnQbYE&t)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Grobullus:
https://datenbank.classic-wow.org/?npc=15931

Schleimstrahl:
https://datenbank.classic-wow.org/?spell=28157

**Comment by Baraz** [comment]
Zumindest der Schadenskomponente des Schleimstrahls sollte man widerstehen können.

[Poison Spray:
Ein Giftkegel den Grobbulus in die Richtung des MTs sprüht (bzw. Kegelförmig auf das Ziel mit der höchsten Aggro). Fügt Naturschaden zu der resisted werden kann.](https://web.archive.org/web/20060901154038/http://www.wow-tactics.de:80/20_taktiken/naxx/grobbulus.php)

**Comment by Baraz** [comment]
Der Schadenskomponente sollte widerstanden werden können. In obigem Video z.B. bei 04:47 erkennbar im Kampflog.

[Ein Giftkegel den Grobbulus in die Richtung des MTs sprüht (bzw. Kegelförmig auf das Ziel mit der höchsten Aggro). Fügt Naturschaden zu der resisted werden kann.](https://web.archive.org/web/20060901154038/http://www.wow-tactics.de:80/20_taktiken/naxx/grobbulus.php)

**Comment by Dotox** [comment]
Stimmt, gut gesehen. Fallout Slimes spawnen aber trotzdem.
