### ISSUE TITLE
[Naxxramas] Gluth / Zombie Chow

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2237]
**Welches Verhalten wird beobachtet?**

Der Boss "Gluth" setzt in regelmäßigen Abständen die Fähigkeit "Dezimieren" ein, welches das Leben aller Spieler und Zombies in dem Raum auf 5% Ihres maximalen Lebens setzt. Die Zombies verlieren zwar sämtliches Leben, rennen danach jedoch nicht zu Gluth. (Bewegungsunfähig) Zusätzlich greifen sie weiterhin Spieler in der Aggro-Liste an. (Falls Sie sich noch bewegen)

**Wie sollte es sich verhalten?**

Wenn Gluth die Fähigkeit "Dezimieren" wirkt, sollten alle Zombies automatisch zu Gluth laufen. Sie sollten sich nicht mehr an die entsprechende Aggro-Liste der Spieler orientieren (Egal wie viel Schaden sie erhalten), sondern nur noch Gluth als Ziel nehmen.

**Schritte zur Reproduzierung**

Gluth pullen und warten bis Dezimierung eingesetzt wird. Dann schauen, ob alle Zombies zu Gluth laufen oder ob sie weiterhin durch Schaden umgelenkt werden können.

Zusätzlich beobachten ob das Pathfinding nach einem Stun noch vorhanden ist.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Was das Pathfinding-Problem angeht, muss man schauen wodurch der Stun-Effekt ausgelöst wird. Die NPCs scheinen sich nicht mehr bewegen zu können, wenn man sie betäubt. (Selbe Problem bei Ouro und den Käfern)

Hier ein Hinweis, warum bei Dezimieren, die Zombies stehen bleiben:

https://datenbank.classic-wow.org/?spell=28374   (Hier ist ein Stunwert drin, warum auch immer, bitte in der DB überprüfen, hier gibt es 2x Decimate) oO. Wäre es nicht deutlich einfacher, den zusätzlichen Effekt: "Send Event (10495) " mit beim https://datenbank.classic-wow.org/?spell=28375 reinzusetzen? 

https://web-beta.archive.org/web/20070106112405/http://www.wowwiki.com:80/Gluth

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Gluth: 
https://datenbank.classic-wow.org/?npc=15932

Dezimieren:
https://datenbank.classic-wow.org/?spell=28375
https://datenbank.classic-wow.org/?spell=28374  (Gibt es einen Grund warum hier ein Stunwert drin ist beim Dezimieren? ---> Sorgt für das Pathfinding Problem der Zombies)
https://datenbank.classic-wow.org/?spell=29682

Zombie Chow:
https://datenbank.classic-wow.org/?npc=16360

Beschwören der Zombies:
https://datenbank.classic-wow.org/?spell=28216

**Comment by Omegaexodus** [comment]
Hallo Dotox, ich habe mir heute früh den Stream vom Naxx-Test-Raid von gestern Abend angeschaut. Dabei habe ich vor allem die Gluth Kämpfe verfolgt.

Eventuell hast du ja bereits den Fehler gefunden und konntest diesen beheben. Falls nicht, habe ich eventuell noch einige Ideen, die dir weiterhelfen können, weshalb die Adds stehen bleiben bzw. sogar teilweise die Aggro-Fixierung auf Gluth ignorieren.

**Fall Nummer 1:** 

Die Adds resetten die Aggro nicht richtig, wegen "Spott-Effekten". 

Sie nehmen zwar Gluth ins Visier, verfolgen aber dennoch die Spieler bzw. bleiben deswegen stehen. Da das Pathfinding nicht mehr möglich ist. (Pathfinding auf Gluth / Aggro auf Spieler?)

Einer der Gründe könnte sein, das sie in dem Moment noch einen "Spott-Effekt" auf sich haben, der die Aggro-Liste von Gluth überschreibt. Eventuell kann man nachschauen, das man beim Dezimieren, den Zombies Immunität gegen Spott oder Spott-ähnliche Effekte gibt.

**Fall Nummer 2:** 

Die Adds resetten die Aggro nicht richtig, wegen dem "Nächstgelegenes Ziel angreifen bei Bewegungseinschränkung".

Soweit ich weiß, hat Dago vor einigen Monaten ein Patch aufgespielt, der dafür sorgt, das Adds, die "immobilize" gesetzt sind (sich also nicht mehr bewegen können), automatisch das nächstgelegene Ziel angreifen, wenn sie sich dazu in Reichweite befinden.

Kann es sein, das wenn Spieler die Zombies "immobilize" setzen (Beispiel: Frostnova), die Zombies aber noch andere Spieler in Reichweite haben und somit angreifen, während Dezimieren auftritt, dass Script (für Immboilize) versucht, den Spieler als Angriffsziel zu setzen? Das würde bedeuten, dass das Script den Path für das fixieren des Spielers umschreibt, obwohl der eigentliche Weg, durch das Dezimieren, auf den Boss in dem Moment gesetzt wird? 

Dadurch könnte es passieren, das beide Bereich im Quellcode, sich gegenseitig blockieren und kein direkter Path mehr weder zum Boss, noch zu dem Spieler gesetzt werden kann. Somit bleiben dann die Zombie stehen und bewegen sich gar nicht mehr.

**Fall Nummer 3:** 

Die Adds bewegen sich deshalb nicht mehr, weil durch das "Dezimieren" der Wert für die Bewegungsgeschwindigkeit bei mehrfachen "Bewegungseinschränkenden Effekten" auf -100% gesetzt wird. (Stappelbarer Effekt??)

Wenn genau in dem Moment, wo Dezimieren gewirkt wird, mehrere Effekt, die die Bewegungsgeschwindigkeit der Zombies verlangsamen, gewirkt werden, sollte man überprüfen, ob der Wert nicht durch Client / Lagg verursachte Probleme sich auf den Zombies stapeln kann. Das würde dazu führen, das der Wert für die Bewegung auf 0 fällt und die Zombies permanent stehen bleiben.


Es wäre sehr hilfreich, wenn man Teile des Quellcodes zur Verfügung hätte, gerade was den "Immobilize" Effekt angeht. Momentan konnte ich mich nur auf Grund des Quellcodes von CMangos orientieren.

Ich hoffe dennoch, das die Anmerkungen dich bei der Fehlersuche einschränken können. Falls du den Fehler gefunden hast, lass es mich wissen. 

Mfg Omega :-)

**Comment by Dotox** [comment]
Ich denke ich hab den Fehler gefunden.
