### ISSUE TITLE
Schwarzer Lotus Spawnzeit und Spawnpunkte

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#224]
Welches Verhalten wird beobachtet?

Nach der Testerei auf dem Testserver sind die schwarzen Lotuse noch immer an den gleichen Stellen  wie auf Nefarian (war zumindest in Winterspring so) und nicht auf den Spawnpunkten von http://old.wowdata.ru/object.html?id=176589 (mich würde noch interessieren ob ihr die Spawnpunkte von früher oder euere eigenen verwendet).

Wie sollte es sich verhalten?
Es sollte pro Gebiet und 60-70min nur EIN schwarzer Lotus spawnen. (Quellen ganz unten)

Schritte zur Reproduzierung
In ein Gebiet gehen wo schwarzer Lotus ist und dort an allen Punkten die Lage checken.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Quellen:
http://wowpedia.org/index.php?title=Black_Lotus&oldid=554941 (Quelle von kurz nach TBC release, allerdings ohne TBC-Daten, also vermutlich noch die Informationen aus Classic)

"Stop asking where they are, the Allakhazam map locations are quite accurate. The problem is that people farm the hell out of black lotus and they only spawn once every hour or two. It's like taming Broken Tooth - takes a measure of perserverance and luck. "
( https://web.archive.org/web/20061025234844/http://wow.allakhazam.com/db/item.html?witem=13468 )

http://www.wowhead.com/object=176589#comments:id=10451

**Comment by hraesvelgr** [comment]
wurde das nicht schon gefixt?
