### ISSUE TITLE
Mal der Wildniss wird nich Überbufft

### ISSUE THREAD

**Issue by weedlord100** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2240]
**Welches Verhalten wird beobachtet?**
macht ein druide mdw rang 3 und ein weiterer danach den grossen gruppen mdw wird der rang 3 nicht überbufft

**Wie sollte es sich verhalten?**
beim buffen des gruppen mdw sollte der single mdw überbufft werden

**Schritte zur Reproduzierung**
mit einem Druiden mdw rang 3 auf einen spieler casten, danach mit einem weiteren Druiden den gruppen mdw buff buffen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?spell=5235
https://datenbank.classic-wow.org/?spell=17055

**Comment by dagochen** [comment]
Nicht, wenn das Ziel ein zu niedriges Level für den hohen MDW-Buff hat.
