### ISSUE TITLE
Verstohlenheitsbug in AQ40

### ISSUE THREAD

**Issue by Mirakoli123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2242]
Welches Verhalten wird beobachtet? 
Nach den ersten Mobgruppen nach Skeram, hat man selbst außerhalb des Kampfes keine Möglichkeit sich unsichtbar zu machen, nach einem /reloadui oder relogg geht es dann wieder für "meistens 1 Mobsgruppe"

Wie sollte es sich verhalten?
Nach dem Kampf sollte man wieder unsichtbar werden können

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Hast du vielleicht mehr Informationen dazu? Bilder, Videos, Kampflogausschnitte etc?

**Comment by godlike321** [comment]
Kann ich so erstmal nicht bestätigen, ich kann seit nunmehr fast 2 Jahren IMMER stealthen

**Comment by Mirakoli123** [comment]
Nein, Videos kann ich keine machen, nen Screenshot kann ich gern mal zukommen lassen.
Das Problem an der Sache an sich ist, dass der Bug erst nach Skeram getötet wird auftritt.

Meine Stealth-Fähigkeit ist dann einfach ausgegraut und es erscheint "Diese Fähigkeit ist noch nicht bereit."

Kampflog zu prüfen fällt mir bisschen schwierig, weil in nem Raid soviele Daten auf einmal getrackt werden, dass ich es meistens nicht finde, bzw schon so schnell überschrieben wird, dass man nimma nachgucken kann.

**Comment by Slimmer2** [comment]
Gib im Chat /kampflog ein, dann wird eine Textdatei erstellt mit Kampflogdaten ab der Eingabe.

**Comment by godlike321** [comment]
Der Bug tritt auf wenn du Vanish zündest und in dieser Sekunde stirbst. Kommt im BG zB. sehr oft vor. 
Wirst du bei Skeram zufällig öfter übernommen?

**Comment by Mirakoli123** [comment]
Katze hat kein Vanish und nein, ich werd bei Skeram eig nie übernommen.
Am Sonntag schick ich dann nen Screenshot rein und ich schau das ich ein Kampflog mitlaufen lasse

**Comment by Mirakoli123** [comment]
http://www.bilder-upload.eu/show.php?file=19a0f2-1503387757.jpg

Hier stehen wir zb gerade vor Viscidius beim buffen und ich kann nicht in stealth gehen, die Fähigkeit ist einfach ausgegraut...

Kampflog hab ich auch mitlaufen lassen, das ist aber irgendwie vermischt mit diversen anderen Tagen und ziemlich lang... wo soll ich das dann hochladen, bzw lohnt es sich, da es vermischt ist.

Ich hoffe das Bild reicht für den Anfang.
