### ISSUE TITLE
Kräuter farmen in Low Levelgebieten

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2243]
Welches Verhalten wird beobachtet?
Trotz zahlreicher, theoretischer MapSpawnpunkte z.B. Silberblatt in Durotar (ca. 100) findet man als Epic reitend Skillender nur wenige. Ich bin ca. 45 Minuten durch Durotar, Mulgore, Barrens geritten und habe satte 20 Kräuter gefunden.

Wie sollte es sich verhalten?
Die Spawnzahl der LowLevel Kräuter sollte wesentlich höher frequentiert sein. In den HighLevelGebieten passt es einigermaßen. Nur im Low Levelbereich fällt es extrem auf.
Ich frage mich, wie ein Spieler ohne Mount skillen soll... selbst mit Mount muss man teils mind 2min reiten, um einem Silberblatt oder eine Friedensblume zu begegnen.

Schritte zur Reproduzierung
einfach mal durch Durotar reiten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://datenbank.classic-wow.org/?object=1617

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?object=1617

**Comment by Dotox** [comment]
Da brauchen wir viel mehr Input wie beispielsweise mehr Erfahrungen von anderen Spielern.

**Comment by godlike321** [comment]
Also ich weiß nur dass Berufe skillen immer Pain war :>
