### ISSUE TITLE
Questkette: Der Vermisste Diplomat

### ISSUE THREAD

**Issue by Gwhenwyfar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2247]
Welches Verhalten wird beobachtet?
Nachdem man [Dashel Eisenfaust](https://datenbank.classic-wow.org/?npc=4961) (NPC 4961) und seine Adds besiegt hat, lässt sich die Quest nicht abgeben. Der Konversationsbutton ist ausgegraut und das Fragezeichen bleibt grau.
Questkette [Der vermisste Diplomat](https://datenbank.classic-wow.org/?quest=1447/Der%20vermisste%20Diplomat) 8/ 11
Wie sollte es sich verhalten?
Man sollte im Dialogfeld auf den Weiterbutton klicken können, danach sollte die Quest abgebbar sein.

Schritte zur Reproduzierung
Dashel ansprechen und den resultierenden Kampf gewinnen.
Quest abbrechen und wieder annehmen, Addons deaktivieren, WTF Ordner löschen und  Relog/ Game neustarten bringt alles zusammen nichts.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Screenshot](http://www.fallout2.de/greymouse/fta/dashel.jpg) 
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Gwhenwyfar** [comment]
Habe mit einem anderen Char herummexperimentiert, die Quest ist machbar wenn man Dashel Eisenfaust nicht attackiert und zuerst die Adds ausschaltet. Wenn man Dashel  auch nur einmal attackiert (auch Autohit oder eine AOE), bevor die Adds down sind, wird er sofort grün,, geht aus de Kampf und die Quest schließt aber nicht ab.
Grundsätzlich sollte die Reihenfolge aber egal sein.

**Comment by Gwhenwyfar** [comment]
Habe mit einem anderen Char herummexperimentiert, die Quest ist machbar wenn man Dashel Eisenfaust nicht attackiert und zuerst die Adds ausschaltet. Wenn man Dashel auch nur einmal attackiert (auch Autohit oder eine AOE), bevor die Adds down sind, wird er sofort grün,, geht aus de Kampf und die Quest schließt aber nicht ab.
Grundsätzlich sollte die Reihenfolge aber egal sein.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1358
