### ISSUE TITLE
Fehlender Rare-Mob in LBRS

### ISSUE THREAD

**Issue by MisterMarax** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2248]
Welches Verhalten wird beobachtet?
Der Rare-Mob "Ghok Haudrauf - Champion der Blutäxte" fehlt in LBRS. Habe jetzt ca. 15 IDs in LBRS getestet, ob er da ist und er war nie anzutreffen, obwohl er in unserer Datenbank vorhanden ist.

Wie sollte es sich verhalten?
Ghok Haudrauf sollte in LBRS im Raum nach Halycon (dort wo die Grunzer, Magier usw. der Blutäxte stehen) an einer Random-Position im Raum spawnen können. 

Schritte zur Reproduzierung
LBRS gehen, mehrere IDs testen und sehen, dass er (sehr wahrscheinlich) nicht da ist.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Hier einmal von WoWhead die Positionen des Mobs in LBRS: http://www.wowhead.com/npc=9718/ghok-bashguud

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Ghok Haudrauf: https://datenbank.classic-wow.org/?npc=9718

**Comment by ChichiWarrior** [comment]
15 ist keine aussagekräftige Anzahl an ID's. Es kann in der Tat vorkommen, dass es einige ID's benötigt bis ein Rare Mob anzutreffen ist.
Selbst schon miterlebt. Ca 40 ID's gebraucht um den Rare Mob anzutreffen.

**Comment by Haudraufinix** [comment]
Legio Expedita hat beim farmen nach Rüstspalter nach Ghok ausschau gehalten.

Wir haben Den Metzger der Felsspitzoger 6x gefunden aber Ghok nie.
