### ISSUE TITLE
Quest - Gesucht Gurgelbacke

### ISSUE THREAD

**Issue by mami1306** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2251]
Welches Verhalten wird beobachtet?
Sobald man in das Feuer geht, spawnt eine Welle Murlocs im Wasser und rennt ins Lager. Sie greifen nur an, wenn sie in Aggro Range sind oder man sie selbst angreift. Nach dem Töten der drei Murlocs passiert gar nichts mehr.

Wie sollte es sich verhalten?
Es sollten drei Wellen kommen, in der dritten Welle sollte Gurgelbacke mit anwesend sein, töten Quest abgeschlossen.

Schritte zur Reproduzierung
Lager clearen, Welle 1 töten warten... Welle 1 spawnt irgendwann nochmal wenn man das Event nochmal triggert.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Gurgelbacke](https://datenbank.classic-wow.org/?npc=10323)
[Küstenläufer der Grauflossen - Mobs in den Wellen](https://datenbank.classic-wow.org/?npc=2202)

**Comment by Dotox** [comment]
Funktioniert bei mir wunderbar. Eventuell abbrechen und neustarten.

**Comment by mami1306** [comment]
Hat geholfen danke :)
