### ISSUE TITLE
Düsterbruch Nord Buffs usw.

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2253]
Welches Verhalten wird beobachtet?
Aktuell bekommen alle, die beim Kill des Ogerkönigs dabei waren automatisch den [Buff](https://datenbank.classic-wow.org/?spell=22799) vom [Mizzle](https://datenbank.classic-wow.org/?npc=14353).

Wie sollte es sich verhalten?
Die Spieler sollten den [Buff](https://datenbank.classic-wow.org/?spell=22799) erst erhalten, wenn sie [Mizzle](https://datenbank.classic-wow.org/?npc=14353) anreden.

Schritte zur Reproduzierung
Ogerkönig töten und sehen wie [Mizzle](https://datenbank.classic-wow.org/?npc=14353) der gesamten Gruppe den [Buff](https://datenbank.classic-wow.org/?spell=22799) gibt. 

Auffälliges Verhalten
Man kann [Mizzle](https://datenbank.classic-wow.org/?npc=14353) anreden, während er auf dem Weg zu seiner Position ist und sich den [Buff](https://datenbank.classic-wow.org/?spell=22799) holen. Wenn er auf Position steht, bekommt man den [Buff](https://datenbank.classic-wow.org/?spell=22799) nicht mehr per anreden, aber er bufft die ganze Gruppe.

Demnach sollten auch nachfolgende Spieler, die nicht beim Kill dabei waren, die Möglichkeit haben, sich den Buff von Mizzle zu holen. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Eintrag von 2006 http://amdsoft.com/wow-how-to-do-a-dire-maul-tribute-run/
Video von 2006, dort sieht man, dass Mizzle während der auf Position läuft, nicht die gesamte Gruppe bufft, jeder muss ihn anreden: https://www.youtube.com/watch?v=AND-5oZBPc4

Video von Nostalrius, dort ist es genau so wie beschrieben:
https://www.youtube.com/watch?v=gXg_KBx-yNQ

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Buff https://datenbank.classic-wow.org/?spell=22799
Mizzle https://datenbank.classic-wow.org/?npc=14353

**Comment by Sheed90** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1800

**Comment by Dotox** [comment]
Konnten andere Spieler die bei dem Kill nicht dabei waren, Mizzle ansprechen und sich ssn Buff holen? Man kann Mizzle nicht ansprechen, wenn man den Buff schon hat bzw. bufft er einen dann nicht.

**Comment by Sheed90** [comment]
Wir testen das jetzt nochmal. Aber es ist zur Zeit so, wie oben beschrieben. 

Sprich, wenn er auf Position steht und den Buff auf die gesamte Gruppe gewirkt hat, ist es **nicht** mehr möglich die Gesprächsoption aufzurufen. Egal, ob man den Buff bereits hat oder eben nicht.

**Comment by Dotox** [comment]
Ne geändert wurde nichts weil nichts dergleichen reproduzieren konnte. Ich lass das Thema trotzdem mal offen, vielleicht tritt es nochmal auf.
