### ISSUE TITLE
[Schurke] [Verstohlenheit] [Kisten]

### ISSUE THREAD

**Issue by Tatanker** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2254]
Durch das Update vom 18.08.2017 ist es nicht mehr möglich Kisten aus der Verstholenheit zu öffnen. Guides zeigen das es in Vanilla möglich war. Bitte ändert das wieder damit man als Schurke wieder farmen kann.

**Comment by Slimmer2** [comment]
Dann poste links zu den Guides
