### ISSUE TITLE
Frostbrand und Frostschock widerstehen teilweise

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2255]
**Welches Verhalten wird beobachtet?**

Wenn man Mobs mit Frostbrand oder Frostschock angreift dann widerstehen diese Zauber teilweise. 

**Wie sollte es sich verhalten?**

Da Frostbrand und Frostschock binäre Zauber sind, da sie noch einen Zweiteffekt haben sollten sie entweder vollen Schaden machen oder komplett widerstehen. Zum Teil widerstehen dürfen sie nicht.

**Schritte zur Reproduzierung**

Mit Frostbrand oder Frostschock Gegner angreifen. Am besten welche, die hohen Frostwiderstand haben.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Screenshot inc.:
http://666kb.com/i/dlyrkyeo758w9zp3r.png

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Frostschock:
https://datenbank.classic-wow.org/?spell=10473

Waffe des Frostbrandes:
https://datenbank.classic-wow.org/?spell=16356

Disteltausammler:
https://datenbank.classic-wow.org/?npc=5481

Grüße

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1714
