### ISSUE TITLE
[Naxxramas] Pre-Event

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2256]
Dotox fragte im Stream, ob jemand Quellen für das Event hat - ich mache mal den Anfang.

Ich denke hier das Event am besten beschrieben. Leider gemischt mit WotLK Infos.
http://wowwiki.wikia.com/wiki/Scourge_Invasion

Trailer zum Patch
https://www.youtube.com/watch?v=3RiJG96t0do

**Comment by Mafyo** [comment]
Hab da einiges gesammelt in der Zeit meiner Recherchen:

https://www.youtube.com/watch?v=C65pQRSZh6A
https://www.youtube.com/watch?v=unusjpGt8bY
https://ds-servers.com/video/shadow-of-doom-bashful.html
https://www.youtube.com/watch?v=3XtNDLs-P5s
https://www.youtube.com/watch?v=bdTjHBLe-VY
https://www.youtube.com/watch?v=c0QjLqHVPRU btw nice Musik ;)
https://www.youtube.com/watch?v=0dtueuXCsJs

Privatserver:
https://www.youtube.com/watch?v=fPQgrNhtoO8

Informationen zum Ablauf des Events mit Spawns etc. 👍 https://progression-annexe.blogspot.lu/2017/03/vanilla-wow-scourge-invasion-2006.html

MfG Shâto

**Comment by weedlord100** [comment]
https://wow.gamepedia.com/Scourge_Invasion  nur den ersten abschnitt und listen mit patch 1.11 vermerk 
http://et.worldofwarcraft.wikia.com/wiki/Scourge_Invasion

**Comment by Sheed90** [comment]
Scheinbar gibt es hier Leute, die die Bugs nicht melden... 

In Tanaris habe ich den offenen Necrotic Shard gefunden, er war auf 85 %, aber es war keine Mobs mehr da und es spawnten auch keine nach. 

![wowscrnshot_010618_111036](https://user-images.githubusercontent.com/10332184/34638746-6ab07bb0-f2d2-11e7-9709-5f269fd251b8.jpg)

**Comment by Sheed90** [comment]
Eben so bei dem Punkt in Azshara:

![wowscrnshot_010618_111728](https://user-images.githubusercontent.com/10332184/34638774-3fcd6f60-f2d3-11e7-9b90-3fb5ec897491.jpg)

![wowscrnshot_010618_111730](https://user-images.githubusercontent.com/10332184/34638775-3fea5166-f2d3-11e7-828c-23d25c90aeac.jpg)

**Comment by Dotox** [comment]
Danke! Das ging vor dem Update heute morgen, hatte schließlich etwas mit den Zahlen experimentiert und bin dann ins Bett. Offenbar sind die Zahlen noch etwas zu hoch weshalb der Respawn nicht mehr geht. Fix kommt im Verlauf des Nachmittags.

**Comment by Sheed90** [comment]
Wir haben einen Shard komplett runter gehauen, die Schemen spawnen lassen und nach und nach umgehauen. Es dauerte etwas, bis der Shard danach despawned ist. 

Was wir beobachtet haben ist, dass der Kristall, ob wohl keine Akolyten mehr da waren, die ihn heilen sollten, wieder zum normalen Shard wurde und nicht im damaged war. Aber der Abschluss ging scheinbar trotzdem.

**Comment by Sheed90** [comment]
Jetzt soll laut NPC ein aktiver Shard in den verwüsteten Landen stehen, aber wir sehen nur die Nekropole dort schweben.

**Comment by Sheed90** [comment]
Hier ein sehr nützliches Video zu den kämpfen in Stormwind: 
https://www.youtube.com/watch?v=c0QjLqHVPRU

Ähnlich wird es wohl in OG zugehen.

**Comment by Dotox** [comment]
Die Markierungen werden erst auf der Map angezeigt, wenn man sich vorher die Information beim NPC abgeholt hat (dafür sind sie ja da, oder?).

**Comment by Sheed90** [comment]
Ah ok, teste ich sofort nochmal. Danke für die Info!

**Comment by Sheed90** [comment]
Ok, wir haben jetzt die beiden aktiven (Tanaris und Azshara) gecleart, sodass alle Mobs despawnt sind. Nun sagt der NPC in der Brennenden Steppe und den Verwüsteten Landen wären kämpfe. Dort sind auch die kleine Nekropolen zu sehen, allerdings kein Spawnkreis darunter und auch keine Mobs.

**Comment by Dotox** [comment]
Super, vielen Dank. Der "Abschluss" eines Events muss noch verbessert werden. Da fehlt, so wie ich das jetzt recherchiert habe, noch ein Zauber und die Animation der Nekropole. Entsprechend sollten die Objekte (Kreis und Nekropole) auch verschwinden und nicht kurz nach Abschluss des Events wieder "respawnen".

**Comment by Dotox** [comment]
Hey, habe nun den Abschluss des Events verbessert. Außerdem wurden entsprechende Anpassungen aus #2444 vorgenommen. Freue mich über Feedback!

**Comment by Sheed90** [comment]
Das Event funktioniert nun wie in #2444 beschrieben. Man hat nun quasi unendlich lange Zeit, die 2. Phase zu beenden. 

Der Abschluss sieht sehr gut aus und funktioniert ebenfalls! Sobald der Respawn wieder aktiviert wird, kannst du uns ja Bescheid geben, dann würden wir die Events noch einmal testen. Ggf. funktionieren dadurch auch die Verkünder wieder #2455 .

Gruß
