### ISSUE TITLE
[Naxxramas] Gluth

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2258]
**Welches Verhalten wird beobachtet?**

Gluth setzt eine Fähigkeit mit dem Namen "Raserei" in regelmäßigen Abständen ein. Diese Fähigkeit wird durch den Schuss "Einlullender Schuss" von den Jägern anuliert. Jedoch kam es gestern dazu das dem Schuss mit sehr hoher Wahrscheinlichkeit widerstanden wurde. (Teilweise passiert dies 2-3 hintereinander)

**Wie sollte es sich verhalten?**

Vorab muss vermerkt werden, das jeder Jäger das entsprechende Hitcap zum treffen aller Schussfähigkeiten besitzen muss! Ist diese Bedingung erfüllt, verbleibt eine Restchance von 1%  (Lvl 63 Elite) das dem Zauber dennoch widerstanden werden kann.

Dem Schuss soll zwar widerstanden werden können, jedoch sollte die Wahrscheinlichkeit deutlich geringer sein. Momentan liegt diese bei einem Wert von bis zu 15 - 20%, was bei ca. ~ 30 Schüssen, etwa 5-6 Resistenzen bedeutet.

**Schritte zur Reproduzierung**

Mit einem Jäger nach Naxxramas begeben und Gluth in den Kampf versetzen. Danach die Fähigkeit "" einsetzen sobald der "Enrage" geht und schauen, ob sich die 1% Marke erreichen lässt. (Zu beachten Hit-Cap muss vorhanden sein)

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Falsche Annahme gestern: Einlullender Schuss ist ein Zauber der Kategorie "Arkan". (Falsche Informationen meiner Seite aus)

In Wirklichkeit ist "Einlullender Schuss" ein Zauber der Kategorie "**Natur**"!

http://web.archive.org/web/20070314064721/http://www.thottbot.com:80/s19801

Gluth weist eine Resistenz von 75 für jede Zauberkategorie auf. Die Resistenz für "Natur" kann jedoch durch keinen Debuff (Ausnahme - TF) verringert werden. 

Demnach hat er grundlegend 75 Naturressi. Da der Wert nicht auf Null fallen kann, entsteht dadurch die zu hohe Resistenz gegen die Fähigkeit. 

Es gibt soweit keine Beweise dafür, das Gluth eine sehr hohe Naturresistenz aufweißt, was den Hunter dazu zwingen würde, Items anziehen zu müssen, die Zauberdurchdringung besitzen.

https://web-beta.archive.org/web/20061117163344/http://www.wowwiki.com:80/Gluth

Ich denke mit dem runtersetzen der Naturressi auf 0, sollte das Problem behoben sein. 

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Gluth: 
https://datenbank.classic-wow.org/?npc=15932

Enrage- Raserei:
https://datenbank.classic-wow.org/?spell=23128

Schuss:
https://datenbank.classic-wow.org/?spell=19801

**Comment by Dotox** [comment]
Hab die Resistenz reduziert.
