### ISSUE TITLE
Prinzessin muss sterben! - Quest

### ISSUE THREAD

**Issue by bsestef** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2261]
Welches Verhalten wird beobachtet?
Quest Mob erscheint nicht
Wie sollte es sich verhalten?
soll anwesend sein
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
![prinzessin](https://user-images.githubusercontent.com/31215943/29526685-bd9cd768-8696-11e7-9ce1-4b5ee0b8737b.JPG)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by WoW-Sid** [comment]
Der Mob ist nicht da, weil er da wo du gerade bist nun mal nicht spawnt!

Du bist bei Stonefields Kürbisfarm. Da spawnt sie erst seit Cataclysm (Patch 4.x).
Vorher und damit auch zu Classic-Zeiten steht sie auf Brackwells Kürbisbeet weit im Osten fett und fröhlich wie immer rum.

Nutze die Datenbank: https://datenbank.classic-wow.org/
