### ISSUE TITLE
[Jäger] Begleiter-HP zu niedrig

### ISSUE THREAD

**Issue by Throndar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2266]
**Welches Verhalten wird beobachtet?**
Pro 5 Punkte Ausdauer die der Begleiter durch Skillung oder Buffs bekommt wird 1 HP zu wenig berechnet. Bei 5 Ausdauer 49 anstatt 50 HP, bei 40 Ausdauer 392 anstatt 400 HP, usw.
Dies tritt erst bei jedem 5. zusätzlichen Punkt auf, d.h. bei 1-4 Ausdauer bekommt er richtigerweise 10-40 HP, bei 5-9 Ausdauer 49-89 HP, usw. **Vermutlich handelt es sich um einen Rundungsfehler!**

**Wie sollte es sich verhalten?**
Der Begleiter sollte 10 HP pro Ausdauerpunkt bekommen.

**Schritte zur Reproduzierung**
Begleiter-HP beobachten und mit verschiedenen Ausdauerbuffs buffen. 5/8 T2 funktioniert auch für 40 Ausdauer/392 HP. 

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Lvl 60 Nachtelf Jäger. Begleiter: Katze, Raptor

void Pet::UpdateMaxHealth()
{
    UnitMods unitMod = UNIT_MOD_HEALTH;
    float stamina = GetStat(STAT_STAMINA) - GetCreateStat(STAT_STAMINA);

    float value   = GetModifierValue(unitMod, BASE_VALUE) + GetCreateHealth();
    value  *= GetModifierValue(unitMod, BASE_PCT);
    value  += GetModifierValue(unitMod, TOTAL_VALUE) + stamina * 10.0f;
    value  *= GetModifierValue(unitMod, TOTAL_PCT);

    SetMaxHealth((uint32)value);
}

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

**Comment by Haudraufinix** [comment]
Ich lehne mich mal aus dem Fenster, aber hat das nicht damit zu tun, das einige Pet-arten mehr HP haben als andere?
Ein Bärhat beispielsweise 110% Baseleben vom Standart und eine Katze nur 90%

**Comment by Haudraufinix** [comment]
http://web.archive.org/web/20070329053754/http://petopia.brashendeavors.net:80/html/articles/stats_families.shtml

Da wäre nochn link zu den modifiern. 90 und 110% hatte ich falsch im kopf, aber geht in die richtung

**Comment by Throndar** [comment]
Hab es nochmal mit einem Pet mit einem Health Qualifier >1.0 aus der Liste ausprobiert, stimmt tatsächlich. War mir nicht bekannt. Thread kann geschlossen werden.
