### ISSUE TITLE
Häuptling der Winterfelle - Adds

### ISSUE THREAD

**Issue by Aeroas1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2270]
Welches Verhalten wird beobachtet?
Sie greifen nicht an und wirken keine Zauber. Ihnen kann kein Schaden zugefügt werden, da Sie immer entkommen. Sie folgen dem Häuptling weiter auf Schritt und Tritt, oder warten bei seinem Leichnam bis er wiederbelebt wird.
Wie sollte es sich verhalten?
Sie sollten angreifen und oder Zauber/Heilung wirken. Man sollte Ihnen Schaden zufügen können. Wenn der Häuptling tot ist, sollten Sie Ihre Patroullie alleine fortsetzen.
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
![wowscrnshot_082317_232721_-_kopie](https://user-images.githubusercontent.com/31292840/29640012-2b6b1724-885d-11e7-80ab-47397d171251.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Rukachi** [comment]
Gerade getestet kann ich bestätigen. Das nächste mal bitte mit den passenden Links macht es etwas einfacher:

Häuptling: https://datenbank.classic-wow.org/?npc=10738
2xSchamane: https://datenbank.classic-wow.org/?npc=7439

**Comment by dagochen** [comment]
grad auf dem testserver ausprobiert....frostshock....kettenblitzschlagschild....welle der heilung und feuerwasser der winterfelle saufen sie auch
