### ISSUE TITLE
[Quest] Die Zähmung der Bestie

### ISSUE THREAD

**Issue by Killerhamsta** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2272]
Welches Verhalten wird beobachtet?

Bei der Quest muss ein scheckiger Terroreber gezähmt und ein scheckiger Terroreber getötet werden. Das Töten eines scheckigen Terrorebers wird nicht angerechnet. Hierbei ist es egal, ob man einen umherlaufenden Eber erlegt oder den zuvor gezähmten Eber freilässt und diesen tötet. Das Problem bleibt bestehen trotz neu annehmen der Quest, WDB Ordner löschen, Neustart sowie Spielen ohne Addons. 

Wie sollte es sich verhalten?

Das Töten eines scheckigen Terrorebers sollte angerechnet werden, sodass die Quest beendet und abgegeben werden kann.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Quest "Die Zähmung der Bestie": _https://datenbank.classic-wow.org/?quest=6062_
Questgeber "Thotar Jägerlehrer": _https://datenbank.classic-wow.org/?npc=3171_
Item "Zähmerrute": _https://datenbank.classic-wow.org/?item=15917_
Questmob "Scheckiger Terroreber": _https://datenbank.classic-wow.org/?npc=3099_

**Comment by TithX** [comment]
Ist bei mir genauso.

Aus meiner Sicht ein ziemlich blöder Fehler, da alle neuen Spieler (Hunter), sofort wieder vom Server verschwinden, wenn so etwas elementares nicht funktioniert.

**Comment by Killerhamsta** [comment]
Hallo Dotox,

ich sehe, dass du den Fehler mit "fixed" markiert hast. Heißt das, dass die Quest nun funktionieren soll? Falls ja: habe die Quest gerade ausprobiert und der Fehler besteht bei mir nach wie vor.

Beste Grüße,
Killerhamsta

**Comment by Dotox** [comment]
Hey, ja der Fix ist auf dem PTR (Testserver).

**Comment by Killerhamsta** [comment]
Alles klar, ich hatte es lediglich auf dem normalen Nefarian Server ausprobiert. Dann bin ich guter Hoffnung, dass ich bald meinen Jäger weiterleveln kann ;-)
