### ISSUE TITLE
Fraktion Rabenhold

### ISSUE THREAD

**Issue by BeautiBeautiful** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2275]
Welches Verhalten wird beobachtet?
es ist nicht möglich als nicht-Schurke für diese Fraktion Ruf zu bekommen

Wie sollte es sich verhalten?
Kill der Syndikatsmitglieder sollten 5 Ruf geben bis 11999/12000 - danach 
abgabe von Pluderlisten

Schritte zur Reproduzierung
Syndikatsmitglieder umhauen :-)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://forum.buffed.de/topic/175166-guide-der-ultimative-fraktionenguide/#entry2921071
(runter scrollen bis Rabenhold) ... so wie es da steht hab ich es auch in Erinnnerung

Im Voraus danke für nen schnellen Fix :-) bei shendralar habt ihr auch nur 2 Wochen 
gebraucht :-)

LG

**Comment by dagochen** [comment]
Der Guide ist aber von Cataclysm...wenn du da noch ne Classic-Quelle findest, kann man da was machen.

**Comment by BeautiBeautiful** [comment]
Hoi,
ne, leider hab ich zu classic Zeiten nichts mehr gefunden, ausser meiner Erinnnerung. Denn ich hatte vor 
BC fast alle Fraktionen auf ehrfürchtig - ausser Dampfdruck -> Jazzrik killen bis ehrfürchtig dauerte n paar Jahre :-)

**Comment by BeautiBeautiful** [comment]
http://db.vanillagaming.org/?faction=349#npcs

**Comment by Mafyo** [comment]
[Currently there is only one known option to increase a player’s reputation with the Syndicate, and that is by killing members of the Ravenholdt Manor faction. Unfortunately, at the moment little is known about the rewards of increasing Syndicate reputation as nearly all Ravenholdt-affiliated NPCs only give 1 Syndicate Reputation Point. With all players starting at 32000/36000 Hated with the faction, it would require killing 10,000 Ravenholdt NPCs to reach Neutral status with the faction; in addition, you can only reach Neutral status with Syndicate, and if not to deter players further, none of the NPCs drop loot. ](http://wowwiki.wikia.com/wiki/Syndicate?oldid=385565)

**Comment by dagochen** [comment]
Du brauchst eine Quelle von 2005/2006. Quellen von späteren Addons oder anderen Privatservern akzeptieren wir nicht.

**Comment by BeautiBeautiful** [comment]
As of patch 2.3.0, additional Syndicate mobs give reputation.[2]

hat sich damit wohl erledigt :-(
