### ISSUE TITLE
Quest: Die Legende von Stalvan

### ISSUE THREAD

**Issue by atkratz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2278]
Welches Verhalten wird beobachtet?
Die Quest Truhe läßt sich nicht anklicken

Wie sollte es sich verhalten?
Es Sollte möglich ein die Truhe im Holzfällerlager des Osttals anzuklicken um den Brief zu bekommen

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://picload.org/view/rwpgdpwl/bildschirmfoto2017-08-29um08.2.jpg.html

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Bulli** [comment]
Ich habe die Quest erst gestern gemacht. Es ging problemlos.

**Comment by WoW-Sid** [comment]
Nein, einfach nur nein.

Dem Questlog auf dem Screenshot entnehme ich, dass du bei [Schritt 5 der Questreihe](https://datenbank.classic-wow.org/?quest=70) bist.
Der [niemals zugestellte Brief](https://datenbank.classic-wow.org/?item=910#contained-in-object) ist nicht in der [Truhe im Holzfällerlager](https://datenbank.classic-wow.org/?object=1562), sondern in einer [Truhe in Goldshire](https://datenbank.classic-wow.org/?object=1560).
Das Holzfällerlager kommt erst ein paar Schritte später. Kein Bug!

Für die Zukunft: https://datenbank.classic-wow.org/

**Comment by atkratz** [comment]
Hallo zusammen 

Danke für die Nachricht. 
Ich habe es zwar fünfmal gelesen mein quest Text aber ich werde es probieren. 

Danke.

**Comment by atkratz** [comment]
Ich schaue immer in die von dir verlinkte Datenbank. 
Wie gesagt war dann wohl mein Fehler. Da ich die quest in goldshire bekommen habe, habe ich mich wohl verlessen. 

Sorry für die Mehrarbeit.
