### ISSUE TITLE
Kampf Animation

### ISSUE THREAD

**Issue by atkratz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2279]
Hallo zusammen

Mir fällt auf, das wenn ich im Kampf bin mein Char sehr oft nicht in der Kampfhaltung steht. Er kämpft zwar trotzdem, dies ist aber sehr komisch. So klicke ich dann immer doppelt auf den Gegner in der Hoffnung das er in der Kampfhaltung ist :-)

**Comment by Dotox** [comment]
Das "Problem" ist mir auch schon aufgefallen. Mal sehen, ob wir noch weitere Informationen finden können, die helfen, die Ursache zu identifizieren.

**Comment by testear** [comment]
Sagen wir man ist mit 2 Zielen im Kampf A und B, man hat Gegner A im Ziel und greift an, klickt man jetzt während A noch lebt auf B um B anzugreifen wird keine Angriffsanimation ausgeführt obwohl der Angriff normal weiterläuft.
Mit tabben hat man dieses Problem nicht - das tritt nur beim Klicken auf.
