### ISSUE TITLE
Tyrs Hand NPCs 

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2280]
**Welches Verhalten wird beobachtet?**
Sämtliche Npcs in Tyrs Hand hinterlassen nach der Tötung zu wenig Silber bzw. Kupfer. Im Durchschnitt hinterlassen diese nur 5-8 Silber.

**Wie sollte es sich verhalten?**
Die Npcs (in der unteren Liste vollständig enthalten) sollten Beträge von 10 bis 30 Silber droppen. Wie genau die Verteilung der Silber-Anteile ist, ist schwer nachzuvollziehen.

**Schritte zur Reproduzierung**
Nach Tyrs Hand begeben und die Npcs dort töten.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Nachweise über die Droprate von Silberbeständen: 

http://wow.ingame.de/forum/threads/105563-farmen-in-tyrs-hand/page2?s=b406db0b548255b365713194077a0915

http://www.taultunleashed.com/worldofwarcraft-discussions/best-spot-to-farm-lvl-60-t37128.html

Hier sieht man einen Hunter erfolgreich Gegner in Tyrs Hand töten. Dabei hinterlassen diese Silberbestände von 8 bis 30 Silber, je nach Gegnerkategorie.

https://www.youtube.com/watch?v=qbXsPT1Rhv0

https://www.youtube.com/watch?v=_xipqfmG3Kg

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Scharlachroter Inquisitor:
https://datenbank.classic-wow.org/?npc=15162

Scharlachroter Plätorianer:
https://datenbank.classic-wow.org/?npc=9448

Scharlachroter Erzmagier:
https://datenbank.classic-wow.org/?npc=9451

Scharlachroter Kurat:
https://datenbank.classic-wow.org/?npc=9450

Scharlachroter Kleriker:
https://datenbank.classic-wow.org/?npc=9449

Scharlachroter Verzauberer:
https://datenbank.classic-wow.org/?npc=9452

Scharlachroter Wärter:
https://datenbank.classic-wow.org/?npc=9447

Kreuzzüglerlord Valdelmar:
https://datenbank.classic-wow.org/?npc=11898

**Comment by Dotox** [comment]
Danke Omega!

**Comment by Elderus** [comment]
Danke Omega für den ausführlicheren Bugtracker-Eintrag.

**Comment by stva23** [comment]
Also ich farme häufig in TH und habe immer Silber im zweistelligen Bereich pro Mob (12-20). Ob es früher auf blizz-classic mehr war kann ich nicht mehr wirklich sagen, es gab halt zusätzlich noch Worldepics.

**Comment by Horim** [comment]
Werte zwischen 8 und 24 Silber könnte ich auf dem ptr feststellen. Der Durchschnitt lag dabei bei ca. 18 Silber.

**Comment by stva23** [comment]
Bei den Mobs unten ist es etwas mehr geworden, für die 

```
Scharlachroter Plätorianer:
https://datenbank.classic-wow.org/?npc=9448

Scharlachroter Erzmagier:
https://datenbank.classic-wow.org/?npc=9451
```
kann ich das aber nicht feststellen. Gefühlt sogar weniger (nach ca. 1h Farmen)
