### ISSUE TITLE
[Naxxramas] Thaddius Wirbelwind

### ISSUE THREAD

**Issue by Horim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2281]
**Welches Verhalten wird beobachtet?**
Die Fähigkeit Wirbelwind von Kriegern trifft nur sehr selten bei Thaddius. Nur wenn man sehr nah drann steht erfolgen Treffer. Bei max. Hitbox ist es nicht möglich damit zu treffen.

**Wie sollte es sich verhalten?**
Wirbelwind sollte immer treffen wenn man sich in der Hitbox von Zielen befindet und sogar bei 8y Distanz. Ich glaube das Verhalten ist mit #1457 vergleichbar.

**Schritte zur Reproduzierung**
Auf dem Testserver in Naxxramas zu Thaddius gehen und Wirbelwind anwenden. Je nach Distanz zum Boss sind keine Treffer möglich.

**[Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)]**
- [Thaddius ](https://datenbank.classic-wow.org/?npc=15928)
- [Wirbelwind](https://datenbank.classic-wow.org/?spell=1680)

**Comment by Herlot** [comment]
Trifft auch für andere Bosse zu. Bei Magmadar in MC zum Beispiel. Bei Nef müsste es das Problem auch geben. Falls man den Fehler findet, könnte man nochmal die Raidbosse allgemein überprüfen.

**Comment by Horim** [comment]
Das scheint eher ein Boss-spezifischer Fehler zu sein. Glaube mich erinnern zu können das bei Thaddius erst vor kurzem was wegen der Hitbox gemacht wurde, vielleicht wurde das hierbei übersehen. Der Fix bei C'thun damals war auch Boss-spezifisch und nicht allgemeiner Natur.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2287
