### ISSUE TITLE
Quest: Krone der Erde (Teldrassil)

### ISSUE THREAD

**Issue by Morphling101** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2282]
Welches Verhalten wird beobachtet? Quest kann bei Abschluss ein zweites Mal angenommen werden. Sobald man die zweite Quest annimmt und gleichzeitig die Folgequest im Questlog hat, stürzt das Spiel ab.

Wie sollte es sich verhalten? Quest sollte nicht ein zweites Mal annehmbar sein.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.) Char Lefya (Level 10 Nachtelfen Druide) ist zur Zeit unbrauchbar, da das Spiel bei jedem Login direkt abstürzt. Wenn möglich, müsste der Char zurückgesetzt werden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
verlinken

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/783
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1415
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1590
