### ISSUE TITLE
scholomance

### ISSUE THREAD

**Issue by pinkemage** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2284]
Welches Verhalten wird beobachtet? die minibosse vorm endboss droppen selten bis gar keine items in den meisten fällen. damit ist es kaum möglich zb das buchband füt paladine zu bekommen da keine items droppen.

Wie sollte es sich verhalten? es sollte jeder miniboss aus dem gemeinsamen loottable etwas droppen. 

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by rachmin** [comment]
Von den 6 Minibossen vor Gandling hat nur Lord Alexei Barov einen garantierten raren Drop (seit Patch 1.4; ist soweit ich das kenne auch implementiert). Die restlichen fünf Minibosse können, aber müssen kein rares Item droppen.

Siehe etwa zu [Der Ravenier](http://web.archive.org/web/20060613194411/http://wow.allakhazam.com:80/db/mob.html?wmob=10507#): "I would like to make note that last night he dropped...nothing. [außer Geißelstein]"
Oder zu [Krastinov](http://web.archive.org/web/20060720203405/http://wow.allakhazam.com:80/db/mob.html?wmob=11261#): "Nice drops on the table up there, but low rates...."

Zum Buchband gibt es bspw. diese motivierende Statistik: [0.46% chance to drop. (206 in 45,123) (Juni 2006)](http://web.archive.org/web/20060629011019/http://wow.allakhazam.com:80/db/item.html?witem=23201#).

**Comment by pinkemage** [comment]
toll das auch alexei barov in den letzten runs eher selten überhaupt was bei hatte. sollte vieleicht mal überprüft werden bzw falls andere spieler das gleiche beobachten bitte ich um beiträge
