### ISSUE TITLE
Zu hohe Reparaturkosten für Leder, Schwere Rüstung und Platte

### ISSUE THREAD

**Issue by Quaregnon** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2285]
**Welches Verhalten wird beobachtet?**

Die vier Rüstungsklassen bezahlen unterschiedliche hohe Beträge für die Reparatur gleichwertiger Items. Die Kosten für die Reparatur von Stoffgegenständen sind am niedrigsten und steigen mit jeder Rüstungsklasse an, sodass Plattengegenstände am teuersten zu reparieren sind.

**Wie sollte es sich verhalten?**

Die Kosten für die Reparatur von gleichwertigen Gegenständen sollte bei allen vier Rüstungsklassen gleich sein und den Kosten für die Reparatur von Stoffgegenständen entsprechen. Die Reparaturkosten für Leder-, Schwere Rüstungs- und Plattengegenstände müssen dementsprechend angepasst werden.

**Schritte zur Reproduzierung**

Exemplarisch getestet mit einem Hunter (Schwere Rüstung) und einem Mage (Stoffrüstung) in Full T2 (=gleiche Itemqualität). Keine anderen, Reparaturkosten verursachenden Gegenstände waren angelegt. Beide Charaktere sind in ihrem Full T2 genau einmal gestorben und haben danach beim selben Händler mit gleichem Discount repariert. Ergebnis:

Reparaturkosten Stoff: 83s20k

Reparaturkosten Schwere Rüstung: 1g23s38k

Von diesem Experiment abgesehen, ist es vermutlich den meisten Spielern bewusst, dass die Kosten für die Rüstungsklassen unterschiedlich sind. Klagen darüber, dass ein Krieger >30g für eine volle Reparatur bezahlt, während es bei einem Mage nur um die 10g sind, hat man schon oft gehört.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

World of Warcraft Patch 1.8.0:

"The cost per point of durability to repair plate, chain, and leather items has been reduced to be equal to the cost of repairing cloth items of the same quality."

Quelle: http://wowwiki.wikia.com/wiki/Patch_1.8.0

Ich habe überprüft, dass bis zum Patchstand 1.12.1 keine Änderung oder Rücknahme dieses Features stattgefunden hat.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Keine zu verlinkenden Items etc.

**Comment by Larirawiel** [comment]
Hi,

ne, das müsste schon passen. Der Punkt ist nämlich, die Rüstungsklassen haben unterschiedliche Haltbarkeit. Man sieht es hier im Screenshot:

http://666kb.com/i/dmdfdrsha271bqg2f.png

Man sieht, Leder hat 35 Haltbarkeitspunkte, Platte 45. Wenn man jetzt stirbt dann verlieren alle angelegten Gegenstände 10% Haltbarkeit. Das macht bei Leder 3,5 Haltbarkeit, bei Platte 4,5. Und deshalb ist ein Sterben in Platte teurer als in Leder oder Stoff oder Kette. Und deshalb ist auch ein Sterben in Epics teurer als in blau oder grün. Weil Epics ebenfalls mehr Haltbarkeitspunkte haben.

Grüße

**Comment by Quaregnon** [comment]
Ich glaube, du hast Recht Lari. Das mit den unterschiedlichen Haltbarkeitspunkten habe ich in der Tat übersehen bzw. nicht berücksichtigt. 

Jetzt müsste man nochmal testen, ob die Kosten pro einzelnem Punkt Haltbarkeit tatsächlich gleich sind, aber ich gehe mal davon aus, dass das der Fall ist.

**Comment by dagochen** [comment]
Ich hatte das bereits einmal überprüft, da es vor der Änderung von Blizzard einmal so war, dass schwere Rüstung und Plattenrüstungen viel teurer pro Punkt Haltbarkeit waren zu reparieren. Das ist bei uns alles korrekt so ;) Liegt tatsächlich nur an der Menge an Haltbarkeit.
