### ISSUE TITLE
Willensbrecher der Qiraji in AQ 40  -  Gedankenschinden - Berserkerwut/Todeswunsch

### ISSUE THREAD

**Issue by Lenymo-Nefarian** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2286]
**Welches Verhalten wird beobachtet?**
Die Willensbrecher der Qiraji casten den Zauber „Gedankenschinden“. Man kann als Krieger den Debuff mit „Berserkerwut“ und „Todeswunsch“ unterbrechen.

**Wie sollte es sich verhalten?**
Man sollte den Zauber nicht mit „Berserkerwut“ und „Todeswunsch“ unterbrechen können. 

**Schritte zur Reproduzierung**
Krieger in AQ40 bei den Willensbrecher Gruppen in der Berserkerhaltung. 

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
„Berserkerwut“ liegt auf der Taste 2 und „Todeswunsch“ auf der Taste T. Hab die beides Videos mal extra gemacht damit man das ganze sieht. 

[mit Berserkerwut](https://www.youtube.com/watch?v=QlgFIC8KdR0&feature=youtu.be)

[mit Todeswunsch](https://www.youtube.com/watch?v=5ZOk2GeGyOY&feature=youtu.be)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

[Willensbrecher](https://datenbank.classic-wow.org/?npc=15246)

[Berserkerwut](https://datenbank.classic-wow.org/?spell=18499)

[Todeswunsch](https://datenbank.classic-wow.org/?spell=12328)

**Comment by Horim** [comment]
Das [Gedankenschinden](https://datenbank.classic-wow.org/?spell=26044) ist ein Fear-Effekt wenn ich die Datenbank richtig verstehe. WotF von UDs und Zwergen-Antifear gehen auch. 

Soweit erstmal kein Fehler, ob das Gedankenschinden ein Fear-Effekt sein sollte ist ein anderes Thema.

**Comment by Lenymo-Nefarian** [comment]
Dann müsste aber der [Manabrand](http://datenbank.classic-wow.org/?spell=26049) laut Datenbank auch ein Fear-Effekt sein und somit sollte man ihn auch unterbrechen können. Dies ist aber nicht der Fall.

**Comment by Dotox** [comment]
Die Werte in der Web-Datenbank stimmen leider nicht immer.

**Comment by Horim** [comment]
Der Manabrand ist irreführend, da dies ein Terror/horrify effect ist, analog zum Deathcoil. Auch hier müsste man eher recherchieren ob das so sein soll. Der bugtracker Eintrag liefert nur keine Infos zu den skills von damals, bzw. Keine Quellen die beweisen daß es hier falsch ist.
