### ISSUE TITLE
Despawnzeit und plötzliches Verschwinden Wässriger Eindringlinge

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2290]
Welches Verhalten wird beobachtet?
Zwei Probleme in Verbindung mit den "Wässrigen Eindringlingen" (Elementare der Elementarinvasion in Winterspring).
(1) Die Leichen der "Wässrigen Eindringlinge" despawnen z.T. "zu schnell", unabhängig davon, ob sie gelootet worden sind oder nicht bzw. unabhängig davon, ob sie Loot hatten oder nicht. Manchmal despawnen sie sofort, nachdem sie getötet worden sind; manchmal wenige Augenblicke danach; in jedem Fall zu schnell. (Eine mögliche Erklärung könnte hierbei sein, dass, solang die Prinzessin lebt, die Elementare nachspawnen und daher ihr Verschwinden nach dem Tod beschleunigt ist.)
(2) Wässrige Eindringlinge, die mit Prinzessin Tempestria patroullieren, verschwinden plötzlich, wenn die Prinzessin getötet, die Elementare dabei (davor/danach) resettet worden sind (durch Wegkiten und Evade oder Totstellen) und dann erneut angegriffen werden. Die Elementare machen dabei die Animation, als ob sie getötet worden sind, obwohl sie noch bekämpft werden, und despawnen komplett. Das tritt wiederum nicht immer bei jedem der Patrouillieren-Elementaren auf, aber häufig genug, sodass es auffällt.

Wie sollte es sich verhalten?
Die Leichen sollten nicht so schnell despawnen.
Die Elementare, die mit Tempestria patroullieren, sollten nicht plötzlich despawnen.

Schritte zur Reproduzierung
Siehe Beschreibung oben.
(1) Elementare töten, Despawnzeit der Leichen beobachten.
(2) Nur Prinzessin töten, Patrouille resetten, danach diese angreifen, Verhalten beobachten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Keine.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Wässriger Eindringling: https://datenbank.classic-wow.org/?npc=14458
Prinzessin Tempestria: https://datenbank.classic-wow.org/?npc=14457

**Comment by Dotox** [comment]
1) kann ich nicht reproduzieren, die Elemente verschwinden recht schnell aber rest, wenn sie gelootet wurden.
2) die elemente sind mit der Prinzessin gelinkt und agieren daher wie beschwörte pets; heißt, sie despawnen wenn ihr owner nicht mehr verfügbar ist.
