### ISSUE TITLE
Gildensatzung lässt sich nicht mehr öffnen

### ISSUE THREAD

**Issue by Tascone** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2292]
Ich habe gestern die Gildensatzung erworben und ein paar leute haben unterschrieben, einen Tag später lässt sich die Satzung nicht mehr öffnen um den Namen zu ändern, bzw. um weite Leute unterschreiben zu lassen.

Deaktivierung der AddOns und ein Relogg brachten kein erfolg.

Die Satzung befindet sich im Standartrucksack

**Comment by Dotox** [comment]
Satzung verschieben und nochmal versuchen. Ein Problem ist nicht bekannt.
