### ISSUE TITLE
Paladin Segen (buffs) stacken

### ISSUE THREAD

**Issue by NukNukPils** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2295]
Welches Verhalten wird beobachtet?
Paladin Segen stacken manchmal. So ist heute bei Lethon 2x großer Segen des Lichts auf dem Tank. 
Der Buff stackt auch effektiv und ist nicht nur visuell. 
Gesehen hab ich auch schon doppelten SDR buff. 
Habens grade in IF nochmal getestet (siehe zweiten Youtube-Link).

Edit: Funktioniert nur mit SDL, der ist jedoch sehr oft stackbar.

Wie sollte es sich verhalten?
Paladin Segen sollten nicht stacken.

Schritte zur Reproduzierung
Beliebig viele Paladine den selben Segen buffen lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://www.youtube.com/watch?v=c53pS7hRJBQ&feature=youtu.be
https://www.youtube.com/watch?v=MF2EaxWle8o&feature=youtu.be

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?npc=14888
https://datenbank.classic-wow.org/?spell=25890

MfG
KühlesPils / NukNuk

**Comment by Dotox** [comment]
Vielen Dank!
