### ISSUE TITLE
"Rückkopplung" wird nicht korrekt gelehrt (Mensch Priester Racial)

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2296]
Welches Verhalten wird beobachtet?
Menschen Priester können ab lvl20 über eins von zwei Quests ihr zweites Priesterracial gelehrt bekommen ("Feedback" bzw. "Rückkopplung", Rang1).
Jedoch wird der Zauber "Rückkopplung" wahrscheinlich durch eine fehlerhafte Questbelohnung bei einem der zwei Quests nicht gelehrt (statt dessen wird noch einmal "Verzweifeltes Gebet" gelehrt). Weil das (fehlerhafte) Quest dennoch abgeschlossen wird, schließt es das andere richtige funktionierende Quest, sodass ein Mensch Priester den Vorgang nicht rückgängig machen und die Fähigkeit nachträglich nicht mehr selber erlernen kann.

Mit anderen Worten: Mein Mensch Priester hat damals auf lvl20 das "falsche", weil fehlerhafte Quest abgeschlossen und somit Rückkopplung (Rang1) nicht gelehrt bekommen. Mein Priester kann "nur" Verzweifeltes Gebet als Priesterracial. Andere Menschen Priester haben hingegen das "richtige", weil wie vorgesehen funktionierende Quest abgeschlossen und den Zauber "Rückkopplung" erhalten.

Nochmals anders beschrieben: Scheinbar muss Mensch Priestern, die o.g. Problem haben (keine "Rückkopplung" Rang1 gelehrt bekommen, wenn/weil sie das "fehlerhafte Quest abgeschlossen haben), nachträglich der Zauber "Rückkopplung" (Rang1) gelehrt werden.

Wie sollte es sich verhalten?
Ab lvl20 sollte ein Mensch Priester durch das Abschließen eines der zwei Quests "Arkane Rückkopplung" die Fähigkeit "Rückkopplung" (Rang 1) gelehrt bekommen.
Das Quest startet entweder bei Bruder Joshua in Stormwind oder Hohepriester Rohan in Ironforge.
Das Quest beendet jeweils Hohepriesterin Laurena in Stormwind, die somit auch den "Zauber" auf einen wirkt.
Das Quest von Bruder Joshua lehrt richtigerweise den Zauber "Feedback" (Rückkopplung).
Das Quest von Hohepriester Rohan lehrt fälschlicherweise erneut "Desperate Prayer" (lvl10 Rassenbonus von Mensch Priester) und nicht "Feedback".

Schritte zur Reproduzierung
Optional jeweils davor: Menschen Priester auf 10 leveln und eines der Quest für "Verzweifeltes Gebet" abschließen, um den ersten Racial zu erhalten.
Menchen Priester auf 20 leveln, Bruder Joshuas o.g. Quest annehmen und abschließen, sodass dem Mensch Priester sein 2. Racial gelehrt wird.
Mensch Priester auf lvl20 leveln, Hohepriester Rohans o.g. Quest annehmen und abschließen. Nun wird anstatt dem 2. Racial "Rückkopplung" nochmal "Verzweifeltes Gebet" gelehrt.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Priester erlernen jeweils über ein Quest ab lvl10 und lvl20 zusätzlich zu den normalen Priesterfähigkeiten zwei weitere Zauber, die von der jeweiligen Rasse abhängen.
Menschen Priester erlernen dabei das Verzweifelte Gebet (lvl10) und Rückkopplung (lvl20).
Durch eine fehlerhafte Questbelohnung wird jedoch Rückkopplung nur bei einem der zwei Quest gelehrt.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Zauber "Rückkopplung" für Menschen Priester: https://datenbank.classic-wow.org/?spell=13896
Zauber "Verzweifeltes Gebet" für Menschen Priester: https://datenbank.classic-wow.org/?spell=19338

Bruder Joshua: https://datenbank.classic-wow.org/?npc=5489
Sein richtig funktionierendes Quest "Arkane Rückkopplung": https://datenbank.classic-wow.org/?quest=5676

Hohepriester Rohan: https://datenbank.classic-wow.org/?npc=11406
Sein fehlerhaftes Quest "Arkane Rückkopplung": https://datenbank.classic-wow.org/?quest=5677

Hohepriesterin Laurena: https://datenbank.classic-wow.org/?npc=376

Weiterführende Informationen zu Priester-Racials via Wowpedia (hier Jan 2007): https://wow.gamepedia.com/index.php?title=Priest_racial_abilities&oldid=394818
Siehe Patchnotes 1.10 zu den Priester-Änderungen etwa: https://wow.gamepedia.com/Patch_1.10.0

Das Problem tritt/trat beispielsweise auch auf anderen Vanilla-Servern auf: https://forum.nostalrius.org/viewtopic.php?f=45&t=37545

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2276
