### ISSUE TITLE
Spell Despawnt Nicht! (Sillithus)

### ISSUE THREAD

**Issue by LinkPegi16** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2298]
**Welches Verhalten wird beobachtet?**
Die Staubstürmer in Sillithus wirken einen "Zauber" (siehe unten) der, sich aber nach dem wirken nicht auflöst.
**Wie sollte es sich verhalten?**
Der gewirkte Zauber sollte (wahrscheinlich) in ein paar sek. despawnen.
**Schritte zur Reproduzierung**
Staubstürmer angreifen lassen und den Zauber "durchgehen" lassen.
**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://www.directupload.net/file/d/4839/gvcibwpw_jpg.htm
**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Staubstürmer: https://datenbank.classic-wow.org/?npc=11744
Blitzwolke: https://datenbank.classic-wow.org/?spell=19513

**Comment by Ryanstekken** [comment]
Sieht mir eher nach nem bekannten Fehler auf der bei manchen Spielern in seltenen Fällen auftaucht.
Macht sich meist bei den Schlafwolken der Worldbosse bemerkbar. 
Der Fehler tritt dann aber auch nur bei dem/den Spieler/n auf und nicht bei jedem und beschränkt sich darauf, dass diese aoe-effekte nicht despawnen. 
Ne wirklich 100% Lösung kann ich dir dafür gerade aber nicht nennen ich persönlich hatte diesen Fehler erst einmal und der erledigte sich von selbst.
Bleibt das übliche WDB Ordner löschen und co. 
Aber um nen fehlerhaften Spell handelt es sich hier nicht.

**Comment by Dotox** [comment]
Handelt sich hier nur um einen visuellen Fehler, klappt nach dem Relogg wieder.
