### ISSUE TITLE
Arcane Crystals aus kleinen Thorium

### ISSUE THREAD

**Issue by sk4dy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2299]
Welches Verhalten wird beobachtet?
Beim Abbau von kleinen Thoriumvorkommen kann man keine Arkankristalle bekommen

Wie sollte es sich verhalten?
Auch zu Classic zeiten gaben kleine Thorium Vorkommen Arkankristalle

Schritte zur Reproduzierung
Kleine Thoriumvorkommen abbauen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Nach vielen Farmstunden zu klassik Zeiten und einem miesen Luck beim farmen war ich einer der wenigen die aus kleinen Thoriumvorkommen mehr Kristalle bekamen als aus großen. Die Dropchance pro hit der node war bei beiden Vorkommen gleich. Das große Vorkommen kann nur ca doppelt sooft abgebaut werden bis es verschwindet, was die dropchance pro node erhöht.
http://wow.allakhazam.com/forum.html?forum=69&mid=111459231230726706 (letzter Post)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Quelle die näher an unserem Patchstand ist: http://wowwiki.wikia.com/wiki/Arcane_Crystal?oldid=301899
