### ISSUE TITLE
Nachtelf Druide: Größe von Katzen & Reisegestalt

### ISSUE THREAD

**Issue by ToniStark87** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2302]
**Welches Verhalten wird beobachtet?**
Mir ist aufgefallen, dass die Animationen des laufenden Druiden in Reise und Katzengestalt unheimlich träge und zähflüssig erscheinen. Es entsteht fast der Eindruck als würde sich der verwandelte Charakter in Zeitlupe bewegen. Das liegt natürlich nur einem optischen Effekt zugrunde, der durch die enorme größe der Figur entsteht.
Ist das bisher noch niemandem Aufgefallen ?

**Wie sollte es sich verhalten?**
Katzen und Reisegstalt sollten kleiner sein.

Schritte zur Reproduzierung
-/-

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Als Referenz der wow-classic server zu einem anderen: 
wow-classic groß:
![travel 1](https://user-images.githubusercontent.com/31835413/30256477-6f1246da-96ab-11e7-9d6f-9471311f5c0c.PNG)
normal:
![travel 2](https://user-images.githubusercontent.com/31835413/30256498-8c8bba8e-96ab-11e7-80ab-1a27b0ccc3c7.PNG)
wow-classic groß:
![cat 2 2](https://user-images.githubusercontent.com/31835413/30256516-b2573c3e-96ab-11e7-9abf-0c19182b5dbb.PNG)
normal:
![cat 1 1](https://user-images.githubusercontent.com/31835413/30256512-a9ecbbb4-96ab-11e7-9cde-86f38617e186.PNG)

(Schatten und Wandtexturen sind geändert, sizes aber nicht.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
-/-

**Comment by Dotox** [comment]
Quelle?

**Comment by Slimmer2** [comment]
Ist das Gerade ein Vergleich von Classic und eine Erweiterung nach Classic?
Das Andere Bild ist mindestens BC, man sieht den Gildentresor.
