### ISSUE TITLE
Felspirscher der Silithus Quest "Noggles Letzte Hoffnung" fälschlicherweise Elite

### ISSUE THREAD

**Issue by Thorval** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2303]
Welches Verhalten wird beobachtet?
Die Spinnen der Art Felspirscher der Silithus Quest "[Noggles Letzte Hoffnung](https://datenbank.classic-wow.org/?quest=8278)" sind fälschlicherweise Elite.
Wie sollte es sich verhalten?
Die Felspirscher sollten normale Spinnen sein und keine Elite.
Schritte zur Reproduzierung
In Silithus südlich der Burg Cenarius findet man Felspirscher entlang der Straße mit Level 57-59 Elite statt normal.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Felspirscher sollten normale Spinnen sein, s. Einträge in [Classic-WoW-Datenbank](https://datenbank.classic-wow.org/?npc=11739) und in [WoWWiki](http://wowwiki.wikia.com/wiki/Rock_Stalker).
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Nifexx** [comment]
siehe https://wow.gamepedia.com/Rock_Stalker
Erst mit Patch 2.3.0 waren die Spinnen keine Elite-Mobs mehr.

**Comment by Thorval** [comment]
Oh, danke für die Info. Dann kann man sich also bei den Datenbänken von Classic-WoW, WoWWiki (s.o.) und [Vanillagaming ](http://db.vanillagaming.org/?npc=11739) nicht darauf verlassen, dass die Informationen dem Stand Patch 1.12.1 entsprechen.
Ich denke, dann kann mein "Bug"-Report geschlossen werden.
