### ISSUE TITLE
Icon vom Buff des [Zaumzeug des Rappen] ist falsch.

### ISSUE THREAD

**Issue by Bulli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2307]
**Welches Verhalten wird beobachtet?**
Das Icon vom Pferd neben Minimap ist falsch, nach dem Aufsitzen. Das Icon dürfte vom Hexer Mount stammen. Das Icon ist auch in der verlinkten Datenbank falsch. Andere Datenbanken zeigen das richtige Symbol.

**Wie sollte es sich verhalten?**
Das Icon sollte richtig sein.

**Schritte zur Reproduzierung**
[Zaumzeug des Rappen] benutzen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
![unbenannt](https://user-images.githubusercontent.com/1497706/30444343-ea643b66-9982-11e7-8cf1-057d5bf9ac6c.JPG)
![unbenannt2](https://user-images.githubusercontent.com/1497706/30444430-3d1a0138-9983-11e7-91d3-af32d7b53bee.JPG)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?item=2411

**Comment by Dotox** [comment]
Kann das Problem nicht feststellen. ggf. WDB löschen
