### ISSUE TITLE
Q Krankhafter Hass

### ISSUE THREAD

**Issue by GasserMarkus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2309]
Hallo, bei dieser Q Krankhafter Hass (Nachtelfen q) sind paar NPC's in der Höhle die wärend dem Kapf abhauen und  "Entkommen". Man hat kaum/ keine Chance diese zu töten weil sie sich alle paar sec. regenerieren.

Würde mich freuen wen ihr dies beheben könntet 

Mfg.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2356
