### ISSUE TITLE
T3 Set Paladin

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2310]
[Pala T3 Set (Erlösung)](https://datenbank.classic-wow.org/?itemset=528)

**Welches Verhalten wird beobachtet?**
2er Bonus: Zauber [Richturteil des Lichts](https://datenbank.classic-wow.org/?spell=20343) heilt trotz des [2er Sotboni](https://datenbank.classic-wow.org/?spell=28775) weiterhin nur 61.

6er Bonus: Zauber [Holy Power](https://datenbank.classic-wow.org/?spell=28789#see-also-ability) procct aktuell gar nicht. Siehe auch Spells - sollte durch die Zauber [Flash of Light](https://datenbank.classic-wow.org/?spell=19943) und [Holy Light](https://datenbank.classic-wow.org/?spell=25292) proccen.
https://datenbank.classic-wow.org/?spell=28790
https://datenbank.classic-wow.org/?spell=28791
https://datenbank.classic-wow.org/?spell=28793
https://datenbank.classic-wow.org/?spell=28795

**Wie sollte es sich verhalten?**
2er Bonus: [Richturteil des Lichts](https://datenbank.classic-wow.org/?spell=20343) sollte 81 heilen.
6er Bonus: Die Zauber [Flash of Light](https://datenbank.classic-wow.org/?spell=19943) und [Holy Light](https://datenbank.classic-wow.org/?spell=25292) sollten beim Ziel (je nach Klasse) die folgenden Buffs zu X% Chance  gewähren:  
https://datenbank.classic-wow.org/?spell=28790
https://datenbank.classic-wow.org/?spell=28791
https://datenbank.classic-wow.org/?spell=28793
https://datenbank.classic-wow.org/?spell=28795

**Schritte zur Reproduzierung**
Volles Set anziehen und entsprechende Zauber wirken.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://wowwiki.wikia.com/wiki/Redemption_Armor 
http://wowwiki.wikia.com/wiki/Holy_Power_(set_bonus)   
Unklar ist, ob doppelt genannte Klassen 2 Buffs erhalten?

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein**
Set: https://datenbank.classic-wow.org/?itemset=528
Siegel des Lichts: https://datenbank.classic-wow.org/?spell=20343
Flash of Light: https://datenbank.classic-wow.org/?spell=19943
Holy Light: https://datenbank.classic-wow.org/?spell=25292

2er Setboni Zauber: https://datenbank.classic-wow.org/?spell=28775
6er Setboni Zauber: https://datenbank.classic-wow.org/?spell=28789#see-also-ability
Unterzauber davon: 
https://datenbank.classic-wow.org/?spell=28790
https://datenbank.classic-wow.org/?spell=28791
https://datenbank.classic-wow.org/?spell=28793
https://datenbank.classic-wow.org/?spell=28795

Der Bugreport kann gerne ergänzt werden!

Folglich: 4er und 8er Setboni funktionieren.

Gruß

**Comment by Sheed90** [comment]
Hey Dotox, vielen Dank für die schnellen Änderungen!

Siegel des Lichts heilt weiterhin nur 61, fehlt dir da noch eine Quellenangabe?

**Comment by Dotox** [comment]
Hey, ne ist noch nicht auf dem PTR, siehe Label :)

**Comment by weedlord100** [comment]
funktioniert super. danke danke

was ich mich gerade frage ob der 8er set Bonus schon früher so mit addheal skaliert hat.

**Comment by Sheed90** [comment]
2er Boni und 6er Boni klappen jetzt!
