### ISSUE TITLE
T3 Set Hexenmeister

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2311]
[T3 Hexenmeister](https://datenbank.classic-wow.org/?itemset=529)

**Welches Verhalten wird beobachtet?**
2 pieces: Your Shadow Bolts now have a chance to heal you for 270 to 331.
Zurzeit ist die Chance 100%
8 pieces: Reduces health cost of your Life Tap by 12%.
Das Set Reduziert die erhaltende Mana und die Reduzierung der HP von Aderlass ensprechen auch keine 12%.

**Wie sollte es sich verhalten?**
2 pieces: Your Shadow Bolts now have a chance to heal you for 270 to 331.
Die Chance sollte ca. 10% betragen.
8 pieces: Reduces health cost of your Life Tap by 12%.
Aderlass sollte 12% weniger HP kosten aber trotzdem soviel Mana zurückgeben, als würde es 1:1 des Spells konsumieren. Beispiel in Zahlen: 100 HP gegen 112 Mana.

**Schritte zur Reproduzierung**
Das Set anlegen und Shadow Bolts casten.
Das Set anlegen und Aderlass mit dem 8er Bonus verwenden.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
2er Set Bonus:
http://de.wowhead.com/spell=28831/blutsaugen#english-comments

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?itemset=529 T3 Set
https://datenbank.classic-wow.org/?spell=11661 Shadow Bolt
https://datenbank.classic-wow.org/?spell=28831 2er Bonus
https://datenbank.classic-wow.org/?spell=28830 8er Bonus Life Tap

Ergänzungen sind gerne gesehen.

**Comment by Slimmer2** [comment]
Dein Beispiel ist etwas falsch.
Wenn 112 Mama 100%sind dann sollte es 98,8 Gesundheit abgezogen werden
