### ISSUE TITLE
T3 Set Magier

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2312]
[T3 Set Magier](https://datenbank.classic-wow.org/?itemset=526)

**Welches Verhalten wird beobachtet?**
6 pieces: Your damage spells have a chance to cause your target to take up to 200 increased damage from subsequent spells.
Über 200 Spells gecastet und keine Verwundbarkeit am Target ausgelöst.

**Wie sollte es sich verhalten?**
Die Chance sollte pro Spell eine 20% Chance haben Elementare Verwundbarkeit aufs Target auszulösen (Debuff).

**Schritte zur Reproduzierung**
6 Teile des Sets anziehen und Spells auf ein Mob casten.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://www.wowhead.com/spell=28771/elemental-vulnerability

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?spell=28771 Elementare Verwundbarkeit
https://datenbank.classic-wow.org/?itemset=526 T3 Set

**Comment by Dotox** [comment]
Die Quellenangabe für 20% ist leider nicht legitim.

**Comment by dagochen** [comment]
![wowscrnshot_092117_122142](https://user-images.githubusercontent.com/5236186/30691282-8ff0c3c6-9ec7-11e7-9b8c-8c235e827560.jpg)
![wowscrnshot_092117_122138](https://user-images.githubusercontent.com/5236186/30691281-8ff081c2-9ec7-11e7-97f6-f6d216e77278.jpg)

**Comment by pdglala** [comment]
hier habe ich noch ne andere quellenangabe gefunden:
https://web-beta.archive.org/web/20100819124219/http://thottbot.com:80/?sp=28771

**Comment by KeksSC** [comment]
Kleine Anmerkung hierzu:

Der 6er Bonus procct mittlerweile und auch die 20% kommen gut hin. Jedoch ändert sich der Schaden der Zauber nicht. (laut tooltip bis zu 200)

http://www.millenium.org/forum/archive/index.php/t-4927.html (leider französisch :/ )

Da steht eigentlich nur, dass er Proc eine 20% chance hat, 30 Sekunden auf dem Mob bleibt oder nur einen (1) Zauber verstärkt. Als konkrete Zahl wird bei Scorch/Versengen 84 Zauberschaden genannt. Das stimmt in etwa mit dem Zauberkoeffizienten überein ( 42.xx) => 200 * 0.42 = ~84

Getestet habe ich das Ganze heute morgen. Kann gern noch ein Video zur Verfügung stellen wenn gewünscht. Oder für eine bessere Übersicht einen weiteren Bugreport aufmachen :)
