### ISSUE TITLE
T3 Set Schurke

### ISSUE THREAD

**Issue by pdglala** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2314]
[T3 Set Schurke](https://datenbank.classic-wow.org/?itemset=524)

Note: 2er Bonus?

**Welches Verhalten wird beobachtet?**
2 pieces: Your normal melee swings have a chance to Invigorate you, healing you for 90 to 111.
Scheint zu funktionieren, jedoch procchance zu niedrig?
4 pieces: Your Backstab, Sinister Strike, and Hemorrhage critical hits cause you to regain 5 energy.
Gibt zurzeit für jeden Style der kritisch Treffen kann 5 Energie wieder zurück (Tritt, Solarplexus, Ausweiden)
8 pieces: Your Eviscerate has a chance per combo point to reveal a flaw in your opponent's armor, granting a 100% critical hit chance for your next Backstab, Sinister Strike, or Hemorrhage.
Chance pro Combopunkt ist zu klein.

**Wie sollte es sich verhalten?**
2 pieces: Your normal melee swings have a chance to Invigorate you, healing you for 90 to 111.
procchance?
4 pieces: Your Backstab, Sinister Strike, and Hemorrhage critical hits cause you to regain 5 energy.
Nur für die im Tooltip beschriebenen Spells sollte Energie wiederhergestellt werden.
8 pieces: Your Eviscerate has a chance per combo point to reveal a flaw in your opponent's armor, granting a 100% critical hit chance for your next Backstab, Sinister Strike, or Hemorrhage.
Die Chance pro Combopunkt sollte fix 20% betragen, sprich bei 5 Combopunkte = 100%

**Schritte zur Reproduzierung**
8 Teile des Set anlegen und auf ein Mob hauen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://www.wowhead.com/spell=28814/revealed-flaw#comments 8er Bonus
8er Bonus mit einem full t3 Schurken zu Vanilla selbst getestet da einen gespielt.
Zusätliche Informationen folgen noch, falls ich welche finden sollte.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?itemset=524 T3 Set
https://datenbank.classic-wow.org/?spell=28816 2er Bonus
https://datenbank.classic-wow.org/?spell=28812 4er Bonus
https://datenbank.classic-wow.org/?spell=28814 8er Bonus
https://datenbank.classic-wow.org/?spell=11294#taught-by-npc SS
https://datenbank.classic-wow.org/?spell=25300 BS
https://datenbank.classic-wow.org/?spell=17348 Hemo
https://datenbank.classic-wow.org/?spell=1769 Kick
https://datenbank.classic-wow.org/?spell=31016 Evis
https://datenbank.classic-wow.org/?spell=11286 Solarplexus

**Comment by dagochen** [comment]
Wir benötigen Quellen zu den korrekten Chancen pro Combopunkt (8er Bonus) und der Procchance (2er Bonus).
