### ISSUE TITLE
[Naxxramas] Master Craftsman Omarion

### ISSUE THREAD

**Issue by Rukachi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2316]
**Welches Verhalten wird beobachtet?**

Er hat keine Quests für die Frostteile zu vergeben um die erlernen zu können

**Wie sollte es sich verhalten?**

Er sollte Quests für Handwerker (Blacksmithing, Tailoring, Leatherworking) zu vergeben haben. die einem auffordern "Omarion's Handbook" zu Craftsman Wilhelm zu der Light's Hope Chapel zu bringen. Der einem das dann beibringt, sofern man Handwerker ist und auch den nötigen Ruf dafür besitzt. 

"The pattern is learned from a quest you get from Master Craftsman Omarion, who is located in the Deathknights wing of Naxxramas. The quest requires you to return Omarion's Handbook to Light's Hope Chapel and give it to Craftsman Wilhelm. He will then instruct you if you are a craftsman. You also must be Revered with the Argent Dawn to learn this pattern."

Nicht Handwerker sollten wohl auch die mölichkeit haben sich das Buch bei dem Omarion abzuholen das einem dann zu dem Wilhelm schickt und sich da auch ohne den Beruf das zeug craften lassen + Gebühr von 200g. 

"Non-crafters can take this book to Craftsman Wilhelm at Light's Hope Chapel in the Eastern Plaguelands. Once he receives this book, he can craft the same frost-resistant gear that Omarion teaches crafters. However, Wilhelm does charge an extra crafting fee of 200Gold and requires a high Argent Dawn reputation for some items." 

Laut dem Text müsste der Wilhelm auch verbuggt sein, da man bei ihm die Quests für die Frostteile schon annehmen kann, ohne die Quest ( von Omarions Handbook) abgeschlossen zu haben oder was sagt ihr?

Alle  restlichen nötigen Infos sind unten aufgeschrieben.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

http://wowwiki.wikia.com/wiki/Craftsman_Wilhelm?oldid=389826 - Craftsman WIlhelm
http://wowwiki.wikia.com/wiki/Master_Craftsman_Omarion?oldid=389828 - Master Craftsman Omarion
https://datenbank.classic-wow.org/?item=22719 - Omarion's Handbook

**Blacksmithing**

Item: https://datenbank.classic-wow.org/?item=22670
Quelle: http://wowwiki.wikia.com/wiki/Icebane_Gauntlets?oldid=276521
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28248

Item: https://datenbank.classic-wow.org/?item=22671
Quelle: http://wowwiki.wikia.com/wiki/Icebane_Bracers?oldid=338478
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28249

Item: https://datenbank.classic-wow.org/?item=22669
Quelle: http://wowwiki.wikia.com/wiki/Icebane_Breastplate?oldid=279122
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28245

**Tailoring**

Item: https://datenbank.classic-wow.org/?item=22658
Quelle: http://wowwiki.wikia.com/wiki/Glacial_Cloak?oldid=292452
->Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28214

Item: https://datenbank.classic-wow.org/?item=22655
Quelle: http://wowwiki.wikia.com/wiki/Glacial_Wrists?oldid=352601
->Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28213

Item: https://datenbank.classic-wow.org/?item=22654
Quelle: http://wowwiki.wikia.com/wiki/Glacial_Gloves?oldid=296865
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28212

Item: https://datenbank.classic-wow.org/?item=22652
Quelle: http://wowwiki.wikia.com/wiki/Glacial_Vest?oldid=382973
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28215

**Leatherworking**

Item: https://datenbank.classic-wow.org/?item=22663
Quelle: http://wowwiki.wikia.com/wiki/Polar_Bracers?oldid=304756
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28230

Item: https://datenbank.classic-wow.org/?item=22662
Quelle: http://wowwiki.wikia.com/wiki/Polar_Gloves?oldid=273765
-> Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28229

Item: https://datenbank.classic-wow.org/?item=22661
Quelle: http://wowwiki.wikia.com/wiki/Polar_Tunic?oldid=272046
-> https://datenbank.classic-wow.org/?spell=28228

Item: https://datenbank.classic-wow.org/?item=22665
Quelle: http://wowwiki.wikia.com/wiki/Icy_Scale_Bracers?oldid=277044
->Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28233

Item: https://datenbank.classic-wow.org/?item=22666
Quelle: http://wowwiki.wikia.com/wiki/Icy_Scale_Gauntlets?oldid=290577
->Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28232

Item: https://datenbank.classic-wow.org/?item=22664
Quelle: http://wowwiki.wikia.com/wiki/Icy_Scale_Breastplate?oldid=273313
->Zauber von Wilhelm: https://datenbank.classic-wow.org/?spell=28231

Sollte ich falsch liegen oder was vergessen haben, dann bitte kommentieren.

**Comment by Rukachi** [comment]
Da der Wilhelm auf dem live Server die Quests für die Frostteile schon offen für alle hat und einige dies schon annehmen, wollte ich zu ihm nochmal einen Kommentar da lassen. Die sollten sich erst bei der abgabe vom Omarion's Handbook öffnen.

**Comment by Dotox** [comment]
Super, vielen Dank!
