### ISSUE TITLE
[BG] Flüche werden nach BG nicht entfernt

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2318]
**Welches Verhalten wird beobachtet?**

Nach ende eines BGs bleiben Flüche auf dem Spieler bestehen, bis sie auslaufen. Zumindest bei CoA hab ich das vermehrt beobachtet.

**Wie sollte es sich verhalten?**

Debuffs sollten entfernt werden.

**Schritte zur Reproduzierung**

BG joinen, sich kurz vor Ende von einem WL verfluchen lassen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

[Curse of Agony](https://datenbank.classic-wow.org/?spell=980)

**Comment by Dotox** [comment]
Hast du eine Quelle? Ich bin mir spontan nicht sicher, ob das damals nicht auch so war.

**Comment by Slimmer2** [comment]
Würde ja dann fast sagen nach BG sollten alle Debuff entfernt werden und evtl. auch die Klassenbuffs.
