### ISSUE TITLE
PVP-Items: Gefechts-Tränke

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#232]
die gefechtstränke:
http://datenbank.welli-it.de/?item=18839
und
http://datenbank.welli-it.de/?item=18841

die man in sw vor der offiziershalle kaufen kann, sollten erst mit pvp rang 6 erwerbbar sein. momentan sind sie frei verkäuflich (oder zumindest unter rang 6 erhältlich)

>http://www.wowwiki.com/Honor_system_(pre-2.0)#Ranks_and_rewards (rang 6 belohnungen)

**Comment by dagochen** [comment]
@hraesvelgr 
Welche der 6 Händler dürfen das nicht verkaufen bzw. doch verkaufen? Die <Rüstmeister für Offizierszubehör> sollten es wohl haben, aber die anderen nicht, sehe ich das richtig?

**Comment by hraesvelgr** [comment]
kein plan. ich weiß nichtmal, wo die anderen npc stehen, oder wer die sind, ausser den beiden offizierrüstmeistern vor den pvp-hallen.

**Comment by dagochen** [comment]
Da Rang 6 der 1. Offiziersrang ist, ist es wohl die sinnvollste Lösung, die Tränke nur von den Rüstmeistern in der Offiziersmesse erhältlich zu machen.

**Comment by soda09** [comment]
Die Tränke werden vom richtigen Händler verkauft (OG und SW) aber dürften bei beiden Fraktionen erst ab Rang6 erhältlich sein.
Sie sollten dann aber dauerhaft erhältlich sein, wenn man einmal Rang 6 war, oder?

**Comment by dagochen** [comment]
http://web.archive.org/web/20061025225714/http://wow.allakhazam.com/db/item.html?witem=18839
Dort sieht man die richtigen Händler, welche sich in den Offiziersmessen befinden.
