### ISSUE TITLE
Ouro verschwindet wenn der Server crasht

### ISSUE THREAD

**Issue by Flowbwolf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2320]
Welches Verhalten wird beobachtet?
Ouro (https://datenbank.classic-wow.org/?npc=15517) despawnt für den rest der ID, wenn der Server crasht während man infight mit ihm ist.
Wie sollte es sich verhalten?
Ouro sollte wieder angreifbar sein, nachdem der Server abgeschmiert ist.
Schritte zur Reproduzierung
Ouro angreifen und Server crashen (gerne auch mal bei Cthun testen, mir wurde von einigen Leuten gesagt er hat den gleichen fehler)
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15517
https://datenbank.classic-wow.org/?npc=15727

**Comment by Ulva-Anorhin** [comment]
Hatten gestern 3 Server Crash bei cthun. 
Da war es nicht der Fall! Konnten danach ganz normal weiter spielen.
