### ISSUE TITLE
[Naxxramas] Todesritter

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2325]
**Welches Verhalten wird beobachtet?**

Die Todesritter setzen die Fähigkeit "Raise Undead" zwar ein, jedoch scheint die Range zu gering zu sein. Außerdem stimmt die Anzahl der beschworenen Skelette nicht. Bei uns kam immer nur ein einziges Skelett pro toten NPC raus.

**Wie sollte es sich verhalten?**

Die Range für das Beschwören der Skelettdiener sollte 20 Yards betragen. (Range zwischen NPC und Object Death_NPC)

Zusätzlich sollten immer 2x Skelett pro toten NPC in Reichweite beschworen werden. 

**Schritte zur Reproduzierung**

Nach Naxxramas begeben und Todesritter pullen. Anderen NPC in der Nähe töten und schauen, ob zwie Skelette beschworen werden. Zusätzlich die Range von 20 Yards testen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Summon Guardian
Value: 2
Creature: Deathchill Servant

https://web-beta.archive.org/web/20071011150543/http://thottbot.com:80/s28353

https://web-beta.archive.org/web/20061113121848/http:/wowwiki.com/Deathknight

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Todesritter:
https://datenbank.classic-wow.org/?npc=16146

Raide Dead:
https://datenbank.classic-wow.org/?spell=28353

**Comment by Dotox** [comment]
Range stimmt, müsste man nochmal genau prüfen.
