### ISSUE TITLE
Druide: Mal der Wildnis setzt niedrigere Werte als vorgegeben auch Talentepunkte werden nicht berücksichtigt.

### ISSUE THREAD

**Issue by Quastel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2330]
Welches Verhalten wird beobachtet?
"Mal der Wildnis" erreicht nicht die Rüstungsvorgaben und Punktwerte der einzelnen Ränge wie in der Zauberbuchinformation angegeben. 
Talentpunkte auf "Mal der Wildnis" haben keine Funktion und geben keine prozentuale Erhöhung.

Wie sollte es sich verhalten?
"Mal der Wildnis" sollte wie in der RANG Beschreibung auch den korrekten Rüstungswert ergeben, oder die Angaben in der Beschreibung sollte man an die Werte in der Datenbank anpassen.

Die Talentpunkte sollen den Zauber prozentual um den angegebenen Wert erhöhen.

Schritte zur Reproduzierung
aktivieren und vergleichen
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Allianz, Druide, alle Level
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=6756

**Comment by dagochen** [comment]
Kannst du bitte genaue Zahlen liefern, bei welchen Werten welche Abweichungen auftreten?

**Comment by Quastel** [comment]
Folgende Werte habe ich nochmal mit einem anderen Spieler abgeglichen.
"Mal der Wildnis"  Rüstung - Wert auf alle Attribute - Widerstandsarten
Zauberbuch Sollwert                    Buff Istwert
Rang1  33                                         25
Rang2  87-2                                      65-2
Rang3  141-5                                   105-4
Rang4  202-8-6                                150-6-5
Rang5  263-10-13                             195-8-10
Rang6  324-13-20                             240-10-15
Rang7  384-16-27                             285-12-20

Talentpunkte werden überhaupt nicht berücksichtigt. Es findet keine prozentuale Erhöhung statt.

**Comment by Slimmer2** [comment]
Hast du das im Charakteranzeige bei den Werten verglichen oder nur auf die Buffanzeige nachgeschaut?

**Comment by Quastel** [comment]
Beim Charakter ist es ebenso die Werte erhöhen sich nur um den Buff-Istwert nicht um den Sollwert wie im Zauberbuch angegeben.
Also z.B. Rang 3 erhöhen sich in der Charakteranzeige die Rüstung um +105 und die Attribute +4

**Comment by headcrash2k** [comment]
Ich hab das mit einem Lvl 13 Druiden und geskillten Mal der Wildnis gestern selbst getestet. Der Tooltip beim Zauber ist korrekt, der Tooltip des Buffs in der Buffleiste ist falsch. Aber das wichtige bleibt: Es wird der korrekte Wert auf die Attribute und Rüstung angerechnet und nicht der in der Buffleiste angezeigte Grundwert ohne das Talent. Es handelt sich daher nach meiner Beobachtung nur um einen Anzeigefehler in der Buffleiste und keinen spielrelevanten Bug.

**Comment by Dotox** [comment]
Ja, leider ist der Classic-Client für solche Anzeigebugs bekannt.
