### ISSUE TITLE
AQ40 Cthun - Über den Eingang gekickt und nicht möglich rauszulaufen

### ISSUE THREAD

**Issue by Fnaticshadow** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2331]
Welches Verhalten wird beobachtet?
Wenn man über den Eingang gekickt wird kann man dort nicht wieder rauslaufen und kommt nur raus, wenn man geschluckt wird.

Wie sollte es sich verhalten?
Man sollte dort nicht reingekickt werden können oder es sollte möglich sein wieder rauszulaufen.

Schritte zur Reproduzierung
Am Eingang entsprechend von einem Tentakel kicken lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://picload.org/view/dglogrgl/wowscrnshot_100117_215527.jpg.html

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15728

**Comment by Sheed90** [comment]
Wurdest du nach der Magenphase in die Position gekickt?

Das Problem daran ist, dass die Welt, wie wir sie im Client sehen, damals auch genau so war. Sprich, das konnte damals durchaus auch passieren. Ist es dann ein Bug in diesem Sinne? 

Dotox könnte vermutlich eine unsichtbare Wand (Game-Objekt) davor setzen, damit man nicht in diesen Spalt gekickt wird. Wie oft ist es denn bereits vorgekommen?

Aus meiner Sicht besteht allerdings kein Handlungsbedarf, da es auch in der offenen Welt Ecken und Kanten gibt, aus denen man ohne Feststeck-Befehl oder Ruhestein nicht wieder raus kommt.

**Comment by Fnaticshadow** [comment]
Nein, ich war nicht vorher im Magen. Ich stand einfach nah an dem Klauententakel. Bisher ist es mir auch das erste mal passiert.

**Comment by Sheed90** [comment]
Dann besteht meiner Meinung nach noch weniger Handlungsbedarf. Einfach nicht mehr dort hinstellen und das Problem ist gelöst. Magen-Auswurf kann man als Spieler nicht kontrollieren. Die Position innerhalb des Raumes schon.

**Comment by Dotox** [comment]
Schließe mich Sheed an, trotzdem danke für den Report :)

**Comment by Nifexx** [comment]
Den Magen-Auswurf kann man auch kontrollieren!
