### ISSUE TITLE
[Naxxramas] Ashbringer Event im Kloster

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2334]
Hallo zusammen,

aufgrund des noch fehlenden Eintrages zum Ashbringerevent eröffne ich hier mal einen Sammelthread.

Falls ihr noch weitere Infos findet, einfach rein poste, damit Dotox diese verarbeiten kann. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Event im Kloster, samt Dialoge (englisch):
http://wowwiki.wikia.com/wiki/Corrupted_Ashbringer/Scarlet_Monastery_Event

Allgemeine Informationen zum Ashbringer: http://wowwiki.wikia.com/wiki/Corrupted_Ashbringer/Scarlet_Monastery_Event

Video von 2008:
https://www.youtube.com/watch?v=QViNP4cnPyM
https://www.youtube.com/watch?v=nT6yE7vuCJc

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Ashbringer: https://datenbank.classic-wow.org/?item=22691

Ashbringer Trigger: https://datenbank.classic-wow.org/?npc=16430
Ashbringer Effekt: https://datenbank.classic-wow.org/?spell=28282
Unbekannter Effekt: https://datenbank.classic-wow.org/?spell=28414

**Comment by Dotox** [comment]
Die deutschen Übersetzungen fehlen mir dazu noch, wenn die jemand hat, gerne melden.

**Comment by Sheed90** [comment]
Ich konnte leider nichts brauchbares finden.

**Comment by Sheed90** [comment]
Moin,

auf den Client EN funktioniert die Quest einwandfrei, das einzige was nicht funktionierte war, dass der Scarlet Commander Mograine nach dem "Kettenblitz" seines Vaters nicht am Boden liegt, sondern stehen bleibt. Sonst passt es!

**Comment by Simit90** [comment]
Hier die deutschen Übersetzungen:

Scharlachroter Kommandant Mograine sagt: Ihr haltet die Klinge meines Vaters in Euren Händen, <Name>. Meine Soldaten stehen unter Eurem Befehl <Mylord/Mylady>. Übernehmt das Kommando... führt sie an... Die Unreinen müssen geläutert werden. Sie sollen vom Bösen gereinigt werden.

Hochlord Mograine sagt: Renault...

Scharlachroter Kommandant Mograine sagt: Vater... aber... wie?

Hochlord Mograine sagt: Hast du wirklich geglaubt, dein Verrat würde vergessen? Untergegangen im Komplott meines von langer Hand geplanten Todes? Verraten vom eigenen Fleisch und Blut. Lange nach meinem letzten Atemzug, trug die Klinge deine Grausamkeit in ihrem Innersten mit sich. Erst im Tod wurde mir das ganze Ausmaß deiner Tat gewahr. Aber jetzt werde ich nicht länger von Kel'Thuzads Ketten zurückgehalten. Der Gerechtigkeit wird nun genüge getan. ICH BIN ASCHENBRINGER.

Scharlachroter Kommandant Mograine sagt: Vergib mir, Vater! Bitte...

Hochlord Mograine sagt: Ich vergebe dir...

Quellen: 
https://db.rising-gods.de/?npc=3976 (Zitate aufklappen) Scharlachroter Kommandant Mograine
https://db.rising-gods.de/?npc=16440 (Zitate aufklappen) Hochlord Mograine

Des Weiteren die Sprüche der niederknieenden Mönche etc:

Seid Ihr gekommen, um diese Welt zu retten? Um sie vom Bösen zu reinigen?
Und so beginnt es...
Aschenbringer...
Kniet! Kniet vor dem Aschenbringer!
<Mylord/Mylady, bitte verschont mein Leben, damit ich Zeuge werde, wie Ihr die Ungläubigen vom Angesicht dieser Welt tilgt.
Bitte nehmt mich mit Euch, <Sire/Mylady>.

Quelle: 
https://db.rising-gods.de/?npc=4540 Scharlachroter Mönch
https://db.rising-gods.de/?npc=4302 Scharlachroter Held
https://db.rising-gods.de/?npc=4303 Scharlachroter Abt
https://db.rising-gods.de/?npc=4301 Scharlachroter Zenturio
https://db.rising-gods.de/?npc=4299 Scharlachroter Kaplan
https://db.rising-gods.de/?npc=4298 Scharlachroter Verteidiger
https://db.rising-gods.de/?npc=4294 Scharlachroter Zauberer

Weitere Quelle leider zu Patch 4.1 und in ziemlich schlechter Qualität:
https://www.youtube.com/watch?v=XDKczmWSuvw
Dort geht jemand mit Aschenbringer ins Kloster

Die Übersetzungen für Hochinquisitor Schönufer konnte ich leider nirgends finden bisher

Zudem ist ein Scharlachroter Verteidiger und die vier Leute vor dem Scharlachroten Kommandanten Mograine (2 Mönche,1 Abt, 1 Held) weiterhin feindlich und angreifbar. Obwohl diese sich hinknien und freundlich agieren. Auch im Video zu sehen sofern es als Quelle dient.
https://www2.pic-upload.de/img/34653375/Verteidigerfeindlich.png
https://www2.pic-upload.de/img/34653377/MnchAbtfeindlich.png
Quelle der Screens: Mein Charakter Botixx auf dem Account Botix - Testserver

> das einzige was nicht funktionierte war, dass der Scarlet Commander Mograine nach dem "Kettenblitz" seines Vaters nicht am Boden liegt, sondern stehen bleibt. Sonst passt es!

Zusätzlich dazu, dass der Scharlachrote Kommandant Mograine weiterhin steht, fällt der Hochlord Mograin zu Boden. Denke, da sind die Animationen vertauscht. Auch im Video zu sehen, dass es anders herum sein sollte.

MfG Simit
PS: Ziemlich langer Beitrag, daher DB-Links gespart. Sollten die Links aus datenbank.classic-wow.org/ dennoch notwendig sein, füge ich diese nach. Hoffe, dass die Links oben als Quelle gültig sind.

**Comment by Dotox** [comment]
Ich hab das ganze etwas überarbeitet und die Übersetzungen eingefügt, vielen Dank! Warum einige NPCs trotzdem noch "rot" gekennzeichnet sind, kann ich noch nicht sagen.

**Comment by Simit90** [comment]
Eben nochmal getestet, meine Erfahrungen:

Die Texte, die gesagt werden, sind nun alle samt deutsch. Ebenso stirbt Scharlachroter Kommandant Mograine nach der Kettenblitz-Animation.

Probleme:
1.) Das mit den rot markierten NPC's sollte nicht an bestimmten Mobs dort hängen, da bei jedem Test wieder andere rot markiert waren und alle Arten von Gegnern mal rot waren.

2.) Hochlord Mograine stirbt weiterhin bzw. am Ende erscheint eine Sterbe-Animation.
Wie sollte es sein?
- Es sollte eine Despawn-Animation erscheinen
Quelle: 
https://www.youtube.com/watch?v=tove-FDz4Tc (Minute 2:35)
https://www.youtube.com/watch?v=XDKczmWSuvw

3.) Wenn man zum Scharlachroten Kommandanten geht, kniet sich dieser zwar hin, aber spricht mittlerweile zu Beginn nicht mehr diesen Text:

[Scharlachroter Kommandant Mograine sagt: Ihr haltet die Klinge meines Vaters in Euren Händen, <Spieler/Name>. Meine Soldaten stehen unter Eurem Befehl <Mylord/Mylady>. Übernehmt das Kommando... führt sie an... Die Unreinen müssen geläutert werden. Sie sollen vom Bösen gereinigt werden.](url)

Er beginnt erst dann zu reden, wenn sein Vater vor ihm steht und Renault... sagt. Im Test vor 2 Tagen hat er den Anfangssatz auf Englisch noch gesagt.

Weiß nicht, ob man damit was anfangen kann, aber im Bugtracker von Rising-Gods.de steht ebenfalls was zum Event und dort ist auch ein kleines "Skript" zum Ablauf:

Spieler steht vor Scarlet Commander Mograine (12 yards - set faction)
nach 4 sek - movepoint [01:38:41]X: 1153.204712 Y: 1398.312988 Z: 32.527924 Orientierung: 3.129206
nach 2 sek - knien + text:->Scarlet Commander Mograine: You hold my father's blade. My soldiers are yours to control, my Lord. Take them... Lead them... The impure must be purged. They must be cleansed of their taint.
10 Sek später- > Highlord Mograine erscheint am Tor und läuft gemütlich herein.
40 Sek später- > Highlord Mograine: Renault...
4 sek später - > remove state kneel
2 Sek später- > Scarlet Commander Mograine: Father... But... How?
5 Sek später- > Highlord Mograine: Did you think that your betrayal would be forgotten? Lost in the carefully planned cover up of my death? Blood of my blood, the blade felt your cruelty long after my heart had stopped beating. And in death, I knew what you had done. But now, the chains of Kel'thuzad hold me no more. I come to serve justice. I AM ASHBRINGER.
nach 12 - > emote shout
2 sek später - > kneel
2 Sek später- > Scarlet Commander Mograine: Forgive me, father! Please...
3 Sek später- > Highlord Mograine casts "Forgiveness (~1 sek) on spellhit > Scarlet Commander Mograine stirbt
4 Sek später > Highlord Mograine: You are forgiven...
3 Sek später- > Highlord Mograine -> despawnorunsummon

01:25:10]28697 - [Vergebung, Rang1 deDE]

Quelle: https://redmine.rising-gods.de/issues/2735

4.) Wenn man das Scharlachrote Kloster betritt, schreit Scharlachroter Kommandant Mograine:

[Bow down! Kneel before the Ashbringer! A new dawn approaches, brothers and sisters! Our message will be delivered to the filth of this world through the chosen one!](url)

Deutsche Übersetzung kann ich leider nicht finden und im o. g. Video aufgrund zu schlechter Quali nicht lesen. Wenn sich jemand etwas besser damit auskennt, kann man die Qualität des Videos vielleicht etwas hoch schrauben.
