### ISSUE TITLE
Mind-Control Fähigkeit

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2336]
**Welches Verhalten wird beobachtet?**

Es scheint, das die Anwendung von "Mind-Control" bei Boss-Encountern dazu führt, das Spieler dauerhaft sämtliche Aggro verlieren. Nach dem Auslaufen der Fähigkeit, sollte sich der Aggro-Wert wieder auf den Ausgangswert zurücksetzen.

Dies gilt besonders für folgende Boss-Encounter:

- Beschützer der Feuerschuppe (MC)
- Hakkar (ZG)
- Skeram (AQ)
- Kel'thuzad (Naxx)

**Wie sollte es sich verhalten?**

Wenn Spieler von den Bossen übernommen wurden, sollte der Wert für die Aggro, nach dem übernommen Zustand, wieder zurückgesetzt werden.

**Schritte zur Reproduzierung**

Sämtliche oben genannte Bosse auf die Fähigkeit: "Mind Control" überprüfen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Einige Boss-Fähigkeiten, (Hakkar, Kel'thuzad) setzen voraus, das Mind Control, die Aggro-Liste mit berücksichtigt und später wieder zurücksetzt. Diese Encounter werden sonst unlegbar.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Mind Control:
https://datenbank.classic-wow.org/?spell=10912

Bosse mit Mind-Control Fähigkeit:

Beschützer der Feuerschuppe:
https://datenbank.classic-wow.org/?npc=12119

Hakkar: 
https://datenbank.classic-wow.org/?npc=14834

Skeram:
https://datenbank.classic-wow.org/?npc=15263

Kelthuzad:
https://datenbank.classic-wow.org/?npc=15990

**Comment by Omegaexodus** [comment]
Nach weiterer Rechereche und der guten Beobachtung anderer Mitspieler. Gibt es bei Kel'thuzad eine besondere Ausnahme bezüglich der Aggrowiederherstellung nach dem MC. 

Alle Spieler im Raum verlieren beim einsetzen der Fähigkeit "Chains of Kel'Thuzad" die gesamte Aggro und erhalten diese auch nicht wieder. Demnach müssen eventuell noch mal besondere Änderungen vorgenommen werden, was die MC Fähigkeit bei Kel'thuzad angeht. :-(

**Comment by Dotox** [comment]
War mir bereits bekannt und ist auch schon so implementiert.

**Comment by Ulva-Anorhin** [comment]
Eben bei Hakkar immer noch der aggro reset nach der tank übernahme

**Comment by godlike321** [comment]
Hakkar unspielbar wenn nicht total overgeared oder 5-7 Krieger im Raid.

Der Mind Control resettet dort immer noch die Tankagro.

Grüße
