### ISSUE TITLE
PvP Mind control - Ende portet eigenen Char zum kontrollierten Char

### ISSUE THREAD

**Issue by TithX** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2337]
**Welches Verhalten wird beobachtet?**

Im Arathibecken wurde Mind control auf einen gegnerischen Krieger gemacht. Der Krieger wurde vom Sägewerk über die Klippe gelenkt, dass dieser runterfällt. Beim Ende des Mind control (durch Fallen oder outrangen, keine Ahnung) wurde der kontrollierende Char (Priester) zum Krieger geportet.

**Wie sollte es sich verhalten?**

Das Mind control müsste sich beenden und der Priester müsste an der ursprünglichen Position stehen.

**Schritte zur Reproduzierung**

s.o.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Horde untot Priester hat Ally kontrolliert.

**Comment by Dotox** [comment]
Lässt sich nicht reproduzieren. Mehr Input sofern vorhanden bitte.

**Comment by TithX** [comment]
Das passiert auch nicht immer. Mir ist es gerade wieder gegen einen Mage passiert. Dieser ist durch Den Fall sogar gestorben.

Es scheint unabhängig vom Client zu sein, mir ist es bisher mit den Windows- und OSX-Clients passiert.

Ich beobachte mal wie häufig das auftritt.

**Comment by Dotox** [comment]
Wirst du hin teleportiert, oder rennst du beispielsweise mit hoher Geschwindigkeit an die Position des übernommenen Ziels? Irgendeine Situation löst das Problem aus, wir müssen der Ursache nur auf die Schliche kommen.

**Comment by TithX** [comment]
Von einem auf den anderen Frame, mit dem Ende von Mind control, wird mein Char geportet.

**Comment by TithX** [comment]
Gerade einen anderen Effekt gehabt: Ich schmeiße einen Mage runter, Mind control endet und ich bekomme den Fallschaden. Obwohl ich noch oben stehe. In der Reihenfolge stand das auch im Kampflog.

Vielleicht hängt das ja irgendwie zusammen.

**Comment by Larirawiel** [comment]
Hi,

das mit dem Fallschaden hatte ich auch. Ich hatte im Blackrock einen Ork übernommen und den dann runter gelenkt. Als der runterfiel bekam ich den Fallschaden ab.

Grüße

**Comment by TithX** [comment]
Mir ist letztens noch etwas aufgefallen: Im Warsong habe ich auf dem Dach jemanden in MC genommen. Dann habe ich ihn runter geworfen und bin noch mit ihm unten rum gelaufen und habe auch mal nach oben geguckt.

Dabei habe ich gesehen, dass mein Char noch während des MC in der Luft über dem Boden "steht" und die MC-Animation macht.

Nach dem MC bin ich dann genau an der Stelle, wo ich vorher meinen Char gesehen hatte, ein paar Meter auf den Boden gefallen.

Die fehlerhafte Positionierung passiert also scheinbar schon vor dem Ende vom MC.

**Comment by Dotox** [comment]
Vielen Dank für die Rückmeldung!

**Comment by Baraz** [comment]
Mir passiert es ab und zu, dass bei einem Jägerpull mit Pet (also [Auge des Wildtiers](http://db.vanillagaming.org/?spell=1002)) ich als Jäger an die Stelle geportet werde, an dem die Mobs mein Pet töten. Zu beobachten bei den Trashpacks vor Huhuran oder vor Ouro/C'thun.
