### ISSUE TITLE
Boss AQ40 Twins: Fehler beim Agrowechsel vom Vek'nilash zur Hexe auf der andern Seite & Fehlerhafter Teleporter

### ISSUE THREAD

**Issue by Rashick** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2339]
Welches Verhalten wird beobachtet?
* Der Imperator Vek'lor hat sich richtig verhalten. 
* Imperator Vek'nilash ist in mehreren Trys nicht auf den nächstne Spieler (Tank oder jemand anderem) agro geworden, sondern zum Hexertank auf der andern Seite rüber gerannt. 

Wir haben 3 oder 4 mal den Boss einen Try unterzogen, auch mit pause dazwischen um uns Buffs zu holen und konnten leider jedesmal diesen Fehler verzeichnen. Dabei hat der <GM> Eisfrosch auch draufgeschaut inkl. Video gemacht. 

Das ganze haben wir zu unterschiedlichen HP zeitpunkten feststellen können.... bei 70%, 35% und 3% ist das passiert. Also ist uns leider kein "chema" aufgefallen, was da für verantwortlich sein könnte. 

Allerdings konnten wir beobachten, dass die Visuelle Animation des Teleports schon vor dem Teleport passiert und somit einen etwas verunsichert. Teilweise sogar 1-2 Sekunden vor dem eigentlichen Teleport. 

Wie sollte es sich verhalten?
* Die Bosse sollen einen Agro reset bei jedem Teleport haben und dann auf den ihnen am nächsten stehenden Spieler die initial agro werfen. 

Schritte zur Reproduzierung
* Wir haben mehrfach die Twins mit und ohne Buffs getryed. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Rachmin: 
* https://www.youtube.com/watch?v=wf98w_Dslg4
* Da bei 15sec rennt der Boss einfach am Tank (Grün) vorbei zum Hexertank (Leviana) auf der andren seite rüber. Der Schurke winry kann agro durch starken dmg auf den Boss dann bekommen und den Boss dann zurück ziehen, da haben die sich allerdings schon hochgeheilt. 

Rashock (Tank): 
* https://www.twitch.tv/videos/180814964
* Bei 19:18 passiert der Teleport, dass der Emperor Vek'nilash eigentlich von dem Tank Rashock (Blau) hätte agro haben müssen, ggf. von dem Meele Furidan, welcher rechts läuft, aber definitiv nicht von der Hexe auf der andern Seite!

Mess: (Krieger für Adds) 
* https://www.youtube.com/watch?v=nEBrrI27Ey8&feature=youtu.be
* Bei 0.08/0:10 die gleiche Szene wie bei Rashocks video auf 19:18. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Twins: 
* https://datenbank.classic-wow.org/?npc=15275

Zusätzlich der Kampflog von Rashock: https://docs.google.com/spreadsheets/d/1IP9dfGKw2cVhC3aBbUKqX7ok7b3ONfHsY03klE086ng/edit?usp=sharing

**Comment by Rashick** [comment]
Heute hatten wir den Fehler nicht mehr.

**Comment by Dotox** [comment]
Es tritt nicht immer auf, scheint sehr zufällig zu sein. Wir sind da einem Fehler auf der Spur, der eventuell die Ursache dafür und für viele andere, ähnliche Reports, sein könnte.

**Comment by Ulva-Anorhin** [comment]
21.01.2018 wieder das selbe

**Comment by Ulva-Anorhin** [comment]
28.01.2018 wieder das selbe... wieder nachdem einer gestorben ist!

**Comment by Rashick** [comment]
Wir hatten heute das gleiche Thema auch mehrfach so dass wir bei den Twins aufhören mussten...

Also das Problem ist definitiv nicht behoben, wäre schön wenn das mal behoben werden könnte.  

Liebe Grüße und danke.

**Comment by Ulva-Anorhin** [comment]
04.02.2018 Twins wieder verbuggt... Raid abbgebrochen!
