### ISSUE TITLE
WL-Klassenskill: Banish lässt sich "wegschlagen"

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#234]
der warlock-skill banish sollte dafür sorgen, dass das ziel keinerlei aktionen ausführen kann, jedoch gegen jeglichen schaden (jedoch nicht gegen spott) immun ist. dieser spell sollte seine volle zeit durchlaufen, erst dann ist das ziel wieder angreifbar und kann aktionen ausführen. (ausser heartbeat-ticks, das kann den debuff eher beenden)

momentan kann man den spell "wegschlagen", also durch autohits entfernen (ähnlich wie eisfalle oder sheep). das sollte defintiv nicht passieren.

http://datenbank.welli-it.de/?spell=710 rang 1
http://datenbank.welli-it.de/?spell=18647 rang 2

**Comment by Slimmer2** [comment]
Hoffe das bald gefixt wird
