### ISSUE TITLE
[AQ40] Skeram Adds - HP Anpassungen

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2340]
**Welches Verhalten wird beobachtet?**

Jedes mal, wenn der Boss Skeram seine Teilungsfähigkeit anwendet (75%, 50%, 25%) lässt er 2x Kopien von sich erscheinen. Die Kopien hatten gestern bei jeder Phase unterschiedlich viel Leben. In der ersten Phase (75%) hatten diese extrem wenig HP, bei der zweiten Teilung (50%) dann etwa den richtigen HP-Wert und bei der dritten Teilung (25%) hatten diese enorm viel Leben.

**Wie sollte es sich verhalten?**

Die Kopien von Skeram, sollten immer den gleichen Basis-Wert an Leben besitzen. Unabhängig davon, in welcher Phase er sich befindet. (75, 50, 25)

Der Basiswert könnte etwa 25% seines max. Lebens betragen. (Natürlich noch die Abhärtung mit draufrechnen)

Leider gibt es keine wirklich guten Informationen zu dem Leben der Kopien von Skeram. Wenn jemand die Orginaldaten hat, bitte angeben. :-)

**Schritte zur Reproduzierung**

Nach AQ40 begeben und Skeram pullen. Dann in die entsprechenden Phasen bringen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

https://web.archive.org/web/20060719221109/http://www.wowwiki.com:80/The_Prophet_Skeram

"_At 75%, 50%, and 25%, creates two images that have identical abilities to Skeram. The images spawn with the same percentage of life as Skeram, but they do not have as many hit points as the true Prophet, making them much easier to kill._"

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Skeram:
https://datenbank.classic-wow.org/?npc=15263

Summon Images:
https://datenbank.classic-wow.org/?spell=747

**Comment by Dotox** [comment]
bereits behoben
