### ISSUE TITLE
 [AQ40] Skeram Übernahme

### ISSUE THREAD

**Issue by Flowbwolf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2341]
Welches Verhalten wird beobachtet?
Der Tank von Skeram wird von den Spiegelbildern übernommen, obwohl er  nicht in Meleerange ist.
Wie sollte es sich verhalten?
Es sollten nur Spieler in Meleerange übernommen werden.
Schritte zur Reproduzierung
Skeram auf 75% bringen und die Spiegelbilder links und rechts auf den Plattformen tanken während Skeram selbst in der Mitte getankt wird (wenn als gm möglich nur mit 3 Leuten versuchen) und warten bis einer der Spiegelbilder seinen Mindcontrol macht.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15263
Hab leider weder die Fähigkdeit Mindcontrol noch die Teilung als Fähigkeit von Skeram in der DB gefunden.

**Comment by Dotox** [comment]
Kann ich leider nicht reproduzieren, mehr Input von anderen Gilden bitte :)

**Comment by Ulva-Anorhin** [comment]
Bei anorhin wurde gestern auch der aktive Tank in der Mitte übernommen. 
Keine Ahnung ob vom Boss selbst oder von einem Add. 

Laut Patchnotes sollte ja kein Tank übernommen werden.

**Comment by Dotox** [comment]
Es soll nicht das aktuelle Ziel (Tank) übernommen werden, korrekt.

**Comment by Ulva-Anorhin** [comment]
Hier noch das Video von gestern.
https://www.youtube.com/watch?v=PAv1-AouKC4&feature=youtu.be

bei 3:21 sieht man wie der aktuelle Tank übernommen wird.
Die Phasen 75, 50 und 25 sind alle richtig.
