### ISSUE TITLE
BWL Vaelastrasz: burning adrenaline widerstehen

### ISSUE THREAD

**Issue by NukNukPils** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2342]
Welches Verhalten wird beobachtet?
Ich war als zweiter (und letzter) Tank bei Vael dran, habe den debuff "burning adrenaline" bekommen und bin nachdem Vael down war gestorben. Allerdings (wie im Video zu sehen) habe ich einen Teil des Spells widerstanden. 
Ich war Tod, allerdings hatte ich noch alle buffs. Ich konnte auch nicht direkt widerbelebt werden. Leider weiß ich selber nicht (video) wie ich widerbelebt wurde. 

Wie sollte es sich verhalten?

Ich bin mir nicht sicher, habe keine sicheren Quellen gefunden, ob der Spell widerstanden werden kann. 
Aber Tod mit allen Buffs ist bestimmt nicht richtig.
Ich hatte bei dem Bossfight 319 FR an.

Schritte zur Reproduzierung

Vael töten mit Debuff und max FR.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://youtu.be/zKfgrlR2tBI

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?spell=23619
https://datenbank.classic-wow.org/?npc=13020

**Comment by NukNukPils** [comment]
Video gibts auf Anfrage, wurde von einem kompetenten Mitarbeiter leider entfernt.

**Comment by Dotox** [comment]
Vielen Dank, ich denke, ich habe eine mögliche Ursache gefunden und behoben.
