### ISSUE TITLE
[Naxxramas] The Four-Horsemen

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2343]
**Welches Verhalten wird beobachtet?**

Es kam bei dem Test am Montag 2x vor, dass der Tank die Aggro des Reiters verloren hat, obwohl dieser erfolgreich Spott einsetzen konnte. Nach dem Ablauf der Spott-Fähigkeit (3 Sek) lief dieser einfach wieder zu vorherigen Tank zurück. 

Zusätzlich scheint die Fähigkeit von Sir Zeliek nicht "Zufällige" Ziele im Bereich von 35 Yards zu treffen. In 80% der Fälle ging die Fähigkeit nur auf den Tank.

**Wie sollte es sich verhalten?**

Die vier Reiter sollten durch eine Rotation und durch das Abspotten von den Tanks dazu gebracht werden, das diese immer in den jeweiligen Ecken der Räume bleiben.

Spott soll zwar verfehlen können. Aber der erfolgreich Einsatz von Spott sollte den NPC dauerhaft an den Tank binden, bis dieser wieder abgespottet wird. Es kam in unserem Fall 2x vor, das der NPC, trotz des erfolgreichen Einsatzes von Spott, nach dem Ablauf der Spott-Fähigkeit wieder zu dem vorherigen Tank zurückgelaufen ist.

Sir Zeliek sollte eine Fähigkeit mit dem Namen "Holy Wrath" einsetzen. Diese fügt einem zufälligen Ziel in 35 Meter Range 495 - 605 Schaden zu und springt auf Gegner in 5 Yards über. Dabei verursacht diese pro Sprung 100% mehr Schaden zu. (Achtung kein "Schleifensprung" möglich)

**Schritte zur Reproduzierung**

Nach Naxxramas begeben und die vier Reiter pullen. Danach die Spott-Fähigkeiten überprüfen und die Zielauswahl + Reichweite von "Holy Wrath".

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

https://go.twitch.tv/videos/180972874

Bei 1:16:00 sieht man das der Tank, einfach und ohne Grund die Aggro verliert und zum vorherigen Tank zurückläuft. Asaph --> Spott von Colbens, hält 3-5 Sekunden Aggro, verliert die Aggro und der Reiter rennt Colbens wieder hinterher. (Spott hat nicht verfehlt)

https://web-beta.archive.org/web/20061117092152/http://www.wowwiki.com:80/The_Four_Horsemen

"_(They are tauntable and from 1.11 on, taunt will put you to top of the aggro list AND make target stick with you. Before 1.11 you need to gain 110% of original target's aggro to make the target stick with you after taunted. )_"

https://web-beta.archive.org/web/20080303045455/http://thottbot.com:80/s28883

Holy Wrath. Reichweite liegt bei 35 Yards, mit 5 (0 Yards) Reichweite zum überspringen. Ziel sollte zufällig gewählt werden.

"_Holy damage 495-605, hit random target in 35 yards range, and continue to chain until no one is within the 5 yards distance of the last target (no loop). Every chaining will double the damage. Cooldown is 12 secs._"

https://go.twitch.tv/videos/180972874

Ab 2:14:00 kann man die Anzahl und das Einsetzen von "Holy Wrath" genau verfolgen. 
Wie man sieht, wird "Holy Wrath" fast nur auf die Tanks gewirkt. Zudem scheint die Reichweite zu gering zu sein. (35 Yards)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Thane Kaorth'azz:
https://datenbank.classic-wow.org/?npc=16064

Highlord Mograine:
https://datenbank.classic-wow.org/?npc=16062

Lady Blaumeux:
https://datenbank.classic-wow.org/?npc=16065

Sir Zeliek:
https://datenbank.classic-wow.org/?npc=16063

Holy Wrath:
https://datenbank.classic-wow.org/?spell=28883

Spott:
https://datenbank.classic-wow.org/?spell=8133

**Comment by Brgs** [comment]
Der Holy Wrath von Zeliek sollte immer sein aktuelles Target zuerst treffen und von da aus dann überspringen. Das is unseren Tests zufolge auch richtig aufm Testserver.

Zitat von Wowwiki: 
Sir Zeliek (230k HP) — Holy Wrath 
Holy damage 495-605, **hits aggro target** and continues to chain until no one is within the 5 yards distance of the last target (no loop). Every chaining will double the damage. Cooldown is 12 secs.

Quelle: http://wowwiki.wikia.com/wiki/Four_Horsemen_(original)

**Comment by Omegaexodus** [comment]
> Der Holy Wrath von Zeliek sollte immer sein aktuelles Target zuerst treffen und von da aus dann überspringen. Das is unseren Tests zufolge auch richtig aufm Testserver.

Sorry aber das ist leider nicht richtig. Auf den alten Webseiten steht dazu:

_"Holy damage 495-605, **hit random target** in 35 yards range, and continue to chain until no one is within the 5 yards distance of the last target (no loop). Every chaining will double the damage. Cooldown is 12 secs."_

Zudem wurde die Fähigkeit damals für Wotlk nicht umgeändert, weshalb man auch dort, in großen Abständen zu Sir Zeliek stehen musste. Das hatte zur Folge, das man bei Ihm entweder Out-of-Range gestanden hat oder man ca. 8 Meter Abstand zu anderen Spielern einhalten musste. 

Würde "Holy Wrath" nur auf den Tank gehen, wäre die Fähigkeit mit (35 Yard Range) ziemlich nutzlos.

Es gibt dazu auch in alten Videos zahlreiche Beweise, das Holy Wrath immer ein zufälliges Ziel in 35 Yard Range getroffen hat:

Beispiel 1:
https://youtu.be/K35jLAJFva0?t=204

Beispiel 2:
https://youtu.be/IE-8l3UXtYI?t=229

Beispiel 3:
https://youtu.be/YM2rIrBTpzE?t=51

Demnach bitte die Fähigkeit noch mal überarbeiten. :-)
