### ISSUE TITLE
[Naxxramas] Sapphiron  --- Aggro / Hitbox / Cleave

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2344]
Auf Grund der Übersicht wird der Bug-Report von Sapphiron in mehrere Parts unterteilt.

**Welches Verhalten wird beobachtet?**

Sapphiron hat schon angegriffen, während noch die Animation (Zusammenbau der Knochen) zu sehen war. In diesem Zeitraum war er unsichtbar und konnte nicht angegriffen werden.

Sapphiron setzt keine "Cleave-Fähigkeit" vor sich ein. Eigentlich sollte er diese Fähigkeit besitzen, da man sich sonst einfach vor ihm stellen kann, ohne Schaden zu bekommen.

Sapphiron setzt sein "Tail-Sweep" (Schwanzschlag) in einer zu großen Range ein. Dies könnte damit zusammenhängen, das Sapphirons Hitbox momentan zu gering ist. Hitbox überprüfen.

**Wie sollte es sich verhalten?**

Sapphiron sollte erst "Erscheinen" und auch angreifen, wenn die Animation über dem Zusammenbau des Bosses erfolgreich abgeschlossen ist. 

Sapphiron sollte eine Fähigkeit mit dem Namen "Cleave" besitzen. Wie alle Drachen sollte es nicht möglich sein, vor ihm zu stehen, ohne Schaden zu erhalten. Dies gilt vor allem für Meeles.

Die Hit-Box von Sapphiron ist zu gering. Eigentlich besitzt Sapphiron eine recht große Hitbox. 

Der "Tail-Sweep" hingegen scheint eine viel zu große Range zu besitzen, weshalb Meeles permanent weggekickt werden. 

**Schritte zur Reproduzierung**

Nach Naxxramas begeben und Sapphiron pullen. (Animation ausführen) Darauf achten ob der Boss Cleave einsetzt. Hitbox / Range des Tail-Sweeps überprüfen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

http://wowwiki.wikia.com/wiki/Sapphiron_(original)

"_Cleave - Your basic Frontal cleave, keep him faced away from the group._"

Weitere Quelle für den Cleave ist Bestarium unter "Sapphiron". 

"_Cleave: Inflicts normal damage plus 315 to an enemy and its nearest allies, affecting up to 10 targets._"

https://youtu.be/iRW7EoVwmk0?t=30

Pull von Sapphiron nach der Animation. Kampf startet nicht vorher!

https://youtu.be/iRW7EoVwmk0?t=238

Hier sieht man genau das die Hitbox von Sapphiron sehr groß ist. Die Meeles können am grünen Zirkel stehen und immer noch Schaden verursachen. 

https://youtu.be/iRW7EoVwmk0?t=314

Hier sieht man, das Meeles auch noch hinten an den Klauen von Sapphiron stehen können, ohne den Schwanzschlag abzubekommen. Momentan ist dies nicht möglich!

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Sapphiron:
https://datenbank.classic-wow.org/?npc=15989

Cleave: 
https://datenbank.classic-wow.org/?spell=27794

Tail-Sweep:
https://datenbank.classic-wow.org/?spell=15847

**Comment by Sheed90** [comment]
Im gestrigen Stream von Dotox konnte man feststellen, dass jetzt alle hier genannten Fähigkeiten und Events korrekt funktionieren.

**Comment by Omegaexodus** [comment]
Nachdem gestrigen Testabend konnten wir noch einige kleine Fehler bei Sapphiron feststellen. Auf Grund der Übersicht, werde ich den bereits erstellten Bug-Report weiterführen.

--------------------------------------------------------------------------------------------------------

**Welches Verhalten wird beobachtet?**

Sapphiron setzt seine "Cleave-Fähigkeit" vor sich nicht richtig ein. Bei uns hat nur der Tank die Cleave-Fähigkeit abbekommen. Andere Spieler die sich vor Ihn gestellt haben, wurden davon nicht getroffen. (Eventuell die Range überprüfen)

Die momentane Hit-Box von Sapphiron ist noch sehr klein. Bitte noch mal die Hitbox überprüfen.

**Wie sollte es sich verhalten?**

Sapphiron sollte eine Fähigkeit mit dem Namen "Cleave" besitzen, die bis zu 10 Spieler gleichzeitig vor ihm treffen sollte. Momentan erhält nur der Tank den Schaden dieser Fähigkeit.

Die Hit-Box von Sapphiron ist zu gering. Eigentlich besitzt Sapphiron eine recht große Hitbox, so das Meeles nicht direkt an ihm stehen müssen und kürzere Laufwege haben.

**Schritte zur Reproduzierung**

Nach Naxxramas begeben und Sapphiron pullen. (Animation ausführen) Darauf achten ob der Boss Cleave einsetzt. Hitbox / Range des Tail-Sweeps überprüfen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

http://wowwiki.wikia.com/wiki/Sapphiron_(original)

"Cleave - Your basic Frontal cleave, keep him faced away from the group."

Weitere Quelle für den Cleave ist Bestarium unter "Sapphiron".

"Cleave: Inflicts normal damage plus 315 to an enemy and its nearest allies, affecting up to 10 targets."

https://youtu.be/iRW7EoVwmk0?t=238

Hier sieht man genau das die Hitbox von Sapphiron sehr groß ist. Die Meeles können am grünen Zirkel stehen und immer noch Schaden verursachen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Sapphiron:
https://datenbank.classic-wow.org/?npc=15989

Cleave:
https://datenbank.classic-wow.org/?spell=27794

**Comment by Omegaexodus** [comment]
Nachtrag zum Testabend vom Montag. (Verspäteter Nachtrag)

Auch falls es noch mal Änderungen zu dem Boss "Sapphiron" gab, (Test von Anorhin) so kann der Nachtrag ignoriert werden.

-----------------------------------------------------------------------------------------------------------------------

**Welches Verhalten wird beobachtet?**

Die momentane Hit-Box von Sapphiron ist zu klein. Sapphiron sollte als Boss-Encounter eine sehr große Hitbox besitzen, was die Laufwege der Meeles bei der Flugphase und gleichzeitig die Schwanzkickfähigkeit + Cleave beeinflusst. 

**Wie sollte es sich verhalten?**

Die Hit-Box von Sapphiron ist zu gering. Eigentlich besitzt Sapphiron eine recht große Hitbox, so das Meeles nicht direkt an ihm stehen müssen und kürzere Laufwege haben.

**Schritte zur Reproduzierung**

Nach Naxxramas begeben und Sapphiron pullen. Hitbox überprüfen. 

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

https://youtu.be/iRW7EoVwmk0?t=238

Hier sieht man genau das die Hitbox von Sapphiron sehr groß ist. Die Meeles können am grünen Zirkel stehen und immer noch Schaden verursachen.

https://youtu.be/L7xktwZNL9E?t=280

Auch wenn der "rote" Angriffszirkel von Sapphrion sehr klein ist. So können die Meeles doch im großen Abstand vom Boss noch Schaden verursachen. Momentan ist dies nicht möglich. (Stand Montag)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Sapphiron:
https://datenbank.classic-wow.org/?npc=15989

**Comment by Dotox** [comment]
Ich kann keinen Fehler an der Hitbox feststellen. Es kann in der Flugphase von Meeles normal Schaden verursacht werden.
