### ISSUE TITLE
Lebensenergie des Geiers

### ISSUE THREAD

**Issue by Blame91** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2347]
Welches Verhalten wird beobachtet?

Der Muskelmagenkaugummi https://datenbank.classic-wow.org/?item=8424
gibt den Willenskraftbuff + 25, jedoch stackt dieser nicht mit dem Willenskraftbuff des Priesters
 
Wie sollte es sich verhalten?
Es sollte Stacken, so wie alle anderen Blasted Land Buffs
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?item=8424

**Comment by Nifexx** [comment]
Gleiches gilt für den Int-Buff https://datenbank.classic-wow.org/?spell=10690

**Comment by Sheed90** [comment]
Ohne Quellen wird das nichts, liebe Freunde.

**Comment by Nifexx** [comment]
Alle anderen dieser Buffs funktionieren doch auch. Warum sollte ich also dafür jetzt Quellen raussuchen. Außerdem wurde diese Buffs doch als Worldbuffs deklariert (finde leider den Thread dazu nicht mehr, ist vielleicht gelöscht worden, da es keine genauen Buffregeln mehr gibt) und sollte demnach mit allem stacken.

**Comment by dagochen** [comment]
https://github.com/elysium-project/server/issues/2197
Laut den Quellen sollte Willenskraft und Stamina vom Priester mit den BL Buffs stacken (genau wie Zanzas es bereits tut), aber Zanzas Flask nicht mit den BL Buffs.

Sprich ein Priester der mehr Willenskraft haben will kann sich selbst buffen und zusätzlich einen der zwei Worldbuffs nutzen: Zanzas Flask oder BL Buff

**Comment by Nifexx** [comment]
Dann scheint das beim Int-Buff wohl eine Ausnahme zu sein. Der Rest sollte dann ganz normal mit den restlichen Buffs (Ausnahme Zanza) stacken.
