### ISSUE TITLE
Text fehler in den Quest "Myranda suchen"

### ISSUE THREAD

**Issue by LinkPegi16** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2348]
**Welches Verhalten wird beobachtet?**
Im schon oben erwähnten Quest ist ein Text fehler enthalten, der im Screenshot hervorgehoben wird. Statt mit seiner Rasse angesprochen zu werden, wird man mit "Draenei" angesprochen, dass in Classic überhaupt nichts zu suchen hat.
**Wie sollte es sich verhalten?**
Statt "Draenei" sollte die entsprechende Rasse angesprochen werden.
**Schritte zur Reproduzierung**
Den Questgeber anklicken, dann auf weiter und sehen, dass vor dem Quest abschließen ein Text fehler enthalten ist.
**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://www.bilder-upload.eu/show.php?file=a94aa9-1508091496.jpg
**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Myranda die Vettel: https://datenbank.classic-wow.org/?npc=11872

**Comment by stva23** [comment]
Auch wenn die Orcs keine Draenei sind, so haben sie sich mit jenen lange Zeit eine Welt geteilt. Ob das wirklich ein Fehler ist, oder schlicht auf die Herkunft der Orcs angespielt wird?
