### ISSUE TITLE
Quest: "Eine Frage der Zeit"

### ISSUE THREAD

**Issue by Nevara19** [ClassicWoW/Nefarian_1.12.1_Bugtracker#235]
Wie es ist:
Questgeber: "Rivern Frostwind"
Man akzeptiert die Quest und man erhält den benötigten Gegenstand nicht.

Wie sollte es sein:
Es sollte ein Item geadded werden: Temporalversetzer

**Comment by dagochen** [comment]
Was haben die Items mit dem Fleisch zu tun? Kann es sein das da Questtexte durcheinander sind?
