### ISSUE TITLE
Rufleiste verändert sich bei dem Steamwheedle-Kartell nicht mehr

### ISSUE THREAD

**Issue by Svensen123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2350]
Welches Verhalten wird beobachtet?
Wenn ich einen Goblin töte, der zum Steamwheedle-Kartell gehört, erscheint im Kampflog, dass ich Rufpunkte bei dem Kartell verliere. Allerdings verändert sich der Wert im Menü "Ruf" nicht. Später wird mir im Chatlog angezeigt, dass die Goblins nun "Unfreundlich" mir gegenüber sind. Im Ruffenster stehe ich allerdings noch bei "Neutral".
Wie sollte es sich verhalten?
Im Ruffenster sollte mir angezeigt werden, dass mein Ruf bei m Steamwheedle-Kartell auf Unfreundlich steht.
Schritte zur Reproduzierung
Ich habe bereits den WDB Ordner gelöscht, alle Addons deaktiviert.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
---
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
---

**Comment by Heri7** [comment]
#1851 
Welche Goblins hast du denn getötet? Ich habs grade mit den Wachen versucht und da kam bei mir keine Meldung das der Ruf sinkt.
Werden bei dir die Namen der Goblins in der entsprechenden Farbe angezeigt? (Unfreundlich wäre Orange und Neutral Gelb)

**Comment by Svensen123** [comment]
Es gibt ziemlich mittig im Ödland zwei Goblins und einen Ork. Die beiden Goblins töte ich öfter. Bei mir werden die Namen auch nur Gelb angezeigt.
