### ISSUE TITLE
Traumachirurg Dr. Gustav van Howzen in Theramore nicht ansprechbar

### ISSUE THREAD

**Issue by MBibaum** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2352]
Seit Tagen schon kann ich den Traumachirurgen in Theramore nicht ansprechen (würde gerne erste Hilfe ab 240 weiterlernen...)
Mir wird auch sein Name nicht angezeigt. Auch nach mehrmaligem Reloggen funktioniert es nicht...
Andere Spieler sagten mir, dass es manchmal nicht funktionieren würde, aber nach dem Reloggen meistens geht... Bei mir ist das leider nicht der Fall. Bitte schnell beheben! 

Danke,
LG Melanie

**Comment by Dotox** [comment]
Versuch mal den WDB Ordner in deinem WoW-Verzeichnis zu löschen

**Comment by Ulva-Anorhin** [comment]
Welches lvl hast du? Welchen 1. Hilfe Skill?

**Comment by MBibaum** [comment]
240 wie gesagt... Stufe 47

**Comment by MBibaum** [comment]
Habe gerade die WDB Datei aus dem Verzeichnis gelöscht, konnte ihn gerade ansprechen und endlich weiterlernen... Danke @Dotox  !!! :)
