### ISSUE TITLE
World chat lässt sich nicht mehr in einem separaten Fenster/Tab anzeigen (nach Farbänderung)

### ISSUE THREAD

**Issue by revbreeze** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2353]
Welches Verhalten wird beobachtet?

World chat ist auf General Tab begrenzt, selbst das fenster löschen und neuanlegen bzw. das leaven und joinen des world chats brachte keine Änderung.

Wie sollte es sich verhalten?

World chat in einem separaten fenster

Schritte zur Reproduzierung

Man ändere die Farbe des world chats (türkis in meinem Fall)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Nicht nötig (denke ich^^) dar auf allen chars das selbe Verhalten reproduziert werden konnte

**Comment by Sheed90** [comment]
Hört sich nach einem Client-Problem und nicht nach einem Server-Problem an. Funktioniert bei mir übrigens einwandfrei. Ich habe den World-Chat bei allen Chars in separaten Fenstern, lustigerweise ebenfalls türkis gefärbt.

Ggf. WTF (Achtung! Dort sind fast alle Addon Einstellungen gespeichert!!) und WDB Ordner löschen.
