### ISSUE TITLE
Quest: Befehl des Kriegsherrn

### ISSUE THREAD

**Issue by Necrolish** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2357]
Welches Verhalten wird beobachtet?
Ich hab die Quest abgeschlossen, alle 3 Bosse getötet + die dokumente vom blackrock. Die Quest ist somit fertig, allerdings kann ich sie die ganze Zeit nicht abgeben :(( Sämtliche Vorschläge vom GM schon durchprobiert zwecks auf bank legen wieder zurück bis hin den WDB Ordner etc löschen.. Leider alles ohne Erfolg. Jetzt hab ich die Dokumente vernichtet im Rucksack auf die Hoffnung das neue droppen - von wegen es droppt leider gar kein Dokument mehr (haben seeeeeeehr viele Mobs gekillt und normal droppt das wie Sand am Meer) Bitte dringend um Hilfe da es die Ony pre ist und ich weiterhin nicht mit der Gilde raiden gehen kann deswegen.. :(((
Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
Hast du die Quest schon mal abgebrochen und neu angenommen?
