### ISSUE TITLE
[AQ40] Skeram Mindcontrol aktiver Tank

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2358]
Welches Verhalten wird beobachtet?
Der Tank, der den originalen Skeram in der Mitte tankt, wurde übernommen.

Wie sollte es sich verhalten?
Der aktive Tank sollte nicht übernommen werden können.

Schritte zur Reproduzierung
Skeram pullen, das Original tanken.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15263

**Comment by Ulva-Anorhin** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2341

**Comment by Dotox** [comment]
Wenn kein anderer Spieler in direkter Umgebung gewesen ist, nimmt er den Tank.

**Comment by Nifexx** [comment]
Es sind 2 Tanks an dem Mob. Nach meinem Verständnis sollte er den nicht aggrohaltenden Tank übernehmen. Bei uns ist es allerdings gerade umgekehrt passiert.
