### ISSUE TITLE
[Zerbrochene Allianzen] Elite Quest im Ödland

### ISSUE THREAD

**Issue by MrValrek** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2359]
Welches Verhalten wird beobachtet?
Können die Bossen nicht Beschwören. Die 3 Steine sind Vorhanden.

Wie sollte es sich verhalten?
Die Bossen sollten Beschwörbar sein

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=793

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1642
