### ISSUE TITLE
Ausweiden AP Skalierung fehlerhaft?!

### ISSUE THREAD

**Issue by Raso89** [ClassicWoW/Nefarian_1.12.1_Bugtracker#236]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
0.8.3.5

Beschreibung:
Der Skill Ausweiden skaliert normal mit AP. Im Tooltip werden diese veränderungen normaler weise dynamisch angezeigt (je nach AP Wert zum jeweiligen Zeitpunkt. Mir ist aufgefallen das er das hier nicht tut und habe deswegen an Mobs getestet ob er es wenigstens im hintergrund tut. Meine erkenntnis ist leider = Nein

Messwerte an Skelettschinder Stufe 50
340AP (bis auf waffen nackt) Non Krits = 715, 734, 707, 732, 722 Krits = 1496, 1549, 1523, 1533, 1492
810AP (mein Raidgear) Non Krits = 701, 726, 743, 727, 708 Krits = 1548, 1567, 1516, 1491, 1489

Zwischen den beiden Messungen liegen 470AP. Die genaue Formel zur berechnung von AP in Ausweidendamage war damals:

Eviscerate (Rank 9)
35 Energy 5 yd range
Instant
Requires Melee Weapon
Finishing move that causes damage per combo point, increased by Attack Power:
1 point : 224-332 damage
2 points: 394-502 damage
3 points: 564-672 damage
4 points: 734-842 damage
5 points: 904-1012 damage

Beispiel 5 Punkte:

[904 + AP * 0.15]-[1012 + AP * 0.15]

Also in meinem Fall:

[904 + 810 * 0.15]-[1012 + 810 * 0.15] was dann im Mindestfall 257,1 erhöhung des Tooltips ergibt und im Höchstfall 273,3!

**Comment by cionex** [comment]
Gibt es hierzu schon was neues @wahaxlekuke ?
Wir haben ja nun geliefert was geht.

**Comment by Larnak1** [comment]
Ich hab das gerade zum Vergleich mal mit Wilder Biss getestet, das ja die gleiche Mechanik hat. Während man bei den Werten oben tatsächlich den gleichen Mittelwert bei einer Standardabweichung von 11 bzw. 16 erhält, sieht man beim Biss einen sichtbaren Unterschied (siehe Bild; auch wenn es nicht so deutlich ist, wie es wohl eigentlich sein sollte, da bin ich mir nicht ganz sicher, woran das liegt). Vielleicht solltet ihr noch ein paar mehr Messungen machen, um Fehler auszuschließen? 5 ist schon sehr wenig. Vor allem kommt mir die Schwankung sehr klein vor, sollte der Schaden nicht eigentlich stärker schwanken? Trotzdem scheint es so, als würde hier beim Ausweiden was nicht stimmen.

![wilderbiss](https://cloud.githubusercontent.com/assets/9204430/5905105/f08ed5b4-a58d-11e4-86ac-fd629d5d681b.png)

**Comment by Raso89** [comment]
@wahaxlekuke gibts da jetzt bald nen fix dazu oder bleibt ausweiden erdrosseln blutung und gezahn te klinge weiter broken?

**Comment by wahaxlekuke** [comment]
Ich habe mal ein Video gemacht, in dem man sieht, dass die AP-Skalierung funktioniert. Ich kämpfe gegen einen Geschmolzenen Riesen mit 43,5% Rüstung - Also sollte ich durch pro AP-Punkt für 5 CP Ausweiden 0.15 * 0.565 = 0.08475 Schaden mehr machen.
Mit 312 AP ist mein höchster Treffer 612 Schaden. Dann erhöhe ich meine AP um 610, was mir 52 

Schaden im Durchschnitt mehr geben sollte und danach ist mein höchster Treffer auch 666.
Am Ende setzte ich meine AP nochmal auf 5497. Das wären dann 5497 * 0.08475 = 439 Bonusschaden im Durchschnitt und meine nicht kritischen Treffer liegen dann auch bei über 1000 Schaden. 

https://www.youtube.com/watch?v=jJLZsAaAdNw

**Comment by Raso89** [comment]
dein rechenweg is schwer nachvollziehbar grade kA bei uns aufm realm is es auf jeden egal was man macht ob ich 300 oder 1600ap hab wenn ich auweiden auf son guul knalle immer selben werte. bei blutung wird der boni auch nur bis zum 3ten cp hochgerechnet danach broken und bei erdrosseln garnicht. immer stumpf 6 92 ticks 552 dmg laut tooltip sollte es aber skalieren.

**Comment by cionex** [comment]
Kann ich nur bestätigen. Wenn ich einen Mob angreife und mein BiS Gear trage ist der Ausweiden-Durschnitt-Wert nicht größer als mit schlechterem Gear und deutliche weniger AP.  Genauso bei Erdrosseln. Eine Skalierung ist nicht festzustellen.

Wenn ihr hier den Fehler nicht findet, könnt ihr mir aber gerne dieses Instant-5-CP-Makro geben, das wäre ein netter Ausgleich *joking* ;)

**Comment by wahaxlekuke** [comment]
Ich hab das grade mit Eldrian nochmal ausführlich getestet.
