### ISSUE TITLE
Quest Höhle der Frostmähnen

### ISSUE THREAD

**Issue by FastByte23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2360]
Welches Verhalten wird beobachtet?
Man kann die Höhle nicht erkunden

Wie sollte es sich verhalten?
Man sollte die höhle erkunden können

Schritte zur Reproduzierung
die höhle durchlaufen

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=287

**Comment by Slimmer2** [comment]
Hast du jeden Winkel der Höhle erkundet?

**Comment by FastByte23** [comment]
Wir waren zu dritt und haben die Höhle zweimal an zwei Tagen untersucht, bzw alle Mobs darin getötet.

**Comment by Dotox** [comment]
Quest funktioniert ohne Probleme
