### ISSUE TITLE
Pfeile stapeln sich ohne Köcher

### ISSUE THREAD

**Issue by Furan86** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2364]
**Welches Verhalten wird beobachtet?**
Beim spielen eines Ork Jäger wurde bei circa 92 verbliebenen Pfeile ein neuer Satzpfeile als Reserver dazu gekauft. Die 200 neue Pfeile tauchten jedoch nicht im Inventar auf sondern wurden über die restlichen 92 "gestapelt". Ich kann nicht genau sagen wie viele Pfeile dadurch zur Verfügung standen.

**Wie sollte es sich verhalten?**
Solange noch ein Stapel Munition vorhanden ist, sollten neue Stapel ins Inventar/Munitionsbeutel wandern.

**Schritte zur Reproduzierung**
Neuen (Ork) Jäger erstellen, paar Pfeile feuern und neue Pfeile dazukaufen.

**Comment by Dotox** [comment]
Quelle?

**Comment by Furan86** [comment]
Quelle: ein frisch erstellter Ork Jäger. Werd es heute Abend nochmal mit einem Screenshot verifizieren.
