### ISSUE TITLE
Das Heilmittel sammeln: Druidenklassenquest Horde

### ISSUE THREAD

**Issue by questbackgaming** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2366]
Welches Verhalten wird beobachtet?
Obwohl alle Questgegenstände gesammelt sind und im Inventar vorhanden sind, kann das Quest nicht abgeschlossen werden.

Wie sollte es sich verhalten?
Questgeber sollte ein gelbes anstatt graues Fragezeichen über dem Kopf haben und das Quest Fenster sollte mit "Weiter" beendet werden können.

Schritte zur Reproduzierung
1. Kaufe 5x Erdwurzel im AH und hole diese aus dem Briefkasten
2. Töte 5x Kodo und sammle die Hörner
3. Beobachte die Quest, 5/5 bei beiden Zutaten
4. Gehe zum Questgeber und beobachte, dass das Quest nicht abgeschlossen werden kann

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Nachdem ich die Erdwurzel beim Händler verkauft und direkt wieder zurückgekauft hatte, konnte die Quest abgeschlossen werden. Es hat also mit den Trade Goods als Questgegenstand zu tun (evtl. andere Item ID?)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://www.classic-wow.org/datenbank/?item=2449
https://www.classic-wow.org/datenbank/?quest=6128
https://www.classic-wow.org/datenbank/?npc=3448

**Comment by Ryanstekken** [comment]
Passiert öfters. Es hilft dann einfach die Quest abzubrechen und neu anzunehmen.
