### ISSUE TITLE
Quest "Fragmente der Vergangenheit": Teil mit dem Düsterteich

### ISSUE THREAD

**Issue by Beecks** [ClassicWoW/Nefarian_1.12.1_Bugtracker#237]
Welches Verhalten wird beobachtet?
Wenn man sich mit der leeren Phiole neben dem als objekt-angezeigten Düsterteich stellt, kann man die Phiole benutzen, aber nur ohne Erfolg. Anscheind würde immer der Düsterteich fehlen. "Benötigt: Düsterteich".

Wie sollte es sich verhalten?
Klickt man auf die Leere Phiole neben dem Objekt Düsterteich sollte man den Questgegenstand: "Phiole mit Düsterwasser" erhalten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Der Bug wurde schonmal getrackt im alten Forum:
http://www.mmobase.de/forum/bugtracker-archiv/1834-fragmente-der-vergangenheit-reloaded.html

http://www.wowhead.com/item=16973#screenshots: Hier wird das Objekt "Düsterteich" nochmal gezeigt, welches auch in Düsterbruch gut zu erkennen ist und somit auch vorhanden ist.

**Comment by nepsiuh** [comment]
Frustrierenderweise wurde das Problem fast nach einem Jahr immer noch nicht behoben...sehr schade.

Bei mir klalppt es auch nicht. Ich habe den Teich, dass eigentlcih wie eine Hochwase oder ein Hochbrunen aussieht, gefunden. Egal wo ich mich daneben und drunter gestellt habe - das Anlicken der Phiole hat die Meldung in der Art "Fehlt Düsterteich" hervorgerufen und nichst passiert. Entweder ist es ein Koordinatenproblem des Objekts auf der Map und der Event-Trigger ist zu hoch für Zwerge ;) bzw. einfach fehlpaziert. Oder bei dem Übersetzen ins Deutsch funktioniert einer der Links in der Serverdatenbase nicht. Vermutte ich mal. Beides wäre sehr schnell behebbar...

Ich hoffe es klappt bald. Die Endlose Welt-Questreihen sind einer der Reize vor Classic-WoW.

**Comment by Slimmer2** [comment]
push

**Comment by Rushor** [comment]
--
SET @GUID  =5379;
UPDATE `gameobject` SET `position_z`=159.746 WHERE `guid`=49957;
INSERT INTO `gameobject` VALUES 
(@GUID, 300159, 1, 1, 1, -4033.2, 1349.91, 159.746, 3.14159, 0, 0, 0, 0, 900, 0, 1);

**Comment by ChristophKV** [comment]
Leider is der Bug immer noch nicht behoben. Pls debuggen.

**Comment by Rushor** [comment]
debuggen? eher fixen ^^

**Comment by earthballquake** [comment]
Problem besteh noch immer!
Bin grade da gewesen und hab die Meldung auch bekommen.
Mit meinem Paladin. Kummadiomada.
Bitte Fixen.

**Comment by dagochen** [comment]
http://datenbank.classic-wow.org/?spell=20814
http://datenbank.classic-wow.org/?item=16973#created-by
http://datenbank.classic-wow.org/?quest=5247/Fragmente%20der%20Vergangenheit
http://datenbank.classic-wow.org/?object=178224

**Comment by earthballquake** [comment]
The second link is what i need.

The Quest is already buggy.

 

Von: dagochen [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Juli 2016 02:20
An: ClassicWoW/Nefarian_1.12.1_Bugtracker
Cc: earthballquake; Comment
Betreff: Re: [ClassicWoW/Nefarian_1.12.1_Bugtracker] Quest "Fragmente der Vergangenheit": Teil mit dem Düsterteich (#237)

 

http://datenbank.classic-wow.org/?spell=20814
http://datenbank.classic-wow.org/?item=16973#created-by
http://datenbank.classic-wow.org/?quest=5247/Fragmente%20der%20Vergangenheit
http://datenbank.classic-wow.org/?object=178224

**Comment by dagochen** [comment]
Kann mir jemand sagen, wo genau ihr das versucht habt zu benutzen? Ich lauf hier in dem Gebiet Düsterbruch vor den Inis hin und her und find es nicht.

**Comment by hraesvelgr** [comment]
http://wow.gamona.de/forum/threads/d%C3%BCsterteich.57684/ @dagochen

**Comment by dagochen** [comment]
Hab das Teil (auf meinem Server ist der Teich 5 Meter unter der Erde und nicht zu sehen ...da kann ich ja lange suchen!) und den Fehler gefunden. http://datenbank.classic-wow.org/?object=178225 existiert bei uns nicht. Und das ist gameobject für den Spellfocus in der cmangos-Datenbank (@Rushor danke für die Idee).
