### ISSUE TITLE
[AQ40]Twin Emperors - Aggro Verhalten

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2370]
Welches Verhalten wird beobachtet?
Es kann vorkommen, dass beim Port ein Tank Initialaggro von beiden Twins hat.

Wie sollte es sich verhalten?
Es sollte immer der Initialaggro haben, der am nächsten zu den Twins steht.

Schritte zur Reproduzierung
Das gestaltet sich schwierig. Es konnte leider nicht genau ausgemacht werden woran es genau liegt. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/KxRIYq1Bxf4 bei ~5min

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15275
https://datenbank.classic-wow.org/?npc=15276

**Comment by Dotox** [comment]
Ist leider nicht reproduzierbar, wurde schon desöfteren gemeldet. Allerdings ist es genau so eingetragen wie es sein soll, funktioniert aber in seltenen Fällen nicht.

**Comment by Nifexx** [comment]
Es tritt in letzter Zeit aber häufiger auf als früher. Wir hatten gestern ganze 6 Tries mit dem Problem, die letzten 5 Wochen auch ca. 3 Mal. Davor hatten wir das Problem noch nie.

**Comment by Dotox** [comment]
Wenn sich das Problem nur irgendwie reproduzieren lassen könnte :/

**Comment by Ulva-Anorhin** [comment]
Ich bin der Meinung das es zu dem bug erst kommen kann sobald ein Tank gestorben ist (wl oder warri)

**Comment by Nifexx** [comment]
Nope.

**Comment by Brgs** [comment]
Bei who cares heut auch dasselbe Spielchen in 4 Trys am Stück. Ohne das n Tank tot war etc... Der Melee Twin is immer zum Tank auf der Casterseite gerannt. Nicht spielbar so =(

**Comment by Dotox** [comment]
Fix ist bereits auf dem PTR, siehe Label.

**Comment by Ulva-Anorhin** [comment]
Leider wieder verbuggt
und wieder nachdem ein Tank gestorben ist.
https://youtu.be/uXxGeB1xzM8

**Comment by Ulva-Anorhin** [comment]
14.1.18 leider wieder aufgetreten

**Comment by Brgs** [comment]
21.1. bei who cares auch wieder aufgetreten.

War zu beobachten das vor dem eigentlichen Port eine verfrühte Portanimation zu sehen war, bei der offensichtlich die initialaggro verteilt wird...

waren knapp 1400 Leute on und es war n leichter lag bei allen spielern im raid vorhanden... vielleicht lags daran. 

Wie dem auch sei, bitte nochmal drüber schauen!!!

**Comment by Ulva-Anorhin** [comment]
21.01.2018 wieder das selbe

**Comment by Ulva-Anorhin** [comment]
28.01.2018 wieder das selbe... wieder nachdem einer gestorben ist!

**Comment by Ulva-Anorhin** [comment]
04.02.2018 Twins wieder verbuggt... Raid abbgebrochen!

**Comment by dagochen** [comment]
Jede Woche in allen Bugreports zu den Twins einen Kommentar zu verfassen hilft uns nicht weiter.
