### ISSUE TITLE
[AQ40] Twin Emperors - Melee-Twin evaded

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2371]
Welches Verhalten wird beobachtet?
Es kann vorkommen, dass der Melee-Twin ab einem Punkt allen Attacken evaded. Er macht selbst auch keinen Dmg mehr und steht nur da. Die Port-Mechanik, sowie der Castermob funktionieren weiter.

Wie sollte es sich verhalten?
Sollte angreifbar sein und selbst angreifen.

Schritte zur Reproduzierung
...

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/KxRIYq1Bxf4 bei 23:39 kurzer Blick auf den Meleemob.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15275
https://datenbank.classic-wow.org/?npc=15276

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2370

**Comment by Ulva-Anorhin** [comment]
Da dachten wir das der Wichtels eventuell dran schuld ist. 
Wenn der wichtel der nähste ist und phasenverschoben, bekommt er Aggro, kann aber nicht angegriffen werden. 
Vill kann man das mal überprüfen. Stelle auch fernen meinen Hexer auf’n testserver zur Verfügung.
