### ISSUE TITLE
[AQ40] Twin Emperors Käfer

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2372]
Welches Verhalten wird beobachtet?
Die Käfer sind nicht aggresiv haben aber dennoch den Dmg und die HP der mutierten aggressiven Mobs. 
Desweiteren können sie ihrer eigenen Explosion widerstehen.

Wie sollte es sich verhalten?
Sollten normale Werte haben, solange sie nicht aggressiv sind. Sollten nach der Explosion tot sein.

Schritte zur Reproduzierung
Twins pullen -> Käfer beobachten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/KxRIYq1Bxf4 ~16:10, ~18:45

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15316
https://datenbank.classic-wow.org/?npc=15317

**Comment by Dotox** [comment]
Video-Link geht leider nicht :/

**Comment by Nifexx** [comment]
Sry war der Editor Link. Jetzt sollte er funktionieren.

**Comment by Dotox** [comment]
Wurde eben auf dem Testserver in einer etwas überarbeiteten Version getestet und scheint funktioniert zu haben. Das beschriebene konnte nicht (mehr) festgestellt werden.

**Comment by questbackgaming** [comment]
Ähnliches Verhalten lässt sich auch bei diversen Silithiden "Käfern"  (sei es in Silithus, Tanaris überall eigentlich) feststellen. Normalerweise spawnen diese wenn ein normaler Mob getötet wird und haben relativ wenige HP und sind eher nervig als sonstwas. Nun aber besitzen alle diese kleinen Käfer die normalen Hitpoints einer Kreatur diesen Levels. Teilweise ist da kein Durchkommen mehr in den Schwarmbauten.

**Comment by Dotox** [comment]
Dein Kommentar hat überhaupt gar nichts mit dem eigentlichen Report zu tun, daher bitte nur Informationen in den entsprechenden Report, die uns wirklich weiterhelfen. Dein beschriebenes „Problem“ ist ggf. besser in einem neuen Report aufgehoben :)
