### ISSUE TITLE
Satura rennt trotz Spott davon. 

### ISSUE THREAD

**Issue by Ulva-Anorhin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2373]
Welches Verhalten wird beobachtet?
Satura ignoriert Spott

Wie sollte es sich verhalten?
Satura darf keinen Spott ignorieren!

Schritte zur  Reproduzierung. 
Mit mehreren Tanks eine Spott Rotation bei Satura machen. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Bei bedarf kann ich mal schauen ob ich noch. Video hab. Dago kennt es aber und wenn nicht sieht mans spätestens Sonntag wieder.

**Comment by Dotox** [comment]
Video wär super, ich schließ mich aber mal mit Dago kurz.

**Comment by Ulva-Anorhin** [comment]
hier das video von heute (26.11.) AQ 40 Skeram
https://www.youtube.com/watch?v=N_pxi6KPMAk&feature=youtu.be

bei 1:56, 4:27 und 5:51 sieht man deutlich wie ein spott drauf ist und der boss trotzdem wegrennt
leider ist mir jetzt erst aufgefallen das mein mikro in der eingenen aufnahme nicht geht =D

**Comment by Dotox** [comment]
Warum Skeram? Tippfehler? :)

**Comment by Ulva-Anorhin** [comment]
Ja Tippfehler 😅

**Comment by Ulva-Anorhin** [comment]
super, danke!

**Comment by Baraz** [comment]
[Satura](https://www.twitch.tv/videos/187924662): 28:48 - Jäger hat Aggro
28:49 Spott ist drauf und wird ignoriert
28:52 Stun

**Comment by Ulva-Anorhin** [comment]
https://youtu.be/hA68R55sQqM
1:00 rennt er trotz spott weg
2:26 das selbe

**Comment by Ulva-Anorhin** [comment]
Push! Noch nicht behoben. Bitte nochmal drüber schauen
