### ISSUE TITLE
Wegfindung der Gegner

### ISSUE THREAD

**Issue by Nihlatak78** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2376]
Welches Verhalten wird beobachtet?
Häufig ist es so, dass Gegner über unsichtbare Hügel laufen und dann auf und abspringen auf dem Weg zu dem Char, wenn man sie gepullt hat. Eigentlich immer ist das Verhalten in hügeligen Gebiet zu reproduzieren. Manchmal kommt es jedoch auch in absolut flachen Gebieten vor.

Wie sollte es sich verhalten?
Gegner sollten normal auf einen zulaufen.

Schritte zur Reproduzierung
Gegner in hügeligen Gebiten angreifen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Rasse: Mensch
Klasse: Magier
Level: 27

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
---

**Comment by Dotox** [comment]
Das ist leider schon bekannt und lässt sich sehr wahrscheinlich (mit unserem Movement-System) auch nicht 100%tig beheben, quellen, dass es damals nicht auch passiert ist, fehlen trotzdem.
