### ISSUE TITLE
Plündern der Gegner

### ISSUE THREAD

**Issue by Nihlatak78** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2377]
Welches Verhalten wird beobachtet?
Häufig wird nicht korrekt geplündert. Wenn man Gegner plündrt, während noch ihre Sterbeanimation läuft, lassen sich Gegner häufig nicht korrekt plündern oder es wird danach noch Beute angezeigt, obwohl keine mehr vorhanden ist. Manchmal hilft es dann erneut zu looten, damit das Glitzern aufhört, manchmal aber auch nicht.

Wie sollte es sich verhalten?
Mobs sollten sich auch während der Sterbeanimation schon plündern lassen und vor allem nach dem Looten nicht mehr glitzern.

Schritte zur Reproduzierung
Einfach eine Reihe von Mobs nach Gang umhauen, kommt immer mal wieder vor.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Rasse: Mensch
Klasse; Magier
Level: 27

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
---

**Comment by Dotox** [comment]
Danke, ist bereits als allgemeines Problem des Loot-Systems bekannt.
