### ISSUE TITLE
Der Blick zu den Sternen

### ISSUE THREAD

**Issue by Nihlatak78** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2379]
Welches Verhalten wird beobachtet?
Laut Questbuch ist das Quest schon grün, als Level 27 Mage sollte der Gegner für den letzen Teil der Quest also höchstens Stufe 24 sein. Schon vor der Höhle sind die Oger aber Stufe 30 und der Oger mit dem Monokel hat laut der Datenbank Stufe 33, bis zu dem bin ich jedoch gar nicht gekommen. Also auch hier wird wieder etwas nicht richtig im Questbuch angezeigt. 

Wie sollte es sich verhalten?
Grüne Quest sollten leicht zu erfüllen sein und nicht zu Gegnern führen die 5 oder mehr Level über einem sind.

Schritte zur Reproduzierung
siehe Verhalten oben

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Rasse: Mensch
Klasse: Magier
Level: 28 ( zu dem Zeitpunkt wo ich dort war aber noch 27)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Quest: https://datenbank.classic-wow.org/?quest=181
Oger Zzarc'Vul: https://datenbank.classic-wow.org/?npc=300

**Comment by Dotox** [comment]
Quellen bitte

**Comment by Nihlatak78** [comment]
Quest und NPC sind angegeben, was braucht ihr noch für Quellen???

**Comment by Dotox** [comment]
Für deine Behauptung:

>Grüne Quest sollten leicht zu erfüllen sein und nicht zu Gegnern führen die 5 oder mehr Level über einem sind."

Also Einträge aus dem Jahr 2005/06 die beweisen, dass die Kreaturen nicht die hier angegebene Stufe hatten.

**Comment by Nihlatak78** [comment]
Sorry, verstehe die Logik gerade nicht. Falsche Einträge im Questbuch werden also nicht gefixt, wenn die im Original schon falsch waren? Anders formuliert: Offensichtliche Fehler werden bewusst beibehalten?

**Comment by Nihlatak78** [comment]
http://de.wowhead.com/quest=181/der-blick-zu-den-sternen

In diesem Falls sollte WoWhead ja als Quelle dienlich sein, da es diese Quest ja auf den Liveservern nicht mehr gibt. Siehe rechts Modus. Damit wäre wohl bewiesen, dass die Quest fälschlicherweise schon auf Stufe 27 als grün (also leicht) markiert wird.

**Comment by Dotox** [comment]
Wenn du was behauptest, musst du es belegen. Wenn die Quest grün ist, kanns sein, dass sie ein falsches Level hat oder die benötigten Mobs zu hoch sind. Um das zu korrigieren brauchen wir entsprechende Nachweise von damals, ein aktueller wowhead-link gehört nicht dazu, auch wenn die quest nicht mehr offiziell verfügbar ist.

**Comment by hraesvelgr** [comment]
simple frage: hängt die einteilung der farben einer quest im questlog mit dem mindestlevel zum annehmen zusammen? wenn ja, ist das hier nicht änderbar, und das hier könnte geschlossen werden.
