### ISSUE TITLE
Düsterbruch: Verstaubte Folianten nicht lootbar während man im Kampf ist.

### ISSUE THREAD

**Issue by rdkli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2380]
**Welches Verhalten wird beobachtet?**
Yo! Ich war letztens in Düsterbruch und habe versucht mit meinem Schurken verstaubte Folianten zu farmen. Als ich dann nach DB Nord kam, war ein Foliant bei der Bank zwischen den zwei Mages, welche sich auf der Platzform von Wache Fengus befinden. Als ich dann einen gekopfnusst hatte und den einen geblendet hatte, wollte ich den Folianten looten. Es kam aber die Meldung: "Während dem Kampf nicht möglich" ... 
Da dies mein erster Eintrag ist: Ist das verhalten gewollt? Falls nicht, ist es wohl ein Bug.
**Wie sollte es sich verhalten?**
Die Folianten sollten auch Infight lootbar sein
**Schritte zur Reproduzierung**
DB besuchen, infight kommen und versuchen einen Folianten zu looten
**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
https://github.com/elysium-project/server/issues/1430
(ich weiss, elysium, aber alles schön beschrieben)
**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?object=179547
https://datenbank.classic-wow.org/?object=179548

**Comment by rdkli** [comment]
Merke grad beim Durchklicken der beiden Itemlinks der Folianten:
Ist das absicht das man nen Folianten ohne Dropchance für Foror's Kompendium erwischen kann?

**Comment by Dotox** [comment]
>Ist das Absicht das man nen Folianten ohne Dropchance für Foror's Kompendium erwischen kann?

Nein, sind einfach Dummys und Platzhalter.

**Comment by rdkli** [comment]
Alles klar - bitte trotzdem den Eingangspost noch Kategorisieren :)

**Comment by hraesvelgr** [comment]
"quellenangabe not found"

**Comment by dagochen** [comment]
Der Link zum Elysium Bugtracker ist leider tot.
