### ISSUE TITLE
Goldvorkommen viel zu zahlreich

### ISSUE THREAD

**Issue by questbackgaming** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2382]
*edit*: (26-11-2017 17:38)
Goldminen in Goldvorkommen geändert

Welches Verhalten wird beobachtet?
Goldvorkommen sind in Gebieten wie Tausend Nadeln oder Tanaris  [Diesteltal im Südwesten z.B.] (aber auch sonst wo) viel zu zahlreich zu finden.

Wie sollte es sich verhalten?
Goldvorkommen sind ja an sich ein "Rare Spawn" eines normalen Vorkommens. So habe ich es zumindest bisher immer interpretiert, und sollte dies auch bleiben.

Schritte zur Reproduzierung
Gebiete anschauen und Goldvorkommen zählen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
none

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
none

**Comment by Dotox** [comment]
Was für Minen meinst du?

**Comment by questbackgaming** [comment]
Abbaubare Goldvorkommen

**Comment by Dotox** [comment]
Achso, die Vorkommen meinst du. Wir arbeiten seit Mitte August daran, die Erzvorkommen für alle Gebiete zu überarbeiten. Es gibt aktuell viele Stellen an denen zu viele, oder auch zu wenige Vorkommen plaziert sind. Auch die prozentuale Verteilung der verschiedenen Erze pro Gebiet wird angepasst. Genaue Informationen dazu findest du hier: https://community.mmobase.de/classic-server-news/10946-testphase-erz-patch.html

**Comment by questbackgaming** [comment]
Falls ihr Hilfe gebrauchen könnt, meldet Euch ruhig.

**Comment by dagochen** [comment]
@questbackgaming 
Der cmangos-Source ist unter https://github.com/cmangos/mangos-classic einsehbar. Wenn du Fehler bei uns findest oder hier im Bugtracker und die bei der Version reproduzieren und fixen kannst, kannst du uns diese Bugfixes gern zur Verfügung stellen. Manche Fehler sind leider inzwischen allerdings sehr "Nefarian-Speziell", da an unserm Source ja fortlaufend weitergearbeitet wurde ;)
