### ISSUE TITLE
[AQ40] Ouro - taucht direkt wieder ab

### ISSUE THREAD

**Issue by Nifexx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2386]
Welches Verhalten wird beobachtet?
Nachdem Ouro auftaucht ist er kurz zu sehen, taucht dann aber direkt wieder ab. Man kann ihn nicht angreifen/spotten.

Wie sollte es sich verhalten?
Er sollte eine gewisse Zeitspanne angreifbar/spottbar sein und erst danach abtauchen, falls er keinen in Melee-Range zum attackieren hat. 

Schritte zur Reproduzierung
Ouro pullen, das Auftauchen abwarten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/2Pl2XOzSsUE (bei ~0:40) - Das ganze wird schlecht reproduzierbar sein, trat bei uns diese Woche konsequent beim ersten Auftauchen auf, danach nicht mehr. Der Bugreport dient eher der Vollständigkeit.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15517

**Comment by Dotox** [comment]
Denke habe den Fehler gefunden und behoben, kann es alleine aber schlecht testen, zumal das auch nicht immer auftritt, wie ich das beobachten konnte.
