### ISSUE TITLE
Worldboss Taerar resettet oft

### ISSUE THREAD

**Issue by Ulva-Anorhin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2387]
Welches Verhalten wird beobachtet?
Taerar resettet manchmal direkt nach dem er seine Fähigkeit "Arcane Blast" gewirkt hat.
"Arcane Blast" macht seinen DMG und Knockback richtig.
Oft ist man nach dem Knockback außer Kampf und er resettet deswegen?
Meiner Meinung ist es am häufigsten im Ashenvale, vill liegt es auch iwie am Gelände...
Haben auch schon verschiedene Tank Positinen versucht.
Wie sollte es sich verhalten?
Er sollte deswegen nicht resetten
Schritte zur Reproduzierung
Taerar pullen und zuschauen =D
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Aus Tank Sicht leider schlecht möglich den Knockback des Raids auf Video zu bekommen.
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=14890

**Comment by Dotox** [comment]
Ich kann da auf Anhieb nichts finden, müssten wir ggf. mal auf dem Testserver durchgehen oder wenn ihr gutes Videomaterial habt, kann ich es auch darüber versuchen herauszufinden.
