### ISSUE TITLE
Kochquest (Grubenratteneintopf) im Brachland nicht verfügbar

### ISSUE THREAD

**Issue by Ingwin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2388]
Welches Verhalten wird beobachtet?
Im Brachland gibt es einen NPC namens "Grub" nahe dem Crossroads bei 55,3 | 31,8 in dem kleinen turmähnlichen Haus links von der Strasse in Richtung Ratchet. Dieser NPC ist ein Questgeber für eine Kochquest, die er allerdings nicht anbietet.

Wie sollte es sich verhalten?
Ab Stufe 15 sollte man dort eine Kochquest annehmen können und ihm 8 Grubenratten aus der Ausgrabungsstätte ganz im Süden des Brachlands bringen. Bei Abschluss erhält man ein paar Eintöpfe sowie das Koch-Rezept Grubenratteneintopf.

Schritte zur Reproduzierung
---

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Die Grubenratten findet man tatsächlich am angesprochenen Ort (48,0 | 86,0) und man kann sie auch korrekt looten, nachdem man sie erschlagen hat. Die Questitems/Kochzutaten sind also implementiert.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
(Questgeber) Grub:
https://datenbank.classic-wow.org/?npc=3443

Grubenratte (Tier)
https://datenbank.classic-wow.org/?npc=3444

Grubenratte (lootbares Item)
https://datenbank.classic-wow.org/?item=5051

Rezept:
https://datenbank.classic-wow.org/?item=5487

Grubenratteneintopf (Verbrauchbar)
https://datenbank.classic-wow.org/?item=5478

Viele Grüße

**Comment by booneyclassic** [comment]
Hallo Ingwin!

Ich habe die Quest mal gemacht und es hat funktioniert. Beachte bitte das manche Koch-Quests nicht nur eine Levelanforderung haben, sondern auch eine Anforderung an deinen Kochskill stellen. Beispiele sind zum Beispiel die Kochlehrer in SIlithus oder auch in Gadgetztan.

Welchen Skill du genau haben musst, habe ich jetzt nicht recherchiert, aber möglich ist die Quest definitiv. Vllt geht es ab Kochskill 90 oder 125?

LG

**Comment by Ingwin** [comment]
Hallo!
Ich habe deinen Rat befolgt und bin mit einem anderen Char mit Kochen auf Skill 227 zum Questgeber. 
-> Ich konnte mit ihm tatsächlich den Quest annehmen.

Finde ich zwar seltsam, da es ja keine Kochquest ist sondern nur ne Quest für ein Rezept, wie es viele gibt und bei denen man nicht mal kochen geskillt haben muss um sie anzunehmen, aber ok.

Die Bug-Meldung kann dann geschlossen und oder gelöscht werden!
Gruß

**Comment by booneyclassic** [comment]
Du könntest höchstens recherchieren ob das so richtig ist.
Schließlich ist das ein Rezept für Skill 90 und daher ist es schon ungewöhnlich, das es erst ab Skill 225 zu erlernen ist.


LG

**Comment by Ingwin** [comment]
ich weiß ja nicht ob es unter 225 auch möglich ist... mit dem Char mit dem ich den Quest eigentlich machen wollte, hatte gar kein Kochkunst geskillt... dazwischen hatte ich so keinen...

Dachte es läuft wie bei den Löwensteaks oder Rotkammgulasch, milde Schildkrötensuppe usw. - da braucht man keinen Kochskill für die Quest.

**Comment by Horim** [comment]
Diese Quest konnte ich bislang immer annehmen, sofern ich Kochkunst gelernt hatte (1/300) und die Level Anforderungen erfüllt waren. Kann jedoch sein das ich das mit einem anderen Server verwechsle.
