### ISSUE TITLE
Flugpunkt Kalimdor

### ISSUE THREAD

**Issue by Drunil** [ClassicWoW/Nefarian_1.12.1_Bugtracker#239]
Moin,

nachdem mein Premium ausgelaufen ist, sind meine Flugpunkte anderts als erwartet. Mit Premium habe ich alle Flugpunktmeister angesprochen, hatte jedoch auch den Bug wie https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/63 (siehe Bild 1). 
Ohne Premium kann ich in Kalimdor nur noch zwischen Ratchet, Theramore, Un Goro, Tanaris; Desolace, Thalanaar und Feathermoon hin und zurückfliegen. (Bild 2)
Von Astranaar kann ich nirgendwo hinfliuegen. (Bild 3)
Vom Teuelswald kann ich nur Winterspring und umgekehrt. (Bild 4)
Die übrigen Flugpunkte habe ich noch nicht getetstet. Da ich aber bald wieder Premium habe wird der Bug hoffentlich weg sein. Aber ich schreibe dann nochmal wie es ausschaut.

Mfg Drunil

Bild1 
![unbenannt](https://cloud.githubusercontent.com/assets/10051001/5283632/12a9a8e4-7b0f-11e4-92ca-f9da411595ad.png)

Bild 2
![1](https://cloud.githubusercontent.com/assets/10051001/5283636/168e2f98-7b0f-11e4-952b-82eca273530b.jpg)

Bild 3
![2](https://cloud.githubusercontent.com/assets/10051001/5283638/1c63ec5a-7b0f-11e4-8e1a-d1f61f026edf.jpg)

Bild 4
![3](https://cloud.githubusercontent.com/assets/10051001/5283651/2c533788-7b0f-11e4-91fb-d33f45aeb7fb.jpg)

**Comment by Drunil** [comment]
Nach dem letzten patch hats bei mir geklappt :D also kann geschlossen werden

**Comment by Slimmer2** [comment]
Das Ist abhängig von Premium
Mit Premium sind alle Flugpunkte beider Fraktionen verfügbar.
Bei Horde gibt es auch eine Fraktion die dann alle Allianz Flugpunkte dann hat, glaube das waren die Tauren.
