### ISSUE TITLE
Flugmount/pvp kill

### ISSUE THREAD

**Issue by xuffix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2390]
Welches Verhalten wird beobachtet?
ich wurde just in dem moment gekillt, wo ich abheben wollte.
Wie sollte es sich verhalten?
entweder kill oder abheben :)
Schritte zur Reproduzierung
beim abheben gekillt werden
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc. 9
hab ich im bilder channel geportet. 30.11.2017 um 22:53Uhr
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by booneyclassic** [comment]
Du musst Quellen angeben, das es so ist wie du sagst

**Comment by Larnak1** [comment]
Nur, wenn es kein offensichtlicher Bug ist. Allerdings geht aus der Beschreibung nicht genau hervor, was dann eigentlich passiert ist... ok, er wurde just in dem Moment getötet, als er abheben wollte. Und dann? Nur weil man gerade einen Zielpunkt aussucht, sollte man wohl kaum immun gegen Schaden werden.

**Comment by Blattgreen** [comment]
Das war wohl die Übertragungsrate bedingte Verzögerung, welche häufig bei Online Multiplayer Spielen, zu seltsamsten Verhalten von Spielmechanismen wie zum Beispiel beim Erledigen oder Erledigt werden führt!
Allerdings würde ich micht trotzdem freuen wenn du deine Eröterungen mit mehr Details ausführen würdest!
