### ISSUE TITLE
Quest fehlerhaft: Questmob Arra'chea in der Quest "Riten der Erdenmutter" taucht nicht auf

### ISSUE THREAD

**Issue by Kirparon** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2391]
**Welches Verhalten wird beobachtet?**

Bei der dritten und letzten Questen der "Riten der Erdenmutter", lässt sich der Questmob Arra'chea nicht auffinden.

Ich habe ihn im Osten von Thunderbluff mit einer ganzen Gruppe von Leuten umfangreich gesucht, aber er war nicht dort. Ich bin das gesamte Gebiet abgegangen, indem er sich laut der Classic-WoW.org Datenbank aufhalten sollte, aber er ließ sich dort nicht finden. 

Ich habe dann sogar 10 Minuten an seinem Spawnplatz gewartet, aber auch dort ist er nicht aufgetaucht. Ich bin mir deshalb sicher das er nicht dort ist und auch nicht spawnt. Hierbei muss es sich demnach um einen Bug handeln.

**Wie sollte es sich verhalten?**

Arra'chea sollte im Osten von Thunderbluff patroullieren bzw. überhaupt spawnen.

**Schritte zur Reproduzierung**

Einfach dort im Osten langlaufen. Man wird ihn nicht finden. Die Spawnzeit liegt angeblich bei 1 Minute.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Keine.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

_Quest:_ https://datenbank.classic-wow.org/?quest=776

_Questmob:_ https://datenbank.classic-wow.org/?npc=3058

**Comment by booneyclassic** [comment]
Doch, der ist schon da^^ Hab extra nachgeschaut 👍  Man muss nur etwas suchen!
[Klick mich](https://imgur.com/a/0dpml)

**Comment by Kirparon** [comment]
Ach ist ja krass :-D

Ich bin wirklich so lange hin und her gelaufen. Ok vielen Dank dafür! Ist ja erfreulich das es kein Bug ist! Läuft er denn auf der Route der WoW Classic Datenbank von euch entlang? Oder nimmt er eine andere? Habe mich nämlich extra dort aufgehalten.

**Comment by booneyclassic** [comment]
Er läuft die Route wie in der Datenbank angegeben, im Uhrzeigersinn.
Lauf also am besten gegen den Uhrzeigersinn, sonst dauert es ewig da du ja nur zu Fuß bist^^
