### ISSUE TITLE
Worldbuff abgabe fail/bug

### ISSUE THREAD

**Issue by Ulva-Anorhin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2396]
Welches Verhalten wird beobachtet?
Wenn man einen ZG, Ony oder Nef Buff abgibt und sich ausloggt oder wegportet, gibt es keinen Buff.
Wie sollte es sich verhalten?
Ich weiß nicht und finde auch nichts ob es so gehört, ABER mein Vorschlag wäre ob man den Buff nicht auf einen NPC wirken kann (zb q Geber), so dass es nicht mehr vorkommt das der Buff nicht zustande kommt, sobald der Q Abgeber Offline ist
Im Moment wird der Buff auf den Spieler gewirkt der die Q abgibt und alle in zb. SW (bei ony oder nef).

Schritte zur Reproduzierung
Worldbuff abgeben und ausloggen bevor der Buff kommt. Mit 2. Char beobachten.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=7496  > Ony Q
https://datenbank.classic-wow.org/?item=18422

https://datenbank.classic-wow.org/?quest=7781  > Nef Q
https://datenbank.classic-wow.org/?item=19002

https://datenbank.classic-wow.org/?quest=8183  > Hakkar Q
https://datenbank.classic-wow.org/?item=19802  > Item

**Comment by hraesvelgr** [comment]
frage: wieso sollte der questgeber bei der abgabe der quest offline gehen?

**Comment by Ulva-Anorhin** [comment]
Weil es sehr oft vorkommt...
Zb weil man Umloggen möchte oder sw überfüllt ist und es zum dc kommt.

**Comment by hraesvelgr** [comment]
klar, es ist eine sinnvolle suggestion, jedoch wird sowas eher schwer implementiert werden. 

dc's gibt es halt, und umloggen: hey, da ist man echt selber schuld, wenn man so ungeduldig ist.
