### ISSUE TITLE
Bugs aufgrund der Resistenz Änderungen #Ragnaros

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2397]
Welches Verhalten wird beobachtet?
Bei Ragnaros kriegt der Tank trotz 315 Feuerresi jeden Kick durch die Fähigkeit [Wrath of Ragnaros](https://datenbank.classic-wow.org/?spell=20566) ab.

Wie sollte es sich verhalten?
Der Tank sollte dem Kick widerstehen können, abhängig von der Feuerresi.

Schritte zur Reproduzierung
Mit 315 Feuerresi an Ragnaros stellen und den Kick abwarten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Mensch Krieger

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=20566
https://datenbank.classic-wow.org/?npc=11502

**Comment by Dschagannad** [comment]
Die gleiche Problematik tritt auch bei anderen Zaubern auf, die vorher bei "ausreichend" Widerstand gut zu handlen waren.

Beispiele:

Flammenpuffer Firemaw in BWL
https://datenbank.classic-wow.org/?spell=23341

Giftatem der Gründrachen (leider den Zauber nicht gefunden)

Anscheinend sind volle Resists selbst bei 315 Resis extrem unwahrscheinlich, stattdessen treten fast nur Teilresists + sekundärer Effekt (Kick bei Ragi, Debuff bei Firemaw) auf.

**Comment by Dschagannad** [comment]
Auch Zauber von Spielern verhalten sich merkwürdig:

Sowohl auf Bossen mit 5 Resi (reduziert durch Fluch) als auch auf Mobs mit 0 Resi (abgefragt mit Makro) gab es Teilresists. Und das sowohl mein Char 5 Teile T2,5 = insgesamt 40 Spell Pen trägt. 
Da gab es vor dem Patch keinerlei Resists und sollte es auch nach dem Pach keine geben. Insbesondere die Spell Pen scheint gar nicht zu funktionieren.

**Comment by Larnak1** [comment]
Haben die Problematik bei Feuerschwinge und Lethon gestern noch beobachten können, das Tag "Fix auf Nefarian" kam hier schon vorgestern drauf, da scheint also noch irgendwas nicht zu stimmen

**Comment by Sheed90** [comment]
@Larnak1 dafür bitte einen separaten Bugreport eröffnen. Ich hatte extra das #Ragnaros hinter den Titel gemacht. 

Gruß

**Comment by Larnak1** [comment]
Ist mir aufgefallen. Allerdings scheint es der selber Fehler gewesen zu sein, daher hab ich es hier dazugeschrieben.
