### ISSUE TITLE
Narbengolem in den Pestländern lassen das Gift zu schnell ticken (0,3 anstelle von 3 Sec)

### ISSUE THREAD

**Issue by Rashick** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2400]
Moin Moin,

Plüschkatze von Epic hat gerade gemerkt, dass folgender Bug in den Pestländern zu finden ist. 
Da Sie kein Account hier hat schreibe ich für Sie in den Bugtracker. 

Welches Verhalten wird beobachtet?
* Es wurde festgestellt, dass der NPC mit 0.3 oder 0.5 sec mit dem Gift um sich wirft.
* Intervall: 0,3-0,5 Sekunden

Wie sollte es sich verhalten?
* Intervall: 3 Sekunden

Schritte zur Reproduzieren
* in den Pestländern gegen ein Gegner kämpfen. 
* 37.8, 52.1
* 35.3 / 58.7 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
* Nicht vorhanden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
* Kreatur: https://datenbank.classic-wow.org/?npc=8545#drop
* Zauber: https://datenbank.classic-wow.org/?spell=16577

**Comment by Dotox** [comment]
Kann ich auf dem Testserver nicht mehr feststellen.
