### ISSUE TITLE
Headmaster's Charge verbuggt

### ISSUE THREAD

**Issue by revbreeze** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2405]
Welches Verhalten wird beobachtet?
Der Int buff von [Headmaster's Charge] verschwindet sobald man den stab nicht mehr trägt.

Wie sollte es sich verhalten?
Int buff sollte erhalten bleiben.

Schritte zur Reproduzierung
Buffen, anderen stab u.ä. anlegen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Droppt in Scholo (Endboss)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
ITEM:
https://datenbank.classic-wow.org/?item=13937
BUFF:
https://datenbank.classic-wow.org/?spell=18264

**Comment by Sheed90** [comment]
Bitte die Links des Items und der Zauber hinterlegen, sonst wird dein Bugreport nicht anerkannt.

**Comment by revbreeze** [comment]
Hi. Werde ich umgehend nachtragen.
Vielen Dank!

Am 08.12.2017 13:21 schrieb "Sheed90" <notifications@github.com>:

**Comment by revbreeze** [comment]
ITEM:
http://db.vanillagaming.org/?item=13937
BUFF: 
http://db.vanillagaming.org/?spell=18264

**Comment by Haudraufinix** [comment]
@hraesvelgr Ist kein Bug, bei dem Buff handelt es sich um eine Aura, nicht um einen zeitlich begrenzten Buff

**Comment by hraesvelgr** [comment]
joa ok.
