### ISSUE TITLE
Firemaw: Flame Buffet tickt zu schnell

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2406]
**Welches Verhalten wird beobachtet?**
Flame Buffet von Firemaw wird alle zwei Sekunden gewirkt.

**Wie sollte es sich verhalten?**
Flame Buffet von Firemaw sollte alle fünf Sekunden gewirkt werden.

**Schritte zur Reproduzierung**
Firemaw angreifen

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://leftoversraiding.org/index.php/topic/781/1/blackwing-lair-summary---pt.-2-%28firemaw-ebonroc-flamegor%29.html
http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/der-pechschwingenhort/feuerschwinge/
http://www.strike-us-if-you-can.de/main/frame/HighEndRaid/Pechschwingenhort/bwl-1.htm

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Flame Buffet: https://datenbank.classic-wow.org/?spell=23341
Firemaw: https://datenbank.classic-wow.org/?npc=11983

**Comment by Dotox** [comment]
Nope, siehe Videos.
