### ISSUE TITLE
Quest [60+]Treffen in Stormwind -Knappe Rowe ist nicht an seinem Platz

### ISSUE THREAD

**Issue by Bassemoluff** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2408]
Das Quest verlangt ein Treffen mit dem Kappen Rowe vor den Toren Sturmwinds

Der Knappe sollte für mich vor den Toren zu sehen sein um mit ihm zu interagieren

Andere Spieler können den Knappen ebenfalls nicht sehen.

**Comment by hraesvelgr** [comment]
ist evtl durch ein vorheriges event noch nicht gespawnt. oder wurde getötet. wie lange habt ihr gewartet? habt ihr die quest zu mehreren tageszeiten versucht?

**Comment by Bassemoluff** [comment]
Ich habe ihn an zwei Tagen jeweils zu verschiedenen Zeiten versucht zu finden.

**Comment by hraesvelgr** [comment]
das ding ist eben, dass er für die ony pre wichtig ist (iirc) und wenn der wirklich fehlen würde, gäbs hier einen fetten aufstand. 

also würd ich eher sagen du hattest nur pech
