### ISSUE TITLE
Todesmine - Bereich der Untoten minenarbeiter.

### ISSUE THREAD

**Issue by Agorass** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2409]
Welches Verhalten wird beobachtet?   -   **Wenn man dort stirbt und den Geist freilässt, wird man direkt als Geist wieder über seinem Leichnam gespawnt, und man kann sich Wiederbeleben, ohne voher vom Friedhof zu seiner Leiche laufen zu müssen.**

Wie sollte es sich verhalten?  -  **Wenn man dorst stribt, sollte man nach dem freilassen am Friedhof der Späherkuppe gespawnt werden.**

Schritte zur Reproduzierung  -  **In die DM laufen, und sich in den Untotenbreich begeben, dort sterben und den Geist freilassen.**

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=168
https://datenbank.classic-wow.org/?quest=167

https://datenbank.classic-wow.org/?item=1894
https://datenbank.classic-wow.org/?item=1875

https://datenbank.classic-wow.org/?npc=623
https://datenbank.classic-wow.org/?npc=624
https://datenbank.classic-wow.org/?npc=625

https://datenbank.classic-wow.org/?npc=626

**Comment by hraesvelgr** [comment]
ich hab nix gegenteiliges gefunden aber...quelle?

**Comment by Agorass** [comment]
?

**Comment by hraesvelgr** [comment]
eine quellenangabe, die bestätigt,d ass es tatsächlich so war. nur weil du sagst "das war so" heißt es nicht,d ass es auch so ist.

**Comment by Agorass** [comment]
? aber dafürist doch die Reproduzierung oder nicht? Ich mein ich kann schon ein Video machen wenn ich da wieder bin. Ich dachte nur weil das doch ziemlich krass is wenn Leute da die Quest machen und nach 2sec wieder leben weil sie nichtmal laufen müssen.

**Comment by Dotox** [comment]
Ja hier fehlt offensichtlich die Verlinkung zum Friedhof.

**Comment by Ulva-Anorhin** [comment]
Das selbe ist wenn man vor düsterbruch oder maraudon.... vill gilt das vor allen inis

**Comment by hraesvelgr** [comment]
@Agorass es ging nicht um die reproduzierbarkeit, sondern dass du beweist, dass es blizzlike ist, dass leute an den fh geportet werden. also..eigentlich. dotox hat aber schon bestätigt, dass die verlinkung fehlt.

**Comment by Blattgreen** [comment]
Man kann sich tatsächlich vor Ort wiederbeleben, allerdings wird die Zeit bis zur Wiederbelebum jedesmal erhöht!
