### ISSUE TITLE
[AQ40] Princess Huhuran - Noxious Poison

### ISSUE THREAD

**Issue by Baraz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2412]
Welches Verhalten wird beobachtet?
Der Zauber wird nicht als binary Spell behandelt, es gibt partielle Resists pro Tick.

Wie sollte es sich verhalten?
Der Zauber hat zwei Komponenten, Gift-DoT + Silence und sollte somit als binary Spell behandelt werden. Daraus resultiert entweder treffen oder nicht treffen.

Schritte zur Reproduzierung
Huhuran angreifen und Noxious Poison abwarten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
[Video 1](https://www.youtube.com/watch?v=zd3E7Hb04Kw): Beispiele 0:16, 0:35, 0:46, 1:10, 1:30, 2:05, 2:18, 2:46 -> siehe Kampflog
[Video 2](https://www.youtube.com/watch?v=zYvXQ1Bl-xg): Beispiele: 1:01, 1:50, 4:55, 5:03
[Video 3](https://www.youtube.com/watch?v=Y7haxdAFW-E): Beispiele: 0:30
[Video 4](https://www.youtube.com/watch?v=bh_1rpm5KqM): Beispiele: 0:45, 1:16

Der Silence-Effekt sollte nur das Initialziel treffen, der DoT dann Ziele im Umkreis von 15 Yards. Inwiefern es da dann eine Unterscheidung zwischen binary/non-binary gibt/geben kann, keine Ahnung.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
[Prinzessing Huhuran](https://datenbank.classic-wow.org/?npc=15509)
[Noxious Poison](https://datenbank.classic-wow.org/?spell=26053)

**Comment by SirBeansen** [comment]
Alle Dots können Teilresisten. Das schon richtig so. Der Inital Dot sollte aber auch durch resi Gear seltener auftreten.

**Comment by Baraz** [comment]
Für DoTs, die nur eine Schadenskomponente haben ist das korrekt, die sollten dann auch als Non-binary behandelt werden. Aber Noxious Poison gehört dank des Silence-Effektes nicht dazu.

**Comment by rachmin** [comment]
Unabhängig von der Thematik: Ist das erste Video (Temple of AQ - 40man - Princess.Huhuran - DND) zweifelsfrei von Vanilla bzw. kann jemand bestätigen, dass es von Classic ist? (Allein die verpeilte Dotleiste beim Boss ist für mich noch kein hinreichendes Indiz) [Ich frage nach, weil doofe Sachen passieren, die Kopfschmerzen verursachen.]

**Comment by Baraz** [comment]
Zweifelsfrei wird man das nicht bestätigen können, Indizien sind 4:3-Format, Server und Gilde haben existiert, Addon-Versionen sehen akzetabel aus, genutztes Gear und Spells suggerieren Classic.

Der Magier castet weiter, weil nur das Initialziel gesilenced wird/werden soll. Möglicherweise hat Blizzard das irgendwann mal umgestellt, das wäre aber meines Wissens nach dann undokumentiert.

**Comment by dagochen** [comment]
Der Zauber wird bereits als binary bei uns berechnet. Partial Resists können dennoch bei Dot-Effekten auftreten.
