### ISSUE TITLE
Server Verbindung unterbrochen an bestimmter Stelle in Dunkelküste/Cliffspring

### ISSUE THREAD

**Issue by samweis78** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2415]
Welches Verhalten wird beobachtet?
Die Server-Verbindung wird unterbrochen, wenn man an einen bestimmten Punkt kommt.

Wie sollte es sich verhalten?
Kein Verbindungsabbruch

Schritte zur Reproduzierung
Unterhalb der Cliffspring-Brücke auf den Wasserfall zuschwimmen, versuchen, auf den rechten Felsen drauf zu springen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://imgur.com/a/qTHri

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
keine

**Comment by Dotox** [comment]
Gibt leider einige, kantige Stellen im Wasser bzw. am Ufer, die hin und wieder dazu führen. Das lässt sich leider nicht ohne Weiteres beheben.
