### ISSUE TITLE
10sek nach login dc

### ISSUE THREAD

**Issue by gorgl** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2420]
Hi 
habe seit etwa einer woche folgendes problem. Etwa 10 sekunden nach dem login werd ich einfach aus dem spiel geschmissen.

das spiel habe ich schon neu drauf gemacht aber das problem besteht noch immer.

Habe den verdacht auf das sicherheitssytem, das ich zwar aus gestellt hatte aber immer noch das symbol für windows defender vor dem wow.exe  symbol.

was kann ich tun. bitte um hilfe.

Danke im vorraus

**Comment by hraesvelgr** [comment]
klingt nach einem problem fürs forum. erstell besser da einen post. ansonsten kann ich nur sagen: porteinstellungen, und wer zum henker braucht windows defender?
