### ISSUE TITLE
Oberhäuptling der Winterfelle, Winterspring

### ISSUE THREAD

**Issue by Spin123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2424]
Der Oberhäuptling der Winterfelle im Dorf bzw, der Höhle der Winterfelle Östlich von Everlook ist Verbuggt und lässt sich nicht mehr Angreifen, bzw geht direkt auf Entkommen.

mod-edit:
https://datenbank.classic-wow.org/?npc=10738

**Comment by Jessienia** [comment]
Das gehört hier nicht rein sondern per GM-Ticket Ingame gemeldet.

**Comment by Ulva-Anorhin** [comment]
24.12. immer noch auf entkommen

**Comment by hraesvelgr** [comment]
@Jessienia kein gm ticket, ist ein pathfinding fehler (nehm ich mal an)
