### ISSUE TITLE
Priester Talent: Inspiration stackt, wenn unterschiedlich geskillt

### ISSUE THREAD

**Issue by Jessienia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2430]
Analog zu dem Bugreport von vor ein paar Tagen, in dem gemeldet wurde, dass verbesserter Schattenblitz mehrmals auf einem Mob sein kann, das gleiche bei Inspiration

_Welches Verhalten wird beobachtet?_
Wenn mehrere Priester das Talent Inspiration unterschiedlich ausgeskillt haben (z.b. 2/3 oder 3/3) kann der Inspirationsbuff von verschiedenen Priestern miteinander stacken. (das Ziel kann mehrere Inspirationsbuffs erhalten)

_Wie sollte es sich verhalten?_
Es sollte nicht stacken. Der schwächere Buff sollte nicht den stärkeren überschreiben können. 

_Schritte zur Reproduzierung_
2 Priester skillen Inspiration unterschiedlich aus und heilen gemeinsam ein Ziel, bis von beiden gleichzeitig der Inspirationsbuff ausgeblößt wird. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
**Talent:**
[Rang1](https://datenbank.classic-wow.org/?spell=14892)
[Rang2](https://datenbank.classic-wow.org/?spell=15362)
[Rang3](https://datenbank.classic-wow.org/?spell=15363)

**Buff:**
[Rang1](https://datenbank.classic-wow.org/?spell=14893)
[Rang2](https://datenbank.classic-wow.org/?spell=15357)
[Rang3](https://datenbank.classic-wow.org/?spell=15359)
=> diese sollten nicht gleichzeitig auf einem Ziel sein können bzw nicht miteinander stacken.

Priester mit 2/3 Inspiration:
http://www.directupload.net/file/d/4956/j7w5h7js_jpg.htm

2 Priester: Einer mit 2/3 und einer mit 3/3
http://www.directupload.net/file/d/4956/62bc2swm_jpg.htm

**Comment by Horim** [comment]
Denke das betrifft auch den Rüstungsbuff vom Schamanen, getestet hab ich es nicht, sollte sich aber analog verhalten.
