### ISSUE TITLE
Quest "Treuebeweis" funktioniert nicht.

### ISSUE THREAD

**Issue by Kimonokosch** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2431]
Quest "Treuebeweis" Auf der Insel im Blendwassersee in Tirisfall funktioniert nicht.

Man soll eine Kerze aus der Kiste neben dem NPC nehmen, diese öffnet aber nur einen "Seid Gegrüßt..." Dialog statt einem eine Kerze zu geben. (haben versucht trotzdem weiter zu machen, ging nicht weil keine Kerze)

>mod edit: evtl falsche levelanforderungen? 
https://datenbank.classic-wow.org/?quest=409

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/404

eventuell quest erneut starten?

**Comment by Kimonokosch** [comment]
schon Probiert

**Comment by Kimonokosch** [comment]
Sooo es hat jetzt doch funktioniert! Wir haben nicht reloggt, sind aber später mit lvl.11 wieder gekommen, als die Quest nicht mehr "orange" sondern gelb für uns war. 
Also außer in Tirisfal weiter questen und eben auf lvl.11 kommen haben wir nichts getan, aber es funktionierte wieder.
