### ISSUE TITLE
[Naxxmaras] Atieshquestreihe fight in Stratholme

### ISSUE THREAD

**Issue by Resulut** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2439]
Welches Verhalten wird beobachtet?
Im Atieshfight in Stratholme droppt der Gegner bei mehrerem Entwaffnen, in einem fortlaufendem Bossfight, auch öfter die Waffe. Bislang in 100% der Fälle. 

Wie sollte es sich verhalten?
Er sollte nur beim ersten Entwaffnen die Waffe droppen und dann nicht mehr.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.youtube.com/watch?v=D5wP695sdao Video vom Atieshfight. Man sieht deutlich das seine rechte hand(die mainhand) immer rot aufleuchtet, weil er entwaffnet wird und unter ihm kein schwert das nach dem ersten mal erneut spawnt. Somit funktioniert es hier noch nicht ganz richtig.

**Comment by Dotox** [comment]
Hab mir das gerade angesehen und hatte es im Code eigentlich so hinterlegt, dass es nur einmalig funktionieren sollte. Wo da nun genau das Problem liegt, kann ich noch nicht sagen. Sobald ein "Fix" aufgespielt ist, update ich den Eintrag über die Labels und es kann nochmal versucht werden.

**Comment by Simit90** [comment]
Derzeit droppt Atiesh beim Entwaffnen zu keiner Zeit die Waffe
