### ISSUE TITLE
Tier Füttern

### ISSUE THREAD

**Issue by demokritosia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2441]
Welches Verhalten wird beobachtet? Ich kann mein Pet nur bei geöffneter Tasche füttern

Wie sollte es sich verhalten? Ich sollte das auch aus der Leiste können

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
quelle?
