### ISSUE TITLE
Schmiederezepte für Rezepte in Gadgezan

### ISSUE THREAD

**Issue by PeatMcGrief** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2443]
Welches Verhalten wird beobachtet?
Die Kosten der Rezepte/Pläne für die imperialen Rüstungsteile in Gadgetzan sind doppelt so hoch, wie es in meine Guide (siehe unten) oder dem Questtext steht. Ich weis nicht ob das so gewollt ist, dass es doppelt so viel kostet, wie im Original. Nach meinem Ticket wurde ich hierher verwiesen. 
Link zum Guide: https://blue.mmo-champion.com/topic/104123-guide-schmiedekunst-1-300/

Wie sollte es sich verhalten?
Die Rezepte für die Rüstungsteile sollten, statt 20- 60 Thoriumbarren zu kosten, eigentlich halb so teuer sein.  Ich bin wie gesagt nicht sicher ob das gewollte ist und das ist auch schon die frage die mir der Ticket-beantwortende nicht aufklären konnte.

Schritte zur Reproduzierung
Benötigt Level 50 und Rüstungsschmied. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Hakumis lvl 51 Paladin, 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Questgeber: Derotain Matschnipper Quests heißen so wie die Rüstungsteile also z.B. Imperiale Armschienen, das Abzugebende sind Thoriumbarren
Danke im Voraus

**Comment by Sheed90** [comment]
Es fehlen die Verlinkungen zu unserer Datenbank.

Bitte die Quests verlinken.

**Comment by Dotox** [comment]
Die Quelle ist aus TBC

**Comment by hraesvelgr** [comment]
"under construction"


tbc guide: 

>To get this recipe you will need to do a quest. However, all you need to do for the quest is to **hand in 10 Thorium Bars**, so nothing epic.
