### ISSUE TITLE
[Naxx Opening Event] Ablauf 2. Phase (Kultisten, Splitter)

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2444]
Welches Verhalten wird beobachtet?
Nachdem erstmals das Leben des Nekrotischen Splitter auf 0% Leben reduziert worden ist (= Phase 1), spawnen richtigerweise die Kultisteningenieure (=Phase 2). Sie "heilen" den beschädigten Splitter von 0 allmählich auf 100% und verschwinden, sobald das Leben des Splitter 100% erreicht hat. Phase 1 beginnt wieder mit dem Nekrotischen Splittter. Wenn man sie dabei "verwandelt", hört der verwandelte Kultist auf, den Splitter zu heilen.

Wie sollte es sich verhalten?
Nachdem Phase 1 abgeschlossen ist, folgt Phase 2 und bleibt bis zum "Ende" (d.h. die Kultisten despawnen nicht, sondern bleiben, bis sie verwandelt und getötet worden sind).

Phase 1 ist richtig implementiert (Untote spawnen; das Töten in der Nähe des Splitters zieht dem Splitter Leben ab; Nekrotische Runen droppen). Phase 2 beginnt, sobald der Nekrotische Splitter das erste Mal 0% (1%) Leben hat.
In Phase 2 erscheinen die Kultisteningenieure und ein Beschädigter nekrotischer Splitter. Die Untoten aus Phase1 spawnen und funktionieren weiter wie in Phase1. Die Kultisten bleiben solange an ihren Spawnpunkten, bis alle vier (nach der Verwandlung) getötet worden sind. Das Töten eines verwandelten Kultisten zieht dem beschädigten Splitter 25% Leben ab.
Phase 2 endet, wenn alle vier Kultisten getötet worden sind UND der beschädigte Splitter erneut 0% Leben erreicht hat. Die Invasion "endet".

Unklar bliebt nach der Recherche, ob die Kultisten den beschädigten Splitter sprichwörtlich "heilen" oder ihn (bzw. den Beschwörungskreis) nur funktionell/konditional "beschützen" (im Sinne von: erst wenn sie tot sind UND der Splitter 0 Leben hat, dann endet das Event, weil dann der Beschwörungskreis verschwindet). Ich gehe von Letzterem aus.
Begründung: Zwar taucht bereits in den ersten WoWPedia-Einträgen zum Event ab dem 21. Juni die Formulierung "four Acolytes will appear and start to **heal** it" auf. Die Formulierung kann auch auf ein Missverständnis einer Erstquelle vom Mai 2006 zurückgehen (Beta Reports - Necrologia: "once it's HP is reduced to 0 turn it into a damaged Necrotic shard ... At that point it'll full heal and the 4 Cultist Engineers spawn"). Umgekehrt heisst es im dazugehörigen Quest "Schatten der Verdammnis": "Nachdem Ihr die Verteidigung der **Beschwörungskreise** der Geißel ... ausgeschaltet habt, könnt Ihr den **Akolyten [=Kultisteningenieure], die sie beschützen**, gegenübertreten."

Schritte zur Reproduzierung
Nekrotischen Splitter erstmals auf 0% Leben bringen. Abwarten, bis Kultisten beschädigten Splitter vollgeheilt haben. Nekrotischer Splitter erscheint. Sie despawnen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Ich habe zwar Videos von unseren Tests gemacht, aber o.g. Ablauf ist in den Ausschnitten nicht so gut sichtbar dokumentiert, dass der Zusammenschnitt aus Einzelsequenzen lohnt.
Wir haben das Event in den Verwüsteten Landen gemacht.
Wir haben einmal nur einen Kultisten verwandelt und getötet. In der Zwischenzeit heilten die anderen drei den Splitter voll und verschwanden. Wir begannen bei Phase1 von vorne. Danach haben wir alle 4 Kultisten zugleich verwandelt, der Splitter war bis 18% Leben geheilt worden. Nachdem wir alle vier getötet hatte, war das Event vorbei.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Nekrotischer Splitter: https://datenbank.classic-wow.org/?npc=16136
Beschädigter nekrotischer Splitter: https://datenbank.classic-wow.org/?npc=16172
Kultisteningenieur: https://datenbank.classic-wow.org/?npc=16230
Quest "Schatten der Verdammnis": https://datenbank.classic-wow.org/?quest=9085

Weitere Quellen
- 1.11 Beta Reports - Necrologia - 05-28-2006 09:08 AM, http://www.lurkerlounge.com/forums/printthread.php?tid=4305
(Zentral "once it's HP is reduced to 0 turn it into a damaged Necrotic shard ... At that point it'll full heal and the 4 Cultist Engineers spawn")
- erstmalige "Acolytes start to heal it"-Erwähnung am 21.06.2006: ( https://wow.gamepedia.com/index.php?title=Scourge_Invasion&direction=prev&oldid=168852
- https://www.youtube.com/watch?v=C65pQRSZh6A (Vgl. ab 2:23 mit Kultisten (Phase2, grün-bläulicher Splitter))

// Beschädigter und "normaler" nekrotischer Splitter etwas eindeutiger nachgetragen.

**Comment by Dotox** [comment]
Bedeutet, die Ingenieure können erst angesprochen werden, wenn sie den Kristall vollgeheilt haben?

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2256

**Comment by Sheed90** [comment]
Feedback: Funktioniert wie oben beschrieben.

**Comment by Simit90** [comment]
Mit dem heutigen Charakter-Update scheinen sich wieder einige Probleme eingeschlichen zu haben:
In den Verwüsteten Landen stehen 3 Kultisteningineure herum, jedoch weder Mobs, noch ein Kristall in der Nähe (was ja nicht sein kann, da dieser erst durch das Töten der 3 verwandelten Ingineure verschwindet).

Screen: https://www2.pic-upload.de/img/34688141/KristallkaputtIngineureda.png
Quelle: Simit - Testserver

**Comment by Dotox** [comment]
Sollte wieder funktionieren, hatte unabhängig vom Charakter-Update einen falschen Parameter eingestellt.
