### ISSUE TITLE
[unsicher, ob Bug] Atieshs Aura „Macht des Wächters“ muss nach dem Tod manuell reaktiviert werden

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2445]
Welches Verhalten wird beobachtet?
Nachdem ein Spieler gestorben ist, verschwindet die Wächter-Aura des Atiesh-Stabs (soweit korrekt und nachvollziehbar, weil Spieler tot).
Nachdem besagter Spieler wieder lebt (zur Leiche gelaufen oder wiederbelebt worden ist), wird die Wächter Aura nicht automatisch „reaktiviert“ bzw. der Aura-Effekt bleibt vorerst inaktiv. Auch bei einem Spieler, der in einer Instanz stirbt und zu seiner Leiche zurück in die Instanz läuft, wird die Aura nicht automatisch reaktiviert, sondern bleibt vorerst inaktiv.
Erst das Ab- und erneute Anlegen von Atiesh oder ein Relog reaktiviert die Wächter-Aura.

Da wir nur zu 3. auf dem Testserver waren, konnten wir es nicht für die BGs testen. Wir gehen aber von einem ähnlichen Verhalten aus (Aura wird nach Wiederbelebung durch Geistheiler wahrscheinlich nicht mit reaktiviert werden).

Wie sollte es sich verhalten?
Wir sind uns nicht sicher, ob es so sein soll, wie oben beschrieben (vgl. Pala Aura vs. Krieger Stances nach dem Tod/Wiederbeleben: Pala Aura muss manuell reaktiviert werden, Kriegerstance bleibt erhalten; sind aber Klassenmechaniken und kein Item). Nichtsdestotrotz dürfte schon ein wenig umständlich sein, jedes Mal den Stab ab- und wieder anzulegen, nachdem man gestorben ist.

Schritte zur Reproduzierung
Spieler mit aktiver Atiesh Aura stirbt (durch NPCs, feindlichen Spieler oder Tod durch anderen Schaden ist dabei egal).
Spieler belebt sich wieder oder wird wiederbelebt und hat keine aktive Wächter-Aura (mehr).
Inaktive Wächter Aura bleibt auch bei Zonenwechsel inaktiv bzw. wird nicht reaktiviert.
Erst das Ab- und Anlegen oder ein Relog reaktiviert die Wächter-Aura von Atiesh wieder.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Getestet mit Hexenmeister Atiesh und Gnom Hexenmeister.
Bisher hatten wir noch nicht die Gelegenheit, es mit anderen Klassen-Atiesh-Auren zu testen. Es dürfte aber dasselbe Verhalten auftreten.

Ein damit verbundenes Problem (was wir so nicht beobachtet haben auf dem Testserver) wird hier beschrieben: https://github.com/dalaranwow/dalaran-wow/issues/3525
„When the wielder dies, the aura is continually (attempted to be) re-applied, causing the error message "You are dead" to appear for the wielder every few seconds until they are revived. The aura does not automatically re-apply itself to the revived character. […] The aura should not be re-applied to a dead wielder until after they revive.“

Zusätzlich der Vollständigkeit wegen:
- Wir konnten nicht testen, ob Atiesh im BG Portale öffnet und was dann passiert (siehe Patch 2.3.0: „[Atiesh] Can no longer open portals in battlegrounds.“)
- Der in 1.12.1 behobene Bug des Warlock-Atiesh („Fixed a bug where the warlock version would cause all healing done by party members under the effects of the staff to be reduced to zero.“) trat bei Tests mit einem Priesterheiler nicht auf (im Gegenteil: Atiesh erhöhte der Aura entsprechend die verursachte Heilung).
- Der in 2.1.0 behobene Bug („The party aura from these items will now be reapplied correctly when a player logs into the game while already mounted.“) konnte von uns mit der Hexenmeister-Version nicht reproduziert werden. Im Gegenteil: Nach jedem Login, unabhängig ob auf Mount oder nicht, unabhängig ob Aura vorher aktiv vom Spieler deaktiviert oder nicht, die Aura war nach jedem Login (wieder/automatisch/immernoch) aktiv.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Atiesh, Hohestab des Wächters (Hexenmeister): https://datenbank.classic-wow.org/?item=22630
Atiesh Wächter Aura (Hexenmeister): https://datenbank.classic-wow.org/?spell=28143

**Comment by hraesvelgr** [comment]
wird das gleiche wie hier sein : https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/266

**Comment by Dotox** [comment]
Das bei https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/266 wurde so verändert, dass die Aura beim Tod nicht entfernt wird. Das könnte man hier wahrscheinlich auch machen, allerdings hat man dann die Aura auch als "Geist". Ob die Aura trotz Tod des Spieler funktioniert, weiß ich gerade nicht, könnte man aber mal ausprobieren.

**Comment by Jessienia** [comment]
Folgende Items haben den gleichen Bug:

https://datenbank.classic-wow.org/?item=22691
https://datenbank.classic-wow.org/?item=23207
https://datenbank.classic-wow.org/?item=23206

Reicht das so oder soll ich dazu einen extra Thread erstellen?

**Comment by Dotox** [comment]
Danke, passt soweit @Jessienia 

Hab das mal auf dem Testserver überarbeitet, darf gerne getestet und versucht werden, irgendwas zu verbuggen :P

**Comment by Simit90** [comment]
Derzeit ist es so, dass die Aura "Macht des Wächters" beim "Caster-Damage-Atiesh", also 2% Crit für den Spieler so wie seine Gruppe auch beim Tod des Spielers weiterhin bestehen bleibt.
Bei dem Heiler-Atiesh, also +Addheal für die Gruppe hingegen verschwindet diese beim Tod.
Weiß nicht, ob es hilft, aber konnte oben nicht herauslesen um welche Aura es sich handelt. Sollte also mit der entsprechenden Aura (+crit) oder dem Damage-Atiesh zusammen hängen

**Comment by Dotox** [comment]
Danke @Simit90 sollte behoben sein.
