### ISSUE TITLE
Düsterbruch Nord Buffs /  Schlachtruf des Drachentöters

### ISSUE THREAD

**Issue by CityPlay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2446]
tribut-Run! 

Fengus Wildheit
- Angriffskraft um 200 erhöht für 120 Minuten (Nur Nahkampf +200) (Distanz +0)

Schlachtruf des Drachentöters
- Zaubercrit um 10% erhöht
- Angriffstempo im Nahkampf um 15% erhöht
- Angriffskraft um 140 erhöht (Nur Nahkampf +200) (Distanz +0)
Für 120 Minuten

Die Buffs sind schon nett aber für einen Jäger nicht fair.
Es steht zwar immer Angriffskraft wird erhöht aber es wird nur die Nahkampfangriffskraft erhöht
und nicht die Distanzangriffskraft die aber normalweiser zur Angriffskraft dazu gehört.
Equip mit Angriffskraft wird ja auch Nah und Distanz erhöht.
Der Buff vom Krieger erhöht nur die Nah und Aspekt des Falken nur die Distanz.
Aura des Volltreffers wird Nah und Distanz erhöht, mit Angriffskraft.

**Comment by hraesvelgr** [comment]
sry, aber wir sind nicht fürs fixen von blizzards klassen-fuckup  zuständig.

**Comment by CityPlay** [comment]
Für mich ist das ein echter Fehler und es ist doch nicht schlimm wenn man die Fehler von Blizzard fixen kann/könnte. Weil da durch sind Jäger einfach extrem benachteiligt.

**Comment by hraesvelgr** [comment]
und wir geben dem pala noch einen spott, geben dem schami plattenrüstung und dem hexer die möglichkeit, alle mobs ausser illidan solo zu killen (oh warte, das kann er schon). 

blizzard hat die mechanik der buffs so vorgegeben, und genau so ist das bei uns auch implementiert. 
wilslt du nun classic spielen oder wotlk?

**Comment by CityPlay** [comment]
Classic ist geil.

**Comment by Haudraufinix** [comment]
Ich hab mich vor Urzeiten als die Buffs aus DM neu waren auch darüber aufgeregt, dass sie dem Hunter ja nichts nutzen. Dabei habe ich Quellen aus 2.x gefunden wo die Buffs endlich angepasst wurden. Leider ist 1.12.1 kein Wunschkonzert und deshalb bleiben die Buffs auch so wie sie sind.

Dafür erwischt ein Hunter beim ZG Buff und der Liedblume mit Abstand den besten Bonus. Hunter DPS ist auch ohne diese Buffs durchaus konkurrenzfähig. Besonders wenn man Bedenkt, dass ein Hunter vom Schlachtruf 10% Crit erhält. nicht wie alle anderen nur 5

**Comment by Sheed90** [comment]
@hraesvelgr hat vollkommen recht, wo will man denn anfangen, wenn man das alles fixen wollte? Dann wäre es auch kein Classic mehr sondern eine Eigenentwicklung.
