### ISSUE TITLE
[Naxx Event] Event-Bosse fehlen

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2448]
Welches Verhalten wird beobachtet?
Die Dungeon-Bosse des Naxxramas Event sind (bisher) nicht (oder ggf. nicht vollständig oder falsch) integriert.

Wie sollte es sich verhalten?
Während des Naxxramas-Event sind in ausgewählten Instanzen mit Untoten-Aktivitäten Event-Bosse erschienen. Sie sind für die Dauer des Events wie normale Bosse der Instanz permanent anwesend gewesen, d.h. sie hatten keine (Rar)Spawnchance (z.B. Jed oder Herdsinger). Zwei der Event-Bosse werden durch ein Script beschworen/aktiviert.

Schritte zur Reproduzierung
Ausgewählte Instanzen betreten und an den vorbestimmten Positionen/Routen nach den Event-Boss suchen. (Bisher aus Zeitgründen nur nachgeschaut für Stratholme und Scholo.)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Folgende Event Bosse tauchen in folgenden Instanz-Zonen auf:
- Der Lich Balzaphon in Stratholme patrouilliert um den Brunnen des Festivalplatzes.
- Das Skelett Lord Blackwood (dt.: Fürst Schwarzstahl) in Scholomanche patrouilliert im großen Raum nach dem „Chamber of Summoning“.
- Der Geist Revanchion in Düsterbruch West scheint zwei Spawnpositionen zu haben: (1) bei den anderen Geistern im Durchgang nach Tendris und vor dem Gefängnis von Immol’thar; (2) im selben Raum wie Magister Kalendris. Ich schätze mal, nur (1) sollte die richtige Spawnposition sein.
- Der Lich Scorn (dt.: Der Verächter) im Scharchlachroten Kloster (Friedhof) spawnt, nachdem der Endboss, Blutmagier Thalnos, getötet worden ist, und patrouilliert dann am Friedhof vom Eingang des Friedhofs bis zum Ende.
- Die Patchwork-Kreatur Sever (dr.: Häcksler) in Burg Shadowfang ist in einem Durchgang (gut beschrieben hier: http://www.wowhead.com/npc=14682/sever#comments:id=420185). 
- Die Banshee Lady Falther'ess in den Hügeln von Razorfen (Razorfen Downs) ist zunächst eine eingesperrte, dem Spieler freundliche gegenüber eingestellte weibliche Humanoide (auf Radar Untote) zwischen Henry Stern und Sah'rhee, verwandelt sich aber in eine Banshee, wenn man sie befreit. Scheinbar erscheint sie erst, wenn man den Endboss Amnennar getötet hat.

Beim Abgleich mit der Datenbank-Einträge scheint bei allen Bossen der richtige Loot bereits eingetragen zu sein, aber bei Lord Blackwood und Lady Falther'ess fehlen noch die Fähigkeiten.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Balzaphone: https://datenbank.classic-wow.org/?npc=14684
Lord Blackwood: https://datenbank.classic-wow.org/?npc=14695
Revanchion: https://datenbank.classic-wow.org/?npc=14690
Häcksler (Sever): https://datenbank.classic-wow.org/?npc=14682
Der Verächter (Scorn): https://datenbank.classic-wow.org/?npc=14693
Lady Falther'ess: https://datenbank.classic-wow.org/?npc=14686
Henry Stern: https://datenbank.classic-wow.org/?npc=8696
Sah'rhee: https://datenbank.classic-wow.org/?npc=8767
Amnennar der Kältebringer: https://datenbank.classic-wow.org/?npc=7358

Allgemeine Informationen:
- WoWPedia Artikel von Januar 2007: https://wow.gamepedia.com/index.php?title=Scourge_Invasion&oldid=457229#New_Bosses
- „Q: Where are the new Bosses?“ in „FAQ: The Scourge Invasion World Event“: http://blue.cardplace.com/cache/wow-general/8553194.htm
- „Invasion Bosses – Drops“: https://forums.mammae.eu/threads/invasion-bosses-drops.1865/
- „Undocumented 1.11 Changes - Concillian - 06-21-2006 09:57 PM“ in: http://www.lurkerlounge.com/forums/printthread.php?tid=4203

Zusammenfassung weiterer offensichtlicher Quellen (ohne Anspruch auf Vollständigkeit):
- Balzaphone
https://wow.gamepedia.com/index.php?title=Balzaphon&oldid=537461
http://de.wowhead.com/npc=14684/balzaphon
- Blackwood
https://wow.gamepedia.com/index.php?title=Lord_Blackwood&oldid=537459
http://www.wowhead.com/npc=14695/lord-blackwood
- Revanchion
https://wow.gamepedia.com/index.php?title=Revanchion&oldid=537467
http://de.wowhead.com/npc=14690/revanchion
- Scorn/Verächter
https://wow.gamepedia.com/index.php?title=Scorn&oldid=537387
http://de.wowhead.com/npc=14693/der-verachter
- Sever/Häcksler
https://wow.gamepedia.com/index.php?title=Sever_(abomination)&oldid=537463
http://de.wowhead.com/npc=14682/hacksler
- Lady Falther'ess
https://wow.gamepedia.com/index.php?title=Lady_Falther%27ess&oldid=784342
http://de.wowhead.com/npc=14686/lady-faltheress

**Comment by Sheed90** [comment]
Der Lich Scorn (dt.: Der Verächter) im Scharchlachroten Kloster (Friedhof) spawnt, nachdem der Endboss, Blutmagier Thalnos, getötet worden ist, und patrouilliert dann am Friedhof vom Eingang des Friedhofs bis zum Ende.
**- Erscheint nach dem Endboss und patrouilliert!**

Die Patchwork-Kreatur Sever (dr.: Häcksler) in Burg Shadowfang ist in einem Durchgang (gut beschrieben hier: http://www.wowhead.com/npc=14682/sever#comments:id=420185).
**- Ist da und patrouilliert!**

Die Banshee Lady Falther'ess in den Hügeln von Razorfen (Razorfen Downs) ist zunächst eine eingesperrte, dem Spieler freundliche gegenüber eingestellte weibliche Humanoide (auf Radar Untote) zwischen Henry Stern und Sah'rhee, verwandelt sich aber in eine Banshee, wenn man sie befreit. Scheinbar erscheint sie erst, wenn man den Endboss Amnennar getötet hat.
**- Funktioniert wie beschrieben, das Tor lässt sich erst nach dem Endboss öffnen und der Boss geht anschließend raus und verwandelt sich.**

-- 
noch offen
--

Der Lich Balzaphon in Stratholme patrouilliert um den Brunnen des Festivalplatzes.
Das Skelett Lord Blackwood (dt.: Fürst Schwarzstahl) in Scholomanche patrouilliert im großen Raum nach dem „Chamber of Summoning“.

Der Geist Revanchion in Düsterbruch West scheint zwei Spawnpositionen zu haben: (1) bei den anderen Geistern im Durchgang nach Tendris und vor dem Gefängnis von Immol’thar; (2) im selben Raum wie Magister Kalendris. Ich schätze mal, nur (1) sollte die richtige Spawnposition sein.
