### ISSUE TITLE
Gesucht: Hogger

### ISSUE THREAD

**Issue by TheVolkster** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2449]
Welches Verhalten wird beobachtet?
Ich habe zwei Quests (Gesucht: Hogger und Kopfgeld auf die Flusspfotengnolle) im Wald von Elwynn im Questlog. Ich habe alle erforderlichen Questgegenstände im Inventar, kann die Quests aber nicht abgeben. Die Fragezeichen sind grau und die Schaltfläche "Weiter" um den Quest abzuschliessen ist nicht anwählbar. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
LVL 8 Mensch Krieger.

Sry falls der bug schon reported wurde, aber über die SuFu habe ich nichts gefunden. Ich bin mir auch bewusst dass es ein low Lvl issue ist, es ist aber nichts desto trotz schade.

Gruß
V
![wowscrnshot_011118_191029](https://user-images.githubusercontent.com/35344856/34839913-90b8cf44-f703-11e7-974b-dd1ed8e46914.jpg)

**Comment by hraesvelgr** [comment]
wow schließen, wdb ordner im wow-verzeichnis ausfindig machen, löschen, wow starten, quest abgeben. 

der wdb ordner ist der cache, in dem temporär daten des spiels gespeichert werden. manchmal spinnt das aber bisschen rum.

**Comment by TheVolkster** [comment]
Eine Anmerkung hierzu noch: Das Löschen des WDB Ordners hat nicht dazu geführt dass das Problem gelöst wurde.
Allerdings habe ich die Quest gelöscht und neu angenommen; da die Questgegenstände beim Löschen nicht verschwunden waren (Bug?) konnte die Quest sofort abgegeben werden.
Warum ist mir völlig unklar, aber so ging es.
