### ISSUE TITLE
Brachland: Quetschzahn (Blutsplitter-Schwein) bufft sich selbst

### ISSUE THREAD

**Issue by graved** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2452]
Welches Verhalten wird beobachtet?
Der Questgeber Quetschzahn, welcher im Käfig von Camp Taurajo sitzt, castet alle Buffs, welche man gegen Blutsplitter bekommt auf sich selbst.

Wie sollte es sich verhalten?
Er castet den Buff auf den Spieler.

Schritte zur Reproduzierung
Blutsplitter gegen Buff tauschen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1843 ist aber glaube ein anderer bug? @dagochen hast du da schonmal was gebastelt?
