### ISSUE TITLE
[Naxxramas] Schulter-VZ: Macht der Geißel führt zum "Selbstmord"

### ISSUE THREAD

**Issue by Simit90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2454]
Welches Verhalten wird beobachtet?
Sobald man sich die Schulter-VZ: Macht der Geißel (Item-ID: 23548) auf ein angelegtes Item verzaubert bzw. ein mit dieser Verzauberung verzaubertes Item anzieht, stirbt man sofort. Im Kampftext steht lediglich: "Ihr sterbt." Dies geschieht bei verschiedenen Items (bei allen getesteten), d. h. an einem bestimmten Item kann es nicht liegen, sondern an der Verzauberung direkt.
Falls es hilft, man verliert keine Haltbarkeit durch diesen Tod.
Dieser Bug tritt nur bei dieser Verzauberung auf, alle anderen funktionieren einwandfrei

Wie sollte es sich verhalten?
Naja, man sollte sicherlich nicht sterben 

Schritte zur Reproduzierung
Auf dem Testserver nach Naxxramas gehen, Verzauberung kaufen, verzaubern und schauen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Weitere Informationen sind denke ich nicht notwendig

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=23548

**Comment by testear** [comment]
Name ist Programm 💃
