### ISSUE TITLE
[Naxxramas Opening Event] Schwacher Nekrotischer Kristall gibt keine Quest

### ISSUE THREAD

**Issue by Simit90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2456]
Welches Verhalten wird beobachtet?

Nachdem man in Undercity den LVL 63er Elite-Mob tötet (In unserem Fall Leichenblasser Schrecken), spawnt ein Schwacher Nekrotischer Kristall, soweit so gut, allerdings gibt  dieser keine Quest.
Wir waren nicht in einem Schlachtzug, wir waren eine 5er-Gruppe und ein einzelner Spieler.

Wie sollte es sich verhalten?

Der Schwache Nekrotische Kristall sollte jedem Spieler - egal ob er am Kampf beteiligt war oder nicht - eine Quest geben, diesen abzugeben. Des Weiteren sollte dies durch eine Questmarkierung über ihm zu erkennen sein

Schritte zur Reproduzierung

In Undercity den LVL 63er Elite-Mob suchen (bestenfalls Leichenblasser Schrecken, mit dem Flickwerkschrecker noch nicht probiert) und töten. Anschließend schauen, ob es eine Quest gibt oder nicht.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Spieler Level 60:
Getestet auf dem Testserver, Spieler anhand des Screenshots zu sehen
https://www2.pic-upload.de/img/34660800/NekroKristall.png

Quellen, wie es sein sollte:
http://wowwiki.wikia.com/wiki/Scourge_Invasion?action=edit&section=8 | Absatz Capital City Invasion
http://de.wowhead.com/quest=9310/schwacher-nekrotischer-kristall#english-comments | Kommentar-Sektion

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?npc=16531 | NPC Schwacher Nekrotischer Kristall
https://datenbank.classic-wow.org/?item=22950 | Q-Gegenstand: Schwacher Nekrotischer Kristall
https://datenbank.classic-wow.org/?quest=9310 | Quest: Schwacher Nekrotischer Kristall
https://datenbank.classic-wow.org/?npc=16394 | Leichenblasser Schrecken

Zusatz: Der ganze Angriff auf Undercity scheint noch nicht richtig zu sein. Die Mobs sollten theoretisch lediglich den Spielern gegenüber Neutral sein und im Kampf mit den NPC's stehen. Wird dementsprechend bei weiterer Recherche ein eigener Report für geschrieben

**Comment by Dotox** [comment]
Das Event in den Städten ist ziemlich schwierig. Dazu gibt es nicht wirklich viele Informationen und die damit verbundenen recherchearbeiten sind sehr zeitintensiv. Sofern es "einigermaßen" funktioniert würde ich sagen, dass man es so aufspielen kann. Das Event in den Städten nun bis ins kleinste Detail zu programmieren und anzupassen würde wahrscheinlich nochmal 3 Monate dauern und darauf hab weder ich, noch die ganzen Spieler, die auf Naxxramas warten, lust :-)

**Comment by Simit90** [comment]
Nein, das ist verständlich :). Ich gebe nur den Input den ich finde. Ob es sich am Ende lohnt, wie zeitintensiv das Ganze ist etc. müsst ihr entscheiden :D. Aber hauptsächlich ging es hier im Bugeintrag ja um die fehlende Quest ;) De Rest unten war nur "Zusatz"^^

**Comment by Simit90** [comment]
Mittlerweile gelbes Ausrufezeichen da, aber leider nicht annehmbar :(

**Comment by Simit90** [comment]
Quest funktioniert, danke! Gerade im Raid getestet
