### ISSUE TITLE
[Naxxramas] Item: Macht der Geißel

### ISSUE THREAD

**Issue by booneyclassic** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2457]
### Inhalt
Hallo zusammen! Ich habe einen Bug gefunden, den ich gerne zu einem Item melden möchte. Zu diesem Item gibt es bereits einen EIntrag im Bugtracker, da dieser jedoch ein vollkommen anderes Problem behandelt, habe ich mich dazu enschlossen einen neuen zu eröffnen.

### Welches Verhalten wird beobachtet?

Das Item der Schulterverzauberung "Macht der Geißel" verbessert die kritische Trefferchance um 1% und die Nahkampfangriffskraft um 26 Punkte.

### Wie sollte es sich verhalten?
Das Item der Schulterverzauberung "Macht der Geißel" verbessert die kritische Trefferchance um 1% und die gesammte Angriffskraft (Nahkampf+Fernkampf) um 26 Punkte. Es handelt sich hierbei um die beste Schulterverzauberung, welche die Verzauberung aus ZG ablöst. Diese galt bereits auch für den Nah- und Distanzkampf.

### Schritte zur Reproduzierung
Die Schulterverzauberung auf die getragenen Schultern wirken. Dann sieht man, das sich nur der Wert der Nahkampfangriffskraft und nicht auch der der Distanzangriffskraft ändert.

### Zusätzliche Informationen (Screenshots, Videos, Quellen, Klasse, Level, etc.)
Zu dem Thema sieht man hier einen offiziellen Blue-Post, der die Problematik beinhaltet. Diese wurde dann durch ein Hotfix/Patch gelöst. [Klick mich hier!](https://blue.mmo-champion.com/topic/16724-might-of-the-scourge/)

### Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Item: [Macht der Geißel](https://datenbank.classic-wow.org/?item=23548)

LG
Booney

**Comment by Dotox** [comment]
Funktioniert wie es soll.

**Comment by hraesvelgr** [comment]
und hunter guides die die thematik beinhalten gibt es nur von 2.0.1 und jünger. dass die devs einen hotfix nachschieben "wollen" heißt nicht, dass das auch getan wurde, bzw vor 2.0.1 passiert ist. 
da müsste mehr recherche vom OP kommen.
