### ISSUE TITLE
[Naxxramas Opening Event] Shadow of Doom + Undead Trash (Pre-Event)

### ISSUE THREAD

**Issue by Omegaexodus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2458]
**Welches Verhalten wird beobachtet?**

Sobald man den Npc "Shadow of Doom" tötet, nachdem man einen der Akolythen an den Beschwörersteinen angesprochen hat (Abgabe von 8 Runen), lässt dieser nur sehr selten Loot fallen. Zusätzlich gibt er keinen Ruf beim töten. Und meisten hat er nur 1x nekrotische Rune dabei.

Die Trash-Npcs welche sich um den Beschwörerstein aufhalten geben keinen Ruf und droppen auch keine Geißelsteine, wenn man die Anstecknadel der Argentumdämmerung trägt.

**Wie sollte es sich verhalten?**

Der Npc mit dem Namen "Shadow of Doom" sollte nach seinem Tot, immer 30 nekrotische Runen als Beute beinhalten. Zusätzlich sollte er 50 Ruf für die Argentumdämmerung geben (Unabhägig von der Rufstufe) und immer 1x "Geißelstein des Verderbers" fallen lassen. Zusätzlich sollte die Wahrscheinlichkeit für das droppen von den Setteilen deutlich höher sein. (Siehe Quelle in Thottbot / Datenbank überprüfen)

Der Trash welcher sich um die Kristalle befindet sollte für jeden getötet Npc genau 5 Rufpunkte geben (Argentumdämmerung). Dabei ist darauf zu achten, dass diese Rufstufe nur bis zum Ende von "Wohlwollend" gilt. (Danach geben die Npcs (Ausnahme Shadow of Doom) keinen Ruf mehr). Auch sollten alle Npcs die Chance beinhalten (durch das tragen der Anstecknadel / Rune der Dämmerung / Siegel der Dämmerung) entsprechend "Geißelsteine des Eindringlings" fallen zu lassen.

**Schritte zur Reproduzierung**

Auf den Testserver begeben und die Trash-Mobs töten bzw. den "Shadow of Doom". Dann den Inhalt der Npcs überprüfen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

https://wow.gamepedia.com/Scourge_Invasion

"_The Acolyte will then convert into a Shadow of Doom, which is a tough 61 elite mob. Upon its defeat, the Shadow of Doom will yield a [Corruptor's Scourgestone], 50 reputation with the Argent Dawn, 30 Necrotic Runes, and has a chance to drop a chest piece of the Undead Slaying set._"

https://web.archive.org/web/20071002084149/http://www.thottbot.com:80/c16143

"_The Shadow of Doom will likely drop a corruptor's scourgestone.  Also, each of the times I've killed it, it has dropped 30 necrotic runes.  There is also a set of undead slaying gear which has int, stam and + spell damage vs undead for clothies, and stam and +atk pwr vs undead for leather, mail, and plate.  The set consists of bracers, gloves, and chestpiece, and the set bonus is 2% bonus damage vs. undead.  The chestpiece has a chance to drop from the shadow of doom (two out of three kills it dropped the cloth chestpiece and the third kill it didn't drop any).  The gloves can be obtained by giving 30 necrotic runes to an NPC at light's hope.  I still haven't found out where to get the bracers._"

Hier sieht man das die Drop-Chance für Stoffteile ziemlich hoch sein muss. Entsprechend auch noch mal überprüfen.

http://et.worldofwarcraft.wikia.com/wiki/Scourge_Invasion

"_The necropoli are accompanied by Necrotic Shards, which are visible on the ground near each of the flying citadels. These shards are always surrounded by a large number of undead. The undead are non-elite and grant 5 Argent Dawn reputation until the end of honored, unlike normal undead. They yield [Invader's Scourgestones] if slain while having the [Argent Dawn Commission] equipped._"

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Shadow of Doom:
https://datenbank.classic-wow.org/?npc=16143

Trash Npcs:
https://datenbank.classic-wow.org/?npc=16141
https://datenbank.classic-wow.org/?npc=16299
https://datenbank.classic-wow.org/?npc=16298

Geißelsteine: 
https://datenbank.classic-wow.org/?item=12840
https://datenbank.classic-wow.org/?item=12841
https://datenbank.classic-wow.org/?item=12843

Anstecknadeln:
https://datenbank.classic-wow.org/?item=12846
https://datenbank.classic-wow.org/?item=13209
https://datenbank.classic-wow.org/?item=19812
https://datenbank.classic-wow.org/?item=23206
https://datenbank.classic-wow.org/?item=23207

**Comment by Simit90** [comment]
Hallo,

also zumindest die Spektralen Soldaten sowie die Ghulberserker droppen Geißelsteine des Eindringlings. Die Droprate scheint auch mit der angegebenen in der Datenbank überein zu stimmen.

Getestet allerdings nicht mit der Anstecknadel, sondern mit dem Mal des Helden.

Quelle: Screenshots - Charakter Simit - Testserver
https://www2.pic-upload.de/img/34665880/GeielsteinGhulberserker.png
https://www2.pic-upload.de/img/34665882/GeielsteinSpektralerSoldat.png

Mal des Helden: https://datenbank.classic-wow.org/?item=23207
