### ISSUE TITLE
Erdbindungs Totem

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#246]
Welches Verhalten wird beobachtet?
Wenn man in ein  Erdbindungs Totem (http://datenbank.welli-it.de/?spell=2484#see-also-ability) als schurke rennt wird man aufgedeckt.

Wie sollte es sich verhalten?
Nur der erste Impuls sollte dies tun. 

Schritte zur Reproduzierung
Schamane erstellen > Schurken erstellen > Totem stellen > Schurke nach 10 sec reinlaufen lassen während er verstohlen ist.

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://www.wowwiki.com/index.php?title=Shaman_PvP_guide&oldid=246410
"Earthbind Totem will unstealth a vanished rogue on its first pulse if the rogue is within range."

http://www.wowpedia.org/index.php?title=Earthbind_Totem&direction=next&oldid=430518
"Currently, the first pulse of Earthbind Totem right after you drop it will bring a rogue out of stealth. Pulses after the first pulse will not bring a rogue out of stealth."

**Comment by DreamRogue** [comment]
Hier noch ein Beweis aus alten Zeiten (ab 15:00 ist Ming der Aura ausgesetzt aber in stealth):

https://www.youtube.com/watch?v=XvhdWI-1Gs0

Bitte um fix, es wird massiv von Schamanen genutzt
