### ISSUE TITLE
Mobs Porten sich mit Spieler aus Instanz

### ISSUE THREAD

**Issue by Fl0o** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2460]
Welches Verhalten wird beobachtet?
Wenn man in UBRS die Gruppe verlässt und im Eierraum die Welpen vor Ablauf des Timers triggert, kommen diese zusammen mit dem Spieler zu seinem Heimatort. Dort greifen sie alles in ihrer Umgebung an.

Wie sollte es sich verhalten?
Die Mobs sollten in der Instanz bleiben, auch wenn der Spieler nicht mehr dort ist.

Schritte zur Reproduzierung
In UBRS die Gruppe verlassen, die Eier vor Ablauf des Timers triggern und schauen was passiert.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Krähenhorstwelpe: https://datenbank.classic-wow.org/?npc=10161
Ob das auch bei weiteren Mobs mit ähnlichem Spawnverhalten funktioniert ist nicht bekannt.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
wie schaffst du es, die welpen vor ablauf des timers zu triggern? 

meinst du mit triggern den spawn (eier kaputt) oder dass sie aggro ziehen? 

wie auch immer du das geschafft hast...

**Comment by Fl0o** [comment]
Damit meine ich den Spawn der Welpen indem man auf die Eier tritt. Wie man das schafft? Habe die Gruppe verlassen, habe auf den Teleport gewartet und bin währenddessen noch bisschen in der Ini rumgelaufen und über die Eier gestolpert... ^^

**Comment by hraesvelgr** [comment]
dazu müsste man aber abändern, dass der spawn der drachlinge beim ei passiert, und nicht beim spieler. momentan scheint es so, dass der spell auf den spieler zielt, ich nehme an, das ist auch blizzlike. bisschen serverlag noch dazu, und schwupps ist der spell erst durch wenn du draussen bist. 

denke nicht,d ass man da großartig was fixen kann.
