### ISSUE TITLE
Zul Farrak - Spinnengott-Quest geht nicht

### ISSUE THREAD

**Issue by xTyraelx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2462]
Welches Verhalten wird beobachtet?

Man muss mit der Steintafel sprechen um den Namen des Spinnengottes zur Erfahren.
Tafel sagt nur "Hallo"

Wie sollte es sich verhalten?

Quest sollte beendet werden können bzw. Name des Spinnengottes erfahren.

Schritte zur Reproduzierung

Nach Zul Farrak gehen und testen :)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Level 47 Untoter Krieger

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/676
