### ISSUE TITLE
Quest "Zerbrochene Allianzen" geht nicht

### ISSUE THREAD

**Issue by xTyraelx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2463]
Welches Verhalten wird beobachtet?

Die Säulen, bei welchem die Steine droppen sollen existieren nicht.

Wie sollte es sich verhalten?

Säulen sollten da sein und Items zur Beschwörung geben.

Schritte zur Reproduzierung

Ins Ödlnad gehen und nachsehen^^

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Level 46 Untoter Krieger

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

http://wowdata.buffed.de/quest/Oedland/Zerbrochene-Allianzen-793

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1642
