### ISSUE TITLE
Schläger/Magus der Felsfäuste gelbe Schrift, aber feindlich

### ISSUE THREAD

**Issue by Simit90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2464]
Welches Verhalten wird beobachtet?

Im Arathihochland bei der Halle der Felsfäuste befinden sich um das Lagerfeuer an dem Truhe-Spawn drei Mobs (1x Magus der Felsfäuste, 2x Schläger der Felsfäuste). Diese werden entgegen aller anderen Mobs der Felsfäuste da mit gelber Schrift (neutral) statt roter Schrift (feindlich) angezeigt, jedoch verhalten sie sich dem Spieler gegenüber feindlich.

Wie sollte es sich verhalten?

Die Gegner sollten feindlich angezeigt werden.

Schritte zur Reproduzierung

Ins Arathihochland zur Halle der Felsfäuste gehen und dort bei den Koordinaten 53,3/74,3 die drei Gegner aufsuchen, auf die Namensplakette schauen und ihr Verhalten bei Annäherung beobachten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://vimeo.com/251979025
Video über das Verhalten
Quelle: Simit - Nefarian Liveserver

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=2566 | Schläger der Felsfäuste
https://datenbank.classic-wow.org/?npc=2567 | Magus der Felsfäuste

**Comment by dagochen** [comment]
Man sieht wie die erst rot sind und dann gelb werden in dem Video. Daher tippe ich auf ein Addon-Problem ;)

**Comment by Simit90** [comment]
Mittlerweile mehrmals getötet, immer wieder mit gelbem Schriftzug gespawnt.
Sind die einzigen Oger im Camp mit gelber Schrift.
Auf dem Testserver sind diese rot markiert komischerweise.
Auch mit anderen Chars verschiedenen Levels gelbe Schrift

**Comment by hraesvelgr** [comment]
kann ich so bestätigen

**Comment by Simit90** [comment]
Jo, klappt wieder auf dem Liveserver, kann als Fixed markiert und geschlossen werden, danke

**Comment by dagochen** [comment]
Scheint einfach durch einen Neustart behoben zu sein. Den Fehler konnten wir nicht wirklich finden, wenn es doch mal wieder auftritt nochmal melden.
