### ISSUE TITLE
Hexenmeister: Dämonenrüstung Rang 3 wird als Rang 1 angezeigt

### ISSUE THREAD

**Issue by marcochristmann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2465]
Welches Verhalten wird beobachtet?
Dämonenrüstung Rang 3 wird als Rang 1 angezeigt. 
Ein /script cast("Dämonenhaut(Rang 3") bleibt ohne Erfolg.

Wie sollte es sich verhalten?
Sollte als Rang 3 angezeigt (und vom o.g. Makro verwendet) werden.

Schritte zur Reproduzierung:
Hexenmeister Level 20 und beim Lehrer die Spells lernen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
![0](https://user-images.githubusercontent.com/26117688/35271895-caf0138c-0033-11e8-9a54-e5ea729b4cf1.jpg)
![1](https://user-images.githubusercontent.com/26117688/35271907-d25739de-0033-11e8-9d3e-f4445248fcf5.jpg)
![2](https://user-images.githubusercontent.com/26117688/35271916-d699163e-0033-11e8-97a3-bf4d0dd0578a.jpg)
![3](https://user-images.githubusercontent.com/26117688/35271919-d97799fc-0033-11e8-85fa-d4270329c613.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Rang1: https://datenbank.classic-wow.org/?spell=687
Rang2: https://datenbank.classic-wow.org/?spell=696
Rang3: https://datenbank.classic-wow.org/?spell=706

**Comment by dagochen** [comment]
"Demon Armor" und "Demon Skin" sind 2 verschiedene Zauber.

**Comment by dagochen** [comment]
@marcochristmann Wenn jeder so ausführlich und gute Bugreports machen würde, wär unsere Arbeit um ein vielfaches leichter ;) Leider war deine Arbeit in diesem Fall umsonst :P
