### ISSUE TITLE
[Naxxramas] Anub'Rhekan Locust Swarm

### ISSUE THREAD

**Issue by Drachling** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2466]
**Welches Verhalten wird beobachtet?**
Der Locust Swarm wird immer nach genau 120 Sek gecastet (wurde heute in 2 Trys mit zusammen 9 Schwärmen immer genau auf die letzte Sekunde des NECB-Timers [120Sek] gecastet).
Auch konnte unser Tank mit 4 Stacks noch immer seinen Schildwall benutzen um zu überleben.

**Wie sollte es sich verhalten?**
Der Locust Swarm sollte 90 Sek Abklingzeit haben und nach 90-120 Sek gecastet werden, wobei dies zufällig ist.
Zudem sollte der Swarm alle Zauber, Fähigkeiten und Instants (auch Schildwall / Last Stand) des betroffenen Spielers deaktiveren, nicht nur gecastete Zauber.
Items (z.B. Lifegiving Gem) sollten aber weiterhin nutzbar sein.

**Schritte zur Reproduzierung**
Anub'Rhekan bis zum Locust Swarm spielen und entweder auf die Timer achten oder eine Stopuhr verwenden.
Beim Locust Swarm versuchen, Instant-Fähigkeiten und aktivierbare Items (z.B. Trinkets / Ingi-Boots) zu nutzen

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
http://wowwiki.wikia.com/wiki/Anub%27Rekhan_(original)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
NPC (Anub'Rhekan)
https://datenbank.classic-wow.org/?npc=15956
Heuschreckenschwarm/Locust Swarm
https://datenbank.classic-wow.org/?spell=28785
https://datenbank.classic-wow.org/?spell=28786

**Comment by Dotox** [comment]
Also die Geschichte mit dem Timer ist etwas merkwürdig, weil dieser bereits random eingetragen ist. Das beobachtete mit Schildwall / Last Stand hab ich mir angeschaut und nochmal eine kleine Verbesserung vorgenommen.

**Comment by Drachling** [comment]
Bei uns ist der Schwarm halt immer genau nach dem NECB-Timer (120 Sek) gekommen, das wurde sogar hinterher runter gezählt und man konnte gemütlich vorher weg laufen.
Das kann natürlich ein totaler Zufall sein, aber die Wahrscheinlichkeit das er 9 mal zufällig genau zur gleichen Zeit kommt ist schon extrem gering.
Hast du es denn mal versucht und ist er da random gekommen oder hast du nur die Einstellungen geprüft?
Ich kann den Boss leider nicht alleine testen und wir werden wohl keinen weiteren Test-Raid mehr durch führen.
Es wäre nur Schade, wenn der Boss beim Release zu einfach wäre, weil der Timer zu berrechenbar ist.
