### ISSUE TITLE
Rüstung schwächen(Expose Armor) - Schurke(Rogue)

### ISSUE THREAD

**Issue by MisterMarax** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2467]
**Welches Verhalten wird beobachtet?**
Der Finishing-Move "Rüstung schwächen" vom Schurken wird von "Rüstung zerreißen" vom Krieger überschrieben (egal wieviele Combopunkte d. h. wie stark der Debuff vom Schurken ist). Das ist relativ ärgerlich, da so ein stärkerer Armor-Debuff auf dem Boss behindert wird, der gerade für den Naxx-Progress interessant ist.

**Wie sollte es sich verhalten?**
"Rüstung schwächen" sollte "Rüstung zerreißen" blockieren, sobald ein Schurke "Verbessertes Rüstung schwächen" geskillt hat (50% mehr Armor Penetration durch "Rüstung schwächen") und der Debuff auf dem Mob ist. Dies sollte passieren, da der Debuff stärker ist als das "Rüstungs zerreißen" (1 Combopunkt geskilltes "Rüstung schwächen" = 490 Armor Pen d. h. insgesamt 2450 Armorpen bei 5 Combopunkten, 1 Stack "Rüstung zerreißen" = 450 Armor Pen d. h. 2250 Armorpen bei 5 Stacks).

**Schritte zur Reproduzierung**
"Rüstung schwächen" auf einen Mob hauen, dann "Rüstung zerreißen" drauf machen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Laut Wowwiki: "Compared to a Rogue's Expose Armor, the rogue can apply their full effect (5 combo points) sunder much sooner than a Warrior, if reducing the mob's armor is the goal for a group. The Expose Armor effect will block an application of Sunder Armor, however." 
(http://wowwiki.wikia.com/wiki/Talk:Sunder_Armor)

Laut Vanilla Wowwiki: "Do not use this ability in a group where a warrior is tanking. He will NOT be able to use his Sunder Armor ability at all (he'll get a "more powerful spell in effect" error message). Sunder Armor is a primary threat move for a tanking warrior, so this is a very bad thing." 
(http://vanilla-wow.wikia.com/wiki/Expose_Armor)

Beide Quellen behandeln zwar "Rüstung schwächen" zu BC, allerdings wurde diese Gegebenheit nirgendwo per Patch in BC eingeführt, weswegen es nahe liegt, dasss es bereits in Classic Wow so war. 

Außerdem gilt seit Patch 1.10 laut Vanilla Wowwiki folgendes:
"Late in vanilla, Blizzard began systematically assigning values to debuffs so that a weaker debuff could not displace a stronger one. The system was announced in February 2006, but it didn't begin to affect the live game until patch 1.11.0 in June." 
(http://vanilla-wow.wikia.com/wiki/Debuff)

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Rüstung schwächen: https://datenbank.classic-wow.org/?spell=11200
Rüstung zerreißen: https://datenbank.classic-wow.org/?spell=11599
Verbessertes Rüstung schwächen: https://datenbank.classic-wow.org/?spell=14169

**Comment by Suzaru** [comment]
Generell war es doch damals so, dass schwächere Debuffs keine stärkeren überschreiben konnten.

**Comment by mkollers** [comment]
>... because Expose Armor rejects Sunders, ...  

Patch-Stand: 2.3.3 http://www.wowhead.com/forums&topic=15252

>Also, rogues should be aware that their Expose Armor ability does NOT stack with Sunder Armor, and therefore should not be used in an instance in which the rogue is attacking the same target as the Main Tank. The effect will make it impossible for a warrior to sunder and maintain aggro.

07.09.2009 http://wowwiki.wikia.com/wiki/Sunder_Armor?oldid=236867

>However, certain things such as Sunder Armor and Expose Armor do not stack. The more powerful version overwrites the older version. I noticed this as a Rogue when I kept accidentally erasing a Warrior's Sunder Armor (wasting their Rage, my bad!).

21.11.2004 http://wow.allakhazam.com/forum.html?forum=21&mid=1101053688209055207

> As a warrior, I would ask rogues NOT to use expose armor on the big boss. When a rogue does expose armor, the warrior cannot use sunder armor until it wear off (it gives you a message that a more powerful spell is already in effect).

23.02.2005 https://forum.rpg.net/showthread.php?175248-WoW-Does-Expose-Armor-work/page2

**Comment by mkollers** [comment]
Gibts ein Feedback von der Entwicklung, ob die Quellen ausreichend sind? :-)

**Comment by MisterMarax** [comment]
Falls das "Fixed" schon gelten sollte: Wird immer noch überschrieben von Rüssi reißen (bei Heigan gerade getestet).

**Comment by mkollers** [comment]
Gibts einen Plan, wann das live gehen soll?
