### ISSUE TITLE
[Naxxramas] Giftiger Huscher buggen an Treppe

### ISSUE THREAD

**Issue by Simit90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2468]
Welches Verhalten wird beobachtet?

Nach Anub'Rekhan in Naxxramas im der Mitte des zweiten größeren Raumes des Spinnenflügels patrouilliert eine Truppe Giftiger Huscher. Jedoch buggen sich immer 2-3 dieser Mobs an der Treppe linksfest, während der Rest der Truppe weiter läuft. Dadurch ist es nahezu unmöglich entweder die Patrouille oder eines der linken Trashpacks alleine zu pullen

Wie sollte es sich verhalten?

Die Giftigen Huscher sollten nicht an der Treppe hängen bleiben und dementsprechend einzeln zu pullen sein. 

Schritte zur Reproduzierung

Nach Naxxramas gehen und im o. g. Raum sich das Ganze anschauen und versuchen, die Patrouille alleine zu pullen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://vimeo.com/253408993
Video, welches das "Fehlverhalten" der giftigen Huscher zeigt
Testserver Naxxramas

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
NPC: Giftiger Huscher nicht in unserer Datenbank vorhanden

**Comment by Dotox** [comment]
Kann das Problem leider nicht reproduzieren und auch Gilden, die den Flügel davor getestet haben, konnten das Problem nicht mehr feststellen. Sehr wahrscheinlich lag es an dem falschen Build, mit dem ihr Naxxramas getestet habt.
