### ISSUE TITLE
Überwältigen(Overpower) - Krieger(Warrior)

### ISSUE THREAD

**Issue by FhyEzee** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2469]
**Welches Verhalten wird beobachtet?**

Überwältigen ist seit ein paar Tagen kaum mehr nutzbar.
(_getestet mit Makros, ohne Makros, ohne Addons & mit Addons_)
Nach Haltungswechsel ist es meistens direkt ausgegraut.
Aus der Kampfhaltung ca. 1 Sekunde nutzbar (Kein Unterschied ob Styles oder Autohits).
Aus der Berserkerhaltung bzw. nach Haltungswechsel selten nutzbar (durch GCD die dabei eine Rolle spielen).

Ob verschiede Ränge von Überwältigen sich anders verhalten kann ich leider nicht sagen, da ich nur Rang 4 ausprobieren konnte.

Das Problem ist nicht nur in mehreren Raids bemängelt wurden sondern auch des öfteren im Worldchat, deswegen wollte ich dem mal nach gehen!

**Wie sollte es sich verhalten?**
Es müsste nach Auslösen (durch Ausweichen des Gegners), einige Sekunden, aktiv sein (an die 5 Sekunden, wenn ich mich nicht täusche).

**Schritte zur Reproduzierung**
Man greift ein Mob aus der Berserkerhaltung oder aus der Kampfhaltung heraus an & schaut sich an wie lange man Überwältigen nutzen kann.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Videoaufnahme nicht möglich, sorry.
### Vielleicht kann jemand anderes es ergänzen!

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?spell=7384
https://datenbank.classic-wow.org/?spell=7887
https://datenbank.classic-wow.org/?spell=11584
https://datenbank.classic-wow.org/?spell=11585

**Comment by Fiinola** [comment]
Auch im PvP sehr nervig.

**Comment by Mixuspidelix** [comment]
kann ich so bestätigen, ist reines Glücksspiel ob man es nutzen kann oder nicht.

**Comment by FhyEzee** [comment]
Danke @Dotox

**Comment by FhyEzee** [comment]
Rache genau das gleiche Problem @Dotox

**Comment by FhyEzee** [comment]
Weiterhin getestet, auch aufm PTR (Heute) 

Zeit die es aktiv ist ist immer unterschiedlich. 
Mal eine Sekunde.. mal 2 Sekunden.

Vielleicht hilft es :)

**Comment by Lyps95** [comment]
Eben auch mal auf dem PTR gewesen, Mit geskilltem Overpower getestet.
Bei Styles kommt es teilweise vor, dass der global cooldown des styles der Rache/Überwältigen auslöst abgelaufen ist und Rache/Überwältigen dann schon nichtmehr aktivierbar ist. D.h.: Der Rache-/Überwältigen-proc läuft schneller aus, als der GC des styles der ihn ausgelöst hat abläuft.
D.h.: der Rache/Überwältigen  proc bleibt unter 1,5 sekunden bestehen. andererseit bleibt es aber auch mal 2-3 sekunden bestehen, aber so gut wie nie die vollen 5 Sekunden wie es vor ein paar Wochen noch der Fall war.

**Comment by FhyEzee** [comment]
Hab ein Video zu ergänzen: 
https://youtu.be/RGBnjELkgok?t=3m53s

(Er dodged seinen MS und seinen Autohit, welche weniger als eine halbe Sekunde auseinander liegen, anschließend ist Überwältigen noch mindestens 5,5 Sekunden aktiv.)

**Comment by Dotox** [comment]
Hey,

danke fürs schnelle testen. Hab nochmal was geändert.

**Comment by FhyEzee** [comment]
Ich werds mir nochmal anschaun, danke für die schnelle Antwort!

**Comment by FhyEzee** [comment]
Mit 2 Personen nochmal getestet. 

Ergebnis:
Die Uptime liegt jetzt bei 3,4-3,6 Sekunden (Überwältigen, so wie auch Rache). Also noch nicht ideal bzw. so wie es sein soll, aber wesentlich besser.

**Comment by Lyps95** [comment]
Jup war der Zweite, war etwas  langsamer beim Zeitmessen (Reaktions technisch bin ich nicht der Besste) hatte so alles von 3,1-3,7 Sekunden Uptime bei OP und Revenge. die meisten waren aber auch im bereich von 3,4-3,6 Sekunden, Wahrscheinlcih hab ich nur zu ungenau gemessen.  Denke mal Der Proc bleibt eine Konstante zeit oben. Vorher war die Dauer des Procs ungleichmäßig.

**Comment by mysteryboyismyname** [comment]
bei mir das gleiche problem. der tooltip ergraut sofort. gestern konnte ich overpower 2 mal benutzen von ca. 40 trys.

**Comment by Lyps95** [comment]
@mysteryboyismyname 
Hast du das auf dem Testserver getestet? Dort ist eine Änderung aufgespielt, Bei der festgestellt wurde, das der OP und revenge proc ca, 3,5 Sekunden bestehen bleiben.  Auf dem Live Server wurde noch Nichts verändert, deswegen passt das mit der Overpower Uptime dort auch noch nicht. Wäre nett wenn du das dort mal testest, ob dir die Uptime auch konstant vorkommt. Bei der Uptime Dauer lässt sich bestimmt noch  was machen. In dem Video ist ja zumindest zu erkennen das es mindestens 5 - 6 Sekunden sein müssten.

**Comment by FhyEzee** [comment]
Ja natürlich aufm Testserver^^

**Comment by FhyEzee** [comment]
Wir haben knapp 40 Minuten Mobs gehauen, es war bei jedem Mob 3,4-3,6 Sekunden.

**Comment by FhyEzee** [comment]
Die Schwankungen enstehen aber wahrscheinlich nur durch die eigene Reaktionszeit

**Comment by FhyEzee** [comment]
@mysteryboyismyname hats aufm Live-Server getestet

**Comment by FhyEzee** [comment]
**Update:** 
Zeit beträgt nun 4,5 Sekunden - Rache so wie Überwältigen

**Comment by Lyps95** [comment]
War auch noch mal auf dem PTR, hab 4,6 - 5,0 Sekunden gemessen, Die meisten Zeiten waren 4,7 Sekunden, aber bin wie gesagt von der Reaktionszeit nicht der Beste beim Zeit Stoppen.
