### ISSUE TITLE
[AQ40] Fehlerhaftes Pathfinding nach Pull und Teleport von Veklor

### ISSUE THREAD

**Issue by rachmin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2470]
Welches Verhalten wird beobachtet?
(1) Beim Pull läuft Veklor seitwärts Richtung des anderen Twins (weil Initialaggro auf Krieger-Tank, der Veknilash pullt), erhält dann Aggro vom Hexer-Tank, läuft weiter Richtung anderem Twin, castet im Laufen seinen Shadowbolt auf den Hexer-Tank und schnippst irgendwann an seine tatsächliche Position zurück (üblicher "Gummibandeffekt" bei Lags).
(Tritt auch beim in (2) beschriebenen Anzeigebug-Laufen auf, dass Veklor im vermeintlichen Laufen castet.)
(2) Nach dem Teleport läuft Veklor vermeintlich in eine beliebige Richtung im Raum, obwohl sein Aggro-Ziel nach dem Teleport in Reichweite und im Sichtfeld gewesen ist. Meist stellt sich heraus (erkennbar daran, dass die Twins sich nicht gegenseitig heilen, obwohl sie sehr nahe beieinander angezeigt werden), dass Veklor dabei tatsächlich einfach nur an seiner Teleportposition steht und seine sichtbare Position ein Anzeigebug ist. Manchmal schnippst Veklor an eine tatsächliche Position zurück, manchmal muss man den Teleport abwarten, um die tatsächliche Position wieder richtig zu sehen.

Wie sollte es sich verhalten?
(1) Veklor sollte sich beim Casten nicht bewegen. 
(2) Nach dem Teleport sollte Veklor einfach an seiner Position stehen bleiben und anfangen, Shadowbolts zu casten, wenn sein Ziel in Reichweite und Sichtfeld ist, anstatt durch den Raum zu laufen.

Schritte zur Reproduzierung
(1) Veknilash von der anderen Seite initial pullen, dann auf Veklors Seite Aggro aufbauen und Pathfinding und Castanimation beobachten.
(2) Twins wie üblich auseinander tanken, auf Teleport warten, Veklors Pathfinding und Castanimation beobachten. (Tritt in letzter Zeit immer häufiger auf, gestern regelmäßig.)

Wir vermuten, dass es an der Leistung (Überlastung) der Instanzenserver liegt (zu der Zeit raidet der Großteil des Servers.), d.h. ohne entsprechende Serverauslastung wird es wahrscheinlich nicht zu reproduzieren sein. Wenn eine technische Lösung nicht ohne Weiteres möglich ist (d.h. Serverkapazität bleibt wie bisher), dann sollte eine Lösung beim Teleport-Verhalten erwogen werden, die den Raids entgegen kommt. (Da ich kein weitere Ahnung davon habe, wie diese aussehen könnte, bleibt es bei dem Allgemeinplatz.)

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Videos sind kurze relevante Auszüge, die das fehlerhafte Verhalten zeigen.

Verhalten (1) trat neben gestern (Sonntag, den 4. Februar 2018, zwischen ca. 18 und 19 Uhr) auch in Vergangenheit häufiger auf (hier etwa am Sonntag, 28 Januar 2018, gegen 19:30).
https://www.youtube.com/watch?v=r74PzhwnzjM
https://www.youtube.com/watch?v=UgG6THMjobA

Verhalten (2) trat gestern (Sonntag, den 4. Februar 2018, zwischen ca. 18 und 19 Uhr) in insg. 3 Tries regelmäßig auf (auch nachdem wir die Instanz 30 Minuten für einen Softreset verlassen hatten).
https://youtu.be/7I2RSlNamG8
https://youtu.be/vnMyn3OeJnY
https://youtu.be/AIOpvedktg0
https://youtu.be/I0C0MZEsvkM
https://youtu.be/4IQCBwCro2I

In den Videos zu (2) sind die jeweiligen Kriegertanks BLAU (Rashock) und GELB (Lynii), die Hexertanks LILA (Leviana) und ORANGE (Telle) markiert.

Vor einiger Zeit gab es einen ähnlichen Teleport-Bug bei Veknilash, siehe https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2339
Diesen konnten wir ebenfalls beobachten (Ticket folgt ggf., wenn ich wieder Zeit dazu habe).

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Imperator Vek'lor: https://datenbank.classic-wow.org/?npc=15276
Twin Teleport (laut wowhead Zuweisung): https://datenbank.classic-wow.org/?spell=800
WoWhead Zuweisung: http://www.wowhead.com/spell=800/twin-teleport

Fußnote: Bedeutet es etwas, wenn die Dauer/Duration bei wowhead 250 Millisekunden ist, in der Datenbank aber "n/a"?

**Comment by Dotox** [comment]
Hey,

danke für deine Mühe; den Fehler hab ich allerdings bereits behoben wird vermutlich am Mittwoch auf den Live-Server aufgespielt.

**Comment by FhyEzee** [comment]
Danke sehr

**Comment by Brgs** [comment]
selbes problem in 5 trys bei who cares am 11.2. 

bitte nochmal öffnen den eintrag, bzw drüber gucken... 

MfG

**Comment by Ulva-Anorhin** [comment]
11.02.2018 wieder verbuggt, anorhin

**Comment by rachmin** [comment]
Bei Epic heute ebenfalls verbuggt, nur noch schlimmer als ursprünglich gemeldet. Videos sind vorhanden und angeblich sollen bei einem der Tries 2 GMs zugeschaut haben.

Ich vermute, die Dauer des Teleportstuns sollte in Vanilla 2.5s statt 0.25s bzw. 250ms sein wie im o.g. WoWhead Link. Sprich: Nach dem Teleport sollten die Twins für ca. 2 Sekunden "festgewurzelt" und "gestunnt" sein. Sie dürfen und sollen sich in der Zeit direkt nach dem Teleport nicht bewegen und keine Aktionen ausführen. Erst nach dem 2.5s "Wurzel-Stun" erfolgt die Zuteilung der Initialaggro und die Aktionen beginnen.

Quelle 1: "Every 30-40 seconds, the two twins will switch places, visible by a blue glow around their feet. The twins will be rooted for about 2 seconds after they teleport before they start attacking again. There is a complete aggro wipe, and the Emperors will attack the closest player to them, who will receive a large amount of threat after the 2 second root runs out."
https://wow.gamepedia.com/index.php?title=Twin_Emperors&oldid=410460
Januar 2007
(vgl. https://web.archive.org/web/20110308134635/http://www.thottbot.com/npc=15275 und https://web.archive.org/web/20061130012937/http://www.anikki.com/aqt_emperors.html)

Quelle 2: https://www.youtube.com/watch?v=HMR_vnt47uU
- ab 2m07s dreht sich Castertwin zwar bereits Richtung Tank, aber erst ca. 2s später castet er den ersten Shadowbolt an; und v.a. der Twin bleibt stehen
- ab 3m55s noch eindeutiger: nach dem Teleport stehen beide Twins kurz einfach nur rum, bevor sie eine Aktion starten

Quelle 3: https://www.youtube.com/watch?v=5y4rpkA0QfA
- bei ca. 0m16s Teleport
- bei ca. 0m18s Beginn des Shadowbolt-Casts
- restliche Video ist in beschleunigter Wiedergabe

Leider scheint es keine archivierte Thottbot-Version des Teleport-Spells zu geben.
https://web.archive.org/web/*/http://www.thottbot.com/spell=800

**Comment by Larirawiel** [comment]
Hi,

also für mich sieht es so aus als ob die Mechanik mit der hohen Initialaggro nach dem Port erst etliche Sekunden zu spät greift. Sprich, die Imperatoren porten sich, ihre Aggro wird gelöscht und dann greifen sie Ziele an, die sich in der regulären Aggro-Tabelle befinden. Das dürften sehr oft Heiler oder DDs, deren Geschosse einschlagen sein. Dann rennen sie wild durch die Gegend, hauen Leute um, heilen sich hoch. Und dann macht es klick, die Mechanik mit der hohen Initialaggro wird aktiviert und sie rennen wieder zurück.

Grüße

**Comment by Dotox** [comment]
Danke für das Feedback. Hab mir das gestern ebenfalls auf dem Live-Server angesehen.

Webdatenbank ≠ Serverdatenbank. Der Cooldown nach dem Teleport ist schon immer 2,5 Sekunden. Das Problem lässt sich nach wie vor nur auf dem Live-Server reproduzieren, auf dem Testserver nicht. Daher sind uns bzw. mir die Hände gebunden.

Mögliche Hauptursache kann nach wie vor die Performance sein, denn das aktuelle Script unterscheidet sich minimal von der Ursprungsversion und hat mit den aufgetretenen Probleme (wie wir jetzt gesehen haben) überhaupt nichts zu tun.

**Comment by rachmin** [comment]
Sollen wir dann einen neuen Bugreport aufmachen oder ist sind die (auch neu aufgetretenen) Probleme soweit bekannt?
Denn derzeit gibt es immernoch ein fehlerhaftes Pathfinding. (Was anscheinend nur auf Liveserver auftritt.).
Und wie gesagt, neu hinzugekommen ist von der reinen Beobachtung des tatsächlichen Verhaltens der Bug, dass die Twins nach jedem Teleport einfach ignorieren, dass sie für 2.5sek bewegungslos (festgewurzelt) keine Aktion machen sollen. Im Gegenteil wirkt nun z.B. der Castertwin direkt nach dem Teleport seine Arkane Explosion, weil jemand in Meleerange ist, obwohl noch keine 2.5s vorbei sind. Oder der Castertwin castet praktisch im Teleport den nächsten Shadowbolt an, sucht sich während der Castzeit aufgrund des Aggroresets und noch vor der Zuweisung der Initialaggro nach dem Teleport einen Spieler aus, der in dem kurzen Augenblick Aggro erzeugt (Heileraggro durch Hots oder Direktheilung oder einen DD, bei dem im Moment des Aggroresets Blutungen oder ein Feuerballdebuff tickt), und wirkt dann den Shadowbolt zu Ende auf dieses Ziel, obwohl der Castertwin durch den Teleport kurzzeitig bewegungs- und aktionslos rumstehen muss und soll und so etwas gar nicht auftreten darf.

Würde es etwas ändern, wenn der "Teleport-Stun" bei den Twins auf 3s oder 4s erhöht würde, wenn aktuell offensichtlich die 2s übersprungen werden oder wird der Stun über nicht gewirkt?

**Comment by Larirawiel** [comment]
Hi,

also wenn das Problem auf dem Liveserver aber nicht auf dem Testserver auftritt dann könnte das eine sog. race condition sein. Sprich, ein Thread läuft los obwohl er Daten eines anderen Threads braucht und der andere Thread die Daten noch nicht zu Ende berechnet hat. Das wäre der erste Anhaltspunkt wo ich suchen würde. 

Und ja, race conditions sind echt arg fies. :<

Grüße
