### ISSUE TITLE
[Quest] Feine Gewürze

### ISSUE THREAD

**Issue by FrostmourneHungers** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2473]
**Welches Verhalten wird beobachtet?**

Die quest Feine Gewürze, gestartet von "Sumpfauge" Jarl verlangt, dass 10x Feine Gewürze abgegeben werden sollen. Dies passt jedoch nicht zum Questtext:

![feinegewuerze](https://user-images.githubusercontent.com/36342581/36066502-ea637e0e-0eaa-11e8-947f-b3e772a4dcf7.JPG)

In unserer Datenbank stimmen Questtext, und Questanforderung überein, allerdings mit 10 Stück.

**Wie sollte es sich verhalten?**
Eigentlich sollten nur 3 Stück verlangt werden. 

Andere DBs sprechen ebenfalls immer von 3 Gewürzen.
https://classicdb.ch/?quest=1218
https://vanilla-twinhead.twinstar.cz/?quest=1218

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Quest: https://datenbank.classic-wow.org/?quest=1218
Questgeber: https://datenbank.classic-wow.org/?npc=4792
Questgegenstand: https://datenbank.classic-wow.org/?item=3713

**Comment by dagochen** [comment]
https://web.archive.org/web/20060516042423/http://wow.allakhazam.com:80/db/quest.html?wquest=1218

**Comment by dagochen** [comment]
@FrostmourneHungers Nächstes mal bitte selbst nach validen Quellen suchen. Die von anderen Privatservern sind nicht zulässig.

**Comment by FrostmourneHungers** [comment]
Alles klar, bin neu hier, war mir deshalb nicht sicher.
