### ISSUE TITLE
Gegner NPC: Heilung Cooldown zu kurz

### ISSUE THREAD

**Issue by Splitframe** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2478]
Welches Verhalten wird beobachtet?
Sämtliche NPC welche sich selbst Heilen können tun dies ohne internen Cooldown.
Die Trigger Grenze für die Selbsheilung ist richtig, allerdings wird der NPC immer versuchen
sich selbst zu heilen wenn er unter dieser ist auch wenn er sich in den letzten 30 Sekunden
bereits selbst oder einen befreundeten NPC geheilt hat.

Wie sollte es sich verhalten?
Auf original Blizzard Server hatte die Heilung einen internen Cooldown von 30 Sekunden.

Schritte zur Reproduzierung
Gegen einen NPC mit Selbstheilung Kämpfen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Dieses Problem führt dazu, dass vor allem in den Anfangsgebieten NPCs mit Heilung für bestimmte
Klassen nahezu unmöglich sind allein zu bezwingen.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Splitframe** [comment]
Hier ein Beispiel NPC:
https://datenbank.classic-wow.org/?npc=3206

**Comment by Simit90** [comment]
Hallo Splitframe,

deine Aufgabe wäre es, eine offizielle Quelle in Bezug auf WoW-Classic darzulegen, die belegt, dass die Abklingzeit zu classic 30 Sekunden betragen hat. In deinem Fall verlinkst du auf unsere Datenbank. Dort hat der Healing Spell keine angegebene Abklingzeit. 
Auf WoWhead hat der Spell ebenfalls keine Abklingzeit: http://bfa.wowhead.com/spell=233421/healing-wave

Und die Kommentare belegen zudem, dass dieser Mob auch auf dem offiziellen Server keine einfachen Gegner sind. 
http://www.wowhead.com/npc=3206/voodoo-troll#comments

Daher: Offizielle Quelle, die belegt, dass die Abklingzeit höher war und man wird sicherlich was dran ändern. Hab selber gerade etwas recherchiert, aber konnt nichts gegenteiliges zu dem Verhalten auf unserem Server finden bisher.

Freundliche Grüße

**Comment by Splitframe** [comment]
Ich kann dazu leider nur Anekdotisch Informationen geben, das Gespräch kam auf als ich mit Freunden, mit denen ich bereits damals 2005 WoW gespielt habe, auf eurem Nefarian angefangen habe.

Und auch wenn die Mobs damals schwer waren, waren sie nicht so unbesiegbar, was daran lag das sie sich nicht mehrmals hintereinander geheilt haben, bzw mit einem längeren Cooldown zwischen den Heilungen.
Dieser Cooldown war natürlich nicht Bestandteil der Zauber an sich, sondern der NPC AI.

Wenn ich mich recht erinnere haben die Scharlach NPC in Tirisfall es damals genauso gemacht:
https://datenbank.classic-wow.org/?npc=1538

Auf den Retail Servern wird dies bis heute so gemacht. Ich werde mal schauen ob ich da ein Webm video
erstellen kann. Falls dies als "Beweis" reicht, es ist halt nicht mehr classic.

**Comment by dagochen** [comment]
Ohne Quellen von 2005/2006 wird das vermutlich nichts.

**Comment by Splitframe** [comment]
Ich habe ein bisschen geforscht, leider sind auf alten gameplay Videos nie heilende NPC zu sehen. Auch ein paar Freunde die mit mir damals classic gespielt haben habe ich mal gefragt, sowie im Battle.net Forum.

Einer meinte sich gut zu erinnern das manche Elite NPC diese Restriktion nicht hatten, normale NPC haben während eines Kampfes selten mehr als einmal geheilt. Die anderen konnten sich nicht gut erinnern ob die NPC mehr als einmal geheilt haben, allerdings sagten viele das sie keine Probleme auf den Echo Inseln oder Tirisfall hatten. Nicht so wie auf heutigen private Servern.

Bei den alten Videos die ich gesehen habe ist mir aufgefallen das besonders im low level bereich die Spieler sehr viel weniger schaden bekommen haben als auf privat Servern heute.

Alles leider nur Anekdotisch, ob ihr es übernehmt oder nicht müsst ihr wissen. Die Game Designer damals waren vielleicht nicht die Krone der Schöpfung aber eine normale Art NPC derart zu overpoweren haben selbst sie damals nicht gemacht.

Hier noch der Foren Eintrag: https://eu.battle.net/forums/de/wow/topic/17618081639#detail

**Comment by dagochen** [comment]
youtubed mal Joanas Playthrough WoW

**Comment by Splitframe** [comment]
Wow danke für den Channel, der ist ja super!
In Ihrem Kampf mit Zalazane kann man gut sehen das sich Zalazane einmal heilt, danach aber erstmal weiter versucht sie anzugreifen. https://www.youtube.com/watch?v=h3pBIJMYEa8

**Comment by dagochen** [comment]
Also bei uns sind da zwischen 2 Heals ein Zeitintervall von 16-21 Sekunden eingeplant, wenn ich mich grad nicht irre. Das deckt sich absolut mit dem Video, da dort 15 Sekunden vergangen sind nach dem 1. Heal, bis Zalazane anfängt zu flüchten, was jegliche Heilung eh unterbindet, bis die Flucht zu Ende ist.

**Comment by Splitframe** [comment]
Hi, sorry für die späte Antwort.
Ich hab Zalazane und den Voodoo Trolls noch einmal besucht. Die 16 Sekunden werden manchmal unterschritten. Aber ja es gibt eine Pause. Ich weiß nicht was es ist, aber manchmal ich glaube durch ein Stück laufen, kann man das Heilen früher triggern. Ich bin mir hier aber nicht sicher.

Ich habe letztens auch erfahren das euer Server wohl absichtlich an einigen stellen schwerer ist.
