### ISSUE TITLE
Die Zwillingsimperatoren sind kaputt

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2482]
**Welches Verhalten wird beobachtet?**

Der Zwilling, der die Schattenblitze zaubert funktioniert überhaupt nicht. Er läuft sehr oft in den Nahkampf und zaubert dann den Arcane Burst weil sich dann jemand in Nahkampfreichweite befindet. 

Auch die Mechanik mit der initialen Aggro nach dem Teleport funktioniert nur sehr zeitversetzt. Sprich, direkt nach dem Teleport nimmt der Zwilling scheinbart zufällig Leute ins Ziel und verteilt die Schattenblitze. Ich verrmute mal, es kommt hier die normale Aggro-Mechanik zum Einsatz. Ein paar Sekunden später nimmt er dann doch den Spieler ins Ziel, der sich beim Port am nächsten befand. Offenbar wird die Mechanik mit den 3.000 Aggro nach dem Port einige Sekunden später aktiv

**Wie sollte es sich verhalten?**

Der Zwilling, der die Schattenblitze zaubert sollte stehen bleiben so lange der Spieler in Zauberreichweite ist. Und die Mechanik mit den 3.000 Aggropunkten nach dem Port sollte sofort nach dem Port aktiv sein und nicht erst einige Sekunden später.

**Schritte zur Reproduzierung**

Mit einem 40-Mann-Raid die Zwillingsimperatoren angreifen und einige Ports abwarten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?npc=15276
https://datenbank.classic-wow.org/?npc=15275

https://datenbank.classic-wow.org/?spell=568
https://datenbank.classic-wow.org/?spell=26006

**Comment by Toeterli** [comment]
https://www.youtube.com/watch?v=RyPmyd_Q8xc        
https://www.youtube.com/watch?v=ObxU63iUTLg              
https://www.youtube.com/watch?v=Rbl7-2URRow

Es scheint so zu sein, dass der Castertwin genau dann buggt, wenn sich der Kriegertank beim Port nicht mehr unter dem Twin befindet (also in seinem "Kreis", der Rand des Kreises zählt schon als außerhalb), so zumindest bei allen Ports in den Videos.

**Comment by Dotox** [comment]
Dago und ich konnten das beschriebene auf dem Testserver reproduzieren und soweit beheben. Es tritt zumindest nicht mehr auf dem Testserver auf.

**Comment by Tiffel** [comment]
Reproduzieren klingt schonmal super. Ist der fix schon auf live, damit man ihn diese Id noch testen kann?

**Comment by Dotox** [comment]
Hey,

der Fix kommt heute Nachmittag auf den Live-Realm.

**Comment by Dotox** [comment]
Fix befindet sich ab 14:40 Uhr auf Nefarian.

**Comment by Simit90** [comment]
hat bei uns gestern wunderbar wieder funktioniert. Scheint auch bei anderen Gilden wieder geklappt zu haben, danke! Kann denke ich geschlossen werden
