### ISSUE TITLE
[NPC] Bena Winterhuf Alchemie Lehrer

### ISSUE THREAD

**Issue by hk227s** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2484]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version: 1.8.0

Wie sollte es sein?
Bena Winterhuf in Donnerfels sollte auch die Stufe Geselle (Journeyman) für Alchemie anbieten.

Wie ist es?
Man kann bei ihr nur die Stufe Lehrling (Apprentice) erlernen.

Links:
https://datenbank.classic-wow.org/?npc=3009
 
Quelle:
http://vanillawowdb.com/?npc=3009#teaches-ability
 
Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by dagochen** [comment]
Bitte such eine korrekte Quelle dafür raus. Fremde Privatserver und deren Datenbanken werden leider nicht akzeptiert.
