### ISSUE TITLE
[Naxxramas - Invasion] - Zerknittertes Schreiben

### ISSUE THREAD

**Issue by booneyclassic** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2487]
## Welches Verhalten wird beobachtet?

Während der Invasion besitzen die spawnenden Untote eine gewisse Chance, dieses Item zu droppen.
[Zerknittertes Schreiben.](https://datenbank.classic-wow.org/?item=22973) Dieses startet eine Quest, [(Schreiben von der Front)](https://datenbank.classic-wow.org/?quest=9302) welche man laut Questtext an der Kapelle abgeben muss. Leider fehlt der NPC bei dem man die Quest abgeben kann!

Laut der Quelle unten, sollte es sich dabei um diesen NPC handeln auf unserem Server handeln:
[Bewahrer der Schriften](https://datenbank.classic-wow.org/?npc=16281). Nur existiert der wie gesagt nicht. 

Informationen zu einer Questbelohnung im Rahmen von Gold, Ruf oder Items konnte ich leider nicht finden. Vielelicht weiß da jemand mehr als ich :)

## Wie sollte es sich verhalten?

Man sollte die Quest auch abgeben können.

## Schritte zur Reproduzierung

Sich auf die Quest begeben!

## Zusätzliche Informationen (Screenshots, Videos, etc.)

Quelle: [Absatz - Letters from the Scourge](http://wowwiki.wikia.com/wiki/Scourge_Invasion)
--> In dem Text steht, das sogar 6 verschiedene Briefe droppen.
Dies ist jedoch aus Woltk, daher bitte nicht beachten!

**Comment by Simit90** [comment]
#2438
