### ISSUE TITLE
Improved Drain Soul funktioniert nicht

### ISSUE THREAD

**Issue by Vahn1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2492]
Welches Verhalten wird beobachtet? Mit 2 Punkten in "Improved Drain Soul" sollte der Hexenmeister, wenn der Gegner unter dem Einfluss von diesem Zauber stirbt, einen 10 sekündigen Manatick bekommen.

Wie sollte es sich verhalten? Das Mana sollte anschließend für 10 Sek. schneller regenerieren.

Schritte zur Reproduzierung Einen Gegner angreifen und vor dessen Tod "Drain Soul" wirken. Zuvor 2 Punkte in "Improved Drain Soul" investieren.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.) Mensch, Hexenmeister, Level 21

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=1120

Das geskillte Talent: https://datenbank.classic-wow.org/?spell=18372

**Comment by Slimmer2** [comment]
Dieser Skill geht nur wenn man den Gegner selbst getötet hat.
Hat ein anderer Spieler den Gegner getötet. Dann bekommst du den Skill nicht

**Comment by dagochen** [comment]
Bug oder kein Bug?

**Comment by hraesvelgr** [comment]
ist beim priester genauso. willensentzug procct nur, wenn der hit, der den npc tötet, auch vom priester priester selber kam. der priester muss töten, um den buff zu bekommen. 

ist mit großer wahrscheinlichkeit kein bug.

**Comment by Vahn1** [comment]
Auch wenn ich allein unterwegs bin und diesen Zauber wirke, bekomme ich weder einen Buff noch kann ich eine schnellere Manaregeneration beobachten. Die beiden Talentpunkte sind somit faktisch verschenkt.

**Comment by stva23** [comment]
Soweit ich das in Erinnerung habe muss der Tick vom Drain Soul den Tod verursachen, damt es wirkt. Somit wirklich ein schwaches Talent.

**Comment by Vahn1** [comment]
Wenn das so wäre, dann wäre der Tooltip überarbeitungswürdig und das Talent wirklich sehr schwach.

**Comment by dagochen** [comment]
Tooltips von Zaubern können wir leider nicht verändern. Ist das jetzt weiterhin nur eine Mutmaßung, oder Gewissheit? Hat jemand Quellen für die eine oder andere Variante, bevor ich den Issue hier zu mache?

**Comment by stva23** [comment]
Ich denke das funktioniert hier am Server genauso wie damals am Offi, inkl. irreführender Beschreibung.

**Comment by Vahn1** [comment]
Das Talent funktioniert, wenn der Gegner tatsächlich **am Soul Drain stirbt**. Da der Tooltip nicht konkretisiert werden kann, kann der Issue meinetwegen geschlossen werden.
