### ISSUE TITLE
Zielattrappe gibt kein Loot

### ISSUE THREAD

**Issue by Ulva-Anorhin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2495]
Welches Verhalten wird beobachtet?
Wenn man die Zielattrappen von einem Ingi killen lässt, durch Mobs oder im Duell, droppen sie nichts und sind verschwunden. Ich denke das wird dann auch bei den anderen Attrappen der Fall sein.
Wie sollte es sich verhalten?
Die Zielattrappen sollten Ingi items dropen.
Schritte zur Reproduzierung
Zielattrappe bauen und töten.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://wowdata.buffed.de/item/Handwerkswaren/Zielattrappe-4366#comments kommentare lesen
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=4366

**Comment by dagochen** [comment]
Wer sollte diese Looten können, wenn ein Spieler/Mob die tötet? Sollten diese auch lootbar sein, wenn sie zerfallen, weil die Zeit abläuft?

**Comment by Millco** [comment]
Im originalen Vanilla konnte der, der sie aufgestellt hat sie nach Ablauf der Zeit und nach Zerstörung looten.

**Comment by dagochen** [comment]
Quelle?

**Comment by Millco** [comment]
http://www.wowhead.com/npc=2673/target-dummy
http://de.wowhead.com/item=4366/zielattrappe#english-comments
http://wowwiki.wikia.com/wiki/Target_Dummy
https://wow.gamepedia.com/Fused_Wiring
(https://vanilla-twinhead.twinstar.cz/?npc=2673)

**Comment by Donf4b** [comment]
ja ich erinnere mich auch genau, so hat man die verschmorrten verkabelungen bekommen

**Comment by treutz** [comment]
Ich war jahrelang Ingi - kann das auch bestätigen mit dem Loot. Der Ing, der ihn gestellt hat, musste ein paar Minuten warten bis die Attrappe ausgewinkt hat (ohne Dmg. kassiert zu haben) und dann konnte man nach einem "Poff" die funkelnde Attrappe looten.

**Comment by Ulva-Anorhin** [comment]
Es steht "fix auf Nefarian" funktioniert aber noch nicht.
Habs im Duell getestet und auch gegen Mobs sterben lassen... nie Looten knnen
