### ISSUE TITLE
[Naxxramas] Pre Event Kristalle Bug

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2496]
Welches Verhalten wird beobachtet?
Ich könnte eine mögliche Ursache gefunden, warum die Events manchmal nicht korrekt abschließen. 

Wenn ein Paladin Heiliger Schock auf den Kristall oder ein Schamane in der Nähe des Kristalls Kettenheilung auf einen Spieler wirkt, könnte das auf den Kristall überspringen und dadurch den Kristall verbuggen. Dann geht er nicht in die nächste Phase und bleibt mit 1-2 % dort stehen.

Wie sollte es sich verhalten?
Die Kristalle sollten auf 0 % droppen und anschließend die Akolyten erscheinen.

Schritte zur Reproduzierung
Kristall durch die Mobs auf unter 100 % droppen lassen und Kettenheilung auf einen Spieler neben dem Kristall wirken oder Heiliger Schock auf den Kristall wirken.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16136
https://datenbank.classic-wow.org/?npc=16172

**Comment by Dotox** [comment]
Hatte ich dahingegend schon so verändert, dass das Event nicht mehr vom Prozentsatz des Kristalls abhängig ist, sondern anhand der getöteten Mobs die gespawnt sind. Das Problem tritt aber immer noch auf.
