### ISSUE TITLE
Aimed Shot (Hunter) Castzeit ist nicht richtig

### ISSUE THREAD

**Issue by ChainoNacro** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2499]
Welches Verhalten wird beobachtet?
- Beim Aimed Shot vom Hunter ist die Castzeit nicht korrekt. Laut Tooltip sollte die Castzeit bei 3 sec liegen. Laut meinem Addon eCastingBar liegt die Castzeit bei 3.2 sec.

Wie sollte es sich verhalten?
- Ohne Köcher sollte die Castzeit bei 3 sec laut Tooltip sein. Mit Köcher der die Range Attack Speed auf 15% erhöht sollte die Castzeit bei 2,55 sec liegen.

Schritte zur Reproduzierung

- Einen Mob ins Target nehmen -> Aimed Shot casten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
- keine vorhanden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
- Aimed Shot (Hunter)

**Comment by booneyclassic** [comment]
Also laut meiner Rechenmaschine sollte der Cast "Gezielter Schuss" mit 15% Speed 2,77 Sekunden dauern und nicht 2,55 sec

**Comment by Donf4b** [comment]
hier ist der aktuelle stand der dinge genau nachzulesen:

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1625

**Comment by ChainoNacro** [comment]
Aimed Shot ist aber schon seit langem buggy und ich dachte man sollte das Thema mit einem neuen Bugreport auffrischen.
