### ISSUE TITLE
Kampfverhalten Elite-NPC's in Lohenscheit

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#250]
Welches Verhalten wird beobachtet?
Die Elite-NPC's in Lohenscheit/Pyrewood greifen im Nahkampf nicht an, verharren nur in Kampfhaltung und schlagen selten oder gar nicht zu. Ansonsten ist das Verhalten aber i.O. Sie verfolgen den Spieler, lassen sich normal pullen und looten. Das Fehlverhalten trifft auf mehrere Arten von NPC's in Lohenscheit zu.

Wie sollte es sich Verhalten?
Elite-NPC's sollten den Spieler attackieren, sobald er ihren Aggro-Radius betritt.

Schritte zur Reproduzierung
Lohenscheit betreten und NPC's angreifen.

Bei folgenden NPC's konnte das Verhalten beobachtet werden:
http://datenbank.welli-it.de/?npc=1891
http://datenbank.welli-it.de/?npc=1894
http://datenbank.welli-it.de/?npc=3530
http://datenbank.welli-it.de/?npc=2067

**Comment by wahaxlekuke** [comment]
Das hat sich scheinbar mit den Änderungen am Movement erledigt.
