### ISSUE TITLE
[Item] Seal of the Dawn

### ISSUE THREAD

**Issue by imbaan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2503]
_Welches Verhalten wird beobachtet?_

Das Item Siegel der Dämmerung https://datenbank.classic-wow.org/?item=13209
gibt keine zusätzliche AP gegen Untote.

Selbiges gilt für das Mal der Helden https://datenbank.classic-wow.org/?item=23206  (Test steht aus)

_Wie sollte es sich verhalten?_

Die Angriffskraft sollte sich gegen Untote erhöhen und damit verbunden der Schaden der Kriegerfähigkeit Blutdurst.

_Schritte zur Reproduzierung_

Einen Untoten Mob angreifen und Blutdurst https://datenbank.classic-wow.org/?spell=23900
benutzen und den Schaden aus dem Combatlog entnehmen.

_Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)_

http://up.picr.de/31996917mn.jpg

http://up.picr.de/31996918jj.jpg

http://up.picr.de/31996919qe.jpg

http://up.picr.de/31996920sz.jpg

http://up.picr.de/31996921la.jpg

http://up.picr.de/31996922fy.jpg

http://up.picr.de/31996923ql.jpg

**Comment by imbaan** [comment]
Kel ist down - wäre sehr schade wenn das Trinket für Melees unbrauchbar wäre.
Kannst du schon etwas dazu sagen @dagochen @Dotox

**Comment by dagochen** [comment]
Wir arbeiten an einer Lösung!

**Comment by Donf4b** [comment]
wenn ich das ganze richtig verstehe, dann bezieht sich die Fähigkeit Blutdurst wohl auf den aktuellen, im charakterfenster angezeigten, AP wert. Dieser wird beim tragen eines der schmuckstücke und anvisieren eines untoten nicht erhöht.

zumindest für das siegel der dämmerung kann ich sagen, dass der schaden sich gegen untote eindeutig erhöht, wenn das siegel getragen wird (getestet mt lvl 1 Waffen). Dies gilt sowohl für auotmatische angriffe, als auch fähigkeiten, welche sich nicht direkt auf den AP wert beziehen (meine theorie).

demnach müsste man entweder die bestimmung der AP in dem charakterfenster beim anvisieren bestimmter NPC-Typen (untote) anpassen, oder den Wert, auf den sich die Fähigkeit (speziell Blutdurst) bezieht, auf den ap wert verschieben, der tatsächlich gegen den npc gilt.

macht das ganze sinn?

**Comment by dagochen** [comment]
letzteres ist korrekt. das anrechnen von attackpower gegen bestimmte ziele funktioniert, nur bei blutdurst halt nicht, da dort eine andere funktion aufgerufen wird.

**Comment by imbaan** [comment]
Guten morgen, und was ist die Lösung des Problems?
Ein weiterer Monat zieht ins Land und diese Mechanik inkl. der Wetzsteine, die fleißig zum opening Event gefarmt wurden liegen auf der Bank ohne Sinn, Zweck und Funktion.
Würde mich sehr über einen zeitnahen Fix freuen.
Vg
