### ISSUE TITLE
Naxxramas: Trash Respawn obwohl Boss tot ist

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2505]
Welches Verhalten wird beobachtet?
Im Military Wing respawnt ein grosser Teil der Trashmobs sowie die Death Knight Understudies obwohl Razuvious getötet wurde.

Wie sollte es sich verhalten?
Der Trash vor Razuvious sollte nicht mehr respawnen nachdem der Boss getötet wurde.

Schritte zur Reproduzierung
- Razuvious töten
- 3 Tage später wieder in die Instanz gehen

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
-

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?spell=29059
https://datenbank.classic-wow.org/?npc=16146
https://datenbank.classic-wow.org/?npc=16145
https://datenbank.classic-wow.org/?npc=16156
https://datenbank.classic-wow.org/?npc=16157
https://datenbank.classic-wow.org/?npc=16803

**Comment by Dotox** [comment]
Wann wurde der Boss getötet? Wann wurde der Respawn festgestellt? Kannst du ausschließen, dass der Trash oder Teile davon während dem Kampf gerespawnt ist?

**Comment by xorann** [comment]
Boss wurde am Mittwoch getötet. Respawn habe ich heute gesehen. Die ersten paar Gruppen sind nicht respawned, erst ab der Galerie. Unten in den Ställen war glaub auch nur ein Pferd respawned.

Hier anzusehen: https://youtu.be/PdgTp1XYs8E?t=1h27m11s

**Comment by Dotox** [comment]
Hab diese Woche in einige IDs geschaut und dort ist der Trash nicht respawnt. Gibt wohl (laut deinen Aussagen) eine Bedingung, die erfüllt werden muss, damit das Beschriebene passiert.

**Comment by xorann** [comment]
Habe gerade noch einmal nachgesehen wie es diese ID aussieht. Diesmal ist nichts respawned, auch nicht in den anderes Wings.
Was wir das letzte mal aussergewöhnliches getan haben könnten, dass so etwas passiert, wüsste ich jetzt nicht wirklich.

**Comment by xorann** [comment]
Heute hatten wir Trash Respawn bei Grobbulus, obwohl wir Grobbulus gestern Abend getötet haben.

**Comment by Koringar** [comment]
Kann nachvollzogen werden. Der Fehler ist sehr Sporadisch, sind ja die besten Fehler.

Bei uns das erste mal bei der ID in der Woche 28.02.18-06.03.18 aufgetreten. In der Woche 07.03.18-13.03.18 nicht auftreten, als ich mal Videos machen wollte.
In der jetzigen Woche 14.03.18-20.03.18 jedoch wieder aufgetreten, wenn es vielleicht weiter Hilft ID 4.

Hier das Video wie wir Razuvious getötet haben und danach den leeren Raum:
https://youtu.be/gV1AH8Z9GYk

Beim nächsten reingehen war etwas Trash und die Adds von Razuvious wieder da:
https://youtu.be/wERPCLeJc4g

**Comment by Koringar** [comment]
Heute Trash von Grobbulus respawn, obwohl Boss down. ID 18, 21.03.18-27.03.18. Videos können nach gereicht werden.

**Comment by Dotox** [comment]
Warum der Trash respawnt kann ich leider noch nicht sagen; habe nun eine Änderung durchgeführt - würde mich über Feedback freuen!

**Comment by Cuanoco** [comment]
Feedback vom 12.4.18, der Fix scheint zu funktionieren. Razu wurde Mittowch 11.4.18 gelegt, am gestrigen Abend lag der komplette Trash incl seiner 4 Adds tot am Boden. Dem Enstprechend interpretiere ich den Fix als Killsequence nachm Softreset und neu betreten der Instanz, worked.

**Comment by Ulva-Anorhin** [comment]
Loatheb wurde am 11.4. gelegt und am 15.4. war der komplette Trash des Wings down inclusive der Gruppen die wir geskippt haben und der komplette Heigan raum.

Wenn ein GM eingegriffen hat, danke :) falls nicht, funktioniert es noch nicht perfekt, aber es gab keinen respawn.

**Comment by Dotox** [comment]
Vielen Dank für das Feedback! Aktuell liegt der Trash ungewöhnlicherweise noch sichtbar am Boden, auch wenn er bereits Tage tot ist. Ich denke, dass wir in Zukunft hier aus ästhetischen Gründen nochmal nachbessern werden.

**Comment by Ulva-Anorhin** [comment]
Trash ist diese ID wieder Down, sieht zwar wieder frisch gelegt aus aber so wie es zur Zeit abläuft funktioniert es sehr gut. Danke :)

**Comment by Koringar** [comment]
Wie schon von anderen gemeldet, so wie es momentan ist läuft es gut. Auch wenn der Respawnte Trash noch am Boden liegt.
