### ISSUE TITLE
Patchwerk verwendet Hateful Strike nur auf Tanks die vor dem Boss stehen

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2506]
Welches Verhalten wird beobachtet?
Auf Tanks welche hinter Patchwerk stehen, verwendet Patchwerk kein Hateful Strike.

Wie sollte es sich verhalten?
Alle Spieler in Nahkampfreichweite sollten von Hateful Strike getorffen werden können

Schritte zur Reproduzierung
Boss pullen und alle ausser Main Tank hinter den Boss stellen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
(folgt bei Gelegenheit)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16028
https://datenbank.classic-wow.org/?spell=28308

**Comment by Dotox** [comment]
Bereits behoben, ist mit dem nächsten Neustart / Crash aktiv.

**Comment by Sheed90** [comment]
Der Hatefull wurde aber trotzdem auf ein Target vor ihm ausgeführt?

**Comment by xorann** [comment]
Nein, wurde schlicht nicht benutzt, solange nur der MT vor dem Boss stand.
