### ISSUE TITLE
T3 Set-Bonus Druiden

### ISSUE THREAD

**Issue by nexus307** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2507]
T3 Set Druide
Welches Verhalten wird beobachtet?
2 pieces: Your Rejuvenation ticks have a chance to restore 60 mana, 8 energy, or 2 rage to your target.
Funktioniert zurzeit nur auf den Druiden selber und gibt nur Mana wieder.
6 pieces: Your initial cast and Regrowth ticks will increase the maximum health of your target by up to 50, stacking up to 7 times.
Initial Cast erhöht die Gesundheit um 50 für 4 Sec.
Wie sollte es sich verhalten?
2 pieces: Your Rejuvenation ticks have a chance to restore 60 mana, 8 energy, or 2 rage to your target.
Solllte bei jeder Manaklasse auf die Verjüngung gecastet wird eine Chance geben Mana wiederherzustellen.
Sollte bei jeder Energieklasse auf die Verjüngung gecastet wird eine Chance geben Energie wiederherzustellen.
Sollte bei jeder Wutklasse auf die Verjüngung gecastet wird eine Chance geben Wut wiederherzustellen.
6 pieces: Your initial cast and Regrowth ticks will increase the maximum health of your target by up to 50, stacking up to 7 times.
Auch die ticks sollten die Gesundheit erhöhen, was Sie zurzeit nicht machen.
Schritte zur Reproduzierung
6 er Bonus anziehen und Verjüngung sowie Nachwachsen auf andere Klassen casten.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Braucht man nicht, da im Tooltip alles Relevante drin steht.
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?itemset=521 T3 Druide
https://datenbank.classic-wow.org/?spell=28716 2er Set
https://datenbank.classic-wow.org/?spell=28744 6er Set
https://datenbank.classic-wow.org/?spell=9858 Regrowth
https://datenbank.classic-wow.org/?spell=25299 Verjüngung

Der 2-er Set-Bonus funktioniert leider nicht wie er funktionieren sollte! Der Tick kommt nur bei dem Char selbst und direkt beim wirken nicht bei den Tick´s!

Bei anderen Charakteren funktioniert er nicht mal beim wirken!

**Comment by Sheed90** [comment]
Der 2er Bonus funktioniert derzeit wie folgt:

1. Verjüngen wird gesetzt
2. Procct nur beim setzen des Hots und nicht bei den Ticks des Hots
3. Procct nur auf Druiden

**Comment by Cuanoco** [comment]
Kann Sheed90 bestätigen, bei mir das gleiche Muster beim 2er Bonus. Bei Selfcast ca. 10% Procc des Initial Ticks, danach kein einziger mehr. Test auf andere Klassen allesamt negativ, kein einziger Procc, weder Initial noch durch Folgeticks.

**Comment by Coz-Nalenia-Khaori** [comment]
2er Boni funktioniert nicht wie oben beschrieben. 
6er Boni funktioniert auch nicht wirklich. Der 50HP "Buff" wird nach dem Initialcast zwar gesetzt aber es stackt nicht hoch mit weiteren ticks vom Nachwachsen. Der Buff kann nur hoch gestackt werden indem weitere Nachwachsen gecastet werden.

**Comment by Envie** [comment]
2er Setboni habe ich auch beobachtet.
Hat nur eine Chance zu proccen wenn man den Buff Verjüngen erhält (und auch nur bei Mana derzeit).
Die Healticks erzeugen jedoch nichts.

**Comment by Coz-Nalenia-Khaori** [comment]
Gibt es hierzu schon ein Update? Ggf. eine ETA für einen Fix?

**Comment by Cuanoco** [comment]
Sind hier alle im Urlaub? Nachdem es sich hier ja nicht um das einzige Set handelt das nicht richtig funktioniert wäre es generell mal schön wenn hier etwas unternommen wird. Die meisten Sets haben nur wegen ihrer Boni eine Daseinsberechtigung, rein von den Stats her sind die meisten Nonset teile aus AQ und Naxx besser. Die Inaktivität diesbezüglich führt immer mehr zu Frustration und damit auch zu Inaktivität von Spielern, das nur mal so am Rande...

**Comment by Sheed90** [comment]
Es wurde vor 2 Tagen gefixed und funktioniert nahezu einwandfrei.

Einziges Problem, welches wir feststellen konnten ist, dass bei dem Buff der durch Nachwachsen entsteht nur die max HP und nicht die min HP erhöht wird.

Andere Buffs, wie z. B. Last Stand erhöhen min und max HP.

Gruß
Sheed

**Comment by Cuanoco** [comment]
Also ich habs grad eben an mir und nem Warri ausprobiert, und kann das leider nicht bestätigen. Der initial Tick auf mir kam zu 2/3 der Zeit, ein anderer Tick kam kein einziges mal, werder auf mir noch dem Warri. Haben es mit low HP und voller HP versucht, das einzige, wir waren nicht infight aber das darf kein Kriterium sein. @ Sheed wie habt ihr es getestet?

**Comment by Sheed90** [comment]
Auf dem Testserver, hätte ich vielleicht erwähnen sollen. :P

**Comment by Cuanoco** [comment]
Lappen :)
