### ISSUE TITLE
Ritual der Beschwörung

### ISSUE THREAD

**Issue by Ychap** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2510]
Leider funktioniert [Ritual der Beschwörung](https://datenbank.classic-wow.org/?spell=698) seit dem letzten Server-Update nicht mehr ganz richtig.

**Welches Verhalten wird beobachtet?**
Man kann als Mitspieler einen Backport, den man mittels [Ritual der Beschwörung](https://datenbank.classic-wow.org/?spell=698) in einer Instanz bekommen hat, nicht mehr außerhalb der Instanz annehmen.

**Wie sollte es sich verhalten?**
Wenn man den Backport außerhalb der Instanz annimmt, sollte man zurück in die Instanz zum Hexenmeister teleportiert werden.
Wichtig ist hierbei nur, dass beide Spieler in der selben Instanz waren, als [Ritual der Beschwörung](https://datenbank.classic-wow.org/?spell=698) gewirkt wurde.

**Schritte zur Reproduzierung**
Man beschwört als Hexenmeister innerhalb einer Instanz einen Mitspieler mit [Ritual der Beschwörung](https://datenbank.classic-wow.org/?spell=698). Dieser Mitspieler benutzt dann seinen Ruhestein, um sich schnell in der Hauptstadt Pots oder ähnliches von der Bank zu holen. Nun kann dieser aber seinen noch offenen Backport nicht annehmen. Das Fenster verschwindet beim Annehmen einfach.

**Spell in Datenbank:**
Ritual der Beschwörung: https://datenbank.classic-wow.org/?spell=698

**Comment by Urschwamm** [comment]
Lt den heutigen "Patchnotes" (https://community.mmobase.de/forum/thread/11465-wartungsarbeiten-mittwoch-07-03-2018/?action=firstNew) ist das so gewollt und bezieht sich auf Patchnotes 1.6.0 (http://wowwiki.wikia.com/wiki/Patch_1.6.0) 

Der Text dort lässt aber m.E. Interpretationsspielraum. 
"Ritual der Beschwörung - Ein Fehler wurde korrigiert, bei dem manchmal Spieler von außerhalb derselben Instanz, wie der Hexenmeister beschworen werden konnten."
Einen Bezug auf den "backport", wie er hier im Bugtracker beschrieben ist, sehe ich in den Patchnotes nicht wirklich.
Oder aber ich scheiter grade an meinen rudimentären Englischkenntnissen bei der Übersetzung der Patchnotes.

**Comment by Badorr** [comment]
Nee, nicht nur du. Bin auch sprachlos über diese sehr freie Interpretation seitens der Serverleitung. Ist das die einzige Quelle, anhand der das geändert wurde? 

Der Satz sagt lediglich aus, dass es einen Bug gab, mit dem manchmal jemand beschworen werden konnte, der sich **zum Zeitpunkt der Beschwörung** nicht in derselben Instanz wie der Warlock befand. 

Da steht nicht, dass man den Port nicht **annehmen** sollen könnte, wenn man sich zu diesem Zeitpunkt nicht innerhalb derselben Instanz wie der Warlock befindet.

**Comment by Denson87** [comment]
Alleine der Ausdruck "in some cases" deutet ja darauf hin das **manchmal** ein Bug auftreten kann. Da der Backport aber **immer** funktioniert hat interpretiere ich darein das der Backport hier nicht als Bug gewertet wird. 

Ich deute es eher so das Blizzard fixen wollte das jemand mit der selben ID wie der Warlock nicht von aussen in die Instanz hereingeportet werden kann. Ergo der Port wird angesetzt während das Ziel ausserhalb der Instanz ist und nicht wie beim Backport innerhalb.

**Comment by Omegaexodus** [comment]
Hier ist noch ein Nachweis, dass das wirken von "Ritual der Beschwörung" wohl in Instanzen funktioniert hat und diese 2 Minuten Zeit hatten, sich außerhalb der Instanz zu bewegen, bevor Sie wieder zurück mussten / konnten. 

Die einzige Ausnahme gab es damals für BGs, da dort bestimmte Game-Mechaniken (Flaggen-Tap, etc.) hätten ausgenutzt werden können. Auch gab es eine Ausnahme zu TBC Zeiten wo die Instanz "Zulaman" für den Teleport gesperrt war, da es auf Grund des "Chest-Events" zu Manipulationen hätte kommen können.

http://de.wowhead.com/spell=698/ritual-der-beschworung#english-comments

Siehe 2006: 

_"A great trick for the Ritual of Summoning is for the Warlock to select himself and two party members "summon" him. This brings up the Summon Accept screen and it gives you 2 minutes before it wears off. The Warlock may then hearth and repair, buy food/water for the group, or whatever else they want in two minutes. They then simply accept the summon from themselves. Voila! No time walking back.

(Note: This isn't as useful for 5 man instances now with meeting stones summoning. It is still useful for questing, random grouping, and **raid areas**.)

**Comment by Dotox** [comment]
Danke für deine Hilfe. Der Spieler, der uns das gemeldet hat, hatte auch eine Quelle dazu geliefert, allerdings finde ich diese nicht (mehr) und auf Nachfrage gab es bisher keine Antwort. Dann nehmen wir die Änderung zeitnah wieder raus.

**Comment by Simit90** [comment]
> Danke für deine Hilfe. Der Spieler, der uns das gemeldet hat, hatte auch eine Quelle dazu geliefert, 

Sollte sich der Spieler noch melden und eine Quelle nach liefern, darf er sich gerne öffentlich outen. Wir tun dem schon nichts :b

**Comment by rachmin** [comment]
Auch wenn wir sicher nicht mehr rekonstruieren können, welche Einzelfälle den 1.6-Bugfix damals nötig machten, würde ich auf die BGs tippen, da diese in 1.5 eingeführt worden sind und immerhin seit 1.1 galt, dass man nur Spieler in der selben Zone initial porten konnte.

**Comment by Dotox** [comment]
Hey,

leider ist aus dem "zeitnah" nichts geworden, da der Server über das Wochenende bzw. seit den letzten Wartungsarbeiten nicht mehr gecrasht ist und ich die Laufzeit aktuell nicht unterbrechen wollte. Die Änderung kommt sehr wahrscheinlich erst am Mittwoch mit den Wartungsarbeiten.
