### ISSUE TITLE
Hexerquest: Fragment der Kugel von Orahil

### ISSUE THREAD

**Issue by Roesmdiboems** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2513]
Welches Verhalten wird beobachtet?
Es ist nicht möglich bei den Akolyten einen "Weg", wie im Questlog beschrieben, auszuwählen. Weder vor noch nach dem Besorgen der Höllenkugel aus Desolace.
Wie sollte es sich verhalten?
Laut Quest, soll man nach der Annahme mit den Akolyten im Turm in Ratchen sprechen und einen Weg auswählen und anschließend die Höllenkugel aus Desolace besorgen. Anschließend soll man die Quest abschließen können.
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
- Rasse: Orc
- Level: 39
- Klasse: Hexenmeister
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Item --> Höllenkugel: https://datenbank.classic-wow.org/?item=7291
Quest --> https://datenbank.classic-wow.org/?quest=1799
Questgeber --> Menara Leerbringer: https://datenbank.classic-wow.org/?npc=6266
Akolyten --> 
Akolyt Fenrick: https://datenbank.classic-wow.org/?npc=6253
Akolyt Magaz: https://datenbank.classic-wow.org/?npc=6252
Akolyt Wytula: https://datenbank.classic-wow.org/?npc=6254

**Comment by LordVuledemort** [comment]
Also bei mir ging das noch vor 2-3 Tagen etwa. 2 der 3 Akolyten hatten eine Quest für mich. Hab die vollständige Questsreihe abgeschlossen. Nur meine 2 Cents^^
