### ISSUE TITLE
[Item] Geweihter Wetzstein

### ISSUE THREAD

**Issue by imbaan** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2514]
Welches Verhalten wird beobachtet?

Der durch das Naxx Eröffnungsevent zugängige "Geweihte(r) Wetzstein" https://datenbank.classic-wow.org/?item=23122 gibt keine Bonusangriffskraft in Form von mehr Schaden bei der Kriegerfähigkeit Blutdurst.

Wie sollte es sich verhalten?

Nach dem Applizieren des Wetzsteins sollte sich die Angriffskraft (um 100) und der damit verbundene Schaden von Blutdurst ( siehe Fähigkeit Blutdurst https://datenbank.classic-wow.org/?spell=23894) erhöhen.

Schritte zur Reproduzierung

Untote NPCs angreifen und über den Combatlog den Schaden von Blutdurst mit und ohne Wetzstein beobachten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Ein ähnlicher Bugreport ist bereits verfasst worden, der den gleichen Fehler behandelt.
Siehe: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2503
Video:  ....folgt

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by yoimbo** [comment]
Video: https://www.youtube.com/watch?v=cIa7OX1MGf4

**Comment by imbaan** [comment]
Wollte mich mal erkundigen ob es hier ein Update gibt?
