### ISSUE TITLE
Pathing in Burning Blade Coven

### ISSUE THREAD

**Issue by krangerich** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2517]
**Welches Verhalten wird beobachtet?**
Wenn man Mobs ist der westlichen Seite des Burning Blade Coven (Höhle im Ork / Troll-Startgebiet) engagt, rennen sie vom Spieler weg, ggf. evaden sie irgendwann und rennen wieder zurück an ihren Spawnpoint. Möglicherweise sind alle Höhlen der gleichen Art betroffen

**Wie sollte es sich verhalten?**
Normales Pathing-Verhalten: Mobs rennen nicht spontan weg, wenn man sie pullt

**Schritte zur Reproduzierung**
Man geht in den Burning Blade Coven, westlicher Gang, haut Mobs, Mobs rennen weg

**Comment by Dotox** [comment]
Entspricht nicht der Vorlage.

**Comment by krangerich** [comment]
Das Ticket entspricht der Vorlage. Die beiden weggelassenen Punkte sind zur Reproduktion und Behebung irrelevant. Wenn das doch relevant sein sollte, warum findet dann kein Triaging statt?

Aber da ich hier nicht der Bittsteller bin und es darum geht, durch QA euren Server zu verbessern, bleibt die Issue dann eben bestehen.

**Comment by Dotox** [comment]
Wenn ich dir sage, dass es nicht der Vorlage entspricht, dann ist es leider so.
