### ISSUE TITLE
Falsches Level Zwergbrandungskriecher

### ISSUE THREAD

**Issue by krangerich** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2518]
**Welches Verhalten wird beobachtet?**
Pygmy Surf Crawler (Zwergbrandungskriecher) haben das falsche Level. Diese Mobs laufen teilweise mit Level 1 herum (vermutlich wurde der fehlerhafte Eintrag aus ClassicDB übernommen, https://classicdb.ch/?npc=3106)

**Wie sollte es sich verhalten?**
Die Mobs sollten Level 5-6 haben. Jeder, der Classic gespielt hat, wird sich erinnern, dass man für Quest 818 (https://datenbank.classic-wow.org/?quest=818) keine grauen Mobs töten musste. 

Nachweis:
https://web.archive.org/web/20070522113833/http://www.thottbot.com/c3106
https://web.archive.org/web/20070522113833/http://www.thottbot.com:80/i4888

**Schritte zur Reproduzierung**
irrelevant

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
irrelevant

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=3106
https://datenbank.classic-wow.org/?quest=818

**Comment by Dotox** [comment]
Enthält Links zu anderen, nicht verifizierten Webseiten/Datenbanken.

**Comment by krangerich** [comment]
Natürlich müssen Links zu externen, historischen Quellen vorhanden sein, wenn man historischen Content rekonstruiert. Wie soll das denn sonst aussehen? "Die Mobs haben das falsche Level, aber ich darf nicht begründen, warum"? Die Issue ist hervorragend beschrieben, take it or leave it.

Was ist das bitte für eine unprofessionelle Vorgehensweise hier? Ich bin davon ausgegangen, dass man daran interessiert ist, die Qualität zu maximieren und hätte dementsprechend Zeit in QA investiert, aber wenn aus absurden Formalitäten heraus Issues nicht erwünscht sind, dann steigt die Qualität eben nicht.

**Comment by Dotox** [comment]
Ja, die Qualitätsprüfung beginnt schon beim melden eines Fehlers. Lass es einfach, wenns dir zu schwer ist.

**Comment by krangerich** [comment]
Ich unterstreiche nochmal: Bugreporter sind hier nicht die Bittsteller. Es geht hier nicht drum, irgendwie meine Wünsche zu erfüllen, denn es ist nicht mein Server und mir ist das persönlich komplett egal, ob da Sachen gefixt werden oder nicht. 
Ziel eines Bugtrackers ist, die Qualität einer Sache zu verbessern. Die Aufgabe von Personen wie dir ist zu gewährleisten, dass dieses Ziel bestmöglichst erreicht werden kann. An erster Stelle steht dabei, dass offene Bugs auch als Issue im System stehen, damit sie behoben werden können. Wenn irgendwelche Formalitäten relevant sein sollten, dann wird von unterschiedlichen Contributoren das Ticket editiert, damit alles "nice & tidy" ist. In der Open-Source-Szene wird das "Triaging" genannt.
Was aber völlig inakzeptabel ist, ist borniertes Verhalten und Polemik gegenüber Bugreportern. Das ist einfach unprofessionell, respektlos und nicht zieldienlich.

Unterm Strich siehts jetzt so aus: Ich hab keine Nachteile, ich bin als Externer unbetroffen. Bugs bleiben unreported / bestehen, zusätzliche zukünftige Bugreports fallen weg. Dafür bleibt dein persönlicher Stolz bewahrt. 
Klar, kann man so machen. Für den Betreiber des Bugtrackers ist das wohl eher ein schlechter Deal.

**Comment by Larnak1** [comment]
Ich glaube Dotox bezog sich auf die ClassicDB, die du auch als Herkunft der fehlerhaften Daten vermutest. Die gibt's erst seit 2018. Nutzt du zwar nur, um eine Theorie zur Herkunft zu entwickeln, aber wahrscheinlich hatte Dotox keine Lust, sich das dann im Detail anzusehen.

Zum Rest:
Die Entwickler haben hier mehr als genug zu tun, als Spieler sollten wir die Bugeinträge daher so schreiben, dass wir ihnen Arbeit abnehmen, statt zusätzliche Arbeit zu verursachen. Wenn Dotox sie für sich nicht hilfreich findet, macht er sie daher zu. Kann man doof finden, aber da der Tracker als Unterstützung für die Entwickler gedacht ist, ist es legitim, dass sie festlegen, was ihnen hilft und was nicht.
