### ISSUE TITLE
NPCs: Augenlose Behüter permanent sichtbar

### ISSUE THREAD

**Issue by treutz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2519]
Dieser Bug wurde bereits als gelöst markiert - scheinbar ist das Problem noch immer / wieder existent:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1146

Welches Verhalten wird beobachtet?
Die NPCs: https://datenbank.classic-wow.org/?npc=8539 sind permanent sichtbar. Eigentlich haben sie Stealth Rang 2 (auf Eurem Server angeblich nur Rang 1).

Wie sollte es sich verhalten?
Sie sollten permanent im Stealth bleiben, bis sich ein Spieler nähert und sie ihn angreifen. Dann sind sie sichtbar.

Schritte zur Reproduzierung:
Östliche Pestländer - oben bei den Toxin-Mobs stehen vier von ihnen rum, die permanent sichtbar sind.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Bild: https://www2.pic-upload.de/img/34977077/20180310-235740_WoWScrnShot_031018_235740.jpg
Link zu den Fähigkeiten der Mobs: https://classicdb.ch/?npc=8539#abilities

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Enthält Links zu anderen, nicht verifizierten Webseiten/Datenbanken.
