### ISSUE TITLE
[Naxxramas] Loatheb / Siegel des Lichts

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2520]
Erneuertes Ticket zu https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2191

Welches Verhalten wird beobachtet?
Loatheb nimmt sich Siegel des Lichts runter.

Wie sollte es sich verhalten?
Loatheb sollte sich Siegel des Lichts nicht runternehmen.

Schritte zur Reproduzierung
Loatheb pullen, Siegel des Lichts richten

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
It's important to have Judgement of Light or Poison Cleansing Totem active at all times since melee must save their consumables to recover damage taken from Inevitable Doom. http://wowwiki.wikia.com/wiki/Loatheb?oldid=388190

Testvideo: https://youtu.be/U_XSVPPPssE?t=3584
Im Testvideo sieht man sehr gut, dass das Siegel regelmäßig runterfliegt. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Loatheb https://datenbank.classic-wow.org/?npc=16011
Siegel des Lichts Rang 4 https://datenbank.classic-wow.org/?spell=20349

**Comment by EisenhowerSC** [comment]
Er reinigt es nicht nur sich selbst, sondern entfernt einen noch nicht gerichteten Licht Siegel auch vom Paladin

**Comment by Sheed90** [comment]
Im oben verlinkten WoW Wiki Eintrag steht außerdem, dass er sich nur alle Flüche entfernt. Nicht Magie.
"Decurse Every 30 seconds, starting at about 2 seconds in fight, Loatheb will remove all curses on himself."

Ich werde Omega mal zu dem Thema fragen, ggf. hat er noch etwas.

**Comment by Ychap** [comment]
Hier noch eine Quelle, wie es damals war: https://youtu.be/MW2uIvXVeb0?t=25

**Comment by Ychap** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2191

**Comment by EisenhowerSC** [comment]
Sehr gut zu sehen im Video. Er richtet es am Anfang und frischt es mit seinen meele Hits über den Gesamten Kampf auf.
Hier aufm Server muss ich es auf cooldown richten und trotzdem ist es kaum 50% oben.

**Comment by Sheed90** [comment]
Das Video von Ychap müsste eigentlich als Beweis dienen. Eine noch bessere Quelle wird schwer zu finden sein.

**Comment by Sheed90** [comment]
Hallo hallo? :)

**Comment by dagochen** [comment]
Manasiegel verschwindet ja nie von ihm....betrifft das nur das Richturteil des Lichts? Oder noch andere Debuffs?

**Comment by Sheed90** [comment]
Hallo Dago, soweit wir das beurteilen können, nur das Richturteil des Lichts. Das seltsame dabei ist aber, dass der Buff, Los Siegel des Lichts vom Paladin entfernt wird.
