### ISSUE TITLE
NPCs: Augenlose Behüter permanent sichtbar

### ISSUE THREAD

**Issue by SebbelBS** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2523]
Dieser Bug wurde bereits als gelöst markiert - scheinbar ist das Problem noch immer / wieder existent:
#1146

Welches Verhalten wird beobachtet?
Die NPCs: https://datenbank.classic-wow.org/?npc=8539 sind permanent sichtbar -- der NPC macht nicht von einer Fähigkeit Gebrauch.

Wie sollte es sich verhalten?
Sie sollten permanent im Stealth bleiben, bis sich ein Spieler nähert und sie ihn angreifen. Dann sind sie sichtbar.

Schritte zur Reproduzierung:
Östliche Pestländer - oben bei den Toxin-Mobs stehen vier von ihnen rum, die permanent sichtbar sind.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Bild: https://www2.pic-upload.de/img/34977077/20180310-235740_WoWScrnShot_031018_235740.jpg
Link zu den Fähigkeiten der Mobs: https://datenbank.classic-wow.org/?npc=8539#abilities

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Das andere waren https://datenbank.classic-wow.org/?npc=8538 diese Mobs hier. Das sind andere ;) Wurde also noch nicht gelöst. Aber ja ist quasi das gleiche Problem gewesen.
