### ISSUE TITLE
Grobbulus: Lua Fehler

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2524]
**Welches Verhalten wird beobachtet?**
Wenn man bei Grobbulus mit der Krankheit infiziert wird, erhält man folgende Fehlermeldung:
`Interface\FrameXML\ChatFrame.lua:1453: bad argument #3 to 'format' (string expected, got no value)`

**Wie sollte es sich verhalten?**
Man sollte keine Fehlermeldung erhalten.

**Schritte zur Reproduzierung**
Grobbulus pullen und warten bis man mit der Krankheit infiziert wird.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Da es sich um ein Blizzard-Standard-Addon handelt, habe ich mir einmal angesehen, was an [dieser Stelle](https://github.com/MOUZU/Blizzard-WoW-Interface/blob/d162a4c0d198a4381b5b6573d975635ed7316702/1.12.1/FrameXML/ChatFrame.lua#L1453) ausgeführt wird. Ich vermute dass es ein Boss-Emote geben sollte, welches einen vor der Krankheit warnt. Etwas weiter recherchiert finde ich im Stock-Mangos Core, dass tatsächlich ein solches [Emote ](https://github.com/cmangos/mangos-classic/blob/14a9304274b88df00454bdf89167184bcbf805da/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/naxxramas/boss_grobbulus.cpp#L38) generiert wird.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Grobbulus: https://datenbank.classic-wow.org/?npc=15931

**Comment by Dotox** [comment]
Ich bekomm die Error-Meldung nicht - die Meldung ist auch korrekt implementiert.

Erhalten das alle Spieler aus dem Raid? Auch wenn es eine klassische Fehlermeldung des Interfaces ist wird es wohl an irgendwelchen anderen Addons liegen.

**Comment by xorann** [comment]
Ob den Fehler alle Spieler erhalten haben, weiss ich nicht. Ich weiss aber dass ich nicht der einzige war. Vermutlich werden viele auch ein Addon installiert haben, welches Lua Fehler unterdrückt und es deswegen gar nicht merken.

Dass das ganze an einem Addon liegt, würde mich doch etwas verwundern, da die Fehlermeldung eigentlich ziemlich eindeutig ist. Im Emote scheint es (mindestens) zwei Platzhalter zu haben, aber es wird nur ein String geliefert um die Platzhalter zu füllen.
Pseudomässig reproduzieren kann man das Ganze mit folgendem Befehl:
`/run event="CHAT_MSG_RAID_BOSS_EMOTE"; arg1="%s and %s"; arg2="Grobbulus"; arg3=""; arg4=""; arg5=""; arg6=""; ChatFrame_OnEvent(event)`

Ich habe eine kleine Anpassung an einem Addon vorgenommen, so dass ich beim nächsten Mal etwas mehr Informationen erhalten sollte. Ich schau mir das ganze dann in der nächsten ID noch einmal an.

**Comment by xorann** [comment]
Heute leider kein einziges Mal die Krankheit abbekommen, nächste Woche vielleicht mehr Glück.

**Comment by xorann** [comment]
Darf man fragen weswegen dieses Ticket kommentarlos geschlossen wurde?

**Comment by Larnak1** [comment]
Xorann hat 3 Tage nach deiner Nachforderung mehr Input geliefert. Dass sich dann von eurer Seite 4 Monate niemand drum kümmert, kann man ja verstehen, aber das ist doch ein merkwürdiger Anlass, um diesen (und andere) Bug(s) zu schließen.
