### ISSUE TITLE
Gluth: Decimate

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2525]
**Welches Verhalten wird beobachtet?**
Nachdem Gluth Decimate gewirkt hat, greift er weiter den Tank an.

**Wie sollte es sich verhalten?**
Gluth sollte nachdem er Decimate gewirkt hat, für kurze Zeit niemanden angreifen, so dass man Zeit hat um die Tanks zu heilen.

**Schritte zur Reproduzierung**
Gluth angreifen und auf Decimate warten.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
In diesem Video kann man schön erkennen, wie Gluth für ca. 3s niemanden im Target hat und niemanden angreift: https://youtu.be/OXRaZX-vJVg?t=2m51s

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Gluth: https://datenbank.classic-wow.org/?npc=15932
Das hier ist vermutlich der Stun welcher auf Gluth gewirkt werden sollte: https://datenbank.classic-wow.org/?spell=28374

**Comment by Blame91** [comment]
Wann geht dieser Fix Online? Finde ihn sehr wichtig, da Gluth so wirklich zu nem Glücksspiel wird. Man wiped andauernd an Autoattacks direkt nach dem Decimate :( Buggy Boss 1 : Motivation 0

**Comment by Badorr** [comment]
Wenn man die Heiler einteilt, kann man das gut kompensieren. Der Fehler tritt ja auch scheinbar nicht immer auf, sonst hätten sicher mehr Gilden Probleme. Aber wurscht, Dotox hat den Fehler ja gefunden.

**Comment by Improlon** [comment]
https://legacyplayers.com/Raids/Viewer/?id=10121&exp=0

Who cares 10 Trys ^^ aber hast ja recht, Fehler ist gefunden und geht hoffentlich bald online

**Comment by Badorr** [comment]
Sehr investigativ von dir. Es soll ja tatsächlich noch andere Mechaniken geben, durch die man bei dem Boss wipen kann als die hier in dem Bug erwähnte ;>

**Comment by Dotox** [comment]
Ist seit dem 21.03 auf Nefarian
