### ISSUE TITLE
Noth der Seuchenfürst Enrage?!

### ISSUE THREAD

**Issue by Mirakoli123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2527]
Welches Verhalten wird beobachtet?
Nach der dritten Skelettphase portet sich Noth der Seuchenfürst in den Raum zurück wird rot und haut den Tank für 11000 Dmg, Lederträger bis zu 50000 Schaden
Wie sollte es sich verhalten?
Noth der Seuchenfürst sollte keinen Enrage in Vanilla haben
Schritte zur Reproduzierung
dritte Skelettphase überleben und warten bis er sich wieder in den Raum portet.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Mirakoli123** [comment]
http://wowwiki.wikia.com/wiki/Noth_the_Plaguebringer_(original)

Hier steht nichts von einem Enrage?

In Wotlk hat er einen Enrage siehe

http://wowwiki.wikia.com/wiki/Noth_the_Plaguebringer

**Comment by Mirakoli123** [comment]
https://www.twitch.tv/videos/238730057

Hier ausm Stream bei 3 Stunden und 28 Minuten zu sehen!

**Comment by Mirakoli123** [comment]
Ja, mit anderen Worten: Noth sollte in Classic WoW keinen Enrage haben.

Wir haben die Adds unter Kontrolle gebracht, Noth portet sich zurück in den Raum unser Tank tankt ihn an, bekommt aber einen One-Shot, weil Noth groß, böse und rot wird, sieht man auch im Video wie er einen Enrage-Effekt auf sich hat und tötet den gesamten Raid.

**Comment by Dotox** [comment]
Hätte während den PTR-Tests auffallen und gemeldet werden müssen. Wir hatten gemeinsam mehr als 1 Jahr Zeit, Naxxramas gemeinsam zu gestalten und zu entwickeln. Bitte habt Verständnis dafür, dass ich nach der Entwicklung (über den Zeitraum von mehr als 16 Monaten) erstmal eine Pause davon benötige und somit keine Anpassungen vornehmen möchte, sofern der Report des beschriebenen Fehlers nicht schwerwiegend (z. B. ein Fehler der eine ganze Mechanik aushebelt (wie bei Patchwerk)) ist.

**Comment by Denson87** [comment]
Naja ich finde bei einem Boss ohne Abhärtung ist sowas schwer auf dem PTR zu testen da man den Kampf ja dann beliebig lange in die Länge ziehen müsste um zu testen ob vllt irgendwann ein Enrage kommt der nicht kommen sollte....

**Comment by Dotox** [comment]
Ich seh anhand deine Aussage, dass du während den Tests auf dem Testserver nicht dabei warst. Es gab Tests bei denen Noth durchaus Abhärtung hatte UND auch in den Enrage ging.

**Comment by Mirakoli123** [comment]
Tut mir Leid Dotox, ich hab leider nicht aufm PTR getestet und verstehe auch, dass du eine Pause brauchst, ist ja vollkommen in Ordnung.
Aber wir hätten den Boss legen können, weil er nur noch 17% Leben hatte, den Raid aber nach der Balkonphase halt durch den Enrage zerstört hat. Somit ist es eine Mechanik die in den Kampf eingreift.

Lass dir von mir aus Zeit und gönn dir Ruhe von dem Stress, aber vergiss es bitte nicht, es zu bearbeiten.
Danke
