### ISSUE TITLE
Erhöhter Wutgewinn bei Critterschaden mit Priesterschild

### ISSUE THREAD

**Issue by Starsh1p** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2530]
Welches Verhalten wird beobachtet?
Wenn man von einem Critter (Eichhörnchen, Kuh, Rehkitz, Made, usw.) geschlagen wird und einen Priesterschild hat erhält man als Krieger beim ersten erhaltenen Schlag 100 Wut. Das passiert pro Critter scheinbar maximal 1-mal.

Wie sollte es sich verhalten?
Da ein Critter nur einen Schaden verursacht sollte der Wut-Gewinn maximal einstellig sein. Dieses Verhalten ist auch ohne Priesterschild zu beobachten.

Schritte zur Reproduzierung
z.B. mit Demoralisierungsruf einen Critter pullen und sich mit einem aktiven Priesterschild hauen lassen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Krieger Mensch Lvl 60, Priester Mensch Lvl 60. Video kann bei Bedarf bereitgestellt werden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=890

Grüße,
Starsh1p

**Comment by dagochen** [comment]
Critter sollten doch fliehen oder nicht?

**Comment by Sheed90** [comment]
Konnte ich nicht reproduzieren, hat bei uns nicht geklappt. Weder mit noch oder Priesterschild.

**Comment by Starsh1p** [comment]
In dem Video ist es noch einmal demonstriert: https://youtu.be/WgNQXSRadlk
