### ISSUE TITLE
Kein Aufbau von Magensäure bei CThun

### ISSUE THREAD

**Issue by Manixer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2531]
Welches Verhalten wird beobachtet?
Wenn C'Thun in seine Weakness-Phase gebracht wird, während man in der Animation zum Magen steckt,
wird man am Ende der Weakness-Phase automatisch in den Magen teleportiert und baut dort keine Stacks auf!

Wie sollte es sich verhalten?
Der Debuff sollte sich wie sonst auch hochstacken.

Schritte zur Reproduzierung
CThun in Phase bringen während man in den Magen teleportiert wird.
Weakness-Phase abwarten.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.twitch.tv/videos/239072037?t=02h31m14s
Habe es nicht sofort realisiert daher erst nach 2-3 Casts rausgegangen. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15727
https://datenbank.classic-wow.org/?spell=26476

**Comment by Jessienia** [comment]
Wurde schon mal reportet:
#1732
