### ISSUE TITLE
T3 Set-Bonus Hexenmeister

### ISSUE THREAD

**Issue by rockefaeller** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2532]
**Welches Verhalten wird beobachtet?**
"Eure Zauber 'Schattenblitz' erhalten eine Chance, Euch für 270 bis 330 zu heilen.
Dieser Proc funktioniert derzeit nicht.

**Wie sollte es sich verhalten?**
Dieser Proc sollte funktionieren. 
Die Procrate sollte zwischen 7-10% liegen (Einzige Quelle dazu die ich dazu gefunden habe: http://de.wowhead.com/spell=28831/blutsaugen#english-comments)

**Schritte zur Reproduzierung**
Einen Warlock mit 2 Teilen des T3-Sets ausstatten und Schattenblitze wirken.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Im Tooltip sollte bereits alles Relevante drin stehen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
https://datenbank.classic-wow.org/?itemset=529 T3 Hexenmeister
https://datenbank.classic-wow.org/?spell=28831 2er Set
https://datenbank.classic-wow.org/?spell=25307 Schattenblitz (Rang 10)

Grüße,
Rockyy

**Comment by Badorr** [comment]
Laut diesem Bugreport wurde das bereits gefixt, die Version ist aber bisher nur auf dem PTR aktiv(?)
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2311

**Comment by Ychap** [comment]
Der Proc funktioniert. Nur ist die Procrate sehr gering.

**Comment by rockefaeller** [comment]
Update:
Der Proc funktioniert wohl nur bei Gegner der Stufe 48+, ob dies so richtig ist kann ich keiner Quelle entnehmen.
Ansonsten funktioniert soweit alles soweit richtig!

Grüße,
Rockyy
