### ISSUE TITLE
Stitched Giant: Slime Bolt Interval

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2534]
**Welches Verhalten wird beobachtet?**
Stitched Giants (Trash vor Grobbulus) verwenden die Fähigkeit Slime Bolt alle 6s.

**Wie sollte es sich verhalten?**
Die Fähigkeit sollte nicht so häufig verwendet werden.

**Schritte zur Reproduzierung**
Stitched Giant pullen und am besten im Combatlog beobachten wann die Fähigkeit Slime Bolt verwendet wird (am besten wenn nur noch einer lebt, sonst sieht man auch noch jene der anderen Giants).

```
	Line 386590: 3/14 22:10:02.179  Stitched Giant begins to perform Slime Bolt.
	Line 386953: 3/14 22:10:08.296  Stitched Giant begins to perform Slime Bolt.
	Line 387319: 3/14 22:10:14.416  Stitched Giant begins to perform Slime Bolt.
	Line 387622: 3/14 22:10:19.866  Stitched Giant begins to perform Slime Bolt.
```

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
https://youtu.be/E3G2G0AbcE8?t=6m57s: In diesem Video erkennt man wie der hintere Giant bei 6:58 das erste mal Slime Bolt verwendet und erst bei 7:14 das nächste Mal. Das wären in diesem Fall 16s statt 6s.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Stitched Giant: https://datenbank.classic-wow.org/?npc=16025
Slime Bolt: https://datenbank.classic-wow.org/?spell=28311

**Comment by Dotox** [comment]
Das reicht leider (noch) nicht als Quelle. Blizzard hat gewiss bei vielen Fähigkeiten zufällige Intervalle verwendet. Ein Ausschnitt kann da nicht als Referenzwert gelten.

**Comment by Nifexx** [comment]
Und bei uns ist das Intervall deshalb bei festen 6 Sekunden? Das macht doch keinen Sinn. Die Mobs sind viel zu hart, weil sie einfach viel zu oft ihren Spit verwenden. Im Video ist halt klar ersichtlich, dass der Timer so nicht stimmen kann.

**Comment by Dotox** [comment]
Ja, dass hier was nicht stimmt ist mir klar und deshalb ist der Eintrag hier auch noch offen und nicht als "Kein Bug" deklariert. Liefere mehr Input (wie oben beschrieben) und die Labels des Eintrags werden entsprechend angepasst.

**Comment by Omegaexodus** [comment]
Das einzige was ich dazu noch gefunden habe, waren folgende Quellenn (Webarchiv hat bei Thottbot hat die Fähigkeit nicht getrackt):

https://web.archive.org/web/20071124002224/http://www.wowhead.com:80/?spell=28311

https://web.archive.org/web/20070218131831/http://www.wowwiki.com:80/Slime_Bolt

Leider gibt es auch dort keine fundierten Beweise darüber, wie lang nun der interne Cooldown der Fähigkeit war. Man könnte nur darüber argumentieren, das der Cooldwon wohl bei über 10 Sekunden gelegen haben muss (oder zumindest genau 10 + 2,5 sec Casttime), da die Fähigkeit (Debuff) vorher wieder ausgelaufen sein muss, bevor man einen weiteren Stack erhalten hat. 

Das Indiz für diese Theorie ist in allen "Kampf-Beschreibungen" zu dem Stitched Spewer zu finden. ---> Keine Erwähnung von zu hohem Poison.-Schaden / Naturressi Notwendigkeit oder Outrangen, wegen Heal.

Lg Omega

**Comment by xorann** [comment]
Darf man fragen weswegen dieses Ticket kommentarlos geschlossen wurde?
