### ISSUE TITLE
Felspirscher in Silithus irrtümlich elite

### ISSUE THREAD

**Issue by treutz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2538]
Welches Verhalten wird beobachtet?
Die kleinen Spinnen in Silithus ("Felspirscher": https://datenbank.classic-wow.org/?npc=11739 ) sind hier elite und deren stapelndes Gift ist richtig, richtig tödlich. Zu Classic waren sie nicht elite und haben bei Weitem nicht so viel Dmg. gemacht.

Wie sollte es sich verhalten?
Sie sollten nicht elite sein und deren Gift sollte dementsprechend ebenfalls abgeschwächt werden.

Schritte zur Reproduzierung:
- Schaut Euch die Mobs an...

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Screenshot: http://fs1.directupload.net/images/180317/ot4d6liz.jpg vom 31.05.2006

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by treutz** [comment]
Und so schauts auf Nefarian aus: http://fs1.directupload.net/images/180317/78lc9uui.jpg

**Comment by Simit90** [comment]
https://wow.gamepedia.com/Rock_Stalker
The Burning Crusade Patch 2.3.0 (2007-11-13): No longer Elite. 

Bis Patch 2.3.0 waren sie Elite, ka woher du das Screenshioben hast, aber kann da auch keinen Zeitnachweis erkennen.

**Comment by treutz** [comment]
1. Den Screenshot habe ich am 31.05.2006 selbst gemacht
2. Dein Link verweise auf einen WIKI-Eintrag, den jeder faken kann wie er will -- indem Fall klick bitte unten mal auf die 2.3.0er Patchnotes und such nach Rock Stalker: Du wirst keinerlei Info dazu finden, weil es in keinem Changelog stand - WEIL ES NIE GEÄNDERT WURDE!
3. In der classic-WOW.org-Datenbank steht der Mob als "normal" -- also *nicht* elite. 

"Simit90", 3x "fälschlich" als Bug gemeldet? Wach mal auf!

**Comment by treutz** [comment]
Weiterer Link: https://web.archive.org/web/20070702092251/http://www.thottbot.com:80/c11739

**Comment by treutz** [comment]
So wie es ausschaut, hat Blizz, mit Patch 1.12.x oder 2.x die NPCs zu Elite upgegradet und zu später wieder downgraded.
Link: https://web.archive.org/web/20060619042713/http://www.thottbot.com:80/?pet=Spider
Wenn man oben auf den -> Button geht, kann man das ganz gut erkennen. 
Dass die Elite ware, war wohl nur ne kurze Zeit und wohl auch nur ein Versehen von Blizz, weil es auch in keinen Patchnotes drin steht.

**Comment by treutz** [comment]
https://web.archive.org/web/20070409144249/http://www.thottbot.com:80/i12205 - am 09.04.2007 waren sie ebenfalls nicht elite.

**Comment by dagochen** [comment]
```
Many elite creatures and quests in the level 1-60 experience have been changed 
to accommodate solo play.
```
Ich vermute mal das auf Grund dieser Änderung in Patch 2.3 ist der fehlerhafte Eintrag im wowwiki entstanden.

**Comment by Haudraufinix** [comment]
Gerade kurz getestet. Innerhalb der Zeitspanne von 5 Autohits 4 Stacks Spinnengift für ein Total von 4008 Schaden kassiert. Die sind immer noch absolut tödlich, aber die werte entspechen ansonsten non Elite mobs


![spinnengift](https://user-images.githubusercontent.com/11026311/39062657-7f388fee-44c8-11e8-8bf2-147ba1aa5fe4.jpg)

**Comment by dagochen** [comment]
Mein Fehler, hab die Spell-ID nicht korrigiert, die ist immer noch im "Elite-Modus" :(
