### ISSUE TITLE
Flickwerk Hasserfüllter Stoss

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2540]
Welches Verhalten wird beobachtet?
Hasserfüllter Stoss folgt der Wrath of the Lichking Mechanik, nach der Flickwerk lediglich die Ziele mit den meisten Leben mit Hasserfüllten Stössen trifft. Ausserdem besitzt er einen Fixen CD für seine Hateful Strikes

Wie sollte es sich verhalten?
Patchwork sollte zu Pull eine Liste mit potentiellen Zielen für Hasserfüllter Stoss erstellen. Diese Liste wird befüllt mit den 3 Patchwerk am nächsten stehenden Spielern, mit Ausname des Aggrohalters beim Pull (dem Maintank). Nur innerhalb dieser Liste wält er das Ziel mit den meisten Leben für Hasserfüllter Stoss aus.
Sollte eines der drei Ziele sterben, beinhaltet diese Liste nur noch 2 Ziele. usw. Es ist nur möglich eine neue Liste für 3 Ziele von Hasserfüllten Stössen zu generieren, wenn er den Maintank aus seinem Ziel verliert (Durch Aggroverlust oder durch Tod).

Befindet sich keines der drei Ziele auf der Liste für Hasserfüllten Stösse, so gehen alle Hasserfüllten Stösse auf sein aktuelles Ziel. Nur wenn dieses auch nicht erreichbar ist, dann Trifft er übrige Ziele in seiner Nahkampfreichweite

Ausserdem Sollte Hasserfüllter Stoss nicht alle 1.2 Sekunden eintreten, sondern zufällig zwischen 0.8 und 1.5 Sekunden delay haben.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Bild aus dem Offiziellen Dungeon Companion Volume 2 von Brandygames
ISBN 978-3-8272-9146-2
![patchwerkguide](https://user-images.githubusercontent.com/11026311/37571875-e95bf684-2b02-11e8-825d-28bb32f145c4.jpg)
Zu beachten: 
Beim Beschrieb von Flickwerks Fähigkeiten wird auf das 2. oder 3. Ziel in seiner Bedrohungsleiste verwiesen. Da der Taktikteil ausführlich ein anderes Verhalten beschreibt tippe ich darauf, das es sich hierbei um einen Übersetzungsfehler der deutschen Version handelt.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Flickwerk: https://datenbank.classic-wow.org/?npc=16028
Hasserfüllter Stoss: https://datenbank.classic-wow.org/?spell=28308
https://datenbank.classic-wow.org/?spell=28307

**Comment by rachmin** [comment]
Gesichert sein dürfte, dass der Hateful-Strike-Swingtimer bei 1,2 Sekunden liegt. Anfänglich schien er wohl bei 1.5 bis 2 Sekunden zu liegen (siehe Quelle 4; außerdem in Quelle 3 einfach mal im Datum zurückspringen, deckt sich mit dem Inhalt des ältesten WoWHead-Kommentar im Patchwerk-Kommentar der 2. Quelle).
Quelle 1: Addon "Patchwerk Hateful strike heale" (Okt 2006), https://wow.curseforge.com/projects/project-3126
"You must use 3 offtanks. [...] We will have 3.6 seconds to land the heal [auf dem jeweiligen Hateful-Tank]."
Quelle 2: WoWHead Kommentar Dez 2012, http://www.wowhead.com/npc=16028/patchwerk#comments:id=12907
Hateful Strike habe "1.25 second attack speed" und "it hits approximately every 1.2 seconds using the mechanic described above"
Quelle 3: Patchwerk-Guide (Feb 2007),https://web.archive.org/web/20070216223757/http://www.wow-tactics.de:80/20_taktiken/naxx/patchwerk.php
"Der Hateful Strike kommt alle 1.2 Sekunden auf das Ziel mit den meisten HP ..."

Was die Bedohrohungsliste-Mechanik angeht, so kann es stimmen oder auch eine falsche Beobachtung bzw. falsche Schlussfolgerung gewesen sein.
Vgl. Quelle, die im Sinne der Bedrohungslisten-Mechanik spricht: https://web.archive.org/web/20090316055529/http://www.tentonhammer.com/node/26644 ("When you are confident that the main tank has aggro (couple of sunders should do it) and the hateful strike rotation is set (he'll only hateful strike 3 people and will only hit the one with the most HP), send in the entire raid and begin DPS.")
Vgl. Quelle, die (im "Vorwort") dagegen spricht: https://web.archive.org/web/20070216223757/http://www.wow-tactics.de:80/20_taktiken/naxx/patchwerk.php (ähnl. Quelle 4: "Therefore the MT has unlimited Rage he can use to build a lot of aggro (which he has to).")

Was den "Hateful Strike Primer" angeht, so wird es komplizierter.
Einerseits müsste es bedeuten: ich greife mit meinem Hateful immer das Target in meiner Nähe an, dass die höchsten HP und Aggro auf mir aufgebaut hat. Wir wollen, dass dies ein Offtank ist, der den Schlag potentiell überlebt, weil es ansonsten alle anderen Melees zermatscht und den Kill unmöglich macht.
Das deckt sich mit folgenden Aussagen:
WoWHead-Tooltip zum"Hateful Strike Primer", http://www.wowhead.com/spell=28308/ : "Deals 21972 to 29728 damage to a threatening target with the highest health within melee range.",
Quelle 4: Naxxramas - Abnomination: Patchwerk (Nov 2006), https://web.archive.org/web/20071106055546/http://www.anikki.com:80/do/viewtopic.php?t=1507
"Hateful Strike: "Physical" (doesnt register as melee or spell though --> no procs) hit every 2 seconds on the target with the most HP in melee range. 22k-33k on naked, 7k on full Wrath+extras. Stays on the same target until he hits at least once." (Meint: Hateful will immer den mit meisten HP treffen; trifft er das Target nicht (weil pariert/ausgewichen), dann wird er es im nächsten Schwung nochmal versuchen usw.)
Quelle 5: https://wow.gamepedia.com/Patchwerk_(original)).
"Hateful Strike hits the person in range with the most hitpoints primed by aggro. (It will hit a rogue if your Tanks arent healed up fast enough)"

Anderseits - wenn man sich die Classic Videos anschaut - gingen bei vielen Videos die Melees äußerst selten in die Suppe. Wahrscheinlich, weil alle mit der 2 Hateful-Offtanks + 1 Ersatz Hateful-Tank spielten und wir meist nur verpixelte Videos von Kills haben, bei dem die Mechanik einfach funktioniert, wie man es kennt/will, ohne zu wissen, wie sie "wirklich" funktioniert.

Lange Rede, kurzer Sinn:
Der Swingtimer für den Hateful sollte so richtig sein.
Die Hateful-Mechanik scheint - je nach Quelle/Wissensstand - noch nicht perfekt (= zweifelsfrei recherchiert) zu sein.

**Comment by Badorr** [comment]
Unabhängig davon, welche Forenposts dafür oder dagegen sprechen, ist das ein von Blizzard offiziell lizenzierter Guide. Man kann schon davon ausgehen, dass die dort veröffentlichen Informationen weniger auf 'falschen Beobachtungen oder Schlussfolgerungen' basieren, sondern eher auf Premium-Insider-Infos.

**Comment by Dotox** [comment]
Da muss ich dir widersprechen. Während der PTR-Phase gab es immer wieder Momente, in denen ich oder wir feststellen mussten, dass die beschriebenen Dinge in dem Buch nicht stimmen können. Widerlegt wurde das durch verschiedene Guids aus dem Internet UND Videos von damals.

**Comment by Dotox** [comment]
Hab mir das gerade nochmal durchgelesen. Da steht doch eindeutig: "Der erste hasserfüllte Stoß trifft den Off Tank mit der höchsten aktuellen Gesundheit". Außerdem steht da auch noch: "Wenn ihre Heiler sehr schnell sind, kann es sein, dass Hasserfüllter Stoß dieselbe Person zweimal hintereinander trifft" was überhaupt keinen Sinn ergeben würde, wenn beim Pull doch eine feste Reihenfolge erstellt werden würde.

**Comment by Haudraufinix** [comment]
Ich würde dich bitten, das ganze nochmal durchzulesen.
Es kann in der Tat vorkommen, das der selbe Tank mehrfach getroffen wird. Denn innerhalb seiner 3 Platz Liste zielt Flickwerk tatsächlich auch auf das Ziel mit dem meisten Leben. Jedoch nur innerhalb dieser 3 Ziele.
Alle Guides die sich zu Patchwerk finden sprechen immer von genau 3 Hateful Tanks. Wenn es nur nach Max HP gehen würde, dann hätte bestimmt irgend eine Gilde weltweit 4 oder mehr Tanks rangestellt, um die Healer zu entlasten (Bzw würden Off Warrys Schildwall + Last Stand ziehen um kurzzeitig die benötigte Heilung massiv abzubremsen.)

Das in dem Guide beschriebene Verhalten ist unter anderem auch der Grund dafür, wieso ebenfalls keine Patchwerkvideos existieren wo melees spontan umfallen. Schlicht weil es gar nicht passieren konnte. Ebenfalls ist es mit der 3 Platz prio nicht möglich tote Tanks durch Battlerezz oder durch einen Bärendruiden der vorher als Katze schaden gemacht hat zu ersetzen.

Ums mal an einem kleinen Beispiel zu erläutern:

Verhalten bei uns:
1 Maintank, 3 Hateful-Tanks 10 Melees am Boss
1. Hateful trifft den 1. Offtank. Dieser droppt auf 10%
2. Hateful trifft den 2. Offtank (Weil er jetzt die meisten leben hat) Dieser droppt auf 10%
Healer heilen den 1. Tank voll. 3. Hateful trifft wieder den 1. Offtank (Der nun wieder die meisten Lebenspunkte hat) Dieser droppt dabei ebenfalls auf 10%
4. Hateful trifft den 3. Tank, da Tank und haut ihn auch auf 10%
Sofern nun keine Heilung auf die 3 Tanks kommt trifft der 5. Hateful einen Melee DD der am Boss steht und tötet diesen.

Sollverhalten:
1 Maintank, 3 Hateful-Tanks 10 Melees am Boss
1. Hateful trifft den 1. Offtank. Dieser droppt auf 10%
2. Hateful trifft den 2. Offtank (Weil er jetzt die meisten leben hat) Dieser droppt auf 10%
Healer heilen den 1. Tank voll. 3. Hateful trifft wieder den 1. Offtank (Der nun wieder die meisten Lebenspunkte hat) Dieser droppt dabei ebenfalls auf 10%
4. Hateful trifft den 3. Tank, da Tank und haut ihn auch auf 10%
Sofern nun keine Heilung auf die 3 Tanks kommt trifft der 5. Hateful denjenigen der 3 Hateful Ziele der noch am meisten Leben hat und tötet diesen.

Sofern ein Ziel von seiner Hasserfüllten Soss Liste verschwindet bleibt es auch draussen. Selbst wenn der Tote Tank gerezzt und vollgehealt werden würde, Nur die anderen beiden würden noch von Hasserfülltem Stoss getroffen werden.

**Comment by drakkart** [comment]
Würde das nicht bedeuten, dass wenn man beim Pull mit den HS-Tanks mit dran geht, die ihren Platz auf der Liste bekommen und anschließend wieder außer Reichweite gehen, niemand überhaupt die HS abbekommt? Das kann doch so nicht gewollt sein, oder?

**Comment by Larnak1** [comment]
Dann bekäme sie der MT ab.
