### ISSUE TITLE
[Naxxramas] Unheilgeplagter Krieger macht zu viel Schaden

### ISSUE THREAD

**Issue by Heri7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2541]
Welches Verhalten wird beobachtet?
Unheilgeplagter Krieger macht zu viel Schaden. Aktuell bis zu 4000 Schaden gegen Stoffrüstung (kein crit). In Kombination mit ihrem Aggro Reste sind diese Gegner dadurch sehr tödlich für alle nicht Tanks im Raid.

Wie sollte es sich verhalten?
Unheilgeplagter Krieger sollte gegen Stoffrüstung ca. 2000 Schaden machen.

Schritte zur Reproduzierung
Nach Naxxramas gehen und gegen einen Unheilgeplagter Krieger im Todesritter Flügel kämpfen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://youtu.be/y3PUGYve2E4?t=3m55s
In der Datenbank scheint ein passender Schaden eingetragen zu sein (1,609 - 1,854).

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=16157 Unheilgeplagter Krieger

**Comment by Dotox** [comment]
Erhöhter Schaden in Naxxramas ist gewollt und wurde seit dem PTR auch nicht mehr verändert; Meldungen hätten während der PTR-Phase erstellt werden müssen. Ich werde hier nachträglich nichts mehr anpassen.
