### ISSUE TITLE
NPC: Staubstürmer / Duststormer zu schnell

### ISSUE THREAD

**Issue by treutz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2544]
Welches Verhalten wird beobachtet?
Der Staubstürmer / Duststormer in Silithus patroulliert wie gestört durchs nordwestliche Silithus.

Wie sollte es sich verhalten?
Er sollte bei seinem Felsen bleiben und nicht mit einer derartig schnellen Geschwindigkeit durch Silithus peesen.

Schritte zur Reproduzierung
Schaut Euch mal den NPC an - Position etwa 20,30 in Silithus

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Das sieht etwa so aus: https://www.youtube.com/watch?v=iCNKlMMv5fY

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=11744

**Comment by Dotox** [comment]
Wird ein einmaliger Fehler gewesen sein, denn ich kann das aus dem Video nicht feststellen.
