### ISSUE TITLE
Mage: T3 4er Bonus buggy

### ISSUE THREAD

**Issue by Waffl87** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2545]
Welches Verhalten wird beobachtet?

Heilig/Arkan/Natur und Frotschaden lösen den 4er Bonus vom Mage T3 Set nicht richtig aus!
Getestet hab ich es mehrfach in Duellen gegen Priest mit folgenden Casts:
- Göttlicher Pein Rang1
- Heiliges Feuer Rang 1
(Gedankenschlag Rang1 hingegen hat den 4er Bonus ausgelöst)
Unter anderem auch mehrfach in Duellen gegen Hunter getestet mit folgenden Casts:
- Schlangengift Rang1
- Arkaner Schuss Rang 1
Auch gegen Mage hab ich es getestet mit folgenden Casts:
- Frostbolt Rang1 löst den 4er richtig aus
- Blizzard Rang1 löst den 4er Bonus jedoch nicht aus
(Getestet hab ich den Bonus auch bei Sapphiron, die Aura löst den Bonus leider auch nicht aus)

Wie sollte es sich verhalten?

Wie auch bei Feuerball Rang1 und Flammenstoß Rang1 sollte der 4er Bonus auch bei den oben aufgeführten Spells ausgelöst werden, siehe Tooltip

Server Version 1.8.4

Ps: Wollte noch anmerken, dass das Arkanschild (ausgelöst durch den 4er Bonus^^) das einzige mit einer 30 sekündigen Animation ist, alle anderen Resischilder haben nur eine ca. 3 sekündige Animation

Arkanschild:
https://imgur.com/a/fSB5n

Wäre Hammer wenn alle anderen Schilder auch eine 30 sekündige Animation hätten, aber ob das Classic like ist oder eben nicht...leider keine Quelle gefunden:(

**Comment by dagochen** [comment]
Quellen und Verlinkung an sich wär schon hilfreich....

**Comment by Haudraufinix** [comment]
http://www.wowhead.com/spell=28764/adaptive-warding#comments
"This seems to proc about 30% of the time. On fights like Firemaw it's up all the time. Unfortunately it does NOT proc off saphiron's frost aura :(."

Firemaw und Sapphiron haben ja ähnliche Auren. das sollt da wohl dann schonmal proccen.

Arkaner Schuss sowie Schlangenbiss verursachen zwar Arkan- bzw Naturschaden, sind aber Sonderfälle, da sie wie normale Schüsse behandelt werden (können Geblockt werden oder verfehlen). Daher würd ich empfehlen das mit einem Druiden zu testen.

**Comment by Tweet1337** [comment]
Die Procc-Chance scheint auch buggy und viel viel niedriger zu sein als die 30% aus dem WoW-Head-Kommentar! Hatte es vorletzten Montag getestet, hatte den Buff nur 2x oben - "Pech" mit den Proccs ist bei der Anzahl an Flame Buffets, die man bekommt, ausgeschlossen :|

**Comment by Dotox** [comment]
Also ich weiß nicht so recht, ist alles etwas schleierhaft. hab mal etwas an der Abfrage geändert, kann auf dem PTR getestet werden.
