### ISSUE TITLE
Elixier des Giftwiderstandes = Trank der Genesung

### ISSUE THREAD

**Issue by Mixuspidelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2546]
Welches Verhalten wird beobachtet?
Das *Elixier des Giftwiderstands* wird als *Rezept:/ Trank der Genesung* ausgezeichnet (siehe Bilder).

Wie sollte es sich verhalten?
Laut https://datenbank.classic-wow.org/?item=3394 sollte im Tooltip Rezept: Elixier des Giftwiderstands stehen (siehe Bilder).

Schritte zur Reproduzierung
Rezept von Npc´s finden oder aber im Ah schauen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://www.bilder-upload.eu/show.php?file=64198c-1521827486.jpg
http://www.bilder-upload.eu/show.php?file=c1a3fe-1521827500.jpg

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=3394
https://datenbank.classic-wow.org/?spell=3182
https://datenbank.classic-wow.org/?spell=3174
https://datenbank.classic-wow.org/?item=3386

**Comment by Dotox** [comment]
WDB leeren
