### ISSUE TITLE
Trash vor Instructor Razuvious

### ISSUE THREAD

**Issue by Cuanoco** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2551]
Welches Verhalten wird beobachtet?

Der Trash vor Instructor Razuvious respawnt auch nach Tötung des Bosses komplett (incl. seiner 4 Trainees)

Wie sollte es sich verhalten?

Kein Respawn nach Bosskill. In den anderen Wings funktioniert es entsprechend.

Schritte zur Reproduzierung

Mehrmaliges Töten von Instructor Razuvious über mehrer ID's, neues betreten der Instanz an einem anderen Tag um bei Gotic weiter zu spielen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://classicdb.ch/?npc=16061
https://datenbank.classic-wow.org/?npc=16154
https://datenbank.classic-wow.org/?npc=16452#drop
https://datenbank.classic-wow.org/?npc=16451
+ noch 2-3 Mobarten die ich leider grade nicht finde.

**Comment by Ulva-Anorhin** [comment]
Nicht ganz
Wir hatten noth und Heigan down und 4 Tage später stand der komplette trash wieder im Wing. 

Ein gm meinte nur das dieses trash respawn Problem schon häufiger passiert ist.

**Comment by Koringar** [comment]
Doppelpost

#2505

**Comment by Ulva-Anorhin** [comment]
ID 2 auch wieder Trash respawn nachdem Razu down ist

**Comment by Ulva-Anorhin** [comment]
ID 13
Trash zu Noth respawnt obwohl Noth und Heigan liegen

**Comment by Sheed90** [comment]
Razu Trash kann SC bestätigen, der respawn scheint recht willkürlich zu sein. Mal gespannt viel, mal wenig. Noth Trash respawn hatten wir noch nicht

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2505
