### ISSUE TITLE
Bestie Kürschnern

### ISSUE THREAD

**Issue by Masterglow** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2554]
Welches Verhalten wird beobachtet?
Lässt sich nicht kürschnern, weder mit 315 noch mit 320, kein Loot drinnen, mehrfach passiert. nach dem alle gelootet haben!
Wie sollte es sich verhalten?
Man sollte nach der Lootvergabe einfach die Bestie wie alle anderen Mobs Kürschnern können! nach dem alle gelootet haben!
Schritte zur Reproduzierung
Bestie legen, man kann nicht kürschnern^^ nach dem alle gelootet haben!
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
<a href="http://www.bilder-upload.eu/show.php?file=905fea-1522409057.jpg" target="_blank"><img src="http://www.bilder-upload.eu/thumb/905fea-1522409057.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=19901
https://datenbank.classic-wow.org/?npc=10430

**Comment by Ulva-Anorhin** [comment]
Es liegt daran weil ein Spieler noch die klauen raus looten muss. Erst danach kann man die Bestie Kürschnern.

**Comment by Donf4b** [comment]
https://datenbank.classic-wow.org/?item=8146

**Comment by dagochen** [comment]
Also kein Bug?

**Comment by Jessienia** [comment]
In dem Screenshot steht aber kürschnerbar im Tooltip. Das erscheint doch erst, wenn der Mob vollständig gelootet ist.
Außerdem kann im Raid jeder das weiße Zeugs rausnehmen. Also eher unwahrscheinlich, dass es daran liegt.
