### ISSUE TITLE
Schurke - Verlust der Combopunkte auf dem aktuellen Ziel

### ISSUE THREAD

**Issue by Filbert1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2555]
Welches Verhalten wird beobachtet?
Ich verliere seit ca. 4 Wochen ständig (unregelmäßig) meine Combopunkte auf dem akutellen Ziel. Sie "verschwinden" einfach. Bei manchen Bossen fast gar nicht, bei anderen sind sie weg, noch ehe der global CD des Sinister durch ist. Besonders oft verschwinden Sie, wenn man gefeart wird (Ony, Taerar etc)
Wie sollte es sich verhalten?
Combopunkte sollten nur verschwinden, wenn man das Ziel wechselt oder sie verbraucht.
Schritte zur Reproduzierung
Ich habe den Schurken bereits viele Wochen gespielt und nichts verändert (da der Server ja immer auf dem selben Stand bleibt und daher keine aktualisierungen notwendig sind)
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Mensch Schurke. Habe einen Kollegen, der selbiges Phänomen hat (Nachtelf Schurke). Ist zuerst im PvP aufgetreten und danach auch im PvE, wobei es im PvE wesentlich öfter erkennbar ist, da man im PvP nicht so oft dazu kommt auf ein Ziel durchzuziehen.
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Vermutlich ein Addon, dass die Ziele / Spieler durchklickt um Buffs und HP und co zu überprüfen?

**Comment by Filbert1** [comment]
Wenn dann "im Hintergrund", bzw. ohne meine Kenntnis. Kannst du da Beispiele benennen? Ich hatte erst das Addon "ArcHud" in Verdacht und nachdem ich das abgeschaltet hatte ging es auch für ein paar Stunden wieder. (oder es schien zumindest so)

**Comment by dagochen** [comment]
Gibt zahlreiche Addons die sowas verursachen. Zumeist versuchen diese durch verschiedene Interaktionsreichweiten die Entfernungen zu berechnen. Sprich das Addon nimmt wen ins Target und schaut ob es z. B. Handeln oder Betrachten kann (um dann zu wissen, dass der Spieler mindestens x und maximal y Meter weit weg ist) ....und wählt dann wieder dein eigentliches Ziel an. Dadurch gehen deine Combopunkte dann verloren. War leider in Classic so und ist auch kein Bug ;) Die Addons sind meist von irgendwelchen Leuten aus der heutigen Zeit programmiert worden und auf vielen Servern funktioniert diese Mechanik leider nicht, wodurch es sonst mit den Addons keine Probleme gibt, bei uns aber schon.
