### ISSUE TITLE
[Ingenieurskunst] Das Pet "Arkanitdrachling" castet keinen Flame-Buffet auf Gegner

### ISSUE THREAD

**Issue by JoyyNefarian** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2556]
**Welches Verhalten wird beobachtet?**
Nach dem Beschwören benutzt das Pet ledigilich Autoattacks.

**Wie sollte es sich verhalten?**
Der Arkanitdrachling sollte von Zeit zu Zeit den Zauber "Flammenatem" benutzen, der ca. 300 Schaden verursacht und den Debuff "Flammenpuffer" auf das Ziel castet. Flammenpuffer erhöht den zugefügten Feuerschaden um bis zu 60 und ist 3x stackbar.

**Schritte zur Reproduzierung**
Pet bauen, benutzen und Mobs angreifen. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
http://classicdb.ch/?item=16022#comments
Deals about 70 damage to a level 60 mob, 2.0 attack speed. Also occasionaly breathes fire, which deals 300 damage and makes fire spells on that mob do up to 60 extra damage. This ability stacks with itself, but I've never seen it breathe more then twice in one outing. Debuff lasts about 30 seconds. Very little health.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=16022

**Comment by dagochen** [comment]
Es gibt keinen Feuerzauber der 300 Schaden macht und den erlittenen Schaden um 60 erhöht. Vielleicht kann jemand hier noch mehr Details zu dem Zauber finden?
