### ISSUE TITLE
Buffstacking

### ISSUE THREAD

**Issue by Dovarion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2558]
Welches Verhalten wird beobachtet?
Grüner Gordokgrog und Kreegs Hauweg Starkbier stacken.

Wie sollte es sich verhalten?
Da es Buffs der selben Kategorie(Alkohol) sind, sollten sie nicht stacken.

Schritte zur Reproduzierung
Düsterbruch "Tribut Run" machen und bei Stampfer Kreeg beide items kaufen und anschließend trinken.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
/

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=18284
https://datenbank.classic-wow.org/?item=18269

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1482
