### ISSUE TITLE
Zauber "Arkane Geschosse" funktioniert nicht korrekt

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#256]
Fehlverhalten:
Beim Wirken von Arkane Geschosse kommt es vor, dass zwar kanalisiert wird, aber keine Geschosse auf den Gegner fliegen und dieser auch keinen Schaden erleidet. Die Art des Gegner spielt dabei keine Rolle.

Wie sollte es sein:
Je nach Stufe des Spells sollten während des Kanalisierens mehrere Arkane Geschosse den Gegner treffen und Schaden zufügen.

Reproduktion des Fehlers:
Arkane Geschosse casten

**Comment by Ataraia** [comment]
Hier nochmal zusätzlich ein Problem, das in Instanzen geschieht:

Casten mehrere Magier Arkane Geschosse, werden ALLE abgebrochen. Wir haben festgestellt, dass immer nur ein Magier Arkane Geschosse casten kann. Beispielsweise wird bei den arkananfälligen Mobs in BWL ein Magier eingeteilt, Geschosse zu casten, während alle anderen Arkane Explosion spammen.
Es sollten jedoch alle Magier uneingeschränkt Arkane Geschosse casten können. Hier ein Video, das das mehr als beweisen sollte.

https://www.youtube.com/watch?v=G8LZU9l6mtM

Ab Phase 2 sieht man deutlich, dass die Mages gleichzeitig Geschosse casten.

mfg Ata
