### ISSUE TITLE
Hunter t3 4er Bonus

### ISSUE THREAD

**Issue by Donf4b** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2562]
Welches Verhalten wird beobachtet?
Der AP Bonus des 4er Sets hält nur 3 Sekunden lang, wobei es in der Regel kurz vor Ablauf resetted, vorrausgesetzt der Begleiter ist noch aktiv. Trotzdem kann es dadurch passieren, dass der Buff für ganz kurze Zeit komplett ausläuft.

Wie sollte es sich verhalten?
Der 4er Bonus Buff sollte ein dauerhafter, passiver Buff sein, ohne Ablaufzeit.

Schritte zur Reproduzierung
4er Bonus ausrüsten, Begleiter rufen, am besten in den Einstellungen Auras, und nachlassende auras anzeigen lassen und auf die Anzeige warten, dass die aura nachlässt.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.youtube.com/watch?v=n-dDNBpvL8w
ab 4:30 Minuten auf die Buffleiste achten.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Laut Datenbank steht die Dauer auf 4Sekunden
[Pirschers Freund](https://datenbank.classic-wow.org/?spell=28757)

**Comment by dagochen** [comment]
Dauer: 4 Sekunden
Die steht halt in dem Buff so drin, dass ist also schon so richtig das die ausläuft, wenn Pet und Jäger zu weit auseinander sind oder das Set gewechselt wird....

**Comment by Donf4b** [comment]
man sieht doch in dem video eindeutig keine Zeit beim buff laufen. ich denke das wird sich genau so verhalten wie bsp aspekt des rudels für teammitglieder. die kriegen ja auch nicht angezeigt, dass rudel in 4 sekunden ausläuft, sondern solange hält wie man in reichweite ist.

**Comment by dagochen** [comment]
Da steht 4 Sekunden und deshalb dauert der Buff genau 4 Sekunden. Von uns hat sich das keiner ausgedacht das da ne 4 steht. Er wird alle 3 Sekunden erneuert und hält dann 4 Sekunden. Wenn es tatsächlich mal passiert, dass es ausläuft, ist das nur durch Reichweite oder extreme Lags, die client- und serverseitig auftreten, erklärbar. Da können wir rein garnix tun.
