### ISSUE TITLE
Naxxramas Wing Teleporter am Ende

### ISSUE THREAD

**Issue by Ulva-Anorhin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2564]
Welches Verhalten wird beobachtet?
3 Tage nachdem clear des Seuchenwings (Loatheb) funktioniert der Teleporter am Ende nicht mehr,
Wie sollte es sich verhalten?
Auch wenn der Kill vom Boss am ende eines Wings schon mehrere Tage her ist, sollte der Teleporter funktionieren.
Schritte zur Reproduzierung
Naxxramas ID 4 besuchen
oder Loatheb killen, paar Tage warten und probieren.

**Comment by Dotox** [comment]
Ist absichtlich so. Wenn es anders sein sollte, wäre es super wenn da jemand was finden könnte.
