### ISSUE TITLE
Warlock Feuerstein Procc

### ISSUE THREAD

**Issue by Merkrath** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2565]
Welches Verhalten wird beobachtet?

Bei Meleeattacken mit Feuerstein (Warlock) wird kein Feuerschadensprocc ausgelöst.

Wie sollte es sich verhalten?

Der Feuerstein sollte, solange er sich in der Offhand des Hexers befindet, den Meleeattacken zusätzlichen Feuerschaden hinzufügen.

Schritte zur Reproduzierung

Als Hexer Feuerstein anlegen und auf beliebige Mobs Meleeangriffe durchführen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Keine.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

[https://datenbank.classic-wow.org/?item=13701](url)

**Comment by cowrea** [comment]
Habe gerade keinen Zugriff auf nen WL, habe ihn aber vor nem halben Jahr mal mit nem Kumpel seinem Char genutzt.

Das Ding Procct, jedoch ziemlich selten.
Glaube es waren weniger als 5%.
Wie auch schon im Tooltip steht handelt es sich um eine Chance.
Nirgends steht geschrieben wie hoch sie ist und da es sich hier um ein Nischenzauber handelt wird die Suche nach der Proccchance in Aspach Uralt Quellen enorm schwer sein.
