### ISSUE TITLE
[Naxxramas] Stalagg bewegt sich nicht/ Stalagg kommt erneut in den Kampf

### ISSUE THREAD

**Issue by Heri7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2568]
Welches Verhalten wird beobachtet?
Stalagg bewegt sich bis zum ersten Tank wechsel nicht (1 mal in 5 Trys passiert).
Stalagg kommt nachdem Stalagg und Feugen getötet wurden wieder in den Kampf und Respawnt/ wird Wiederbelebt (1 mal in 3 Trys passiert).

Wie sollte es sich verhalten?
Stalagg sollte sich bewegen.
Stalagg sollte nicht erneut in den Kampf kommen und Respawnen/ Wiederbelebt werden nachdem Stalagg und Feugen gleichzeitig getötet wurden.

Schritte zur Reproduzierung
Nach Naxxramas gehen und gegen Stalagg und Feugen kämpfen. Uns ist leider nichts ungewöhnliches aufgefallen was dieses Verhalten erzeugt hat.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Stalagg bewegt sich nicht: https://www.twitch.tv/videos/253653171?t=03h37m16s
Stalagg kommt nach seinem Tod wieder in den Kampf: https://www.twitch.tv/videos/253653171?t=03h51m23s
Unten links im Bild sieht man die Lebensanzeigen von Stalagg und Feugen an der man erkennen kann das diese zeitgleich sterben. Unten rechts im Chat schreit erst Stalagg und dann Feugen das sie gestorben sind (Stalagg: Master save me... / Feugen: No...more...Feugen) und danch kommt von Stalagg der Schrei das er den Kampf beginnt (Stalagg: Stalagg crush you!).
http://wowwiki.wikia.com/wiki/Stalagg_(original)
http://wowwiki.wikia.com/wiki/Feugen_(original)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Thaddius: https://datenbank.classic-wow.org/?npc=15928
Stalagg: https://datenbank.classic-wow.org/?npc=15929
Feugen: https://datenbank.classic-wow.org/?npc=15930

**Comment by Heri7** [comment]
Wir waren gestern abend wieder bei Thaddius und haben den Boss 6 mal bekämpft. Ein mal ist der Fehler aufgetreten das sich Stalagg erst nach dem ersten Wurf bewegt hat. Der zweite Fehler ist garnicht aufgetreten.

**Comment by Dotox** [comment]
Wir hatten das Problem während den Beta-Tests auch gehabt, wirklich reproduzieren konnte man es aber nicht. Ich habe daraufhin einiges geändert und bis dahin ist es (während den Tests) nicht mehr aufgetreten. Falls noch jemand etwas auffälliges dazu beobachtet hat, oder in Zukunft darauf achten wird, würde ich mich über mehr Input freuen.
