### ISSUE TITLE
T3 Magier - 6er Bonus existiert nicht

### ISSUE THREAD

**Issue by Tweet1337** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2569]
Welches Verhalten wird beobachtet?
Der 6er T3-Bonus des Magiers existiert nicht. Es werden keine Proccs ausgelöst.

Wie sollte es sich verhalten?
Normalerweise sollte ein Mage mit 6 Teilen des T3-Sets durch jeden verursachten Damage eine 20%ige Chance haben, "Elemental Vulnerability" auf dem Target aufzutragen. Dies sollte "Your damage spells have a chance to cause your target to take up to 200 increased damage from subsequent spells." bewirken. 

Schritte zur Reproduzierung
6 Teile vom Magier T3-Set anlegen und beliebige Mobs damagen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
WoW-Head: 
http://de.wowhead.com/spell=28771/elementarverwundbarkeit#english-comments

Aussage in WoW-Head-Kommentarsektion über Procc-Chance:
http://de.wowhead.com/item-set=526/frostfeuerornat#english-comments
(Antwort von "Freud" auf den Kommentar von "Pyrokinesis"- mit Strg-F suchen)

andere Privat-Server-Datenbanken:
http://reinosdeleyenda.org/aowow/?spell=28771
http://www.wow-mania.com/armory/?spell=28771
https://db.linebr.com/woltlk/?spell=28771
https://www.wowdb.com/spells/28771-elemental-vulnerability
https://db.rising-gods.de/?spell=28771

Github-Eintrag von ehemals Feenix - dort trat der selbe Fehler auf:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2749

Beispiel vom Sound-Effekt bei Procc:
https://db.rising-gods.de/?spell=28772&locale=3#sounds

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
T3-Kopf: https://datenbank.classic-wow.org/?item=22498
Spell des 6er-Bonus: https://datenbank.classic-wow.org/?spell=28771

**Comment by Sheed90** [comment]
Warum wurde sowas nicht auf dem Testserver getestet? Habt ihr nicht damals auch T3 zum testen gekriegt? Ich will unsere Mages da nicht ausschließen.

**Comment by Tweet1337** [comment]
Hab es gerade nochmal allein (wie vorher auch) in Winterspring & im Duell getestet, also gegen Targets auf denen 0 Debuffs liegen - der Procc wird visuell und akustisch ausgelöst (ist mir vorher nicht aufgefallen). Es taucht aber nix in der Debuffleiste oder im Kampflog auf, ebenso ist keine Erhöhung im Schaden vorhanden.

**Comment by Haudraufinix** [comment]
Ist es möglich das vielleicht der auftragende Spell den Effekt direkt Konsumiert?

Da ein Geschoss im Moment des Abschusses den Schaden berechnet, nicht beim Einschlag (Gut zu Beobachten mit Trinkets oder Wutgeheul beim Jäger), könnte es sein, dass der Schadensbonus nicht angerechnet wird, weil der Schaden vom Spell bereits berechnet wurde?

Das wäre halt eine verkettung zweier "kleinerer" Bugs die diesen Effekt hätten. Vielleicht mal mit casts ohne Flugzeit testen.

**Comment by Tweet1337** [comment]
Habe vor 3 Wochen mit Dago geschrieben, es hat auf dem Testserver auch **nicht** funktioniert - ohne es näher ausführen zu wollen. ^^

Außerdem habe ich es mit Instant-Spells probiert, wie von Haudraufinix vorgeschlagen, selbes Schauspiel: Procc wird visuell und akustisch ausgelöst, es tritt aber ebenfalls kein Effekt auf. Weder ist in der Debuffleiste ist der Procc zu sehen (sollte laut WoW-Head aussehen wie Magie entdecken-Spell vom Mage), noch verändert sich in irgendeiner Weise der Schaden.

Falls ich bei irgendwas behilflich sein kann bzgl. Tests gerne einfach melden, ansonsten wüsste ich grad nicht inwiefern ich mehr Recherche betreiben / Input liefern kann.

**Comment by 2muchmage** [comment]
Gibt es inzwischen etwas neues oder wird das Thema nicht mehr behandelt? 
Ich mein, Tweet hat doch schon eine Menge getestet. Wenn mehr gewünscht wird bitte auch dies explizit benennen :)
Einige Magier aus dem Sc - Kader könnten dabei auch gern behilflich sein. Dafür müsste jedoch wie gesagt benannt werden, was wirklich an Testwerten gebraucht wird.
Einfach so 100 mobs kloppen hat der Tweet ja schon gemacht ^^

Gruß
Toomuch

**Comment by Haudraufinix** [comment]
In der DB hat der Aura Effekt eine Reichweite von 0 (Self Only)
https://datenbank.classic-wow.org/?spell=28771

Andere ähnliche Auraeffekte haben stattdessen eine Reichweite von 30+ Metern

Klinge der ewigen Dunkelheit:
https://datenbank.classic-wow.org/?spell=21978

Expose Weakness vom Jäger T2 Set
https://datenbank.classic-wow.org/?spell=23578

Nach dem was Dago mir neulich über Auren erklärt hat sollte das zwar kein Problem darstellen.

Ausserdem hat der Procc des T3 Sets eine 30 Meter Reichweitenbegrenzung. Kann es sein, dass ihr bei den allermeisten Tests weiter als 30m weg standet?
