### ISSUE TITLE
Traumachirurg der Allianz

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2570]
Welches Verhalten wird beobachtet?
Bietet keine Quest an für Charakter lvl 35 mit 220/225 Erste Hilfe Skill.

Wie sollte es sich verhalten?
Sollte die Quest Traumachirurg der Allianz für Charakter ab Stufe 35 und einem Skill von 175/225 anbieten.

Schritte zur Reproduzierung
Versuchen die Quest anzunehmen unter den Vorraussetzungen lvl 35 zu sein und einen Skill von 220/225 zu haben. 
Kann leider nicht sagen ob die Quest mit lvl 40 annehmbar ist. Sie sollte aber wie auch in der Datenbank ersichtlich ab lvl 35 annehmbar sein. 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Klasse: Schurke
Rasse: Gnom
Lvl: 35
Skillevel Erste Hilfe: 220/225

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Quest: https://datenbank.classic-wow.org/?quest=6625
Questgeberin Nissa Feuerstein: https://datenbank.classic-wow.org/?npc=5150

**Comment by Slimmer2** [comment]
Mindest Voraussetzung für die Quest ist Level 35 und Skill 225/225

**Comment by Suzaru** [comment]
Wie sollte es sich verhalten?
Sollte die Quest Traumachirurg der Allianz für Charakter ab Stufe 35 und einem Skill von 175/225 anbieten.

Hast du dafür eine Quelle?

**Comment by Suzaru** [comment]
Also gemäß dem Link brauchst du Skill 225 für die Quest "Triage".
Selbe Information findet sich auch hier -> https://classicdb.ch/?quest=6624
Da heißt es: "By Anator on 04/12/2008 (Patch 2.4.1)
You DONT need the prequest, **all you need is 225 First Aid to obtain the quest from the Trauma Surgeon.** For the quest itself I simply went round the room clockwise. Got it first time."
