### ISSUE TITLE
AQ20 - Manapot Batterie?

### ISSUE THREAD

**Issue by danbl** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2573]
**Welches Verhalten wird beobachtet?**
In einer geleerten AQ20 ID kann man alle 30 min nach einen Reset der Instanz (Raid auflösen, 30 min warten, Raid aufmachen) immer wieder 5 Manapots bei dem NPC Generalleutnant Andorov (https://datenbank.classic-wow.org/?npc=15471) kaufen. 

**Wie sollte es sich verhalten?**
Gute Frage, dazu finde ich ehrlich gesagt nichts. Aber ich kann mir nicht vorstellen, das es so gewünscht ist. Vielleicht sollte man eine Despawn Zeit einbauen, wenn General Rajaxx getötet wurde (z.B. 30 min)

**Schritte zur Reproduzierung**
AQ20 ID aufmachen, General Rajaxx killen, beim NPC Generalleutnant Andorov (https://datenbank.classic-wow.org/?npc=15471) 5 Manapots kaufen. Aus der Ini laufen, Raid auflösen, 30 min warten, Raid aufmachen, reinlaufen, erneut kaufen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Generalleutnant Andorov (https://datenbank.classic-wow.org/?npc=15471)

**Comment by Haudraufinix** [comment]
Despawns des NPC finde ich ungünstig, da man bei Andorov auch Rezepte kaufen kann, welche man vielleicht mit dem Twink o.ä. nach Raidende erwerben möchte.

**Comment by booneyclassic** [comment]
Der NPC muss despawnen :D Gerade weil wir hier in Classic sind, ist es nicht gedacht, mal eben seinen Twink mit den "wertvollen" Rezepten auszustatten ohne den Boss dafür besiegen zu müssen.

Die Sache mit dem Despawn etc steht übrigens schon im Bugtracker, siehe dazu #1451
