### ISSUE TITLE
Wolfskopfhelm

### ISSUE THREAD

**Issue by mattuk1337** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2574]
**1. Welches Verhalten wird beobachtet?**
Der [Wolfskopfhelm] für den Druiden (https://datenbank.classic-wow.org/?item=8345) stellt nur manchmal 20 Energie her wenn man in die Katzengestalt geht.
Nach meinen Tests schätze ich, dass es ein eingebauter "interner Cooldown" von 1 Minute ist.

Dies ist nicht "blizzlike", da dieser Helm bis zum Addon "Burning Crusade" und sogar noch zu "Wrath of the Lich King" verwendet wurde für das sogenannte "powershifting" (Erklärung dazu folgt)

*) Sidenote: 
In Bär scheint alles ohne inneren Cooldown zu funktionieren. Der Helm stellt immer 5 zusätzliche Wutpunkte her wenn man in die Bärengestalt wechselt.

der offizielle Bluepost zu dem Thema lautet: 
"This was an advanced technique used by many skilled or knowledgeable feral dps players **in The Burning Crusade** while chain-drinking Mana Potions (!) in order to squeeze out as much energy and therefore dps as possible. It was also sometimes used in conjunction with the **infamous level 40 (!)  [Wolfshead Helm]** which caused the strange appearance of very highly-geared Feral Druids raiding in fully epic tier sets and the latest, best gear - but still using a Rare helm normally crafted using simple materials for characters not even level 60.
This technique was nerfed in Patch ___ by a change to the Furor Talent **toward the end of The Burning Crusade** and will not return, (...)"
(Quelle: Zitat aus einem offiziellem Bluepost: "https://wow.gamepedia.com/Powershifting", 
"http://wowwiki.wikia.com/wiki/Powershifting")

*) Änderung die erst nach "Burning Crusade" (also auch nach "Vanilla WoW") gemacht wurde: http://de.wowhead.com/spell=17770/wolfskopfhelm-energie#see-also-other

**2. Wie sollte es sich verhalten?**
Der Wolfskopfhelm sollte immer 20 Energie wiederherstellen wenn man in die Katzengestalt geht und 5 Wut wenn man in Bärengestalt geht, nicht nur 1 mal pro Minute.

Zusammen mit den 5 Talentpunkten im Talent "Furor" (https://datenbank.classic-wow.org/?spell=17061) sollte man damit, je nach Energietick, entweder 60 oder 80 Energie besitzen jedes mal wenn man in Katzegestalt geht.

*) Bester Indikator dafür: Genau so wie es sich mit der Wut für die Bärengestalt verhält, sollte es sich auch mit der Energie für die Katzengestalt verhalten.

*) Der grüne Zusatztext auf dem Item ist so formuliert, dass es ohne Zweifel ein fixer, dauerhaft zu Verfügung gestellter Wert sein sollte, jedes mal wenn man in die entsprechende erwähnte Tierform wechselt.
"Equip: When shapeshifting into Cat form the Druid gains 20 energy, when shapeshifting into Bear form the Druid gains 5 rage." (Zitat: Zusatztext auf dem Item [Wolfskopfhelm])

Immer wenn auf einem Item "Equip: (...)" verwendet wird ist das in der Regel ein dauerhaft zu Verfügung gestellter Wert, ausser es wird eine Procc-Chance oder ein Cooldown erwähnt.
Die Formulierung ist hier sehr wichtig.

**)hypothetische Alternativbeispiele:
Bsp. Wenn das Item eine Procc-Chance hätte, würde die Formulierung lauten:
"Equip: When shapeshifting into Cat form **you have a chance** to gain 20 energy (...)" 
"Equip: When shapeshifting into Cat form you gain 20 energy **once every minute** (...)"

Interne Cooldowns wurden aber erst später in das Spiel bzw. in den Zusatztext auf Items hinzugefügt:
Hinter dem grünen Zusatztext: "(can occur once every Minute)" oder "(1 Minute Cooldown)"

Bei den sogenannten "Use"-Items gab es diese "internen Cooldowns" auch schon zu "Vanilla WoW" 
zb. bei [Linken's Boomerang] https://classicdb.ch/?item=11905 "(cooldown 3 min)"

allerdings nicht bei jedem Item wurde der "Cooldown-Text" hinzugefügt:
zb. bei [Luffa] / [Luffaschwamm] https://datenbank.classic-wow.org/?item=19141
Dieser Cooldown wird aber nach benutzen des "on-use"-Effekts sichtbar. ("3 min CD")

**3. Schritte zur Reproduzierung**

Selbsttest:
Ich shifte kurz vor einem Energie Tick in Katzengestalt --> jede Minute erhalte ich dadurch 1 mal 80 Energie (40 aus der Skillung + 20 vom Wolfskopfhelm + 20 vom Energietick) 
Wenn man das Gestaltwandeln, wieder zurück in Taurengestalt und danach wieder in die Katzengestalt, innerhalb des "internen Cooldowns" (Vermutung: ~1min) fortsetzt erhält man nur 60 Energie (40 skillung + 20 vom nächsten Energietick)

Zusätzliche Informationen:
Druide (Taure, Nachtelfen) 
Item: [Wolfskopfhelm] / [Wolfshead Helm]
https://datenbank.classic-wow.org/?item=8345 / https://classicdb.ch/?item=8345

Noch ein Link zu einem Youtube Guide auf einem Testserver der ganz gut zeigt wie es sich verhalten sollte --> https://youtu.be/a_b-vtx67eU?t=391  (an die signifikante Stelle gespult)

Noch ein Link zu einem Youtube Video mit mehreren langjährigen WoW-Pros/Streamern
--> https://youtu.be/h5KMJJHZVb4?t=1878  (an die signifikante Stelle gespult)

Ich würde mich sehr freuen über eine baldige Antwort/ Anpassung.

Lg Madmatt

**Comment by mattuk1337** [comment]
Danke für die Links zu den früheren Bugtracker-Einträgen.
Ich habe die leider nicht gefunden und die scheinen ja schon sehr alt zu sein.

Ich denke aber, dass ich bessere Argumente und Beweise dafür habe, das man sich vielleicht doch überlegt diesen Fehler anzupassen.

LG Mad

**Comment by dagochen** [comment]
Ändert weiterhin nichts daran, dass in den Client-Daten von einem unmodifizierten Classic-WoW-Client dieser Cooldown einprogrammiert ist. Daher ist der Glaube daran, dass das Item gar keinen Cooldown haben sollte, ziemlich weit hergeholt, solange es keine Quelle aus 2006 gibt. Und so professionel die 4 im Stream auch seien mögen, eine handfeste Quelle von 2006 ist es nun mal nicht. Powershifting ist bei uns bereits möglich. Auch die Aussage das der Helm gut sei, weil er zusätzliche Energie liefert ist auch richtig. Ich kann also auch nur nochmals auf meine Kommentare dazu in den vergangenen Bugreports hinweisen und an der Stelle hier wieder dicht machen, bis ggf. was handfestes geliefert werden kann.

**Comment by mattuk1337** [comment]
Woher soll dieser "unmodifizierte Classic-WoW-Client" denn stammen? Laut Blizzards Aussagen besitzen sie diesen nicht einmal selbst. Definitive Beweise von 2005/06 gibt es nicht. Auch keine unmodifizierten WoW-Clienten/Server etc. 

Weder kann bewiesen werden, dass das Item einen Internen Cooldown hatte, noch, dass es keinen hatte.
Aber es ist schon sehr komisch, dass die Überzeugende Mehrheit der Quellen und Augenzeugen von damals der Überzeugung sind, dass es damals so gewesen ist, bis zu irgendeinem Patch der irgendwann zwischen BC und Wotlk kam.

Warum schenkt man den Leuten die Vanilla WoW 2005/2006 wirklich gespielt haben (und es damals so erlebt haben) nicht einfach Glauben und ändert es dahingehend? Es wäre wahrlich keine weltbewegende Veränderung ... Ferals würden nicht auf einmal mehr Schaden machen als Schurken o.Ä. ... aber es würde vielleicht erlauben wenigstens einen im Raid zu haben.

Mir ist schon klar, dass powershifting so auch möglich ist, aber eben nicht mit 80, sondern nur mit 60 Energie.

Lg Mad

**Comment by dagochen** [comment]
Der Classic-Client, den wir zum Download anbieten ist unmodifiziert (bis auf die Realmlist). Jeder der noch die CDs von damals hat kann alternativ diese nutzen zur Installation und sich die Updates aus dem Internet runterladen. Dann hat er auch einen funktionierenden 1.12 Client und kann die Daten, wie z.B. interne Cooldowns, auslesen.

Ganz einfach: Weil diese Leute schon viel zu oft falsch lagen. Wie schammig die Aussage selbst ist siehst du ja selber ("[...] bis zu irgendeinem Patch der irgendwann zwischen BC und Wotlk kam."). Das sind einfach zu viele "irgend"s.... überspitzt gesagt: "Irgendwann in irgendeiner Version auf irgendeinem anderen Privatserver konnten Katzen irgendwie mal richtig viel Schaden machen und irgendwie hat das den Leuten irgendwas in den Kopf gesetzt, wodurch sie irgendwie auf diese Idee gekommen sind, dass es irgendwann in Classic auch so war."

Und wir können nun mal keine Klassenänderungen ohne Beweise durchführen, sonst würden Paladine ihren Holy-Shock wollen, Ferals ihre Waffenverzauberungen, Shadowpriests wollten mehr Range und Mana, Eulen weniger Manakosten und mehr Zauberkrit, Schamanen würden auch noch irgendwas verrücktes wollen und und und und und.....

**Comment by Firstfloyd** [comment]
Hallo, ich weis das die Katze damals in Cata in blauem EQ an Ultraxion mehr Schaden machen konnte als der gesamte Raid, aber nicht zu Classic Zeiten.

 

Von: dagochen [mailto:notifications@github.com] 
Gesendet: Samstag, 5. Mai 2018 11:49
An: ClassicWoW/Nefarian_1.12.1_Bugtracker
Cc: Subscribed
Betreff: Re: [ClassicWoW/Nefarian_1.12.1_Bugtracker] Wolfskopfhelm (#2574)

 

Der Classic-Client, den wir zum Download anbieten ist unmodifiziert (bis auf die Realmlist). Jeder der noch die CDs von damals hat kann alternativ diese nutzen zur Installation und sich die Updates aus dem Internet runterladen. Dann hat er auch einen funktionierenden 1.12 Client und kann die Daten, wie z.B. interne Cooldowns, auslesen.

Ganz einfach: Weil diese Leute schon viel zu oft falsch lagen. Wie schammig die Aussage selbst ist siehst du ja selber ("[...] bis zu irgendeinem Patch der irgendwann zwischen BC und Wotlk kam."). Das sind einfach zu viele "irgend"s.... überspitzt gesagt: "Irgendwann in irgendeiner Version auf irgendeinem anderen Privatserver konnten Katzen irgendwie mal richtig viel Schaden machen und irgendwie hat das den Leuten irgendwas in den Kopf gesetzt, wodurch sie irgendwie auf diese Idee gekommen sind, dass es irgendwann in Classic auch so war."

Und wir können nun mal keine Klassenänderungen ohne Beweise durchführen, sonst würden Paladine ihren Holy-Shock wollen, Ferals ihre Waffenverzauberungen, Shadowpriests wollten mehr Range und Mana, Eulen weniger Manakosten und mehr Zauberkrit, Schamanen würden auch noch irgendwas verrücktes wollen und und und und und.....

**Comment by mattuk1337** [comment]
Firstfloyd: "Hallo, ich weis das die Katze damals in Cata in blauem EQ an Ultraxion mehr Schaden machen konnte als der gesamte Raid, aber nicht zu Classic Zeiten. "

Lass mich raten. Du bist ein Cata Spieler? Hast du zu Vanilla überhaupt gespielt ? Irgendwelche fundierten Beweise, dass es nicht so war? Ansonsten würde ich solche vagen Statements hier lassen.

**Comment by Dotox** [comment]
Der Classic-Client den wir hier nutzen ist original und jetzt hört bitte auf hier rumzueiern

**Comment by Larnak1** [comment]
Blizzard meint dabei immer den Server, nicht den Client. Den Client gibt's auf jeder CD, wie dago schon sagt, der ist nicht schwer zu beschaffen.

Die Entwickler haben mehr als genug zu tun, du führst ja selbst einige Punkte an, die noch offen sind. Da ist es Aufgabe von uns, den Entwicklern entgegenzukommen, indem wir Quellen für unsere Erinnerungen finden.

**Comment by Firstfloyd** [comment]
Sorry du hast mich sicher falsch verstanden, ja ich hab zu Classic schon gespielt von 2007 - 2016. 

Das war keine Kritik, ich kann mich nur an eine Situation erinnern wo eine Katze soviel Schaden gemacht hat das es aufgefallen ist.

 

 

Von: mattuk1337 [mailto:notifications@github.com] 
Gesendet: Samstag, 5. Mai 2018 13:30
An: ClassicWoW/Nefarian_1.12.1_Bugtracker
Cc: Firstfloyd; Comment
Betreff: Re: [ClassicWoW/Nefarian_1.12.1_Bugtracker] Wolfskopfhelm (#2574)

 

Firstfloyd: "Hallo, ich weis das die Katze damals in Cata in blauem EQ an Ultraxion mehr Schaden machen konnte als der gesamte Raid, aber nicht zu Classic Zeiten. "

Lass mich raten. Du bist ein Cata Spieler? Hast du zu Vanilla überhaupt gespielt ? Irgendwelche fundierten Beweise, dass es nicht so war? Ansonsten würde ich solche vagen Statements hier lassen.

**Comment by dagochen** [comment]
@mattuk1337 Dann schreib Bugreports, dann können wir die Fehler auch angehen. Aber bitte suche valide Quellen raus, wie jeder andere auch. Bitte versteh einfach, dass Erinnerungen keine zulässige Quelle sind, da jeder sich an was anderes erinnert und wir keine Lust haben, jede Woche irgendwas hin- und herzuändern. Du schreibst es gibt so viele Fehler, aber ich sehe nur einen Bugreport von dir. Es ist ein Community-Projekt, wir sind ein kleines Team und können nicht alles selbst machen. Ohne die Mithilfe von den Spielern wäre AQ und Naxx bis heute noch nicht offen, weil wir dann die ganzen Informationen selber hätten raussuchen und überprüfen müssen, dann programmieren und testen und und und ....du siehst es ist sehr viel Arbeit.

Zu der "nicht mal Blizzard hat das mehr" ist so auch nicht ganz richtig. Sie haben die Daten (Spielmechaniken, Dropchancen, Formeln für Zauber, Schaden etc.) aber das was sie nicht haben ist aktuell die Technologie, um die Server von damals mit der Performance und Stabilität laufen zu lassen, wie es Nostalrius z.B. getan hat. 2005 und 2006 waren es ca. maximal 3000 Spieler auf einem Server und diese hatten extreme Probleme wenn viele Spieler in einer Zone waren. Um diese Probleme anzugehen, haben sich Blizzard-Mitarbeiter u.A. mit denen von Nostalrius getroffen und Details zur Implementierung der Server ausgetauscht. Es geht dabei also um technische Aspekte, Technologien und Programmier-Ansätze, die genutzt wurden, um 10000 Spieler gleichzeitig auf einem Server, zu bewerkstelligen. Das was uns mit den Legacy Servern erwarten wird, sind gänzllich neue Server UND Clients, die wir uns dann runterladen müssen. Mit dem Classic Client und den cMangos / TrinityCore-Servern (die die meisten Privatserver nutzen) wird das was Blizzard entwickelt so gut wie gar nichts zu tun haben.


@Firstfloyd Was hat der Schaden einer Katze in Cata mit unserm Bugreport zu tun? ;) Und Classic war 2005 und 2006, 2007 war bereits TBC ;)

**Comment by mattuk1337** [comment]
Das Problem ist einfach, dass es für manche Dinge, wie sie damals vor 15 Jahren waren, keine Beweise mehr gibt. Thottbot ist tot, Elitistjerks gibts auch nichtmehr. Das waren die Hauptquellen an sinnvoller Information über Vanilla WoW.

Ich kenne kaum Spieler die von der Zeit damals überhaupt noch selbst Screenshots und anderes Material besitzen. Also wie soll man so eine kosmetische Veränderung wie "das nicht existieren eines internen hidden Cooldowns auf einem low level Item" beweisen?

Fakt ist, dass genau solche Items und Möglichkeiten den Reiz an der "Urversion" des Spiels ausgemacht haben (übrigens einer der Gründe warum ich hier auf Nefarian gelandet bin und nun schon seit Jahren spiele).
Diese wurden erst später, nach Vanilla WoW, nämlich mit Addons wie BC und Wotlk dahingehend von Blizzard verändert, weil Blizzard nicht wollte, dass ein "Classic" Item über Jahre hinweg großen spielerischen Einfluss auf spätere Addons nimmt.
Solche Änderungen (interne Cds) für manche Items wurden ganz klar in einer Ära nach Vanilla WoW, vielleicht aber auch erst nach BC eingeführt. 

Stur zu sagen: "Haste Beweise" "Nein?" "Dann, Pech." wird nicht die Lösung sein.
Ihr solltet, meiner Meinung nach, überdenken euer Paradigma dahingehend zu ändern.

Noch eine Frage wurde mir leider nicht beantwortet, nämlich warum der Helm für die Bärengestalt zwar immer Wut wiederherstellt , aber für die Energie in Katzengestalt ein interner Cooldown besteht.
Müsste das Item nicht eigentlich dann wenigstens für beide Tiergestalten gleich funktionieren?
Der erwähnte "grüne Zusatztext" auf dem Item ist nämlich in der Formulierung für beide Tiergestalten identisch.
Ich bitte euch das dahingehend noch einmal zu überprüfen.

Lg Mad

**Comment by dagochen** [comment]
1. https://cdn.discordapp.com/attachments/344798336492240896/442262658281111562/unknown.png
2. https://cdn.discordapp.com/attachments/344798336492240896/442262757258166272/unknown.png
3. https://cdn.discordapp.com/attachments/344798336492240896/442262551661641738/unknown.png

1. ist der Zauber, der beim wechseln in Katze/Bär ausgelöst wird. Je nachdem ob Katze oder Bär, wird dann 2, oder 3. ausgelöst. Bei der Katzengestalt und dem Energie-Tick gibt es einen 60 Sekunden Cooldown.
