### ISSUE TITLE
Alteractal Vandarkill ohne Sieganerkennung 

### ISSUE THREAD

**Issue by Zahul** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2575]
Welches Verhalten wird beobachtet?
Im Alteractal wurde von der Horde Vanndar Stormpike erfolgreich getötet jedoch läuft das Bg weiter ohne Sieganerkennung

Wie sollte es sich verhalten?
Mit einem Horlder Av joinen paar allys mitnehmen/ umhauen, dann 
Vandar töten Bg Siegreich verlassen.  Ich denke mal spricht für sich und benötigt keine Quelle

Schritte zur Reproduzierung
Schwer zusagen ist heute das 1. aufgetreten, soll aber schon mal vorgekommen sein, ob und wie es Reproduzier ist kann ich leider nicht sagen 

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://ibb.co/g6LUdn
https://ibb.co/dERfjS
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=11948

**Comment by cowrea** [comment]
Selbiges ist auch schon auf Allianzseite vorgekommen.
Ich habe jetzt kein genaues Datum und auch kein Video machen können, war aber Mitte Februar, kurz vor Naxx Release.
Damals ging die Vermutung rum das Pet hätte den "Todesstoß" verpasst.

Zumindest was Ehre anbelangt wird dem  Hunter nämlich scheinbar nichts zugesprochen wenn das Pet andere Spieler tötet.


Das BG wurde Beendet als die Allianz dann kapituliert hat und Vanndar Strompike zusätzlich getötet wurde.

**Comment by dagochen** [comment]
Oh das klingt interessant. Das könnte tatsächlich ein Auslöser sein für das merkwürdige Verhalten ;) Ich guck mal nach...^^

**Comment by Zahul** [comment]
Bei der Allianz is das Problem grad wieder aufgetreten, kann es evtl möglich ,dass wenn Npc Wachen die geaddet wurden und mit auf den Boss kloppen, dieses Auslösen und der Kill nicht anerkannt wird ?
