### ISSUE TITLE
[Naxxramas] Maexxna - HP Bug und Double Hits

### ISSUE THREAD

**Issue by booneyclassic** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2577]
### Welches Verhalten wird beobachtet?

- Beim Raid am 06.05.18 konnten wir Maexxna aufgrund eines Bugs nicht besiegen. Ab dem dritten Try haben wir bemerkt, das der Boss bei weiteren Versuchen UND beim wirken vom Zauber "Web Spray" stetig HP verliert. Zunächst dachten wir, das sich der Boss vollheilen würde, jedoch bemerkt wir dann beim genauen Hinschauen das die HP-Anzeige auf 100% sprang, weil er seine HP angepasst hat.

Für diese Erkenntnis haben wir ein paar weitere Versuche bei dem Boss unternommen, letztendlich hatte er sogar nur noch 540.601 HP und somit weniger wie manche Trashmobs in der Instanz. Das Beweisfoto ist unten verlinkt. Wir haben den Boss dann natürlich nicht getötet und haben ihn ausgelassen... Ruljin wurde an dem Abend direkt darüber informiert.

Außerdem kam es an dem Abend wieder vermehrt vor, das der Boss mehrere Schläge gleichzeitig auf sein Ziel gewirkt hat (2-3 Hits auf einmal). Dies können wir jedoch leider nicht per Video belegen.

### Wie sollte es sich verhalten?

- Der Boss sollte nicht bei jedem Webspray und jedem erneuten Pull nach einem Wipe seine HP verringern.
- Der Boss sollte nicht 2 oder gar 3 Schläge auf einmal auf den Tank, bzw auf sein Ziel wirken

### Schritte zur Reproduzierung

- Boss pullen und so lange wie möglich bekämpfen.

### Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

- [Screen nach dem Fight](https://picload.org/view/doaapaga/worldofwarcraftscreenshot2018..png.html) (Auf Boss-HP achten)

### Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

- [Maexxna](https://datenbank.classic-wow.org/?npc=15952)
- [Web Spray](https://datenbank.classic-wow.org/?spell=29484 )

**Comment by Ulva-Anorhin** [comment]
Falls diese doppelhits nicht gewollt sind, kann ich demnächst gerne Videos dazu stellen.

**Comment by Dotox** [comment]
Kann den Fehler mit den HPs leider nicht reproduzieren. Sollte dieser nochmal auftreten und euch etwas auffallen, gerne hier kundtun.
