### ISSUE TITLE
Ravasaurusmatriarchin 

### ISSUE THREAD

**Issue by admiralhugo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2582]
Der oben benannte NPC spawnt nicht.
Hier ein Link vom NPC und der Position: http://endb.wow-atlantida.com/?npc=6581

mfg Kalu

**Comment by Dotox** [comment]
Vorlage, wo bist du nur? :(

**Comment by Haudraufinix** [comment]
Vor 2 Tagen habe ich besagten Mob umgehauen. Spawnt sehr wohl.

Sie spawnen aber nur, wenn man genügend andere Raptoren im Bereich tötet. Das entspricht ihrem Sollverhalten

**Comment by admiralhugo** [comment]
seit 2 wochen spawnt er auch wieder regelmäßig... davor war das mindestns 1 woche nicht der fall.
