### ISSUE TITLE
Heigan bewegt sich nach dem Teleport

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2584]
**Welches Verhalten wird beobachtet?**

Heigan bewegt sich manchmal nachdem er sich in die Mitte der Plattform teleportiert hat vor dem Tanz. Das löst mit ziemlicher Sicherheit einen Wipe aus da man beim Tanz seine Aura abbekommt.

**Wie sollte es sich verhalten?**

Heigan sollte nach dem Teleport in der Mitte der Plattform stehen bleiben und sich nicht bewegen.

**Schritte zur Reproduzierung**

Sicher reproduzierbar ist das nicht wirklich. Ist bisher einmal aufgetreten bei uns.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

http://666kb.com/i/dtgx9xa0m8ifwvlj7.jpg
http://666kb.com/i/dtgxbyomb68dcpygz.jpg

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

https://datenbank.classic-wow.org/?npc=15936
http://wowwiki.wikia.com/wiki/Heigan_the_Unclean_(original)

**Comment by Larirawiel** [comment]
Hi,

könnte man den boss nicht nach dem Teleport eine Art Stun verpassen? Das wurde bei den Zwillingsimperatoren glaub auch gemacht nachdem sie nach dem Port wild durch die Gegend liefen.

Grüße

**Comment by Suzaru** [comment]
Naja Heigan muss ja schon noch seinen Cast durchziehen, damit wir tanzen müssen.
So wie ich das gesehen habe ist folgendes passiert: der Port resettet die aggro (?), Spieler XY hat einen instant gecastet genau in der Millisekunden bevor Heigan anfing zu casten und ihn so geaggrot. Daraufhin ist er dann zu uns gelaufen. 
Keine Ahnung, ob das hilfreich ist. 

Grüße, 
Suzu
