### ISSUE TITLE
BWL-Pre-Brief verbuggt

### ISSUE THREAD

**Issue by Trashiboy** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2585]
Welches Verhalten wird beobachtet?

[https://datenbank.classic-wow.org/?item=18987](url) kann ich als Quest nichtannehmen. Es wird mir angezeigt, dass ich diese Quest bereits angenommen habe. Mein Questlog ist jedoch leer.

Wie sollte es sich verhalten?

Es sollte mir möglich sein diese Quest anzunehmen.

Schritte zur Reproduzierung

Ich habe bereits versucht den Gegenstand wegzuwerfen und mir einen neuen zu besorgen. Der entsprechende Mob, droppt den Brief nicht mehr.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Bitte mach für sowas ein GM-Ticket. Da wird dir dann geholfen ;)
