### ISSUE TITLE
Vernichter Debuff wird gekickt

### ISSUE THREAD

**Issue by Toeterli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2586]
Welches Verhalten wird beobachtet?

Der Armor Shatter Debuff vom Vernichter besitzt auf Nefarian keine genügend hohe Debuff Priorität und wird bevorzugt von Tiefe Wunden gekickt, wenn kein weiterer Tiefe Wunden Debuff auf dem Ziel ist, s. Video unten.

Wie sollte es sich verhalten?

Der Debuff sollte ähnlich wie Rüstung zerreißen die höchste Debuff Priorität besitzen (vgl. Datenbanken von Light's Hope Vanilla Servern) und somit nicht von Tiefe Wunden gekickt werden können (die teilen sich eine Priorität mit dem Feuerball Debuff und Waffen-Dot-Procs).

Schritte zur Reproduzierung

Im Raid (der genügend Debuffs aufbringt also bvzgt mit Feuermages, in BWL ohne Feuerballdots bleibt der Vernichterdebuff deutlich besser auf Bossen) einen bzw. mehrere Krieger mit dem Vernichter spielen lassen, der Debuff wird schnell wieder gekickt.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

https://www.youtube.com/watch?v=5M8n4-MEtN8

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

Vernichter: https://datenbank.classic-wow.org/?item=12798
Vernichterdebuff: https://datenbank.classic-wow.org/?spell=16928
Feuerball: https://datenbank.classic-wow.org/?spell=10151
Tiefe Wunden: https://datenbank.classic-wow.org/?spell=23255

**Comment by Suzaru** [comment]
Danke für den Fix. Leider funktioniert es immernoch nicht wie geplant. Wenn zwei Spieler den Vernichter nutzen, dann kicken sich die Debuffs wohl gegenseitig. Wir werden diesbezüglich demnächst ein neues Ticket aufmachen.
