### ISSUE TITLE
Höherer Schaden als Interface anzeigt

### ISSUE THREAD

**Issue by fearon1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2587]
Welches Verhalten wird beobachtet?
das Blizzard-Standard-Interface zeigt an wieviel Schaden ich erhalte, aber eigentlich "droppe" ich von den HP her mehr, als um den Wert des angezeigten Schadens.
Aufgefallen ist dies beim Kampf gegen Patchwerk (weil da die zahlen entsprechend hoch sind). Der Kampf geht los, ich habe 10k HP. Dann erhalte ich als Hateful-Tank den ersten Hit. Mir wird 8500 Schaden angezeigt. Ich schaue auf meine HP anzeige und bin nur noch bei 500 Leben. D.h. ich habe ca. 1000 Schaden mehr bekommen, als angezeigt. Infolge habe ich dies den ganzen Kampf über beobachten können, und das Verhalten tritt bei jeden Hit auf. Es waren immer zwischen 10-15% mehr Schaden, als angezeigt.

Bisher konnte ich das Verhalten nur als Hateful-Tank bei Patchwerk feststellen. In der open-world tritt das Verhalten nicht auf.

Wie sollte es sich verhalten?
Meine Annahme wäre, dass man nur den Schaden bekommt, der angezeigt wird. 6000-8700er Hits als Tank sind schon hart genug, auch ohne 10-15% mehr.

Schritte zur Reproduzierung
Patchwerk hinstellen: Zwei GMs mit massig HP ranstellen und dann die Werte vergleichen.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
- Leider nein. 

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Hateful-Strike: https://datenbank.classic-wow.org/?spell=28308 
Von Patchwerk selber hab ich kein Link gefunden.

**Comment by Baraz** [comment]
https://datenbank.classic-wow.org/?npc=16028

**Comment by fearon1** [comment]
die oben genannte Referenz mit den Giftpfützen passt nicht zu dem gemeldeten Fehler

**Comment by Umkaluabo** [comment]
Das kann ich bestätigen, es sind ca. 10% mehr Schaden als angezeigt wird.
Ich kann bei Bedarf auch ein Video stellen.

**Comment by Horim** [comment]
Kann es vielleicht sein, das das mit der defstance von Kriegern zusammenhängt ? 10% sind etwas auffällig, vielleicht wird es im kampflog richtig angezeigt, aber vom Server nicht berücksichtigt?
