### ISSUE TITLE
Twins kommen nicht aus dem Verbannen raus

### ISSUE THREAD

**Issue by Toeterli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2591]
Welches Verhalten wird beobachtet?

Die letzten 2 Wochen ist bei uns der Castertwin nach einem Teleport mitten im Kampf nicht mehr aus dem Verbannen gekommen, nach 30 Sekunden folgte auch kein weiterer Teleport mehr.

Wie sollte es sich verhalten?

Der Kampf sollte linear weiterlaufen, der Castertwin sollte aus dem Verbannen rauskommen und seine Schattenblitze verschießen, und sich weiterhin aller 30 Sekunden teleportieren.

Schritte zur Reproduzierung

Die Twins bekämpfen, wir konnten leider keinen Auslöser für den Bug ausfindig machen. Nach einem herbeigeführten Wipe trat der Bug beim nächsten Anlauf nicht mehr auf.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

https://datenbank.classic-wow.org/?npc=15276

**Comment by Sheed90** [comment]
Wir gehen heute auch AQ40, falls wir entsprechendes Verhalten ebenfalls beobachten, melde ich mich hier.

**Comment by Sheed90** [comment]
Wir konnten diesen Bug nicht reproduzieren.

Gruß
