### ISSUE TITLE
Szepter von Celabras

### ISSUE THREAD

**Issue by floxxo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2592]
Welches Verhalten wird beobachtet?
-Ich kann die Quest nicht abschließen und somit leider keinen Stab für Princess-Runs bekommen; der erforderliche npc spammt immer nur seinen Text in extrem kurzen Zeitabständen.

Wie sollte es sich verhalten?
-Quest-npc sollte die Quest beenden und einem den Stab geben

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1231
