### ISSUE TITLE
Stärke der Geißel Verzauberung fehlerhaft

### ISSUE THREAD

**Issue by Sheed90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2594]
Welches Verhalten wird beobachtet?
Im Tooltipp der Schultern Verzauberung steht folgender Text:

"Benutzen: Fügt einem Gegenstand, der sich an einem Schulterplatz befindet, dauerhaft eine um bis zu 18 erhöhte Schadens- und Heilwirkung durch Zauber und magische Effekte hinzu und erhöht die Chance auf einen kritischen Zaubertreffer um 1 %"

Sobald man die VZ auf die Schultern machen will, wird einem angezeigt (nur wenn bereits eine VZ drauf ist), ob man diese gegen + 15 Zauberschaden und 1 % Crit tauschen will.

Wie sollte es sich verhalten?
Es sollte laut Tooltipp Schaden UND Heilung sein.
Es sollte 18 Zauberschaden und Heilung sein und nicht 15.

Schritte zur Reproduzierung
VZ auf eine Schulter wirken

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://i.imgur.com/Axvv0Nn.jpg

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=23545

**Comment by dagochen** [comment]
Tooltip ist falsch, Verzauberung mit +15 ist richtig und es wird Schaden und Heilung erhöht.

https://datenbank.classic-wow.org/?spell=29468

**Comment by Sheed90** [comment]
Dummer deutscher Client...
