### ISSUE TITLE
Sonnenwendfest - "Lodernde Flammen in Kalimdor" und "Lodernde Flammen in den östlichen Königreichen"

### ISSUE THREAD

**Issue by Nullnummer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2596]
Welches Verhalten wird beobachtet? Nach anklicken der Feuer passiert nichts. Es öffnet sich nur ein Fenster, in dem nichts weiter steht außer ein Gruß.

Wie sollte es sich verhalten? Ich erwarte Questfortschritt

Schritte zur Reproduzierung: Quest annehmen und selbst versuchen. Dann sieht man das ja.

Steht doch in der Beschreibung. Wie wärs damit: https://datenbank.classic-wow.org/?quest=9388 und hiermit https://datenbank.classic-wow.org/?quest=9389 ?

**Comment by dagochen** [comment]
Welche Quest? Verlinkung? Was soll ich hier nur fixen :(

**Comment by Nullnummer** [comment]
Steht doch in der Beschreibung. Wie wärs damit: https://datenbank.classic-wow.org/?quest=9388 und hiermit https://datenbank.classic-wow.org/?quest=9389 ?

**Comment by Nullnummer** [comment]
Funktionieren https://datenbank.classic-wow.org/?quest=9388 und https://datenbank.classic-wow.org/?quest=9389 jetzt?

**Comment by dagochen** [comment]
Wieso jetzt? Wir haben nichts geändert. Die Fehler sind bereits gemeldet, was du mit etwas suchen auch hättest finden können. Daher habe ich deinen Bugreport geschlossen.

**Comment by Nullnummer** [comment]
Na ok. Dann hoffe ich einfach drauf, dass es repariert wird ^^
