### ISSUE TITLE
Herz der Flamme

### ISSUE THREAD

**Issue by Vorathel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2598]
Welches Verhalten wird beobachtet?
Der Questgegenstand "Herz der Flamme" ist vermutlich nicht mehr vorhanden. Auch in der Datenbank kommt eine Fehlermeldung.
Links zur Datenbank:
[Quest](https://datenbank.classic-wow.org/?quest=3442)
[Gegenstand](https://datenbank.classic-wow.org/?item=10509)

Wie sollte es sich verhalten?
Der Gegenstand sollte von Elementaren in der Sengenden Schlucht gedroppt werden.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Doch droppt bei folgenden Kreaturen mit einer Chance von ~30%:
https://datenbank.classic-wow.org/?npc=5850
https://datenbank.classic-wow.org/?npc=5852
https://datenbank.classic-wow.org/?npc=5855
