### ISSUE TITLE
Krieger: Zuschlagen zeigt keine Wirkung

### ISSUE THREAD

**Issue by thekk1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2602]
Wird die Fähigkeit Zuschlagen auf einen NPC angewendet der einen Cast macht, so wird die Wirkung scheinbar unterbrochen. Trotzdem wird nach der Castdauer der Zauber gewirkt.
Ebenso wird das erneute wirken von Zaubern nicht 4 Sekunden lang verhindert.

Wie sollte es sich verhalten?
Der Zauber sollte keine Wirkung entfalten.

Schritte zur Reproduzierung
NPC der Castet aussuchen, bei Cast Zuschlagen wirken. Den Kampflog kontrollieren.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
![wowscrnshot_070518_172233](https://user-images.githubusercontent.com/16156402/42332900-87e2084a-8079-11e8-967a-0a983bfdb4c8.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Haudraufinix** [comment]
Es gibt mehrere Gründe wieso dieses Zuschlagen nicht funktioniert hat.

Am Häufigsten kann lag dazu führen, dass Zauber die clientseitig kurz vor Vollendung gekickt werden dies nicht rechtzeitig dem Server melden, wodurch dieser den Cast als erfolgreich betrachtet. (Der Client schreibt dir den Combatlog, daher taucht Zuschlagen trotzdem vor dem Cast in der Reihenfolge auf)

2. Dieser Zauber ist schlicht nicht kickbar. Es gibt einige Spells die nicht Kickbar sind, selbst wenn sie als Cast angezeigt werden (Raidbosse sind bekannte vertreter davon. Auch einige "normale Mobs" haben derartige spells) Es könnte daher sein, das dieser Mob schlichtweg ne Kickprotection hat.

**Comment by thekk1** [comment]
Zu Ersterem:
Das hab ich auch schon öfter festgestellt. Im Bereich um ca. 0,3 Sek vor Castende zeigt Zuschlagen keine Wirkung mehr. Die Verarbeitung des Servers scheint hier recht langsam zu sein denn ich habe eine 12ms Latenz zum Server. Es gibt auch noch verschiedene andere Probleme im Zusammenhang mit der Verarbeitungszeit aber das ist ein anderes Thema.
**In der oben dargelegten Situation ist dies nicht der Fall.**

Ob dieser spezielle Mob immun gegen Unterbrechungen ist kann ich nicht beurteilen und habe auch keine Motivation dies zu recherchieren. Nach meiner Erinnerung gibt es im Gebiet der östlichen Pestländer einige Mobs bei dennen Unterbrechen nicht funktioniert.
Sollte das dann aber nicht entsprechend im Combatlog vermerkt sein dass Widerstanden wurde oder aber Immunität besteht?
**Im oberen Fall taucht überhaupt keine Meldung auf.
Weder obs gewirkt hat oder nicht und das kann eigentlich nicht richtig sein.**

**Comment by dagochen** [comment]
Das mit den 0,3 Sek ist vermutlich eher dein Addon, dass einfach zu langsam ist bzw. erst den Timer startet, wenn das Addon den Kampflog ausgelesen hat. Serverseitig hat der Mob da aber schon 0,3 Sekunden lang gecastet....

**Comment by dagochen** [comment]
Das Problem war, dass der Zauber nicht unterbrechbar sein sollte, da er von einer Aura ausgelöst wird. Die Castzeit sollte auch nicht vorhanden sein. Habe den Zauber der Kreatur angepasst und überprüft, ob das Zuschlagen bei anderen Kreaturen korrekt Zauber unterbricht und konnte das Problem sonst nicht weiter reproduzieren.
