### ISSUE TITLE
Kel'Thuzad: Frostbolt Volley und Frost Blast fast gleichzeitig

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2604]
**Welches Verhalten wird beobachtet?**
Kel'Thuzad wirkt teilweise Frostbolt Volley und Frost Blast innert kürzester Zeit nacheinander, was den sicheren Tod für den betroffenen Spieler bedeutet.

**Wie sollte es sich verhalten?**
Die beiden Fähigkeiten sollten nicht in so kurzem Abstand voneinander auftreten können. Das Problem wurde bereits [hier](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2567) besprochen und behoben, scheint aber nun wieder oder immer noch aufzutreten.

**Schritte zur Reproduzierung**
Kel'Thuzad in Phase 2 bringen und etwas abwarten.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Auszüge aus dem Combatlog:
`	Line 254064: 7/9 22:50:16.409  Kel'Thuzad's Frostbolt hits Hazeblaze for 3378 Frost damage.`
`	Line 254068: 7/9 22:50:16.409  Hazeblaze is afflicted by Frostbolt.`
`	Line 254102: 7/9 22:50:16.798  Hazeblaze is afflicted by Frost Blast.`
`	Line 254159: 7/9 22:50:17.845  Kel'Thuzad's Frost Blast hits Hazeblaze for 1318 Frost damage.`
`	Line 254160: 7/9 22:50:17.845  Hazeblaze dies.`

`	Line 257088: 7/9 22:51:46.660  Kel'Thuzad's Frostbolt hits Saandro for 2814 Frost damage.`
`	Line 257089: 7/9 22:51:46.660  Saandro is afflicted by Frostbolt.`
`	Line 257125: 7/9 22:51:47.333  Saandro is afflicted by Frost Blast.`
`	Line 257157: 7/9 22:51:48.402  Kel'Thuzad's Frost Blast hits Saandro for 1131 Frost damage.`
`	Line 257160: 7/9 22:51:48.406  Saandro dies.`

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Frost Blast: https://datenbank.classic-wow.org/?spell=27808
Frostbolt Volley: https://datenbank.classic-wow.org/?spell=28479
Kel'Thuzad: https://datenbank.classic-wow.org/?npc=15990

**Comment by Dotox** [comment]
In wievielen Trys ist das genau so passiert?

**Comment by xorann** [comment]
Wir hatten bisher erst einen einzigen Versuch, beim welchem wir etwas länger in Phase 2 waren. In diesem Versuch ist es mir die zweimal wie oben aufgeführt aufgefallen. Ob es davor bereits einmal passiert ist weiss ich nicht, wäre aber wohl im Chaos des Phasenübergangs untergegangen.

**Comment by Sheed90** [comment]
Auch bei uns kommt das ab und zu vor. Aber soll das nicht auch so sein? Ich meine mich zu erinnern, dass die Frostboltvolley (Prio 2) maximal 4x ausgesetzt wird, wenn der Volley fast zur gleichen Zeit wie das Frostgrab (Prio 1) kommt. Danach wird es zu 100 % ausgelöst.

Kleiner Tipp am Rande: das Priesterschild muss sofort auf die betreffenden Personen gesetzt werden, damit man 1 Tick Zeit hat, seinen 1,5 Sekunden Spell (Blitzheilung, geringe Welle der Heilung, geringer Rang Heilende Berührung, usw.) - und es sind alle Heiler in der Nähe gefragt. So kann man quasi jeden retten. Sind mehrere Personen (außer Melees) im Block, hat mindestens eine Person gefailed und das verzeiht der Boss einfach nicht.

**Comment by Dotox** [comment]
Genau @Sheed90

**Comment by Nifexx** [comment]
Nur um mal Klarheit zu schaffen: Eine 3 Sekunden Regel wie sie von omega im KT Thread gefordert und mit Quellen belegt wird, gilt also nur für 4 aufeinanderfolgende Volleys. Danach wird der Volley und das Grab gleichzeitig ausgelöst, weil der Volley zu 100% getriggert wird? Habe ich das soweit richtig verstanden?

**Comment by Sheed90** [comment]
Ja
