### ISSUE TITLE
Kel'Thuzad: Totems werden durch Shadow Fissure zerstört

### ISSUE THREAD

**Issue by xorann** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2605]
**Welches Verhalten wird beobachtet?**
Wenn ein Totem eines Schamanen im Shadow Fissure (void zone) steht, wird dieses zerstört.

**Wie sollte es sich verhalten?**
Totems sollten von Shadow Fissure nicht getroffen werden.

**Schritte zur Reproduzierung**
Als Schamane Totems um sich herum stellen, warten bis man von Shadow Fissure betroffen wird und zusehen wie drei Sekunden später die Totems mit dem hochgehen des Shadow Fissure zerstört werden.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Hier kann man schön sehen, wie ein Strength of Earth Totem mitten im Shadow Fissure steht, dabei aber nicht zerstört wird: https://youtu.be/XOpxCUuXDH8?t=9m49s

Auszug aus dem Combatlog:
`7/9 22:35:17.684  Shadow Fissure's Void Blast hits Windfury Totem III for 133392 Shadow damage.`
`7/9 22:35:17.684  Windfury Totem III is destroyed.`

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Kel'Thuzad: https://datenbank.classic-wow.org/?npc=15990
Shadow Fissure: https://datenbank.classic-wow.org/?spell=27810
Strength of Earth Totem V (stellvertretend für alle Totems): https://datenbank.classic-wow.org/?spell=25362

**Comment by dagochen** [comment]
Private server video? Ich kenn Blood Legion nicht (was nix heißen muss)...?

**Comment by Ryanstekken** [comment]
Scheint real zu sein.
Armory
https://worldofwarcraft.com/en-us/character/illidan/zonker

**Comment by Ryanstekken** [comment]
https://worldofwarcraft.com/en-us/character/illidan/zonker
Notable Heroic Achievements:

US Horde 2nd Kel'thuzad kill in the original 40-man Naxxramas

**Comment by Dotox** [comment]
Wie sieht das mit Pets aus? Wenn die auch keinen Schaden erhalten sollten, wäre eine Änderung relativ einfach möglich ansonsten ist das ohne ein aufwändiges Refactoring nicht möglich.

**Comment by xorann** [comment]
Pets werden davon getroffen: https://youtu.be/XOpxCUuXDH8?t=8m58s

**Comment by Partyraiser** [comment]
Ich habe zusätzlich heute beobachtet, dass Detonate Mana den gleichen Effekt hat.
Ich muss leider zugeben, dass ich diesen Effekt selber nicht auf Video aufgenommen habe
und auch keine Nachweiße dazu gefunden habe, wie es sich verhalten sollte.
Trotzdem wollte ich die zusätzliche Information hier bereitstellen.

Welches Verhalten wird beobachtet?
Erhält ein Schamane das Detonate Mana Debuff und explodiert nach 5 Sekunden, so sterben alle Totems
in seiner unmittelbaren (fünf bis zehn meter) Nähe durch den Zauber Mana Detonation.
Dies habe ich leider nicht auf Video.

Wie sollte es sich verhalten?
Ich kann nur davon ausgehen, dass dies nicht die Totems töten sollte, da dies im Allgmeinen in WoW
nicht der Fall ist. Ich habe leider noch keine Nachweiße hierfür gefunden.

Schritte zur Reproduzierung
Als Schamane Totems um sich herum stellen, warten bis man von Detonate Mana betroffen wird und zusehen wie fünf Sekunden später die Totems in 5 Meter nähe des Schamanen mit dem Auslaufen des Detonate Mana Debuffs durch Mana Detonation zerstört werden.

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Kel'Thuzad: https://datenbank.classic-wow.org/?npc=15990
Detonate Mana (Debuff): https://datenbank.classic-wow.org/?spell=27819
Mana Detonation (Explosion nach Debuff): https://datenbank.classic-wow.org/?spell=27820
Strength of Earth Totem V (stellvertretend für alle Totems): https://datenbank.classic-wow.org/?spell=25362
