### ISSUE TITLE
Quest - Augustus' Receipt Book

### ISSUE THREAD

**Issue by Donlod** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2608]
Welches Verhalten wird beobachtet?
Die Einstufung der [Quest](https://datenbank.classic-wow.org/?quest=6164) ist fälschlicherweise für lvl 10, ist demnach mit lv 57 grau und gibt kaum xp. 

Wie sollte es sich verhalten?
Laut extended quest log sollte sie für Stufe 55 sein. Ab wann sie annehmbar sein soll weiß ich nicht.

**Comment by Haudraufinix** [comment]
http://wowwiki.wikia.com/wiki/Quest:Augustus%27_Receipt_Book?oldid=1869224

Wurde zuletzt am 27.04.2009 Geupdated und spricht von einem Mindestlevel von 52
Leider finde ich auch keine Quelle aus 1.12.
Daran gemessen, das die Quest 2000 Erfahrung für kaum Aufwand gibt sollte sie doch ein deutlich höheres mindestlevel als 10 haben
