### ISSUE TITLE
Lord Incendius, falsches Level

### ISSUE THREAD

**Issue by Donlod** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2609]
Welches Verhalten wird beobachtet?
Lord Incendius in BRD ist Stufe 48. Ist wohl eindeutig, dass es falsch ist.
https://datenbank.classic-wow.org/?npc=9017

Wie sollte es sich verhalten?
Richtiges level ist 55.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://www.youtube.com/watch?v=kRXGQpMeKi0

**Comment by Slimmer2** [comment]
http://classic-wow.wikia.com/wiki/Warlock_farming
Unter Blackrock Depths zu finden.
