### ISSUE TITLE
Auktionen - Betrag automatisch einfügen

### ISSUE THREAD

**Issue by uejo84** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2611]
Welches Verhalten wird beobachtet?
Wenn eine Auktion erstellt wird für zum Beispiel 20 Bronzebarren gebe ich den gewünschten Startpreis und den Sofortpreis ein. Wenn ich nochmals dasselbe wiederhole für wiederum 20 Bronzebarren, dann sind die Preise erneut einzutragen.

Wie sollte es sich verhalten?
Existiert in den eigenen Auktion für das zu verkaufende Element bereits ein Eintrag, so sollten die beiden Beträge automatisch basieren auf dem Wert der bereits bestehenden Auktion ausgefüllt werden.
Gerade wenn man mehrere Auktionen desselben Materials erstellen möchte wäre dies eine enorme Erleichterung. Voraussetzung sollte natürlich sein, dass es sich um genau dasselbe Element in derselben Menge handelt.

Schritte zur Reproduzierung
Auktion mit einem Element erstellten. Egal mit welchem. Anschliessend nochmals eine Auktion erstellen mit einem identischen Element.

**Comment by jfastnacht** [comment]
IMO ist das Problem nicht serverseitig. Schau dir mal Interface Addons für Auktionen an, wie:

* https://github.com/shirsig/aux-addon
* https://github.com/mrrosh/aux-addon (ältere Version von aux mit dem Standard Auktionsinterface)
* https://github.com/UndercityAddons-Vanilla/Auctioneer

**Comment by dagochen** [comment]
Wär mir auch neu, dass der Classic Client das selbst konnte früher....aber wenn du Quellen findest kann man sich das auch gern mal angucken.

**Comment by uejo84** [comment]
Danke für die Infos. Ich werde mir diese Addons anschauen. Soweit für mich erledigt. Kann geschlossen werden
