### ISSUE TITLE
Quest vom Item: Feuchte Notiz kann nicht gestartet werden - falsches Mindestlevel

### ISSUE THREAD

**Issue by WoW1337** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2615]
Welches Verhalten wird beobachtet?
Die Quest "Treue zu den Alten Göttern" vom Item: [Feuchte Notiz] kann nicht gestartet werden, obwohl das Mindestlevel 17 beträgt. Wenn mein Level 19 Charackter probiert die Quest anzunehmen, dann kommt folgende Meldung:  "Ihr erfüllt die Anforderungen für diese Quest nicht"

Wie sollte es sich verhalten?
Es sollte möglich sein, dass die Quest schon mit Level 17 angenommen werden kann, weil es so ja auch im Item [Feuchte Notiz] steht (Requires Level 17).

Schritte zur Reproduzierung
Item [Feuchte Notiz] einfach ausführen und probieren die Quest anzunehmen. Level 17-19.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Klasse: Krieger
Rasse: Orc
Level: 19
![feuchte notiz](https://user-images.githubusercontent.com/42253385/43926457-a267c070-9c2a-11e8-9d68-c8ca5bc42061.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?item=16790
https://datenbank.classic-wow.org/?quest=6564

**Comment by dagochen** [comment]
Das Problem könnte auch anders rum sein, dass das Item erst mit Stufe 22 benutzbar sein könnte. Bitte recherchier das etwas genauer mit entsprechenden Quellen, danke!
