### ISSUE TITLE
Quest: Gewürzter Wolfskebab

### ISSUE THREAD

**Issue by nesferatuh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2616]
Welches Verhalten wird beobachtet?
DIe quest kann nicht abgegeben werden.
Wie sollte es sich verhalten?
Die quest kann man abgeben wenn man 10x Magere Wolfflanke und Würzkräuter aus Stormwind hat.
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by dagochen** [comment]
Grad ausprobiert, funktioniert einwandfrei.
