### ISSUE TITLE
Verbesserter Seelendieb procct nicht bei Kill durch irgend eine andere Fähigkeit

### ISSUE THREAD

**Issue by twothe** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2618]
Welches Verhalten wird beobachtet?
Wird ein Gegner unter Einfluss von Seelendieb bei geskilltem [Verbesserter Seelendieb](https://datenbank.classic-wow.org/?spell=18372) getötet so erhält der Hexer den Buff nur dann, wenn der Gegner durch Seelendieb-Schaden getötet wird.

Wie sollte es sich verhalten?
Der Hexer sollte den Buff erhalten wann immer ein Mob durch Schaden vom Hexer getötet wird während Seelendieb auf dem Gegner ist. Vergl. auch die englische Beschreibung: "if the target is killed by you while you drain its soul."

Schritte zur Reproduzierung
1. Verb. Seelendieb 2/2 skillen
2. Gegner mit Dots und Pet angreifen und Seelendieb aktivieren.
3. Steht im Combat-Log als finaler Schaden nicht Seelendieb, erhält der Hexer den Buff nicht.

**Comment by dagochen** [comment]
Bitte aus unserer DB verlinken.

**Comment by Slimmer2** [comment]
Sicher das du den Npc getötet hast und nicht dein Begleiter?

**Comment by twothe** [comment]
Ich hab das mehrfach probiert, nur wenn der Seelendieb den Kill gemacht hab gabs den Proc.

Eigentlich sollte das auch egal sein wenn mein Pet den Kill macht, denn dann ist der Kill ja immer noch von meinem Character gemacht worden.

**Comment by stva23** [comment]
Siehe #2492

**Comment by twothe** [comment]
Konkret in 2492: "Das Talent funktioniert, wenn der Gegner tatsächlich am Soul Drain stirbt."
Bestätigt also meine Tests. So hat das Talent aber damals nicht funktioniert, der Gegner musste durch Schaden vom Hexer sterben, das ging aber auch wenn Dots oder andere Quellen den Schaden verursacht haben. In Kern aktiviert sich das Talent unter den selben Bedingungen wie das [Äquivalent vom Priester](https://datenbank.classic-wow.org/?spell=15338).

Wenn man die alten Guides durchliest findet man auch Tipps Drain Soul direkt nach dem Shadowbolt zu casten, damit dann der DS aktiv ist wenn der SB den Mob killt für den Procc. In der [Wiki ](http://wowwiki.wikia.com/wiki/Improved_Drain_Soul) wird auch als Änderungen nur aufgeführt, dass mit BC das Talent auch geprocct ist, wenn das Pet den Kill ausgeführt wird.
