### ISSUE TITLE
Scholo Schlüssel Quest nicht machbar

### ISSUE THREAD

**Issue by Shyalya** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2619]
Welches Verhalten wird beobachtet?
Kompletter QuestHub nicht verfügbar nach Abgabe der Quest "Ruf zu den Waffen, Die Pestländer"

Wie sollte es sich verhalten?
Nach Abgabe der Quest sollten verschiedene Questreihen verfügbar sein.
Scholo Schlüssel Questreihe, Kessel Quest westliche Pestländer etc.

Schritte zur Reproduzierung
Anfang: Künder Balthazad Quest annehmen
Ende: Hochexekutor Derrington Quest abgeben

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Barthalomeus Untot - Magier - Level 60 Ruf Freundlich Argentumdämmerung

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=5094
https://datenbank.classic-wow.org/?quest=5096/Scharlachrote%20Ablenkung nicht existent

**Comment by dagochen** [comment]
Welche der drei Ruf zu den Waffen hast du genau gemacht?
a) https://datenbank.classic-wow.org/?quest=5093
b) https://datenbank.classic-wow.org/?quest=5094
c) https://datenbank.classic-wow.org/?quest=5095

**Comment by Shyalya** [comment]
https://datenbank.classic-wow.org/?quest=5094

Wie oben schon beschrieben

**Comment by dagochen** [comment]
Kann das Problem nicht reproduzieren.

**Comment by Shyalya** [comment]
Kein Bug ?

Danke

**Comment by dagochen** [comment]
Wie gesagt, egal welche der 3 Quests ich mache, ich bekomme mit Quest-Minimum-Level problemlos die Folgequest und kann dann weitermachen. Wenn du da Probleme hast, schreib am besten ein GM-Ticket, dann guckt sich einer unserer GMs das direkt bei dir an ;)
