### ISSUE TITLE
NPC: Margol der Wütende / Margol der Wüterich (Sengende Schlucht) droppt Horn nicht

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#262]
**Welches Verhalten wird beobachtet?**
Der NPC Margol der Wüterich (der in der Datenbank nur als Margol der Wütende vertreten ist) droppt nichts, obwohl in der Datenbank ein Wert von 100% steht. Möglicherweise hat das etwas mit den ungleichen Namen zu tun.

**Wie sollte es sich verhalten?**
Der NPC sollte ein Questitem, sein Horn, droppen, das dann eine Quest startet.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Margol der Wütende: http://datenbank.welli-it.de/?npc=5833
Margols Horn: http://datenbank.welli-it.de/?item=10000

**Comment by Larnak1** [comment]
Hab ihn gerade mit einem anderen Char probiert, wieder kein Loot

**Comment by dagochen** [comment]
@Larnak1 Bist du zufällig Hordler? Die Quest ist nur für Allianzler, daher droppt das Horn für Hordler nicht?

**Comment by Larnak1** [comment]
ah, stimmt... ich hab nur bis 
"Seite: Both" 
gelesen :D
