### ISSUE TITLE
Überbuffen von Dots mit kleineren Rängen

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2620]
**Welches Verhalten wird beobachtet?**

Setze ich einen DoT (z.b. SW:P oder Verderbnis (mit den beiden hab ich es getestet) kann ich den selbigen nicht mit einem geringeren Rang überschreiben.

**Wie sollte es sich verhalten?**

Ich sollte meine eigenen Debuffs mit niederen Rängen überschreiben können.

**Schritte zur Reproduzierung**

--

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

Das ging bis vor einiger Zeit noch. Den genauen Zeitpunkt kann ich allerdings nicht mehr sagen.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

--

**Comment by Slimmer2** [comment]
Das ging noch nie.
Man musste immer erst den höheren debuff ablaufen lassen.
