### ISSUE TITLE
Quest Goldzahn

### ISSUE THREAD

**Issue by nesferatuh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2621]
Welches Verhalten wird beobachtet?
Mob spawned nicht oberhalb der Tiefenschachtmiene
Wie sollte es sich verhalten?
https://de.wowhead.com/quest=87/goldzahn
Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Slimmer2** [comment]
In den Kommentaren steht
Von agatushka (149 – 0) am 2008.01.08 (Patch 2.3.2)		
in the Fargodeep Mine, which is south from Goldshire, turn right at the crossroads inside. Goldtooth is 8 lvl mob, he is at the end of that tunnel
