### ISSUE TITLE
T3 - Magier - 8er Bonus

### ISSUE THREAD

**Issue by Tweet1337** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2622]
**Welches Verhalten wird beobachtet?**
Der 8er-Bonus des Magier-T3-Sets zeigt keine Wirkung. Man bekommt den Buff, der einen 0 Aggro auf den nächsten Spell erzeugen lassen sollte, aber das passiert nicht. 

**Wie sollte es sich verhalten?**
Wenn man 8 Teile des T3-Magier-Sets angelegt hat, sollte man die 15%-ige Chance erhalten, mit dem nächsten Schadenszauber 0 Aggro zu erzeugen. Der Procc wird ausgelöst, man bekommt den Buff, dieser zeigt aber keine Wirkung. Die Aggro des darauffolgenden Spells (also mit Procc aktiv) wird im KTM ganz normal angerechnet, als ob man den Buff nicht hätte.

**Schritte zur Reproduzierung**
Zuerst dachte ich, dass es evtl. an KTM liegen könnte, woraufhin ich es mit 2 Chars getestet habe. Mit meinem Krieger habe ich in einem Tab einen Mob angehauen und so 200 Aggro im KTM auf dem Mob aufgebaut. Mit meinem Mage habe ich dann auf einem anderen Mob den Procc geholt, der eigentlich dafür sorgen sollte, dass der nächste Spell keine Aggro erzeugt. Daraufhin habe ich mit dem Procc den Mob des Warris angeschossen und sofort die Aggro bekommen, obwohl der Spell 0 Aggro hätte erzeugen sollen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
/

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein:**
Ein Teil des T3-Sets, Robe: https://datenbank.classic-wow.org/?item=22496
8er-Bonus-Procc: https://datenbank.classic-wow.org/?spell=28761
Der selbe Procc auf WoW-Head, mit %-Chance-Angabe: https://de.wowhead.com/spell=28761/nicht-dort#used-by-item-set

LG Tweet

**Comment by Haudraufinix** [comment]
Test mal ob du die Aggro tatsächlich nicht kriegst. KTM schätzt die Aggro anhand des Combatlogs ab. Wenn KTM den T3 Buff nicht kennt/Auswertet, dann wird der Spell im KTM gerechnet, als würde er Aggro generieren.

In dem Falle wärs also ein Addonfehler, kein Spielfehler.
Erst wenn du tatsächlich Aggro ziehst mit einem 0 Aggro Spell weisst du das es ein Spielfehler ist.

Idealerweise lässt du einen Tank nen Mob pullen und Blutrausch benutzen (Aber sonst nichts machen). Dann Zauberst du auf andere Mobs ein, bis der Effekt Procct. Wenn du den Mob vom Tank mit einem Feuerschlag triffst sollte er zu dir Laufen, wenn die Aggroreduktion nicht funktioniert

**Comment by Tweet1337** [comment]
Hey Haudraufinix - siehe "Schritte zur Reproduzierung" ^^

**Comment by Haudraufinix** [comment]
Kommentar schon gelöscht, war wieder schneller im Tippen als im Denken ;)

**Comment by Tweet1337** [comment]
Hey, mal vorsichtig angefragt: ist in näherer Zukunft ein Fix geplant? 

Ist schon sehr schade, jeden Tag das für Mage beste Set im Inventar liegen zu sehen und der wichtigste Bonus funktioniert nicht :-(

lg Tweet
