### ISSUE TITLE
Jäger Zorn des Wildtiers / bestial Wrath

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2624]
Welches Verhalten wird beobachtet?
Der Zauber Zorn des Wildtiers (https://datenbank.classic-wow.org/?spell=19574) kann gewirkt werden, wenn das Pet nicht im  Sichtfeld ist, geht dabei auf CD und berechnet seine Kosten, gewährt dem Pet aber nicht den dazugehörigen Buff

Wie sollte es sich verhalten?
Der Zauber sollte auf das Sichtfeld des Jägers limitiert sein.

Schritte zur Reproduzierung
Pet ausserhalb des Sichtfelds abstellen, Zorn des Wildtiers zaubern

**Comment by Donf4b** [comment]
Darf ich fragen warum das Problem hier und bei ticket [#2623](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2623) angegangen wird, bei ticket [#2559](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2559) aber unzureichende Quellenangaben sind?

Was fehlt denn bei #2559, was hier nicht fehlt?

**Comment by dagochen** [comment]
#2559 ist irgendwie auch schwierig, weil es 3 verschiedene bugs sind....in einem report.

**Comment by Donf4b** [comment]
naja ich finde halt dass es ziemlich eindeutig ist, dass diese Fehler nicht gewollt sind und das ganze mit "unzureichende Quellenangabe" zu schließen nicht ganz richtig.

wenn man die fehler kennt, kann man damit umgehen.
Anders sehe ich das ganze beim Ticket #2562. Mit der Funktion, die Auren beim erhalt und beim verschwinden als text über dem char anzeigt ist es während eines Kampfes teilweise sehr störend.
Mit dabei sogar ein video mit beweis wie es damals war.
Klar müsste es eigentlich passen wenn man alle 3 sekunden den buff neu erhält, der selbst 4 sekunden lang hält. da es aber in der Praxis eben nicht so ist, könnte man da nicht die buffdauer auf 5 sekunden setzen und alle 3 sekunden erneuern?
oder ist auch hier keine einfache behebung möglich?
