### ISSUE TITLE
[Naxxramas] Die Leerenzonen bei Lady Blaumeux sind manchmal fast unsichtbar

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2628]
**Welches Verhalten wird beobachtet?**

Wenn Lady Blaumeux eine Leerenzone platziert dann ist sie manchmal fast unsichtbar. Man sieht für Bruchteile von Sekunden eine schwarze Fläche, die aber verschwindet. Und danach sieht man nur ein schwaches bläuliches Leuchten.

**Wie sollte es sich verhalten?**

Die schwarze Fläche unter der Leerenzone sollte nicht verschwinden und immer sichbar sein.

**Schritte zur Reproduzierung**

Die vier Reiter angreifen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**

Lady Blaumeux:
https://datenbank.classic-wow.org/?npc=16065

Void Zone:
https://datenbank.classic-wow.org/?spell=28863

Grüße

**Comment by Dotox** [comment]
Dafür ist das bläuliche leuchten ja implementiert worden, damit Spieler wissen an welcher Stelle eine Voidzone ist. Die Voidzones sind auch damals durch den Boden gefallen, daher ist es für uns nicht möglich es zu fixen da es womöglich eine Änderung am Terrain benötigt (Client-Patch).

Die stärke des leuchten kannst du ja in deinen Grafik-Einstellungen optimieren.

**Comment by Suzaru** [comment]
@Dotox kannst du sagen, welche Grafikeinstellung genau die Sichtbarkeit erhöht? Vielleicht hilft das den Spielern ja :).
