### ISSUE TITLE
Maexxna greift Tanks im Kokon nicht an.

### ISSUE THREAD

**Issue by Toeterli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2631]
Welches Verhalten wird beobachtet?
Maexxna in Naxxramas verursacht keinen Schaden an Tanks, die in einen Kokon eingesponnen wurden.

Wie sollte es sich verhalten?
Maexxna sollte auch eingesponnene Tanks normal vermöbeln können.

Schritte zur Reproduzierung
Maexxna angreifen und den MT sterben lassen, während der zweite in der Aggroliste eingesponnen ist.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?npc=15952

**Comment by cowrea** [comment]
Ist mir gestern auch aufgefallen.

Tank gestorben ich war im Kokon (nicht Web spray)
Ich war als nächster in der Aggro.
Maexxna läuft unter mich, erreicht mich aber nicht.

Sah für mich nach zu wenig Range aus.
Ich war im südlichsten Kokon.

**Comment by Ulva-Anorhin** [comment]
Meinst du den Kokon an der Wand oder seine Phase?

**Comment by cowrea** [comment]
Ich spreche von dem an der Wand.

Das hier müsste es sein:
https://datenbank.classic-wow.org/?npc=16486

**Comment by Ulva-Anorhin** [comment]
Dann weis ichs nicht, habe meinen Beitrag wieder gelöscht

**Comment by Dotox** [comment]
Maexxna kann keine Spieler im Kokon angreifen.
