### ISSUE TITLE
Fall in die Todesmiene.

### ISSUE THREAD

**Issue by Danga13** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2635]
Welches Verhalten wird beobachtet?
Man fällt von der Oberfläche im Klingenhügel (Westall) plötzlich durch den Boden in die Todesmiene.
Fallpunkt (wenn man in der Miene landet): 41, 79,8  -  Westall

Wie sollte es sich verhalten?
Man fällt nicht. Man kann normal gehen.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Wird ein Geländeproblem sein welches nur mit einem Clientpatch behoben werden kann.

**Comment by WOW-Player** [comment]
Gleichen effekt. Siehe #2653
