### ISSUE TITLE
Quest: "Die Anweisungen des Pariahs" (Maraudon) nicht lösbar

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#264]
**Wie sollte es sich verhalten?**
Mit Hilfe des Amuletts der Geister, das zuvor erbeutet werden muss, müssen die verschiedenen Geister der Zentaurenkhans feindlich geschaltet werden, sodass sie sich töten lassen, um die jeweiligen Quest-Edelsteine von ihnen zu erbeuten.

**Welches Verhalten wird beobachtet?**
Das Nutzen des Amuletts bei den Geistern hat schlicht keinerlei Wirkung. Dadurch lassen sich die Zentaurenkhan-Geister nicht bekämpfen, wodurch die Questitems nicht von ihnen gesammelt werden können.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Quest: http://datenbank.welli-it.de/?quest=7067
Amulett der Geister: http://datenbank.welli-it.de/?item=17757
Geist von Kolk: http://datenbank.welli-it.de/?npc=12240
Kolk: http://datenbank.welli-it.de/?npc=13742
Geist von Gelk: http://datenbank.welli-it.de/?npc=12239
Gelk: http://datenbank.welli-it.de/?npc=13741 
Geist von Magra: http://datenbank.welli-it.de/?npc=12241
Magra: http://datenbank.welli-it.de/?npc=13740
Geist von Maraudos: http://datenbank.welli-it.de/?npc=12242
Maraudos: http://datenbank.welli-it.de/?npc=13739
Geist von Veng: http://datenbank.welli-it.de/?npc=12243
Veng: http://datenbank.welli-it.de/?npc=13738

**Comment by obipwn** [comment]
push :/

**Comment by escobarabc** [comment]
push
quest: http://db.vanillagaming.org/?quest=7067
Amulet: http://db.vanillagaming.org/?item=17758

**Comment by hraesvelgr** [comment]
bitte nicht pushen. es wird gefixt wenn resssouren und zeit vorhanden sind. verlinkt wurde bereits auch alles...

**Comment by Dotox** [comment]
Bitte genau reproduzieren, was da nicht geht. Ich sitz jetzt hier und würde das gerne beheben, hab aber keine Ahnung was genau nicht funktioniert, ob man das Amulett bekommt bzw. erstellen kann oder nicht etc.
