### ISSUE TITLE
Der Entscheidungsschlag

### ISSUE THREAD

**Issue by nesferatuh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2641]
Welches Verhalten wird beobachtet?
Quest kann nicht abgegeben werden.
Wie sollte es sich verhalten?
Bringt Blutmagier Drazial 3 Skorpokzangen, 2 Geiermuskelmägen und 1 feuerverbrannte Eberlunge.
Schritte zur Reproduzierung
Bringt Blutmagier Drazial 3 Skorpokzangen, 2 Geiermuskelmägen und 1 feuerverbrannte Eberlunge. und versuch die quest abzugeben.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://imgur.com/a/ZGzhIge
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=2585

**Comment by Nifexx** [comment]
Quest abbrechen und wieder annehmen, dann sollte das funktionieren.

**Comment by Dotox** [comment]
Und oder den WDB Ordner löschen.
