### ISSUE TITLE
Kicherfangunterkiefer

### ISSUE THREAD

**Issue by nesferatuh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2642]
Welches Verhalten wird beobachtet?
Quest kann nicht abgegeben werden
Wie sollte es sich verhalten?
Bringt Blutmagier Drazial 3 Kicherfangunterkiefer, 2 feuerverbrannte Eberlungen und 1 Skorpokzange
Schritte zur Reproduzierung
Bringt Blutmagier Drazial 3 Kicherfangunterkiefer, 2 feuerverbrannte Eberlungen und 1 Skorpokzange und versuch die quest ab zu geben.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://imgur.com/a/tjwgXlY
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=2581

**Comment by Nifexx** [comment]
Quest abbrechen und wieder annehmen, dann sollte das funktionieren.

**Comment by Dotox** [comment]
Und oder den WDB Ordner löschen.
