### ISSUE TITLE
Lebenskraft des Ebers

### ISSUE THREAD

**Issue by nesferatuh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2643]
Welches Verhalten wird beobachtet?
Quest kann nicht abgegeben werden.
Wie sollte es sich verhalten?
Bringt Blutmagier Drazial 3 feuerverbrannte Eberlungen, 2 Skorpokzangen und 1 Basiliskengehirn.
Schritte zur Reproduzierung
Bringt Blutmagier Drazial 3 feuerverbrannte Eberlungen, 2 Skorpokzangen und 1 Basiliskengehirn und versuch die quest ab zu geben.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
https://imgur.com/a/pkflz9O
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://datenbank.classic-wow.org/?quest=2583

**Comment by Nifexx** [comment]
Quest abbrechen und wieder annehmen, dann sollte das funktionieren.

**Comment by Ulva-Anorhin** [comment]
Ja, sollte definitiv kein Bug sein. 
Hab die quest schon oft genug gemacht

**Comment by Dotox** [comment]
Und oder den WDB Ordner löschen.
