### ISSUE TITLE
Fordring Questreihe (Östliche Pestländer)

### ISSUE THREAD

**Issue by Slantje** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2648]
Welches Verhalten wird beobachtet?
Bei dem Punkt (Scarlet Subterfage) wo man eine Verkleidung bekommt und man in den Westlichen Pestländern nach Hearthglen gehen soll um dort in der Kaserne auf Herrn Fordring zu treffen, gibt es nun das Problem das dieser nicht anwesend ist und somit das Event nicht getriggert werden kann.

Wie sollte es sich verhalten?
Fordring anwesend, Event startet.

**Comment by Slantje** [comment]
Sehr gut nachgelesen Dovarion. Kann man in den einschlägigen Foren alles finden, aber diesmal wohl kein Mount für dich XD. ne Spaß bei Seite. Hilft mir alles gerade nicht, wieso weshalb warum ist mir alles bekannt, ging weniger um die Erkenntnis das der Bug existiert, sondern vielmehr um die Bitte diesen zu beheben, da er im Moment existent ist und man den NPC zurücksetzen sollte damit andere Ihre Quest erledigen können (unter anderem ich selber). Hab zwar nur noch 12 Minuten die Illusion, da der Rest der Zeit futsch ist durch immer wieder einloggen und schauen ob er da ist, hoffe mal ich kann wenn denn dann dem so sei, dass er wieder da ist, die Quest und das Event von der Zeit her noch abschließen. Um den Bug in Zukunft zu verhindern sollte man evtl. ab Start des Events einen Timer Scripten, welcher nach vielleicht 40 Minuten oder so (um genug Zeit zu haben alles easy abzuschließen) das ganze Scenario automatisch komplett resettet, sprich den alten Tirion despawnen lassen und einen neuen spawnen, also so zu sagen eine Schleife.

**Comment by Spleeny88** [comment]
Quest gestern problemlos abgeschlossen.
