### ISSUE TITLE
[PvP] Pets verfolgen Gegner wenn diese sich Tarnen

### ISSUE THREAD

**Issue by stva23** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2650]
**Welches Verhalten wird beobachtet?**
Wechselt ein Spieler in die Verstohlenheit (Elfen, Schurken, Kätzchen) nachdem ein Jäger oder WL bereits sein Pet auf den Spieler geschickt hat, so geht das Pet weiter auf den verstohlenen Spieler und holt ihn gegebenenfalls aus dem Stealth.

**Wie sollte es sich verhalten?**
Wie bei einem normalen Spieler sollte auch das Pet das Target verlieren.

**Schritte zur Reproduzierung**
Siehe Punkt 1

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Auch hier nur stellvertretend die Fähigkeit der [Elfen](https://datenbank.classic-wow.org/?spell=21009).

**Comment by stva23** [comment]
Tatsächlich, zum Glück hab ich da mit niemand gewettet :D. Wurde wohl erst in BC geändert.

**Comment by SirBeansen** [comment]
hihi
