### ISSUE TITLE
Zul'Farrak (ZF) Treppenevent / Wünschel-mato-Rute

### ISSUE THREAD

**Issue by treutz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2651]
Das ZF-Treppenevent funktioniert leider nicht ganz, wie es soll. Ursprüngliche Funktion:

- Schlüsselmeister wird umgehauen und der Schlüssel zu den Käfigen wird gelootet
- Die Käfige werden geöffnet und die vier Alli-Mobs (incl. Unteroffizier Bly) stehen oben an der Treppe
- Von unten kommen feindliche NPCs (die zum Event spawnen) und greifen in Wellen an / kommen hoch und werden von den vier freundlichen NPCs angeriffen (wichtig fürs Event, sonst wird das Runterlaufen nicht getriggert!)
- Wenn alle Wellen tot sind, laufen die NPCs runter
(bis hierhin ist alles OK)

Man kann nun Unteroffizier Bly ansprechen, er möchte einem doch bitte den Anteil geben (Sprechblase).
Ab hier geht es nicht weiter. Die Sprechblase scheint keine Funktion zu triggern.

Wie sollte es sich verhalten?
Die Sprechblase soll das Event triggern, wo alle vier NPCs:
- Oro Eyegouge: https://datenbank.classic-wow.org/?npc=7606
- Murta Bauchgrimm: https://datenbank.classic-wow.org/?npc=7608
- Weegli Lunte: https://datenbank.classic-wow.org/?npc=7607 und
- Unteroffizier Bly: https://datenbank.classic-wow.org/?npc=7604
feindlich werden und sich angreifen lassen und nach deren Tod soll sich das Holztor zum Endboss öffnen. Zusätzlich muss Unteroffizier Bly folgendes Quesetitem droppen: https://datenbank.classic-wow.org/?item=8548

Schritte zur Reproduzierung
- Event wie o.g. triggern - es gibt eine optionale Quest dazu: Wünschel-mato-Rute: https://datenbank.classic-wow.org/?quest=2768

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
(reiche ich nach)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
- optionale Quest: https://datenbank.classic-wow.org/?quest=2768
NPCs: 
- Oro Eyegouge (Name ingame weicht von der DB ab): https://datenbank.classic-wow.org/?npc=7606
- Murta Bauchgrimm: https://datenbank.classic-wow.org/?npc=7608
- Weegli Lunte: https://datenbank.classic-wow.org/?npc=7607 und
- Unteroffizier Bly: https://datenbank.classic-wow.org/?npc=7604

Viele Grüße und vielen Dank im Voraus
 Treutz

**Comment by Dotox** [comment]
Hey,

ich hab das Event neulich erst überarbeitet und eben auch nochmal getestet - hat problemlos funktioniert. Gab es bei euch irgendwelche Auffälligkeiten während dem Event? Sind am Ende alle NPCs der Gruppe noch am Leben gewesen oder ist während des Events einer davon gestorben?

**Comment by treutz** [comment]
Schönen guten Abend Dotox, 

die 4 NPCs standen da, wie auf dem Bild zu sehen und haben sich nicht mehr verändert. Bin mir nicht sicher, ob es nicht doch 5 waren.

Auffälligkeiten? Mein Twink (Level 43) ist ein Mal gestorben während des Events und ich habe ihn mit dem Main gerezzt (Kabel).

Nach dem Event habe ich den Bly mit meinem Main angesprochen, der die Quest nicht mehr hatte (Level 60): Die Sprechblase war da und hat sich klicken lassen - danach konnte ich ihn nicht mal mehr ansprechen.


Spiele mit nem deDE-Client.


Wenns bei Dir geklappt hat, würde ich es glatt noch einmal probieren jetzt am WE. Vielleicht stelle ich mich auch nur zu dämlich an.


Viele Grüße
 Sebastian (Treutz)

**Comment by treutz** [comment]
Hier noch ein Screenshot: https://www.bilder-upload.eu/bild-abc66e-1538203612.jpg.html

**Comment by treutz** [comment]
Habe das Event eben noch einmal gemacht - die gleichen 4 NPCs standen hinterher noch immer (obwohl 5 aus dem Käfig sind?!), aber das Event hat funktioniert -- und sogar das Tor hat sich geöffnet.

Funktioniert also alles einwandfrei. Danke Dotox! 👍

**Comment by Dotox** [comment]
Also das beschriebene Problem findet oder hat bei dir NACH dem Ansprechen stattgefunden? Oder konntest du ihn erst gar nicht ansprechen?
