### ISSUE TITLE
Krieger fällt bei Sturmangriff durch den Boden in darunterliegende Höhle

### ISSUE THREAD

**Issue by WOW-Player** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2653]
Welches Verhalten wird beobachtet?
Bei einem Sturmangriff fällt der Krieger in die darunter liegende Höhle. Gleich wie #2635 und wie #2421.
Ist reproduzierbar. Diesmal: Westfall, Dolchhügel. Siehe Video.

Wie sollte es sich verhalten?
Normaler Sturmangriff, fester Boden.

Schritte zur Reproduzierung
Als Krieger die Position oberhalb des NPC einnehmen, den NPC anvisieren und Sturmangriff. Habe dieses Verhalten mehrmals getestet, immer gleiches Ergebnis.

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Mensch Krieger Lvl. 18
[WOW-Bug.zip](https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/files/2423608/WOW-Bug.zip)
Bitte an Dotox:
Welcher Clientpatch? Wo erhältlich?
Bitte an alle Spieler: Testen! - Danke!

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.

**Comment by Dotox** [comment]
Es gibt kein Client-Patch dafür, dazu müssten die originalen WoW-Dateien verändert werden und sowas machen wir hier nicht.

**Comment by WOW-Player** [comment]
@Dotox:
Herzlichen Dank für die Erklärung, habe ich so nicht gewusst.
Kann man halt nichts machen.
Und nochmals vielen Dank!
