### ISSUE TITLE
Runenklinge von Baron Totenschwur - Zaubermacht

### ISSUE THREAD

**Issue by cowrea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2655]
### Welches Verhalten wird beobachtet?
"Runenklinge von Baron Totenschwur" skaliert nicht mit Zaubermacht.

### Wie sollte es sich verhalten?
Es sollte kein HP/5 Effekt sein, sondern eine Heilung alle 5 Sekunden welche auch mit Zaubermacht skalliert.

### Schritte zur Reproduzierung:
Mit nicht gefüllten HP in den Kampf gehen und schauen wie viel Gesundheit generiert wird.
Sofern man kein Troll ist und auch keine Items mit Hp/5 besitzt sollte exakt 0 Gesundheit generiert werden.
Sobald man das Runenschwert anlegt erhält man alle 5 Sekunden exakt 20 HP.
Diese 20 HP ändern sich aber nicht wenn man Zaubermacht anlegt.

### Zusätliche Informationen:
Das Item "Runenklinge von Baron Totenschwur" besitzt eine Aura.
Namentlich "Unholy Aura".
Diese Aura ist unsichtbar und hat zwei effekte.
Zum einen erhöht es das Bewegungstempo um 8%.
Dieser Effekt soll mit nichts stacken.
Der andere Effekt ist eine spezielle Gesundheitsregeneration.

Diese Gesundheitsregeneration ist kein einfacher 20 HP/5 effekt, sondern eine Heilung.
Sein Regenerationszyklus ist unter Umständen ein anderer wie der eigene HP/5 Zyklus.

Durch den Status als Heilungszauber soll dieser auch mit Gegenständen skalieren welche die Heilung erhöhen.

Vergleicht man diese Aura mit herkömlichen HP/5 Items wie bspw. dem Trinket von Onyxia so erkennt man bereits in unserer Datenbank einen Unterschied:

HP/5 Items werden gelistet als "Vitality".
Dieser hat einen Effekt mit dem Wert 7.
Kein Intervall o.ä. ist genannt.

Schaut man sich hingegen einen Heilzauber an, bspw. Erneuerung sieht das so aus:
Effekt 1 "ApplyAura: Periodic Heal"
Wert 194
Intervall: 3 Sekunden

Die "Unholy Aura" ist vom Schema her identisch:
Auch hier gibt es den Effekt #1.
Dieser heißt ebenfalls "Apply Aura: Periodic Heal".
Wert: 20
Intervall: 5 Sekunden

Heißt man sieht direkt in der Datenbank dass es kein HP/5 effekt ist, sondern ein Heilzauber alle 5 Sekunden.

Die These selbst stammt von "Zeliek" aus dem aktuellen Classic Forum von Blizzard:
https://us.battle.net/forums/en/wow/topic/20760205815?page=8#post-145

Hier heißt es :

> Runeblade of Baron Rivendare's unholy aura scaled with spell damage and healing. probably with +spell healing too but I was playing as ret so I never tried it. One of the most overlooked items because its ability is passive and doesn't show up in the logs. I loved that sword. Saved my !@# so many times.

Ein paar Posts später sagt er noch das dazu:
https://us.battle.net/forums/en/wow/topic/20760205815?page=8#post-149

> Others didn't notice until I think it was "Sheath of Light" with WotLK as it gives passive 30% of attack power as spellpower. I noticed it around patch 1.11 as I had a few of the new spell damage plate items. I used it to level in outlands as a spell damage ret because crusader strike scaled with spell damage >.< for a short while. Around 62 I gave up and started grabbing the strength gear and it was great.

Nun hat man die These dass es so sein könnte.

Schaut man nun auf WoW-Head so ist die These mehrfach bestätigt, dass es zumindest in nachfolgenden Addons so ist.
https://www.wowhead.com/item=13505/runeblade-of-baron-rivendare#comments

"Zansky" sagt am 31.05.2010 zum Patchstand 3.3.3 folgendes:

> The life regen upon equiping seems to be 30hp5 increased by ~100% of your spellpower
> On my ret pala it's ticking well over 1.5k hp every 5 seconds, which makes it awesome for passive healing, should you ever need that

https://www.wowhead.com/item=13505/runeblade-of-baron-rivendare#comments:40
"harmil" sagt am 08.02.2011 zu Patch 4.0.6

> With sword: 1770/26sec = 68.1 health/sec
> Without sword (empty slot): 1770/84sec = 21.1 health/sec

Unholy Aura
https://datenbank.classic-wow.org/?spell=17625

Runenklinge von Baron Totenschwur
https://datenbank.classic-wow.org/?item=13505

Talisman mit Onyxiablut
https://datenbank.classic-wow.org/?item=18406

Vitality
https://datenbank.classic-wow.org/?spell=21601

Erneuerung
https://datenbank.classic-wow.org/?spell=25315

**Comment by dagochen** [comment]
Ja und wie stark soll das skalieren zu classic?
