### ISSUE TITLE
Krieger: Sturmangriff in "Koven der brennenden Klinge"

### ISSUE THREAD

**Issue by HeikoAA** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2658]
**Welches Verhalten wird beobachtet?**
Innerhalb der "Koven der brennenden Klinge" (Höhle im Norden des Startgebiets der Orks und Trolle im "Tal der Prüfungen" in Durotar) ist der Sturmangriff teilweise fehlerhaft:
a) Manchmal wird kein Pfad gefunden, obwohl das Monster ("Übler Familiar" bzw. "Teufelspirscher") direkt vor einem ist.
b) Schwerwiegender: Manchmal rennt der Krieger bei einem Sturmangriff soweit, dass er durch die Hügel rennt und im Freien wieder rauskommt.

**Wie sollte es sich verhalten?**
a) Es sollte ein Pfad gefunden werden, wenn der Weg eben ist und keine Hindernisse vorhanden sind.
b) Der Sturmangriff sollte nicht aus der Höhle führen.

**Schritte zur Reproduzierung**
Innerhalb der "Koven der brennenden Klinge" mittels "Sturmangriff" des Kriegers angreifen.

**Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)**
Klasse: Krieger
Rasse: Ork
Level: 5 bis 8
Sieht für mich wie der Bug #1564 aus.

**Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.**
Sturmangriff: https://datenbank.classic-wow.org/?spell=100
"Übler Familiar": https://datenbank.classic-wow.org/?npc=3101
Teufelspirscher: https://datenbank.classic-wow.org/?npc=3102

**Comment by Ulva-Anorhin** [comment]
Bekannter Bug
Siehe zb auch: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2653
