### ISSUE TITLE
Blessed Wizard Oil Buffdauer

### ISSUE THREAD

**Issue by zwirbl** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2666]
### Welches Verhalten wird beobachtet?
Das Blessed Wizard Oil, welches im Rahmen des Naxx Pre-Events erhältlich ist, hat eine Wirkungsdauer von 30min.

### Wie sollte es sich verhalten?
Laut Tooltip und DB beträgt die Wirkungsdauer 60min.

### Schritte zur Reproduzierung
Blessed Wizard Oil auf eine Waffe auftragen und verbleibende Wirkdauer anschauen.

Blessed Wizard Oil https://classicdb.ch/?item=23123

**Comment by Dotox** [comment]
Tooltip ist falsch; falscher DB-Link btw.

**Comment by zwirbl** [comment]
https://www.youtube.com/watch?v=CVqvIclhiqQ&feature=youtu.be&t=1m1s 
oben links verbleibende Buffzeit auf seine Waffe 48min

**Comment by zwirbl** [comment]
und diese quelle bei der es nur 30min anhält
https://www.youtube.com/watch?v=EXgqgDMoj9w
ab 9:11 
Damit kann ich also leben
