### ISSUE TITLE
Naxx Opening Event - Phase 2 startet nicht

### ISSUE THREAD

**Issue by zwirbl** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2667]
### Welches Verhalten wird beobachtet?
Nach dem Vernichten zahlreicher Mobs um den Nekrotischen Splitter kann es vorkommen, dass alle noch im Kampf befindlichen Gegner "einfrieren". Es ist weder möglich, sie anzugreifen, noch ist es möglich, zu dem Zeitpunkt tote Mobs zu looten. Der Nekrotische Splitter verschwindet und es findet keine P2 statt.
Dieser Bug scheint nicht immer aufzutreten, ich habe gestern ein Event beobachtet, welches regulär ablief (Burning Steppes). Seitdem jedoch auch zwei Events beobachtet, bei dem eben beschriebenes stattfand.

### Wie sollte es sich verhalten?
Wenn der Nekrotische Splitter auf 0% ist, sollte der Kampf gegen die normalen Mobs regulär weitergehen. Außerdem beginnt P2. 4 Kultistingenieure spawnen, beginnen mit der Reparatur des Splitters und lassen sich im Rahmen der Quest "Schatten der Verdammnis" zu legbaren Mobs "Schatten der Verdammnis" umwandeln.

### Schritte zur Reproduzierung
Das Event bei einen Nekrotischen Splitter durchführen und versuchen, P2 zu erreichen.

### Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Ich verzichte an dieser Stelle auf Quellen, da es bereits in der Vergangenheit Probleme mit dem Event gab, welche reportet/gefixt wurden, der reguläre Ablauf sollte hinlänglich bekannt sein.
z.B. https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2444

### Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Nekrotischer Splitter: https://datenbank.classic-wow.org/?npc=16136
Beschädigter nekrotischer Splitter: https://datenbank.classic-wow.org/?npc=16172
Kultisteningenieur: https://datenbank.classic-wow.org/?npc=16230
Quest "Schatten der Verdammnis": https://datenbank.classic-wow.org/?quest=9085

**Comment by zwirbl** [comment]
Ergänzung: Gibt es für das Event einen Timer? Beide Male, als die Kultisten erschienen sind, standen mehrere Gruppen am Nekrotischen Splitter und haben Mobs in Hochgeschwindigkeit gefarmt. Die 4 Male, die es nicht geklappt hat, waren wir eine einzelne Gruppe und entsprechend nicht so schnell unterwegs.

Sollte dies so beabsichtigt sein, bitte closen. Kann keine Quelle finden die für oder gegen einen Timer spricht.

**Comment by Dotox** [comment]
Ja das ist ein Workaround, da das Event ggf. feststecken kann.

**Comment by Mathemagier** [comment]
Hallo zusammen,
das Problem besteht nach wie vor. Da das Interesse an Nekrotischen Runen spürbar nachgelassen hat, ist es in den letzten Tagen kaum möglich gewesen, den Splitter in Phase 2 zu bekommen. Eventuell kann man sich das ja nocheinmal anschauen. 
VG
