### ISSUE TITLE
JomGabbar

### ISSUE THREAD

**Issue by MikazaLegion** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2678]
Welches Verhalten wird beobachtet?
Nach der Benutzung des Schmuckstück Jom Gabbar (https://datenbank.classic-wow.org/?item=23570) wird der 2 Minuten Cooldown auch auf alle anderen Trinkets getriggerd.
Wie sollte es sich verhalten?
Der Cooldown sollte sich lediglich auf das benutzte Trinket beschränken und nicht die anderen CDs triggern.
Schritte zur Reproduzierung
Jom Gabbar ausrüsten und den USE Effekt benutzen.
Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)
Die Offiziellen PatchNotes von 1.12 und da wurde der bekannte Fehler gefixxt - http://wowwiki.wikia.com/wiki/Patch_1.12.0
Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
https://www.warcraftmovies.com/movieview.php?id=31393
https://www.youtube.com/watch?v=mEra4q8tXhU

**Comment by Haudraufinix** [comment]
Kopie von https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1550

**Comment by MikazaLegion** [comment]
https://www.warcraftmovies.com/movieview.php?id=31393
https://www.youtube.com/watch?v=mEra4q8tXhU

hier nochmal 2 links mit upload video von 2006 um das zu beweisen
