### ISSUE TITLE
Erzvorkommen mehrmals abbaubar

### ISSUE THREAD

**Issue by Lyychee** [ClassicWoW/Nefarian_1.12.1_Bugtracker#2679]
Welches Verhalten wird beobachtet?
Ein Erzvorkommen war mehrmals hintereinander abbaubar, ohne dass es zwischenzeitlich despawnt ist.
Insgesamt 4x. Jedes mal waren Erze etc. (s. u.) darin vorzufinden.
Zeit: 5.12.2018,  zwischen 20.45 und 20.50 Uhr

Wie sollte es sich verhalten?
Nachdem es 1x abgebaut wurde, sollte es auch despawnen. Erst dann sollte das Erzvorkommen nach einiger Wartezeit wieder verfügbar sein.

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, Klasse, Rasse, Level, etc.)

![1](https://user-images.githubusercontent.com/45639741/49541163-43da4a00-f8d2-11e8-916e-96d50e8f46c6.jpg)
![2](https://user-images.githubusercontent.com/45639741/49541167-463ca400-f8d2-11e8-907e-2be83d530108.jpg)

Alle Kreaturen, Items, Objekte, Quests, Zauber etc. müssen aus unserer Datenbank verlinkt sein.
Erhaltene Gegenstände
Überflüssig erhaltene Gegenstände (abzgl. des ersten Abbaus, das war 1x Kupfererz)

Kupfererz 5x
https://datenbank.classic-wow.org/?item=2770

Schattenedelstein 1x
https://datenbank.classic-wow.org/?item=1210

Rauer Stein 2x
https://datenbank.classic-wow.org/?item=2835

Summe Gegenstände = 8

**Comment by Dotox** [comment]
Danke für deinen Report. Allerdings war das zu Classic so, also alles korrekt.
