### ISSUE TITLE
Hexenmeister: Teufelsbeherrschung wirkt nicht mehr bei abgebrochener 1. Beschwörung

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#271]
**Welches Verhalten wird beobachtet?**

Beschwört man mit aktivierter "Teufelsbeherrschung" einen Diener und bricht die Beschwörung ab, so wird der Geschwindigkeits- und Manabonus bei einer erneuten Beschwörung nicht mehr berücksichtigt, obwohl die Teufelsbeherrschung noch läuft, der Buff also aktiv ist.

**Wie sollte es sich verhalten?**

Nicht nur der angezeigte Buff, sondern auch die Wirkung der Teufelsbeherrschung sollte bei abgebrochener Beschwörung erhalten bleiben.

**Schritte zur Reproduzierung**

Teufelsbeherrschung aktivieren, Diener beschwören, Beschwörung abbrechen, erneut Diener beschwören.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Teufelsbeherrschung: http://datenbank.welli-it.de/?spell=18708
Meister der Beschwörung Rang 1: http://datenbank.welli-it.de/?spell=18709 
Meister der Beschwörung Rang 2: http://datenbank.welli-it.de/?spell=18710
Wichtel beschwören: http://datenbank.welli-it.de/?spell=688
Leerwandler beschwören: http://datenbank.welli-it.de/?spell=697
Teufelsjäger beschwören: http://datenbank.welli-it.de/?spell=691
Sukkubus beschwören: http://datenbank.welli-it.de/?spell=712

Screenshot zeigt die 2. Beschwörung nach abgebrochener 1. Die Dauer der Beschwörung ist nur noch von Meister der Beschwörung beeinflusst, obwohl der Teufelsberrschung noch aktiv ist.
http://imageshack.com/a/img537/953/sfxr3J.png

**Comment by Armauskugelbob** [comment]
push

**Comment by Gnomorus** [comment]
Behoben und getestet mit 1.0.5.
