### ISSUE TITLE
Franclorn Schmiedevater: fälschlicherweise sichtbar, wenn man am Leben ist

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#275]
**Welches Verhalten wird beobachtet?**

Franclorn Schmiedevater ist fälschlicherweise sichtbar, auch wenn man sich gerade bester Gesundheit erfreut.

**Wie sollte es sich verhalten?**

Franclorn Schmiedevater sollte nur für Geister bzw. freigelassene Geister sichtbar sein.

**Schritte zur Reproduzierung**

Lebendig zum entsprechenden Mob gehen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Schmiedevater mit lebendigem Gnom sichtbar:
https://imageshack.com/a/Eqfz/1

Franclorn Schmiedevater: http://datenbank.welli-it.de/?npc=8888

http://wowdata.buffed.de/npc/Franclorn-Schmiedevater-8888#comments
*1. sterben (vorher kleidung ausziehen is recht vorteilhaft, repkosten und so)
2. in den blackrock rein
3. kette runterlaufen bis man in nem raum ist, der sich grabmahl nennt
4. zwergengeist ansprechen und gg*

http://de.wow.wikia.com/wiki/Franclorn_Schmiedevater
*Man kann ihn aber nur sehen wenn man tot ist.Dann steht Er auf seinem Grab.*

**Comment by Larnak1** [comment]
Gilt auch für Gaeriyan: http://datenbank.welli-it.de/?npc=9299
Geht hervor aus der Questbeschreibung sowie der Tatsache, dass Extra zum "Geist-Sehen" ein Trank besorgt werden muss, der den Spieler bei Konsum tötet:
http://datenbank.welli-it.de/?quest=3912
