### ISSUE TITLE
Gromsblut: Spawn unter der Erde/nicht lootbar

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#282]
**Welches Verhalten wird beobachtet?**

In den verwüsteten Landen gibt es 1 Gromsblut (ca. bei 56,51) , das anscheinend unter der Welt oder in einem Stein steht und somit nicht lootbar ist. Dies ist schon länger so und bestimmt auch unter den Kräuterern bekannt.

**Wie sollte es sich verhalten?**

Dadurch, dass jetz die Spawns zahlenmäßig beschränkt sind, sollte dieses eine Gromsblut entfernt oder versetzt werden, um die fröhliche Farmerei nicht zu beeinflussen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Gromsblut: http://datenbank.welli-it.de/?object=142145

Screenshots (wie man sieht mit nicht sichtbarem Gromsblut)
https://imageshack.com/a/DSfz/1

**Comment by dagochen** [comment]
#1085
