### ISSUE TITLE
Plündern als Gruppe: Gegenstand nicht plünderbar, wenn er mit vollem Inventar gewonnen wurde

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#283]
**Welches Verhalten wird beobachtet?**

Wird im Plündermodus "Plündern als Gruppe" ein Gegenstand gewonnen, während das Inventar voll ist, gewinnt man zwar den Gegenstand, hebt ihn aber richtigerweise nicht auf.
Nachdem man Platz im Inventar geschafft hat, kann man den Gegenstand jedoch nicht mehr plündern. Sowohl mit Plündern als Gruppe und "Jeder gegen Jeden" ist dies nicht möglich. Mit "Jeder gegen Jeden" konnte man vor dem Patch den Gegenstand nachträglich noch plündern, was jetzt auch nicht mehr möglich war.
Die Gruppenmitglieder können jedoch den betreffenden Gegenstand plündern, obwohl sie ihn nicht einmal gewonnen haben.

**Wie sollte es sich verhalten?**

Nachdem man Platz im Inventar geschaffen hat, sollte der Gegenstand auch mit Plündern als Gruppe für den jeweiligen Gewinner zu plündern sein.

**Schritte zur Reproduktion**

Plündermodus "Plündern als Gruppe" einstellen, Inventar randvoll füllen, einen Gegenstand gewinnen, Platz im Inventar schaffen, plündern wollen.
Das Ergebnis sieht man im angehangenen Screenshot.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

https://imageshack.com/a/ESfz/1

**Comment by Archidamos** [comment]
Kann ich bestätigen
