### ISSUE TITLE
Hunter Schlangenbiss Spelldmgkoeff.

### ISSUE THREAD

**Issue by drgrey** [ClassicWoW/Nefarian_1.12.1_Bugtracker#29]
Der Spelldamagekoeffizient für den Schlangenbiss des Jägers stimmt nicht. Dieser sollte 1 betragen, beträgt allerdings 0. Gerade heute an den Puppen getestet: Serpent Sting skaliert nicht mit Spelldamage.

Quelle:
http://www.wowwiki.com/Spell_damage_comparison?oldid=310234

**Comment by Haudraufinix** [comment]
Ich habe selber nachforschungen dazu angestellt, und ich glaube um ehrlich zu sein, WoWwiki ist hier nicht Akkurat. genaueres auf https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/503

Sry bin zu dumm diese beiden Themen zu verlinken
