### ISSUE TITLE
Todesminen Verlinkung Handlanger Pein

### ISSUE THREAD

**Issue by Memphisrain** [ClassicWoW/Nefarian_1.12.1_Bugtracker#291]
Welches Verhalten wird beobachtet?
Boss beim Schiff in den todesminen sollte mit 2 Adds kommen.
Wenn man ihn Pullt kommt das halbe oberdeck des schiffes mit.
Ca 8 -10 Mobs inkl Pain. Das sind die Mobgruppen die Links und Rechts von ihm stehen

Wie sollte es sich verhalten?
Er sollte langsam runter laufen und 2 Adds dabei haben, 2 schurken.

Schritte zur Reproduzierung
Boss normal pullen und zuschauen wie alles angerannt kommt.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank
http://datenbank.welli-it.de/?npc=646

Zusätzliches

**Comment by prydox** [comment]
irgendwie hat sich da immernoch nichts getan

**Comment by Rushor** [comment]
wird sich schon bald jemand drum kümmern ^^
