### ISSUE TITLE
PvP Dämon banish

### ISSUE THREAD

**Issue by Armauskugelbob** [ClassicWoW/Nefarian_1.12.1_Bugtracker#299]
Der Dämon eines gegnerischen Spielers lässt sich nicht verbannen.
Das Spiel gibt uns aus, dass es kein gültiges Ziel sei.

Wie es sein sollte:
Das pet sollte als Dämon erkannt werden und somit auch verbannbar sein.

**Comment by Armauskugelbob** [comment]
push

**Comment by SirBeansen** [comment]
btw können pets im cc auch weiter angreifen. Spieler auch, solange sie im direkten sichtfeld bleiben.
