### ISSUE TITLE
Quest: "Das Gleichgewicht der Natur" in Shadowglen - Falsche Anzahl an Questitems

### ISSUE THREAD

**Issue by oooverclocker** [ClassicWoW/Nefarian_1.12.1_Bugtracker#300]
![wowscrnshot_122014_033623](https://cloud.githubusercontent.com/assets/273609/5513566/a4624e14-87fb-11e4-991f-d2639e75dc9f.jpg)
Edit: Der Quest ist trotzdem abschließbar aber intern scheinen je 5 eingetragen zu sein, sodass der falsche Text angezeigt wird, als wenn man die Questziele noch nicht erfüllt hätte.

**Comment by oooverclocker** [comment]
![nochnquest](https://cloud.githubusercontent.com/assets/273609/5623133/65ab085e-954e-11e4-9fe5-b9ef732b4a12.jpg)

Bei der Quest "Die Straße nach Darnassus" wird ebenfalls der Text angegeben, als ob man die Aufgabe nicht erfüllt hätte.

**Comment by dagochen** [comment]
Quest problemlos durchführbar.
