### ISSUE TITLE
Fear im arathibecken

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#302]
Welches Verhalten wird beobachtet?
Wenn man gefeart wird an sw oder sm kann man die kanten der berge herunterfallen....also von der base.

Wie sollte es sich verhalten?
Man sollte eigentlich nicht an stellen gefeart werden an den dann nach fear ende herunterfallen kann.

Schritte zur Reproduzierung:
Jemanden in der nähe von den Kanten an sw fearen.

Links aus unserer Datenbank:

http://datenbank.welli-it.de/?spell=6216
http://datenbank.welli-it.de/?spell=10891
http://datenbank.welli-it.de/?spell=5246
http://datenbank.welli-it.de/?spell=17928

Ich hoffe das sind die richtigen spells ansonsten eben berichtigen wie mans richtig machen soll.

**Comment by Dotox** [comment]
Tritt das immernoch auf?

**Comment by hraesvelgr** [comment]
schon ein ganzes stück her. mir selber ist es schon lange nicht mehr passiert. nur mindcontrol ist nervig, aber dagegen kann man nix machen :^)

**Comment by dagochen** [comment]
Hatte Wahax vor langer Zeit gemacht.

**Comment by SirBeansen** [comment]
bei sheep, blind und scatter ist es immernoch so
