### ISSUE TITLE
Alteractal - Türme der Allianz

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#305]
Was wird beobachtet:
Im Alteractal befinden sich immer noch Marshalle in den einzelnen Türmen, in denen der Horde nach wie vor keine.

Wie sollte es korrekt sein:
Weder in den Allianz noch in den Hordetürmen sollten Marshalle und Kriegsmeister stehen. Lediglich eine Elitewache, welche den Turmeingang verteidigt. Z.B. Mortimer, Philipps etc. ...
...Ich verweise erneut auf den Report 233, in dem wir viele Belege und Erläuterungen gepostet haben:

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/233

Edit:
Da dass Anchargen der Krieger nun korrekt funktioniert, ist es fast unmöglich einen Turm mit 4 -5 Angreifern einzunehmen und zu halten, sobald ein o. zwei Allianzler verteidigen und die Angreifer verlangsamen o. in den Marshall pullen. Diese haben ca. 160 000 HP und Gleaven immer noch mit 2000 - 3000 Schaden.

Die Hordentürme können dagegen durch mind 1 Allianzler problemlos eingenommen werden.

Die angekündigten Verbesserungen des AVs führen leider nicht zu einem ausgeglichenen Kampf...eher im Gegenteil. Wenn man sich die Chats der Horde durchliest...schwindet des Motivation sich beim AV anzumelden rapide.

Daher die erneute Bittte, diesen Bug endlich zu beheben...Oder einfach die Marshalle der Allys raus o. welche bei den Hordis rein..sodass wenigstens gleiche Voraussetzungen bestehen.

**Comment by drgrey** [comment]
/push.
war letztes WE noch so
