### ISSUE TITLE
PvP Schlachtzugsanmeldung nicht möglich?

### ISSUE THREAD

**Issue by Thay-skill3d** [ClassicWoW/Nefarian_1.12.1_Bugtracker#31]
Anscheinend ist es jedem Spieler bekannt, dass man mit einem Schlachtzug nicht bei einem Schlachtfeld anmelden kann - Niemand bekommt dabei eine Einladung.

Ist dieser Fehler denn auch den Admins bekannt, bzw. wurde das schon einmal überprüft?

**Comment by Thay-skill3d** [comment]
Dotox? Gibts zu dem Thema was neues?

**Comment by dagochen** [comment]
Das Anmelden im Schlachtzug funktioniert bereits. Falls für die anderen Themen noch irgendwas benötigt wird, bitte ein neues und frisches Ticket aufmachen. Danke!
