### ISSUE TITLE
Marschall von Vanndar (Alterac valley)

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#314]
Welches Verhalten wird beobachtet?
Die Marschall sind für die Horden spieler einzel pullbar. Als gegenstück die Horde NPC sind in der Base verlinkt und nicht so leicht pullbar.

Wie sollte es sich verhalten?
Tja das es für die Allianzer extra schwerer gemacht wurde und alle Kriegsmeister verlinkt sind, andauernd während des Pulls oder des fightes reseten.....solllte man es bei den Marschall auch so machen. Auch wenn ich der meinung bin man konnte sie früher  einzeln pullen.....auf beiden Seiten.

Links aus unserer Datenbank (hier gehts zur Datenbank)

http://datenbank.welli-it.de/?npc=14766
http://datenbank.welli-it.de/?npc=14764
http://datenbank.welli-it.de/?npc=14762
http://datenbank.welli-it.de/?npc=14765
http://datenbank.welli-it.de/?npc=14763
http://datenbank.welli-it.de/?npc=14768
http://datenbank.welli-it.de/?npc=14767
http://datenbank.welli-it.de/?npc=14769

**Comment by Haudraufinix** [comment]
Ich meine mich zu erinnern, dass immer Hunter gepullt haben, ein anderer Spieler den Mob anschlagen musste und der Hunter dann Totzustellen um die restlichen loszuwerden. Beim Pull ohne reset war schnell der Vorplatz vor den Gebäuden mit cleavenden und wirbelnden Marschällen voll

Ist allerding nur meine Erinnerung, ich versuch mal ne Quelle zu finden
