### ISSUE TITLE
Hunter Pet reset

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#316]
Welches Verhalten wird beobachtet?
Es passiert öfters dass das ein Hunter pet einfach resetet wenn man es auf ein Target schickt. Besonders im PvP. Man schickt es auf pvp Ziel und es resetet andauernd.

Wie sollte es sich verhalten?
Es sollte nicht einfach reseten.

Schritte zur Reproduzierung
Einen grund habe ich schon gefunden:
Pet auf ein Ziel schicken. >
Dann das Pet auf ein zweites Ziel schicken >
währendessen das erste add killen >
man kommt out fight und das pet resetet bevor es das zweite add angreift (an besten im low lvl bereich testen mit einem 60iger)
Besonders schlimm ist es im pvp da kommt vielleicht noch des gegnas kampf status mit rein.

**Comment by wahaxlekuke** [comment]
Tritt das Problem immer noch auf?

**Comment by SirBeansen** [comment]
Sorry hab nicht mehr lange rein geschaut und es ist zurzeit noch viel schlimmer.....das pet ressetet nurnoch.

**Comment by SirBeansen** [comment]
push
