### ISSUE TITLE
Wichtel greift nicht an!

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#317]
Welches Verhalten wird beobachtet?
Der Wichtel des Hexenmeisters hat bei mir in den Hügeln von Razorfen in Defensivstellung keine Feuerblitze gecastet, nur wenn ich den Feuerblitz manuell bediente.

Wie sollte es sich verhalten?
Der Wichtel sollte sobald sein Meister in den Kampf eingreift(aktiv) auch selbst zu casten beginnen.

Schritte zur Reproduzierung:
Mit Wichtel (vl. auch nur mit Wichtel der geskillten Feuerblitz hat(Dämonologietalentbaum Talent: Verbesserter Wichtel) in eine Instanz und auf  Defensiv stellen .--> beobachten

**Comment by Archidamos** [comment]
Mein Wichtel geht immer noch in den Nahkampf... wundert mich, dass es als Behoben markiert wird

**Comment by Larnak1** [comment]
Hier geht es ja nicht um den Nahkampf, sondern um den fehlerhaften Feuerblitz. Das Nahkampf-Problem ist oben verlinkt. :)
