### ISSUE TITLE
Segnung - 2% Critchance

### ISSUE THREAD

**Issue by Pannndara** [ClassicWoW/Nefarian_1.12.1_Bugtracker#318]
Welches Verhalten wird beobachtet?
Die 2% Crit auf Segnung werden nicht auf die Holycritchance angerechnet

Wie sollte es sich Verhalten? 
Segnung sollte die Hoylcritchance um 2% erhöhen

Wege zur Reproduktion
Segnung an/ ausziehen, keine veränderung bei der Holycritchance

Links aus der Datenbank:
http://datenbank.welli-it.de/?item=18608
![wowscrnshot_122214_132848](https://cloud.githubusercontent.com/assets/10259447/5525224/c3750088-89e2-11e4-9030-8ac599bac451.jpg)
![wowscrnshot_122214_132857](https://cloud.githubusercontent.com/assets/10259447/5525228/d0f71d22-89e2-11e4-9c95-3e84cf980b42.jpg)

**Comment by Ministry1990** [comment]
@hraesvelgr Bei jedem anderen Gegenstand mit Holy-Crit, den wir angezogen haben, hat Theory Craft die richtigen Werte angezeigt, nur bei Segnung nicht.

@Staff Label adden?

**Comment by Gnomorus** [comment]
Kann geschlossen werden. Ist ein Lokalisationsproblem in Theorycraft. Die dortige Suchmaske lautet "Erhöht Eure Chance, einen kritischen Treffer durch Heiligzauber zu erzielen, um (%d+)%%%..". Von daher ist klar, dass der Heiligcrit auf Segnung nicht erkannt wird.

**Comment by hraesvelgr** [comment]
sagte ich ja....theorycraft ist nicht verlässlich...
