### ISSUE TITLE
Allgemein: Quest-Erfahrung

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#320]
Mir ist in letzter Zeit aufgefallen, dass ich enorm viel (zu viel) Erfahrung für Quests bekomme und wollte das hier mal beispielhaft angeben.

Gerade habe ich für diese Quest:
http://datenbank.welli-it.de/?quest=5385/Die%20%C3%9Cberreste%20von%20Trey%20Lichtschmied
22.000 Erfahrung bekommen, das ist mehr als 10% vom Level und für lvl 58 damit viel zu viel. 

Ich habe hier ein altes Buch, "WoW: Das offizielle Strategiebuch", in dem alle Quests tabellarisch aufgelistst sind. Der Stand ist sicher einige Patches vor 1.12.1, allerdings sind mir aus dem Zeitraum keine signifikanten Änderungen an den Questerfahrungen bekannt. In diesem Buch ist die maximal mögliche Erfahrung (Sprich: Erledigung auf Minimallevel) für diese Quest 7550. Auf meinem Level dürfte die Erfahrung 3000 oder 4450 betragen (Ich weiß nicht, wie genau die Einteilung der XP-Stufen nach Level erfolgt; Ich nehme an, dass die beiden höchsten XP-Stufen (6050 und 7550) orange und rot vorbehalten sind, sodass einer dieser Werte zutreffend wäre).
Die tatsächlichen XP wären demnach um ein Vielfaches zu hoch.

Die Quest ist ein Extrembeispiel, die meisten Quests, die ich gerade abschließe, geben 16.500 XP, immer noch sehr viel (Und der Sollwert liegt bei diesen auch wieder geringer)

PS: .rate 2 nutze ich nicht, ich habe es, um sicher zu gehen, sogar explizit auf 1 gestellt.

**Comment by dagochen** [comment]
@Larnak1 Kannst du hier handfeste Zahlen für EP-Werte für fehlerhafte Quests liefern? Dann kann ich hier tätig werden, ansonsten weiß ich nicht was ich wo ändern soll.

**Comment by Larnak1** [comment]
Für die Beispiel-Quest habe ich sie ja angegeben. Vielleicht kannst du anhand des Beispiels ja mal prüfen, ob da was dran ist und welche Infos du für Quests brauchst, dann kann ich gern weitere raussuchen aus dem Büchlein.

**Comment by hraesvelgr** [comment]
und wie exakt ist das büchlein?

**Comment by dagochen** [comment]
Also die erhaltene XP hängt halt von mehr als nur den in der Datenbank eingetragenen Werten ab. Weiter gehört das Questlevel, das Level des Spielers und eine ziemlich verrückt aussehende Formel dazu. 

Anhand deines Levels (58) und des Questlevels (57) solltest du die volle XP erhalten haben, da die erhaltene Erfahrung erst verringert wird, wenn man mehr als 5 Level über dem Questlevel ist. Ich hab deine Werte bei mir eingegeben und da kommt übrigens auch 7550 raus. Weiter habe ich die Quest grad selbst ohne Premium erledigt und 11000 Erfahrung bekommen. Ich werde meine Formel aus dem aktuellen cMangos mit der von Nefarian vergleichen müssen ;)

**Comment by Larnak1** [comment]
Es kann gut sein, dass damals fälschlicherweise noch irgendein Multiplikator drin war, der nicht hätte drin gewesen sein sollen und dass der mittlerweile behoben ist (da du exakt die Hälfte bekommen hast, wäre das naheliegend). Zwischen 11.000 und 7550 ist der Unterschied ja schon nicht mehr so arg gewaltig.

Zum Buch: Da stehen für jede Quests die Erfahrungspunkte drin, die man bekommt, je nachdem, wie das eigene Level im Verhältnis zum Quest-Level ist, wenn man sie abschließt. Ich hab das wegen Umzug aber gerade nicht mehr vor Ort.

**Comment by dagochen** [comment]
Wenn du mir ne Liste gibst mit Quests, die zu viel EP geben und deren korrekten Werte aus dem Buch hast, kann ich da sicherlich was machen. Die Formel ist laut Dotox die gleiche wie im aktuellen cmangos Core, daher wird wohl in der Datenbank der Wert zu hoch sein. Ich korrigier das mal.
