### ISSUE TITLE
Das Smaragdgrüne Heiligtum (Teufelswald): NPCs vergeben keine Quests

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#321]
**Wie sollte es sich verhalten?**
Folgende Quests sollten im Smaragdgrünen Heiligtum angeboten werden:
http://datenbank.welli-it.de/?quest=5156 bei http://datenbank.welli-it.de/?npc=10921
http://datenbank.welli-it.de/?quest=4421 bei http://datenbank.welli-it.de/?npc=9116
Sie haben (siehe Datenbank) keine Voraussetzungen. 

**Welches Verhalten wird beobachtet?**
Die entsprechenden NPC bieten die Quests nicht an. Taronn Rotfeder lässt sich nicht einmal ansprechen.

**Comment by dagochen** [comment]
Die Quests gibt es doch inzwischen oder? @Larnak1

**Comment by Larnak1** [comment]
Müsste ich nochmal testen, hab es nie wieder versucht

**Comment by Larnak1** [comment]
Den Taronn Rotfeder kann ich noch immer nicht ansprechen und die andere Quest wird mir auch nicht angeboten. Allerdings kann ich nicht 100% ausschließen, dass ich sie im letzten Jahr irgendwann mal gemacht habe ...

**Comment by dagochen** [comment]
Ich kann die Quests annehmen auf Allianzseite, daher schließe ich hier mal. Falls es mit der Fraktion zusammenhängt, bitte nochmal Bescheid geben, dann schaue ich es mir nochmal genauer an.

**Comment by dagochen** [comment]
http://web.archive.org/web/20070311210843/http://wow.allakhazam.com/db/quest.html?wquest=5156

**Comment by Larnak1** [comment]
:)
