### ISSUE TITLE
mehrfaches wurzeln möglich

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#326]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?search=Entangling+Roots kann auf beliebig viele gegner gewirkt werden und aktiv sein.

Wie sollte es sich verhalten? 
http://datenbank.welli-it.de/?search=Entangling+Roots sollte immer nur auf 1 gegner aktiv sein können. Wird es auf ein zweites ziel erfolgreich gewirkt, verliert der gegner, der den debuff vorher hatte, den effekt (kommt wieder frei).

Schritte zur Reproduzierung:
auf mehrere verschiedene ziele http://datenbank.welli-it.de/?search=Entangling+Roots casten

Zusätzliche Informationen (Screenshots, Videos, etc.): 
"Ja bitte wieder mehrere Targets."
http://wow.gamona.de/forum/threads/wucherwurzeln-underpowered.69038/ (während der beta und kurz danach war das mehrfache wurzeln teilweise möglich)

**Comment by Jeysa** [comment]
Griff der natur und Wurzeln sind 2 verschiedene Skills ;)

**Comment by c0keh** [comment]
schön @jeysa, nur geht es hier nicht um griff der natur
