### ISSUE TITLE
Q "der angriff!" bleibt hängen

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#327]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?quest=434 bleibt hängen, http://datenbank.welli-it.de/?npc=1754 und http://datenbank.welli-it.de/?npc=1755 werden nicht angreifbar.
„Belauscht das Gespräch von Lescovar und Marzon.“ wird nicht als fertig markiert, es findet kein gespräch statt.

Wie sollte es sich verhalten? 
„Belauscht das Gespräch von Lescovar und Marzon.“ sollte nach einem gespräch als fertig markiert werden und dann sollten http://datenbank.welli-it.de/?npc=1754 und http://datenbank.welli-it.de/?npc=1755 angreifbar werden.

Schritte zur Reproduzierung:
http://datenbank.welli-it.de/?quest=434 machen

Zusätzliche Informationen (Screenshots, Videos, etc.): 
https://www.youtube.com/watch?v=Io8EsfNb3Mw
im video ist wohl nur der erste teil mit dem belauschen zu sehen.

**Comment by Faafaa** [comment]
Welches Verhalten wird beobachtet?
Bei Annahme des Quest läuft Tyrions Spionagebot (http://datenbank.welli-it.de/?npc=8856) los, despawnt irgendwann und taucht gleich danach wieder neben Tyion (http://datenbank.welli-it.de/?npc=7766) auf.
Marzon die Stille Klinge (http://datenbank.welli-it.de/?npc=1755) bewegt sich währenddessen nicht vom Fleck.

Wie sollte es sich verhalten? 
Siehe oben

Schritte zur Reproduzierung:
Ich habe ebenfalls mit 2 Charakteren diese Quest angenommen. In beiden Fällen (mit mehreren Wiederholungen) gleicher Ablauf wie beschrieben.

Zusätzliche Informationen (Screenshots, Videos, etc.): 
keine

**Comment by fiffzek** [comment]
Die Quest ist wie FaaFaa beschrieben hat nicht abschließbar.

**Comment by ErnisKommentar** [comment]
Doch sie ist abschließbar, aber die Leute, die das Script geschrieben haben, haben als Voraussetzung eine Begleitquest daraus gemacht. Das heißt, du musst dem Roboter hinterherdackeln, wenn du die Quest lösen willst und anschließend dem anderen NPC hinterherdackeln. Ist zwar total falsch gescriptet. Wobei ich sagen muss, dass 99% aller Datenbankfehler hier auf der neuesten Mangosversion behoben sind. Aber offensichtlich schafft man es nicht mal ne neue Mangoszeroversion zu installieren. Wäre schon zu viel Arbeit.

**Comment by dagochen** [comment]
@Dotox 
Quest wurde komplett überarbeitet. Daher sollten diese Probleme hinfällig sein und das Ticket kann bitte geschlossen werden. Danke!
