### ISSUE TITLE
IF auf der dun morogh map nicht anklickbar

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#328]
Welches Verhalten wird beobachtet?
Hat man in der weltkarte dun morogh offen und klickt dann auf ironforge, kommt man nicht auf dessen karte, man bleibt auf dun morogh.

Wie sollte es sich verhalten? 
Normalerweise müsste sich beim klicken auf die stadt IF auf der karte dessen map öffnen. Bei SW und darnassus funktioniert dies auch.

Schritte zur Reproduzierung:
weltkarte → dun morogh → IF anklicken

Zusätzliche Informationen (Screenshots, Videos, etc.): 
(damals auch bugged?)

**Comment by nightblizard** [comment]
Problem des Clients
