### ISSUE TITLE
schiff rut'theran -> auberdine manchmal unsichtbar

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#329]
Welches Verhalten wird beobachtet?
Das schiff, das rut'theran ↔ auberdine verbindet, ist immer mal wieder unsichtbar und durchlässig für einige spieler. Als wenn es gar nicht existieren würde.
Während spieler A also nichts von dem schiff weiß, kann es sein, dass bei spieler B alles normal ist und er drauf laufen kann. Für spieler A sieht es dann aus, als wenn spieler B in der luft steht und dann wegfährt.
Auch nach wiederholtem neueintreffen des schiffes bleibt es für spieler A unsichtbar – neu einloggen behebt den bug jedoch.

Wie sollte es sich verhalten? 
Ganz normal immer sichtbar und nutzbar sein.

Schritte zur Reproduzierung:
/

Zusätzliche Informationen (Screenshots, Videos, etc.): 
/

**Comment by Archidamos** [comment]
Ich sah das Schiff zwar wegfahren, aber es tauchte auch nach 15 Minuten warten nicht wieder auf. Also entweder unsichtbar oder der Timer is falsch. So lange hat es in Classic nicht gedauert.
