### ISSUE TITLE
gurgelbacke spawnt nicht

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#335]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?npc=10323 spawnt nicht.

Wie sollte es sich verhalten? 
Laut http://www.wowhead.com/npc=10323#comments (2007..) müsste er beim camp (etwa 38,75) spawnen.

Schritte zur Reproduzierung:
das murloc-camp bei ~38,75 (mehrfach) auslöschen, schauen ob er auftaucht.

Zusätzliche Informationen (Screenshots, Videos, etc.): 
http://datenbank.welli-it.de/?quest=4740

**Comment by Slimmer2** [comment]
Push

**Comment by hraesvelgr** [comment]
soll in dem camp erst spawnen, wenn man alle murlocs in dem camp getötet hat UND sich in dem camp befindet. es spawnen erst 2 wachen im wasser und greifen den spieler an, sind diese tot spawnt murkdeep/gurgelbacke persönlich, ebenfalls aus dem wasser.

**Comment by mami1306** [comment]
Quest ist entweder wieder oder immer noch verbugged, nachdem die erste Welle gespawned ist, passiert gar nichts mehr.
