### ISSUE TITLE
Arathibecken: Unsichtbares Flaggen-Tappen

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#342]
Mir ist es jetzt schon mehrfach aufgefallen, dass Schurken eine Flagge angegriffen haben, ohne dass man sie sehen konnte. Laut deren Aussagen verschwindet ihr Schleichen-Buff zwar beim Tappen, allerdings werden sie für Spieler der gegnerischen Fraktion nicht sichtbar.

**Comment by drgrey** [comment]
Hatte dir das auch schonmal gemeldet, Wahax. Damals ging es allerdings um Druiden. Da scheint also generell was mit der Unsichtbarkeit nicht ganz koscher zu sein. Ich selber habe es allerdings noch nie geschafft :(. Kann also auch nicht sagen wodran es liegt aber irgendwie muss es gehen (vllt sogar gewollt).
