### ISSUE TITLE
Zauber: Gegenzauber, Schlagen, Tritt

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#343]
Der Zauber Gegenzauber funktioniert nicht korrekt. Die 10 Sekunden Sperre für Zauber der jeweiligen Magieschule funktioniert nicht. Dies ist genau wie bei dem Tritt von Schurken (siehe #199 ) und Zuschlagen vom Krieger.

Zauber: 
http://datenbank.welli-it.de/?spell=2139
http://datenbank.welli-it.de/?spell=6552

Falls noch weitere Klassen solche Zauber haben, bitte die Liste vervollständigen. Danke ;)

**Comment by Slimmer2** [comment]
Der teufelsjäger vom Hexer hat auch einen Spell zum unterbrechen

**Comment by wahaxlekuke** [comment]
Dann sollte das nun auch funktionieren.
