### ISSUE TITLE
Kampfmodus ("infight") wird nicht beendet

### ISSUE THREAD

**Issue by Bonfuzius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#346]
**Welches Verhalten wird beobachtet?**

In letzter Zeit passiert es immer häufiger, daß man - sei es in Instanzen oder in der freien Welt - nicht mehr aus dem Kampf kommt, nachdem der feindliche Mob besiegt ist. Es hilft dann nur noch das Besteigen eines Greifen (was im Kampf eigentlich nicht möglich sein sollte) oder das Beenden des Clients mit ALT-F4. Letzteres führt dann jedoch dazu, daß man sich beim erneuen Einloggen als Geist wiederfindet.

**Wie sollte es sich verhalten?**

Sofort nachdem alle gegnerischen Mobs tot sind, mit denen man im Kampf war, sollte der Kampfmodus beendet werden. 

**Schritte zur Reproduzierung**

Immer reproduzieren lässt sich das leider nicht. Sehr häufig tritt es in BWL bei den Trashpacks nach Lashlayer auf, wo insbesondere die Heiler nicht aus dem Kampf kommen und nicht mehr regenerieren können. Gerade eben kann es es jedoch auch beim Solospiel beobachten, wo ich mit meinem Hexermeister nach jedem einzelnen Mob nicht mehr aus dem Kampf komme.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Besonders unschön ist dieser Bug im Zusammenhang mit der Reduzierung der Kräuterspawns. Muß man beim Sammeln nämlich einen Mob töten so kommt es oft vor, daß man danach nicht mehr aufmounten kann und darf zu Fuß weiterlaufen darf. Auch im Raid verliert man durch ALT-F4 mit Geistermodus sämtliche Elixier-Buffs.

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

keine

**Comment by Cleptomaniac** [comment]
kann die beobachtung bestätigen. tritt in der freien welt bei mir nur dann auf, wenn ich vor mobs fliehe. der infight modus verschwindet dann nicht, wenn der mob bereits die verfolgung aufgegeben hat.

**Comment by Dotox** [comment]
@wahaxlekuke hattest du dafür nicht bereits ein Fix geschrieben? Ist aufgespielt, aber scheinbar tritt das Problem immernoch auf.
