### ISSUE TITLE
Fehlerhafte Lokalisierung mit englischem Client

### ISSUE THREAD

**Issue by Bonfuzius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#347]
**Welches Verhalten wird beobachtet?**

Schon seit ich hier spiele (März 2014) verwende ich den englischen Client, weil ich einfach daran gewöhnt bin. Schon damals hatten sich insbesondere einige deutsche Questtexte eingeschlichen, die anscheinend vom Server kommen. Mitte November wurde aber anscheinend ein Patch aufgespielt, mit dem nun auch sämtliche Item- und NPC-Namen auf deutsch rüberkommen. 

**Wie sollte es sich verhalten?**

Idealerweise sollte im deutschen Client nur deutscher Text und im englischen Client nur englischer Text auftauchen. Dies funktionierte auch schon mal kurzzeitig im Juli, wurde aber wohl wieder zurückgerollt, weil es Auswirkungen auf die Datenbank hatte. Von daher wäre auch der Stand vor Mitte November hilfreich.

**Schritte zur Reproduzierung**

Englischen Client installieren und einloggen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Die Verwendung des englischen Client ist nicht nur reiner Selbstzweck. Abgesehen davon, daß es auch ein paar nicht-deutschsprachige Spieler gibt, existieren in der P-Server-Szene weiterentwickelte Addons, die mit der deutschen Version nicht richtig funktionieren (z.B. 40-Meter-Rangecheck von sRaidFrames Improved). Zudem führt das jetzige Verhalten zu Problemen, da einige Addons Itemnamen in der jeweiligen Lokalisierung erwarten. So zeigt z.B. Necrosis die Anzahl der "shoul shards" nicht an, weil es lediglich "Seelensplitter" vorfindet.

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

keine

**Comment by Dotox** [comment]
Im Moment gibt es weiterhin das Problem mit der Datenbank, welche mit der englischen Lokalisierung nicht funktioniert. Da die Datenbank-Schnittstelle ein fertiges Produkt (sehr unsauber programmiert) war und nicht selbst entwickelt wurde fällt es uns relativ schwer, das vorhandene Konstrukt so anzupassen, dass es mit anderen Tabellen aus der Datenbank funktioniert.
