### ISSUE TITLE
''Gezahnte Klingen'' Schurke

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#352]
Welches Verhalten wird beobachtet?
Das Talent Gezahnte Klingen funktioniert leider nicht wie vorgesehen. Auf dem Server Steht im tooltip Aktuell : ''Eure Angriffe Ignorieren 0 Rüstung eures Ziels''.
 
Wie sollte es sich verhalten?
im Talent Planer von WoW Classic steht wenn man 3 Punkte in dieses Talent Steckt das es 8 Rüstung Ignoriert und es mit jedem level ansteigt, das heisst 8x60= 480 Rüstung  http://www.wowprovider.com/Old.aspx?talent=11215875_4 kann sein das es nur ein anzeige Bug ist , wäre toll wen ihr dort mal rüber schauen würdet

Schritte zur Reproduzierung
Tooltip anpassen, Talent überprüfen.

**Comment by Dotox** [comment]
Nur weil im Tooltip steht, dass keine Rüstung ignoriert wird, heißt es nicht, dass es in wirklichkeit auch so ist. Zu Classic war der Tooltip oft nicht korrekt. Ich bitte dich, dies genauer zu testen und deine Ergebnisse hier zu posten.

**Comment by cionex** [comment]
Dafür bräuchten wir den Testserver der leider nicht zugänglich ist.
Dann mache ich Test mit durschnittlichem Schaden ohne und mit dem Talent. Habe aber auch das Gefühl das es nicht korrekt funktioniert. Zu Classic stand auch garantiert nicht im Tooltip das 0 Rüstung ignoriert wird.

**Comment by Maxwill** [comment]
Hab ich vor einem halben jahr getestet und Funktioniert wie es sein sollte. Der Tooltip ist nur fehlerhaft.

**Comment by cionex** [comment]
@Dotox 
Leider stimmt der Kommentar von Maxwill nicht. Mehr mals getestet, die Rüstung des Ziels wird nicht ignoriert.

**Comment by wahaxlekuke** [comment]
Ich hab mir das Talent mal angeschaut und mir ist aufgefallen, dass die Rüstung, die man beim Ziel ignoriert zu gering ist.
Man ignoriert z.B. auf Rang 3 pro Stufe 3,3 Rüstung, anstatt 8. Das lässt sich beheben

Was sich nicht so leicht beheben lässt ist, dass im Tooltip steht die Rüstung wird um 0 verringert.

**Comment by cionex** [comment]
Sauber @wahaxlekuke 
Das die Funktion des Talentes funktioniert ist absolut wichtiger als die Anzeige im Tooltip. :) Danke dir für deine Hilfe.
