### ISSUE TITLE
Fehler in der PvP- Ehreabrechnung

### ISSUE THREAD

**Issue by Brahe2k7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#354]
Welches Verhalten wird beobachtet?

Die Ehrenabrechung ist bei allen Spielern falsch.

Letzte Woche 
Ehrenhafte Siege  0
Ehre                      0
Platzierung            0

Wenn das nicht offentsichtlich falsch ist, weis ich auch nicht.

Wie sollte es sich verhalten?

Es sollten die Ehrenhaften Siege, Ehre und Plazierung vom 31.12.2014 stehen mit den damit verbundenen Rängen und prozentuallen Fortschritten.

**Comment by smas2810** [comment]
Der Fehler ist letztes Jahr am 01.01. ebenfalls aufgetreten falls es weiter hilft. Da war die Abrechnung allerdings auch an diesem Tag.

**Comment by Bladsn** [comment]
Letztes Jahr entstand das Problem schon in der 2. Dezemberwoche (neuer Patch, der R14 möglich machen sollte) und ging über 4-6 Wochen etwa. 
Also bitte kein Halbwissen verbreiten! :) 

Grüße
