### ISSUE TITLE
Kernteufelsstofftasche für Warlocks

### ISSUE THREAD

**Issue by Anorhin-Alane** [ClassicWoW/Nefarian_1.12.1_Bugtracker#355]
Welches Verhalten wird beobachtet?

In Scholomanceist es nach dem Töten von Jandice Barov nicht möglich das Rezept Teufelsstofftasche zu lernen.

Wie sollte es sich verhalten?
Wurde mehrmals getestet, mit Gruppen wo nur ein Schneider dabei war.

Schritte zur Reproduzierung

Keller clearen, Jandice töten, Bug wurde vom GM Tokala reproduziert.

Zusätzliche Informationen (Screenshots, Videos, etc.)

unnötig

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?item=21341
http://wowdata.buffed.de/item/Behaelter/Teufelsstofftasche-21341
(Kommentare aus 2006)

**Comment by Anorhin-Alane** [comment]
Update: Man hat möglicherweise nach dem Bossfight doch die Möglichkeit die Tasche herzustellen.
Aber das Zahnrad für das Item ist nicht da.
Eventuell trotzdem buggy aber "erlernbar"

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/188 wurde bereits gemeldet.
