### ISSUE TITLE
Geschossanimation ohne Textur

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#356]
Fehler:
Die Geschossanimation von http://datenbank.welli-it.de/?npc=4053 hat keine Textur, anstatt des Geschosses wird man nur von einem kleinen Würfel mit Lila/pinken Kacheln getroffen.

So sollte es sein:
Ich glaube, diese Art NPC wirft mit Speeren.

Links:

NPC http://datenbank.welli-it.de/?npc=4053

Fähigkeit, bei der die Textur fehlt http://datenbank.welli-it.de/?spell=10277

**Comment by Larnak1** [comment]
Dürfte dieses Problem sein: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/51
