### ISSUE TITLE
Schlachtstandarten sollten nicht aus dem Inventar verschwinden

### ISSUE THREAD

**Issue by Feddebla** [ClassicWoW/Nefarian_1.12.1_Bugtracker#357]
Beobachtetes Verhalten:

Die Schlachtstandarten im PVP sind nur einmalig verwendbar, d.h. wenn ich sie verwendet habe, muss ich mir diese wieder beim npc kaufen, um sie zu verwenden.

Wie sollte es richtig funktionieren:

Die Schlachtstandarte kauft man einmal und hat sie für immer im Inventar. Sie hat lediglich einen CD von 15min oder sogar nur 10min -> siehe Quelle Nr. 2 (Patchnotes zum damaligen BWLcontent beim Punkt "Gegenstände" etwas weiter unten).

Quelle :
Hier ein paar Comments dazu aus dem Jahr 2006/07:

http://wowdata.buffed.de/item/Verbrauchbar/Schlachtstandarte-der-Frostwoelfe-19046#comments

Patchnotes BWlContent:
http://wow.4fansites.de/patchnotes_1_6.php

**Comment by Archidamos** [comment]
Gibts hierzu updates? Bin grade Rang 9 und ärgere mich über dieses sinnlose Item ^^

**Comment by wahaxlekuke** [comment]
Sobald das auf Nefarian aufgespielt ist, muss man den WDB-Ordner löschen, weil ansonsten immer 0 Aufladungen bei den Items angezeigt werden.
