### ISSUE TITLE
Important Issue! - Wahaxlekuke

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#358]
Danke!   :D

**Comment by Dotox** [comment]
Quelle?

**Comment by wahaxlekuke** [comment]
Im ersten Moment, als ich die Überschrift gelesen hab dacht ich mir wirklich
> Scheiße ... hab ich da etwa irgendnen fetten Bug reingebaut?? 

Und dann sowas... über so ein Lob freut man sich wirklich riesig :+1:
