### ISSUE TITLE
Zwergische Handkanone macht keinen Schaden

### ISSUE THREAD

**Issue by Rajack** [ClassicWoW/Nefarian_1.12.1_Bugtracker#360]
Sehr geehrte Damen und Herren,

Was passiert?
Die Waffe "Zwergische Handkanone" bringt nicht den abgezeigten Schaden, vgl. Video.
https://www.youtube.com/watch?v=taqatVwPFOI

Reproduzierbar?
Ja

Wie sollte es sein?
Der Schaden müsste ca. 10 Schaden/s über 111 Schaden/s liegen, vgl. Video.

Mit freundlichen Grüßen

Rajack

**Comment by dagochen** [comment]
Gleiches Problem wie bei #117
