### ISSUE TITLE
Flucht durch Verstohlenheit / Flucht durch Gewalt Quest

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#361]
Welches Verhalten wird beobachtet?
Der Druide Volcor, den man aus der Höhle begleiten muss, geht im Fall der Quest Flucht durch Verstohlenheit weder in Verstohlenheit, weswegen die Quest automatisch fehlschlägt, noch verhält er sich vernünftig wenn man durch Gewalt flüchten möchte. Er teleportiert sich wild rum und pullt somit alle Gegner die dort bei der Höhle stehen, was es für Spieler im richtigen lvlBereich beinahe unmöglich macht die Quest abzuschließen.

Wie sollte es sich verhalten?
Wenn man die Quest Flucht durch Verstohlenheit annimmt, sollte man mit Volcor aus der Höhle schleichen können. http://datenbank.welli-it.de/?quest=995
Wenn man die Quest Flucht durch Gewalt annimmt, sollte er ganz normal wie jeder andere Begleitmob vor einem herlaufen und gegen Mobs kämpfen wenn er in den Kampf kommt. http://datenbank.welli-it.de/?quest=994

Schritte zur Reproduzierung
Quest machen.

**Comment by c0keh** [comment]
kann ich bestätigen, hatte mir die Q auch als verbuggt notiert.

**Comment by Archidamos** [comment]
Ergänzung: Wenn man die Flucht durch Gewalt mithilfe eines Highlevelspielers versucht ist es dennoch nicht abschließbar, weil Volcor sobald er die Straße erreicht einfach stirbt und die Quest danach fehlschlägt.
