### ISSUE TITLE
Quest: Elektropeller

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#362]
Welches Verhalten wird beobachtet?
Man kann keine Elektropeller (http://datenbank.welli-it.de/?item=6718) aus den Flüssen in Dunkelküste angeln, welche man für die Quest benötigt.

Wie sollte es sich verhalten?
Man sollte sie angeln können.
http://datenbank.welli-it.de/?quest=1580

Schritte zur Reproduzierung
In Flüssen in Dunkelküste danach angeln.

**Comment by dwilhelms** [comment]
Bestätigt: 23.06.16 - in keinem Gewässer in der Dunkelküste kann man das Questitem angeln
