### ISSUE TITLE
Quest: Therylunes Flucht

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#363]
Welches Verhalten wird beobachtet?
Man kann Therylune aus der Meistergleve begleiten(auch wenn sie einige Movementbugs hat und sich auch dumm rumportet), danach steht auch Quest abgeschlossen. Nun müsste man eigentlich nur noch die Quest bei der Schwester von Therylune am Hain von Aessina abgeben. Das Problem ist, dass die Quest einfach nach ihrem Abschluss plötzlich aus heiterem Himmel fehlschlägt.

Wie sollte es sich verhalten?
Therylune sollte sich normal bewegen, wenn man sie aus der Meistergleve begleitet und die Quest sollte nicht Fehlschlagen wenn Therylune nicht stirbt.

Schritte zur Reproduzierung
Die Quest erledigen.
http://datenbank.welli-it.de/?quest=945

**Comment by Larirawiel** [comment]
/push

Ist leider immer noch verbuggt. :)

Grüße

**Comment by Pipecaff** [comment]
Funktioniert wieder einwandfrei, auch die Laufweg stimmt.
Danke :)
