### ISSUE TITLE
Siegbedingunen im AB und WS

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#366]
Bug?:
Zur Zeit scheint es wieder so zu sein, dass die Allianz den Sieg und wahrscheinlich auch 3 Marken zugesprochen bekommt, trotzdem der BG nach 60 Sekunden schließt und sie weniger Spieler besitzt.

Ich verweise hierbei auf die Diskussion in Issue 295:

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/295

**Comment by ircfelix** [comment]
Bitte genauere Recherche und Anleitung zum reproduzieren posten. Merci!

**Comment by Frostlatte** [comment]
Wei soll ich das recherchieren? Kann ich irgendwo Videos hochladen, da ich keinen Youtube-Account habe

**Comment by Jipptech** [comment]
Nein, das ist quatsch...seit dem Update bekommt kein Team 3 Marke, solange das BG nicht gewonnen wird. Auch wenn hierbei 10 Spieler in der Warsong oder 15 im Arathi sind. Die 3 Marken gibt es nur, wenn 3 Flaggen oder 2000 Punkte erobert wurden und beides ist nicht möglich in 2 Minuten.

MfG Kon

**Comment by Ilikegyoza** [comment]
Es steht immer das die Allianz das BG gewinnt sofern es geschlossen wurde. Allerdings bekommen beide Seiten nur eine Marke. Das verwirrt den Herrn Frostlatte wohl ein wenig

**Comment by Frostlatte** [comment]
Verstehe, wenn das so stimmt, ist es in der Tat nur verwirrend. 

Bezüglich der Aussage Jippies,  werde das aber auch bedeuten, dass ein unterlegenes Team bspw. eine AB Gruppe den Sieg versauen könnte,  wenn es bei 300:1000 den BH verlassen wurde,  oder liege ich da falsch?

**Comment by Jipptech** [comment]
Korrekt...das durfte die Allianz an diesem Wochenende 10 mal beobachten ;) 
(nicht bös gemeint, die Aussage ist etwas aus dem Frust heraus) 
Aber 12 BGs haben wir an diesem Wochenende "verloren" weil jedesmal die Hordengruppe beim 2:0 (Wsg) oder der klaren Führung im Arathibecken entweder AltF4 drückt oder schnell ins andere BG ausweicht (wenn möglich).

Daher wäre es gut (auch wenn es nicht Thema dieses Reports ist) wenn man die Zeit wieder auf 5 Minuten hoch drehen könnte, bis das BG schließt. 
So hat das erfolgreiche Team wenigstens die Chance den Sieg noch zu holen.

Ansonsten kann das Thema hier geschlossen werden.

MfG
