### ISSUE TITLE
Immer noch Probleme beim Kürschnern

### ISSUE THREAD

**Issue by elfinchen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#367]
Ich hatte bereits vor einigen Wochen meine Probleme beim Kürschern preisgegeben. Seitdem kann ich zwar gelegte Tiere wieder kürschnern auch wenn sie keinen Loot enthalten, aber es kommt nachwievor vor, dass ich nach dem looten nicht kürschnern kann, da mir der Lootbeutel immer wieder angezeigt wird. Ich habe rumgefragt und das ist wohl ein Problem, das schon länger besteht. Zudem kommt es jetzt immer öfter vor, dass ich in Instanzen die Tiere zwar kürschnern kann, aber den Kürschnerloot also das Leder oder Schuppen nicht bekomme.

**Comment by Larnak1** [comment]
Es geht um dieses Problem: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/288

**Comment by dagochen** [comment]
Das Problem mit dem Kürschnern, aber Loot (Leder, Drachenschuppen) nicht einsammeln zu können liegt daran, dass du zu weit weg stehst. Stell dich in den Leichnam rein, dann sollte es gehen.

**Comment by elfinchen** [comment]
Selbst wenn ich mich in den Leichnam reinstelle und dann kürschner, kann ich den Loot zum Teil einfach nicht einsammeln. Ich kürschner und dann wir mir nichts weiter angezeigt... Normalerweise erscheint dann der Loot (Leder, Schuppen, Balg) und ich kann ihn einsammeln, aber nix ist...

**Comment by c0keh** [comment]
lootbar, aber nicht kürschnerbar:
es scheint immer die gleichen mob-IDs zu betreffen. während manche spawns einer mobgruppe immer kürschnerbar sind, sind anderen spawns der selben mobgruppe es NIE.

**Comment by ertbert** [comment]
Probiers mal mit dem Kürschner Skill aus dem Zauberbuch. Damit funktioniert es bei mir, auch wenn noch das Lootsymbol erscheint.
