### ISSUE TITLE
PvP - FlagTimer

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#368]
Hallöle,

der Timer fürs PvP - Geflaggt - Sein scheint etwas buggy. Trotz der Einstellung "inaktiv" geht es nach 5min nicht immer aus. 
Teils stehe ich mehr als 15min und konnte so nicht am Raid teilnehmen. Gerade man aus einem BG kommt für Raids etwas unpraktisch, besonders bei Allies mit ner Unruhigen Hand ;)

Daher die Bitte, dies mal zu überprüfen.

**Comment by Jimsy2** [comment]
Habe dasselbe Problem nachdem ich mit meinem Level 10 Priest jemanden gebufft habe, der PvP war.
