### ISSUE TITLE
Rang14 Waffen falsch implementiert 

### ISSUE THREAD

**Issue by LOLBUG** [ClassicWoW/Nefarian_1.12.1_Bugtracker#371]
Liebes Classic Team,

da ja jetzt r14 möglich sein soll wollte ich darauf hinweisen das einige Waffen erst mit dem Naxxramas-Patch implementiert wurden. 

http://www.wowwiki.com/Patch_1.11.0

"New rank 14 weapons have been added! In order to give casters the same diversity of selection that melee currently enjoy we have added new caster items that are available to be purchased by Grand Marshals and High Warlords."

Dies Betrifft folgende Waffen: (Horde Version)
(bei Patchchanges deutlich zu erkennen wann es implementiert wurde.)

http://www.wowwiki.com/High_Warlord%27s_Spellblade 
http://www.wowwiki.com/High_Warlord%27s_Tome_of_Mending
http://www.wowwiki.com/High_Warlord%27s_Tome_of_Destruction
http://www.wowwiki.com/High_Warlord%27s_Destroyer
http://www.wowwiki.com/High_Warlord%27s_Battle_Mace

Diese Items sind auf AQ Niveau und wurden erst mit Naxxramas eingefügt.

Daher bitte ich diese Items bis zum erscheinen von Naxxramas zu entfernen .

MFG

**Comment by hraesvelgr** [comment]
crybabies inc.

**Comment by LOLBUG** [comment]
warum wurde das geschlossen ??? ich mein hier handelt es sich nicht um trinkets oder armschinen die eigentlich erst viel später verfügbar waren sondern um DEN HAUPTITEMSLOT ... die waffe ... einfach nur fail

**Comment by Knacks** [comment]
weil hier auf 1.12.1 aufgebaut wird und nicht alles zig mal im nachhinein wieder geändert wird, damit es auf einen anderen Patchstand passt. Der Patchstand des Servers ist 1.12.1 und nach dem patch werden bugs auch gefixt. Alles andere wäre einfach Sinnlos!
