### ISSUE TITLE
Häufige Disconnects im AV

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#373]
Im AV waren heute viele Disconnects zu beobachten. Es erhielten häufig ganze Wellen von Spielern welche.

Bei mir sowie von vielen im TS wurde bestätigt, dass man getrennt wurde, wenn man auf den Statistik-Button der Karte klickte.

**Comment by Dotox** [comment]
Einfach so? Etwas mehr Informationen zum Stand der Buildings auf dem Schlachtfeld wäre wichtig. Vielleicht tritt es nur auf, wenn ein bestimmter Friedhof o.Ä eingenommen wurde.
