### ISSUE TITLE
Standbilder im AV

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#374]
Innerhalb der BGs kommt es bei allen Spielern immer wieder zu kurzen o. auch längeren Standbildern (bei mir z.B. teils 10Sek.).
Es scheint sich dabei aber nicht um Laggs zu handeln, da die Mitspieler im TS immer unabhängig von einander Standbilder haben.

Woran es liegt..immo keine Idee. Mir ist dieses Phänomen in allen BGs aufgefallen.

Außerhalb der BGs konnte ich dies noch nicht beobachten.

in der letzten Woche scheint dies verstärkt aufzutreten.

MfG  Frost

**Comment by hraesvelgr** [comment]
seltenes auftreten bei betreten von instanzen wie BRD oder stratholme haupttor (etwas häufiger).

vllt auch ein clientseitiges problem, hab es auf vielen classicservern schon erlebt.

**Comment by Dotox** [comment]
Ich denke das liegt an verschiedenen Files, die wir seit Mittwoch zum testen getauscht haben um dies als mögliche Quelle der Lags auszuschließen. Sollte mit dem heutigen Update nicht mehr vorkommen.

**Comment by Frostlatte** [comment]
Besten Dung!

Wir werden berichten ;)
