### ISSUE TITLE
Banish (Verbannen) durch Melee angriff beenden

### ISSUE THREAD

**Issue by maganzi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#377]
Mir ist aufgefallen, wenn ich einen Dämonen durch "Verbannen" Banish verbanne lässt er sich durch einen einzigen Schlag mit einer Nahkampfwaffe "raushauen". Dies sollte nicht so sein. der Gegner sollte die volle Zeit Immun gegen Nahkampf, Fernkampf und Zauberangriffe sein.

Hier ein Video von mir
https://www.youtube.com/watch?v=WK0x9oH5YuQ
Video lädt gerade noch hoch sollte um 20:00 online sein.

Grüße

Maganzy
<Solid Core>

**Comment by Gnomorus** [comment]
guckst du hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/234

**Comment by Slimmer2** [comment]
Hier mal der Link zum Zauber http://datenbank.welli-it.de/?spell=18647#see-also-ability
