### ISSUE TITLE
Zul Gurub - High Priest Thekal - Rezz Phase 1 Buggy

### ISSUE THREAD

**Issue by Jamayj** [ClassicWoW/Nefarian_1.12.1_Bugtracker#378]
Server Version  Last Core Update [12.01.2015] Version: [1.0.1] 
(Geprüft am 12.01.15 , Raid fand statt am 10.01.15 Ca. 21:30)

So sollte es laufen:
Am Ende der ersten Phase müssen Thekal und seine beiden Adds gleichzeitig bzw mit sehr geringem Abstand gekillt werden. Ist der zeitliche Abstand zwischen den Kills zu hoch, werden alle 3 mobs wieder Belebt, Phase 1 beginnt praktisch von vorne.

Wie es tatsächlich ablief:

Statt dass alle 3 Mobs wiederbelebt wurden, sind lediglich Thekal und Zealot Lor'Khan in den Kampf zurückgekehrt, Zealot Zath blieb tot. Auch nach dem gleichzeitigen Kill beider beim zweiten mal verbliebener Mobs wurden besagte wieder wiederbelebt,während Zealot Zath tot blieb.

Footage vom Vorfall: 

https://www.youtube.com/watch?v=tWrgWoDxYFU&feature=youtu.be

Anmerkungen:

- Wir wissen nicht ob die Situation auch mit Zealot Lorkhan statt Zath reproduzierbar ist.
- Eine später erfolgter Server-restart konnte das Problem nicht beheben
- Das Verlassen des "Boss-Raumes"  konnte Thekal nicht resetten
- Verlassen der Instanz und Ausloggen aller Raidmitglieder (Gleichzeitig) zeigte auch keinen Effekt

**Comment by Mokkaa** [comment]
Problem besteht weiterhin (14.03.15, Mobs gingen fast synchron down)
