### ISSUE TITLE
Paladin Skill: Hammer of Justice (Hammer der Gerechtigkeit) Rang 1

### ISSUE THREAD

**Issue by Vishara** [ClassicWoW/Nefarian_1.12.1_Bugtracker#380]
Welches Verhalten wird beobachtet?
Dieser Skill betäubt maximal 1 - 1,5 Sekunden den Gegner und ist somit wegen dem hohen Cooldown fast nutzlos. 

Wie sollte es sich verhalten?
Normalerweise soll dieser Skill auf Rang 1 den Gegner 3 Sekunden lang betäuben.

Schritte zur Reproduzierung
Skill an einem beliebigen Gegner benutzen. 
Ich habe diesen Bereits an mehreren Gegnern ausprobiert und nie eine längere Stundauer als 2 Sekunden bekommen. Eine Selbstheilung (2,5s) ist innerhalb des Stuns nicht möglich.

Zusätzliche Informationen
Ob die anderen Ränge genauso schnell ihren Effekt verlieren, kann ich nicht sagen, da mein Pala gerade Stufe 14 ist.

Links aus unserer Datenbank
http://datenbank.welli-it.de/?spell=853

**Comment by Archidamos** [comment]
Habe zwar nie tatsächlich mitgestoppt, aber der Stun kam mir auch immer tatsächlich sehr kurz vor

**Comment by ircfelix** [comment]
Bugreports die auf Schätzungen basieren sind zwar immer noch besser als gar keine Bugreports aber dennoch zu wischi waschi. Gebt euch doch bitte mehr Mühe.

**Comment by Vishara** [comment]
Ich glaube nicht das meine Aussagen oben ungenau sind. Sie sind sogar ziemlich präzise. Egal wie man es dreht und wendet ... 
Dieser Skill betäubt keine 3 Sekunden wie er sollte sondern DEUTLICH weniger. Ich wüsste nicht wie man dies noch genauer ausdrücken sollte ... 

Grüße
Vishara

**Comment by Dotox** [comment]
z.B durch ein Video indem klar zu erkennen ist, dass der Stun nur 1,5 Sekunden geht.

**Comment by Sabbaer** [comment]
ja, klaro ist das inerhalb eines stuns nicht möglich da es einen global cooldown von 1ner sek gibt
