### ISSUE TITLE
Dropchance Sulfuronblöcke

### ISSUE THREAD

**Issue by Thandor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#381]
Hab grad den Post von Raso gelesen in dem es um die Dropchance des Drakefangtalisman geht : 
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/308
Als Quelle ist dort www.wowdb.com angegeben. Sollte diese Quelle verlässlich und von euch anerkannt sein müsste ein Sulfuronblock bei Golemagg mit 40% droppen .
http://www.wowdb.com/npcs/11988-golemagg-the-incinerator#related:drops-item
Auf dem Server droppen sie im Moment mit ungefähr 12% laut eigener Datenbank.
http://datenbank.welli-it.de/?item=17203

Dies bitte ebenfalls anpassen, da es sehr ärgerlich ist, dass die Augen droppen und man nie genug Blöcke zusammenbekommt um den Hammer dann auch zu bauen.
Vielen Dank

**Comment by Larnak1** [comment]
Lässt sich ausschließen, dass das später erhöht wurde?

**Comment by Thandor** [comment]
kp.. wenn allerdings die Dropchance bei dem Drakefang für richtig befunden wurde sollte auch die Dropchance der Blöcke dort richtig sein, denn welche Datenbank ist bei einem Item auf dem Classic Patchstand und bei einem anderen Item aus demselben Content auf einem höheren Patchstand?
Dann müsste ja bei jedem Item stehen bei welchem Patchstand es welche Dropchance hatte.

**Comment by Larnak1** [comment]
Oft sind daher nicht die Datenbankeinträge selbst interessant, sondern die darauf bezogenen Kommentare, die man bei einigen Datenbanken noch findet.

>Erbeutet von:
Der geschmolzene Kern
Golemagg der Verbrenner (Boss) 10.69%

http://wowdata.buffed.de/item/Handwerkswaren/Sulfuronblock-17203 
Kommentar Nummer 23, die 12% scheinen also ganz gut zu passen.

**Comment by Thandor** [comment]
http://wow.gamepedia.com/Sulfuron_Ingot
Laut dieser Seite wurden sie nur mit Patch 6.0.2 verändert und zwar wurde da lediglich die Stackgröße von 20 auf 200 angehoben. Laut der Seite wurde die Dropchance mit keinem Patch verändert.

**Comment by Larnak1** [comment]
Leider sind Wiki-Einträge selten vollständig. Solange da nicht explizit steht, dass etwas nicht getan wurde, ist die Abwesenheit der Information kein Beleg :(

Darüber hinaus gibt das Wiki selbst diese 12% an, wenn man sich mal folgenden History-Eintrag ansieht:
http://wow.gamepedia.com/index.php?title=Sulfuron_Ingot&oldid=279691
Die Info ist im Mai 2007 aus dem Wiki entfernt worden.

**Comment by Thandor** [comment]
http://wowdata.buffed.de/item/Handwerkswaren/Sulfuronblock-17203#comments
Hast du Post Nr. 70 gelesen? Dort schreibt jemand was von 28,39% Dropchance.
Aber laut Gamepedia wurde die Dropchance mit keinem Patch erhöht oder geändert.
Könnte es daher nicht auch sein das die 10.69% mit Droppech entstanden sind weil diese Zahl ist nirgends sonst zu finden und ich hab eben mal einige andere Classic-Privatserver Datenbanken durchgestöbert und bei vielen liegt die Dropchance der Blöcke bei 30%.

**Comment by Larnak1** [comment]
Ja, und Post 70 stammt von 2011, was damit die Theorie der geänderten Droprate bestätigt. Die 10,69% sind kein exakter Wert, das ist klar, und es ist gut möglich, dass der im realen Serverbetrieb (Droppech) aus 12% Dropchance entstanden ist. Dass er aus 30% oder gar 40% Dropchance entstanden ist, halte ich aber für unwahrscheinlich, der Wert dürfte schon damals nicht nur auf einigen einzelnen Kills basiert haben.

**Comment by Thandor** [comment]
Ja sicher ist es unwahrscheinlich und vermutlich wären bei 30-40% Dropchance damals wesentlich mehr Blöcke im Umlauf als sie es sowieso waren, aber trotzdem wundert es mich das nirgends explizit steht wann die Dropchance erhöht wurde und das nicht nur um einige Prozente sondern direkt um knappe 30% wenn man nach wowdb.com geht, denn sowas wird normalerweise in den Patchnotes beschrieben. Desweitern muss ich sagen ( auch wenn das mein persönlicher Eindruck ist ) gab es damals zu Classiczeiten gefühlt wesentlich mehr Blöcke als Augen während hier auf dem Server einige mit nem Auge rumlaufen aber die nötigen Blöcke in einem raidjahr nicht zusammenkommen.

**Comment by Thandor** [comment]
Ich denke ich hab mich da etwas verrannt und nach etwas längerer Überlegung bin ich der Meinung, dass die 12% passen und der Thread hier geschlossen werden kann. Der Grund für die sehr wenigen Blöcke hier auf dem Server ist, dass hier nur 2-4 Gilden pro Fraktion Mc raiden und damals waren es deutlich mehr, wodurch natürlich insgesamt mehr Blöcke gedroppt sind.

**Comment by Thandor** [comment]
Trotzdem komisch, dass pro Auge nur 3 Blöcke droppen wenn man nach den Dropchancen geht, man aber 8 Blöcke braucht um zusammen mit dem Auge einen fertigen Hammer zu bauen. Kp da war en die von Blizzard anscheinend betrunken am programmieren xD
