### ISSUE TITLE
Verführen vom Sukkubus funktioniert sporadisch

### ISSUE THREAD

**Issue by maganzi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#386]
Guten Tag,
Mir ist ein Fehler aufgefallen.

Der/die sukkubus verführt nurmehr sehr sporadisch. Dies ist mir gestern im PVP aufgefallen.
Vorher war das verführen sehr zuverlässig nun läuft der sukkubus meistens nurnoch zum Gegner und Attackt ihn obwohl nur Verführen auswählt wurde.
Andere Fähigkeiten vom Pet hab ich abgeschaltet, Fehler immernoch vorhanden.

**Comment by Armauskugelbob** [comment]
Kann ich so bestätigen. Dieser Fehler ist von mehreren Wls berichtet worden.

**Comment by Beecks** [comment]
Ist-Analyse: (Version 1.0.2 - Core Update vom 18.01.)
Ich habe das Mal im Duell getestet.

Beim 1. Aktivieren der Verführung sieht es so aus als wenn die Sukkubus sich zum Ziel hin dreht und kurz anfängt zu zaubern (schattige Hände). Im Schlachtfeld fängt sie danach sofort an, jemanden anzugreifen, sodass Unsichtbarkeit verschwindet. Im Duell dagegen muss man ein zweites Mal Verführung aktivieren, und dann zaubert die Sukkubus das endlich.

Soll-Zustand:
Egal, ob die Sukkubus unsichtbar ist oder nicht, sobald mal beim 1. Aktivieren des Zaubers ist, es sollte 1,5Sek das Target verführt werden.

**Comment by Armauskugelbob** [comment]
Need sukkkiii! :dancers:

**Comment by wahaxlekuke** [comment]
Das sollte der gleiche Fehler wie #389 sein und dadurch mit dem letzten Update behoben. Es gibt allerdings immer noch den Fehler #289, der noch nicht (komplett) gefixt wurde.
