### ISSUE TITLE
Lokalisation: Englische Emotes im deutschen Clienten

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#387]
**Welches Verhalten wird beobachtet?**

Seit dem Update 1.0.2 sind div. Emotes auch im deutschen Clienten auf englisch. Aufgefallen ist es mir bis jetzt in Stormwind und bei Nefarian.

**Wie sollte es sich verhalten?**

Die Emotes sollten weiterhin in der deutschen Version vorhanden sein.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

http://picload.org/image/ccpogwg/wowscrnshot_011615_000201.png
http://picload.org/image/ccwpgrr/nef.png

**Comment by Dotox** [comment]
Ich habe vorhin einen Fehler mit den Umlauten behoben, der nach einem Neustart aktiv ist. Kannst du eventuell danach prüfen, ob die Emotes wieder korrekt angezeigt werden?

**Comment by Gnomorus** [comment]
Klappt noch nicht so ganz:
http://picload.org/image/cidlcrw/uebersetzung1.png
http://picload.org/image/cidlcdr/uebersetzung2.png
http://picload.org/image/cidlcdr/uebersetzung2.png

**Comment by Gnomorus** [comment]
Ragnaros ist seit neuestem auch bilingual unterwegs:
http://picload.org/image/ciadwcw/uebersetzung5.png
http://picload.org/image/ciadwir/uebersetzung6.png

**Comment by Dotox** [comment]
Ja gut, dass sind aber keine Emotes sondern Texte.

**Comment by Gnomorus** [comment]
Da muss ich dir wohl recht geben. Ändert an den Ungereimtheiten mit der Darstellung der Umlaute aber auch nichts^^

**Comment by Gnomorus** [comment]
Da muss ich dir wohl recht geben. Ändert aber an der Sache an sich nichts^^
