### ISSUE TITLE
Hexenmeister Pet: Leerwandler Schatten verzehren in der Bewegung buggy

### ISSUE THREAD

**Issue by maganzi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#389]
Hey,
hab hier einen Fehler gefunden es könnte sein, dass er mit "Verführen" von der Sukkubus zusammenhängt.

Wenn ich Laufe und dem Leerwandler befehle "Schatten verzehren" kostet es die ca 400 Mana und es leuchten kurz seine Hände allerdings passiert nichts weiteres... Als wenn er es direkt abbricht.
Wenn man den Cast zuerst startet und dann läuft ist alles gut ;)

Grüße

**Comment by Dotox** [comment]
@wahaxlekuke Kann das mit der Änderung aus BWL (erster Boss) zusammenhängen?
