### ISSUE TITLE
Alptraumdrachen 75%, 50%, 25% und 0%?!

### ISSUE THREAD

**Issue by maganzi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#390]
Guten Tag,

mir ist ein Fehler aufgefallen: Da die Drachen nun nicht mehr genau bei 75% 50% und 25% ihre "Superfähigkeit" machen kam es bei uns zu folgenden Fehler:
Bei etwa 1% seiner Lebensenergie hat Emeriss nochmal seinen Dot an alle verteilt.

Grüße

**Comment by Gnomorus** [comment]
Auch wenns nicht unbedingt blizzlike ist, find ich die zufällige Komponente rund um die 0% garnicht mal so übel. Immerhin kann ein 4. Event kommen, oder nicht. Bringt etwas Abwechslung bzw. Unvorhersehbarkeit in die Sache.

**Comment by maganzi** [comment]
Gilden die mit der minimalbesetzung angreifen könnten damit ein problem haben ;)

**Comment by Thandor** [comment]
Dann sind die Minimalbesetzungen eben um einige Leute angestiegen. Find ich persönlich keine schlechte Sache, da so mehr Leute die Möglichkeit bekommen einen Worldbossfight mitzuerleben.
