### ISSUE TITLE
Händler: Wurfwaffen

### ISSUE THREAD

**Issue by nicole-woebse** [ClassicWoW/Nefarian_1.12.1_Bugtracker#391]
Hallo,

mir ist gerade aufgefallen das nur noch ein Händler Wurfwaffen verkauft.

Lindsay Aschenlocke <Gemischtwaren>
http://datenbank.welli-it.de/?npc=791

Eigentlich sollten alle Gemischtwarenhändler welche verkaufen.

Auch heissen alle Wurfwaffen nun "Zerbrochene XY", was aber erst mit einem späteren Addon kam als die Mechanik der Wurfwaffen geändert wurden. Das Zerbrochene gehört also eigentlich nicht dazu.

Hier einmal die links zu Wurfwaffen die Gemischtwarenhändler verkaufen sollten.

http://datenbank.welli-it.de/?item=3131
http://datenbank.welli-it.de/?item=3135
http://datenbank.welli-it.de/?item=2946
http://datenbank.welli-it.de/?item=3107
http://datenbank.welli-it.de/?item=15326
http://datenbank.welli-it.de/?item=3111
http://datenbank.welli-it.de/?item=3137
http://datenbank.welli-it.de/?item=3108
http://datenbank.welli-it.de/?item=15327

Ich weiß nicht ob das alle Waffen sind, aber zumindest die meisten.

lg Nicole/Yuki

**Comment by Dotox** [comment]
Kurze Frage da ich auf die schnelle auch nichts finden konnte, war das damals so? Hast du eine Quelle? Dein Report klingt logisch, dennoch wäre ein Link zur Quelle hilfreich.

**Comment by nicole-woebse** [comment]
Es war auf jedenfall so, ich suche mal nach einer Quelle. Auch wenn ich nicht recht weiß wo ich eine für so etwas finde. Auf Fremdsprachigen Servern scheint es auch so zu sein, das dort nur ein Händler sie verkauft. Aber ich kann mich nicht daran erinnern mit meiner Schurkin damals immer in Seehain rum gehangen zu haben. Es kann sein das es aber mit dem Pre BC patch geändert wurde. Ich werde mal nach Infos suchen.

Hier ein Link schon mal, eine ganze reihe weiterer werden im nächsten post folgen (ich muss sie nur erst mal sortieren ^^)

http://www.wowwiki.com/Ammo_vendor

**Comment by nicole-woebse** [comment]
Level 1
http://wow.gamepedia.com/Light_Throwing_Knife
http://wow.gamepedia.com/Crude_Throwing_Axe

Level 3
http://wow.gamepedia.com/Weighted_Throwing_Axe_%28common%29
http://wow.gamepedia.com/Balanced_Throwing_Dagger

Level 11
http://wow.gamepedia.com/Keen_Throwing_Knife
http://wow.gamepedia.com/Sharp_Throwing_Axe

Level 22
http://wow.gamepedia.com/Heavy_Throwing_Dagger
http://wow.gamepedia.com/Deadly_Throwing_Axe

Level 35
http://wow.gamepedia.com/Wicked_Throwing_Dagger
http://wow.gamepedia.com/Gleaming_Throwing_Axe

Level 50
http://wow.gamepedia.com/Blacksteel_Throwing_Dagger
http://wow.gamepedia.com/Jagged_Throwing_Axe

So ich hoffe die Links sind ok, es scheint sich nie etwas an ihnen geändert zu haben bis sie mit 5.0.4 entfernt wurden. (Ausser das sie mal von verbrauchbar wie Munition dazu gewechselt sind das sie ihre Haltbarkeit verbrauchen mit wotlk oder cata als die Munition abgeschafft wurde).

**Comment by KappaAlphaOmega** [comment]
(Duplikat: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/763)

Quelle: Webarchiv von Thottbot.com (2005).

Liste von Händlern für "Ausbalancierter Wurfdolch":
https://web.archive.org/web/20050412145159/http://www.thottbot.com/?i=29837

Verkaufsangebot von Thurman Mullby (Gemischtwarenhändler) in Stormwind:
https://web.archive.org/web/20050504045317/http://www.thottbot.com/?n=473864

Ruhm und Ehre der WayBackMachine von archive.org!
