### ISSUE TITLE
Quest: "Widderzaumzeug" nicht abschließbar

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#393]
**Welches Verhalten wird beobachtet?**

Die genannte Quest ist trotz genügend Frostwolfbälge im Inventar nicht abschließbar.

**Wie sollte es sich verhalten?**

Sollte abgebbar sein.

**Schritte zur Reproduzierung**

Frostwölfe kloppen, Bälge looten, abgeben wollen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Quest: http://datenbank.welli-it.de/?quest=7026
Frostwolfbälge: http://datenbank.welli-it.de/?item=17643

**Comment by Zahul** [comment]
push fehler besteht immer noch
