### ISSUE TITLE
Quest: "Vorräte der Eisenschachtmine" - Vorräte nicht plünderbar 

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#396]
Welches Verhalten wird beobachtet?

Die in der Mine verteilten Kisten können zwar geöffnet werden, es öffnet sich jedoch kein Plünderfenster, nachdem sie geöffnet wurden.

Wie sollte es sich verhalten?

Es sollte sich ein Plünderfenster öffnen, um die Vorräte plündern zu können.

Schritte zur Reproduzierung

Rechtsklick auf die Vorratskisten, kurz warten, nichts geschieht.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Quest (Horde): http://datenbank.welli-it.de/?quest=6985
Quest (Allianz): http://datenbank.welli-it.de/?quest=5892
Objekt: http://datenbank.welli-it.de/?object=178785
Item: http://datenbank.welli-it.de/?item=17522

Wurde zwar schonmal in nem Sammelpost(#133) gemeldet und teilweise gefixt - plündern lässt sich aber immer noch nichts. Deshalb der Übersicht halber nochmal einzeln.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/394

**Comment by Gnomorus** [comment]
sind halt 2 verschiedene quests - deshalb 2 reports

**Comment by Dotox** [comment]
Habs ja miteinander verknüpft durch die Makierung :)
