### ISSUE TITLE
Quest: "Verwaiste Ställe" nicht annehmbar

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#397]
**Welches Verhalten wird beobachtet?**

Die gegannte Quest lässt sich (zumindest auf Seiten der Allianz) nicht annehmen. Der Questgeber zeigt zwar ein Austufezeichen an, die Quest befindet sich jedoch bereits quasi in dem Status, als hätte man sie angenommen. Zumindest entspricht der Questtext dem zu "Fortschritt" zugeordnetem aus der Datenbank.

**Wie sollte es sich verhalten?**

Die Quest sollte normal annehmbar sein. Beim Annehmen erhält man das Zähmungshalsband, mit welchem man die Alteracwidder in gezähmte Alteracwidder verwandeln kann. Diese folgen einem dann wie ein Begleiter bis zu den Ställen/dem Questgeber. Dort kann man die Quest abgeben, der gezähmte Widder despawnt.
Nach und nach füllen sich dann auch die Boxen des Stalls als Indikator dafür, wann man genug Widder eingefangen hat, um die Kavallerie zu rufen.

**Schritte zur Reproduzierung**

Im Alteractal die Quest annehmen wollen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Quest (Allianz): http://datenbank.welli-it.de/?quest=7027
Zähmungshalsband (Allianz): http://datenbank.welli-it.de/?item=17689
Alteracwidder: http://datenbank.welli-it.de/?npc=10990
gezähmter Alteracwidder: http://datenbank.welli-it.de/?npc=13676
Quest (Horde): http://datenbank.welli-it.de/?quest=7001
Frostwolf (Horde): http://datenbank.welli-it.de/?npc=10981
gezähmter Frostwolf (Horde): http://datenbank.welli-it.de/?npc=13618

Wurde zwar schonmal in nem Sammelpost(https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/133) gemeldet, ist jedoch wohl neben der anderen, gemeldeten Quest untergegangen. Deshalb der Übersicht halber nochmal einzeln.

**Comment by Zahul** [comment]
Bisse gesucht wegen dem Forumthread, soweit ich das rauslese ist das immer noch wie oben erläutert
