### ISSUE TITLE
Quest: Flucht durch Gewalt

### ISSUE THREAD

**Issue by Faafaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#398]
Welches Verhalten wird beobachtet?
Zu beschützender Char (Volkor) verschwindet und taucht 20 Meter weiter wieder auf, läuft dann den Weg zum Ausgangspunkt zurück um dann wieder wieder weiter vorne aufzutauchen. Dieses Verhalten soppt auch im Kampf nicht, wodurch nach und nach alle Mobs im Kampf sind und das Quest scheitert.

Wie sollte es sich verhalten?
Escort-Quest: Volkor geht normal voraus und bleibt stehen, wenn er in einen Kampf verwickelt wird
Schritte zur Reproduzierung:
Quest mehrmals innerhalb einer Woche mit zwei verschiedenen Charakteren erfolglos gestartet.

Zusätzliche Informationen (Screenshots, Videos, etc.): n/a

Links aus unserer Datenbank: 
http://datenbank.welli-it.de/?quest=994
http://datenbank.welli-it.de/?npc=3692

**Comment by Archidamos** [comment]
Wird schon in Bug # 361 angesprochen.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/361
kannst ja dort deine Infos nochmal hinposten, vermute dass das hier geschlossen wird :-/
