### ISSUE TITLE
Kräuter- low lvl

### ISSUE THREAD

**Issue by zutrer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#399]
Wo sind die Low Lvl Kräuter geblieben?
mindesten 70-80% sind weg.

**Comment by Wosser** [comment]
http://www.mmobase.de/forum/classic-server-news/6567-serverupdate-1-0-0-a.html
- Die Kräuterspawns in verschiedenen Gebieten wurde überarbeitet.
