### ISSUE TITLE
Paladin Klassenspell "hammer des zorns" skaliert 0 mit +zauberschaden

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#400]
Welches Verhalten wird beobachtet? der paladin klassenspell "hammer des zorns" http://datenbank.welli-it.de/?search=hammer+of+wrath skaliert 0 mit +zauberschaden. er sollte laut datenbank http://pastebin.com/2EuNW40i die gleiche skalierung wie der paladin spell "exorzismus" bekommen welcher richtig im spiel den +zauberschaden angerechnet bekommt. durch diesen fehler ist der spell quasi nutzlos als finisher.

Zusätzliche Informationen (Screenshots, Videos, etc.): https://www.youtube.com/watch?v=hoOVlOMErIg bei 1:20min macht der spell 986 mit full t2 , zg trinket und seele der macht vom priester

Links aus unserer Datenbank: http://datenbank.welli-it.de/?spell=24239

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/157
