### ISSUE TITLE
Pechschwingenhort Bugreport

### ISSUE THREAD

**Issue by Classic-WoW** [ClassicWoW/Nefarian_1.12.1_Bugtracker#401]
Razorgore

Welches Verhalten wird beobachtet?
Es kann vorkommen das gespawnte Drachkin in der Ecke einfach stehen bleiben und despawnen.

Wie sollte es sich verhalten?
Drachen sollten nicht despawnen und nicht in der ecke stehen bleiben.

Schritte zur Reproduzierung
/
Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=gYzMuxPxPuA
Video auf HD gucken und genau hinsehen. Drache steht dort und despawnt..
Links aus unserer Datenbank (hier gehts zur Datenbank)
/

Nefarian

Welches Verhalten wird beobachtet?
1) In Phase 1 ist aufgefallen das Drachkins zu wenig Rüßtung haben und teilweise riesengroße Krittischetreffer stattfinden. Krieger mit mehr AP als mein Schurke werden dort mit >1,6k Crits arbeiten.
2) Nach Phase 3, nach dem Nefarian Tot ist, spawnen die Adds aus P3 noch einmal.

Wie sollte es sich verhalten?
1) Mehr Rüßtung.
2) Sollten nicht spawnen
Schritte zur Reproduzierung
1) Nefarian P1 starten.
)2 Nefarian töten?:D

Zusätzliche Informationen (Screenshots, Videos, etc.)
1) https://www.youtube.com/watch?v=G9Vfpo7CCKU
2) https://www.youtube.com/watch?v=jpJCLXccMF
Links aus unserer Datenbank (hier gehts zur Datenbank)
/
/

**Comment by Dotox** [comment]
Die Kreaturen bitte verlinken.
