### ISSUE TITLE
Westliche Pestländer: Untote Standardmobs sind Elite

### ISSUE THREAD

**Issue by Mooshirn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#403]
Hallo, in den westlichen Pestländern sind einige NPCs Elite, obwohl sie eigentlich keine sein sollten.
Auf der Suche nach Quellen die dies bestätigen habe ich diesen Thread im Forum gefunden:

http://www.mmobase.de/forum/npcs/5922-%5Bnpc%5D-westliche-pestlaender-untote-elite-mobs.html

Da im ersten Beitrag alle betroffenen NPCs mit Datenbanklink, Namen, lvl-Bereich, Ort sowie auch Quellen bzgl. Elite / Nonelite vorbildlich aufgeführt sind, spare ich mir hier mal die Arbeit alles nochmal aufzulisten und bitte darum dies einfach im genannten Thread nachzulesen.
Anscheinend wurde sogar bereits an einem Fix gearbeitet, dieser kam jedoch offensichtlich nie auf dem Liveserver an.

Da die betroffenen NPCs die Questitems für die Rufquests und auch Items für die Rufbelohnungen der Argentum Dämmerung droppen, würden sich sicher einige Spieler über einen Fix freuen.
Den Ruf zu erfarmen ist so schon eine sehr zähe Sache, durch die Elite an den anderen Feldern farmen derzeit alle ihren Ruf am einzigen Feld ohne Elite-NPCs und stehen sich dabei oft auf den Respawn wartend die Füße in den Bauch.

**Comment by ErnisKommentar** [comment]
Interessiert die Verantwortlichen hier nicht. Die Datenbank zu öffnen und ne Zahl zu ändern, kostet zu viel Kraft und Zeit. Dann doch hier lieber etwas rumtrollen.

**Comment by Karmanaz** [comment]
@nightblizard  Das ist doch mit dem anderen Task schon behoben worden. Also kann auf Closed.

**Comment by dagochen** [comment]
Mobs sind nicht mehr Elite --> Closed!
