### ISSUE TITLE
(Horde)Quest: Treuebeweis

### ISSUE THREAD

**Issue by mfgmw** [ClassicWoW/Nefarian_1.12.1_Bugtracker#404]
Welches Verhalten wird beobachtet?
- Man kann keine Kerze aus der Kiste nehmen, so wie es dort beschrieben und nötig ist.

Wie sollte es sich verhalten?
- Man sollte eine Kerze des Heranlockens aus der Kiste neben Gunther Arkanus bekommen um am Altar Lillith Nefara heraufzubeschwören und zu töten.

Schritte zur Reproduzierung:
- Quest starten und Kiste anklicken.

Zusätzliche Informationen (Screenshots, Videos, etc.)
- WDB gelöscht, Addons ausgeschaltet, Client neugestartet half alles nichts

Links aus unserer Datenbank
Quest: http://datenbank.welli-it.de/?quest=409
Kerze: http://datenbank.welli-it.de/?item=3080

**Comment by Larnak1** [comment]
Ich hab die Quest vor kurzem gemacht, bei mir hat es funktioniert. Hast du die Kiste gar nicht gefunden oder hat sie dir nichts geben wollen? Vielleicht kannst du es noch ein bisschen genauer beschreiben.

**Comment by mfgmw** [comment]
Hi, wie gesagt die Kiste ist ja direkt neben ihm (schätze das es die ist). Sie ist Leer und das Fenster was sich öffnet ist auch leer dementsprechend hab ich auch keine Kerze. Wenn nötig mach ich auch noch ein Video wenn nötig

**Comment by dagochen** [comment]
Ich kann den Fehler leider nicht reproduzieren. Falls dir noch etwas einfällt, was du vielleicht anders gemacht haben könntest, kann ich mir das gern nochmal anschauen.
