### ISSUE TITLE
Gruppenanmeldung und Schlachtzugsanmeldung PvP in WS/AB/AV

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#407]
Welches Verhalten wird beobachtet?
Gruppenanmeldungen gehen maximal bis 4 Personen, ab einer Größe von +5 Personen, vor allem als Schlachtzug, bekommt man kein beitreten zu einem BG

Wie sollte es sich verhalten?
Anmeldung und beitreten soll bei Warsong bis 10 Spieler gehen
Anmeldung und beitreten soll bei Arathibecken bis 15 Spieler gehen
Anmeldung und beitreten soll bei Alteractal bis 15 Spieler gehen

Schritte zur Reproduzierung
Gruppe, bzw. Schlachtzug erstellen, BG's anmelden und vergebens auf einen Beitritt warten.

Beste Grüße

Chichi

**Comment by c0keh** [comment]
wirst wahrscheinlich noch quellen dazu raussuchen müssen

**Comment by ChichiWarrior** [comment]
Quelle für AV?

Warsong und Arathibecken sollte ja klar sein.

**Comment by Ilikegyoza** [comment]
Wir waren heute als 7ner Gruppe für WSG und Arathi gemeldet und haben auch einen Invite bekommen.

**Comment by Frostlatte** [comment]
@Ilikegyoza  Der BG - Invite funktioniert im Kern auch, jedoch werden nicht alle der Gruppe eingeladen, wenn der BG schon voll ist. Heißt, wenn in dem von Euch angemeldeten BG schon 4 Personen gewesen wären, bleibt einer von Euch draußen, trotz Gruppenanmeldung.
