### ISSUE TITLE
Talisman der Ephemeren Macht CD

### ISSUE THREAD

**Issue by disc0** [ClassicWoW/Nefarian_1.12.1_Bugtracker#410]
Welches Verhalten wird beobachtet:
Der Talisman der Ephemeren Macht löst bei Benutzung einen Cooldown von 2 Minuten aus.

Wie sollte es sich verhalten:
Der Talisman der Ephemeren Macht sollte bei Benutzung einen Cooldown von 1 Minute 30 Sekunden auslösen.

Schritte der Reproduzierung:
TdEM anlegen und anschließend benutzen.

Zusätzliche Informationen:
WCM-Link zum Beweis-Video (Upload-Datum 23.10.2005):
http://www.warcraftmovies.com/movieview.php?id=8903
Youtube-Mirror (Reupload) des besagten Videos (da bei WCM Premium benötigt wird zum DL):
https://www.youtube.com/watch?v=FLEhudSh51U
Forumspost über DMG-Berechnung gibt ToEP mit "+175 dmg every 90s" an: 
http://forums.nurfed.com/showthread.php?3274-Your-opinion-on-Talisman-of-Ephemeral-Power&p=27757&viewfull=1#post27757
Link zum Item in der Datenbank:
http://datenbank.welli-it.de/?item=18820

Anmerkung:
Erste Benutzung des Trinkets im Video bei ~ 0:45 (oberste linke Aktionsleiste). Konnte auch keine Informationen zu einem Nerf in den Patchnotes (1.1.0-1.12.2 durchgesehen) finden (abgesehen vom allgemeinen Trinket Nerf um Doppelnutzung zu verhindern, sollte aber nichts am CD des Trinkets selbst ändern).

Grüße,

Xarten

**Comment by Wosser** [comment]
Nein tut er nicht. Nach der Aktivierung steht nur 2 min CD dran, weil im Tooltip einfach aufgerundet wird. Wenn der Cooldown zur Hälfte abgelaufen ist, stehen im Tooltip noch 45 Sekunden CD.

**Comment by disc0** [comment]
Ah, alles klar, dann bedanke ich mich für die Berichtigung. Hab nur die 2 Minuten gesehen und vorschnell gehandelt. Kann geschlossen/abgelehnt werden, weiß nicht ob ichs löschen kann, kenne mich mit github nicht wirklich aus... :s
