### ISSUE TITLE
Feenfeuer(Tiergestalt) wird der vergebene Talentpunkt nicht mehr angezeigt

### ISSUE THREAD

**Issue by Thornem** [ClassicWoW/Nefarian_1.12.1_Bugtracker#415]
Hallo,
ich habe vor einiger Zeit Feenfeuer im Feraltree(Druiden) geskillt, jetzt ist mir aufgefallen, dass der Talentpunkt da nicht mehr angezeigt wird. In meiner Aktionsleiste wird das Talent aber angezeigt und ich kann es auch benutzen.

**Comment by Larnak1** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/110
