### ISSUE TITLE
Hunter Shots setzten swing timer zurück.

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#416]
Welches Verhalten wird beobachtet?
Wenn man einem multi- oder aimedshot benutzt und danach direkt versucht einen melee angriff oder raptorstrike auzuführen ist dies nicht möglich. Da anscheind der melee swing timer durch die beiden spells (habe ich nur bei den beiden festgestellt) zurück gesetzt wird.

Wie sollte es sich verhalten?
Sollte nicht so sein. 

-Beim Arkanshot funktioniert es.

Schritte zur Reproduzierung
So nach wie möglich an das target heran, multishot casten und auf dne gegner zu laufen und versuchen einen melee angriff/raptorstrike auszuführen.

http://datenbank.welli-it.de/?spell=27632 Aimed
http://datenbank.welli-it.de/?spell=14290 Multi
http://datenbank.welli-it.de/?spell=14266 Raptorstrike

**Comment by smas2810** [comment]
Vielleicht sollte das beim arkanshot auch nicht so sein?! Quelle bitte

**Comment by SirBeansen** [comment]
Genau....man sollte auf alle spells einen melee autoattack cooldown bekommen x.X

Aber belehre ich dich gerne unwissender!

https://www.youtube.com/watch?v=aGli2EPbK-A ab minute 2

**Comment by smas2810** [comment]
An keiner Stelle macht er nach einem gezielten Schuss oder Multischuss direkt einen Nahkampfangriff der auf dem Autoswingtimer basiert...

**Comment by Ghulfang** [comment]
Für dich nochmal auf die Sekunde. 2min8sec. Aimed und danach gleich Raptorstoß

**Comment by SirBeansen** [comment]
push

**Comment by Nobugsanymore** [comment]
Ist nicht nur beim Jäger so. Der bug ist bei allen Klassen und u.a. auch beim Tauren-racial "War Stomp" (http://datenbank.welli-it.de/?spell=20549) vorhanden.
Jegliche Form von Cast schluckt im Anschluss einen Meele-swing. Bei einer langsamen Waffe kann das schon sehr nervig sein.
Ich nehme an, dass man aus dem selben Grund "Slam" (http://datenbank.welli-it.de/?spell=20549) nicht richtig verwenden kann.

**Comment by Seniorash** [comment]
Woher hast du das mit Slam? Das ist jetzt geändert worden aber ich kann mir nicht vorstellen dass das richtig ist.
Auf Anhieb habe ich nur Quellen zu BC gefunden aber der Swintimer sollte beim Slam doch resettet werden?

**Comment by SirBeansen** [comment]
ja bei Slam sollte der swing timer zurück gesetzt werden....das ist ein fetter warry push sonst
