### ISSUE TITLE
Hunter +Dmg Talente werden nicht richtig berechnet

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#417]
Welches Verhalten wird beobachtet?
Wenn man Distanzwaffen spezialisierung  skillt wird sich das Talent anscheinden nicht auf die Spells des Hunters aus. 
Beim Autoschuss funktioniert es.

Wie sollte es sich verhalten?
Es sollten alle range spells mehr dmg machen.

Schritte zur Reproduzierung
Am schnellsten kann man es mit Arkan Shot testen...da bleibt der dmg immer gleich.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Eventuel buggen die Talente Monster-/Humanoiden Töten auch mit dem +dmg und +crit Schaden bei Multi- und Aimedshot. Wenn man sich das anschaut ist es möglich sich diese Talente auch noch anzusehen?

http://datenbank.welli-it.de/?spell=27632 Aimed
http://datenbank.welli-it.de/?spell=14290 Multi

http://datenbank.welli-it.de/?spell=19507  Ranged Weapon Specialization 1
http://datenbank.welli-it.de/?spell=19508  " " " 2
http://datenbank.welli-it.de/?spell=19509  " " " 3
http://datenbank.welli-it.de/?spell=19510  " " " 4
http://datenbank.welli-it.de/?spell=19511  " " "5

http://datenbank.welli-it.de/?spell=19153 Humanoidentöten
http://datenbank.welli-it.de/?spell=24295 Monster töten

**Comment by dagochen** [comment]
Humanoidentöten funzt für Arkaner Schuss, Mehrfachschuss, Gezielter Schuss, Schlangenbiss und Arkaner Schusss.

**Comment by Haudraufinix** [comment]
Das Problem ist hierbei wohl, dass Distanzwaffenspezialisierung einen 5% Schadensbonus auf deine Ranged Attacks erzeugt(nachzusehen im Charakterfenster). Arkanschuss hat diese nicht in seiner Schadensformel drin und spuckt darum unabhängig der Schwusswaffenspezi immer den gleichen Schaden aus. Auf Schlangenbiss wirkt das Talent jedoch zuverlässig.
Auf Aimed und Multi müsst es nach eben genannter Theorie wirken jedoch nicht auf die 600 bzw 120 Bonusschaden der Schüsse.

Ich meine aber das ist Retail-like. Finde aber auf die schnelle gerade keine brauchbare Quelle

**Comment by wahaxlekuke** [comment]
Scheint zu korrekt zu funktionieren.

**Comment by Ghulfang** [comment]
Distanzwaffenspezialisierung – Betrifft nun alle Distanzangriffe (z.B. Arkaner Schuss).
http://wow.gamona.de/aktuelles/patchnotes/live/patchnotes-1-7-de/

**Comment by wahaxlekuke** [comment]
Mein Kommentar war auch, dass der Schaden korrrekt erhöht wird und _nicht_, dass es nicht so sein sollte.

**Comment by Ghulfang** [comment]
Arcan Shot ohne Spezialisierung: https://www.dropbox.com/s/1l6bhf4v41b9dec/Screenshot%202015-03-26%2018.34.07.png?dl=0

Arcan Shot mit Spezialisierung: https://www.dropbox.com/s/nk9r23jz7ghdu4z/Screenshot%202015-03-26%2018.37.32.png?dl=0

Schlangenbiss ohne Spezialisierung: https://www.dropbox.com/s/xfraitkpbn6sn1g/Screenshot%202015-03-26%2023.07.17.png?dl=0

Schlangenbiss mit Spezialisierung: https://www.dropbox.com/s/hp55h4dsx7orm97/Screenshot%202015-03-26%2022.57.29.png?dl=0

**Comment by wahaxlekuke** [comment]
Ok. Ich war etwas verwirrt. Was funktionieren tut, ist z.B. Humanoidentöten (ungeskillt 183, mit skill 188). Nur die Distanzwaffenspezialisierung funktioniert nicht.
