### ISSUE TITLE
Gegnerische Hunterfallen sind unsichtbar

### ISSUE THREAD

**Issue by smas2810** [ClassicWoW/Nefarian_1.12.1_Bugtracker#418]
Welches Verhalten wird beobachtet?
Im PvP werden die Hunterfallen der Gegner nicht angezeigt.

Wie sollte es sich verhalten?
Die Fallen sollten sichtbar sein.

Schritte zur Reproduzierung
Im Duell oder einen Jäger der gegnerischen Fraktion Fallen legen lassen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=1NoiL-PKq8E
Bei ca 07:57 ist die Eisfalle genau zu erkennen bevor sie aktiviert wird.

Links aus unserer Datenbank:
http://datenbank.welli-it.de/?spell=13809
http://datenbank.welli-it.de/?spell=14311
http://datenbank.welli-it.de/?spell=14305
http://datenbank.welli-it.de/?spell=14317

**Comment by Ghulfang** [comment]
das Video ist aus Sicht eines Schurken. Welche Klasse spielst du? Hier auf dem Server sehen Schurken die Fallen und können diese auch entschärfen.

**Comment by smas2810** [comment]
https://www.youtube.com/watch?v=fnu24GvWuWA
03:57

**Comment by SirBeansen** [comment]
Du kannst die Fallen nur vorher sehen als Schurke....und die Szene bei 3:57 wird sie sichbar weil sie ausgelößt wurde.....
