### ISSUE TITLE
Runenverzierte Verzaubererruten sind nicht abwärtskompatibel

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#421]
In den Itembeschreibungen von Verzaubererruten heißt es "Kann auch wie jede geringere runenverzierte Rute verwendet werden." Im Spiel benötigt man aber für jede Verzauberung die entsprechende Rute, mit einer Runenverzierten Goldrute kann man z.B. keine Verzauberung durchführen, für die eine Runenverzierte Kupferrute benötigt wird.

Links:

http://datenbank.welli-it.de/?item=11130
http://datenbank.welli-it.de/?item=11145
http://datenbank.welli-it.de/?item=11130

**Comment by wahaxlekuke** [comment]
Die Beschreibungen der Gegenstände sind falsch. Die Verzauberungsruten sind erst mit TBC "abwärtskompatibel".

Siehe http://www.wowwiki.com/Patch_2.0.1

> Spells can now require either a totem item or a totem category item to cast a spell. This means that the Enchanting Rods now count as all of the lower level enchanting rods as well, so you only need a single enchanting rod instead of all six. This also means that "Finkle's Skinner" now counts as a Skinning Knife. Several weapons that are picks have been flagged as counting as a Mining pick as well.

**Comment by ircfelix** [comment]
Mal wieder ein Fall von nem schlechtest rrecherchierten Bugreport. Gut dass Wahax das klarstellen konnte.

**Comment by Larnak1** [comment]
Jeder macht mal Fehler :)

**Comment by Cleptomaniac** [comment]
TBC nie gespielt, woher soll ich das wissen du schlaumeier!?
