### ISSUE TITLE
Psychic Scream

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#424]
Wie im Tooltip angegeben sollte der Psychic Scream eine Chance besitzen bei Schaden zu brechen.
Meinen Beobachtungen in den Battlegrounds zufolge funktioniert das bei uns auf dem Server nicht korrekt. Man sind eigentlich immer 8 Sekunden im Fear, egal wie viel Schaden man bekommt.

Wenn ihr euch das bei Gelegenheit anschauen könntet, wäre das sehr nett.

Quelle: http://www.wowwiki.com/Psychic_Scream

Datenbank: 
Rank 1 http://datenbank.welli-it.de/?spell=8122
Rank 2 http://datenbank.welli-it.de/?spell=8124
Rank 3 http://datenbank.welli-it.de/?spell=10888
Rank 4 http://datenbank.welli-it.de/?spell=10890

**Comment by maganzi** [comment]
Sieht man auch im raid wenn ein Priester feared... Da können 10k dps draufprasseln... Interessiert den Mob nicht.
