### ISSUE TITLE
Magiertalente: Schutz des Frostes/Verbesserter Feuerzauberschutz/Eisblock

### ISSUE THREAD

**Issue by Xardor2492** [ClassicWoW/Nefarian_1.12.1_Bugtracker#425]
Hallo Entwicklerteam, mir ist aufgefallen, dass die beiden Talente: Schutz des Frostes/Verbesserter Feuerzauberschutz nicht ordnungsgemäß funktionieren. Dh. der Spellreflect von 20% Chance ist gleich Null (wir haben das mit Frobo/Feuerball R1 ausprobiert)

Außerdem gibt es die Möglichkeit für Klassen und Bosse mit Purgefähigkeiten den Magier im Eisblock zu dispellen (Garr oder auch Priester im PvP).

Idealer Zustand: im Eisblock ist man gegenüber jeglichen Schaden/Einflüssen Immun aber Bewegungsunfähig

Die ganze Magierfraktion würde sich freuen wenn ihr euch das mal bei Gelegenheit anschauen könntet.

Vielen Dank

**Comment by Sabbaer** [comment]
quote: Außerdem gibt es die Möglichkeit für Klassen und Bosse mit Purgefähigkeiten den Magier im Eisblock zu dispellen (Garr oder auch Priester im PvP).
gleiche mit Gottesschild
