### ISSUE TITLE
PvP Klassen Begleiter

### ISSUE THREAD

**Issue by Xardor2492** [ClassicWoW/Nefarian_1.12.1_Bugtracker#426]
Hallo zusammen, 
die Arten der Begleiter sind nicht richtig angepasst, Bedeutet zb. dass im BG Hunter gegnerische Hunterpets nicht fearen können, Hexenmeister keine gegnerischen Hexerpets verbannen, oder Palas an hexerpets keine Exorzismen durchführen können. 

Würdet ihr euch das mal anschauen?

**Comment by Armauskugelbob** [comment]
#299 gehört auch dazu
