### ISSUE TITLE
Knochenhäschers Schneide

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#428]
Welches Verhalten wird beobachtet?
Knochenhäschers Schneide verursacht einen Procc, der die Rüstung bei einem Gegner 3 * 700 ignoriert.
Nach Testversuchen an diversen Gegnern verhält sich die Proccchance weit mehr als 50%.

Durch diese hohe Proccchance ist Knochenhäschers Schneide im Moment BiS, sowohl im PvE, wie auch im PvP.

Wie sollte es sich verhalten?
Die Proccchance sollte sich bei 15%-20% "einpendeln".

Schritte zur Reproduzierung
Duell machen / Trainingspuppe auf dem Testserver und Kniesehne spammen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Video folgt, sobald der Testserver läuft.
Dev als Beobachter dabei gehabt.
Kommentare von damals gibt es, leider keine zuverlässige Quelle, deshalb nenne ich die Quelle vorerst nicht und füge sie nur auf Nachfrage ein.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?item=17076

**Comment by Bladsn** [comment]
Leider keine genaue Proccchance, aber eventuell eine kleine Hilfe: http://www.wowwiki.com/Bonereaver's_Edge

**Comment by ircfelix** [comment]
Es gibt auf wowwiki eine history Funktion mit der man auf den Eintrag von 2006 zurückspringen kann.

**Comment by Ilikegyoza** [comment]
Das sollte auf jeden fall verändert werden. Mittlerweile läuft jeder Krieger damit rum.

**Comment by Malize** [comment]
Dann bitte nur Patchen wenn es einen genauen Richtwert gibt...

**Comment by drgrey** [comment]
Ich hab letztens mal was von 6 PPM (proccs per minute) gelesen. Aber ich kann den Artikel nicht mehr finden. Das ändert aber nichts an der Tatsache, dass "Knochenhäschers Schneide", so wie alles andere auch, viel zu oft procct.
