### ISSUE TITLE
Verbuggte Quest in Dunkelküste "GESUCHT: Gurgelbacke!"

### ISSUE THREAD

**Issue by genesis1712** [ClassicWoW/Nefarian_1.12.1_Bugtracker#429]
Hey,
mir ist beim questen in Dunkelküste ein Fehler aufgefallen.

Welches Verhalten wird beobachtet?

Gurgelbacke ist nicht vorhanden. Weder so, noch wenn man das Murlocdorf erledigt.

Wie sollte es sich verhalten?

Laut Buffed.de sollte er eigentlich aus dem Meer kommen, wenn man die Murlocs in dem Dorf erledigt hat

Links aus der Datenbank:

http://datenbank.welli-it.de/?quest=4740

**Comment by c0keh** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/335
