### ISSUE TITLE
General Marcus Jonathan

### ISSUE THREAD

**Issue by Faafaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#433]
Welches Verhalten wird beobachtet?
General Marcus Jonathan kniet die ganze Zeit vor dem Eingang nach Stormwind. Der knieende General lässt sich nicht ansprechen. dadurch lässt sich das Quest Botschaft nach Sturmwind nicht abschliessen.

Wie sollte es sich verhalten?
Er sollte die meiste Zeit auf seinem Pferd vor der Statue am Eingang stehen. Die knieende Position ist meines Wissens Teil der Abschlusszeremonie bei der Übergabe von Onyxias Haupt.

Schritte zur Reproduzierung
Vor dem General ausgeloggt und an zwei aufeinanderfolgenden Tagen wieder eingeloggt. Er hat seine knieende Position nicht verändert.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.google.ch/search?q=general+marcus+jonathan&safe=off&biw=1920&bih=865&source=lnms&tbm=isch&sa=X&ei=CJXKVJWcEsW7ygPr1YDIAw&sqi=2&ved=0CAYQ_AUoAQ

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?quest=120
http://datenbank.welli-it.de/?npc=466#drop

**Comment by Faafaa** [comment]
Dürfte sich erübrigt haben. Nach insgesamt 5 Tagen hat General Jonathan seine Meditation beendet und begrüsst die Helden wieder hoch zu Ross am Eingang von Stormwind.

**Comment by heildose** [comment]
Er kniet sobald jemand die Ony Pre Questreihe in SW abgibt, eventuell wird er nach dem erfolgreichen Beenden der Questreihe nicht richtig resettet (die Ony Pre Questreihe ist ebenfalls buggy)

**Comment by Archidamos** [comment]
Kann das bestätigen, jedesmal wenn wer ony pre macht bleibt er bis zum nächsten Restart hocken
