### ISSUE TITLE
Battleground Spieleranzahl

### ISSUE THREAD

**Issue by Brahe2k7** [ClassicWoW/Nefarian_1.12.1_Bugtracker#435]
Welches Verhalten wird beobachtet?
Im Arathibecken startet man das Spiel mit 8 VS 11. Es ist hat niemand das BG geleaved.
Warsongschluch Start 6 : 10. Es ist hat niemand das BG geleaved.

Wie sollte es sich verhalten?
Es sollten beim Start eines Bgs niemals mehr als 1 Spieler mehr einer Fraktion sein, auser die Mindesanzahl der Spieler ist nicht erreicht.

Schritte zur Reproduzierung
Arathbecken oder Warsong joinen und die Spieleranzahl überprüfen.

**Comment by ircfelix** [comment]
Quelle?

**Comment by SirBeansen** [comment]
Wahrscheinlich haben die Leute den Bg inv nicht angenommen. Dadurch kommt oft das ungleichgewicht.

**Comment by Brahe2k7** [comment]
Dafür eine Quelle? Hast du damals gezockt? Wie soll man dazu bitte ein Quelle finden, aber es sollte doch logisch sein. Genauso das 14 : 16 im BG zu spielen nicht Blizzlike ist. Ich kann mich nich errinnert jemals so etwas erlebt zuhaben. Man sollte eben Invites nur +1 raus geben und nicht einfach 10 bzw 15 wenn von der andern Fraktion nur 6 bzw 8 annehmen.

**Comment by ircfelix** [comment]
Ich meinte de vorletzten absatz.

**Comment by dagochen** [comment]
Dies kann geschlossen werden. Das PvP-System hat damals nicht einzeln Leute eingeladen und überprüft, ob es ausgeglichen ist. Aktuell auf den Offi-Servern ist es so, aber damals nicht. Wenn auf der einen Seite der Fraktion nicht alle den BG-Invite annehmen, dann hatte die Fraktion halt Pech. 

Das Problem mit 14vs16 im Arathibecken oder 11vs9 in Warsong ist ein anderes Problem und sollte getrennt behandelt werden.
