### ISSUE TITLE
Sturmangriff Bug im BG

### ISSUE THREAD

**Issue by Schnitzelkoenig** [ClassicWoW/Nefarian_1.12.1_Bugtracker#438]
Hallo,

seit dem letzten Update kann es beim Krieger vorkommen, dass sollte es während des Sturmangriffes zu einem Stun kommen, der Krieger sich nicht mehr im BG bewegen kann.
Die einzige Möglichkeit die besteht, um diese Problematik zu lösen ist per Alt+F4 das Spiel zu beenden, was jedoch im BG eine Problematik darstellt.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/436
