### ISSUE TITLE
Quest "Kirtonos der Herold" - Loot Fehler

### ISSUE THREAD

**Issue by thebadcat** [ClassicWoW/Nefarian_1.12.1_Bugtracker#439]
Beim Abgeben der Quest "Kintonos der Herold" konnte ich die Quest abgeben obwohl ich nur noch einen freien Taschenplatz hatte. Deshalb habe ich zwar die Quetbelohnung erhalten, nicht aber die spektrale Essenz. Beim Abgeben der Quest sollte der HInweis "Ihr habt nicht genug Platz" o.ä. erscheinen. Leider habe ich dafür keine passende Quellenangabe gefunden.

Gruß,

BadCat

**Comment by heildose** [comment]
Das gleiche ist mir auch bei anderen Quests passiert, vermute mal dass es ein genereller Fehler ist
