### ISSUE TITLE
Rache des Minenarbeiters

### ISSUE THREAD

**Issue by Faafaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#444]
Welches Verhalten wird beobachtet?
Die Zweihandaxt "Rache des Minenarbeiters" hat im Beschreibungstext stehen: "Dient auch als Spitzhacke." Nachdem ich meine lvl-1 Spitzhacke weggeworfen habe, konnte ich aber nicht mehr weiter Erz abbauen (weder als die Hacke equippt war, noch als sie im Gepäck war).
Mein Char hat das nötige Level zum abbauen des Erzes.

Wie sollte es sich verhalten?
Mit der Hacke sollte Erz abbaubar sein

Schritte zur Reproduzierung
keine

Zusätzliche Informationen (Screenshots, Videos, etc.)
keine

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?item=1893 (Name in der Datenbank und im Spiel stimmen nicht überein).
http://datenbank.welli-it.de/?item=2901 (diese Hacke habe ich bis dahin benutzt)

**Comment by c0keh** [comment]
gleiches gilt für http://datenbank.welli-it.de/?item=19901
und wahrscheinlich alle anderen derartigen items

möglicherweise ist der text auch nur fehlerhaft /aus BC

**Comment by Dotox** [comment]
Der Tooltip ist falsch. In Classic gab es solche Items nicht.

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/40
