### ISSUE TITLE
Loot-Fenster lässt sich nach Entzauberung nicht schließen

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#445]
Sobald sich das Loot-Fenster nach dem Entzaubern öffnet, erscheinen die VZ-Mats bereits im Inventar, ohne dass gelootet wurde. Das Fenster lässt sich dann nicht mehr schließen und wenn man versucht, die Gegenstände zu looten kommt die Meldung "Dieser Gegenstand wurde bereits geplündert." Öffnet sich ein neues Loot-Fenster (z.B. durch Töten eines NPC) verschwindet das verbuggte Loot-Fenster.

Dieser Bug tritt insgesamt nur selten und unabhängig von den entzauberten Gegenständen auf.

**Comment by dagochen** [comment]
Dieser Fehler tritt dann auf, wenn man beim Entzaubern sich bewegt. Einfach den Gegenstand erneut "entzaubern", dann kommt die Meldung das dies nicht möglich ist und das Fenster lässt sich wieder schließen, sodass man nicht erst auf einen Mob zum Looten warten muss.

**Comment by Cleptomaniac** [comment]
tatsächlich, danke.
