### ISSUE TITLE
Gnomeregan Quest: Das einzige Heilmittel ist mehr grünes Leuchten

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#446]
Welches Verhalten wird beobachtet?
Mann kann die Phiole nicht füllen so wie es sein sollte.

Wie sollte es sich verhalten?
Die Phiole sollte zu Füllen sein in Gnomergan bei den Mobs rund um den Verstrahlten Schrecken.

Schritte zur Reproduzierung
Quest machen.

Links aus unserer Datenbank (hier gehts zur Datenbank)
Quest: http://datenbank.welli-it.de/?quest=2962/Das%20einzige%20Heilmittel%20ist%20mehr%20gr%C3%BCnes%20Leuchten
Questitem das benutzt werden muss:
http://datenbank.welli-it.de/?item=9364
Ergebnis für Questabgabe: http://datenbank.welli-it.de/?item=9365

**Comment by Faafaa** [comment]
Gleiches beobachtet.
In 3 Runs an x Mobs getestet, kein Mal konnte die Phiole gefüllt werden.

**Comment by ErnisKommentar** [comment]
Wird niemals behoben, aber danke für die Meldung.

**Comment by dwilhelms** [comment]
Am 30.05. immer noch kein Füllen der Phiole möglich

**Comment by dwilhelms** [comment]
9.07.2016: bug immer noch vorhanden wie oben beschrieben

**Comment by Slimmer2** [comment]
Solange Open da steht sind Bugs nicht behoben
