### ISSUE TITLE
Inventar voll beim rollen - Gewinn - Lootbug

### ISSUE THREAD

**Issue by Anorhin-Alane** [ClassicWoW/Nefarian_1.12.1_Bugtracker#447]
Welches Verhalten wird beobachtet?
Rolle ich auf ein Item in einer Ini mit dem Standard Würfelsymbol bei Plündern als Gruppe in der Grundeinstellung ist das Item nicht lootbar, wenn mein Inventar voll war in dem Moment wo ich das Item hätte zugewiesen bekommen.
Es erscheint immer die Meldung, um diesen Gegenstand wird noch gewürfelt.

Wie sollte es sich verhalten?
Auch Plündern umstellen half nicht, egal ob JGJ oder PM.

Schritte zur Reproduzierung
einfach reproduzierbar, Ini, Plündern als Gruppe, vorher Inventar voll machen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Hier mit meinem Twink:
http://abload.de/image.php?img=wowscrnshot_020115_128fuu9.jpg

Links aus unserer Datenbank (hier gehts zur Datenbank)

**Comment by Gnomorus** [comment]
guckt ihr hier #283
