### ISSUE TITLE
(Allianz)Quest: Blutwurst aus Thelsamar

### ISSUE THREAD

**Issue by Zahtu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#448]
Welches Verhalten wird beobachtet?
* Von den Bergebern wird das Item "Ebergedärme" nicht gedroppt

Wie sollte es sich verhalten?
* Das Item wird gedroppt, wenn die Quest aktiv ist

Schritte zur Reproduzierung:
* Im Gegensatz zu dem "Bärenfleisch" und dem "Spinnensekret" droppen die "Ebergedärme" nicht bei dem in der Gegend ansässigen Mob. Vergleich: 3 Alter Schwärzbär gekillt : 100% Drop, 3 Waldlauerer getötet : 100% Drop, 5 Bergeber gekillt: 0% Drop

Links aus unserer Datenbank
Quest: http://datenbank.welli-it.de/?quest=418
Ebergedärme: http://datenbank.welli-it.de/?item=3172

**Comment by ircfelix** [comment]
Ich weiss nicht wo das Problem ist? In der Db stehen 32%. Du hattest eben Pech. Und nach 5 Kills nen Bugreport zu schreiben... weisst du schon dass du dich mit sowas lächerlich machst?
