### ISSUE TITLE
Oberste Macht stackt nicht mit großem Arkanelixier

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#45]
Wenn man ein Fläschchen der obersten Macht intus hat und dann ein großes Arkanelixier oder ein Arkanes Elixier nimmt, wird die Flask überschrieben, nimmt man eines der Elixiere und dann eine Flask, wird das Elixier überschrieben, die Flask sollte aber mit den Elixieren stacken und nur die beiden Elixiere sich gegenseitig überschreiben.
Quelle: https://www.youtube.com/watch?v=XLmBHOLvCDQ
Links: http://datenbank.welli-it.de/?item=13512
http://datenbank.welli-it.de/?item=13454
http://datenbank.welli-it.de/?item=9155

**Comment by Mathemagier** [comment]
Ist dies nicht noch Aktuell?

**Comment by Sabbaer** [comment]
close plz is gefixed
