### ISSUE TITLE
Spähbericht des Zoraschwarms

### ISSUE THREAD

**Issue by ataniker** [ClassicWoW/Nefarian_1.12.1_Bugtracker#450]
Welches Verhalten wird beobachtet?

Die Spähberichte des Zirkel des Cenarius funktionieren nicht.
Laut des Quests: Taktikscher Einsatz VI
[60+] Spähbericht des Zoraschwarms

Soll man im Zoraschwarm mit der Cenarischen Späherin Azenel reden um die Spähbericht zu bekommen. Leider sagt diese nur den Standardtext "Seid gegrüßt, Name" auch wenn man die Quest angenommen hat.

Wie sollte es sich verhalten?

Der Späher sollte wenn man die Quest besitzt ein Spähbericht des Schwarms aushändigen.

![azenel1](https://cloud.githubusercontent.com/assets/6612706/6038847/19c73c6c-ac61-11e4-9102-5054377bac1f.jpg)
![azenel2](https://cloud.githubusercontent.com/assets/6612706/6038846/19c3b34e-ac61-11e4-8405-534017e5ba09.jpg)

Links aus unserer Datenbank:
http://datenbank.welli-it.de/?quest=8534
http://datenbank.welli-it.de/?npc=15610

**Comment by ircfelix** [comment]
Ich glaube das ist bei allen drei Schwärmen das gleiche Problem! (Gibt ja pro Schwarm eine dieser Quests)

**Comment by ataniker** [comment]
Ja ist es. Habs nochmal beim Regalschwarm getestet und da ist es ebenfalls so. :-(

**Comment by Gnomorus** [comment]
http://datenbank.welli-it.de/?search=Späherbericht+des
