### ISSUE TITLE
Versammlungssteine

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#452]
Welches Verhalten wird beobachtet?
In (normalen) gruppen können versammlugnssteine zum teleporten von gruppenmitgliedern genutzt werden.
die versammlungssteine (und gastwirte) verfügen nicht über die eigentliche „LFG-funktion“.

Wie sollte es sich verhalten? 
Zu classic gab es eine derartige teleportfunktion nicht.
Stattdessen wurde man in einen player-pool für die entsprechende instanz geworfen, woraus dann automatisch gruppen zusammengestelt wurden.
Dem pool konnte man via versammlungsstein, aber auch über gastwirte, beitreten.
Mehr u.a. in den changelogs von http://wow.gamepedia.com/Meeting_Stone

Schritte zur Reproduzierung:
eine gruppe von 4 spielern eröffnen. Als gruppenanführer den spieler, den man porten möchte, auswählen und dann auf einen versammlungsstein (für den man die level-kriterien erfüllt) rechtsklicken. Das portal, das sich nun öffnet,  von einem anderen gruppenmitglied rechtsklicken lasse. (= Der vom gruppenanführer ausgewählte spieler erhält nun eine teleport-option zum genutzten versammlungsstein.)

versammlungssteine (ohne gruppe) benutzen, bzw gastwirte ansprechen, um zu sehen, dass die „gruppen-zusammenstell-funktion“ nicht vorhanden ist.

Zusätzliche Informationen (Screenshots, Videos, etc.): 
„-Meeting stones weren't used for summoning other people, they were used so you can look for other people who queued for that instance.“
http://www.mmo-champion.com/threads/726876-Some-things-you-didn-t-know-about-WoW

"Patch 2.0.1 (2006-12-05): Meeting Stones now function similar to a Warlock Summon spell.“ ← BC patch erst
http://wow.gamepedia.com/Meeting_Stone

**Comment by Slimmer2** [comment]
Hier die Patchnotes bei Einführung der Versammlungssteine.
http://wow.gamona.de/archiv/patch-1-3-patch-notes/

Versammlungssteine

Versammlungssteine befinden sich außerhalb jedes Dungeons und sollen Spielern bei der Suche nach einer Gruppe helfen, mit der sie sich gemeinsam in den Dungeon wagen können. Der Versammlungsstein wird versuchen eine geeignete 5-Personengruppe ausfindig zu machen, indem er nach einem Tank, einem Heiler usw. sucht. Je mehr Zeit verstreicht, ohne dass eine Gruppe gefunden wird, desto weniger wählerisch wird der Versammlungsstein bei der Auswahl der Gruppenzusammenstellung werden.

**Comment by SirBeansen** [comment]
Bug ist bekannt...aber ist von der Community so gewünscht dass es so bleibt mit der Port funktion.

**Comment by Slimmer2** [comment]
Hat aber dann nichts mit Blizzlike zu tun

**Comment by Slimmer2** [comment]
Bitte fixen. Da es aktuell nicht dem Stand von Classic auf den Offiziellen Server entspricht.
