### ISSUE TITLE
schnellfeuer funktioniert oft nicht

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#453]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?spell=3045 funktioniert trotz mehrfachem geklickte oft einfach nicht. Oft funktioniert es erst nach >10s gespamme.

Wie sollte es sich verhalten? 
http://datenbank.welli-it.de/?spell=3045 sollte immer nutzbar sein, wenn nicht auf CD oder gerade am wirken von etwas anderem.

Schritte zur Reproduzierung:
(in bossfights) schnellfeuer aktivieren.

Zusätzliche Informationen (Screenshots, Videos, etc.): 
der bug tritt seit einem server-patch etwa ende dezember häufig auf.
Eine genaue ursache, warum es manchmal funktioniert und andere male nicht, konnte ich noch nicht ausmachen.

**Comment by SirBeansen** [comment]
push...nervt mega....hab ich bei jeden raid den bug...bekomm es immer nur 10 sec verzögert.

PvP teilweiße auch.
