### ISSUE TITLE
Prophet des Schattenhammers / zwielichtprophet

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#454]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?npc=15308 nutzt seine fähigkeiten nicht und hat keine laufroute / steht nur rum.

Wie sollte es sich verhalten? 
Fähigkeiten nutzen und (mit den begleitern) der laufroute folgen.

Schritte zur Reproduzierung:
propheten angreifen

Zusätzliche Informationen (Screenshots, Videos, etc.): 
http://wowdata.buffed.de/npc/Zwielichtprophet-15308 (laufrouten. nicht aus vanilla aber wahrscheinlich die selben)
http://datenbank.welli-it.de/?npc=15308#abilities fähigkeiten

**Comment by hraesvelgr** [comment]
wurde indirekt mit https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/26 schon reportet, aber für behoben erklärt. auch auf anfrage nie wieder geöffnet worden.

sämtliche mobs in silithus brauchen einfach mal ein rework, da sie in 90% der fälle weder fähigkeiten, noch laufrouten haben und teilweise auch zu groß oder zu klein sind, sowie keinen korrekten status haben (elite oder nonelite, bei den braunen spinnen zb)
