### ISSUE TITLE
Quest: eine Plage kommt über euch

### ISSUE THREAD

**Issue by Hades30005** [ClassicWoW/Nefarian_1.12.1_Bugtracker#456]
Welches Verhalten wird beobachtet?
Beim Anklicken des Fasses im Sägewerk der westlichen Pestländer passiert nichts obwohl das gefüllte Termitenfass im Inventar ist

Wie sollte es sich verhalten?
Beim Anklicken des Fasses sollen die Termiten freigelassen werden

Schritte zur Reproduzierung
Quest machen

http://datenbank.welli-it.de/?quest=5904

**Comment by Hades30005** [comment]
Spielername: Seuchenwind

**Comment by Gnomorus** [comment]
Man sollte mit dem Fass mit Pestlandtermiten (http://datenbank.welli-it.de/?item=15044) im Inventar das Termitenfass(http://datenbank.welli-it.de/?object=177491) benutzen können.

**Comment by Larnak1** [comment]
Benutzen kann man die Kiste:
http://datenbank.welli-it.de/?object=177490
aber es gibt dann nur eine Beschreibung. Beenden oder fortsetzen lässt sich nichts und das Fass im Inventar lässt sich auch nicht benutzen.

**Comment by Archidamos** [comment]
kann ich bestätigen.

**Comment by Xgna** [comment]
Besteht das Problem immer noch ?

**Comment by Slimmer2** [comment]
Es steht kein Label behoben dran.
