### ISSUE TITLE
Leerwandler läuft beim Kampf vorwärts

### ISSUE THREAD

**Issue by Hades30005** [ClassicWoW/Nefarian_1.12.1_Bugtracker#457]
Welches Verhalten wird beobachtet?

Beim attackieren eines Gegners passiert es gelegentlich das der leerwandler stockend mit dem Gegner nach vorne bewegt

Wie sollte es sich verhalten?
Der Leerwandler soll den Gegner auf der Stelle halten, an dem er ihn angegriffen hat

**Comment by Hades30005** [comment]
Spielername: Seuchenwind

**Comment by wahaxlekuke** [comment]
Genau das gleiche Problem, wie #455. Ich habe den Fehler bereits gefunden.
