### ISSUE TITLE
Eis, Feuer und Schattenreflektor

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#458]
Hallo, die 3 genannten Reflektoren funktionieren hier auf dem Server nicht ordnungsgemäß.

Welches Verhalten wird beobachtet?
Aktiviert man einen der 3 genannten Reflektoren passiert bei den meistens Zaubern nichts, einige Zauber werden allerdings schon reflektiert z.B die Eisfalle.

Wie sollte es sich verhalten?
Aktiviert man einen der 3 genannten Reflektoren, sollte man 5 Sekunden lang die Art von Magie reflektieren. Mit Effekt und Schaden.

Schritte zur Reproduzierung
Gyrofrosteisreflektor nutzen und einen Frostblitz auf sich Zaubern lassen

Zusätzliche Informationen (Screenshots, Videos, etc.)
In diesem Video sieht man bei Minute 5:36 das der Zauber reflektiert wurde und der Zaubernde dabei stirbt,
Video: https://www.youtube.com/watch?v=3vNgeutZ1vE
Gyrofrosteisreflektor: http://datenbank.welli-it.de/?item=18634
Hyperstrahlender Flammenreflektor: http://datenbank.welli-it.de/?item=18638
Ultrablendender Schattenreflektor: http://datenbank.welli-it.de/?item=18639

**Comment by ircfelix** [comment]
Also Frostnova wird reflektiert.

**Comment by Ilikegyoza** [comment]
Wenn sich ein paar Allys bereit erklären, könnte man testen welche Spells schon reflektiert werden und welche nicht

**Comment by Sabbaer** [comment]
Verderbnis: JA,JA,JA
Fluch der Pain: JA,JA,JA
Todesmantel: JA,JA,JA
Furcht: JA,JA,JA
Schreckensgeheul: JA,JA,JA
Lebensentzug: JA,JA,JA
Schattenblitz:Nein,Nein,Nein

**Comment by wahaxlekuke** [comment]
Das kann morgen auf dem Testserver ausprobiert werden.
