### ISSUE TITLE
Druidentalente: Talentpunkt für "Feenfeuer (Tiergestalt)" wird nicht gezählt

### ISSUE THREAD

**Issue by Sisores** [ClassicWoW/Nefarian_1.12.1_Bugtracker#459]
**Welches Verhalten wird beobachtet?**
Anzeigebug bei der Verteilung von Talentpunkt in "Feenfeuer (Tiergestalt)". Man erhält die Fähigkeit, aber der Punkt wird nicht verteilt, dadurch sinkt weder die Anzahl der verbleibenden Punkte, noch steigt die Anzahl der verteilten Punkte für den Talentbaum. Effektiv müsste der Druide dadurch 52 Punkte verteilen können.

**Wie sollte es sich verhalten?**
Der Talentpunkt sollte bei verbleibenden & verteilten Punkten gezählt werden.

**Schritte zur Reproduzierung**
Talentpunkte beim Druiden verteilen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
![Imgur](http://i.imgur.com/TSuPUmt.png)

**Comment by c0keh** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/110

**Comment by Sisores** [comment]
Sorry, wurde mir bei der Suche nach "druid" nicht angezeigt :/
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues?q=druid
