### ISSUE TITLE
Prestors Talisman der Verschwörung falsche Version

### ISSUE THREAD

**Issue by ataniker** [ClassicWoW/Nefarian_1.12.1_Bugtracker#460]
Das Amulett von Nefarian **Prestors Talisman der Verschwörung** hat hier auf dem Server die falschen Werte.

**Auf diesem Server:**
+30 Beweglichkeit
+1% Hit

**In allen anderen Datenbanken sowie Retail hat das Amulett:**
+25 Beweglichkeit
+1% Hit
+22 Angriffskraft

Weiss nicht warum das noch keinen Schurken, Jäger oder Furor Krieger der dieses Amulett besitzt aufgefallen ist. ~~Ich denke das es sich hier auf dem Server um die Alpha Version des Amulett handelt.~~

Links aus der Datenbank:
http://datenbank.welli-it.de/?item=19377
Quellen:
http://www.wowwiki.com/Prestor%27s_Talisman_of_Connivery
https://www.wow-one.com/database/index.php?item=19377
http://db.vanillagaming.org/?item=19377
https://db.rising-gods.de/?item=19377

- Ateni

**Comment by c0keh** [comment]
deine angaben scheinen aus BC zu stammen.
schau dir mal die unteren comments an: http://www.wowhead.com/item=19377/prestors-talisman-of-connivery#comments

**Comment by DrTonic** [comment]
Der Talisman ist zu Anfang BC Opfer der generellen Itemveränderungen geworden, welche in keinen Patchnotes vermerkt wurden (teilweise wg. der veränderten Hunter Mechanik). 
In deiner ersten Quelle (wowwiki) kannst du rechts neben der Überschrift auf "edit" -> "history" drücken um dir ältere Versionen des Items anzusehen. 
Zum Beispiel unter dem Eintrag: http://www.wowwiki.com/Prestor%27s_Talisman_of_Connivery?oldid=345340 sind die Stats hinterlegt, wie sie auch auf dem Server sind. 

P.S.: Für (A)Fury Warrior ist von der raw dps Prestor minimal besser als der Onyxia Zahn (BoK).

**Comment by ataniker** [comment]
Ok, das wusste ich nicht das es erst mit TBC angepasst wurde.
Mir ist es nur aufgefallen weil ich von einen anderen Classic Server komme auf dem sie die *TBC* Version benutzen.

Ich selbst habe das Amulett nicht und würde es auch als Schurke vom aktuellen Stand garnicht wollen. 
Für 9 itemlvl über Onyxias Zahn ist das Item einfach zu schlecht hier, auch wenn es minimal mehr DPS macht als Allianz Krieger mit Segen der Könige ist die fehlende Ausdauer und Feuerresi einfach ein Downgrade von den Statpunkten her.

**Comment by c0keh** [comment]
ist ja nicht schlimm.
einfach closen, sonst machts ein mod :)
