### ISSUE TITLE
Hitbox bei "größeren" Mobs

### ISSUE THREAD

**Issue by Schnitzelkoenig** [ClassicWoW/Nefarian_1.12.1_Bugtracker#461]
Hallo,

seit dem letzten Update vom 02.02.2015 1.0.4 

- Das Bewegungs-System der NPCs wurde überarbeitet. Vor allem große NPCs sollten sich nun nicht länger auf ihr Ziel drauf bewegen.

kommt es nun dazu, dass sich größere Mobs in MC als auch Ony (BWL war schon clear zum Zeitpunkt des Updates) im Kreis drehen,sich von einem weg bewegen oder sich nach rechts oder links bewegen, obwohl man sich selber nicht bewegt.

Jene Problematik kann doch zu einigen Problemen führen und es wäre schön, wenn nochmal drüber geschaut wird (:

**Comment by Slimmer2** [comment]
Es gibt auch ein Fehler bei dem Pets.
Wenn man Mobs angreift da die Pets immer einen Schritt zurückgehen der Gegener das widerum ausgleicht.
Stellenweise greift das Pet den NPX nicht an, kommt da anscheinend nicht an die Hitbox ran.

**Comment by c0keh** [comment]
laut https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/455 wurde zumindest das mit den pets gefixt. evtl funktioniert dann auch das mit dem bossmovement wieder richtig. hat wahrscheinlich beides was mit dem überarbeiteten movementsystem und hitboxen vom 02.02. zu tun

**Comment by Dotox** [comment]
Besteht das Problem immernoch?
