### ISSUE TITLE
Argentum Dämmerung: Rüstungsquests nicht wiederholbar

### ISSUE THREAD

**Issue by Mooshirn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#462]
Hallo,
die Rüstmeisterin Miranda Knackschloss (http://datenbank.welli-it.de/?npc=11536) vergibt unter anderem 2 Quests für überragende und epische Ausrüstung, die man für Insignien erhalten kann.
Beide Quests gibt es je 4 mal, da die Anzahl der benötigten Insignien mit steigendem Ruf sinkt.

Diese Quests sollten eigentlich wiederholbar sein, sind es jedoch leider nicht (zumindest nicht die für epische Ausrüstung auf ehrfürchtig, die anderen habe ich nicht getestet).
In folgendem Link zu einem alten Rufguide von Gamona steht unter Belohnungen für Insignien:
- Quests sind wiederholbar, es lassen sich mehrere Belohnungen holen
http://wow.gamona.de/archiv/reputation/die-argentumdaemmerung/#insignienbel
Auch auf wowhead und in den Einträgen der Datenbanken anderer Classic Server sind die Quests als wiederholbar markiert.

Die Datenbanklinks zu den 4 Quests für epische Ausrüstung:
- freundlich: http://datenbank.welli-it.de/?quest=9222
- wohlwollend: http://datenbank.welli-it.de/?quest=9224
- respektvoll: http://datenbank.welli-it.de/?quest=9225
- ehrfürchtig: http://datenbank.welli-it.de/?quest=9228

Die Datenbanklinks zu den 4 Quests für überragende Ausrüstung:
- freundlich: http://datenbank.welli-it.de/?quest=9221
- wohlwollend: http://datenbank.welli-it.de/?quest=9223
- respektvoll: http://datenbank.welli-it.de/?quest=9226
- ehrfürchtig: http://datenbank.welli-it.de/?quest=9227

Wie in dem alten Forenthread
http://www.mmobase.de/forum/bugtracker-archiv/1513-argentumdaemmerung-insignienabgabe-nicht-wiederholbar.html
zu sehen wurde wohl bereits mal daran gearbeitet, womöglich wurden die Quests nur teilweise auf wiederholbar gestellt, ich habe nur die epische auf ehrfürchtig bisher getestet.

**Comment by Dotox** [comment]
Die Arbeiten daran wurden eingestellt, da dies erst mit einem späteren Patch kam.
