### ISSUE TITLE
Quest: "Tempo halten". Vorhandener Fehler und entsprechende Fixmethode.

### ISSUE THREAD

**Issue by Nwardho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#463]
http://datenbank.welli-it.de/?quest=1190/Tempo%20halten

Name der Quest: "Tempo halten"
Gebiet: Tausend Nadeln -> Illusionenrennbahn

Normaler Verlauf der Quest: 
- Zamek wird angesprochen und läuft hinten zur schwarzen Maschine, um für eine Ablenkung zu schaffen.
- Gameobject Nr. 179888 [http://datenbank.welli-it.de/?object=179888] 
wird durch Gameobject Nr. 20805 [http://datenbank.welli-it.de/?object=20805] ersetzt.

////Vorhandener Fehler: 
Gameobject Nr. 179888 bleibt bestehen und wird nicht durch Gameobject Nr. 20805 ersetzt.\\\\

Temporärer Lösungsvorschlag solang Script nicht angeglichen werden kann:
------------------------------------------------------------------------------------------------

Ausführen des Commands: ".gobject tar [bzw.] .gobject target" und nach der GUID ausschau halten.
Ausführen des Commands: ".gobject del [GUID]"
Und zu guter letzt das einfügen des Gameobjects zum beenden der Quest:
Ausführen des Commands. ".gobject add [In diesem Falle 20805]

_____________________________________________________________

 Gameobject Nr. 20805 [http://datenbank.welli-it.de/?object=20805] ersetzt somit seinen Vorgänger und mit dem klicken auf das Gameobject wäre die quest beendet.

**Comment by Dotox** [comment]
Bitte Quest verlinken.

**Comment by Nwardho** [comment]
http://datenbank.welli-it.de/?quest=1190/Tempo%20halten

**Comment by Nwardho** [comment]
#push

**Comment by c0keh** [comment]
man kann die quest machen und beenden. nur teleportiert sich zamek von punkt zu punkt und läuft nicht, was einen leicht in die irre führen kann
