### ISSUE TITLE
Sully Balloos Brief

### ISSUE THREAD

**Issue by Archidamos** [ClassicWoW/Nefarian_1.12.1_Bugtracker#464]
Welches Verhalten wird beobachtet?
Die Schriftrolle (Durchnässter Umschlag)die man bei der Leiche von Sully Balloo looten kann, enthält nicht den durchnässten Brief.
(http://datenbank.welli-it.de/?object=2656)

Wie sollte es sich verhalten?
Der durchnässte Brief sollte zu 100% vorhanden sein.

Schritte zur Reproduzierung
Schriftrolle looten.

Links aus unserer Datenbank :
Quest: 
http://datenbank.welli-it.de/?quest=637
Questitems siehe Oben

**Comment by dagochen** [comment]
Ich mach den hier mal zu, da es noch den aktuelleren Eintrag dazu gibt.
