### ISSUE TITLE
Rezzbug

### ISSUE THREAD

**Issue by Mirakuli** [ClassicWoW/Nefarian_1.12.1_Bugtracker#469]
heyho

wie der titel schon sagt gehtz uman Rezzbug...der seit dem letzten Update sehr sehr oft auftritt.
das Wochenende vom 06.02.2015-08.02.2015 war es sehr krass!!

im WSG erst nach dem 4tn rezz erst wircklich wiederbelebt worden!
AB das gleiche!!!
im AV maximal 1x oda 2x das er nicht wiederbelebt hat!

was mir persönlich aufgefallen ist...das genau in der sekunde wo ich wiederbelebt werden sollte und wer anderes im BG gestorben ist und somit an den fh teleportiert wurde zu 99% keine Wiederbelebung statt fand!! inwiefern euch das weiter hilft ka^^...hoffe aber es tut es....
leider ist mir sonst eigentlich nichts mehr dazu aufgefallen!!

hoffe auf baldige lösung dieses Problems!!
is halt krass wenn man alle 3min stirbt und dann nochmal 2min auf Wiederbelebung warten kann im BG!

mfg Alex

**Comment by Dotox** [comment]
Benutzt du ein Addon, welches automatisch den Geist freilässt?

**Comment by dagochen** [comment]
Ich hab heute 2-3h lang BGs gemacht und nur einmal den Rezzbug gehabt. Vielleicht hilft mein Fall ja :) Ich war 1vs4 im Warsong und bin im gegnerischen Flaggenraum gestorben. Am Geistheiler angekommen waren noch 4 Sekunden auf der Uhr, als diese abgelaufen wurden traf mich ein Zauber von einem Spieler im gleichen Moment, als mein Rezz kommen sollte. Dadurch musste ich weitere 30 Sekunden warten. Vielleicht ist es nur Zufall, aber wer weiß :)
