### ISSUE TITLE
Item: Zulianischer Schnitzler

### ISSUE THREAD

**Issue by Discipline1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#470]
Fehler:
Das Item Zulianischer Schnitzler, wird gedropped in ZG von der Hohepriesterin Thekal, sollte auch als Kürschnermesser funktionieren. Dies tut es aber nicht.

Wie sollte es sich verhalten?
Man sollte auch Tiere kürschnern können, wenn man dieses Item nur im Inventar hat ohne ein Kürschnermesser vom Vendor besitzen zu müssen. 

Schritte zur Reproduzierung:
Bitte das Item fixen, damit man mit dem Item auch kürschnern kann.

**Comment by Dotox** [comment]
Kein Bug, lediglich ein Tooltip fehler.

**Comment by wownerds** [comment]
Zur Klarstellung: Das Kürschnermesser sollte +10 Skinning Skill geben (wenn angelegt), ersetzt jedoch kein Kürschnermesser.

Quelle: http://www.wowwiki.com/Zulian_Slicer?oldid=295654
