### ISSUE TITLE
Nefarian

### ISSUE THREAD

**Issue by Ataraia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#471]
Hallihallo!

Da ich vor ein paar Tagen mit nem alten Kumpel gesprochen hab, der mit mir damals auch Classic gespielt hat, wollt ich hier mal reinschreiben, was an Nefarian net richtig funktioniert.

Also, das Problem letztens mit der immens schnellen Spawnrate ist nun behoben.
Allerdings werden die Konstrukte nach dem Tod von Nefarian immer wieder belebt, egal wie oft man sie tötet.

Noch etwas: Nefarian sollte eigentlich Spottimmun sein. 

Quelle: http://fahrenheit-llane.org/smf/index.php?topic=6001.0

Aufm Wiki findet man nichts bezüglich Spott, ich nehme an, dass die Information zu trivial ist. Steht eh auch in der Diskussion drinnen, dass ein spottbarer Nefarian im Prinzip zu einfach wird.

Dann noch der Fear, der übrigens bei Onyxia auch net richtig funktioniert. Normalerweise sollte er sich analog zu Magmadar verhalten.
Soll heißen, dass, wenn der Maintank gefeart wird, der Boss automatisch auf den nächsten in der Aggroliste geht, der NICHT im Fear ist. Momentan behält jedoch der Tank die Aggro bei Onyxia und Nefarian, wenn er gefeart wird, lediglich bei Magmadar funktioniert der Fear korrekt.

Quelle: http://www.wowwiki.com/Onyxia_%28original%29

Beim Artikel zu Nefarian auf WoWWiki steht lediglich, dass sich der Fear genauso verhält wie bei Onyxia und Magmadar.

Falls noch weitere Informationen gewünscht, werd ich mich nochmal auf die Suche machen. ;)

mfg Ata

**Comment by Ataraia** [comment]
So, nochmal bissl Youtube durchforstet und ein Video gefunden.

Quelle: http://www.youtube.com/watch?v=G8LZU9l6mtM

Hier sieht man ganz deutlich, dass mehrere Tanks Aggro aufbauen. Wenn der Maintank im Fear ist, dreht sich Nefarian zum anderen Tank, der im 45 Grad Winkel steht. Das hat zwar zur Folge, dass der Schwanz kurzzeitig im Raid ist, da der Fear aber nur 4 Sekunden dauert, dreht sich Nef anschließend wieder zum Maintank.
Da Orcs einen zusätzlichen Resist gegen Fear haben, ist der MT auch ein Orc. Meine Vermutung ist, dass der MT auch noch das Talent im Schutzbaum mitgenommen hat, das noch einmal 15% Resist gegen Fear bietet.

Wichtig ist auch: Alle Mages casten Arkane Geschosse. Das hat den Hintergrund, dass man im Arkanbaum die Bedrohung von Arkanzaubern um ein noch Vielfacheres senken kann als Frost- oder Feuerzauber. Das bietet den Tanks genügend Spielraum für ihre Aggro.

Und noch etwas: Der Mage-Call! Auf WoWWiki steht, dass man ihn weder Outrangen noch Out-of-Sight setzen kann. Soll heißen, egal wo der Mage steht, der Raid wird IMMER gesheept. Sieht man im Video, dass die Verwandlungen gedispelled werden müssen.

Quelle: http://www.wowwiki.com/Nefarian_%28tactics%29

So, jetzt fällt mir nichts mehr ein. ;)

Es tut mir leid, dass der Post solange geworden ist. ABER: Ich hab heute mit Zenobia gesprochen und dabei ist folgendes rausgekommen:

Nefarian hat aktuell den besten verfügbaren Loot im Spiel. Das wird auch mit AQ40 net viel ändern, denn der nächstbessere Lootgeber ist C'Thun. Alles andere in AQ40 sind nur minimale Verbesserungen, wenn das Zeug net gar schlechter ist (zB Stab der Schattenflamme und Gesegneter Akolytenstab der Qiraj).
Deshalb sollte der Boss dringend weiter verbessert und gefixt werden!

mfg Ata

**Comment by Karmanaz** [comment]
@nightblizard Dieser Task ist schon komplett behoben.
