### ISSUE TITLE
Tierausbilder - Talente verlernen

### ISSUE THREAD

**Issue by Jimsy2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#472]
Bei der Tierausbilderin in der Nachtlaublichtung im Teufelswald stimmt der Text für das Verlernen der Tier-Talente nicht. Dort steht "GOSSIP_OPTION_OUTDOORPVP" statt "Talente verlernen" Siehe Screenshot

![bildschirmfoto 2015-02-10 um 10 29 50](https://cloud.githubusercontent.com/assets/10938662/6124901/9a468ef6-b111-11e4-8f54-ae2bc35285ed.png)

**Comment by wownerds** [comment]
Wird wohl nur ein kleiner Datenbankfehler seien.
