### ISSUE TITLE
Chromaggus TimeLaps

### ISSUE THREAD

**Issue by Ataraia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#473]
Hiho!

Da ich grad so am Schreiben und Suchen bin, hab ich mir gedacht, dass ich auch gleich noch einen Report zum TimeLaps von Chromaggus mache.

Erst einmal: http://www.asga.co.uk/forum/index.php?topic=3003.0

Chromaggus sollte wieder einmal Spottimmun sein, da der TimeLaps im Moment jedoch nicht richtig funktioniert, wäre er dann mit TimeLaps unmöglich zu legen. Na gut, unmöglich vllt nicht, aber das würde ein exaktes Timing mit Unverwundbarkeitstränken erfordern. ;O

Egal, hier mal meine Übersetzung vom TimeLaps.

Beim TimeLaps werden alle Charaktere, die Inline of Sight stehen für 10 Sekunden gestunned und ihre Aggro wird für diese Zeit reduziert. Nach Ablauf dieser 10 Sekunden wachen alle Charaktere wieder aus dem Stun auf und erhalten ihre Aggro LEICHT REDUZIERT zurück.
Deshalb benötigt man beim TimeLaps eine Offtank-Gruppe. Der Tank in der Offtank-Gruppe baut zusammen mit dem Maintank Aggro auf. Wenn TimeLaps kommt, rennt die gesamte Offtank-Gruppe Out of Sight. Kommt der TimeLaps, verliert diese Offtank-Gruppe keine Aggro, da sie nicht vom TimeLaps betroffen sind. Der Tank in der Offtank-Gruppe zieht Chromaggus an seinen Platz zurück. Nach Ablauf des TimeLaps erhält der MT seine Aggro zurück und sollte somit weitertanken können. 

Nach einer gewissen Zeit jedoch kann es passieren, dass der MT von der Aggro des Offtanks überholt wird, da der MT seine Aggro nach jedem TimeLaps zwar zurückbekommt, diese aber immer leicht reduziert wird. Dieses Problem wird ganz einfach gelöst, indem die beiden Tanks die Plätze tauschen, der MT wird der Offtank und umgekehrt. 

IM MOMENT verhält es sich so, dass der MT zwar gestunned wird, seine Aggro jedoch nicht verliert! Das Problem dabei ist aber, dass der MT trotzdem nur noch 50% MaxxHP hat, was es nahezu unmöglich macht, ihn am Leben zu erhalten, da er ja auch noch gestunned ist und somit nicht Ausweichen, Parieren oder Blocken kann. Deshalb müssen die anderen Tanks raus und sofort spotten, da der MT sonst umkippt. Spott sollte bei Chrom aber nicht möglich sein. ;)

mfg Ata

**Comment by nightblizard** [comment]
Hey,

ich gehe das gerade allgemein für alle Fear, Stun, usw. Effekte an und müsste wissen wie sich das verhält, wenn nur ein Spieler in der Aggro Liste ist.
Muss dann der NPC zurückgesetzt werden oder greift er dann dennoch einfach den gestunnten Spieler an?

**Comment by Ataraia** [comment]
Heyho!

Also, der Spieler verliert, wenn er gestunned ist, ja nicht seine gesamte Aggro, sondern nur einen Teil davon (Ich wage zu behaupten, dass es damals auf dem Offi etwa 80% waren, rein vom Gefühl her, aber finde dazu keine Quellen... Deshalb war es ja auch so wichtig, dass die Leute am Anfang langsam machen und dem Offtank Zeit geben!). 
Wenn also nur ein Spieler in der Liste ist, hat er trotzdem Aggro vom Boss.

Dasselbe beim Fear. Dort gibt es zwar keinen Aggroverlust, aber der Boss sollte, wie ich im Nefarian-Bericht geschrieben habe, immer auf ein Ziel gehen, das NICHT gefeart ist, und von allen Zielen, die NICHT gefeart sind, am höchsten in der Aggroliste ist.
Ist nur ein Spieler in der Aggroliste verhanden, bleibt natürlich nix anderes übrig, als dass der Mob wie beim TimeLaps auf dieses Target Aggro hat.

Super, dass du dich darum kümmerst! Wird Onyxia, Nefarian und Chrom wieder recht knackig machen, weil die Leute vermehrt auf ihre Aggro achten müssen. ;-)

mfg Ata
