### ISSUE TITLE
Questitem: Amulett der drachischen Subversion verwandelt in Schwein statt Drache

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#476]
**Welches Verhalten wird beobachtet?**
Das Amulett der drachischen Subversion, das im Rahmen der Ony-Prequest benötigt wird, um sich in einen Angehörigen des schwarzen Drachenschwarms zu verwandeln, um mit Aschenschwinge zu reden, verwandelt den Spieler in ein rosa Schweinchen.

**Wie sollte es sich verhalten?**
Gemäß den Questtexten sollte es den Spieler in einen schwarzen Drachkin verwandeln (genaues Modell unbekannt, ich glaube es war so ein normaler Nahkampf-Drache, wie sie um Onys Hort herum zu finden sind).

**Links aus unserer Datenbank (hier gehts zur Datenbank)**
Amulett des drachischen Subversion: http://datenbank.welli-it.de/?item=16787
Effekt: http://datenbank.welli-it.de/?spell=19937
Aschenschwinge: http://datenbank.welli-it.de/?npc=10321
zugehöriger Teil der Ony-Prequest: http://datenbank.welli-it.de/?quest=6570

**Comment by Haudraufinix** [comment]
Ich meine das Model müsste ein schwarzer Welpling sein, kein Elite Drachkin mit Lanze

**Comment by Larnak1** [comment]
Hier sieht man das Modell:
http://i34.photobucket.com/albums/d115/rahil_blitz/memories/1.jpg
http://www.horderockcafe.com/images/gallery/WoWScrnShot_090405_044924.jpg

**Comment by Haudraufinix** [comment]
Tschuldigung, mein Fail

**Comment by Larnak1** [comment]
Warum geschlossen?
