### ISSUE TITLE
Magier: Blizzard

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#477]
**Welches Verhalten wird beobachtet?**

1) Wenn man Blizzard Castet und kurz vor dem Auslaufen des Kanalisierungszaubers einen neuen Blizzard setzt, sieht man 1x die Animation des neuen Blizzards, dann bricht der neue Blizzard aber fast instant ab. Nervig beim Farmen wenn man mit seinem letzten Mana Blizzard castet, dieser dann sofort abbricht und 20 wütende Mobs auf einen zugestürmt kommen.

2) Allgemein verhält es sich auch so, dass man Blizzard an eine gewisse Stelle auf max. Range hincasten kann (das Blizzardfeld ist dann grün und nicht rot), und vom Cast beginnt wie unter 1. beschrieben nur die Animation und er bricht fast instant wieder ab. Sehr nervig im PVP, wenn man mit Rang 1 Schurken aufdecken will und sich nichts tut.

**SIEHE VIDEO CA: 36-41s**

**Wie sollte es sich verhalten?**

zu 1): Der alte Blizzard sollte wie gehabt abgebrochen werden und der neu angefangene Blizzard sollte dann folgen ohne abzubrechen.

**Schritte zur Reproduzierung**

Mobs pullen, Blizzard nutzen, ansehen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

https://vimeo.com/119592412

**Comment by Larnak1** [comment]
Solche Kanalisierungs-Abbruch-Probleme habe ich auch bei "Hurrikan" (Druide) und Hexenmeister haben neulich berichtet, dass es auch den Feuerregen betrifft. Ich kann Hurrikan oft gar nicht nutzen, da es direkt nach dem ersten oder zweiten Tick wieder abbricht, auch wenn mich nichts haut. Leider habe ich auch keine Idee, woran das konkret liegen könnte.

**Comment by Haudraufinix** [comment]
Selbes Trifft auch für Salve zu, diese bricht auch oft sehr schnell ab und hat dann den vollen 1 Min CD

**Comment by ircfelix** [comment]
Push!!!

**Comment by wahaxlekuke** [comment]
Tritt das immer noch auf?

**Comment by ircfelix** [comment]
Vor ein paar Tagen is es noch aufgetreten, ja!
Zum heuten Zeitpunkt kann ich dazu aber nichts sagen.

**Comment by ircfelix** [comment]
reminder

**Comment by wahaxlekuke** [comment]
Ich kann den Bug leider nicht repoduzieren. Irgendwelche Tipps? Oder vielleicht ein aktuelles Video? Immerhin wurde ein Bug gefixt, der AE-Effekte unterbrochen hat...

**Comment by Haudraufinix** [comment]
Die Salve zumindest scheint dank dem AE fix zu funktionieren, für Blizzard kann ichs dir leider nicht sagen

**Comment by ircfelix** [comment]
Ich denke es könnte sich folgendermaßen verhalten:

Nach dem vorletzten Tick bzw. vor dem letzten tick von Blizzard_A wird ein neuer Blizzard_B angefangen zu casten. Nun endet die Castzeit von Blizzard_A und Blizzard_B, wird abgebrochen.

**Comment by dagochen** [comment]
tritt das noch auf?
