### ISSUE TITLE
[Priest] Innerer Focus - trotzdem Manaverbrauch

### ISSUE THREAD

**Issue by Jaquec** [ClassicWoW/Nefarian_1.12.1_Bugtracker#48]
Welches Verhalten wird beobachtet?
- Innerer Fokus veringert, entgegen der Beschreibung, nicht die Manakosten um 100%, wenn zuvor ein Zauber angecastet und wieder abgebrochen wurde. Der darauf folgende Zauber hat dann normal Mana gekostet. In wie fern die Crit-Erhöhung dabei auch nicht funktioniert hat kann ich leider nicht sagen. Der Buff "Innerer Focus" war auch nach dem abbrechen noch aktiv!

Wie sollte es sich verhalten?
- Laut Beschreibung sollte erst der durchgecastete Zauber vom Inneren Focus betroffen sein.

Schritte zur Reproduzierung
- Innerer Fokus wirken
- Blitzheilung anzaubern
- Blitzheilung abbrechen
- Große Heilung zaubern
- Manaverbrauch beobachten

**Comment by Armauskugelbob** [comment]
http://datenbank.welli-it.de/?spell=14751

**Comment by Larnak1** [comment]
Könnte auch etwas mit #223 zu tun haben, dort wird der gleiche Effekt genutzt
`Apply Aura: Add % Modifier (14)
Wert: -100 `
