### ISSUE TITLE
Söhne von Ragnaros: Manaburn auch nach dem Tod

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#480]
**Welches Verhalten wird beobachtet?**

Die Manabrand Fähigkeit der Söhne von Ragnaros bleibt bestehen wenn sie tot sind, bis die Leichen despawnt sind. (Ähnlich Tatsache, dass auch tote, noch nicht despawnte der Worldbosse noch Spieler sleept #478 )

**Wie sollte es sich verhalten?**

Sollte nicht so sein.

**Schritte zur Reproduzierung**

Söhne von Ragnaros umhauen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Die Söhne beschwörender Zauber: http://datenbank.welli-it.de/?spell=21117  (21110 bis 21117)
(Die Söhne direkt hab ich nicht gefunden)

**Comment by ircfelix** [comment]
Ich schätze mal dass das mit dem out of combat - combat - ooc - combat - ooc - .... zusammen hängt ähnlich wie bei #478 .

Allgemein ist mir aufgefallen dass viele Bosse einen nachm kampf mit c - ooc - c - ooc spam nerven.
