### ISSUE TITLE
Söhne von Ragnaros: Respawn

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#481]
**Welches Verhalten wird beobachtet?**

Die Söhne von Ragnaros respawnen nach dem töten außerhalb der Untertauchphase von Ragnaros erneut. Laut GM Sinau könnte dies wohl mit dem plündern der Leichen zu tun haben.

**Wie sollte es sich verhalten?**

Sollte nicht so sein.

**Schritte zur Reproduzierung**

Söhne von Ragnaros umhauen, plündern.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Die Söhne beschwörender Zauber: http://datenbank.welli-it.de/?spell=21117 (21110 bis 21117)
(Die Söhne direkt hab ich nicht gefunden)

**Comment by Thandor** [comment]
Haben Donnerstag Abend im MC Raid angesagt die Söhne nach dem Töten nicht zu looten. Dies hat ein respawnen der Söhne verhindert. Nachdem Raggi im Staub lag haben wir Probe weise die Söhne gelootet und sie sind ca 5 Sekunden nach dem looten respawnt.

**Comment by wahaxlekuke** [comment]
Sollte mit dem letzten Update (14.02.) behoben sein.
