### ISSUE TITLE
Quest: Gesucht: Gath´llzogg

### ISSUE THREAD

**Issue by Nathuz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#482]
**Welches Verhalten wird beobachtet?**

Nach dem Tod von Gath´llzogg droppt dieser nicht seinen Kopf.

**Wie sollte es sich verhalten?**

Gath´llzogg sollte seinen Kopf droppen wenn er getötet wurde.

**Schritte zur Reproduzierung**

Während der aktiven Quest "Gesucht: Gath´llzogg" den Mob Gath´llzogg töten.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Quest: http://datenbank.welli-it.de/?quest=169
Mob: http://datenbank.welli-it.de/?npc=334

**Comment by dagochen** [comment]
Quest in letzter Zeit erfolgreich gemacht worden.
