### ISSUE TITLE
Netherwind-Set 8er-Setbonus

### ISSUE THREAD

**Issue by Ataraia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#483]
Heyho!

Hab mal ein wenig die Patches von damals auf WoWWiki durchgelesen und folgendes entdeckt:

Der 8er-Setbonus vom T2-Mageset löst momentan den Buff für den Instantzauber erst aus, wenn der Cast beim Ziel trifft. Er verhält sich also so, wie sich der Freizauberzustand verhält.

Nun sollte der Setbonus allerdings so funktionieren, dass er sofort bei erfolgreichem Abschließen eines Zaubers ausgelöst wird.

Quelle: http://www.wowwiki.com/Patch_1.9.0
(Unter Mage: Netherwind Regalia)

mfg Ata

**Comment by ircfelix** [comment]
Noch was: ich habe den Eindruck dass der 8erbonus nur geht, wenn man das set gerade frisch angelegt hat. Beim Anlegen erscheint dann die Zauberanimation und der sound von Frostruestung.
Wenn man beispielsweise im Bg stirbt und geresst wird, erscheinen die Animation und der Sound NICHT. Deshalb vermute ich, dass der 8er Bonus nach dem Tode nicht mehr funzt.

**Comment by Ataraia** [comment]
Kann ich nicht bestätigen. Bonus funktioniert auch nach dem Tod und muss nicht neu equipt werden.

**Comment by ircfelix** [comment]
Danke!
