### ISSUE TITLE
Autohit startet nicht, nachdem man gestunned wurde

### ISSUE THREAD

**Issue by DrTonic** [ClassicWoW/Nefarian_1.12.1_Bugtracker#485]
Welches Verhalten wird beobachtet?
Nachdem man in einer PvP-Situation von einem Stun betroffen ist, startet der eigene Charakter keine Autohits. Der Autohit-Button ist zu dieser Zeit rot hinterlegt, als würde er gewirkt werden. Fähigkeiten sind in dieser Zeit regulär nutzbar. 

Wie sollte es sich verhalten?
Der Charakter sollte sobald er aus dem Stun kommt mit den Autohits beginnen.

Schritte zur Reproduzierung
Der Effekt lässt sich relativ einfach mittels eines Krieger mirror Duells reproduzieren. Derjenige Krieger der sich den Charge fängt, reagiert mit hoher Wahrscheinlichkeit nicht mit Autohits. Gefühlt ist die Häufigkeit des Bugs nach dem Charge eines Druiden in Bärform noch höher als bei Kriegern.  

Zusätzliche Informationen (Screenshots, Videos, etc.)
Falls das Problem nicht reproduzierbar sein sollte, lade ich gerne ein entsprechendes Video hoch.

Ich konnte noch nicht eingrenzen, ob das Problem nur nach Charge-Effekten oder auch nach anderen Stuns auftreten kann. Eventuell kann jmd. aus der Community hier noch Informationen ergänzen.

Links aus unserer Datenbank 
Exemplarisch:
Charge Stun: http://datenbank.welli-it.de/?spell=7922
Intercept Stun: http://datenbank.welli-it.de/?spell=20253

**Comment by Dotox** [comment]
Quelle?

**Comment by DrTonic** [comment]
Ich nehme den Bug mal auf und stelle zeitnah einen Link zur Verfügung. Glaube das macht die Problembehebung einfacher.

**Comment by DrTonic** [comment]
https://www.youtube.com/watch?v=wYcqdwWSBSs&feature=youtu.be

Noch ein paar Informationen:
1) Den Bug gibt es schon länger (hat also vermutlich nichts mit den kürzlichen Änderungen an Charge/Intercept zu tun)
2) Der Effekt tritt in unterschiedlicher Stärke auf: teilweise startet der Autohit mit Verzögerung, manchmal (wie im Video) überhaupt nicht. 
3) Ich habe nochmal gegen andere Stun-Effekte getestet (Cheapshot/Kidneyshot), bei denen es ebenfalls regelmäßig zu diesem Problem kommt.

**Comment by Sabbaer** [comment]
passiert nicht nur dem krieger, ist beim paladin auch so

**Comment by Nobugsanymore** [comment]
Ergänzung: Bei mir startet der Autoattack nach dem charge zwar hin und wieder auchmal so wie er es soll, allerdings verliere ich bevor die autoattack anfängt noch mal 1-2 waffenschwünge. Also bei einer 3,8er waffe können das locker mal 7 sekunden ohne autohit sein. Man wird den bug oft auch nur dann los, wenn man das Ziel abwählt und erneut anklickt.

**Comment by Sabbaer** [comment]
beobachtungen seid patch 1.0.5
starte ich den auto attack während ich gestunnd bin oder habe ich den autoattack am "laufen" während ich gestunnt werde, tritt dieser bugg ein. Nachzuvollziehen bei schurke fieser trick/nierenhieb  krieger: ansturm taure: warstomper
tritt nicht auf bei paladin hammer der gerechtigkeit

**Comment by Sabbaer** [comment]
bugg tritt bei mir nicht mehr auf, patch 12.03.2015
