### ISSUE TITLE
Lokalisierungsproblem mit Chatkanälen.

### ISSUE THREAD

**Issue by caradas** [ClassicWoW/Nefarian_1.12.1_Bugtracker#486]
Die Voreingestellten Channel im Chat sind bei englischem client nicht identisch mit dem deutschen.
Wenn man in den General (/1) mit englsichem Client schreibt ist das nicht lesbar im Allgemein (/1) mit deutschem Client, umgekehrt genauso.

Reproduktion: 
Englisches wow Starten und vesuchen im Genealchat jemanden zu erreichen.

Erwartetes Verhalten:
Sprachübergreifende Serverkanäle, die Voreingestellten Chatkanäle (Allgemein,Lokale Verteidigung, Welt Verteidigung, Gilden Recruitment) müssten Lokalisierungsübergreifend gelinkt sein (trotz des leicht abweichenden namens).
Quelle: Leider nur eigene erfahrung vor etlichen Jahren von Blizz.

**Comment by nightblizard** [comment]
Weißt du seit wann das ungefähr auftritt? Das würde mir bei der Fehlersuche ungemein helfen!

**Comment by caradas** [comment]
Kann ich nicht sagen da ich erst seit wenigen Tagen auf dem Server aktiv bin.
