### ISSUE TITLE
Lootbug durch volles Inventar

### ISSUE THREAD

**Issue by MMMark** [ClassicWoW/Nefarian_1.12.1_Bugtracker#488]
Habe mit vollem Inventar ein Item gewonnen, Item dadurch nicht bekommen, Platz geschaffen und konnte dann nicht mehr looten.

![wowscrnshot_021115_210710](https://cloud.githubusercontent.com/assets/11015080/6202870/a0c2651c-b502-11e4-8b8c-a28b9719f5bb.jpg)

**Comment by Gnomorus** [comment]
gleiches wie #283 und #447
