### ISSUE TITLE
Heileffekt von Vampirumarmung bei Schaden mit Zauberstäben

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#489]
Fehlverhalten:

Vampirumarmung kann im Talentbaum beim Priester erlernt werden, in der Beschreibung heißt es sinngemäß "Peinigt Euer Ziel mit Schattenenergie und heilt alle Gruppenmitglieder 60Sek lang um 20% jeglichen von euch zugefügten Schattenschadens". Dazu müsste ja dann auch Schattenschaden gehören, der mit Zauberstäben zugefügt wird. Das ist aber leider nicht der Fall.

So sollte es sein: 

Zu "jeglichem" Schattenschaden gehört auch Schattenschaden von Zauberstäben, Gruppenmitglieder sollten dann auch durch diesen Schaden geheilt werden.

Reproduktion: Vampirumarmung wirken, Zauberstab mit Schattenschaden auf Ziel anwenden.

Vampirumarmung: http://datenbank.welli-it.de/?spell=15286

Verwendeter Zauberstab: http://datenbank.welli-it.de/?item=5216  (btw. Ingame hat der Zauberstab noch +3 Stärke u. +4 Int, wird in der Datenbank aber nicht angezeigt)

**Comment by ircfelix** [comment]
Das Problem ist dass die Zauberstäbe irgendeinen  Schaden machen, aber nicht den Zauberschaden, den sie sollten.

**Comment by Gnomorus** [comment]
wird mit #412 zusammenhängen. wenn der zauberstabschaden gefixt wurde, erledigt sich dieser report womöglich von selbst.

**Comment by wahaxlekuke** [comment]
http://wow.gamepedia.com/index.php?title=Vampiric_Embrace&oldid=320570
>Does only affect spells that deal Shadow damage and will not grant you healing from Shadow damage wands.
