### ISSUE TITLE
Verstohlenheit fehlerhaft

### ISSUE THREAD

**Issue by cionex** [ClassicWoW/Nefarian_1.12.1_Bugtracker#491]
Welches Verhalten wird beobachtet?

Die Verstohlenheit eines Schurken ist nach dem Update leider oft fehlerhaft. Gerade nach Vanish kommt es oft vor, dass man nach der verbesserten Verstohlenheit gar nicht in die normale Verstohlenheit kommt. Demnach können auch keine Attacken wie z.B. Fieser Trick ausführen kann.

Wie sollte es sich verhalten?
Richtig.

Schritte zur Reproduzierung
Schurke > Verstohlenheit durch Vanish > keine Attacken ausführbar. Ist leider sporadisch der Fehler. Aber oft genug das es die Klasse einschränkt.

PS: Bemerkt habe ich es nach dem Update: http://www.mmobase.de/forum/updates-changelog/6717-update-02-02-2015-1-0-4-a.html

**Comment by Jipptech** [comment]
Kann ich nur bestätigen. 
Solange der Vanish-"Buff" noch aktiv ist, kann man Fähigkeiten nutzen. Sobald dieser aber ausgelaufen ist, ändert sich die Bewegungsannimation und obwohl Verstohlenheit aktiviert ist, können keine Fähigkeiten genutzt werden.
Man muss erst Verstohlenheit deaktivieren und neu aktivieren (nach ablauf des CD) damit man normal aggieren kann.

**Comment by Knacks** [comment]
Noch nicht auf Nefarian aufgespielt oder? Bug ist zumindest aktuell noch vorhanden.

**Comment by Larnak1** [comment]
Nein, sonst würde dort auch "Auf Nefarian" als Label stehen :)

**Comment by cionex** [comment]
@wahaxlekuke 
Bug tritt in manchen Fällen immernoch auf. Können das gerne gemeinsam testen. Gerade wieder paar mal gehabt in Duellen und im BG.
