### ISSUE TITLE
Quest: Buch der Uralten (6027)

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#496]
**Welches Verhalten wird beobachtet?**

Man kann den Questgegenstand  "Edelstein der Schlange" nicht wie vorgesehen an der Nagastatue  auf der Insel im Nordwesten von Desolace nutzen und den Questmob "Lord Kragaru" somit nicht beschwören. Dies macht die Vollendung der Quest unmöglich.

**Wie sollte es sich verhalten?**

Es sollte funktionieren

**Schritte zur Reproduzierung**

Vorquest machen, Folgequest "Buch der Uralten" annehmen und zur Insel gehen. Versuchen das Questitem auf den Nagaschrein anzuwenden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

*Quest:* http://datenbank.welli-it.de/?quest=6027
*Questitem zum beschwören:* http://datenbank.welli-it.de/?item=15766
*Mob der erscheinen soll:* http://datenbank.welli-it.de/?npc=12369
*Item das droppen soll:* http://datenbank.welli-it.de/?item=15803

**Comment by Larnak1** [comment]
Den Eintrag gibt's schon 2 mal:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/6
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/340

**Comment by ircfelix** [comment]
Zeit es zu fixen!
