### ISSUE TITLE
Schattenbrand doppelte Chance auf Resist?

### ISSUE THREAD

**Issue by maganzi** [ClassicWoW/Nefarian_1.12.1_Bugtracker#498]
Hey,

folgender Fehler ist mir aufgefallen:
Er betrifft sowohl den Zauber "Schattenbrand" als auch "Schattenblitz"

Gehen wir mal davon aus ein Schattenbrand trifft gibt es immernoch die chance, dass direkt dabei Widerstanden steht und man den Seelensplitter nicht zurück bekommt...

Beim Schattenblitz kann der Gegner einmal den Schattenblitz widerstehen und falls er doch trifft dem Debuff (Verbesserter Schattenblitz) auch nochmal...

Grüße

**Comment by Gnomorus** [comment]
Beim Schattenbrand sprichst du auch vom Debuff, dem getrennt widerstanden werden kann, richtig?

**Comment by ircfelix** [comment]
Schattenblitzproblem auch bei Feuer und Frostzaubern mit ignite, winterkälte und verbessertes versengen.

**Comment by Wosser** [comment]
http://forums.elitistjerks.com/topic/8487-spell-vulnerability-resist-mechanics/#entry209440
