### ISSUE TITLE
AQ20 - Test (Inheritance)

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#502]
Hallo, wie vorab angekündigt hier unser Bugreport zu AQ20. Wir konnten uns vorher nicht mehr mit den anderen Gilden abstimmen, wollten den Report aber nicht unnötig verspäten.

Trashmobs:
1. Schwarmwache der Quiraj - der Movementspeed der Einheit ist ca 2x so hoch wie er sein sollte
Weiterhin hat der Mob 0 Rüstung, er sollte ca. einen Wert um 3.500 haben. Schaden des Mobs ist auch viel zu gering.
2. Trash-Gruppe um Stecher des Zaraschwarms - Der Movementspeed ist ca 2x so schnell wie der auf dem Offi war. Weiterhin machen die Pakete zu wenig Schaden und das Gift wird zu langsam gecastet, dies erschien deutlich öfter
3. Gladiatorder Quiraj - Die Pakete sind nicht untereinander verlinkt - scheinbar ist immer nur der rechte Mob nicht mit dem linken verlinkt, aber andersherum. Weiterhin machen diese viel zu wenig Schaden.

Kurinaxx:
1. Die Pullrange für den Mob ist ca. 2-3x so hoch wie Sie sein sollte.
2. Die Anzahl der Sandhaufen ist viel zu gering, früher war viel Movement gefragt und unter Kurinaxx war sehr oft ein Ansammlung von Sandhaufen, dies war nicht der Fall, die Spawns müssten mindestens verdoppelt werden.
3. Die Reichweite des Debuffs bei den Sandhaufen ist zu gering, wir schätzen er müsste ca. 5 Yards höher sein. Weiterhin kann man dem Debuff widerstehen, wir sind uns nicht sicher, aber das dürfte nicht so sein.
4. Spieler die über der Maxrange stehen werden nicht mehr zu ihm geportet - es sollten eigentlich alle Spieler in der Instanz zu ihm geportet werden können. Weiterhin ist auf dem Offi-Server quasi immer unter dem geporteten Spieler sofort ein Sandhaufen entstanden.
5. Wenn man auf einer Kante steht und geportet wird oder von Kurinaxx auf eine Kante geportet wird, fällt man durch die Welt und steht unsterblich unter AQ
6. Der Debuff trifft nicht immer alle getroffenen Spieler des Cleaves, sondern oft nur den aktuellen "Tank".

Generall Rajaxx + Event:
1. Die Mobs beim Event laufen deutlich zu schnell und auch die Wellen kommen zu schnell nacheinander, der Speed ist höher als beim nachträglichen Beschleunigen des Events von Blizzard.
2. Alle Mobs inkl. der Hauptmänner haben 0 Rüstung, daher fallen Sie quasi instant um
3. Die Hauptmänner können CCt werden, dies sollte nur bei den normalen Adds möglich sein
4. Generalleutnant Andororov + Kollegen sind nicht heilbar
5. Generall Rajaxx selbst macht viel zu wenig Schaden
5. Generall Rajaxx´s Clap kann durch NR-Pots und NR-Equip widerstanden werden, dies sollte nicht so sein. Weiterhin ist die Freqzuenz des Clap viel zu niedrig.
6. Generall Rajaxx killt Spieler bereits unter 200 HP, nicht erst unter 100 HP, welches der Mindestschaden sein sollte. DIes kann man aber z. B. durch einen NR-Pot verhindern, was nicht so sein sollte.

Sonstiges:
1. Die Skarabäus-Kisten sind nicht abgeschlossen - die sollten sie sein
2. NPC Generalleutnant Andororov ist zu groß in der Darstellung
weiterhin verschwindet der NPC und seine Gruppe zum Teil im Boden. Scheinbar nach dem Kill kann man bei ihm auch keine Items kaufen, es kommt kein Handelsfenster
3. Götzen droppen viel zu viele, quasi jeder Mob hatte 2 Götzen dabei - dafür ist zu wenig Grünes gedroppt
4. Wenn man stirbt, kann man oft den Geist nicht freilassen. Teilweise gibt es auch erhebliche Probleme beim rezzen.

Anmerkungen:
Mit der Fernsicht des Schamanen sind wir bereits durch die Instanz gewandert und haben uns mal Rüstung und HP der Mobs angesehen, dort ist uns aufgefallen, dass die Mobs in vielen Gängen zu nah aneinander stehen, die Rüstung teilweise zu hoch oder zu gering ist (z. B. Schwanzpeitscher des Zaraschwarms - 40.914 Rüstung). Die Bosse haben teilweise zu wenig HP (wie z. B. Ossirian 467k - statt 499k HP)

Positives Feedback:
Insgesamt scheinen alle Mobs wie die Hauptmänner beim Rajaxx-Event alle Fähigkeiten zu haben, die Sie besitzen sollten und setzen diese soweit auch korrekt ein. Auch sind bis auf "Kleinigkeiten" die Bosse in Ordnung. Hier wurde schon viel gearbeitet und dies möchten wir loben. Auch lief der Testserver ab 19 Uhr soweit sehr stabil. Gerne sind wir auch weiterhin bei den Bug-Reports und eventuellen Tests dabei und unterstützen euch beim Release von AQ.

Viele Grüße
Karmanaz
Horde - Inheritance

**Comment by Larnak1** [comment]
"Die Pakete sind nicht untereinander verlinkt"
Das Problem betrifft auch die anderen Trashgruppen (oder zumindest einige), wir haben gestern einige von den 3er-Packs getrennt gepullt.

Zu den Sandhaufen von Kurinnaxx:
Mir ist aufgefallen, dass die gelegentlich erst sichtbar sind, wenn sie schon sehr groß sind, sodass sie direkt explodieren und keine Chance bleibt, noch zu verschwinden.

**Comment by Dotox** [comment]
>1. Schwarmwache der Quiraj - der Movementspeed der Einheit ist ca 2x so hoch wie er sein sollte
Das ist zu 100% korrekt, kannst du in etlichen Videos nachsehen oder aktuell auf dem Offiziellen Server beobachten (daran wurde auch nichts geändert).

**Comment by Larnak1** [comment]
Ich dachte auch, es wäre korrekt, aber in diesem Video:
https://www.youtube.com/watch?v=fST7H_oGKoI&hd=1
wirkt es doch spürbar langsamer als gestern beim Test. Dort sind die etwa so schnell wie der reitende Todesritter.

**Comment by Karmanaz** [comment]
@Dotox Evtl liegt es an der Animation oder falscher Erinnerung das es so wirkt - aber wir hatten geschlossen den Eindruck das die Einheiten im ersten Raum sich zu schnell bewegen.
Auch in dem Video wirkt es deutlich langsamer: https://www.youtube.com/watch?v=2JWhGHllaLA besonders die Trash-Gruppe um Stecher des Zaraschwarms bewegt sich hier sichtbar langsamer als auf dem Testserver.

@Larnak1 
Der Fehler mit der Sichtbarkeit der Sandhaufen stimmt, der wurde oben im Bugreport vergessen. Oft verstecken sich die Sandhaufen auch im Boden und sind teilweise gar nicht sichbar. z. B. auf Schrägen etc.

Und das die Schwarmwache der Qiraji noch Probleme mit der Tankbarkeit haben sollte ist auch korrekt.

**Comment by Seniorash** [comment]
Edit:
Trashmobs: 
2. Verlinkung zwischen den Wespen (http://datenbank.welli-it.de/?npc=15325) und den Stingern (http://datenbank.welli-it.de/?npc=15327) ist nicht vorhanden. Das Anstürmen fehlt bei den Stingern komplett. Außerdem sollten die Stinger nicht rootbar sein (http://www.skryer.com/index.php?art/id:52).

Generall Rajaxx (http://datenbank.welli-it.de/?npc=15341) + Event:
4. Generalleutnant Andororov + Kollegen ( http://datenbank.welli-it.de/?npc=15471 + http://datenbank.welli-it.de/?npc=15473) machen relativ viel Schaden (kann mit zu geringer Rüstung der Mobs zusammenhängen). Die NPCs resetten nach jeder Welle ihre HP.
6. Man stirbt wenn man unter 200 Hp ist und nicht unter 100 (http://www.hordeguides.de/Schlachtzug/Classic/Boss/15341/General-Rajaxx/index.htm)
i) Rajaxx entwaffnet auch Spieler, die keine Aggro haben.
ii) Nach einen Wipe sind Andorov und seine Adds nicht respawned.
iii) Nach einem Wipe bricht das Event nicht ab, sondern läuft weiter bis die letzte Gruppe losgelaufen ist. Wenn nur noch der Boss steht, resettet es.
iv) Rajaxx hat eine zu große Hitbox.

Sonstiges:
2. Auch die Mobs fallen durch den Boden. Außerdem können sie dabei oder durch wegziehen vom Tor resetten. 
4. Wenn man stirbt und dann auf Geist freilassen klickt, verschwindet das Fenster aber man bleibt einfach liegen. Nach einem Relog steht man als Geist auf seinem Körper (in der Instanz).

**Comment by Dotox** [comment]
@Karmanaz 
>@Dotox Evtl liegt es an der Animation oder falscher Erinnerung das es so wirkt - aber wir hatten geschlossen den Eindruck das die Einheiten im ersten Raum sich zu schnell bewegen.
Auch in dem Video wirkt es langsamer bei allen Mobs: https://www.youtube.com/watch?v=2JWhGHllaLA besonders die Trash-Gruppe um Stecher des Zaraschwarms bewegt sich hier sichtbar langsamer als auf dem Testserver.

Das kann echt an der Animation liegen. Also ich bin selbst dafür extra auf den offiziellen Server gegangen (auch allgemein damit wir die Trashpacks so nachbauen können, wie sie im originalen auch sind) und dort sind die Mobs ziemlich schnell oder deutlich schneller unterwegs gewesen als alle anderen.

**Comment by Karmanaz** [comment]
@Dotox Das die Schwarmwache der Quiraj deutlich schneller war als die restlichen Mobs ist auf jeden Fall richtig. Nur ob Sie so schnell sind wie auf dem aktuellen Testserver, das war unser Diskussionspunkt.
Und die Trash-Gruppe mit Stecher des Zaraschwarms ist zu schnell auf dem Testserver (im Vergleich zum Video). Auch sind die Haltepunkte der Trashpacks, die man auf dem Video sehr gut sehen, kann kaum spürbar.
