### ISSUE TITLE
Spelldmg scaling auf Huntern

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#503]
Ich meinte mich zu erinnern, Schlangenbiss und Arkanschuss hatten zu classic relativ gut mit + Zauberschaden skalliert. Darum habe ich mich daran gemacht Quellen zu finden.
Schliesslich habe ich in Dysphoria's bekannter Hunter VS World Serie den Beweis gefunden.

In https://www.youtube.com/watch?v=7XgF_P9Ddjk ab 12:36 ist zu sehen wie der Hunter im Spelldmg EQ und Buffs einen Schlangenbiss einsetzt, der bis zu 336 tickt. Auf Nefarian tickt der Schlangenbiss ungeskillt für 97 Schaden und besitzt einen Zauberschadenskoeffizienten von 0. Lediglich Schusswaffenspezialisierung und verbesserter Schlangenbiss erhöhen diesen Schaden)

Ausserdem wird im selben Video Arkaner Schuss verwendet, welcher mit allen Buffs 644 Schaden ohne Crit anrichtet. Glücklicherweise benutzt der Hunter das Trinket Zandalarianisches Heldenamulett http://datenbank.welli-it.de/?item=19950 welches den Buff "Unstable Power" gewährt (zu sehen u.a. bei 13:17) somit lässt sich cirka auf den Koeffizienten schliessen.

Ein Arkanschuss verursacht mit Flask (+150 Spellpower), Großes Arkanelixier(+35 Spellpower), 2x Hervorragendes Zauberöl(je + 36 Spellpower), Unstable Power(+204 Spellpower),verursacht 644 Schaden

183 Basisschaden + (461 Spelldmg +X Gear Spelldmg) * Koeff Y = 644 Schaden.

ohne den "Unstable Power" Buff hittet Arkaner Schuss noch für 514 (zu sehen u.a. bei 13:41)

183 Basisschaden + (257 Spelldmg +X Gear Spelldmg) * Koeff Y = 514 Schaden
Daraus Folgt:
(461 Spelldmg - 257 Spelldmg) * Koeff Y = 644 - 514
204 Spelldmg * Koeff Y = 130
-> Koeff Y = 130/204
  -> Koeff Y = 63%

Nun können wir relativ leicht auf das Gear des Jägers und damit auf den Koeffizienten von Schlangenbiss schliessen.
183 Basisschaden + (461 Spelldmg +X Gear Spelldmg) * 63% = 644 Schaden
-> (461 Spelldmg +X Gear Spelldmg) * 63%= 461 Schaden
  -> 461 Spelldmg + X Gear Spelldmg = 461/0.63
      461 Spelldmg + X Gear Spelldmg = 731.7
     X Gear Spelldmg = 270.7

Ab 13:50 Tickt der Schlangenbiss, der ohne Trinket aufgetragen wurde für 280 Schaden.
Ausgehend von 270 Zauberschaden auf dem Gear + 257 Spelldmg durch Buffs ergibt sich ausgehend davon, dass warscheinlich Das AQ Buchband für Schlangenbiss Rang 9(555 Schaden über 15 Sek) gelernt wurde und warscheinlich verbesserter Schlangenbiss und Schusswaffenspezialisierung geskillt wurde (ist Anzunehmen bei Skillung mit Volltrefferaura ;)):
Grunddmg * Verbesserter Schlangenbiss * Schusswaffenspezi = Schaden ohne Spelldmg
555 * 1.1*1.05 = 610
Schlangenbiss tickt alle 3 Sekunden. Wir erhalten also 122 Schaden pro Tick. Der DoT im Video tickt aber für 280. Daraus lässt sich schliessen;

Grundschaden + (Gear Spelldmg + Spelldmg von Buffs) * Koeff S = 280 Schaden
122 + (270+ 257)*Koeff S = 280
527*Koeff S = 158
->Koeff S = 158/527
  ->Koeff S = 30% Spellpower pro Tick!

Zur Rechnung:
Da Arkanschuss und Schlangenbiss fixe Schadenswerte und keine Streuung verursachen ist der Schaden bei jeder Anwendung exakt identisch (Sofern keine Trinkets gezündet werden o.ä.).
Zur Quelle:
Dysphoria -> WCM Link http://www.warcraftmovies.com/pv.php?t=3&l=dysphoria
ist ein Jäger der in Classic und BC mehrere Instanzen solo gemacht hat und dadurch den Mythos von Hunter können alles Soloen mitgeprägt hat. Ich bin mir bewusst, dass die Quelle leider ein Reupload aus dem Jahre 2012 ist. Leider Besitze ich kein WCM Premium um an das Originalvideo von 2006 heranzukommen. Ich hoffe die Quelle genügt.
PS:
Flask + Arkanelixier scheint tatsächlich gestackt zu haben. Hier eine anderes Video mit besagtem Doppelbuff https://www.youtube.com/watch?v=oOkz0oxzFSI (ich weis das Video ist etwas neuer, es stammt jedoch aus 1.12 von der top PvE Gilde des Servers Anetheron EU und hoffe hat somit etwas Gewicht. aber das ist ein anderes Thema.)

Ich hoffe ich habe keinen groben Rechenfehler gemacht zu haben.
Gruss Kairina

Zusatzinfo:
Das Video ist Teil einer Serie. Der Videobeweis findet sich in Teil 1. Teil 4 wurde auf Youtube am 4.9.2006 hochgeladen -> siehe https://www.youtube.com/user/dysph/videos ich habe mir allerdings sagen lassen dass manche der Videos von der GEMA gesperrt wurden. Für Leute mit schweizer Wohnsitz oder nem Proxy funktionieren sie aber ;)

**Comment by Haudraufinix** [comment]
Zusatzinfo:
Das Video ist Teil einer Serie. Der Videobeweis findet sich in Teil 1. Teil 4 wurde auf Youtube am 4.9.2006 hochgeladen -> siehe https://www.youtube.com/user/dysph/videos ich habe mir allerdings sagen lassen dass manche der Videos von der GEMA gesperrt wurden. Für Leute mit schweizer Wohnsitz oder nem Proxy funktionieren sie aber ;)

**Comment by Jipptech** [comment]
Wow, ich bin beeindruckt von der Rechnung :) 
Wirklich gut. Ich habe lange versucht Videos dazu zu finden, aber leider habe ich nichts gefunden, da es nichts direkt zu dem Thema gibt, aber wie du das gelöst hast, echt gut.

Freue mich sehr darauf, wenn es gefixed ist und ich wieder Hunter spielen kann.

**Comment by Jipptech** [comment]
Gestern beim daddeln ist mir eingefallen, das "Salve" auch von SpellDMG beeinflusst werden sollte...leider war die Suche nach einem Koeffizienten ohne Erfolg, da sich dazu einfach so gut wie nichts finden lässt :// 
Aber Salve macht ebenso wie Arkaner Schuss, Arkanschade...ich hoffe das ich dazu noch etwas finde, aber ich glaube leider nicht dran.

Darf man denn fragen, wie weit ihr mit der Bearbeitung schon seit?

**Comment by Haudraufinix** [comment]
@ Jipptech
Hier sollten bitte nur genaue Informationen zum Topic rein, eine Diskussion gehört eher ins Forum. Wenn du also genaue Scalings zu Salve hast, nur her damit. Aber ich hab alle Jäger-Skills aufm Schirm und werde es Reporten, sollten welche davon Scalings haben, die nicht mit denen von Nefarian übereinstimmen.

Ich habe mich gleich mal daran gemacht, die neue Änderung zu Begutachten, aber jedoch skalliert mein Arkaner Schuss nur zu 43% (nicht wie er sollte zu 63%) und der Schlangenbiss skalliert stolze 0%

Bitte Issue wieder öffnen

**Comment by dagochen** [comment]
@Haudraufinix 
Bei der 1. Rechnung hast du leider nicht beachtet, dass der Arkanschuss von Talenten beeinflusst wird (Schusswaffenspezi+Humanoidentöten) und dadurch einen Fehler in der Rechnung eingebaut, der sich auf Grund dieser Annahmen leider durch sämtliche Rechnungen zieht und dazu geführt hat, dass du mit falschen Werten weitergerechnet hast. 

Die 644 Schaden sind mit 1,0815 multipliziert. Korrekt wäre also: 
1,0815 * (183 Basisschaden + (461 Spelldmg +X Gear Spelldmg) * Koeff Y) = 644 Schaden.

**Comment by Haudraufinix** [comment]
Stimmt, ich hatte fälschlicherweise angenommen das Schlangenbiss und Arkanschuss wies zum Zeitpunkt des Bugreports auf Nefarian der Fall war, nicht von Schusswaffenspezi und Humanoidentöten profitieren.

Demnach scheinen deine Werte zu stimmen
