### ISSUE TITLE
Emerald Dragons Spawn Timer

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#504]
Hi, 

laut Patch 1.10
"Die vier grünen Drachen sollten jetzt wie ursprünglich geplant spawnen. Sie spawnen jedes Mal gleichzeitig."

Unter: Schlachtzüge und Dungeons
http://wow.gamona.de/aktuelles/patchnotes/live/patchnotes-1-10-de/

**Comment by Gnomorus** [comment]
Ich WUSSTE, dass es so war. endlich hat jmd einen Beweis gefunden.

**Comment by wahaxlekuke** [comment]
Das ist ja auch erst mit Content-Patch 1.10. Die Respawn-Timer sind bewusst so wie sie im Moment sind.
