### ISSUE TITLE
Schattengestalt nicht aktivierbar

### ISSUE THREAD

**Issue by Armauskugelbob** [ClassicWoW/Nefarian_1.12.1_Bugtracker#506]
Nach einer Wiederbelebung ist die Schattengestalt des Priesters häufig nicht mehr aktivierbar und aus gegraut. Dies lässt sich bisher nur durch ein löschen des WTB Ordners beheben was besonders in BGs und Raids lästig wird.
lg :)

**Comment by Dotox** [comment]
Bitte Zauber verlinken.

**Comment by Armauskugelbob** [comment]
Der Zauber "Shadowform" ist aktuell nicht in der Database unter den Priesterzaubern zu finden. Daher hier eine Mobversion: http://datenbank.welli-it.de/?spell=15473#see-also-ability

**Comment by Dotox** [comment]
Das ist leider nicht das gleiche, spiele und units sind unterschiedlich. Vielleicht findest du den Zauber auf WoWhead.com

**Comment by Armauskugelbob** [comment]
Nein leider ist, zumindest für mich, nirgends ein spell mit den passenden Anforderungen zu finden.
Hier ist zwar eine aktuelle Version, glaube aber nicht dass diese uns auf einem 1.12 Server weiterhelfen wird: http://de.wowhead.com/spell=15473/schattengestalt

**Comment by Sabbaer** [comment]
[spell 15473]
class=Priest
name=Shadowform
jo, die spell id ist die selbe
