### ISSUE TITLE
Gromsblut Spawn nicht auffindbar

### ISSUE THREAD

**Issue by Beleidiger** [ClassicWoW/Nefarian_1.12.1_Bugtracker#507]
Das Gromsblut am Punkt 56,9 / 50,4 ist irgendwie nicht da, auch wenn es auf der Minimap angezeigt wird. Steckt vielleicht im Boden drin.
![wowscrnshot_022015_092154](https://cloud.githubusercontent.com/assets/11026247/6283272/4db2c19e-b8e2-11e4-97b8-7b759a8b5936.jpg)

**Comment by Gnomorus** [comment]
#282
