### ISSUE TITLE
Gedankensicht - Priester

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#508]
Welches Verhalten wird beobachtet?
-Gedankensicht  funktioniert nur wenn sich das Ziel  in Sichtlinie befindet

Wie sollte es sich verhalten?
-Gedankensicht sollte unabhängig der Sichtlinie funktionieren. Sobald man das Ziel im Target hat konnte man es früher casten.

**Comment by 0815Priester** [comment]
Rank 1 has a line of sight requirement, Rank 2 does not. 
http://www.wowwiki.com/Mind_Vision?oldid=316815

**Comment by Dotox** [comment]
Zauber Verlinken.

**Comment by 0815Priester** [comment]
http://datenbank.welli-it.de/?spell=10909
