### ISSUE TITLE
NPC Wurfaxt-Textur fehlt

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#51]
Welches Verhalten wird beobachtet?
manche NPCs, wie zB http://datenbank.welli-it.de/?npc=2554, die äxte werfen können, haben eine fehlerhafte "wurfaxt". wenn sie werfen fehlt die textur des geworfenen objektes. man sieht ein blau-weißes kästchen auf sich zufliegen.

Wie sollte es sich verhalten?
textur haben...

Schritte zur Reproduzierung
sich anwerfen lassen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www11.pic-upload.de/24.10.14/ur49nnox7xls.jpg

edit zur übersichtlichkeit:
http://datenbank.classic-wow.org/?npc=2554 axtwerfer der bleichborken
http://datenbank.classic-wow.org/?npc=458 murlocjäger
http://datenbank.classic-wow.org/?npc=4061 mirkfallondryade

**Comment by Adalbern12** [comment]
Auch die Murlocs in Westfall schmeissen würfelchen

**Comment by Slipru** [comment]
http://datenbank.classic-wow.org/?npc=4061 benutzen auch Würfel

**Comment by hraesvelgr** [comment]
hab mir grad mal die dryade angeschaut. mir scheints eher so, dass sie keinerlei spells haben sollte, oder generell den falschen spell benutzt (keine quellen, nur so ein gefühl).

bei den anderen beiden npc (murloc und axtwerfer): kann es evtl mit dem spell zusammenhängen? 
http://datenbank.classic-wow.org/?spell=10277
