### ISSUE TITLE
Aegis der Bewahrung

### ISSUE THREAD

**Issue by Knacks** [ClassicWoW/Nefarian_1.12.1_Bugtracker#510]
Hallo,

datenbank.welli-it.de/?item=19345 <- sollte nicht mit Spellpower/addheal skalieren (oder zumindest nicht so heftig -> also mit einem geringerem Faktor), da ein Priester damit sogar gegen 2 BWL Rogues für 20 Sekunden unbesiegbar ist.

Quelle: Vielleicht findet ja jemand anderes was. So wie´s jetzt ist, ist es auf jeden Fall bei der Dauer von 20 Sekunden zu heftig. 
Effekt: Heal  Wert: 35

MfG

**Comment by 0815Priester** [comment]
man findet nur Quellen bzgl. des addheal aber keine Aussage zu Spelldmg.

**Comment by dagochen** [comment]
Der Heileffekt sollte keinerlei Bonus durch Addheal erhalten. Zu sehen in dem Video https://www.youtube.com/watch?v=qz5SRdQSqxg und nachzulesen in dem Blog http://andreasaronsson.com/2008/03/18/wow-aegis-of-preservation/

Sorry Priesters ;)

**Comment by 0815Priester** [comment]
Patch 1.7  (Items letzter Punkt)
http://www.wowwiki.com/Patch_1.7.0

Hm aber man könnte es ja auch lassen so wie es ist. Habt doch ein wenig Mitleid mit den armen Priestern :-)

**Comment by Knacks** [comment]
Sorry aber es wird von vielen Priestern aktiv genutzt und sowas kann im PvP zum Beispiel im Warsong Spielentscheidend sein, wie es in letzter Zeit auch schon öfters war.... Bei der Horde sind aktuell Schurken ziemlich PvP aktiv und wenn da ein ally-shadowpriest die flagge nimmt und das trinket hat ist das nicht mehr lustig. Wenn man diese leute dann anschreibt und darauf hinweist wird man auch noch beleidigt....(weil sie es genau wissen, dass es buguse ist)

**Comment by Cazukee** [comment]
Habe ich das richtig verstanden? Das Video bezieht sich auf Patch 1.7.0? und es wird geändert mit der Begründung "Es ist zu stark"? Obwohl es keine Patchnotes o.ä. gibt?

**Comment by Cazukee** [comment]
Video Veröffentlicht am 18.03.2008
