### ISSUE TITLE
Unbekante Quest: Marschenfroschschenkel

### ISSUE THREAD

**Issue by Faafaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#511]
Welches Verhalten wird beobachtet?
NPC Sumpfauge Jarl (http://datenbank.welli-it.de/?npc=4792) gab mir beim ersten Kontakt das Quest "Marschenfroschschenkel", welches nicht in der Datenbank zu finden ist. Der Text stimmt mit http://wowdata.buffed.de/quest/Duestermarschen/Marschenfroschschenkel-1218 überein.
Es sollen dann aber nicht 10 Marschenfroschschenkel (http://datenbank.welli-it.de/?item=33202)gesammelt werden, sondern 10 Feine Gewürze. Dieses Questziel würde dem Startquest von Jarl in der Datenbank entsprechen (http://datenbank.welli-it.de/?quest=1218).

Wie sollte es sich verhalten?
Wenn der Datenbankeintrag http://datenbank.welli-it.de/?quest=1218 korrekt ist, muss der Questtext in-game ausgetauscht werden.
Sollte der Datenbankeintrag falsch sein, dann muss sowohl die In-Game Quest (Text und Questziel passen nicht zusammen) als auch der Datenbankeintrag überarbeitet werden.

Schritte zur Reproduzierung
n.a.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Screenshot kann ich auf anfrage schicken.

Links aus unserer Datenbank
Questtext (ingame): http://wowdata.buffed.de/quest/Duestermarschen/Marschenfroschschenkel-1218 
Quest (Datenbank): http://datenbank.welli-it.de/?quest=1218
Item Marschenfroschschenkel (nicht in Verwendung): http://datenbank.welli-it.de/?item=33202
Questgeber: http://datenbank.welli-it.de/?npc=4792

**Comment by ollyhdh** [comment]
Die Quest "Marschenfroschschenkel" existiert wirklich und kommt als erste quest von diesem NPC.
Allerdings fehlen die "Marschenfrosch" Mobs. Diese laufen normalerweise in größeren Mengen auf der "Insel" um die Hütte des Questgebers herum zufällig durch die Gegend, haben ca. 10 HP und droppen soweit ich weiß mit 100% chance einen Marschenfroschschenkel.
Es gab im selben Gebiet auch noch aggro-mobs, die ebenfalls fehlen. Möglicherweise Graunebelspinnen?

Als folgequest gibt es dann die quest http://datenbank.welli-it.de/?quest=1218
(diese gibt im übrigen als Belohnung http://datenbank.welli-it.de/?item=6807   , nicht siecher wie viele.)

**Comment by dagochen** [comment]
#1240 ist behoben und somit auch dieser Eintrag.
