### ISSUE TITLE
Totem des Windzorns proct nicht korrekt auf Fähigkeiten

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#513]
Welches Verhalten wird beobachtet?
Wenn Totem des Windzorns steht, wird der Procc von allen Angriffen ausgelöst. Der Procc funktioniert allerdings nur bei Autoattacks. Bei allen Fähigkeiten kommt jedoch nur die Animation, aber kein Extraschlag. Dabei spielt es keine Rolle, ob es ein On-Swing-Angriff, wie beispielsweise Heldenhafter Stoß, oder eine sonstige Fähigkeit ist. Dadurch ist der wichtigste Buff der Horde zur Zeit fast nutzlos. 

Wie sollte es sich verhalten?
Der Procc sollte von allen Nahkampfangriffen ausgeführt werden, die Schaden  machen. Bei jedem Proc sollte nicht nur die Animation, sondern auch ein zusätzlicher Autohit ausgeführt werden.

Schritte zur Reproduzierung
Windfury Totem stellen und Fähigkeiten spammen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Dass WF nur noch auf Autohits procct, wurde erst zu BC eingeführt. http://wow.gamona.de/2007/08/10/hotfix-windfury-totem-der-schamanen/

Bei 01:07 sieht man deutlich wie WF auf den Autohit und den fast gleichzeitigen MS procct 
https://www.youtube.com/watch?v=MVvl_x2CTrA

Die WF Proccs sollten keine Aufladungen von Schlaghagel aufbrauchen. Bei 07:25 wird durch einen Krit ein WF-Proc ausgelöst. Dieser WF-Proc ist nicht kritisch und dennoch sind danach noch alle 3 Stacks von Schlaghagel da.
https://www.youtube.com/watch?v=ISx6eni6I1k
Heruntergeladen und hochgeladen von: http://worldofwarcraft.filefront.com/file/George_2H_Fury_PvP_Episode_2;69520

Links aus unserer Datenbank 
Windfury Totem: http://datenbank.welli-it.de/?spell=27621
Windfury Buff: http://datenbank.welli-it.de/?spell=10612
Schlaghagel: http://datenbank.welli-it.de/?spell=16284

**Comment by Malize** [comment]
Ich kann das nur bestätigen. Hab das heute auch getestet. Es kommt zwar die Windfury Animation aber kein Damage. Weder im Combatlog noch über SCT. Das mit dem Schlaghagel wurde von Frostlatte schonmal reportet aber abgelehnt.

**Comment by Sabbaer** [comment]
http://wow.gamona.de/aktuelles/patchnotes/live/patchnotes-1-12-de/

Totem des Windzorns: Die Waffenverzauberung dieses Totems wird nur noch bei normalen Nahkampfschlägen ausgelöst. Das bedeutet, dass Fähigkeiten wie “Tödlicher Stoß”, “Finsterer Stoß” und “Kniesehne” nicht mehr das “Totem des Windzorns” auslösen.

**Comment by Seniorash** [comment]
Das ist aus den PTR-Patchnotes. Das wurde damals aber noch nicht aufgespielt sondern erst im Aug. 2007 mit einem Hotfix geändert. Einfach mal folgendes googeln: 

Windfury Totem will no longer trigger for any “yellow” attacks unless they are on next swing attacks, such as Heroic Strike and Cleave.

**Comment by Sabbaer** [comment]
die vermutung liegt schon sehr nahe, das es auch auf style "SWINGS" proggen sollte.
Jedoch ist Blutdurst z.B. kein weapon swing, und das totem gibt explicit einen buff auf die in der mainhand getragene waffe(oder den 2händer) und ich glaub du musst schon ne fähigkeit benutzen die einen schlag ausführt

**Comment by smas2810** [comment]
Wie gesagt im Video 07:25 procct wf auf blutdurst. Am x-realm Chat erkennt man auch den patchstand. Sollte also auf alles proccen können wie gesagt... hier geht es aber nicht darum auf was es procct sondern nur die Animation ausgeführt wird und nicht der Schlag

**Comment by Sabbaer** [comment]
meines erachtens nach sieht man das nicht im video, das kann auch von was ganz anderem kommen, wir haben keinen combat logg da in dem video und der combat text so wie er ihn hat ist keine zuverlässige quelle, das weist du auch, bei mir werden manchmal auch white hits einfach nicht angezeigt, die im combat logg vermerkt sind. hab mir grad wirklich seit meinem ersten kommentar dazu viele viele seiten von damals durchgelesen und gesucht, ob das jmd mal iwo erklärt, auf was der progg alles proggt
finde dazu aber leider nichts

**Comment by Haudraufinix** [comment]
Seniorash ich glaube der besagte Doppelprocc von 1:07 kann auch sehr gut von der HoJ stammen (Autohit, Wf Procc, Ms, HoJ) weil WF Totem müsste einen kleinen internen CD besitzen, dieser ist dazu da, um nicht bei  Mehrfachproccs (soll heissen, Hauklinge AA + Procc + HoJ + MS + Schwertspezi+ je 1x WF = 10 Hits) komplett zu überborden. Ist leider fast unmöglich nachzuweisen, da sich Classicspieler da eigendlich immer uneins waren. Ich denke die pvp Videos von high Warlord Pat wären hierzu die besten Informationsquelle.

Windfury Totem will no longer trigger for any “yellow” attacks unless they are on next swing attacks, such as Heroic Strike and Cleave. Aus TBC Patchnotes heisst jedoch ganz klar, dass dies in unserem Patchstand noch möglich sein müsste.

Ich würd mich jedoch freuen, wenn ein gewisser Paladin Fakten hätte, wieso WF denn NICHT auf Blutdurst proccen sollte, wenn Blutdurst doch sämtliche Waffenvz, Waffenproccs, Flurry und andere Procceffekte auslösen kann. Einfache Mutmassungen gehören eigendlich ins Forum und nicht in den Bugtracker

**Comment by Seniorash** [comment]
Tatsächlich ist einer der Proccs ein Schwertprocc. Jedoch nun bitte wieder back to Topic: Es geht hier darum dass nur eine Animation kommt wenn es auf einer Fähigkeit geprocct ist. Wie oft der Procc kommt und wovon er ausgelöst werden kann war niemals Bestandteil dieses Reports. Falls du der Meinung bist es würde auf zu viele Attacken oder zu häufig proccen, dann mach dafür bitte einen eigenen Report auf und beschreibe und belege es dort. Ich habe hier nur vollständigkeitshalber beigefügt, dass es auch auf Fähigkeiten Proccen müsste (was es zur Zeit auch tut). Die von mir genannten Quellen belegen das ausreichend. Hier geht es lediglich darum, dass die Mechanik nicht stimmt wenn der Procc bereits ausgelöst wurde.

**Comment by Malize** [comment]
Zu dem Doppelprocc im Video... Es steht sogar im SCT das es zweimal Windfury und einmal Swordspec ist.

**Comment by Seniorash** [comment]
Habe es getestet und es funktioniert nun wie es sein sollte. Nochmal Thumbs up und good Job!

**Comment by Malize** [comment]
Ja vielen dank an Euch.
