### ISSUE TITLE
Gottesschild/Divine Shield

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#515]
Welches verhalten ist zu beobachten:
Gottesschild macht nicht immun

Wie sollte es sich verhalten:
Gottesschild macht gegen alles immun, außer Wiederbelebungsnachwirkungen, PvP debuff oder Weltenbossdebuff bei tot.

Schritte zur reproduzierung:
http://www.wowwiki.com/Immune
Der Paladin bekommt trotz Gottesschild schaden, wenn er durch lava schwimmt.
Der Paladin ertrinkt weiter Unterwasser.
Dem Paladin kann durch Priester oder Schamanen buffz gedespellt werden obwhol Gottesschild an ist.

Links aus unserer Datenbank:
Rank 1
http://datenbank.welli-it.de/?spell=642
Rank 2
http://datenbank.welli-it.de/?spell=1020

**Comment by Haudraufinix** [comment]
Divine Shield prevents all damage, including (unlike most other bubbles of other classes) falling damage, and even drowning damage. It is not uncommon for a Paladin to leap off a high cliff or despawn their flying mount in the air and bubble before landing, preventing damage or death. Hand of Protection does exactly the same thing for falling damage, and a Paladin with good timing may bubble himself and a party member.
http://www.wowwiki.com/Divine_Shield

Ich würde hierbei gerne auf die Änderungen durch Patches aufmerksam machen -> Keine Änderungen an Effekten wie "Blocking Fall / Drowning Damage"
