### ISSUE TITLE
Questtext "Eine seltsame Anforderung" fehlerhaft

### ISSUE THREAD

**Issue by Cleptomaniac** [ClassicWoW/Nefarian_1.12.1_Bugtracker#516]
Im ingame Questtext heißt es "Bringt den Schrumpfkopf zu Xerash Feuerklinge beim Larisspavillon."
Die Beschreibung beginnt mit: "Xerash Feuerklinge am Larisspavillon nördlich von Camp Mojache [...]"

Dieser NPC existiert aber nicht, in der Datenbank ist der Questtext korrekt.

Quest: http://datenbank.welli-it.de/?quest=3121

**Comment by Slimmer2** [comment]
Der NPC Xerash Feuerklinge wurde erst mit Patch 3.2.0 zur WoW Welt hinzugefügt.
Der Questtext Ingame ist deswegen falsch und der Text von der Datenbank ist richtig hinterlegt

**Comment by ulle182** [comment]
Kann ich bestätigen. Diese Quest kann bei dafür Neeru Feuerklinge in Orgrimmar beendet werden.
