### ISSUE TITLE
Arathibecken -Hof-

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#518]
Hi,
im Arathibecken am Hof fehlen ein paar Ratten. Wäre toll wenn man da ein paar hinzufügen könnte.

Hierzu ein Video aus 2006
https://www.youtube.com/watch?v=u_sJu8fu82w

**Comment by 0815Priester** [comment]
Nachtrag:
Sind natürlich andere sachen wichtiger aber für die Spielmechanik wäre es halt ganz nett.

**Comment by cionex** [comment]
Danke 0815Priester. Die Ratten sind ab 18 Uhr wieder im BG und werden die Horde zerhäckseln. =) Aber schön das wir vermisst werden.

**Comment by 0815Priester** [comment]
Jo, geht eher darum das man die Ratten dazu benutzen kann um in den Kampf zu kommen damit man z.b. nicht gesapt wird.

**Comment by Dotox** [comment]
@Dotox

**Comment by dagochen** [comment]
Gibt es die Ratten nur am Hof oder auch am Stall?
