### ISSUE TITLE
Priesterskill: Geist der Erlösung buggy

### ISSUE THREAD

**Issue by MMMark** [ClassicWoW/Nefarian_1.12.1_Bugtracker#520]
Welches Verhalten wird beobachtet?
Beobachtung im BG.
Geist der Erlösung endet nicht korrekt, nach den 15 Sekunden steht man mit 1 Leben und X Mana da. Kann sein Mana noch aufbrauchen, sich jedoch nicht bewegen, angreifen, nicht angegriffen werden.
Um an den Friedhof zu kommen muss man sich neu einloggen.  
Wie sollte es sich verhalten?
Geist der Erlösung endet und man stirbt.

**Comment by Dotox** [comment]
Mach davon bitte ein Video und füge es hier ein :)

**Comment by SirBeansen** [comment]
Der Bug entsteht wenn du während im Geist bist noch dmg bekommst und nochmal stirbst :p 

zb ein cast oder Pfeil fliegt noch auf dich zu obwohl du dich schon in den Geist verwandelt hast. Glaube aber das man das umgehen kann wenn man sich selber den buff einfach vor ablaifen der Zeit weg klickt.

**Comment by MMMark** [comment]
Gerade nicht reproduzierbar.

**Comment by Rushor** [comment]
auch aoe schaden (bei thaddi z.B) sorgt für ein 'erneutes' sterben und die geistgestalt wird komplett noch einmal aufgetragen.

**Comment by Ghulfang** [comment]
http://youtu.be/SgChmaNdk98
