### ISSUE TITLE
Diminishing returns Fear - Seduction

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#521]
Fear und Seduction unterliegen der selben Diminishing Kategorie [Fear] und sollten sich somit einen gemeinsamen Diminishing Returns teilen.

Dies tun sie hier auf dem Server leider nicht.

Quelle: http://www.wowwiki.com/Diminishing_returns

**Comment by Armauskugelbob** [comment]
Stimmt nicht. Gerade im Duell getestet und es funktioniert alles wie es soll.

**Comment by wahaxlekuke** [comment]
Kann ich ebenfalls nicht reproduzieren? In welcher Situation ist das aufgetreten?

**Comment by Ilikegyoza** [comment]
Hm ich hab das selbe nun auch nochmal im Duell getestet und er funktioniert wie es sollte.
Das ganze trat im Arathibecken auf. Da hab ich mich wohl getäuscht. Entschuldidung :(
