### ISSUE TITLE
Hügel der Klingenhauer - Tuten Kash kommt nicht

### ISSUE THREAD

**Issue by TiberiusII** [ClassicWoW/Nefarian_1.12.1_Bugtracker#525]
Im Hügel der Klingenhauer funktionier der Gong nicht. Es erscheinen keine Spinnen und somit auch Tuten Kash nicht.
Normalerweise muss man den Gong 3 mal schlagen, und 3 Gegnerwellen besiegen.

Sehr schade.

Gruß

**Comment by ircfelix** [comment]
Quelle? Links?

**Comment by TiberiusII** [comment]
Wie meinst das? 
hier der Link zum NPC
http://www.wowhead.com/npc=7355/tutenkash

Quelle bin ich. Hab die Instanz heute gemacht

**Comment by Rushor** [comment]
scripted in https://github.com/mangos/SD3/commit/f4fde8135707302e379fd140cadf0f45f919ed9d
