### ISSUE TITLE
Falsche Info bei Sturmwindwachen

### ISSUE THREAD

**Issue by TiberiusII** [ClassicWoW/Nefarian_1.12.1_Bugtracker#526]
Bei Sturmwindwachen kann man nicht nach Schneidern fragen. 
Wenn man auf Inschriftenkunde klickt wird der Schneider angezeigt. Inschriftenkunde gibts bei Classic nicht.
Wenn man auf Bergbau klickt, dann wird man zum Lederer verwiesen.

**Comment by ircfelix** [comment]
Hast du das bei anderen Städten und Berufen auch getestet?

Es würde das Bugfixing auch leichter machen, wenn du die Npcs nach Städten sortiert und mit Datenbanklink zum npc tabellarisch auflistest und DANN nochmal dazugehörig die falschen Texte :)

**Comment by TiberiusII** [comment]
Die anderen Berufe stimmen soweit ich weiß.

**Comment by ElmarHoefinghoff** [comment]
Das ist mir auch gerade aufgefallen. Das Problem haben auch andere Wachen in andere Hauptstätten. Inschriftenkunde gibt es in Classic nicht, daher verschiebt sich ab da der Index und man erhält eine Falsche Antwort auf die eigentliche Frage.
