### ISSUE TITLE
Dunkelmond Jahrmarkt

### ISSUE THREAD

**Issue by Nwardho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#527]
Der Dunkelmondjahrmarkt ist nicht erschienen, obwohl heute der erste Sonntag des Monats ist.

**Comment by dagochen** [comment]
Description
The Darkmoon Faire is an event that appears in the game (starting in version 1.6). Starting on the first Friday of each even-numbered month, the Faire sets up in a field in Elwynn Forest (south of Goldshire); on the first Friday of odd-numbered months, it sets up in Mulgore at the base of Thunder Bluff. Setup takes the carnies three days, and the Faire officially starts early that Monday at 4:00 AM server time.

http://www.wowwiki.com/Darkmoon_Faire_(old)?oldid=365271

Kann sein das der Teil mit dem graden/ungraden Monat bei uns falsch ist?

**Comment by Nwardho** [comment]
Es ist Freitag und weder in Elwynn noch in Mulgore ist der Jahrmarkt...
