### ISSUE TITLE
Anzeige Teilnehmer Chat Channel

### ISSUE THREAD

**Issue by Mokkaa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#529]
Die Befehle /chatlist oder /chatinfo sollten ja, genauso wie die API Funktion ListChannelByName(ChanNum), die Mitglieder im jeweiligen Channel auflisten. Keine der Funktionen tut was sie sollte, sie werden zwar ohne Fehlermeldung angenommen, zeigen aber keinerlei Effekt.

**Comment by Larnak1** [comment]
Behoben! Cool, danke! <3

**Comment by Mokkaa** [comment]
Danke, wann wird das denn aufgespielt? :)

**Comment by Larnak1** [comment]
Funktioniert, top! Danke :)
