### ISSUE TITLE
Psychischer Schrei fehlerhaft 

### ISSUE THREAD

**Issue by cionex** [ClassicWoW/Nefarian_1.12.1_Bugtracker#530]
Hallo Dev-Team,

der Spell des Priesters "Psychischer Schrei" ist auf dem heutigen Patchstand fehlerhaft. 
Der Fear bricht weder durch schadenverursachende Zauber des Preisters noch durch andere Schadesquellen wie Meleehits ab.

Dies ist definitiv falsch und der Zauber sollte durch jeglichen Schaden abgebrochen werden.

Durch diesen Spellbug entsteht ein großer Vorteil für Preister sowohl PVP als auch PVE. 

Würde mich freuen, wenn dies zeitnah behoben wird.

**Comment by wahaxlekuke** [comment]
Siehe #424 ist bereits behoben, aber noch nicht auf dem Server aufgespielt.
