### ISSUE TITLE
Premium - Keine NPC Buffs

### ISSUE THREAD

**Issue by Karmanaz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#531]
Hallo,

mir ist schon mehrfach aufgefallen, das man von vielen NPCs keine Buffs erhält am Ende einer Quest, da ich nun noch mal mit 2 Gildenmitgliedern gelevelt habe, welche keinen Premium haben, konnte ich feststellen, dass man den Buff nur dann nicht erhält, wenn man einen Premiumaccount hat. Ich habe es dann noch einmal mit einem Account getestet, der kein Premium hat, dieser konnte die selben NPC-Buffs bei der Questabgabe erhalten.

Was sollte verändert werden:
Das auch Accounts mit Premium von NPCs die Questbuffs wie MDW und Intelligenz erhalten können. 

Hinweis:
Es betrifft keine wichtigen Questbuffs, sondern nur Stärkungszauber.

**Comment by dagochen** [comment]
Hi,
wäre toll, wenn du Beispiele für die Buffs und Quests mit deren Verlinkung aus der Datenbank posten würdest. 
Vg, 
dago

**Comment by Karmanaz** [comment]
Hi, 

natürlich - ist irgendwie unter gegangen.

Zuletzt beim twinken ist es bei folgenden Quests aufgefallen:
http://datenbank.welli-it.de/?quest=422 - Buff: Intelligenz bei Quest-Abschluss
http://datenbank.welli-it.de/?quest=772 - Buff: Mal der Wildnis

VG Karma

**Comment by Sabbaer** [comment]
Bei der onyxia pre quest allianz seite hat der marshal windsor leider seine aura nicht, nachdem er seine rüstung angezogen hat
http://datenbank.welli-it.de/?quest=4322
müsste diese quest sein, sobald er seine rüstung an hat müsste eine aura auf alle spieler wirken.

Yeasterday when I was doing my onyxia attunment, Jail Break part, right after the dude got his gear; he supply the group with a aura that gives you 65% melee attack speed. At this point me and my two friends who were helping me all DCd (LAN-Party DC is the shit!) and when we logged back in we could all exit the instance still using the buff. We kept it until we logged out.

das ist das, was ich dazu erstmal finden konnte im internet.

**Comment by dagochen** [comment]
Das Problem hierbei ist, dass der Server den Spieler den Zauber auf sich selbst casten lässt. Eigentlich sollten die Quest-NPCs den Zauber auf den Spieler casten.
