### ISSUE TITLE
Hunter Pet Boar/Eber

### ISSUE THREAD

**Issue by Dragoon2004** [ClassicWoW/Nefarian_1.12.1_Bugtracker#533]
Der Rasse der Boar/Eber fehlt hier auf dem Server gänzlich der Skill Gore/Aufspießen.
Laut Petskill Database für Classic sollten aber die meißten Eber diesen skill auf diversen Skill lv besitzen. Tun sie aber aktuell leider nicht.

Hier die liste der Pets und ihrer Skills
https://dl.dropboxusercontent.com/u/35397320/Patricks%20Webpages/Hunter%20Pet%20Guide/Hunter%27s%20Pet%20Bestiary.html#Boar

**Comment by Haudraufinix** [comment]
http://web.archive.org/web/20070222092117/http://petopia.brashendeavors.net/html/articles/skills_list.shtml#gore

Skills added in Patch 2.0 and/or The Burning Crusade:
* Fire Breath
** * Gore**
* Poison Spit
* Warp

**Comment by wahaxlekuke** [comment]
Danke für den Hinweis. Die Fähigkeit kam tatsächlich erst in mit TBC.
