### ISSUE TITLE
Segnung wirkt nicht auf Siegel des Befehls

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#534]
Welches Verhalten wird beobachtet?
Siegel des Befehls erhält keine manakosten verringerung durch segnung

Wie sollte es sich verhalten?
Der skill "Segnung" im vergelter skillbaum sollte auch die kosten für Siegel des Befehls verringern
auch das richturteil des befehls sollte davon betroffen sein

Schritte zur Reproduzierung
ich skill es, kostet immernoch gleich viel mana

**Comment by Haudraufinix** [comment]
Hast du die effektiven Zauberkosten betrachtet oder nur den Tooltipp? Viele Talente verbilligen Zauber, aber lange nicht jeder ändert dabei den Tooltipp des betreffenden Zaubers.

**Comment by Acolatronico** [comment]
es wird immer gleich viel "mana" im balken abgezogen egal wieviele punkte man in das talent sitzt das bezieht sich aber nur auf "siegel des befehls". bei dem damage siegel der rechtschaffenheit funktioniert das talent richtig
