### ISSUE TITLE
arathiebecken magierwasser trinken

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#535]
keine ahnung obs in der warsong auch so ist oder in der normalen welt(dort ist es bis jetzt noch nicht vorgekommen), wenn ich im arathiebecken auf das magewasser in meiner aktionsleiste drücke, sagt mein char: "Diesen gegenstand kann ich nicht anlegen."
manchmal wenn ich aufstehe, vorhin auch während des laufens ooc hat mein char gesagt: "Für meine Waffe brauche ich beide hände" oder so ähnlich.

**Comment by Sabbaer** [comment]
beim hinsetzen und trinken des magier wassers an der säge sagt mein char: "Ich brauch beide Hände für meine Waffe."

**Comment by ircfelix** [comment]
Hast du ein Makro das ein Item aus einem bestimmten Inventarslot nutzt?

**Comment by Sabbaer** [comment]
nein

**Comment by Sabbaer** [comment]
ist irgendwie nicht mehr vorhanden der bug, keine ahnung warum aber er ist weg
