### ISSUE TITLE
Magier Talent Entzünden/Ignite

### ISSUE THREAD

**Issue by Ethnie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#538]
Mir sind **3 Fehler** beim passiven Magier Talent Entzünden / Ignite aufgefallen

**Entzünden:**
Eure kritschen Treffer von Feuerzaubern lassen das Ziel 4 Sek. lang für zusätzliche 8% Eures Zauberschadens brennen.
Mit 5 Skillpunkten 40% auf 2 Ticks
nach 2 Sek 20%
nach 4 Sek 20%

http://datenbank.welli-it.de/?spell=12848

**1. Debuffslot**

Atm ist es so, dass jeder Magier seinen eigenen Entzünden Dot auf dem Target erzeugt. Zu unserem Patch Stand 1.12.1 sollten sich alle Magier noch einen Entzünden Dot teilen und diesen gemeinsam hoch stacken können.
Die Änderung das jeder seinen eigenen Dot besitz kam erst mit BC sprich mit Patch 2.0.1

http://www.wowwiki.com/Ignite_%28old%29 siehe Patch changes

**2.Schadensberechnung**

Es liegt ein Fehler in der Berechnung des Dot Schaden vor. Der Schaden sollte sich eigentlich hoch addieren. Bei uns multipliziert er sich einfach pro stack (ausgehend vom initial Krit) egal wie hoch der Kritische schaden ausfällt der den neuen Stack erzeugt.

In Zahlen sieht das ganze so aus.

*Im Moment:*
0:00.00 - Your Fireball crits <Target> for 1500 Fire damage. 
0:00.00 - <Target> is afflicted by Ignite. 
0:02.00 - <Target> suffers 300 Fire damage from your Ignite. 
0:03.00 - Your Fireball crits <Target> for 1600 Fire damage. 
0:05.00 - <Target> suffers 600 Fire damage from your Ignite. 
0:07.00 - <Target> suffers 600 Fire damage from your Ignite. 

Es ist vollkommen egal wie hoch der 2te crit ausfällt, der Dot multipliziert sich 
 
*Richtig wäre:*
0:00.00 - Your Fireball crits <Target> for 1500 Fire damage. 
0:00.00 - <Target> is afflicted by Ignite. 
0:02.00 - <Target> suffers 300 Fire damage from your Ignite. 
0:03.00 - Your Fireball crits <Target> for 1600 Fire damage. 
0:05.00 - <Target> suffers 470 Fire damage from your Ignite. 
0:07.00 - <Target> suffers 470 Fire damage from your Ignite. 

Hier addiert sich der Schaden. 300 dmg rest + 640 dmg erzeugt vom 2ten crit /2 ticks = 470 dmg pro Tick

**3.Skalierung**

Der Entzünden Dot scheint zusätzlich noch mit spell dmg zu skalieren. Habe nirgends gelesen das es so sein sollte, also gehe ich davon aus das es falsch ist und nur die geskillten Prozente vom Talent berechnet werden sollten.
Da lasse ich mich aber auch gern eines besseren belehren. =)

**Links,  Videos:**

https://www.youtube.com/watch?v=YZm7psZBKbo
https://www.youtube.com/watch?v=bMWKNeIISmo
http://www.wowwiki.com/Ignite_%28old%29
http://forums.elitistjerks.com/topic/7465-how-do-rolling-ignites-work/
http://www.wow-one.com/forum/topic/88471-how-does-ignite-actually-work/

Möchte auch gern die Erfahrungen und Meinungen der Community dazu lesen, weil es ein recht komplexes und undurchsichtiges Thema ist. 
Also bitte korrigiert und ergänzt mich, aber einer muss ja mal den Anfang machen =)

**Comment by wahaxlekuke** [comment]
Wenn das ein geteilter Debuff ist, erscheint dann im Kampf-Log für jeden Magier der Gesamtschaden oder nur der eigene Anteil? Oder wird der Schaden einfach dem letzten Mage zugeordnet, der kritisch getroffen hat?

**Comment by Ethnie** [comment]
Der Schaden wird dem Magier zugeordnet der mit dem ersten crit den Dot "eröffnet" hat. Alle anderen crit´s stacken den debuff hoch bis auf 5 und refreshen den timer

**Comment by Ethnie** [comment]
stelle mich auch gern zum Testen zur Ferfügung.
/w Smoker

**Comment by ircfelix** [comment]
Bisher ist das so weit richtig bis auf **2.**:

Ich weiss nicht wie es genau ist, aber wenn es so wäre wie du sagst müsste man versengen hochstacken, pyro mit trinkets kritten lassen, weiter versengen spammen. Das funktioniert aber auch nicht, weil sich in diesem Fall der Schaden des Pyros leider NICHT multipliziert. 

Ich suche dir gleich webn ich am Pc bin noch ein paar Quellen raus Wahax.

**Comment by Ethnie** [comment]
Hab es gerade noch einmal geteste und es verhält sich genau so wie beschrieben.

  2k Pyroschlag (rang8) Krit ---> 400dmg Tick
+120 Feuerball (rang1) Krit ---> 800dmg Tick

**Comment by ircfelix** [comment]
Des is ja lustig ^^ ich hab das mal im Raid gemacht mit Pyro + Trinket, 3.8k crit, dann versengen und der stack is nur um 200 oder so mehr geworden.

**Comment by Ethnie** [comment]
konkrete Zahlen würden mehr helfen

**Comment by ircfelix** [comment]
Hab die gute Quelle, die auch den Unterschied zwischen dem Vanilla- und Bc-Ignite sehr gut heraushebt und vieles mit Screenshots belegt hat :-(

**Comment by wahaxlekuke** [comment]
Dann schreib doch deine Quelle trotzdem dazu. Ich hab mich beim Fixen vor allem an der 4. Quelle von Ethnie orientiert. Also bei http://forums.elitistjerks.com/topic/7465-how-do-rolling-ignites-work/

**Comment by ircfelix** [comment]
Ich find die Quelle nimmer :( Wenn doch, geb ich bescheid :)
