### ISSUE TITLE
Falscher Spawnpunkt von Dunkelbewahrer Bethek

### ISSUE THREAD

**Issue by DreamRogue** [ClassicWoW/Nefarian_1.12.1_Bugtracker#541]
Welches Verhalten wird beobachtet?
Nachdem man in BRD vor dem Tresorraum das Bild angeschaut hat spawnt ein Randommob mit jeweils vordefiniertem Spawnpunkt in der Instanz. Im Falle von Dunkelbewahrer Bethek ist das aber der falsche Spawnpunkt.

Wie sollte es sich verhalten?
Bethek spawnt wie vorgesehen direkt im Tresorraum und patroulliert dort auf und ab.

Schritte zur Reproduzierung
Das Bild anschauen und so lange Instanz resetten bis einmal Dunkelbewahrer Bethek spawnt.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Derzeit spawnt Bethek am selben Spawnpunkt wie Vorfalk (obwohl eigentlich alle Dunkelbewahrer einen eigenen Spawnpunkt haben).
http://www.hordeguides.de/Instanz/Classic/Boss/9437/Dunkelbewahrer/index.htm (Spawnpunkte am Ende der Seite; erstellt 2004)
http://de.wowhead.com/item=11197/schlussel-des-dunkelbewahrers#english-comments (Spawnpunkte in den Kommentaren; erstellt 2007)
http://wowdata.buffed.de/item/Schluessel/Schluessel-des-Dunkelbewahrers-11197#comments (Spawnpunkte in den Kommentaren; erstellt 2008)
-> die Spawnpunkte wurden nie verändert somit sollten es auch auf Nefarian die angegebenen Punkte sein

Links aus unserer Datenbank
Dunkelbewahrer Bethek - http://datenbank.welli-it.de/?npc=9438

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1008
