### ISSUE TITLE
Durchbohren/Impale bei Wirbelwind

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#544]
Welches Verhalten wird beobachtet?
Durchbohren gibt keinen Schadensbonus auf kritische Treffer mit Wirbelwind.

Wie sollte es sich verhalten?
Wie bei allen Fähigkeiten sollte Wirbelwind ebenfalls mit Durchbohren skalieren.

Schritte zur Reproduzierung
Durchbohren Skillen und mit Wirbelwind auf Ziele mit bekannter Rüstung/Absorb kritten.

Links aus unserer Datenbank 
Impale: http://datenbank.welli-it.de/?spell=16494
Wirbelwind: http://datenbank.welli-it.de/?spell=1680

Zusätzliches
http://vanilla-wow.wikia.com/wiki/Whirlwind

**Comment by dagochen** [comment]
Nur kurz getestet, aber scheint korrekt zu funktionieren :/

**Comment by Seniorash** [comment]
Ich bin mir sicher dass es nicht funktioniert. Ich habe es im Duell ausgetestet. Rechnung ist: MinWepaonDMG*2,2*(1-TargetAbsorb). Dabei habe ich einen niedrigerenCrit gemacht als diesen Wert. Umkehrschluss wäre wenn man einen höheren Hit macht als MaxWepaonDMG*2*(1-TargetAbsorb).

**Comment by dagochen** [comment]
Unser Test sah wie folgt aus:
Ohne Talent: Wirbelwind Krits zwischen 850 und 1000.
Mit Talent: Wirbelwind Krits zwischen 1050 und 1200.

**Comment by Seniorash** [comment]
Dann  muss ich euch leider sagen, dass euer Testergebnis nicht richtig sein kann...
Das Talent: Erhöht den kritischen SchadensBONUS

Der ungeskillte Schadensbonus liegt bei 100%. Daher ist der geskillte bei 120%. Ungeskillt muss man demnach mit 2 und geskillt mit 2,2 multiplizieren. Die Zahlen sind effektiv also nicht 20% (so wie in deinem Ergebnis), sondern nur um 10% höher. Siehe auch: http://www.wowwiki.com/Impale

Noch einmal: Wenn man wirklich die Wertebereiche mit und ohne Durchbohren durch Testes ermitteln will, muss man schon eine größere Anzahl an Hits landen um eine Aussage treffen zu können. Ich gehe davon aus, dass das bei dir der Fehler war. Da Wirbelwind nur einfachen Schaden macht, kann man die Wertebereiche ganz einfach ausrechnen, wie hoch die Crits geskillt  bzw. ungeskillt sein müssten. Diese Bereiche haben durch die Streuung des Waffenschadens eine relativ große Überlappung. Sobald du aber höher als den "ungeskillten" Bereich oder niedriger als den "geskillten" Bereich triffst, hast du dein Ergebnis.

Ungeskillt: (1-Target-Absorb)*2*MinWeaponDMG - (1-Target-Absorb)*2*MaxWeaponDMG
Geskillt: (1-Target-Absorb)*2,2*MinWeaponDMG - (1-Target-Absorb)*22,*MaxWeaponDMG

Bei allen anderen Fähigkeiten liegen die Werte im "geskillten" Bereich.

**Comment by wahaxlekuke** [comment]
Das bedeutet doch dann, dass es sogar 10% Schaden zu viel Schaden macht und nicht zu wenig. Oder sehe ich das falsch?

**Comment by Seniorash** [comment]
Ich habe es getestet und die Werte waren immer in dem Bereich ohne die 20% Critbonus. Da waren auch Treffer dabei die niedriger waren als sie mit dem Talent sein müssten. Sprich es wurden nur 100% Critbonus berechnet und niemals die 120%.

**Comment by Kratkan** [comment]
Ich habe es ebenfalls mit und ohne geskilltem Talent getestet. Dabei habe ich durchgehend die selben mobs gehauen und stets darauf geachtet bei jedem mob mit den gleichen buffs rein und rauszugehen. Sprich: diverse procs wie Kreuzfahrer/Wutanfall habe ich mir jedesmal vor einem Wirbelwind weggeklickt um genauere Werte zu bekommen. Den Berechnungen zufolge hat Wirbelwind nicht bei einem Treffer von dem 20% krittischen Schadensbonus profitiert.

**Comment by bugreportor** [comment]
Normalisiertes Waffentempo. miese Sache :(

**Comment by Seniorash** [comment]
Du hast Recht...sorry, hab ich nicht dran gedacht. Falscher Alarm
