### ISSUE TITLE
Out-Of-Combat Bug

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#545]
Welches Verhalten wird beobachtet?
Wenn im PvP 5 Sekunden lang keinen Schaden oder schädlichen Debuff erzeugt oder erhält kommt man aus dem Kampf und hört auf anzugreifen. Dies geschieht auch wenn man Hits macht und diese keinen Schaden machen weil sie absorbiert/ausgewichen/parriert/immun/verfehlt werden.

Wie sollte es sich verhalten?
Auch wenn der Angriff keinen Schaden macht sollte man weiterhin im Kampf bleiben.

Schritte zur Reproduzierung
Im PvP Immun gegen Schaden machen/absorbieren oder nach einer Serie von ausweichen/parrieren/verfehlen schauen ob man im Kampf bleibt.

**Comment by SirBeansen** [comment]
Dadurch entsteht auch der autohit bug.
