### ISSUE TITLE
Reckoning

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#548]
Welches Verhalten wird beobachtet?
Die Aufladungen behält man aktuell immer bis zum nächsten Autohit egal ob man:
* Ending a Duel 
* Mounting up (including gryphons) 
* Switching Continents 
* Switching Weapons 
* Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control, etc.) 

Wie sollte es sich verhalten?
Die Aufladungen sollten verschwinden wenn man:
* Ending a Duel 
* Mounting up (including gryphons) 
* Switching Continents 
* Switching Weapons 
* Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control, etc.) 

Schritte zur Reproduzierung
Paladin erstellen, Reckoning skillen und sich kritisch treffen lassen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://blue.cardplace.com/cache/wow-paladin/1069149.htm

**Comment by Sabbaer** [comment]
http://www.mmobase.de/forum/bugtracker-archiv/3849-reckoning.html
ich bitte diesen beitrag zu betrachten in dem wiederlegt wurde, dass zu 1.12.1 diese mechaniken die du hier angibst nicht stimmen und falsch zitiert sind, ist dir hoffentlich bewusst

When will Reckoning be fixed to be instant? 
Recently, a dev did say they were working to fix some bugs with Reckoning, as to make it so charges would not be dropped if you did not reach melee range with the target before you took a swing at them, but no date has been named. 

Why didn't my Reckoning bomb go off? 
The following things can cause you to drop your charges: 


* Ending a Duel 
* Mounting up (including gryphons) 
* Autoattacking too early (e.g. from out of range) 
* Switching Continents 
* Switching Weapons 
* Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control, etc.) 

You will however retain reckoning charges after casting Blessing of Protection on yourself or Divine Shield. 


bitte richtig übersetzen.
Wir reden hier von einem bug den der paladin leider eine zeit zu classic hatte, indem er die aufladungen verloren hat.
Dies wurde auch im nächsten patch dann gefixed von blizzard.
wie in dem mmobase forum schon ausführlich diskutiert und geklärt wurde

**Comment by Ilikegyoza** [comment]
Poste doch einfach Quellen die diesen Post widerlegen. Irgendein Flamethread von vor 2 Jahren lese ich mir sicher nicht durch.

**Comment by Ilikegyoza** [comment]
Nach etlichen langweiligen reckoning Pala videos habe ich keines gefunden in dem man sieht das er seine Ausladungen bei Kontrollverlust verliert. 

Kann also geschlossen werden.
