### ISSUE TITLE
Sturmschlag Schamane ist kein Style mehr und resetet den Angreifen-Timer.

### ISSUE THREAD

**Issue by bugreportor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#549]
Welches Verhalten wird beobachtet?
Wenn man als Verstärker-Schamane Sturmschlag (31. Talent im Verstärk.-Talentbaum) wirken will, wird dieser als white-hit angezeigt (combat-text und kampflog) und resettet auch den Autoattack-timer. Somit ist Sturmschlag im moment nicht nutzbar, weil der "zusätzliche Schlag" einen jetzt immer mindestens einen anderen White-hit kostet. Es wird also kein zusätzlicher Schlag mehr ausgeführt, stattdessen fängt autoattack einfach wieder von vorne an.
Wie sollte es sich verhalten?
Sturmschlag sollte ein Sofortschlag sein - ähnlich MS, Sinister Strike, Blutsturz, Wirbelwind - der zusätzlich zu den White hits (timer unabhängig) gewirkt werden kann. Wenn Angreifen/autoattack "nicht aktiviert" ist und man in nahkampfreichweite eines mobs einen Meele-style wirkt sollte der Style und der Autohit gleichzeitig beginnen. Im kampflog sind dann eine gelbe und eine weiße Zeile zu sehen und der Combat-text über dem Charakter zeigt auch eine gelbe und eine weiße Zahl zeitgleich an.
Schritte zur Reproduzierung
An einem Mob stehen ohne Autoattack und sturmschlag wirken (nur ein schlag wird ausgeführt).
An einem Mob stehen mit Autoattack und Sturmschlag wirken (es wird kein zustäzlicher Schlag ausgeführt)
Links aus unserer Datenbank 
http://datenbank.welli-it.de/?spell=17364 (Sturmschlag)

**Comment by Frostlatte** [comment]
Aus eigenen Erfahrungen kann ich die Schilderung von "bugreportor" bestätigen. Wie auch in dem für den Windfuror Bug aufgenommenen Video zu sehen ist, wird der Sturmschlag nicht als "Zauber-/Zusatzangriff" angezeigt und scheint zudem auch spielmechanisch als zusätzlicher Autohit zu zählen, wodurch auch der Swingtimer zurückgesetzt wird.

Relativ gut nachzuvollziehen im genannten Video: https://www.youtube.com/watch?v=qjbS-ikH0kI
Hier wird Sturmschlag gewirkt und es erfolgt kein unmittelbarer Autohit, obwohl der letzte vor dem Sturmschlag nicht länger als ca. 1,5 Sekunden mittels Flurry dauern dürfte.
Man sieht jedoch deutlich sieht, dass der Autohit erst ca. 1,5 Sekunden nach dem Sturmschlag erfolgt und einen WF auslöst.
Die dort verwendete Waffe ist folgende: http://datenbank.welli-it.de/?item=19362 mit einem Speed von 2,3 mit 30% Flurry = 1,6 Sek. , was der Zeit zwischen Sturmschlag und Autohit entspricht.

Damit wird der Sturmschlag etwas obsolet, da man durch ihn mittels eines 31er Talents nicht wirklich einen ExtraAngriff erhält, sondern einen weiteren Autohit, der den Swingtimer mitunter bei langsamen Waffen auf 3,7 Sekunden bis zum nächsten Angriff zurück setzt.

Daher die Bitte, dies möglichst bald zu korrigieren.

Mit besten Dung und Grüßen

Frost
