### ISSUE TITLE
PvP Flag

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#553]
Fehler:
Im BG verliert man nach einiger Zeit, wenn man defft am Stall z.B., das PvP-Flag. Dadurch ist man für feindliche Spieler nicht angreifbar und diese werden bei einem selbst nicht rot, sondern gelb angezeigt (HP-Balken). Durch Eintippen von /pvp oder angreifen der feindlichen Spieler erhält man das PvP-Flag zurück.

Reproduktion:
Stall / Hof deffen und hoffen, dass keiner kommt :D

**Comment by Pennywiize** [comment]
Hmm diesen Bug gabs auch schon Ende letzten Jahres. War dann irgendwann weg. Damals ging die PvP-Flag allerdings nur aus wenn man sich auch nicht bewegt hat - sobald man wieder 2-3 Schritte lief, war man wieder geflaggt.
