### ISSUE TITLE
Schwimmtempotrank

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#554]
Hi
beim benutzen des "Schwimmtempotrank" bekommt man einen DC
http://datenbank.welli-it.de/?item=6372

**Comment by dagochen** [comment]
Speedhack-Detection ;)

**Comment by Envie** [comment]
Habe heute bei Schwimmtepotrank Nutzung weiterhin Disconnects bekommen.

mfg Envy
