### ISSUE TITLE
"Edelstein des Gedankensprungs" (Mage) aus BWL rechnet mit 25% statt 33%

### ISSUE THREAD

**Issue by ocb1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#557]
Hallo,

mir ist aufgefallen, dass der Magierschmuck:"Edelstein des Gedankensprungs" von "Vaelastrasz der Verdorbene" nicht mit den angegeben 33% Zauber Geschwindigkeit rechnet, sonder mit 25%. Dies ist ein enormer Unterschied. Am besten einmal selbst ausprobieren. Bei einem geskillten Frostblitz (2.5 Sekunden) beträgt die castzeit 1.88 Sekunden. Ich denk, dass das Spiel die 1,875 Sekunden (75% der castzeit) hierbei aufrundet. Jedoch sollten es bei 2,5 Sekunden 1,666666666, bzw. 1,67 Sekunden sein. 

Link zur Datenbank: http://datenbank.welli-it.de/?item=19339
Ansonsten funktioniert alles wie es soll: Der CD von 5 min stimmt, und es teilt sich einen CD mit den Weiteren Trinkets im Spiel, beispielsweise dem aus ZG und MC.

Vielen Dank.

**Comment by Larnak1** [comment]
Das ist meiner Meinung nach korrekt. Der Edelstein reduziert laut Text nicht die Castzeit um 33%, sondern erhöht die Castgeschwindigkeit um 33%, also das Inverse der Castzeit. 

Castgeschwindigkeit = 1/2,5s = 0,4 1/s
Castgeschwindigkeit * 1,33 = 0,532 1/s  --> 1,88 Sekunden Castzeit

**Comment by dagochen** [comment]
Ja das rechnet genauso wie beim Jäger die Köchergeschwindigkeit (15%), sowie Schnellfeuer und Schnelle Schüsse, also genauso wie Larnak1 es erklärt hat.
