### ISSUE TITLE
Schamane - Schlaghagel - Aufladungsfehler

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#561]
Mir ist aufgefallen, dass, wenn die letzte FlurryAufladung nach einem kritischen Treffer besteht, ein weiterer Kritischer Treffer als normaler, eine FlurryAufladung verbrauchender, Autohit gezählt wird, statt den Flurry erneut aufzuladen.

Videos:

https://www.youtube.com/watch?v=_kORnmORs4I

https://www.youtube.com/watch?v=febbWxn1JlM

Bei den Aufladungen 3 & 2 scheint die Mechanik normal zu funktionieren und der FlurryEffekt wird auf 3 zurückgesetzt. Bei der letzten Aufladung geschieht dies leider nicht.

Folge: Ein weitere Verlangsamung der Waffengeschwindigkeit und damit Damageverlust im Raid.

Beste Grüße

Frost

**Comment by Seniorash** [comment]
Kann ich bestätigen. Tritt bei Kriegern genauso auf
