### ISSUE TITLE
Jäger Begleiter Schleichen

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#562]
Hallo,
momentan ist es nicht möglich das Begleiter Talent Schleichen zu erlernen.

Wie sollte es sich verhalten?
Nach der Zähmung einer Katze, die Schleichen Rang 1-3 kann und mehrmaligen nutzen dieser Fähigkeit, sollte man dieses Talent in der Wildtierausbildung erlernt haben und kann es somit jeder beliebigen Katze beibringen.

Schritte zur Reproduzierung
Eine Katze mit Schleichen Rang 1-3 zähmen, das Talent immer wieder nutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Schleichen Rang 1 http://datenbank.welli-it.de/?spell=24451
Schleichen Rang 2 http://datenbank.welli-it.de/?spell=24454
Schleichen Rang 3 http://datenbank.welli-it.de/?spell=24455

**Comment by wahaxlekuke** [comment]
Rang 1 funktioniert übrigens

**Comment by Haudraufinix** [comment]
Hast du sichergestellt, dass dein gezähmtes Pet auch gekämpft hat? Tiere geben ihre Skills nur weiter, wenn sie auch aktiv kämpfen!
In der Stadt 4-5x Schleichen aktivieren reicht nicht.
