### ISSUE TITLE
Wachen zeigen falschen Weg bei Berufen

### ISSUE THREAD

**Issue by Sharoxx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#563]
Wenn man die Wachen nach dem Weg zu einem Berufslehrer zeigt, wird der falsche Weg angezeigt.
Bei Bergbau wird zum Kürschnerlehrer geschickt, bei Kürschner zum Schneiderlehrer und bei Lederverarbeitung zum Bergbaulehrer. Weitere Fehler nicht getestet.
Fehler gefunden in Dun Morogh und Ironforge

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451

/close
