### ISSUE TITLE
Magiewiderstände

### ISSUE THREAD

**Issue by Hexquantum** [ClassicWoW/Nefarian_1.12.1_Bugtracker#567]
Magiewiderstände werden bei primären Zaubern doppelt verrechnet.

So kann z.B. ein Schattenblitz(primär) vom Hexenmeister zu [(effektiver Widerstand des Ziels) / (5 * Zauberer Level) ] * 0,75 komplett widerstanden werden und der durch nicht widerstandene Zauber verursachte Schaden wird im Durschnitt zu [(effektiver Widerstand des Ziels) / (5 * Zauberer Level) ] * 0,75 in absorbiert (Widerstanden)[3]. 
Der Fehler: Das Treffen des Zaubers kann nur bei binären Zaubern(verursachen keinen Schaden) wie z.B. Fluch der Schatten oder Furcht widerstanden werden jedoch nicht bei Primären Zaubern [1].

Dadurch machen Caster z.B. in Dire Maul (West) kaum schaden ( 25% * 25% = 6,25%)an den Elementaren an den Pylonen, aber auch andersrum machen Bosse z.T. kaum Schaden an Spielern mit Magiewiderständen.

Quellen: 
[1] http://wow.ingame.de/wiki/Zaubertrefferchance   Abschnitt: Effekte von Widerständen

[2] http://wow.ingame.de/wiki/Widerstand  Abschnitt: Schadenreduzierung

[3] http://wow.ingame.de/wiki/Magiewiderstand Abschnitt: Magische Widerstände

Bei Fragen bin ich Ingame auf "Hexquantum" erreichbar. Ich kann zu dem genannten Problem auch ein Video aufnehmen. Das beheben des Problems ist mir wichtig, da z.B.  Firemaw (BWL) viel zu wenig Schaden austeilt und AQ bald erscheinen soll.

mfG Hexquantum

**Comment by dagochen** [comment]
Ich verstehe selbst nachdem ich es jetzt zum 3. mal gelesen habe nicht, was falsch ist. Du schreibst etwas mit "Das Treffen des Zaubers....widerstanden werden". Was meinst du nun:
a) Treffen eines Zaubers
b) Teilweise widerstehen des Schadens

Und woher nimmst du die 25%. Die hängen doch von den Resistenzen der Ziele ab, die immer anders sind?

**Comment by ircfelix** [comment]
Finde diesen Report auch äußerst undurchsichtig und fragwürdig.

**Comment by ircfelix** [comment]
Übrigens ist deine erste Quelle schon von 2009...

**Comment by Seniorash** [comment]
Woher hast du, dass Firemaw zu wenig Schaden macht? Weißt du dass er einen stackenden Debuffverteilt und der Schaden dann auch steigt und tödlich wird?
Dass Gegner zu wenig Zauberschaden zufügen kann ich nicht bestätigen. Drakki wird für Neulinge kaum noch legbar sein wenn sich sein Feuerschaden weiter erhöht. Bei uns im Raid werden Tanks teilweise mit Feuerresicap teilweise Onehitted (Raggi/Geddon).

Und natürlich kann direkten Schadenszaubern komplett widerstanden werden.
Aus deiner Eigenen Quelle (2): Normale Schadenszauber können zu 0%, 25%, 50%, 75%, or 100% widerstanden werden. Mit maximalen widerständen hat man gute Chancen 75% zu widerstehen auch 100% und 50% kommen häufiger vor, 25% und 0% sind dagegen eher selten.

Geht es dir hier um Trefferchance oder Magiewiderstände? Vielleicht solltest du das nochmal etwas umschreiben,um es besser verständlich zu machen. Ansonsten benutz doch besser die Vorlage für die bessere Strukturierung =)

**Comment by wahaxlekuke** [comment]
Im Moment wird fäschlicherweise Resist angezeigt, wenn ein Zauber verfehlt hat. - Ich denke daher kommt die Verwirrung. Dafür hab ich auch schon einen Fix geschrieben, der erstmal morgen auf dem Testserver sein aktiv sein wird.

**Comment by Gnomorus** [comment]
nur, um mal was altes widerstände betreffent einzuwerfen: http://wow.ftpi.de/showtopic.php?threadid=320

**Comment by Seniorash** [comment]
Benutzt ihr SCT? Nach dem Update werden da nämlich Sachen angezeigt, die vorher nicht angezeigt wurden (z.B, Ausweichen von Fähigkeiten).

**Comment by wahaxlekuke** [comment]
@gnomoris Mit dem letzten update hat nur die Anzeige geändert, nicht die Berechnung der treffchance.

Das ticket hier mach ich dann mal zu, weil die Treffchance richtig berechnet wird. (Die fehlerhafte Anzeige wird mit dem nächsten update behoben.)
