### ISSUE TITLE
Wurfwaffenhändler leer

### ISSUE THREAD

**Issue by Xenifa** [ClassicWoW/Nefarian_1.12.1_Bugtracker#568]
Wurfwaffenhändler verkaufen keine Wurfwaffen, getestet an Nathaniel Steendocht und Gordon Wendheim in Unterstadt

**Comment by ircfelix** [comment]
Leberkäs heißt Leberkäs, getestet in einer kleinen bayerischen Metzgerei. 

Übrigens toller Bugreport. Vote4Close.

**Comment by Seniorash** [comment]
Na, wenn Officer Felix das sagt...

**Comment by Xenifa** [comment]
Quelle wäre zum Beispiel das hier:

http://wowdata.buffed.de/npc/Nathaniel-Steendocht-4592

Laut dieser Tabelle sollte er die Wurfwaffen für Schurken verkaufen, ebenso wie 

http://wowdata.buffed.de/npc/Gordon-Wendheim-4556

Hoffe, das hilft jetzt. Ist mein erster Bugreport, daher wusste ich nicht, was ihr alles braucht...

**Comment by ircfelix** [comment]
Klickst du oben auf "Nefarian_1.12_Bugtracker", siehst du Vorlage.

**Comment by Xenifa** [comment]
Verdammt, hätte ich das mal gewusst. Sorry, geht auf meine Kappe das Ganze. Neu schreiben im gewünschten Format?

**Comment by Larnak1** [comment]
Du kannst es einfach editieren :)
