### ISSUE TITLE
Chromaggus spottbar

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#571]
Welches Verhalten wird beobachtet?
er ist spottbaer

Wie sollte es sich verhalten?
er sollte nicht spottbaer sein

Schritte zur Reproduzierung
gestriger bwl raid

Zusätzliche Informationen
Die Bossmechanik erklärt schon, dass er spott immun sein muss, wegen time lapse!
übrigens danke für das fixen des bosses, time laps funktioniert nun so wie es sollte.

Links aus unserer Datenbank:
http://datenbank.welli-it.de/?npc=14020

**Comment by dagochen** [comment]
Doppelte Meldung, bitte erst suchen ob es dazu schon was gibt: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/473

**Comment by Sabbaer** [comment]
oh sry
