### ISSUE TITLE
AQ40 Bugreport (Anorhin, Die Legion, Refugium)

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#572]
**AQ40:**

*Obsidianwächter*
- Movement zu schnell.
- Obsidianwächter Manareg zu gering (nur 1000 pro tick, anstatt 250 Mana pro Spieler (von maximal 16 Spielern))

*Anubisath Sentinel*
- reflektierte Schattenblitze/Feuerzauber ignorieren den Schattenzauberschutz/Feuerzauberschutz (evtl. auch andere Schutzzauber/Schutztränke? Bitte überprüfen!)
- macht kaum Schaden am Tank
- Die verbleibenden Anubisatz Sentinels übernehmen die Fähigkeiten der toten Anubisath Sentinels nur zum Teil.
- Aggro Range so gering, dass man die Mobs einfach umgehen kann.

*Skeram*
- Man bekommt ne ID, wenn man ein Spiegelbild tötet
- Arkane Explosion ist während der Castzeit nicht kickbar, hätte kickbar sein sollen.
- Wenig Schaden am Tank

*Allgemein*
- Geist Freilassen funktioniert nicht: Man bleibt einfach liegen nachdem man "Geist Freilassen" drückt.
- Man kann, wenn man tot ist und auf geist freilassen geklickt hat, reloggen und an ort und stelle (in der inni) den Ress annehmen.
- Teilweise Critical Error, wenn man auf "Geist freilassen" klickt.

______________________________________________________________________

**Quellen:**
http://wow.gamona.de/das-spiel/instanzen-und-raids/classic/tempel-von-ahn-quiraj/

**Comment by ircfelix** [comment]
Habt ihr den Boss absichtlich einfacher gemacht? Wenn ja wäre es interessant zu wissen was genau ihr vereinfacht habt.

**Comment by Seniorash** [comment]
Obsidianvernichter (http://datenbank.welli-it.de/?npc=15262):
- Hat 0 Rüstung.
- Entzieht Spielern kein Mana.

Wächter der Anubisath (http://datenbank.welli-it.de/?npc=15264):
- Die erste Gruppe respawnt, sobald man die Gruppe vor Skeram pullt.
- Manaburn: hat keinen Effekt.
- Donnerknall: Macht ca. 500 Schaden aber keinen Debuff. Nach Weitergabe durch Tod macht die Fähigkeit nicht mal mehr Schaden.
- Schattensalve: Trifft keine Spieler in Nahkampfreichweite (unsicher ob fehlerhaft)

Skeram (http://datenbank.welli-it.de/?npc=15263):
- Die übernommenen Spieler unterliegen einem DR, wodurch sie teilweise schwierig zu CCn sind.
- Schaden ist Blizzlike (Die Tanks sind allerdings auch overgeared) 
http://www.wowwiki.com/The_Prophet_Skeram

Allgemein: 
- Crit Error tauchte auch auf, wenn man nicht gerade tot oder am Einloggen war. Konnte auf die schnelle nicht reproduziert werden.
- Die Trashmobs geben zu viel Ruf. http://www.hordeguides.de/Fraktion/Classic/910/Brut-Nozdormus/index.htm
