### ISSUE TITLE
Heldenhafter Stoß/Spalten

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#573]
Welches Verhalten wird beobachtet?
Heldenhafter Stoß und Spalten können nicht aktiviert werden, wenn das Ziel sich nicht in Nahkampfreichweite befindet. Dadurch ist es nicht möglich direkt eine dieser autohit-basierten Attacken auszuführen wenn man gerade an einem Ziel ankommt.

Wie sollte es sich verhalten?
Diese Attacken sollten beide unabhängig von der Entfernung des Ziels aktiviert und sobald es in Nahkampfreichweite ist ausgeführt werden. Nur durch das Drücken von esc oder Abbruch von "Angreifen" sollte diese Aktivierung aufgehoben werden.

Schritte zur Reproduzierung
Auf Distanz gehen und Heldehafter Stoß und/oder Spalten aktivieren.

Zusätzliche Informationen 
https://www.youtube.com/watch?v=ISx6eni6I1k
Heruntergeladen und hochgeladen von: http://worldofwarcraft.filefront.com/file/George_2H_Fury_PvP_Episode_2;69520

Links aus unserer Datenbank 
Heldenhafter Stoß: http://datenbank.welli-it.de/?spell=78
Spalten: http://datenbank.welli-it.de/?spell=845

**Comment by Haudraufinix** [comment]
Gilt im übrigen für alle "Next Swing" Angrife. Also auch Raptorstoss und Maul
http://datenbank.welli-it.de/?spell=6807
http://datenbank.welli-it.de/?spell=14266
