### ISSUE TITLE
Magmadar: Lavabombe macht keinen Schaden

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#575]
**Welches Verhalten wird beobachtet?**

Die Lavabombe von Magmadar macht keinen Schaden (0).

**Wie sollte es sich verhalten?**

Sollte den angegebenen Schaden machen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Magmadar: http://datenbank.welli-it.de/?npc=11982
Lavabombe: http://datenbank.welli-it.de/?spell=19411

**Comment by Haudraufinix** [comment]
Die Lavabombe von Magmadar ist ein Bodeneffekt. Als ich das letzte mal davon getroffen wurde hat die definitv Schaden gemacht, solange ich drin stand. Hast du einen Screenshot o.ä.? sonst renn ich morgen mal MC mit und prüf das gerne nach =)

**Comment by Seniorash** [comment]
Kann den Report bestätigen. Das ist schon länger so
