### ISSUE TITLE
Aggroverlust bei CC-Effekten

### ISSUE THREAD

**Issue by Ataraia** [ClassicWoW/Nefarian_1.12.1_Bugtracker#577]
Heyho!

Nach langer, langer Suche... Hab ich zumindest einmal eine Erwähnung am Rande gefunden, die den Aggroverlust bei CC-Effekten durch Bosse betrifft.
Das Experiment von Nightblizzard mit dem Aggroverlust hat ja meiner Meinung nach super geklappt, bis auf die Tatsache, dass eben auch Stuns einen Aggroverlust hervorgebracht haben. Aber da sich wahrscheinlich viele Spieler aufgeregt haben, dass man bei nem Stun als Tank die Aggro verliert, habt ihr das rückgängig gemacht.
Dieser Post soll dazu dienen, mal aufzuzeigen, welche CCs einen Aggroverlust verursachen.

http://wow.allakhazam.com/wiki/Threat_%28WoW%29

Unter "Losing Aggro" steht: "Additionally, if the player is effected by most kinds of crowd control that break on damage the mobs will pick a different target - these effects include Gouge and Polymorph."

Also sollte man die Aggro nur bei CC-Effekten verlieren, die durch Schaden gebrochen werden können. Auf die schnelle wäre das einmal Fear, womit wir schonmal bei Magmadar (funktioniert), Onyxia und Nefarian (funktioniert aktuell nicht) sind. Wenn man also als Tank gefeart wird, sollte man IMMER die Aggro verlieren!
Auch bei Nicht-Boss-Mobs sollte das geschehen. Ein Beispiel: Die Gurubashi-Berserker in Zul Gurub.
http://www.wowwiki.com/Gurubashi_Berserker

"They hit fairly hard and do an AoE fear (Aggro reset), an AoE knockback, enrage at 50% and an AoE thunderclap."

Dann das Sheep: http://www.wowwiki.com/Jin'do_the_Hexxer

"Jin'do Hex - Turns the character highest on Jin'do's hate list into a frog. This is usually the main tank. Jin'do will attack the character next-highest on his hate list until the Hex expires. Can be dispelled."

Ausgehend davon ist der Magecall bei Nefarian ein echtes Problem! Denn wird der MT gesheept, verliert er ebenfalls die Aggro. Da der Magecall ohne LoS- und Entfernungseinschränkungen funktionieren sollte, kann dieser leicht zu einem Wipe führen.

http://www.wowwiki.com/Nefarian_(tactics)

"Mages
Effect: Cast Wild Polymorph on random raid members, which has no range or Line of Sight (LoS) restrictions.
Solution: Mages can use Ice Block to remove this debuff, but priests and paladins need to be ready to Dispel Magic and Cleanse polymorphed players, especially tanks. Wild Polymorph has no range or line-of-sight limitations, so moving away from the raid or behind the nearby pillars is ineffective; mages can continue to DPS through this call."

So, kommen wir jetzt zu den Stuns. Ausgehend von der ersten Quelle, sollte man nur bei den CC-Effekten die Aggro verlieren, die durch Schaden gebrochen werden können.

http://www.wowwiki.com/Stun

"Additionally, stuns are not broken by damage."

Dementsprechend sollte man bei Stuns nicht die Aggro verlieren. Abgesehen davon ist ein Tank im Stun schon problematisch genug, da er weder Ausweichen, Parieren oder Blocken kann, was den Schaden enorm erhöht.

Sämtliche Effekte, die einen Spieler immun gegen Zauber und Attacken machen (Verbannen), bewirken ja bereits einen Aggroverlust.

So, das wars erst mal, ist wieder ein wenig viel geworden... Man findet leider sehr schwer eine annehmbare Quelle, die belegt, bei welchen CCs man die Aggro verliert. Wenn ihr wollts, kann ich mich nochmal auf die Suche machen, aber dieser eine Satz war schon recht schwer zu finden. ;-)

mfg Ata

**Comment by hraesvelgr** [comment]
dass jindo's frosch-zauber die aggro resetten sollte wurde bereits im gesamtreport zu jindo aufgeführt. jindo an sich gilt jetzt aber (auf diesem server) als "blizzlike", der eigentliche detaillierte bugreport dazu wurde aber nie wirklich beachtet und ist weiterhin offen. (https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/165). in einigen punkten funktioniert jindo also immernoch nicht korrekt, und das ist nicht nur der aggroreset.

**Comment by Seniorash** [comment]
Außerhalb von Raids (World und Instanzen) funktioniert das alles richtig. So verliert man beispielsweise in UBRS die Aggro wenn man von einem Schurken Solarplexus bekommt. Das einfachste wäre einen Aggroverlust bei den Bossen hinzuzufügen, wo er halt merkbar fehlt.

**Comment by Ataraia** [comment]
So, noch eine Kleinigkeit am Rande:

Der TimeLaps bei Chromaggus ist keine Ausnahme, was die Stuns angeht. 
Theoretisch sollte der MT bei Chromaggus die Aggro ja nicht verlieren, wenn er durch den TimeLaps gestunned ist.
ABER: Zusätzlich zum Stun bewirkt der TimeLaps, dass sämtliche Aggro des Spielers verschwindet. Nachdem der TimeLaps ausläuft, erhält jeder vom TimeLaps betroffene Spieler seine Aggro leicht reduziert zurück.
Der MT sollte also die Aggro eigentlich behalten, aber da der TimeLaps noch diesen zusätzlichen Effekt hat, verliert er sie und ein Offtank muss bereitstehen, der nicht vom TimeLaps betroffen ist.

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/473

mfg Ata

**Comment by Larnak1** [comment]
> Außerhalb von Raids (World und Instanzen) funktioniert das alles richtig. So verliert man beispielsweise in UBRS die Aggro wenn man von einem Schurken Solarplexus bekommt.

Solarplexus funktioniert korrekt, weil Solarplexus sofort unterbrochen wird, wenn man danach geschlagen wird. Dieses Verhalten wurde vor einiger Zeit korrigiert. Bei Fear funktioniert es mMn auch außerhalb von Raids nicht, auch dort bleibt die Aggro, wo sie ist.

**Comment by Ataraia** [comment]
Gibts vielleicht mal ne Stellungnahme, wann ihr dieses Großprojekt in Angriff nehmen wollt?

 @ Wahax / Dotox
