### ISSUE TITLE
seal of command block parry dodge

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#578]
Welches Verhalten wird beobachtet?
siegel des befehls kann parriert geblocked ausgewichen werden etc

Wie sollte es sich verhalten?
siegel des befehls darf nur resisted werden können

Schritte zur Reproduzierung
mc raid gerade.

zusätzliche informationen:
vermute das hängt mit dem patch zusammen.

Patch 1.3.0 (07-Mar-2005)Seal of Command: The damage effects can now be resisted instead of dodged, blocked, or parried.

 Resistable Spells on holy
Paladin: 3 Judgements, Consecration, Hammer of Wrath, Holy Shock, Avenger's Shield, Repentance, Holy Wrath, Exorcism, Turn Undead,Turn Evil
Priest: Smite, Holy Fire, Holy Nova, Dispel Magic, Mass Dispel
http://www.wowwiki.com/Holy_resistance

Seal of Command and Seal of Righteousness are not listed there - an enemy player or npc can completely resist the JUDGEMENT of Righteousness (as it is coded as an actual spell) but not the Seal itself..... (kommentar: das gleiche auch bei seal of command)
(http://www.wow-one.com/forum/topic/61649-seal-of-command-fixes/page__st__20)
i know, sachen von anderen foren zu posten ist nicht das ding von euch, jedoch wurde das thema hier ausfürhlich diskutiert und beschrieben, sowie eindeutig gelöst, denn die hatten dort anscheinend auch das problem

links aus der datenbank
http://datenbank.welli-it.de/?spell=20920#taught-by-npc

**Comment by hraesvelgr** [comment]
http://paladin-guide.blogspot.de/2005/12/seals.html weitere quelle. 

und passt bitte auf, dass die chance on hit effekte, die für melee gelten danach trotzdem noch funktionieren. die hitmechanik ist die von melee-waffen, die schadensmechanik ist die von spells.

**Comment by wahaxlekuke** [comment]
Wird im Moment wieder widerstanden angezeigt oder immer noch block/parry usw.?

**Comment by Sabbaer** [comment]
widerstanden darf beim progg überhauptnicht dran stehen, nur beim richturteil und beim richturteil steht resisted dran, jupp, das ist auch korrekt, doch es geht ja um den progg beim waffenschlag.
ich teste gerade.

**Comment by Sabbaer** [comment]
nun funktioniert der zaubercrit bei siegel des befehls progg sowie richturteil nicht mehr.
1 1/2 stunden bwl raid und kein einziger crit auf richturteil oder siegel des befehls bei 10% zaubercrit.
ebenso getestet in den westlichen pestländern bei niedrigeren mobs. 30min kein einziger siegel des befehls crit. Auch mit meele crit gear und 27% meele crit getestet, kein crit von sdb oder sdbrichturteil.

**Comment by hraesvelgr** [comment]
das SIEGEL des befehls UND das RICHTURTEIL des befehls bekommen beide ihre crit- und hit-chance vom nahkampfcri und -hit.
der schaden von siegel und richturteil ist jedoch als zauberschaden zu werten, und demnach folgt es den zauber-resistenz-formeln. 

schadensmechanik und treffermechanik folgen also zwei unterschiedlichen schulen. 

hoffe, es ist jetzt deutlich :D

**Comment by Sabbaer** [comment]
nein, das ist nicht richtig. Siegel des befehls geht auf meele hit und spell crit, richturteil des befehls geht auf spellhit und spellcrit. nur der white hit vom paladin geht auf meele crit und meele hit.

**Comment by Sabbaer** [comment]
ok, habe falsche informationen, denn die patchnotes zu 1.3.0 wurden durch bestimmte blueposts verändert und es wurde anscheinend danach wieder zurückgenommen.
http://blue.cardplace.com/cache/wow-realm-test/391.htm
hraesvelgr hat also recht....

**Comment by Acolatronico** [comment]
siegel des befehls proc und richurteil sind beide abhängig von dem meele crit wert. seit dem heutigen update? können beide fähigkeiten nicht mehr critten.

**Comment by dagochen** [comment]
Das wichtige was ich aus hraesvelgrs post rauslese ist:
Hitberechnung wie ein Melee und Dmgberechnung wie ein Spell
Oder?

**Comment by hraesvelgr** [comment]
es verursacht zauberschaden, der durch meleeschaden beeinflusst wird, berechnung nach zauber-resistenzen. critchance und hitchance bei siegel und richturteil gilt für melee.
wobei siegel des befehls nicht nur durch nahkampfschaden (70% des nahkampfschadens) verstärkt werden kann, sondern auch durch zauberschaden. 20% für "zauberschaden" und 29% für "heiligschaden". 
ausserdem trifft das siegel sowie das richturteil  mit 200% kritischem schaden (was für alle spells gilt)


ist zugegebenermaßen bisschen komplifiziert. aber ich hoffe, dass es jetzt echt mal zusammengefasst ist
