### ISSUE TITLE
Wetzsteine halten zu lange

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#579]
Welches Verhalten wird beobachtet?
http://datenbank.welli-it.de/?item=7964 und http://datenbank.welli-it.de/?item=12404 buffen einen bzw die waffe für 60 min

Wie sollte es sich verhalten?
Der buff sollte nur 30 min anhalten, so wie im tooltip beschrieben

Schritte zur Reproduzierung
wetzstein auf waffe anwenden

Zusätzliche Informationen (Screenshots, Videos, etc.)
vermutlich verhält es sich bei allen anderen wetzsteinen ebenfalls so.
http://datenbank.welli-it.de/?search=wetzstein#items
http://www.wowwiki.com/Dense_Sharpening_Stone?oldid=219780 (30 min)

**Comment by dagochen** [comment]
Elementarwetzstein auch: http://datenbank.welli-it.de/?item=18262

**Comment by Seniorash** [comment]
Weitere Bugs im Zusammenhang mit Wetzsteinen: #467 #64

**Comment by bugreportor** [comment]
Dagonchen hat leider keine Ahnung.. Mit Patch 1.11.1 wurden alle wetzsteine auf 60 Minuten gepatcht.

**Comment by dagochen** [comment]
http://www.wowwiki.com/Patch_2.3.0
Sharpening Stones and Weightstones now last 1 hour.

**Comment by c0keh** [comment]
quelle @bugreportor ?
