### ISSUE TITLE
Druide Katzengestalt kein Aggroreduce

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#580]
Welches Verhalten wird beobachtet?
In katzenform wird der schaden genau wie bei anderen melees in aggro „umgewandelt“

Wie sollte es sich verhalten?
Druiden in katzengestalt sollten standardmäßig weniger aggro produzieren (als andere melees)

Schritte zur Reproduzierung
in katzenform ein wenig mehr schaden an einem feindlichen NPC verursachen als ein anderer nahkampf-charakter (-> durch die aggro-reduce in katzenform müsste deshalb trotzdem der andere, nicht die katze, die aggro haben)

Zusätzliche Informationen (Screenshots, Videos, etc.)
"Cat Form: This form now has an innate threat reduction component.“
http://www.wowwiki.com/Patch_1.12.0
ob der aggro-reduce tatsächlich nicht auf nefarian ist müsste evtl nochmal von jemandem getestet werden!!

**Comment by Gnomorus** [comment]
Der Mob sollte sein Ziel erst ab 1xx% Aggro des aktuellen Ziels ändern. Für Nahkampfangriffe war diese Schwelle meines Wissens 110%. D.h. mit 109% Aggro des konkurrierenden Nahkämpfers, wird der Mob sein Ziel nicht ändern.
Jetz kommt es halt drauf an, wie weit du über dem Konkurrent in der Aggro/im Schaden warst.

**Comment by wahaxlekuke** [comment]
Die Aggro-Reduzierung funktioniert. In der Katzengestalt hat man auch diesen unsichtbaren Buff: http://datenbank.welli-it.de/?spell=3025. Das macht 29% Aggro-Reduzierung.
