### ISSUE TITLE
Zul'Farrak: aus Flachem Grab keine Gegner

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#582]
Welches Verhalten wird beobachtet?
Aus http://datenbank.welli-it.de/?object=128308 und http://datenbank.welli-it.de/?object=128403 in zul'farrak erhält man beim öffnen immer nur freeloot

Wie sollte es sich verhalten?
Aus http://datenbank.welli-it.de/?object=128308 und http://datenbank.welli-it.de/?object=128403 aus zul'farrak sollten gelegentlich http://datenbank.welli-it.de/?npc=7286 oder http://datenbank.welli-it.de/?npc=7276 rauskommen/spawnen, wenn man sie öffnet

Schritte zur Reproduzierung
http://datenbank.welli-it.de/?object=128308 oder http://datenbank.welli-it.de/?object=128403 öffnen

Zusätzliche Informationen (Screenshots, Videos, etc.)
(noch) nichts

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/581
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/584

**Comment by wahaxlekuke** [comment]
Also bei meinem Test kommen da auch npcs aus den Gräbern. Kannst davon mal ein Video machen?

**Comment by c0keh** [comment]
hatte es gestern extra nochmal getestet, da kam aus 10 gräbern kein einziger. jetzt nochmal getestet und es kamen welche. war dann wohl nur pech gestern, sorry.

wobei bei mir jetzt auch 4x der elite zombie raus kam und kein toter held. bin mir nicht sicher, ob das so richtig ist.

trotzdem sorry nochmal.
