### ISSUE TITLE
Hunter Epic Quest für andere machbar

### ISSUE THREAD

**Issue by c0keh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#586]
Welches Verhalten wird beobachtet?
Bei den objectives für http://datenbank.welli-it.de/?quest=7636 (köpfe der dämonen einsammeln) kann jeder aus der gruppe, der die quest hat, die köpfe looten.

Wie sollte es sich verhalten?
Nur der, der den dämonen angesprochen hat und somit auch gegen ihn kämpfen muss, darf (bei den köpfen) lootberechtigt sein.

Schritte zur Reproduzierung
bspw. 2 jäger in eine gruppe tun, einer mit der quest. der andere jäger ohne quest spricht die dämonen an und tötet sie. Der jäger mit der quest, der gar nichts gemacht hat, kann nun einfach die köpfe looten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
allen jägern, die nur auf diese weise den bogen bekommen haben, sollte er wieder weggenommen werden. oder sie gebannt werden (da bugabuse). Oder sie müssen sich in eine ecke stellen und sich ganz doll SCHÄMEN!!! ;)

dämonen:
http://datenbank.welli-it.de/?npc=14533#drop
http://datenbank.welli-it.de/?npc=14534#drop
http://datenbank.welli-it.de/?npc=14530#drop
http://datenbank.welli-it.de/?npc=14535#drop

auch dürften eigentlich nur charaktere, die die Q überhaupt haben, in der lage sein, die NPCs als dämonen zu "enttarnen" und somit angreifbar machen können. aber das ist ein anderes thema/issue

**Comment by wahaxlekuke** [comment]
Hast du hierfür irgendeine Quelle? Soviel ich gehört habe ging das zumindest irgendwann mal.

**Comment by c0keh** [comment]
gegenfrage: es gibt ja doch relativ viele videos und guides zu der entsprechenden Q; steht in irgendeinem guide oder sieht man in irgendeinem video, dass man sich das auch einfach von einem overgearten/-skillten kollegen machen lassen kann?

da quellen für zu finden ist schwer bzw unmöglich, da es total offensichtlich ist. es ist der kern der Q, dass sie alleine und von einem selbst gemacht werden muss.
wenn das damals wirklich so ging wie hier, dann möge dafür jemand entsprechende quellen liefern.

**Comment by Ghulfang** [comment]
ich bin mir ziemlich sicher das das damals ging. 

https://www.youtube.com/watch?v=_N3BlF-x-to
I beat this demon alone for my bow/staff. And then made 200g everytime i did it for another hunter and it was super easy.

**Comment by c0keh** [comment]
@ghulfang man konnte sich auf die accounts der anderen einloggen, SO kenn ich das auch.
war aber auch nicht gern gesehen, da account-sharing

**Comment by dagochen** [comment]
nein das ging auch so. hab silithus dämon für nen dutzend anderer jäger gekillt.
ansprechen + verwandeln ging nicht.
töten ging.
looten durch anderen jäger ging danach auch.
