### ISSUE TITLE
AQ20 Bugreport General Rajaxx (Gilde Inheritance)

### ISSUE THREAD

**Issue by Nightfly385** [ClassicWoW/Nefarian_1.12.1_Bugtracker#589]
AQ20:

Trashmobs:

- Hive'Zara Stinger: http://www.wowwiki.com/Hive%27Zara_Stinger
Der Charge funktionierte soweit, jedoch sollte der Schaden rein physisch sein und kein Naturschaden
Ebenfalls sind die Stecher weiterhin stunbar, was nicht sein sollte.

- Die Skarabäuskisten sind immer noch nicht verschlossen.

Boss: General Rajaxx (http://www.wowwiki.com/General_Rajaxx)

- Nach einem Wipe gibt es keinen Respawn von Andorov und seinen Gefolgsleuten. Ich glaube mit 1.9 war das sogar korrekt, zum testen jedoch etwas bescheiden.

- Die Hauptmänner der 7 Wellen können alle mit CC kontroliert werden (Fear,Eisfalle usw.) Dies sollte nicht der Fall sein. 

- Andorov und seine Gefolgsleute ziehen so gut wie keine Aggro von den Mobs! Das war früher auf jeden fall anders. Da mussten sich die Tanks tierisch anstrengen, die Aggro der entsprechenden Mobs und auch vom General selber zu halten bzw. in den meisten Fällen hat man versucht, dass Andorov den Boss tankt, da dieser immun gegen den Knockback des Thunder-Claps ist.

Fähigkeiten von Rajaxx:

- AoE Thunder Clap that cuts everyone's hitpoints in half (200 minimum damage) and wipes aggro.
- A single target deaggro, where he yells "You are not worth my time, <target>." and changes to a new target.

Der Aggro-Reset funktioniert beim Thunder-Clap. Jedoch ist es unseren Tanks danach nicht mehr möglich erneut Aggro aufzubauen. Beide Tanks haben versucht Aggro aufzubauen (Heldenhafter Stoß, Rüstungszerreißen usw) Jedoch schien das den Boss überhaupt nicht zu interessieren und er nahm sich zufällig irgendwelche Raidmember vor. Wir hatten auch das Gefühl, dass die zweite Fähigkeit (A single target deaggro, where he yells...) sich nicht nur auf ein Ziel auswirkte, sondern auf mehrere gleichzeitig und das die Fähigkeit mit dem Thunder Clap gekoppelt war.

- HP: Rajaxx hatte über 700k HP. In Classic betrug dieser Wert ca. 416K
Wenn Andorov und seine Gefolgsleute noch da sind, sind die 700k HP von Rajaxx mit viel Glück schaffbar. Ohne Andorov konnten wir ca. 500k HP abziehen bevor es zum Wipe kam. Man beachte das wir mit hierbei mit einem 20 Mann Raid drin waren, der zum Großteil komplett T2 gegeared war + Flasks und Pots.

- Mit dem Start des Events verfiel die Wirkung der Totems der Schamanen. Windfury, Erdstärke usw wurde gestellt, jedoch gab es keinen Effekt. 

Die Trashmobs der Wellen:

- Qiraji Gladiator
- Qiraji Swarmguard

haben weiterhin keine Rüstung. Der Schaden ist inzwischen angehoben worden. Mit T2-Gear+Flask ist es heilbar, mit schlechterem Gear könnte es ziemlich schwierig werden (ist aber nur eine Vermutung)

**Comment by Karmanaz** [comment]
@nightblizard Testserver Task, kann auch zu
