### ISSUE TITLE
Hunter EpicQuest Simone die Verführerin - Kein Loot

### ISSUE THREAD

**Issue by Ghulfang** [ClassicWoW/Nefarian_1.12.1_Bugtracker#590]
Welches Verhalten wird beobachtet?
Nach dem Töten von Simone der Verführerin (http://datenbank.welli-it.de/?npc=14533) kann man ihren Kopf (http://datenbank.welli-it.de/?item=18952) für die Hunter Epic Quest (http://datenbank.welli-it.de/?quest=7636) nicht looten.

Wie sollte es sich verhalten?
Man sollte Simones Kopf (http://datenbank.welli-it.de/?item=18952) nach dem besiegen looten können.

Schritte zur Reproduzierung
Nach UnGoro reisen, Dämon killen, looten.

**Comment by c0keh** [comment]
hinzuzufügen ist vielleicht noch, was eigentlich selbstverständlich sein sollte, dass nur der jäger, der ihn angesprochen hat, den kopf looten können darf.

**Comment by Ghulfang** [comment]
das stimmt so nicht.

They can be addressed by anyone but only a hunter on the epic hunter quest has the option in dialogue to unmask them. After choosing that option the humanoid in question turns into its real demon form after a few seconds. Those few seconds should be used to get to a safe distance to avoid initial aggro. Once shapeshifted, the demon remains that way for about 15 minutes during which time it may be killed by any hunter.
Quelle: http://free-zg.t-com.hr/tlovey/epic.htm

**Comment by Ghulfang** [comment]
Deine Aussage ist soweit richtig. Das schließt aber nicht aus, das man den Dämon von einem anderen Jäger der die Quest bereits gemacht hat, killen lassen kann und den Kopf selbst lootet.

They can be addressed by anyone but only a hunter on the epic hunter quest has the option in dialogue to unmask them. After choosing that option the humanoid in question turns into its real demon form after a few seconds. Those few seconds should be used to get to a safe distance to avoid initial aggro. Once shapeshifted, the demon remains that way for about 15 minutes during which time it may be killed by any hunter.
Quelle: http://free-zg.t-com.hr/tlovey/epic.htm

**Comment by c0keh** [comment]
wo steht, dass den kopf dann jeder looten kann?

1. steht da "only a hunter on the epic hunter quest has the option in dialogue to unmask them."
deutsch: nur jäger, die die Q offen haben, können ihn zum dämonen verwandeln (auf nefarian ist das nicht so, bug)

2. "during which time it may be killed by any hunter."
deutsch: jeder (jäger) kann gegen den dämonen kämpfen und ihn töten, unabhängig davon, welcher ihn angesprochen hat (auf nefarian auch nicht so, bug).

3. "the demon remains that way for about 15 minutes"
deutsch: der dämon bleibt nur 15min und despawnt dann (ist auf nefarian auch nicht so)

zu 3. hatte ich gerade auch schon was gefunden, wo die rede von 20 min war.

kurz: dass man ihn sich von wem anders töten lassen kann, um ihn dann selbst zu looten, steht da nicht

**Comment by Ghulfang** [comment]
mach bitte dazu ein eigenen post auf
