### ISSUE TITLE
Schlachtfeld: Warsongschlucht - Fear unter der Map

### ISSUE THREAD

**Issue by Discipline1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#592]
Hey,

neulich im BG Warsongschlucht hatte ich die Flagge und stand direkt auf dem Flaggenpunkt der Allianz um diese zu verteidigen. Nach einem Angriff der Horde bekam ich genau dort einen "Streuschuss" vom Jäger ab. Desorientiert fiel ich durch den Boden und gelang auf einer kleinen Kante unterhalb der Karte. 
Wie auf dem Screenshot schön zu sehen: http://www.directupload.net/file/d/3938/2e5p273z_jpg.htm

Wie sollte es sich verhalten?
Bei Fears oder Desorientierungen sollte man oberhalb der Karte bleiben. Bei dem Gameobject wo die Flaggen immer spawnen scheint eine kleine Lücke hinsichtlich dessen zu sein. Beobachtet nur bei dem Allianzspawn der Flagge. 

Grüße!

**Comment by Larnak1** [comment]
Das ist ein allgemeines Problem von Fear und Desorientieren, das es praktisch an allen Kanten gibt. Der Fix von heute
(http://www.mmobase.de/forum/updates-changelog/6867-update-31-03-2015-a.html)
soll das Problem verbessert haben.
