### ISSUE TITLE
Dunkeleisen und reiches Thorium

### ISSUE THREAD

**Issue by TiberiusII** [ClassicWoW/Nefarian_1.12.1_Bugtracker#595]
Hallo liebe Leute. Mir ist aufgefallen, dass es in der sengenden Schlucht und in der brennenden Steppe viel zu wenig Dunkeleisen gibt. Damals war in den beiden gebieten fast nur dunkeleisen und Thorium zu finden. Mithril war selten. 

In der brennenden Steppe gabs auch ordentlich Dunkeleisen und sogar mindestens 2 reiche Thoriumvorkommen.

Grüße

**Comment by ircfelix** [comment]
Und mir ist aufgefallen dass wohl irgendwie wenn Sie mit dem Zug vom Hauptbahnhof aus starten, dieser dann in zehn Minuten am Flughafen eincheckt. Könnten aber auch 11 minuten sein, jedenfalls habe ich keine Quelle diesbezüglich und behaupte das jetzt einfach mal.

Weiterhin ist mir aufgefallen, dass level eins hasen nicht wie vorgesehen 1000g droppen.

Klingelts?

**Comment by TiberiusII** [comment]
Es spielen so viele Spieler hier die zu klassik Zeiten gespielt haben. Es gab in der brennenden Steppe mindestens 5 Dunkeleisenvorkommen. mindestens. 
4 dunkeleisenvorkommen in der gesamten nicht Dungeon Welt ist einfach lächerlich. Das wäre wie wenns in der gesamten WoW Weltkarte nur 4 Spots Gromsblut geben würde.

Na Klingelts?

**Comment by Wosser** [comment]
Vielen Dank für deine ausführlichen Quellenangaben.

**Comment by TiberiusII** [comment]
Dafür gibts keine Quellen mehr ihr Schlaumeier. Aber vll sollte man mal den Erinnerungen vieler Spieler glauben.

**Comment by dagochen** [comment]
Ich erinnere mich daran, dass Jäger immer über 10000 Leben hatte und alles geoneshottet haben....und alle Jäger hier werden mir bestimmt zustimmen *hust*

**Comment by ircfelix** [comment]
Momentan bist du der einzige der "vielen Spieler", der einfach ohne Quelle was behauptet. Du hast vermutlich auch recht, aber wenn die bugreports hier weiterhin so schlampig geschrieben werden, dann grunzt in Bälde jeder nur noch unproduktiven Bullshit in den Bugtracker rein.
Also sei doch bitte so gut, such Quellen und mach an vernünftigen Report und kein solches Trauerspiel mehr.

Dingdong! Dingdong!

**Comment by Seniorash** [comment]
Er hat recht, die Spawnpunkte von Erzvorkommen stimmen hier überhaupt nicht. Kannst versuchen Quellen dazu zu finden, ist in der Priorität aber sicherlich weiter unten.
@ ircfelix: Hör mal auf unter jedem nicht konformen Bugreport rumzuweinen. Da gibt es andere Leute die entscheiden ob er so akzeptiert wird oder nicht. Oder wurdest du hier von irgendjemandem zum Cop ernannt? Machst dich einfach schon lächerlich

**Comment by ircfelix** [comment]
@Senior: dass ich "weine" ist nicht korrekt, eher ermahne ich die Leute. Und wenn das nicht passt, dass ich versuche das ganze hier einigermaßen am laufen zu halten, dann werden mich "andere Leute" schon drauf hinweisen und nicht DU.

Das war mein letzter Kommentar zu der Thematik. Ich habe keine Zeit mit dir hier zu diskutieren.

P.S. der einzige der hier gerade Mimimi macht, bist du.
