### ISSUE TITLE
Mindeststufen von Berufen falsch

### ISSUE THREAD

**Issue by karni186** [ClassicWoW/Nefarian_1.12.1_Bugtracker#596]
Zur Zeit ist es möglich mit Charakteren sehr niedriger Stufen z.B. Thorium abzubauen, da die Mindeststufen nicht korrekt sind. Reales Beispiel: Ich beobachte zur Zeit Charaktere der Stufe 12, die reiches Thoriumvorkommen abbauen. Laut der folgenden Tabelle müssten sie aber mindestens Stufe 25 haben:

Siehe hier: http://wow.gamona.de/berufe/

**Comment by Slimmer2** [comment]
Dein Link ist keine Info für classic.

**Comment by wahaxlekuke** [comment]
> You must be level 35 to train Artisan level in building tradeskills. 

usw. http://www.wowwiki.com/Profession?oldid=325413

**Comment by Slimmer2** [comment]
wahaxlekuke dein Link bezieht sich schon auf BC

**Comment by wahaxlekuke** [comment]
> Revision as of 18:01, November 14, 2006

Auch wenn da schon zukünftige Änderungen mit BC erwähnt werden bezieht sich der Artikel auf Zustand zu Classic-Zeiten. Außerdem gibts den Hinweis mit den Mindeststufen auch in noch früheren Version von dem Wiki-Artikel.
