### ISSUE TITLE
Death Coil kann kritisch trefffen.

### ISSUE THREAD

**Issue by Nobugsanymore** [ClassicWoW/Nefarian_1.12.1_Bugtracker#597]
Welches Verhalten wird beobachtet?
Die Hexenmeisterfähigkeit "Todesmantel" kann aktuell kritische Treffer landen (und ich glaube auch teilweise widerstanden werden).

Wie sollte es sich verhalten?
Todesmantel sollte nicht kritisch treffen können und auch nicht teilweise-widerstanden werden können.
"It is a binary spell, and as such it can only hit or miss. Neither critical hits nor partial resists are possible."

Schritte zur Reproduzierung
Deathcoil benutzen

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www.wowwiki.com/Death_Coil_%28warlock_ability%29
Hexenmeister Videos in denen Deathcoil niemals crittet.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?spell=28412

**Comment by Sabbaer** [comment]
woher kommen diese informationen? wie es zu classic war, finde leider nichts darüber

**Comment by wahaxlekuke** [comment]
Ich bin mir relativ sicher, dass der aktuelle Zustand falsch ist, weil sowohl binary als auch non-binary resistance
