### ISSUE TITLE
Schlachtstandarten fehlerhaft/verbrauchbar

### ISSUE THREAD

**Issue by Ghulfang** [ClassicWoW/Nefarian_1.12.1_Bugtracker#598]
Welches Verhalten wird beobachtet?
Die Schlachtstandarten verbrauchen sich nach dem benützen wie Tränke. Sie sollten jedoch erhalten bleiben und nach einem Cooldown wieder verwendbar sein.

Links aus unserer Datenbank (hier gehts zur Datenbank)
Schlachtstandarte der Frostwölfe: http://datenbank.welli-it.de/?item=19046
Schlachtstandarte der Sturmlanzen: http://datenbank.welli-it.de/?item=19045
Schlachtstandarte der Allianz: http://datenbank.welli-it.de/?item=18606
Schlachtstandarte der Horde: http://datenbank.welli-it.de/?item=18607

Die Schlachtstandarten der Allianz und Horde sollten 10 Minuten Cooldown haben:
http://www.wowhead.com/item=18606/alliance-battle-standard
http://www.wowhead.com/item=18607/horde-battle-standard

Die Schlachtstandarten der Frostwölfe und der Sturmlanzen sollten 15 Minuten Cooldown haben:
http://www.wowhead.com/item=19046/frostwolf-battle-standard
http://www.wowhead.com/item=19045/stormpike-battle-standard

Quellen:
erster Kommentar: http://wowdata.buffed.de/item/Verbrauchbar/Schlachtstandarte-der-Allianz-18606#comments

http://wow.gamona.de/aktuelles/patchnotes/live/patchnotes-1-6-de/
PvP-Schlachtstandarten von Horde und Allianz werden jetzt nur noch innerhalb von PvP-Schlachtfeldern verwendet werden können, die Abklingzeit wurde jedoch auf 10 Minuten verringert.

Video: min 4:07
https://www.youtube.com/watch?v=IMYQ7PT1bEU#t=248

Anmerkung: wurde anscheinend schon einmal gefixt, hat es aber nicht auf Nefarian geschafft.
http://www.mmobase.de/forum/bugtracker-archiv/2556-schlachtstandarte-der-allianz-horde-nichtsowichtig.html

**Comment by Gnomorus** [comment]
guckst du #357

**Comment by bugreportor** [comment]
"Similar to a totem, it is placed in a stationary position, and provides 15% more health points for all party members within 45 yards of it. It can take 1500 points of damage before being destroyed. They can only be used in PvP Battlegrounds and have a cooldown of 10 minutes. They last for 2 minutes, until destroyed, or until the caster is killed."
und 
"Another type of battle standard that can only be used in the Alterac Valley Battleground are the Stormpike Battle Standard (Alliance) and Frostwolf Battle Standard (Horde). These battle standards also differ from regular battle standards in that they increase the damage (dealt) by 10% and have a cooldown of 15 minutes. They are similar in that they work on party members within 45 yards, last for a maximum of 2 minutes, and have 1500 health." 
Wow-Wiki eintrag vom 30.09.2006 
http://www.wowwiki.com/Battle_Standard?direction=prev&oldid=369660

Bitte wieder öffnen und dafür unvollständigen Report #357 schließen.
