### ISSUE TITLE
Grunzer von Orgrimmar: Lederverarbeitung, Kürschner, Bergbau Lehrer vertauscht

### ISSUE THREAD

**Issue by Jizzl3** [ClassicWoW/Nefarian_1.12.1_Bugtracker#599]
Wenn die Grunzer von Orgrimmar nach dem Lederverarbeitungs-, Kürschner- oder Bergbaulehrer gefragt werden, zeigen sie nicht den korrekten Lehrer an.

SOLL-Zustand => IST-Zustand

Lederverarbeitung => Bergbaulehrer
Bergbau => Lederverarbeitung
Kürschner => Schneiderlehrer

Ein ähnlicher Fehler ist mir auch bei einer Wache in dem Taurendorf vor Thunder Bluff aufgefallen.

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451
