### ISSUE TITLE
Paladin: Reckoning / Abrechnung

### ISSUE THREAD

**Issue by Nobugsanymore** [ClassicWoW/Nefarian_1.12.1_Bugtracker#602]
Welches Verhalten wird beobachtet?
Die zusätzlichen Schläge von "Abrechnung" (http://datenbank.welli-it.de/?spell=20178) können zu hoch stacken (5 Aufladungen, anstatt 4) und Waffen- und Paladinprocs wie z.B. Siegel des Befehls (http://datenbank.welli-it.de/?spell=20920) auslösen. Außerdem gibt es in Bezug auf /issues/548 und http://blue.cardplace.com/cache/wow-paladin/1069149.htm noch Situationen in denen der Paladin seine Aufladungen nicht verliert:
-Ending a Duel
-Mounting up
-Switching weapons

Wie sollte es sich verhalten?
Die zusätzlichen Schläge von Abrechnung sollten keine Waffen- und/oder Paladinprocs wie z.B. Siegel des Befehls auslösen können.
Die maximale Anzahl an Aufladungen für zusätzliche Schläge mit Abrechnung sollte bei vier und nicht fünf liegen. 
Der Paladin sollte seine Aufladungen für Zusatzschäge verlieren wenn er ein Duell beendet, aufs Mount steigt oder die Waffen wechselt.

Schritte zur Reproduzierung
1. Im Duell critten lassen 2. Aufmounten und zum Pvp-Anmelder reiten. 3. Den Nächstbesten Onehitten
oder
1. Fünf Aufladungen mit Schild+Einhandwaffe sammeln in dem man nicht zurückschlägt 2. Auf langsame Zweihandwaffe wechseln 3. Jemanden Onehitten

Zusätzliche Informationen (Screenshots, Videos, etc.)
Es ist zwar korrekt, dass man die Charges nicht verlieren sollte wenn:
-Autoattacking too early (e.g. from out of range)
-Losing control of your character (Fear, Scattershot, Blind, Polymorph, Mind Control etc.)

In allen anderen Fällen war es aber kein Bug und man sollte dementsprechend die Aufladungen verlieren.

**Comment by Nobugsanymore** [comment]
Edit: http://www.warcraftmovies.com/de/movieview.php?id=26149 youtube: https://www.youtube.com/watch?v=lQzxgkXRA1Y
Laut diesem Video vom 19.08.2006 - drei Tage vor Patch 1.12 Release -  verliert man die Reckoning-charges wohl doch wenn man sich im Fear, Blind, Scatter Shot oder Polymorph befindet. Siehe Minute 5:20. In den Patchnotes von 1.12 (http://www.wowwiki.com/Patch_1.12.0)  steht auch nicht, dass daran noch  etwas geändert wurde.

**Comment by Sabbaer** [comment]
wtf, du hattest letztens erst den allerselben beitrag gepostet und ich habe ihn beantwortet, und entweder hast du ihn selber gelöscht, oder ein dev hat ihn gelöscht.
Erbitte selbiges sonst muss ich wieder einen wall of text schreiben

**Comment by Nobugsanymore** [comment]
"wtf, du hattest letztens erst den allerselben beitrag gepostet und ich habe ihn beantwortet, und entweder hast du ihn selber gelöscht, oder ein dev hat ihn gelöscht.
Erbitte selbiges sonst muss ich wieder einen wall of text schreiben"
Der letzte Post dazu kam nicht von mir. Dass Reckoning eine Aufladung zuviel hat, hast du ja sogar selbst schon reportet: http://www.mmobase.de/forum/bugtracker-archiv/3849-reckoning-4.html

**Comment by Sabbaer** [comment]
ach, und deswegen musst du das nochmal reporten? doppelposts werden geschlossen btw, und so wie ich das jetzt hier grad mitbekommen ist das glaub ich schon gefixed,

**Comment by Sabbaer** [comment]
no comment on you anymore, dont feed the troll

**Comment by wahaxlekuke** [comment]
Ich werde hier auf jedenfall erstmal die offensichtlichen Fehler fixen, also dass der Buff 5 statt 4 Aufladungen haben kann und dass er in den genannten Fällen
>-Ending a Duel
-Mounting up
-Switching weapons

nicht verschwindet. Ob das bei CC-Effekten auch verwinden soll oder nicht, werd ich irgendwann später mal überprüfen.

**Comment by Sabbaer** [comment]
bitte dabei auch das fehlerhafte buße beachten, das ich nicht noch extra reporten werde, das nicht als stun zählt und weniger RICHTURTEIL des befehls schaden macht! find das schon sehr armselig, da in einem blue track das als bugg beschrieben wurde und sein video nicht 1.12 ist sondern von weis gott wann. es gibt keinen einzigen beweis von wann das video ist und ich kann videos posten wo jmd mit dem mount nach og reinreitet und danach einen 1 hittet!

**Comment by Sabbaer** [comment]
meine komplette erklärung sowie sein post, in dem er falsch zitiert hat etc, wurde aus dem forum hier gelöscht!

**Comment by Ilikegyoza** [comment]
Der erste Kommentar zu dem Video auf http://www.warcraftmovies.com/de/movieview.php?id=26149
ist vom 19/08/2006.

Und lieber Sabbaer kam der letzte Bugreport von mir und nicht von Nobugsanymore
