### ISSUE TITLE
Siegel des Befehls / Rache

### ISSUE THREAD

**Issue by Nobugsanymore** [ClassicWoW/Nefarian_1.12.1_Bugtracker#603]
**Welches Verhalten wird beobachtet?**
Die Siegel des Befehls-Procs (http://datenbank.welli-it.de/?spell=20920) fallen insbesondere im Zusammenhang mit Rache (http://datenbank.welli-it.de/?spell=20059)  unverhältnismäßig hoch aus. 
Außerdem können im Moment auch die zusätzlichen Schläge von Abrechnung den Proc auslösen. Siehe: /issues/602

**Wie sollte es sich verhalten?**
Laut Tooltip und Datenbank bezieht sich der Schaden von SdB immer auf "70% of normal weapon damage" (http://datenbank.welli-it.de/?spell=20920). "Normal" weapon damage heißt ohne Multiplikatoren wie Zweihand-Spezialisierung und Rache. Andernfalls würde SdB von diesen Talenten doppelt profitieren.
Meine Vermutung:
Anstatt mit 
(Waffenschaden * 0,7 + SPD-Koeffizient) * 1.15
wird mit 
(Waffenschaden * 1.15 * 0,7 + SPD-Koeffizient) * 1.15 gerechnet. 
Was erklären würde warum die SdB-Procs auf unserem Server so hoch ausfallen.
Eine andere Möglichkeit wäre, dass die prozentualen Schadenboni von kritischischen SdB-Treffern nicht nicht additiv sondern multiplikativ stacken.
1,15 (Rache) * 1,1 (Aura) * 2 (Crit) = 2,53 Schadenmultiplikator anstatt 
1,15 (Rache) + 0,1 (Aura) + 1 (Crit) = 2,25 Schadensmultiplikator für kritische SdB-Treffer.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
In meinen Tests habe ich mit weniger +Zauberschaden, weniger AP und einer wesentlich schwächeren Waffe (http://datenbank.welli-it.de/?item=19854) höhere SdB-Crits gemacht als Kirill in seinem Video. ( http://www.warcraftmovies.com/movieview.php?id=24936 und http://www.warcraftmovies.com/movieview.php?id=27618, Youtube-Link: https://www.youtube.com/watch?v=r8ZUqTlUq7U)
Unser aller Lieblingspaladin Sabbaer hat laut eigenen Angaben schon für über 2000 Schaden mit Siegel des Befehls gecrittet.

**Comment by hraesvelgr** [comment]
siegel des befehls skaliert nicht nur mit waffenschaden, sondern auch mit zauberschaden  (20%) und heiligschaden (29%). hast du das mit einberechnet? ist ja klar, wenn overbuffed sabbaer mit full vz t2 gear durchs bg rennt, und lowbobs umklatscht. 

rüstung wird nicht angerechnet, holy-resi hat eh keiner, und es crittet für 200% schaden. das macht nunmal...rumms.

**Comment by Sabbaer** [comment]
"Welches Verhalten wird beobachtet?
Die Siegel des Befehls-Procs (http://datenbank.welli-it.de/?spell=20920) fallen insbesondere im Zusammenhang mit Rache (http://datenbank.welli-it.de/?spell=20178) unverhältnismäßig hoch aus."
deine berechnung muss dann aber falsch sein. 

Außerdem können im Moment auch die zusätzlichen Schläge von Abrechnung den Proc auslösen. Siehe: /issues/602"
Dazu erbitte ich bitte screenshots in denen dies der fall ist, denn das hab ich bis jetzt noch nie erlebt.
Du solltest bedenken, dass wir paladine häufig das doppelschlagtrinket anhaben.

"Wie sollte es sich verhalten?
Laut Tooltip und Datenbank bezieht sich der Schaden von SdB immer auf "70% of normal weapon damage" (http://datenbank.welli-it.de/?spell=20920). "Normal" weapon damage heißt ohne Multiplikatoren wie Zweihand-Spezialisierung und Rache. Andernfalls würde SdB von diesen Talenten doppelt profitieren.
Meine Vermutung:
Anstatt mit 
Waffenschaden * 0,7 + SPD-Koeffizient * 1.15
wird mit 
(Waffenschaden * 1.15) * 0,7 + SPD-Koeffizient * 1.15 gerechnet. 
Was erklären würde warum die SdB-Procs auf unserem Server so hoch ausfallen.
Eine andere Möglichkeit wäre, dass die prozentualen Schadenboni von kritischischen SdB-Treffern nicht nicht additiv sondern multiplikativ stacken.
1,15 (Rache) * 1,1 (Aura) * 2 (Crit) = 2,53 Schadenmultiplikator anstatt 
1,15 (Rache) + 0,1 (Aura) + 1 (Crit) = 2,25 Schadensmultiplikator für kritische SdB-Treffer."

deine "Vermutung" ist nicht richtig! die berechnungen werden ganz normal ausgeführt. habe wochen damit verbracht alles zu überprüfen und nachzurechnen. Ich biete dir gerne an mit mir ins ts zu kommen und ich rechne dir alles bis ins kleinste detail vor.

"Zusätzliche Informationen (Screenshots, Videos, etc.)
In meinen Tests habe ich mit weniger +Zauberschaden, weniger AP und einer wesentlich schwächeren Waffe (http://datenbank.welli-it.de/?item=19854) höhere SdB-Crits gemacht als Kirill in seinem Video. ( http://www.warcraftmovies.com/movieview.php?id=24936 und http://www.warcraftmovies.com/movieview.php?id=27618, Youtube-Link: https://www.youtube.com/watch?v=r8ZUqTlUq7U)"

der paladin in dem video hat bei keinem einzigen seiner schläge heilig aura an. er hat 137 spdmg an.
Er hat keine buffmats drin und spielt ohne sdm. er hat keinen einzigen siegel des befehls crit im gesamten video. nochmal: auch wenn du hier mich schon namentlich erwähnst, dann komm bitte ins ts mit mir und wir können dann schön theorie craften und alles durchrechnen, die einladung steht.

dir ist wohl nicht ganz bewusst, das ich mit flask auf weit über 350 spdmg komme, ohne trinkets zu zünden, der paladin in diesem video ist wirklich grottenequiped. Desweiteren ist die pvp rank14 waffe eine nicht so gute wahl für einen retri paladin. Ich kann dir gerne dann auch vorrechnen, dass der legendäre kolben lange das beste ist.
hier mal ein full t2.5 equipter retri pala zu 1.12.1 im vergleich 
https://www.youtube.com/watch?v=f6SPpRZmuBU
mit t2.5 verliert der pala ca 70 spdmg jedoch bekommt er jede menge crit dazu was dieses set so gut macht, denn dadurch hat man rache häufiger.

ich finde es wirklich ein unding möchte ich hier noch für die devs anmerken, hier ohne jegliche beweise, formeln, blue posts etc so einen thread zu eröffnen.
Danke für die Aufmerksamkeit

**Comment by Sabbaer** [comment]
anbei noch ein video von mir in bwl ist nen bisschen her, dort hab ich noch ashkandi an und kein drakefang etc. full t2 spelldmg schon vorhanden. kurz vorm pull zeig ich das gear

**Comment by bugreportor** [comment]
"deine berechnung muss dann aber falsch sein. "
Ok. Bitte erklären und nachvollziehbar widerlegen.

"Dazu erbitte ich bitte screenshots in denen dies der fall ist, denn das hab ich bis jetzt noch nie erlebt.
Du solltest bedenken, dass wir paladine häufig das doppelschlagtrinket anhaben"
Selbst mit einem Screenshot vom SCT+Kampflog könnte man daran nicht eindeutig erkennen, von was die zusätzlichen Schläge und Procs ausgelöst wurden. Im Kampflog und im SCT- mein lieber Paladin-Freund - steht nicht von was die Whitehits ausgelöst werden. Mit Gm-Befehlen und dem Ring of critical testing kann man das aber leicht rekonstruieren. 

"deine "Vermutung" ist nicht richtig! die berechnungen werden ganz normal ausgeführt. habe wochen damit verbracht alles zu überprüfen und nachzurechnen. Ich biete dir gerne an mit mir ins ts zu kommen und ich rechne dir alles bis ins kleinste detail vor."
Ok und welche Formel ist deiner Meinung nach die "normale" Rechnung?
Waffenschaden * 0,7 + SPD-Koeffizient * 1.15 und 
1,15 (Rache) + 0,1 (Aura) + 1 (Crit) = 2,25 wäre korrekt.
Du musst mir nichts "vorrechnen". Das hier ist kein Verkaufsgespräch.
Weder ich noch einer der Devs ist dein Kunde dem du den buggy Paladin als funktionierend verkaufen musst. Meine Rechnung hier ist leicht nachzuvollziehen, fußt auf einer unanfechtbaren Quelle und vorallendingen ist sie korrekt.

"der paladin in dem video hat bei keinem einzigen seiner schläge heilig aura an. er hat 137 spdmg an.
Er hat keine buffmats drin und spielt ohne sdm. er hat keinen einzigen siegel des befehls crit im gesamten video."
Das ist schlichtweg nicht wahr. Sowohl in Kirill II aber auch in Kirill I gibt es zahlreiche Stellen wo Kirill mit Siegel des Befehls+Rache+Aura crittet. 
Im verlinkten Youtube-video z.b.:
5:14 SdB+Rache+Aura 883 Crit.
6:04 SdB+Rache+SdM+Aura+Stun 1002 Crit
Wenn du dir die verlinkten Videos wirklich angeschaut hättest wüsstest du auch, dass der höchste Crit in beiden Videos (Kirill I) mit SdB ( Bei Rache+SdM+Aura+CrusaderProc+Stun) bei 1273 Dmg liegt. 

"Desweiteren ist die pvp rank14 waffe eine nicht so gute wahl für einen retri paladin."
Das hat zwar überhaupt nichts mit diesem Bugreport zu tun, aber um den Zusammenhang herzustellen:
base_weapon_damage + weapon_speed * Attack Power / 14
Mit gutem Gear sind fullbuffed 1000AP (ohne Waffe) locker drin, eher noch mehr. 
Raggihammer: 297,5 + (3.7 * 1024AP / 14) = 568 durschnittlicher Whitehit-DMG
R14 Claymore: 294 + (3.8 * 1052 AP / 14) = 579,5 durschnittlicher Whitehit-DMG
Heißt, dass man mit der R14-Waffe sogar höhere SdB-Crits erreichen kann als mit Sulfuras. Und da white hits keiner Normalisierung unterlaufen profitiert die R14 Waffe bei steigender AP auch mehr als Sulfuras.

"ich finde es wirklich ein unding möchte ich hier noch für die devs anmerken, hier ohne jegliche beweise, formeln, blue posts etc so einen thread zu eröffnen."
Bluepost-link ist oben zu finden. Die Beweise sind in Form von Videos erbracht worden und die Formel stammen aus der Datenbank mit doppelcheck auf wowwiki.

"ich vermute das ist mal eher wieder ein hate den sabbaer thread, deswegen auch meine namentliche erwähnung hier."
Auch wenn Dein Name hier Erwähnung gefunden hat, geht es nicht um Dich.
Und dass du schon für 2k gecrittet haben sollst, hast du selbst im Say-Chat vor IF beim duellieren gesagt.

**Comment by Nobugsanymore** [comment]
"deine berechnung muss dann aber falsch sein. "
Ok. Bitte erklären und nachvollziehbar widerlegen.

"Dazu erbitte ich bitte screenshots in denen dies der fall ist, denn das hab ich bis jetzt noch nie erlebt.
Du solltest bedenken, dass wir paladine häufig das doppelschlagtrinket anhaben"
Selbst mit einem Screenshot vom SCT+Kampflog könnte man daran nicht eindeutig erkennen, von was die zusätzlichen Schläge und Procs ausgelöst wurden. Im Kampflog und im SCT- mein lieber Paladin-Freund - steht nicht von was die Whitehits ausgelöst werden. Mit Gm-Befehlen und dem Ring of critical testing kann man das aber leicht rekonstruieren. 

"deine "Vermutung" ist nicht richtig! die berechnungen werden ganz normal ausgeführt. habe wochen damit verbracht alles zu überprüfen und nachzurechnen. Ich biete dir gerne an mit mir ins ts zu kommen und ich rechne dir alles bis ins kleinste detail vor."
Ok und welche Formel ist deiner Meinung nach die "normale" Rechnung?
Waffenschaden * 0,7 + SPD-Koeffizient * 1.15 und 
1,15 (Rache) + 0,1 (Aura) + 1 (Crit) = 2,25 wäre korrekt.
Du musst mir nichts "vorrechnen". Das hier ist kein Verkaufsgespräch.
Weder ich noch einer der Devs ist dein Kunde dem du den buggy Paladin als funktionierend verkaufen musst. Meine Rechnung hier ist leicht nachzuvollziehen, fußt auf einer unanfechtbaren Quelle und vorallendingen ist sie korrekt.

"der paladin in dem video hat bei keinem einzigen seiner schläge heilig aura an. er hat 137 spdmg an.
Er hat keine buffmats drin und spielt ohne sdm. er hat keinen einzigen siegel des befehls crit im gesamten video."
Das ist schlichtweg nicht wahr. Sowohl in Kirill II aber auch in Kirill I gibt es zahlreiche Stellen wo Kirill mit Siegel des Befehls+Rache+Aura crittet. 
Im verlinkten Youtube-video z.b.:
5:14 SdB+Rache+Aura 883 Crit.
6:04 SdB+Rache+SdM+Aura+Stun 1002 Crit
Wenn du dir die verlinkten Videos wirklich angeschaut hättest wüsstest du auch, dass der höchste Crit in beiden Videos (Kirill I) mit SdB ( Bei Rache+SdM+Aura+CrusaderProc+Stun) bei 1273 Dmg liegt. 

"Desweiteren ist die pvp rank14 waffe eine nicht so gute wahl für einen retri paladin."
Das hat zwar überhaupt nichts mit diesem Bugreport zu tun, aber um den Zusammenhang herzustellen:
base_weapon_damage + weapon_speed * Attack Power / 14
Mit gutem Gear sind fullbuffed 1000AP (ohne Waffe) locker drin, eher noch mehr. 
Raggihammer: 297,5 + (3.7 * 1024AP / 14) = 568 durschnittlicher Whitehit-DMG
R14 Claymore: 294 + (3.8 * 1052 AP / 14) = 579,5 durschnittlicher Whitehit-DMG
Heißt, dass man mit der R14-Waffe sogar höhere SdB-Crits erreichen kann als mit Sulfuras. Und da white hits keiner Normalisierung unterlaufen profitiert die R14 Waffe bei steigender AP auch mehr als Sulfuras.

"ich finde es wirklich ein unding möchte ich hier noch für die devs anmerken, hier ohne jegliche beweise, formeln, blue posts etc so einen thread zu eröffnen."
Bluepost-link ist oben zu finden. Die Beweise sind in Form von Videos erbracht worden und die Formel stammen aus der Datenbank mit doppelcheck auf wowwiki.

"ich vermute das ist mal eher wieder ein hate den sabbaer thread, deswegen auch meine namentliche erwähnung hier."
Auch wenn Dein Name hier Erwähnung gefunden hat, geht es nicht um Dich.
Dass du schon für 2k gecrittet haben sollst, hast du selbst im Say-Chat vor IF beim duellieren gesagt, deßhalb habe ich das erwähnt.

**Comment by Sabbaer** [comment]
nee, ich vermute garnix. du rechnest einfach falsch und ich poste nicht nochmal den ganzen thread den ich dir schonmal gepostet habe zu dem allergleichen thema, mr. flame

**Comment by Sabbaer** [comment]
Im verlinkten Youtube-video z.b.:
5:14 SdB+Rache+Aura 883 Crit.
6:04 SdB+Rache+SdM+Aura+Stun 1002 Crit

nein, falsch, das sind richturteil crits, man beachte den cd unten in seiner leiste, das ist kein sdb progg sondern jeweils ein richturteil des befehls

**Comment by wahaxlekuke** [comment]
Könnt ihr zumindest mal _versuchen_ vor allem bei langen Texten alles etwas übersichtlicher zu posten? Hier gibts eine kurze Übersicht, wie man die Texte in den Kommentaren formatieren kann: https://guides.github.com/features/mastering-markdown/
(Ich bin mal so frei und füg mal ein paar Formatierungen bei euch hinzu.)

**Comment by Sabbaer** [comment]
ich finde es noch schlimmer, dass ich bzw der retri paladin orden nun in die beweispflicht genommen wird, jetzt sollen wir beweisen das es so stimmt

**Comment by dagochen** [comment]
Naja, er hat Blueposts und Videos und und und und....und du hast dein  "Nein, das stimmt nicht!". Ist halt schwer da den Überblick zu behalten, wenn zum Paladin alle 5 Minuten ein Beitrag hier im Bugtracker gepostet wird und jeder was anderes erzählt.

**Comment by Sabbaer** [comment]
welche blue posts? und welche videos die ich nicht wiederlegt hab? er bezieht sich auf komplett falsche informationen und denkt das RICHTURTEIL des befehls das gleiche sei wie siegel des befehls, muss ich die mechanik hier jetzt auch noch erklären?

**Comment by Sabbaer** [comment]
Ich biete desweiteren immernoch Nobugsanymore an, sich mit mir im ts zu treffen, was er ja anscheinend ablehnt, um ihm einige dinge und rechnungen näher zu bringen, aber er scheint sich anscheinend dagegen zu streuben

**Comment by Seniorash** [comment]
Durchatmen und chilln. Zu classic War es sicherlich nicht so dass man als retri im gottesschild (100% langsamer angreifen) t2 Priester umnietet oder pvp/bwl warris in 3 sek umklatscht. Dass beim pala irgendetwas nicht stimmt, meint nicht nur der Autor. So lange wie der t1 Bonus abused und nicht reportet wurde Braucht nun auch niemand erzählen man will das es hier blizzlike zugeht... wenn hier falsche Tatsachen vorgetragen werden gibt es eh keinen fix und wenn das so passt spricht doch nichts gegen eine Überprüfung? !

**Comment by Sabbaer** [comment]
yo der wurde ja jahrelang abused der t1 boni kontinuierlich und dauerhaft, hab nef gesolod oder?
was soll denn nicht stimmen ich hab bis gear mit einem orangenen item? hast du das auch? nein? dann flame bitte weiter wtf...... ey komm bitte ins ts ich rechne dir alles vor! again post über mir ist flame

**Comment by Jipptech** [comment]
Ich muss Sabbaer da recht geben...keine Ahnung warum alle so Probleme mit dem Pala haben.
Im PvP ist er nicht stärker oder schwächer als alle anderen Klassen auch. Der Unterschied liegt halt meist am Gear. 
Außerdem ist der Pala wohl die einzige Klasse die auf dem "Random" Prinzip funktioniert...
Und die Nummer, das PvP/BWL Warris in 3 Sek. umgeklatscht werden...keine ahnung, wenn du mir roter Rüstung spielst eventuell...aber sonst nicht.
Wenn du gegen einen Pala mit Reckoning Spec spielst und dich wunderst, warum er so viel "Schaden" macht, dann selbst schuld...

Und NEIN, Reckoning löst keinen SdB Procc aus, selber schon oft genug getestet...lediglich SdL, und SdR werden ausgelöst ( so wie es sein sollte) 
Jedoch hat man durch "Hand of Justice/Hand der Gerechtigkeit" Ein Trinked aus den schönen Blackrocktiefen vom Endboss die Chance, das bei diesem Procc Siegel des Befehls ausgelöst wird und somit die Chance 4 kritische Treffer zu landen...Full Raidbuffed und dazu gehören auch Ony-Buff, Liedblume und Flask könnte man dann an die 2k oder drüber kommen...aber ohne dies, habe ich auch in full T2 und mit Raggihammer im PvP noch keine 2k gelandet...

Hier gibt es irgendwie nur von Hordeseite aus Flames über die Paladine...aber um die eigenen Schamanen, die im Durchschnitt mit jedem Spell 2,5k Schaden machen und R14 Warris mit 2 Zaubern Instant umnuken kümmert sich keiner...weil...ey Blizzlike...ne is klar.

https://www.youtube.com/watch?v=YJi7bbQkK1o
https://www.youtube.com/watch?v=msOcBP24aRs
https://www.youtube.com/watch?v=a3HCYKN5W5w
https://www.youtube.com/watch?v=eurgBEEZFhM

Wenn ich das richtig sehe, machen alle mehr Schaden als Kirill in seinem Video...selbst der t0,5 Pala...aber gut, die haben zu Classic Zeiten sicher auch Hacks benutzt um ihren Schaden zu boosten.

Ich glaube einfach, du hast dich mit dem Paladin viel zu wenig beschäftigt und es nervt dich einfach nur, das du hier oft auf Spieler triffst die wissen wie man ihre Klasse spielt.

**Comment by lysop** [comment]
so erst mal ("Normal" weapon damage heißt ohne Multiplikatoren wie Zweihand-Spezialisierung und Rache.) ist schon mal falsch normal schaden ist der weiße schaden nix andres (normal /magie palas können beides gleichzeitig oder auch waffen drum steht normal dran) talente wie Zweihand-Spezialisierung und rache erhöhen den (normal waffen schaden )

nun zu deinem kirill movie der is ja nicht grad das gelbe vom ei aber ok wenn du das als grundlage nehmen möchtest bitte...
der macht 550 sdb-non krit und 1100 sdb-krit und 880 richturteil krit du schreibst du würdest mit schlechterem gear mehr sdb- krit schaden machen ( das ist möglich) ich erklär dir auch warum.

1. hat er kein sdm als buff oben das würde sein waffenschaden nochmal dick puschen und auch sein sdb proc
2. keine heiligaura an 10% mehr holy dmg (wird auf sdb gerechnet)
3. kein kreuzfahrer richturteil auf seine gegner das glaub so 155 holydmg erhöht
4. auch ein pala der nur blau oder random episch eq hat kommt dem schaden eines voll oder bis eq 
retri palas nah was krit schaden an geht.
der unterschied zu ( besser eq ) liegt mehr in der kampf dauer als am schaden (kirills gear hat einfach nur mehr hp int und krit ! )
5. warum du meinst das du dickere sdb krits machst liegt an rache (15% mehr waffenschaden +15% mehr holy schaden bei krit)  15% mehr waffenschaden heist auch mehr sdb schaden und da sdb holy schaden ist nochmal 15% aber um den vollen rache schaden zu bekommen braucht man 2 krits da der erste nicht zählt auf waffenschaden.
  z.b. erster waffehit is krit löst (rache aus 15% mehr waffe
dmg +15% mehr holy dmg ) sdb proct dazu ( bekommt nur die 15% holy weil der waffendmg
rache erst ausgelöst hat 2- hit waffeschaden bekommt 15% waffendmg angerechnet da rache noch aktiv ist, proct dazu noch sdb und sogar noch kritisch is der schaden weit über( 1100 sdb) die kirill macht (auch mit deiner waffe)
6. da kirill in seinem movie rache nicht oben halten kann bis sein nächster schlag kommt macht er auch nur einfachen schaden ohne bonus ( weil er sich heilen muss oder ihm rache runter gemacht wird)
7. da sabbaer und ich z.b bis gear tragen sag ich dir meine werte und wenn mir dann erzählst das du mehr machen würdest als ich dann stimmt was bei dir nicht und nicht an der klasse an sich
ohne buffs: sdb non krit ca. 600 und krit 1200 richturteil im stun ca.1000
mit sdm + aura: sdb non krit ca. 700 und krit 1400 "                 "
das sind unsre werte ohne rache bonus würde kirill das in seinem movie hinbekommen wäre sein schaden höher
8. sabbaer hat dir mehrfach movies gepostet das sogar 2k+ sdb krits möglich sind du hast dir halt das schlechteste movie raus gesucht, nicht um einen bug zu reporten sondern einen nerv der palas zu erzwingen und zeigst auch noch gleichzeitig das du von der klasse paladin keine ahnung hast .

ich bitte um close und um seine weiteren beiträge (report was palas an geht nicht zu beachten da er oder ihr wie auch immer weder erfahrung noch ahnung von der klasse habt )

mfg silbaer

**Comment by Nobugsanymore** [comment]
Habe ausversehen den Falschen Datenbank-Eintrag verlinkt. http://datenbank.welli-it.de/?spell=20059 ist korrekt

**Comment by Karmanaz** [comment]
Offtopic - auch wenn es eigentlich nicht hier rein gehört, so wie viele der Posts.

Zitat Sabbaer: "yo der wurde ja jahrelang abused der t1 boni kontinuierlich und dauerhaft, hab nef gesolod oder?
was soll denn nicht stimmen ich hab bis gear mit einem orangenen item? hast du das auch? nein? dann flame bitte weiter wtf...... ey komm bitte ins ts ich rechne dir alles vor!"

@Sabbaer 

Alleine dieser Abschnitt beweist doch, Zitat "einfach armselig, man kann mit der horde und poke nicht diskutieren", dass die einzige Person die in Bugs die den Pala betreffen nicht ordentlich diskutieren kann, du bist. Du begibst dich sofort in Flame und Polemik. Es ist vollkommen egal ob du 3 Jahre in deinen Char gesteckt hast, ob du BiS bist und andere nicht oder aber ob der Lorenz der allertollste und beste Paladin EU ist. Die Klasse Paladin hat genau so viele Bugs wie viele andere Klassen auch, nur das es bei euch scheinbar oft zum Vorteil der Klasse ist und nicht zum Nachteil. 

Ich persönlich weiß auch nicht warum man solche Vorteile nicht selbst reportet. Das proaktive Ausnutzen der Bugs und das Erfreuen an den Vorteilen ist schlichtweg armselig und dient nur dem eigenen Ego. Das es viel mehr Spaß macht und eine Herausforderung ist den Char ordentlich gefixt zu spielen sollte doch klar sein. Ich meine ich selbst habe erst kurz hier gespielt als Schamane und bin bei gegangen und habe den T1-Bug fixen lassen, weil es keine Herausforderung war und schlichtweg nicht Classic. Und das beim Paladin ebenfalls ein T1-Bug vorlag und ihn nie jemand reportet hat spricht doch auch für sich, daher glaube ich auch nicht das einer dieser Personen dabei helfen wird, einen Fehler zu fixen, welcher eine Verschlechterung des Status Quo verspricht. Ihr werdet eher alles daran legen, solche Bugfixes zu boykottieren.

Bitte besinnt euch etwas und seht zu das der Server Classiclike wird und nicht ein Server auf dem die Klasse die ihr gerade spielt die allertollste ist, um eurem Ego einen Push zu geben.

**Comment by Frostlatte** [comment]
Schließe mich meinem Vorredner an. Die Art und Weise des Bugreports ist doch korrekt.

 Sollte er einen Denkfehler darin haben, nimm Dir doch die Zeit Saebaaer und belege es anhand von Beispielen u. Links sowie Deinen 3 Jahren Erfahrung als Paladin. Sollte Dir doch nicht schwerfallen, wenn man die PalaMechaniken und Begriffe verinnerlicht hat. 

Alle sollten bestrebt sein, fair zu spielen oder nicht. Und sollte der Bugverdacht falsch sein, wovor hast Du Angst? 
Aber wenn Du Bammel hast, dass etwas fehlerhaft geändert werden könnte, musst Du Dir die mind. die gleiche Mühe machen wie alle anderen. 
Ich erinnere mich noch gut an Beasens Kommentare alla "Stimmt nicht"...und ich habe Beleg um Beleg rausgesucht u. erklärt und argumentiert, um mir immer wieder anzuhören, dass es Quatsch sei. Ergo, wenn Du der Meinung bist, der Bugreport sei fehlerhaft, solltest Du produktiv in die Tasten hauen..und Deine Polemik weglassen. 

Beste Grüße, frost

**Comment by nerfdisplx** [comment]
Da ihr schön offtopic betreit, mache ich da mal weiter.
T1 8er Bonus wurde bereits am 04.09.13 reported. Ich denke auch mit genügend Quellen im Thread.
Wurde da etwas gemacht?

**Comment by Karmanaz** [comment]
Ich sehe dort nur, dass die selben Personen wie hier im Thread/Bugreport sich auf das übelste gewehrt haben. Und auch nicht einsehen wollten, dass man einen Bug fixen sollte.
