### ISSUE TITLE
Debuff "rausdrück/kick" Verhalten

### ISSUE THREAD

**Issue by Maxwill** [ClassicWoW/Nefarian_1.12.1_Bugtracker#604]
Hallo ,

## Welches Verhalten wird beobachtet?
Debuffs werden von Debuffs der selben Prio kategorie rausgekickt obwohl sie früher und auch schon länger in der Debuffleiste sind.

## Wie sollte es sich verhalten?  

Die Debuff sollte nur rausgekickt werden wenn er:
**a.** ausläuft
**b.** ein neuer höher priorisierter debuff drauf kommt und dadurch 16 höher priorisierte debuffs drauf sind

## Ansonsten sollte das Verhalten wie folgt aussehen:  

Jede Prio Kateorie ist ein eigener Stack/Stapel.
**bsp. Stack1 ( high prio) , Stack2 (mid Prio) , Stack3(low prio)**

#### logik der stacks intern: 
neue debuffs werden auf den jeweiligen stapel gelegt.
wenn debuffs auslaufen werden sie aus dem stapel entfernt und debuffs obendrüber sacken.

#### AddDebuff logik der 3 Stacks:
**Stack3** kann nur ein debuff hinzugefügt werden wenn **((Stack1.length+Stack2.length)<16 and (Stack1.length+Stack2.length+Stack3.length)<16) = true**

**Stack2** kann nur ein debuff hinzugefügt werden wenn **(Stack1.length<16 and (Stack1.length+Stack2.length)<16) = true**

**Stack1** kann nur ein debuff hinzugefügt werden wenn **(Stack1.length<16) = true**

#### kickDebuff logik der 3 Stacks:
*(logik die für das rausdrücken niedriger priorisierter buffs zuständig ist)*
**Reinfolge der überprüfung ist zubeachten!**

**Stack1** kann keinen debuff kicken da es keine höhere prio gibt die ihn rausdrücken könnte.
-> anzumerken , in der addDebuff logik wurde bereits ausgeschlossen das es nicht mehr als 16 debuffs auf den stack sein können.

**Stack2**  der oberste debuff wird gelöscht wenn in Stack1 ein neuer debuff hinzu kommt und dadurch **(Stack1.length + Stack2.length >16) = true** gibt, da werden die debuffes von oben vom Stack2 entfernt bis **(Stack1.length + Stack2.length > 16) = false**.

**Stack3**  der oberste debuff wird gelöscht wenn in Stack1 oder in Stack2 ein neuer debuff hinzu kommt und dadurch **(Stack1.length + Stack2.length+Stack3.lenght >16) = true** gibt, da werden die debuffes von oben vom Stack3 entfernt bis **(Stack1.length + Stack2.length+Stack3.lenght > 16) = false**.

## Schritte zur Reproduzierung :

Mob mit Debuffs zu dotten und kucken wie sich die leiste verhält.

Gruß Maxwill

**Comment by wahaxlekuke** [comment]
Hast du dafür irgendwelche Quellen? Ich denke eher, so wie das grade auf unserem Server läuft, ist das korrekt.
