### ISSUE TITLE
Erzspawns

### ISSUE THREAD

**Issue by QuelSera** [ClassicWoW/Nefarian_1.12.1_Bugtracker#606]
Mal abgesehen von dem Problem mit zu wenig Dunkeleisen-/reichen Thoriumvorkommen, das Tiberiusll bereits angesprochen hat, für das ich aber auch bisher keine Beweise finden konnte (die einzige relativ genaue Map hierzu macht keinen Unterschied zwischen der Art der Vorkommen), funktionieren die Spawns von Silber, Gold und Echtsilber auf diesem Server falsch.
Diese Erze haben keine eigenen Spawnpunkte, sondern sind Rarespawns von Zinn, Eisen, Mithril und Thorium.
(Könnte mit Kräutern ähnlich sein, hatte nie Kräuterchars über Stufe 20)

Quelle:
http://www.wowwiki.com/Silver_Ore
http://www.wowwiki.com/Gold_Ore
http://www.wowwiki.com/Truesilver_Ore

Edit: das schleimverkrustete Vorkommen an der Südküste von Stranglethorn gehört da nicht hin, die spawnen ausschließlich in der Nähe von Silithiden.

**Comment by Larnak1** [comment]
Ich finde die Quellen nicht überzeugend. Dort steht nicht explizit, dass die Spawnpunkte geteilt werden, sondern nur, dass die Vorkommen dort auftauchen, wo auch die normalen Erze zu finden sind. Das klingt für mich eher nach "in der gleichen Region" denn nach geteilten Spawns.

Außerdem sind die Quellen von 2012, 2014 und 2013. Für diesen Server sollten Quellen nach Möglichkeit nicht älter als 2006 sein, in jedem Fall nicht älter als 2010, da mit Cataclysm enorm viel im Classic-Bereich geändert wurde.

Wäre außerdem gut, wenn du dich an die Formatvorlage halten könntest :)
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by ErnisKommentar** [comment]
looool. Ich finde die Quellen nicht überzeugend. Seid ihr Hansens, Alter. Ich hab das Spiel 10 Jahre gespielt. Und meine Zeit war die bis WotLK-Zeit. Ich muss euch gar nichts beweisen, ihr Kasper. Natürlich funktionieren die Erze nicht richtig. Ist mir aber auch relativ egal, aber man könnte natürlich wenn man mal mit Leuten zusammenarbeiten würde, die offensichtlich mehr Ahnung von WoW haben als ihr, zumindest Zustände schaffen, die mehr mit Klassik zu tun haben als der aktuelle Zustand, was zum Beispiel die Verteildung der Handwerksmaterialien angeht. Würgetang darf beispielsweise nicht am Strand rumliegen, der muss im Wasser sein. Aber ich nehme an, dass muss man euch auch beweisen, weil ihr Kasper noch nie WoW gespielt habt, aber aus irgendnen religiösmotivierten Grund nen Privatserver dazu anbietet, deren zahlreiche Datenbankfehler ihr aber nicht mal mit der Kneifzange anrührt, weil ihr entweder nicht wollt oder nicht könnt.
