### ISSUE TITLE
Arkaner Schuss kann nicht criten

### ISSUE THREAD

**Issue by Opius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#614]
Welches Verhalten wird beobachtet? 
Seid dem letzten oder vorletzen Patch kann der Arkane Schuss beim Jäger nicht mehr criten.

Wie sollte es sich verhalten?
Sollte criten können! In ganz BWL und anschließende Duelle critete er nicht einmal.

Zusätzliche Information (Screenshot)
Hier ein Screenshot der es zeigt: https://www.dropbox.com/s/4xb0mplhc2ur7gt/WoWScrnShot_040215_024932.tga?dl=0

**Comment by dagochen** [comment]
Gleiche wie beim Pala Siegel/Richturteil
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/612
