### ISSUE TITLE
Psychic Scream bricht oft zu schnell.

### ISSUE THREAD

**Issue by dontworrywegotthisundercover** [ClassicWoW/Nefarian_1.12.1_Bugtracker#615]
**Was wird beobachtet:**
Psychic_Scream wird signifikant zu oft und zu schnell durch Schaden gebrochen. Schon 2 DoT Ticks bzw. Mind Flay (Pain) lässt Targets aus dem Fear kommen. Ich bitte deswegen um Anpassung. 

**Schritte zur Reproduzierung:**
Jemanden fearen, DoT setzen, Mindflay und Gedankenschlag casten.

**Wie sollte es sich verhalten:**
Stattdessen sollte bei DoT Dmg (Mindflay und Shadow Word; Pain), die Chance den CC zu brechen marginal sein. Selbst bei Gedankenschlag kann es passieren, dass mit einer bestimmten Chance, der im Fear stehende im CC bleibt.  

**Zusätzliche Infos:**
Ähnliches Verhalten wie beim Drohruf auf nicht Krieger Ziele.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/514

_"At the same time, it makes 5 other enemies within 10 yards to run away randomly, these enemies' fear is not so easy to break as the target's.. "_

**Quellen:**

http://www.wowwiki.com/Psychic_Scream

**Video:**

Seksi - The Beginning  -  https://www.youtube.com/watch?v=1_OJNHjQ7o4
7:07 - 7:14 + 10:49 - 11:00

https://youtu.be/1_OJNHjQ7o4?t=7m7s
https://youtu.be/1_OJNHjQ7o4?t=10m56s

Beckon  -  https://www.youtube.com/watch?v=Rd7oamCTRf4
11:04 - 11:13

https://youtu.be/Rd7oamCTRf4?t=11m5s

**Patch:**

Patch 1.11.0
http://us.battle.net/wow/en/game/patch-notes/1-11-0

_Fear: The calculations to determine if Fear effects should break due to receiving damage have been changed. The old calculation used the base damage of the ability. The new calculation uses the final amount of damage dealt, after all modifiers. In addition, the chance for a damage over time spell to break Fear is now significantly lower. Note that Fear continues to be roughly three times as likely to break on player targets as on non-player targets. In addition, Intimidating Shout now follows that player versus non-player distinction, while previously it did not._

Datenbank: 
Rank 1 http://datenbank.welli-it.de/?spell=8122
Rank 2 http://datenbank.welli-it.de/?spell=8124
Rank 3 http://datenbank.welli-it.de/?spell=10888
Rank 4 http://datenbank.welli-it.de/?spell=10890

Danke fürs draufschauen.

**Comment by Nobugsanymore** [comment]
>Ähnliches Verhalten wie beim Drohruf
Ja habe ich auch schon festgestellt. Wie früher  - vor dem Fix - bricht der Feareffect wieder sofort wenn das gefearte Ziel schaden erleidet. (Der minimalste blutungstick von 1 Schaden reicht aus).

**Comment by Haudraufinix** [comment]
Fear sollte ab einem gewissen Schadenswert eine höhere Brechchance besitzen, findet ihr zahlen dazu? einfach nach "Gefühl" fixen ist etwas schwer ;)

**Comment by dontworrywegotthisundercover** [comment]
Ich habe nun mehrere Videoquellen ausgewertet und auch ausgetestet wie es hier aufm Server sich verhält. Leider kann ich kein Open Office Tabellen Dokument hier hochladen.

Der durchschnittliche erlittene Schaden bevor Fear des Priesters bricht ist dabei  ca. 1100 und hier auf dem Server war es ca. 450.
 
Zusätzlich habe ich zum Thema herausgefunden, dass bei Schadenabsorbtion (z.B. Machtwort: Schild, Schattenschutz) der Fearabbruch nicht stattfinden sollte, was defintiv hier nicht der Fall ist. 

http://www.wowwiki.com/Patch_4.3.0

_"Spells which have an effect broken by taking damage past a threshold (Entangling Roots, Fear, Frost Nova, etc.) now count damage that was prevented by damage absorbs or other damage reducing effects."_

**Comment by dontworrywegotthisundercover** [comment]
![fear-page-001](https://cloud.githubusercontent.com/assets/11767716/7127545/1d753b64-e246-11e4-84bd-17ce332c7026.jpg)
![fear-page-002](https://cloud.githubusercontent.com/assets/11767716/7127547/25381542-e246-11e4-880a-31257cc6c990.jpg)
![fear-page-003](https://cloud.githubusercontent.com/assets/11767716/7127548/2e302694-e246-11e4-9569-5be6b447b945.jpg)

**Comment by dontworrywegotthisundercover** [comment]
Die verschiedenen zusätzlichen Videoquellen oben auftretender Reihenfolge:
 
https://www.youtube.com/watch?v=kuob-3QGltA
https://www.youtube.com/watch?v=tyarUUYeJ-E
https://www.youtube.com/watch?v=zUZ0G-EnRTs
https://www.youtube.com/watch?v=MH7sOcSaj-Q
https://www.youtube.com/watch?v=889fJ4ymZqg
https://www.youtube.com/watch?v=hy_UjZKPOoE
https://www.youtube.com/watch?v=a4BzjAoL3-Q
https://www.youtube.com/watch?v=UsZT1DBb4Sw
https://www.youtube.com/watch?v=9SYsJzGK06o
https://www.youtube.com/watch?v=tXgsBdLQfvU
https://www.youtube.com/watch?v=hnWby-ruZ4k
https://www.youtube.com/watch?v=RV5rk80Ud4E

**Comment by dontworrywegotthisundercover** [comment]
Zusätzliche Quelle 2: POV eines Feraldruiden vom 17. März 2006, der Autor selbst gibt das am Anfang des Videos an.

Cat drood is not meow lol (Vanilla WoW Feral Druid PvP) - https://youtu.be/PFMFiGPS4YQ?t=6m2s
6:04 - 6:12  Autoattacks, DoT`s, Vipernbiss brechen den Fear nicht.

**Comment by wahaxlekuke** [comment]
Das Problem war, dass der Schaden über mehrere Ticks deutlich häufiger den Fear unterbrochen hat, als wenn man viel Schaden auf einmal bekommen hat. z.B. 100 Schaden gegen einen Stufe 20 Spieler hatten eine Chance von 28,57% den Fear zu brechen, wenn man allerdings 10 x 10 Schaden auf dem Ziel verursacht hat, lag die Chance bei 82,75%. 

Mit einer neuen Formel sollte nur noch der Gesamtschaden beeinflussen, wie hoch die Chance fürs Unterbrechen ist und nicht auf wie viele Ticks der Schaden aufgeteilt wird.
