### ISSUE TITLE
Gnomentodesstrahl (Gnomish Death Ray)

### ISSUE THREAD

**Issue by Sagittarius1337** [ClassicWoW/Nefarian_1.12.1_Bugtracker#618]
Quelle: Zalgradis paladin pvp - https://www.youtube.com/watch?v=4fDpvS32s1M 

Der Schaden der vom Gnomentodesstrahl ausgeht, entspricht nicht dem Schaden welcher im Video zu sehen ist. Dies wird durch folgende Szenenausschnitte belegt: 

Bsp 1:
Ab 3:08 Min - https://www.youtube.com/watch?v=4fDpvS32s1M
Dot tickt 4x: 1x 150, 1x 149, 1x 150 und 1x 154 – Schaden gesamt: 603 Schaden
Gnomentodesstrahl trifft das Ziel für 1047 Schadenspunkte

Bsp 2:
Ab 9:53 Min - https://www.youtube.com/watch?v=4fDpvS32s1M
Dot tickt 4x: 1x 133, 1x 134, 1x 133 und 1x 133 – Schaden gesamt: 533 Schaden
Gnomentodesstrahl trifft das Ziel für 934 Schadenspunkte

Bsp 3:
Ab 3:34 Min - https://www.youtube.com/watch?v=UaODHMVloxk
Dot tickt 4x: 1x 100, 1x 100, 1x 100 und (1x 100) – Schaden gesamt: 400 Schaden
Gnomentodesstrahl trifft das Ziel für 704 Schadenspunkte

Bsp 4:
Ab 0:22 Min - https://www.youtube.com/watch?v=FD01NG2-HVo
Dot tickt 4x: 1x 122, 1x 123, 1x 122 und 1x 122 – Schaden gesamt: 489 Schaden
Gnomentodesstrahl trifft das Ziel für 853 Schadenspunkte

Bsp 5:
Ab 4:55 Min - https://www.youtube.com/watch?v=ZM2q7Uf1YtM
Dot tickt 4x: 1x 286, 1x 287, 1x 286 und 1x 286 – Schaden gesamt: 1145 Schaden
Gnomentodesstrahl trifft das Ziel für 2006 Schadenspunkte

Es können noch weitere Beispiele als Beweis für den Schaden aus den verschiedenen Parts des Videos gewonnen werden.
Wie man anhand der Beispiele sieht, wird der gesamte Schaden der durch Aktivierung von „Gnomentodesstrahl“ zusammenkommt mit dem Wert ~1,75 multipliziert.

Tests mit Airmail auf unserem Server ergeben allerdings einen anderen Wert.

1. Dot tickt 4x: 4x 247 – Schaden gesamt: 988 Schaden
Gnomentodesstrahl trifft das Ziel für 2348 Schadenspunkte
2. Dot tickt 4x: 4x 233 – Schaden gesamt: 932 Schaden
Gnomentodesstrahl trifft das Ziel für 2187 Schadenspunkte
3. Dot tickt 4x: 4x 235 – Schaden gesamt: 940 Schaden
Gnomentodesstrahl trifft das Ziel für 2212 Schadenspunkte
4. Dot tickt 4x: 4x 157 – Schaden gesamt: 628 Schaden
Gnomentodesstrahl trifft das Ziel für 1273 Schadenspunkte
5. Dot tickt 4x: 4x 156 – Schaden gesamt: 624 Schaden
Gnomentodesstrahl trifft das Ziel für 1260 Schadenspunkte

Wie man anhand der Beispiele sieht, wird der gesamte Schaden der durch Aktivierung von „Gnomentodesstrahl“ zusammenkommt mit dem Wert ~2,35 bei den hohen Werten(1-3) multipliziert! Bei den kleineren Werten hingegen wird alles mit ~2,0 multipliziert.

Wir haben also 2 Probleme: 
1. Die Werte zum generieren des Schadens der auf den Spieler geleitet wird, werden mit der falschen Zahl multipliziert.
2. Zudem wird die Zahl die den eintreffenden Schaden generiert höher, sobald der Spieler durch den Dot mehr Schaden erleidet (vgl. 1-3 u 4-5).

Ich hoffe ihr könnt damit etwas anfangen.
Sagittarius

**Comment by dagochen** [comment]
Danke für die vielen Daten. Daran kann ich ne gute Formel bauen ;) Die aktuelle Formel zur Berechnung ist linear, was offensichtlich nicht ganz korrekt ist. Werde ich nachher gleich die Formel berechnen und anpassen, danke!

**Comment by dagochen** [comment]
Linear ist richtig, allerdings mit einer abgewandelten und leicht schwächeren Steigung. Pro erlittenem Schadenspunkt ergibt sich aus den Werten die hier gepostet wurden nämlich folgende Formel:

Schadenstick * 7 = Schadensburst
