### ISSUE TITLE
seal of command / rache sowie keine spelldmg skallierung auf seal of command

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#619]
Welches Verhalten wird beobachtet?
zu wenig schaden durch siegel des befehls progs im zusammenhang mit rache
Wie sollte es sich verhalten?
sdb sollte die auswirkungen von rache vollständig angerechnet bekommen

Schritte zur Reproduzierung und Zusätzliche Informationen:

Rache:
gives you a 15% bonus to physical and HOLY DAMAGE you deal for 8 seconds after dealing a critical strike from a weapon swing, spell or ability.

ich mache mit über 100 spelldmg mehr, weniger bis gleich viel schaden bei sdb progs als kirill in dem video https://www.youtube.com/watch?v=r8ZUqTlUq7U (ca.500 heilig schaden mit einem progg), obwohl ich heilig aura(10%mehr heilig schaden) + rache oben habe und kirill in dem video nicht. Wie ist dies zu erklären. er kämpft gegen pvp ziele die 7% weniger schaden bekommen und ich habe gegen npcs stufe 58-60 getestet. 

https://www.youtube.com/watch?v=VEs9coe5XRg
laut meinen berechnungen wie es jetzt hier auf dem server ist, ist mit dem gear, das  in diesem video gepostet ist, der Schaden den er macht gar nicht möglich. min 0.58 ist sein gear zu sehen. 163 spellpower, ich habe 232 +150 durch flask an.
Es geht hierbei nicht um die diskussion ob t2.5 mehr schaden macht, denn es hat viel höhere crit werte, es geht hierbei um den max dmg den ein siegel des befehls prog auslösen kann bzw könnte.

https://www.youtube.com/watch?v=rXNWvytYbyo
das ist der selbe paladin nur das video ist etwas langsamer, so kann man besser die siegel des befehl progs sehen bei min 1.53 macht er einen 1869 white hit gefolgt von einem 2100er siegel des befehls prog.
er hat in diesem video keine spelldamage flask aktiviert. nach welcher berechnung ist mit der waffe http://datenbank.welli-it.de/?item=21134 und dem gear was er anhat dieser hit möglich?

Auch möchte ich dann fragen wozu bei rache explizit noch einmal dran steht, dass es auch heilig schaden erhöht und meele schaden?
Das würde ja bedeuten, dass wenn rache nach dem ersten schlag schon oben ist, müsste ja beim nächsten schlag rache mit auf sdb gerechnet werden, oder nicht? denn es erhöht ja den heilig schaden? es wird aber nicht dazu berechnet.
auch stimmt etwas mit der spelldamage skallierung nicht. Wenn ich ein zaubermacht trinket für 200 spdmg anmache verändert sich der schaden nicht, soweit ich das jetzt nach 1 stunde mobbsklopfen feststellen konnte

Links aus unserer Datenbank
http://datenbank.welli-it.de/?spell=20947

**Comment by SirBeansen** [comment]
mein gott es heißt PROC und nicht progg....

**Comment by Seniorash** [comment]
Die antworten auf deine fragen aus dem letzten Absatz sollten der eigentliche Inhalt eines Bugreports sein und nicht eine Anhäufung von Videos und ein einfacher Vergleich der Schadenszahlen.
so wie das da steht wird einfach nur eine umkehrung des fixes von gestern vorgestern verlangt.

**Comment by Sabbaer** [comment]
anbei https://vanilla-twinhead.twinstar.cz/?issue=2855
da taucht ein alter bekannter auf, lharts
da sind die gleichen argumente, sogar das gleiche video gepostet, und ihm wurde das gegenteil bewiesen.

**Comment by Haudraufinix** [comment]
* After a small discussion about it with Zarquon I reread the tooltip and it states "70% of normal weapon damage". This implies that the damage to calculate the Seal is always the damage range from your melee swings without additional multipliers like Two-Hand Specialization odr Vengeance.
If it was otherwise Vengeance would affect the Seal proc twice. *

* 
My first guess would be incorrect scaling with spelldamage.
The judgment of the Seal should scale with spell damage, but the proc should not. *

Heisst doch eigendlich, dass Rache den schaden von BoC NICHT nochmal erhöht, weil sie duch erhöhten Waffenschaden schon Einfluss in die Rechnung hat und der Procc sollte NICHT mit spelldmg skallieren

**Comment by Sabbaer** [comment]
weiterlesen

**Comment by Haudraufinix** [comment]
Um das mal in ins richtige Licht zu rücken:
*but you didn't post any proofs of the statement, you only explained the problem. Therefore a confirmation is required that it is indeed wrong, before a fix will be applied.*
Du willst also beweisen, dass du zu wenig Schaden machst, weil auf einem anderen Privatserver ein anderer Report nicht genügend war, ist das richtig?

**Comment by Sabbaer** [comment]
nein, ich will beweisen, dass die gestrigen änderungen aufgrund mangelnder beweise zurückgenommen werden müssen, denn es war davor anders und wurde geändert aufgrund eines fehlerhaften buggtracker beitrags

**Comment by Ilikegyoza** [comment]
Und wieso steht dann dieser Bugreport den du hier als Beweis verlinkst unter dem Status Fixed?

**Comment by Sabbaer** [comment]
ich vermute mal der dev oder gm hat eine weile gewartet ob noch beweise kommen und das problem als gefixed eingestuft, da es ausführlich überprüft wurde.
hier noch einmal die berechnungen und ganz wichtig auch die sdb crits aus dem ersten teil des videos!


quote: Regarding that Kirill's video, I checked the equipment on testrealm.
From previous tests we can conclude, that Spelldamage bonuses for SoC, Vengeance, Sanctity Aura and Twohanded Weapon Specialization all work as intended.

According to the end of his video, it's full pvp set + GM Claymore + hand of justice + Ruins of AQ ring + Don Rodrigo's Band + Onyxia Tooth Pendant + Windshear Cape + Zandalar belt and wrist.
The enchants affecting his damage are +4 all stats on chest, +30 AP on shoulders (ZG enchant), +9 STR on wrist, others are resistances/stamina/agility.

According to the comment on his warcraftmovie entry, he uses a 11/9/31 build, which definitely uses twohanded weapon specialization.

In the video at 6:06, he crits the hunter for 835 melee (vengeance is up), then hits for 535 noncrit SoC damage. With Sanctity Aura and Blessing of Might as the only buffs.
With his gear, Blessing of Might, Sanctity Aura and Vengeance my charscreen shows: 622-767.
min: 622 * 0,7 = 435,4; 435,4 * 1,25 = 544,25
max: 767 * 0,7 = 543,75; 543,75 * 1,25 = 679,6875
I did a short testing, soc procs with venge up ranging from 457 to 665.
Notice that my low end damage was way below the calculated minimal damage. However my max damage did not exceed the calculated maximum damage.
And Kirill's SoC damage was also well within the calculation parameters.

Note that all the tests were performed on the lvl 63 Felguard Elite in Blasted Lands and all the numbers are non-crits unless mentioned elsewhere. Critical damage modifier of Seal of Command is x2.

PS: Also notice Kirill's other hits and crits in the first part of the same video https://www.youtube.com/watch?feature=player_detailpage&v=6oiIy5j5oUA#t=130
1142 SoC crit (1142/2=571), followed by a 601 SoC hit, both with BoM+Aura+Venge. Later here he hits SoC into a warrior for 640 without Blessing of Might.

**Comment by Haudraufinix** [comment]
Okey gut, nun wissen wir, wie die Schadenszahlen auf Kronos sind, Sind hier Kronos GM's, die das bitte auf ihrem Server fixen könnten?

Scherz beiseite:
Du hast KEINE Wiki DMG formel, leitest aus dem Video selber keine ab... Rechne doch mal bitte zurück, WIE es denn bitte Skallieren soll. 1000% Spelldmg Scaling pro hit, 1%? man kann nur raten. Selbst wenns die Devs fixen wollen, wissen sie gar nicht, wie hoch denn das Scaling korrekterweise ist!

**Comment by Sabbaer** [comment]
20% skallierung auf +spdmg 29% auf + holy dmg

hier die berechnungen:
eine berechnung mit einer 784schlag berechnung:
784 * 0,7 = 548,8; 
548,8 + 27,4 = 576,2 sdb basis dmg

fall A: alles multipliziert: 1,15 (venge) * 1,1 (aura) * 2 (crit) = 2,53
576,2 * 2,53 = 1457,786 max soc dmg.
case B: rache+heilig additive, crit multipliziert. 1,25 * 2 = 2,5 
576,2 * 2,5 = 1440,5 max soc dmg.
case C: rache+heilig multipliziert, crit addiert. 1,265 + 1 = 2,265
576,2 * 2,265 = 1305,093
case D: everything additive. 1,15 + 0,1 + 1 = 2,25
576,2 * 2,25 = 1296,45
