### ISSUE TITLE
Partial Resist Frostbolt

### ISSUE THREAD

**Issue by Ethnie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#620]
**Frostbolt:**
http://datenbank.welli-it.de/?spell=25304

Kann zum Teil widerstanden werden

**Wie sollte es sich verhalten?**
Frostbolt ist ein binärer Zauber und sollte nicht zum Teil widerstanden werden.
er sollte treffen oder komplett widerstehen

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
http://forums.elitistjerks.com/topic/9411-spell-hit-spell-crit-and-mages/
http://www.wowwiki.com/Binary_spell
https://www.youtube.com/watch?v=K44ubcAGmII

Bei Fragen oder näheren Infos bitte melden
mfg Smoker

**Comment by SirBeansen** [comment]
War am anfang ein binärer spell wurde dann aber geändert. Schon richtig so.

Bei deinem link http://www.wowwiki.com/Binary_spell steht sogar 

"Frostbolt is no longer a Binary Spell"

**Comment by ircfelix** [comment]
Von wann sind die Quellen??

**Comment by Seniorash** [comment]
Elitistjerks aus 2006. @wowiki: guckst du den Eintrag von 2007 (älteste Version )

**Comment by wahaxlekuke** [comment]
Ich denke auch, dass das (genau wie alle Dots) ein binary-spell sein soll.
(Das wär sogar schon im letzten Patch dabei gewesen, aber ich wollte das noch etwas mehr testen)

**Comment by 0815Priester** [comment]
@Wahax anscheinend gab es bei DoTs auch Partial Resists - 
(Falls das überhaupt zur Diskussion steht) 

Post 1
http://forums.elitistjerks.com/topic/8975-tbc-beta-and-caster-mechanics-level-based-resists/

Post 14 - vorletzter Absatz
http://forums.elitistjerks.com/topic/8294-warlocks-vs-mages-regarding-hit-and-crit/

**Comment by Seniorash** [comment]
In wowwiki steht: DoTs used to be binary spells, but this was changed.
Der Eintrag ist aber aus 2007 und deine Quellen ebenfalls kurz vor dem Release von tbc. Wäre interessant zu wissen wann es denn geändert wurde. Zu tbc oder schon vorher
