### ISSUE TITLE
Verzauberkunst! Problem mit den Verschieden Ruten

### ISSUE THREAD

**Issue by Kazzard** [ClassicWoW/Nefarian_1.12.1_Bugtracker#621]
Moin,

Normalerweise kann man mit zb. Silberrute auch kleinere verzauberungen machen die zb eine Kupferrute benötigen! 
Ich hab jetzt gesehen das ich das auf euren server nicht kannl!
Obwohl der Spruch bei der Silberrute sagt "Kann auch wie jede geringere runenverzierte Rute verwendet werden"

mfg
Kazzard

**Comment by dagochen** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/421

**Comment by wahaxlekuke** [comment]
Dieser Text wurde mittlerweile entfernt, damit das richtig angezeigt wird musst du den WDB-Ordner im WoW-Verzeichnis löschen
