### ISSUE TITLE
Aura der Heiligkeit wirkt nicht auf Siegel des Befehls 

### ISSUE THREAD

**Issue by wahaxlekuke** [ClassicWoW/Nefarian_1.12.1_Bugtracker#623]
**Welches Verhalten wird beobachtet?**
Effekte, die nur Heiligschaden prozentual erhöhen (wie Aura der Heiligkeit), wirken sich nicht auf Siegel des Befehls aus.

**Wie sollte es sich verhalten?**
Da Siegel des Befehls Heiligschaden verursacht sollte der Bonus natürlich angerechnet werden.

**Zusätzliche Informationen**
10% weniger Schaden machen den Paladin offenbar _UNSPIELBAR_.

**Comment by lysop** [comment]
ist auch auch so ;)

**Comment by Sabbaer** [comment]
unspielbaer

**Comment by hraesvelgr** [comment]
- WoW Icon 16x16 Patch 1.11.0 (20-Jun-2006):

    Clarified tooltip.
    Seal of Command critical hits can now trigger Vengeance.
                Since Patch 1.11, Seal of Command proc will have approximately 0.5 second delay before the animation begins and the Holy damage is incurred, instead of having the proc occur instantly with the swing of the attack. This is considered a good change, since if the normal swing is a critical strike and Vengeance is triggered, the Seal of Command proc will be affected by the buff.


ist das auf unserem server der fall? ich glaube, das ist auch ein problem, was nicht mit beachtet wurde (bei den letzten fixes dazu) , also dass der effekt und die animation erst mit einem delay kommen, damit sie beim initiativproc von rache den effekt des buffs mit erhalten

also: critical melee hit -> SdB procc -> rache procct (durch melee) 
durch die partchchanges für 1.11 ist es aber so, dass der SdB procc sozusagen nach hinten verschoben wird. dadurch bekommt SdB beim initiativprocc eben den boost. man könnte sagen, rache hat eine höhere priorität als der SdB-procc.
