### ISSUE TITLE
Allgemein: Swingtimer Reset durch Fähigkeiten

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#624]
Hallo Leute,

manche Fähigkeiten resetten aktuell den Swingtimer nicht, obwohl sie es (vermutlich) sollten. Hierbei brauchen wir weitere Quellen in Form von Videomaterial, Klassenguides und anderem Textmaterial. Beim Kriegsdonner z.B. ist es wahrscheinlich der Fall, dass der Swingtimer zurückgesetzt werden soll, wie man in dem Video ( https://youtu.be/k8i4o08gizE?t=4m7s ) sieht. 

Bitte helft mit, Quellen zu finden! Es sind nicht ausschließlich die Krieger-Fähigkeiten betroffen!

**Comment by SirBeansen** [comment]
Slam

While Slam is without a doubt a good ability, being spell with casting-time, it resets the swing timer of your weapon......

http://www.wowwiki.com/Slam?oldid=308870

**Comment by dagochen** [comment]
https://www.youtube.com/watch?v=yBnDvOzoYnI

Kann jemand hier was erkennen?

**Comment by SirBeansen** [comment]
ja da kann man sehr gut erkennen das er nur gelben schaden macht, also keine autoattacks mehr. Außer dem ganz am anfang aber eventuell ist das HoJ proc oder sword specc.

Da braucht man nicht lange suchen. Slam war nur in der alpha/beta ohne reset des autoattacks.

**Comment by dagochen** [comment]
Aber gilt das jetzt für alle casting-time/channeled spells oder nur bestimmte? Ich bin der Meinung wir brauchen hier mehr Anhaltspunkte, um es wirklich blizzlike hinzukriegen....

**Comment by SirBeansen** [comment]
wie viele melee fähigkeiten die eine cast zeit haben gibt es denn? oO

Ich weiß nur das bei Slam die reset mechanik dazu gehört.

**Comment by cookye** [comment]
>Bitte helft mit, Quellen zu finden! Es sind nicht ausschließlich die Krieger-Fähigkeiten betroffen!

>wie viele melee fähigkeiten die eine cast zeit haben gibt es denn? oO

Ich weiß nur das bei Slam die reset mechanik dazu gehört.

Slam resettet aktuell den Swingtimer komplett und es wird kein Flurry auf den kommenden Schwung angerechnet. D.h. bei einer 3.4-Waffe wartet man nach dem ausführen vom geskillten Slam (1 Sekunde castzeit) noch auf die 0,48 Sekunden vom Global-CD+die komplettten 3,4 Sekunden auf den Waffenschwung. Dabei kommt es zu keiner Reduzierung durch Flurry (30% schneller angreifen).

>Es geht nicht nur um Krieger- oder Nahkampffähigkeiten.

Zur Zeit kann mann auch als Paladin "Lichtblitz" zwischen den Autohits casten, als Jäger Tierheilen, als Magier Frostblitze usw.
Ich könnte mir Vorstellen dass das in Zusammenhang zu den Update steht in dem 
 z.B. eingeführt wurde, dass Castzeiten der Jäger (Mehrfach- und Gezielter Schuss) den Melee-Swingtimer nicht zurücksetzen.
Vor dem Update:
Das Abschließen eines Casts setzt den Swingtimer immer zurück , egal wie kurz der Cast ist (bsp. 1,5 Sekunden Lichtblitz). Wird aber z.B. ein 10 Sekunden Cast bei 9,9 Sekunden abgebrochen kommt unmittelbar nach Abbruch ein Autohit. ( Swingtimer wird bei Abbruch nicht zurückgesetzt, bei Zauberunterbrechungen wie Counterspell, kick, schildschlag habe ich es nicht getestet).

**Comment by Seniorash** [comment]
Ist zwar Offtopic, aber dass Flurry nach Slam nicht angerechnet wird, stimmt nicht.

**Comment by SirBeansen** [comment]
"Zur Zeit kann mann auch als Paladin "Lichtblitz" zwischen den Autohits casten, als Jäger Tierheilen, als Magier Frostblitze usw."

Und das ist ein Fehler?

weiß nicht worauf du hinaus willst cookye

**Comment by Larnak1** [comment]
Ich erinnere mich noch, dass früher in Classic in Druiden-Diskussionen immer diskutiert wurde, dass Druiden ja viel schlechter dran wären als Schamanen, weil bei Druiden grundsätzlich alles den Swingtimer zurücksetzt. Das ist momentan nicht (mehr) der Fall, ich kann mich z.B. an einen Mob stellen und Zorn spammen und schlage zwischen den "Zorn"s immer mit dem Streitkolben zu. Funktioniert auch mit Heilende Berührung und vermutlich auch den anderen Zaubern. Quelle muss ich noch suchen ...

**Comment by Seniorash** [comment]
Hatte die Änderung auch einen Effekt auf NPCs? In letzter Zeit ist besonders bei Nef aufgefallen, dass Schattenflamme und ein Autohit gleichzeitig kommen.

**Comment by Seniorash** [comment]
Nach Zaubern mit Casttime sollte der Swing timer immer resettet werden.
http://forums.elitistjerks.com/topic/7136-nightfall-the-axe/

Das betrifft wohl Spieler und Kreaturen. Bei uns werden Tanks mit bestem Gear und allen Buffs teilweise instant umgehauen, wenn der Swingtimer z.B. während einer Schattenflamme endet. Ein schneller Fix wäre hier sehr wünschenswert.

**Comment by Haudraufinix** [comment]
* Also, if I'm right, you can't do much more than use this axe the whole time rather than healing to keep the proc up as much as it can be up. If you stop attacking, it doesn't remember how much time you have left till the next swing, it resets the swing and makes it take another 3.5 sec. 

Schamanen und Paladininstants setzen im übrigen als einzige den Swingtimer nicht zurück, Was reihenweise verstärker PvP Videos beweisen.

**Comment by Seniorash** [comment]
Bezüglich des Swingtimers von Spielern bei Zaubern: 
http://forums.elitistjerks.com/topic/7136-nightfall-the-axe/
Posted 03 July 2006 - 06:25 AM
Paladins/Shamans don't get their swing timer reset on instant cast spells. However, it is reset after casting any spell that is not instant. 
 
https://www.youtube.com/watch?v=mxUlBoTWtnQ
04:49 ist der Heal durch. 04:53 kommt der erste Autohit, obwohl er bereits vorher am Gegner steht.

https://www.youtube.com/watch?v=U64cTFNjHyg
04:56 selbe Geschichte bei Schamanen.

**Comment by Haudraufinix** [comment]
Taurenfähigkeit resettet den casttimer meines wissens nach auch.
Der Hunter ist im übrigen eine Ausnahme weil es kein "Zauber" ist sondern eine Ability ähnlich wie finsterer Stoss. Wieso sie's verhängt haben Slam vom Krieger auch so zu scripten weis ich bis heute nicht :D
