### ISSUE TITLE
Gnomischer Alarm O Bot - Keine Aufdeckungs Impulse / Nicht Lootbar

### ISSUE THREAD

**Issue by SirSoarin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#625]
Ist-Zustand:
Gnomischer Alarm O Bot sendet keine Impulse aus zum "Aufdecken" von getarnten Einheiten.
Er wirkt nur wie ein normales Angriffs Pet (Zb Gnomisches Kampfhuhn)
Er ist nicht Lootbar / Hat keinen Loottable

Sollzustand:
Gnomischer Alarm O Bot , sollte in unregelmäßigen Zeitabständen "Impulse"  , die wie Arkane Explosion aussehen von sich geben , der getarnte Gegner aufdeckt (Schurken , Katzen Druide etc.)
-----------------------------------------------
- Zusatz, wofür ich noch keine Quelle habe , aber aus alten Kommentaren gelesen und auch von retail Erinnerung.

Auserdem war es möglich , nach Zerstörung oder ablauf der 10 Minuten ihn zu Looten und einen Teil seiner Materialien (Verschmorte Verkabelung zb) zurück zu erhalten.

Quelle:
Steht sogar auf dem Rezept.....
http://datenbank.welli-it.de/?item=18645
Er macht halt NIX ...nur zuhauen wenn man Angegriffen wird.

**Comment by hraesvelgr** [comment]
bot: http://datenbank.welli-it.de/?npc=14434
spell den er haben sollte: http://datenbank.welli-it.de/?spell=23002
(in wowwiki hat dieser spell in seinen sounds den gleichen wie arkane explosion, jedoch: https://www.youtube.com/watch?v=E7wIbxlXCdw
sieht eher wie frostnova aus)
