### ISSUE TITLE
Nicht kürschnerbare Raptoren

### ISSUE THREAD

**Issue by zellklumpen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#627]
Was wird beobachtet:
Die Blutsumpfkreischer in den Marschen von Dustwallow werden nicht als kürschnerbar makiert.

Wie sollte es sein:
Die Blutsumpfkreischer sollten wie die Blutsumpfraptoren kürschnerbar sein.

**Comment by Ghulfang** [comment]
http://datenbank.welli-it.de/?npc=4352
