### ISSUE TITLE
"sechsdemonen" tasche sollte mit spell damage skalieren

### ISSUE THREAD

**Issue by Acolatronico** [ClassicWoW/Nefarian_1.12.1_Bugtracker#628]
Welches Verhalten wird beobachtet?
das trinket "sechsdemonentasche" sollte mit spell damage skalieren welches aber zurzeit nicht der fall ist.

Schritte zur Reproduzierung
items mit spell damage tragen, das trinket benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://de.wowhead.com/item=7734/sechsdamonentasche#english-comments:40 (272 chainlightning hit
297 fireball hit
i wonder if its effected by spell damage

Snazzy am 2007.03.18 (Patch 2.0.10)
It's 100% bonus from spell damage, currently i'm level 52 paladin, with 26 spell dmg, and my Fireballs hits for 226 each time (200 without spell damage.) Nice item. Can't wait till i'll get 700+ Spell dmg :)

dieses sieht man sehr gut in dem folgenden video: https://www.youtube.com/watch?v=6X278igTGuY auch wenn es aus bc ist sieht man das es skaliert, ich habe keine patchnotes gefunden zwischen classic und bc wo erwähnt wurde das die skalierung erst später hinzugefügt wurde, also musste es schon in classic skaliert haben.

Links aus unserer Datenbank: http://datenbank.welli-it.de/?item=7734

**Comment by hraesvelgr** [comment]
weitere quelle:
der change kam erst mit patch 2.2.0:
Six Demon Bag: The damage spells cast by this item no longer benefit from a player’s bonus spell damage effects. 

http://wow.allakhazam.com/forum.html?forum=21&mid=1173901565129166786
I use this on my 62 Paladin still. + spell damage gear definitely affects it. The base damage seems to be around 300, but mine does 450-500. It can crit for 700. I don't think it scales with level because I don't remember seeing a change from 47-58 when I got +dmg gear.

**Comment by bugreportor** [comment]
Ist zwar korrekt, war aber nen Bug und sollte daher nicht reingepatcht werden.

**Comment by Acolatronico** [comment]
wenn sie es erst mit bc rausgepatcht haben ist es also automatisch ein bug gewesen? aha.. fakt ist es ging zu unsererm classic patch stand

**Comment by ircfelix** [comment]
Bc quelle -> warum wird hier noch diskutiert?
Vanilla quelle -> ok kann man patchen.

**Comment by hraesvelgr** [comment]
bc quelle: am classic-content wurde mit BC nicht viel geändert. es wurde nur content geaddet. 
ausserdem gab es wowhead erst mit bc, die kommentare da sind allerdings eine verlässliche quelle. nicht in allen fällen, aber in sehr vielen.

**Comment by ircfelix** [comment]
Quatsch.  Wowhead gab's schon eher und mit bc wurde so einiges geändert, sodass man sich nicht auf bc quellen verlassen kann. Ich glaube ich muss das classic researcher tool von classicwarcraft.com mal hochladen...

**Comment by Larnak1** [comment]
Wo wir gerade dabei sind:

Ist:
- Der Frostblitz hat eine versteckte Castzeit ("entweicht" erst etwa 2 Sekunden nach dem Nutzen der Tasche, der Spieler kann sich während der Zeit aber bewegen)
- Der Self-Sheep ist ein Buff, lässt sich also wegklicken

Soll:
- Der Frostblitz sollte wie alle anderen Zauber ein Sofortzauber sein
- der Self-Sheep sollte ein Magie-Debuff sein
