### ISSUE TITLE
Alle Flugpunkte verfügbar

### ISSUE THREAD

**Issue by Thay-skill3d** [ClassicWoW/Nefarian_1.12.1_Bugtracker#63]
Es ist anscheinend wieder möglich, alle Flugpunkte anzufliegen (Hordenseite, Premium)

Stand 26.10.2014, 02:04 Uhr

Screenshot beigefügt.
![untitled-1](https://cloud.githubusercontent.com/assets/9324743/4781514/258072a6-5ca4-11e4-8aaf-78426c48514a.jpg)

**Comment by Slimmer2** [comment]
Auf Allianz ist das gleiche Problem, Aber nur bei der Rasse Gnom.
Auf Horde ist es auch eine bestimmte Rasse

**Comment by Slimmer2** [comment]
Push

**Comment by Taasch** [comment]
Ich kann ich bestätigen, Mein Troll kann in Kalimdor alles anfliegen. Andere Chars können das nicht.

**Comment by Slimmer2** [comment]
Push

**Comment by Dotox** [comment]
Pushen ist nicht erlaubt. Trag irgendwas nützliches zum Thema bei oder warte ab.

**Comment by Thay-skill3d** [comment]
Naja - jemanden zu sagen “warte ab“ bei einem Bug den ich vor über einem Jahr gemeldet habe ist natürlich eine undefinierte Variable von evtl. 0-10?! Jahren? XD
Das ist ja schon so lange her.. Ich hatte gar nicht mehr gewusst, dass ich das hier geschrieben habe :P

**Comment by Dotox** [comment]
Wenns einfach wäre, wärs schon lange behoben.

**Comment by dagochen** [comment]
Betrifft Gnome und Trolle only soweit ich das beobachten konnte.
