### ISSUE TITLE
[Rogue] Spell Damage Skalierung

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#630]
**Ist-Zustand:**
Aktuell skalieren Schurken Gifte mit Spelldamage. 

**Behauptung:**
Dies ist nicht korrekt. 

**Quellen & Argumente:**
Die Quellen dazu sind leider alle von später, sprich nach Release von BC. 
1. "I toyed around with the idea of some wacky shiv build using +Nature Damage gear. Alas, +Spell Damage gear does not affect poison damage." 
   [2008/04/02 at 4:17 PM (Patch 2.4.1)}
   http://www.wowhead.com/forums&topic=18441/spell-damage-for-poisons
2. "Damaging poisons now scale with attack power." 
   [Release (US) October 14, 2008]
   http://www.wowwiki.com/Patch_3.0
3. Schurken Guides beschreiben ausführlich, welche Buffs sich für Schurken eigenen, darunter sind die Worldbuffs (Verwüstete Lande, ZG, Drachentöter, Teufelswald), Mungos, Riesen, Bufffood,etc....mit einer Ausnahme: Spelldamage-Flasks und Arkan-Eliixere. Die wurden, soweit ich recherchiert habe, nie genannt.

**Schlussfolgerung:** 
Damals haben Schurken-Gifte nicht mit Spelldamage skaliert, sonst hätte dazu etwas in den Patchnotes bei der Änderung zu AP-Sklaierung gestanden oder Informationen in irgendwelchen Guides oder Videos zu dieser "sonderbaren" Variante des Schurken in irgendeiner Form dokumentiert sein müssen. Wenn es mit 2.4 bereits nicht mit Spelldamage skaliert hat, spricht dies dafür das es vorher auch nicht der Fall war.

**Comment by z3v3n** [comment]
Ist eine sehr wage Vermutung.. Um wirklich sagen zu können ob, oder ob es nicht skaliert hat, bräuchte man eine Quelle aus dem tatsächlichen Classic, und nicht von Dingen die Jahre später herausgebracht, eingefügt oder verändert wurden.

Meine Meinung wäre ja im Zweifelsfall für den Angeklagten, da es hier mehrere Schurken auf dem Server gibt, die diese "sonderbare" Skillung spielen und sie doch viel zu balanced scheint als dass es tatsächlich ein Bug sein könnte.

**Comment by dagochen** [comment]
Auch Schurken, die sich nicht darauf spezialisieren, profitieren davon, was gegenüber allen anderen Klassen einen enormen Vorteil, sowohl in PVE als auch PVP bringt. Unter diesem Gesichtspunkt von Balance zu sprechen halte ich für falsch...aber das es nur eine Vermutung ist und ich mir selbst nicht sicher bin hab ich ja auch gesagt ;) Wenn jemand was für oder dagegen findet, bitte, ich lass mich gern überzeugen^^

**Comment by cionex** [comment]
Du bist ja ein richtiger Reporter. Wahnsinn. Ging früher auch, sowohl mit Giften als auch mit Items wie TF. Kurz vor BC haben sie TF dann patched. 

Woher ich das weiß? Weil ich damals schon gespielt hab! 

Man man man, Kranplätze MÜSSEN verdichtet sein!

**Comment by Seniorash** [comment]
Kurz vor BC ist gut..Das war mit 1.8 http://www.wowwiki.com/Patch_1.8.0
Dass sich aber wirklich gar nichts aus der Zeit finden lässt in der Richtung ist schon verdächtig.

**Comment by dagochen** [comment]
"But back on topic. Poisons are indeed another problem. They do not scale at all therefore becoming less and less important in terms of damage. Additionally though Blizz added a new DP rank, I still see no use for it. One idea might be to revise the way DP and IP work by scaling them with weapon damage but this strikes me somehow as the wrong way. It`s obviously dumb to improve poisons by wearing spelldamage/spellcrit gear. Ideas?"
http://forums.elitistjerks.com/topic/6839-patch-112rogue-review-speculations/page-4#entry152835

Dies spricht für eine SPD-Skalierung (mindestens bis zum Thunderfury-Fix in Patch 1.8.0), auch wenn auf den 30 weiteren Seiten des Threads kein anderer Schurke darauf eingeht. Und ja, ich hab grad alle  Seiten durchgeschaut :P

**Comment by bugreportor** [comment]
>Ging früher auch, sowohl mit Giften als auch mit Items wie TF. Kurz vor BC haben sie TF dann patched. 

Gibt es dafür Quellen?
Dass TF mal drei Monate lang mit Spell Damage gescalet hatbevor es gefixt wurde, ist kein Indiz dafür dass es auch mal mit Giften so war. Im Gegenteilt: 
Warum sollte Blizzard einem - zur damaligen Zeit - extrem seltenen Legendary-Item das Scaling wegpatchen, es aber bei normalen Schurkengiften von Release bis zum heutigen Tag unberührt lassen? 

>Ging früher

Wenn es tatsächlich mal gescalet hätte und es jetzt nicht mehr tut, würde es dazu Patchnotes geben.
Die einzige Änderung die es dazu aber gibt ist: "Damaging poisons now scale with attack power. " (Patch 3.0.2 vom 14.10.2008 http://www.wowwiki.com/Patch_3.0.2 ). Das würde heißen, dass SpellPower bis heute mit Giften skalliert, was nicht der Fall ist.

**Comment by cionex** [comment]
Hmm ich versuche mal Quellen dafür zu finden, bin mir aber sicher, dass bei uns damals ein paar Spinner dabei waren die Magerogue gespielt haben. Und das war definitiv auch zu Classic. Ich forsche mal etwas.

**Comment by z3v3n** [comment]
Alles was ihr schreibt ändert aber immernoch nichts daran dass es Blizzlike ist.
Klar ist es schwer bis unmöglich noch Beweise dafür zu finden, aber das gleiche gilt z.b. für die Thunderfury spelldmg skalierung. Davon sind kaum bis keine Videos, etc.,  mehr im Umlauf obwohl es, wie wir alle wissen, definitiv eine Zeit lang skaliert hat.

**Comment by wahaxlekuke** [comment]
So lang es keine echten Beweise, werd ich hier erstmal nix ändern.

**Comment by SirBeansen** [comment]
schaut euch einfach von einem schurken ein video an, der damals naxx gemacht hat. Im normalfall haben die sich IMMER alles gegeben an tränke was ging...da wird man bestimmt auch die billigen + Zauberschaden elexiere geschluckt haben, wenn gifte dadurch mehr schaden gemacht hätten.

**Comment by Seniorash** [comment]
Joa sehe ich genau so Bean: https://www.youtube.com/watch?v=_wW4n0FLKgo
Sogar zum TF finden sich solche Videos: https://www.youtube.com/watch?v=j7bIWySdXi4

**Comment by dagochen** [comment]
https://www.youtube.com/watch?v=PE9PN5S1O7s
3 Schurken ohne +Spelldmgflask / Elixier

https://www.youtube.com/watch?v=5MRdRvkCU6U
kann nix erkennen ^^

https://www.youtube.com/watch?v=wXgwBMZyMR4
hier auch kein spelldmg....

**Comment by SirBeansen** [comment]
Man muss ja mal überlegen...wenn es Spell dmg schurke zu classic gegeben hätte. HÄTTTE! dann würde man dazu auch was finden. Damals haben millionen das spiel gespielt und hier nur 1000?

Da wäre auch jemand anderes auf die idee gekommen. 

Ich finde wenn hinter einem Thema ein großes fragezeichen steht und man es weder wirklich bestätigen kann noch das gegenteil beweißen kann.....doch man mit dem gedanken ran geht, macht es wirklich sinn das spell dmg mit giften skalliert?, sodass es sogar mehr dmg macht als die eigentliche kampf mechanik eines schurken, sollte man es ändern.

Für mich ist es beweiß genug das man einfach nicht dazu findet. Selbst auf elite jerks die alles ausrechnen...jeden kleinen noch +dmg. Selbst in exel datein ist ja nichts zu finden.

**Comment by cionex** [comment]
Und genau die gab es früher auch, genau wie Jäger mit Spell die Leute mit Arkaner Schuss onehitted haben. Nach einiger Zeit wurde die Fähigkeit dann gepatched. Ich suche morgen was dazu. Leider sind selbst Patchnotes von Blizzard nicht immer 100% verlässlich von den Angaben. Ich werd mir morgen mal die Festplatte von damals anschließen und in den alten Videos etc rumschauen.

**Comment by cionex** [comment]
Ihr müsst halt auch bedenken, wie krass damals Flasks im Kurs waren. Bei uns hatte KEINER eine Flask bis auf eventuell Maintanks. Hier kann sich jeder einfach alles geben um maximal abzuliefern. Hat damals so keiner (nicht mal im Progress) gemacht. Deshalb wird es schwer werden mit Belegen dafür oder dagegen. Ich weiß auch leider nicht mehr wann das Phänomen Spelldmg Rogue verschwand - ein Fall für Galileo Mystery!

**Comment by Seniorash** [comment]
Zumindest ein arkanelexier in einem patchwerk dps Video könnte man schon erwarten

**Comment by dagochen** [comment]
https://www.youtube.com/watch?v=q2aPdzcWDOo

**Comment by z3v3n** [comment]
Comment:
"Wound poison existed in vanilla, it was -135 per stack, not a percentage.﻿"
Antwort:
"This guy started playing in Wotlk so its no surprise that his facts aren't that accurate sometimes﻿"

nice^^

**Comment by dagochen** [comment]
Jop beim Wound poison lag er falsch ;) Alles andere stimmt aber, sonst hätte da ja auch wer widersprochen? :)

**Comment by Seniorash** [comment]
Was ist denn ein ausreichender Beweis für etwas was es NICHT gab? Mehr als nix dazu finden zu können geht halt nicht. Hier sehe ich die Beweispflicht eher so rum, dass man einen Beleg für die Skalierung finden sollte. Der Einzige Widerspruch kommt von einem Schurken der in eigenen Kommentaren geschrieben hat dass er selbst nur der Meinung ist, dass es mal ging (und diese Kommentare dann wieder gelöscht hat).

**Comment by cionex** [comment]
Mir ist mittlerweile völlig egal was gepatched wird und was nicht. Ich kann nur mit 100% Sicherheit sagen das dies früher mal ging. Zu welchem Patchstand genau es ging und nicht ging weiß ich leider nicht mehr. Auf diesem Server ist doch alles entsprechend angepasst (Boss HP etc) ich weiß jetzt nicht wo das Problem liegt. Es ist so wie es ist und wenn was geändert werden soll liefert Beweise - nicht irgendwelche Gimpvideos von Leuten die nicht Wissen wo vorn oder hinten ist. :D #closed

**Comment by Larnak1** [comment]
Es ist wirklich nicht einfach, zu dem Thema was zu finden, was merkwürdig ist. Das einzige aus der Zeit, was ich gefunden habe, ist das hier:

>Off the top of my head, other damage abilities which don't scale with weapon damage, attack power, or spell power are:
>
>Thorns
>Retribution Aura
>Blessing of Sanctuary
>All hunter and warlock pet abilities.
>Rend
>Deadly and Instant poisons (effectively)
>Garrote, Rupture
>Rip, Ferocious Bite
>Arcane Shot (effectively)
>Mongoose Bite
>Curse of Doom
http://www.lurkerlounge.com/forums/thread-4155-post-112725.html#pid112725

Später erklärt er, was er mit "effectively" meint:
>That's why I said "effectively":). Same with rogue poisons, as I understand it--they'll benefit from anything that increases nature damage, but no rogue will have much of that, so it's usually irrelevant (exceptions maybe being nature-vulnerable wyrmguards in BWL and rogues who hang out with Stormstrike shamans).
http://www.lurkerlounge.com/forums/thread-4155-post-112843.html#pid112843

**Comment by Seniorash** [comment]
Vor allem stimmt die Aufzählung anfangs schon nicht. Bei uns wurde die fehlende Skalierung von garotte schon reportet und behoben

**Comment by wahaxlekuke** [comment]
Weil bisher alle Quellen ein Hinweis darauf sind, dass Gifte nicht mit Zauberschaden skalieren sollten und es keine einzige Quelle gibt, die das Gegenteil beweist, wird Skalierung in einem zukünftigen Update entfernt.

(Eine weitere Quelle wäre z.B. das alte _TheoryCraft_-Addon, bei dem die Spellkoeffizient von Giften 0 beträgt.)

Weil sich allerdings _nicht_ ausschließen lässt, dass es tatsächlich mal in einem früheren Patch funktioniert hat, werde ich diesen Bug erst mit dem Ahn'Qiraj Content-Update fixen.

**Comment by z3v3n** [comment]
@wahaxlekuke Also dafür dass keine der beiden Seiten bis jetzt IRGENDETWAS beweisen konnte, finde ich diese Entscheidung sehr stark übereilt, zumal dieser Thread hier nur deshalb offen ist weil, und ich zitiere Celly: "Ich mehr damage in raids mache als er".
Ich finde solange nichts bewiesen ist, und das meine ich nicht nur weil es meine Skillung betrifft, erstmal nichts geändert werden sollte. 

Außerdem "alle Quellen" ist schlicht und ergreifend nicht richtig da es, wie man weiter oben sehen kann, stark umstritten ist und es sehr viele alte Offi-Veteranen hier auf dem Server gibt die mir schon mehrfach bestätigt haben dass der "Spelldmg Rogue" legitim UND blizzlike ist.

Ich weiß "Hören-Sagen" zählen zwar nicht viel, aber ich fände es einfach hart für'n Arsch wenn die monatelange Arbeit die ich mir gemacht habe um eine gute Skillung auszuarbeiten und mir das dafür nötige Equip zu besorgen, einfach zu nichte gemacht werden würde weil hier manche Leute Irrtümlicher weise meinen es wäre ein Bug.

Daher bitte ich Dich darum, es so zu lassen wie es ist, bis eindeutig eine der Seiten ihren notwendigen Beweis gefunden hat.

MFG TainteD

**Comment by Larnak1** [comment]
Das AQ-Update wird sicherlich noch Wochen auf sich warten lassen. Ergo ist noch genug Zeit, einen Beleg zu finden :)

**Comment by wahaxlekuke** [comment]
> Außerdem "alle Quellen" ist schlicht und ergreifend nicht richtig da es, wie man weiter oben sehen kann, stark umstritten ist und es sehr viele alte Offi-Veteranen hier auf dem Server gibt die mir schon mehrfach bestätigt haben dass der "Spelldmg Rogue" legitim UND blizzlike ist.

Das Gedächnis keine zuverlässe Quelle und ansonsten hab ich bisher kein Video und kein Foren-Eintrag oder sonstiges irgendwas gesehen, was eure Behauptung stützt.

> Also dafür dass keine der beiden Seiten bis jetzt IRGENDETWAS beweisen konnte


Doch. Sowohl bei dem Video als auch bei dem Theoriecraft-Addon sehe ich keinen Grund warum dort falsche Infomationen genannt werden sollten. 
Außerdem ist es tatsächlich sehr merkwürdig, wenn Gifte mit Zauberschaden skalieren _sollten_, dass z.B. hier http://forums.elitistjerks.com/topic/6646-rogue-spec-discussion/#entry145405 in einem "Poison-build" kein einziges Item erwähnt wird, dass den Zauberschaden erhöht.

> finde ich diese Entscheidung sehr stark übereilt


Das ist bisher der erste und einzige Bug, den ich mit Absicht nicht sofot fixe.

Zumal die Schurkengifte _fast_ 1:1 mit Zauberschaden skalieren und dieser Wert vollkommend wilkürlich aus irgendwelchen Werten für kanalisierte Zauber berechnet wird.

**Comment by z3v3n** [comment]
Naja genau genommen skalieren sich nicht 1:1 sondern deadly 1,3zu 1 und instant poison 0,5~ zu1

Mal eine von uns unabhängige Quelle die das selbe sagt wie ich:
http://wow.ingame.de/forum/roguesa-hideout-184/spelldamage-und-gifte-138079/
"Nicht mehr. Gab vor Urzeiten mal ein paar Verrückte, die Zeug mit +Zauberschaden gesammelt haben und dann ’nen netten Giftschaden hatten. Wurde aber rausgepatcht. :/ "

Und wenn man unter Google "spelldamage rogue" sucht und mal alles einzeln durchgeht findet man  unter anderem mal wieder so etwas: 
http://i.imgur.com/8qoRytn.jpg

Die Seite an sich gibts leider nicht mehr wie viele andere auch die ähnliches im Titel oder der Beschreibung haben.


Achja es gab in eurem Forum schonmal ne diskussion darüber, siehe: 
http://community.mmobase.de/talk-und-allgemeines/3320-spelldmg-schurke.html
Hat nightblizzard damals einfach verschoben, er schien dies nicht als bug zu erachten evtl weiß er ja etwas? ;)

Wie gesagt es gibt einfach zu viele Leute die besagen dass gifte skalieren bzw es mal taten.

**Comment by wahaxlekuke** [comment]
> Mal eine von uns unabhängige Quelle die das selbe sagt wie ich:
http://wow.ingame.de/forum/roguesa-hideout-184/spelldamage-und-gifte-138079/

Ich hab auch nicht bezweifelt, dass es irgendwann mal so war. 
Aber von allen Quellen, die bisher gesammelt wurden, deuten alle, die sich eindeutig auf das Ende von Classic-WoW beziehen darauf hin, dass kein Gift mit Zauberschaden skaliert hat.

**Comment by ChichiWarrior** [comment]
Fakten:
- die Spieler sind heute "intelligenter" als damals
- Du machst mehr DMG als ich, deswegen muss ich dich im Bugtracker reporten

ABER, ganz wichtig:
- Der Kläger steht in der Beweispflicht. Sind die Beweise nicht eindeutig und stützen sich auf Vermutungen oder nicht eindeutig belegbaren Fakten, ist das Verfahren einzustellen.

Diese zwei Zeilen sind hier EINDEUTIG gegeben, denn eine Schlussfolgerung ist in diesem Fall ein subjektives Denken.

Den SpellDMG-Rogue gab es bis Ende World of Warcraft Vanilla und die Skalierung der Gifte wurde DANACH mit AP kombiniert.

Und 98% der Spieler die damals gespielt haben bestätigen, dass das Gift mit SP skalierte.

Zu den Videos:

Das einzige was da zu sehen ist, dass Buffs genommen werden die bei uns nicht gehen.

Und, was meinen ganzen Post überflüssig macht: http://community.mmobase.de/talk-und-allgemeines/6870-der-allmighty-bugtracker.html 

Der Report entspricht nicht der Vorlage. Sieht das jemand anders?

**Comment by z3v3n** [comment]
Vollkommen richtig.

Kommt da noch was von @wahaxlekuke dazu?

**Comment by SirBeansen** [comment]
Im schurken spreadsheet steht auch nichts von spell damage...also ich bitte euch. Wenn es spell damage schurken damals gegeben hätte und gifte auch nur 1dmg mehr machen würden durch Arkan Elexier dann wüssten es nicht nur 4 Spieler......die auch noch alle hier spell damage schurken befürworten....

**Comment by cionex** [comment]
SirBeanson du hast - so scheint es mir - erst mit WotLk angefangen Wow zu spielen, oder? Sonst wüsstest du, dass es sowas sowohl mit Rogues als auch bei Huntern (spielst du den nicht sogar :D ) gab. Wie dem auch sei - es ist nicht die Frage ob, sondern zu bzw. bis zu welchem Patchstand es so war.
Ich befürworte übrigens gar nichts. Spiele kein Mage-Rogue und ich mache auch ohne SpellDmg genug Schaden.

**Comment by Rekooh** [comment]
Hallo liebe Community,

Die Rogue spell damage skalierung!

Ist Zustand:

Rogue poisons oder items mit "Adds x fire damage to your melee attacks."
skalieren mit Spelldmg

Soll Zustand:

Genau so soll es auf dem patchstand auch sein und auch bleiben, 
denn nur genau zu der zeit war es möglich mit dem besagten spellrogue das ultimative rauszuholen.


Warum?: 

Rogue poisons sind zwar Gifte aber richten Naturschaden an. Sie zählen soweit ich weiß nicht zu einem spell sondern sind eine extra kategorie die keiner zuordnen kann. (gifte halt)
jeglicher Spelldmg besteht aus +fire, +arcane, +holy, +nature, +shadow und + frostdmg.

Deshalb ist das Scaling von giften mit spelldmg möglich zu erhöhen. (classic + bc)

"The Nature school is usually used for nature based attacks, buffs, and curative spells. Nature damage can be direct damage (like lightning) or damage over time (like poison).
This means that Rogues (poison), Shamans, Druids, and Hunters (stings) have access to Nature damage."

"Acids, diseases, and poisons inflict Nature damage, and damage from lightning is also considered part of the Nature school. 
Shamans' and Druids' healing spells are Nature spells, and other nondamaging spells such as Entangling Roots and Faerie Fire are in this school as well. 
Hunters' Stings and the Snake Trap's viper poisons are Nature based, as are their Mend Pet and Revive Pet abilities. Rogues' poisons are also Nature based."


Patch 3.0.2 (2008-10-14): Damaging poisons now scale with attack power. 

Erst mit dem patch wurde es eingeführt das poisons nur noch abhängig von ap sind.
Das ap scaling beim rogue kam nach un nach für jede rogue ability. Es fing bei aq oder kurz davor an, wo evis mit ap skalierte. 
Später kamen rapture un co. dazu bis hin zu den poisons die schließlich mit patch 3.0.2. ebenfalls abhängig von ap wurden.

Da blizzard mit classic wow das erste der wow serie startete, war alles anfangs auch nicht perfekt... items, klassenbalance etc.
Es wurde viel gepatched und gefixxt um das spiel ausgeglichener und spielerisch attraktiv für jeden zu machen. 
Ich denke selbst blizzard hätte nie vermutet das eine meleeklasse wie der schurke seine spielmechanik zu der zeit so ausnutzen kann, 
sodass er nur mit seinen giften, die eigentlich nebensächlichen dmg machen, den meisten schaden extrem ausreitzen kann. 

Fragt euch mal selber. wer von euch der ein spiel anfängt und keine ahnung davon hat vermutet das attribute für zauberer auch für eine nahkampfklasse interessant sein kann.


Spellrogue:

Der Spellrogue setzt sich aus einem mix von physical, spelldmg, procitems und der richtigen hybridskillung zusammen.
Wenn ein spellrogue sich wirklich nur auf seine gifte verlässt, wird er nicht ganz so viel dmg fahren wie ein spellrogue der mit giften sowie z.b. +fire dmg spielt.
Das problem am spellrogue ist ,dass es einfach lange dauert bis man die items für diesen speziellen spec zusammen hat(wo man wahrscheinlich 3 leute mit equippen kann), 
da sie momentan aus caster und meleeitems von dem aktuellen high content bestehen. (mc, bwl, zg)

procitems mit "Adds x fire damage to your melee attacks." sind sehr wichtig für diese spielart (ähnlich dem firerogue)
diese proccen nicht gerade selten und mit einiges an spelldmg auch sehr hoch. ein zusätzlicher schaden zu dem gift und meleehits.
Blazefury Medallion, Fiery Retributer, Fiery Plate Gauntlets oder auch Storm Gauntlets. blazefury medallion wurde zu bc glaub entfernt und hatte somit keinen nutzen mehr.
3 verschiedene schadensarten machen dem spellroge extrem stark und teilweise op. 


History:

Den spell- oder auch firerogue gab es in classic von anfang an bis ende! auch wenn er in naxxramas eher überflüssig wurde, da es dort kaum items gab, die den spellrogue im dmg pushen, 
zogen die physical rogues durch die enorme steigerung der physical naxx items an ihnen vorbei und machten im endeffekt mehr schaden. fazit: spellrogue lohnte sich nicht mehr! items wie z.b. Blazefury Medallion 
oder auch Fiery Retributer gab es nur rar und während naxx in keiner stärkeren form.


Deshalb werden ihr keine videos von spellrogues in naxxramas finden. zumal in naxx nur ein winziger prozentsatz an spielern war, gab es die spellrogues zu einem noch 100mal geringen prozentsatz.
Auf den offizellen Blizz servern hatte man als spellrogue eigentlich kaum die chance ihn überhaupt ansatzweise kennenzulernen, da sämtliche contents einfach viel zu schnell aufgespielt wurden.
Man hatte ca. 2 jahre zeit gehabt um alles was wir heute schon (auch durch die fortsetzenden addons) kennen un kennengelernt haben schnell aufzunehmen und umzusetzen. heute ist das was anderes
jeder kennt das spiel und die mechaniken immer mehr im detail...früher wusste man erstmal gar nicht was man machen sollte. während im vergleich früher ein char von 0-60 gelevelt wurde hat das
oft ein monat lang gedauert... hier geht das innerhalb weniger tage. zudem waren die spieleranzahlen wesentlich höher und mats für potions und flasks mehr begrenzt wie hier auf dem server.
Keiner hat sich irgendwas gefarmt was teuer und zeitaufwendig war und die dps nur um ein geringes maß steigert. allein aus zeitlichen gründen!



Schlusswort:

Da es zu dem thema kaum noch quellen gibt ist es schwer beweise zu finden. hier werden quellen aus foren von leuten die mal gespielt haben gepostet und deren meinung scheint zu zählen da es schriftlich ist.
aber auf erinnerungen un wissen anderer spieler wird hier gepfiffen. im prinzip werden hier auch nur erinnerung von leuten aus anderen foren gepostet. Hier gibt es momentan keine wirkliche quelle die das gegenteil beweist! leider nur anhaltspunkte die es teils beweisen.
Ich finde es ist beweis genug das poisons naturzauber sind die naturschaden machen und der spelldmg sich aus den faktoren fire,natur,frost..... zusammensetzt, 
diese unterstützt und erst mit wotlk das scaling der poisons mit ap eingeführt wurde.

**Comment by dagochen** [comment]
Wo hast du die Zitate her? Quellen bitte immer nennen, damit diese nachvollziehbar und überprüfbar sind. Danke!

**Comment by z3v3n** [comment]
Also man muss auch sagen, dieses Thema sollte behandelt werden wie jedes andere im Bugtracker.
Wenn etwas geändert, entfernt oder eingefügt werden soll, muss ein eindeutiger Beweis geliefert werden damit der Server so blizzlike wie nur möglich bleibt.

Bis jetzt waren alle "Argumente" und Quellen, von Leuten die Behauptungen aufstellen. 
Aussagen wie "Das hat nie skaliert, bla bla bla.." werden allein dadurch entkräftigt, dass der Server hier die Coreversion von 1.xx benutzt und da die Gifte mit Spelldmg skalieren. Ich habe mir auch alle Patchnotes die es gibt durchgelesen und nicht EINMAL wurde die Skalierung der Giften erwähnt, erst mit 3.0 mit "Gifte skalieren jetzt mit Attackpower". Man findet nichts wie bei patch 1.8 "Thunderfury's proc skaliert nicht länger mit Spelldmg" und Blizzard war immer SEHR genau bei den Patchnotes, denn hätten sie das einfach entfernt gäbe es vermutlich Beschwerden in den Foren dass plötzlich die Gifte nicht länger skalieren und diese Beschwerden könnte man eventuell sogar noch finden!

Klar sich auf Hören/Sagen zu verlassen ist schlicht weg scheiße aber was anderes bleibt aktuell einfach nicht übrig. Nur ein kleines Beispiel: Thunderfury hat mal skaliert, weiß jeder, aber finde mir mal jemand einen Screenshot oder ein Video, wo man sieht: "Ah der hat so und so viel Spelldmg an und macht so und so viel Dmg mit dem Thunderfury Proc.". Das Video von Seniorcash (" Sogar zum TF finden sich solche Videos: https://www.youtube.com/watch?v=j7bIWySdXi4 ") zeigt GAR NICHTS.

Es hat mal skaliert wie Wahax gesagt hat, man weiß nur nicht genau von wann bis wann. Nachdem man bzw ich bis jetzt immernoch nichts gefunden habe, und glaubt mir ich habe wien bekloppter nach nem Zeitschema gesucht, bin ich der Meinung dass man es Kulanz und Fairheit so beibehalten sollte wie es aktuell ist. Die Skalierung ist keines Falls OP, sonst wäre ich immer und überall Dmg 1., was nicht der Fall ist und auch nie sein wird. 

MfG TainteD

**Comment by dagochen** [comment]
http://www.lurkerlounge.com/forums/thread-4155-page-5.html

Sinngemäß wird hier gesagt, dass Gifte mit Zauberschaden skalieren, über die Menge wird nix gesagt und dass es für Schurken nicht/wenig sinnvoll ist, +spelldmg zu stacken, weil man ja nicht an genug kommen würde, dass es gut wird.

**Comment by Rekooh** [comment]
http://www.wowwiki.com/Magic_schools_%28WoW%29#Nature
quelle für meine post 4 dagochen :)

**Comment by Seniorash** [comment]
AQ inc, push!

**Comment by SirBeansen** [comment]
Off the top of my head, other damage abilities which don't scale with weapon damage, attack power, or spell power are:

Thorns
Retribution Aura
Blessing of Sanctuary
All hunter and warlock pet abilities.
Rend
Deadly and Instant poisons (effectively)
Garrote, Rupture
Rip, Ferocious Bite
Arcane Shot (effectively)
Mongoose Bite
Curse of Doom

http://www.lurkerlounge.com/forums/thread-4155-page-3.html

Wenn die gifte damals mit Spell damage skalliert hätten würde es irgendwo stehen....als wenn ein schurke das nicht mal mit einem trank ausprobiert hätte.....

**Comment by Sabbaer** [comment]
und nocheinmal ein hardpush, schurken machen viel zu viel dmg in aq, kann echt nicht sein.......der thread wurde am 6.april eröffnet und es ist sehr ärgerlich, dass eine klasse seinen dmg ungemein durch pots in die höhe pushen kann, bei denen es nicht möglich sein sollte

**Comment by dagochen** [comment]
@Dotox  @nightblizard 
Bitte fixen. Skalierung wie bei Schami-Waffen-Verzauberungen wäre ein guter Mittelweg?

**Comment by hraesvelgr** [comment]
sollte doch reichen, den spelldmg koeff auf 0 zu setzen? 

wahax hatte doch mal einen screen gepostet, der gezeigt hat, dass es wirklich nur das simple ändern weniger zahlen bedeutet. ich such euch auch gern sämtliche id's raus

**Comment by dagochen** [comment]
Ja. Oder 0.1 wie bei den anderen Waffen-Enchants von Schamis z.B.

**Comment by Sabbaer** [comment]
hier wäre es echt wichtig etwas zu machen 450er gift procs sind einfach nur extrem übertrieben und absolut nicht legit

**Comment by z3v3n** [comment]
Mimimi

**Comment by Sabbaer** [comment]
sehr konstruktiv z3v3n, aber es gibt genügend beispiele bei anderen klassen, die weniger auswirkung auf den gesamt dmg hatten als in diesem fall hier

**Comment by z3v3n** [comment]
Such mimimi Much Wow Kappa

**Comment by Dotox** [comment]
> ich such euch auch gern sämtliche id's raus

Wäre Super!

**Comment by testear** [comment]
Von R1 bis R5 bzw 6 von Oben nach unten.

Tödliches Gift:
http://datenbank.classic-wow.org/?spell=2818 
http://datenbank.classic-wow.org/?spell=2819 
http://datenbank.classic-wow.org/?spell=11353
http://datenbank.classic-wow.org/?spell=11354
http://datenbank.classic-wow.org/?spell=25349

Sofortwirkendes Gift:
http://datenbank.classic-wow.org/?spell=8680
http://datenbank.classic-wow.org/?spell=8685
http://datenbank.classic-wow.org/?spell=8689
http://datenbank.classic-wow.org/?spell=11335
http://datenbank.classic-wow.org/?spell=11336
http://datenbank.classic-wow.org/?spell=11337

bitte noch oben in den Startpost kopieren.

**Comment by Sabbaer** [comment]
push

**Comment by Hakii** [comment]
Selbst die ältesten Forenleichen aus bekannten Diskussionforen von damals die noch verfügbar sind, behandeln auch nicht wirklich dieses Thema. Wird schwierig hier eine klare Antwort zu finden. Ich hab damals auch relativ erfolgreich geraidet, wäre aber damals nie auf den Trichter gekommen, Spelldamage-Gear oder ähnliches auszuprobieren. Vor einem halben Jahr hab ich in einer Elitist Jerks Forenleiche einen Einzeiler von einem Diskussionsteilnehmer entnommen, der meinte dass Gifte skalieren, sei aber nicht lohnend (1 Satz auf zig Seiten) - auf diesen Post erfolgte dann auch keine Reaktion mehr. Da ich aber nicht mehr weis wo dieser Post vergraben liegt und dieser Post auch nicht wirklich ein Beweis darstellt, bin ich nun zu faul diesen erneut rauszusuchen :-)

**Comment by dagochen** [comment]
Erklärung: Die Skalierung wurde entfernt. Im Server gibt es 2 Arten, wie die Skalierung berechnet wird:
a) durch fest hinterlegte Werte für viele Zauber
b) durch eine Aneinanderreihung verschiedener Formeln, für alle anderen Zauber

Die Gifte hatten bisher keine festen Skalierungen eingetragen und wurden daher wie "jeder andere Zauber" behandelt. Beim sofort-wirkenden-Gift wurde mit den Formeln aus b) dann ein Skalierung von 1,5 / 3,5 berechnet und angewendet. Dies war so weder von uns, noch von den cmangos-Entwicklern, gewollt. Der Eintrag der Skalierung für die Gifte bei a) hat also gefehlt und wurde ergänzt.
