### ISSUE TITLE
[Hunter] Entrapment Diminishing Return

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#632]
Aktuell unterliegt der Entrapment-Root-Effekt dem diminishing return Regeln. Dies wurde erst mit 2.1 eingeführt und sollte bei uns folglich nicht so sein.

Patch 2.1.0 (22-May-2007): Entrapment (Survival): Effect duration reduced to 4 seconds and is now subject to diminishing returns in PvP.
http://www.wowwiki.com/Patch_2.1.0

**Comment by wahaxlekuke** [comment]
Betrifft auch das Frostbite-Talent vom Magier.
