### ISSUE TITLE
Schmiedekunstquest: "Habt ihr das verloren?"

### ISSUE THREAD

**Issue by Puschek** [ClassicWoW/Nefarian_1.12.1_Bugtracker#633]
Nach dem Abschließen der 3 Vorquests, müsste man eine Quest vom gleichen Questgeber bekommen, damit man ihm bei der Arbeit zusieht. Dies passiert nicht. Ich hab jetzt die Quest von einem netten GM bekommen, trotzdem kann ich die Quest nicht beenden, weil ich ihm nicht zugucken kann wie er arbeitet!

**Comment by wahaxlekuke** [comment]
Bitte an die Vorlage halten. Vor allem die Links aus der Datenbank sind wichtig.

**Comment by Puschek** [comment]
Hey ok!

http://datenbank.welli-it.de/?quest=3321

Die Quest sollte nach dem Abschließen der 3 Quests davor 
http://datenbank.welli-it.de/?quest=2773
http://datenbank.welli-it.de/?quest=2772
http://datenbank.welli-it.de/?quest=2771
zum annehmen sein. Leider bekommt man keine quest! In der Quest soll man Mithril Kid beim Arbeiten zuschauen, da man die Quest selbst nicht annehmen kann und somit das Event Triggern kann, ist diese Quest nicht zum Abschließen.

Ich kann mich erinnern, dass auch den damaligen Live servern das gleiche Problem vorliegte.

**Comment by MountFoult** [comment]
Welches Verhalten wird beobachtet?
Die Quest "Habt ihr das verloren?" (http://datenbank.welli-it.de/?quest=3321) wird nach wie vor nicht beim Questgeber "Trenton Lichthammer" (http://datenbank.welli-it.de/?npc=7804) angezeigt, nachdem wie Puschek oben schon beschrieben die drei Vorquests 
"Ein schlauer Kopf auf den Schultern" http://datenbank.welli-it.de/?quest=2771
"Die Welt zu Euren Füßen" http://datenbank.welli-it.de/?quest=2772
"Mithril-Kid" http://datenbank.welli-it.de/?quest=2773
bei Trenton Lichthammer abgeschlossen wurden.

Wie sollte es sich verhalten?
Trenton Lichthammer sollte die Quest http://datenbank.welli-it.de/?quest=3321 nach Abschluss der anderen Drei anbieten. 
In dieser soll wie Puschek oben beschrieb Trenton Lichthammer beim arbeiten zugesehen werden.

Schritte zur Reproduzierung
Questreihe beginnt in Orgrimmar bei "Aturk der Amboss" (http://datenbank.welli-it.de/?npc=7792)
mit der Quest "Die alten Traditionen" (http://datenbank.welli-it.de/?quest=2756).
Voraussetzung sind Schmiedekunst und Level 40.
Nach dieser wird man nach Beutebucht geschickt. Die Quests werde ich jetzt nicht alle verlinken.

Zusätzliche Informationen
Die Questbelohnung ist die "Gleißende Mithrilinsignie" http://datenbank.welli-it.de/?item=10418
Das Item ist vielseitig einsetzbar und fehlt sowohl im PVP, als auch in Bossfights (z.B. bei Lethon auf der Hordenseite, um den Fear entgegenzuwirken).
