### ISSUE TITLE
Nachricht an Vega

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#635]
Habe zufällig ihren offenen Brief im Classic-Forum gelesen. Sollte der Inhalt ernst gemeint gewesen sein, was ich ehrlich gesagt nicht weiß, ich bin was das angeht immer schon sehr naiv, dann möchte ich mich für den Einsatz bedanken.

**Comment by wahaxlekuke** [comment]
Hallo Ernie,

erstmal ist der Bugtracker nicht zum Nachrichten schreiben gedacht und mich wundert fast schon, dass du hier im Bugtracker noch nicht bebannt bist.
Allerdings halte ich dich nicht für nen reinen Troll und möchte mich daher mal kurz mit dir unterhalten (Am besten über Skype - siehe mein Foren-Profil)
Wenn du also möchtest, meld dich mal bei mir.
