### ISSUE TITLE
Windhäscher: übermäßige Resistenzen

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#637]
**Welches Verhalten wird beobachtet?**

Der Windhäscher hat extreme hohe Resistenzen gegen alle Magieschulen (480-600). Möglicherweise ist das ganze sogar richtig so - scheint mir aber sehr unwahrscheinlich.

**Wie sollte es sich verhalten?**

Ich hoffe, dass der Windhäscher "normale" Resistenzen haben sollte. Vielleicht auch eine oder zwei erhöhte Resistenzen.

**Schritte zur Reproduzierung**

Windhäscher anschauen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Screenshot mit den Resis: http://picload.org/image/irglaoo/resis.png

http://www.wowwiki.com/Elemental_Invasions " The Windreaver, who travels with his four guards throughout the Dust Stormer area of Silithus"

http://forscherliga.wikia.com/wiki/Windh%C3%A4scher " reist mit seinen vier Wächtern durch das Staubstürmer-Gebiet "

**Links aus unserer Datenbank**

Der Windhäscher: http://datenbank.welli-it.de/?npc=14454

**Comment by wahaxlekuke** [comment]
Soo unwahrscheinlich ist die hohe resistenz gar nicht - z.B. hat Ghamoo-ra (http://datenbank.welli-it.de/?npc=4887) tatsächlich 925.032 Rüstung, obwohl das Cap vieeeel niedriger ist. 

Ohne z.B. ein Video, in dem man den Widerstand zumindest abschätzen kann, werd ich da nix ändern.
