### ISSUE TITLE
Windhäscher: patroulliert nicht

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#639]
**Welches Verhalten wird beobachtet?**

Der Windhäscher steht fest auf einer Position im nordwesten von Silithus.

**Wie sollte es sich verhalten?**

Er sollte um den Berg, an dessen Flanke er steht, patroullieren.

**Schritte zur Reproduzierung**

Windhäscher anschauen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Wegpunkte: http://wow.freierbund.de/map_and_guide/314345-2/Der_Windhaescher-Bilder.html

http://www.wowwiki.com/Elemental_Invasions " The Windreaver, who travels with his four guards throughout the Dust Stormer area of Silithus"

http://forscherliga.wikia.com/wiki/Windh%C3%A4scher " reist mit seinen vier Wächtern durch das Staubstürmer-Gebiet "

**Links aus unserer Datenbank**

Der Windhäscher: http://datenbank.welli-it.de/?npc=14454

**Comment by dagochen** [comment]
Weiß nicht wieso du jetzt 3 Tickets dafür machst, wenn ein Mob nicht korrekt funktioniert. Zumal das (bis auf die Resis) schon reportet war: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/215

**Comment by Gnomorus** [comment]
Wenn du die Einleitung im Bugtracker liest, weisst du vllt auch warum ich 3 Tickets aufgemacht hab. (Nur ein Fehler pro Fehlermeldung).
Dein anderer Punkt ist soweit richtig - hab vorher nicht gesucht.
Clevererweise hättest du dann aber das Ticket mit den Resistenzen kommentiert, da die anderen ja eh wieder geschlossen werden.
