### ISSUE TITLE
Gnomischer Diskombobulatorstrahl Dismountet Gegner im PvP nicht

### ISSUE THREAD

**Issue by SirSoarin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#644]
Ist-Zustand:
Gnomischer Diskombobulatorstrahl verwandelt Gegner in einen Lepra Gnom und verringert das Bewegungstempo um 20% sowie den verursachten Nahkampf und Magieschaden um 40.

Sollzustand:
Genau wie oben alles richtig , nur zusätzlich hatte der Strahl den Effekt einen Gegner vom Mount runter zu werfen , sozusagen ein "Ingenieurs Sheep".

Quelle:
Retail Erinnerung , das Teil war der Burner für PvP Paladine , war es doch die einzige Möglichkeit , flüchtende Gegner vom "Pferd zu werfen" und zu verlangsamen , auserdem wurde der "Vom Mount werf Effekt" erst mit BC entfernt weil zu Mächtig gegen Fliegende Reittiere.

Und Natürlich auf WoWiki stehts auch nochmal....http://www.wowwiki.com/Discombobulator_Ray

"This item used to be fairly overpowering in PVP, especially for something this easy to make. It slows the movement speed of the target by 20% and reduces their melee/spell damage by 40. The big killer was that it would even dismount mounted opponents. Not to mention the humiliation and surprise of being transformed into an ugly leper gnome. Blizzard has removed this item's ability to dismount targets, citing that it was never intended to be able to dismount players flying in Outland."

**Comment by dagochen** [comment]
NEEED!!!!

**Comment by Haudraufinix** [comment]
https://www.youtube.com/watch?v=Xlm6i23hMXs
Sehr Unterhaltsames Beweisvideo in dem ausdrücklich auf den Diskomobulatorstrahl eingegangen wird.
