### ISSUE TITLE
Hallo Fans

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#646]
Ich möchte mal generell sagen, dass es ein falscher Ansatz ist, Unwissenheit mit Arroganz und Ignoranz vertuschen zu wollen. Und ihr seid nun mal unwissend. Keiner von euch hat jemals in seinem Leben WoW gespielt, sonst wüsste er einfach ein paar grundlegende Dinge, die niemand beweisen muss.

Ich gehöre zum Beispiel der Fraktion an, die tatsächlich Klassik-WoW gespielt haben. Deswegen muss ich mir auch euren Client nicht runterladen, weil ich hab das Original hier zu Hause liegen. DAs heißt auch mit Karte und Handbuch. Das gab es damals nämlich noch. So und seit einiger Zeit ist es bei euch so, dass man als Geist normales Lauftempo hat, was total bescheuert ist.

Ich finds ja gut, wenn ihr Fehler behebt, alle 5 Monate einen oder zwei, aber was ich nicht gut finde, dass ihr alle 5 Monate ein bis zwei neue Fehler einbaut, das ist eigentlich doof. Wenn ich das mal so sagen darf.

Und das ist zum Beispiel so ein Fehler, der extrem nervt. Dann kommen so ne Gehirnamputierten von eurem Server und wollen mir erzählen, dass das in Klassik so gewesen ist. Jetzt hab ich mir noch mal das Handbuch durchgelesen aus nostalgischen Gründen und es steht sogar im Handbuch drin, dass man als Geist erhöhtes Lauftempo hat. Es ist richtig Elfen haben noch mal erhöhtes Lauftempo als Geist, aber das ist zusätzlich. Das übersteigt offensichtlich euer GEhirn so etwas. Ihr fühlt euch einfach in der Rolle wohl, dass andere als Bittsteller kommen und ihr sie mit Arroganz und Ignoranz begutachtet. Ich hab keine Ahnung warum ihr das überhaupt macht hier. Ich kann mir das eigentlich nur so vorstellen, dass ihr dem Bösen angehört, das diesen Planeten beherrscht und für euch ist das Teil der Kriegsführung gegen das Gute, was zumindest vor einigen Hundert Jahren das Deutsche symbolisierte besser gesagt das Preußische.

Wie dem auch sei. Das ist ein Fehler bei euch und das kann man leicht korrigieren. Das sind Einstellungen in der mongos.conf-Datei. Da muss man eine Zahl ändern. Wie hoch die Geschwindigkeitserhöhung war, weiß ich jetzt nicht exakt. Ich glaub es waren 40% - als Geist.

Zweiter Fehler, den ihr eingebaut habt, also seit einiger Zeit schon ist die Anzeige von den Quests. Normalerweise müssen Quests solange sichtbar angezeigt werden wie man selbst Erfahrungspunkte dafür bekommt. Das ist ungefähr so ein Levelunterschied von 7 Levelstufen. Es ist mir jetzt schon mehrmals passiert, dass ich in einem Gebiet war und wenn ich nicht gewusst hätte, dass da noch Quests sind, hätte ich die gar nicht annehmen können, weil sie mir nicht angezeigt worden. Ich hatte Level 34 und die Quest hatte Stufe 30 oder so und wurde nicht mehr angezeigt. Das ist auch eine Einstellung in der mangos.conf-Datei und wenn ihr was anderes habt als mangos macht es auch nichts, weil das ja alles ähnlich aufgebaut ist. Die Datenbanken sind sowieso fast identisch aufgebaut.

Die beiden FEhler zu korrigieren würde euch ungefähr 1 Minute Arbeitszeit kosten. Aber wahrscheinlich verlangt ihr von mir, dass ich ein Video aus dem Jahr 2005 organisiere, wo ersichtlich ist, dass man Quests auch noch 7 Stufen über der Queststufe annehmen konnte. Klar so kann man sichs einfach machen. So hat man es einfach andere zu ignorieren und vor allen Dingen müsst ihr niemanden beichten, dass ihr von dem Spiel absolut keine Ahnung habt. Das scheint ihr mit der momentanen Blizzardbelegschaft gemeinsam zu haben. Vielleicht könnt ihr sogar da mal irgendwann arbeiten, wenn die bis dahin WoW nicht an die Wand gefahren haben.

**Comment by dagochen** [comment]
> Ich glaub es waren 40% - als Geist.

Glaubst du es oder weißt du es? Nicht das jemand sich die Mühe macht und es dann immer noch falsch ist. Dann würde ja wieder ein neuer Fehler eingebaut werden?

> Es ist mir jetzt schon mehrmals passiert, dass ich in einem Gebiet war und wenn ich nicht gewusst > hätte, dass da noch Quests sind, hätte ich die gar nicht annehmen können, weil sie mir nicht 
> angezeigt worden.

Du kannst auch Quests annehmen, die nicht angezeigt werden. Einfach einen NPC anquatschen und wenn er eine Quest für dich hat, nimm sie an, ansonsten lass es sein. Geht auch, für Quests, die eine zu geringe Stufe für dich haben.

**Comment by Flaktrack** [comment]
Extrem schnell wars früher auch nicht.
lt. Addon "MonkeySpeed" wird bei mir 125% Speed als Geist angezeigt. Dies sollte so korrekt sein. Nachtelfen schaffen 150 Sachen :-)

Quelle:
x-beliebige Klassen-FAQ vom 08.12.2005
http://www.ign.com/faqs/2005/world-of-warcraft-druid-faq-674483

***Night Elves***
---Racial Traits---
......
Wisp Spirit: When you die (In which you will many times) you 
become a Wisp Spirit meaning your running speed will be increased 
by 50% until you get to your corpse, or a wondering kind hearted 
Priest/Paladin/Shaman revives you on the spot. Most definitely a 
cool passive skill, specially since other races have a 25% speed 
bonus when they are normal spirits.

**Comment by ircfelix** [comment]
mongos.conf

^_^ bitte bannt ernie nicht sofort!!! :-)

**Comment by dagochen** [comment]
haha ircfelix ;) das hatte ich garnet gesehen^^ voll gut ;)
