### ISSUE TITLE
heilig resistenzen

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#647]
Titel:
alle mobs besitzen heilig resistenzen

Welches Verhalten wird beobachtet?
npcs können teilresisten auf heilig dmg oder vollständig

Wie sollte es sich verhalten?
Extremst wenige mobs sollten heilig resistenzen besitzen bzw teilresisten können (an einer hand abzählbaer)

Schritte zur Reproduzierung
http://www.wowwiki.com/Holy_resistance
Resistable Spells Edit
Paladin: 3 Judgements, Consecration, Hammer of Wrath, Holy Shock, Avenger's Shield, Repentance, Holy Wrath, Exorcism, Turn Undead
anmerkung: keine soc erwähnung

http://www.wowwiki.com/Magic_schools_%28WoW%29
unterpunkt holy

**Comment by Haudraufinix** [comment]
*It only exists against PvE targets of a higher level.*
Das heisst für mich mobs ab c.a. Lvl 45 haben Holy Resistenz. Welche Mobs sollen nach dieser Quelle denn Heiligresistenz besitzen?

*It is not possible to build resistance to Holy magic, giving Holy Priests an advantage over other casters, but all characters and mobs do have a base resistance chance. Also, the damaging Holy spells used by Priests and Paladins tend to deal smaller amounts of damage in comparison to other schools, counterbalancing the lack of resistance*
Aus: http://www.wowwiki.com/Magic_schools_(WoW)?oldid=297382
Ich find vor allem den Teil über die geringeren Schadenswerte interessant, aber das istn Topic für sich. Darauf brauchen wir hier nicht einzugehen

**Comment by Sabbaer** [comment]
soc ist ein special weapon attack. Er wird im resistance thread nicht erwähnt, er kann geblockt parriert ausgewichen werden und bekommt einen partial resist auch noch?

https://www.youtube.com/watch?v=rXNWvytYbyo
https://www.youtube.com/watch?v=VEs9coe5XRg
wie in den videos gut zu sehen werden richturteil des befehls oder exorzismus komplett widerstanden oder treffen voll.
Er hat in beiden videos keinen einzigen partial resist auf soc proGGs. Die wahrscheinlichkeit darauf ist erschreckend gering bei sovielen soc proGGs!

**Comment by dagochen** [comment]
Siegel des Befehls: Melee-Hitberechnung, Spelldmg-Schadensberechnung
Richturteil des Befehls: Spelldmg-Hitberechnung, Spelldmg-Schadensberechnung
Exorzismus: Spelldmg-Hitberechnung, Spelldmg-Schadensberechnung

Ist korrekt so implementiert würde ich sagen, weil parieren gibt es, rest kann voll resisten oder teil. Sind ja keine Binären Zauber oder?

**Comment by Sabbaer** [comment]
ist es nicht, weil ich teilresists drauf hab

**Comment by Haudraufinix** [comment]
Bleibt also die Frage zu klären, ob SoC Binär ist oder partiell wirkt.
Dem Schamanen gehts mit Flammenzunge im Moment übrigens auch nicht besser ;)

**Comment by 0815Priester** [comment]
hab null plan vom Pala,hier steht aber folgendes:
http://www.elitepvpers.com/forum/wow-guides-templates/55208-paladinformeln-auch-ein-paar-f-r-andere-klassen.html

Binäre Zauber (Binary spells) sind alle Zauber, die einen Schadenskomponenten und einen nicht-Schadenseffekt haben. Nicht-binäre Zauber (non-binary spells) sind Zauber, die nur Schaden verursachen. Der Paladin hat keinen binären Zauber.

**Comment by Sabbaer** [comment]
Patch 1.3.0 (07-Mar-2005): The damage effects can now be resisted instead of dodged, blocked, or parried.

also kann ihm jetzt so wie es implementiert ist "resisted, dodged, block or parried" werden!

**Comment by 0815Priester** [comment]
Hier wird folgendes behauptet:

binäre und nicht-binäre Zauber
Binäre Zauber (Binary spells) sind alle Zauber, die einen Schadenskomponenten und einen nicht-Schadenseffekt haben. Nicht-binäre Zauber (non-binary spells) sind Zauber, die nur Schaden verursachen. Der Paladin hat keinen binären Zauber.

http://www.elitepvpers.com/forum/wow-guides-templates/55208-paladinformeln-auch-ein-paar-f-r-andere-klassen.html

**Comment by Sabbaer** [comment]
http://paladin-guide.blogspot.de/2005/12/stats.html

 Notice that some mobs have holy resistance (especially bosses).
The paladin class spells deals holy damage so they are not influenced by resistences.

http://paladin-guide.blogspot.de/2005/12/seals.html

However on the damage calculation is considered as an holy spell hence resistances and not armor comes in play. Like we have seen in the previous chapters holy resistance in game is quite absent so normally the holy damage is dealed at its full potential.

**Comment by Haudraufinix** [comment]
*When you are hit by a direct-damage spell, you have a chance to resist 100%, 75%, 50%, 25%, or 0% of the spell's damage, depending on your resistance score in relation to the level of the attacking caster. Your average percentage of damage resisted is the weighted average of your resistance percentages for each level of damage resistance (100%, 75%, 50%, 25%, and 0%).*
aus http://paladin-guide.blogspot.de/2005/12/stats.html zweiter Beweis, dass SoC nicht-binär ist.

Die grundfrage die wir nun Beweisen müssen ist, welche Mobs denn nun Holy resist besitzen und welche nicht. Vorher macht ein Fix wenig sin. Wir haben nun die Quelle http://paladin-guide.blogspot.de/2005/12/stats.html die besagt kaum ein Mob hat Reistenzen und trotzdem besagt die selbe Quelle Implizit dass es trotzdem welche mit resistenzen gibt. Ich denke nicht dass man das korrekt fixen kann. Wenn man nicht genau weis welche Regeln Blizzard hierfür angewant hat. Fürs PvE ist vielleicht das hier ganz brauchbar:
* In PvE, Holy resistances do exist under specific circumstances (if the enemy has a higher level than you), and in that case your Holy spells may be partially resisted.*
http://www.wowwiki.com/Magic_schools_%28WoW%29?oldid=623209 Link aus BC patchnotes!

**Comment by Sabbaer** [comment]
also macht ein best in slot paladin mit ony buff und spelldamage flask +best in slot meele sowie full t2 alle enchants mungo, winterfelle und stärke juju sowie bufffood + sulfuras hand von ragnaros weniger dps als ein deff krieger. 
Das ja interessant

**Comment by Haudraufinix** [comment]
das ist definitv nicht der Fall. Rein durch deine Waffe generierst du an Bossen als Mensch
(80-(80*(0.3*0.15)))*(1-0.22) = 59.5 Dps (Rüstung und Glancingsabzüge) Dazu kommt dein komplettes EQ mit Stärke, dazu noch einmal 0.44*70 = 31% Dmgbonus durch Siegel + 0.29x deine Spellpower pro Siegelprocc.
Ich kenn die Palaset stats nicht genau genug, aber der DMG müsste meiner meinung nach höher sein.
Bei 800 AP z.b. hast du zusätzlich 42 Dps durch Angriffskraft (FINAL, NACH RÜSTUNG UND GLANCES)
und bei 200 Spellpower etwa 7 Dps durchs siegel nochmal hinzu.
Wir haben also Cirka 140 Dps durch Autohits. OHNE Richturteil, Siegel des Kreuzfahrers, Hammer of Wrath, Schadensboni durch Rache, Waffenproccs oder auch nur Critchance einberechnet zu haben. Schätzungsweise wird sich dein DPS so cirka bei 300-400 Dps irgendwo einpendeln. Passt etwa zu den 450 Dps eines MM Hunters im T2 Standart. Betrachtet man dabei dass der Pala eine Klasse ist die sehr viele Raidbuffs hat stimmt dieser wert etwa.

Aber back to topic, es geht hier um die resists, nur indirekt um Paladps

**Comment by Sabbaer** [comment]
http://www.wowwiki.com/Magic_schools_%28WoW%29#Holy

It is not possible to resist Holy magic, giving it a slight advantage over other schools, but it does have a basic miss chance like all spells, offset by Hit rating, and spells can be silenced.

http://www.wowwiki.com/Resistance
There was no resistance stat for Holy, and as such no players nor NPCs could resist Holy spells. A character's current resistance score to each school was advertised on the character sheet.

**Comment by Haudraufinix** [comment]
Du widersprichst dir gerade selbst. im http://paladin-guide.blogspot.de/2005/12/stats.html link den du gepostet hast steht drin:
*Notice that some mobs have holy resistance (especially bosses). im Punkt Magic Resistances*
und nun kommt
*t is not possible to resist Holy magic, giving it a slight advantage over other schools, but it does have a basic miss chance like all spells, offset by Hit rating, and spells can be silenced.*
aus http://www.wowwiki.com/Magic_schools_%28WoW%29#Holy
der Thread ist eigendlich unnötig, da du selbst nicht weist, was nun stimmen soll...

**Comment by Sabbaer** [comment]
nein, es gibt ein paar ausnahmen, der normalfall ist, dass es das nicht gibt
Du betreibst hier haarspalterei, das ist dir schon bewusst?

**Comment by Sabbaer** [comment]
zitat: "Wir haben also Cirka 140 Dps durch Autohits. OHNE Richturteil, Siegel des Kreuzfahrers, Hammer of Wrath, Schadensboni durch Rache, Waffenproccs oder auch nur Critchance einberechnet zu haben. Schätzungsweise wird sich dein DPS so cirka bei 300-400 Dps irgendwo einpendeln. Passt etwa zu den 450 Dps eines MM Hunters im T2 Standart. "

erklär mir bitte dann meine 249dps mit allem drin was geht?

**Comment by lysop** [comment]
sabbaer hat recht ich war mit meim guffel hunter dabei selbst der hat mehr dmg gemacht^^

**Comment by Haudraufinix** [comment]
Deine Skillung wird nicht unspielbar. Es ist ja nicht so als ob du kein SoC mehr hast, du machst lediglich weniger Schaden als es bis jetzt der Fall war. Falls es dir nicht aufgefallen ist. JEDE Klasse die Spelldmg macht (Schurken und Jäger eingeschlossen) haben neuerdings mit Resistenzen zu kämpfen.

Die einzige Klasse die von diesem Nerv nicht begroffen war ist der Krieger.
Nur weil du hier Beweise anschleppst, die sich nicht einmal gegenseitig Decken, sondern sogar widersprüchlich sind braucht der Pala keinen weiteren Buff.

Fehlende Debuffs auf dem Boss, falsches Positioning, Spielfehler (Soll in den besten Familien vorkommen), Schlechte RNG das alles sind Faktoren die deinen DPS auch an einem guten Wipefreien Raidabend senken können.
Hast du mal überprüft, ob die Streitkolbenspezialisierung des Menschen richtig funktioniert? ansonsten verlierst du etwa 5-10% Schaden ohne offensichtliche Fehler.

@ Iysop Du kriegst als Jäger die Setboni der T2 Jäger ab (450 Distanzangriffskraftporocc) Die pushen deinen DMG auch wenn du lvl 1 gear hast um je 32 Dps wenn aktiv, sind Stackbar und skallieren mit Crt - Have Fun

**Comment by hraesvelgr** [comment]
man muss dazu sagen, dass wir oft nicht wissen, aus welchen patches diese guides sind. es gab nämölich mal holy resistance, aber keine arcane resistance. das wurde dann getauscht.

**Comment by 0815Priester** [comment]
leider französisch ^^ aber man sieht die partial resists. Ich denke die " Level based resists " also Player -> Npc, die man nicht weg bekommt, betreffen alle Zauberarten.

https://www.youtube.com/watch?v=ovhRqAxnXqg

**Comment by Sabbaer** [comment]
reopen, naxx bosse, patch 1.12: https://www.youtube.com/watch?v=VEs9coe5XRg
loatheb auch kein einziger teilresist, 
original videos
