### ISSUE TITLE
Erzvorkommen und Kräuter Spawnen zuviel 

### ISSUE THREAD

**Issue by Kazzard** [ClassicWoW/Nefarian_1.12.1_Bugtracker#648]
Moin zusammen,

Ich versuch mal zu erklären ^^
Also  die Erze und die Kräuter Spawnen ganz krass gesagt in Massen , oder sogar ineinander 4-7 mal
und ich find das ist ein zu Krasser überschuss an Mats die man Farmen kann ! gut zum Skillen
Schlecht für den Handel! 5 Meter laufen und man hat 5-6 spawn punkte gefunden bei Kräuter gibs noch übertriebene Stellen . 

Am besten Je höher das erz desto seltener sollte die Spawn gescheige den Silber/Gold/Echtsilber 

Ich hoffe ihr wisst was ich meine ^^

mfg
Kazzard

**Comment by Haudraufinix** [comment]
Wir wissen genau was du meinst, Antwort: NEIN
KEINER kann genau sagen, wie die Kräuter schlussendlich spawnen müssen. Ich denke bei den Highlevel Kräutern passts im Moment etwa. Die Lowkräuter sind halt extrem oft vertreten, weil sie schlicht keine Sau mehr braucht.

Wenn du Blizzlike Kräuter willst, wäre hier alles noch schlimmer zugeschissen mit Blumen. wir haben etwa 10% der Spieler eines Classic Offi Servers. Dann bräuchten wir vlt 8x so viele Kräuter wies im Moment gibt.

**Comment by Kazzard** [comment]
Ich hatte Ja auch früher zu classic zeiten gespielt und so voll "geschissen" war das nicht .
Beim Erz würde ich ja nur Sagen das man die Erze Silber/Gold/Echtsilber Seltener macht da diese difinitiv zu extrem viel Spawnen und das macht das Erz nicht mehr selten .

Und es gibt Spieler die gerne Farmen und damit Handeln wollen .

mfg
Kazzard

**Comment by Haudraufinix** [comment]
Auf Blizzardservern wars nicht vollgeschissen weil da 10x so viele Leute gefarmt haben wollte ich damit ausdrücken! Gespawnt sind trotzdem mehr Kräuter als hier.
Ausserdem kann man nichts flicken, wenn man nicht weis, wie es ganz sein sollte. Wie viel Kräuter pro Stunde sollten denn spawnen? Abhängig von der Spielerzahl im Gebiet oder nicht? abhängig von der anzahl gepflückten Kräuter oder nicht? Spawnt auf jedes ausgerissene Kraut jeweils das selbe Kraut nach?

Man weis NICHT, wie genau es sein sollte, und nach Gefühl fixen kommt nie gut raus. Bring ne Quelle die genau besagt, wie viele Kräuter dass spawnen und es wird umgehend gefixt, vorher kann ich auch Argumentieren, dass Eichhörnchen in Classic zu 10% Chance n Rnd Epic gedroppt haben

**Comment by Wosser** [comment]
Ein Stack Traumblatt kostet zur Zeit etwa 20g, ein Stack Gromsblut sogar 30g. Wenn du findest, dass es zu viele Kräuter gibt, dann heißt das dass du die preise für die Kräuter zu billig findest. Welche Preise hälst du denn für angemessen?
