### ISSUE TITLE
Thoriumgranaten fehlerhaft y0

### ISSUE THREAD

**Issue by cionex** [ClassicWoW/Nefarian_1.12.1_Bugtracker#649]
Was wird beobachtet:

Wählt ein Spieler eine Thoriumgranate und den Targetkreis an und wird anschließend von einem Spieler gestunt oder betäubt, so kann der Spieler die Granate trotzdem casten. Ein Vorteil von z.B. Schurken mit Nierenhieb kann dadurch komplett aufgehoben werden.

Wie sollte es sich verhalten:

Nach dem Anwählen der Granaten kann die eigentliche Granate im Stun nicht mehr gecastet werden bzw. wird der Cast durch den Stun unterbrochen!

Wie kann man den Bug reproduzieren:

Granate anwählen und Targetkreis auf Spieler legen, anschließend stunnen lassen und die Granate casten -> Die Granate wird trotz Stun ausgeführt.

http://datenbank.welli-it.de/?item=16041

**Comment by SirBeansen** [comment]
der bug ist neu...das betrifft nicht nur granaten sondern alle cast solange man im direkten sichtfeld ist. Habe das auch auf video aber kein bock hochzuladen =).

Aber wer es selber testen will.

Spieler 1 cc´t (Stun, sheep, falle, blind, scatter) Spieler 2 während spiler zwei als beispiel einen frostblitz castet. Wie der frostblitz castene Spieler in zb eine Eisfalle gestellt castet er trotzdem seinen zauber fetig obwohl er keine kontrolle über seinen char mehr hat.

Den bug gab es vorher auch schon doch ist er durch die letzten patchs noch extremer geworden. Ich denke das liegt dan den "succubus castet auch im CC verführung" fix.

Wenn man als Hunter einen warry Scattert und in sein direktes sichtfeld läuft während er orientierungslos herumspackt kann er einem trotzdem noch Kniesehne und co drücken.

Geht auch bei blind, sheep, fear und co.

**Comment by wahaxlekuke** [comment]
Ich kann nix von dem was ihr beschrieben habt reproduzieren. Ihr müsst also mal ein Video machen.

**Comment by cionex** [comment]
Sag mal Bescheid wenn du online bist @wahaxlekuke 
Und pack ein paar Granaten ein :dancer:
