### ISSUE TITLE
Auge von Kilrogg

### ISSUE THREAD

**Issue by Kadoing** [ClassicWoW/Nefarian_1.12.1_Bugtracker#650]
Das "Auge von Kilrogg" vom Hexenmeister ist nicht beschwörbar.
Kommt immer ein Text "Ich seit nicht für den Zauber nicht berechtigt"  oder so ähnlich.

MfG

**Comment by Gnomorus** [comment]
Ist kein Bug, sondern ein Feature!

**Comment by Gizmodragon** [comment]
Wie darf man das mit dem "feature" verstehen? Soll das Ironie sein? Ich nutze den Spell eigl. sehr gern.

**Comment by Rushor** [comment]
ironie ist das.. herrje xD

**Comment by Gnomorus** [comment]
Kann mich erinnern, dass der Zauber im Sommer gleichzeitig mit dem Trank XYZ Vision, der auch so ein Auge beschwört, deaktiviert wurde, weil sie im Verdacht standen, den Server zu crashen.

**Comment by Gizmodragon** [comment]
Endlich mal eine Antwort mit der man was anfangen kann.  Danke dir für die Info.  Sollte es an etwas anderes liegen,  immer her mit den Informationen,  sofern man auch etwas damit anfangen kann.  Und kein sinnloser Müll.

**Comment by wahaxlekuke** [comment]
Dieses Item hat den Server möglicherweise zum crashen gebracht:
http://datenbank.welli-it.de/?item=13508
Ich werde mir das demnächst nochmal anschauen.
