### ISSUE TITLE
[Druide] Charakter wird kurze Zeit nach dem Gestaltwandel wieder zurückgesetzt

### ISSUE THREAD

**Issue by Tuary** [ClassicWoW/Nefarian_1.12.1_Bugtracker#651]
Titel: [Druide] Charakter wird kurze Zeit nach dem Gestaltwandel wieder zurückgesetzt

Welches Verhalten wird beobachtet?

Wechselt man als Druide im Lauf seine Gestalt ohne dabei anzuhalten, kann es passieren (nicht immer), dass man eine kurze Zeit nach dem Weiterlaufen in Tiergestalt wieder zurück an den Ort gesetzt wird, an dem der Gestaltwandel vollzogen wurde.
Besonders häufig tritt der Fehler bei der Katzengestalt in Verbindung mit Spurt auf.
Lässt man es auf viele demonstrative Gestaltwandel hintereinander ankommen, wird man nach
dreimal Zurücksetzen vom Server gekickt. 
Der Fehler tritt sowohl mit 4 Setteilen des blauen PvP Sets (Geschwindigkeit von Bären, Katzen- und Reisegestalt draußen um 15% erhöht) als auch in normaler Rüstung auf.

Wie sollte es sich verhalten?

Bereits zurückgelegter Weg nach dem Gestaltwandel, sollte nicht dazu führen wieder zurückgesetzt zu werden.

Schritte zur Reproduzierung

siehe Videos:
(Die eingebetteten Videos sind von der Quali besch...eiden, falls notwendig also die Originaldatei downloaden)

https://www.dropbox.com/s/iefx2jlevbp00r7/druid_shapeshifting_bug1.mp4?dl=0

- bei Gestaltwandel drei, vier und fünf ist der Bug zu sehen

https://www.dropbox.com/s/ar689ouks0865nf/druid_shapeshifting_bug2.mp4?dl=0

- und der Bug nochmal nach Aktivierung von Spurt

Links:

Bärform: http://datenbank.welli-it.de/?spell=5487
Terrorbärform: http://datenbank.welli-it.de/?spell=9634
Katzenform: http://datenbank.welli-it.de/?spell=768
Spurt: http://datenbank.welli-it.de/?spell=9821
Reiseform: http://datenbank.welli-it.de/?spell=783
PvP Boni: http://datenbank.welli-it.de/?item=16397

Beste Grüße
Tuary

**Comment by Haudraufinix** [comment]
Ein ähnliches Verhalten tritt auch beim Aspekt des Geparden auf, vor allem wenn man ihn beim betreten von Gebäuden einsetzt. Ich gehe mal davon aus, dass noch mehr Geschwindigkeitsbuffs davon betroffen sind

**Comment by Ghulfang** [comment]
Das passiert auch wenn man während des reitens sein Reit-Gear anzieht

**Comment by Larnak1** [comment]
Das hat glaube ich etwas mit dem Anticheat-System zu tun, das die Geschwindigkeit prüft (?). Als das eingeführt wurde, wurden sehr viele "außerordentlichen" Geschwindigkeitsvorteilen (Reitboni, Setgeschwindigkeitsboni, ...) noch gar nicht erkannt, was zu heftigen Problemen führte. Das wurde sehr schnell behoben, seitdem kommt es aber selten zu dem oben beschriebenen Effekt. Ich glaube bei Blinzeln kann das auch passieren und bei "Wilde Attacke" habe ich das auch schon erlebt.

**Comment by dagochen** [comment]
Ja hat mit dem Anti-Speedhack zu tun, zeitlich passt es und das mit dem Serverkick was Tuary beschrieben hat, passt auch in die Kategorie.

**Comment by WCPaco** [comment]
Kann das bestätigen. Extrem nervig als Flag-Carrier im Warsong. Vor allem die DC's wenn man oft hintereinander shapeshiftet, da man dann logischerweise die Flag verliert. Bitte schnellstmöglich beheben. Danke!

Gruß Paco

**Comment by wahaxlekuke** [comment]
Tritt das Problem im Moment immernoch auf?

**Comment by Tuary** [comment]
Also bei mir ist es heute den ganzen Tag noch nicht aufgetreten.
Dankeschön für's beheben.

Grüße
Tuary

**Comment by Larnak1** [comment]
Wie passend dass du gerade jetzt fragst. Hatte es vorhin in ZG in Katzengestalt (30% Outdoor-Bonus). Stand ganz normal rum, wollte loslaufen und Zack war ich wieder da, wo ich vorher stand. Ist gut möglich, dass es seltener geworden ist, ganz weg ist es aber noch nicht.
