### ISSUE TITLE
Runenverzierte Ruten (Verzauberkunst)

### ISSUE THREAD

**Issue by Icebeaver** [ClassicWoW/Nefarian_1.12.1_Bugtracker#653]
So, folgendes Problem:

Hab mir letztens die Runenverzierte Arkanitrute gebaut,
und dann natürlich vorher die Runenverzierte Echtsilberrute verkauft.
Tag darauf will ich eine Verzauberung wirken und siehe da funktioniert
nicht, da diese die Runenverzierte Echtsilberrute benötigt!!!
So, nochmal nachgeschaut im Tooltip:

Runenverzierte Arkanitrute
''Kann auch wie jede geringere Runenverzierte Rute verwendet werden''

FUNZT ABER NICHT, und das bei keiner
(wenn ich einen low enchant machen will, brauch ich wieder die Runenverzierte Kupferrute, etc...)

Lg Icebeaver

**Comment by Cleptomaniac** [comment]
bekanntes problem #421

**Comment by Larnak1** [comment]
Der Tooltip ist fehlerhaft und sollte gemäß #621 eigentlich schon angepasst worden sein. Da hat wohl irgendwas nicht geklappt. In der Web-Datenbank ist der Tooltip korrekt, im Spiel aber nicht.

**Comment by hraesvelgr** [comment]
weils wohl ein clientseitiges problem ist.

**Comment by dagochen** [comment]
Vielleicht den WDB Ordner löschen?

**Comment by hraesvelgr** [comment]
bringt da auch nix. genausowenig, den WTF zu  löschen. liegt wohl direkt an den spieldateien.
