### ISSUE TITLE
Siegel des Kreuzfahrers / Manaverbrauch / Elitegegnerstärke

### ISSUE THREAD

**Issue by ErnisKommentar** [ClassicWoW/Nefarian_1.12.1_Bugtracker#654]
Habe den Eindruck, dass Siegel des Kreuzfahrers so gut wie gar nichts bewirkt. 

https://www.youtube.com/watch?v=l2mJVooeANs

Wie man erkennt, plättet er Level 55-Elite-Gegner solo, ohne dass er wirklich viel SChaden machen würde. Da kommen wir auf das Thema von mir zurück, dass viele Elite bei euch zu stark sind, zumindest wenns ums Questen geht, während die Elite in den Instanzen eindeutig zu lasch sind.

Ach so und man erkennt, dass die Gegner Siegel des Kreuzfahrers nicht widerstehen. Hab ich während des Videos jedenfalls nicht einmal gesehen.

Was bedeuten solche Sprüche wie "bis zu", beispielsweise bei Siegel der Rechtschaffenheit oder Siegel des Kreuzfahrers. Nun, der tatsächliche Schadensschub ist von der Geschwindigkeit der Waffen abhängig. Deshalb sollte ein Vergelter durch eine sehr langsame Waffe auch den maximalen Schadensschub erhalten. Keine Ahnung wie das im Moment berechnet wird, aber es wird definitiv auf diesem Server zumindest nicht richtig berechnet. Langsamere Waffen bedeuten auch eine erhöhte Chance, dass Siegel des Befehls ausgelöst wird - normalerweise.

Mir ist durchaus klar, dass man um solche Spielmechanikfehler zu beheben sehr tiefe Kenntnisse besitzen muss. Es ist also ziemlich schwer. Insofern wäre ich nicht mal sauer, wenn ihr das nicht hinbekommt, ganz im Gegensatz zu den zahlreichen Fehlern, die wie gesagt zu 90% sehr leicht alleine über Datenbankänderungen zu beheben wären, die ihr aber jahrelang im Spiel lasst. Warum weiß niemand. Ihr könnt hier eine super Weltnetzseite kreieren, offenbar einen Server ins Netz stellen und warten, ihr bemüht euch dort auch redlich jede kritische Stimme zu bannen, scheint ihr von Blödzart gelernt zu haben, was unheimlich viel Aufmerksamkeit und Zeit erfordert, aber die 5 Minuten täglich, die notwendig wären, um einen Fehler in der Datenbank zu beseitigen, opfert ihr nicht.

Schon seltsam. Na ja, ein paar Dinge funktionieren auf eurem Server tatsächlich besser als auf anderen, was bedeuten könnte, dass ihr tatsächlich programmieren könnt, aber wie gesagt erklärt es in keinsterweise warum ihr die zahlreichen leicht behebbaren Fehler hartnäckig im Spiel lässt. Wollt ihr eure Spieler trollen oder habt ihr Angst zu erfolgreich zu werden? Wie gesagt mit etwas Engagement wäre der SErver hier zumindest was Quests und Skripts angeht oder andere Datenbankfehler so gut wie fehlerfrei. Das kann man im MOment leider nicht sagen. Viele Quests funktionieren nicht oder sie fehlen schlicht und ergreifend. Viele Gegner sind falsch geskriptet. Die Antworten sind irgendwo da draußen. Besser gesagt in den DBC-Dateien. Selbst wenn die Quests fehlen, dort sind sie drin, aber gut ihr habt daran kein INteresse. Hab ich schon verstanden. Deshalb bleiben auch die einfachsten Fehler, die aber sehr nervig sind, im Spiel.

Jedenfalls sieht man hier auch, dass der Paladin sich nicht mal heilen muss und einen guten Manastand hat, obwohl er gegen Elite kämpft. Etwas, was auf eurem Server leider nicht der Fall ist, weil der Manaverbrauch bzw. die Regeneration falsch ist. Normalerweise sollte das Spielen mit einem Charakter in einem Rollenspiel mehr Spaß machen je höher das LEvel ist, bei euch wirds mit Level 60 zu einer Tortur, weil der Manaverbrauch speziell beim Paladin einfach zu krass ist. Und ich nutze mit Sicherheit mehr Möglichkeiten, genauer gesagt alle vorhandenen, um Mana zu sparen als dieser Paladin hier im Video. Ich hab mir Sachen programmiert per Makro und Addons, die je nach Manastand den optimalen Rang meiner Zauber nutzen. Das hat der hier mit Sicherheit nicht gemacht.

Was auch auffällt, dass das Trinken zu langsam das Mana auffüllt. Das liegt daran, weil leider eine reduzierte Manaregenerationsrate in mongos.conf alle Manaregenerationen reduziert, also auch die über das Trinken. Wodurch es doppelt nervig wird.

**Comment by dagochen** [comment]
1. ClassicWoW benutzt kein Mongos!

2. Der Pala im Video ist ja mal überhaupt nicht repräsentativ. Er bufft sich nicht mal selbst mit SDM oder so...und Raidbuffed paar Mobs hauen gehen ist doch klar, dass er mehr HP/MANA und so hat als du...? Anstatt zu meckern solltest du mit deinen 10 Jahren Erfahrung vielleicht lieber Guides für die Leute schreiben, die nicht wissen wie man als Paladin irgendwelche Mobs solo umhaut. Gerade du, mit deinem nahezu unendlichen Wissen solltest doch in der Lage sein, alles was nicht in einer Instanz ist, solo umzuflexen?

Gruß,
dago

**Comment by hraesvelgr** [comment]
warum verwendet man zeit darauf, so einen text zu schreiben? ist doch klar, dass t2 platte (buffed) weniger schaden bekommt, als zb eine undergeared katze, oder ein shadow. das ist...irgendwo einfach nur logik.
