### ISSUE TITLE
[Hunter] Totstellen

### ISSUE THREAD

**Issue by Xardor2492** [ClassicWoW/Nefarian_1.12.1_Bugtracker#655]
Hallo, folgendes ist mir im PvP aufgefallen,

Jäger, die die Fähigkeit Totstellen aktiviert haben, können nicht von Flächeneffekten getroffen werden. Sei es mal am Beispiel des Magiers genommen: Arkane Explosion oder Kältekegel

reproduzieren kann man das am Besten in einem Duell. Jäger Totgestellt, Pet daneben. Den entsprechenden Zauber gewirkt, dann sieht man wie das Pet Schaden erhält, aber der Jäger nicht.

Wie sollte es sich verhalten?
Wenn ein Jäger sich totstellt, springt der Spieler aus dem Target.

Quelle: der Tooltip sagt alles. http://de.wowhead.com/spell=5384/totstellen

**Comment by wahaxlekuke** [comment]
Irgendwelche Quellen, dass das nicht so sein soll?

**Comment by Nobugsanymore** [comment]
http://www.wowwiki.com/Feign_Death?oldid=322223 
Kein Wort davon, dass man durch Feign Death immun  gegenüber AoE-Zaubern werden sollte.
Außerdem kann das im Moment auch im pve missbraucht werden um Mechaniken bestimmter Bosse mit Flächen-Schaden zu umgehen.

**Comment by Haudraufinix** [comment]
*No combat log message is generated, your pet will not disappear, and no honor points are granted so any experienced PvP opponents will notice that you are not really dead. While players will lose targeting if they have you targeted when you feign, they can still retarget you and attack you while you are feigning death.*

Heisst das man genau gleich weiter Angegriffen werden kann. Da für AE Zauber keine Targetwahl nötig ist, sollte man Dennoch von AE Zaubern wie dem Feuer von Vaelestraz getroffen werden können. Hingegen wird man Totgestellt von Mobs nicht ins Target genommen(Es sei denn, Totstellen hat widerstanden). Einzelzielzauber wie "Lebendige Bombe" oder "Brennendes Adrenalin" können daher nicht aufgetragen werden.

**Comment by hraesvelgr** [comment]
also...der bugreport sagt schon eindeutig, dass es momentan falsch ist, weil der hunter NICHT getroffen wird.

**Comment by dagochen** [comment]
Einige AoE-Effekte treffen, es ist definitiv nicht so, dass man immun gegen alles ist. Ich bin der Meinung, dass aktuell alle Zauber treffen, die in irgendeiner Form "targeted" sind, sprich Zauber, die eine Position haben, an die sie gezaubert werden (Salve z.B.). Ob das so korrekt ist oder zu Classic anders war, sollte vielleicht mit Hilfe eines Videos bewiesen werden?
