### ISSUE TITLE
[Priester] Volk Zwerg, Zauber Furchtschutz

### ISSUE THREAD

**Issue by Xardor2492** [ClassicWoW/Nefarian_1.12.1_Bugtracker#656]
Hallo,

folgendes Problem, der Furchschutz funktioniert nicht. 

Was wird beobachtet: Hexer zaubert Furcht, trotz aktiviertem Buffs wird man gefeart, Buff bleibt erhalten. (Kriegerfear hat denselben Effekt).

Wie sollte es sich verhalten: Hexer zaubert Furcht. Gebuffter Spieler ist Immun, Buff verschwindet

**Comment by hraesvelgr** [comment]
fearward: http://datenbank.welli-it.de/?spell=6346

**Comment by wahaxlekuke** [comment]
Den Bug kann ich auf dem Test-Server leider nicht repoduzieren. Ein Video davon wäre ganz gut.
