### ISSUE TITLE
BWL: Vaelastrasz, Tankwechsel --> 360° Drehung & Resistenzen

### ISSUE THREAD

**Issue by Nightfly385** [ClassicWoW/Nefarian_1.12.1_Bugtracker#657]
Welches Verhalten wird beobachtet?

Nachdem der aktuelle MT "Burning Adrenaline" erhält und sich der nächste MT auf die Tank-Position begibt, passiert es, dass beim Tod des aktuellen Tanks, Vaelastrasz sich einmal schnell um 360° dreht und erst dann auf den nächsten Tank geht. Bei der 360° Drehung wird der Rest des Raids aufgrund seines Tail Sweeps durch den Raum gekicked. 
Ebenso haben viele Melees berichtet, dass sich die Hitbox verändert habe und man nun den Cleave sehr schnell abbekommt. 

Ein weiterer Punkt sind die neuen Resistenzen. Im Vergleich zu anderen Kills früher (3-8 Wochen) ist der Caster-DMG schon gut eingebrochen. 

Wie sollte es sich verhalten?

Vaelastrasz sollte sich beim Wechsel des MTs nicht um 360° drehen...

Das die Resistenzen angepasst bzw. hinzugefügt wurden ist ja gut und schön nur dann bitte im Rahmen oder ihr passt die HP von den Bossen an. Hier auf dem Server hat Vaelastrasz 6,95 Mio. HP . Auf den Offis waren es 3,3 Mio HP (http://www.wowhead.com/npc=13020/vaelastrasz-the-corrupt) (http://www.hordeguides.de/Schlachtzug/Classic/Boss/13020/Vaelastrasz-der-Verdorbene/index.htm)

Das soll jetzt nicht heißen das ihr 3 Mio HP entfernen sollt!!! Aber wenn ihr schon an den Resis der Mobs schraubt, dann beachtet wenigstens den HP-Pool der Mobs. Dotox hat vor über einem Jahr extra die HP der Mobs in BWL angehoben, da es zu Beginn in BWL zu einfach war, was auch richtig gewesen ist. Wenn nun die Resistenzen/Rüstungswerte angepasst sind könnte man überlegen den HP-Pool auch anzupassen und wenn es nur minimal ist.
Dies bezieht sich jetzt nicht nur auf Vaelastrasz, sondern betrifft auch andere Boss-Mobs.

LG
Nightfly (Inheritance

**Comment by dagochen** [comment]
@Nightfly385 
Kannst du bitte hier mal drüber schauen und Bescheid geben, was davon noch aktuell ist. Es gab einige Änderungen an den Movement-System. Und die Resisten-Sache wurde ja auch mehrfach überarbeitet und sollte inzwischenn vom Tisch sein.
