### ISSUE TITLE
Blenden verbraucht Muniton

### ISSUE THREAD

**Issue by cionex** [ClassicWoW/Nefarian_1.12.1_Bugtracker#660]
.. ich weiß ist ewig alt und im Forum schon reportet. Trotzdem wollte ich es hier zur Übersicht im Bugtracker einfügen.

Was wird beobachtet:
Gewisse Fähigkeiten des Schurken wie z.B. Blenden oder Falle entschärfen verbrauchen neben den dafür üblichen Materialien wie Blendungspulver auch Munition für Bögen oder Schusswaffen die man bei sich trägt.

Wie sollte es sich verhalten:
Die Fähigkeit "Blenden" sollte zwar Blendpulver verbrauchen nicht jedoch die bei sich geführte Munition aufzehren.

Reproduktion?
Schurke inkl. Munition im Inventar > Spieler blenden.

**Comment by hraesvelgr** [comment]
http://datenbank.welli-it.de/?spell=2094

**Comment by cionex** [comment]
@wahaxlekuke Hey Wahax, kannst du mich Ingame anschreiben, wenn du da bist? Gerade was nettes bzw. nicht nettes entdeckt.

**Comment by dagochen** [comment]
Seit dem Fix verbrauchen Fähigkeiten vom Hunter wie z.B. Arkaner Schuss und Schlangenbiss keine Munition mehr.

Man könnte also bei 
```c++
void Spell::TakeAmmo()
```
aus
```c++
        if (!pItem || pItem->GetProto()->SubClass == ITEM_SUBCLASS_WEAPON_WAND)
            return;
```
folgendes machen: 
```c++
if (!pItem || pItem->GetProto()->SubClass == ITEM_SUBCLASS_WEAPON_WAND || m_spellInfo->Id == 2094)
            return;
```

Dann wird Blenden genau wie Zauberstab ohne Munition ausgeführt und die Hunter-Schüsse sind nicht betroffen.

**Comment by Dotox** [comment]
Die Idee von @dagochen könnte funktionieren. Ich hab Blenden und Falle entschärfen mal mit in die Abfrage aufgenommen. Wenns weitere Zauber gibt, bitte hier aufzählen!

**Comment by dagochen** [comment]
Bei Falle entschärfen ist das mit der Munition verbrauchen bei mir nicht reproduzierbar gewesen (und auch mein Schurke auf Nefarian hat dabei keine Munni verbraucht!). Daher ist der Fall nicht notwendig denke ich.
