### ISSUE TITLE
Jäger: Teleport beim Wechsel zwischen Aspekten

### ISSUE THREAD

**Issue by Jizzl3** [ClassicWoW/Nefarian_1.12.1_Bugtracker#661]
Was wird beobachtet:

Beim Laufen und Wechsel zwischen folgenden Aspekten wird der Spieler ca. 1 Meter zurück teleportiert:

- Aspekt des Falken
- Aspekt des Affen
- Aspekt des Geparden
- Aspekt des Rudels

Wie sollte es sich verhalten:

Der Wechsel sollte keinerlei Effekt auf die Positionierung des Spieler haben.

Wie kann man den Bug reproduzieren:

Laufen und zwischen den oben genannten Aspekten Wechseln.

**Comment by Acolatronico** [comment]
das selbe problem haben paladine beim wechseln ihrer aura auch

**Comment by Haudraufinix** [comment]
Siehe hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/651

**Comment by dagochen** [comment]
Bitte nicht jede Klasse ein Ticket dazu aufmachen, es handelt sich hier um ein klassen-übergreifendes Problem mit der Anti-Speedhack-Erkennung.
