### ISSUE TITLE
Schlammiger Beutel: Lässt sich nicht handeln und versenden nach dem öffnen

### ISSUE THREAD

**Issue by Mamoc1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#662]
Was wird beobachtet:

Der Gegenstand "Schlammiger Beutel" lässt sich nach dem öffnen nicht mehr Handeln und Versenden.

Wie sollte es sich verhalten:

Handeln und Versenden muss auch nach hineinsehen/öffnen und nicht looten des Inhalts möglich sein, da dieser Beutel nicht verschlossen ist und auch nicht gebunden wird durch einmaligees hineinsehen.

Wie kann man den Bug reproduzieren:

Einen "Schlammiger Beutel" ungeöffnet Handeln oder Versenden und dann die Gegenprobe machen nachdem man einmal hineingeshen hat.

**Comment by hraesvelgr** [comment]
http://www.wowhead.com/item=20768/oozing-bag#comments:id=158038
By Muzzer (307 – 1·2) on 2007/09/25 (Patch 2.2.0)		
Apparently you can send these to another character and the contents will change. So if you open one up and there isn't a pet inside, send it to an alt and open it up on that char and you may get lucky.

Contents can only change once though

**Comment by ircfelix** [comment]
(Patch 2.2.0)

**Comment by hraesvelgr** [comment]
(zeig mir die patchnotes, in denen der beutel geändert wurde) :^)

**Comment by Mamoc1** [comment]
Also, es geht nicht darum den Beutel zu versenden weil kein Pet drin ist um dann mit einem anderen Charakter reinzuschauen ob dann vieleicht ein Pet drin ist.
Es geht darum, dass ich mit einem Charakter das Pet bereits besitze und nun noch einen Beutel mit diesem Pet gefunden habe. Da dieses Pet aber einzigartig ist, kann ich es nicht aus dem Beutel heraus nehmen. Also möchte ich den Beutel samt Pet an einen andern Charakter senden, damit dieser dann auch das Pet hat.

Ich kann den Beutel aber nicht versenden, da dann eine Fehlermeldung kommt. Auch handeln kann ich ihn nicht, der Handel wird dann sofort abgebrochen. Das ist definitiv ein Bug. Denn wenn man in  einen "Schlammigen Beutel" nicht hinein sieht, kann man ihn versenden und Handeln. Nach dem hineinsehen nicht mehr, obwohl sich am Beutel ja nicht geändert hat, er ist ja nicht gebunden oder so, nach dem hineinsehen.

Leider will mir da kein GM helfen, das finde ich echt schade.
