### ISSUE TITLE
Vaelastrasz ignoriert Druiden als Aggrohalter

### ISSUE THREAD

**Issue by WCPaco** [ClassicWoW/Nefarian_1.12.1_Bugtracker#663]
Welches Verhalten wird beobachtet?

Nach nun einigen BWL-ID's in denen ich als Druiden-Tank dabei war ist mir und einigen anderen auch aufgefallen, dass scheinbar was beim Aggroverhalten des Druiden (implizit bei Vaelastrasz) nicht stimmt. Egal mit welchem Vorsprung ich im KTM Erster bin ich bekomme nie die Aggro von ihm. Er scheint mich einfach zu ignorieren. Alternativ stimmt was bei der Berechnung der Aggro-Spells nicht, was ich aber im Großen und Ganzen ausschließe, weil ich dieses Verhalten bisher nur so extrem bei Vael feststellen konnte.

Wie sollte es sich verhalten?

Der Druiden-Tank sollte in der Aggro-liste bei Vaelastrasz berücksichtigt werden.

Schritte zur Reproduzierung

Vaelastrasz als Druide versuchen zu tanken. Wobei ich erwähnen möchte, dass ich nie als 1. Tank vorgesehen war. Vllt. teste ich das beim nächsten mal.

Links:

Vaelastrasz: http://datenbank.welli-it.de/?npc=13020

Gruß Paco

**Comment by Haudraufinix** [comment]
Ich glaube es liegt an der Aggro die durch Maul/ Zermalmen (http://datenbank.welli-it.de/?spell=9881) generiert wird.
*Patch 2.0.3 (09-Jan-2007): Maul has had its threat bonus multiplier changed to a flat value similar in threat per time to Heroic Strike. Threat generation was changed from a 1.75 damage multiplier to a static +threat component*
aus WoWWiki (http://www.wowwiki.com/Maul) beweist, dass Maul Zu Classic einen immensen Aggroboost hatte. Zusammen mit dem Aggro Multiplyer 1.3 vom Terrorbären (http://datenbank.welli-it.de/?spell=9634) heisst das: Ein Maul vom Druiden müsste 2.275 fache Aggro des Schadens verursachen.
Mir ist selbst auch aufgefallen, dass der Druide nach dem Gefühl sehr viel weniger Aggro verursacht als er sollte.
Quelle zu Aggrobonus: http://www.wowwiki.com/Dire_Bear_Form -> Beachte: Keine Changelogs zum Aggrobonus!

**Comment by WCPaco** [comment]
Die Berechnung und die tatsächlich Aggro-Generation kommt mir jetzt nich falsch vor hier aufm Server. Wenn ich jetzt nich gerade Miss/Dodge Pech habe kann ich in der Regel schon einen Krieger-Tank abhängen. Nur bei Vael ist das Problem, dass ich völlig ignoriert werde.

**Comment by WCPaco** [comment]
Gestern nochmal getestet und zwar als 1. Tank. Aggro direkt verloren als die anderen Tanks richtig eingestiegen sind. Da stimmt was ganz gewaltig nicht.

**Comment by nightblizard** [comment]
Nicht reproduzierbar
