### ISSUE TITLE
AQ40 vom 13.04.

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#665]
Trashmobs vor Bug-Trio/Sartura:
- Krieger der Vekniss (http://datenbank.welli-it.de/?npc=15230) setzt seine Fähigkeit Spalten nicht ein.
- Wächter der Vekniss (http://datenbank.welli-it.de/?npc=15233): Anstürmen der Mobs sieht sehr eigenartig aus: Der Charge ist stark verzögrert und durch Sloweffekte sehr langsam. Dadurch kann ihm im Charge ausgewichen werden.
-Packs in der Höhle vom Bug-Trio weist keine Verlinkung zu den Wächtern der Vekniss auf.

Bug-Trio:
- Prinzessin Yauj (http://datenbank.welli-it.de/?npc=15543): Es wird immer nur ein Speiler gefeart. Es sollten aber alle Spieler innerhalb eines 60y Radius getroffen werden (http://datenbank.welli-it.de/?spell=26580). Der Aggroreset des Bosses funktioniert. Wir konnten jedoch nicht sehen ob es mit dem Fear gleichzeitig ist. Außerdem heilt sie sich nur selbst und nicht ihre Verbündeten. (http://datenbank.welli-it.de/?spell=25807)
- Vem (http://datenbank.welli-it.de/?npc=15544): Nach seinem Ansturm kommt es oft zu einem weiteren Hit auf den Spieler und ist dann tödlich (http://datenbank.welli-it.de/?spell=26561). Während des Knockdowns sollte der Tank kurz die Aggro verlieren (http://datenbank.welli-it.de/?spell=19128).
- Allgemein: Der Encounter sollte zurückgesetzt werden, sobald ein Aggrohalter den Bossraum verlässt.

http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/AQ/aq-40-2.htm

Schlachtwache Sartura (http://datenbank.welli-it.de/?npc=15516):
- Sartura benutzt ihre Fähigkeit Rüstung zerreißen nicht (http://datenbank.welli-it.de/?spell=25174)
- Sartura sollte Stunnbar sein.
- Königswachen (http://datenbank.welli-it.de/?npc=15984): Sind anfällig für alle Slows und Crowdcontrols. Sollten aber nur stunbar sein.
- Der Encounter resettet nicht wenn man aus dem Raum läuft.

http://www.strike-us-if-you-can.de/main/frame/HighLvlRaid/AQ/aq-40-3.htm

Fankriss (http://datenbank.welli-it.de/?npc=15510):
- Aus der westlichen Nische Spawnen keine Jungtiere (http://datenbank.welli-it.de/?npc=15962).
http://www.hordeguides.de/images/maps/map_ahnqiraj40_fankriss.jpg
- Die Jungtiere spawnen teilweise auch aus den Seiten wo die Würmer (http://datenbank.welli-it.de/?npc=15630) herkommen.

Allgemein: Wenn man beim Friedhof vor AQ losläuft bekommt man immernoch einen Disconnect.

**Comment by hraesvelgr** [comment]
sartura und ihre wachen sollten stunnbar sein: NUR wenn sie NICHT im wirbelwind sind.
also bitte nicht dauerhaft stunbar machen.

**Comment by Haudraufinix** [comment]
* Sartura and her Guards can be stunned any time they are not spinning. Paladins can use hammer of justice, rogues use kidney shot, and warriors use concussion blow until diminishing returns kick in.

Quelle:
http://www.wowhead.com/npc=15516/battleguard-sartura#comments Kommentar von Omnistegan

**Comment by Seniorash** [comment]
Bei den Königswachen funktioniert es. Sobald sie den Wirbelwind casten bekommen sie auch den Buff wo explizit stunimmun steht (mit Magie entdecken sichtbar). Nur Sartura selbst ist komplett stunimmun.

**Comment by DrTonic** [comment]
Ich hoffe ich darf euren Thread für ein paar Ergänzungen "hijacken"; ich denke für die Devs ist das übersichtlicher, als wenn ich einen neuen Thread aufmache in dem zu 90% der selbe Kram steht.

Trashmobs vor Sartura
Wächter der Vekniss
Der Schaden durch Impale und den Knockup schien zu gering, leider finde ich keine Quelle zu den tatsächlichen Damage-Zahlen außer, dem nachfolgenden Schnipsel aus wowwiki.

They have a large knockup that can send players to their death upon landing; therefore, they are usually engaged beside a wall.
(http://www.wowwiki.com/Vekniss_Guardian)


Battleguard Sartura
Die Adds von Sartura haben bei unserem 1. Try korrekt nach 5 Sekunden Wirbelwind, wieder die entsprechenden Tanks ins Target genommen. Nachdem wir den Reset getestet haben, und uns Sartura und die Adds durch halb AQ gejagt haben, schien der Encounter verbugged zu sein (Position im Vorraum, Sartura kurzzeitig verschwunden etc.). Beim 2. Try hat der "Reset" nach 5 Sekunden nicht mehr funktioniert.

"Sartura and her adds will occasionally reset aggro for several seconds and start chasing random people for a duration of 5 seconds. After those 5 seconds they will return to the highest aggro target, so as long as you don't pull aggro off of the tank they will go back to him."
(http://www.wowwiki.com/Battleguard_Sartura)

Der Schaden nach dem Softenrage (20%), hat nicht zugenommen. (Auch beim 2.Try getestet, eventuell war es einfach bugged)

"Enrage: +124 physical damage, +60% attack speed."
(http://www.wowwiki.com/Battleguard_Sartura)


Fankriss
Der Mortal Wound debuff, der mit dem Cleave aufgetragen wird, tritt relativ selten auf. Ein Tank kann Fankriss bequem durchtanken, da Mortal Wound im Maximalfall auf 30% stackt und dann ausläuft. In der Regel ist kein Debuff auf dem Tank oder 1 Stack.

"Mortal Wound - Stackable debuff on the MT that reduces healing by 10%. This is a cleave attack so it can hit multiple people in front of him. Rotate him between two MTs to let this wear off."
(http://www.wowwiki.com/Fankriss_the_Unyielding)


Der Teleport von Spielern zu den Adds funktionert beim 1. Mal wie gewünscht (gleichzeitig zum Spawn der Adds). Die restlichen Ports kamen zu spät, nachdem die Adds schon "rausgelaufen" waren. 

"There are 3 "bug tunnels" around the room. Starting shortly after the pull then once every minute or so, each tunnel will spawn 4 Vekniss Hatchlings. With each spawn, one player will be ported and rooted in one of the small alcoves around the room."
(http://www.wowwiki.com/Fankriss_the_Unyielding)

**Comment by DrTonic** [comment]
Noch ein paar Ergänzungen, welche ich nicht direkt verifizieren kann (keine Quellen, nicht immer reproduzierbar etc.). Also vllt. als Anhaltspunkte nützlich:
- Sartura kann scheinbar nicht critten (kann keine Quelle finden, in der steht ob das so passt)
- Bei den Wächterpacks chargen nicht alle Wächter nach dem Tod (evtl. gab es ein LOS Problem)
- Die Dots der chargenden Wächter bekommen Tanks die in Range stehen nicht immer ab

**Comment by Seniorash** [comment]
Wir hatten in der Instanz Respawn der Trashmobs. Laut Hordeguide sollte das nicht so sein.

/q Alle in der Instanz getöteten Mobs respawnen nicht (mit Ausnahme des Tunnels vor Fankriss während des ersten Tages).

http://www.hordeguides.de/index.php?ra=3428

**Comment by Raso89** [comment]
Ausserdem verschiebt sich der Enragetimer der spawnenden Würmer mit der Zeit. Bei uns fing der Timer für Wurm 6 Bspw. an bei 15s wie gewünscht aber der Wurm kam erst bei ca 9.0s wobei er dann bei 0s trotzdem in den Enrage ging. Sprich irgendetwas am Timer hat sich da aufgehangen.
