### ISSUE TITLE
Dropraten BWL

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#666]
**Welches Verhalten wird beobachtet?**
Die Dropraten der meisten Items stimmen nicht ganz, Bosse droppen für Allianzraids Schamanenitems und umgekehrt.

**Wie sollte es sich verhalten?**
Sie sollten etwa so sein wie in den unten angegebenen Allakhazam Links.

**Schritte zur Reproduzierung**
Dropraten der Datenbank mit denen von Allakhazam vergleichen (siehe unten)

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Anmerkung: Ich vermute dass die Dropraten der Schamanen- und Paladinsetteile zu niedrig sind, weil ALLE Kills gezählt wurden, aber nicht alle Kills von der Horde bzw. von der Allianz selbst waren. Früher war es auch so, dass in einem Allianzraid keine Schamiteile gedropt sind und umgekehrt.
Vorschlag für die Paladin-/Schamanensetteile: Den Mittelwert der Dropraten aller T-Teile bilden und diesen dann verwenden.

Links zu Allakhazam:
**1** Razorgore: https://web.archive.org/web/20070114060619/http://wow.allakhazam.com/db/mob.html?wmob=12435
Mittelwert aus den 7 anderen T2-Dropraten: 19.60
Aus den Kommentaren (habe nach "drop" gesucht) geht hervor, dass er immer 3 Items dropt.

**2** Vael https://web.archive.org/web/20070127204006/http://wow.allakhazam.com/db/mob.html?wmob=13020
Mittelwert aus den 7 anderen T2-Dropraten: 19.07
Aus den Kommentaren (habe nach "drop" gesucht) geht hervor, dass er immer 2 Setteile und ein Offset Item dropt.

**3** Brutlord https://web.archive.org/web/20070220104600/http://wow.allakhazam.com/db/mob.html?wmob=12017
Mittelwert aus den 7 anderen T2-Dropraten: 15.09
Aus den Kommentaren (habe nach "drop" gesucht) geht hervor, dass er immer 2 Setteile dropt. Ob das dritte Item ein garantierter Drop ist oder nicht, konnte ich nicht rausfinden.

**4** Feuerschwinge https://web.archive.org/web/20070222070919/http://wow.allakhazam.com/db/mob.html?wmob=11983
Mittelwert aus den 7 anderen T2-Dropraten: 6.11

**5** Schattenschwinge https://web.archive.org/web/20070222070909/http://wow.allakhazam.com/db/mob.html?wmob=14601
Mittelwert aus den 7 anderen T2-Dropraten: 6.38
Aus den Kommentaren (habe nach "drop" gesucht) geht hervor, dass er 2 Items dropt, eines davon ist ein Setteil.

**6** Flammenmaul https://web.archive.org/web/20070222070848/http://wow.allakhazam.com/db/mob.html?wmob=11981
Mittelwert aus den 7 anderen T2-Dropraten: 6.39
Aus den Kommentaren (habe nach "drop" gesucht) geht hervor, dass er 2 Items dropt, es muss aber kein Setteil dabei sein (vielleicht hier eine einheitliche Regelung für alle drei Drachen finden?!?).

**7** Chromaggus https://web.archive.org/web/20070228095251/http://wow.allakhazam.com/db/mob.html?wmob=14020
Mittelwert aus den 7 anderen T2-Dropraten: 16.58
Aus den Kommentaren von https://web.archive.org/web/20070610134038/http://thottbot.com/c14020 (habe nach "drop" gesucht) geht hervor, dass er 2 Setteile dropt, 2 Nonsetteile und manchmal noch 1 non setteil. Ein anderer Kommentar auf thottbot spricht von 2 Setteilen, 2 nonsetteile aber nicht von dem 1 nonsetteil.

**8** Nefarian https://web.archive.org/web/20070228103029/http://wow.allakhazam.com/db/mob.html?wmob=11583
Mittelwert aus den 7 anderen T2-Dropraten: 13.22
Aus den Kommentaren war nicht ersichtlich wie viele Items er dropt.

**Links aus unserer Datenbank (hier gehts zur Datenbank)**
Links aus der Datenbank hier:
**1** Razorgore: http://datenbank.welli-it.de/?npc=12435
**2** Vael http://datenbank.welli-it.de/?npc=13020
**3** Brutlord http://datenbank.welli-it.de/?npc=12017
**4** Feuerschwinge http://datenbank.welli-it.de/?npc=11983
**5** Schattenschwinge http://datenbank.welli-it.de/?npc=14601
**6** Flammenmaul http://datenbank.welli-it.de/?npc=11981
**7** Chromaggus http://datenbank.welli-it.de/?npc=14020
**8** Nefarian http://datenbank.welli-it.de/?npc=11583

**Comment by Hexquantum** [comment]
Patch 1.12 ist der Pre-BC Patch. Dass die Horde Palaitems und die Allianz Schamanenitems bekommt ist Blizzlike 1.12. Darüber haben sich die Gilden damals auch aufgeregt. Ist zwar vollkommen retarded von Blizz , aber es ist kein Bug.

**Comment by ircfelix** [comment]
Wenn dass was du sagst stimmen würde,  dann wäre die droprate der pala und schamiteile in der allakhazam datenbank annähernd gleich. Dass sie sich so sehr unterscheiden ist die logische Konsequenz daraus, dass es schon immer mehr Allianzspieler in vanilla gab und weniger hordler. Dadurch haben weniger Hordler Bwl gesehen. Deswegen hat von den 21k gesamtkills das schami T2 die geringere dropchance. Darum kann es nur bei der Horde gedropt sein.  Schau dir die Zahlen mal an.

**Comment by Larnak1** [comment]
Der Pre-BC-Patch war 2.0.1, eine entsprechende Änderung dürfte also eher darin enthalten gewesen sein.

**Comment by Hexquantum** [comment]
@Larnak: Bitte keine Sachen in den Bugtracker schreiben, von denen du selber keine Ahnung hast ("dürfte also eher darin enthalten gewesen sein" gehört hier nicht hin).

@ircfelix : Bei der Dropchance bin ich mir nicht sicher, aber ja es dropped beides. ( https://www.youtube.com/watch?v=oN2BCvdNgy4 ) Der Satz fällt in der 1. Stunde des videos. ( Naxxrams liveraid vom 6.1.2007) Wenn du dich überzeugen willst. Gucks dir an ( Hab grad nicht die Zeit dazu )

**Comment by ircfelix** [comment]
Push
