### ISSUE TITLE
Quest: Der Schattenwächter / Der Eiswächter

### ISSUE THREAD

**Issue by Hexquantum** [ClassicWoW/Nefarian_1.12.1_Bugtracker#667]
Server Version: 1.0.6

Wie Sollte es sein? - Quests sollen wiederholbar sein ( so wie der Naturresi Arkanums in ZG, die mit dem selben Patch kamen)

Wie ist es? - Quest funktioniert , kann jedoch nur ein mal abgegeben werden und ist nicht wiederholbar

Links  : Schattenwächter:  http://datenbank.welli-it.de/?quest=9213
          Eiswächter:           http://datenbank.welli-it.de/?quest=9211

Quellen: http://eu.battle.net/wow/en/game/patch-notes/1-11-0 ( Siehe bei : Quests )
              http://wow.ingame.de/forum/dungeon-of-witchcraft-37/der-hexer-als-tank-in-aq40-111528/
              (siehe 2. Antwort 20. August 2006, 23:41"[...] +10 Schattenresi auf Kopf und Hose (gibts bei  
              Argent Dawn zu holen)[...] )

Anmerkung: Quest muss wiederholbar sein, auch wenn es erst nach AQ kam. Viele Klassen haben ja 
                    auch Zauber aus Patchständen nach  AQ, z.B. Winters Chill , Pyroblast ohne Abklingzeit, 
                    Arkane Explosion als instandcast. Sprich in meinen Augen gibt es keinen Grund die Quest
                   aufgrund ihres späteren Releasedatums nach hinten zu schieben.(Quelle: s.o. (Patchnotes) )

lg Hexquantum

**Comment by dagochen** [comment]
Naja, das eine sind Klassenfertigkeiten und Zaubermechaniken, welche allein schon wegen den Talenten auf Patchstand 1.12 sein müssen. Das was du jetzt forderst, ist allerdings eher der Kategorie Quest- und Spielinhalte und wird vermutlich erst gefixt, sobald wir vom Content soweit sind. Ist ähnlich wie mit den Quests in Silithus, da gehen halt nur nen paar, aber nicht alle.

**Comment by hraesvelgr** [comment]
und wird auch erst gefixt, wenns wirklich nötig ist :P ergo wirklich mit naxx...vorher brauchst du nahezu nie so extrem viel frost/schattenresi.

**Comment by Hexquantum** [comment]
"und wird auch erst gefixt, wenns wirklich nötig ist :P ergo wirklich mit naxx...vorher brauchst du nahezu nie so extrem viel frost/schattenresi."

AQ : Twins, Hexertank

**Comment by dagochen** [comment]
Glaube kaum das nur weil Hexer in AQ40 das brauchen, Naxx Quests vor Naxxramas gefixt werden ;)

**Comment by Wosser** [comment]
Es gibt genügend andere Items mit denen man als WL ans Schattenresi-Cap kommt, da sind die ZG-Enchants sinnvoller. Und Hexquantum, hast du nich noch ein paar andere Sachen hier zu erledigen, bis du dir übers Tanken der Twins gedanken machen kannst? :P

**Comment by Anorhin-Alane** [comment]
up
siehe auch https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/929

Heute auch mit einem GM über das Thema gesprochen.
AQ steht vor der Tür, wir brauchen dieses Quest, es ist wiederholbar und es ist auch so gewünscht das es wiederholbar ist. Hexenmeister benötigen diese Quest für AQ Twins.

**Comment by dagochen** [comment]
Funktioniert bereits.
