### ISSUE TITLE
Siegel des Befehls zu kleine Spelldmg-Skalierung

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#671]
Welches Verhalten wird beobachtet: 
Siegel des Befehls skaliert nur zu 20% statt zu 29% mit Zauberschaden.

Schritte zu Reproduzierung:
Siegel des Befehls nutzen.

Zusätzliche Informationen:
http://www.elitepvpers.com/forum/wow-guides-templates/55208-paladinformeln-auch-ein-paar-f-r-andere-klassen.html

29% Siegel des Befehls - Seal of Command - [erhöht, vorher 20%]

http://datenbank.welli-it.de/?spell=20947

(Vermutlich müssen Siegel der Rechtschaffenheit, Richturteil der Rechtschaffenheit, Segen des Refugiums und Heiliges Schild auch überarbeitet werden.)

**Comment by Haudraufinix** [comment]
Refugium:
* http://web.archive.org/web/20080214192532/http://www.wowwiki.com/Blessing_of_Sanctuary
* http://www.wowwiki.com/Blessing_of_Sanctuary?oldid=403610
Heiliges Schild:
* http://web.archive.org/web/20070212093853/http://www.wowwiki.com/Holy_Shield

Vermutlich ist eine sehr gewagte Aussage. Ich konnte leider zu BoS und HS keine Koeffizienten finden. Lediglich HS besitzt in BURNING CRUSADE einen 5% Spelldmg/Block koeffizienten. Ich konnte leider nicht rauskriegen, wie es zu Classic ist.

**Comment by Testear** [comment]
10% Siegel der Rechtschaffenheit - Seal of Righteousness - [reduziert, vorher 26%]
50% Richturteil der Rechtschaffenheit - Judgement of Righteousness - [reduziert, vorher 59%]
29% Siegel des Befehls - Seal of Command - [erhöht, vorher 20%]
43% Richturteil des Befehls - Judgement of Command - [keine Änderung]
33% Weihe - Consecration - [keine Änderung]
43% Heilger Schock - Holy Shock - [keine Änderung]
43% Hammer des Zorns - Hammer of Wrath - [keine Änderung]
43% Exorzismus - Exorcism - [keine Änderung]
19% Heilger Zorn - Holy Wrath - [keine Änderung]
00% Segen des Refugiums - Blessing of Sanctuary - [in der Beta direkt reduziert, vorheriger Wert unbekannt]
00% Heiliger Schild - Holy Shield - [reduziert, vorher 100%]

s. Link oben.

**Comment by Haudraufinix** [comment]
Oh, tschuldigung

**Comment by wahaxlekuke** [comment]
http://www.wowwiki.com/Seal_of_Command_%28old%29?oldid=327126 
(November 15, 2006)
> Seal of Command receives 20% coefficient from normal +spell damage stats, and 29% from +holy damage stats (such as Judgement of the Crusader). Judgement of Command receives 43% coefficient from any +spell damage stats. 

genau so skaliert das auch

**Comment by Testear** [comment]
bla
