### ISSUE TITLE
[Schurke] Wundgift verringert nicht die Heilung von Verbänden

### ISSUE THREAD

**Issue by Ilikegyoza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#674]
Ist-Zustand:
Egal wie viel Stacks Wundgift das Target auf sich hat, heilt es sich mit schweren Runenstoffverbänden immer um 250 pro Tick.

Soll-Zustand:
DIe Heilung sollte pro Stack um einen gewissen Wert verringert werden.

http://datenbank.welli-it.de/?item=10922

**Comment by bugreportor** [comment]
Hast Du dafür Videobeweise oder ähnliches? Immerhin erhöht +Heilung ja auch nicht die Heilung von Verbändenm warum sollte dann -Heilung die Heilung verringern?

**Comment by Rushor** [comment]
liegt evtl daran, dass der heal von dem item generic ist, gesundheitssteine erfahrern aj auch keine erhöhte heilung

**Comment by hraesvelgr** [comment]
-Hast Du dafür Videobeweise oder ähnliches? Immerhin erhöht +Heilung ja auch nicht die Heilung von Verbändenm warum sollte dann -Heilung die Heilung verringern?

addheal ist was anderes als "overall heal reduced by xx%"

ich hab jetzt nichts gefunden, aber blizzard scheint keinerlei unterschiede zwischen verbänden und heals zu machen. beides ist "heal by xx" der wert ist an sich erstmal fest. wound poison funktioniert ja wie mortal strike, und auch der sollte theoretisch den heal des verbandes verringern. anders ist es beim gesundheitsstein., der wird mM nach nicht davon betroffen, da er "leben wiederherstellt" und nicht heilt

**Comment by Haudraufinix** [comment]
Ich meinte Mortal Strike hat verbandsheilung aufm Offi auch nicht reduziert, aber wie gesagt "meinte" sicher bin ich mir nicht

**Comment by Ilikegyoza** [comment]
Also MS verringert hier auf dem Server die Heilung des Verbandes um 50%

**Comment by wahaxlekuke** [comment]
Ich vermute auch dass es bei Wundgift und MS genau gleich funktionieren soll. Aber ohne Quelle ist das schwer zu sagen...

**Comment by Haudraufinix** [comment]
http://datenbank.welli-it.de/?spell=13227

Wie wirkt das dann, 675 Heilung weniger auf die 2000 Punkte des Verbandes oder 675 Heilung weniger pro Verbandstick. In letzterem Fall reichen 2 Stacks um selbstheilung durch Verbände komplett zu negieren o.0

**Comment by Testear** [comment]
Beim Mortal Strike steht ganz klar "reducing the effectiveness of ANY healing by 50% for 10 sec"
Beim Wundgift steht "reducing all healing effects used on them by 135 for 15 sec. Stacks up to 5 times on a single target."
Das legt nahe, dass das nur für Zauber gilt und nicht für Heiltränke, Gesundheitssteine und Verbände.

**Comment by Haudraufinix** [comment]
Used on them bezieht sich nicht auf eine Quelle. Er kann sich also auch selber heilen und hat die Einschränkung.

**reducing all healing effects** (Wundpoison)
vs
**reducing the effectiveness of any healing** (Mortal Strike)

Klingt für mich eigendlich danach, als ob die beiden Skills genau die selben "Quellen" betreffen müssten

**Comment by Testear** [comment]
Nein, es gibt einen Unterschied zwischen "reducing healing effects used on them" und "reducing the effectiveness of any healing" . 
Ersteres (http://datenbank.welli-it.de/?spell=13230) bedeutet, dass alle Heileffekte, die auf das Ziel gewirkt werden (sprich Zauber oder Verbände von anderen Spielern) reduziert werden, aber alle Heileffekte, die er nur selber nutzen kann nicht (sprich Gesu und Heiltrank).
Letzeres bedeutet, dass jeder Heilungseffekt reduziert wird. 
Ansonsten gäbe es keinen Unterschied zwischen den Tooltips, da Wundgift entsprechend Höhe der Heilung auch weit mehr als 50% der Heilung reduzieren kann.

**Comment by Haudraufinix** [comment]
*Wound Poison is a poison that is created by Rogues who then apply it to their weapons. Everytime the rogue hits with the weapon, there is a 30% (40% w/ Imp. poisons) chance of the victim being poisoned for 15 seconds. The poison will **reduce all healing** affects on the victim. It can stack up to 5 times on the same victim.*

Quelle: http://www.wowwiki.com/Wound_Poison_(item)?oldid=329360

Klingt recht genau nach
*A vicious strike that deals weapon damage plus 160 and wounds the target, **reducing the effectiveness of any healing** by 50% for 10 sec.*

Btw: du hast 2x den selben Link gepostet...

**Comment by Testear** [comment]
Das ist keine Haarspalterei, es ist einfach nicht das gleiche.

**Comment by Haudraufinix** [comment]
Okey, ich seh schon, ich halte mich in Zukunft von Bugreports wo du mitmischst fern, da is ja Hopfen und Malz verlohren

**Comment by Testear** [comment]
In 3 Tagen ist dir kein besseres Argument als eine Beleidigung eingefallen?

**Comment by dagochen** [comment]
Der Unterschied ist, dass es sich bei dem einen um einen physischen Effekt handelt (MS) und bei dem anderen um einen magischen Effekt handelt (Wound Poison). Falls hier aber doch noch richtige Quellen kommen, mache ich gerne wieder auf.
