### ISSUE TITLE
Hoodoohaufen: Übernimmt keine Spieler

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#675]
**Welches Verhalten wird beobachtet?**

Beim öffnen eines Hoodoohaufens wird kein Spieler der Gruppe übernommen.

**Wie sollte es sich verhalten?**

Zitiert aus der Quelle: *Denn alle Gruppen, die sich im näheren Umfeld des Haufens befinden, werden aktiv sobald ihr euch bückt. Ferner wird der Spieler, der den Haufen versucht zu plündern zu 75% übernommen. Er sollte umgehend von einem Magier verwandelt werden, sodass er keinen Schaden anrichten kann. Ist die Übernahme vorbei, kann er von einem Priester befreit werden.*

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

http://wow.ftpi.de/showtopic.php?threadid=13 am besten nach "Haufen" suchen

**Links aus unserer Datenbank**

Verwunschene Hoodoohaufen / Jinxed Hoodoo Pile:
http://datenbank.welli-it.de/?object=180228
http://datenbank.welli-it.de/?object=180229
http://datenbank.welli-it.de/?object=180244
http://datenbank.welli-it.de/?object=180247

Den Zauber, den der Haufen wirken müsste, konnte ich in der Datenbank nicht finden. kA, wie dieser heißen könnte.

**Comment by dagochen** [comment]
Nicht sicher, aber vielleicht: http://datenbank.welli-it.de/?spell=24157

**Comment by Rushor** [comment]
müsste aber nen mod_charm effect haben der spell

**Comment by hraesvelgr** [comment]
der hodoo hex gehört wohl eher dazu: http://datenbank.welli-it.de/?spell=24165.

ich konnte auch nach langem suchen keine ID finden, .

alles was ich finden konnte ist, dass ein user meint, dass es genau der gleiche debuff ist wie "will of hakkar", was ich aber nicht ganz glauben kann, denn warum war es dann essentiell, die MC'ed person zu killen? bei hakkar killt man die ja auch nicht.
http://www.experts123.com/q/how-are-jinxed-hoodoo-piles-handled.html

**Comment by Rushor** [comment]
sah der spell denn genau gleich aus wie der von hakkar? wenn ja kann man nach spellids mit gleicher icon-id suchen

**Comment by hraesvelgr** [comment]
ja, sah genauso aus. halt dieses "domination"-debuff symbol.(http://datenbank.welli-it.de/?spell=17405)

https://www.youtube.com/watch?v=061yT8pW6wU&feature=player_detailpage#t=22

**Comment by dagochen** [comment]
ja stimmt. hab garnet auf die werte geachtet ;)

vermutlich ist es sogar der gleiche zauber wie bei hakkar. und man hat die bei den hoodoohaufen einfach getötet weil man es kann! würde man dieses verfahren auch bei hakkar so durchführen, wären wipes ziemlich sicher garantiert?

**Comment by Rushor** [comment]
im bereich um hakkar spellids gibts auch net viele spells mit gleichem effect + gleichem symbol, denke auch, dass es der hakkar charm ist http://pokit.org/get/?02cb203bccc950b297cf3fc5c9aa534d.jpg

**Comment by hraesvelgr** [comment]
will of hakkar: http://datenbank.welli-it.de/?spell=24178

dann ab damit

**Comment by Gnomorus** [comment]
Hoodoo Haufen

Über die gesamte Instanz verteilt sind unzählige Hoodoo Haufen zu finden. In diesen kann zu 50% eine Voodoopuppe für eine bestimmte Klasse sein. Das plündern der Haufen sollte aber gut geplant sein. Denn alle Gruppen, die sich im näheren Umfeld des Haufens befinden, werden aktiv sobald ihr euch bückt. Ferner wird der Spieler, der den Haufen versucht zu plündern **zu 75% übernommen**. Er sollte umgehend von einem Magier verwandelt werden, sodass er keinen Schaden anrichten kann. Ist die Übernahme vorbei, kann er von einem Priester befreit werden.
