### ISSUE TITLE
[Raid]: BWL - Nefarian/Feuerschwinge/Schattenschwinge/Flammenmaul | MC - Baron Geddon/Ragnaros

### ISSUE THREAD

**Issue by ChichiWarrior** [ClassicWoW/Nefarian_1.12.1_Bugtracker#677]
Welches Verhalten wird beobachtet?

Schattenflamme setzt den Swingtimer von Nefarian NICHT zurück
Elementarangriffe können kritisch treffen

Wie sollte es sich verhalten?

Schattenflamme soll den Swingtimer von Nefarian zurück setzen.
Elementarangriffe können den Tank nicht kritisch treffen.

Schritte zur Reproduzierung

Nefarian (oder andere Bosse mit Schattenflamme) angreifen und auf Schattenflamme + Hit warten und durch ein Addon die Zeiten der Angriffe vergleichen
Baron Geddon/Ragnaros angreifen und Kampflog kontrollieren

Zusätzliche Informationen (Screenshots, Videos, etc.)

https://dl.dropboxusercontent.com/u/12580113/WoWScrnShot_041915_204041.tga
Screenshot von Baron Geddon/Ragnaros imo nicht vorhanden. (Vielleicht hat jemand einen Screenshot)

Links aus unserer Datenbank

http://datenbank.welli-it.de/?spell=22539

http://datenbank.welli-it.de/?npc=11583
http://datenbank.welli-it.de/?npc=11502
http://datenbank.welli-it.de/?npc=12056

Zusätzliches

Die Möglichkeit besteht, dass auch andere Bosse unter diesem Problem stehen. (Alle Bosse mit der Fähigkeit Schattenflamme)

http://datenbank.welli-it.de/?npc=11983
http://datenbank.welli-it.de/?npc=14601
http://datenbank.welli-it.de/?npc=11981

Mit sonnigen Grüßen

Chichi

**Comment by hopplagit** [comment]
Quellen dafür finden sich wo?

**Comment by ChichiWarrior** [comment]
Quelle:

Nachdem die Swingtimer verschiedener Klassen angepasst und korrigiert wurden, änderte sich dieser auch bei den Bossen.

Desweiteren, wenn man den Schaden der Fähigkeit <Schattenflamme> aus der Datenbank mit dem Schaden aus dem Combatlog vergleicht, ist dieser auch nicht korrekt.

Um einen weiteren Zweifel aus den Weg zu räumen. Der Tank hatte bei diesem Combatlog und Kampf gegen Nefarian (19.04.2015) BiS Gear an + Critimmun dazu noch über 10k HP.

**Comment by Haudraufinix** [comment]
Wird wohl das selbe Problem sein, wie dass auch nicht "Hybrid" Klassen(Pala, Schami), zauber wirken können und direkt danach einen Autohit landen. Kein Mob und auch keine Klasse ausser Pala/Schami konnte dies zu Classic.
Das führt zu den lächerlich hohen Schadensspitzen. Autohit, Cleave(der eigendlich n verstärkter autohit sein sollte?!) und Flammenatem etc. können sich so verketten.
Normalerweise sollte man nach einem Flammenatem o.ä. Einen Swingtimer lang Zeit haben, um den Tank hoch zu bringen.

Bleibt bloss die Frage, wie lächerlich einfach der Content für full Equipte Spieler mit +- 8 Jahren zusätzlicher Erfahrung ist.

* You are mistaken. If you cast Slam within the Swing Timer and it hits before your next autohit the swingtimer will reset.
(Just tested it on ED) Thats how it's supposed to be on 1.12.
aus http://www.wow-one.com/forum/topic/85818-request-swingtimer-that-resets-after-you-used-slam/ (FEENIX - FORUM!)
Als kleines Beispiel.
Bin leider auf der Arbeit und finde gerade mit "vertretbarem" Suchaufwand keine besseren Beispiele

**Comment by Ataraia** [comment]
Bei Onyxia verhält es sich genauso.

Habe letzte Woche innerhalb von weniger als 1 Sekunde alle 3 Attacken abbekommen, die die zickige Dame so drauf hat.
Wegschlagen, Flammenatem und Cleave. Der Cleave hat dann natürlich auch noch gecrusht, weil Schildblock schon für die anderen beiden Attacken draufging. Da waren dann halt etwa 9k HP auf einen Streich weg (bei nem halb T2-equipten Krieger!).

Nefarian boxt momentan rein, dass man als Tank den KriegerCall nur mit sehr viel Glück überleben kann, weshalb bei uns Last Stand jetzt immer für den KriegerCall aufgehoben wird. ;)

**Comment by Haudraufinix** [comment]
Cleave ist n Skill genau wie Wegschlagen, Flammenatem, Thash oder Dynamitwurf und kann darum KEINE crushing Blows auslösen. Hingegen kann sie auf "unserem" Server gleichzeitig zum Cleave nen Autohit machen, DIESER kann dann Crushen.

(das Phänomen mit dem Cleave != Autohitgesehen habe ich an Kurinaxx in AQ20 beobachtet)

Du hast also vlt 4 Schläge abgekriegt, nicht 3. Bei den drei aufgezählten ist ein Crush unmöglich

**Comment by Larnak1** [comment]
Siehe bestehenden Eintrag:
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/624

**Comment by Ataraia** [comment]
Mann, dann wars von mir aus nen normaler Autohit, bin jedenfalls im Dreck gelegen, weil ich 3 Hits innerhalb von 1 Sekunde kassiert hab und einer von den drei war auch ein Crushing. Ich hätt nen Screenshot machen sollen...^^

**Comment by Haudraufinix** [comment]
Ich wollts nur richtigstellen, sollte kein Vorwurf sein :D

**Comment by Seniorash** [comment]
Bzgl fehlender Quellen:
- Schattenflamme macht zu viel Schaden (Teilweise über 6,5k, dadurch wird der Onyumhang fast nutzlos wenn man kein Tank ist) http://www.wowwiki.com/Shadow_Flame?oldid=336459
It deals about 3938-5062 cone-shaped shadow damage and is not partially resistable.

Bezüglich des Swingtimers von Spielern bei Zaubern: 
Habe die Quellen zu den Schamanen und Paladinen in #624 beigefügt.

Dass der gleiche Fehler bei NPCs und bei Spielern auftritt liegt einfach auf der Hand. Ebenso, dass NPCs mit Zauberschaden nicht kritisch treffen können (gab es sogar mal als Tipp beim Ladescreen). Das ist einfach offensichtlich falsch, weil diese beiden Fehler einfach zum sofortigen Tod des Tanks führen.

Zum Spalten konnte ich aber nichts finden, ob sich diese Fähigkeit den Swingtimer teilt. Die Beschreibung sieht allerdings genauso aus wie beim Krieger und deswegen würde ich davon ausgehen.
http://www.hordeguides.de/Schlachtzug/Classic/Boss/11583/Nefarian/index.htm
Spalten (Cleave)
Fügt einem Feind und seinem nächsten Verbündeten normalen Schaden plus 50 zu, wirkt auf bis zu 10 Ziele. 5 Meter Reichweite.

**Comment by wahaxlekuke** [comment]
Das Problem mit den Swing-Timern sollte mittlerweile behoben sein.
