### ISSUE TITLE
Hexenmeister Fluch der Verdammnis(CoD)

### ISSUE THREAD

**Issue by Jura500** [ClassicWoW/Nefarian_1.12.1_Bugtracker#681]
Welches Verhalten wird beobachtet?
Wenn mehrere Hexenmeister CoD auf einem Ziel aktiv haben, und einer dieser Hexer seinen Fluch mit einem anderen überschreibt, so fallen alle CoD aus der Debuffleiste.

Wie sollte es sich verhalten?
Nur der CoD des einen Hexers sollte überschrieben werden, die anderen bleiben erhalten.

Schritte zur Reproduzierung
CoD überbuffen, während mehrer CoD's auf dem Ziel sind.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?spell=603 Fluch der Verdammnis

**Comment by Gnomorus** [comment]
Läuft, danke.
