### ISSUE TITLE
Hexenmeister DoT's

### ISSUE THREAD

**Issue by Jura500** [ClassicWoW/Nefarian_1.12.1_Bugtracker#682]
Welches Verhalten wird beobachtet?
Wenn bereits eine stärkere Verderbnis auf einem Ziel ist, dann erscheint beim casten der Verderbnis die Meldung "Ein mächtigerer Zauber ist bereits aktiv." 
Fluch der Pein verhält sich gleich.

Wie sollte es sich verhalten?
Auch wenn bereits ein stärkerer DoT auf dem Ziel ist, sollte der schwächere DoT der Debuffleiste hinzugefügt werden.

Schritte zur Reproduzierung
Siehe Oben

Links aus unserer Datenbank 
http://datenbank.welli-it.de/?spell=11713  Fluch der Pein
http://datenbank.welli-it.de/?spell=11672  Verderbnis

**Comment by wahaxlekuke** [comment]
Betrifft das nur Hexenmeister oder andere Klassen auch?

**Comment by Gnomorus** [comment]
Läuft, danke.
