### ISSUE TITLE
BRD: Boss "Wärter Stilgiss" mit "Verek" fehlt/ rare

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#683]
**Welches Verhalten wird beobachtet?**
Im Vault ("Das schwarze Gewölbe") in BRD ist der Boss "Wärter Stilgiss" nicht immer vorhanden und wenn er spawnt, tut er das ohne Verek. Außerdem nutzt er seine Frostnova und Frostblitz-Fähigkeiten nicht.

**Wie sollte es sich verhalten?**
Genau in der Mitte des Vault-Raums mit den vielen Reliktkästen sollte der Boss regulär (immer) stehen, mit einem Dämonenhund-Add namens Verek. Nach dem Töten des Bosses kann das Reliktkasten-Event regulär gestartet werden, wie es momentan funktioniert.

**Schritte zur Reproduzierung**
In BRD das schwarze Gewölbe besuchen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Kommentare von Wowhead:

> He's not a rare, he always spawns. Like krawnight says, he's in the vault room. He also has an elite dog by his side (which can also drop blues, yay). Easy boss since he has fairly low hp.

http://de.wowhead.com/npc=9041/warter-stilgiss#english-comments

Soll-Zustand:
![Bild](http://vignette4.wikia.nocookie.net/wowwiki/images/8/86/The_Black_Vault.jpg/revision/latest?cb=20080103013234)

Hordeguides-Beschreibung mit Fähigkeiten und Bildern:
http://www.hordeguides.de/Instanz/Classic/Boss/9041/Waerter-Stilgiss-und-Verek/index.htm

> Vor dem 1.1 Patch war er wie Lord Roccor und Pyromant Weisenkorn ein Rare-Spawn der Instanz. Wenn er nicht anwesend war, wurde er von drei Wachen vor dem Tresorraum ersetzt.

Video:
https://youtu.be/NBgPPjV48Pw?t=6m12s

**Links aus unserer Datenbank**
Wärter: http://datenbank.welli-it.de/?npc=9041
Dämonenhund: http://datenbank.welli-it.de/?npc=9042

**Comment by Gnomorus** [comment]
Die 2 Bosse bzw Boss und Begleiter sind momentan als rare spawn vertreten und spawnen wenn überhaupt nur einzeln.

**Comment by Larnak1** [comment]
Ah, guter Tipp. Mir war auch so, als hätte ich ihn irgendwann mal gesehen, konnte mich aber nicht mehr erinnern. Hab den Report entsprechend angepasst. 

Da fällt mir gerade ein, da gab es doch auch diese Wachen, die den Zugang zum Kastenraum versperrt haben. Waren die später regulär da oder gab es die nur in der Zeit, als Stilgiss Rare war? Habe die hier noch nie gesehen.

**Comment by Gnomorus** [comment]
Die Dunkelwachen sind Begleiter der Dunkelbewahrer und spawnen richtig im 3er oder 4er Pack, sobald der dazugehörige Dunkelbewahrer an der entsprechenden Stelle in BRD auch spawnt.

**Comment by Larnak1** [comment]
Das wären auch die Dunkelwachen, hatte irgendwo ein Bild gefunden. Frage beantwortet :)

**Comment by ircfelix** [comment]
Quellenangabe: 2007.03.23 (Patch 2.0.10)

Wieso suchst du nicht eine Quelle pre 2.0.10? Gerade Patch 2.0 war mit vielen gravierenden Änderungen verbunden. Natürlich kann man jetzt behaupten, dass sich bei diesen beiden Mobs hier nicht viel geändert hat, aber behaupten kann man vieles. Also such doch bitte was gscheites raus. 
Im Forum habe ich ein Tool zur Suche von alten Vanillainhalten gepostet. Nutz es doch einfach.

**Comment by Larnak1** [comment]
> Die weiteren Quellenangaben erscheinen mir jedoch legit :-)
This. Die andere dient nur zur Ergänzung. EoD.

**Comment by ircfelix** [comment]
Ich mecker nicht um des meckern willens, sondern weil du eine Quelle von Patch 2.0.10 angegeben hast.

**Comment by Larnak1** [comment]
Ich habe dir gerade erläutert, warum das hier überhaupt kein Problem ist. Aus irgendeinem mir unbekannten Grund versuchst du aber, eins daraus zu machen.

**Comment by Haudraufinix** [comment]
http://www.wowwiki.com/Warder_Stilgiss?oldid=354269

* Warder Stilgiss is a level 56 elite rare mob dwarf mini-boss found in the Black Vault, Blackrock Depths, with his pet darkhound, Verek. He appears on the threshold of the Coffer Room. If he is not there, there will be three dwarf guards instead.

Wieso wird das erwähnt? WEIL ER RARE IST!

**Comment by hraesvelgr** [comment]
zugegeben,m wir kriegen hier zweideutige informationen, aber ich denke, das liegt daran, dass brd mit 1.10 revamped wurde, die guides jedoch alle gleich geblieben sind (wowwiki und co)

http://www.wowhead.com/npc=9041/warder-stilgiss#comments
auf wowhead in den comments wird ziemlich felsenfest behauptet, dass er bereits mit patch 2.0.1 nicht mehr rare war, und davor anscheinend auch nicht. auf dem offi war er definitiv mit wotlk und cata nicht rare, trotztdem steht in wowwiki drin, dass er rare ist, was mich zu dem schluss kommen lässt, dass wowwiki einfach nie geupdated wurde, in der hinsicht.


pyromancer loregrain wurde auch mal revamped, das steht wiederum in wowwiki drin, aber nicht in den patchnotes:
http://www.wowwiki.com/Patch_1.10.0

-Blackrock Depths

    Lord Roccor is no longer a rare spawn. His patrol path was altered accordingly.
    Pick lock and Seaforium now work on the Shadowforge Gates Mechanism.
    The difficulty of the Lord Incendius and Ambassador Flamelash encounters has been increased.
    Marshal Windsor will now open the door to the supply room during the escort 'Jail Break,' instead  of walking through it. 

für roccor steht es regulär drin. 

die seiten sind einfach alle nicht wirklich zuverlässig.

**Comment by Haudraufinix** [comment]
Ist bei jeder Software so. Das schlampigste ist immer die Dokumentation ^^

**Comment by Larnak1** [comment]
Steht auch in meinen Quellen, dass er zuvor Rare war und es gepatcht wurde. Von mir aus kann man ihn auch Rare lassen, soll mich nicht stören. Was in jedem Fall falsch ist, ist, dass Verek und sein Herrchen nicht gemeinsam spawnen.

**Comment by ircfelix** [comment]
Naja, roccor is doch auch kein rare im Moment. Was denken sich die devs grade dazu? Wie würdet ihr es lösen?

**Comment by Haudraufinix** [comment]
Da eh jeder Instanzen reseten kann bis der gesuchte Rare drin ist machts keinen Unterschied und führt zu weniger Frust wenn er NICHT rare wäre.

**Comment by hraesvelgr** [comment]
das wurde rausgefixt. instanzen resetten ist nur jeder stunde möglich.

**Comment by Haudraufinix** [comment]
jede stunde 5x - wenn bevor du die gruppe baust jeder alleine kurz reinguckt haste 25 resets. So viel Pech kannste kaum haben

**Comment by Larnak1** [comment]
Das funktioniert aber nur bei den Sonderfällen, bei denen du den Boss schon vom Instanzeingang aus ins Target nehmen kannst, beispielsweise in UBRS mit Jed. In den meisten anderen Fällen, so auch hier, musst du erst mal in die Nähe, bevor du sehen kannst, ob er da ist. 

Beim Wärter Stilgiss beispielsweise musst du bis auf die Mitte der Brücke hinter dem großen Tor auf dem Weg zu Incendius, um in Reichweite zu sein.

**Comment by Haudraufinix** [comment]
Naja ich wollt mich nicht daran aufhängen. Schlussendlich glaube ich aber nicht, dass sich irgendjemand in seinem Spielgefühl gestört fühlt, wenn der Boss immer da ist ;)

**Comment by ircfelix** [comment]
Naja, die Schultern sind für Frostmagier bis zu den BWL Schultern/R10 Schultern Best in Slot, aber okay ;-)

**Comment by dagochen** [comment]
Was denn nun? Rare oder nicht Rare?

**Comment by Larnak1** [comment]
Um mal den damaligen Stand zusammenzufassen:
Es kann als sicher angenommen werden, dass beide immer zusammen spawnen sollten und nicht einzeln. Das ist aktuell hier nicht so und sollte gefixt werden. Dafür sollte auch nicht mehr Input nötig sein und es lässt sich auch unabhängig von der Rare-Frage lösen.

Die Frage, ob er Rare ist oder nicht, konnte nicht abschließend beantwortet werden, da die Quellen sich teilweise leicht widersprechen. Bei uns sind aktuell beide Rare, das so zu belassen, wäre angesichts der Quellenlage kein Problem. Wenn es zu der Frage noch klärenden Input gibt, wäre es natürlich schön, aber ich denke endgültig klären wird man es kaum können, da es eben diese unterschiedlichen Quellen dazu gibt.
