### ISSUE TITLE
Quest "Buch der Uralten" in Desolace

### ISSUE THREAD

**Issue by Quoronexro** [ClassicWoW/Nefarian_1.12.1_Bugtracker#685]
Welches Verhalten wird beobachtet?
Laut Questlog soll man den Edelstein vom Questgeber in die Hand der Naga-Statue auf der Insel Ranazjar legen, damit der benötigte Mob erscheint. Man kann zwar den Edelstein auswählen, aber die Hand der Statue ist nicht anwählbar. Der Stein kann nirgendwo an der Statue abgelegt werden und die Quest ist somit nicht abschließbar.

Wie sollte es sich verhalten?
Die Hand der Statue sollte für den Edelstein anwählbar sein, damit der Mob mit dem benötigten Buch erscheint.

**Comment by Gnomorus** [comment]
guckst du #340
