### ISSUE TITLE
[Schurke] Taschendiebstahl lässt Loot-Table "verschwinden"

### ISSUE THREAD

**Issue by Flaktrack** [ClassicWoW/Nefarian_1.12.1_Bugtracker#687]
Welches Verhalten wird beobachtet?
- nach einem erfolgreichen Taschendiebstahl bei einem beliebigen Humanoiden, "verliert" dieser offenbar seine Loot-Table und droppt gar nix mehr. 

Wie sollte es sich verhalten?
- der Mob sollte auch nach einem erfolgreich durchgeführten Taschendiebstahl Gegenstände droppen. 

Schritte zur Reproduzierung
- ein paar Mobs bestehlen, diese dann umlegen und man merkt ziemlich bald, dass man keinen Loot mehr bekommt. Gut zu testen auch bei NPCs, die zu 100% Questitems droppen sollten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
- alte Thottbot Kommentare:
http://web.archive.org/web/20050307182424/http://www.thottbot.com/?k=372

Links aus unserer Datenbank (hier gehts zur Datenbank)
- http://datenbank.welli-it.de/?spell=921

**Comment by JoFlo03** [comment]
Kann ich zu 100% bestätigen. Wenn denn mal der Taschendiebstahl erfolgreich ist...
