### ISSUE TITLE
Quest: Erde von Un'Goro (Thunderbluff) falsche Anforderungen

### ISSUE THREAD

**Issue by Larnak1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#688]
**Welches Verhalten wird beobachtet?**
Die Quest "Erde von Un'Goro" kann nicht angenommen werden, obwohl die Questvoraussetzungen erfüllt sind. Nach Abgabe der Prequest erscheint die Meldung, dass die Anforderungen nicht erfüllt werden.

**Wie sollte es sich verhalten?**
Nach Abgabe einer der Prequests "Erzdruide Runetotem helfen" sollte direkt die Folgequest "Erde von Un'Goro" angenommen werden können, da die Questanforderung für beide lvl 47 ist.

**Schritte zur Reproduzierung**
Mit einem Charakter, der die Stufenanforderung erfüllt, die Prequest bei Hamuul Runetotem abgeben.

**Links aus unserer Datenbank**
Quest: http://datenbank.welli-it.de/?quest=3761
Prequest: http://datenbank.welli-it.de/?quest=936/Erzdruide%20Runentotem%20helfen (eine von mehreren)
Hamuul Runetotem: http://datenbank.welli-it.de/?npc=5769

**Comment by Flaktrack** [comment]
Könnte mit der Rasse zusammenhängen. Offenbar bekommt man als Untoter (getestet mit einem Alt) fälschlicherweise keine Folgequests. Als Taure hat gerade alles bestens funktioniert.

**Comment by Larnak1** [comment]
Hab es als Taure und Untoter probiert :(

**Comment by BedlamHorde** [comment]
Ich habe dasselbe Problem mit einem Ork 
Prequest "Erzdruide Runetotem helfen" erledigt. Danach kam die Meldung "Anforderungen nicht erfüllt" - und die Questreihe brach ab. 

Mittlerweile bin ich lvl 60 und kann die Quest "Erde von Un Goro" bisher nirgendwo annehmen oder neu starten.
Keiner der NPCS der Questreihe hat etwas für mich. 

Es kam öfter vor, dass Questreihen auf diese Art abgebrochen sind - bisher waren diese jedoch unwichtig.

**Comment by Tanduit** [comment]
das Problem besteht immer noch....

**Comment by Slimmer2** [comment]
Deswegen ist es noch offen

**Comment by bockworst** [comment]
selbe problem hier
alles schön gequestet und dann anforderung nicht erfüllt.
kann sie seither nicht mehr annehmen...
wdb ordner auch gelöscht.
bitte um hilfe
