### ISSUE TITLE
Texturfehler Vazario Kuppelschmier in Ratchet (Lehrer für Goblinische Ingenieurskunst)

### ISSUE THREAD

**Issue by 1990Darkdrake** [ClassicWoW/Nefarian_1.12.1_Bugtracker#690]
Sobald man bei ihm sachen erlenen will und schaut was man lernen kann und auf ein neues Rezept geht ist speziell bei diesem NPC ein BUG bei den Symbolen anstatt den Symbolen kommt ein Bild von einem Typen !!!

lg Darkdrake

**Comment by hraesvelgr** [comment]
aus irgendeinen grund dachte ich immer, dass das stefan raab ist. naja.

ist auch bei vielen anderen dingen so. fehlerhafte anzeige. aber nix dramatisches.

**Comment by Sabbaer** [comment]
isn entwickler foto, hab ich damals aufm offi-forum wo gelesen

**Comment by Larnak1** [comment]
Jop, das ist Samwise Didier.
