### ISSUE TITLE
Einfaches Lagerfeuer: Willenskraftbuff fehlt

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#691]
**Welches Verhalten wird beobachtet?**

Das einfache Lagerfeuer gibt keinen Willenskraftbuff.

**Wie sollte es sich verhalten?**

Von den Lagerfeuern sollte den Stärkungszauber "Gemütliches Lagerfeuer"/"Cozy Fire" ausgehen, der die Willenskraft um 4 erhöht.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

http://www.wowwiki.com/Basic_Campfire?oldid=83794

**Links aus unserer Datenbank**

Basic Campfire: http://datenbank.welli-it.de/?spell=818 (Tooltip spricht für sich)
Cozy Fire: http://datenbank.welli-it.de/?spell=7353

**Comment by hraesvelgr** [comment]
passiert nur in seltenen fällen, dass der buff kommt.. denke das hat was mit der LOS abfrage zutun, eventuell auch damit, dass das lagerfeuer manchmal im boden steckt.

**Comment by Gnomorus** [comment]
Gestern in IF vor der Bank kam der Bug z.B. nicht. das Feuer war eigentlich normal auf dem Boden und ich war die ganze zeit auch nah dabei und in LoS.

**Comment by Gnomorus** [comment]
In Scholomance in dem Raum von Theolen Krastinov hat das Lagerfeuer ohne zu zicken seinen Buff gespendet.
