### ISSUE TITLE
[Quest] Fackel der Vergeltung

### ISSUE THREAD

**Issue by Flaktrack** [ClassicWoW/Nefarian_1.12.1_Bugtracker#692]
Bug noch vorhanden - #22 
http://datenbank.welli-it.de/?quest=3453

Ich eröffne zur angegebene Quest einfach ein neues Ticket, da das alte #22 bereits geschlossen wurde, obwohl der Bug leider wieder bzw. noch immer auftritt.

Kalaran Windklinge (http://datenbank.welli-it.de/?npc=8479) murmelt zwar vor sich hin und fuchtelt mit den Händen in der Gegend herum, doch die Fackel, die er bei dem ganzen Hokuspokus erschaffen sollte, erscheint leider nicht. Da die Fackel nun nicht erschaffen wurde, kann die Quest bei dieser jenen eben nicht abgegeben werden.
Ein Abbruch mit folgender Neuannahme, dazwischen auch mal Relog, WDB-Ordern leeren und sonstige Verrenkungen, hat sich leider als nicht hilfreich erwiesen.

**Comment by Slimmer2** [comment]
Nach annehmen der Quest sollte nach ein paar Sekunden das Objekt Fackel der Vergeltung http://datenbank.welli-it.de/?object=149047 erscheinen bei der man die Quest abgibt
