### ISSUE TITLE
Quest: In den Träumen

### ISSUE THREAD

**Issue by ebeeb** [ClassicWoW/Nefarian_1.12.1_Bugtracker#693]
**Welches Verhalten wird beobachtet?**
Die Quest kann nicht beendet werden, da der Questmob (Taelan Fordring) sich während der Eskorte in Luft auflöst. Laut Combatlog ist er gestorben.
![combatlog](https://cloud.githubusercontent.com/assets/3743342/7361193/c4c1326a-ed54-11e4-9197-742cf3e0874c.PNG)

**Wie sollte es sich verhalten?**
Ich habe diese Quest nicht mehr so gut in Erinnerung, deshalb hier ein Kommentar von Wowhead (Patch 1.12.0):
> In order to get this quest you must complete ALL of Tirion Fordring's quests at the cave in EPL. After numerous kill quests and a trip to Live Strath you will go to hearthglen in disguise. Only with this disguise buff can you speak to Highlord Taelan Fordring and do this quest. 
> 
> You can keep your disguise on for a long time. No need to remove it when he says. The quest is very easy while you are in hearthglen, just let him kill everything and try not to get aggro from the elites. 
> 
> Once you get outside you will be attacked by 5 lvl 60 elites. He can kill them all on his own if you let him. You will not fail for dying at this stage if you can get rezzed immediately to catch up with the Highlord.
> 
> **###**
> The last part is kinda rough. The highlord will take you to the tower where everyone farms for Crusader enchants and yell for the Inquisitor to come out. Do not attack them...it will take a little bit but eventually the Highlord will engage. He will handle the main guy and he tells you to "deal with the crimson elites". Doing this with just myself and a shaman proved to be fairly difficult. There are only two guards with him but a group of 5 comes down the path and engages as well. 
> 
> I am not sure if these auto aggro you, or if you can let them aggro the highlord as well. When i did it we got aggro and it was a mess. The shaman ended up dying and even with a combat rez right away he failed the quest.
> 
> The highlord basically ends up getting owned and Tirion Fordring (the original quest giver) comes to save the day. If you can avoid getting aggro he will handle all the elites and you will get your nice reward.
> 
> If i have one piece of advice it is: either dont aggro anything or bring a full group.

In Luft aufgelöst hat sich der Taelan Fordring bei **### (coords: 54.0, 24.3)**. Ich habe es alleine und in der Gruppe probiert..

**Schritte zur Reproduzierung**
Quest bei Taelan Fordring starten.

**Links aus unserer Datenbank**
**Quest** http://datenbank.welli-it.de/?quest=5944
**Taelan Fordring** http://datenbank.welli-it.de/?npc=1842

**edit:**
**Video** https://youtu.be/FJ-R8c0XSAk

**Comment by Haudraufinix** [comment]
Wenn du die Questbelohnung schon haben möchtest, dann kannst du ein Video machen, wie du die Quest erledigst (soweit es eben möglich ist) und dieses /bzw den Link dazu einem GM schicken. Dann kriegst du die gewünschte Belohnung (nicht vergessen diese zu erwähnen) zugesendet.
Dient allerdings nur als Zwischenlösung

Auf jeden Fall danke für den Report

**Comment by ebeeb** [comment]
Video angehängt

**Comment by Bonfuzius** [comment]
Meines Erachtens muß der NPC einfach wesentlich stärker gemacht werden. Bei Blizzard konnte man diesen Quest einfach solo beenden, indem man die Verkleidung anbehalten hat und sich zum Schluß aus dem Kampf rausgehalten hat. 

Hier noch ein Kommentar aus der Quelle von ebeb: http://www.wowhead.com/quest=5944/in-dreams#comments
"Best is to let Highlord Taelan tackle them to death so do not terminate the disguise and watch from a distance until big daddy Fordring arrives to spank everybody."

Der eigenliche Quest, für den man die blaue Belohnung gekommt, ist eben in Startholme, dies ist lediglich ein nettes Abschluß-Event.

**Comment by usrmx** [comment]
Mir ist bei der Quest aufgefallen, dass Tirion, sobald er auftaucht, ziemlich nutzlos ist. Er greift weder an, noch hält er allzu viel aus und stirbt ziemlich gleich. Laut den Wowhead-Kommentaren sollte er aber die Gegner schon fast alleine töten können.
