### ISSUE TITLE
Spawn-verhalten Erze/Kräuter

### ISSUE THREAD

**Issue by ollyhdh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#694]
Welches Verhalten wird beobachtet?
Jedes Vorkommen (Erz/Kraut) respawnt einfach nach einer gewissen Zeit am selben Ort.

Wie sollte es sich verhalten?
Ich konnte leider keine Artikel im internet finden, die das belegen, aber ich selbst habe damals massig gefarmt, vor allem Erze. Mir fiel folgendes auf:
1. Es existierten sehr viele potenzielle spawnpunkte für Erze und Kräuter, jedoch waren NIE alle besetzt. Immer wenn ein Vorkommen abgebaut wurde, spawnte irgendwo innerhalb dieses Gebiets ein neues vorkommen, mit etwas verzögerung. Damit war es unmöglich, an einem einzigen Ort auf respawn zu warten, denn die chance, dass etwas wieder genau dort spawnen würde, war sehr gering.
2. "Seltene Erze", also Silber, Gold, Echtsilber, spawnten immer ANSTATT einem "normalen" Erz:
   - Zinnvorkommen hatten eine chance, als silbervorkommen zu spawnen,
   - Eisenvorkommen hatten eine chance, als Goldvorkommen zu spawnen,
   - Mithril- und Thoriumvorkommen hatten eine chance, als Echtsilbervorkommen zu spawnen.
   - Die Chance betrug ungefähr 20%.
   - [nicht ganz sicher] kleine Thoriumvorkommen haben IN BESTIMMTEN GEBIETEN eine chance, als Großes Thoriumvorkommen zu spawnen (eventuell waren das separate spawnpunkte für große Vorkommen, siehe 1.)

**Comment by Rushor** [comment]
https://github.com/classicdb/database/releases/tag/v1.5.0

**Comment by ollyhdh** [comment]
wow, nice! Ich dachte schon es gäbe keine Hoffnung dass sich damit mal jemand richtig auseinandersetzt, einfach weil es viel Arbeit ist. :D

**Comment by ircfelix** [comment]
Hey, es is schön dass du dazu einen Bugreport schreibst, aber ohne Quellen wirds wohl schwer das durchzubringen. Schätzwerte und Erinnerungen sind absolut unbrauchbar.

**Comment by dagochen** [comment]
Jep da hat felix recht, allerdings ist das Update von classicdb vielleicht auch einen 2. blick wert?

**Comment by Larnak1** [comment]
Die Quelle ist hier womöglich nicht so wichtig, da das Team schon an anderer Stelle im Forum beschrieben hat, dass zumindest Punk 1) hier auch so sein *sollte* und es eben nur aus irgendwelchen Gründen nicht funktioniert.

Der Vollständigkeit halber hier noch der Link zur aktuellsten Forumdiskussion zum Thema:
http://community.mmobase.de/hilfe-und-support/6840-erze-und-kraeuter-auf-nefarian.html

Und der ältere, in dem die Absicht der Devs deutlich wird und auch einige Indizien-Quellen verlinkt sind (interessant ab Seite 3):
http://community.mmobase.de/hilfe-und-support/5674-kraeuter-spawn-3.html

Hier explizit der Beitrag von Dotox, der den Soll-Zustand beschreibt:
http://community.mmobase.de/hilfe-und-support/5674-kraeuter-spawn-3.html#post45663
Und hier einen, der den vermeintlichen(!) Ist-Zustand beschreibt:
http://community.mmobase.de/hilfe-und-support/5674-kraeuter-spawn-5.html#post46484

Demnach kann das bestehende Verhalten als offensichtlicher Bug betrachtet werden.

**Comment by c0keh** [comment]
gabs auch schon hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/167
und das wurde dann "gefixt": http://community.mmobase.de/hilfe-und-support/5674-kraeuter-spawn-4.html#post45762

**Comment by ircfelix** [comment]
Pusch

**Comment by Loplin** [comment]
Gibt es denn eine Möglichkeit Kräuterkunde am Testserver auf 300 zu erlernen?
würde das testen erleichtern :)

**Comment by Larnak1** [comment]
Die Verteilung der Kräuter scheint auf jeden Fall zu funktionieren, wenn man annimmt, dass dort eben als ich drauf war wahrscheinlich seit Stunden niemand gefarmt hat. Bei Nefarian wäre dann jedes Kraut besetzt gewesen, auf dem Testserver waren viele Slots leer, was ja so sein sollte.

Gut kann man das vor allem an einigen Stellen sehen, wo bei Nefarian der komplette Boden mit Low-Kräutern nur so überwuchert ist, das ist auf dem Testserver weg (Zumindest die Stellen, die ich mir angesehen habe).

Der Respawn ist ein bisschen schwierig zu testen :/ Vielleicht könntest du hier kurz sagen, wie er genau funktionieren *sollte*? Z.B. ob es serverweit oder regionsweit sein soll. Einen regionsweiten habe ich versucht zu beobachten, konnte aber keinen Respawn beobachten. Um serverweite Respawns zu testen fehlen mir die Mittel.

**Comment by Dotox** [comment]
Die Spawns sind nun in verschiedene Gebiete aufgeteilt. Das ganze alleine zu testen ist mit Sicherheit nicht möglich aber lustig ist es trotzdem. Da wird Wochenlang im Forum rumgeheult und am Ende bekommt es ein oder zwei Spieler hin, das überarbeitete System, was einiges an Zeit gefressen hat, zu testen.

**Comment by Sheed90** [comment]
Wenn ich heute Zeit finde, werde ich es mir auch mal anschauen. Vielleicht finden sich ja noch 1-2 freiwillige. 

Nur zum Verständnis,  wenn ich in den verwüsteten Landen alle Gromsblut abbaue, dann sollten sie auch im selben Gebiet wieder respawnen?

Gruß

**Comment by Sheed90** [comment]
So, ich habe das System mal etwas getestet. In den verwüsteten Landen ist es ja recht überschaubar, was die Kräuter an geht. 

Man sieht natürlich manchmal, dass ein Kraut direkt neben einem respawnt, auch wenn man dieses Kraut 2-3 Pflanzen vorher abgebaut hat, aber im großen Ganzen würde ich sagen, dass dieses System wesentlich besser ist, als das, was jetzt live drauf ist.

Wie sieht das ganze denn mit dem schwarzen Lotus aus? Respawnt dieser auch nur in dem selben Gebiet oder weltweit (1 Pool)? Wenn er schwerer zu finden ist, wird er evtl. auch wertvoller, so wie früher.

Gruß

**Comment by ircfelix** [comment]
Ich teste das heut Abend auch mal.

Wenn der respawnort random ist, ist es gut möglich dass das Kraut neben einem respawnt.

**Comment by Sheed90** [comment]
Natürlich, aber gerade in größeren Gebieten wie Ungoro oder die östlichen Pestländer, wo es so massiv viele Spawnpunkte gibt, verringert sich die Chance natürlich. 

Auf jeden Fall sehr gute Arbeit, Dotox. Von mir aus kann das Ding so schnell wie möglich aufgespielt werden. :+1:

**Comment by ary1** [comment]
Ich habe das ganze bereits kurz nachdem es auf dem Testserver war getestet, mich allerdings erst jetzt mal hier angemeldet. Ich gehe mal davon aus dasss sich bisher nichts geändert hat.

Was habe ich getestet: Geisterpilz im Hinterland, Gromsblut in den Verwüsteten Landen und Desolace.

Geisterpilz:
Es gibt maximal 3 aktive Spawns. Respawnzeit ca 55 sek, mal in der Höhle, mal darauf. Scheint sehr gut zu funktionieren. Getestet ca 35 Minuten lang, hatte dann 2,5 Stacks. Allerdings viel Zeit vertrödelt, hier kann man gut und gerne 7-9 Stacks die Stunde farmen(alleine).

Gromsblut Verwüstete Lande:
Hier habe ich leider vor meiner ersten Runde nicht alle aktiven Spawns gezählt. 
Erste Runde habe ich 6 Spots gefunden. In der zweiten, dritten und vierten 4. Also denke ich es sind hier 4 aktive Spots ( in der ersten runde wohl schon respawn mitgenommen)
Respawnzeit konnte ich nicht beobachten, da kein Kraut zufällig mal neben mir gespawnt ist.
Insgesamt relativ ok zu farmen, es könnten evtl 1-2 mehr aktive Spots geben, vor allem im Vergleich zum Geisterpilz den ich vorher getestet habe.

Gromsblut Desolace:
3 aktive Spots gezählt, nachdem ich diese gepflückt habe ist allerdings innerhalb von etwa 15 Minuten nichts respawnt. Keine Ahnung ob es irgendwo anders respawnt ist. Bin dann noch in die Verwüsteten Lande um zu schauen ob es evtl dort respawnt ist. Waren allerdings immernoch nur 4. Also entweder woanders gespawnt oder hier ist die Respanwzeit wesentlich höher. Ist halt schwer nachzuvollziehen.


Anderes Kraut farme ich zu selten um da einen ordentlichen vorher/nachher Vergleich ziehen zu können. Insgesamt aber echt ein Schritt in die richtige Richtung. Top !

**Comment by ircfelix** [comment]
Wie ist das mit respawn in gebieten wo z.b. nur drei krau einer Art sind? (Wie beim post über mir beschrieben)

**Comment by Sheed90** [comment]
Naja, es ist relativ egal, wieviele max. Käuterspawns es gibt. Wenn du ein Kraut abbaust, wird es nach ca. 1 Minute innerhalb des Gebietes an einem zufällig Spawnpunkt respawnen.

**Comment by ircfelix** [comment]
Ich war gestern an einer Stelle wo nur ein Kraut dieser Art in diesem Gebiet stehen sollte und das Kraut war nicht da. Wenn es so ist wie du sagst, wäre das System z.b. mit den Geisterpilzen oder des 3 Gromsblut in Desolace sehr leicht auszunutzen.

**Comment by Sheed90** [comment]
Natürlich. Es kann halt konstant ohne große Wartezeit gefarmt werden. 

Je mehr Spieler farmen, desto weniger kriegt man. 
Je weniger Spieler farmen, desto mehr kriegt man. 

Wenn es zuviele Kräuter sind, muss man die maximale Anzahl an Kräutern in einem Gebiet verringern. Aber das kann man wohl erst nach einem Liveserver Test feststellen.

**Comment by Sheed90** [comment]
Wie stehen die Chancen, dass das neue Kräutersystem bald auf Nefarian aufgespielt wird?

**Comment by Sheed90** [comment]
Push

**Comment by Dotox** [comment]
Wir werden es aufspielen, sobald es ausführlich getestet wurde.

**Comment by ircfelix** [comment]
Was genau sollen wir testen?

**Comment by Larnak1** [comment]
Da keine exakten Informationen darüber vorhanden sind, wie es funktionieren sollte, kann diese Funktionalität auch nicht geprüft werden. Momentan ist es ein Stochern im Nebel abgesehen von den grundsätzlichen Hinweisen, die oben schon gegeben worden sind.

Wie sich das System mit 500+ Online-Spielern verhält, lässt sich ohnehin nur abschätzen, aber auch das wiederum nur mit genauen Informationen, wie es funktioniert.

**Comment by Sheed90** [comment]
Moin, also wir haben gestern nochmal etwas getestet. 
Folgende Gebiete:
- Verwüstete Lande
- Brennende Steppe
- Wald von Elwynn

Wie bereits vorher geschrieben, funktioniert in den verwüsteten Landen alles einwandfrei. Sonnenkraut, Feuerblüte und Gromsblut respawnen nach ca. 30 sek. - 60 sek. an einem anderen Spawnpunkt. 

Brennendw Steppe, hier haben  wir nur Traumblatt getestet - 1 Runde komplett alles  abgebaut. Ca. 6-7 Pflanzen. Allerdings ist direkt  aufgefallen, dass nichts  respawnt. Mein Kollege  hatte leider keinen Char mit Bergbau, also kannte er von seiner Runde schon alle 6-7 Spawns. Auch nach 15 Minuten ist nichts  respawnt, alles leer. Wir sind nach gut einer Stunde nochmal hin und siehe  da, es ist respawnt. Meiner Meinung  nach ist der Respawntimer für Traumblatt zu hoch. 

Im Wald von Elwynn hingegen konnten wir uns kaum vor respawns retten. Kaum hat mein Kollege  abgebaut, ist es schon wieder in der Nähe respawnt.

Gruß

**Comment by Dotox** [comment]
Hey,

sehr gut vielen Dank. Wie sieht es mit den Erzvorkommen aus?

**Comment by Sheed90** [comment]
Also wir haben sowohl reiche als auch kleine Thoriumvorkommen in der brennenden Steppe gesehen, aber das können wir uns nochmal im Detail angucken.

**Comment by ircfelix** [comment]
Dotox, gibt es.die Möglichkeit das zwei Tage oder so auf Bef aufzuspielen und dann wwieder bis zur Auswertung zurückzusetzen? Vll. Sind viele dann besser zum testen motiviert, wenn sie die gefarmten Mats auch nutzen können.

**Comment by EisenhowerSC** [comment]
Moin, also wir haben heute nochmal etwas getestet.
Folgende Gebiete:

  Westfall
Der respawn funktioniert gut. Die Kräuterspawns sind aber leider nicht gut verteilt. Süd-Westlich von dem Jangoschacht bei den Gnolen sind sehr viele Spawns auf einem Punkt. Hier könnte man ständig vom Kraut zu Kraut rennen pflücken und hinterdir respawnt es schon. Also ein Gebiet von 100x100 meter. Diesen Spot ein wenig entzerren und westfall ist gut

Gruß
Eisenhower

**Comment by Dotox** [comment]
Nein, auf Nefarian wird das System nicht zum testen gespielt.

Alles klar, dann schau ich mir das Gebiet nochmal an, klingt nicht so wild. Die Premade-Funktion ist eine gute Idee! Werden wir versuchen umzusetzen.

Im Grunde muss jedes Gebiet getestet werden. Das funktioniert nicht von heute auf morgen aber wenn wir irgendwann fertig sind, haben wir ein sehr gut funktionierendes System :)

**Comment by Sheed90** [comment]
Gut zu wissen, dann werden wir versuchen, noch ein paar Leute zu mobilisieren.

**Comment by dagochen** [comment]
Außerdem wäre zum vereinfachen des Reisens Premium eine gute Idee für alle auf dem Testserver....? Schnellreise wär sehr praktisch!

**Comment by Sheed90** [comment]
Nightblizard hat bereits in jedem Gebiet und vor jeder Instanz Teleport-NPC bereit gestellt.

**Comment by Larnak1** [comment]
Mh, ich war gerade dort und irgendwie sind alle Testserver-Händler, Teleport-NPCs und Test-Puppen nicht mehr da.

**Comment by Dotox** [comment]
Ich arbeite gerade am Testserver weswegen die NPCs nicht mehr da sind. Sollte heute Abend aber wieder beim alten sein.

**Comment by Sheed90** [comment]
Moin, ist der Testserver down? Ich wollte noch ein paar Gebiete testen.

**Comment by Larnak1** [comment]
Gestern kam ich rauf, allerdings waren die Test-NPCs noch nicht wieder da (Oder ich habe sie nicht gefunden)

**Comment by EisenhowerSC** [comment]
Moin, heute nochmal etwas getestet.
Folgende Gebiete:
Duskwood
Erste Runde viele Kräuter(sehr schön) . Alles abgebaut. Zweite Runde deutlich weniger... eher zu wenig. Es ist was respawnt aber meiner meinung nicht genug

Mfg Eisenhower.

**Comment by Dotox** [comment]
Das Testen ist im Moment nur bedingt möglich, da ich zur Zeit sehr viel am programmieren und testen bin. Deswegen sind auch die Händler nicht da. Melde mich sobald ich fertig bin. Kann aber noch einige Tage dauern :)

**Comment by EisenhowerSC** [comment]
Bitte melde dich, wenn du mit dem Programieren fertig bist, damit wir mit dem Testen weitermachen können.

P.s Hilfreich wäre es auch, wenn du wieder die Charaktere vom Life auf den Testserver kopieren würdest.

**Comment by ircfelix** [comment]
Und falls wir etwas spezifisches (ein spezielles kraut z.b.) testen sollen, wäre es nett wenn du uns das sagen könntest :)

**Comment by EisenhowerSC** [comment]
Auch eine genaue Beschreibung wie es jetzt funktionieren muss wäre hilfreich. Also hat jedes Kraut eigene Spawnpunke, oder gibt es spawnpunkte für Kräuter und da können alle Kräuter des Gebiets spawnen? Welche Respawnzeiten und im Welchem Radius? Wie ist es mit Schwarzem lotus?
Wie funktioniert das mit Erzen und seltenen Erzen? Thorium und Reiches thorium? Teilen die sich die spawnpunkte oder jedes hat eigene?  Ändert sich was an den chancen Edelsteine in Erzen zu finden? Mit allen sollchen Infos können wir besser testen.

Mit freundlichen Grüßen 
Eisenhower

**Comment by Dotox** [comment]
Jedes Kraut hat seinen spawnpunkt, muss aber nicht aktiv sein. Das hängt davon ab, wieviel Kraut der Sorte gerade aktiv ist. Jedes Gebiet hat für jedes Kraut einen Pool indem festgelegt ist, wieviele Spawns mind. aktiv sein sollen.

Respawnzeiten werden wir in dem Sinne nicht preisgeben. Auf unserer Web-Datenbank kann zwar davon etwas eingesehen werden, aber dass muss nicht immer stimmen weil die Datenbank Scripttechnische-Inhalte nicht beachtet.

Ich hab das ganze System nicht umgebaut, um nachträglich einen Roman darüber zu schreiben, wo was und mit welchen Zeiten respawnen soll :D Testet es und sagt uns eure Ergebnisse. Ob daran dann etwas geändert werden muss, entscheiden wir nachdem wir uns alle Reports durchgelesen haben. Der Loot hat damit nichts zu tun (Edelsteine).

**Comment by Sheed90** [comment]
Aber... wenn wir nach dem Test eine Vergiss-mich Pille nehmen? :-D

Spaß beiseite. Das ist natürlich verständlich. Jetzt ist noch eines wichtig:
Hat jedes Kraut in allen Gebieten die gleiche Respawnzeit? Oder kann z. B. Traumblatt im Ungoro Krater schneller respawnen als in der brennenden Steppe?

Weil das heißt für uns Tester, dass wir nur jede Art von Kraut/Erz testen müssen, egal in welchem Gebiet.

Gruß

**Comment by EisenhowerSC** [comment]
Sollen wir uns erstmal auf kräuter konzentrieren?

**Comment by EisenhowerSC** [comment]
Bist du fertig mit programieren?
Können wir mit dem Testen vorfahren?

**Comment by Dotox** [comment]
Klar ihr könnt die ganze Zeit testen, nur eben mit diversen Einschränkungen.

**Comment by Wosser** [comment]
UPDATE???

**Comment by Sheed90** [comment]
Hm, wie solls denn jetzt weitergehen mit dem System?

**Comment by EisenhowerSC** [comment]
Als normaler Spieler finden man einfach kaum Kräuter. Würden uns sehr über ein Statusupdate freuen :)

**Comment by Popowich90** [comment]
Habe das Problem immer noch. Aufm echt Server konnte ich in Azshara kein Traumblatt looten, das lootfenster bleibt leer und die Pflanzen despawnt auch nicht. Alle anderen Kräuter machten kein Problem.
Gibt es schon eine Lösung für die Kräuter/Erz Probleme?

**Comment by Popowich90** [comment]
Problem lag an meinem Client, nach löschen des WTF Ordners, funktioniert es wieder.
