### ISSUE TITLE
Schlaghagel

### ISSUE THREAD

**Issue by Seniorash** [ClassicWoW/Nefarian_1.12.1_Bugtracker#697]
Welches Verhalten wird beobachtet?
Die Aufladungen von Schlaghagel werden nur aufgebraucht, wenn man einen nicht kritischen Treffer landet. Heldenhafter Stoß und Spalten verbrauchen ebenfalls keine Aufladungen.

Wie sollte es sich verhalten?
Die Aufladungen sollten auch aufgebraucht werden, wenn man verfehlt oder parriert/ausgewichen/immun wird. Auch autohit-basierte Fähigkeiten sollten Aufladungen aufbrauchen.

Schritte zur Reproduzierung
Gegner mit Schlaghagel verfehlen oder Heldenhafter Stoß/Spalten benutzen.

Zusätzliche Informationen (Screenshots, Videos, etc.)

http://www.wowwiki.com/Flurry_(warrior_ability)?oldid=1300891
Flurry will consume charges regardless of whether your attack hits, misses, or is dodged/parried/blocked.

https://www.youtube.com/watch?v=ISx6eni6I1k

Links aus unserer Datenbank
Flurry: http://datenbank.welli-it.de/?spell=16284
Heroic Strike:http://datenbank.welli-it.de/?spell=25286
Cleave;http://datenbank.welli-it.de/?spell=20569

Zusätzliches
Ich vermute, dass der Fehler auch bei Schamenen auftritt.

**Comment by Frostlatte** [comment]
Beim Shami trifft es nur bedingt zu, da wir nur Sturmschlag als  "Cast"-Schlag bestizen. Und dieser verbraucht wiederum 1x Flurry....was mich wundert, da es ja eigentlich ein Extra-Schlag ist.

**Comment by wahaxlekuke** [comment]
> Beim Shami trifft es nur bedingt zu, da wir nur Sturmschlag als "Cast"-Schlag bestizen. Und dieser verbraucht wiederum 1x Flurry....was mich wundert, da es ja eigentlich ein Extra-Schlag ist.

Soll das so sein?

**Comment by Seniorash** [comment]
Nur autohitbasierte Fähigkeiten und Autohits sollten flurry aufbrauchen, also immer wenn ein Swingtimer endet. Sturmschlag gehört nicht dazu
