### ISSUE TITLE
Warlock Succubus

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#698]
Welches Verhalten wird beobachtet?
Die Succubus kann ihre Fähigkeiten  Seduction während des Laufens benutzen und aus einem CC heraus (zb Scatter).

Wie sollte es sich verhalten?
Sollte nicht so sein, weil sie den Zauber casten muss und dafür halt stehen bleiben muss.

Links aus unserer Datenbank 

http://datenbank.welli-it.de/?spell=6358 - Seduction

**Comment by bugreportor** [comment]
Nicht nur das. Succubus kann auch seducen wärend der WL noch auf dem Mount sitzt, dabei sollten alle Fähigkeiten solange deaktiviert sein.

**Comment by Slimmer2** [comment]
Bei mir wird beim Reiten alle Fähigkeiten der Pets grau und somit deaktiviert

**Comment by wahaxlekuke** [comment]
Zumindest das auf dem Aufmounten konnte ich fixen, weil ich das reproduzieren konnten. Der Rest hat bei mir nicht funktioniert.

**Comment by SirBeansen** [comment]
Das mit dem Aufmounten ist ganz easy. Der Zauber grauen aus und auch das Pet geht auf passiv. Doch wird es nur angeziegt. In wirklichkeit hat das Pet noch den vorher eingestellen modus.

Zb: Pet ist Defensive und hat alles spells auf auto. Man mounted auf > Pet wird auf Passiv angezeigt, bleibt aber in wirklichkeit im Defensiv modus und kann so zb Seduction zaubern, obwohl der Hexer auf seinem mount reitet.

Zu meinem Bug report.....kannst du mir ein Hexer auf dem Test server zur verfügung stellen? dann kann ich dir ein video machen.
