### ISSUE TITLE
Stun lokalisierung

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#700]
Welches Verhalten wird beobachtet?
spieler und npcs verschwinden komplett von der map oder stehen an ganz anderen stellen, wie an der position, an der sie stehen sollten. wenn der stun endet sind sie wieder da, wo sie seien sollten. auch werden sie manchmal ca 2-3 meter an falschen stellen angezeigt. passiert auch häufiger bei fear. als paladin renn ich dann extrem schnell übers schlachtfeld um am ende wieder ganz woanders rauszukommen.

Wie sollte es sich verhalten?
spieler sollten mir dort angezeigt werden, wo sie sich befinden. auch bei stun und fear.

Schritte zur Reproduzierung
beispiel: stunne vorbeireitenden spieler im pvp mit hammer der gerechtigkeit
auswirkung: a)verschwindet komplett von der map --->stun endet, auf einmal wieder da, ist währenddessen an der stelle hitbar
b) spieler wird mir an einer position angezeigt--->drücke stun, auf einmal steht der spieler ca. 2-5 meter weiter "vorne" in die richtung in die er gelaufen ist.
will ich den spieler nun schlagen, muss ich auf die postion laufen, auf der ich stun gedrückt habe, obwohl seine animation ganz woanders ist.

**Comment by SirBeansen** [comment]
Glaube der bug lässt sich ganz einfach repoduzieren indem den Spieler der gestunt werden soll während des laufens und er springt gestunt wird.

Also Pala läuft hinter Krieger her > Krieger spirngt die ganze Zeit herum, während des laufens und wenn der Krieger in der Luft ist > versuchen zu stunnen. Dann ist der Bug bei mir oft aufgetreten.

Der Bug tritt auch bei Fear und Eisfalle auf.

**Comment by Sabbaer** [comment]
NOT MARKED NOT FIXED! dieser bugg ist extrem nervig!

**Comment by Testear** [comment]
Dieser Bug funktioniert auch mit allen anderen Stuns!

**Comment by Dotox** [comment]
Mittlerweile gab es dazu ein Update, welches einige Probleme behoben hat. Allerdings wird es das Problem immer geben, solange es Lags gibt. Die Lags verursachen nämlich das Anzeigeproblem mit der Position des gestunnten Spielers.

**Comment by hraesvelgr** [comment]
mir ist es beim schurken jedenfalls aufgefallen,d ass das nur bei gegnern passiert, die den schurken beim schleichen erwischt haben.bemerkt ein npc aus der entfernung einen schurken zb, dann dreht er sich in richtung schurke, ohne direkt anzugreifen. 

also:

npc läuft in richtung x, schurke schleicht von richtung y heran.
npc entdeckt schurke, dreht sich selbst in richtung z (welche das gegenteil von y sein soll) und greift evtl an
schurke macht solarplexus (stun).
npx steht wieder in richtung x gedreht, zumindest visuell. 

backstab geht dann totzdem noch in richtung z, obwohl da snicht möglich sein sollte.
ist halt ein reiner anzeigefehler.

**Comment by Dotox** [comment]
Immnoch vorhanden?
