### ISSUE TITLE
auto hit bugg

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#701]
Welches Verhalten wird beobachtet?
nach stuns von schurken und kriegern weigert sich mein char vehement zuzuschlagen
muss auto attack abbrechen, wieder starten, dann gehts wieder
Wie sollte es sich verhalten?
stuns sollten den auto attack nicht für immer unterbrechen obwohl er gestartet ist
Schritte zur Reproduzierung
bg gehen
ist mir im pve nicht mehr aufgefallen
glaube gab dazu schonmal einen buggtrack, entweder geschlossen oder ich bin zu doof zum suchen sry

**Comment by DrTonic** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/485

**Comment by Sabbaer** [comment]
danke

**Comment by pvpmaster2000** [comment]
Der Autohit bug tritt aber z.B. auch auf wenn man länger als 5 Sekunden keinen Schaden macht und auch keinen erleidet (z.b. wenn der Schaden absorbiert wird oder man in der Bubble eine Swingtime von mehr als 5 Sekunden hat. OOC->Autohit stopt, obwohl man die ganze zeit in MeeleRange "auf Angriff" stand.

**Comment by Sabbaer** [comment]
NOT MARKED NOT FIXED! dieser bugg ist extrem nervig!

**Comment by Slimmer2** [comment]
Ich hab den Bug auch bei meinen LvL 22 Krieger beim Questen und inis ohne das ich gestunt wurde

**Comment by Frostlatte** [comment]
Der Bug tritt zur Zeit in fast jedem BG auf. Als Meleeklasse im Grunde das Todesurtel im 1vs1.  Das verlinkte Video aus Issue 485 zeigt im Grunde das gleiche Verhalten wie beim Schamanen und anderen Klassen.

https://www.youtube.com/watch?v=wYcqdwWSBSs&feature=youtu.be
