### ISSUE TITLE
[DROP] Dickschalige Muschel

### ISSUE THREAD

**Issue by Amasov** [ClassicWoW/Nefarian_1.12.1_Bugtracker#705]
Beobachtet: Sumpfland, Blaukiemenmarschen
Drop: Dickschalige Muschel
Mob: Murlocs
Datum: 01.05.2015 ca. 13:30h

In jeder dickschaligen Muschel war entweder eine irisierende kleine Perle, oder eine schillernde Perle enthalten.

![dickschalige_muschel](https://cloud.githubusercontent.com/assets/11898994/7429832/36158e82-f009-11e4-8791-60b55ff9cbd6.jpg)

**Comment by Slimmer2** [comment]
Hier der Link zum Item
http://datenbank.welli-it.de/?item=5524#contains

**Comment by c0keh** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/585
