### ISSUE TITLE
Arkane Geschosse im Raid weiterhin useless

### ISSUE THREAD

**Issue by Feddebla** [ClassicWoW/Nefarian_1.12.1_Bugtracker#707]
Hi Serverteam,

die arkanen Geschosse funktionieren trotz mehrfacher Ankündigung in den Patchnotes immer noch nicht. 

Es ist nur einem einzigen Magier im Raid möglich Arkane Geschosse zu casten. Fängt ein Zweiter an diese Geschosse zu casten unterbricht der Zauber bei Magier 1. 

Wird dieser Cast evtl. als Debuff gewertet und dann von einem anderen Magier der Arkane Geschosse castet überschrieben, sodass sich die Magier ihre arkanen Geschosse untereinander blockieren/ vom Mob runternehmen?

**Comment by dagochen** [comment]
Jep korrekt, genau da liegt der Hund begraben ;) Problem bekannt und wird demnächst gelöst ;)

**Comment by Feddebla** [comment]
Ok, Danke für die schnelle Info :)

**Comment by wahaxlekuke** [comment]
Das Problem tritt nur dann auf, wenn man unterschiedliche Ränge von Arkane Geschosse benutzt. Wenn alle den höchsten Rang verwenden, funktioniert es.
