### ISSUE TITLE
Hexenmeister: Pets ausgewechselt

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#709]
**Welches Verhalten wird beobachtet?**

Die Diener der Hexer werden in unregelmäßigen Abständen ausgewechselt. Es scheint, dass man  einfach einen neuen Begleiter "lernt", da er einen neuen Namen hat und nur die Rang 1 Zauber kann, die er zu Beginn können müsste.

**Wie sollte es sich verhalten?**

Sollte nicht passieren.

**Zusätzliche Infos**

http://community.mmobase.de/hexenmeister/6942-pets-ausgewechselt.html

**Links aus unserer Datenbank**

Sind zwar die Beschwörungszauber. Ich glaube aber nicht, dass es was mit den Zaubern direkt zu tun hat.
Wichtel: datenbank.welli-it.de/?spell=688
Teufelsjäger: http://datenbank.welli-it.de/?spell=691
Sukkubus: http://datenbank.welli-it.de/?spell=712
Leerwandler: http://datenbank.welli-it.de/?spell=697

**Comment by dagochen** [comment]
Zum Reproduzieren wäre es gut, wenn herausgefunden wird, wann bzw. wie es dazu kommt. Login/Logout? Tot des Begleiters? Oder vielleicht doch was ganz anderes?

**Comment by hraesvelgr** [comment]
- kam der fehler beim einloggen/reloggen?
- ist es beim neubeschwören passiert?
- hast du evtl vorher ordner gelöscht, neue addons hinzugefügt, etc?
- begleiter gestorben (oder geopfert), neu beschworen, oder durch zu große entfernung verschwunden?
- betreten von instanzen? 

die liste ist bald endlos :)

**Comment by Gnomorus** [comment]
Ich weiß, dass der fehlende Auslöser des ganzen wohl das wichtigste an dem ganzen Report wäre. Allerdings kann ich dazu noch keine wirklich hilfreichen Angaben machen, da mir noch nichts aufgefallen ist.
Auf jeden Fall ist mir bis heute folgendes noch NICHT passiert:
- auswechseln des selben Pets während einer Sitzung (ohne erneuten Login dazwischen)
- während er am Leben war (wäre auch sehr komisch)

Darüber hinaus wird WDB bei jedem Spielneustart gelöscht.

Auch würde ich einen Zusammenhang mit dem Opfern der Pets als unwahrschienlich ansehen, da bei mir und den Hexern, die bislang das gleiche Problem hatten, vorrangig Wichtel und Leerwandler betroffen sind, welche selten bis garnicht geopfert werden.

Eine Vermutung meinerseits: Der Wichtel despawnt meistens nicht korrekt, wenn man ihn an einer Stelle stehen lässt und sich entfernt. Dies passiert vor allem in Instanzen. Danach kann man ihn auch nicht mit einem Rechtsklick auf das Portrait und "freigeben" freigeben, sodass man einen neuen über den alten Wichtel drüberbeschwören muss.
Dies wäre zumindest eine Begründung, dass der Fehler meistens beim Wichtel auftritt. Ich werde dem innerhalb der nächsten Tage nochmal nachgehen.

**Comment by dagochen** [comment]
Das mit dem Verlust der Kontrolle über den Begleiter ist mir beim Jägerpet auch schon aufgefallen, wenn die Distanz innerhalb einer Instanz zu groß ist. Nur das wir halt nicht das Problem mit den "Zufallsnamen" und dem "komplett neubeschwören" haben. Aber vielleicht ist das ja ein guter Anhaltspunkt zum suchen.

**Comment by Haudraufinix** [comment]
Die Teufelswache die man in BC haben konnte hatte bei jedem Mal neu skillen stets einen anderen Namen. Vielleicht bringt irgend ein Fehler in der DB o.ä. das Spiel dazu den Hexern den Skill fürs beschwören "Neu beizubringen" bzw die Verlinkung zwischen Wichtel und Begleiter werden vertauscht/gelöscht

**Comment by Malgora** [comment]
Der Fehler ist reproduzierbar:

- Pet muss vorhanden sein (Wichtel, Sukku, was auch immer)
- Höllenbestie muss beschworen werden
- Höllenbestie muss sterben
- Wird das selbe Pet, das vor dem Beschwören der Höllenbestie da war wieder beschworen, besitzt dieses keine Skills und einen neuen Namen.

Ich wäre über eine zügige Bearbeitung des Problems durchaus glücklich.

**Comment by Crippi** [comment]
Habe das Problem zusammen mit Malgora beobachtet!! Kann dies nur bestätigen.

**Comment by Gnomorus** [comment]
Aaaah. Danke für die Recherchearbeit. Das erklärt zumindest auch, warum der Fehler erst seit kurzem auftritt. Das automatische Freigeben wurde ja erst kürzlich so eingerichtet.

**Comment by dagochen** [comment]
Man munkelt, dass dieses Feature von einigen Jung-Helden aus Goldshire gewünscht wurde, da dort häufig diverse Höllenbestien im und vor dem Gasthaus am wüten waren. Folglich handelt es sich hier nicht um einen Bug.

**Comment by Gnomorus** [comment]
Bei dem automatischen Freigeben handelt es sich nicht um einen Bug, ja. Aber bei dem dadurch ausgelöstem Petwechsel doch sehrwohl!

**Comment by wahaxlekuke** [comment]
Danke für den Hinweis! Mit dem nächsten Serverneustart sollte das Problem behoben sein.

**Comment by Gnomorus** [comment]
Getestet. Funzt. Danke!
