### ISSUE TITLE
Hexenmeister Pet (Wichtel) - reagiert nicht

### ISSUE THREAD

**Issue by Matrose44** [ClassicWoW/Nefarian_1.12.1_Bugtracker#711]
Problem:
Nach der Beschwörung lässt sich der Wichtel über die Leiste nur extrem eingeschränkt steuern.

1. Angriff auf Ziel - geht nicht - Pet verharrt an der Stelle (obwohl nicht passiv)
2. Folgen - geht
3. Stehenbleiben - geht
4. Feuerblitz - geht - muss aber nach 1x casten, immer wieder neu gecastet werden.
5. Aggressiv - geht nicht - Pet verharrt regungslos - bleibt passiv
6. Defensiv - geht nicht - Pet verharrt regungslos - bleibt passiv

bitte einmal überprüfen - Danke

**Comment by Haudraufinix** [comment]
Zu Punkt 4: Hast du den Feuerblitz auf Autocast gestellt -> Rotierendes Gelbes Glitzern um den Skill. Ansonsten zaubert er ihn nur 1x pro Befehl.
Dazu betreffend Punkt 1. Wichtel besitzen "normalen" Angriff. Sie greifen lediglich mit Feuerblitz an.

5 und 6: Wichtel haben Phasenverschiebung. Diese macht den Wichtel unverwundbar aber verhindert dazu, dass er an Kampfhandlungen teilnimmt. Diese beendet er auch nur, wenn er ausdrücklich zum Angriff befohlen wird.
Er wird also auch als Agressiv oder als Defenisv in einer "Passiven Haltung" bleiben.

Bitte Schau ob die Probleme auch mit Feuerblitz auf Autocast und ohne Phasenverschiebung auftreten

**Comment by hraesvelgr** [comment]
siehe dazu: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/664

**Comment by dagochen** [comment]
"bitte einmal überprüfen - Danke"

DU musst es überprüfen. Danke ;)
