### ISSUE TITLE
Quest: Arena Grand Master Level vorraussetzung

### ISSUE THREAD

**Issue by Envie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#712]
Moin, 
die Quest "Arena Grandmaster" (http://www.wowhead.com/quest=7838/arena-grandmaster)
sollte eigendlich keine Level Vorraussetzung haben, wie die Vorquest "Arena Master" (http://www.wowhead.com/quest=7810/arena-master). Zu Patch 1.12 wurden mit diesem Trinket immerhin Dodge-Twinks / 19er PvP Twinks etc. gespielt, wofür es auch genug Quellen im Internet geben sollte.

mfg

**Comment by dagochen** [comment]
Dann poste bitte diese Quellen. Danke.

**Comment by dagochen** [comment]
http://www.wowhead.com/quest=7838/arena-grandmaster

**Comment by Envie** [comment]
http://wow.allakhazam.com/forum.html?forum=243&mid=1148303395196043608

Falls dies als Quelle ausreicht.
