### ISSUE TITLE
Quest: Die große Maskerade

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#713]
Was wird beobachtet:
Wenn man Reginald Windsor durch Stormwind folgt bleibt er öfters hängen und geht nicht weiter.
Zudem Resetet das Script nicht von alleine, nach dem man die Quest abgegeben hat.
Bei dem Event/Script kniet General Marcus Jonathan links an der Brücke nieder und bleibt nach abschließen der Quest dort.

Wie sollte es sich verhalten?
Reginald Windsor sollte nach dem General Marcus Jonathan sich seitlich hinkniet ohne hängen zu bleiben bis zur Burg hochgehen.
Das Script sollte sich nach abschliesen der Quest bzw nach einer gewissen Zeit resetten.

Schritte zur Reproduzierung:
Quest annehmen und den Reginald Windsor folgen. 

Link zur Datenbank:
http://datenbank.welli-it.de/?quest=6403
Quest die sich durch das nicht resetten nicht abgeben lässt, https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/433

**Comment by dagochen** [comment]
Ich hab die Quest auch anders in Erinnerung, aber bisher nicht viel dazu gefunden. Oben im Thronsaal meine ich, dass die Wachen sich in Drachen verwandeln sollten und dann diesen Bolvar-irgendwas-Typ angreifen müssten, was sie aktuell leider nicht tun. Oder hab ich das falsch in Erinnerung?

**Comment by Slimmer2** [comment]
Ja das war bei mir noch wie ich meine Ony Pre gemacht habe im Herbst letztes Jahr

**Comment by hraesvelgr** [comment]
generell ist das ganze script verbuggt bis sonstwo. falsche emotes/texte, wachen salutieren /verwandeln sich nicht, das script wird nicht resettet und/oder bricht mittendrin einfach so ab... und und und. sollte man vllt mal komplett neu implementieren, dafür gibts sicher schon komplettfixes.
