### ISSUE TITLE
Nefarian Paladin Call

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#716]
Welches Verhalten wird beobachtet?
Der Pala Call geht teilweiße bis zu 45 sec lang.

Wie sollte es sich verhalten?
Der Paladin sollte wie jeder andere Call nur 30 sekunden.
Es scheint so als würde er sich die melee bubble kurz vor ablaufen der 30 sek nochmal drauf zaubern.

**Comment by dagochen** [comment]
Quelle?

**Comment by Sabbaer** [comment]
funktionierte eben im raid mit 30 sek keine meele bubble nach ablauf durch nefarian

**Comment by Haudraufinix** [comment]
Kann gut sein, dass das so gewollt ist. Nefarian erlangt für 30 Sekunden "Kontrolle" aber es heisst nicht, nach 30 Sekunden muss der Effekt zuende sein. Durch Magier Classcall gesheepte Ziele bleiben auch gesheept. Selbiges verhalten ist auch beim Schami Classcall zu beobachten. Er behält die Effekte solange das Totem steht.

Ich spiele leider keinen Allianzler, der "normale" Segen des Schutzes lässt sich bannen, vlt kann man nach 30 Sekunden den letzten Segen von einem Priester dispellen lassen.

**Comment by Sabbaer** [comment]
der paladin klassencall funktioniert einwandfrei ist ohne fehler mit richtiger zeit und korrektem sds auf nefarian. Wenn der buff noch 1 sek aufm pala ist und man läuft zu früh raus, dann bufft er nefarian mit sds, der dann die volle zeit noch läuft, und das ist auch richtig so wie in videos zu eindeutig zu sehen ist.
Plz close

**Comment by wahaxlekuke** [comment]
Ohne entsprechende Quelle werde ich hier erstmal nix ändern.
