### ISSUE TITLE
Schattenhaftigkeit bugt seit Patch

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#718]
Welches Verhalten wird beobachtet?
Schattenhaftigkeit lässt sich nicht mehr direkt benutzen wenn man einige Aktion ausführt. Ist seit dem letzten Patch so.
Der Spell lässt sich teilweiße erst beim 3 versucht ausführen.
Fehlermeldung: Der Zauber ist noch nicht bereit.

Wie sollte es sich verhalten?
Sollte wie vor dem Patch sein und keine verzögerung haben,

Schritte zur Reproduzierung
Wasser Trinken und versuchen direkt die Fähigkeit zu benutzen > Funktioniert nicht
Totstellen und versuchen direkt die Fähigkeit zu benutzen > Funktioniert nicht

Links aus unserer Datenbank 

http://datenbank.welli-it.de/?spell=20580

**Comment by bugreportor** [comment]
Ist das immer so oder tritt der Fehler nur unter bestimmten Umständen oder nach einer bestimmten Aktion auf?

**Comment by dagochen** [comment]
Ich kanns aktuell in Ironforge nicht reproduzieren :(
