### ISSUE TITLE
Pechschwingenhort: Techniker bei Vaelastrasz werden zu Corinna Stähler

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#719]
**Welches Verhalten wird beobachtet?**

Die Techniker, die wegrennen, sobald man in den Raum von Vaelestrasz geht, werden nach einigen Sekunden unsichtbar. Dabei werden sie auch mitten im Raum unsichtbar und nicht nur oben am Tor. Sie bleiben aber wohl am Leben und man kommt nicht außer Kampf und bekommt Schaden von ihnen bzw. der guten Corinna Stähler. Man kann sie dennoch mit AoE Angriffen umhauen.

**Wie sollte es sich verhalten?**

Die Techniker sollten nur am oberen Tor despawnen/sterben und nicht unsichtbar werden.

**Links aus unserer Datenbank**

Techniker der Pechschwingen: http://datenbank.welli-it.de/?npc=13996

**Comment by Sabbaer** [comment]
i love u

**Comment by wahaxlekuke** [comment]
Tritt das Problem immer noch auf?

**Comment by Sabbaer** [comment]
das problem trat im gestrigen BWL raid nicht mehr auf

**Comment by Gnomorus** [comment]
Meine Beobachtungen gleichen sich mit Sabbaers.
Allerdings Laufen die Techniker jetzt (wie vorher) von Vael hoch zum Tor und anschließend wieder runter in die Gruppe. D.h. sie despawnen nicht oben am Tor, wie es eigentlich sein sollte.

**Comment by Sabbaer** [comment]
1 spieler blieb heute wieder infight 01.06.2015
