### ISSUE TITLE
Arkane Geschosse im Raid weiterhin useless

### ISSUE THREAD

**Issue by Feddebla** [ClassicWoW/Nefarian_1.12.1_Bugtracker#720]
Hi Serverteam,

Arkane Geschosse funktionieren nun leider noch weniger. Es kommt teilweise nur ein Geschoss raus bzw. gar keins mehr im Raid.

**Comment by Feddebla** [comment]
Ok komischerweise hat es eben bei einem arkananfälligenmob funktioniert. Davor an anderen Mobs nicht. komisch

**Comment by dagochen** [comment]
Arkane Geschosse nutzen einen unsichtbaren Debuffslot, der dennoch zu den 16 maximalen Debuffs gehört. Das ist schon korrekt so, ob es von der Priorität stimmt, ist allerdings nicht ganz sicher. Gibt leider nicht viele Videoquellen, an denen man erkennen kann, was genau Arkane Geschosse runterschubsen. Vielleicht findet da noch wer was?

**Comment by Feddebla** [comment]
Aber wenn man sich Videos von früher anschaut, sieht man bei vielen Bossfights, dass alle Magier AM casten, auch aufgrund der geringen Aggro, die die Geschosse verursachen. Also ich denke es sollte nicht abhängig vom Debuffslot sein, ob sie castbar sind?

**Comment by dagochen** [comment]
Die Prio ist eh hoch genug, dass sie nicht runtergeschossen wird. Vielleicht noch ne andere Idee?

**Comment by hraesvelgr** [comment]
-http://wowmb.net/forums/f9/6762-debuff_dots_priority_rules/
 Everything that puts an icon on the monster's portrait is something that takes up one of the 16 slots. This includes our curses, corruption, immolate, drain life or drain siphon. People refer to them as debuff slots but the slots take debuffs, magic damage (immolate), weapon procs, talent spell procs (like the after effect of a fire mage's fire spells), etc. 

habt ihr je dran gedacht, es in debuffs zu unterteilen die "ein icon verursachen" und in debuffs die "kein icon verursachen"?

denn arkane geschosse verursacht definitiv keins. man könnte also debuffs, die kein icon verursachen unendlich oft gleichzeitig draufhaben, und debuffs, die eins verursachen eben auf 16 begrenzen. 
wäre die simpelste lösung, jedoch denke ich, dass es auch da bei gewissen spells einen haken gibt.

**Comment by dagochen** [comment]
Nein das wäre falsch. Es gibt Videos wo man es ganz gut sieht:
https://www.youtube.com/watch?v=uKEhgE7J7UY
Bei Minute 4 ist Chromaggus Arcane anfällig. Schwupp sind es nur noch 13 Debuffs und 3 Magier casten von hinten Arkane Geschosse (sieht man, wenn er sich dreht). Gibt noch paar Szenen in dem Video wo es zu sehen ist. Hatte auch schon mal ein anderes Video, das ich grad nicht wieder finde. 

Die Variante die du vorgeschlagen hast, klingt nicht schlecht, aber es gibt dafür einfach keine Quellen, dass es so war und würde das System schon arg vereinfachen. Es war damals einfach mühselig und doof, das war ja das schwere daran. Man hat einfach nicht 10 Krieger mitgenommen und Jäger haben keine Schlangenbisse gesetzt...war halt so ;)

**Comment by hraesvelgr** [comment]
was wohl der angesprochene haken  wäre. die letzte  möglichkeit wäre dann, arkane geschosse eine so hohe debuff-prio zu geben, dass sie einfach nicht überschrieben werden können. 
ich hab jedoch das gefühl, dass man mit einer einfachen lösung für einen spell ziemlich viel versauen kann.

**Comment by Feddebla** [comment]
Ok klingt plausibel. Aber Mal andersrum: Ich habe auch noch kein Video gesehen, bei dem plötzlich alle Mages beim Casten unterbrochen werden bzw. der Cast einfach abbricht bzw. die Hände leuchten aber keine Geschosse rausfliegen. Daher glaube ich, dass die Prio hier bei uns auf dem Server für Arkane Geschosse weiter hoch gesetzt werden muss. Man findet ja zig Videos, wenn man bei YouTube nach den Firstkills von Bwl Bissen sucht, bei denen fast alle Mages AM casten. Ich habe es ausgesagt noch nie abbrechen sehen.

**Comment by Feddebla** [comment]
*Bossen ; *wiegesagt ps: mit Handy geschrieben ;)

**Comment by Haudraufinix** [comment]
Ich denke ne höhere Priorität für "Hidden" Debuffs wie Arkane Geschosse und Bodeneffekte (Weihe, Flammenschlag, Sprengfalle, Höllenfeuer etc.) tut im Endeffekt keinem Weh und wäre eine gute Möglichkeit Arkane Geschosse spielbar zu kriegen.

**Comment by hraesvelgr** [comment]
weihe verursacht mein er meinung nach immer schaden (selbst wenn 16 slots voll sind). sind bodeneffekte da nicht etwas anderes, als ein direkter spell?

**Comment by Haudraufinix** [comment]
Ich habs selbst erst mit der Huntertrap ausgetestet, aber diese belegt definitiv einen Debuffslot

**Comment by Feddebla** [comment]
Hier ein Video vom Broodlord: https://www.youtube.com/watch?v=Obbnvcgabwg    

Zwischen 2:40 -3:00 sieht man das 16 Debuffs auf dem Boss sind aber trotzdem Arkane Geschosse auf den Boss fliegen!

**Comment by dagochen** [comment]
Das letzte Video ist bereits mit mehr als 16 Debuffslots, sprich das ist 2.0 Pre-BC-Patch.

Ich vermute, dass alle Channeling Spells, grade wegen dem channeling-Effekt und der besonderen Mechanik von diesen Spells, eine sehr hohe Prio haben sollte.

**Comment by Haudraufinix** [comment]
Wenn du beim 1. Link genau hinsiehst siehst du, dass es 15 Debuff slots sind, ein 16er dazu kommt und direkt wieder verschwindet. Das ist wohl weil die Arkanen Geschosse gerade auslaufen -> Debuff weg -> und wieder neu gecastet werden -> Neuer Debuff.

**Comment by hraesvelgr** [comment]
bei dem ersten video auf 2:50 sieht man ziemlich genau, wie die arkanen geschosse gerade angefangen werden, und es 16 debuffs werden, obwohl die geschosse gerade gechannelt werden. sollte das letzte egschoss nicht genau dann einschlagen, wenn der cast grad ausläuft? das heißt, solange es gechannelt wird, fliegen geschosse, egal wo sie grad sind. geschosse existieren -> channel läuft -> debuff sollte da sein. ist er aber nicht. es sind 16 sichtbare debuffs UND die geschosse werden gechannelt.

**Comment by Haudraufinix** [comment]
Bei uns im Raid wurde gestern die Beobachtung gemacht, dass Arkane Geschosse funktionierten ( von mehreren Mages) bis unser Schattenpriester Gedankenschinden aufs Ziel gewirkt hat. Ich könnte mir vorstellen dass der Debuff ähnlich wie bei den verschwindenden Hexerflüchen falsch entfernt wird wenn iwas ausläuft. Vlt hilft diese Erkenntnis beim Fixen

**Comment by wahaxlekuke** [comment]
Ich hab eine mögliche Ursache gefunden. Damit sollte das also mal wieder behoben sein.... 
Mit dem nächsten Serverneustart sollte der Fix aktiv sein.

Außerdem schließ ich mal dieses Ticket, aber lass dafür #707 offen.
