### ISSUE TITLE
Broken Tooth (pet) falsche Laufgeschwindigkeit

### ISSUE THREAD

**Issue by ciscologne** [ClassicWoW/Nefarian_1.12.1_Bugtracker#722]
Servus,

seit einigerzeit attackiert das Pet "Broken Tooth" mit falscher Anlaufgeschwindigkeit. Das läuft wie folgt ab:

1. Wenn das Pet zum angreifen zum Gegner läuft, tut es dies zu langsam. Die Laufanimation ist auch die falsche; das Pet "schleicht" zum gegner, also ob es stealthen würde, es aber de facto nicht tut (siehe Bild: http://abload.de/img/slowchjv2.jpg)

2. Das ganze tritt in ca 80% der Fälle bei jedem Angriff auf (hier z.b. nicht: http://abload.de/img/normalrkkwf.jpg). Das führt dazu, dass NPCs, als auch Gegner im PVP problemlos von der Katze weglaufen können. Bild 2 zeigt die "normale" Laufanimation

3. Das Pet läuft nach dem Kampf, sobald der Mob tot ist, mir sehr hohem (als ob es sprinten würde) Tempo zu mir zurück.

3. Ein anderer Hunter bestätigte mir, dass sein Broken Tooth ähnliches verhalten zeigt, wenn seine sprint Fähigkeit einen cooldown hat.

4. Bei anderen Pets, inkl. anderer Katzen tritt das Phänomen nicht auf. Wahrscheinlich beschränkt sich das also wirklich nur auf Broken Tooth. Wissenswert: Ich habe eine BM Skillung, demnach die +30% Laufgeschwindigkeit im freien. Vielleicht hängt es damit zusammen, jedenfalls sind es gefühlt eher -30%.

**Comment by ciscologne** [comment]
Zusatz: Das Problem tritt unabhängig auf, egal ob drinnen oder draußen.

**Comment by wahaxlekuke** [comment]
Besteht das Problem immernoch?

**Comment by ciscologne** [comment]
Jup, aber gefühlt seltener. In 40% der Fälle, ganz grob geschätzt.

**Comment by wahaxlekuke** [comment]
Das ist nur ein Anzeige-Fehler, der sich wahrscheinlich auch nicht beheben lässt.
