### ISSUE TITLE
Buffstacking Regelung

### ISSUE THREAD

**Issue by Classic-WoW** [ClassicWoW/Nefarian_1.12.1_Bugtracker#726]
Welches Verhalten wird beobachtet?
Es geht mir um zwei Threads welche man (Stellenweise) widerlegen kann:
1. ) http://community.mmobase.de/hilfe-und-support/6636-doppeltes-trinket-zuenden-per-makro.html
2. ) http://community.mmobase.de/talk-und-allgemeines/5167-buff-stacking.html
Wie sollte es sich verhalten?
Manche Buffs sollten stacken.

Schritte zur Reproduzierung
/

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://www.warcraftmovies.com/movieview.php?id=18906 
http://worldofwarcraft.filefront.com/file/RedEyes;60914 (DL Link weil kein Stream)

Im Ersten Link findet sich oben rechts das Upload datum! Mitte 2006 irgendwas.
Da der Stream aber kaputt ist muss man sich das downloaden.

0:21 http://datenbank.welli-it.de/?item=18820 + 
http://datenbank.welli-it.de/?item=22678

3:04 http://datenbank.welli-it.de/?item=13512 + http://datenbank.welli-it.de/?item=9155

13:56 http://datenbank.welli-it.de/?item=13512 + http://datenbank.welli-it.de/?item=13454

Links aus unserer Datenbank (hier gehts zur Datenbank):

S. oben :)

Zusätzliches:

Ich bin Liebe!

**Comment by Wosser** [comment]
Und du kannst nicht einfach mal schreiben, was genau deiner Meinung nach falsch ist? Muss man sich das alles erst aus deinen Quellen raussuchen?

**Comment by Bladsn** [comment]
Wie sollte es sich verhalten?
Manche Buffs sollten stacken.

**Comment by Haudraufinix** [comment]
Manche ist recht präzise :D

**Comment by dagochen** [comment]
Ich sehe jetzt schon das "Dev abgelehnt"-Label hereinfliegen....weil der Report mehr Recherche durch das Entwickler-Team als Entwickler-Arbeit erfordert ;)

**Comment by Bladsn** [comment]
DL Link nutzen, Video laden und die angegebenen Zeiten ansehen (Buffleiste). 
Die anderen Links sind reine Statistik (Streamlink dient nur zur Beweispflicht, weil da ein Uploaddatum angegeben ist), die anderen zwei Forenlinks sind lediglich zur Info da, weil man gewisse "Thesen" widerlegen und richtig stellen kann.

**Comment by Haudraufinix** [comment]
Der erste Kommentar zum Video ist am 16.04.2006. 2 Wochen nachdem der Patch life ging, der besagtes Stacking unterbinden sollte. Kann also gut sein, dass die Videoaufnahmen aus der Zeit VOR 1.10 stammen.
Ausserdem *beweist* das nur einen Fall. Diese beiden Trinkets wenn wir einen generellen Fix wollen wären alternative stichhaltige Quellen wünschenswert.
Das Arkanelixier + Fläschchen wurde schon hier: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/45 reportet

**Comment by SirBeansen** [comment]
laut hordeguides soll Das Arkanelixier + Fläschchen auch nicht stacken.

**Comment by dagochen** [comment]
Bladsn:
> Man sollte sich halt auch mal etwas Zeit nehmen, wenn es um essenziell wichtige Thematiken geht, > die den Progress entweder beschleunigen oder verlangsamen können.

Eben drum sollte der Report "besser" und durchdachter sein, damit er schneller bearbeitet werden kann.

**Comment by Bladsn** [comment]
Man kann es auch übertreiben...
