### ISSUE TITLE
Hunter T2 Setbonus ist Resistbar

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#727]
Der 8/8 Teile Bonus vom Jäger T2 "Schwäche Aufdecken" unterliegt aktuell der "Arkan"Zauberschule und ist resistbar. Nach den 1.10 Patchnotes wurde die Resistbarkeit dieses Effektes allerdings entfernt.

* The Expose Weakness effect of the Hunter's Dragonstalker set can no longer be resisted as a magical spell. -> http://www.wowwiki.com/Patch_1.10.0

Schritte zur Reproduzierung:
Einen Gegner mit Arkanresistenz angreifen und warten bis das T2 Set procct. Zu empfehlen sind hierfür die Arkanelementare in DM west, da sie über 300 Arkanresistenz verfügen und somit fast garantiert widerstehen.

Links:
Schwäche Aufdecken: http://datenbank.welli-it.de/?spell=23578 und http://datenbank.welli-it.de/?spell=23577
Hunter T2: http://datenbank.welli-it.de/?itemset=215
Arkane Entartung (Mob zum Testen): http://datenbank.welli-it.de/?npc=11480

**Comment by Haudraufinix** [comment]
T2 Hunter Setbonus wird immer noch selten Widerstanden!

**Comment by Dotox** [comment]
Hab was geändert, ist auf dem Testserver.
