### ISSUE TITLE
Kalteisenhacke wird nicht als Spitzhacke anerkannt

### ISSUE THREAD

**Issue by CplBasti** [ClassicWoW/Nefarian_1.12.1_Bugtracker#728]
Welches Verhalten wird beobachtet?
Wenn man die Kalteisenhacke im Inventar

Wie sollte es sich verhalten?
Die Kalteisenhacke sollte als Ersatz für die normale Spitzhacke anerkannt werden.

Schritte zur Reproduzierung
Kalteisenhacke im Inventar haben, normale Hacke rauswerfen.
Dann versuchen etwas abzubauen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://abload.de/img/wowscrnshot_051215_10s9uv5.jpg

Links aus unserer Datenbank
http://datenbank.welli-it.de/?item=1959

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/292
/close
