### ISSUE TITLE
Wache in Brill setzt falsche Wegpunkte

### ISSUE THREAD

**Issue by Avalarion24** [ClassicWoW/Nefarian_1.12.1_Bugtracker#729]
Die Wache in Brill setzt falsche Wegpunkte. Zum Beispiel schickt die mich zum Schneiderlehrer, obwohl ich zum Lederverarbeitungslehrer möchte oder man wird zum Bergbaulehrer geschickt, obwohl man Kürschnern lernen möchte

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/451
/close
