### ISSUE TITLE
Lootbug: Handschuhe des Magisters

### ISSUE THREAD

**Issue by ciscologne** [ClassicWoW/Nefarian_1.12.1_Bugtracker#730]
Servus,

habe neulich die Handschuhe in Scholo beim würfeln gewonnen. Meine Taschen waren aber voll, sodass ich hinterher manuell looten musste. Ging aber nicht, wegen des Lootbugs. Wäre top wenn ihr mir die zusenden könntet - danke :) !

http://abload.de/img/lootbugynpgk.jpg

**Comment by Gnomorus** [comment]
war das nicht mal ne zeit lang gefixt? :(

**Comment by dagochen** [comment]
Gibt immer mal wieder Probleme wenn
a) jemand oder alle passen
b) Loot-Modus umgestellt wird
c) Taschen voll sind

**Comment by ciscologne** [comment]
ich habe leider immernoch keinen ersatz bekommen. wäre nett wenn man mir die handschuhe irgendwie zukommen lassen könnte.

**Comment by Larnak1** [comment]
Für solcherlei Anliegen ist das die falsche Plattform, hier sollen allgemeine Fehler gemeldet werden. Für individuelle Hilfe sind die Gamemaster zuständig, die du über das Formular direkt im Spiel erreichen kannst.

**Comment by Gnomorus** [comment]
Ich kann dir gerne die 5g, die die Dinger im AH kosten, zukommen lassen. /w Gnomorus ingame.

**Comment by dagochen** [comment]
Horde...@Gnomorus
