### ISSUE TITLE
Hunter pets sind nicht spottbar

### ISSUE THREAD

**Issue by Grunza** [ClassicWoW/Nefarian_1.12.1_Bugtracker#731]
Gegen Spieler im PvP wirkt Spott natürlich nicht, aber gegen Tiere sollte das so sein.
Referenz: http://wow.ingame.de/forum/threads/115391-Pets-brechen-Falle-durch-Spott?s=3df392b20efe77d60b95e8186

**Comment by SirBeansen** [comment]
Sollte aber nicht funktionieren wenn der Hunter sein Pet nach dem Spott zurückruft.

**Comment by Grunza** [comment]
Ja, völlig richtig. Der Spott kann also manuell vom Hunter beendet werden, das sehe ich auch so. Das heißt aber eben auch, dass die Dauer des Spotts von der Reaktionszeit des Hunters abhängt, wiederum voll ok, das ist eben dann skill ;) Aber momentan funktioniert der Spott eben gar nicht, was bitte geändert werden sollte.

**Comment by Haudraufinix** [comment]
Selbiges wird allem Anschein nach auch für die Hexerpets gelten ;)

**Comment by SirBeansen** [comment]
Und wie verhält sich Spöttischer Schlag?

**Comment by Seniorash** [comment]
Da Masstaunt gehen sollte kann man beim Spöttischen Schlag auch davon ausgehen weil es der gleiche Effekt ist nur ein ein Einzelziel. 
One tactic to easily kill a Hunter is as follows. If you charge in, the Hunter is very likely to have an ice trap waiting for you. Do not fret, though, because you (the cunning Warrior) has a plan. Spam the AoE taunt ability Challenging Shout as you are charging in. If you time it well, it may force the Hunters pet to attack you once you are frozen in the trap, causing the root to be broken and essentially screwing over your enemy. 
Ist zwar aus dem aktuellen wow. Aber diese Mechanik wurde nie geändert http://www.wowwiki.com/Warrior_PvP_guide

**Comment by hmmkay** [comment]
"While still a good practice, it is no longer necessary to call off your pet for a Freezing Trap or any CC which can be broken by damage. The pet now automatically returns to follow mode."
Quelle: http://vanilla-wow.wikia.com/wiki/Freezing_Trap

Sprich: Wenn ein Gegner in der Falle ist, MUSS das Pet auf "follow" gehen. Bitte berücksichtigen

**Comment by hmmkay** [comment]
"While still a good practice, it is no longer necessary to call off your pet for a Freezing Trap or any CC which can be broken by damage. The pet now automatically returns to follow mode."
Quelle: http://vanilla-wow.wikia.com/wiki/Freezing_Trap

Sprich: Wenn ein Gegner in der Falle ist, MUSS das Pet auf "follow" gehen.

**Comment by Haudraufinix** [comment]
hmmkay Das bezieht sich nur darauf, wenn das Pet von dir auf einen Gegner gehetzt wurde. Spott zwingt das Pet hingegen zum Angriff, selbst wenn sein Ziel in eine Eisfalle tritt.

Deine Quelle dreht sich schlicht um eine andere Mechanik ;)

**Comment by wahaxlekuke** [comment]
> Quelle: http://vanilla-wow.wikia.com/wiki/Freezing_Trap

Dieses Wiki ist leider keine verlässliche Quelle. Viele Artikel (wie z.B. den über Freezing Trap) sind einfach 2010 von der von wowwiki.com-Seite kopiert worden (Siehe http://www.wowwiki.com/Freezing_Trap?oldid=2184663).

In den Wiki-Artikel von 2006 findet man eigentlich immer den Hinweis, dass man sein Pet manuell auf Passiv stellen muss. http://www.wowwiki.com/Freezing_Trap?oldid=366627
> Be sure to have your pet in passive mode so it doesn't attack your enemy and counteract the trap.

**Comment by hmmkay** [comment]
Ich habe lange gesucht aber ich konnte keine offizielle Quelle finden, die den Bugfix hier rechtfertigt.... Dass das Pet die Eisfalle nicht bricht, war das einzige, was man dazu finden konnte. Und da es seitdem keinen Patch gab der das geändert hat (die sind ja alle unten vermerkt...). Aber nagut, ist ja schon life aufm Server. Hoffentlich können Hunterpets dann auch andere Pets Spotten :D. Ist ja die selbe Mechanik^^

**Comment by Haudraufinix** [comment]
nein, ist leider nichtmal die selbe Mechanik, Hunterpets besitzen nämlich keinen "Spott" sondern lediglich einen Zauber der einen Fixwert Aggro erzeugt :D

**Comment by hmmkay** [comment]
Dem Tooltip nach zu urteilen schon^^

**Comment by Haudraufinix** [comment]
http://datenbank.welli-it.de/?spell=15151 <- Knurren
http://datenbank.welli-it.de/?spell=355#taught-by-quest Spott
Nichtmal ansatzweise das selbe
