### ISSUE TITLE
UBRS Bugs

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#732]
**Welches Verhalten wird beobachtet?**
Mehrere Bugs:
1. Awbee ist angreifbar, sollte aber allen Spielern gegenüber freundlich gesinnt sein. (Quelle1)
2. Von einer Mobgruppe direkt gegenüber von Drakki ist nur EIN Orc sichtbar, alle anderen Mobs dieser Mobgruppe sind unsichtbar, werden aber beim Pull des Orcs oder wenn man zu nah kommt sichtbar.
3. Drakkisath dropt seit geraumer Zeit ab und zu nur ein Item und die Droprate von Titans Flask stimmt nicht (ist zu hoch). (Dropraten siehe Quelle 2)

Wenn euch noch mehr Bugs einfallen, bitte meldet sie! :)

**Wie sollte es sich verhalten?**
1. Awbee sollte gegenüber allen Spielern freundlich gesinnt sein.
2. Mobs nicht unsichtbar
3. Drakki sollte wohl mindestens 4 Items droppen (siehe Quelle) und die Droprate der Flask sollte viel geringer sein. Des weiteren wäre es cool, wenn ihr die Dropraten überarbeiten würdet. Wie viele Items genau er droppen sol, hab ich nich rausgefunden. Ich denke dass es 4-5 Items waren, aber das ist natürlich keine verlässliche Aussage verglichen mit festgeschriebenen Quellen von damals. Deshalb würde ich mich an die 4 Items aus der Allakhazam Quelle halten.

**Schritte zur Reproduzierung**
1. Zu Awbee porten -> ist neutral und angreifbar.
2. Vor Drakki porten und die Mobgruppe anschauen
3. Drakki legen.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Quelle1: https://web.archive.org/web/20070811022146/http://www.thottbot.com/c10740
*"you know that room where you fight that dude flying around on that dragon, and you have to kill his dragon, then you kill him, Warcheif Rend i think is his name..well, i saw Awbee laying on the ground outside the gates on the side you enter on, he is a light blue lvl 57 elite dragon, who shows up as freindly"*

Quelle2: https://web.archive.org/web/20070114163337/http://wow.allakhazam.com/db/mob.html?wmob=10363
*"Just did it first time with my friends, got this loot:*
*Blackblade of Shahram*
*Draconic Infused Emblem*
*Lightforge Breastplate*
*Recipe: Flask of the Titans*

*They said it was an amazing selection of drops, I got the flask recipe <3"*

Links aus unserer Datenbank
Awbee http://datenbank.welli-it.de/?npc=10740
Drakkisath http://datenbank.welli-it.de/?npc=10363

**Comment by dagochen** [comment]
3. ist bereits gefixed und auf Nefarian. Die Wahrscheinlichkeiten der Items sind nicht ganz die, wie auf allakhazam, könnte ich aber gerne nochmal drüber schauen. Der beschriebene Loot mit den Items damals war unglaublich unwahrscheinlich:

Blackblade of Shahram 1%
Draconic Infused Emblem 8%
Lightforge Breastplate 6%
Recipe: Flask of the Titans 2,22%
--> 0,01 * 0,08 * 0,06 * 0,022 = 0,000001056 %

ist aber bei uns auch möglich:
Blackblade of Shahram 1,6%
Draconic Infused Emblem 9%
Lightforge Breastplate 10%
Recipe: Flask of the Titans 3%
--> 0,016 * 0,09 * 0,1 * 0,03 = 0,00000432 %

Und ja, der Gruppenloot ist nicht korrekt, schau ich mir morgen direkt mal an ;) Dann passe ich die % alle an :)

**Comment by ircfelix** [comment]
Flask hat bei uns 55% dropchance und vorgestern war ich in ubrs und awbee wurde gekillt.
Also bitte die allakhazam dropraten aus dem link von quelle 2 verwenden. Danke!

**Comment by ircfelix** [comment]
Vergleich die droprates von unserer db und von allakhazam. Die sind völlig anders.

**Comment by dagochen** [comment]
Patchnotes lesen!

**Comment by ircfelix** [comment]
Wurden die ubrs loottables auch gefixt? Ich dachte das war auf Bwl bezogen?!?
auch lese ich in den patchnotes nix von awbee.

**Comment by dagochen** [comment]
hab zu 3. den post oben gemacht....und github hat da 1. draus gemacht :D

**Comment by ircfelix** [comment]
Wie auch immer. Ich habe nicht das Gefühl dass bei Drakki was geFIXT ist, wenn er nur ein Item dropt.
Und die Quelle mit dem Blackblade udn Flaskrezept sollte nur als Nachweis gelten, dass er wohl drei blaue/zwei blaue ein epic und evtl. noch ein viertes Item dropt dropt.

**Comment by hraesvelgr** [comment]
Now you can reap your rewards, and good rewards they are. Drakkisath can drop any of the Class set BPs, and he always drops one, in addition he drops another blue item out of 4 items,[...]

http://www.wow-pro.com/dungeon_and_raid_guides/60_jame039s_upper_blackrock_spire_guide_ubrs


ein klassenitem + ein blaues (oder sharam, nehm ich an) + in seltenen fällen: rezept?

**Comment by ircfelix** [comment]
**Nachtrag Drakki Drops:**

https://www.youtube.com/watch?v=GZIl9UoVXic bei 2:19 -> 1 Setteil, 2 offset teile, 1 grünes.
