### ISSUE TITLE
Sunken Tempel ( 3 Bugs )

### ISSUE THREAD

**Issue by Hexquantum** [ClassicWoW/Nefarian_1.12.1_Bugtracker#733]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server Version:

1.0.6 ( Datum: 14.05.2015)

Wie sollte es sein ?

1. Nach dem aktivieren der Statuen sollte Atal'alarion spawnen 
2. "Traumsense"(Dreamscythe) und "Wirker" (Weaver) sollten entsprechenden Bossloot droppen.
3. Morphaz und Hazzas sollten entsprechenden Bossloot droppen.

Wie funktioniert es hier?

1. Es spawnt "Wirker" (Weaver) und dropped nichts.
2. "Traumsense" (Dreamscythe) und "Wirker" (Weaver) droppen sehr oft nichts (auch kein Gold/Silber)
3. Morphaz und Hazzas droppen nichts (auch kein Gold/Silber)

Links:
Atal'alarion:
http://www.wowwiki.com/Atal%27alarion
Traumsense:
http://datenbank.welli-it.de/?npc=5721
Wirker:
http://datenbank.welli-it.de/?npc=5720
Morphaz: 
http://datenbank.welli-it.de/?npc=5719
Hazzas: 
http://datenbank.welli-it.de/?npc=5722

Quellen:
s. Links
AtlasLoot PRE-TBC v1.21.02 u. entsprechende Atlas version

Anmerkungen:

Ich finde, das es ist eine beeindruckende Leistung ist alle Events komplett zu fixen ( Avatar of Hakkar  funktioniert komplett). Sogar die Statuen funktionieren (Altar und Statue im Wasser bei Atal'alarion grüßen zwar wenn man sie anklickt, das ist aber nicht so schlimm). Quests funktionieren komplett.
Die Bugs mit Atal'alarion und den 4 anderen sind sehr wahrscheinlich beim fixen der Bugs entstanden/erkennbar geworden. ( 1. Mob id verwechselt; 2. Traumsense und Wirker spawnen erst wenn Jammal tot ist [ Raum war vorher blockiert wegen verbuggten minibossevent] ; 3. Morphaz und Hazzas haben vorher bei ihrem Tod nicht Eranikus killbar gemacht).

Bis auf diese 3 oben genannten Bugs funktioniert die Instanz komplett :)

mfG Hexquantum

**Comment by Gnomorus** [comment]
zu 1. #678

**Comment by Haudraufinix** [comment]
+1 Bug:
Traumsense, Wirker und Eranikus sind gegen alle Arten von CC anfällig, betrifft ev. noch weitere Bosse

**Comment by Hexquantum** [comment]
yo das kommt dazu.
