### ISSUE TITLE
Krieger: Schildblock funktioniert nahezu nie

### ISSUE THREAD

**Issue by Vexz00** [ClassicWoW/Nefarian_1.12.1_Bugtracker#735]
Hi!

Da ich mir momentan einen Krieger hochspiele, ist mir aufgefallen, dass der Skill "Schildblock" nur bei den allerwenigsten Mobs funktioniert. Herausgefunden habe ich, dass er nur gegen einige wenige Defias in Westfall funktioniert, ansonsten gegen keinen anderen Mobtyp.
Der Schildblock wird einfach von den Gegnern ignoriert. Ja, natürlich verleiht er keine 100%ige Chance zu blocken, aber ich habe es an genügend Mobs lange genug getestet, um herauszufinden, dass manche Gegner sich einfach gar nicht daran interessieren.
Ich könnte ein Beweisvideo aufnehmen, wenn das nötig sein sollte.

Grüße!

Edit:
Habe soeben herausgefunden, dass wohl Rache einen Bug auslöst, der für kurze Zeit Schildblock unbrauchbar macht. Benutze ich die beiden Skills also in kürzester Zeit nacheinander, funktioniert Schildblock einfach nicht mehr und die Mobs ignorieren die erhöhte Blockchance einfach.

**Comment by Gnomorus** [comment]
Kriegst du denn den Schildblock Buff oder wird selbst dieser nicht angezeigt?

**Comment by Vexz00** [comment]
Der Buff vom Schildblock wird angezeigt und verschwindet auch, sobald ich dann Schaden erleide. Alles ist ganz normal, aber die Mobs ignorieren einfach nur die erhöhte Blockchance und treffen mich so, als wäre der Skill nie benutzt worden.

**Comment by Haudraufinix** [comment]
Hmm also unsere Raidtanks würden Reihenweise im Staub liegen, wenn der Skill nicht funktioniert. Hast du im Kampflog nachgesehen. Da müsste bei einem Block etwas stehen wie "X Trifft euch für 15 Schaden (30 Geblockt) o.ä. . Ein geblockter Angriff absorbiert nämlich nicht den kompletten Schaden eines Angriffs. Lediglich gegen Gegner die sehr schnell zuschlagen und dafür wenig Schaden pro Schlag veruraschen  (Defias z.B.) blockt man den kompletten Schaden weg.

Falls es sicht tatsächlich um einen Bug handelt: Spellid=12169
Link:http://datenbank.welli-it.de/?spell=12169

**Comment by Gnomorus** [comment]
Und im WoWeigenen Kampflog steht nichts davon, dass ein kleiner Teil des Schadens geblockt wird?

**Comment by Vexz00** [comment]
Kann es sein, dass ich den Skill einfach nur grundsätzlich missverstanden habe? Im Kampflog steht, dass ein Teil des Schadens geblockt wurde. Allerdings dachte ich immer (und ich könnte fast drauf schwören), dass der Charakter dann einfach den kompletten Schaden abwehrt. Also dieses typische Blocken mit dem Schild, bei dem dann auch immer "Blocken" da steht.

Habe hier mal ein Video gemacht:
https://vid.me/BhnR

**Comment by Gnomorus** [comment]
Es wird immer nur ein recht kleiner Teil des Angriffsschadens geblockt. Wie hoch der geblockte Teil ist, wird durch den "Blockwert" bestimmt. Dieser wiederrum hängt soweit ich weiß mit u.a. mit deiner Stärke zusammen. Für genauere Infos einfach mal nen Tank Guide im Forum lesen.

**Comment by Haudraufinix** [comment]
Jop simples Missverständniss passiert jedem Mal :)

Der geblockte Schaden ist abhängig vom benutzten Schild und zu einem sehr geringen Teil vom Rest der Ausrüstung. Wär zu schön, wenn unsere Tanks den kompletten Schaden abblocken würden. Die wären ein wenig gar einfach zu heilen :D

@ Dev: Kann geclosed werden

**Comment by Vexz00** [comment]
Okay, tut mir leid für die unnötige Aufregung. Hatte den Skill wohl einfach total falsch in Erinnerung. Vielen Dank euch für die Aufklärung!

**Comment by Hexquantum** [comment]
Rache löst keinen Bug aus. Hab selber vor ner Stunde Sunken Temple getanked. Man muss berücksichtigen, dass man nur 75% erhöhte Blockchance hat, sprich im low level bereich ist man nicht crush immun und somit kommen auch ungeblockte hits durch. Dazu kommt, dass mobs mit höherem Level ne Höherer Waffenkunde haben und somit der Effekt vom Schildblock verringert wird.

**Comment by dagochen** [comment]
@Vexz00 bitte einfach selber schließen.
