### ISSUE TITLE
[Hexenmeister][Teufelsjäger] Zaubersperre

### ISSUE THREAD

**Issue by antiwlbugs** [ClassicWoW/Nefarian_1.12.1_Bugtracker#736]
Hallo,

mir ist nun in letzter Zeit oft aufgefallen das gerade im PvP der Zauber "Zaubersperre" des Teufelsjägers widerstanden wird. Dieser Zauber sollte nicht verfehlen können, wie man hier in den Zauber Details nachlesen kann  http://www.wowhead.com/spell=19647/spell-lock#comments.

Zaubersperre Rang 1: http://datenbank.welli-it.de/?item=16388
Zaubersperre Rang 2: http://datenbank.welli-it.de/?item=16389

**Comment by Haudraufinix** [comment]
Zaubersperre kann wie jeder andere Kick/Silence Effekt zu Classic auch verfehlen. Das Flag "Cannot Miss" kam ab Cata hinzu (Korrigiert mich wenn ich beim Addon falsch liege).
In Classic ist dies so allerdings Korrekt.

**Comment by dagochen** [comment]
Habe auch nix anderes dazu gefunden, wenn du, @antiwlbugs , hier auch nix anderes mehr findest, bitte den Beitrag schließen, danke!
