### ISSUE TITLE
[Priester] T2 8/8 Bonus stackt nicht mit Erneuerung

### ISSUE THREAD

**Issue by dagochen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#737]
Istzustand:
Die beiden Buffs überschreiben sich.

Sollzustand:
Beide Buffs sollten zeitgleich auf einem Ziel sein.

Quelle:
https://web.archive.org/web/20070220111241/http://wow.allakhazam.com/db/spell.html?wspell=22010

**Comment by Wosser** [comment]
Wie heißt denn der Hot den der Setbonus auslöst? Liegt der Fehler einfach darin, dass sich die beiden Hots überschreiben, oder wird statt dem richtigen Spell tatsächlich ein Renew Rang 5 aufs Ziel gecastet? http://datenbank.welli-it.de/?spell=22009

**Comment by Shiruja** [comment]
Der Hot vom 8/8 heißt " Greater Heal" . Dieser Hot tickt wie ein Renew Rank 5 , heißt jedoch nicht so . Wenn man nun , egal welcher Rang, Renew castet , wird der 8/8 Hot ersetzt. Andersrum ist das auch der Fall.
Es sollten 2 seperate Buffs sein. 

http://datenbank.welli-it.de/?spell=22009
http://datenbank.welli-it.de/?spell=22010
