### ISSUE TITLE
Rezzbug im BG

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#739]
Welches Verhalten wird beobachtet?
Ungefähr jedes 3. mal kommt kein Rezz vom Geistheiler am Friedhof durch.

Wie sollte es sich verhalten?
Es sollte bei jedem mal gerezzt werden.

Schritte zur Reproduzierung
BG joinen, sterben (lassen), auf den Rezz warten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
sollte wohl klar sein, dass jedes mal gerezzt werden sollte

Links aus unserer Datenbank (hier gehts zur Datenbank)
-

**Comment by Haudraufinix** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/469
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/420

Danke für diesen Bug, den hatten wir alle übersehen =)

**Comment by hmmkay** [comment]
Naja, er ist ja noch da und nicht behoben ;)

**Comment by pvpmaster2000** [comment]
Es war eine Zeit lang gefixt, wird im Moment aber wieder von Tag zu Tag schlimmer.
Genauso wie vieles Andere: BGSpielerzahlen, Spieler "verschwinden" btw. laggen weg wenn sie gestunnt/gefeart/desoirientiert werden, diverse Fears brechen viel zu leicht wohingegen das Schreckensgeheul vom Warlock auch unter extrem viel Schaden nicht brechen kann, Autohit-Bug, OutofCombat bug, Swingtimer bug bei den Casterklassen, Slam etc. pp.

**Comment by Haudraufinix** [comment]
Du kannst devs anschreiben, dann können sie die betrefenden tickets wieder öffnen - und tun das auch. Eine "Sammelklage" ist bloss leider extrem unübersichtlich zum fixen.

Die Fears sind ein Spezialfall, weil Fears in classic nicht bei genau 1712 Schaden z.B. brechen, sondern du jedes mal wenn du Schaden erleidest eine immer grösser werdende Chance hast dem Fear zu entkommen. Aber verlässliche Werte hat bis jetzt leider noch keiner gefunden und darum bleibts vorerst auch so. Wie du bereits erwähnt hast, gibt wichtigere fixes die zuerst anstehen

Slam ist im übrigen nicht kaputt, bloss scheisse :D
