### ISSUE TITLE
Spieleranzahl im BG

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#740]
Welches Verhalten wird beobachtet?
Häufig gibt es eine Ungleiche Spieleranzahl im BG (auch von Anfang an) und es können mehr als das maximale Limit an erlaubten Spielern auf einem Schlachtfeld sein.

Wie sollte es sich verhalten?
Es sollten keine Spieler nachjoinen dürfen, wenn eine der Fraktionen in Unterzahl ist. Situationen, wo von Anfang an 11:4 antreten sollten daher nicht möglich sein.
Des weiteren sollten sich nicht mehr als den erlaubten 10 (WS) oder 15 (AB) Spielern pro Seite im BG befinden dürfen.

Schritte zur Reproduzierung
BG joinen und abwarten.

Zusätzliche Informationen (Screenshots, Videos, etc.)
0

Links aus unserer Datenbank (hier gehts zur Datenbank)
0

**Comment by Haudraufinix** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/310
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/222
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/219

"Dieses Problem ist uns bekannt"
Dafür, dass Arathibecken mit 11:4 Aufgeht musst du nicht den Devs auf die Nase hauen, sondern deinen Mitspielern, die ebenfalls für Arathibecken angemeldet waren, aber dann lieber WS gejoined haben oder AFK gegangen sind. Der Client versendet nämlich nur so viele Invites wie es Plätze gibt. Erst nach einer Berzögerung werden diese Leute aus der Warteschlange geworfen und andere eingeladen.

Rest siehe verlinkungen

**Comment by hmmkay** [comment]
Wer haut hier wem auf die Nase? Erklär das mal bitte...

B2T: Die Anzahl der Spieler in einem BG hängt nicht von den Anmeldungen sondern von den Personen IN einem BG ab

**Comment by Haudraufinix** [comment]
von *Anfang* an 11:4 antreten sollten daher nicht möglich sein.
Du sprichst von ANFANG. Am ANFANG werden 10-15 Arathi invites gestartet. Wenn von einer Fraktion lediglich 4 leute Annehmen können von der ANDEREN Fraktion dennoch 11 Leute joinen - so far so classic

**Comment by hmmkay** [comment]
Nein..... Die freigeschaltete Anzahl sollte sich an den vorhandenen Spielern im Bg und nicht an den Anmeldungen orientieren.

**Comment by Haudraufinix** [comment]
und Grubenratten sollten epics droppen. wir drehen uns irgendwie im Kreis....
1. Einmal wurde das ganze schon 3(!) mal Reportet. ein 4. Thread zum selben Thema ist recht bekloppt. Man kann im übrigen geschlossene Themen auch wieder aufmachen.
2. Hör ich bezüglich BG Zahlen nur gejammer aber nie was konstruktives. Wie wärs mit nem Lösungsvorschlag. Ausserdem vermischst du hier FAKT mit FIKTION
Es kann sehr wohl vorkommen dass es zu classic mal 5v8 etc BG's gab. Aber das scheint ja wegen den in 1.12.1 bereits implementierten cross Realm BG's bereits jeder vergessen zu haben!

**Comment by hmmkay** [comment]
Also ich glaube du verstehst das Problem nicht.... Hier redet keiner von Epics, es geht um BG's. Bleib bitte beim Topic. Was hat das mit dem Thread zu tun. Ein Lösungsvorschlag steht oben: "Die freigeschaltete Anzahl sollte sich an den vorhandenen Spielern im Bg..." orientieren. Außerdem kann immer mal jemand das BG verlassen und dann steht es eben 5 vs 8. Darum gehts hier aber auch nicht...
Des weiteren geht man schnell davon aus, dass alte Themen/ Bugs/ Reports wieder vergessen werden, daher werden dann gerne mal neue eröffnet.

**Comment by dagochen** [comment]
Korrekterweise sollten Invites nur rausgehen, wenn gleichviele Spieler beider Fraktionen im BG vorhanden sind. Das heißt, wenn ein AB aufgeht, sollte nach und nach jeweils einer von jeder Fraktion joinen. Es sollten keine 8 Invites gleichzeitig rausgehen, sodass eine 8vs1 Situation entsteht. Dies sollte nicht möglich sein.

**Comment by pvpmaster2000** [comment]
Es gibt momentan aber zwei Möglichkeiten wie eine ungleiche Anzahl an Spielerm im BG zustande kommen kann. (Zu beachten: 1 Spieler mehr bzw. 1 Spieler weniger auf einer Seite ist blizzlike.) 

Möglichkeit 1: 
In der Warsongschlucht sind 6A und 7H. 5 weitere Hordler sind angemeldet, bekommen aber keinen Invite da maximal nur 1 Spieler mehr von einer Fraktion im BG sein darf. 
Dann melden sich zwei Allys (A) an: Es werden 4 Invites versendet. 2 an die beiden frisch angemeldeten Allys und 2 an die beiden Hordler die am längsten in der Warteschlange sind. 
Wenn alle dem BG beitreten müsste es also 8A und 9H stehen; also "balanced" nach dem System, da nur ein Spieler unterschied.
Wenn einer der Allys sich zwar anmeldet und dem BG nicht beitritt steht es auf einmal 7A zu 9H und das BG ist nicht mehr balanced. 
Diese Mechanik wird auch oft von Spielern missbraucht. Sie melden mit einem 60er-Twink bei der anderen Fraktion an ohne die Absicht mit diesem Twink dem BG beizutreten. So können die Invites manipuliert werden. Dies geschiet mit der Absicht bestimmte BGs aufgehen zu lassen, für ein ungleichgewicht der Spielerzahl im BG zu sorgen oder einfach um sich bei der eigenen Fraktion einen Invite zu verschaffen.

Möglichkeit 2:
Im Arathibecken sind 10A und 9H. 5 weitere Allys sind in der Warteschlange. Dann verlässt ein Hordler das Schlachtfeld. Es steht 10A zu 8H. Anstatt dass das System wartet bis sich mindestens 2 Hordler anmelden bevor ein weiterer Ally ins BG invitet wird, versendet das System sofort einen Invite an die Allys. (So als würde das BG glauben ein Ally hätte das BG verlassen und nicht ein Hordler).
Dann steht es 11A zu 8H und ist nicht mehr balanced.
In letzter Zeit wird dieser Bug teilweise auch ausgelöst ohne das jemand das BG verlassen hat und es gab Wasongs mit 14A zu 9H im Warsong (maximum sollte 10vs10 sein) und Arathibecken mit 9A zu 17H usw. 

Also es sind neue Bugs dazu gekommen und daher ist das Ticket schon ok finde ich. :-)

**Comment by pvpmaster2000** [comment]
" Korrekterweise sollten Invites nur rausgehen, wenn gleichviele Spieler beider Fraktionen im BG vorhanden sind. Das heißt, wenn ein AB aufgeht, sollte nach und nach jeweils einer von jeder Fraktion joinen. Es sollten keine 8 Invites gleichzeitig rausgehen, sodass eine 8vs1 Situation entsteht. Dies sollte nicht möglich sein. "
Da das AB nur aufgeht wenn mindestens 8 Spieler auf beiden Seiten angemeldet sind, sollten selbstverständlich alle 16 Invites gleichzeitig rausgehen. Ja sogar 17 wenn von einer Fraktion mehr als 8 Spieler angemeldet sind. Alles andere würde überhaupt gar keinen Sinn ergeben.

Da aber absichtlich manipuliert wird müssen eben diese Flaws ausgemerzt werden. Es gab bereits verschiedene Vorschläge aus der Community. U.a.:
-Grundsätzliche Regeln seitens der Serverleitung bezüglich der gleichzeitigen PvP-Anmeldung auf beiden Fraktion durch die benutzung verschiedener Accounts. (Müsste untersagt werden)
-Zeit bevor das BG zugeht wenn auf einer Seite zuwenige Spieler vorhanden sind auf vier Minuten reduzieren um ein 3/0 WS oder 5/0 AB Freewin zu unterbinden und damit die Motiavation BGs zu "dodgen" zu senken.
-Ehre für ein BG erst beim Verlassen des BGs anrechnen und auch nur dann wenn wenigstens die Mindestanzahl an Spielern bei der gegnerischen Fraktion vorhanden ist wenn das BG schließt.
-15 Minuten Deseteurs-Debuff wenn man von einem BG ins andere geht. Man kann das BG zwar noch Spielen aber 15 Minuten nicht mehr anmelden. Dadurch wär das Dodgen reguliert und würde sich zum Ehre- und Ruffarmen weniger lohnen.

**Comment by hmmkay** [comment]
Es sind gute Ansätze, die du vorgebracht hast. Allerdings würde ich noch gerne ergänzen:
- "Grundsätzliche Regeln seitens der Serverleitung bezüglich der gleichzeitigen PvP-Anmeldung auf beiden Fraktion durch die benutzung verschiedener Accounts. (Müsste untersagt werden)". Das wird wohl schwer zu kontrollieren sein, weil es ein anderer Acc ist.
- Man könnte die Anzahl der rausgehenden Invites wirklich sehr stark an die Spieler in einem BG binden. Sprich: es joinen nach und nach immer mehr Leute und es werden nicht gleich 8 Invites versendet.
- Oder, was am einfachsten wäre um die "Dodges" zu verhindern: Sobald ein Spieler ein BG betritt, wird er automatisch aus allen Warteschleifen gekickt. Das führt dazu, dass das BG zuende gespielt werden muss.

**Comment by Seniorash** [comment]
Es müssen in jedem Fall mindestens so viele invites versendet werden dass das bg zumindest offen bleibt. Alles andere macht keinen Sinn

**Comment by dagochen** [comment]
Dazu kommt noch folgender Fehler bei uns: 

Battles must now last at least ten minutes after the start of the battle in order for the losing team to receive a Mark of Honor.
http://www.wowwiki.com/Patch_1.8.4

Aktuell bekommen beide Seiten keine Marken, auch das Team, was genug Spieler hat / am gewinnen ist.

**Comment by Sabbaer** [comment]
manchmal kommt es vor, dass ein spieler eine anmeldung besitzt aber nicht das bg joinen kann.
Danach kommt es zu den problemen mit den spielern, habe das nun ca 5 monate beobachtet und es tritt genau dann auf!
