### ISSUE TITLE
Ingenieur: Goblinüberbrückungskabel XL

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#744]
Welches Verhalten wird beobachtet?
Es kann sein, dass das Kabel nicht funktioniert, wenn der Spieler seinen Geist freigelassen hat. (Das müsste vllt noch von 'nem Dev. überprüft werden)

Wie sollte es sich verhalten?
Es sollte auch rezzen, wenn der Spieler seinen Geist freigelassen hat.

Schritte zur Reproduzierung
Sterben -> rezzen lassen

Link
http://wowwiki.wikia.com/Goblin_Jumper_Cables_XL

**Comment by hraesvelgr** [comment]
ergo: der spell des kabels sollte auch auf das objekt "player-character-leiche" anwendbar sein.
