### ISSUE TITLE
Wiederbeleben des Hunterpets

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#745]
Welches Verhalten wird beobachtet?
Das Hunterpet kann von anderen Spielern nicht wiederbelebt werden.

Wie sollte es sich verhalten?
Wenn ein Spieler das Hunterpet wiederbelebt (Priest, Pala, Goblinkabel XL) sollte das Pet wiederbelebt werden. Der Link s.u. bestätigt, dass das Hunterpet durch ein Rezzkabel belebt werden kann: "NPCs cannot be resurrected, but you can resurrect pets and other players". Daher sollte es auch möglich sein das Pet von einem anderen Spieler beleben zu lassen.
(Vllt kann da wer 'nen weiteren Link finden aber ich bin auch der Meinung, dass das in Classic so war.)

Schritte zur Reproduzierung
Hunterpet sterben lassen und danach versuchen es Wiederzubeleben.

Links
http://wowwiki.wikia.com/Goblin_Jumper_Cables_XL

**Comment by Haudraufinix** [comment]
Die Jumper Cables funktionieren im Moment generell nicht, hast du auch versucht dein Pet durch einen anderen Spieler rezzen zu lassen?

Ich hab leider keine zusätzliche quelle, aber ich hab zu classic selber öfters mal n Hunter pet gerezzt (nein ich hab nicht mit zwei classic huntern telefoniert ;)) und als zusatzinfo: Hexerpets konnte man nicht rezzen (wurde rausgepatched, weil manche Opferskillung benutzt haben und sich dann ihre Sukkubus haben rezzen lassen) und Gerezzte Pets wurden von anderen Spielern an ihrem Todesort gerezzt - man hat damit öfters mal n wipe verursachen können ;)

Priesterrezz: http://datenbank.welli-it.de/?spell=2006#see-also-ability
Palarezz: http://datenbank.welli-it.de/?spell=7328
Schamirezz: http://datenbank.welli-it.de/?spell=2008#see-also-ability

**Comment by hmmkay** [comment]
"Welches Verhalten wird beobachtet?
Das Hunterpet kann von anderen Spielern nicht wiederbelebt werden." -> Habe versucht es von anderen Spielern rezzen zu lassen. bzgl. des Kabels hab ich 'nen extra Thread eröffnet.

**Comment by hmmkay** [comment]
Nochmal 'nen extra Link:
Patch 1.4.0 (2005-05-05): When a non-Hunter resurrects a pet, the pet will no longer receive resurrection sickness.
http://wowwiki.wikia.com/Patch_1.4.0
