### ISSUE TITLE
Westfall-Huhn-Quest buggy

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#747]
Welches Verhalten wird beobachtet?
Die Quest (s.u.) ist zwar annehmbar, man kann sie aber nicht abgeben.

Wie sollte es sich verhalten?
Sie sollte abgebbar sein.

Schritte zur Reproduzierung
Quest annehmen und versuchen sie zu beenden.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?quest=3861

**Comment by Rushor** [comment]
hast du auch /cheer auf das huhn gemacht?

**Comment by hmmkay** [comment]
Ja! Habe darauf hin ein Ticket geschrieben und ein GM hat mir bestätigt, dass die Quest verbuggt ist.

**Comment by dagochen** [comment]
Das Problem ist, dass wenn man /chicken auf das Huhn macht, es zwar freundlich wird, aber die Quest nicht gestartet wird. Und wenn man die Quest nicht im Questlog hat, kann man sie logischerweise auch nicht abgeben.

**Comment by ircfelix** [comment]
Bitte fixt das mal, das schreckt neue Spieler ab!

**Comment by Jizzl3** [comment]
No fun like tiz!

**Comment by dagochen** [comment]
@Dotox hier kann auch zugemacht werden.
