### ISSUE TITLE
Richturteil

### ISSUE THREAD

**Issue by Jipptech** [ClassicWoW/Nefarian_1.12.1_Bugtracker#748]
Welches Verhalten wird beobachtet?
Beim wirken des Zaubers "Richturteil" passiert es in letzter Zeit sehr häufig, dass das Mana berechnet, die Abklinzeit gestartet aber der Zauber an sich nicht ausgeführt wird...im Kampflog gibt es an der Stelle an der der Zauber gewirkt wird auch keinen Eintrag. (Dem Zauber wird nicht Widerstanden, er verfehlt nicht oder sonstiges) Dies betrifft alle Varianten der Richturteile, ob Kreuzfahrer, Weißheit oder des Befehls...

Wie sollte es sich verhalten?
Bei der Anwendung des Zaubers "Richturteil" sollten die zusätzlichen Effekte der einzelnen Paladinsiegel ausgelöst werden. 

Schritte zur Reproduzierung
Siegel nutzen, Richturteil wirken und zusätzlich zu den Manakosten und dem setzen des Cooldowns sollten die Effekte auftreten, außer der Gegner widersteht oder man verfehlt.

**Comment by dagochen** [comment]
Vermutlich fehlt nur die Anzeige im Kampflog, dass es resisted wurde?

Judgements - Judgements that place a debuff on their victim will now all have their duration refreshed when the judging paladin strikes the victim with his or her melee swings. All these debuffs have had their duration decreased to 10 seconds. In addition, Judgements that place debuffs can no longer be resisted.
http://wowwiki.wikia.com/Patch_1.9.0

**Comment by Sabbaer** [comment]
es fehlt die anzeige, bzw es wird resisted

**Comment by Sabbaer** [comment]
gerade nochmal getestet, es steht wirklich sehr häufig einfach garnichts im kampflog.

**Comment by Sabbaer** [comment]
seitdem das gefixed wurde mit dem nicht mehr resisten, habe ich trotzdem manchmal kein siegel des kreuzfahrers drauf, obwhol ichs gerichtet habe, auch mit siegel des befehls ist das selbe zu beobachten. noch einmal in duellen und bei npcs getestet. Es steht einfach nichts im kampflog und passieren tut auch nichts, wie von jipptech beschrieben!

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875

**Comment by Sabbaer** [comment]
nicht gefixed leider, siehe reference
kann es sein, dass die berechnung, als das früher noch auf zauberhit und zaubercrit ging, weiterhin auch noch die resist berechnung drin hat für den "zauber" v.a. für siegel des befehls, bzw auch für die anderen siegel

**Comment by Dotox** [comment]
Das Problem konnte soweit reproduziertbar behoben werden. Das da war LOS das Problem. Wenn es nicht korrekt funktioniert gibt es eventuell noch einen anderen Auslöser.

**Comment by Sabbaer** [comment]
ok ich teste mal nochmal auf dem testserver

**Comment by Sabbaer** [comment]
also aufm testserver scheint es zu funktionieren hatte jetzt bei ka 40 richturteilen kein so ein auftreten mehr
sehr gute arbeit, danke an alle die mitgewirkt haben, hoffe es kann bald aufgespielt werden

**Comment by Sabbaer** [comment]
im naxx test raid jede menge wieder aufgetreten

**Comment by Sabbaer** [comment]
push

**Comment by Sabbaer** [comment]
funktioniert leider nicht auf nefarian! bitte um reopen https://www.twitch.tv/sabbaer666 video sektion, video vom 27.04.2017. tritt leider weiterhin alle schieß lang auf ;(

**Comment by Sabbaer** [comment]
ka aufm testserver hats damals funktioniert, ist dort was anders als auf nef? keine ahnung ob es was damit zu tun hat aber https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1878 wurde zur selben zeit angelegt wie der fix damals, hatt das damit was zu tun, just a question

**Comment by Sabbaer** [comment]
any suggestions? es ist wirklich extrem frustrierend, und ich kann da im sinne aller paladine und nicht nur der retris sprechen (natürlich sind die am meisten betroffen) aber das problem ist wirklich sehr sehr schlimm. ein retri macht so schon nicht unbedingt den tollsten schaden und dann noch "bugged" zu sein, seit über 2 jahren und nicht meinen eigentlichen dmg machen zu können finde ich leider sehr schade. es ist ja auch nicht nur ich, der retri paladin spielt, es spielen mittlerweile viele retris mit gutem bis sehr sehr gutem equip auf dem server und die raids nehmen gerne mal einen retri mit. 
das ganze thema macht mich sehr traurig und ihr habt schon viel zeit da reingesteckt, kann ich mir vorstellen, aber so ist das kein dauerzustand, der retri paladin macht pro bosskampf 50-100 dps zu wenig, je nach länge des kampfes und häufigkeit der nicht berechneten richturteile. auf einen kompletten aq40 run gerechnet sind das unmengen an schaden die über die zeit verloren gehen.

es wäre sehr lieb wenn man da ma noch was machen könnte, auch im pvp ist das einfach lächerlich wenn dein richturteil einfach jedes 3-4 mal nicht berechnet wird

**Comment by Sabbaer** [comment]
antwort? iwelche offiziellen statements iwas? ansonsten habt ihr eine komplette klassenskillung dem untergang geweiht wenn sich daran nichts ändert...

**Comment by Dotox** [comment]
Ich hab nochmal was geändert, ist auf dem Naxxramas-Testserver.

**Comment by Sabbaer** [comment]
ok supi werd ich dann mal testen

**Comment by Sabbaer** [comment]
getestet und funktioniert auf dem naxx server einwandfrei,  ca 100 richturteile alle berechnet

**Comment by Dotox** [comment]
Ist auf Nef

**Comment by Sabbaer** [comment]
scheint zu funktionieren, falls nicht meld ich mich nochmal? vielen lieben dank schonmal

**Comment by Sabbaer** [comment]
aehm das geht noch nicht, der fehler besteht weiterhin!

**Comment by Sabbaer** [comment]
push

**Comment by Sabbaer** [comment]
immernoch push

**Comment by Dotox** [comment]
Ursache leider unbekannt.
