### ISSUE TITLE
rogue spell damage scale

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#750]
Welches Verhalten wird beobachtet?
schurken gifte skallieren zu 100% mit spdmg, manche sogar mit 125%
Wie sollte es sich verhalten?
schurkengifte sollten garnicht oder extremst gering mit spelldmg skallieren
Schritte zur Reproduzierung
http://wow.allakhazam.com/forum.html?forum=243&mid=11217892439741807
http://forums.elitistjerks.com/topic/6839-patch-112rogue-review-speculations/page-4
http://www.killerguides.net/games/world-of-warcraft/rogue
http://wowwiki.wikia.com/Rogue_builds/Level_60
http://www.warcraftmovies.com/movieview.php?id=27354 (1of the best rogues ww at that time, scheint keinen wert auf spdmg zu legen in all seinen videos)
http://shadowpanther.net/aep.htm (keine erwähnung in all seinen tabellen, guides etc von spdmg)
http://www.gamefaqs.com/pc/534914-world-of-warcraft/answers/136865-what-is-the-best-rotation-for-combat-rogue keine erwähnung von spdmg o.ä.
http://www.wow-one.com/forum/topic/66284-rogue-pve-guide-by-oto-friends/ keine erwähnung von spdmg scale!
http://www.wow-one.com/forum/topic/8500-rogue-pve-guide-by-sheina/ keine erwähnung von spdmg
http://us.battle.net/wow/en/forum/topic/3988230709 keine erwähnung von spdmg
http://vanillagaming.org/forum/index.php?topic=7364.0 keine erwähnung von spdmg
http://projectextreme.guildlaunch.com/forums/viewtopic.php?t=8361442&start=0&postdays=0&postorder=asc&highlight=&gid=255597&sid=58ce23273976f458f7c5d4305746e295 keiner erwähnung von spdmg 
https://apakhe.wordpress.com/2011/11/10/1-12-1-guide-for-rogues-by-wallzy/ keine erwähnung von spdmg
..... usw

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=5MRdRvkCU6U
https://www.youtube.com/watch?v=Po0SYNfxVL0^
https://www.youtube.com/watch?v=cA8ueCWc4VQ
https://www.youtube.com/watch?v=rzQnLNt0uRE (sowie eviscerate 1 und die parts dazu, auch noch ein extremst starker rogue, keine spdmg oder ähnliches benutzt in all seinen videos)
etc kann gerne noch naxx etc posten von rogues world first kills oder auch nicht, die keine spelldmg benutzen
Links aus unserer Datenbank
http://datenbank.welli-it.de/?search=deadly+poison
http://datenbank.welli-it.de/?search=instant+poison
http://datenbank.welli-it.de/?search=wound+poison

**Comment by dagochen** [comment]
Doppel-Post von #630
