### ISSUE TITLE
Login Problems

### ISSUE THREAD

**Issue by Rojaxx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#751]
Hi ;-)
Need pls a little Help.... It seems my Login didn´t Work for now.... Whats the Problem?! 
And i Think i´m not the only one... I will check it now again....but i think there were no chance...

Pls GM´s im very pleased to be right back on your smart server
I like this Classic WoW Fealing with all of these Bug´s 

mfg
Rojaxx

**Comment by Sabbaer** [comment]
i think its a small problem with the event that recently started, just check out on mmobase.de and use google translater for latest news. it will be fixed soon i think but i have no insider info on that so just a guess

**Comment by dagochen** [comment]
Server up and running again. Was down due to technical problems for 30 minutes.
/close
