### ISSUE TITLE
Unsichtbarkeitstrank cooldown fehlerhaft

### ISSUE THREAD

**Issue by pvpmaster2000** [ClassicWoW/Nefarian_1.12.1_Bugtracker#754]
Welches Verhalten wird beobachtet?
Unsichtbarkeitstrank und geringer Unsichtbarkeistrank lösen einen 10 Minuten Cooldown auf alle anderen Tränke wie Heiltrank, Manatrank usw. aus.

Wie sollte es sich verhalten?
Der Cooldown sollte 2 Minuten sein

Schritte zur Reproduzierung
Heiltrank nemhen -> 2 Minuten CD auf alle Tränke
Unsichtbarkeitstrank -> 10 Minuten CD auf alle Tränke

Zusätzliche Informationen (Screenshots, Videos, etc.)
"Potions 2 minutes: This includes items such as Health Potion, Mana Potion, Invisibility Potion and Mighty Rage Potion." (http://www.wowwiki.com/Patch_1.11.0)

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?item=3823 http://datenbank.welli-it.de/?item=9172

**Comment by ircfelix** [comment]
Da kann man sich jetz wieder streiten:
Manche Sachen werden auf <1.9 stand gefixt, manche auf 1.9, manche auf > 1.9. Mir is das ja egal, aber eine klare Linie wäre ahch hier nice.
