### ISSUE TITLE
Hunter Pet Defensiv/Passiv

### ISSUE THREAD

**Issue by Ghulfang** [ClassicWoW/Nefarian_1.12.1_Bugtracker#756]
Seit dem letzten Patch vom 28.05.2015 verhält sich das Pet nach dem Abmounten Defensiv, nicht Passiv wie es richtig wäre. 

https://www.youtube.com/watch?v=aGli2EPbK-A  gut zu erkennen bei 0:37 min

**Comment by SirBeansen** [comment]
Danke für den fix....doch zurzeit ist es noch so das auch während des Zonen wechseln (ladebildschirm) sich das pet wieder auf defensiv stellt. Wäre schön wenn das auch noch behoben werden könnte.

**Comment by rschinkoeth** [comment]
der bug ist sowas von noch nicht gefixed! sowohl dismount als auch zonenwechsel lösen immernoch aus das pet defensiv wird. und es treibt mich in den wahnsinn!

**Comment by wahaxlekuke** [comment]
Aufmounten -> Abmounten : Pet ist immer noch passiv
Ruhestein von Scholo -> Silithus : Pet bleibt ebenfalls passiv

Wenn du möchtest, dass sich irgendwas ändert, musst schon nen brauchbaren Fehlerbericht liefert. (Genau beschreiben was/wo passiert ist oder noch besser ein Video davon machen)
Einfach nur "geht nicht" drunter schreiben hilft wenig.

**Comment by rschinkoeth** [comment]
habe eben wegen eines andren problems neu installiert, vmtl muss man den wdb ordner löschen. zumindest konnte ich den fehler nach der reinstallation (feenix en client) nicht mehr reproduzieren. 
problem lag also auf meiner seite, sorry.
