### ISSUE TITLE
Ein Schuss ein Treffer

### ISSUE THREAD

**Issue by Syriass** [ClassicWoW/Nefarian_1.12.1_Bugtracker#757]
Oben genannter Quest in Ashenvale bei Schildwache Aynasha kann angenommen werden aber startet nicht also die Schildwache bewegt sich kein mm!

MFG

**Comment by hraesvelgr** [comment]
bitte an die vorlage halten: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker siehe readme.
