### ISSUE TITLE
Flucht durch Gewalt/Verstohlenheit

### ISSUE THREAD

**Issue by Syriass** [ClassicWoW/Nefarian_1.12.1_Bugtracker#758]
Oben genannter Quest in Ashenvale ist buggy. Der Nachtelf wird bei verstohlenheit entdeckt>Fehlgeschlagen und bei Gewalt läuft er immer zurück und Quest schlägt fehl wenn er unten ankommt!

MFG

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/757#issuecomment-107190178
