### ISSUE TITLE
Hunter Talent: "Sicherer Stand", funktioniert nicht richtig

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#759]
Welches Verhalten wird beobachtet?
Das Talent "Sicherer Stand" sollte eine Chance von 15% geben Verlangsamungs- und Fixierungsfähigkeiten zu widerstehen. Dies ist allerdings (vermutlich) nicht der Fall.
Getestet wurde dies mit insgesamt mehreren 100 Verlangsamungs- und Fixierungsfähigkeiten wie: Kniesehne, Frostblitz, Frostnova und Wurzeln. (Für weitere Tests mit einem GM oder ähnlichen stehe ich gerne bereit.)

Wie sollte es sich verhalten?
Verlangsamungs- und Fixierungsfähigkeiten (Kniesehne, Schurkengift, Frostnova, Chill-Effekten, Wurzeln, Gegenangriff etc.) sollte zu 15% widerstanden werden können.

Schritte zur Reproduzierung
Duell starten -> slowen lassen: Der Slow geht jedes mal durch.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?spell=24283
-> "increases the chance movement impairing effects will be resisted by an additional 15%"

http://datenbank.welli-it.de/?spell=6615
-> Makes you immune to Stun and Movement Impairing effects for the next 30 sec

http://datenbank.welli-it.de/?spell=13875
-> Gives a 100% chance to remove all movement impairing effects when you activate your Sprint ability

=> Sicherer Stand hat demzufolge die selben Auswirkungen, wie Free Action Potion oder Improved Sprint

http://datenbank.welli-it.de/?spell=30918
-> Removes snares and roots

=> Sicherer Stand sollte demzufolge dazu führen, dass Snares and Roots widerstanden werden kann

Was sind Snares and Roots? 
http://wowwiki.wikia.com/Snare
-> reduce a victim's movement speed (verlangsamt)
http://wowwiki.wikia.com/Root
-> cause the victim to be locked in place (fixiert)

=> Demzufolge sollte Sicherer Stand die Chance erhöhen allen Verlangsamungs- und Fixierungsfähigkeiten  zu widerstehen.

**Comment by pvpmaster2000** [comment]
Ich habe das auch schonmal getestet und es wurde regelmäßig ( ca. jedem fünften) Slow widerstanden.
Auch dem gnomischen Net-o-matic kann durch das Talent widerstanden werden.

**Comment by hmmkay** [comment]
Bei mir absolut nicht.... sry

**Comment by SirBeansen** [comment]
Also wenn das Talent nicht funktionieren würde wäre es neu....da es vorher immer funktioniert hat.

**Comment by Haudraufinix** [comment]
Rein vom Gefühl her meinte ich auch, es funktioniert, aber ich werds die Tage mal testen, kann schon sein dass es rumbugt

**Comment by wahaxlekuke** [comment]
Das Talent funktioniert korrekt.
