### ISSUE TITLE
Beim Briefkasten öffnen , Crash auf Desktop

### ISSUE THREAD

**Issue by Motrosack** [ClassicWoW/Nefarian_1.12.1_Bugtracker#760]
Hallo beim öffnen des Ingame Briefkasten crasht mir immer das Game , erst seit ich mir von einem anderen Char 5g geschickt habe.

Brief Empfänger : Motrius
Brief Sender : Metak

World of WarCraft (build 5875)

Exe:      C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
Time:     Jun  1, 2015  7:39:16.621 AM
User:     Motro
Computer: MOTRIUS
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:00214E4C

The instruction at "0x00214E4C" referenced memory at "0x00214E4C".
The memory could not be "read".

WoWBuild: 5875
------------------------------------------------------------------------------

----------------------------------------
    x86 Registers
----------------------------------------

EAX=00214E4C  EBX=0018FDE8  ECX=00000000  EDX=00003600  ESI=0AD9E008
EDI=00003600  EBP=0018FDD4  ESP=0018FDBC  EIP=00214E4C  FLG=00210202
CS =0023      DS =002B      ES =002B      SS =002B      FS =0053      GS =002B

----------------------------------------
    Stack Trace (Manual)
----------------------------------------

Address  Frame    Logical addr  Module

00214E4C 0018FDD4 0000:00000000 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
00537CA5 0018FE00 0001:00136CA5 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
00538541 0018FE28 0001:00137541 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
005B3DE3 0018FE68 0001:001B2DE3 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
00421022 0018FED8 0001:00020022 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
00420BF1 0018FEF0 0001:0001FBF1 C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
0040411E 0018FF80 0001:0000311E C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
74E07C04 0018FF94 0001:00007C04 C:\WINDOWS\SYSTEM32\KERNEL32.DLL
771DAD1F 0018FFDC 0001:00059D1F C:\WINDOWS\SYSTEM32\ntdll.dll
771DACEA 0018FFEC 0001:00059CEA C:\WINDOWS\SYSTEM32\ntdll.dll

----------------------------------------
    Stack Trace (Using DBGHELP.DLL)
----------------------------------------

00214E4C <unknown module> <unknown symbol>+0 (0x000139B8,0x0018FDE8,0x0AD94208,0x0AD9E008)
00537AE7 WoW.exe      <unknown symbol>+0 (0x00000000,0x00000000,0x00000000,0x00000000)

----------------------------------------
    Loaded Modules
----------------------------------------

0x00330000 - 0x003C6000  C:\Games\Classic-Wow\World of Warcraft 1.12.1\fmod.dll
0x00400000 - 0x00D06000  C:\Games\Classic-Wow\World of Warcraft 1.12.1\WoW.exe
0x04E40000 - 0x05058000  C:\WINDOWS\system32\nvspcap.dll
0x10000000 - 0x10069000  C:\Games\Classic-Wow\World of Warcraft 1.12.1\DivxDecoder.dll
0x11F70000 - 0x12088000  C:\Games\Classic-Wow\World of Warcraft 1.12.1\dbghelp.dll
0x70AB0000 - 0x70B19000  C:\WINDOWS\system32\dxgi.dll
0x70B20000 - 0x70DFA000  C:\WINDOWS\system32\nvapi.dll
0x71940000 - 0x71B46000  C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17784_none_a9f497a901334c74\Comctl32.dll
0x71B50000 - 0x71C9A000  C:\WINDOWS\SYSTEM32\urlmon.dll
0x71CA0000 - 0x71DDA000  C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI.dll
0x71DE0000 - 0x72DEF000  C:\WINDOWS\SYSTEM32\nvd3dum.dll
0x72F60000 - 0x73192000  C:\WINDOWS\SYSTEM32\iertutil.dll
0x731E0000 - 0x733B3000  C:\WINDOWS\SYSTEM32\d3d9.dll
0x733C0000 - 0x7340B000  C:\WINDOWS\SYSTEM32\mswsock.dll
0x73450000 - 0x7346A000  C:\WINDOWS\SYSTEM32\dwmapi.dll
0x734C0000 - 0x7355F000  C:\WINDOWS\SYSTEM32\winhttp.dll
0x73580000 - 0x7358A000  C:\WINDOWS\SYSTEM32\ondemandconnroutehelper.dll
0x73590000 - 0x735C6000  C:\WINDOWS\SYSTEM32\wdmaud.drv
0x735D0000 - 0x737A3000  C:\WINDOWS\SYSTEM32\WININET.dll
0x737B0000 - 0x737BF000  C:\WINDOWS\SYSTEM32\profapi.dll
0x737C0000 - 0x737CA000  C:\WINDOWS\SYSTEM32\Secur32.dll
0x737D0000 - 0x737D8000  C:\WINDOWS\SYSTEM32\midimap.dll
0x737E0000 - 0x73840000  C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
0x73840000 - 0x73848000  C:\WINDOWS\SYSTEM32\WINNSI.DLL
0x73850000 - 0x73859000  C:\WINDOWS\SYSTEM32\msacm32.drv
0x73860000 - 0x738B3000  C:\WINDOWS\System32\MMDevApi.dll
0x738C0000 - 0x73941000  C:\WINDOWS\SYSTEM32\dsound.dll
0x73950000 - 0x73A2E000  C:\WINDOWS\SYSTEM32\OPENGL32.dll
0x73A30000 - 0x73B1D000  C:\WINDOWS\system32\uxtheme.dll
0x73B20000 - 0x73B2A000  C:\WINDOWS\SYSTEM32\AVRT.dll
0x73B30000 - 0x73B37000  C:\WINDOWS\SYSTEM32\ksuser.dll
0x73B40000 - 0x73B80000  C:\WINDOWS\system32\powrprof.dll
0x73B80000 - 0x73B97000  C:\WINDOWS\SYSTEM32\MSACM32.dll
0x73BA0000 - 0x73BC5000  C:\WINDOWS\SYSTEM32\GLU32.dll
0x73BD0000 - 0x73BD8000  C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x73BE0000 - 0x73BE7000  C:\WINDOWS\SYSTEM32\DCIMAN32.dll
0x73BF0000 - 0x73C13000  C:\WINDOWS\SYSTEM32\WINMMBASE.dll
0x73C20000 - 0x73F96000  C:\WINDOWS\SYSTEM32\msi.dll
0x73FA0000 - 0x73FB6000  C:\WINDOWS\SYSTEM32\MPR.dll
0x73FC0000 - 0x73FDB000  C:\WINDOWS\SYSTEM32\USERENV.dll
0x73FE0000 - 0x740CC000  C:\WINDOWS\SYSTEM32\DDRAW.dll
0x740D0000 - 0x740F3000  C:\WINDOWS\SYSTEM32\WINMM.dll
0x74100000 - 0x74189000  C:\WINDOWS\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.9600.17415_none_7c5769eaaa0aa358\COMCTL32.dll
0x74190000 - 0x741B0000  C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x741B0000 - 0x7422F000  C:\WINDOWS\SYSTEM32\mscms.dll
0x74230000 - 0x742A4000  C:\WINDOWS\AppPatch\AcSpecfc.DLL
0x742B0000 - 0x74350000  C:\WINDOWS\system32\apphelp.dll
0x74350000 - 0x743DB000  C:\WINDOWS\SYSTEM32\SHCORE.DLL
0x74550000 - 0x74558000  C:\Windows\System32\rasadhlp.dll
0x74560000 - 0x745A6000  C:\WINDOWS\System32\fwpuclnt.dll
0x745B0000 - 0x745BA000  C:\WINDOWS\System32\winrnr.dll
0x745C0000 - 0x7463E000  C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x74640000 - 0x74654000  C:\WINDOWS\system32\NLAapi.dll
0x74660000 - 0x74676000  C:\WINDOWS\system32\pnrpnsp.dll
0x74680000 - 0x74691000  C:\WINDOWS\system32\napinsp.dll
0x746A0000 - 0x746A9000  C:\WINDOWS\SYSTEM32\kernel.appcore.dll
0x74830000 - 0x74858000  C:\WINDOWS\SYSTEM32\ntmarta.dll
0x74860000 - 0x74881000  C:\WINDOWS\SYSTEM32\DEVOBJ.dll
0x74900000 - 0x74908000  C:\WINDOWS\SYSTEM32\VERSION.dll
0x74910000 - 0x74964000  C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
0x74970000 - 0x7497A000  C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x74980000 - 0x7499E000  C:\WINDOWS\SYSTEM32\SspiCli.dll
0x749A0000 - 0x749E1000  C:\WINDOWS\SYSTEM32\sechost.dll
0x74A00000 - 0x74BB1000  C:\WINDOWS\SYSTEM32\SETUPAPI.dll
0x74BC0000 - 0x74C05000  C:\WINDOWS\SYSTEM32\SHLWAPI.dll
0x74C70000 - 0x74D47000  C:\WINDOWS\SYSTEM32\KERNELBASE.dll
0x74D50000 - 0x74D8C000  C:\WINDOWS\SYSTEM32\cfgmgr32.dll
0x74DF0000 - 0x74F30000  C:\WINDOWS\SYSTEM32\KERNEL32.DLL
0x74F30000 - 0x74FBD000  C:\WINDOWS\SYSTEM32\clbcatq.dll
0x74FC0000 - 0x75148000  C:\WINDOWS\SYSTEM32\CRYPT32.dll
0x75150000 - 0x751EB000  C:\WINDOWS\SYSTEM32\COMDLG32.dll
0x751F0000 - 0x7649C000  C:\WINDOWS\SYSTEM32\SHELL32.dll
0x764A0000 - 0x76563000  C:\WINDOWS\SYSTEM32\msvcrt.dll
0x76570000 - 0x76682000  C:\WINDOWS\SYSTEM32\MSCTF.dll
0x76690000 - 0x766E0000  C:\WINDOWS\SYSTEM32\WS2_32.dll
0x76770000 - 0x7677E000  C:\WINDOWS\SYSTEM32\MSASN1.dll
0x76780000 - 0x768FD000  C:\WINDOWS\SYSTEM32\combase.dll
0x76900000 - 0x76927000  C:\WINDOWS\SYSTEM32\IMM32.dll
0x76930000 - 0x76936000  C:\WINDOWS\SYSTEM32\PSAPI.DLL
0x76940000 - 0x7697D000  C:\WINDOWS\SYSTEM32\WINTRUST.dll
0x76980000 - 0x76AA8000  C:\WINDOWS\SYSTEM32\ole32.dll
0x76C50000 - 0x76C57000  C:\WINDOWS\SYSTEM32\NSI.dll
0x76C60000 - 0x76D1A000  C:\WINDOWS\SYSTEM32\RPCRT4.dll
0x76D20000 - 0x76E73000  C:\WINDOWS\SYSTEM32\USER32.dll
0x76E80000 - 0x76F15000  C:\WINDOWS\SYSTEM32\OLEAUT32.dll
0x76F20000 - 0x7702E000  C:\WINDOWS\SYSTEM32\GDI32.dll
0x77030000 - 0x770AC000  C:\WINDOWS\SYSTEM32\ADVAPI32.dll
0x77180000 - 0x772EE000  C:\WINDOWS\SYSTEM32\ntdll.dll

----------------------------------------
    Memory Dump
----------------------------------------

Code: 16 bytes starting at (EIP = 00214E4C)

00214E4C: <can't read from this address>

Stack: 1024 bytes starting at (ESP = 0018FDBC)

* = addr                                         **                       *   
0018FDB0: E8 FD 18 00  08 42 D9 0A  08 E0 D9 0A  E7 7A 53 00  .....B.......zS.
0018FDC0: B8 39 01 00  E8 FD 18 00  08 42 D9 0A  08 E0 D9 0A  .9.......B......
0018FDD0: 08 88 E3 16  00 FE 18 00  A5 7C 53 00  B8 39 01 00  .........|S..9..
0018FDE0: E8 FD 00 36  D5 A2 C2 00  E4 F9 7F 00  08 C0 E4 20  ...6........... 
0018FDF0: 00 00 00 00  FF FF FF FF  8A 2B 00 00  02 00 00 00  .........+......
0018FE00: 28 FE 18 00  41 85 53 00  B8 39 01 00  08 C0 E4 20  (...A.S..9..... 
0018FE10: 8A 2B 00 00  D5 A2 C2 00  48 FE 18 00  28 C3 08 0B  .+......H...(...
0018FE20: 0C 42 D9 0A  68 FE 18 00  68 FE 18 00  E3 3D 5B 00  .B..h...h....=[.
0018FE30: 28 C3 08 0B  29 36 40 00  B0 46 42 00  18 DC B9 02  (...)6@..FB.....
0018FE40: 08 DC B9 02  00 00 00 00  28 C3 08 0B  A8 38 C1 02  ........(....8..
0018FE50: 6C FE 18 00  70 FE 18 00  18 DC B9 02  01 00 00 00  l...p...........
0018FE60: 06 00 00 00  AC DC B9 02  D8 FE 18 00  22 10 42 00  ............".B.
0018FE70: 00 00 00 00  02 01 00 00  08 DC B9 02  00 00 00 00  ................
0018FE80: 5A 0D 42 00  00 10 40 00  00 00 00 00  00 E0 FD 7F  Z.B...@.........
0018FE90: 45 6E 67 69  6E 65 20 31  30 64 30 00  00 00 00 00  Engine 10d0.....
0018FEA0: 00 00 00 00  A5 41 E0 74  64 65 00 00  E2 96 1C 77  .....A.tde.....w
0018FEB0: 18 3D C5 00  00 00 00 00  44 45 00 00  00 00 00 00  .=......DE......
0018FEC0: 00 E0 FD 7F  5C C5 1B 77  60 12 C8 74  94 21 00 00  ....\..w`..t.!..
0018FED0: C8 39 01 00  00 00 00 00  F0 FE 18 00  F1 0B 42 00  .9............B.
0018FEE0: 00 00 00 00  E9 21 40 00  01 00 00 00  01 00 00 00  .....!@.........
0018FEF0: 80 FF 18 00  1E 41 40 00  A0 99 40 00  00 00 40 00  .....A@...@...@.
0018FF00: 00 00 00 00  50 1D EE 00  01 00 00 00  00 10 40 00  ....P.........@.
0018FF10: 00 10 40 00  00 E0 FD 7F  05 00 00 C0  50 1D EE 00  ..@.........P...
0018FF20: 01 E0 FF FF  44 00 00 00  78 2D EE 00  20 EC EE 00  ....D...x-.. ...
0018FF30: 08 E3 EE 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018FF40: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
0018FF50: 01 0C 00 00  01 00 00 00  00 00 00 00  00 00 00 00  ................
0018FF60: 01 00 01 00  00 00 00 00  0C FF 18 00  FC F7 18 00  ................
0018FF70: CC FF 18 00  40 B1 40 00  60 FE 7F 00  00 00 00 00  ....@.@.`.......
0018FF80: 94 FF 18 00  04 7C E0 74  00 E0 FD 7F  E0 7B E0 74  .....|.t.....{.t
0018FF90: A5 77 27 77  DC FF 18 00  1F AD 1D 77  00 E0 FD 7F  .w'w.......w....
0018FFA0: 0D 40 E0 74  00 00 00 00  00 00 00 00  00 E0 FD 7F  .@.t............
0018FFB0: 02 F8 FF FF  00 00 00 00  00 00 00 00  20 26 0E CD  ............ &..
0018FFC0: 0D 40 E0 74  A0 FF 18 00  01 E0 FF FF  E4 FF 18 00  .@.t............
0018FFD0: A0 74 21 77  E1 12 E5 03  00 00 00 00  EC FF 18 00  .t!w............
0018FFE0: EA AC 1D 77  FF FF FF FF  4A 02 1C 77  00 00 00 00  ...w....J..w....
0018FFF0: 00 00 00 00  00 10 40 00  00 E0 FD 7F  00 00 00 00  ......@.........
00190000: 41 63 74 78  20 00 00 00  01 00 00 00  0C 33 00 00  Actx ........3..
00190010: DC 00 00 00  00 00 00 00  20 00 00 00  00 00 00 00  ........ .......
00190020: 14 00 00 00  01 00 00 00  07 00 00 00  34 00 00 00  ............4...
00190030: 7C 01 00 00  01 00 00 00  00 00 00 00  00 00 00 00  |...............
00190040: 00 00 00 00  00 00 00 00  00 00 00 00  02 00 00 00  ................
00190050: 4E EF 26 1A  98 02 00 00  44 00 00 00  E0 02 00 00  N.&.....D.......
00190060: 60 02 00 00  00 00 00 00  BA 71 32 F3  40 05 00 00  `........q2.@...
00190070: 4A 00 00 00  8C 05 00 00  1E 03 00 00  00 00 00 00  J...............
00190080: 5B 49 59 2D  AC 08 00 00  32 00 00 00  E0 08 00 00  [IY-....2.......
00190090: 00 03 00 00  00 00 00 00  CD EA CE 32  E0 0B 00 00  ...........2....
001900A0: 42 00 00 00  24 0C 00 00  36 03 00 00  00 00 00 00  B...$...6.......
001900B0: C8 5F 50 38  5C 0F 00 00  5E 00 00 00  BC 0F 00 00  ._P8\...^.......
001900C0: 68 03 00 00  00 00 00 00  44 05 28 B1  24 13 00 00  h.......D.(.$...
001900D0: 56 00 00 00  7C 13 00 00  98 03 00 00  10 00 00 00  V...|...........
001900E0: 09 00 00 00  EC 00 00 00  02 00 00 00  01 00 00 00  ................
001900F0: 7C 01 00 00  D0 15 00 00  01 00 00 00  02 00 00 00  |...............
00190100: 4C 17 00 00  A0 07 00 00  01 00 00 00  03 00 00 00  L...............
00190110: EC 1E 00 00  8C 0E 00 00  01 00 00 00  04 00 00 00  ................
00190120: 78 2D 00 00  14 03 00 00  02 00 00 00  05 00 00 00  x-..............
00190130: 8C 30 00 00  98 00 00 00  02 00 00 00  06 00 00 00  .0..............
00190140: 24 31 00 00  CC 00 00 00  02 00 00 00  07 00 00 00  $1..............
00190150: F0 31 00 00  F0 00 00 00  01 00 00 00  09 00 00 00  .1..............
00190160: E0 32 00 00  28 00 00 00  02 00 00 00  0B 00 00 00  .2..(...........
00190170: 08 33 00 00  04 00 00 00  01 00 00 00  53 73 48 64  .3..........SsHd
00190180: 2C 00 00 00  01 00 00 00  01 00 00 00  01 00 00 00  ,...............
00190190: 06 00 00 00  8C 00 00 00  01 00 00 00  98 15 00 00  ................
001901A0: 2C 00 00 00  5E 00 00 00  5E 00 00 00  00 00 00 00  ,...^...^.......
001901B0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................

------------------------------------------------------------------------------

======================================================================
Hardware/Driver Information:
Processor:              0x0
Page Size:              4096
Min App Address:        0x10000
Max App Address:        0x7ffeffff
Processor Mask:         0xff
Number of Processors:   8
Processor Type:         586
Allocation Granularity: 65536
Processor Level:        6
Processor Revision:     11527

Percent memory used:    10
Total physical memory:  -1
Free Memory:            -1
Page file:              -1
Total virtual memory:   2147352576

Gruss Motrius

**Comment by mangelus** [comment]
same here! 
bei mir trat es auf, nachdem ich gestern den gm wegen einer kaputten quest kontaktiert hab...
account: heckenhugo
char: akaki

**Comment by M0in** [comment]
jupp hab das selbe prob.
Acc:moinone
Char:blinkydoo

**Comment by mangelus** [comment]
looft wieder... danke an den Fixer^^

**Comment by Rojaxx** [comment]
Fix it pls 4 all MANNNNNNN

**Comment by mangelus** [comment]
jo, zu frueh gefreut... -> wieder kaputt!

**Comment by mangelus** [comment]
problem besteht wieder... bitte reopen!
