### ISSUE TITLE
Sturmschlag verfehlt trotz HitCap

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#761]
Was wird beobachtet:

Wenn man als Schamane Sturmschlag wirkt, kann dieser trotz Hitcap von 8% +  verfehlen.  

Da es ein zusätzlich gewährter physischer Angriff ist, sollte er beim Hitcap nicht mehr verfehlen können.

mfG  Frost

**Comment by dagochen** [comment]
Eine Grund-Verfehlens(-Resist)-Chance bleibt vermutlich auch bei Sturmschlag immer. Und ist das Hitcap nicht 9%?

**Comment by Seniorash** [comment]
8,6 gegen Bosse. Bei melees gibt es anders als bei castern ein richtiges cap

**Comment by hraesvelgr** [comment]
es ist vollkommen egal, ob es 8% sind oder 9%. der debuff von sturmschlag und der dadurch ausgelöste normale hit sollte mit der mechanik der normalen angriffe berechnet werden.

**Comment by Jipptech** [comment]
Es ist egal ob du die 8% oder 9% hit hast...du kannst auch mit 13% hit rumlaufen...aber es wird immer eine Chance bestehen, dass deine Attacken verfehlen werden...du kannst diese nur minimieren, aber nicht vollständig eliminieren.

**Comment by hraesvelgr** [comment]
also davon ist mir nix bekannt,d ass attacken auch bei hitcap verfehlen können.

**Comment by Seniorash** [comment]
Ab 9% mit 0 waffenkunde werden zumindest keine  mehr angezeigt ;)
Ich denke das ist das Problem bei Frostlatte. Allerdings sollten mit 8% dann auch deine Autohits verfehlen können

**Comment by dagochen** [comment]
Gibt immer ne ca. 1%-ige Chance für Miss/Resist....

Sturmschlag ist doch ne Fähigkeit die Nahkampf benötigt oder? Dann sollte es auch korrekt sein mit der Mechanik das es melee-gerollt wird.

**Comment by Frostlatte** [comment]
auch bei 9% verfehlt der Sturmschlag bei Bossen sehr oft..und das Verfehlen lese ich nur bei Sturmschlag im PvE Gear. Nicht bei Autohits...  Resist wäre ja ein Zauber  oder Ausweichen eben eine andere Mechanik als "Verfehlen".

Ich könnte mir vorstellen, dass der Schlag mit der Zauberhitchance berechnet wird. Da es aber ein "Extra" Angriff ist, sollte es mit der MeleeMechanik berechnet werden.

**Comment by SirBeansen** [comment]
Nur bei Zaubern bleibt die 1% wahrscheinlichkeit eines misses....nicht bei melee attacks. Dafür können die streifen/parriert/geblockt oder ausgewichen werden.

**Comment by hraesvelgr** [comment]
-Ich könnte mir vorstellen, dass der Schlag mit der Zauberhitchance berechnet wird. Da es aber ein "Extra" Angriff ist, sollte es mit der MeleeMechanik berechnet werden.

der treffer des zaubers ist zaubermechanik, der den debuff auslöst (mehr naturschaden). allerdings soll das wirken dieses zaubers (egal ob er resistet wird oder nicht trifft) einen autoangriff auslösen, der ganz normal als autoangriff gewertet und berechnet wird.

**Comment by Frostlatte** [comment]
Laut dieses Vanilla Links, zählt der Schlag als physisch und die Aura 20% dmg als Magie. 

https://vanilla-twinhead.twinstar.cz/?spell=17364
