### ISSUE TITLE
[Quest] Die Blutsegelbukaniere

### ISSUE THREAD

**Issue by walt0r** [ClassicWoW/Nefarian_1.12.1_Bugtracker#762]
http://datenbank.welli-it.de/?quest=604

Bei der Quest ist es nicht möglich, die Karte auf dem Ruderboot http://datenbank.welli-it.de/?item=3920 zu looten, wenn sie schon von jemandem in der gleichen Gruppe gelootet wurde. Habe versucht, sie nach dem Serverneustart zu looten, ohne die Quest abzubrechen und neu anzunehmen, hat nicht funktioniert. Quest abbrechen und neu annehmen funktioniert nicht.

**Comment by dagochen** [comment]
Quest mehrfach in den letzten 30 Tagen erfolgreich gemacht, in der Gruppe und solo.
