### ISSUE TITLE
Keine Wurfwaffen zu kaufen

### ISSUE THREAD

**Issue by jokihara** [ClassicWoW/Nefarian_1.12.1_Bugtracker#763]
Mir ist aufgefallen, dass es weit und breit keien Wurfwaffen für Schurken zu kaufen gibt. Meiner Meinung nach müssten die beim Gemischtwarenhändler verfügbar sein.

**Comment by Slimmer2** [comment]
Quellen?

**Comment by thrallsblood** [comment]
der hier verkauft bespielsweise

http://datenbank.welli-it.de/?npc=791

**Comment by KappaAlphaOmega** [comment]
Quelle: Webarchiv von Thottbot.com (2005).

Liste von Händlern für "Ausbalancierter Wurfdolch":
https://web.archive.org/web/20050412145159/http://www.thottbot.com/?i=29837

Verkaufsangebot von Thurman Mullby (Gemischtwarenhändler) in Stormwind:
https://web.archive.org/web/20050504045317/http://www.thottbot.com/?n=473864

Ruhm und Ehre der WayBackMachine von archive.org!
