### ISSUE TITLE
Quest: Die Relikte des Erwachens

### ISSUE THREAD

**Issue by Schattenruf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#764]
Die Truhe für den Saphier des Himmels spawnt nicht, somit ist das Quest unlösbar, da die anderen Truhen nur jeweils ein mal geöffnet werden können.

**Comment by hraesvelgr** [comment]
das dauert nur eine ganze zeit, weshalb die quest zu zweit ein graus war, aber alleine noch schwerer.
