### ISSUE TITLE
Prophet des Schattenhammerklans patroulliert nicht

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#765]
**Welches Verhalten wird beobachtet?**

Die 2 Propheten des Schattenhammerklans sind recht statisch. Sie laufen zwar auf einem kleinen Areal hin und her, vernachlässigen aber ihre eigentlich Patroullienroute.

**Wie sollte es sich verhalten?**

Sie sollten mit ihren Beschützern, d.h. 2-4 Rächern des Schattenhammerklans (lt. wowhead), gemäß den u.a. Wegpunkten durch Silithus wandern.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Wegpunkte 1: http://www.wowhead.com/npc=15308/twilight-prophet
Wegpunkte 2: http://www.strike-us-if-you-can.de/main/plain/index.php?go=tipps&p=silithus
WP1 und WP2 decken sich.
Auf wowhead wird die Menge der Beschützer auf 2-4 angegeben. Da es Momentan beim südlichen Propheten ca. 2 und beim nördlichen ca. 4 sind, wird die angabe so stimmen.

**Links aus unserer Datenbank**

Prophet des Schattenhammerklans: http://datenbank.welli-it.de/?npc=15308
Rächer des Schattenhammerklans: http://datenbank.welli-it.de/?npc=11880

**Comment by Ghulfang** [comment]
Bin auch der Meinung das 10 Minuten respawn Zeit zu kurz sind. Habe da 20 oder sogar 30 Minuten in Errinnerung. Habe leider nix genaues bisher dazu gefunden. Vlt hat jemand anderes Glück oder weiß mehr.

**Comment by Larnak1** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/454

**Comment by Ghulfang** [comment]
She patrol's between two camp locations (refer to picture below) starting at Twilight Post to Twilight Base Camp. She spawns every 20-30mins 

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/726-silithus-farming-guide-50-80g-hour.html
