### ISSUE TITLE
Ruf/Quest "Verschlüsselte Twilighttexte" - Zuviel Ruf

### ISSUE THREAD

**Issue by Ghulfang** [ClassicWoW/Nefarian_1.12.1_Bugtracker#766]
Die wiederholbare Ruf-Quest "Verschlüsselte Twilighttexte" in Silitus gibt 250 Ruf beim Zirkel des Cenarius pro Abgabe von 10 Texten. Richtig wäre aber 100 Ruf.
250 Ruf gabs ab 2.0.1

Quellen:
http://wowdata.buffed.de/item/Quest/Verschluesselter-Schattenhammertext-20404#comments

http://wow.ingame.de/forum/threads/93621-Rufsteigerung-bei-Zirkel-des-Cenarius

http://wow.4fansites.de/silithus.php

**Comment by dagochen** [comment]
Ich seh schon alle wie verrückt Texte farmen, bevor das hier geändert wird... ;)
