### ISSUE TITLE
Object: Altar der Tiefen (BFT) ohne Fuktion

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#767]
Welches Verhalten wird beobachtet?
Wenn man in Blackfathom Deeps am Ende der Instanz den Altar der Tiefen anklickt läuft ein Cast durch, nur passiert danach nichts,

Wie sollte es sich verhalten?
Wenn man auf den Altar klickt sollte der Cast durchlaufen und den Spieler nach Darnassus Porten.
Betrifft nur Spieler der Allianzfraktion

Schritte zur Reproduzierung.
Altar anklicken.

Quellen:
http://wowwiki.wikia.com/Blackfathom_Deeps

**Comment by hraesvelgr** [comment]
"After killing Aku'Mai you can click the altar in the back of the room to receive a teleport to outside the instance. There is also a Dwarf that spawns after the battle. Alliance toons can talk to the Dwarf and be ported to Darnassus."



zwerg (http://datenbank.welli-it.de/?npc=6729)  portet nach darnassus, er spawnt nach dem tod von akumai
http://wowwiki.wikia.com/Morridune
http://wow.zamimg.com/uploads/screenshots/normal/156418.jpg

"Morridune can be found in Blackfathom Deeps. He is a former member of the Twilight's Hammer cult and was locked away with Aku'mai for treason. After Aku'mai has been defeated by players, he comes out and creates a portal to Darnassus for members of the Alliance."

altar portet vor die instanz




allerdings: die quellen sind sich nisschen uneinig, wann morridune nun wirklich spawnt. nachdem man auf den altar klickt, nachdem mnan auf beide altäre klickt, nachdem man akumai besiegt, oder spawnt er garnicht, läuft er in den raum...keine ahnung. ich würd sagen, wir gehen den wowwiki-weg, und spawnen ihn einfach neben dem altar, zusammen mit seinem yell.
