### ISSUE TITLE
Totem der Flammenzunge fehlerhaft

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#768]
Das Totem der Flammenzunge gibt den Gruppenmitgliedern nicht wie vorgesehen bei jedem Waffenschwung die entsprechende Flammenzungenverzauberung. Sie tritt nur sporadisch auf...

...sollte aber eine 100% Procchance haben und mit dem Spelldamage skallieren wie das Äquivalent der Schamanen WaffenVerzauberung.

Wir haben es im PvE, PvP sowie Duellen getestet, daher sollte es recht leicht reproduzierbar sein.

Besten Dank zum Gruße,

Frost

**Comment by Haudraufinix** [comment]
Totem der Flammenzunge: http://datenbank.welli-it.de/?spell=16387
Passive Aura: http://datenbank.welli-it.de/?spell=16388 (Effekt mir nicht bekannt)
"Pulsierende" Aura: http://datenbank.welli-it.de/?spell=15036 (Verzaubert die Waffe)

als kleine Ergänzung ;)

**Comment by dagochen** [comment]
Mit "tritt nur sporadisch auf" ist dann vermutlich alle 5 Sekunden gemeint, verstehe ich das richtig?

**Comment by Haudraufinix** [comment]
die 5 Sekunden sind der Pulsintervall, in denen das Totem die Waffe neu verzaubert, das hat nichts mit dem Procc auf den Angriff zu tun

**Comment by Frostlatte** [comment]
Jupp...danke für die Ergänzungen Haudrauf^^
