### ISSUE TITLE
Windsteine: Twilightset wird nicht zerstört

### ISSUE THREAD

**Issue by Ghulfang** [ClassicWoW/Nefarian_1.12.1_Bugtracker#769]
Beim Aktivieren der Windsteine werden nicht alle drei Teile des Twilightsets zerstört. Bei mir verschwindet immer nur die Brust, Kopf und Schultern kann man wieder verwenden.

http://datenbank.welli-it.de/?item=20408 - Kopf
http://datenbank.welli-it.de/?item=20406 - Schulter
http://datenbank.welli-it.de/?item=20407 - Brust

http://youtu.be/ywxLyrZTFPw

**Comment by dagochen** [comment]
In deinem Video sieht man sehr deutlich, dass du ein komplettes Set verloren hast. Allerdings verschwinden erst die Items aus dem Inventar, danach erst die angelegten Items. Hab das bei mir auch schon beobachtet.

**Comment by Ghulfang** [comment]
Stimmt tatsächlich, hab ich übersehen. Damals stand man halt nach dem aktivieren halb nackt da, wohl deshalb meine Verwirrung.

**Comment by Gnomorus** [comment]
Ein bisschen abgeändert hat der Report trotzdem seine daseinsberechtigung.  Es wird eben das falsche Set zerstört.

**Comment by wahaxlekuke** [comment]
Mittlerweile werden zuerst angelegte Items entfernt.
