### ISSUE TITLE
Standbilder in Battlegrounds

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#772]
In den Battlegrounds kommt es vermehrt zu Standbildern während des Kampfes. Diese dauern zumeist zwischen 5 - 10 Sek. Dabei scheinen diese Spieler anhängig aufzutreten, da Kampfgefährten im TS diese selten gleichzeitig ansagen.

Vlt. können weitere Erfahrungen helfen, das Problem zu finden. Wie gesagt, bei mir tritt das Problem überwiegend im PvP auf.

**Comment by hraesvelgr** [comment]
im pvp, speziell kriegshymnenschlucht, und in stratholme am haupttor wenn man die erste npc gruppe angreift.
