### ISSUE TITLE
Unsichtbares Flaggentappen im Arathibecken

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#773]
Nach wie vor ist ein unsichtbares Flaggentappen im BG möglich, sogar ohne dass die Tapp-Animation einen Hinweis darauf gibt. 
Videobelege sind daher schwer zu bekommen, da man das gesamte BG die Flagge filmen müsste. 

Als Beleg könnte ich nur eine TS Situation schildern, bei der wir zu 3 vor einer Flag standen uns unterhielten und alle gleichzeitig mit einem "Hähh" den unsichtbaren Tapp kommentierten. 
Evtl. könnte man auf dem Testserver ein BG simulieren u. verschiedene Szenarien testen...Unsichtbarkeitstrank, stealth usw....oder aber Leuter melden sich mal fairer Weise zu Wort und erläutern die Mechanik, die Ihnen  vom guten Freund "berichtet wurde"

**Comment by dagochen** [comment]
Vielleicht nicht hier rein posten wie es geht, sondern direkt an GM/Developer schicken, sonst macht es jeder ;)
