### ISSUE TITLE
Fallen entschärfen

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#774]
Welches Verhalten wird beobachtet?
Als Schurke können fast alle Fallen der Jäger nicht entschärft werden, oder es werden zwischen 3-20 versuche benötigt weil der Skill Fallen entschärfen nur einen Orangenes Skill lvl bei der Falle hat.

Wie sollte es sich verhalten?
Alle Hunterfallen müssten bei einem 60er Schurken ein grünes Skill lvl bei Fallen entschärfen haben und zu 100% beim ersten Versuch entschärft werden.

http://community.mmobase.de/schurke/6941-fallen-entschaerfen.html

**Comment by dagochen** [comment]
Quelle:
http://web.archive.org/web/20070811095403/http://www.thottbot.com/s1842

In der oberen Quelle sind einige Kommentare, dass man sehr nah ran muss und mit Pech die Falle auslöst. 

Auch wird geschrieben, dass man den Zauber aus dem Zauberbuch benutzen musste. Vermutlich war es damals schon ein Bug, der irgendwann(?), vielleicht auch schon in Classic gefixt wurde?

Kommentare nach 2.0 (keine Ahnung ob da viel geändert wurde)
http://www.wowhead.c...l=1842#comments
By Dena (623 – 1·5) on 2007/08/04 (Patch 2.1.3)	Report	
From my experience, it's about luck if a hunter trap goes off while disarming, even at maximum range.
Still a great supportive skill in PvP, in my opinion, seeing that only us rogues actually see the traps in time to avoid (and to disarm for example; before your warrior buddy charges into) them.

By MusubiKororin (330 – 1·4) on 2007/11/18 (Patch 2.3.0)	Report	
I've found this skill to be pretty useless in pvp; if the fight hasn't started yet, there will usually be a flare on the trap, making it impossible to get close enough. I've also tested this out of stealth (in a duel) and I was unable to get close enough to disarm the trap without it going off.

**Comment by dagochen** [comment]
Ok, grad mit meinem Schurken mal bisschen rumprobiert:
Der Zauber Falle entschärfen funktioniert korrekt. Geht man allerdings mit dem Cursor über die Falle erscheint das Interaktionsrädchen. Dies sagt einem, dass man die Fähigkeit Fallen entschärfen 300 benötigt und die Falle lässt sich nicht entschärfen.

**Comment by nightblizard** [comment]
Der Fehler liegt hier darin, dass man Fallen in Classic noch nicht mit einem Rechtsklick entschärfen können sollte. Das ist deshalb auf dem Server, weil alle Classic Server ein backport von TBC Servern sind und das (neben vielen anderen Dingen) übersehen wurde.

Für den zukünftigen Dev, der das in Angriff nimmt:
Alle Hunter Fallen müssen das Flag 16 bekommen.

**Comment by Slipru** [comment]
Auch wenn man nicht das Rädchen benutzt sondern den Zauber aus dem Zauberbuch lassen sich einige Fallen nicht entschärfen ( Fehlversuch ) egal wie oft man es versucht.
