### ISSUE TITLE
Jägerfallen Reichweite zu kurz

### ISSUE THREAD

**Issue by nightblizard** [ClassicWoW/Nefarian_1.12.1_Bugtracker#775]
Derzeitiges Verhalten:
Fallen von Jägern haben eine Reichweite von 2 Metern.

Sollverhalten:
Fallen müssen eine Reichweite von 5 Metern haben.

Quelle:
http://web.archive.org/web/20070811095403/http://www.thottbot.com/s1842 - Antwort von Benutzer <Blank>

**Comment by pvpmaster2000** [comment]
So sehr ich die ganzen Hunterbuffs in letzter Zeit zu schätzen weiß, so gewiss weiß ich dass die Reichweite bei uns keines falls zu gering ist.
 "useless now (since 1.7 patch but 1.8 patch just came out)
traps range is now incresed to 5-6 yards!!! cant disarm nemore "
halte ich - unabhängig von der Rechtschreibung - für ein wenig qualifizierten Kommentar. Auch weil in den Patch notes nicht von einer Änderung der Reichweite dokumentiert ist. 
Subjektiv - und ich spiele selber Jäger im Pvp - ist die Reichweite von der sie ausgelöst wird auf Nefarian sogar zu hoch und es wirkt total buggy auf welche Distanz andere Spieler getrapt werden können. 
Auf zwei anderen Classic-Privatservern auf denen ich regelmäßig spiele ist die Reichweite jedenfalls spürbar geringer.

**Comment by SirBeansen** [comment]
Also es ist so das die Fallen range hier schonmal geändert wurde wenn ich mich recht erinnere.

Als ich hier angefangen habe war die range auf 5 yards. Doch irgendwer hatte die fallen range von TwinStar (anderer privat server) 2yards als bug gemeldet. Daraufhin wurde die range auch hier auf 2 yards umgeändert. Die Frage ist halt welches jetzt die richtige range ist.

@pvpmaster2000 

Das die range dir zu hoch vor kommt stimmt nicht. Eher das gegenteil.
Schau dir mal https://www.youtube.com/watch?v=aGli2EPbK-A ab 2:35 an, wann der Schurke schon die trap auslößt.

**Comment by bugreportor** [comment]
In dem Video bei 2:35 (https://youtu.be/aGli2EPbK-A?t=2m34s) kann man gut erkennen dass die Eisfalle NICHT auf 5 Meter Range ausgelöst wird. 
Der Jäger is von FieserTrick betroffen und bekommt zwei weitere Authits ab bevor die Falle ausgelöst wird. (Sprich Meele-Fäigkeiten ohne Falle auszulösen)
Bei uns auf dem Server ist das schon gar nicht möglich, hab ich eben getestet. 
Wenn ein Jäger in der Falle Steht, ist es auf Nefarian nicht möglich FieserTrick / irgendeine Andere Fähigkeit die Nahkampf erfordert auf diesen Jäger auszuführen ohne dabei in dessen Falle zu landen.
Wirkt für mich so als sei die Range zu hoch bei uns.

**Comment by SirBeansen** [comment]
@bugreportor 

Schau dir mal an wo der Hunter steht...er steht nicht in der Falle und der Schurke kommt auch nicht hinzer ihm raus sondern an der Seite. Wenn dann musst du das auch so nachstellen....
Aber die range ist hier auf dem Server nicht zu groß wenn dann gefühlt zu klein zu den videos:

https://www.youtube.com/watch?v=cCQWtQaUOIQ ab 10 Sekunden

https://nl.proxfree.com/permalink.php?url=s54aaHA%2FaGsaD5vHs0QZLcUclS%2FcUxrnNZwEMCiA0I%2FyqYSMrWZXIhaXPfY24N7P4EnHJYRK3nO937EMCE%2FZKw%3D%3D&bit=1 Ab min 4 Dort zieht man ganz gut das zb durch den Server das Target auch später die trap auslösen kann und noch 1-2 schritte gehen kann obwohl die Falle schon längst getriggert hat.

Dann ab 5:15 legt er sehr wiet vor dem Pala die trap....dich dieser lößt die trotzdem aus.

**Comment by hmmkay** [comment]
" "useless now (since 1.7 patch but 1.8 patch just came out)
traps range is now incresed to 5-6 yards!!! cant disarm nemore "
halte ich - unabhängig von der Rechtschreibung - für einen wenig qualifizierten Kommentar. Auch weil in den Patch notes nicht von einer Änderung der Reichweite dokumentiert ist. "

Als der Spott auf das Hunterpet "gefixt" wurde, war eine Forumquelle ausreichend. Leider hat jemand das Ticket gelöscht, aber spätestens seit dem sollten diese Art von Quellen standardmäßig anerkannt werden.


In dem Video oben sieht man auch ab Sek. 50 auch sehr gut, wie groß die Fallenreichweite sein müsste...

**Comment by wahaxlekuke** [comment]
Ich vermute mal, dass die Reichweite von Hunterfallen tatsächlich etwas größer war, als bei uns. Allerdings denke ich auch, dass auf dem Offi-Server die Tickrate der Fallen geringer war. 

Mit 5 Metern Fallenreichweite wäre es bei uns unmöglich Fieser Trick, Falle entschärfen usw. bei ner Frostfalle zu benutzten.

**Comment by SirBeansen** [comment]
Welche range haben die denn jetzt genau?

**Comment by hmmkay** [comment]
D.h. es wird gefixt und die Tickrate angepasst, oder nicht gefixt (obwohl es Blizzlike wäre)? Ich meine, wenn Nightblizard sowas reportet, dann wird er wohl recherchiert haben =).

**Comment by hmmkay** [comment]
Momentane Range ist 2m: http://datenbank.welli-it.de/?spell=14311. Zur zeit ist es also Möglich, dass ein Meele den Hunter über die Falle hinweg killen kann (da Meelerange 5m) ohne, dass die Falle auslöst.

@wahaxlekuke 
Bitte setz das auf die to do list :).

Ich kann auch gerne noch Bugreports von anderen Privatservern verlinken, wo das selbe Problem reportet wurde und mit etwaigen Beispielen (Videos), dass die Range größer sein müsste. Die kurze Range beeinflusst das PvP-Game eines Hunters sehr extrem.
(Vor allem, weil hier beim Scatter-Shot der Gegner teilweise sehr weit wegrennt. Das wurde schon mal reportet, gefixt aber tritt teilweise wieder auf. Daher macht es die kurze Range schwer den Gegner vernünftig zu trappen. Nur als kleiner Anreiz :) )

**Comment by SirBeansen** [comment]
Wird das nochmal gefixt? Immerhin war die range am anfang richtig auf 5 yards und wurde dann anscheind fälschlicherweise geändert.

**Comment by SirBeansen** [comment]
push

**Comment by hmmkay** [comment]
push

**Comment by soda09** [comment]
Hier, das wäre auch nochmal nen Indiz dafür, dass die Fallenreichweite höher und die Triggerzeit etwas langsamer sein müsste (ab Min 1.36): https://nl.proxfree.com/permalink.php?url=s54aaHA%2FaGsaD5vHs0QZLcUclS%2FcUxrnNZwEMCiA0I8Hrvol3Wk4BLg%2FNBuDDnh%2FEZQ%2BZ00Caaqduowhry4Cvg%3D%3D&bit=1

**Comment by dagochen** [comment]
In den DBC-Dateien und deren Doku steht, dass es sich um Durchmesser = 5 Meter handelt. Damit wäre die Reichweite zum Ziel bei 2,5 Meter, immerhin ein halber Meter größer als bei uns aktuell. Ich denke der Unterschied von Durchmesser und Radius ist bei der Programmierung des mangos-core nicht korrekt beachtet worden, wodurch bei Fallen diese falschen Werte entstanden sind.

**Comment by soda09** [comment]
5 Meter (Durchmesser) wäre Meelerange und damit könnte man wenigstens nicht mehr so easy über die Falle drüberhinweg hauen.

**Comment by Seniorash** [comment]
Nochmal zusammengefasst:
Zitat Wahax: 
Mit 5 Metern Fallenreichweite wäre es bei uns unmöglich Fieser Trick, Falle entschärfen usw. bei ner Frostfalle zu benutzten.

Und dann schaut mal Beansens Video bei den genannten 2:35 obwohl die Falle in Richtung des Schurken steht... Die Quelle ist außerdem mehr als fragwürdig. In keinem Video konnte ich eine solche Range finden, wie sie jetzt bei uns ist.

**Comment by dagochen** [comment]
Sie hat ja auch nicht 5 Meter Reichweite, sondern 5 Meter Durchmesser. Das ist also nur halb so weit. Der fehlerhafte Wert resultierte aus einem Fehler beim laden der dbc-Dateien. "Diameter" und "radius" sind halt 2 verschiedene Dinge ;)
