### ISSUE TITLE
Entschärfen von Jägerfallen setzt kein PvP Flag

### ISSUE THREAD

**Issue by nightblizard** [ClassicWoW/Nefarian_1.12.1_Bugtracker#776]
Derzeitiges Verhalten:
Das Entschärfen von Fallen setzt dem Schurken kein PvP Flag

Sollverhalten:
PvP Flag setzen beim Entschärfen

**Comment by Ghulfang** [comment]
weil ich das heute erst gelesen habe und nicht weiß ob es später nochmal geändert wurde.

Eine feindliche Falle eines Jägers zu Entschärfen wird den Schurken nicht länger für den PvP-Kampf markieren.

Quelle: http://wow.4fansites.de/patchnotes_1_6.php

und nochwas:

Wenn der PvP-Status eines Jägers 'Inaktiv' ist, ist es Schurken nicht möglich, dessen Falle zu entschärfen.

Quelle: http://wow.4fansites.de/patchnotes_1_12.php

**Comment by Haudraufinix** [comment]
Disarming an enemy faction hunter's trap will now flag the rogue for PvP.
aus http://wowwiki.wikia.com/Patch_1.6.0 - > könnte es sich bei "Eine feindliche Falle eines Jägers zu Entschärfen wird den Schurken nicht länger für den PvP-Kampf markieren." um einen übersetzungsfehler handelt?

**Comment by Ghulfang** [comment]
habs auch grad nochmal im englischen gelesen. scheint sich wohl wirklich um einen übersetztungsfehler zu handeln. sry
