### ISSUE TITLE
Vom Land ins Wasser Chargen > Disconnect > Tot

### ISSUE THREAD

**Issue by SirSoarin** [ClassicWoW/Nefarian_1.12.1_Bugtracker#777]
Es ist mir nun öfters im Arathibecken passiert, das ich vom Ufer übers oder durch das Wasser gestürmt  , einen Disco bekommen habe und gestorben bin.

Selbiges ist auch in Darnassus passiert als ich eine Kröte angecharged habe die im Wasser rumdümpelte.

Kein Weltbewegender Bug , aber es ist Ärgerlich einen Schwimmenden Feind aus Angst eines Spiel Crashes nicht mit Ansturm und Abfangen angreifen zu können

**Comment by wahaxlekuke** [comment]
Das ist ziemlich sicher das gleiche Problem, wie der Disconnect, wenn man unter einem Wasserfall schwimmt. (Ich dachte zuerst das sei ein Client-Bug, aber man wird vom Server gekickt, weil der Client den Swimming-Flag sendet, obwohl man für den Server nicht im Wasser ist.)

**Comment by dagochen** [comment]
nicht doch eher Speedhack-Detection-Problem?

**Comment by Dotox** [comment]
Kann ich nicht (mehr) reproduzieren. Hab verschiedene Varianten versucht, gab keine Probleme. Wenn du das nächste mal im AB unterwegs bist, nimm die Session einfach auf und verlink mir den Ausschnitt :)
