### ISSUE TITLE
Animation von "Kopfgeldjäger der Frostmane" fehlerhaft

### ISSUE THREAD

**Issue by suddenrage** [ClassicWoW/Nefarian_1.12.1_Bugtracker#779]
Hallo liebes Classic Team,
wie im Titel beschrieben ist mir ein auffälliger Animationsfehler bei dem Moob "Kopfgeldjäger der Frostmane" aufgefallen.

Bild: http://i1222.photobucket.com/albums/dd493/Konochan/WoWScrnShot_060615_102526_zpsoplremlw.jpg

Im Bild zu sehen, wie ich vom Spell des Moobs getroffen wurde, in Form eines kleinen karierten Würfels.

Quelle: Konnte leider zu dem Moob nichts in den Datenbanken finden.

**Comment by c0keh** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/51
