### ISSUE TITLE
Blitzschlagschild verursacht Spell push back

### ISSUE THREAD

**Issue by SirBeansen** [ClassicWoW/Nefarian_1.12.1_Bugtracker#780]
Welches Verhalten wird beobachtet?
Das Schamanen Blitzschlagschild verursacht beim gegner wenn dieser es auslößt eine Verzögerung des cast.

Wie sollte es sich verhalten?
Das Schild sollte kein Spell push Back auslösen.

Links aus unserer Datenbank 

http://datenbank.welli-it.de/?spell=10432 

unter siehe auch sind die restlichen ränge

**Comment by wahaxlekuke** [comment]
Hast du auch irgendwelche Quellen, dass es das nicht tuen sollte?

**Comment by Seniorash** [comment]
Wie löst man das Schild aus wenn man gerade castet?

**Comment by wahaxlekuke** [comment]
Ich denke mal, wenn du mit einem Zauber kämpfst, der eine Flugzeit hat. In dem Fall trifft dein Spell das Ziel, während du schon den nächsten Zauber castest.

**Comment by Dotox** [comment]
Bitte Quellen hinterlegen. Im Moment ist es so, dass jeder Schaden den Cast verzögert.
