### ISSUE TITLE
Tiertrainer in IF Fehlerhaft

### ISSUE THREAD

**Issue by hmmkay** [ClassicWoW/Nefarian_1.12.1_Bugtracker#784]
Welches Verhalten wird beobachtet?
Tiertrainer in IF verlernt keine Tierfähigkeiten.

Wie sollte es sich verhalten?
Man sollte in jeder Hauptstadt Pettalente verlernen können.
"Hunter pets can now be untrained of all their skills from any beast trainer in the major cities. "

Schritte zur Reproduzierung
Trainer aufsuchen und versuchen die Tiertalente verlernen zu lassen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
http://wowwiki.wikia.com/Patch_1.7.0

**Comment by c0keh** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/177
