### ISSUE TITLE
Krieger: Anger Management generiert keine Wut.

### ISSUE THREAD

**Issue by bugreportor** [ClassicWoW/Nefarian_1.12.1_Bugtracker#786]
Welches Verhalten wird beobachtet?
Das Krieger-Talent "Aggressionskontrolle" (http://datenbank.welli-it.de/?spell=12296) generiert keine Wut. 

Wie sollte es sich verhalten?
Aggressionskontrolle sollte alle drei Sekunden 1 Wutpunkt generieren sobald der Krieger im Kampf ist. (Auch wenn das nicht explizit im Tooltip erwähnt wird)

Schritte zur Reproduzierung
Wenn man im Raid durch den Pull in den Kampf kommt schaun ob man nur durchs Rumstehen nach 60 Sekunden 20 Wutpunkte generiert hat.

Informationen:
"The written description of this talent states that it reduces decay of rage while out of battle, but it has an exceptional undocumented side effect: while in combat, this talent will generate one rage per tick. "
"..this means that if you are in combat for 60 seconds, Anger Management will give you 20 rage. In this regard, Anger Management is roughly equivalent to rank 2 Improved Berserker Rage which also gives the Warrior 20 rage every 60 seconds.."

http://wowwiki.wikia.com/Anger_Management?oldid=376584

**Comment by wahaxlekuke** [comment]
Ich dacht ursprünglich das Talent wär verbugt, weil es Wut generiert, obwohl das nicht im Tooltip steht... 

Naja zumindest funktioniert die Wut-Generierung bei mir.

**Comment by bugreportor** [comment]
Ich habe es heute nochmal ausgiebig im Raid getestet und es generiert zeitweise tatsächlich Wut. 
Allerdings wirklich erst nach dem man mal angegriffen hat. Stirbt der Mob, hört die Generation wieder auf auch wenn man noch im Kampf ist. (Bei Razorgore hat die Generation in der ersten Phase andauernd ausgesetzt, obwohl ich nicht ein einziges Mal aus dem Kampf gekommen bin) 
Auto-Attack einfach zu aktivieren obwohl man noch nicht in LOS oder meele range steht lässt die Generation auch nicht beginnen. (Man muss wirklich Schaden verursachen, um sie zu triggern)
Sollzustand:
Das Talent sollte sobald man den Kampf betritt anfangen Wut zu genieren, also auch schon beim Bosspulll bevor man das erste Mal zugeschlagen hat. Zudem sollte die Generation anhalten bis man den Kampf verlässt und nicht zwischendurch aussetzten weil ein Mob stirbt oder eine längere Dmg-Pause vom Encounter gefordert ist.

**Comment by nightblizard** [comment]
Das Aktivieren von Auto-Attacks setzt dich nicht wirklich in den Kampf. Die standard Unit-Frames mögen das vielleicht zwar anzeigen, aber das lässt sich relativ leicht überprüfen. Wenn du mit einem Schurken Auto-Attack wirkst, dann kannst du trotzdem noch in Verstohlenheit wechseln.
So lange du keine feindliche Aktion gegenüber Andere ausführst, wirst du nicht als im Kampf markiert. Dementsprechend darf das Talent auch keine Wut erzeugen, wenn du mit aktivierten Auto-Attack 2 Minuten neben deinem Ziel stehst, weil du sonst ständig volle Wut hättest.

**Comment by bugreportor** [comment]
> Das Aktivieren von Auto-Attacks setzt dich nicht wirklich in den Kampf.

Das ist klar. Aber beim Bosspull kommt der ganze Raid automatisch in den Kampf. Und dann ist es egal ob ich autoattack aktiviert habe oder nicht, die Wutgeneration setzt frühestens ein wenn ich das erste Mal Schaden verursacht habe.

> Die standard Unit-Frames mögen das vielleicht zwar anzeigen, aber das lässt sich relativ leicht überprüfen. Wenn du mit einem Schurken Auto-Attack wirkst, dann kannst du trotzdem noch in Verstohlenheit wechseln.

Der Sturmangriff vom Krieger funktioniert auch nur außerhalb des Kampfes genauso wie das Bufffood. Zudem zeigt mein SCT mir an <Beginne Kampf> und <Verlasse Kampf>.

Beispiel Razorgore: Hier hat die das Talent zu großen Teilen keine Wut  erzeugt, obwohl ich permanent im Kampf war. (kein charge möglich, kein essen möglich)
Beispiel Firemaw: In der Antankphase nach dem Bosspull ist der ganze Raid automatisch im Kampf. Das Talent fängt aber frühestens ab dem Zeitpunkt an Wut zu generieren wenn ich das erste Mal Schaden am Boss verursacht habe. In längeren Schaden-Pausen, setzt die Wutgeneration wieder aus. Das Talent sollte aber nicht triggern wenn man Schaden verursacht, sondern sobald der Spieler als "in combat" geflagt ist. 



>So lange du keine feindliche Aktion gegenüber Andere ausführst, wirst du nicht als im Kampf markiert. Dementsprechend darf das Talent auch keine Wut erzeugen, wenn du mit aktivierten Auto-Attack 2 Minuten neben deinem Ziel stehst, weil du sonst ständig volle Wut hättest.

Das ist klar. Aber wie oben beschrieben

**Comment by Testear** [comment]
(Bei Razorgore hat die Generierung in der ersten Phase andauernd ausgesetzt, obwohl ich nicht ein einziges Mal aus dem Kampf gekommen bin) 

Ich denke, du bist sogar regelmäßig aus dem Kampf rausgekommen. 
Bei uns sind die einzigen, die permanent bei Razorgore infight sind die Drachenkiter und deren Heiler, weil Razorgore durch übernehmen freundlich wird. Erst in P2 ist wieder der ganze Raid durch den Boss im Kampf.
Man sieht also das Problem ist nicht das Talent, sondern der Bosskampf bei dem du es getestet hast.

**Comment by bugreportor** [comment]
> Ich denke, du bist sogar regelmäßig aus dem Kampf rausgekommen. 

Nein, bin ich nicht. Und man sollte auch nicht aus dem Kampf kommen nach Blizzard-standard. Das  wäre Buguse.

> Man sieht also das Problem ist nicht das Talent, sondern der Bosskampf bei dem du es getestet hast.

Ich hab es bei allen Bossen in Bwl und Mc getestet. 

>Nebenbei bemerkt, als ich das vor über einem Jahr getestet habe, hat das Talent reibungslos funktioniert

Ich glaube Du bist mit der Mechanik des Talents nicht vertraut. Das Talent hat hier nämlich hat noch nie kontinuierlich Wut erzeugt. Und selbst wenn es vor einem Jahr funktioniert hätte, würde es nicht daran ändern dass es im Moment nicht so funktioniert wie es soll.

**Comment by Testear** [comment]
So, ich habs jetzt nochmal getestet. Du musst entweder einmal zuschlagen, Demoshout oder Blutrausch anmachen, damit du Aggressionskontrolle aktivierst. Auch wenn der Mob stirbt durch den es aktiviert ist bleibt die Wutregeneration aktiv.
Ich habs an Kleintieren im Elwynnforrest ausprobiert, einfach mit Demoshout pullen und du siehst, dass alles richtig Funktioniert.
Ich denke das Problem liegt hier eher bei der Aktivierungsmechanik, falls das wirklich ein Bug ist.

Out of Topic: Wenn die Adds bei Razorgore schnell genug umkippen kommst du sehrwohl oft aber kurz aus dem Kampf. Das erste mal, nachdem die 2 Orcwachen + KontrollOrc tot und Razorgore übernommen ist. Und dannach zwischendurch immer wieder kurz.
