### ISSUE TITLE
Kein Drop von Rar-Mobs

### ISSUE THREAD

**Issue by thrallsblood** [ClassicWoW/Nefarian_1.12.1_Bugtracker#787]
Hallo,

ich wollte mal fragen, wie es denn um die Drops von Rarmobs steht.

Welches Verhalten wird beobachtet?

Kein Rar-Mob droppt seltene, rare oder epische Gegenstände, sondern lediglich normale Sachen.

Wie sollte es sich verhalten?

Damals und auch heute war und ist es so, dass in jedem Rar-Mob mindestens ein seltenes oder besseres Item zu finden ist.

Schritte zur Reproduzierung

Am einfachsten verschiedene Loot-Tabellen überprüfen und ggf. korrigieren.

Danke für eine Antwort ;)

**Comment by Gnomorus** [comment]
gief quelle - kriegst du bugfix. vielleicht :p

**Comment by g3n3a** [comment]
http://wowwiki.wikia.com/Rare_mob

Rares hatten früher ne spezielle Loottable. Sie droppten mobbezogene Gegenstände von grüner oder blauer Qualität. Rares in Instanzen scheinen dagegen korrekt Loot zu droppen.

**Comment by Larnak1** [comment]
Hallo,
das Thema kommt immer wieder mal auf und wurde auch schon im Forum diskutiert, beispielsweise hier:
http://community.mmobase.de/hilfe-und-support/6049-rare-mob-loot-ui-fehler-oder-bug.html
woraus auch hervorgeht, dass zumindest Nightblizzard das fehlerhafte Verhalten bewusst ist, es allerdings keine Priorität hat.

Ich hatte BrainSmooth damals eine PN geschrieben auf seine Bitte hin, Quellen zu melden, wenn wir welche hätten, ich zitiere die hier einfach mal.


>du hattest im Thread über Rare Mob Loot darum gebeten, dir per PN Quellen zum Drop zu schicken.

>Vorweg: Dass Raremobs auf diesem Server praktisch nie irgendwas droppen ist mir auch aufgefallen, ich habe hier in den letzten Wochen (vorher habe ich kaum gespielt) vielleicht 5 Rares gefunden, gedroppt hat keiner davon. Auch meine Gildenkollegen haben das bestätigt.

>Hier ein paar Quellen mit Hinweisen darauf, dass grüne Drops von Rares etwas selbstverständliches waren:
1) http://www.wowdaily.info/a.asp?a=2013434
Quelle von 2006, oben steht "One can expect something nice to drop", was ein Hinweis auf mindestens grüne Beute sein dürfte

>2) http://wow.ingame.de/forum/community...m-spiel-98179/
Aus diesem Thread von 2006 geht in einigen Beiträgen hervor, dass grüne Drops bei Rare-Mobs offenbar üblich waren. Einer spricht sogar von "nur" grünen Drops, offenbar war ein grünes Item bei Rare Mobs also fast eine Enttäuschung.

>3) http://wow.allakhazam.com/forum.html...21&h=50&p=1#23
Thread von 2005. Hier wird deutlich ausgesprochen, dass Rares (abgesehen von einigen Ausnahmen) nahezu immer grün droppen (Wobei die Prozentzahl vermutlich nur sein Gefühl spiegelt und nicht als exakter Wert wahrgenommen werden darf)

>4) http://gold-world-of-warcraft.com/30...ml#comment-200
Eintrag von vor "8 Jahren". Die Formulierung "if you're luvky enough there will bea rare mob spawn so he drops some nice items" deutet darauf hin, dass es sehr zu erwarten ist, dass ein Rare deutlich überdurchschnittlich droppt

>Persönliche Erinnerung:
In meiner Erinnerung haben Rares auch nahezu immer grün gedroppt. Ausnahme: Die etwas weniger seltenen Rares in den Startgebieten, die man fast jedes Mal trifft und die meistens nur weißes Zeug dabei haben, was man zu dem Zeitpunkt aber oft auch noch brauchen kann (Umhänge, mal 'ne Tasche, ..)

**Comment by dagochen** [comment]
Es war früher halt so, dass nicht jeder Raremob speziellen Loot hatte. Vultros ist da ein gutes Beispiel: der hatte früher manchmal seine Kralle, aber östers auch nicht. Hier ist es hingegen ein garantierter Drop. So ist es mit einigen Rares. Aktuelle Lootlisten von wowhead sind hingegen eine nutzlose Quelle, da diese Listen von jetzt sind, nicht von damals.

Früher:
https://web.archive.org/web/20071103210755/http://wow.allakhazam.com/db/mob.html?wmob=462
Heute:
http://datenbank.welli-it.de/?npc=462

**Comment by nightblizard** [comment]
Ich hab das damals ein wenig unglücklich ausgedrückt. Das Problem mit fast allen Rare Mobs ist, dass es heute so gut wie nicht mehr nachvollziehbar ist wer da was droppen sollte. Da kannst du schnell mal Wochen damit verbringen die Loottables für eine handvoll NPCs zu beheben, weil du so viel nachforschen und vergleichen musst. Das ist den Aufwand einfach nicht wert, weil ich in der selben Zeit dutzende andere Bugs beheben kann.
Das wäre ggf. ein gutes Communityprojekt. Jeder Spieler sucht 1-2 Infos zu den Raremobs raus und postet die so simpel wie möglich (oder besser noch in SQL Form) im Forum oder hier im Bugreport. Dann wäre in absehbarer Zeit mit einem Fix zu rechnen, aber ansonsten steht das gaaanz weit hinten an.

**Comment by Larnak1** [comment]
Das ist ein valider Punkt. 

Zugegeben, ohne Quelle, aber in meiner Erinnerung ist es so, dass die Mehrheit der Raremobs einfach zufällig irgendein grünes oder blaues (vllt auch episches?) Item aus ihrer Levelrange droppen, so wie es auch jeder andere Mob des Levels kann, nur eben mit deutlich höherer Chance (~100% für "grün"). Diejenigen Rares, die wirklich spezifischen Loot haben, also spezielle Items, die es nur dort gibt und die auf den Rare angepasst sind, waren meiner Erinnerung nach eher selten.

Wäre es vielleicht einfacher, zunächst allen Raremobs höhere Dropchancen auf die ihrem Level entsprechenden Worlddrops zu geben (also seltener Loot wie bei normalen Mobs, nur wahrscheinlicher), und dann spezielle Dropchancen einzelner Mobs danach Stück für Stück zu korrigieren, sobald jemandem etwas auffällt und ein Bugreport eingeht?

**Comment by nightblizard** [comment]
Ich persönlich bin kein Fan von solchen Zwischenlösungen, da sie doppelt Arbeit bedeuten. Und 2x Arbeit klaut Zeit von einem anderen Bugfix. Wenn es nur noch triviale Bugs gibt lässt sich darüber diskutieren, aber bis dahin ist es recht unwahrscheinlich, dass ich mir die Zeit dafür nehme, da der Nutzen für den einzelnen Spieler nicht groß genug ist, dass sich das rechtfertigen ließe.

**Comment by g3n3a** [comment]
Liste gibts hier 
http://web.archive.org/web/20060701034234/http://wow.allakhazam.com/dyn/mobs/rare.html

**Comment by thrallsblood** [comment]
wenn ich loot listen machen würde, würdet ihr se annehmen?

**Comment by thrallsblood** [comment]
zudem können beispielsweise Drops wie http://eu.battle.net/wow/de/item/12836 garnicht in der datenbank vorkommen.

**Comment by g3n3a** [comment]
Wobei ich vorsichtig mit dem Golddrop-Wert bin. Das ist definitiv nicht die Menge, die man direkt lootet. Aktuell in Retail WoW ist der lvl 42 und droppt ~3s. Den derzeitigen Datenbankwert würde ich daher nicht ändern was das anbelangt.

**Comment by thrallsblood** [comment]
Ja 1g 43s kommt mir auch schon etwas viel vor. So viel droppt ja nen iniboss in dem lvl nicht^^

**Comment by Gnomorus** [comment]
Es handelt sich um mit an Sicherheit grenzender Wahrscheinlichkeit um einen Mangos Kern. Ich hoffe, du kriegst das irgendwie zumindest semi-automatisch hin. Alles andere ist doch purer Selbstmord. Würde das genaue Format erstmal mit den Devs absprechen - es sei denn du hast natürlich zu viel Zeit :D

**Comment by thrallsblood** [comment]
Naja der Sinn von nem rarmob is die Herausforderung und dessen loot. So ist er einfach nur nen nerviger Mob um den jeder ein Bogen macht. Die batchdateien sind kein Problem.  Wenn man das ganze mal bei wow-v eingeragen hat kann man es in allen 6 Formaten speichern. Da haben wir früher alle items, loot npc's etc. Erstellt und hatten nie Probleme damit

**Comment by thrallsblood** [comment]
Hab nochmal eine andere Seite gefunden mit richtigen droprates denk die verwende ich^^

**Comment by Larnak1** [comment]
Bevor du da Arbeit investierst sprich aber lieber nochmal mit Night etc. ab, ob das als Quelle für die Dropchancen akzeptiert wird :)

**Comment by markthetechie** [comment]
Natürlich wäre es super, wenn jemand tatsächlich die originalen Loottables aller rares vollständig zusammentragen könnte. Aber wie bereits angesprochen, viel Arbeit und evtl. garnicht vollständig möglich.
Warum also nicht einfach generell alle rares grüne und blaue Gegenstände passend zu ihrem levelbereich mit erhöhter chance droppen lassen? Das ist vielleicht nicht 100%ig blizzlike, kommt dem aber schon sehr nahe und ist definitiv 100 mal blizzlikiger (was für ein Wort Oo) als es jetzt ist. Zudem dürfte das mit vertretbarem Aufwand machbar sein, schätze ich.

**Comment by dagochen** [comment]
Jo das stimmt, zumal solche level-bezogenen Lootgruppen von Items zwischen Stufe 40-45 und 45-50 etc....bereits existieren...sogar noch unterteilt nach green, blues und epixxx :)

**Comment by Karmanaz** [comment]
Gibt es hier schon etwas neues? Die Rare Mobs tragen doch durchaus zum Classic Feeling bei.

**Comment by dagochen** [comment]
Naja so lange Rare Mobs normale Spawnzeiten haben und nicht wirklich Rare sind, sollte hier nix geändert werden, da es sonst zu lukrativ wird. Würde auf das gleiche Problem hinauslaufen wie bei der Elementaren Invasion, die bis heute leider nicht korrekt implementiert wurde....
