### ISSUE TITLE
Massige Goldvorkommen

### ISSUE THREAD

**Issue by thrallsblood** [ClassicWoW/Nefarian_1.12.1_Bugtracker#789]
Hallo,

Welches Verhalten wird beobachtet?
Goldvorkommen spawnen massenhaft an allen Spawnpunkten, an denen es ihnen möglich ist.

Wie sollte es sich verhalten?
Die Goldvorkommen sollten nur an verschiedenen Spawnpunkten spawnen und nicht an jedem Sapwnpunkt an dem die möglichkeit besteht -> Dauerhaft sollten weniger Goldvorkommen zur verfügung stehen, da es z.B. im Steinkrallengebirge im Tal der Verbrennung mehr Gold als sonst irgendwas gibt..

Schritte zur Reproduzierung
1-2 Goldvorkommen (im Beispiel Tal der Verbrennung) spawnen lassen, allerdings an verschieden möglichen Punkten.

Danke für eine Antwort ;)

**Comment by Larnak1** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/694
