### ISSUE TITLE
Schließkassetten und das Handelsfenster

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#790]
Laut letzten Patchnotes vom 6.6.2015 kann man jetzt Schließkassetten über das Handelsfenster öffnen. Der Vorgang wird korrekt ausgeführt, allerdings ist die Schließkassette immernoch verschlossen. Sie kann auch erneut nicht über das Handelsfenster geöffnet werden (Fehlermedlung: ist schon offen). Normales traden und manuelles Öffnen im Inventar funktioniert dann.

Getestet mit zwei verschiedenen Spielern.

**Comment by nightblizard** [comment]
Nicht reproduzierbar. Siehe:
https://youtu.be/rWP9e3A3cLQ

**Comment by g3n3a** [comment]
Hat sich nur auf Thoriumkassetten erstreckt? Die hab ich nämlich überprüft (ingesamt 4 Stück).

**Comment by nightblizard** [comment]
Kann ich dir nicht sagen, das habe ich nicht geprüft, aber ich habe es so behoben, dass das für alle Kassetten gilt.
