### ISSUE TITLE
Hexer widersteht eigenem Seelendieb

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#796]
Hallo!
Seit einem der letzten Updates (schon vor dem 06.06.) können Hexenmeister ihrem eigenen Seelendieb Spell widerstehen, wenn sie versuchen damit einen Soulshard zu ziehen.
<a href="http://s923.photobucket.com/user/WosserBijerd/media/Seelendieb.jpg.html" target="_blank"><img src="http://i923.photobucket.com/albums/ad76/WosserBijerd/Seelendieb.jpg" border="0" alt=" photo Seelendieb.jpg"/></a>

http://datenbank.welli-it.de/?spell=11675
http://datenbank.welli-it.de/?spell=8289
http://datenbank.welli-it.de/?spell=8288
http://datenbank.welli-it.de/?spell=1120

**Comment by Slimmer2** [comment]
Ist auch nur ein Cast der widerstehen kann.
