### ISSUE TITLE
Erdungstotem buggy (wichtig für pvp)

### ISSUE THREAD

**Issue by Feddebla** [ClassicWoW/Nefarian_1.12.1_Bugtracker#797]
Hallo Serverteam,

folgendes Problem tritt beim Erdungstotem auf:

Das Erdungstotem verschwindet nicht, obwohl schon 1x sheepen (oder Counterspell) reingegangen ist. Es gehen weitere Casts in dieses Totem, obwohl es nach dem ersten Cast verschwinden müsste.

Fürs PVP wäre dieser Fix sehr wichtig.

Gruß, Fedde

**Comment by wahaxlekuke** [comment]
Quelle? Datenbank-Links?

**Comment by MukiDaBoss** [comment]
Kann geschlossen werden, da der Autor sich offensichtlich überhaupt nicht mit der Mechanik des Totems auseinandergesetzt hat.
".. das alle 10 Sekunden einen schädlichen Zauber, der auf ein in der Nähe befindliches Gruppenmitglied gewirkt wurde, auf das Totem umleitet"
Mit dem richtigen Timing kann man innerhalb von drei Sekunden bis zu drei Spells eines unwissenden, geflaskten, overgearten Feuermages auf das Totem umleiten. :-) soll so sein und ist blizzlike.
