### ISSUE TITLE
[Hexer] Zauber "Lebenslinie"(Rang 1)

### ISSUE THREAD

**Issue by usrmx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#799]
Hallo,

laut Tooltip sollte der Zauber meinem Pet 12 Gesundheit/Sekunde geben und mir einmal 11 Gesundheit abziehen, und während dem kanlisieren 5 Gesundheit/Sekunde abziehen.

Problem: Der Zauber zieht mir 12 Leben/Sekunde ab. 

Bis jetzt steht mir nur Rang 1 zur Verfügung, ich kann darum nicht sagen, ob die höheren Ränge funktionieren.

Zauberlink: http://datenbank.welli-it.de/?spell=755

**Comment by wahaxlekuke** [comment]
Lebenslinie skaliert nun auch nicht mehr mit +Heal-Equip, weil das erst in BC kam.
> Patch 2.0.3 (09-Jan-2007): Now scales with equipment.
