### ISSUE TITLE
Zerhäckseln des Schurken

### ISSUE THREAD

**Issue by DreamRogue** [ClassicWoW/Nefarian_1.12.1_Bugtracker#800]
Welches Verhalten wird beobachtet?
Zerhäckseln des Schurken wirkt nicht ordnungsgemäß

Wie sollte es sich verhalten?
Ein 5CP Zerhäckseln das noch bspw. 25 sek läuft kann nicht von einem 1CP Zerhäckseln überschrieben werden, sondern erst wenn das "neue Zerhäckseln" eine länger Zeit laufen würde als das gerade aktive

Schritte zur Reproduzierung
Schurke erstellen -> ausprobieren

Zusätzliches
Da es keine Möglichkeit gibt zu sehen wie etwas nicht aktiviert wird (da Zerhäckseln nicht aktiviert werden konnte während noch eines gelaufen ist was länger hält) gibt es leider kein Video

**Comment by Slimmer2** [comment]
Macht ein 5 Combopunkt Zerhäckseln nicht mehr Schaden als ein 1 Combopunkt?
Somit wäre auch ein Stärkerer Zauber Aktiv den man nicht überschreiben kann.

**Comment by wahaxlekuke** [comment]
Bitte immer noch Links aus der Datenbank hinzufügen:

**Comment by Slipru** [comment]
Ich finde es wichtig zu fixen
