### ISSUE TITLE
NPC-Movementsystem[Probleme mit Terrain]

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#802]
Im Gegensatz zum Offiziellen Server suchen sich Mobs auf unserem Server nicht immer den Weg zum Ziel sondern tendieren dazu, einfach stehen zu bleiben und nach gewisser Zeit zu evaden, selbst wenn es einen Weg zum Ziel geben würde.

Dieser Bug kann z.B. bei Lord Incendius abused werden, um ihn zu 2. oder als Klasse mit einem Pet fast ohne Gegenwehr zu töten.
(Spieler 1 stellt sich an "unerreichbare" Stelle(1) und greift den Mob an. Spieler 2 stellt sich in einiger Entfernung zum Mob auf und wirkt etwas dass kaum Aggro erzeugt aber ihn auf die Aggroleiste des Mobs bringt. Evaded der Mob nun Spieler 1 und rennt zu Spieler 2, so kann Spieler 1 von seiner Position aus die Aggro zurück erlangen. Der Mob versucht wieder Spieler 1 zu erreichen. Evaded wieder, rennt zu Spieler 2 -> und so weiter.)
Beweisvideo kann ich wenn von einem Dev verlangt gerne machen.

(1) Eine Stelle die der Mob nur mit erheblichen Movementaufwand erreichen könnte -> z.B. oben auf dem Geländer in genanntem Beispiel

Andererseits sind dadurch Mobs schwerer als sie sein sollten, da sie unnötig evaden/Spieler aus der Aggroliste kicken. Namendliche Vertreter hiervon wären sämtliche NPC's mit Knockback und/oder Charge ability (Lavawoger)

So sieht etwa der Sollzustand aus:
https://youtu.be/2JCusIVD0KU?t=178
https://youtu.be/mtdik-lF1ik?t=20
https://youtu.be/O7bHOv9UCo0?t=472
Sorry dafür dass es alles Huntervideos sind, aber Krieger, die Mobs zu tode kiten gibts leider so wenige :-D

Istzustand:
Mobs evaden beim Nachstellen dieser Positionen und ähnlicher Stellen oder der Spieler landet gar nicht auf ihrer Aggroliste (Cho'Rush der Beobachter)

EDIT: Der Istzustand ist selbstverständlich nur in Instanzen fehlerhaft, in der offenen Welt stimmt das NPC-Verhalten

**Comment by Gnomorus** [comment]
Das ganze geht z.B. auch in Scholo, wenn ein Gruppenmitglied gleich zu Beginn der Instanz von der Brücke in den Raum mit den kranken Ghoulen springt und die restlichen von oben runterschießen.

**Comment by Haudraufinix** [comment]
Ich stups den Beitrag mal an, da er für Jäger extrem viel vom classicfeeling zerstöhrt!

Wahaxlekuke meinte mal, das wäre einfach nen Distanzwert für die Verfolgung, den man hochstellen müsste.

**Comment by Haudraufinix** [comment]
close

**Comment by Haudraufinix** [comment]
>close

**Comment by Haudraufinix** [comment]
Undokumentiert aber scheint behoben zu sein.
