### ISSUE TITLE
Kürschner Bug 

### ISSUE THREAD

**Issue by mighty2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#803]
Die Mobs Träumender Welpe und Halbwüchsiger Welpe in den Sümpfen des Elends lassen sich nicht kürschnern. Nach dem looten wird mir immer noch das glitzern angezeigt, obwohl nix mehr drinne ist.
Komme nicht an die Grünwelpenschuppen ran, die ich für die Kürschner VZ auf Handschuhe brauche.
WDB Ordner habe ich gelöscht und relogg gemacht.
Pls Fix.

**Comment by mighty2** [comment]
wenn ich allerdings einen Welpen töte, und danach ALT f4 drücke, kann ich diesen nach dem neustart des Spiels kürschnern. Vielleicht hilft euch das weiter

**Comment by dagochen** [comment]
Wurde schon reportet. https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/468

**Comment by mighty2** [comment]
Allerdings sind diese hier auch NICHT kürschnerbar WENN sie gegenstände dabei haben, also garnicht. Nur mit relogg

**Comment by mighty2** [comment]
Hab die Schuppen aufjeden Fall bekommen durch ständiges reloggen. :)
