### ISSUE TITLE
Totem-Skills im Verstärkerbaum fehlerhaft

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#804]
Skillt man die Totems im Verstärkerbaum geben diese nicht wie angegeben die entsprechenden Prozentzahlen mehr Boni auf z.B. Stärke und Beweglichkeit.

Im Zauberbuch ändert sich die Anzeige zwar, aber die Boni bleiben ohne Wirkung. 

Z.B sollte StärkeTotem 70 statt 61 geben...es bleibt aber bei 61  ..Bewegl. 77 statt 67.

Diesbezüglich würde ich darum bitten, die Mechaniken der Windfury und Flammenzungetotem-Skills auch zu überprüfen, da diese ja mit Skills genauso verbessert werden können. 

Besten Dung und Grüße

Frost

**Comment by hraesvelgr** [comment]
http://datenbank.welli-it.de/?search=enhancing


trifft das auch auf die beiden zu?
http://datenbank.welli-it.de/?spell=16258
http://datenbank.welli-it.de/?spell=16293

**Comment by Frostlatte** [comment]
Die habe ich vergessen, kann ich aber überprüfen und werde berichten.

Wo es schwierig wird zu testen, ist dieser:

http://datenbank.welli-it.de/?spell=29192
http://datenbank.welli-it.de/?spell=29193

da sie nicht in der Buffliste mit den entsprechenden AP / Flammenzunge-Werten angegeben werden.

**Comment by wahaxlekuke** [comment]
Zumindest die Totems, die plus Beweglichkeit und Stärke geben funktionieren korrekt. Stoneskin Totem funktioniert nicht. Den Rest hab ich bisher noch nicht getesetet.

**Comment by wahaxlekuke** [comment]
Ok hab mich geirrt auch das Talent für das "Stoneskin Totem" verstärkt den Effekt. Alle Talent die Totems verstärken funktionieren korrekt. Bei dem Windfury-Totem Sieht man sogar für einen kurzen Moment im Charakterfenster, wie die Angriffskraft erhöht wird.

**Comment by Frostlatte** [comment]
Um die Sache abzuschließen... der oben beschriebene Fehler ist also nur ein AnzeigeBug?

**Comment by wahaxlekuke** [comment]
Der tooltip von den Fähigkeiten ist richtig. Nur die Buffs zeigen die ungeskillten Werte an.

**Comment by Frostlatte** [comment]
kk, danke  :)
