### ISSUE TITLE
Taerars Schemen: Modellskalierung fehlerhaft

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#805]
**Welches Verhalten wird beobachtet?**

Taerars Schemen sind genauso groß wie der Boss Taerar selbst.

**Wie sollte es sich verhalten?**

Taerars Schemen sollten ungefähr um den Faktor 0,33 bis 0,5 kleiner sein als der Boss Taerar selbst.

**Schritte zur Reproduzierung**

Taerar auf 75%,50%,25% hauen.

**Zusätzliche Informationen**

Taerar Video aus 2006: https://www.youtube.com/watch?v=bAAt7w1T5Jw

**Links aus unserer Datenbank**

Shade of Taerar: http://datenbank.welli-it.de/?spell=24841
Shade of Taerar: http://datenbank.welli-it.de/?spell=24842
Shade of Taerar: http://datenbank.welli-it.de/?spell=24843

**Comment by Larnak1** [comment]
Nice! Dann sieht man da auch mal was anderes außer Flügel...
