### ISSUE TITLE
Schamane, Windfury kann Windfury auslösen!(momentan buggy)

### ISSUE THREAD

**Issue by Lunte1** [ClassicWoW/Nefarian_1.12.1_Bugtracker#806]
Das es nicht geht! Darin besteht zurzeit ein Fehler im Spiel.

Wie bereits im Schamanen Klassenforum angesprochen konnte damals zu classic Zeiten Windfury einen erneuten Windfury proc auslösen! Ca 20% auf jeden White Hit (auch die von WF).

WF bekam erst mit Einführung von BC einen internen cd von 3 Sekunden! Da Dual Wield Fähig...
http://eu.battle.net/wow/de/forum/topic/7101270224 (Post 2, Abs. 2)

Fangt bloß nicht an in PvP Videos danach zu suchen.. Soweit kam es meistens nicht!^^
Ich bin mir 10000% sicher das es dazu nen passenden Blue Post kam, Sommer 2005!
Meine 2 PvP StammgruppenLeader waren beides Enhancer, darüber wurde mehrere Wochen vorher drüber diskutiert.... Leider ist dieser unauffindbar!

Stehe bei Rückfragen jederzeit zur Verfügung

Lunte

**Comment by Haudraufinix** [comment]
Nette Quelle - Nicht

Patch 1.4.0 (2005-05-05): Fixed a bug that caused an additional attack beyond what was intended. In addition, fixed a bug that caused the next normal melee attack to happen sooner than intended.
wäre u.U. dein besagter doppelprocc - wurde zu 1.4 entfernt
http://wowwiki.wikia.com/Windfury_Weapon

**Comment by Lunte1** [comment]
Käse zum Whine?

wiki.. Eben selbst geschrieben?

Und wir haben 1.12? und nicht1.4?

**Comment by Haudraufinix** [comment]
This just made my day!

**Comment by hmmkay** [comment]
Warum hast du denn nicht selbst das Wiki verlinkt, wenn es vorher (deiner Meinung nach) dort anders stand? :D 
Da steht ja eindeutig, dass es nicht ging ;)

**Comment by Lunte1** [comment]
Eben mit nem alten PvP kollegen gesprochen! Der ist sich auch sicher das das funktionierte...

**Comment by wahaxlekuke** [comment]
Ich denke nicht, dass es mit Patch 1.12 noch möglich war. In einem Foren-Sticky-Post am 26.5.2006 stand:
> 4.10 Can the extra hits from Windfury proc another Windfury proc? 
The answer here is almost 100% no. This question is one of many advanced questions attempted to be answered in Vehementi's thread here: http://forums.worldofwarcraft.com/thread.aspx?fn=wow-shaman&t=42555 

https://web.archive.org/web/20060526100242/http://forums.worldofwarcraft.com/thread.aspx?fn=wow-shaman&t=26616&p=1&tmp=1#post26616

**Comment by Lunte1** [comment]
"Elementarwaffen: Erhöht den Nahkampfangriffskraftbonus Eurer Waffe des Felsbeißers um 7%/14%/20%, den Effekt Eurer Waffe des Windzorns um 13%/27%/40% und den Schaden Eurer Waffe der Flammenzunge und Waffe des Frostbrands um 5%/10%/15%.
Der DPS-Bonus für Windfury ist nur 11,4%, da ja nur 2 von 7 Schlägen den AP-Bonus bekommen. Trotzdem gibt es keine Alternative für Enhancer, vor allem wenn sie an Sturmschlag kommen wollen. "

Hier Spricht er auch von 7 Schlägen! Ergo wenn WF WF auslöst..

Link: http://wow-mow.de.tl/Shamanen-Guide.htm

**Comment by Haudraufinix** [comment]
Ich kann dir Sagen wie der auf 7 Schläge kommt. Jeder Angriff hat die Chance von 20% auf ZWEI Zusatzschläge.
100% / 20% = im Schnitt also Fünf(5) Schläge bis du Zwei(2) Zusatzschläge auslöst. Ergo lerns, wenns passiert dann ist es ein BUG und definitv nicht so Beabsichtigt, Hol dir ne gescheite Waffe wenn du Spass im PvP haben willst

**Comment by Lunte1** [comment]
http://eu.battle.net/wow/de/forum/topic/14899613720#1

**Comment by wahaxlekuke** [comment]
> Und wir haben 1.12? und nicht1.4? 

Nur um das mal klar zu stellen: Patch 1.12 kommt NACH 1.4
Der Patch hat die Nummer 1.12, weil es der 12. große Classic-Patch war. Das sollte man nicht mit Patch 1.1.2 verwechseln.

**Comment by Haudraufinix** [comment]
Da du den ganzen Schmock parallel im Forum und hier betreibst -> Fragen zur Glaubwürdigkeit des Videos im Forenthread

**Comment by Lunte1** [comment]
Du behauptest nach wie vor das Wf nen internen cd hat, was Käse is! 

Frag da mal nach deiner Glaubwürdigkeit... :)

Push!

**Comment by Haudraufinix** [comment]
Ich hab genau so viel Erfahrung als Schami wie du. Ausserdem hab ich bis jetzt mindestens genau so viele aussagekräftige Beweise geliefert wie du. Der wesendliche unterschied zwischen uns ist; Ich will nichts ändern. Daher ist MEINE Glaubwürdigkeit komplett irrelevant. Du hingegen willst etwas ändern, daher müssen dir die Developer glauben, dass die Änderung berechtigt ist.

Bis jetzt waren deine Beweise in dieser Hinsicht an den Haaren herbeigezogener Nonsense.

**Comment by Sabbaer** [comment]
nein, so ist das nicht lieber haudraufinix. Am paladin wurden mehrere signifikante änderungen ohne einschlägige beweise vorgenommen! daher stehst du genauso in der beweispflicht wie er
