### ISSUE TITLE
Taerar: Ist in den 25% Phasen zu kurz inaktiv

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#807]
**Welches Verhalten wird beobachtet?**

In den 25% Phasen von Taerar ist er kürzer als 180s inaktiv. (Oder meine Wahrnehmung täuscht mich schon sehr.)

**Wie sollte es sich verhalten?**

Taerar sollte auf jeden fall mehr als 120s, laut Kommentar im 1. Video sogar 180s inaktiv sein.

**Schritte zur Reproduzierung**

Taerar auf 75%,50%,25% hauen.

**Zusätzliche Informationen**

Taerar Video aus 2006 inkl. Kommentar mit 180s: https://youtu.be/gClfDG_vN6E?t=44
Taerar Video, in dem das Töten der Shemen ca 120s dauert und Taerar nach dem Tod des 3. Schemens wieder kommt: https://www.youtube.com/watch?v=R8C2SVRGEXE

**Links aus unserer Datenbank**

Taerar: http://datenbank.welli-it.de/?npc=14890

**Comment by ircfelix** [comment]
Mir ist noch was aufgefallen:

**1.) Die Schemen sind zu groß**
Die Schemen sind laut dem Video aus http://community.mmobase.de/hilfe-und-support/6998-sammelthread-alte-wow-videos.html viel zu groß. In dem Video sieht man ganz deutlich, wie klein die Dinger eigentlich sind.
> https://www.youtube.com/watch?v=ot3-SH-zU7g

Dass die Schemen so groß sind, macht das ganze sehr unübersichtlich.

**Comment by Gnomorus** [comment]
siehe #805 :D
