### ISSUE TITLE
Arkane Geschoss

### ISSUE THREAD

**Issue by Buuhuu90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#808]
Arkane Geschoss schießt weiterhin auf das Ziel selbst wenn es außer Sichtfeld ist (hinter Objekte ist)
Wie es sein soll: 

Sobald Target außer Sichtfeld ist müsste die Kanalisation abbrechen.

**Comment by Gnomorus** [comment]
Stimme dafür, Arkane Geschosse aus dem Spiel zu entfernen. Die machen nur Ärger...

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/128

**Comment by Buuhuu90** [comment]
Patch 2.0.3 (09-Jan-2007): Mages will no longer see line of sight errors if the target moves behind an obstacle after the spell "Arcane Missiles" has begun casting.; "Arcane Missiles" will no longer continue to channel after the target is dead.

Quelle: http://wowwiki.wikia.com/Arcane_Missiles

Da dies erst zu einem späteren Zeitpunkt gefixt worden ist, ist es nicht legitim zu unserem Patchzustand

**Comment by Slimmer2** [comment]
Steht doch eindeutig da "
•Magier erhalten nicht mehr die Fehlermeldung 'Ziel ist nicht im Sichtfeld', wenn sich das Ziel hinter ein Hindernis bewegt, nachdem der Magier begonnen hat, 'Arkane Geschosse' zu wirken."
Fehlermeldung und nicht der Zauber bricht ab wenn außer Sicht Feld läuft

**Comment by Buuhuu90** [comment]
falls ich mich falsch tu dann verzeiht mir. Aber ich bin immer noch der Meinung das wenn du hinter einem Haus bist, der die dicke des Pentagons hat, das dies dann abbricht. Aber egal :) trotzdem danke

**Comment by Gnomorus** [comment]
Die o.g. Patchnotes von 2.0.3 in Kombination mit den in #128 genannten von 2.3.0 zeigt aber eindeutig, dass die arkanen Geschosse abbrechen sollten. Aber wie so oft: what shalls...
