### ISSUE TITLE
Windfuror Procc-Chance geändert / beeinflusst?

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#809]
Einigen Schamanen der Hordenseite ist aufgefallen, dass die ProccChance der WindfurorVerzauberung seit der letzten Schamanenänderung merklich gesunken ist.

http://datenbank.welli-it.de/?spell=16362

 
Jetzt kann man natürlich sagen, dass es die 20% Zufallsrate ist, aber mehrere Schamanen haben die gleiche "subjektive" Wahrnehmung.

Wurde da etwas geändert...oder ist es möglich, dass die ProccChance durch eine der Änderungen beeinflusst wird?

Vielleicht können ja andere Schamanen diesen Eindruck bestätigen o. widerlegen.

MfG

Frost

**Comment by wahaxlekuke** [comment]
An dem Zauber bzw. der Proc-Chance wurde nichts geändert. Wenn Ihr trotzdem das Gefühl habt, da stimmt was nicht, macht erstmal eine aussagekräftig Stichprobe.

**Comment by Frostlatte** [comment]
Alles klar, danke für die Antwort.

Was für eine Probe schwebt Dir vor?  Auszählen der Proccs vs Anzahl der Schläge?

Hast Du da vlt einen AddonTipp, welches das ggf auszählt?

Beste Grüße

Frost

**Comment by SirBeansen** [comment]
procc watch sollte es können einfach im raid laufen lassen.

**Comment by Frostlatte** [comment]
Nach einigen Tests ist mir aufgefallen, dass scheinbar der Stormstrike kein WF mehr auslöst. 
Jetzt kann man argumentieren, dass es bisher unglücklich lief, aber ich habe gestern im BWL Raid nich einen WF Procc erlebt..auch heute bisher nicht. 

Kann es evtl sein, dass das mit dem Verfehlenchance-Fix zu tun hat?

Was beobachten andere Stormstrike Nutzer?

**Comment by Frostlatte** [comment]
@Beansen: Ist das Addon im Pack dabei?

**Comment by muzikk** [comment]
Habe auch einige Tests bezüglich Stormstrike -> WF Procc angestellt (1 MC Run, mehrere BGs, Solo 30min lang Mobs getötet und dabei ca. 70-80x Stormstrike benutzt) und habe auch kein einziges Mal beobachten können, dass Stormstrike einen WF Procc auslöst.
