### ISSUE TITLE
Global cooldown und Instantzauber, die keinen GCD auslösen sollten

### ISSUE THREAD

**Issue by wowtom** [ClassicWoW/Nefarian_1.12.1_Bugtracker#810]
Der GCD sollte 1,5 Sekunden lang mit einigen Ausnahmen. Siehe Quelle
2. Es gibt Instantzauber, die keinen GCD auslösen sollen, es hier aber offenbar tun. Siehe Quelle und unsere Datenbank
3. Der GCD ist ein serverseitig ausgelöstes Script, auf diesem Server wird er anscheinend fälschlicherweise für jeden Zauber ausgelöst. Für Instantzauber ist er auch vorhanden, wenn auch keine 1,5 Sekunden. Genau das sollte nicht sein.
wie sollte es sich verhalten? Instantzauber sollten keinen GCD auslösen. "Another action is in progress" darf nicht auftreten.

Solche Macros waren zu Classic und auch noch zu TBC Patch 2.4.3 - in geänderter Schreibweise - möglich und üblich
/script CastSpellByName("Instantzauber1");SpellStopCasting();CastSpellByName("Instantzauber2");SpellStopCasting();UseInventoryItem(xy);SpellStopCasting();CastSpellByName(Zauber mit GCD)

Quellen:
Gamepedia zum Cooldown (ein wiki) vom 01.02.2008, das älteste, was ich gefunden hab: [url=http://wow.gamepedia.com/index.php?title=Cooldown&oldid=1179140]Cooldown - Wowpedia - Your wiki guide to the World of Warcraft[/url]
wowhead.com zur Länge des GCD: [url=http://www.wowhead.com/spell=61304/global-cooldown]Global Cooldown - Spell - World of Warcraft[/url]

**Comment by dagochen** [comment]
Wenn du jetzt noch ein paar konkrete Zauberkombinationen angibst, kann man das auch versuchen zu reproduzieren. Bisher weiß niemand, um welche Zauber und Items es sich handelt.

**Comment by hmmkay** [comment]
Gibt hier einige Spells, die keinen GCD auslösen. Beispiel: Instantheal vom Druiden mittels 2 Zaubern (Schnelligkeit der Natur + beliebiger Heilzauber).

**Comment by Slimmer2** [comment]
http://wow.gamepedia.com/index.php?title=Cooldown&oldid=1179140
Ist der älterste Beitrag, aber von Heal steht da nichts drin, sondern das [Nature's Swiftness] nur kein GCD hat

**Comment by wahaxlekuke** [comment]
Das Ticket ist zwar nicht 100% korrekt, aber ich hab es trotzdem erstmal so geändert, dass alte Classic-Makros, die man auf wowwiki/wowpedia findet, funktionieren.
