### ISSUE TITLE
Rüstung der Distelelementare

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#814]
Mich deucht, dass sie folgenden NPCs in Tanaris keine oder nur minimale Rüstung besitzen. Ich schätze mal, dass das nicht beabsichtigt ist.
Distelwurzelformer (http://datenbank.welli-it.de/?npc=5485)
Knorriger Distelwandler (http://datenbank.welli-it.de/?npc=5490)
Disteltausammler (http://datenbank.welli-it.de/?npc=5481)

Wollen ja nicht, dass eine der nervigsten Quests in Classic-WoW zu einfach wird ;P

Korrektur: Knorriger Distelwandler (http://datenbank.welli-it.de/?npc=5490) scheinen adäquate Rüstung zu besitzen.

**Comment by dagochen** [comment]
Quelle?

**Comment by Gromnir** [comment]
Die Datenbank zeigt zumindest bei den Distelwurzelformer und den Disteltausammler kein Rüstungswert rechts in der Kurzübersicht an. Und mir ist es nicht bekannt, das Mobs keine Rüstung haben sollten, weshalb die Meldung schon richtig ist.

**Comment by Haudraufinix** [comment]
Richtig ist es definitv nicht, als Melee kannste die beim leveln two shoten - wie viele andere Mobs ohne Rüstung auch, bloss QUELLE is der Knackpunkt. sonst fixen wir von bad to worse

**Comment by g3n3a** [comment]
ANgeblich soll in dem Bestarium zu WoW Rüstungswerte drinstehen und Mobs.
