### ISSUE TITLE
Leere Kräuterspawns

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#815]
Welches Verhalten wird beobachtet?
Beim looten mancher Kräuter geht ein leeres Lootfenster auf.

Wie sollte es sich verhalten?
Es sollten 1-3 Kräuter lootbar sein und das Kraut sollte despawnen wenn es leer ist.

Schritte zur Reproduzierung:
Kräuter looten mit dem Beruf "Kräuterkunde". (hatte gerade eben in azshara ca. 4 leere Kräuter gefunden )

**Comment by Slimmer2** [comment]
Das liegt eher daran das die Kräuter wieder nicht immer Despawnen wenn man sie abgebaut hat.

**Comment by Sheed90** [comment]
Seit der fix für Teufelsunhold aufgespielt wurde, tritt das Problem deutlich seltener auf.

Gruß
