### ISSUE TITLE
pet verschwunden

### ISSUE THREAD

**Issue by rschinkoeth** [ClassicWoW/Nefarian_1.12.1_Bugtracker#817]
Welches Verhalten wird beobachtet?
Beim talente verlernen und neu speccen verschwindet das pet. wechselt man das pet direkt danach beim stablemaster (zb um pvp zu machen) ist das originale pet weg. auch nicht beim stablemaster zu sehen.

Wie sollte es sich verhalten?
das pet sollte erhalten bleiben.

Schritte zur Reproduzierung:
vermutlich:
umspeccen, "verschwundenes" pet NICHT rufen.
zum stablemaster gehen, anderes pet herausholen
altes pet ist weg.

mehr kann ich nicht sagen, mir ist es erst aufgefallen als ich mein pvp pet vom stablemaster geholt habe.
ist auch das erste mal in ~30 mal umspeccen dass das passiert.
dass mein wolf weggelaufen ist ist auszuschließen, er war vor dem weglaufen grün gefüttert.

**Comment by dagochen** [comment]
Tier rufen, dann ist es wieder da.

**Comment by rschinkoeth** [comment]
das problem ist, dass mir das erst auffiel nachdem ich mein pvp pet vom stablemaster geholt habe. dh ich habe jetzt mein pvp pet, mein lupos ist nicht im stable master und ergo futsch.

**Comment by rschinkoeth** [comment]
ist NICHT gefixed. habe nun extra vorsicht walten lassen beim umspeccen. ist man in der welt unterwegs, das pet tot, und man geht umspeccen, ohne es vorher zu rufen, wiederzubeleben und wegzupacken despawnt es immer noch beim stablemaster... zum glück war es diesmal "nur" das pvp pet (59 fledermaus aus zg..)

**Comment by dagochen** [comment]
doofer bug, ja, aber einfach immer dafür sorgen, das es neben dir steht, wenn du zum stallmeister gehst. so schwer kann das doch net sein :)

**Comment by rschinkoeth** [comment]
ich habe jetzt 2 wochen jeden tag aufgepasst. vor ner woche gesehen dass es gefixt wurde, trotzdem aus gewohnheit weiter gemacht. gestern nicht drangedacht, "aber ist ja fixed".
man ist halt mal aus versehen unachtsam. und wäre es nicht so blöd pets nachzuleveln mit treuestufe usw würde ich deswegen auch nicht so nerven.

**Comment by dagochen** [comment]
Hab letzte Nacht beim Pet durchwechseln auch folgende Beobachtung gemacht, vielleicht kriegt es noch wer hin: Wenn man oft hin und her wechselt, sind irgendwann in allen 3 Petslots das gleiche Pet, die anderen 2 werden nicht mehr angezeigt. Gibt man das aktuelle Pet frei und ruft es wieder, ist es eins von den anderen 2. Auf diese Weise lassen sich die anderen 2 "wiederherstellen", bis im Stallmeister wieder alle 3 richtig angezeigt werden.
