### ISSUE TITLE
Onyxia Flugphase

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#819]
Welches Verhalten wird beobachtet?
Während der Flugphase können Nahkämpfer durchgehen Schaden machen.
Tiefer Atem macht zu wenig schaden.

Wie sollte es sich verhalten?
Nahkämpfer sollten nur an den erhöhten stellen Schaden machen und da müssen sie Springen.
Tiefer Atem sollte Spieler bis zu 6 mal Innerhalb kurzer Zeit treffen, Um den Schaden zu vermeiden muss man sich am Rand stellen

Schritte zur Reproduzierung:
Onyxia bis zur Flugphase bringen und abwarten

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://youtu.be/ZpSPHPXSl2g
https://www.youtube.com/watch?v=VYImqV1Riww
http://wowwiki.wikia.com/Onyxia_(original)

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?npc=10184

**Comment by Larnak1** [comment]
Das mit den Nahkämpfern kann ich anhand deines ersten Videos nicht nachvollziehen, da sieht man bei 4:10 mehrere ganz gemütlich vom Boden aus draufhauen.

**Comment by ircfelix** [comment]
Fehlt nicht auch die Fluganimation?
