### ISSUE TITLE
Meister der Arena loot Bug

### ISSUE THREAD

**Issue by Nexxonus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#82]
Ich habe jetzt schon mehrmals die Truhe in der Schlingendorntaler Arena geöffnet allerdings bekam ich nur beim 1. mal das Schmuckstück Meister der Arena. Nachdem ich ein Ticket geschrieben habe wurde mir gesagt, dass das Schmuckstück Meister der Arena nur droppt wenn man die Quest die man auf dem Schmuckstück findet nicht annimmt! Das Heißt wenn ihr das Schmuckstück bekommt und es noch öfter wollt (um bsw. Großmeister der Arena zu werden) dürft ihr die Quest nicht annehmen! Bzw erst dann wenn ihr alle habt, die ihr braucht (bei Großmeister z.b. sind es 12).

Wenn ihr die Quest angenommen habt und lootet die Truhe, findet ihr den Normalen Loot drin. Auch das Schmuckstück ist Theoretisch drin nur könnt ihr es nicht looten oder sehen. Die Truhe verschwindet dann nicht. Erst wenn sie jemand lootet der die Schmuckstück Quest noch nicht angenommen hat.

**Comment by ataniker** [comment]
Bitte fixen, ist wirklich ärgerlich wenn man die Quest abgegeben hat und man keine 11 mehr für die verbesserte Version bekommen kann.

**Comment by emgmaege** [comment]
Hallo liebes Classic Team.
Der Fehler ist leider noch nicht behoben.

Server-Version:
 1.0.5

Beschreibung:
Nach beginn der Quest können keine weiteren [Meister der Arena]-Items gelootet werden.
Gibt es eine Möglichkeit die Quest abzubrechen, die 12Stk. zu sammeln und dann abzugeben?

Links:
http://datenbank.welli-it.de/?quest=7838


 Vielen Dank,
 hoffe auf baldige Rückmeldung

**Comment by Slipru** [comment]
Huhu ich war eben das erste mal in der Arena und habe das Questitem gelootet, aber ich kann die Quest nicht annehmen ( bin lvl 60 ).
Als Fehler steht da "Ihr erfüllt die Anforderung für diese Quest nicht"
