### ISSUE TITLE
Schamanen Geisterwolfgestalt Tempobonus fehlt

### ISSUE THREAD

**Issue by muzikk** [ClassicWoW/Nefarian_1.12.1_Bugtracker#821]
Welches Verhalten wird beobachtet?

Das Item Panzerschienbeinschützer des Blutgardisten (http://datenbank.welli-it.de/?item=22857) erhöht die Geschwindigkeit des Schamanen in Geisterwolfgestalt nicht. Auch die Beschreibung des Geisterwolfbuffs besagt "Erhöht Bewegungstempo um 40%.". 

Wie sollte es sich verhalten?

Durch das Item sollte die Geschwindigkeit des Geisterwolfs auf 55% (40% Grundgeschwindigkeit + 15% Bonusgeschwindigkeit) erhöht werden. Auch in der Mouse-Over-Beschreibung des zugehörigen Buffs sollten diese 55% angegeben sein.

Schritte zur Reproduzierung

http://datenbank.welli-it.de/?item=22857  als Schamane anlegen und die Geisterwolfgeschwindigkeit mit derjenigen vergleichen, die bei nicht angelegtem Gegenstand erkennbar ist (-> kein Unterschied).

Links aus unserer Datenbank

Panzerschienbeinschützer des Blutgardisten: http://datenbank.welli-it.de/?item=22857

**Comment by Larnak1** [comment]
"Auch in der Mouse-Over-Beschreibung des zugehörigen Buffs sollten diese 55% angegeben sein."
Das funktioniert glaube ich bei keinem Buff, war aber in Classic glaube ich auch so.

**Comment by Haudraufinix** [comment]
Wurde zu classic nicht angezeigt, aber du müsstest cirka gleich schnell sein wie Spieler aufm Non Epic Mount

**Comment by ircfelix** [comment]
Oder zwei Schamis (einer mit Set und einer ohne) machen ein Wettrennen!?!?

So wird selbst ein Bugreport zum Spaß für die ganze Familie!

**Comment by muzikk** [comment]
Doch, die Mouse-Over-Beschreibung hat mal korrekt funktioniert. Dann kam das Update am 14.04.2015 (http://community.mmobase.de/updates-changelog/6913-patchnotes-14-04-2015-a.html) , mit dem u.a. folgendes behoben wurde: 

"- Es sollte weniger oft vorkommen, dass man nach dem Benutzen von Blinzeln, Reisegestalt, Aspekt des Geparden oder ähnlichen Effekten zurückgesetzt wird. "

Ich nehme ganz stark an, dass der Geisterwolf Bug damit zusammenhängt. Seitdem werden weder die 55% angezeigt, noch ist man auch in Wirklichkeit 55% schnell.

Habe das selber getestet mit an- und abgelegtem Item und es ist kein Unterschied feststellbar. Auch zu anderen Schamanen in Geisterwolf, die das Item nicht haben, sehe ich keinen Unterschied.

**Comment by nightblizard** [comment]
Gerade mit 2 Schamanen getestet und der mit PvP Item ist schneller als der ohne.
