### ISSUE TITLE
Stormstrike löst kein WF mehr aus

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#822]
Auf der Basis des Issue https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/809 

sowie verschiedener Tests einiger Schamanen kommen wir zu dem Schluss, dass mit dem Fix des Sturmschlags irgendwie dessen Fähigkeit WF auszulösen negiert worden ist,

Daher hier noch einmal ein spezifischer Issue.

Zitat Issue 809:

muzikk commented 9 minutes ago

Habe auch einige Tests bezüglich Stormstrike -> WF Procc angestellt (1 MC Run, mehrere BGs, Solo 30min lang Mobs getötet und dabei ca. 70-80x Stormstrike benutzt) und habe auch kein einziges Mal beobachten können, dass Stormstrike einen WF Procc auslöst.

Auch bei mir ist seit gestriger Beobachtung kein WF beim Stormstrike mehr ausgelöst worden.

**Comment by wahaxlekuke** [comment]
Seit dem Sturmschlag keine Flurry-Aufladung verbraucht, zählt es als Extra-Schlag und kann deswegen kein Windfury auslösen.

**Comment by Frostlatte** [comment]
Dami hätten wir den Übeltäter... 😆

Danke fürs rasche Suchen !

**Comment by Seniorash** [comment]
Wurde was an den WF-Proccs gedreht? Bis neulich haben auch Extra-Angriffe Windfury ausgelöst.
