### ISSUE TITLE
Harte Schläge, Ewige Verfolgungen und Tollwut auf Redbull

### ISSUE THREAD

**Issue by Gromgah** [ClassicWoW/Nefarian_1.12.1_Bugtracker#823]
1.Welches Verhalten wurde beobachtet:
Hexendoktoren von Zanzil (Mobs der Stufe 44 , für die , die sie kennen) schlagen im Moment mit etwa 200 Schaden auf einen Stoffträger, mit etwa 350 Rüstung zu.
Im vergleich alle anderen Non-elite der selben stufe hauen mit etwa 50-70 Schaden auf einen Stoffträger mit 350 Rüstung. 

Wie sollte es sich verhalten: 
Eigentlich sollten besagte Mobs ein normaler Mob der Stufe 44 sein und entsprechend zuschlagen, al zwischen 50-70 Schaden auf einen Stoffträger mit 350 Rüstung.

Schritte zur Reproduktion: 
Den Mob auf ein Ziel der selben Stufe mit etwa 350 Rüstung schlagen lassen.

Zusätzliche Informationen:
http://datenbank.welli-it.de/?npc=1490

Vergleich: http://datenbank.welli-it.de/?npc=1491 

-> Der Hexendoktor haut doppelt so hart zu (meinet wegen okay) scheint aber auch noch Rüstung zu Ignorieren? Muss ausgetestet werden.
Es war keine Orginalquelle aufzufinden die dies belegt, doch möchte ich anführen das es unwahrscheinlich ist das ein Mob der gute 4mal so hart zuschlägt wie ein gleichwertiger Mob, in einem solchen Format vorkommt.
1. Welches Verhalten wurde beobachtet:
   Es gibt viele verschiedene Mobs die andere Mobs als Pet haben. Viele verhalten sich normal , wie z.B. die Hexenmeister der Blutsegelbukaniere und ihre Sukkubi. Andere sind nicht wirklich verlinkt wie die Rufer des Blackrockclans und ihre Wichtel. Und wiederum andere sind komplett am durchdrehen wie die Schwärmer der Hazzail in Tanaris.
   Zur Erklärung; die Schwärmer sind immer begleitet von einem Schwarm der Hazzik , der wie ein Pet funktioniert. Greift man den Schwärmer nun an so wird man auch vom Schwarm angegriffen. Soweit okay, doch beschwört der Schwärmer im Sekundentakt(etwa alle 5 Sekunden) weitere Schwärme. Da ein Schwarm jedoch so stark ist wie der Schwärmer selbst ist nimmt dies schnell überhand.
   Versucht man nun zu fliehen kehrt der Schwärmer irgendwann an seine ursprüngliche Position zurück, nicht so die Schwarms die er gerufen hat. Diese verfolgen einen bis Hintertimbukistan (Gadgetzan) und darüber hinaus, bis man stirbt oder es irgendwie in die Östlichen Königreiche schafft. 

Wie sollte es sich verhalten: 
Die Schwarms sollten einen nicht bis in alle Ewigkeit verfolgen. Auch wage ich zu bezweifeln das sie so schnell gespawnt werden und gleichzeitig so stark wie der Schwärmer sind.

Schritte zur Reproduktion: 
Einen Schwärmer der Hazzali pullen kurz tanken bis ein paar Schwarms gespawnt sind und dann nach Gadgetzan laufen.

Zusätzliche Informationen:
http://datenbank.welli-it.de/?npc=5451 (Schwärmer)

Ich vermute dieser Fehler hängt damit zusammen, das die Spawn Lokailtät des Schwarms nicht festgelegt ist und einen deshalb ewig verfolgen kann (ähnlich dem Läuterer). Ebenso denke ich das es mit der Spawnrate verbuggt sein muss, da es so nicht möglich ist für einen Nahkämpfer diesen Mobtyp zu töten ohne selbst zwangsläuf zu sterben , sofern man den Mob nicht innerhalb weniger Sekunden tötet.
Auch die http://datenbank.welli-it.de/?npc=458 Murlocjäger in Westfall weisen den Verfolgungs Bug auf.
1. Welches Verhalten wurde beobachtet:
   Mobs die z.B. Tollwütig sind sowohl im Namen als auch die Fähigkeit besitzen den Effekt auf einen Spieler zu wirken , haben nicht mehr die Chance den Effekt bei einem Angriff auf den Spieler zu wriken , sondern casten den Effekt mit mehrern Sekunden Zauberzeit mit einer Reichweite größer als 20 Meter auf den Spieler. Der Zauber ist unterbrechbar. 
   Dies ist bei allen mir bekannten Krankheiten und Gift verbreitenden Mobs zu beobachten.

Wie sollte es sich verhalten: 
Eigentlich sollten Gifte und Krankheiten (mit der Ausnahme von einigen spuckenden Spinnen, Kobras und z.B. den Monstrositäten in Stratholm) eine Chance haben bei einem Angriff den Spieler zu treffen oder eben in Nahkapfreichweite ohne Zauberzeit gewirkt werden.
Schritte zur Reproduktion:
Man nehme sich z.B. einen Skeletträuber aus dem Dämmerwald, halte ihn auf etwa 20 Meter Reichweite und warte bis seine Hände grün leuchten. Dann kann man ihn unterbrechen oder wird vom Gifteffekt betroffen.

Zusätzliche Informationen:
http://datenbank.welli-it.de/?spell=7992#used-by-npc (Spell ist doppelt gemoppelt verwendet, der eine sollte 5 yards haben und NICHT gespuckt werden der andere 30 yards und gespuckt werden)
http://datenbank.welli-it.de/?npc=2924 (Effekt nicht in der Datenbank, auch 30 Meter)
http://datenbank.welli-it.de/?spell=3150 (Hat 30 Meter im Moment und nicht 5, wird gecastet)
Leider habe ich keine Quelle die Belegt das es in Classic so war das diese Mobs diese Fähigkeiten nicht auf Reichweite beherrschten, doch sein wir ehrlich, selbst mit Redbull hat Tollwut immernoch keine Flügel und ein Schwertkämpfer mit vergifteter Klinge wird eine wohl kaum auf X Meter Reichweite vergiften können ohne die Klinge zu werfen....

Und ja ich weiß, dass das ewig lange Datenbank ändernde Arbeit ist die nur vom generellen Spielgefühl was bringt, weshalb ich fragen wollte ob ich diese Arbeit vielleicht selbst verrichten könnte , weil sie ja so weit hinten in der Priorität ist.

**Comment by hraesvelgr** [comment]
bei dem spell rabies zb http://datenbank.welli-it.de/?spell=3150 fehlt einfach die flag "on next swing". 5 meter ist dabei sogenannte combat-range. also ist er bis auf die flag korrekt eingetragen (werden flags in der db überhaupt angezeigt?^^)

bist du dir sicher, dass dieser spell wirklich 30 meter hat? in classic ist es so, dass wenn der cast einmal begonnen wurde, und du zb instant nach dem neginn des castes ausser reichweite komsmt, kommt der cast trotzdem durch, egal wie weit du weg bist. das ist bei "rabies" aber eigentlich nichtmal der fall, da es ein instant-cast ist.

**Comment by Gromgah** [comment]
@hraesvelgr Nicht sicher aber halte es für wahrscheinlich: Wenn ich den Mob kite und er mir nie als 20 Meter nah kommt und ich trotzdem den Effeckt bekomme, finde ich das nunmal ein wenig merkwürdig^^

**Comment by dagochen** [comment]
Bitte die 3 Fehler auf 3 getrennte Bugreports aufteilen.

**Comment by Gromgah** [comment]
Wollte eigentlich heute abend noch etwa 10 bis 12 weitere Bugs reporten a 3 pro ding entsprechend wollt ich nicht alles zuspammen

**Comment by dagochen** [comment]
Das Problem ist, wenn mehrere Bugs in einem Ticket sind und einer davon bereits gelöst ist, dann ist das markieren als "Auf Nefarian/Behoben" nicht wirklich möglich...daher bitte aufteilen ;)
