### ISSUE TITLE
Wucherborkenkapseln nicht plünderbar

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#824]
**Welches Verhalten wird beobachtet?**

Die Wucherborkenkapseln in Düsterbruch Ost können nicht geplündert werden. Dadurch wird das Sammeln der Runn Tun Knollen nahezu unmöglich und das daraus gekochte Verstärkungsessen ist quasi nicht im Spiel vorhanden.
Das Zahnrädchen wird zwar gülden jedoch geschieht bei einem Rechtsklick: nichts.

**Wie sollte es sich verhalten?**

Bei einem Rechtsklick und güldenem Zahnrädchen sollte die Kapsel normal plünderbar sein.

**Schritte zur Reproduzierung**

Nach Düsterbruch Ost gehen, den Mauszeiger auf eine Wucherborkenkapsel manövrieren.

**Links aus unserer Datenbank**

http://datenbank.welli-it.de/?object=179526
http://datenbank.welli-it.de/?object=179528
http://datenbank.welli-it.de/?object=179532
http://datenbank.welli-it.de/?object=179533

**Comment by Gnomorus** [comment]
Oh Mist. #240 tut aber nichts an der Aktualität.

**Comment by ircfelix** [comment]
Gülden :D
