### ISSUE TITLE
UBRS: Kohlepfannen in Richtung UBRS brennen dauerhaft

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#826]
*Passt gut zur aktuellen Athmospährenfixes Offensive*

**Welches Verhalten wird beobachtet?**

In den 6 Kohlepfannen, welche sich kurz vor der Tür zu UBRS befinden, brennt bereits Feuer, obgleich man die Tür noch nicht geöffnen hat.

**Wie sollte es sich verhalten?**

Das Feuer sollte erst mit Öffnen der Tür entfacht werden.

**Schritte zur Reproduzierung**

xBRS betreten, vor der Tür zu UBRS nachschauen.

**Weitere Informationen**

UBRS Magier Video von 05.09.2006: https://www.youtube.com/watch?v=6NPg20GdNxk
bei 4:11 und späteren Einstellungen sieht man, dass die Kohlenpfannen noch nicht brennen
bei 6:00 sieht man die brennenden Kohlepfannen aus eine vergleichbaren Einstellung wie in den 2min zuvor. Man sieht jedoch eindeutig das leuchten - also hätte man es vorher auch leuchten sehen müssen, würden die Pfannen immer brennen.

**Links aus unserer Datenbank**

Ich hätte die betreffenden Pfannen gerne verlinkt. Allerdings wird keine Name angezeigt, wenn man die Maus über sie bewegt. Von daher hatte ich keinen Anhaltspunkt, wie genau sie nun heißen.
Es KÖNNTEN die Dunkeleisen-Kohlepfannen sein, von denen auch 6 Stück in UBRS vorhanden sind:
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier01): http://datenbank.welli-it.de/?object=175528
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier02): http://datenbank.welli-it.de/?object=175529
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier03): http://datenbank.welli-it.de/?object=175530
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier04): http://datenbank.welli-it.de/?object=175531
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier05): http://datenbank.welli-it.de/?object=175532
Dunkeleisen-Kohlepfanne (Doodad_DarkIronBrazier06): http://datenbank.welli-it.de/?object=175533

**Comment by Rushor** [comment]
die pfannenids sind die richtigen - welche tür sollte geöffnet werden damit diese pfannen aktiv werden?

**Comment by Rushor** [comment]
mit wotlk war es zumindest nicht so https://youtu.be/teG_IhaTu7k?t=61 muss wohl ein reiner classicfeature sein

**Comment by hraesvelgr** [comment]
mit wotlk brauchte es so ein script nicht mehr, da die türen permanent offen waren.

**Comment by Gnomorus** [comment]
@Rushor Die Tür zu UBRS muss geöffnet werden, damit die Pfannen entzündet werden.

Da die Tür ab WOTLK wohl permanent offen stand (Zugluft 4tw), brannten die Pfannen wohl dauerhaft. Das sollte hier jedoch nicht sein.
