### ISSUE TITLE
MC ID

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#827]
Welches Verhalten wird beobachtet?
Meine ID von meinem MC Raid am Sonntag ist inzwischen nicht mehr vorhanden ( Mittwoch )

Wie sollte es sich verhalten?
Die ID von MC sollte eine Woche vorhanden sein

**Comment by Slimmer2** [comment]
Das passiert wenn sich Spieler in der Instanz auslogen

**Comment by ircfelix** [comment]
Vll. Könnte man das auch mal fixen. Ist ziemlich ärgerlich wenn man in Bwl z.b. flasks bauen will und did id weg is weil sich wer in der inze ausgeloggt hat.
