### ISSUE TITLE
UBRS: Beschworene NPC sind schneller als die Beschwörung erlaubt!

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#832]
**Welches Verhalten wird beobachtet?**

Die beschworenen NPC stehen bereits vor ihrer Beschwörung in den Kammern am Anfang von UBRS.

**Wie sollte es sich verhalten?**

Die beschworenen NPC sollten erst in den Kammern sein, nachdem sie beschworen wurden. Normalerweise stehen zu Kampfbeginn immer 4 Orcs in jeder Kammer.

**Schritte zur Reproduzierung**

Nach UBRS gehen, vor dem Angreifen einer Gegnergruppe in den Kammern nachschauen.

**Weitere Informationen**

http://wow-pro.com/dungeon_and_raid_guides/60_jame039s_upper_blackrock_spire_guide_ubrs
*The first room is divided in 7 little chambers, in each of these chambers 4 orcs which you must defeat to unlock the runes.*

**Links aus unserer Datenbank**

Beschworener Schreckenswirker der Schwarzfaustlegion: http://datenbank.welli-it.de/?npc=10680
Beschworener Veteran der Schwarzfaustlegion: http://datenbank.welli-it.de/?npc=10681

**Comment by hraesvelgr** [comment]
working as intended. momentan stehen imemr 4 orcs (2 beschwörer, 2 soldaten) in den kammern, die beschwörer fangen korrekt an zu beschwören, bei kampfbeginn, und wenn das nicht unterbrochen wird spawnt pro portal 1 weiterer soldat
