### ISSUE TITLE
Dropraten Alptraumdrachen

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#834]
**Welches Verhalten wird beobachtet?**

Die Dropraten der Alptraumdrachen aus unserer Datenbank stimmen nicht mit denen von damals überein. Außerdem scheinen die Drachen hier zu selten bosspezifischen Loot zu droppen.

**Wie sollte es sich verhalten?**

Die Dropraten sollten an die von früher angepasst werden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Dropraten alt:
Taerar https://web.archive.org/web/20070122203801/http://wow.allakhazam.com/db/mob.html?wmob=14890
Emeriss https://web.archive.org/web/20070120122708/http://wow.allakhazam.com/db/mob.html?wmob=14889
Lethon https://web.archive.org/web/20070116062053/http://wow.allakhazam.com/db/mob.html?wmob=14888
Ysondre https://web.archive.org/web/20070120025441/http://wow.allakhazam.com/db/mob.html?wmob=14887

"Killed yesterday on EU-Twisting Nether by Nightwatchers, dropped hammer of bestial fury and Nightmares Blade" (Taerar)
"Dropped Hammer of Bestial fury, Trance Stone" (Taerar)
In nem wowhead kommentar zu Ysondre von 2008 heißt es "dropped the healing trinket and the jade inlaid vestements", was beides bossspezifische Items sind.
=> Die Dropraten bei uns in der Datenbank sind nicht korrekt.
=> Die Bosse können zwei geteilte, (vermutlich) zwei bosspezifische oder ein geteiltes+ein bosspezifisches droppen

**Links aus unserer Datenbank (hier gehts zur Datenbank)**
Dropraten aktuell:
Ysondre http://datenbank.welli-it.de/?npc=14887
Lethon http://datenbank.welli-it.de/?npc=14888
Emeriss http://datenbank.welli-it.de/?npc=14889
Taerar http://datenbank.welli-it.de/?npc=14890

**Comment by Gnomorus** [comment]
"=> Die Bosse können zwei geteilte, (vermutlich) zwei bosspezifische oder ein geteiltes+ein bosspezifisches droppen" ... ist mit den aktuellen Dropraten/-einstellungen möglich.
" => Die Dropraten bei uns in der Datenbank sind nicht korrekt." ... sollte wirklich gefixt werden.

**Comment by ircfelix** [comment]
Da ich jetzt schon mehrfach von Celly per PN für meine Bugreports zu den Dropraten geflamed wurde, da die Dropraten auf Allakhazam die 100% übersteigen und so nicht stimmen können, bitte ich um Instruktion durch die Devs fürs weitere Vorgehen. Ich gehe beim Lootsystem davon aus, dass z.B. ein Roll von 1-1000 gemacht wird und das Item dropt, welches sich in einem gewissen Bereich befindet.

a) alle Dropraten gleichsetzen.

b) "Falsche" Dropraten von allakhazam verwenden und auf 100% umrechnen:
z.b. 10 Drops bei nem Boss mit 
(15+14+13+12+11+10+10+10+9+9)*x=100
=> x=0.88495575221
d.h. aus den 15% werden 13.27% etc. aber das Verhältnis ist das gleiche wie bei den Allakhazam Werten.

c) Das Lootsystem ist völlig anders und ihr könntets nochmal erklären.

**Comment by Larnak1** [comment]
Dass bei den alten Werten tatsächlich überall die bossspezifischen Drops ganz oben stehen, halte ich auch für einen Punkt, der sich schwer wegdiskutieren lässt. Die Frage ist, woher das kommt. 

Die andere Frage ist, wie die Dropchancen gefixt werden sollen. Nur weil in der alten Quelle 12% steht, heißt es nicht, dass das die Werte sind, die wir brauchen. Denn die Items in unserer Datenbank haben immer zwei Mal die Chance, mit dieser Wahrscheinlichkeit zu droppen, die alte DB gibt uns aber nur eine kumulierte Chance.

Wenn man mit den aktuellen Werten von unserem Server rechnet, erhält man pro Item eine Chance von 13.5%, dass es mindestens einmal droppt. Das ist höher als das meiste, was dort eingetragen ist, man sollte sich also von den reinen Prozentzahlen nicht verwirren lassen. Fragen kann man sich aber natürlich, ob man nun eine Anpassung vornimmt, um die Dropchancen der spezifischen Items zu erhöhen, während alle anderen verringert werden. Aber da zu konkreten Werten zu kommen, dürfte sehr schwierig werden.
