### ISSUE TITLE
Dropraten Azuregos

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#835]
**Welches Verhalten wird beobachtet?**

Die Dropraten von Azuregos aus unserer Datenbank stimmen nicht mit denen von damals überein. Außerdem scheint es möglich zu sein, dass er zweimal das gleiche Item dropt. Ich weiss nicht ob das hier auf dem Server so funktioniert, aber es soll wohl so sein (siehe Kommentar unten)

**Wie sollte es sich verhalten?**

Die Dropraten sollten an die von früher angepasst werden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Dropraten alt:
https://web.archive.org/web/20070122104208/http://wow.allakhazam.com/db/mob.html?wmob=6109

Zitat: "crapp loot we had :S 2x Cold Snap hehe", "Two Typhoons, one Mature Blue Dragon Sinew."

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

Dropraten aktuell:
http://datenbank.welli-it.de/?npc=6109

**Comment by dagochen** [comment]
Ja, er kann 2x das gleiche droppen, siehe http://datenbank.welli-it.de/?npc=6109
