### ISSUE TITLE
Dropraten Kazzak

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#836]
**Welches Verhalten wird beobachtet?**

Die Dropraten von Kazzak aus unserer Datenbank stimmen nicht mit denen von damals überein. 
Außerdem sollte er noch Teufelsstoff und Dämonische Runen droppen können (siehe Kommentar)

**Wie sollte es sich verhalten?**

Die Dropraten sollten an die von früher angepasst werden.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Dropraten alt:
https://web.archive.org/web/20070123122031/http://wow.allakhazam.com/db/mob.html?wmob=12397

Zitat vom 10. Januar 2007 (pre tbc!) auf Wowhead:
"He usually drops around 7-8 Felcloth and 10-16 Demonic Runes"

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

Dropraten aktuell:
http://datenbank.welli-it.de/?npc=12397

**Comment by bugreportor** [comment]
>"Zitat vom 10. Januar 2007 (pre tbc!)"
 da war bc doch schon draußen oder? zumindest ptach 2.0.1 kam ja schon am 5.12.06

**Comment by ircfelix** [comment]
Google tbc release.

Schau mal auf die dropraten vom felcloth und von den runen, dann siehste dass er das schon öfter gedropt hat.

**Comment by dagochen** [comment]
BC-Release: 16. Januar 2007
Prepatch-Release: 5. Dezember 2006
"Zitat vom 10. Januar 2007 (pre tbc!)" <<< Aussage ist somit wenigstens teilweise falsch

Beides ist für den Loot von Azuregos zu 99,9999% irrelevant, da hier wohl kaum etwas geändert wurde (soweit ich grad recherchiert habe jedenfalls).

**Comment by ircfelix** [comment]
Naja wenn vorher 10000x felcloth gedropt ist, kann man auch ne quelle von so kurz vor pre bc nehmen. Ich glaube kaum, dass sich das so kurz vor tbc nochmal drastisch geändert hätte.

**Comment by thrallsblood** [comment]
Ich schreib morgen mal folgende loot liste auf und schick se nightblizard, weil so ne komplette loot liste frisst verdammt viel zeit:

https://web.archive.org/web/20070123122031/http://wow.allakhazam.com/db/mob.html?wmob=12397#

**Comment by Larnak1** [comment]
Ehrlich gesagt sehe ich da jetzt nicht so richtig den großen Fehler. Es schwankt alles recht nah um 10. Weil das "reale" Loots sind und keine Chancen, ist eine ursprüngliche Loot-Chance von 10% für die Items recht passend. Einzig die Hosen fallen da etwas raus.
