### ISSUE TITLE
Boni des Lunarzauberstabes nicht korrekt

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#837]
**Welches Verhalten wird beobachtet?**

Der Lunarzauberstab sollte bis zu 23 Schaden und bis zu 35 Heilung gewähren (siehe Quelle), was er momentan nicht tut.

**Wie sollte es sich verhalten?**

Mehr Damage-/Heilungsbonus gewähren!

**Schritte zur Reproduzierung**

.add_item 15283

**Zusätzliche Informationen (Screenshots, Videos, etc.)**

Quelle:
https://web.archive.org/web/20061231222700/http://wow.allakhazam.com/db/item.html?witem=15283

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

Lunarzauberstab:
http://datenbank.welli-it.de/?item=15283

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/801 ?

eher weniger...

**Comment by ircfelix** [comment]
Die Änderung kam erst mit AQ und die vorher erhaltenen zauberstäbe behalten laut mathemagier ihre sstats bei.

**Comment by hraesvelgr** [comment]
die chance, dass du das item noch vor dem aq-openign auf dem server bekommst MIT dem fix ist relativ grring. sehr gering^^
