### ISSUE TITLE
MC: gelöschte Runen falsch animiert 

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#840]
Welches Verhalten wird beobachtet?
Wenn man nach dem Boss die entsprechende Rune löscht, wird sie weiterhin so animiert als wäre sie nicht gelöscht

Wie sollte es sich verhalten?
Wenn man die Runen löscht, sollte es keine Flamen um die Rune anzeigen.

Schritte zur Reproduzierung

Rune löschen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

**Comment by Gnomorus** [comment]
Rune von Blaz: http://datenbank.welli-it.de/?object=176955
Koro: http://datenbank.welli-it.de/?object=176951
Kress: http://datenbank.welli-it.de/?object=176956
Mazj: http://datenbank.welli-it.de/?object=176953
Mohn: http://datenbank.welli-it.de/?object=176957
Theri: http://datenbank.welli-it.de/?object=176954
Zeth: http://datenbank.welli-it.de/?object=176952

**Comment by Slipru** [comment]
Die Runen sind momentan auch mehrmals löschbar, was wahrscheinlich zu dem Fehler führt, dass sie weiterhin brennend Angezeigt werden.

**Comment by Slimmer2** [comment]
Hab meinen WDB Ordner noch nicht gelöscht, aber die Animation ist nicht geändert.
