### ISSUE TITLE
PvP-Flag wenn man einen Gegner ins Target nimmt

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#841]
**Welches Verhalten wird beobachtet?**
Spieler (die kein PvP anhaben) die einen Gegner ins Target nehmen der PvP an hat werden PvP geflaggt. Also nur durch das Anvisieren eines Gegners ohne eine Aktion auszuführen.

**Wie sollte es sich verhalten?**
Man sollte selber nur PvP geflaggt werden wenn man eine Aktion auch ausführt. Keine Ahnung
ob man dazu Dmg machen muss oder ob z.b. ein Huntermark ausreicht.

**Comment by Slimmer2** [comment]
Ich hab so noch nie PvP Flag bekommen

**Comment by 0815Priester** [comment]
Jo ok, wenn ich jmd mit der rechten maustaste anklicke und nichts weiter mach.Soll das so sein?

**Comment by wahaxlekuke** [comment]
Nur anvisieren und Auto-Attack starten (auch außer Reichweite) ist nicht das gleiche...
Auch wenn ich denke, dass man erst geflagt werden sollte, wenn man den Gegner tatsächlich angreift und nicht schon, wenn man aus großer Entfernung Auto-Attack aktiviert.

**Comment by 0815Priester** [comment]
Jo schlechter bugreport, sry.
