### ISSUE TITLE
Quest "Schurkenhandel"  

### ISSUE THREAD

**Issue by extremebse** [ClassicWoW/Nefarian_1.12.1_Bugtracker#842]
Hi

Kehrt man zu Calvin Montaque (http://wowwiki.wikia.com/Calvin_Montague) nach Deathknell zurück um seine Belohnung einzufordern, startet der zweite Teil der Quest.
Aufgeführt im questtext sind zwei Ziele, ihn zu besiegen und ihn zu töten. 
Vor seinem Tod bricht er den Kampf ab ,lobt die Kampfkünste seines Gegners, setzt sich hin und ißt.
Das Ziel ihn besiegt zu haben ist erfüllt. Das zweite jedoch nicht, ihn zu töten. Auch das Fragezeichen über seinem Kopf bleibt grau. Man kann die Quest jetzt auch abgeben. Zumindest erscheint das entsprechenden Fenster. Nur abschließen kann man dann die quest nicht. der sound für das abschließen einer quest ertönt, aber weder erhält man die belohnung noch erfahrungspunkte, noch schließt sich das Fenster.

Ich befand mich nicht in einer gruppe.

mfg

**Comment by Heinzelmann** [comment]
Ich denke, das es daran liegt, das man ihn eigentlich nicht töten soll. Wäre ja auch kontraproduktiv - wenn er tot ist - wie soll ich die Aufgabe bei ihm abgeben? Also im Kampf besiegen sollte da reichen.

**Comment by idl0r** [comment]
Hm, warum closed? Der Bug ist weiterhin vorhanden.

**Comment by Dotox** [comment]
Anleitung lesen :)

**Comment by idl0r** [comment]
Naja, er sagt ich soll ihm ne Minute geben aber danach passiert nichts mehr.
http://wowwiki.wikia.com/wiki/Quest:A_Rogue's_Deal_%282%29
Welche Anleitung meinst du?

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/blob/master/README.md
