### ISSUE TITLE
Overpower

### ISSUE THREAD

**Issue by Buuhuu90** [ClassicWoW/Nefarian_1.12.1_Bugtracker#843]
So nun, 

Welches Verhalten wird beobachtet?
Ziel weicht aus. Procc vom Overpower löst aus, aber Fähigkeit ist nicht anwendbar. Der procc verschwindet. von 10 Hits haben 8 gebuggt. (im pvp)

Ursache:
Bewegung. Sofern man sich bewegt, Stance wechselt oder im Kampfhaltung verschwindet Overpowerprocc.Das heiß, der Bewegung kann man kein Overpower ausüben.

Wie sollte es sich Verhalten?
Overpowerprocc sollte nicht instant verschwinden

**Comment by wahaxlekuke** [comment]
Funktioniert bei mir bei mir problemelos. Vielleicht liegts an nem Addon oder sowas?

**Comment by Buuhuu90** [comment]
Dies tritt überwiegend nur im PvP auf und ich bin nicht der einzige dem das oft passiert. Ich werde demnächst mal einen Video machen von einem Arathi Becken. Überwiegend tritt es dort auf Wahax. Vielleicht siehst du das Problem dort schneller. Movement oder sowas denk ich jetzt nicht das dies die Ursache ist.

**Comment by Testear** [comment]
Das Problem trifft häufig (nicht immer) auf, wenn sich eine oder beide Parteien im Moment des Ausweichens bewegen und ist definitiv nicht mehr nur ein PvP Problem.
Konnte es aber auch noch nicht auf Video festhalten.

**Comment by VenomXDE** [comment]
Kann ich nur bestätigen, dass dieser Bug exisitiert.....

**Comment by Testear** [comment]
kann geschlossen werden. ist kein bug.
