### ISSUE TITLE
Silithyst nicht genug Ehre

### ISSUE THREAD

**Issue by devilxxx** [ClassicWoW/Nefarian_1.12.1_Bugtracker#845]
Silithyst in Silithus (Roter Staub) sollte 200 Ehre bringen statt momentan 18

Silithus:
The Silithus event is centered on returning 'Silithyst' (sometimes referred to as 'magic sand') to the appropriate Horde or Alliance field duty camp. The dust comes from Sand Worms which erupt periodically or from random-spawn geysers near the worms. The eruptions prompt zone-wide announcements and are marked on the main map and pvp mini-map. The sand worms themselves seem to be heavy 10-person raid mobs. My very uncoordinated 5-man team spent 10 minutes doing corpse runs to DPS one down. If you succeed in killing one, everyone in your group (Raids are eligible) can loot a charge of sand. Successfully returning the sand nets you 10 CC rep and 199 honor.

http://www.lurkerlounge.com/forums/thread-4039.html

MfG

**Comment by Gnomorus** [comment]
#645

**Comment by Gnomorus** [comment]
Ehre wurde mir als ich es getestet habe sogar gutgeschrieben. Sieht man aber erst nach nem Relog. Würde es nochmal probieren. Kann natürlich auch sein, dass ich mich täusche.

**Comment by Haudraufinix** [comment]
Gerade auch noch getestet - Nach etwa 10 Abgegebenem Silithist satte 80 Ehre gekriegt
