### ISSUE TITLE
Falsche Statberechnng (mana) bei Levelup

### ISSUE THREAD

**Issue by Naudhiz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#847]
Fehler nicht von mir gefunden sondern aus Worldchat aufgegriffen.

Veränderung der Mana-Werte stimmt nicht mit den im Chat gemeldeten Erhöhungen bei Levelup überein. Das Phänomen tritt bei unterschiedlichen Klassen auf unterschiedlichen Leveln auf.

Aufgefallen ist der Effekt bei Manawerten und entsprechenden Klassen, möglicherweise trifft es auch auf andere Werte zu.

**Comment by Sabbaer** [comment]
?

**Comment by Heinzelmann** [comment]
Bei einem Levelup erhält man ja +Mana als Wert und zudem oft +Intelligenz. 1 Punkt in Intelligenz bringt aber zusätzlich 15 Mana. Am Beispiel eines Schamanen: Der bekommt beim Stufenanstieg auf 2 und später auf 3 jeweils 1 Intelligenz. Sollten zusammen 30 (2 mal 15) mehr Mana sein. Tatsächlich wird aber nur der Intelligenzanstieg mit 1 dazuaddiert. Fehlen also durch diese 2 Levelups 28 Mana.
Stufe 4 ist dann ohne Intelligenz und beim Aufstieg auf Stufe 5 gibt es dann wieder +1 Intelligenz, der dann aber richtigerweise 15 Mana bringt.

Auf Stufe 60 mögen diese 14 Punkte, die sich dann hochsummieren (Keine Ahnung, bei wievielen der 59 Levelups das falsch ist) nicht soo dramatisch sein, aber gerade am Anfang sind die noch eintscheidend. Wenn das bis Stufe 15 5x falsch ist, fehlen einem Heiler oder Mana-DD eben 70 Mana, die in einer Instanz dann eben am Schaden oder an der Heilung fehlen.

**Comment by Heinzelmann** [comment]
Achja: Extrem ist mir das bei Druiden aufgefallen. Seinerzeit hatte ich hier eine Tauren-Druiden begonnen und hatte massive Manaprobleme dadurch

**Comment by dagochen** [comment]
Ich vermute mal, das im Chat nur die Grundmana angezeigt und erhöht werden und das man durch Intelligenz, die nicht von Items/Buffs herrührt eh kein Mana bekommen kann. Macht ja irgendwie auch Sinn, wenn 1 Int = 15 Mana sind. Sonst müssten Level 1 Chars mit ca. 20 Int ja schon 300 Mana haben....?

**Comment by Heinzelmann** [comment]
Wie geschrieben funktioniert das mit den 1 Inttelligenz gliech 15 Mana ab und an. Ich kann mich erinnern, daß ich mit einem Schaman gefragt wurde, ob ich im Flammenschlund heilen könne, dies aber dankend abgelehnt habe, weil der nach 3 mal heilen kein Mana mehr gehabt hätte.

Ich empfehle einfach mal einen Druiden oder Schamanen anzufangen und darauf zu achten, wie gut man die mit Elementarzaubern/Selbstheilung spielen kann und wie gut man damit dann z.B. im Flammenschlund heilt.

Priester/Magier scheinen davon nicht so stark betrfoffen zu sein (Priesterin auf Stufe 9 440 Mana)

**Comment by dagochen** [comment]
Such doch mal verlässliche Quellen darüber heraus, anstelle hier noch mehr Mutmaßungen reinzuwerfen. Ne Quelle wo steht, wieviel HP/Mana/Stats ein nackter Char mit jedem Level haben sollte würde das Problem lösen. Aber so kann da aktuell nix gemacht werden, da keine Infos vorliegen, wie es korrekt sein sollte...

**Comment by Heinzelmann** [comment]
Weisst du was? Das ist mir einfach zu blöde hier. Quellen - Quellen - Quellen - Schau einfach selber mal nach, wieviel Mana 1 Punkt in Intellligenz gewährt und du hast dein Quelle. 

Korrekt ist: 1 Intelligenz ergibt 15 Mana
falsch ist: 1 Intelligenz ergibt 1 Mana

Probier es mal aus und spiele einen Druiden/Schamane auf 13 und heile im Flammenschlund. Als Schamane bist du nach 3 mal heilen oom und hast dann aber ein Problem: Du hast noch kein Totem gestellt. 

Und denkst du es gibt dazu heute noch Tabellen für Manawerten nach Klasse/Stufe? 

Vielleicht sollte ihr hier tatsächlich mal selber spielen, was ihr ja zu 100 Prozent noch nie habt. Ich könnte hier diesen Bugtracker zu hältte füllen mit falschen Questtexten, mal englischen-mal deutshen Antworten, mit Gegnern, die nicht richtig funktionieren. Aber ich spare mir das lieber. Mir ist eh die Lust vergangen hier noch zu spielen - es ist mir - wie heisst es so schön? - zu buggy

**Comment by dagochen** [comment]
Dann schließe den Bugreport bitte, wenn du keine Lösung des "Problems" möchtest, damit Bugreports, die korrekt dokumentiert sind, nicht zwischen Bugreports wie diesem hier, untergehen. Danke ;)

**Comment by wahaxlekuke** [comment]
Ich denke, das auf Nefarian alles korrekt funktioniert. 

Die Nachricht, dass man Mana bekommen hat, die beim Levelup angezeigt wird, bezieht sich nur auf das Grundmana des Charakters. Durch mehr Intelligenz beim Levelup erhält man nochmal zusätzliches Mana und zwar +1 Mana für jeden Intelligenz-Punkt unter 20 Intelligenz und +15 Mana sobald man über 20 Intelligenz hat.
