### ISSUE TITLE
Angelwettbewerb Booty Bay - Falsche Uhrzeit

### ISSUE THREAD

**Issue by shagu** [ClassicWoW/Nefarian_1.12.1_Bugtracker#849]
**Welches Verhalten wird beobachtet?**
Das Angelevent in Booty Bay findet nicht Sonntags von 14-16 Uhr statt.

**Wie sollte es sich verhalten?**
Das Angelevent sollte jeden Sonntags von 14-16 Uhr stattfinden

**Zusätzliche Informationen**
"Currently, this event is held every Sunday from 2pm-4pm (server time). "
http://wowwiki.wikia.com/Stranglethorn_Fishing_Extravaganza?oldid=259744
_(September 24, 2006, entspricht Patch 1.12.1)_

**Comment by Gnomorus** [comment]
Findet das Angelevent denn überhaupt statt? Wenn ja, wann? Hab ich mich gestern auch schon mal gefragt.

**Comment by shagu** [comment]
Keine Ahnung, laut /world taucht jedoch "Fischbot 5000" irgendwann Samstag Vormittags auf.

**Comment by Slimmer2** [comment]
Aktuell findet es nicht statt, soweit ich weis.

**Comment by dagochen** [comment]
Dann steht mal bisschen früher auf ihr Faultiere! :P

**Comment by Dotox** [comment]
Feedback am Sonntag wäre super :)

**Comment by Knarfinator** [comment]
Am Sonntag den 24.04 ist der Fsichbot 5000 leider nicht zwischen 14~16uhr gespwannt

**Comment by Cassedy** [comment]
War heute mal da und kann bestätigen, dass die NPCs in der betreffenden Zeit nicht spawnen, als da wären:

http://datenbank.classic-wow.org/?npc=15077

http://datenbank.classic-wow.org/?npc=15079

Bin nicht mehr sicher, ob da noch mehr NPCs spawnen sollten für das Event, aber die beiden wären zum Abgeben schon mal die wichtigsten.

**Comment by Knarfinator** [comment]
Sonntag den 15.05 wieder kein Fischbot5000 von 14~16 uhr

**Comment by hraesvelgr** [comment]
ist irgendwann mittwochs gegen 13 uhr

**Comment by dagochen** [comment]
Aktuell besteht eh ein kleines Problem mit der Sommerzeit :/

**Comment by Agorass** [comment]
Leider funktioniert der Wettbewerb immer noch nicht richtig. 
Am 11. und am 18 um 13:30 - 15:00 Uhr gechekt..
Leider spawnen die 2 NPC´s nicht

**Comment by dagochen** [comment]
Inzwischen geht es ;)
