### ISSUE TITLE
Elitegegner in den WPL

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#850]
Verschiedene Mobs in den westlichen Pestländern besitzen eine Eliteeinstufung und dementsprechend erhöhten Schaden, nicht jedoch erhöhte Lebenspunkte. Das macht insbesondere das Questen auf den Trauerfeldern mit den Geißelkesseln zur Farce.
Es handelt sich um folgende Gegner:
Verseuchter Zombie (http://datenbank.welli-it.de/?npc=4475) - Dalsons Trauerfeld
Seelenloser Ghul (http://datenbank.welli-it.de/?npc=1794) - Andorhal
Hungerndes Gespenst (http://datenbank.welli-it.de/?npc=1802) - Gharrons Trauerfeld
Klagender Tod (http://datenbank.welli-it.de/?npc=1804) - Gharrons Trauerfeld

Edit: Sengender Ghul (http://datenbank.welli-it.de/?npc=1795) ebenso

Wie es sein sollte:
Keiner dieser Gegner besaß zu Classic eine Elite-Tag. Diese Felder waren beliebte Ziele fürs AoE-Farmen von Mages. Dementsprechend muss auch der ausgeteilte Schaden auf normales Niveau gesenkt werden.

Quellen (man beachte den fehlenden Elitetag im Namen im Gegensatz zu z.B. http://web.archive.org/web/20060720195246/http://wow.allakhazam.com/db/mob.html?wmob=1827 einem Mob in Hearthglen, die korrekterweise Elite sind)

Verseuchter Zombie (http://web.archive.org/web/20060720195818/http://wow.allakhazam.com/db/mob.html?wmob=4475)
Seelenloser Ghul (http://web.archive.org/web/20060720164202/http://wow.allakhazam.com/db/mob.html?wmob=1794)
Hungerndes Gespenst (http://web.archive.org/web/20060720195209/http://wow.allakhazam.com/db/mob.html?wmob=1802)
Klagender Tod (http://web.archive.org/web/20060720195217/http://wow.allakhazam.com/db/mob.html?wmob=1804)

**Comment by ircfelix** [comment]
Diese Mobs schlagen auch gern 2-3× pro Sekunde zu.

**Comment by Larnak1** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/403

**Comment by g3n3a** [comment]
"Diese Mobs schlagen auch gern 2-3× pro Sekunde zu."

Das tun tatsächlich sehr viele Mobs u.a. auch die Skelette in Sorrow Hill.

@Larnak1 
kein Datenbankverweis im Bugtracker, daher wirds wohl nicht bearbeitet werden.

**Comment by wahaxlekuke** [comment]
WDB-Ordner muss gelöscht werden, damit die mobs korrekt angezeigt werden.
