### ISSUE TITLE
Sonnenwendfest - Freudenfeuer Quests

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#851]
Server-Version:
[19.06.2015] 1.1.0

Beschreibung:
Die Sonnenwendfest Freudenfeuer Quets funktionieren nicht richtig. Wenn die Freundenfeuer angeklickt werden bricht der vorgang ab mit der Meldung "Es wird gerade eine andere Aktion ausgeführt."
Unter den Links sind die betroffenen Quests aufgelistet, bei den Allianzquests vermute ich das diese ebenfalls verbuggt sind.

Links:
Lodernde Flammen in den östlichen Königreichen
http://datenbank.welli-it.de/?quest=9389

Lodernde Flammen in Kalimdor
http://datenbank.welli-it.de/?quest=9388

Raubt die Flamme von Darnassus
http://datenbank.welli-it.de/?quest=9332

Raubt die Flamme von Eisenschmiede
http://datenbank.welli-it.de/?quest=9331

Raubt die Flamme von Sturmwind
http://datenbank.welli-it.de/?quest=9330

Raubt die Flamme von Donnerfels
http://datenbank.welli-it.de/?quest=9325

Raubt die Flamme von Orgrimmar
http://datenbank.welli-it.de/?quest=9324

Raubt die Flamme von Unterstadt
http://datenbank.welli-it.de/?quest=9326

MfG Grishnark

**Comment by Gnomorus** [comment]
Zur Allianzseite: Da wir nicht so Böse sind, und die Flammen stehlen müssen, sondern und nur an ihnen erfreuen sollen, ist bei uns die Quest machbar. Beim Anklicken des Feuers läuft ein Zauberbalken durch, nach dessen Beendigung der betreffende Questabschnitt auf "Erfüllt" gesetzt wird. Allerdings bekommen Allianzler auch die Meldung "Es wird gerade eine andere Aktion ausgeführt." in dem Moment, in dem der Zauber des Freuens beendet wird.

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2180
