### ISSUE TITLE
Quest: "Lodernde Flammen in den östlichen Königreichen"

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#852]
**Welches Verhalten wird beobachtet?**

Die in den östlichen Königreichen verteilten Freudenfeuer des Sonnenwendfests sind zwar anklickbar und "öffnen" sich nach 5 Sekunden. Man wird jedoch nur nett begrüßt. Den betreffenden Questfortschritt geben sie einem nicht.

**Wie sollte es sich verhalten?**

Nachdem man sich am Freudenfeuer davon überzeugt hat, dass es noch brennt, sollte der betreffende Questfortschritt gewährt werden.

**Schritte zur Reproduzierung**

Nach Westfall, Hillsbrad, Silberwald und ins Sumpfland fliegen und nachschauen.

**Weitere Informationen**

http://wowwiki.wikia.com/Midsummer_Fire_Festival?oldid=382277

**Links aus unserer Datenbank**

Quest: Lodernde Flammen in den östlichen Königreichen: http://datenbank.welli-it.de/?quest=9389
NPC(?) Freudenfeuer des Sonnenwendfests: http://datenbank.welli-it.de/?npc=16592
Freudenfeuer des Sonnenwendfests: http://datenbank.welli-it.de/?object=181288
Freudenfeuer des Sonnenwendfests, Lagerfeuer, Schadensfalle: http://datenbank.welli-it.de/?object=181376

**Comment by Dotox** [comment]
#853
