### ISSUE TITLE
Brandblüte: An Freudenfeuern nicht benutzbar

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#854]
**Welches Verhalten wird beobachtet?**

Benutzt man eine Brandblüte in der Nähe oder selbst auf einem Freudenfeuer erscheint die Fehlermeldung: "Benötigt Freudenfeuer des Sonnenwendfests."

**Wie sollte es sich verhalten?**

Die Feuerblüte sollte in das Feuer geworfen werden und den "Toss Fuel on Bonfire" Zauber inklusive des Verstärkungszaubers auslösen.

**Schritte zur Reproduzierung**

Zum Freudenfeuer von Ironforge oder Westfall gehen und die Brandblüte im Inventar benutzen.

**Weitere Informationen**

http://wowwiki.wikia.com/Midsummer_Fire_Festival?oldid=382277
unter "Miscellaneous"

**Links aus unserer Datenbank**

Brandblüte: http://datenbank.welli-it.de/?item=23247
Toss Fuel on Bonfire: http://datenbank.welli-it.de/?spell=28806

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/2180
