### ISSUE TITLE
Spieler Leichen wandern

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#857]
Welches Verhalten wird beobachtet?
Wenn ein Spieler stirbt kommt es manchmal vor, das ihre Leiche wandert und so nicht wiederbelebt werden kann. Der Spieler muss erst den Geist freilassen damit man ihm wiederbeleben kann

Wie sollte es sich verhalten?
Wenn ein Spieler stirbt sollte die Leiche nicht wandern und auch wiederbelebbar sein

Schritte zur Reproduzierung
Sich töten lassen und ein anderer Spieler der wiederbeleben kann soll es versuchen.

**Comment by g3n3a** [comment]
Den Bug gabs aber auch schon zu Classic WoW.

**Comment by Gnomorus** [comment]
Von daher blizzlike also #abgehakt
