### ISSUE TITLE
Sengende Schlucht Quest: [50] Die Fackel der Vergeltung

### ISSUE THREAD

**Issue by Schlomo080** [ClassicWoW/Nefarian_1.12.1_Bugtracker#858]
Die Quest bekommt man vom NPC Questgeber "Kalaran Windklinge" im Gebiet "Sengende Schlucht".
Questtext:
Die Fackel der Vergeltung
Nehmt die Fackel der Vergeltung.

Beschreibung
Die Fackel muss jetzt an ihren Besitzer gebunden werden. Nehmt die Fackel auf, <Name>.

Belohnungen
Ihr bekommt:
Questitem: [Fackel der Vergeltung]

Nach Annahme der Quest sollte man also diese besagte Fackel der Vergeltung bekommen, um die Questreihe weiterzuführen und die Quest zu beenden. Der Questgeber gibt einem diese Fackel aber nicht.
Nach eigener Recherche bei anderen Spielern und in der Datenbank, sollte er einem diesen Gegenstand jedoch geben. 

Ich bedanke mich für das Lesen und Bearbeiten und hoffe für mich und meine Mitspieler auf baldige Behebung dieses Fehlers :) 

Liebe Grüße,

Schlomo

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/692
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/22

**Comment by Schlomo080** [comment]
habe mir
#22 und #692 durchgelesen. 
Habe die quest ebenfalls abgebrochen und neu angenommen. Diese Fackel erscheint nicht, auch nicht nach einer weile warten. Bug ist also nach wie vor vorhanden.

**Comment by Slimmer2** [comment]
Und trotzdem doppelt gemeldet...

**Comment by g3n3a** [comment]
Die Fackel ist ein Ingame-Objekt, dass erscheinen sollte. Kann bestätigen, dass sie das nicht tut.

**Comment by dagochen** [comment]
Also mit meinem Jäger, Schurken, Priester und Druiden hat es immer geklappt ;)

**Comment by hraesvelgr** [comment]
wenn ich jetz die quest mache, und sie nicht geht, hau ich dir die fackel um die ohren, dago :P

**Comment by Schlomo080** [comment]
Update: Ich hatte parallel zu dem Bugtracker Eintrag hier ein GM-Ticket offen bezüglich der Sache.
Ein netter GM äußerte, dass Ihm diese Problem bekannt sei und hat mir fix und unkompliziert das Questitem in meine Tasche gesteckt und die Folgequest in meinem Questlog gepackt. So konnte ich dann zu guter letzt weitermachen :) 

Also ein bisschen Geduld zahlt sich doch aus.

**Comment by g3n3a** [comment]
@dagochen 
Da ich stark bezweifle, dass du es eben gestern erst getestet hast, hilft der Kommentar nicht weiter. Vor nem halben Jahr hab ich die Quest auch ohne Probleme gemacht.

**Comment by dagochen** [comment]
Is schon bissl her....schätze mal August '14, November '14, Februar '15 und März '15

**Comment by hraesvelgr** [comment]
jetz is ja die frage, warum es bei dago und dotox immer funktioniert, und bei anderen spielern nie? was ist bei denen anders? dotox hat es kurz nach mir (n tag später oder so) probiert, und bei ihm ging es ohne probleme. bei mir ging es auch im dritten anlauf nicht, und ich habe einiges versucht, um diese quest zum laufen zu bringen (wtf/wdb löschen, ohne addons, etc). das war auch der grund, warum dotox meinen report damals abgelehnt hat. ich hab die quest bis heute nicht fertig.
