### ISSUE TITLE
Sillithyst - Kein PvP Flag 

### ISSUE THREAD

**Issue by Frostlatte** [ClassicWoW/Nefarian_1.12.1_Bugtracker#860]
WEnn man Sillithyst aufnimmt, bleibt man auf unserem Server frei vom PvP - Flag. 

Wie solls sein:

Nimmt man das Sillithyst auf, sollte man PvP - Markiert werden. ..ergibt auch Sinn, da man ja laut anderen Aussagen auch RP und Ehre bekomme.

**Comment by Gnomorus** [comment]
Naja - ich (als großer PVP Noob) lehne mich jetzt mal aus dem Fenster uns behaupte, dass man beim Abgeben von BG Marken auch nicht PVP geflaggt wird, obwohl man Ehre (wär ja noch nachvollziehbar) und Ruf (hat mit PVP ja mal garnichts zu tun) bekommt.
Sollte man doch geflaggt werden, bin ich soeben aus dem Fenster gefallen.
Trotzdem wird ohne Quelle nichts passieren.

**Comment by Heinzelmann** [comment]
Hallo!

Also die Siltihysten gehören eben einfach zum PvP-Event in Silithus dazu - wie die Flaggen in der Kriegshymenschlucht. Die Fraktion, die zuerst 200 gesammelt hat gewinnt.

http://www.wowpvpguide.de/pvp-im-freien/silithus.html
http://wowwiki.wikia.com/Silithyst_Mound

Und unter
http://forum.druckwelle-hq.de/archive/index.php/t-14136.html

beachzte man besonders den Satz:

"Der Staub lässt euren Charakter über eine weite Entfernung hin erstrahlen und macht euch so automatisch zum Ziel für die gegnerische Fraktion. Bis ihr den Silithyst abgeliefert habt, können Gegner euch töten und euch dann den Silithyst abnehmen. Dies führt natürlich dazu, dass eure Gegner nun wiederum zur Zielscheibe werden."

**Comment by dagochen** [comment]
Der Zauber in der Datenbank zu dem Zeug, wenn man es trägt ist da auch sehr eindeutig: 
http://datenbank.welli-it.de/?spell=29519

**Comment by Frostlatte** [comment]
Danke Heinzelmann und Dago für die Quellen. Ich hielt das PvP gemarkt werden für selbstverständlich und wollte nur darauf hinweisen, dass es buggy ist. 
Ich möchte mich mal aus dem Fenster lehnen hinterherschauen und behaupten, dass der PvP Hinweis sogar in der Questbeschreibung zu finden ist.

Besten Dung und Grüße,

Frost
