### ISSUE TITLE
Schurkengift-Ladungen

### ISSUE THREAD

**Issue by Tinkertanner** [ClassicWoW/Nefarian_1.12.1_Bugtracker#861]
Aktuelles Verhalten:
Gifte halten 30 Minuten(soweit korrekt) verbrauchen allerdings beim Procc keine Aufladung.

Korrektes Verhalten in Classic:
Gifte halten 30 Minuten oder bis alle Ladungen verbraucht sind.

Patchinformation:
Mit Patch 2.1 wurden die Ladungen erst von den Giften entfernt
http://wowwiki.wikia.com/Patch_2.1.0

**Comment by Slimmer2** [comment]
link zu den Giften die solche Aufladungen haben, wäre bestimmt hilfreich

**Comment by Gnomorus** [comment]
Die Aufladungen stehen sogar noch in den Giftbeschreibungen dabei. Jedoch scheint die Mechanik fehlerhaft zu sein, da bei jedem befragten Schurken die Gifte immer genau 30min halten. Entweder existiert die Aufladungsmechanik noch gar nicht, oder es werden einfach keine Aufladungen verbraucht.
http://datenbank.welli-it.de/?search=sofort+wirkendes
http://datenbank.welli-it.de/?search=t%C3%B6dliches+gift
http://datenbank.welli-it.de/?search=wundgift
http://datenbank.welli-it.de/?search=gedankenbenebelndes

Einzig das verkrüppelnde Gift scheint keine Aufladungen zu besitzen:
http://datenbank.welli-it.de/?search=verkr%C3%BCppelnde

**Comment by ircfelix** [comment]
Quellen!

**Comment by Tinkertanner** [comment]
In dem Patch kam ein Bugfix wo die Ladungsanzahl des tödlichen Giftes Rang 4+5 erwähnt wird.
http://wowwiki.wikia.com/Patch_1.9.3

Die Werte von dem Gift stimmen z.B. auch mit den Tooltips auf unserem Server überein. Es ist zwar keine offizielle Quelle allerdings glaube ich auch das es so gut wie keine Quelle zu sowas gibt.
