### ISSUE TITLE
Gottesschild und Göttliches Eingreifen

### ISSUE THREAD

**Issue by bambutscho** [ClassicWoW/Nefarian_1.12.1_Bugtracker#862]
Sers,

gerade im PvP gemerkt, dass ich durchs Gottesschild durch verführt werden kann.

Zusätzlich gibt es einen Bug mit göttlichem Eingreifen. Habe in BWL einen befreundeten Spieler heraus genommen, dieser ist dann jedoch durch Feuer AoE gestorben.

Lg

**Comment by hraesvelgr** [comment]
gehts etwas genauer? screens vom combatlog oder so?

**Comment by bambutscho** [comment]
sukkubus vom hexenmeister war gemeint :) screens habe ich keine gemacht, denke beim nächsten mal daran.

lg

**Comment by Slimmer2** [comment]
Göttliches Eingreifen verschwindet auch bei Hakkar, wenn er den Blutsauger macht.

**Comment by Sabbaer** [comment]
dies ist nicht korrekt, dass kommt durch den serverdelay und tritt EXTREMST selten auf. damit musst du dich abfinden das passiert mages auch im eisblock, ausßerdem passiert es in 1 von 100 bubbels dass du trotzdem stirbst, und damit musst du dich abfinden

**Comment by hraesvelgr** [comment]
bubble wurde ja schon gefixt. aber durch den vvon sabbaer genannten delay kann sowas eben trotzdem noch in seltenen fällen auftreten. lieber also eine sekunde eher einsetzen, anstatt etwas zu riskieren.

**Comment by Sabbaer** [comment]
slimmer, dein bugg ist leider ein neuer bugg, bitte einen neuen buggtracker beitrag erstellen und das bitte melden inklusive razorgore, der killt dich nämlich auch trotz eingreifen, thx dafür ;)

**Comment by Slimmer2** [comment]
bambutscho hat das aber auch geschrieben, ich hab das nur erweitert.
