### ISSUE TITLE
Eine Plage komme über Euch

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#863]
Welches Verhalten wird beobachtet?
Die Quest "Eine Plage komme über Euch" ( 2. von den 3 Quests der Reihe) von dem NPC "Mickey Levine" am Bollwerk ist leider nicht machbar, weil man den Questgegenstand nicht benutzen bzw. am vorgesehnen Item im Sägewerk abgeben kann

Wie sollte es sich verhalten?
Der Questgegenstand oder das Item auf der Map sollte benutzbar sein.

**Comment by hraesvelgr** [comment]
http://datenbank.welli-it.de/?quest=5902 horde

http://datenbank.welli-it.de/?quest=5904 allianz

**Comment by Gnomorus** [comment]
#456
