### ISSUE TITLE
PTR Tempel von Ahn'Qiraji 25.06.2015

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#866]
Die Gilde Inheritance hat beim Testen auf dem PTR folgendes festgestellt:

# Trashmobs:
### Istzustand:
1. Kann von allen Arten von CC's kontrolliert werden (Stun, Fear, Slows, Eisfalle, Roots).
2. Es sind viel zu viele Schwarmkriechergruppen im Gang zwischen Huhuran und Fankriss.
3. Sie geben 500 Ruf für Cenarius und 31 Ruf für Nozdormu.
4. Nicht kürschnerbar.

### Soll:
1. Sie sollten zumindest gegen Massenkontrolleffekte immun sein (Schätzungsweise gegen alles).
2. Im Gang sollten 2x 2 Schwarmkriechergruppen patroulieren.
3. Sie sollten viel weniger Ruf geben.
4. Diese mobs sollten zwischen 2 und 4 Unverwüstliches Leder droppen oder Silithidenchitin wenn sie gekürschnert werden.

### Istzustand:
1. Kann von allen Arten von CC's kontrolliert werden (Stun, Fear, Slows, Eisfalle, Roots).
2. Der Katalysator der Vekniss (ihr Debuff) erhöht den Schaden von Wespen der Vekniss nicht.

### Soll:
1. Sie sollten zumindest gegen Massenkontrolleffekte immun sein.
2. Der Katalysator sollte dazu führen, dass die Ziele der Wespen massiven Nahkampfschaden erleiden und sogar Tanks sehr schnell umfallen können.

### Istzustand:
1. Kann von allen Arten von CC's kontrolliert werden (Stun, Fear, Slows, Eisfalle, Roots).

### Soll:
1. Sie sollten zumindest gegen Massenkontrolleffekte immun sein.

### Istzustand:
1. Kann von allen Arten von CC's kontrolliert werden (Stun, Fear, Slows, Eisfalle, Roots).
2. Ihr Spezialangriff macht gegen Ziele die vom Katalysator der Vekniss betroffen sind keinen Bonusschaden.

### Soll:
1. Sie sollten zumindest gegen Massenkontrolleffekte immun sein.
2. Der Katalysator sollte dazu führen, dass die Ziele der Wespen massiven Nahkampfschaden erleiden und sogar Tanks sehr schnell umfallen können.

# Bosse:
### Istzustand:
1. Viscidus benötigt viel zu wenig Meleehits um zu zerspringen.
2. Giftwolken machen keinen Schaden
3. Giftwolken werden auch auf Phasenverschobene Wichtel und Totems gewirkt.
4. Giftblitzsalve wird nicht auf alle Spieler gewirkt.

### Soll:
1. Viscidus hat festgefrohren drei Stadien wie auch beim einfrieren. Es war war nicht ungewöhnlich dass auch mal zu wenig meleehits gemacht wurden um ihn zerspringen zu lassen.
2. Giftwolken sollten 1500 Naturschaden alle 2 Sekunden verursachen sowie ihre Ziele um 60% verlangsamen
3. Nur Ziele die tatsächlich Schaden durchs Gift erleiden würden sollten Ziel des Zaubers sein.
4. Viscidus Giftblitzsalve sollte alle Spieler in 100m Reichweite unabhängig von der Line of Sight treffen.

### Istzustand:
1. Huhurans Giftblitzsalve würfelt vor dem Giftblitz aus, ob sie vollends widerstanden wird. Ist dies der Fall, wird statdessen ein anderes Ziel beschossen.
2. Der Stich des Flügel von Huhuran bricht nicht bei Schaden.
3. Prinzessin Huhuran ist Spottbar
4. Begleiter zählen zu den 15 Spielern für die Giftblitzsalve hinzu.

### Soll:
1. Huhuran sollte unabhängig von Widerstehen nur die nächsten 15 Ziele mit Giftblitzen beschiessen.
2. Der Stich des Flügeldrachen sollte bei erlittenem Schaden den Spieler wieder aufwecken.
3. Huhuran sollte Spottimmun sein.
4. Lediglich Spieler sollten von der Giftblitzsalve anvisiert werden.

**Comment by ircfelix** [comment]
So lange man hasserfüllt ist geben die trahsmobs immer viel ruf. Vll. Könnte man mal auf verschiedenen rufstufen den erhaltenen ruf abchecken.

**Comment by wahaxlekuke** [comment]
Danke für den Bugreport. 
Bei diesem Punkt bin ich mir nicht sicher:
> Der Stich des Flügeldrachen sollte bei erlittenem Schaden den Spieler wieder aufwecken.

Ich vermute mal, dass das nicht so sein sollte und ich habe auch bisher nur ein Video gefunden, bei dem man gesehen hat, dass der sleep nicht unterbrochen wird. (Das war allerdings schon mit tbc-pre-patch 2.0.1, jedoch bezweifle ich, dass Blizzard mit tbc AQ40 schwieriger gemacht hat.)

**Comment by ChichiWarrior** [comment]
zu Viscidus:
- erhält noch zu viel Schaden, sowohl Melee-Hits, wie auch Elementarschaden machen vollen Schaden -> 50% absorbtion
- Die Blubbs haben zu viel HP (16.000HP) -> 10.000HP
- Viscidus kann nur durch Blubbs sterben, sollte bei 1HP stehen bleiben bis man in der richtigen Phase ist
- Viscidus soll nicht spottbar sein

zu Huhuran:
- "Fleischschild" in der 30% Phase funktioniert nicht -> 15 Melees sollen die Giftblitzsalve abbekommen
- Debuff sollte beim Dispellen am Dispeller beim zweiten Mal in Folge Schaden verursachen, was nicht passiert

zum Trash:
- Fähigkeiten funktionieren soweit, der DMG-Output ist aber viel zu gering.
