### ISSUE TITLE
Dialogfehler in Es ist für jeden ein Geheimnis (3)

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#868]
Questhub und Quotenpummelchen in Winterspring Donova Schneeweh (http://datenbank.welli-it.de/?npc=9298) hat ein Script/Dialogfehler, wenn man die Quest Es ist für jeden ein Geheimnis (http://datenbank.welli-it.de/?quest=3908) bei ihr abgibt. Es sollte ein Dialog gestartet werden, von dem scheinbar nur die Wegfindung richtig funktioniert.
Dialog:

Donova Snowden says: Please, follow me.
     Regieanweisung - Donova Snowden walks to the nearby hot springs.
Donova Snowden says: I haven't really figured out what it is, but there's something strange about the hot springs...
     Emote - Donova Snowden tosses the sword into the shallow pool.
     Regieanweisung - Donova retrieves the sword and returns to her camp.
Donova Snowden says: I've found that when I throw something into this water, it has improved incredibly when I retrieve it.
Donova Snowden says: Well, whatever it is, it works quite well!
Donova Snowden says: And I am determined to find out more... So if you need my help again, you know where I'll be.

Stattdessen kommt folgendes:
http://s22.postimg.org/4m5vujwkf/Wo_WScrn_Shot_062515_180249.jpg

**Comment by Gnomorus** [comment]
#365

**Comment by dagochen** [comment]
Duplikat
