### ISSUE TITLE
Siegel der Anrufung: Wasser

### ISSUE THREAD

**Issue by ocbalf** [ClassicWoW/Nefarian_1.12.1_Bugtracker#871]
Auswahl ohne Siegel:

- Random 

d.h. es kommt irgendein Fürst 

Auswahl mit Siegel der Anrufung: Wasser

- Random
- Fürst des Feuers

Nach der Auswahl Feuer Fürst verschwindet das Siegel nicht aus dem Inventar.

**Comment by Gnomorus** [comment]
Bin mir auch ziemlich sicher, dass beim Erstellen der Quests ein paar Gegenstands-IDs vertauscht wurden, die zu fehlern wie dem o.g. führen.
http://datenbank.welli-it.de/?search=siegel+der+anrufung

**Comment by wahaxlekuke** [comment]
Dieses "<Random>" war übrigens nur ein Platzhalter für die deutsche Übersetzung, den ich vergessen hatte zu entfernen.
