### ISSUE TITLE
Eisblock vom Magier ist fehlerhaft.

### ISSUE THREAD

**Issue by Elektroboter** [ClassicWoW/Nefarian_1.12.1_Bugtracker#873]
Seit dem letzten Patch (Danke das Ony endlich ordentlich Deep Breath macht und nicht mehr luschenhaft ist) ist der Eisblock vom Magier eindeutig fehlerhaft. Mein Magier stirbt seit dem regelmässig, obwohl der Block läuft.

Im Duell hab ich bissl getest, da tritt es nicht auf, aber im PVE.

Ich denke ich brauche dafür keine Quellenverweise oder ähnliches. Das erklärt sich von selbst.

Vielen Dank für die Aufmerksamkeit.

**Comment by Gnomorus** [comment]
Say what?

**Comment by dagochen** [comment]
Konkrete Beispiele zum reproduzieren bitte?

**Comment by Thandor** [comment]
Naja es ist doch ganz einfach :+1: 

Ony die geile Alte,
spuckt Feuer aus ihrer Spalte
und das ist so heiß,
da schmilzt sogar nen Block aus Eis.

**Comment by ircfelix** [comment]
Danke für diesen lyrischen Erguss,
Er befreite mich von allem Verdruss!
Als ich sah diesen Bugreport,
Wollt ich von Nefarian nur noch fort.

Doch dann sah ich ein Gedicht,
voll Erklärung dass Onyxia die alte Spalte
Mit ihrem Feuer den Eisblock zerschallte.
Und es ward am Ende des Tunnels doch Licht

**Comment by Thandor** [comment]
Es lag mir fern dich abzuhalten,
von anderer Bossen Spalten,
Geh wieder zu Nef dem Lappen,
auf das seine Scripte endlich klappen!

**Comment by nightblizard** [comment]
Nicht reproduzierbar aufgrund mangelnder Infos.

**Comment by ircfelix** [comment]
Er schloss den Fred zugleich,
Ich stand dort angewurzelt,
Wie 'ne deutsche Eich'.

Gäb' er uns nur eine Chance,
Zu schreiben nen Report
Mit viel Extravaganze.

So brächten wir die tollen Informationen, 
Glaub' er mir,
Es würd' sich lohnen.

So gib uns noch ein wenig Zeit,
Für einen Report,
Der dir bringt Zufriedenheit.
