### ISSUE TITLE
Siegel, die debuffs verursachen

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#875]
Welches Verhalten wird beobachtet?
Siegel des Kreuzfahrers, Siegel der Weisheit, Siegel des Lichts und siegel der Gerechtigkeit kann widerstanden werden

Wie sollte es sich verhalten?
diesen sollte nicht widerstanden werden können.

Schritte zur Reproduzierung
http://wowwiki.wikia.com/Patch_1.9.0
Judgements - Judgements that place a debuff on their victim will now all have their duration refreshed when the judging paladin strikes the victim with his or her melee swings. All these debuffs have had their duration decreased to 10 seconds. In addition, Judgements that place debuffs can no longer be resisted.

Links aus unserer Datenbank
http://datenbank.welli-it.de/?search=seal+of+light
http://datenbank.welli-it.de/?search=seal+of+the+crusader
http://datenbank.welli-it.de/?search=seal+of+wisdom
http://datenbank.welli-it.de/?search=seal+of+justice

**Comment by Sabbaer** [comment]
leider im heuten bwl raid wieder 4 mal resist auf richturteil der weisheit und 3 mal auf richturteil des kreuzfahrers

**Comment by Dotox** [comment]
Ist doch offen :D Aber danke für die Info, dann schau ich nochmal.

**Comment by Sabbaer** [comment]
kann es sein, dass hier diese grund resist gegen mobs höherer stufe wieder ins spiel kommt? gegen "normale" mobbs ist mir das seit dem patch nicht mehr passiert

**Comment by Dotox** [comment]
Eigentlich ausgeschlossen. Die Änderung sollte für alle Kreaturen gelten. Es kann dort natürlich trotzdem ein Fehler vorliegen - müssen wir aber erst genauer ansehen :) Denke das bekommen wir auch noch hin.

**Comment by hraesvelgr** [comment]
laut http://community.mmobase.de/updates-changelog/8198-update-16-10-2015-%5Balteractal-patch%5D.html sollte das gefixt sein. bei venoxis heute wurde siegel der weisheit allerdings resistet.

**Comment by Sabbaer** [comment]
der fehler besteht leider weiterhin, dies kommt wenn der npc nicht auf der selben "ebene" ist wie der paladin, dadurch entsteht auch der siegel des befehls bugg https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/748
https://www.youtube.com/watch?v=BNbW2mVwpws&feature=youtu.be
hier mal ein kleines video dazu zuerst cite ich einen wolf um einen baum drücke richturteil, nichts passiert mana wird abgezogen richturteil geht auf cd
beim 2ten mal um den baum schlage ich den wolf per meele hit und drücke in der selben 0.1 sec mein richturteil da ich ja im meele range zum mobb bin, wieder passiert nichts!
danach zeige ich, dass es auf einer "geraden fläche" einwandfrei funktioniert

beim 2ten mal hole ich mir einen welpling und ziehe ihn über ein vorkommen und drücke richturteil, nichts passiert mana wird abgezogen richturteil geht auf cd.
(funktioniert genauso mit weißheit usw.)

**Comment by hraesvelgr** [comment]
kann es vllt an der LOS zwischen dir und dem npc liegen? was meinst du mit "ebene"?

**Comment by Sabbaer** [comment]
jo, es ist eine andere "polygon ebene" häufig passiert das auch einfach so, der mobb ist einfach "nicht in meiner range" weil er ka wo ist, ich kenne ja die scripts nichts aber mein richturteil geht halt auf cd ich krieg mana abgezogen aber es wird einfach schlichtweg nicht berechnet, das kostet einen ret pala extrem viel mana und dmg, wenn der mobb nicht in range für die attacke ist, sollte dranstehen, der gegner ist nicht in reichweite, solange bis ich das richturteil drücke und die berechnung stattfindet

**Comment by Sabbaer** [comment]
immernoch vorhanden, videos benötigt? selbe fehler

**Comment by dagochen** [comment]
ja bitte

**Comment by Sabbaer** [comment]
https://www.twitch.tv/videos/121863792 in dem video vom sonntag dem 12.02.2017 gibt es noch viele stellen mehr wo es passiert

**Comment by Sabbaer** [comment]
auch hier wieder in meinem letzten raid video häufiger zu sehen (z.B. bei cthun)
