### ISSUE TITLE
API UnitCastingInfo("unit") und UnitChannelInfo("unit") fehlen

### ISSUE THREAD

**Issue by Maxwill** [ClassicWoW/Nefarian_1.12.1_Bugtracker#877]
## Welches Verhalten wird beobachtet?
In der API fehlen die Funktionen UnitCastingInfo("unit") und UnitChannelInfo("unit")

## Wie sollte es sich verhalten?
Diese Funktionen sollte es geben, um sie in Addons verwenden zu können

/run UnitCastingInfo("player") 

sollte keine NullPointerException werfen.

## Schritte zur Reproduzierung
/run UnitCastingInfo("player") 

wirft eine NullPointerException 

## Zusätzliche Links
http://wowwiki.wikia.com/API_UnitCastingInfo
http://wowprogramming.com/docs/api/UnitCastingInfo
http://wowprogramming.com/docs/api/UnitChannelInfo

so long Maxwill

**Comment by Gnomorus** [comment]
Verhält sich ähnlich mit UnitIsAFK
http://wowwiki.wikia.com/API_UnitIsAFK?oldid=373532
http://wowprogramming.com/docs/api/UnitIsAFK

**Comment by wahaxlekuke** [comment]
Beides sind Funktionen, die der Client erst mit 2.0.1 also TBC zur Verfügung gestellt hat. (Siehe http://wowwiki.wikia.com/Patch_2.0.1/API_changes) 

Da es eine clientseitige Sache ist, können wir daran sowieso nicht ändern.
