### ISSUE TITLE
Grünwelpenrüstung - Sleept auch LvL 60 Spieler

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#878]
**Welches Verhalten wird beobachtet?**
Dast Item http://datenbank.welli-it.de/?item=7375 sleept auch LvL 60 Spieler.

**Wie sollte es sich verhalten?**
Sollte nur Gegner sleepen die lvl 50 oder unter drunter sind.

**Comment by ircfelix** [comment]
Quelle!

**Comment by Haudraufinix** [comment]
Ich glaube das problem ist hier das iwan die Zielstufe begrenzt wurde (ähnlich wie bei vielen ingenieurssachen zu BC) ich glaube daher stark, dass das lediglich ein falscher Tooltipp ist und der Effekt korrekt funktioniert.

**Comment by hraesvelgr** [comment]
Zamfix on 2008/05/06 (Patch 2.4.1)
It was used during the Arlokk encounter in Zul'Gurub for the panther off-tanks. However, blizzard then reduced the duration of the sleep (30 sec to 10 sec) and capped its effectiveness at targets below level 50.

wann genau jedoch das cap kam, ist mir nicht bekannt.

**Comment by nightblizard** [comment]
Quellen sind hier nicht benötigt. Das steht im Tooltip und bedarf daher keiner weiteren Erklärung.

**Comment by ircfelix** [comment]
Dann kann man jetzt die Patchnotes durchsuchen wann das geändert wurde. Habt ihr devs vll. Schon nen textfile mit ALLEN pre bc patchnotes drinnen wo man mit strg+f suchen kann? Wen  ja wäre es knorke wenn ihr dieses mit uns teilen würdet :-)

**Comment by 0815Priester** [comment]
http://wowwiki.wikia.com/Patch_1.10.0
Green Whelp Armor no longer affects targets above level 50 and the sleep duration was reduced to 10 seconds.

**Comment by Larnak1** [comment]
"Quellen sind hier nicht benötigt. Das steht im Tooltip und bedarf daher keiner weiteren Erklärung."
Das kann leider kein Maßstab sein, so steht (stand?) beispielsweise bei den Verzauberrruten drin, sie seien abwärtskompatibel, obwohl sie es korrekterweise nicht sind. Bei solchen Unterschieden muss daher gefragt werden, ob der Tooltip oder die Funktion falsch ist.

**Comment by nightblizard** [comment]
Bei welcher Rute steht das denn bitte dran? Abgesehen davon sind die grünen Texte bei Zaubern etwas anderes, die sind in jedem mir bekannten Fall richtig, weil ich die vom Server aus nicht manipulieren kann (die Texte ließt der Client aus seinen eigenen Daten aus)

**Comment by Larnak1** [comment]
Bei jeder steht das dran. Irgendwie klappt das Fixen wohl auch nicht.
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/653

**Comment by hraesvelgr** [comment]
@nightblizard 
nicht nur die grünen, auch die gelben texte sind wohl auch spieldatei-abhängig, und nicht wtf/wdb-abhängig.

**Comment by dagochen** [comment]
naja von fernkampfwaffen mit elementarschaden hat es geklappt das serverseitig zu fixen, dass da jetzt der "chance on hit:..." text steht.
