### ISSUE TITLE
Krieger Ansturm - Wut

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#880]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
1.1.0

Beschreibung:

Wenn man Ansturm benutzt und gleichzeitig mit der Maus oder mit einem Makro die Haltung wechselt (zb Deff) behält man die Wut wenn man schnell genug klickt. ( Ohne Taktiker Talent http://datenbank.welli-it.de/?spell=12295 )

**Comment by Testear** [comment]
Das kommt durch den Serverdelay und kommt vor, wenn man während des Stürmens bevor man beim Ziel ist, die Haltung wechselt. Das liegt daran, dass man die Wut oft erst am Ende der Stürmens erhält. Wenn man nun vorher die Haltung wechselt, was man noch während der 1,5 Sekunden GCD kann (Fähigkeiten und Haltungen haben beim Krieger einene unterschiedlichen GCD!) hat man den Wutvorteil in einer anderen Haltung.

Ich behaupte. dass das nur am Serverdelay liegt, denn ich kann es nicht zu 100% reproduzieren. Aus dem gleichen Grund sterben Palas/Magier manchmal in der Babbel bzw. im Eisblock.

**Comment by Sabbaer** [comment]
hm, die ist aber doch ein rießenvorteil, was könnte man denn tuen um dies zu verhindern?

**Comment by Testear** [comment]
Im laufe meiner Recherchen habe ich keinen Hinweis darauf gefunden, dass das zu classic auch möglich war. 
Ein Lösungsvorschlag wäre statt der Reihenfolge
Anstürmen > Wutreg > Stun

die Reihenfolge

Wutreg > Anstürmen > Stun 

verwendet?  So sollte die Wut immer beim drücken der Taste regeneriert werden.
