### ISSUE TITLE
bestie loot #2

### ISSUE THREAD

**Issue by hraesvelgr** [ClassicWoW/Nefarian_1.12.1_Bugtracker#885]
bug tritt wieder auf: die bestie droppt nur ein blaues item, mehr nicht. 

siehe: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/182

**Comment by dagochen** [comment]
https://web.archive.org/web/20070122040800/http://wow.allakhazam.com/db/mob.html?wmob=10430

This guy is sooo easy. we did 3 runs in a row and got the Ironweave thing and 2 tristam leggings. we had 2 rogues, and they were very happy. (Sep 20th 2006)


took this down yesterday with my 58 hunter and he dropped.. Lightforge Shoulders! cant see set items anywhere in the droplist.. new content from the patch or what? (Oct 1st 2005)

**Comment by hraesvelgr** [comment]
und wer hat nun recht? quelle gegen quelle.

**Comment by wahaxlekuke** [comment]
Ich hatte das vor kurzem geändert (Als ich Finkles Kürschner gefixt hatte), dass nur noch ein Item + ein weiteres Item zu ~40 % droppen kann, damit das mit den Wahrscheinlichkeiten auf allakhazam übereinstimmt.
Nachdem ich mir aber mehrere Youtube-Videos angeschaut habe, bin ich mir ziemlich sicher, dass immer zwei Items droppen sollen. Und der Kommentar auf Allakhazam schließt auch nicht unbedingt aus, dass noch andere Sachen gedropt sind...

**Comment by hraesvelgr** [comment]
ich sag ja auch nicht,d ass du oder dago falsch liegst, es wär nur geil, zu wissen, was nun wirklich korrekt ist (egal wer von uns  richtig oder falsch liegt)

**Comment by dagochen** [comment]
Meine Vermutung wäre, dass es einen Pool von Items gab, und dazu Zusatzloot mit etwas geringerer Chance, sodass er (fast) immer 2 Items droppt. Vermutlich Bestien-Ass, Finkles und noch irgendwas?

**Comment by c0keh** [comment]
war es nicht so, dass die bestie 1-3 items droppte und für jedes item, das zu 3 fehlte, wurde drakki 1 hinzugefügt?
*noch mehr spekulationen streu*

**Comment by ircfelix** [comment]
Nein ich glaube die Bestie hat nur dann 3 Items gedropt wenn im Raum von Rend der ganze Raid sich hingesetzt hat und /pfeifen eingegeben hat.

Genau wie mit dem Baron, der sein Mount nur gedropt hat wenn man alle Kakerlaken in Strat Ud in 15 Minuten gekillt hat.

Wie kann es nicht sein dass ihr das nicht mehr wisst? ;@)
