### ISSUE TITLE
Falsche Fraktion im Ruffenster

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#886]
Als Hordler hat man die Fraktion "Stormpikegarde" in der Rufübersicht ( zumindest wenn man mal im AV war). Die Fraktion wird aufgeführt unter dem Begriff "Streitkräfte der Allianz".

Normalerweise sollte man als Hordler oben genannte Fraktion nicht haben.

**Comment by Testear** [comment]
Ebenso wird auf Allianzseite der "Frostwolfklan" unter dem Punkt "Streitkräfte der Horde".

Als Lösung schlage ich vor diese Fraktion einfach auf Inaktiv zu setzen, wenn man sich dadurch gestört fühlt.

**Comment by Haudraufinix** [comment]
Die Fraktionen hatte man zu classic tatsächlich zeitweise angezeigt gekriegt - allerdings immer auf Hasserfüllt. Wieso weis nur Blizzard^^

**Comment by Slipru** [comment]
Update:
Die Allianz PvP Fraktion "Der Bund von Arathor" wird einem als Hordler ebenfalls im Ruffenster angezeigt sobald man Kontakt mit ihnen hatte.
