### ISSUE TITLE
Gahz'ranka Beschwörung

### ISSUE THREAD

**Issue by Slipru** [ClassicWoW/Nefarian_1.12.1_Bugtracker#887]
Die items zur Beschwörung "Zulianischer Matschstinker" und "Matschstinkerköder" können überall in ZG benutzt werden um den Boss zu beschwören ( Auch außerhalb von ZG kann man sie benutzen und sie verschwinden danach)

Wie das Item schon sagt sollte Gahz'ranka nur von Pagle's Point Beschwörbar sein ( und nur dort sollten die items in kobination benutzbar sein )

Matschstinkerköder
Use: Load with 5 Zulian Mudskunks, and then cast from Pagle's Point in Zul'Gurub.

**Comment by Gnomorus** [comment]
Gief Links zu den Items. Sonst nie Fix kommen.

**Comment by hraesvelgr** [comment]
http://datenbank.welli-it.de/?object=300052 pagles point
http://datenbank.welli-it.de/?item=19974 der köder
http://datenbank.welli-it.de/?spell=24325 der matschstinker-zauber den man von pagles point zaubern sollte

**Comment by Larnak1** [comment]
Wo wir gerade dabei sind: Ihre Spawn-Position sollte auch woanders sein, man sieht hier im Video wo sie herkommt:
https://www.youtube.com/watch?v=jiib6v_WsDg

Hier sieht man den Spawnvorgang im Detail, allerdings ist das Video von 2007:
https://www.youtube.com/watch?v=s_dCpVbhKug

Nach dem Spawn im Wasser läuft sie dorthin, wo sie bei uns spawnt, wie man hier sehen kann:
https://www.youtube.com/watch?v=06sDeRhDsg8
