### ISSUE TITLE
In den Träumen

### ISSUE THREAD

**Issue by Amaran87** [ClassicWoW/Nefarian_1.12.1_Bugtracker#889]
Der NPC "Hochlord Taelan Fordring" respawnt nach der Quest nicht mehr.
Seid ca. 2 Tagen ist dieser NPC nicht mehr da.
Sein Kadaver liegt immer am Turm wo man nach seinen Ableben auf Tirion trifft.

**Comment by Bonfuzius** [comment]
Soeben habe ich Taelon mal zufällig erwischt (wahrscheinlich nach server-Restart). Leider machte er genau 0 Schaden und starb dementsprechend bei den ersten 4 Mobs.

**Comment by Amaran87** [comment]
Habe ihn 2 mal angetroffen jeweils immer an anderen Positionen und total verbuggt. 
Quest startet -> NPC macht garnix.
