### ISSUE TITLE
Die Hand von Rastakhan löst Scriptevent aus

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#891]
Die Abgabe der Quest Die Hand von Rastakhan (http://datenbank.welli-it.de/?quest=8182) löst dasselbe Scriptevent aus wie die Abgabe von Hakkars Herz (http://datenbank.welli-it.de/?item=19802) bzw die Quest Das Herz von Hakkar (http://datenbank.welli-it.de/?quest=8183) ohne jedoch am Ende ein Buff zu vergeben. Passieren sollte bei der Abgabe der Quest natürlich nichts.

**Comment by hraesvelgr** [comment]
hab die quest grad gemacht, und konnte es nicht reproduzieren. war vllt ein spieler in der nähe. der diese  quest (herz von hakkar) gemacht hat?
