### ISSUE TITLE
UBRS: Bestie Kürschnern

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#892]
Derzeit tritt ein Bug auf, der es verhindert die Bestie (http://datenbank.welli-it.de/?npc=10430) zu kürschnern. Bei <315 Kürschnern hat man ständig das Kürschnereisymbol, auch wenn die Bestie noch am Leben ist. Bei 315 Kürschnern kann man die Leiche der Bestie nicht kürschnern, weil angeblich noch geplündert wird.

**Comment by Testear** [comment]
Ich hab die Erfahrung gemacht, dass wenn man PM vor der Bestie anmacht, dieses Problem nicht auftritt, da oft die Tückischen Klauen in der Bestie liegen gelassen werden.

**Comment by hraesvelgr** [comment]
normal sollten die tückischen klauen aber jedem angezeigt werden, und daher auch lootbar sein.das einzige was ich mir vorstellen kann, ist, dass der "pristine hide" als bossloot gewertet wird, aber unsichtbar im lootfenster ist, (da der ja nur beim kürschnern droppt). aber wnen noch was im lootfenster ist, kann man ja nicht kürschnern. 

oder aber die tückischen klauen sind im loot einem spieler zugewiesen (die anderen sehen das dadurch nicht) und dieser spieler vergisst einfach zu looten, weshalb dann nicht gekürschnert werden kann. für die anderen spieler sieht der npc dann aus, als hätte er ein leeres lootfenster.

**Comment by g3n3a** [comment]
Wenn noch Loot in nem Mob ist, kommt aber kein Kürschnersymbol.

**Comment by Testear** [comment]
"oder aber die tückischen klauen sind im loot einem spieler zugewiesen (die anderen sehen das dadurch nicht) und dieser spieler vergisst einfach zu looten, weshalb dann nicht gekürschnert werden kann. für die anderen spieler sieht der npc dann aus, als hätte er ein leeres lootfenster." 

THIS

**Comment by g3n3a** [comment]
Es kommt kein leeres Lootfenster und auch keine Interfaceanzeige als wenn noch Loot in nem Mob ist (fehlende Kürschneranzeige mit benötigtem Skilllevel in Farbe). Außerdem hat sie auch lebend nen Kürschnersymbol statt ein Schwertcursor.

**Comment by Testear** [comment]
Darüber, dass man die Bestie oft nicht kürschnern kann sind wir uns alle einig.

Mein Vorschlag wäre um das Problem erstmal zu behen allen Loot um den nicht gewürfelt wird aus dem Loottable rauszunehmen, damit man als kürschner die Bestie immer kürschnern kann.

**Comment by hraesvelgr** [comment]
oder aber einfach das lootverhalten bei kürschnerbaren bossen (wo man wirklich aufs kürschnern angewiesen ist , in aq gibts glaube auch solche bosse?) so setzt, dass aller loot, der sich nicht automatisch verwürfelt, immer allen spielern angezeigt wird, es sozusagen keinen zugewiesenen trashloot gibt.

**Comment by nightblizard** [comment]
Verstehe ich das richtig, dass das Problem darin liegt, dass die Leute die NPCs nicht looten? Wenn ja, dann ist das kein Bug.

**Comment by g3n3a** [comment]
Was hat die ständige Kürschneranzeige trotz lebendigem Mobs mit irgendwelchem Loot zu tun?
