### ISSUE TITLE
Alptraumdrachen spawnen einzeln

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#897]
Die Alptraumdrachen spawnen nie zusammen.

Sie sollten alle immer gleichzeitig spawnen.

The Four Green Dragons will now spawn as originally intended. They should all now spawn at the same time everytime. 

http://wowwiki.wikia.com/Patch_1.10.0

1. Punkt bei Raid & Dungeons

**Comment by wahaxlekuke** [comment]
Siehe #504. Wird wahrscheinlich mit gleichzeit mit AQ eingeführt.

**Comment by Testear** [comment]
Bin auch letztens nur zufällig drüber gestolpert als ich den Kriegercharge recherchiert hab.
