### ISSUE TITLE
pvp account in hauptstädten/startgebieten

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#899]
Man bleibt in allen Hauptstädten und Startgebeiten der eigenen Fraktion PvP geflaggt wenn man einen PvP Account hat und es ist auch nicht möglich dieses loszuwerden.

Man sollte in allen Startgebieten und Hauptstädten der eigenen Fraktion das PvP Flag verlieren wenn man " /pvp off " eingibt.

http://wowwiki.wikia.com/PvP_flag

Schritte zur Reproduzierung:

Einen PvP Account erstellen, sich in eine freundliche Hauptstadt stellen, " /pvp off " eingeben und 5 Minuten warten.

Danke an die Hordler die mich heute in If darauf aufmerksam gemacht haben.

**Comment by hraesvelgr** [comment]
generell scheint der befehl "pvp off" nicht zu funktionieren, es steht immer da "pvp status: aktiv". es beginnt auch kein kleiner timer neben der hp-anzeige (im normalen interface)

**Comment by Slimmer2** [comment]
Wenn man einen PVP Account hat, kann man PVP auch nicht ausschalten

**Comment by Testear** [comment]
http://community.mmobase.de/updates-changelog/5974-update-12-08-2014-a.html

"Die Charaktere auf dem Account werden nachdem ihr den Befehl bestätigt habt so behandelt, als würden sie auf einem PvP Realm spielen."

Aktuell werden sie so behandelt als wäre überall PvP Gebiet, was schlicht falsch ist.

**Comment by hraesvelgr** [comment]
>Wenn man einen PVP Account hat, kann man PVP auch nicht ausschalten

toll, und jetz darf ich an jedem neutralen FP erstmal dreimal sterben bevor ich weiter farmen/questen kann?

**Comment by Testear** [comment]
Den befehl kann ich auch eingeben, aber PvP läuft nicht ab.
