### ISSUE TITLE
ein stärkerer zauber ist bereits aktiv 

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#900]
Wenn man einen schwächeren Zauber nutzt während man einen starken Zauber draufhat überschreibt der schwächere den starken oder sie stacken.
Zum beispiel überschreibt "Elixier der schwachen Seelenstärke" (27 HP) das "Fläschchen der Titanen" (1200 HP)

So sollte es sein:

Wenn ein schwächerer Zauber zusätzlich zu dem Starken gewirkt wird erscheint auf dem Bildschirm die Fehlermeldung "Ein stärkerer (mächtigerer?) Zauber ist bereits aktiv" und der schwächere Buff kann nicht ausgeführt werden.

http://www.warcraftmovies.com/movieview.php?id=26232    Zeitpunkt: 10:45

**Comment by nightblizard** [comment]
Ein Fehlerhaftes Verhalten beim Stacken konnte ich nicht reproduzieren. Siehe: https://youtu.be/2U4pXWlntYM

Jedoch fehlt hier tatsächlich die Fehlermeldung, dass bereits ein stärkerer Buff aktiv ist, was dazu führt, dass ihr das Item bei der Benutzung verschwendet.
