### ISSUE TITLE
Quest: Kriegsausrüstung

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#901]
Welches Verhalten wird beobachtet?
Wenn man die Quest Die Anrufung abgibt,bekommt man die Folgequest Kriegsausrüstung nicht.
Die betrifft nur Hexenmeister

Wie sollte es sich verhalten?
Wenn man die Quest Die Anrufung abgibt, sollte man die Folgequest Kriegsausrüstung bekommen.

Schritte zur Reproduzierung
Als Hexenmeister die Quest Die Anrufung abgeben.

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)
Die Anrufung: http://datenbank.welli-it.de/?quest=8315
Kriegsausrüstung: http://datenbank.welli-it.de/?quest=8381
http://www.wowhead.com/quest=8315/the-calling#comments

**Comment by Gnomorus** [comment]
#180 interessiert wohl niemanden. musst nen gm anscheiben, dann bekommst die quest ins log gepackt.

**Comment by Testear** [comment]
Chillt mal, es ist Sommer, da dauert alles länger.

**Comment by dagochen** [comment]
seh ich das richtig das mage/hexer die gleiche q haben sollten?

**Comment by Slimmer2** [comment]
Ja ist die gleiche und sollte bekannt sein

**Comment by Slimmer2** [comment]
Wann wird der Fix aufgespielt?
