### ISSUE TITLE
Hunter epic Quest Silithus

### ISSUE THREAD

**Issue by asdfgjh** [ClassicWoW/Nefarian_1.12.1_Bugtracker#902]
Also erstmal eine fucking Unverschämtheit das man immer auf diese externe Plattform  gezwungen wird und sich auchnoch hier anmelden muss um einen BUG zu reporten... 

Davon abgesehen das ich Tagelang auf eine Antwort ingame gewartet habe und dann MITTEN IN DER NACHT per Ticketantwort mit der Art "hast pech mach nen report" abgespeist werde echt das letzte....
UND NEIN ich habe auch kein Video davon denn ich besitze kein REC-Prog.

Aber es sollte eindeutig sein das wenn man den Dämon in Silithus macht einfach >>>>>>OHNE Fremdeinwirkung & ohne fremde Buffs....  bin ja net behindert ..... was die einem immer in diesen shize tickets antworten *tztztztz* <<<<<<<< 
Das dieser früher oder später die Läuterer ruft .... hatte das mitten als ich gefeart war von ihm, wie auch wenn ich mit Multishot die Käfer erwischt habe .... also weis ich net genau woran es liegt was klar ist das er nicht geht ..... leider kann man nicht wie bei jedem fucking mob 1000 mal probieren was es genau ist und ich habe nach einer woche auch keine lust mehr dazu.

Mehr meldung könnt ihr euch von mir hier leider net wünschen schon ein wunder das ich das hier melde total lächerlich das SOWAS echt Essenzielles wie eine Klassenquest kaputt gepatcht wird von euch nasen. schaut zu das ihr das wieder fixt ...... laufen genug leute rum die die shize haben.......

Greez Trathos

**Comment by g3n3a** [comment]
close in 3..2..

**Comment by Gnomorus** [comment]
Scheinst ja echt echt Zeit zu haben, wenn du die Unverschämtheit mitmachst und dich auf der externen Plattform anmeldest, nur um die Gülle hier von dir zu geben.

**Comment by hraesvelgr** [comment]
@asdfgjh 
ich würde bei dir gern die impertinenz besitzen, auf rechtschreibfehler hinzuweisen. 
und sei dir gewiss, du bist nicht der einzige, den das stört, aber der erste, der so abartig ausfallend wird. deshalb denke ich, dass ein problem mit dir besteht, und nicht mit dem server oder den devs.

**Comment by asdfgjh** [comment]
eigentlich warte ich nur darauf das man die shize wieder so schließt ohne es zu lesen wie meine tickets ( welche alle nicht so ausfallend waren :P )

mit der antwort das es kein prob gibt ohne vid oder das ich nur zu blöd bin buffs wegzudrücken von anderen :P

wer hier wieder rechtschräääääbfehler zääääählt kAnnn soe behülten is klar ne

**Comment by asdfgjh** [comment]
aber lasst den bug ruhig shize auf das ticket hier twinken is eh nicht das wahre
is halt lustig wenn es neulingen so geht wie mir ....:O 
Die Q geht net und jeder schreibt ihnen sie seien nur zu doof 1A sowas 

greez

**Comment by Seniorash** [comment]
Iss nen Snickers
