### ISSUE TITLE
Kodo emote

### ISSUE THREAD

**Issue by Armauskugelbob** [ClassicWoW/Nefarian_1.12.1_Bugtracker#905]
Sitzt ein Charakter auf einem Kodoreittier und wird dann die Sprungtaste gedrückt, sollte ein emote ausgelöst werden.  Dieser ist aktuell nicht vorhanden.
lg ;)

**Comment by hraesvelgr** [comment]
ähm...nein.

**Comment by Haudraufinix** [comment]
Doch, der Kodo sollte seinen Kopf nach links und rechts schlagen - begleitet von einem beherzten gähnen.
Genau so wie sich z.b. Nachtsäbler auch strecken sollten etc^^

**Comment by hraesvelgr** [comment]
das ist aber kein emote, da sich ein emote aiuch im chat niederschlägt. 

ausserdem ist dann der bugreport falsch. denn diese aktion sollte nur dann erscheinen, wenn man mit seinem reittier steht. 
läuft man, erscheint das nicht, man springt einfach.

**Comment by dagochen** [comment]
Nachtsäbler knurren aber und gähnen nicht, oder?

**Comment by hraesvelgr** [comment]
nennt sich mountspecial, gibts in späteren addons auch als makro:
http://wow.gamepedia.com/Mountspecial

**Comment by Haudraufinix** [comment]
Emote hat nichts mit Chatnachricht zu tun. /sit ist beispielsweise auch ein Emote...

**Comment by hraesvelgr** [comment]
http://wowwiki.wikia.com/Emote

emote vs animation/action. wie du siehst hat ein emote IMMER  eine textausgabe oder eine soundausgabe nachdem(!) man einen slash-befehl eingegeben hat.
so gesehen wäre laut deiner definition und der definition des OP das  y-drücken (waffe ziehen/wegstecken) auch ein emote.

/sit ist also eine action, und kein emote :P (keine- text oder soundausgabe)


aber das ist eigentlich alles egal, es ist nun bekannt, was mit dem bugreport gemeint ist:
die mounts führen im stillstand bei drücken der spacebar keine animation mehr aus.

**Comment by Bonfuzius** [comment]
Das wird in den Patchnotes zu 2.0.1 als "known issue" aufgeführt: http://wowwiki.wikia.com/Patch_2.0.1
"The Kodo mount is missing an idle spacebar animation. "

Von daher halte ich es für sehr unwahrscheinlich, daß dies in 1.12 funktioniert hat. Wenn die Animation im Client gar nicht vorhanden sein sollte, dürfte das auch nicht zu fixen sein.

**Comment by dagochen** [comment]
Dann mache ich hier mal zu.
