### ISSUE TITLE
Magier: Arkane Konzentration

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#907]
**Welches Verhalten wird beobachtet?**

Das Arkantalent "Arkane Konzentration" wird erst verbraucht wenn ein Zauber das Ziel getroffen hat.

**Wie sollte es sich verhalten?**

Der Proc sollte nach dem **Wirken** und nicht nach dem Einschlag eines Damagezaubers verbraucht werden.

**Schritte zur Reproduzierung**

Das Talent skillen und Hasen vor Stormwind mit Zaubern penetrieren.

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

Arkane Konzentration Buff:
1 http://datenbank.welli-it.de/?spell=11213
2 http://datenbank.welli-it.de/?spell=12574
3 http://datenbank.welli-it.de/?spell=12575
4 http://datenbank.welli-it.de/?spell=12576
5 http://datenbank.welli-it.de/?spell=12577

**Comment by dagochen** [comment]
"after any damage spell hits a target"

**Comment by ircfelix** [comment]
Gives you a 10% chance of **entering a Clearcasting state after any damage spell hits a target**.

vs.

The Clearcasting state reduces the mana cost of your next damage spell by 100%.
Das Arkantalent "Arkane Konzentration" wird erst **verbraucht** wenn ein Zauber das Ziel getroffen hat.


Wer lesen kann ist klar im Vorteil. Auch wenn man Celly heißt.

**Comment by dagochen** [comment]
Ok, den Unterschied zwischen verbrauchen und erhalten habe ich nicht beachtet :/ Da war ich zu misstrauisch :(

**Comment by Gnomorus** [comment]
*The Clearcasting state reduces the mana cost of your next damage spell by **1000%.***

**Comment by wahaxlekuke** [comment]
Kann ich ich nicht reproduzieren - Den Freizauber-Buff bekommt man, sobald man ein Gegner trifft und verschwindet wieder, wenn nachdem man den nächsten Zauber gecastet hat.

**Comment by ircfelix** [comment]
Ich check das gleich mal daheim :) wurd mir schob mehrfach so erzählt und ich hab selber noch nich drauf geachtet.

**Comment by ircfelix** [comment]
Also es is so:

Cast 1 trifft das Ziel -> Arkane Konzentration wird aktiv
Cast 2 wird gezaubert -> Arkane Konzentration bleibt
Cast 3 wird gezaubert -> Arkane Konzentration wird verbraucht

**UND**

Cast 1 trifft das Ziel -> Arkane Konzentration wird aktiv
Cast 2 wird gezaubert -> Arkane Konzentration wird verbraucht

Beides wurde heute im Raid beobachtet und vermutlich wurde deshalb darauf geschlossen dass erst beim Treffer von Cast 2 der Buff verschwindet.
