### ISSUE TITLE
Sweeping Strikes + Whirlwind

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#909]
Sweepings Strikes in Kombination mit Wirbelwind erhält bis zu 4 Extraschläge und entfernt bis zu4 Aufladungen der Sweeping Strikes. Man sollte grundsätzlich nur 1 Extraschlag erhalten und nur 1 Aufladung sollte verbraucht werden.

http://wowwiki.wikia.com/Patch_1.10.0

Whirlwind - When this ability is used with Sweeping Strikes, it will burn only one charge of Sweeping Strikes and will generate only one additional attack. 

http://datenbank.welli-it.de/?spell=12292 (Sweeping Strikes)
http://datenbank.welli-it.de/?spell=1680 (Whirlwind)

**Comment by Sabbaer** [comment]
das ist ja mal wirklich heftig. Sollte behandelt werden wie der sdb fix, der 3 stunden nach report live ging! und dass das kein krieger reported hat find ich noch viel schlimmer

**Comment by Testear** [comment]
https://www.youtube.com/watch?v=YxgylTQ5FoA

**Comment by Testear** [comment]
Das ist in der Tat ziemlich heftig.

**Comment by Seniorash** [comment]
Fass dir mal an die eigene Nase =)

**Comment by Sabbaer** [comment]
zwecks was?
