### ISSUE TITLE
Hexenmeister/Wichtel

### ISSUE THREAD

**Issue by harkes** [ClassicWoW/Nefarian_1.12.1_Bugtracker#911]
Der Wichtel greift die mobs nicht an, bzw er macht gar nichts man muss alles manuel drücken

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/84

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/711

**Comment by harkes** [comment]
auf automatisch stellen geht nicht habs schon versucht kenne normalerweise
den hexenmeister schon, wichtel schon mehrmals neugerufen usw also es ist
nur punkt 4 in 711

2015-07-10 13:40 GMT+02:00 hraesvelgr <notifications@github.com>:

**Comment by harkes** [comment]
habs hinbekommen, war doch mein fehler sollte mal rechtemaustasten
benutzten :)

Am 10. Juli 2015 um 16:24 schrieb Martin Harke <harkone78@gmail.com>:
