### ISSUE TITLE
Zandalarianisches Heldenamulett

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#912]
Fehler:
http://datenbank.welli-it.de/?item=19950
Die Aufladungen vom Amulett verschwinden, sobald man AoE macht (wenn man 16 Aufladungen hat sind z.B  mit einem Kältekegel alle 16 Aufladungen weg wenn man 16 Gegner trifft).

Das sollte nicht sein, wenn man 1x Castet sollte eine Aufladung verschwinden egal wieviele Gegner man Trifft, hier in dem Video ist es auch gut zu sehen:
https://www.youtube.com/watch?v=3O_pNDc73MM
http://www.gamewatcher.com/videos/world-of-warcraft-video/13764 ( in dem hier is der Upload 2006 Qualität is nicht so gut deshalb oben das von Youtube )

**Comment by ircfelix** [comment]
Ist beim Talisman of Ascendance auch so.

**Comment by dagochen** [comment]
Vermutlich ähnlicher Fehler, wann und wie Aufladungen verschwinden wie beim Magier und beim Jäger mit Wutgeheul. Scheint ein allgemeines Problem zu sein.
