### ISSUE TITLE
Käfer von Solenor nicht gegen Salve anfällig

### ISSUE THREAD

**Issue by CplBasti** [ClassicWoW/Nefarian_1.12.1_Bugtracker#913]
Welches Verhalten wird beobachtet?
Die Käfer die Solenor während des Kampfes spawnt, nehmen kein Schaden von Salve.

Wie sollte es sich verhalten?
Die Käfer von Solenor sollten normalerweise Schaden durch Salve erhalten.

Schritte zur Reproduzierung
Kampf eintreten, warten bis Käfer spawnen, Sann salve.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=8CRE5aLR7Tw

**Comment by dagochen** [comment]
du meinst: https://www.youtube.com/watch?v=8CRE5aLR7Tw

**Comment by CplBasti** [comment]
Okay, gerade nochmal getestet bei mir. Sie nahmen kein Schaden. Konnte leider kein Video machen, weil ichs verpeilt hab.

**Comment by dagochen** [comment]
meld dich mal ingame bei mir (Celly)

**Comment by dagochen** [comment]
http://www.twitch.tv/dagochen/b/677397159

Bei 1:26 sieht man Salve funzt.

**Comment by CplBasti** [comment]
Okay, komisch. Aber danke für das Video, spart mir die Arbeit :D

Kann dann also zu.
