### ISSUE TITLE
Käfer von Solenor zu schnell

### ISSUE THREAD

**Issue by CplBasti** [ClassicWoW/Nefarian_1.12.1_Bugtracker#914]
Welches Verhalten wird beobachtet?
Die Käfer die Solenor während des Kampfes spawnt, sind im Vergleich zum Offi zu schnell.
Im Moment rennen sie ungefähr so schnell wie der Spieler. Im Video unten sieht man aber dass sie viel viel langsamer sind.

Wie sollte es sich verhalten?
Sie sollten langsamer rennen, ungefähr die Hälfte von dem was sie gerade an Geschwindigkeit haben.

Schritte zur Reproduzierung
Einfach mal schauen wie schnell sie rennen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://www.youtube.com/watch?v=8CRE5aLR7Tw

**Comment by dagochen** [comment]
du meinst : https://www.youtube.com/watch?v=8CRE5aLR7Tw

**Comment by CplBasti** [comment]
Danke für den Hinweis mit dem Video, kein Plan wie das andere reingekommen ist....

Ich teste das heute nochmal eingiebig und mache Videos.

**Comment by CplBasti** [comment]
Soi, habs grad nochmal gemacht, aber verpeilt Video zu machen.
Aber: Einige Käfer haben die richtige Geschwindigkeit. Wenn aber ab Mitte des Kampfes wieder Käfer spawnen, sind die unglaublich schnell, schneller als die die am Anfang des Kampfes gespawnt sind.

Ich geb die Quest mal noch nicht hab, dann kann ich den Dämon morgen nochmal ansprechen um Video zu machen.

**Comment by Rushor** [comment]
speed messen:

/run ChatFrame1:AddMessage(format("Geschwindigkeit: %.2f%%", GetUnitSpeed("player")/0.07))

**Comment by dagochen** [comment]
@Rushor Added with WoW 3.0

**Comment by dagochen** [comment]
Ja, grad paar Tests gemacht und das Speed angepasst.
Beim Video https://youtu.be/s0B-Skd7jeA?t=1m10s spawnen die Käfer bei 1:12 und sind bei 1:22 beim Jäger. Habe die Positionen nachgestellt und am Käfer-Speed bisschen gedreht, bis die auch 10 Sekunden brauchen für die Distanz. Aktuell brauchen sie auf Nefarian nur ca. 7 Sekunden für die Distanz.

**Comment by CplBasti** [comment]
Top!
