### ISSUE TITLE
Hügel der Klingenhauer - Tuten Kash kommt nicht [Die Zweite]

### ISSUE THREAD

**Issue by suddenrage** [ClassicWoW/Nefarian_1.12.1_Bugtracker#915]
Im Hügel der Klingenhauer funktionier der Gong nicht. Es erscheinen keine Spinnen und somit auch Tuten Kash nicht.
Normalerweise muss man den Gong 3 mal schlagen, und 3 Gegnerwellen besiegen.

Sehr schade.

Gruß

Ps: Hab es einfach mal kopiert weil das Problem immer noch besteht.
Eine Script Lösung (scripted in mangos/ScriptDev3@f4fde81 ) dazu wurde zwar geposted aber anscheinend funktioniert es immer noch nicht.

lg

**Comment by wahaxlekuke** [comment]
Das Ticket wurde geschlossen, weil es für diesen Bug schon ein anderes offenes Ticket gibt (#220).
