### ISSUE TITLE
Zauberkoeffizient Mind Flay 

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#917]
Mit Patch 2.0.1 wurden die Koeffizenten von Kanalisierungszauber überarbeitet.

*HoTs, DoTs, and channeled spells have been re-balanced to receive a more appropriate (higher) percentage of +spell damage and +healing.*  http://wowwiki.wikia.com/Patch_2.0.1

**Welches Verhalten wird beobachtet?**
   Mind Flay skaliert momentan mit 0,57 / 3 Ticks = 0,19 pro Tick. http://pastebin.com/2EuNW40i. 
   Dies entpricht auch genau den Beobachtungen bei Elite-Jerks
   vom 14.12.2006 - also nach release von Patch 2.0.1 der am 05.12.2006 war.
   http://forums.elitistjerks.com/topic/9354-damage-coefficients/

**Wie sollte es sich verhalten?**
   Theoriecraft (Addon) gibt eine Saklierung von 0,45 an. Der User Snowy von Elite Jerks hat am 20.09.2006 Mind Flay getestet und kommt auch auf eine Skalierung von 0,45-0,46. Den Test hat er kurz vor Patch 1.12.1 gemacht http://forums.elitistjerks.com/topic/8334-mind-flay-how-much-does-it-benefit-from-spell-damage/?p=203137

**Zusätzliche Informationen**
Zauber von anderen Klassen habe ich nicht getestet. Denke aber das z.b. Arkane missels auch zu hoch skaliert.

**Comment by ircfelix** [comment]
Ah da will jemand weniger Damage machen! Nobel! Nobel! So eine ehrliche Haut!
