### ISSUE TITLE
BRD: Spawnpunkt Dunkelbewahrer Bethek

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#918]
So ist es: Dunkelbewahrer Bethek (http://datenbank.welli-it.de/?npc=9438) spawnt bei Öffnung des Porträits im Tresor zusammen mit zwei Dunkelwachen (http://datenbank.welli-it.de/?npc=9445) in der Taverne auf dem Spawnpunkt von Dunkelbewahrer Vorfalk.
Die restlichen Dunkelbewahrer 
Dunkelbewahrer Ofgut (http://datenbank.welli-it.de/?npc=9442)
Dunkelbewahrer Pelver (http://datenbank.welli-it.de/?npc=9443)
Dunkelbewahrer Uggel (http://datenbank.welli-it.de/?npc=9439)
Dunkelbewahrer Vorfalk (http://datenbank.welli-it.de/?npc=9437)
Dunkelbewahrer Zimrel (http://datenbank.welli-it.de/?npc=9441)
spawnen an den korrekten Orten mit jeweils zwei Wachen. Alle Dunkelbewahrer sind dem Spieler gegenüber neutral eingestellt. DIe Wachen sind dem Spieler gegenüber feindlich eingestellt.

So sollte es sein:
Alle Dunkelbewahrer sollten dem Spieler gegenüber feindlich eingestellt sein. Das Pullen von Dunkelbewahrer Vorfalk sollte umliegende Gäste der Bar mitaggron. Dunkelbewahrer Bethek spawnt zusammen mit 4 Wachen direkt am Tresoreingang und läuft dann Richtung Schließfächer statt einem Spawn in der Bar.

Quelle:http://wowwiki.wikia.com/Dark_Coffer und die jeweiligen Einträge über die Dunkelbewahrer, die im Artikel gelinkt sind.

**Comment by Gnomorus** [comment]
#541

**Comment by Dotox** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/1008
