### ISSUE TITLE
BRD: Stöpsel Zapfring - falsche Ausrufe

### ISSUE THREAD

**Issue by g3n3a** [ClassicWoW/Nefarian_1.12.1_Bugtracker#919]
Stöpsel Zapfring ruft gelegendlich Dinge quer durch die Instanz. Die ergeben allerdings keinen Sinn und passen eher zu einem Oger (Grammatik).
Richtige Ausrufe (Englisch):

Plugger Spazzring says:

    Try the boar! It's my new recipe!
    Enjoy! You won't find better ale anywhere!
    Drink up! There's more where that came from!
    Have you tried the Dark Iron Ale? It's the best!

Plugger Spazzring yells:

    What are you doing over there?
    Hey! Get away from that!
    No stealing the goods!
    That's it! You're going down!
    Hey, my pockets were picked!
    That's it! No more beer until this mess is sorted out!

**Comment by nightblizard** [comment]
Die Texte sind insofern falsch, dass sie in dem Gossip Menu stehen müssten, anstatt gerufen zu werden. Keine Ahnung warum ich das vor 2 Jahren so eingebaut habe.

**Comment by g3n3a** [comment]
Das kommt hinzu ;)
