### ISSUE TITLE
Uldaman ''Die Platinscheiben'' quest

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#92]
Welches Verhalten wird beobachtet?
- Nach dem annehmen der Quest bei   ''Scheiben von Norgannon'' soll man mit dem Steinbehüter Sprechen der normaler weise direkt Links neben Scheiben von Norgannon auftauchen soll als hologram. Dort befindet sich momentan kein Npc zum beenden der Quest.

Wie sollte es sich verhalten?
- nach der Annahme der Quest die Platinscheiben redet man mit dem  Steinbehüter. ''Sprecht mit dem Steinbehüter und findet heraus, welche uralten Lehren er aufbewahrt. Sobald Ihr alles erfahren habt, was er weiß, aktiviert die Scheiben von Norgannon''. Diese schickt einen dann mit einer folge  Quest weiter nach Ironforge mit der miniatur ausgabe der Platinscheiben.

Schritte zur Reproduzierung
-den Npc als hologram anzeigen.
Sprecht mit dem Steinbehüter und findet heraus, welche uralten Lehren er aufbewahrt. Sobald Ihr alles erfahren habt, was er weiß, aktiviert die Scheiben von Norgannon.

**Comment by ErnisKommentar** [comment]
Bei euch existiert ein Script-Dungeon-Eintrag in der DAtenbank? Wie dem auch sei. DAs hat was mit dem Gameobject_Scripts zu tun. Ihr müsst das richtige GAmeobject ausfindig machen und dann das richtige Script dazu schreiben. Viel Spaß. Dürfte als GM mit dem Befehl .gps eigentlich kein Problem sein. DBCUtil wäre auch nicht verkehrt um die Datenbanken in ein Format zu transformieren, dass man lesen kann.
