### ISSUE TITLE
Jäger: Pet verschwindet, keine Treuestufe

### ISSUE THREAD

**Issue by exsangius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#920]
Das Tier des Hunters (bisher mehrere) verschwindet zufällig ohne Grund, obwohl es zufrieden ist. Zusätzlich gewinnt das Pet keine Treuestufe durch Questen oder ausgiebiges Füttern.

Tharul, Troll Hunter LvL 13+14, 17+18

**Comment by exsangius** [comment]
Pet hat sich in Treuestufe gedowngraded (von Treue 2 auf Treue1) und hat -17 Ausbildungspunkte bekommen? Nicht gestorben/grüne Zufriedenheit

**Comment by Agorass** [comment]
Kann ich bestätigen

**Comment by exsangius** [comment]
Und erneut verschwunden :/

**Comment by wahaxlekuke** [comment]
In der Datenbank steht, dass dein Tier unzufrienden war. 

Gibts du deinem Tier auch Futter mit der passenden Stufe? (Niedrigstufiges Futter bringt weniger Zufriedenheit) 
Benutzt du vielleicht irgendwelche Addons, die die Zufriendenheit falsch anzeigen? Oder schaust du vielleicht auf das Symbol im Charakter-Fenster (unter Begleiter)? Das ist keine Anzeige für die Zufriedenheit.

**Comment by exsangius** [comment]
Merkwürdig, ich hab ein Addon bei dem nach Zufriedenheit die HP Leise Grün, Gelb oder Rot ist. Danach habe ich mich bisher gerichtet, aber vielleicht ist es ja falsch ... aber merkwürdig dass sich das PEt in Zufriedenheit downgraded? Da weiß ich nicht ob das normal ist

**Comment by Haudraufinix** [comment]
Das Pet verliert solange es den Status "Unzufrieden" hat, Treuepunkte. Wenn die Treuepunkte 0 erreichen verlässt das Pet seinen Hunter - für immer. Treuepunkte hängen auch direkt mit dem Treuelevel zusammen. ein Pet das Treuestufe 6 (Bester Freund) hat, wird erst langsam zurück auf Treuestufe 1 (Rebellisch) fallen bevor es dich verlässt.

Downgraden der Treuestufe kannst du also verhindern in dem du es immer zufrieden hälst. Wärend du ihm am Anfang noch Stackweise Futter in den Rachen werfen musst hast du es nach wenigen Spielstunden auf Treuestufe 6 und es braucht fast kein Futter mehr.


Zu den Ausbildungspunkten:
Ein Pet kann mit Treuestufe 6 und lvl 60 satte 300 Ausbildungspunkte haben.müsste also etwas in der Art von folgender Formel sein (Spekulativ habs nie genau nachgeprüft):
Petlvl*5 / 6*treuestufe
Manche Pets besitzen aber von Haus aus skills wie Klaue, Sprint oder Biss. Diese Skills kosten auch von den Ausbildungspunkten. werden aber direkt von diesem Grundbudget abgezogen. Sagen wir dein Pet ist also lvl 40 und Treuestufe 1 (33 Ausbildungspunkte) und kann einen Skill der 50 Ausbildungsunkte kostet - bleiben am ende -17 Ausbildungspunkte übrig.
