### ISSUE TITLE
Siphon Life / Lebensentzug

### ISSUE THREAD

**Issue by Desmodai** [ClassicWoW/Nefarian_1.12.1_Bugtracker#921]
Heyho Community.
Hab eben mal etwas mit Siphon Life rumexperimentiert.
Zu den Fakten: 
Siphon Life mit 0 Spelldmg tickt alle 3 Sekunden für 49-50 DMG.
Siphon Life mit 540 Spelldmg tickt alle 3 Sekunden für 75-76 DMG.
Siphon Life hält 30 Sekunden, also ergeben sich 10 ticks.
Subtrahiert man nun die 0er ticks von den 540er ticks ergibt sich ein DMG unterschied von ~ 26-27 DMG.
27 DMG mal 10 ticks ergibt 270 DMG. 
In diesem Fall genau 50% der 540 Spelldmg.
Habe dann mal die elitist jerks Spellkoeffizienten von 2006 aufgeschlagen und siehe da:
laut deren Aufzeichnungen sollte Siphon Life einen 100% Koeffizienten haben.
Ergo : Siphon Life macht zu wenig DMG.

Könnt ihr euch das mal ansehen ?

Link zu elitist jerks: 
http://forums.elitistjerks.com/topic/9354-damage-coefficients/
Posted 14 December 2006 - 01:56 AM

**Comment by wahaxlekuke** [comment]
> 7) If it does both damage and healing (life tap, devouring plague etc), multiply by 0.5. (NOTE: only in some cases - compare life tap, siphon life, drain soul, vampiric touch etc.)

**Comment by 0815Priester** [comment]
Nochmal,diese Liste von Elite Jerks betrifft den Patch 2.0.1 also TBC. Und mit 2.0.1 wurden eben 
HoTs, DoTs, and channeled spells überarbeitet.

**Comment by Larnak1** [comment]
In der Quelle tauchen auch schon die ganzen TBC-Zauber auf.

**Comment by Desmodai** [comment]
der punkt 7 den wahax aufführt is in den 100%  weiter unten in der liste schon mit einberechnet. 
Siphon life - 100% (30/15 * 0.5 - both healing and damage)
also dot dauer / 15 * 0.5 multiplicator

finds halt seltsam dass corruption zum beispielt bei etwa 100% liegt und siphon life nur bei 50%

**Comment by Desmodai** [comment]
ok hab nochma weitergesucht
ich lag falsch.

hier mal eine auflistung der spells mit 1.12

http://wowwiki.wikia.com/Spell_damage_comparison?oldid=256167

**Comment by 0815Priester** [comment]
Wenn man nach der Liste geht http://wowwiki.wikia.com/Spell_damage_comparison?oldid=256167
müssten Arcane Missiles auch geändert werden.

**Comment by wahaxlekuke** [comment]
Weil die Änderungen zu TBC explizit markiert sind, denke ich, dass der Koeffizient auch schon zu classic 100% war. (Das würde auch zu der in der Quelle genannten Formel passen, die auch bei den anderen spells funktioniert.)
Allerdings wäre noch eine weitere Quelle nicht schlecht, weil z.B. auch das theorycraft addon nur 50% als Koeffizient angibt.

**Comment by Larnak1** [comment]
Meinst du die Dotdauer / 15-Formel?
Soweit mir bisher bekannt war, kann die nur bis höchstens 1 gehen, sprich alles was länger als 15 Sekunden dauert, wird "bestraft" und gleich 1 gesetzt, so wie es auch bei Zaubern mit Castzeit über 3,5 Sekunden ist. Darunter "leidet" beispielsweise auch Nachwachsen, was durch die lange Dauer von 21 Sekunden pro einzelnem Tick nur noch relativ wenig Addheal bekommt.
Schade dass die wowwiki-Tabelle nur Schadenszauber enthält...

**Comment by Sabbaer** [comment]
was sollte denn dein lebensentzug deiner meinung nach an schaden machn? in allen videos die ich finde mit sehr guten hexxern zu patch 1.12.1 ist das alles sehr konform mit dem was du hier an werten angibst.

 Außerdem hab ich mit meinem hexxer getestet und wenn ich das trinket aus mc zünde hab ich auch ganz gute spdmg werte, die mir die gleichen werte bringen, die leute in classic videos zeigen

**Comment by wahaxlekuke** [comment]
Ich mach hier dann mal zu, weil sich ja offensichtlich alle einig sind, dass es nur 50% sein sollten.

**Comment by 0815Priester** [comment]
Jo 50% 
http://forums.elitistjerks.com/topic/9052-spell-damage-scaling-in-tbc/?p=239683
