### ISSUE TITLE
Arlokk Pyramide Map/ AE 

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#922]
Höllenfeuer wirkt statt nur auf der Fläche, auch durch Böden oder Brücken nach unten und vermutlich auch nach oben.

http://datenbank.welli-it.de/?spell=11683

Reproduktion/ Bericht:

Gestern Abend in Zul Gurub hat unser Hexenmeister auf der Pyramide von Arlokk mit Höllenfeuer die Bluttrinker-Patrouille unter uns geaddet. Als wir das dann getestet haben (auf der Brücke in der Etage wo die beiden Bluttrinker patrouillieren), haben wir die Gruppe die ganz unten steht mit Höllenfeuer gepullt.
Selbiges kann ein Paladin wohl auch mit Weihe.

Keine Ahnung ob das nun beabsichtigt ist oder nicht - Wir fanden es seltsam.

**Comment by hraesvelgr** [comment]
die pyramide hat generell ein ziemlich abgedrehtes mapping, das liegt nicht direkt an hellfire, sondern eher an der pyramide selber.

**Comment by Testear** [comment]
Das würde mich wundern, da ich das in >50 ZG Runs noch nie beobachtet habe.
Mir ist aber noch keine andere Stelle eingefallen, an der man das testen kann um die Pyramidenmap auszuschließen.

**Comment by Testear** [comment]
Heute habe ich den Tipp bekommen, dass ein Paladin und ein Mage ebenso an diesen Stellen durch den Boden/ die Decke bomben können. Es dürfte als wirklich an der Pyramide liegen.

**Comment by wahaxlekuke** [comment]
Ich schätze mal, das Problem liegt darin, dass bei den Fähigkeiten nicht überprüft wird, ob das Ziel im Sichtfeld ist.
Zumindest ist das nicht die einzige Stellen, wo man mit diesen Zauber Gegner durch Wände pulln kann.

**Comment by Sabbaer** [comment]
jo, hatte mit weihe in der pyramide schonmal das gleiche problem

**Comment by Testear** [comment]
:D it´s not a bug - it´s a feature

**Comment by g3n3a** [comment]
Ach früher hat fast jeder AoE durch Decken und Wände gepullt. War besonders lustig in Scholomance...
Haben sie dann irgendwann mal gefixt.

**Comment by hraesvelgr** [comment]
ich kenns halt auch von anderen servern. das gesamt pathfinding- und LOS-system in der pyramide ist extrem abgedreht und verbuggt, wobei es auf diesem server im gegensatz zu anderen servern echt harmlos ist und mir nie so krass ins auge fiel.

**Comment by Haudraufinix** [comment]
Das Problem sind in der Regel Zauber, die über einen Bodeneffekt Schaden machen; Sprengfalle, Flammenschlag, Weihe und Höllenfeuer wären da die prominentesten vertreter. Dieser Debuff ignoriert nämlich Sichtfeld und tickt auch ein Stockwerk über dem Caster noch.

Soweit zumindest was ich beobachten konnte.

**Comment by hraesvelgr** [comment]
@Haudraufinix 
schon, aber mir ist es (zb mit weihe) nie aufgefallen. hab damit in einem dungeon noch nie fehlerhaft gepullt, und ich benutze weihe als tank oft. waren letztens im tempel, und die ini ist verdammt verschachtelt. absolut keine probleme, trotz weihe-spam. auch in anderen inis hab ich das auf diesem server nie beobachtet. 
ausser eben in der pyramide.
