### ISSUE TITLE
E'ko der Winterfelle Droprate

### ISSUE THREAD

**Issue by VenomXDE** [ClassicWoW/Nefarian_1.12.1_Bugtracker#923]
Hallo, 

es scheint, als wäre die Droprate der E'ko der Winterfelle extrem schlecht und das ist meiner Erinnerung nach auf dem offiziellen Server nicht der Fall gewesen. Wie es bei den anderen E'ko aussieht, kann ich nicht sagen, da ich bisher nur die Winterfelle gefarmt habe.

Atm liegt die Dropchance zwischen 2-4 % (laut meinem Tool), Ursas haben bei mir bisher gar keines gedropt (die hatten in Classic jedoch die höchste Dropchance, abgesehen vom Häuptling). Normalerweise sollte das Item von Mauri die Dropchance irgendwo auf ca. 10 - 20 % erhöhen, was aber nicht der Fall ist.

**Comment by Seniorash** [comment]
Der Behälter ist Voraussetzung dass du ekos überhaupt loten kannst. Ich habe bereits über 1k ekos gefarmt und kann die dropraten aus der Datenbank bestätigen (Ursas habe die größte droprate). Wie hoch diese sein sollten weiß ich nicht und da müsste man eine entsprechende Quelle suchen

**Comment by VenomXDE** [comment]
Also ich habe den Behälter von Mauri in Bag 1. Ich kann nur sagen, was mein Tool mir ausgibt, also scheint es doch irgendeinen Fehler zu geben. Wann hast Du denn das letzte Mal gefarmt?

**Comment by Gnomorus** [comment]
"so viel ich noch weiß" = das ganze hier wird keine beachtung finden

**Comment by VenomXDE** [comment]
Also wenn mir als langjähriger Classic-Spieler auffällt, dass Items, die ich damals als Progressraider dauerhaft gefarmt habe, bedeutend schlechter droppen als damals, dann kann man das als schon als gewissen Wert nehmen. Ich bin doch nicht der Serverbetreiber, der dafür zu sorgen hat, dass die Datenbanken stimmen. Wenn man so was betreibt, dann sollte man man die entsprechenden Lootlisten mit der Droprate vorliegen haben (siehe z.B. Spelldmg-Rogue, genau das gleiche)

**Comment by Larnak1** [comment]
Nein, kann man nicht, da Erinnerungen trügerisch sind. Du brauchst eine Classic-Quelle. Der Behälter hat auch früher nicht die Chance erhöht, sondern überhaupt erst ermöglicht, die Dinger zu finden ("This Item drops of various kinds of Winterfall furbolgs in Winterspring if you have the Cache of Mau'ari in your inventory", http://wowwiki.wikia.com/Winterfall_E%27ko?oldid=295347 ). Dass du dich daran nicht mehr erinnerst, zeigt, warum hier Quellen gebraucht werden :)

Dein Addon brauchst du übrigens nicht, steht alles hier:
http://datenbank.welli-it.de/?item=12431

**Comment by VenomXDE** [comment]
Also, damit man den Behälter überhaupt erst bekommt, muss man E'ko abgeben oder nicht? Also, sofern die E'ko nicht droppen, wenn man den Behälter nicht hat, kann man die Quest nicht erfüllen oder? ;)

**Comment by VenomXDE** [comment]
http://www.wowhead.com/item=12431/winterfall-eko#comments

**Comment by Larnak1** [comment]
Ah, den hab ich übersehen :)

**Comment by ircfelix** [comment]
Farm die einfach mit mehreren chars gleichzeitig (z.B. nach ony/mc mit deinem Raid noch kurz Ekkos farmen = 40 ekkos gelootet anstatt einem)

**Comment by VenomXDE** [comment]
Das ist mir klar dass das so geht. Aber es ändert ja nichts an den mangelhaften Drops.....

**Comment by dagochen** [comment]
UPDATE creature_loot_template SET ChanceOrQuestChance = 15 WHERE entry in (7438, 7439, 7440, 7441, 7442, 10916) AND item = 12431;

UPDATE creature_loot_template SET ChanceOrQuestChance = 30 WHERE entry = 10738 AND item = 12431;
