### ISSUE TITLE
[Druide] [PvP] kein Aufbau von Kombopunkten in Katzengestalt

### ISSUE THREAD

**Issue by Tuary** [ClassicWoW/Nefarian_1.12.1_Bugtracker#924]
Titel: [Druide] [PvP] kein Aufbau von Kombopunkten in Katzengestalt

Welches Verhalten wird beobachtet?

Kombopunkte aufbauende Angriffe eines sich in Katzengestalt befindenden Druiden bauen im PvP keine Kombopunkte auf. Wird ein Gegner z.B. mit 'Klaue' angegriffen, so wird zwar der Schaden verrechnet, allerdings kein Kombopunkt auf dem Gegner gutgeschrieben, was am nicht erscheinenden roten Punkt am Rand des gegnerischen Potraits erkennbar ist. Das Fehlen der roten Punkte ist nicht nur visuell. Beim Versuch einen Finisher anzusetzen erscheint die Meldung "Das könnt ihr noch nicht".

Wie sollte es sich verhalten?

Kombopunkte aufbauende Angriffe sollten auch Kombopunkte aufbauen und den Einsatz eines Finishers ermöglichen.

Schritte zur Reproduzierung

Ehrlich gesagt: Keine Ahnung. Mal funktioniert es für zwei Gegner, dann die nächsten 10 Minuten wieder nicht, dann doch wieder für ein paar Gegner. Ob das Problem auch im PvE auftritt, kann ich nicht sagen, da ich auf dem Server nur noch hin und wieder mal ein paar BGs spiele.

Video:
(Das eingebettete Video ist von der Quali besch...eiden, falls notwendig also die Originaldatei downloaden)

https://www.dropbox.com/s/g177q5t1lugx6ln/druid_combo_bug.mp4?dl=0

Folgender Ablauf: Opener mit Anspringen (1 KP) - Schreddern (Miss: 0 KP) - Klaue Crit (2 KP - wegen dem Blutraserei Talent) - Klaue (1 KP)

Es müssten sich also vier Kombopunkte auf dem Ziel befinden - es sind aber null.

Links:

Katzenform: http://datenbank.welli-it.de/?spell=768
Klaue: http://datenbank.welli-it.de/?spell=9850
Schreddern: http://datenbank.welli-it.de/?spell=9830
Anspringen: http://datenbank.welli-it.de/?spell=9827
Verheeren: http://datenbank.welli-it.de/?spell=9867
Wilder Biss: http://datenbank.welli-it.de/?spell=22829

**Comment by hraesvelgr** [comment]
kansnt du bitte das ganze nochmal ohne interface-addons machen? der bug ist bisher niemandem aufgefallen, und wahax/nightblizzard hat jetzt auch nicht soo viel an dem core rumgebastelt. so ein gamebreaking bug für druiden wäre also schon länger da und längst aufgefallen. es leveln ja auch etliche leute als druiden. (pve dann)
mach das ganze bitte nochmal komplett ohne addons, und lösch den WDB ordner vor dem nächsten mal spielen (wenn wow geschlossen is, logisch)

ansonsten brauch das evtl noch bestätigung von anderen.

**Comment by dagochen** [comment]
hab mit meinem dudu grad mal paar runden gemacht, bei mir ist der fehler nicht aufgetreten.

**Comment by Tuary** [comment]
Hi,

hab's nochmal ohne Addons probiert und so funktioniert alles.
Ich guck mal wer der Übeltäter ist und schreib es dann hier rein.

Sorry für eventuell entstandene Mühen, aber ich hätte nicht gedacht, dass sowas von einem Interface Addon verursacht werden kann.

Beste Grüße

**Comment by dagochen** [comment]
Wärs kein Addonproblem hätten sich bestimmt schon viel mehr Druiden gemeldet ;)

**Comment by WCPaco** [comment]
Ich kenne das Problem auch nicht und nutze sämtliche gängige Addons, muss also was exotischeres sein :p 

Gruß Paco

**Comment by Tuary** [comment]
Okay, das Problem lag an Improved SRaidFrames, welches einen Range Check integriert hat und wahrscheinlich zu dem Verhalten führte.

Grüße
