### ISSUE TITLE
Jin'do der Verhexer Manakostenfehler

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#925]
Der Bossmob in ZG Jin'do der Verhexer hat zwar eine Manaleiste und gibt auch fröhlich Mana für Gehirnwäschetotem sowie seinen Grossen Heilzauberschutz aus, jedoch zaubert er diese auch noch, wenn er gar icht genügend Mana dafür besitzt.

Die betroffenen Zauber:
Heiltotem: http://datenbank.welli-it.de/?spell=24309 und http://datenbank.welli-it.de/?npc=14987
Gehirnwäsche Totem: http://datenbank.welli-it.de/?spell=24262 und http://datenbank.welli-it.de/?npc=15112

Reproduzieren:
Jin'do so lange bekämpfen / Manadrainen bis ihm das Mana ausgeht.

**Comment by hraesvelgr** [comment]
liegt das daran, dass eventAI die totems zaubert, und nicht der boss selber?

**Comment by Haudraufinix** [comment]
Würd ich spontan auch drauf Spekulieren, denn wenn er zu wenig Mana hat fällt er einfach auf 0 Mana zurück, das riecht schon nach nem Event, sicher sagen kann ichs leider nicht

**Comment by dagochen** [comment]
Heiltotem:
Kosten	200 Mana
Gehirnwäschetotem:
Kosten	Keine

Naja und er wird vermutlich immer so 200+ Mana reggen und dann direkt das Healtotem hinstellen.

**Comment by hraesvelgr** [comment]
http://guildhouse.net/yabbse/index.php?topic=3609.msg%msg_id% hier is nochmal ein schöner guide.

da steht sogar drin, dass die shades definitiv schattenschaden machen (was sie meiner meinung gnicht tun auf dem server.

anyway, wenn so viele leute früher manadrain verwendet haben, soltl das ja schon ein zeichen dafür sein, dass es wirklich einen impact auf den kampf hatte. wenn jindo bei uns weiterhin fröhlich totems stellt, in der gleichen frequenz, dann reggt er entweder zuviel mana, oder es ist ein eventAI problem...

**Comment by dagochen** [comment]
Ändert sich bald ;)

**Comment by hraesvelgr** [comment]
uh ja bitte *-*

**Comment by Haudraufinix** [comment]
Jindo regeneriert kaum Mana, der hat teilweise mit 17 Mana noch ein Heiltotem gestellt.

**Comment by dagochen** [comment]
Hier bitte auch zu machen, sollte mit dem überarbeiteten Jindo-Script gefixt sein @Dotox
