### ISSUE TITLE
Paladin/Krieger Zweihandwaffenspezialisierung

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#926]
Das Talent Zweihandwaffenspezialisierung vom Paladin und Krieger erhöht den Schaden von Einhandwaffen statt nur den Schaden von Zweihandwaffen. Beim Krieger wird auch der Fernwaffenschaden erhöht.

Reproduzierung:

Zweihandwaffenspezialisierung skillen, eine Einhandwaffe anlegen und im Charakterfenster die Maus über das Waffenschadentooltip bewegen. 
Statt 100% werden dort beim Paladin 106% und beim Krieger 105% Waffenschaden berechnet. 
(jeweils mit voll ausgeskillter Zweihandwaffenspezialisierung)

Paladin:
http://datenbank.welli-it.de/?spell=20111
http://datenbank.welli-it.de/?spell=20112
http://datenbank.welli-it.de/?spell=20113

Krieger:
http://datenbank.welli-it.de/?spell=12163
http://datenbank.welli-it.de/?spell=12711
http://datenbank.welli-it.de/?spell=12712
http://datenbank.welli-it.de/?spell=12713
http://datenbank.welli-it.de/?spell=12714

**Comment by Sabbaer** [comment]
lol, das wusste ich nicht. gut beobachtet testear.

**Comment by g3n3a** [comment]
Setzt sich das auch in realen Schaden um, oder ist das nur ein Interface-Fehler? Davon gibts ja reichlich. Bitte mal genau testen.

**Comment by Testear** [comment]
Würde es das nicht hätte ich es nicht reportet.

**Comment by Testear** [comment]
no comment

**Comment by Testear** [comment]
wenn du es nicht glaubst teste es selber - danke

**Comment by Testear** [comment]
Genea wenn du der Meinung bist ich teste meine Reports nicht teste sie selber.

**Comment by Testear** [comment]
aktualisiert - Fernwaffenschaden wird beim Krieger auch erhöht!

**Comment by Dotox** [comment]
Bitte Links aus der Datenbank hinzufügen sonst wird das nichts.

**Comment by Testear** [comment]
done

**Comment by Bananendieb** [comment]
Betrifft auch Einhandwaffen-Spezialisierung im Schutzbaum, sämtlicher Nahkampf und Fernkampfschaden wird auf 110% erhöht.

http://datenbank.classic-wow.org/?spell=16542

**Comment by dagochen** [comment]
Der Schaden wird nicht erhöht. Lediglich die Prozente im Client werden falsch dargestellt.
