### ISSUE TITLE
Tempel: Klassenquest

### ISSUE THREAD

**Issue by Kazragore** [ClassicWoW/Nefarian_1.12.1_Bugtracker#928]
Moin liebes Classic-Wow Team!

War grad im Tempel, u.a. mit einem Krieger, der genau wie ich (hexer, jinkz) die Federn der mini-Bosse brauchte. 
Leider konnten immer nur entweder er oder ich die Federn looten. Ich bin mir aber sicher, dass es früher so war, dass jeder, der die Quest hatte, seine 6 Federn looten konnte. 
So konnte ich nur 3 ergattern, genau wie der Krieger.  
Die Instanz ist sowieso recht fehleranfällig, die Klassenquests gingen aber lange Zeit. Da jetzt nicht mal mehr die zu funktionieren scheinen.... Den Rest spare ich mir.

Lieben Gruß und bis demnächst
Jinkz
Improved
Horde

**Comment by Larnak1** [comment]
Der "Rest", von dem du sprichst, wurde vor einiger Zeit gefixt, die Instanz funktioniert einwandfrei.
