### ISSUE TITLE
Quest: Der Schattenwächter

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#929]
Welches Verhalten wird beobachtet?
Die Quest ist nur einmalig zu machen

Wie sollte es sich verhalten?
Die Quest sollte wiederholbar sein

Schritte zur Reproduzierung
Quest abschließen und versuchen erneut anzunehmen

Zusätzliche Informationen (Screenshots, Videos, etc.)
Questbelohnung ist eine Verzauberung, für Hose und Kopf mit Schattenwiderstand

Links aus unserer Datenbank (hier gehts zur Datenbank)
Quest http://datenbank.welli-it.de/?quest=9213
Item das man bekommt http://datenbank.welli-it.de/?item=22638

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/667

das suchen nach "schattenwächter" gab keine ergebnisse o.o musste nach "Naxx" suchen, um dieses report zu finden.

**Comment by Gnomorus** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues?utf8=%E2%9C%93&q=schattenw%C3%A4chter

**Comment by dagochen** [comment]
@Gnomorus  #667 

FYP
