### ISSUE TITLE
HunterQuest Dämon Winterspring

### ISSUE THREAD

**Issue by Allesodernix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#930]
Hi,

Ich habe vor ein paar Tagen den Dämon in Winterspring gelegt und er war verbuggt.

Vid: https://vimeo.com/133957579              Leider nicht so gute Qualität  aber hoffe zu erkennen.

Pw:1337

Wie in dem Video zu sehen Funktioniert er soweit richtig bis er stirbt nach dem kill despawnt er in Sekunden und  den Kopf looten kann man auch nicht. Da beim Kill von ihm nicht im Kampflog steht das ich ihn nicht (Artorius der Verhängnisvolle Stirbt) gelegt habe sondern nur das er Stirbt aber durch wen ist nicht zu erkennen. 1 Mehrfachschuss zählt er als getroffen von mir ,wie im Video zu erkennen aber das ist auch der einzigeste Skill der gewertet worden ist als Treffer von mir.

ich hoffe ihr könnt das Problem lösen.

MFg Allesodernix

**Comment by dagochen** [comment]
Hey,

der Bug davon ist bereits gefixt. Mach ein GM-Ticket oder Post im Forum, dann teilt dir ein GM den Kopf zu. Kannst auch einen der 2 Threads im Forum dazu verwenden.

Gruß,
dago
