### ISSUE TITLE
segen der opferung/schaden trotz gottesschild

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#931]
Welches Verhalten wird beobachtet?
wenn ich segen der opferung auf jemanden mache, und gottesschild anmache, bekomme ich trotzdem schaden
Wie sollte es sich verhalten?
bei gottesschild sollte man überhauptkeinen schaden bekommen
Schritte zur Reproduzierung
beschreibung zu gottesschild lesen
Zusätzliche Informationen (Screenshots, Videos, etc.)
http://community.mmobase.de/bugtracker-archiv/3061-gottesschild.html
hier auch mit photos etc
Links aus unserer Datenbank
http://datenbank.welli-it.de/?spell=1020
http://datenbank.welli-it.de/?spell=20729

**Comment by dagochen** [comment]
Nightblizard hatte im 1. Post gebeten, Quellen zu finden, nach denen Divine Shield wirklich immun gegen diese Art von Schaden macht. In dem Forumpost sehe ich leider keine dafür, nur eine Menge bestätigter Meldungen, welcher Zauber durch gehen.

**Comment by Sabbaer** [comment]
was gibs denn da für quellen anzugeben? bubble macht immun gegen alles? steht sogar so in der beschreibung? was für quellen soll ich denn nun angeben?

**Comment by Haudraufinix** [comment]
Bubble macht eben NICHT immun gegen Alles. z.B. Burning Adrenaline und meines wissens nach Verbinden Debuff werden ja auch nicht entfernt. Ebenfalls kannst du dich mit Divine Inervention selbst töten, auch wenn du eine Bubble auf dir hast.

**Comment by ircfelix** [comment]
Naja ich muss jetz schonmal für den Sabbaer Partei ergreifen. Es ist schon relativ naheliegend, dass man gegen diese Art von Schaden immun sein sollte und ihr deswegen nicht gleich auf ihn einprügeln müsst. Es ist glaube ich verständlich dass z.B. manche Bossmechaniken damit auch nicht counterbar sein sollten, da die Bosse sonst easypeasy wären.

Allerdings ist der Report wirklich ein wenig dürftig und man sollte sich doch ein wenig Mühe machen es wenigstens zu versuchen Quellen zu finden. Hast du schon den ClassicWowResearcher ausprobiert Sabber?

**Comment by Testear** [comment]
Divine Inervention macht auch keinen Schaden sondern opfert den Paladin.

Dass Babbel in Kombination mit Segen der Opferung keinen Schaden durchkommen lassen sollte ist einfach nur logisch.

**Comment by Sabbaer** [comment]
@Haudraufinix es geht hier auch nicht um einen debuff der von einem boss ausgelöst wird oder ähnliches, es geht um einen segen, den man geben kann. und in vanilla und auch später in allen addons die kamen war es gang und gebe segen der opferung zu machen und dann bubble um schaden vom tank nehmen zu können! wizo sollte dieser eine schaden durchkommen, wenn es sonst nur npc raidbosse gibt, die die bubble umgehen können mit einem ihrer effekte. Das mark bleibt übrigens erhalten wenn man bubble drückt und senkt so die maximal hp, bis man an einem feuertick nach ablauf der bubble stirbt! dies sind 2 verschiedene dinge

**Comment by Haudraufinix** [comment]
@Sabbaer Hmm haste wohl recht, dass BoS aufn Tank gewirkt wird hatte ich auch schon gehört, ich war da wohl etwas voreilig. Dennoch ist Fixen ohne quelle so ne Sache...

**Comment by wahaxlekuke** [comment]
Ich denke, von der Zauber-Beschreibung her ist es offensichtlich, dass Gottesschild _jeglichen_ Schaden und somit auch den Schaden durch Segen der Opferung verhindert.

Ich kann mir allerdings auch vorstellen, dass Segen der Opferung möglicherweise den Schaden gar nicht erst überträgt, wenn Gottesschild aktiv ist. Also es wäre schon hilfreich, wenn es dazu ne Quelle gäbe. (Was ja auch kein Problem sein sollte, wenn das so ne bliebte Taktik war)

**Comment by Sabbaer** [comment]
ich denke, dass der schaden trotzdem zugefügt wird, jedoch steht dann im kampflog sowas wie: "segen der opferung macht x schaden jedoch seid ihr immun."

**Comment by Sabbaer** [comment]
hab jede menge holy pala videos mittlerweile geguggt aus vanilla und leider bis jetzt noch kein video gefunden, wo irgendjemand überhaupt segen der opferung benutzt..... ich geb die hoffnung nicht auf noch eins zu finden, jedoch sollten die erklärungen für eine rechtfertigung ausreichen dieses zu fixen.
ich erbitte auch andere, falls sie dazu was finden, dies hier zu posten.
kleiner fun am rande, man stirbt in der bubble wenn man segen der opferung auf jmd anderen wirkt und die hp unter 0 fällt obwohl der paladin in dem moment keinen dmg bekommen sollte ;)

**Comment by lysethea** [comment]
Wie schon geschrieben, sollte der Tooltipp unmissverständlich sein. 
Aber in diesem Video sieht man, das in der bubble kein Schaden durch SdO durch kommt, den der Pala auf 2 anderen Spielern hat.

Ihr müsst allerdings das Video mit dem unblocker addon öffnen ;) 
https://www.youtube.com/watch?v=8QWJkydiB9s&feature=youtu.be&t=3m13s

ab ca. 3:00 sieht man es wie der die Segen castet und danach Bubble zündet
