### ISSUE TITLE
Aura der Vergeltung /heilig schaden

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#932]
Welches Verhalten wird beobachtet?
aura der vergeltung macht white dmg, also meele schaden
Wie sollte es sich verhalten?
aura der vergeltung sollte heilig schaden machen
Schritte zur Reproduzierung
aura der vergeltung anmachen, von was hauen lassen, kampflogg anguggen

Links aus unserer Datenbank
http://datenbank.welli-it.de/?search=retribution+aura

**Comment by dagochen** [comment]
Was steht im Kampflog? Bei mir steht "Ihr reflektiert xy Heiligschaden auf ...."

**Comment by hraesvelgr** [comment]
und normaler damage soltle doch auch durch rüstung des gegners reduziert werden

**Comment by Sabbaer** [comment]
hm scheint irgendwas dann bei mir anders anzuzeigen... naja

**Comment by hraesvelgr** [comment]
erste regel beim bug finden: bug ohne interfaceaddons testen :P
