### ISSUE TITLE
Mob in Tyrs Hand teilweise mehrmals lootbar.

### ISSUE THREAD

**Issue by Kagrim** [ClassicWoW/Nefarian_1.12.1_Bugtracker#933]
Das Silber in einem Scharlachroten Prätorianer Lvl. 57 war mehrmals lootbar.

**Comment by ircfelix** [comment]
Bitte gib dir doch mehr Mühe Kagrim!

**Comment by Rushor** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker

**Comment by Kagrim** [comment]
Werde bei Gelegenheit nochmal rüberschaun und nötige Informationen bzw. Screenshots erarbeiten, dazu hatte ich leider keine Zeit. Entschuldigung, dass ich das Format nicht eingehalten hab.

**Comment by Slimmer2** [comment]
So was ähnliches hatte ich auch mal.
Aber man bekam den Loot nur einmal, auch wenn man öfters auf das Looten konnte.
