### ISSUE TITLE
Waffenverzauberung Tiergestalten

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#934]
Die Waffenverzauberungen + Waffenschaden wirken sich auf Katzen/Bärenform vom Druiden aus. Dies war zu classic nicht so. Die einzigen Enchants die in Katzen/Bärenform gewirkt haben waren Statenchants

Quelle:
http://wow.allakhazam.com/forum.html?forum=21&mid=113950310940335407  (1. und 2. Post)

Betroffene Zauber:
http://datenbank.welli-it.de/?spell=20031 (+5 Waffenschaden auf 1h)
http://datenbank.welli-it.de/?spell=13943 (+4 Waffenschaden auf 1h)
http://datenbank.welli-it.de/?spell=13693 (+3 Waffenschaden auf 1h)
http://datenbank.welli-it.de/?spell=13503 (+2 Waffenschaden auf 1h)
http://datenbank.welli-it.de/?spell=7788   (+1 Waffenschaden auf 1h)
http://datenbank.welli-it.de/?spell=20030 (+9 Waffenschaden auf 2h)
http://datenbank.welli-it.de/?spell=13937 (+7 Waffenschaden auf 2h)
http://datenbank.welli-it.de/?spell=13695 (+5 Waffenschaden auf 2h)
http://datenbank.welli-it.de/?spell=13529 (+3 Waffenschaden auf 2h)

**Comment by Testear** [comment]
luv u

**Comment by Haudraufinix** [comment]
Stimmt, wusste ich hab was vergessen^^ interessanterweise funktionierte allerdings bei Blizzard auch schon der +4 Waffenschaden Ring.

**Comment by Leluri** [comment]
Die Quelle ist keine richtige. Die sagen da nur, dass Waffenschaden der Waffe kein Rolle spielt und das stimmt auch so. Aber die Waffenschadenverzauberungen sowie Schleifsteine gehen direkt auf den MH - OH oder Zweihandschaden des Spielers und nicht auf die Waffe. Somit legen sich die Waffenschadenverzauberungen sowie die Steine direkt auf den Schaden und nicht auf die Waffe. Der Ring aus Silithus ist das gleiche mit den +4 Waffenschaden. Dieser hat früher funktioniert.

Quelle: http://tangedyn.awardspace.com/cat-dps-items.htm
--> Auf Finger im Reiter gehen: Macht des Cenarius hat 56 AP --> sind 14 AP pro Waffenschaden.

**Comment by Testear** [comment]
"Die Quelle ist keine richtige."  Bitte was?
Poste doch erstmal eine richtige Gegenquelle.

**Comment by Leluri** [comment]
Das sind zwei Leute die sich über Verzauberungen unterhalten, wovon der eine der Meinung ist + zu Waffenschaden würde nichts bringen. In fast allen Feral-Guides ist der Macht des Cenarius wegen den +Waffenschaden enthalten. Einer einzigen Unterhaltung in Foren kann man so wenig ablesen. Es gab vor meine Guide http://community.mmobase.de/druide/6535-feral-katze-allumfassender-guide-und-diskutierthread.html auch keine richtige Feral-Guids auf Deutsch und die meisten hatten wenig Ahnung diesbezüglich. Ich hab vor 1 1/2 Jahren mich durch so viel duchgewühlt und hab so viele Foren durch, weil ich auch erstma Infos suchen musste. Ich habe auch mit einigen Ferals von früher gesprochen, die wissen, dass sie das drauf hatten. Wenn es um einige Skillungen geht in Classic (Priest-Smite, Shamy Tank, Spelldmg-Rogue) findest du so wenig oder so viel falsches (Beispiel Vergelterpala oder WF-Shamy ... kaum einer spielt den richtig), das ein einziger Post so nichtsagend ist.

**Comment by Testear** [comment]
Sorry, aber ich habe eher den Eindruck, dass du nicht genervt werden willst.

Immer noch keine Quelle.

**Comment by Haudraufinix** [comment]
Leluri nimm den Ring aus der Diskussion mal raus. Der Ring funktioniert - wie ich angemerkt habe - sogar. Es ist lediglich die Waffenvz (und demzufolge auch Wetzsteine) die nach dem 2. Post aus http://wow.allakhazam.com/forum.html?forum=21&mid=113950310940335407 als "Schaden der Waffe" angerechnet werden und keinen Effekt auf die Schadensberechnung von Katzen/Bären haben sollten.

Den Warheitsgehalt deines Guides lass ich mal im Raum stehen. Ich habe weder das nötige Equip noch die Zeit das nachzuprüfen. Ich hab einen Vollzeitferal von damals im eigenen Haus (Mein Bruder) und wir hatten damals nächtelang über Sin und unsinn von Feralsachen diskutiert. Unter anderem Hatte er Waffenschaden mal drauf und es hatte einfach keinen Effekt.
Das alleine ist verständlicherweise genau so Aussagekräftig wie dein " Ich hab mit Ferals von früher gesprochen" (Ist das mittlerweile eigendlich so n Beanson running gag?!)

Wenn es denn Tatsächlich funktionieren sollte, dann würde man ja in Druidenforen schwärmen wie geil +7 Waffenschaden doch wäre (für die nicht druiden: Schreddern macht 225% Waffenschaden für 42 Energie). Hingegen empfehlen alle eben NICHT Waffenschaden zu verwenden, wieso wohl.
Da müsste sich doch sicher was im Internet finden, denn es gab damals sehr wohl Ferals und einige davon waren in Theorycrafting recht bewandert.

**Comment by Leluri** [comment]
@Testear Natürlich will ich, dass es nicht gefixed wird. Habe mit den Links gearbeitet die ich damals hatte und nur dadurch die VZ draufgemacht. Hatte auch vorher 15 beweg weil ich annahm es bringt nix. Hatte dies aber dann in Posts gefunden. Ich mach das hier mit Bugtracker nicht so wirklich wie ihr an der Postmenge erkennt. Die 200 AP zu verlieren würde aber sorgen, dass eine bisher im Raid spielbare Klasse (platz 6-20 im dmg-Meter) nutzlos wird (wieviel 200 AP macht merkt man an DB Tribut Buffs).

@Haudraufinix Was sind denn ordentliche Quellen? Gilt der Guidethread von Feenix Server? Weil die die gleiche Plattform haben wie wir. Die empfehlen zum Beispiel auch den Wolfskopfhelm aber der funktioniert bei uns auf dem Server nicht wegen nem internen Cooldown (der auch Classic-Like wohl ist).
https://www.youtube.com/watch?t=18&v=Y2weWvmDtb0 <-- der hat 5 Waffenschaden drauf in Naxx. Weiß halt auch nicht was Quelle ist aber hab mehrere solcher Videos und auch Posts

**Comment by Haudraufinix** [comment]
Feenix ist extremst verbugt und taugt als Quelle mal gar nichts ( Dort hält Schaf im PvP 45 Sekunden und Weihe rang 1 tickt für 80 dmg um mal paar Beispiele zu nennen)

Demzufolge sind Forenposts aus Classiczeiten, Wikieinträge, Classicvideos etc gute Quellen. Blizzard selbst hat da leider die glühenden Kohlen ausm Feuer genommen und das offizielle Classic-Forum voll von Druidengeheule ist nicht erreichbar ;)

Nun zum Video. Ich hoffe wir sind uns beide einig dass das wohl ein Privatservervideo ist. Gute Qualiät, Uploaddatum 2014, Buffrollen mit Elixieren gestackt und ein Feraldruide in Naxxramas sprechen irgendwie dafür ;)
Damit kommen wir zu dem obigen Problem, Privatserver sind keine geeignete Referenz.

Am besten verlinkste doch diese Videos und wir gucken sie durch.Vlt stammt ja eines vom Offi und gibt anhaltspunkte.

**Comment by Leluri** [comment]
Hm, das habe ich noch gefunden. Kannst dir das mal anschauen Zitat aus der mitte der Seite:

Weapon DPS and weapon +damage enchants have no effect, however, armor enchants such as the Enchant Ring - Striking enchant, and armor pieces such as the Crystalforged Trinket that boost weapon damage do work. The bonus damage from Weightstones and Sharpening Stones also does work. Weapon enchants that boost stats such as Attack Power and Agility rather than weapon damage also work. 

Quelle: http://vanilla-wow.wikia.com/wiki/Druid

Die Waffenverstärkungen scheinen auf jeden Fall zu funktionieren. Der Rest scheint laut der Quelle aber so zu sein wie du geschrieben hast. Sprich +5 Einhand und +9 Zweihand gehen wohl nicht, dafür aber die Gewichtsteine. Ich hab derzeit 3 Videos durch ... dauert ewig da nochma auf alles zu achten. Das zwei davon waren auch Feenix Server. Der andere war nen Server aus Korea aber der hatte weder Schleifstein drauf hat aber neben Feral auch Heal und Cast gemacht im BG

**Comment by Gromnir** [comment]
In folgendem Thread wird der Gegenstand "Might of Cenarius" (der mit +4 Waffenschaden) nach AQ Öffnung diskutiert. Es sieht wohl so aus, dass der Ring beim Feral funktioniert hat, also die DPS um 4 erhöht. 

http://wow.ingame.de/forum/threads/92454-Might-of-Cenarius-und-andere-Sili-Items?highlight=feral+waffenschaden

Im 3. Beitrag wird auch bestätigt, dass Waffenverzauberungen den Schaden nicht eröhen. Generell wenn ich in dem Forum durch die Beiträge von 2006 stöber und auf Verzauberungsthreads für Druiden lande, wird immer nur über 25 Beweglichkeit und 15 Stärke diskutiert. 

"Original geschrieben von eQui
dann müsste doch +Waffenschaden sich auch auf den DPS der Cat auswirken ?

tuts aber nicht, wie wir alle wissen. "



Auch die Wetzsteine bringen einem in Tierform scheinbar nichts:
"Ja, auch Wetzsteine und Gegengewichte nutzen uns in den Tierformen nicht das Geringste."

http://wow.ingame.de/forum/threads/88166-7-Schaden-auf-2-Handwaffe?highlight=wetzstein

**Comment by Thandor** [comment]
http://forums.elitistjerks.com/topic/7397-healingtankingdps-druid-calculations/
In dieser Quelle beschreibt jmd sein Katzengear und hat die Macht des Cenarius an.
-> der Ring scheint zu klappen.
Desweiteren erwähnt er unter Buffmats auch den Elementarwetzstein als möglichen Buff.
Ich denke die Art und Weise seiner Rechnungen dort und allgemein der Ruf von Elitistjerks zeigt das derjenige sich wohl intensiv mit der Materie befasst hat und man die Quelle als zuverlässig und aussagekräftig bezeichnen kann.
-> Elementarwetzstein funktioniert in Katzengestalt.
Normale Wetzsteine wurden bisher nirgends erwähnt, daher tendiere ich bei diesen eher dazu, dass sie nicht funktionieren, kann es aber auch nicht ausschließen aufgrund von Nichterwähnungen.
Schadensverzauberung auf die Waffe wird ebenfalls nirgends erwähnt. Alle Quellen die ich bisher gefunden habe empfehlen Agi oder Stärke als Vz.
Auch hier ist wieder die Frage, ob man etwas also nicht funktionsfähig erachten kann zu dem es nur sehr wenige Beweise gibt und diese meist in Form von Auslassungen in Guides oder Threads.
( Das in einem Thread nur Stärke und Agi diskutiert wird muss ja nicht zwingend heißen, dass nichts anderes geht)
Lg

**Comment by Wosser** [comment]
Die Quelle aus dem Eröffnungspost ist nicht brauchbar. Da im zweiten Post schon die Aussage im zweiten Satz falsch ist, kann man der Aussage im dritten Satz auch keinen Glauben schenken.

**Comment by dagochen** [comment]
nur weil er 2 ap statt 2,4 ap sagt? vllt hat er boni/talente nicht eingerechnet? Ansonsten deckt sich das doch mit allen anderen quellen und führt letztendlich zu folgendem Fazit: 
Waffenschaden als fester Enchant -> geht nicht
Waffenschaden als temporärer Enchant -> geht nicht
Waffenschaden auf Ring -> geht

**Comment by g3n3a** [comment]
"Weapon DPS and weapon +damage enchants have no effect, however, armor enchants such as the Enchant Ring - Striking enchant, and armor pieces such as the Crystalforged Trinket that boost weapon damage do work."

Das ist eine Quelle aus Burning Crusade. Enchant Ring - Striking und Crystalforded Trinket kam erst mit BC.

**Comment by Haudraufinix** [comment]
@Wosser 
1 Punkt Stärke macht ohne Heart of the Wild auch 2 Punkte AP aus und nicht 2.4. Also ist die Aussage aus der Originalquelle dennoch richtig.

@g3n3a 
im Prinzip funktionieren auch BC Quellen, da vor 3.0.2 nichts daran geändert wurde. Auch in BC hat Waffenschaden auf der Waffe keinen Effekt gehabt - die aufm Gear (genau wie zu classic schon).

@Thandor 
Der Elementarwetzstein gibt dem User lediglich 2% crt und ist nicht auf die angewendete Waffe beschränkt (gut nachzutesten mit Dualwieldklassen die mit 2x Wetzstein +4% crt erhalten und nicht nur auf die Schwünge mit der jeweiligen Waffe 2%) also funktioniert er in Katzenform.
Du hast schon recht, dass die nichtnennung der Waffenschadensenchant nicht zwangsläufig heisst, dass sie nicht funktioniert. Jedoch wird in den beiden Forenquellen (http://wow.allakhazam.com/forum.html?forum=21&mid=113950310940335407 + http://wow.ingame.de/forum/threads/92454-Might-of-Cenarius-und-andere-Sili-Items?highlight=feral+waffenschaden) beide Male erwähnt, dass es nicht funktioniert.

**Comment by dagochen** [comment]
Q.E.D. :)

**Comment by Testear** [comment]
"(gut nachzutesten mit Dualwieldklassen die mit 2x Wetzstein +4% crt erhalten und nicht nur auf die Schwünge mit der jeweiligen Waffe 2%)"

Teste es mit ner Dualwildklasse, dass du mit 2 Critsteinen am Critcap bist. Du wirst nicht nur Crits und Glancings erhalten. Sondern genau 2% normale Autohits.

**Comment by Haudraufinix** [comment]
Mach bitte nen eigenen Report für Wetzsteine auf, das Maintopic hier ist Waffenschadenenchant. Mehrere Topics zusammen kommen nie gut.
Und so langsam fange ich an mich zu fragen, was ich gerade angestellt habe. Aus nem kleinen eher optischen Nerf (Grünes statt blaues Leuchten(sind c.a. 34 ap unterschied)) wurd innerhalb eines Tages ein riesiger nerf (etwa 200 AP) für eine Klasse dies im Raid ohnehin schon schwer hat.

**Comment by Testear** [comment]
sobald ich zeit/ lust habe mach ich das.

**Comment by Thandor** [comment]
Die 9 Waffenschaden von der Verzauberung sind wesentlich mehr als 34 Ap ( 14Apx9Ws=126 AP )

**Comment by Haudraufinix** [comment]
Die Aktuelle BiS Waffe ist eine Einhandwaffe - daran ändert sich bis Atiesh auch nichts. Aus sicht des Raidferals ist es also +5 Waffenschaden vs 15 Stärke. Ich gebe zu bei Zweihandwaffen ist der Unterschied zwischen +9 Waffenschaden und 15 Stärke satte 75AP

**Comment by Leluri** [comment]
Ja, wie es ausschaut müssten die Waffen echt gefixed werden, wass eher Feralneulinge die noch Zweihand tragen stört als Raidferals. Wenn die Schleifsteine in einem weiteren fix ebenfalls getroffen werden würden, wären Raidferals nicht mehr tragbar, weil der Verlust von 200 AP etwas dem Geargewinn in BWL + PvP gleichkommt :-) also in der tat hast du mit dem bugtrackereintrag wohl den Anfang vom Ende der Ferals in Progress-Raids eingeleitet. Ich teste das heute Abend mal im Overal Gear mit 15 Str Verz + Crit-Wetzstein. Musste aber auch durch die hohen Dmg Verlust ne Umlagerung von beweg auf Stärke machen.

Das einzige was mir aus dieser Sicht noch übrig bleibt zu sagen ist ein Apell an das DEV-Team, dass sich dieser Server zwar bemüht "blizzlike" zu sein, ihn abern icht 1zu1 kopieren möchte. Ferals sind derzeit mit dem jetzmöglichen Spielbar in Progress-Raids. Ich bin an jedem außer 1 Slot BiS, was farmen für R12, BWL, Gründrachen, Silithus Kampfaufträge und Pvp-Fraktionen auf exalted beinhaltete. Bei dem Verlust  der Waffenschadenverzauberung wären sie merklich schwächer, da sie gravierend mit Stats skalieren. (Der Gründrachenhammer sind umgerechnet auch nur 13,05 Waffenschaden, etwa so viel wie 5 Waffenschaden + 8 Schleifstein)aber bei dem verlust der Gewichtssteine sind sie etwa da, wo nun Vergelter sind. Dieser "optische" Fix ist einer, der den Spielern des Servers die Vielfalt nimmt, Feral im Progress zu spielen.

Das sollt mein Endbeitrag hier sein, da ich schon immer der Spieler und nicht der Bürokrat (Bug-Fix-Richtigkeit-Schreiben) oder Entwickler war.

so long - Oldschool X_X

**Comment by Sabbaer** [comment]
@Haudraufinix "für eine Klasse dies im Raid ohnehin schon schwer hat." hat dich beim retri auch nicht gestört. soll ich noch mehr von dir zitieren?

**Comment by dagochen** [comment]
Wir sind hier nochmal am nachbessern, da die Lösung nicht so einfach war wie zunächst gedacht.
