### ISSUE TITLE
Ruf Zuwachs Gelkis/Magram in Desolace

### ISSUE THREAD

**Issue by exsangius** [ClassicWoW/Nefarian_1.12.1_Bugtracker#937]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
Steht im Chat (in Gelb) direkt nach dem Charakter-Login. z.B 1.1.0

Wie sollte es sein?
Man sollte beim Sammeln des Rufs z.B. +20 Ruf bei Gelkis bekommen und -100 bei Magram.

Wie ist es?
+9 Ruf bei Gelkis und -49 bei Magram

Quelle:
http://db.vanillagaming.org/?faction=92

Anmerkung:
Macht das Ruffarmen für die Quests etwas langwierig :)

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by hraesvelgr** [comment]
welches level hast du bei den kills gehabt?

>In order to be deemed worthy of the Gelkis' trust, adventurers must gain reputation with the tribe by slaying members of the Magram until they reach Friendly status with the Gelkis. Each kill gives 5/20/25 reputation to the Gelkis faction and lowers the reputation of the Magram by 25/100/125. As of April 2009, kills reward full reputation, even at level 80. Previously, if mobs were at grey difficulty, they only awarded 1/5 reputation, however this appears to have been changed. 

http://wowwiki.wikia.com/Gelkis_clan

viele andere seiten sagen aber auch +20/-100

**Comment by exsangius** [comment]
Level 32, deshalb waren die Mobs Gelb bis teilweise Orange!

**Comment by Wosser** [comment]
Als ich die Quest letztens gemacht habe habe ich 20 Gelkisruf pro Magramkill bekommen, bzw. 100 für den Khan.
