### ISSUE TITLE
[PvP] Schlachtstandarten verhindern das ein Char stirbt

### ISSUE THREAD

**Issue by Gromnir** [ClassicWoW/Nefarian_1.12.1_Bugtracker#938]
Aloha,

Nachdem die Schlachtstandarten gefixed wurden und diese jetzt auch regelmäßig in Battlegrounds verwendet werden, tritt neuerdings ein Bug auf, dass der Charakter nicht stirbt wenn man auf 0% fällt solang die Standarte aktiv ist (bzw. man kann nicht mehr auf 0% fallen).
Der Char kann sich nicht bewegen, aber z.B. weiterhin angreifen. Ein relog löst das Problem, was aber während eines BGs störend ist. Ich glaube auch, wenn die Standarte verschwindet, löst es das Problem, bin mir da aber nicht sicher.

Ich konnte jetzt nicht so genau prüfen, ob dieser Bug immer auftritt, wenn man stirbt während die Standarte aktiv ist, aber ich denke mal die Standarte dürfte der Grund sein. 

![Screenshot](https://cloud.githubusercontent.com/assets/9378243/8848086/d8f94fd2-3134-11e5-9619-306abf6f065b.jpg)

Schritte zur Reproduzierung
Standarte platzieren, sterben und hoffen das der Bug auftrifft :D 

Standarten:
http://datenbank.welli-it.de/?item=19046
http://datenbank.welli-it.de/?item=18607
http://datenbank.welli-it.de/?item=19045
http://datenbank.welli-it.de/?item=18606

Effekt:
http://datenbank.welli-it.de/?spell=23538#see-also-ability

Leider macht der Bug die Standarte fast wieder nutzlos, weil mit dem Stellen ein gewisses Risiko verbunden ist, dass jmd dann halt wieder ausloggen und einloggen muss. Das kostet halt immer unnötig Zeit. Hoffe das Prob kann ohne größeren Aufwand gefixed werden.

**Comment by Testear** [comment]
https://www.youtube.com/watch?v=APZIsJOAvc8

dieser bug kann auch auftreten

**Comment by Testear** [comment]
danke für den schnellen fix
