### ISSUE TITLE
Geiselsteine in Gruppen-Loot-Rotation aufnehmen

### ISSUE THREAD

**Issue by Furyouz** [ClassicWoW/Nefarian_1.12.1_Bugtracker#941]
Bitte nehmt die Geißelsteine in die Gruppen-Loot-Rotation auf. Als Range-DD ist es praktisch unmöglich diese Steine in Instanzen einzusammeln da jeder sie bei jedem Mob looten kann solange er die Anstecknadel trägt.

**Comment by ircfelix** [comment]
Schonmal das template für bugreports durchgelesen?

**Comment by Thandor** [comment]
Gibt es dazu auch eine Quelle?

**Comment by Furyouz** [comment]
Was meinst du mit Quelle? Soll ich ein Video machen davon wie ich in Inis kein Loot bekomme?
Ich war vorgestern Scholo und gestern Strath... sobald man einen Melee DD in der Gruppe hat (und natürlich Tank auch als Melee Klasse) der direkt nach dem Tod des Mobs lootet bleibt für die Range Klassen (egal ob DDs oder Heal) nichts übrig...

**Comment by ircfelix** [comment]
Also ich weiss auch dass es früher mit den Geißelsteinen (abgesehen von den grünen) so war dass man die zum eigenen loot dazu bekam und den andere nicht looten konnten, außer man hat angelootet und den stein aber nicht genommen. Ich glaube mich zu erinnern dass das auch sonst beim loot so war. Aber dennoch brauchen die Devs eine Quelle, da sich sonst womöglich jemand dran erinnert dass die Hasen vor Stormwind Flasks gedropt haben.

**Comment by Furyouz** [comment]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version:
1.12.1

Wie sollte es sein?
Gruppen Loot-Rotation: Geißelsteine sollten abwechselnd lootbar sein, NUR für denjenigen der die Berechtigung hat den Mob zu looten (kein ffa)

Wie ist es?
Jeder der die Anstecknadel trägt kann jeden Mob looten und so unabhängig von der Group-Loot-Rotation alle Geißelsteine an sich nehmen

Links:
http://datenbank.welli-it.de/?item=12840
http://datenbank.welli-it.de/?item=12841


Quelle:
Habe alle Foren und Patchnotes von Classic durchgelesen zu diesem Thema aber nichts gefunden. Auch bei späteren Patches aus BC nicht. 

Anmerkung:
Dass ich keine Quelle gefunden habe ändert aber meiner Ansicht nach nichts an der Tatsache das man den angesprochenen "Bug" (oder besser Zustand) ändern sollte. Es ist im weitesten Sinne ein Questgegenstand den jeder gebrauchen kann und der nicht für jeden zugänglich sein sollte, sondern nur für denjenigen, der wie oben beschrieben, der Rotation nach an der Reihe ist den Mob zu looten. Da auch andere Änderungen am Spiel vorgenommen wurden (Instant-Ports zB.) sollte diese Änderung auch möglich sein, da Sie für niemanden einen Nachteil mit sich bringt (außer für die Ninja-Looter die ohne Rücksicht auf den Rest der Gruppe alles looten)

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by Robnroll** [comment]
Hallo liebes Entwicklerteam,
ich würde gerne nochmal auf diesen Bug aufmerksam machen.
Als Heal gehe ich regelmäßig aus Strath mit 0 - 2 Geißelsteinen, während Tank und Melee um die 20 abgrasen können.

Die Beschreibung von Furyouz vom 24 Juli ist sehr präzise und ich kann dem nichts hinzufügen.  Ich würde mich über eine Lösung dieses Fehler freuen, weil er zu einer ungerechten Verteilung oder schlechtem Gruppenverhalten führt.

Vielen Dank für eure Zeit und Mühe,
Rob

**Comment by hraesvelgr** [comment]
aufmerksam machen brignt nix, gefixt wird, was wichtig ist. sprecht euch einfach mal ab vorher. 

wirklich wichtig wird der argentumruf eh erst mit dem naxx release.

**Comment by b2410** [comment]
Richtig das der Ruf auf dem jetzigen Stand nicht die höchste Prio hat, (von den Items abgesehen) jedoch ist dieser mit Absicht eher langwirig gehalten und es nützt nix wenn so einfach gefarmt werden kann.

Die jetzige Praxis erlaubt mit Absprache ein massives Bugusing und erhebliche Vereinfachung das Spiels.

**Comment by hraesvelgr** [comment]
was nicht sonderlich kritisch ist, da, bis naxx rauskommt, eh jeder so oft scholo/strath gerannt ist, dass sie eh alle ehrfürchtig sind
