### ISSUE TITLE
Fernkampfangriffe verschwinden in der Luft

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#943]
Seid dem jüngsten Patch werden Geschosse (Kann leider nicht sagen, ob dies auch Zauber betrifft) gelegendlich von der Umgebung "verschluckt"

Aufzutreten scheint dies meistens, wenn es kleine Hindernisse wie Kiesel auf dem Boden hat, oder wenn man über einen Hügel schiesst. (Es fühlt sich fast an als würde Sichtfeld auch beim Geschoss nochmal überprüft, nicht nur beim initialen wirken des Schusses) Dies ist extrem nervig beim Pullen u.a. in BWL bei der Rampe. kann man das ev. wieder zurückfixen? Danke

**Comment by Slipru** [comment]
In bgs können z.b. Hunter auch beim initial Schuß weiter fröhlich durch ganze Hügel und Wände schießen, dass sollte vllt gerade mit überprüft werden.

**Comment by Haudraufinix** [comment]
So muss es ja sein. Du kannst ein bereits fliegendes Geschoss nunmal nicht mehr mit LoS Dodgen - Solange der Hunter Sichtfeld hat sobald er Feuert muss das Geschoss ankommen!

**Comment by dagochen** [comment]
Eigentlich dürften Bäume, Zäune und andere Objekte (außer Gebäude) garkeine LoS blockieren!

**Comment by ircfelix** [comment]
Quelly Celly?

**Comment by Haudraufinix** [comment]
Macht bitte ein anderes Ticket dafür auf, es geht hier um verschwindende Geschosse trotz gültiger LoS zum Castzeitpunkt - ob ein Objekt/Gelände nun LoS Blockt ist was anderes

**Comment by Slipru** [comment]
Mir geht es nicht um ein bereits fliegendes Geschoß sondern, darum dasss momentan in Bgs genau das gegenteil deiner Aussage der fall ist. Hunter können sich hintern hügel, Bäume, Häuser whatever verstecken und fröhlich drauf los ballern obwohl sie niemals ihr Ziel in LoS haben.

**Comment by Haudraufinix** [comment]
Slipru das ist hat mit dem Bug hier nichts zu tun. Mach einen Bugreport auf wenn du's gefixt haben willst (Is zwar weird aber Blizzlike - viel glück beim das durchkriegen). Hier gehts aber darum, dass dem Hunter die normale Hitanimation etc. angezeigt wird, und er sogar Specials Schiessen kann, diese auf CD gehen, aber nicht geschossen werden. Stells dir etwa so vor; Charge und Abfangen gehen auf CD aber brinen dich nicht zum Ziel.

Der Hunter HAT LoS und dennoch wird sein Schuss abgebrochen. Gerade diese Nacht wieder wundervoll in den Zaun beim Hof im Arathibecken geschossen, der nichtmal LoS behindert und Schüsse wurden davon abgebrochen! (Zur Erinnerung, Charge, Frostnova und Meleehits gehen da alle durch ohne Probleme)

**Comment by Slipru** [comment]
Da es sich wahrscheinlich um die gleiche Mechanik handelt wird es wenn überhaupt zusammen gefixt ;)

**Comment by Haudraufinix** [comment]
Dann bring fundierte Quellen die Besagen dass diese Sachen sichtfeld blocken, ich geb dir n altes PvP Video dass das gegenteil beweist und wir sind beide Glücklich und ich krieg meinen Fix.

**Comment by SirBeansen** [comment]
@Slipru 

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/304

**Comment by nightblizard** [comment]
Konnte ich nicht reproduzieren. Könnt ihr mir da vielleicht ein wenig mehr Infos zu geben?

**Comment by Haudraufinix** [comment]
Klar kann ich machen, Ich kanns dir u.A. aufm Testserver in Arathi, in BWL oder in ZG zeigen. Soll ich n Video machen?

**Comment by Sabbaer** [comment]
man kann auch nicht durch die säulen buffen und mages können da auch nicht durchschießen oder hexxer? das ist doch hunterspezifisch nicht anders? ich möchte auch die pvp videos sehen, die du oben ankündigst, in denen ein hunter das mit unserem patchstand macht

**Comment by Haudraufinix** [comment]
@Sabbaer Jeder der Augen im Kopf und eine einzelne funktionierende Hirnzelle hat, sieht, dass hier was nicht funktioniert, da du ja offensichtlich in WoW nicht dauernd gegen Wände läufst, bleibt bei dir nur eine Möglichkeit übrig....

ausserdem zitiere ich mich mal selbst, da du offensichtlich nicht einmal den Initialpost gelesen hast:
*Seid dem jüngsten Patch werden Geschosse (Kann leider nicht sagen, ob dies auch Zauber betrifft) gelegendlich von der Umgebung "verschluckt"*
Steht da irgendwas drin von wegen es betrifft nur Jäger?

Zu den Videos:
https://www.youtube.com/watch?v=4sj21TAmQ-M 4:36-4:40, 14:28-14:30
https://www.youtube.com/watch?v=DgV-FPWuWQk 1:17-1:22, 3:55-4:07
https://www.youtube.com/watch?v=aGli2EPbK-A 1:58-2:04 (Dieser Zaun verschluckt bei uns Geschosse kann leider nicht genau sagen, ob er darüber schiesst oder durch)

Stellen wo es gehen sollte: Alle die Sichtfeld aufs Ziel bieten. Dies umfasst (ohne Anspruch auf Vollständigkeit) Baumstrunke, Zäune, Bodenunebenheiten, Steine auf dem Boden, Stühle, BWL-Fallen, Bodenunebenheiten etc.

**Comment by Sabbaer** [comment]
video 1 und 2 nur über proxy erreichbar
video 1,4:40: er castet über den baumstumpf an und der gegner rennt dann nicht hinter den baumstumpf, sondern ist bei beendigung des castens neben dem baumstumpf.
14:28: da ist eine lücke zwischen den baumstämmen
video 2, 1:14:er castet vor dem wagen den instant und läuft während der cast fliegt hinter den wagen. somit kommt der cast "durch" den wagen geflogen. der zeitpunkt des auslösens ist hier entscheidend. er hat in diesem moment los.
3.55: dies ist ein glitch den viele ausgenützt haben, sieht für mich so aus, als hätte er sich in den baum "gestellt" daher auch die nahansicht und ohne ui!
video 3, 1:58: er schießt über den zaun, bist du dir 100% sicher, dass man bei uns nicht durchschießen kann? denn ich meine da letzte woche erst von huntern über diesen zaun bearbeitet worden zu sein.
Die bwl fallen sind übrigends verbuggt, bitte in einem gesonderten bugreport behandeln. diese sollten keine festen mauern darstellen, sondern nur wenn sie oben sind! die fallen sind bei uns was buffen oder casten angeht eine wand, auch wenn sie unten sind.

es gab anscheinend wirklich ein paar objekte, durch die es blizzard möglich gemacht hat, durchzucasten/schießen. durch man andere war dies allerdings und ist auch nicht möglich.
dafür genaue beispiele zu finden durch was man nun durchballern konnte und durch was nicht würde extremst viel viel viel arbeit bedeuten. 

außerdem solltest du dich in deiner beleidigenden form mal etwas zügeln. du beleidigst und wirst persönlich gegenüber mir, ich habe versucht sachlich zu bleiben!
Deswegen rate ich dir eines:
mach doch bitte von allen dingen, wo du meinst dass du durchschießen könntest ein video und poste es hier, dann können es die developer fixen, nachdem auch leute, die keine hunterbrille anhaben, sich das mal angeschaut haben. 
Schönen tag auch noch

**Comment by Haudraufinix** [comment]
Ich zügle meine beleidigende Form wenn du etwas Sinvolles beiträgst - und ich habe mich geirrt, du bist offensichtlich DOCH blind -> 
Video 1 4:40 Wenn ein gegner LoS Dodget bei angefangenem Cast, dann wird der Zauber abgebrochen.
Video 2 1:14 Im zweiten Video zaubert er dannach noch zwei Zauber durch den Wagen
Video 2 3:55 Selbst wenn es ein Glitch ist -> ich verweise auf http://community.mmobase.de/talk-und-allgemeines/7542-wie-viel-blizzlike-ist-richtig.html wenn du Probleme mit Blizzlike glitches hast und die gefixed haben möchtest - aber da biste ja felsenfest dagegen.
Video 3 1:58 "Ich **meine** erst da letzte woche erst..."  rest ignoriere ich davon mal.

BWL Fallen: Die Fallen habe ich als Veranschaulichungsort gewählt. Wenn du lesen könntest - sry kanns dir leider nicht in Braille anbieten - wüsstest du dass ich diesen Ort nur gewählt habe, weil der Bug dort besonders gut sichtbar ist.

Bist du Developer? Nein?
Dann verschwende nicht Stunden meines Lebens damit mich aufzufordern sinlose Videos zu machen, denn es ist nicht ein Objektbezogenes Problem (ergo LoS) sonder ein Problem, dass TROTZ LoS und erfolgreichem Cast nix ankommt.

Last but not least:
**DAS IST KEIN HUNTERPROBLEM - JEDE KLASSE DIE AUCH NUR EINEN RANGED ANGRIFF BESITZT KANN DIES REPRODUZIEREN**

**Comment by wahaxlekuke** [comment]
> Seid dem jüngsten Patch werden Geschosse (Kann leider nicht sagen, ob dies auch Zauber betrifft) gelegendlich von der Umgebung "verschluckt"

Ich bin mir nicht ganz sicher, wie du das genau meinst. Kannst du davon bitte mal ein Video machen?

Ich hab nicht alle Kommentare durchgelesen, aber es war bzw. ist tatsächlich so, dass auf den orginalen Blizzard-Servern viele Objekte (insbesondere auch Bäume) die LoS *nicht* blockieren. Allerdings würde die Mehrheit der Spieler das bei uns für nen Bug halten, wenn man plötzlich durch Bäume etc. durchschießen könnte. Aus diesem Grund _und_ weil es einfach etwas aufwendiger wäre, das zu ändern, wird hier aktuell nichts geändert.

**Comment by Haudraufinix** [comment]
https://www.youtube.com/watch?v=tytluHcQyeY Video in dem der Fehler zu sehen ist.
Mir ist eigendlich egal, ob ich nun durch die Falle durchschiessen kann oder nicht, aber ich kann die Skills auslösen, bezahle Mana und den CD aber der Schuss verschwindet einfach. Das tritt erst seid 1-2 Wochen auf. Bis kurz vor dem Bugreport konnte ich entweder schiessen oder aber ich erhielt die Meldung, dass das Ziel nicht im Sichtfeld sei.

**Comment by Sabbaer** [comment]
und wieder nur am rumflamen der typ, diskutieren kannste nicht oder? einfach lächerlich, nimmst alles persönlich, wenn man anderer meinung ist und dies kundtut. 
dann beleidigst mit deinen hordenkollegen denjenigen der anderer meinung ist als du, und somit gewinnst du den "flamewar" na dann gz an dich, du bist der tollste

**Comment by Bladsn** [comment]
Ich bin der Meinung, dass nur der Ersteller des Threads und die Dev's hier kommentieren dürfen. 
Dann entsteht auch nicht so ein inhaltsloser Blödsinn. 

Worauf er hinaus möchte ist: " Bis kurz vor dem Bugreport konnte ich entweder schiessen oder aber ich erhielt die Meldung, dass das Ziel nicht im Sichtfeld sei." 
Da aktuell Mana für ein Spell verbraucht wird, welcher nicht mal in einem Paralleluniversum ankommen wird. Obwohl einfach klipp und klar die Fehlermeldung kommen müsste: "Ziel ist nicht in Sichtfeld bzw. außer Reichweite!" 

Für jeden, der nicht mit besonders viel Intelligenz gesegnet wurde. 
Leider kann man das auch nicht buffen, obwohl es ein geliebter Segen ist, lieber Sabbaer.

Grüße eines Hordenkollegen.

**Comment by nightblizard** [comment]
Hab hier etwas aufgeräumt und alles unwesentliche gelöscht. Danke für die Meldung und für das Video, damit können wir etwas anfangen!

**Comment by nightblizard** [comment]
Ist das hier noch aktuell? Ich kann das nämlich trotz Video nicht reproduzieren.

**Comment by Haudraufinix** [comment]
Scheint nicht mehr aktuell zu sein, zumindest bei mir ist es in letzter Zeit nicht mehr aufgetreten

**Comment by wahaxlekuke** [comment]
Ich habe die Ursache für den Bug gefunden.
