### ISSUE TITLE
Mehrere Bugs ausgelöst durch Schlachtzugsanmeldung in den BGs

### ISSUE THREAD

**Issue by L4Z3** [ClassicWoW/Nefarian_1.12.1_Bugtracker#944]
Hallo,
Seit mehreren Wochen melden die Allianzler unseres Servers gerne als 10er Schlachtgruppe in den BGs Warsongschlucht und Arathibecken an. Daran ist an sich nichts verwerfliches. Jedoch führt diese Anmeldung zu einigen Bugs, die das Spielgeschehen und den Ausgang der BGs stark beeinflussen und im Grunde allen Beteiligten außer besagten 10 Allis den Spielspaß rauben.

1. Sehr oft wird die Warsongschlucht durch die Anmeldung komplett blockiert, trotz genügend angemeldeten Spielern beider Fraktionen.
![wowscrnshot_072415_172431](https://cloud.githubusercontent.com/assets/11063683/8881262/bd64cc8c-323e-11e5-9d3b-a69b303f88d7.jpg)
![wowscrnshot_070315_214805](https://cloud.githubusercontent.com/assets/11063683/8881284/dc9ecbde-323e-11e5-84cc-8654969d48b9.jpg)
Dies sollte mit dem Timing der anmeldung zu tun haben. Beispielsweise 4 Allis melden für WS an danach die 10er Gruppe. Niemand kann joinen, kein BG geht auf.

2. Ein weiterer verstärkt auftretender Bug ist ein ungerechtes Verhältnis beider Fraktionen. Diesen Bug gibt es schon länger, jedoch vereinzelt. In letzter Zeit tritt er sehr häufig auf. Selbst wenn sich die Spieler über dem Maximum an den Rand stellen,ist man bei 17 gegen 13 immernoch sehr stark benachteiligt und versucht im Allgemeinen es nur hinter sich zu bringen.
![wowscrnshot_072415_170030](https://cloud.githubusercontent.com/assets/11063683/8881356/74a0f40c-323f-11e5-870a-112d35afcd5a.jpg)
![wowscrnshot_072415_173038](https://cloud.githubusercontent.com/assets/11063683/8881363/8554d5f2-323f-11e5-93a6-244093bd7d36.jpg)
![wowscrnshot_071715_222743](https://cloud.githubusercontent.com/assets/11063683/8881367/907489fa-323f-11e5-90cc-8a577abf949b.jpg)
Wodurch dieser Bug genau ausgelöst wird, kann ich nichtmal raten, jedoch nimmt es mir und vielen anderen gehörig den Spielspaß mit Teilweise 6 Leuten in Unterzahl zu spielen, obwohl genug Hordler angemeldet wären. Diese bekommen leider keinen Invite.

Ich hoffe hierfür wird eine angemessene Lösung gefunden. Sonst wird das PvP auf unserem Server wohl früher oder später ganz aussterben.

Gruß Ulki

**Comment by Testear** [comment]
1. Das Blocken der Bgs entsteht dadurch, dass zu wenig Leute auf Hordeseite oder Alliseite einzeln anmelden. Wenn wir in einer Gruppe spielen wollen ist das unser gutes Recht. 

2. Ist schon reportet worden und hat rein nix mit der Anmeldung im Raid zu tun. 
    siehe: https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/846

**Comment by Tuary** [comment]
Komm mal wieder runter Genosse.
Er hat den Bug sachlich und ohne jegliche Schuldzuweisungen reportet.
Ich habe gehört, dass es auch mal vorkommen kann, dass man einen gemeldeten Bug übersieht oder einfach unter seinen Suchbegriffen nicht findet. 

Viel Spaß noch in eurer kleinen elitären Gruppe!

**Comment by Archidamos** [comment]
Uns als Gruppe ärgert es genauso wenn zu wenig Hordler angemeldet sind oder zu wenig Allies und wir deshalb Wartezeiten in Kauf nehmen müssen. Die Wartezeiten betragen aber maximal 15-20 Minuten und das ist man als Allianzler sowieso gewöhnt. Als Hordler vermutlich nicht, aber dennoch ist die Mechanik die dahintersteckt nicht buggy sondern blizzlike.

**Comment by dagochen** [comment]
Ich kann mich nicht dran erinnern, dass auf den Blizzard Servern je eine Premade-PVP-Gruppe warten musste, wenn Gegner da waren. Vermutlich wurden Gruppen gegenüber einzelnen Spielern sogar bevorzugt, aber das lässt sich nur schwer oder gar nicht beweisen, auch wenn es das Problem vermutlich lösen würde.

**Comment by L4Z3** [comment]
Der Unterschied ist, dass auf den Blizzard Servern sehr viel mehr Spieler für BGs angemeldet waren. Dadurch waren alle voll. Egal ob Pre-Made oder nicht. Wir haben nunmal eine kleine PvP-aktive Population.
@Archidamos Zurzeit sind fast immer mehr Hordler angemeldet als Allis. Ihr hättet Instant Invite wenn ihr einzeln oder in 5er Gruppen anmelden würdet. Und würdet eh fast jedes Mal zusammen rein kommen. Und ich kann mich nicht erinnern dass auf Blizzard Servern ein Arathi 17 vs 13 voll war und niemand mehr joinen kann. Es ist offensichtlich ein Bug der sich durch das oben erwähnte Verhalten deutlich verschlimmert hat.

**Comment by Archidamos** [comment]
@dago: ich war in einer pc Stamm auf der silbernen Hand, allianzseite, wir mussten oft eine Stunde warten.
@Ulki: ich bin jetzt fast r14, heisst spiele schon lange ally pvp und konnte keine signifikante Erhöhung dieser Problematik feststellen. Der bug is ewigkeiten bekannt und hat nix mit premadegruppen zu tun.
Diese Meldung hier is ne Farce und nur dem Frust aufgrund vieler looses der Horde entsprungen. 
Pls close

**Comment by Slipru** [comment]
Wie oben gepostete Screens zeigen wird durch die Gruppenanmeldung definitiv die bg öffnung verbuggt und geblockt, obwohl von beiden Fraktionen mehr als genug Spieler angemeldet sind.
Das problem gab es vorher nicht.
Zu Punkt 2. kann ich sagen, dass es diesen Bug schon länger gibt allerdings nicht so extrem ( 17 / 13 oder 17 / 11 ) hab ich vorher noch nie gesehn, 16 / 14 war immer das schlimmste was man zocken musste.

**Comment by Archidamos** [comment]
Da wird gar nichts verbuggt, nur geblockt. Wenn immer nur 5 random allys anmelden, willst du die dann jedesmal nach hinten reihen stundenlang bis vielleicht ein 6. anmeldet? Das ist die Blizzlike Mechanik. Der erste der anmeldet kommt rein, wenn der zweite in der liste sich für Warsong als Beispiel in ner 10er Gruppe anmeldet, rücken die Spieler die hinter der 10er Gruppe sind nach bis ein BG geöffnet wird. Nachdem das gespielt wurde, ist die 10er Gruppe erster und kann joinen. Wenn wir als 10er Gruppe lieber warten möchten als nur zu 9t zu spielen ist das unsere Sache und das Problem der Horde ist nur, dass es zu wenig angemeldete randoms gibt.
Zu Zeiten als Floppi und Troopi noch spielten waren wir nie in Gruppe angemeldet und auch dort gab es 15 vs 5 warsong, also rede mal nicht so einen Stuss bitte. Wurde auch alles ausführlich reportet bereits.

Uns als Stammgruppe würde es natürlich nichts ausmachen wenn wir nach vorne gereiht werden würden, wenn zu wenig random allys anmelden, es ist aber dann definitiv keine blizzlike mechanik mehr und würde der Horde auch nicht zu mehr Siegen verhelfen.

**Comment by L4Z3** [comment]
@Archidamos ich habe nie gesagt dass es den Bug mit den 16-14 oder 17-13 arathis nicht vorher gegeben hat. Mir ist eine DEUTLICHE Häufung aufgefallen durch eure Schlachtzugsanmeldung. Z.B. gestern 5 oder 6 BGs in Folge, die ALLE unausgeglichene Spielerzahl haben. Obwohl mehr Horde als Allianz angemeldet waren. Und nein sie sind nicht gedodged, da ja kein Warsong aufgegangen ist. Ich habe hier wirklich gerne PvP gespielt und bin schließlich auch schon Rang 13. Aufgrund der Häufung solcher Bugs macht es einfach keinen Spaß mehr. Und es geht mir hier nicht um Sieg oder Niederlage für die eine oder andere Fraktion. Schlichtweg darum Spaß in einem Content des Spiels zu haben, der leider etwas unterrepräsentiert ist. Dass 10 Leute das für den gesamten restlichen Server kaputt machen und sich dann noch damit brüsten, geht mir nicht in den Kopf. Wir sind eine Community.
Und bitte spar dir die Flame-Comments. Das hilft niemandem weiter

Ich persönlich wäre für eine Beschränkung der Gruppengröße bei der Anmeldung auf 5 Spieler anstatt, was mit der relativ geringen Anzahl an aktiven Spielern zu tun hat. Aber das müssen andere entscheiden.

**Comment by Archidamos** [comment]
Ja sicher, und als nächstes verbieten wir bitte allen BWL equippten in BGs zu gehen, da die Horde fast immer einen Gear-Vorteil hat, sogar gegenüber der Stammgruppe.
Ohne die Stammgruppe hat es nämlich den aktiven PvPlern hier keinen Spaß gemacht, da die Horde aufgrund des Gearvorteils nur gewonnen hat und es keine Aussicht auf Besserung gab. Dadurch wurde die Stammgruppe überhaupt erst ins Leben gerufen.

**Comment by Feddebla** [comment]
Bitte bleibt fair und organisiert euch selbst ne Stammgrp, um Mal vernünftig gegenzuhalten, anstatt hier am grünen Tisch zu versuchen, uns zu sperren und zu gewinnen. 

Zur Problematik:

Ich kann auch einige Screens rausholen, bei der die Horde in der Überzahl ist. Allerdings liegt das sicherlich nicht an der Stammgruppe und mir ist es auch nicht aufgefallen. Früher war das viel schlimmer. Zur Zeit kommt das Ganze vielleicht 1x in der Woche vor. Allerdings bin ich der Meinung, dass dann auch entsprechend fair gehandelt wird und die Leute, die zu viel im BG sind am Ausgang warten. So habe ich es in der letzten Zeit zumindest auf Allyseite erlebt. Auf Hordenseite weiß ich nicht, wie es läuft. Aber ich vermute Mal auch so. 

Da wir uns ja immer in Richtung Blizzlike bewegen wollen und es früher auch Gruppen gab, sehe ich da kein Recht diese Gruppen zu verbieten oder zu reduzieren.

**Comment by Haudraufinix** [comment]
Sagt mal habt ihr irgendwie komplexe mit eurer Stammgruppe?

Eigendlich ist es Blizzlike, dass bei 4 Einzelspielern und 10 Stammgruppenspielern kein BG startet, die Frage ist, wie es sich verhält, wenn nach der 10er Gruppe nochmal 2 Einzelspieler anmelden. Diese müssten dann eigendlich nachrücken um ein erstes WS zu Starten, so lange bis die komplette Stammgruppe auf dem 1-10. Warteplatz ist. Man müsste nachprüfen, ob dies so der Fall ist. Hier müsste man was anpassen, wenn dies nicht so ist. Allerdings ist das BG Stammgruppenverhalten zwar ein Tritt in die Eier für jeden der hier n gemütliche Runde BG Spielen will, jedoch vollkommen Legitim.

Dieser Gearvorteil ist meiner Meinung nach einfach nur nen Whine - Es gibt auf beiden seiten Extrem gut UND extrem schlecht equipte PvP Spieler. Das ist eher Glück/Pech wer gerade lust auf PvP hat.

**Comment by Lavinja** [comment]
@Haudraufinix 

Es ist kein " whine " zumindestens kein direkter , aber dieses gegenargument das die horde auch so viele unterequipte leute im bg hat is schlicht und einfach nur gelogen.
ich weiss auch nicht ob du mit irgendeinen char regelmässig pvp machst aber wenn nicht dann solltest du dich selbst mal davon überzeugen.

so ziemlich jeder aktive hordler spielt mit R10 oder Bwl niveau gear , die einzigen die da nicht nachkommen sind zurzeit die ganzen lustigen frischen eleschamis....

selbst die stammgruppe ist im gear den aktiven hordlern weit unterlegen.

und wenn das 1-2 vorkommt am tag das mal kurz was geblockt wird dann wird das auch meistens behoben. 

also bitte ulki, übertreib nicht so maßlos.  glaubst du wir haben einfaches spiel gegen euch ? wir sind zur zeit einfach nur melees die ganze zeit im bg , und wenn dann 7 schamis im bg sind und 6 davon eleschamis .. macht nen heidenspass  instant bei 7k+ leben  ausm leben getreten zu werden.

das nächste warum auch so wenige random allis manchmal anmelden ist einfach nur weil die horde die allis in ihrer base wobei sie nichts mehr machen weil sie aufgegeben  haben einfach abgeschlachtet werden. 

die stammgruppe macht das nicht , nur bei leuten die uns praktisch den free win bei 10:2 versauen, dann muss man halt damit leben das man nur noch am fh abgefangen wird. 

den meisten hordler fehlt es leider an mangelnden respekt ihren gegnern über.

in dem sinne, ulki du hast es bald hinter dir und da man von dir so aussagen hört wie " du hast doch r14 gemacht , wieso machst du immer noch pvp " .. nehm ich mal an das man dich auch bald nicht mehr sehn wird , also ziehs noch 3 wochen durch und dann bye bye

**Comment by L4Z3** [comment]
Zurück zum Thema bitte. Keine Lust dass das hier ein Whine-Thread wird. Meines Wissens haben die Allis generell hier einen höheren Gearstand. Mehr aktive Raidgilden etc. Aber wer sich wann warum anmeldet, darauf hat niemand einen Einfluss. Ich möchte einfach nur faire Möglichkeiten für alle und genau das sabotiert ihr mit Blockaden.

Und @Feddebla du spielst vielleicht mal abends 2 stunden BGs. Bist schwerlich PvP aktiv genug es zu beurteilen. Problem ist auch nicht dass sich Nr 16 und 17 an den Rand stellen. Sondern dass bei der anderen Fraktion Nr 14 und 15 schlichtweg nicht joinen können. Dadurch entsteht trotzdem eine Unterzahl von 2 Spielern. 
 
Und mal so nebenbei. Nach Serverregeln müssten die überzähligen /afk eingeben bzw leaven. Aber ich hab kein Interesse daran dass hier irgendwer gebannt wird und es noch weniger PvP gibt. Versteht doch einfach mal dass es in diesem Report nur um ein faires Spielerlebnis geht. Aber jeder von euch sieht es als persönlichen Angriff, versucht es ins lächerliche zu ziehen etc etc.

**Comment by Archidamos** [comment]
es ist einfach lächerlich zu fordern eine blizzlike mechanik zu verändern und uns den spielspass damit zu rauben, nur weil dir deiner im moment flöten geht. Das ist ein bugtracker und kein whinetracker.
thats it

**Comment by dagochen** [comment]
Nicht alles durchgelesen was noch kam, aber das 17-11 ist ein 17-13, man sieht wie 2 nachjoinen ;)

**Comment by ChichiWarrior** [comment]
Lasst mal die Kirche im Dorf, bitte.

Fakt ist:
- die Möglichkeit von 17 zu xx nicht sein soll. War das damals auch so?
- das egal wer, wann und wo anmeldet, erst ein BG aufgehen darf/soll, wenn beidseitig genügend Spieler angemeldet sind
- sobald die maximale Anzahl an Spielern gegeben ist, keine Möglichkeit mehr bestehen soll, dass weitere Spieler nachjoinen können

Der größte Fakt:
Dankt Wahax das Rang 14 möglich ist, wir das einige Wochen getestet haben und das PvP einen Schub bekommen hat.
Wir sind ein PvE Server und haben defnitiv andere Prioritäten!

Gruß

Chichi

**Comment by Archidamos** [comment]
@ Chichi: 
1.Dies sollte nicht möglich sein, wurde aber bereits in einem anderem post gemeldet.
2. Ja aber darum geht es nicht, sondern darum, dass Ulki entweder nicht damit klar kommt 5 Minuten auf einen BG invite zu warten, denn wir lösen das Problem mit dem blockieren, wenn wir nicht ins BG kommen immer recht schnell oder dass er einfach unsere Gruppe zerstören will, weil er zu oft gegen sie verliert.
3.Richtig, ist aber auch schon in einem anderem Bugpost vermerkt. (Siehe Posting 2 hier)

**Comment by Feddebla** [comment]
@Ulki 
Bei /afk hätten die Leute einen Deserteurbuff und außerdem joinen dann trotzdem wieder Nr. 16 und 17. nach. Aus diesem Grund macht es sich am besten, wenn man am Ausgang wartet und nichts macht. Ich hab es wiegesagt kaum mitbekommen, dass es in letzter Zeit vorgekommen ist. Vielleicht war es an dem Tag eine ungünstige Konstellation.

Meine Meinung zu dem Thema darf ich wohl äußern, auch wenn ich nicht 24/7 PVP spiele.

**Comment by L4Z3** [comment]
@Feddebla 1x die Woche, wie du es beschrieben hast und 70-80% der Arathibecken in denen die Stammgruppe spielt, wie ich es erlebe, ist halt ein gewaltiger Unterschied. Nichts für ungut.

**Comment by Archidamos** [comment]
Selbst wenn es so wäre, dass es durch die Stammgruppe gehäuft autritt, was ich vehement bestreiten würde, kann man deshalb nicht verlangen, dass die Gruppe sich nicht mehr anmelden darf sondern sollte darauf bestehen, dass das Problem, welches eh schon lange reportet wurde schneller gefixt wird. Ansonsten wirkt das genau wie oben erwähnt.

**Comment by Testear** [comment]
bisschen käse zum whine?

pls close

**Comment by ircfelix** [comment]
Zum Problem #1:

Den Bug dass man ein Bg einfach nicht joinen kann, kenne ich auch. Eine Möglichkeit könnte sein dass z.b. bei 11 Allies und 10 Hordlern in der Wsg Warteschlange alle 11 einen invite kriegen, aber nur dir schnellsten 10 joinen können. Allerdings sollten die ersten 10 Anmelder vor dem 11. Anmelder rein dürfen. Vll. liegt es daran?

**Comment by L4Z3** [comment]
@Testear Spar dir solche Posts. Danke

**Comment by Testear** [comment]
ich habe in meinem ersten post erläutert, warum dein bugreport unsinn ist.

dannach stand dort nur noch geflame. so pls close

**Comment by ErnisKommentar** [comment]
Wir reden hier von Klassik-PvP. Ungleichgewichte wie 17-13 haben überhaupt keine Bedeutung. Ich habe in Klassik zusammen mit einem Elfenkrieger, also zu zweit, ganze Wellen von Hordlern zermetzelt im Alteractal! Können spielt hier noch ne Rolle. Zumindest wenn nicht betrogen wird wie auf den Originalservern wie seit MoP. Und es spielt auch keine Rolle, ob der andere Typ Naxxramas-Ausrüstung trägt und man selbst nur ein blaues Set hat. Ja Können spielte früher im PvP eine Rolle. Deshalb ist ja auch das aktuelle PvP im offiziellen aktuellen WoW seit MoP klinisch tot und wird wenn überhaupt nur noch von Idioten, Bots und Betrügern praktiziert. Gut, die Spielmechanik ist zwar hier vor allem im PvP extrem fehlerhaft, aber sogar diese fehlerhaften Klassikmechaniken sind ausgereifter als die funktionsfähige Idiotenmechanik auf den aktuellen Originalservern - seit MoP. Leider melden sich für PvP auf den Privatservern kaum Leute an. Bedauerlich. Sollte es zusätzlich durch solche Fehler verhindert werden, dass SChlachtfelder aufgehen, wäre das natürlich auch nicht hilfreich.
