### ISSUE TITLE
Diremaul Buffs // Fengus

### ISSUE THREAD

**Issue by Bladsn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#945]
Welches Verhalten wird beobachtet? 
Der Buff "Fengus' Wildheit" hat zwei Fehler. 
a) 200 Angriffskraft 
b) Nahkampfangriffskraft

Wie sollte es sich verhalten?
a) 100 Angriffskraft 
b) Nah- und Distanzangriffskraft

Effekt #1	Apply Aura: [Mod Melee Attack Power]
Wert: 100
Effekt #2	Apply Aura: [Mod Ranged Attack Power]
Wert: 100
Quelle: http://de.wowhead.com/spell=22817/fengus-wildheit

Grüße

**Comment by ircfelix** [comment]
Dir ist bewusst dass deine Quelle nicht von 2005-2007 und der bugreport somit fehlerhaft ist?

**Comment by Bladsn** [comment]
Alles relevante und wichtige steht drin, lass den Rest bitte die Dev's entscheiden. 
Dennoch vielen Dank für deine Anteilnahme.

**Comment by Slimmer2** [comment]
http://db.vanillagaming.org/?spell=22817

**Comment by Bladsn** [comment]
Anderer Privatserver, andere Datenbank -> keine zuverlässige Quelle.

**Comment by Bladsn** [comment]
http://wowdata.buffed.de/spell/Fengus-Wildheit-22817 
http://ptr.wowraider.net/spell/22817/de/Fengus'-Wildheit 

Zwei weitere Quellen die ich auf Anhieb finde ohne großen Aufwand.

**Comment by Brgs** [comment]
Schau dir mal das Changelog von dem Buff auf wowhead an.  

"Fengus' Ferocity	6.0.1 (Mon Oct 13 2014) Build 18125" 

Sprich: Der Buff wurde erst am 13.10.2014 auf 100 AP geändert, die vorherigen Versionen von dem Buff haben immer 200 AP

**Comment by Bladsn** [comment]
Da stimme ich Dir wohl überein, mein Fehler. 

Dennoch fehlt der Range-AP Wert. 

Effekt #1	Apply Aura: Mod Attack Power
Wert: 200
Effekt #2	Apply Aura: Mod Ranged Attack Power
Wert: 200

weitere Quelle: http://wow-mania.com/armory/?spell=22817

**Comment by ircfelix** [comment]
Bladsn, nutze doch bitte den classicwowresearcher, den ich ins Forum gestellt habe. Bei der Suche "tools" eingeben oder alternativ das Talk&Allgemeines durchsuchen.  Das Programm ist genau dafür ausgelegt alte Datenbanken und Infoseiten zu durchforsten. Dann findest du auch richtige Quellen. 

Danke aber für die Anteilnahme und Mühe die du dir bisher gemacht hast.

**Comment by dagochen** [comment]
Oder einfach mal nach Worldbuffs + Jäger + WoW 1.12 suchen....dann findet man raus, dass ALLE BUFFS (mit Ausnahme der Hunter-Volltreffer-Aura!) die +Angriffskraft geben KEINE RAP geben.

**Comment by nightblizard** [comment]
Ist kein Bug
