### ISSUE TITLE
Priester Schattenverwundbarkeit widersteht

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#946]
Welches Verhalten wird beobachtet?
Wenn man 5/5 Skillpunkte in Schattenwirken hat, wird Schattenverwundbarkeit widerstanden.

Wie sollte es sich verhalten?
Wenn man beim Talent Schattenwirken 5/5 Skillpunkte hat sollte jeder Schattenzauberschaden der das Ziel trifft Schattenverwundbarkeit am Ziel zu 100% auslösen
Bei 1/5 zu 20%
bei 2/5 zu 40%
bei 3/5 zu 60%
bei 4/5 zu 80%
Wenn ein Schattenzauber Widerstanden wird, soll natürlich keine Schattenverwundbarkeit ausgelöst werden

Schritte zur Reproduzierung
5/5 Skillpunkte in Schattenwirken Skillen und mit Schattenschaden NPC killen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)

Schattenschadenzauber: Kleinere Ränge gehören auch dazu
http://datenbank.welli-it.de/?spell=19280
http://datenbank.welli-it.de/?spell=18807
http://datenbank.welli-it.de/?spell=10947
http://datenbank.welli-it.de/?spell=10894

Talent
http://datenbank.welli-it.de/?spell=15334

Schattenverwundbarkeit hoffe das ist der richtige spell
http://datenbank.welli-it.de/?spell=15258

**Comment by Wosser** [comment]
Nope. http://forums.elitistjerks.com/topic/8487-spell-vulnerability-resist-mechanics/#entry209440

**Comment by Slimmer2** [comment]
Hier gehts um die Schattenverwundbarkeit von Priester und nicht Hexer in deinen Link geht es um Shadowbolt

**Comment by Wosser** [comment]
In meinem Link geht es um jeden Debuff. Imp. Shadowbolt, Imp. Scorch, Ignite, Schattenverwundbarkeit, Winters Chill... jedem dieser Debuffs kann separat widerstanden werden, auch wenn der verursachende Zauber getroffen hat und man eine Apply-Chance von 100% geskillt hat.

**Comment by dagochen** [comment]
1% Restchance bleibt halt erhalten.

**Comment by Slimmer2** [comment]
aktuell sind es aber deutlich mehr als die 1%

**Comment by Haudraufinix** [comment]
Schaut doch mal Wossers link an, da ist erklärt, dass der Grundzauber (z.B. Gedankenschlag) unabhängig vom Talent Schattenverwundbarkeit resistet werden kann und auch anders herum. Beide Effekte haben die normale Misschance.
Heisst allerdings auch, dass es möglich ist, den Schattenschaden zu widerstehen aber dennoch von Schattenverwundbarkeit getroffen zu werden.

**Comment by 0815Priester** [comment]
Hi,
ich glaube es handelt sich einfach um einen bug den Blizzard in Classic einfach nicht mehr behoben hat. Aus dem bereits verlinkten thread http://forums.elitistjerks.com/topic/8487-spell-vulnerability-resist-mechanics/?p=211034

**Fact 1:** Pre-1.11, full points in Improved Scorch gave a 100% chance to apply a fire vulnerability debuff as long as the spell itself wasn't fully resisted

**Fact 2:** 1.11 goes live, and people start seeing the Improved Scorch debuff get resisted separately from the spell for the first time

**Fact 3:** The "Known Issues" sticky in the official Bug Report forum acknowledges something screwy with the fact that talents giving a 100% chance to proc an effect are getting resisted. This goes on the same list with many, many other known bugs.

Ich finde leider nicht mehr die Patchnotes wo Sie es gefixt haben. Aber das war definitv nicht mehr in Classic.

**Comment by dagochen** [comment]
Eh egal, da der Fix erst später kam ;)
