### ISSUE TITLE
Quest: Eine Schleimprobe...

### ISSUE THREAD

**Issue by Enloo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#947]
Ahoi,

Welches Verhalten wird beobachtet?
Nach dem Sammeln der "Schleimprobe aus dem Teufelswald" lässt sich diese am Testset nich zu "Verderbte Probe aus dem Teufelswald" wandeln. Es wird beim Anklicken nur "Seid gegrüßt" angezeigt

Wie sollte es sich verhalten?
Das Testset müsste interagiern und die Probe in "Teufelswaldschleimprobe" wandeln. Diese lässt sich öffnen und mit einer Dropchance "Verderbte Probe aus dem Teufelswald" beinhalten.

Schritte zur Reproduzierung
Quest "Eine Schleimprobe..." und "...und eine Menge Brühschlammer" annehmen,
4x "Verderbte Probe aus dem Teufelswald" erhalten und "...und eine Menge Brühschlammer" absolvieren.
Dann nochmal versuchen "Schleimprobe aus dem Teufelswald" zu wandeln.
Evtl besteht auch ein Zusammenhang mit dem gestrigen Server-Neustart (28.7.15).

Zusätzliche Informationen (Screenshots, Videos, etc.)
Namen aus der Datenbank stimmen nicht mit den Namen aus dem Spiel überein.

Serverversion 1.1.0
Links aus unserer Datenbank
http://datenbank.welli-it.de/?quest=4293

**Comment by Wosser** [comment]
Hab beide Quests letztens gemacht, bzw. angefangen weil die Dropchancen Questitems aus den Beuteln so blöd is, hatte aber keine Probleme dabei. Du weißt dass da zwei Testsets auf dem Tisch stehen, jeweils eins für jede Quest?

**Comment by Papuelspapals** [comment]
Fehler nach einem Jahr immer noch vorhanden.
