### ISSUE TITLE
Schlachtstandarten stacken

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#948]
Schlachtstandarten können mehrfach gestackt werden.

Es kann auch passieren, dass man den Standartenbuff aus dem BG behält wenn man aus dem BG rausgeht (bis man reloggt). Dadurch behält man manchmal die HP ohne den Buff zu haben - ich schreibe manchmal weil uns die Ursache nicht klar ist.

http://www.directupload.net/file/d/4063/r29e3hxs_png.htm

Schlachtstandarten sollten nicht stacken und den Buff nur im BG gewähren. Die HP sollten abgezogen werden, sobald man das BG verlässt.

Bitte nehmt die Schlachtstandarten aus dem Spiel, bis sie richtig funktionieren.

**Comment by Gromnir** [comment]
Ahoi,

ist mir heute auch zum ersten mal aufgefallen. Hängt das vllt auch irgendwie mit dem letzten fix zusammen? (falls dieser schon auf dem Server eingespielt ist)

#938

Ansonsten würde ich hier beide Seiten darum bitten Fair zu sein und die Leute zu benachrichtigen und auch aufzufordern, während dem BG zu reloggen falls jemand von diesem Bug betroffen ist.

Wirklich schade das die Standarte solche Probs verursacht :/

**Comment by Testear** [comment]
Das mit dem Ausloggen ist problematisch, weil man dann - da wir in grp anmelden - die Warteschlange verlässt.

**Comment by Gromnir** [comment]
Joa, ich denk mal beide Seiten einfach bisschen zurückhalten mit der Standarte bis die richtig funzt. Verbieten wäre natürlich bitte, kann es aber nachvollziehen.  
Wenns mal in nem BG passiert und man nicht ausloggen will/kann, dann bitte zur Seite stellen, da es sonst schlicht buguse wäre. 
Bug ist ja jetzt bekannt und sollte dann auch IG weiter kommuniziert werden, sodass keine unnötigen Probleme oder Flamewars entstehen.

**Comment by Lavinja** [comment]
push !

**Comment by wahaxlekuke** [comment]
Wie funktioniert das genau? Ich hab es mit Ausloggen und mit /afk versucht, aber bei mir verschwinden die HP immer wieder.

**Comment by Testear** [comment]
keine ahnung - wir wissen nur, dass es so ist und haben keine lust andauernd zu reloggen.

**Comment by Haudraufinix** [comment]
Ich hab nur ne vermutung, aber kann es sein, dass Last stand/Ausdauerbuffs etwas damit zu tun haben?

**Comment by Testear** [comment]
von unseren warris hat niemand last stand geskillt

**Comment by Testear** [comment]
Entfernt die Dinger bitte - Der bug wird von beiden Seiten genutzt und macht BGs absolut lächerlich.
