### ISSUE TITLE
Cenarisches Leuchtfeuer wirkt nicht nur im Teufelswald

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#949]
Das Item Cenarisches Leuchtfeuer sollte es einem erlauben, von Pflanzen die im Teufelswald heimisch sind Teufelsunholde abzuernten, von Monstern aus dem Teufelswald Seelensplitter zu erbeuten sowie durch Kürschnerei und Bergbau ein verderbtes Material zu erhalten. Auf unserem Server können leider Kräuterkundler und Bergbauer diesen Effekt auf der ganzen Welt benutzen und nicht nur im Teufelswald.
Was harmlos klingt hat einen doch recht grossen Einfluss auf die  Wirtschaft, da so gut wie jedes hochlevelige Kraut zwischen  18 und 56 silber zusätzlich enthält (4 Teufelsunholde können als Quest für 75 silber und 2 Cenarische Pflanzensalben abgegeben werden)

Quellen:
http://wowwiki.wikia.com/Cenarion_Beacon
_You must first complete the quest Cleansing Felwood given by Arathandris Silversky (Alliance) or Maybess Riverbreeze (Horde), who can be found near the road to Emerald Sanctuary. You will be given a [Cenarion Beacon], which, when held in your inventory, allows you to collect [Corrupted Soul Shard] from mobs in Felwood. You can also collect other drops based on your profession. For example, you will collect Fel Creep every time you gather herbs or Tainted Vitriol every time you mine ore. These items only drop in Felwood. You can repeatedly turn in quantities of these items to the NPC and get two Cenarion Plant Salve in exchange._

http://wowwiki.wikia.com/Fel_Creep
_Fel Creep is found while collecting herbs in Felwood while in possession of a Cenarion Beacon._

Prequest: http://datenbank.welli-it.de/?quest=4101
Leuchtfeuer: http://datenbank.welli-it.de/?item=11511
Teufelsunhold: http://datenbank.welli-it.de/?item=11514
verderbter Seelensplitter: http://datenbank.welli-it.de/?item=11515
besudeltes Vitriol: http://datenbank.welli-it.de/?item=11513
besudelter Hautfetzen: http://datenbank.welli-it.de/?item=11512

Questnpc: http://datenbank.welli-it.de/?npc=9528

**Comment by hraesvelgr** [comment]
war dasnichtmal gefixt worden?

**Comment by dagochen** [comment]
das was mal gefixt wurde war, dass die kräuter/erze dann für andere nicht mehr lootbar waren, wenn jemand mit cenarischem leuchtfeuer die nicht leer gemacht hat, oder?

**Comment by hraesvelgr** [comment]
ja, hast recht.
