### ISSUE TITLE
Undercity Meldung der Wachen "Schneider" vs "Inschriftenkunde"

### ISSUE THREAD

**Issue by Taasch** [ClassicWoW/Nefarian_1.12.1_Bugtracker#950]
Der Schneider wird einem nicht angezeigt, sondern nur ein Inschriftenkundler.
![30-07-2015 11-36-08](https://cloud.githubusercontent.com/assets/13570145/8981273/41d38036-36b7-11e5-806d-2453c9258b02.jpg)

**Comment by hraesvelgr** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/729
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/599
