### ISSUE TITLE
Quest: Erlösung (Tirion Fordring)

### ISSUE THREAD

**Issue by MasterX141** [ClassicWoW/Nefarian_1.12.1_Bugtracker#951]
Es handelt sich hierbei um diese Quest: http://datenbank.welli-it.de/?quest=5742 .

Nach Abgabe der 3 Vorquests, startet diese Quest. Jedoch spricht er nicht und es passiert leider rein gar nichts.

**Comment by hraesvelgr** [comment]
Fortschritt
Please, friend; sit and hear my tale. 

ähm..machs einfach
setz dich hin udn hör ihm zu. der meint das wörtlich.

**Comment by Sabbaer** [comment]
jo, is kein bugg, du musst dich hinsetzen ;)
