### ISSUE TITLE
PvP als Gruppe anmelden nicht möglich

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#952]
Wenn man PvP als Gruppe oder als Schlachtzug anmelden möchte ist das nicht möglich.

Wie sollte es sein:

Man sollte PvP sowohl als Gruppe als auch als Schlachtzug anmelden können.
Quelle: Es gibt einen Knopf beim PvP-Anmelder auf dem steht: "Als Gruppe betreten".

**Comment by Lavinja** [comment]
push ! 

sonst seh ich die ohnehin schon kleine pvp szene als ausgestorben an leider

**Comment by Testear** [comment]
Danke sehr
