### ISSUE TITLE
Quest: Die ultimative Täuschung (Silithus Logistikauftrag XI)

### ISSUE THREAD

**Issue by zabulock** [ClassicWoW/Nefarian_1.12.1_Bugtracker#954]
Für die Quest "Die ultimative Täuschung" im Rahmen der Silithus Logisitk Quests, habe ich alle benötigten Materialien zusammen.
Die Quest wird mir im Questlog auch als FERTIG angezeigt.
Mein Problem:
Die Quest sollte man bei Aurel Golblatt abgeben können, allerdings leuchtet über ihr kein gelbes Fragezeichen, sondern lediglich gelbe Ausrufezeichen .
Klicke ich sie an, so wird mir meine fertige Quest auch als fertig angezeigt und sollte daher beendet werden können.
Allerdings passiert nichts wenn ich auf "Quest beenden" klicke, sodass ich diese Quest leider nicht abschließen kann.
Hilfe! :)

![wowscrnshot_080115_121427](https://cloud.githubusercontent.com/assets/13599429/9021558/432543ba-3848-11e5-99ce-2f18e6b6e64a.jpg)
![wowscrnshot_080115_121441](https://cloud.githubusercontent.com/assets/13599429/9021559/432950c2-3848-11e5-994f-b4cf3e52e78d.jpg)

**Comment by Slipru** [comment]
Quest abbrechen und neu annehmen, kann bei allen Sammel Quest derzeit passieren, allerdings weiß ich nicht wann oder wodruch der Fehler ausgelöst wird :/
