### ISSUE TITLE
BWL: Corinna Stähler

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#955]
Hi,

könntet ihr diesen nervigen Trashmob, der aus dem Nichts erscheint und gerne mal den halben Raid tötet, rauspatchen?

Danke! :-) :+1:

**Comment by Slimmer2** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/719

**Comment by Slimmer2** [comment]
Und der Mob heist Corina Stähler
http://datenbank.welli-it.de/?npc=54

**Comment by Haudraufinix** [comment]
Und erscheint nicht, sondern bleibt unsichtbar. Bei uns taucht der Mob idr. beim Techniker Trashpack rechts im Raum hinter Brutwächter Dreschbringer auf.

**Comment by Seniorash** [comment]
Felix gib dir doch mal mehr Mühe! Hast du schon mal die Reportvorlage gesehen?

**Comment by dagochen** [comment]
Frag mich ja echt, warum Leute, denen ich so gut ich es selbst halt weiß erkläre, wieso der Bug auftritt und das daran bereits gearbeitet wird und das es bereits einen Bugreport dazu gibt, hingehen und NOCH EINEN sinnfreien und dämlichen Bugreport zum selben Thema OHNE Zusatzinhalt/Zusatzinformation erstellen.... vermutlich wollen einige echt nicht, dass ernsthaft am Server entwickelt wird und versuchen die Arbeit auf jegliche Art und Weise zu sabotieren....

**Comment by Haudraufinix** [comment]
Tja Dagochen, nicht jeder weis, wie Mangos funktioniert. Einige denken sich halt das ist keine grosse Sache den Mob zu finden und zu fixen. Er hats ja nicht böse gemeint.

Leider wie gesagt, Problem bekannt und ich glaube es wird daran gearbeitet. Der Bug ist ziemlich hartnäckig und hatte schon aufm Offi damals sehr viele Probleme bereitet. Ihr werdet euch also wohl noch ein paar wochen mit frau Stähler rumschlagen müssen.

Mein Tipp wie der Raid den Mob umgehen kann:
Technikergruppen wo Frau Stähler mitkommt von einem Hunter pullen lassen, dann soll sofort jeder auf seinen Techniker irgend nen Spell wirken, damit die Techniker nicht nur den Jäger in der Aggroliste hat. Dann kann sich der Jäger totstellen. So habt ihr gute Chancen, Corinna wieder deaggroen zu lassen.
Weiterhin denk ich den Bugreport kann man schliessen ;)

**Comment by Slimmer2** [comment]
Habt aber schon gesehen das der andere report behoben ist

**Comment by ircfelix** [comment]
Also, Dago hat gestern im raid gemeint dass der Bug schobmal behoben wurde und immer noch buggy ist. Er hat aber nix davon gesagt, dass immer noch dran gearbeitet wird und hellsehen kann ich leider auch nicht.

Da der Bug schon bekannt ist und laut dago auch wie er zustande kommt, habe ich diesen Post als eine Art /push eröffnet. Ich entschuldige mich hiermit bei dir dago, ich wollte deinen Puls nicht in die Höhe treiben und auch nicht bewirken dass du dich mal wieder aufführst wie ein arroganter .... .
