### ISSUE TITLE
Azuregos: Sprachfehler beim Teleport

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#956]
**Welches Verhalten wird beobachtet?**

Azuregos Schrei, den er bei jedem Teleport los lässt, lautet "Kommt, ihr Wichtel!..."

**Wie sollte es sich verhalten?**

Der Schrei sollte "Kommt, ihr Wichte! Tretet mir gegenüber!" lauten.
Dies ist u.a. dadurch zu begründen, dass gerade die Wichtel wegen der Phasenverschiebung nicht zu ihm kommen werden. Von daher ist der Schrei mit den Wichteln unsinn.

**Quelle**

KLH Threat Meter v17.22 in "KTM_deDE.lua"(145) ["azuregosport"] = "Kommt ihr Wichte! Tretet mir gegen\195\188ber!",

**Links aus unserer Datenbank**

Azuregos: http://datenbank.welli-it.de/?npc=6109

**Comment by dagochen** [comment]
UPDATE script_texts SET content_loc3 = 'Kommt ihr Wichte! Tretet mir gegenüber!' WHERE entry = -1000100;

**Comment by hraesvelgr** [comment]
komma nicht vergessen :^)

**Comment by Larnak1** [comment]
Wenn im KTM kein Komma drin ist, gab's damals wahrscheinlich auch keines, sonst hätte die Erkennung nicht funktioniert.

**Comment by hraesvelgr** [comment]
aber aber aber.... grammatik :o

**Comment by Slimmer2** [comment]
Dann einfach bei den Addons das abändern, dann sollte es auch gehen.

**Comment by dagochen** [comment]
Da muss kein Komma hin. Bei mir in der Schule hieß so ein Komma, welches nicht zwingend gesetzt wurde musste, "Kann-Komma". Sprich: Es kann gesetzt werden, muss aber nicht.

**Comment by Gnomorus** [comment]
Ist nicht "Auf Nefarian". Beim heutigen Azuregos Kill hat er noch seinen alten Spruch aufgesagt.

**Comment by dagochen** [comment]
Server Uptime: 23 h
Auf Nefarian labeled: 17 h ago

--> Neustart, dann ist es aktiv.

**Comment by Gnomorus** [comment]
Bitte wieder öffnen. Beim heutigen Azu kill war immer noch der alte Spruch am Start.

**Comment by wahaxlekuke** [comment]
Irgendwas ist da wohl schief gelaufen. Zumindest hab ich den Text nun nochmal korrigiert.

**Comment by Gnomorus** [comment]
Passt. Danke.
