### ISSUE TITLE
Reflektionsschaden durch Gottesschild

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#957]
Welches Verhalten wird beobachtet?
der reflektionsschaden durch Sulfuras, Hand von Ragnaros und Aura der Vergeltung und viele andere reflektionsitems kriegt der gegner trotzdem, obwohl ein Paladin Gottesschild aktiviert hat.

Wie sollte es sich verhalten?
Der Reflektionsschaden darf nicht auf npcs sowie spieler gehen, wenn Gottesschild aktiviert ist, da der Paladin auch keinen schaden bekommt.

Schritte zur Reproduzierung
reflektionsitems anziehen, bubble drücken, von irgendwas hauen lassen

Zusätzliche Informationen
http://wowwiki.wikia.com/Divine_Shield?oldid=267261

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?search=Divine+shield

**Comment by dagochen** [comment]
Wo steht, dass andere Spieler/NPCs keinen Schaden bekommen, wenn sie einen Sulfuras-Pala mit Bubble hauen?

**Comment by Sabbaer** [comment]
der schaden wird nur zurückgeworfen, wenn der spieler auch schaden erleidet

**Comment by dagochen** [comment]
Wo steht das Wort "reflect"? Dann post doch einfach so ein Video, damit die Sache klar ist. Oder erwartest du im Ernst, dass jetzt die Devs hingehen und Videos suchen?

**Comment by Sabbaer** [comment]
hae?

**Comment by Sabbaer** [comment]
https://www.youtube.com/watch?v=mbZMRFIi85E
cromer 3 retribution   release 04.07.2006

**Comment by Sabbaer** [comment]
upsi verklickt mit dem close ;)

**Comment by dagochen** [comment]
Man sieht keine 5 Dmg aufploppen weil der Schurke nicht zuhaut. Sonst würde man im Combatlog ja auch das die Immun-Meldungen sehen....aber da is totaler Stillstand. Wenn ein Pala das Schild an hat und dann jemand nicht zu haut, nimmt man logischerweise keinen Schaden. Ansonsten nimmt man Schaden, weil man ja angreift. Von reflektieren steht da immer noch nix, also bitte wirklich closen, danke ;)

**Comment by Sabbaer** [comment]
1. das ist ein krieger
2. das ist definitiv falsch und ich werde das nicht closen und ich werde das dir beweisen, abwarten, es gibt leider nicht soviele raggi kolben pala videos.
ich kann leider grad noch nichts hochladen, weitere beweise aus dem video kommen, ist schon geschnitten und fertig, leider ist meine leitung was den upload angeht extremst bescheiden.

**Comment by dagochen** [comment]
Auch wenn die Mechanik iwie keinen Sinn ergibt, scheint ja doch so zu sein ;)
