### ISSUE TITLE
MC: Magmadar Feuer macht kein Schaden

### ISSUE THREAD

**Issue by Slimmer2** [ClassicWoW/Nefarian_1.12.1_Bugtracker#958]
Welches Verhalten wird beobachtet?
Der Boss macht Feuer auf dem Boden, wenn man drinnen stehen bleibt, bekommt man keinen Schaden vom Feuer.
Der Feueratem den man bekommt macht auch keinen Schaden auf andere Spieler.

Wie sollte es sich verhalten?
Wenn man in den Feuer stehen bleibt sollte man Schaden bekommen

Schritte zur Reproduzierung
Magmardar pullen und dann in das Feuer Stellen

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?npc=11982
http://datenbank.welli-it.de/?spell=19411
http://datenbank.welli-it.de/?spell=19272

**Comment by Gnomorus** [comment]
relatiert #575

**Comment by Slimmer2** [comment]
Bei den anderen Report fehlt der Flamenatem den die Spieler bekommen. 
Der macht ja aktuell auch keinen Schaden bei Mitspielern die man damit anhaucht.
Die Suche gehört verbessert, da man oft bei Suchen nichts findet und dann Doppelt reportet
