### ISSUE TITLE
Uldaman Erforschung der geheimen Kammer  Quest

### ISSUE THREAD

**Issue by Mafyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#96]
Welches Verhalten wird beobachtet?
-Lest Baelogs Tagebuch, erforscht die geheime Kammer und erstattet dann Ausgrabungsleiter Stormpike Bericht. Nach besiegen vo Ironaya begibt man sich in besagten Raum  aber die Quest wird nicht abgeschlossen

Wie sollte es sich verhalten?
- Wenn man den Raum tiefer betritt schliesst man die Quest mit der erkundung ab

Schritte zur Reproduzierung
- Erkundung abschliessen nach betreten der Geheimen Kammer. siehe video

Zusätzliche Informationen 
- https://www.youtube.com/watch?v=QAN-n4HVeoA&feature=player_detailpage#t=149

**Comment by ErnisKommentar** [comment]
Um das zu beheben müsste man ca. 5 Minuten investieren. Der FEhler ist aber schon seit 3 Jahren im Spiel.
