### ISSUE TITLE
Schurken Combo Punkte Verlust bei Zielwechsel

### ISSUE THREAD

**Issue by hackyo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#960]
Vorweg, ich habe weder im Forum noch hier etwas dazu gefunden, denke aber dass es ein bekanntes Problem ist. Ich möchte nur hier der Form halber nochmal drauf hinweisen.

Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.:

Man verliert als Schurke seine auf dem gegenwärtigen Ziel aufgebauten Combopunkte, durch "abvisieren" desselben, ohne Combopunkte auf einem anderen Ziel aufgebaut zu haben. Um sich beispielsweise selbst ins Ziel zu nehmen & zu bandagieren.

Server-Version:

Last Core Update: [26.07.2015] Version: [1.1.0]

Wie sollte es sein?

Combopunkte, welche auf dem gegenwärtigen primären Ziel (A) aufgebaut wurden, sollten auch nach anvisieren eines anderen  Gegners, freundlichen / neutralen NSC oder Spielern bzw. sich selbst, auf dem primären Ziel (A) erhalten bleiben, solange keine Combopunkte auf einem anderen Ziel aufgebaut wurden.

Wie ist es?
Man verliert alle aktiven Combopunkte durch abvisieren des gegenwärtigen Ziels. 

Links:
-
Quelle:
 https://youtu.be/1C7Uvt_0oYs?t=6m23s

Anmerkung:
Zu sehen bei Minute 6:23, der linkte sollte einen aber auch automatisch dahin bringen. 

Wie dort eindeutig zu sehen ist, baut er erst 5 Punkte auf, wird dann gecoiled, gefeared hat das Pet vom Warlock im Ziel, sprintet zum Warlock nimmt diesen ins Ziel und hat immernoch alle 5Punkte mit welchen er Ausweiden macht.

 die Videobeschreibung lautet wie folgt: 
"Hochgeladen am 16.06.2011
For the morons who keep insisting this was not from live servers some of the footage comes from this movie: http://www.warcraftmovies.com/movieview.php?id=29067

Notice that the upload date is October 2006. Explain that away, idiots."

Das stelle ich zumindest mal zur Diskussion.

Vielen Dank,
 <3<3

**Comment by dagochen** [comment]
Leider falsch, gab schon paar Beschwerden darüber im Forum, aber ist korrekt so wie es aktuell implementiert ist.  

Patch 1.4.0 (2005-05-05): Combo points will no longer be removed if the target is deselected. They will only be removed if a different target is selected.

As of Patch 2.0.3, the rogue will not lose Combo Points upon switching targets until a point has been added to another target.

Quelle: 
http://wowwiki.wikia.com/Combo_point
http://wowwiki.wikia.com/Patch_1.4.0
http://wowwiki.wikia.com/Patch_2.0.3

**Comment by nightblizard** [comment]
Ist kein Bug.
