### ISSUE TITLE
Arkankristall Droprate

### ISSUE THREAD

**Issue by signs4** [ClassicWoW/Nefarian_1.12.1_Bugtracker#962]
Welches Verhalten wird beobachtet?

Ich habe heute über 300mal Thoriumerz aus reichen Vorkommen gefarmt und nicht 1 Kristall bekommen.
Droprate Arkankristall laut Datenbank hier: http://datenbank.welli-it.de/?item=12363

Wie sollte es sich verhalten?

Droprate laut Klassikdatenbanken:
http://de.wowhead.com/item=12363/arkankristall#mined-from-object
http://wowdata.buffed.de/item/Edelstein/Arkankristall-12363#mined

Zusätzliche Informationen (Screenshots, Videos, etc.)
Klar unterscheiden sich die Dropraten der von Buffed und WOW-Head jedoch ist es immer schon und auch zu Klassikzeiten so gewesen, dass aus reichen Vorkommen mehr Kristalle kommen als aus kleinen.

Links aus unserer Datenbank (hier gehts zur Datenbank)
http://datenbank.welli-it.de/?item=12363

**Comment by Gnomorus** [comment]
Du hattest Pech oder einen Charaktercharakter. Normalerweise wird man hier mit Arkanit totgeworfen.

**Comment by Pennywiize** [comment]
Die Dropraten sind wirklich normal. Wenn ich von meinem Farmchar die Taschen leere, habe ich neben ca. 360 Thoriumerzen, diverse verdichtete Steine und anderen Steinchen, auch immer zwischen 10 und 16 Arkankristalle dabei. Aber manchen Tagen läufts besser und an anderen weniger - ist halt eine Glückssache.

**Comment by dagochen** [comment]
http://web.archive.org/web/20061026005948/http://wow.allakhazam.com/db/item.html?witem=12363

Laut den Kommentaren sollten die auch nur in reichen Vorkommen enthalten sein...die Prozentangaben von 3% in unserer DB sind aber wohl korrekt.

**Comment by Slimmer2** [comment]
WOWhead und buffed eine aber keine classic Abgaben

**Comment by dagochen** [comment]
@Slimmer2 Ja, das haben einige immer noch nicht begriffen...

**Comment by signs4** [comment]
Habt ihr überhaupt mal zu Klassikzeiten gespielt? Oder seid ihr nur wieder solche die zu geizig für nen offi sind und deshalb hier anfangen? Also ich habe zu Klassikzeiten immer nur auf Buffed geschaut, das war glaub auch die einzige deutschsprachige Seite und ich weißt das es nen Dropunterschied das es zwischen dem kleinen und großen Thoriumvorkommen gab.
Was nun deinen tollen Link von http://web.archive.org/web/20061026005948/http://wow.allakhazam.com/db/item.html?witem=12363 betrifft: auch das weich von der Datenbank hier ab - vergleiche dazu mal das Hakkari Thoriumvorkommen

**Comment by Haudraufinix** [comment]
Buffed WAR einmal ne Classic Datenbank. Buffed hat allerdings all ihre Items und Werte auf den aktuellen Content umgeschrieben. Heisst da stehen mittlerweile Arkankristallwerte aus WoD Thoriumvorkommen drin!

Ausserdem, ich weis nicht ob du dich mit Warscheinlichkeiten auskennst, aber 3% Dropprate besagt NICHT, dass du auf 100 Thoriumvorkommen garantiert 3 Kristalle kriegst. Also bete einfach zu RNGsus dass du bald welche findest.

**Comment by nightblizard** [comment]
Dropchancen stimmen mit denen in der Datenbank überein. Hier simuliert an 1.000.000 Lootvorgängen:
![Bild](http://puu.sh/jrQxY/3767d5ee53.jpg)

Sollten die Dropchancen an sich inkorrekt sein, bitte gesondert mit korrekten Quellangaben posten.

**Comment by Seniorash** [comment]
Das einzige was an den Kristallen buggy ist, ist dass sie aus kleinen vorkommen abgebaut werden können. Aber da es viel zu wenig reiche vorkommen gibt, wäre der fix entsprechend kacke
