### ISSUE TITLE
Talen wird als Zivilist gewertet - jedoch nicht so angegeben

### ISSUE THREAD

**Issue by Sojabohne** [ClassicWoW/Nefarian_1.12.1_Bugtracker#963]
Hallo zusammen,

habe eben bei Koords: ca 13, 31 einen Nachtelfen Namens Talen umgehauen. Leider wurde er als ruchloser Mord gewertet, was ich nicht so toll finde, denn er war nicht als PvP/Zivilist getaggt

Gibt es eine Möglichkeit sowas rückgängig zu machen? War ja nicht mein Fehler. Bin da etwas Eitel.. sorry ;)

Und wäre es nicht sinnvoll, ihn richtig zu Taggen?

Habe drei Screenshots angehängt. Gerne könnt ihr mich ingame erreichen. 

Mfg Sojabohne

![wowscrnshot_080715_180607](https://cloud.githubusercontent.com/assets/13696872/9140641/0675de3a-3d33-11e5-8118-8069ead4f5df.png)
![wowscrnshot_080715_180613](https://cloud.githubusercontent.com/assets/13696872/9140642/06782bf4-3d33-11e5-9c88-fc58167af566.png)
![wowscrnshot_080715_180619](https://cloud.githubusercontent.com/assets/13696872/9140643/06802084-3d33-11e5-8445-1d2241babc16.png)

**Comment by Slimmer2** [comment]
http://datenbank.welli-it.de/?npc=3846
Er ist ein Questgeber, und deswegen ein Zivilist ist.

Zudem ist es Buggy und nach der nächsten PvP Abrechnung wird es nicht mehr angezeigt.

**Comment by dagochen** [comment]
Außerdem mit Stufe 31 kleine arme Nachtelfen umzuhauen ist schon ziemlich ruchlos.....

**Comment by Sojabohne** [comment]
Danke Slimmer2, vielleicht sollte man die NPCs dann auch als Zivilist taggen? Gut zu wissen, dass es dann nicht mehr angezeigt wird. 

dagochen, ja da hast du recht, aber ich war grade so in fahrt :D 

danke euch fürs beantworten
