### ISSUE TITLE
Respawnzeiten der Kampfmeister in den Hauptstädten zu lang

### ISSUE THREAD

**Issue by Gromnir** [ClassicWoW/Nefarian_1.12.1_Bugtracker#965]
Ahoi ahoi,

Welches Verhalten wird beobachtet?
Die Kampfmeister für die Schlachtfelder haben zum Teil sehr unterschiedliche Respawnzeiten. Aufgrund des folgenden Threads wäre es sinnvoll, den Kampfmeistern eine einheitliche und angemessene Respawntime zu verpassen.
http://community.mmobase.de/hilfe-und-support/7737-strafen-fuer-permanentes-bg-anmelder-toeten.html#post53712
http://community.mmobase.de/hilfe-und-support/7737-strafen-fuer-permanentes-bg-anmelder-toeten.html#post53718

Wie sollte es sich verhalten?
Finde keine spezifische Quelle zu genauen Timern. Ist eher ein Vorschlag/Wunsch um zukünftig unnötigen Frust und Ärger zu vermeiden. Ich hoffe der Aufschrei "nicht blizzlike" hält sich daher in Grenzen. 3-5 Minuten Respawn halte ich für angemessen. Sowohl Rogues als auch Raids können sich weiterhin austoben ohne das es für die andere Fraktion zu frustrierend ist. 

NPC IDs:
Kampfmeister der Kriegshymnenschlucht:
http://datenbank.welli-it.de/?npc=2302 - Teldrassil - 10 Minuten Respawn im Moment
http://datenbank.welli-it.de/?npc=14981 - Sturmwind - 3 Minuten Respawn
http://datenbank.welli-it.de/?npc=14982 - Ironforge - 1h 45 Min Respawn

http://datenbank.welli-it.de/?npc=2804 - Unterstadt - 15 Min 
http://datenbank.welli-it.de/?npc=3890 - Orgrimmar - 10 Min
http://datenbank.welli-it.de/?npc=10360 - Donnerfels - 20 Sek

Kampfmeister des Arathibeckens:
http://datenbank.welli-it.de/?npc=907 - Teldrassil - 10 Minuten
http://datenbank.welli-it.de/?npc=15008 - Sturmwind - 3 Minuten
http://datenbank.welli-it.de/?npc=857 - Ironforge - 20 Min

http://datenbank.welli-it.de/?npc=15007 - Unterstadt - 15 Min 
http://datenbank.welli-it.de/?npc=15006 - Orgrimmar - 10 Min
http://datenbank.welli-it.de/?npc=12198 - Donnerfels - 20 Sek

Kampfmeister des Alteractals:
http://datenbank.welli-it.de/?npc=5118 - Teldrassil - 10 Minuten
http://datenbank.welli-it.de/?npc=7410 - Sturmwind - 28 Minuten 
http://datenbank.welli-it.de/?npc=12197 - Ironforge - 1h 45 Min

http://datenbank.welli-it.de/?npc=347 - Unterstadt - 15 Min 
http://datenbank.welli-it.de/?npc=14942 - Orgrimmar - 10 Min
http://datenbank.welli-it.de/?npc=7427 - Donnerfels - 8 Min 20 Sek

Möglicher Fix für 3 Min Respawn: (Weiß nicht genau ob der SQL Befehl stimmt, bitte anpassen falls falsch. Hab keine DB zur Verfügung, nur Internet als Quelle)

```
UPDATE `creature_template` SET `spawntimesecs`=180 WHERE `entry` IN (2302, 14981, 14982, 2804, 3890, 10360, 907, 15009, 857, 15007, 15006, 12198, 5118, 7410, 12197, 347, 14942, 7427);
```

**Comment by dagochen** [comment]
Nicht ganz. `spawntimesecs` ist ein Feld in der Tabelle `creature` und dort findet man die Anmelder dann über ihre Id, welche entry referenziert.

Korrekt wäre also folgendes SQL:
`UPDATE creature SET spawntimesecs=180 WHERE id IN (2302, 14981, 14982, 2804, 3890, 10360, 907, 15009, 857, 15007, 15006, 12198, 5118, 7410, 12197, 347, 14942, 7427);`
