### ISSUE TITLE
Drain Mana Rank 4 nicht erlernbar

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#966]
Hallo! http://datenbank.welli-it.de/?spell=11704 sollte ab lvl 54 bei Warlock Lehrern erlernbar sein, bislang kann man aber nur die ersten drei Ränge erlernen.

Screenshot vom  World of Warcraft Official Strategy Guide: http://i.imgur.com/K11VSeM.png

**Comment by dagochen** [comment]
Habe mal allen Trainern, die auch Rang 3 beibringen können Rang 4 hinzugefügt.

INSERT INTO `npc_trainer` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) VALUES
('461','11706','44000','0','0','54'),
('906','11706','44000','0','0','54'),
('988','11706','44000','0','0','54'),
('2127','11706','44000','0','0','54'),
('3172','11706','44000','0','0','54'),
('3324','11706','44000','0','0','54'),
('3325','11706','44000','0','0','54'),
('3326','11706','44000','0','0','54'),
('4563','11706','44000','0','0','54'),
('4564','11706','44000','0','0','54'),
('5171','11706','44000','0','0','54'),
('5172','11706','44000','0','0','54'),
('5173','11706','44000','0','0','54'),
('5495','11706','44000','0','0','54'),
('5496','11706','44000','0','0','54'),
('5612','11706','44000','0','0','54');
