### ISSUE TITLE
Krieger: Wutanfall und Blutwahnsinn

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#968]
Wutanfall 
http://datenbank.welli-it.de/?spell=13048 
http://datenbank.welli-it.de/?spell=13047
http://datenbank.welli-it.de/?spell=13046
http://datenbank.welli-it.de/?spell=13045
http://datenbank.welli-it.de/?spell=12317
und Blutwahnsinn
http://datenbank.welli-it.de/?spell=16487
http://datenbank.welli-it.de/?spell=16489
http://datenbank.welli-it.de/?spell=16492

können im Sitzen ausgelöst werden. Das ist erst mit 2.3.0 eingeführt worden.

http://wowwiki.wikia.com/wiki/Patch_2.3.0

**Comment by wahaxlekuke** [comment]
Danke. Das sind genau die IDs, die ich gebraucht habe.
