### ISSUE TITLE
Krieger Schwertspezialisierung

### ISSUE THREAD

**Issue by ghost** [ClassicWoW/Nefarian_1.12.1_Bugtracker#969]
Die Schwertspezialisierung vom Krieger kann keine Extraangriffe nach dem Schwertprocc auslösen. Das ist erst mit 2.2.0 entfernt worden.

Sword Specialization: This talent’s free extra attacks can no longer trigger additional extra attacks. 

http://wowwiki.wikia.com/wiki/Patch_2.2.0

http://datenbank.welli-it.de/?spell=12281
http://datenbank.welli-it.de/?spell=12812
http://datenbank.welli-it.de/?spell=12813
http://datenbank.welli-it.de/?spell=12814
http://datenbank.welli-it.de/?spell=12815

**Comment by Seniorash** [comment]
Weißt du wie es mit Hand der Gerechtigkeit und Windfury aussieht?

**Comment by Testear** [comment]
Hand der Gerechtigkeit und Windfury sollen auf den Schwertprocc proccen können, aber soweit ich weiss - ohne, dass ich Quellen dafür habe - gilt bei diesen Dingen kein Procc auf Procc.
Habe nur diesen Expliziten Verweis auf die Schwertspezialisierung gefunden.

**Comment by testear** [comment]
https://www.youtube.com/watch?v=MVvl_x2CTrA

1:07 hat der Krieger einen Windfuryprocc folgend auf einen Schwertprocc.
