### ISSUE TITLE
Partielles Widerstehen bei Heiligschaden

### ISSUE THREAD

**Issue by Larirawiel** [ClassicWoW/Nefarian_1.12.1_Bugtracker#972]
Welches Verhalten wird beobachtet:
Gegner, die sich auf dem gleichen Level wie der Spieler oder darunter befinden widerstehen teilweise gegen Heiligschaden.

Wie sollte es sich verhalten?
Da es keinen Widerstand gegen Heiligschaden gibt, darf es partielles Widerstehen nicht geben. Zumindest nicht bei Gegnern, die sich auf Spielerlevel oder darunter befinden. Allerhöchstens ein Verfehlen ist möglich.

Quellen:
http://wowwiki.wikia.com/wiki/Holy_resistance
http://wowwiki.wikia.com/wiki/Magic_schools_(WoW)#Holy

Schritte zur Reproduzierung:
Die Staubstürmer in Silithus mit Heiligschaden angreifen.

Screenshot inkl. sichtbaren Kampflog:
http://666kb.com/i/d14z32muw1ha1zr0e.jpg

**Comment by Wosser** [comment]
Das ist derzeit bei allen Zauberarten der Fall.

**Comment by dagochen** [comment]
Hochstufige Mobs haben eine Grundresistenz gegen alle Arten von Magie, auch Heilig. Dies ist korrekt. Mit dem aktuellen Spielerlevel des Angreifers hat dies nichts zu tun.

**Comment by Sabbaer** [comment]
beweise @dagochen ?

**Comment by Haudraufinix** [comment]
@Larirawiel 
Die "Verfehlten" Zauber werden vom Kampflog auch als Widerstanden gelistet. Sieht nach dem selben aus, hat aber nichts zusammen zu tun.

Ich kann mir nicht vorstellen, dass diese Randommobs ausgerechnet Heiligresistenz besitzen Wenn man Bedenkt, dass kaum ein Open-World Mob überhaupt Resistenzen besitzt (Wobei ich durch den Tooltipp in deinem Screenshot echt verwundert bin. Demnach besitzen sie ja sogar 25% Heiligresistenz?). Sehr wohl besitzen sie aber abhängig zum Angreiferlevel eine Verfehlchance für Zauber, die gegen sie gerichtet sind.
Diese kann man auch nicht komplett negieren, sondern lediglich auf 1% Minimieren (Grundwiderstand)

Daher wärs gut zu wissen, wie viele Zauber denn tatsächlich widerstanden wurden. So könnte man darauf schliessen, wie viele Verfehlt haben, und was tatsächlich widerstanden wurde.

**Comment by dagochen** [comment]
Ich muss nix beweisen. Ich bin weder im Dev-Team, noch habe ich mich mit der Recherche dazu weiter beschäftigt. Aber wenn das so umgesetzt worden ist, wird es wohl eine Quelle dafür geben. 

Die 25% sind die Partial-Resist-Menge, also wieviel Schaden resisted wurde. Und "verfehlen" und "widerstanden" hat etwas mit der Hit-Berechnung zu tun, nicht mit dem Partial-Resist. Das sind zwei verschiedene Dinge, bringt das bitte nicht durcheinander!

**Comment by Wosser** [comment]
Ich hab halt bei Mobs die laut dem Makro ausm Forum 0 Resis gegen meine Spells haben partialresists, das verwundert mich nur.

**Comment by dagochen** [comment]
Vermutlich werden Grundresis nicht über das Makro mit angezeigt?

**Comment by 0815Priester** [comment]
Ist schon komisch warum dieser Lvl 55 Mop deine Zauber teilweise widersteht.

Gibt einen ganz guten thread bzgl. der  Lvl-based-partial resists.
http://www.graffe.com/forums/showthread.php?40025-Partial-resists-and-spell-penetration-on-lvl-61-mobs-%28caster-glancing-blows%29

man könntet ja mal den Test wiederholen den der User aus dem verlinkten thread gemacht hat und damit überpfüfen ob das hier auch so ist.

I found a lvl61 Twilight Overlord mob in silithus, shoot it with 0 -resist items, get partial resists. Then i put on -70items, turn on trinket for another -100, shoot lvl61mob again, get partial resists.

Unequiped my -resist gear again, find lvl60 Twilight Overlord, shoot it for god knows how long with 0 -resist items, no partial resists at all.

Der Lvl 61 Mop befindet sich Nordöstlich bei der Höhle.

**Comment by dagochen** [comment]
Wie gesagt, Grundresis funktionieren anders als normale Resis. Bestätigt der Post ja nur. Werden nicht angezeigt per Makro und lassen sich nicht durch irgendwas verringern.

**Comment by 0815Priester** [comment]
Was ich nicht verstehe, er castet auf LvL 60 Mops und hat 0 Partial resists. Lari castet auf Lvl 55 Mops und hat Partial Resists. Im Kampflog steht ja das 110 widerstanden wurden. Drecks Thema ^^

**Comment by dagochen** [comment]
Staubstürmer und Twilight Overlords sind aber nicht die gleichen Mobs --> Vergleich hinkt vorn und hinten

**Comment by 0815Priester** [comment]
ok,bedeutet das, wenn ich nun CoS auf den Mob draufhaue und Arkane Missels benutze dürfte ich keine Partial resists mehr haben?

**Comment by dagochen** [comment]
Wenn die Grundresis, die über die in der Datenbank enthaltenen hinaus gehen und nicht einsehbar sind, nicht bei dem Mob hinzugefügt werden (weil Level oder was auch immer die genauen Details dazu sind nicht zutreffen), dann sollte das so sein, UND wenn auf Nefarian die gleichen Werte in der Datenbank stehen wie bei mir (welche ich nicht verändert habe, die kommen von classicdb, aber können theoretisch verändert werden), dann ja.

**Comment by Wosser** [comment]
Ich hab jetzt noch nicht genau verstanden was Grundresis genau sein sollen und warum es die geben sollte.

**Comment by Haudraufinix** [comment]
Sowas wie versteckte Resistenz existiert nicht. Die Resistenzen von Mobs können zwar eigendlich NICHT eingesehen werden, ausser man Spielt Jäger ( Wildtierkunde(Nur gegen Wildtiere)) aber sie sind genau so da wie Rüstung und können auch von CoE/CoS etc beeinflusst werden. (Das Makro aus dem Forum kanns by the way Trotzdem)

Dago allerdings stimmt die sache mit der Magieiimmunität gegen die eigene Schule hier auf Nefarian bei weitem nicht. Die meisten Elementare besitzen diese nicht. 

**Da es keinen Widerstand gegen Heiligschaden gibt, darf es partielles Widerstehen nicht geben. Zumindest nicht bei Gegnern, die sich auf Spielerlevel oder darunter befinden. Allerhöchstens ein Verfehlen ist möglich.**

Um da mal drauf zurückzukommen: Ich habe in meinem ersten Post ungenau gelesen und habe nicht gesehen, dass du dich lediglich auf Partialresists beziehst. Sorry an dieser stelle für meinen unsinnigen ersten Beitrag)
Partialresists sollten gegen Mobs ohne Heiligresistenz gegen Spieler über ihrem Level eigendlich NICHT resisten. Das stimmt soweit. Jedoch existieren Heiligresistenzen sehr wohl im Spiel.

*Holy resistance does not currently exist as a visible or collectible statistic in World of Warcraft. It only exists against PvE targets of a higher level.* aus http://wowwiki.wikia.com/wiki/Holy_resistance sagt das zumindest :D

**Comment by Wosser** [comment]
"Partialresists sollten gegen Mobs ohne Heiligresistenz gegen Spieler über ihrem Level eigendlich NICHT auftreten, weil die Parteielresistchance unter 0% fällt. (Formel findet man hier: http://wowwiki.wikia.com/wiki/Resistance) Das stimmt soweit."
Aber eben das stimmt doch nicht, oder?
[URL=http://s923.photobucket.com/user/WosserBijerd/media/Partialresist.jpg.html][IMG]http://i923.photobucket.com/albums/ad76/WosserBijerd/Partialresist.jpg[/IMG][/URL]
[URL=http://s923.photobucket.com/user/WosserBijerd/media/Makro.jpg.html][IMG]http://i923.photobucket.com/albums/ad76/WosserBijerd/Makro.jpg[/IMG][/URL]

**Comment by Haudraufinix** [comment]
Die Aussage stimmt. Nicht der Zustand aufm Server ;)

**Comment by dagochen** [comment]
Vielleicht sollte es mit "hochstufige Mobs" tatsächlich nur Mobs gemeint sein, die über lvl 60 sind, und nicht ab 50 oder 55 oder so?

**Comment by 0815Priester** [comment]
jap, sehe ich auch so.

**Comment by Haudraufinix** [comment]
Kannst du den EJ Post verlinken?

**Comment by 0815Priester** [comment]
also anscheinend weiß das keiner so ganz genau, aber diese 8 geistern halt immer wieder in den EJ threads rum. z.b. hier
http://forums.elitistjerks.com/topic/8975-tbc-beta-and-caster-mechanics-level-based-resists/

**Comment by Sabbaer** [comment]
also holy resi war allgemein extrem selten, und nicht alle mobs mit höherem lvl hatten diese. Such grad schon das video von dem prot pala aus bwl, der tankt da einiges an trash und bei neff die adds und der hat bei dene nef adds z.B. viele teilresists aber bei den anderen mobbs überhaupt nicht, und bei weihe hat er z.B. garkeine teilresists. ich hab in scholo auf lvl 57elite mobbs teilresists von über 75%! Auf untote

**Comment by Sabbaer** [comment]
https://www.youtube.com/watch?v=84OwHLAuQzc in dem ganzen video seh ich eigentlich keinen einzigen partiellen resist auf holy, nur full resists auf exorzismus oder richturteil (was ja auch richtig ist bei uns).
Man beachte v.a. den part in molten core, als er die corehound packs tanked. wenn ich da weihe drücke ist die hälfte mind. teilresisted. 
Bei ihm resisted es KEIN EINZIGES MAL

die einzigen mobbs die mir persönlich bekannt sind mit holy resi sind wyrmkin!
Kein anderer hat holy resi und ich kann mich auch nie erinnern, dass da iwer partielle resists hatte, außer z.B. razergore o.a. wyrmkin!

**Comment by 0815Priester** [comment]
aber hier sieht man doch die partial resists @ Sabbaer https://www.youtube.com/watch?v=ovhRqAxnXqg

**Comment by Haudraufinix** [comment]
Bin gerade über etwas im EJ Forum gestossen.
** mobs DO have holy resistance. Aside from the base misschance any nuke can have, I've seen numerous partial resists on holy spells, someting afaik only happens against resists in this damage type. It happens very rarely though.**
Link: http://forums.elitistjerks.com/topic/6329-offensive-priest-holy-spec/ (3. Post)
Allerdings sagen auch Leute das Gegenteil.

Ich denke jedoch das Retrivideo von 0815Priester zeigt hervorragend, dass es Heiligresistenzen gab. Jedoch treten die Resists sehr selten auf, was für diese 8 Resistenz pro Level zwischen Caster und Ziel hinweisen würde.

**Comment by Larirawiel** [comment]
Gegen höherlevelige Gegner können Zauber tatsächlich teilweise widerstehen. Das stelle ich nicht in Abrede. Aber das passiert aufgrund des Level-Unterschieds. Und da Golemagg Boss-Level hat und Boss-Level sich wie Spielerlevel + 3 verhält wäre Golemagg mit Level 63 gleichzusetzen. Und da kann es ebenfalls dazu kommen, dass Zauber teilweise widerstanden werden.

In meinem Fall ist der Gegner aber 1 Level unter mir. Und dafür gibt es eigentlich nur 2 Erklärungen:

1. Heiligwiderstand
2. Ein Anzeigefehler des Levels des Mobs.


Grüße

**Comment by wahaxlekuke** [comment]
Aktuell haben Mobs mit hoher Stufe tatsächlich ein paar Punkte Heiligresistenz (außer Untoten und Dämonen), allerdings sind Heiligzauber auch nicht von der Level-Based Resistance betroffen.
Mit dem nächsten Update wird also die Resistenz von Mobs unter Stufe 61 wegfallen (bis auf einige Ausnahmen), aber die Resistance für Stufe 63 Gegner wird etwas höher sein als sie im Moment ist.

**Comment by Wosser** [comment]
"Mit dem nächsten Update wird also die Resistenz von Mobs unter Stufe 61 wegfallen"
Bezieht sich das jetzt auf Heilig-Resis oder generell auf Partialresis gegen Mobs mit niedrigerem LvL die angeblich keine Resis haben?

**Comment by Sabbaer** [comment]
"aber die Resistance für Stufe 63 Gegner wird ein wenig höher sein als sie im Moment ist."
jedoch wird heilig resi aus dem spiel entfernt dann? auch für mobbs mit "lvl 63"?

**Comment by wahaxlekuke** [comment]
Es gibt nur die Level-Based-Resistance, die man nicht wegbekommen kann. (Die betrifft alle non-binary Spells)

**Comment by Sabbaer** [comment]
https://www.youtube.com/watch?v=VEs9coe5XRg
https://www.youtube.com/watch?v=rXNWvytYbyo
bitte wegen untote beachten auch mit höherem lvl und dämonen.
habe teilresists auf lvl 61er sowie lvl 60er mobbs bei heiligdmg
