### ISSUE TITLE
Siegel, die debuffs verursachen

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#973]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/875

funktioniert nicht, immernoch werden welchen widerstanden! plz reopen und close diesen hier

**Comment by Haudraufinix** [comment]
Ich bin mal so frei und häng hier https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/727 an
Selbes Problem. Nicht resistbarer Debuff der ebenfalls Widerstanden werden kann

**Comment by Sabbaer** [comment]
yepp, selbes problem, passiert extrem selten bei den siegeln, also vermute ich kommt wegen holy resi

**Comment by ChichiWarrior** [comment]
8/8 Hunter T2 ebenfalls.

**Comment by Sabbaer** [comment]
jo chichi, is oben verlinkt von haudraufinix
