### ISSUE TITLE
Drohruf wird bei Schaden beendet 2.0

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#974]
Das war gefixt, ist es aber leider nicht mehr.

Welches Verhalten wird beobachtet?
Die Spieler/Kreaturen die vom Drohruf getroffen werden, kommen aus dem Fear sobald sie Schaden bekommen haben.

Wie sollte es sich verhalten?
Die Spieler/Kraturen die nicht Ziel des Kriegers sind, sollten herumlaufen und erst nach einer bestimmten Schadensgrenze aus dem Fear kommen. Sie sollten sich also ähnlich wie beim Fear des Priesters verhalten. (funktioniert nicht)
Nur das Ziel des Kriegers sollte auf der Stelle stehen bleiben und sobald darauf Schaden verursacht wird rauskommen. (funktioniert korrekt)

Schritte zur Reproduzierung
Drohruf auf Nebenziele wirken und anschließend Schadenzufügen.

Zusätzliche Informationen (Screenshots, Videos, etc.)
Eintrag aus WoW-Wiki:
http://vanilla-wow.wikia.com/wiki/Intimidating_Shout

Bei 00:09 sieht man wie der Magier im Kriegerfear rumrennt und dabei geschlagen wird.
https://www.youtube.com/watch?v=Y2QIBBKJ1CY

Links aus unserer Datenbank
Drohruf: http://datenbank.welli-it.de/?spell=5246
Effekt 1: http://datenbank.welli-it.de/?spell=20511
Effekt 2: http://datenbank.welli-it.de/?spell=12730

https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/514

**Comment by Slimmer2** [comment]
das wurde doch bei jedem Fear so abgeändert für alle Spells aller Klassen.
Das NPC raus kommen sobald sie Schaden bekommen. 
Finde aber den Report gerade nicht

**Comment by Testear** [comment]
Anderer Spell, andere Klassen, andere Reports.

**Comment by wahaxlekuke** [comment]
Kann ich nicht reproduzieren, weder mit Drohruf noch mit Furcht oder Schreckensgeheul. 

Man muss natürlich beachten, dass bei Schaden immer die Chance besteht, den Fear zu unterbrechen. Aber besonders bei NPC ist die Wahrscheinlichkeit extrem gering, wenn man nur wenig Schaden macht.
