### ISSUE TITLE
Simone the Seductress

### ISSUE THREAD

**Issue by Flako123** [ClassicWoW/Nefarian_1.12.1_Bugtracker#975]
Hallo liebes Classic Team.
Ich habe einen Fehler entdeckt und möchte euch diesen gerne mitteilen.

Server-Version: 1.1.0

Wie sollte es sein?
Simone sollte ca. 50-70 Schaden (non-krit) machen und ihr Pet ca. 140-160 Schaden (non-krit).

Wie ist es?
Simone macht ca. 140-180 Schaden (non-krit) und ihr Pet 430-460 Schaden (non-krit).

Links:
http://datenbank.welli-it.de/?npc=14533 (Simone)
http://datenbank.welli-it.de/?npc=14538 (Simones Pet)

Quelle:
https://www.youtube.com/watch?v=qAAERKlq9ZQ
https://www.youtube.com/watch?v=79vTeVV9iWQ
https://www.youtube.com/watch?v=kQwseC4-1x4

Anmerkung:
Ich bitte darum, den Schaden schnell zu fixen, da durch diesen Fehler die Jägerquest aus Molten Core nur schwer machbar ist.

Vielen Dank,
hoffe auf baldige Rückmeldung.

**Comment by dagochen** [comment]
Joa stimmt, macht echt zu viel Schaden.
Mit folgenden Werten sollte der Schaden ungefähr stimmen. Ist bisschen kniffelig, da die Werte hier unten durch Rüstung verringert werden. Ich hab einfach mit ca 35% gerechnet und bin auf folgende Werte gekommen:
UPDATE `creature_template` SET `mindmg` = '90' , `maxdmg` = '130' WHERE `entry` = '14533';
UPDATE `creature_template` SET `mindmg` = '220' , `maxdmg` = '300' WHERE `entry` = '14538';
