### ISSUE TITLE
Thunderfury und andere Nahkampfwaffen mit extra Elementarschaden

### ISSUE THREAD

**Issue by Testear** [ClassicWoW/Nefarian_1.12.1_Bugtracker#976]
Der Elementarschaden den manche Waffen extra haben wird als Physischer Schaden auf den Grundschaden aufaddiert. 

Er sollte als Extraschaden kommen und einzeln als Elementarschaden (Natur beim Beispiel von Thunderfury) aufgeführt werden. Dazu kann man diesem Schaden widerstehen, teilweise widerstehen, er wird nicht durch Rüstung verringert und Mobs mit Imunitäten sind imun gegen den Magieschaden.
Der Schaden wird im Kampflog zusammengerechnet, wenn geblockt oder widerstanden wird steht immer zuerst Blocken im Kampflog. 

Quellen:

http://www.lurkerlounge.com/forums/printthread.php?tid=4352

Messing around with my hunter a while back, I stumbled across a Hurricane in Un'Goro while questing. Usually I don't have that kind of luck, since I've got a lot of alts. I always find something that can be used by ANOTHER character. So I was pretty pumped to actually get an upgrade piece of gear while questing WITH that character.

The cool part of the weapon, putting it in the family of those such as Thunderfury, the Iceblade Hacker, etc., is that it has elemental damage added.
"Awesome," I thought, "can't be mitigated."
But checking through the combat log showed no frost damage that I could see.

http://www.wowhead.com/item=13982/warblade-of-caer-darrow#comments

The extra frost damage does not show up seperately and is added to the white damage dealt by the weapon. It does break through Blessing of Protection though the damage from that will be rather small.

But checking through the combat log showed no frost damage that I could see.

https://www.youtube.com/watch?v=71QCfREf6Sk#t=278

4:52
1: Glancing Blow
"You hit The Lurker Below for 124. (Glancing)
2: Glancing Blow + Resist
"You hit The Lurker Below for 135. (Glancing) (12 Resisted)
3: Normal hit + Resisted
"You hit The Lurker Below for 191. (6 Resisted)

Thanks to Zetox von Nostalrius

**Comment by Sabbaer** [comment]
also beim raggi hammer sind die bosse immun gegen meinen feuer schaden, vll hilft das

**Comment by Haudraufinix** [comment]
Es geht um die +16 - 30 Nature Damage die Pro Schlag hinzukommen. Keinen Proccschaden Sulfuras besitzt diese Schadensart nicht.

Die Schusswaffen die bis Patch 1.11 ebenfalls Elementarschaden verursacht haben sollten, hatten dies aber auch nie getan. Darum wurden sie Später(1.12) zu den Proccwaffen umfunktioniert.

**Comment by dagochen** [comment]
Jop, weil das für Ranged Waffen schon zu Blizzard-Zeiten nicht funktioniert hatte, wurde das damals zu der Chance on Hit umgewandelt. Bei Nahkampfwaffen sollte es eigentlich funktionieren, needs to be fixed.

**Comment by Sabbaer** [comment]
ah lol, falsch verstanden

**Comment by Seniorash** [comment]
#35 wurde das TF diesbezüglich bereits angepasst. Meines Wissens nach sind die anderen Waffen jedoch immer noch fehlerhaft.
Der Elementarschaden wird nicht separat angezeigt, was auch vollkommen richtig ist. Ansonsten würde man den Naturschaden auch im SCT in alten Videos sehen.
Das mit der Anzeige der Teilresists weiß ich nicht ob es zu Classic auch so war. Kann auch sein dass dem Naturschaden bei uns nicht resisted werden kann.

**Comment by Testear** [comment]
TF verursache komplett körperlichen Schaden. Kein Naturschaden, kein Imun bei den Weltdrachen, kein Teilresist.

**Comment by dagochen** [comment]
Falls sich jemand noch eingehender damit beschäftigen will, hab das mal von Nostalrius geklaut, aber mir ist das zu viel Text ;)

http://forum.nostalrius.org/viewtopic.php?f=24&t=703

**Comment by Testear** [comment]
Genau da hab ich mich durchgewühlt.

**Comment by nightblizard** [comment]
Was ist nun konkret falsch? Dass dir der Elementarschaden nicht extra im Combat Log angezeigt wird? Das war in Classic so und deine erste Quelle sagt so ziemlich das Gleiche. Die andere Quelle stammte aus TBC und da wurden genau solche Sachen in das Spiel eingefügt.

**Comment by Testear** [comment]
Es ist falsch, dass der Schaden komplett als Physischer Schaden gerechnet wird. Dem Elementaren Schaden sollte widerstanden und teilwiderstanden werden können. Gegen Mobs mit Naturresistenzen 
-imunität sollte TF weniger DPS machen als es macht. 

Zusätzlich generiert ein Krieger im Durchschnitt 1 Wut zuviel mit einem TF Schlag. Da der Naturschaden keine Wut regenerieren sollte.

**Comment by nightblizard** [comment]
Ich nehme an du hast das getestet? Denn ich kann das kein Stück reproduzieren. Ich bekomme sowohl resists als auch partial resists in meinen Tests.
Hier Beispielhaft an einem nackten Level 60 Jäger mit 75% Frostresistenz:
![IBild](http://puu.sh/jEm6q/929de63e63.jpg)

Die Waffe:
![!Bild](http://puu.sh/jEmcm/2169b8c81c.jpg)

Die Treffer mit 28 und 29 Schaden stammen von der Grund dps eines nackten Level 60 Orcs.

Hier auch gerne nochmal an einem Frost immunen Ziel:
![Bild](http://puu.sh/jEmj1/5b43484bf4.jpg)

Hab das eine Stunde lang durchlaufen lassen und es kam kein einziges mal Frostschaden an.

Ich denke also das wir aneinander vorbeireden oder du nicht gründlich genug getestet hast.

**Comment by Testear** [comment]
Was soll ich sagen. Ich bin froh, dass es doch keinen Nerv für mich gibt.
