### ISSUE TITLE
Sulfuras, Hand von Ragnaros

### ISSUE THREAD

**Issue by Sabbaer** [ClassicWoW/Nefarian_1.12.1_Bugtracker#979]
Welches Verhalten wird beobachtet?
Der Schaden des Proccs von sulfuras kann teilresisted werden.

Wie sollte es sich verhalten?
Da Sulfuruas neben dem Schaden von Feuerball auch einen feuerball debuff hinterlässt, sollte ihm nicht teilresisted werden können.

Binary Spells
Binary spells are any spells that have a damage component and a non-damage effect. (examples: Frost Bolt, Frost Shock, Blast Wave). Non-binary spells are spells that do only damage. (examples: Shadow Bolt, Fireball, Wrath). Binary spells are either always completely resisted or do full damage.
http://wowwiki.wikia.com/wiki/Formulas:Magical_resistance?oldid=384862

Datenbank
http://datenbank.welli-it.de/?item=17182

**Comment by 0815Priester** [comment]
äh doch.. 1:35 https://www.youtube.com/watch?v=ovhRqAxnXqg

**Comment by Sabbaer** [comment]
dann stimmt also die aussage mit binär und non-binär nicht? Welche ausnahmen soll es denn dazu dann geben.
Wo war es so und wo nicht?
erklär mir doch dann mal bitte, warum das ein binärer oder non binärer zauber ist?

**Comment by 0815Priester** [comment]
steht doch da, binär hat eine NON-Damage effect. Der Proc von Sulfuras ist ein Feuerball +Dmg-Dot.

**Comment by Sabbaer** [comment]
ah ok, löl
