### ISSUE TITLE
BWL: Techniker

### ISSUE THREAD

**Issue by ircfelix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#980]
**Welches Verhalten wird beobachtet?**

Die Techniker in den Trashpacks nach Firemaw machen mit ihren Bomben zu viel Schaden (etwa 1900 non crit) und laufen zu schnell.
Früher konnte man diese Goblinpacks mit einem Hauptbomber wegbomben. So wie es hier auf dem Server ist, ist es zwar anspruchsvoll, aber definitiv nicht blizzlike.
Auch der Giftdebuff erscheint mir viel zu stark, jedoch konnte ich für den keine Quelle finden.

**Wie sollte es sich verhalten?**

Die Techniker sollten langsamer laufen und mit ihren Bomben nicht Leute two-hitten können. Es sollte möglich sein die Techniker mit der in den Quellen angegeben Bombtechnik zu bomben.

*Quelle1:*
"Blackwing Technician:
Kleine Goblins, die mit Dynamit auf ihr nächstes Ziel werfen - da sie relativ langsam laufen, kommen sie meist am Ende des Pulls auf einem Haufen und müssen dann mit konzentriertem AoE getötet werden."
"Ein Jäger pullt die Mobs zum Raid. Daraufhin startet sofort der AoE der Magiern (Blizzard) und Hexern (Feuerregen). Dabei sollte ein Magier mit Ausdauer- und Feuerresiequip in Nahkampfreichweite der Tachniker gehen und diese bomben. SO wird verhindert, dass die Bomben der Techniker auf den Raid geschmissen werden und sie unkontrolliert herumlaufen. Die heilung wird hierbei auf den Magier konzentriert."

*Quelle2:*
Blackwing Technicans
These throw bombs and do **350-400** damage. not a great amount but if all 10 decide to throw them at you they can hurt alot.

**Schritte zur Reproduzierung**

Testet es.

**Zusätzliche Informationen (Screenshots, Videos, etc.)**
Quelle1: http://www.illusions-blackmoore.de/community/index.php?page=Thread&threadID=1436
Quelle2: http://z14.invisionfree.com/Relentlesswow/ar/t693.htm

**Links aus unserer Datenbank (hier gehts zur Datenbank)**

Techniker: http://datenbank.welli-it.de/?npc=13996
Feuerbombe: http://datenbank.welli-it.de/?spell=22334
Gift: http://datenbank.welli-it.de/?spell=22335

**Comment by Gnomorus** [comment]
Und was genau sollte jetzt wie geändert werden, damit die o.g. Taktik durchführbar wird? (Außer der Schaden, der ist eindeutig.)

**Comment by Testear** [comment]
Kurz: Das Bewegungstempo muss verlangsamt werden.

**Comment by dagochen** [comment]
Bei der Feuerbombe steht "Waffenschaden +" und in der nächsten Zeile 300. Und dieser Waffenschaden ist laut der Datenbank wie folgt: Schaden: 1,456 - 1,932

**Comment by nightblizard** [comment]
Die Techniker sind auf Wunsch der Community so schwierig geblieben. Ich sehe das deshalb nicht in all zu naher Zukunft geändert.

**Comment by dagochen** [comment]
Auf Wunsch der Community? Wurden wir dazu gefragt? O_o

**Comment by Testear** [comment]
Oben sind klare Beweise aufgeführt, dass es anders sein sollte. Blizzlike und so.

**Comment by ircfelix** [comment]
Ich weiss dass Bwl im Moment clearbar ist. aber es ist etwas unverhältnismäßig, wenn der trash das schwiergste ist weil allein ein nicht CCter techniker den ganzen raid auslöschen kann.

Wenn die Feuerbombe waffenschaden + 300 macht, sollte man den waffenschaden reduzieren. 

Was das lauftempo angeht: die gepostete quelle besagt dass die techniker sich langsamer bewegen als der restliche trash. Ist im Moment auch absolut nicht der Fall.

Übrigens noch eine Frage: welchen CD haben die beim bomben werfen?

**Comment by dagochen** [comment]
Und die 1,5 Castzeit....naja...das stimmt bei uns auch noch nicht oder?

**Comment by ircfelix** [comment]
Und die range wohl auch nicht.


http://leftoversraiding.org/index.php/topic/781/1/blackwing-lair-summary---pt.-2-(firemaw-ebonroc-flamegor).html

**Comment by ircfelix** [comment]
http://www.strike-us-if-you-can.de/main/frame/HighEndRaid/Pechschwingenhort/bwl-1.htm

Hier noch ein guide von 2006 wie die techniker zu machen sind, mit range angabe der bomben (ca. 5m)

**Comment by ircfelix** [comment]
Hi,

ich wollte nur mal fragen ob das zeitnah in Angriff genommen wird.

Lg

**Comment by Thay-skill3d** [comment]
Irgendwie ist die Aussage bezüglich der Meinung der Community wirklich interessant. Geht es da um die durchschnittliche Meinung oder um die Meinung von 1-2 Personen der länger auf diesem Server bestehenden Gilden, welche dementsprechend auch außerhalb von Forum/Bugtracker Kontakt zu z.B. Night haben?

**Comment by armadu** [comment]
Das würde mich auch mal Interessieren ich kann mich nicht daran erinnern mal eine Umfrage oder ähnliches gesehen zu haben

**Comment by ircfelix** [comment]
Ich denke es wurde schonmal gefragt wie bwl sein soll aber das ist a) zu lange her und b) könnte man die fuzzis wenigstens ein bisschen runter tunen. Die techniker zu legen ist weniger eine sache von skill, sondern mehr vom raidsetup, und das sollte eben nicht so sein.

**Comment by ircfelix** [comment]
Ist es so schwer den Datenbankeintrag für movement speed, wurfrange und damage der Techniker zu ändern?
Es wurden nun mehrfach Argumente und Beweise aufgeführt, bitte macht das halt endlich mal.

**Comment by Dotox** [comment]
Mach doch einfach die Query fertig und poste sie hier :)

**Comment by ircfelix** [comment]
Wenn du mir sagst wie gerne!

**Comment by ircfelix** [comment]
P.s. ihr seid die devs

**Comment by Dotox** [comment]
Dann musst du dich leider weiterhin gedulden bis sich jemand von uns damit auseinander setzen möchte :)

**Comment by Slimmer2** [comment]
Es sind aktuell 330 offene Bugs manche Doppelt. Die von 2 Devs in Ihrer Freizeit gefixt werden.
Geduld ist eine Tugend die nicht jeder hat, in unser hektischen Welt

**Comment by nightblizard** [comment]
Wir werden BWL mit dem Öffnen der AQ Tore nochmal im Schwierigkeitsgrad überarbeiten. Es wurden seit der Öffnung von BWL sehr viele Klassenbugs behoben, die die Klassen sowohl generft als auch gepusht haben, jedoch unterm Strich eher generft. Deshalb werden die HP einiger Bosse leicht gesenkt und auch die Techniker werden an das Original angepasst.

**Comment by dagochen** [comment]
@nightblizard Yeah das ist doch nice!
