### ISSUE TITLE
Baron Geddon's Inferno

### ISSUE THREAD

**Issue by cowrea** [ClassicWoW/Nefarian_1.12.1_Bugtracker#981]
<h1>Baron Geddon's Inferno</h1>

Der Zauber <a href="http://wow-mania.com/armory/?spell=19695">Inferno</a> von Baron Geddon löst einen Debuff aus, welcher mit Höllenfeuer eines Hexenmeisters zu vergleichen ist.

Das soll heißen, dass der Zauber nur solange gewirkt wird wie der Debuff aktiv ist. Das Problem sind nun die bekannten 16 Debuffslots. Die Priorität des Debuffs "Inferno" auf Barron Geddon selbst ist zu gering. Fähigkeiten wie Deep Wound eines Kriegers überschreibt den Debuffslot von Inferno wodurch Inferno abgebrochen wird.

Hier ein kurzer Auszug aus dem Kampflog von Wow selbst über den Baron Geddon kampf.

5/27 20:40:01.535  Baron Geddon's Inferno hits Spieler1 for 546 Fire damage.
5/27 20:40:01.536  Baron Geddon's Inferno hits you for 125 Fire damage. (372 resisted)
5/27 20:40:01.536  Baron Geddon's Inferno hits Spieler2 for 249 Fire damage. (248 resisted)
5/27 20:40:01.537  Baron Geddon's Inferno hits Spieler3 for 112 Fire damage. (335 resisted)
5/27 20:40:01.537  Baron Geddon's Inferno hits Spieler4 for 375 Fire damage. (125 resisted)
5/27 20:40:01.537  Baron Geddon's Inferno hits Spieler5 for 500 Fire damage.
5/27 20:40:01.537  Baron Geddon's Inferno hits Spieler6 for 375 Fire damage. (125 resisted)
5/27 20:40:01.538  Baron Geddon's Inferno hits Spieler7 for 336 Fire damage. (111 resisted)
5/27 20:40:01.538  Baron Geddon's Inferno hits Spieler8 for 500 Fire damage.
5/27 20:40:01.538  Baron Geddon's Inferno hits Spieler9 for 550 Fire damage.
5/27 20:40:01.538  Baron Geddon's Inferno hits Spieler10 for 224 Fire damage. (223 resisted)
5/27 20:40:01.542  Baron Geddon is afflicted by Inferno.
5/27 20:40:01.763  Spieler11 begins to cast Healing Touch. 
5/27 20:40:01.764  Spieler12 begins to cast Flash of Light. 
5/27 20:40:01.765  You hit Baron Geddon for 185. (glancing)
5/27 20:40:01.765  Your Seal of Righteousness hits Baron Geddon for 47 Holy damage.
5/27 20:40:01.765  Spieler1 crits Baron Geddon for 868.
5/27 20:40:01.766  Spieler1 gains 1 Rage from Spieler1's Unbridled Wrath. 
5/27 20:40:01.766  Spieler1's Bloodthirst heals Spieler1 for 20.
5/27 20:40:01.767  Inferno fades from Baron Geddon.
5/27 20:40:01.767  Baron Geddon is afflicted by Deep Wound. 

Man sieht, dass in der selben Sekunde in der Deep Wound gewirkt wird das Inferno erlischt.

Hierbei handelt es sich jedoch um vermutungen. Sicher bin ich mir bei der beobachtung eines Gildenkollegen nicht.

Gruß cowrea

**Comment by Gnomorus** [comment]
Wie heißt das Kampflogaddon, welches dir das ganze millisekundengenau anzeigt? Suche schon ewig nach sowas.
