### ISSUE TITLE
Versorger der Shen'dralar versorgt nicht

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#982]
Beim Gastwirt in der Bibliothek in Düsterbruch kann man zwar seinen Ruhestein setzen, er will einem aber keine Waren verkaufen. Das ist recht unerfreulich, weil er der einzige NPC ist, bei dem man das Muster für die Mondstoffrobe kaufen kann.
NPC: http://datenbank.welli-it.de/?npc=14371

**Comment by dagochen** [comment]
-- 1 gossip, 4 vendor, 128 innkeeper
UPDATE creature_template SET NpcFlags = 133 where entry = 14371;
