### ISSUE TITLE
Schmiedekunstquest Feurige Plattenstulpen

### ISSUE THREAD

**Issue by Haudraufinix** [ClassicWoW/Nefarian_1.12.1_Bugtracker#983]
Die Ungebrannten Plattenstulpen für die Quest Feurige Plattenstulpen in LBRS lassen sich in der aktuellen Spielversion nicht Looten. Dadurch ist dieses Rezept für Schmiede nicht erreichbar.

Quest: http://datenbank.welli-it.de/?quest=5124
Item: http://datenbank.welli-it.de/?item=12812
Behälter: http://datenbank.welli-it.de/?object=176089

**Comment by hraesvelgr** [comment]
das ist glaub aufs volk beschränkt. ich konnte sie looten, konnte die weiterführenden quests bei dem npc aber nicht annehmen, da dieser sagte "diese quest ist für euer volk nicht verfügbar" (oder so).
falsch ist es allemal.
