### ISSUE TITLE
Rogue (A) - Gift Quest Klavens Turm

### ISSUE THREAD

**Issue by koba1985** [ClassicWoW/Nefarian_1.12.1_Bugtracker#984]
Die Dämmerwaldtruhe oben im Turm lässt sich trotz Schlüssel im Inventar nicht öffnen.

**Comment by Slimmer2** [comment]
Bitte schliessen.
Die Truhe kann man generell nicht mit Schlüssel öffnen.
Du bist die dann benutze deine Fertigkeiten.
Ich sag nur Skill 50.

**Comment by Slimmer2** [comment]
Nach bist sollte Schurke stehen

**Comment by Gnomorus** [comment]
Man kann Kommentare bearbeiten.

**Comment by Slimmer2** [comment]
Geht mit der Mobilen Anzeige aber nicht zum bearbeiten.
