### ISSUE TITLE
Angereicherter Mannakeks

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#985]
Angereicherter Mannakeks hat bei Benutzung einen CD den man nicht sieht.

Item: http://datenbank.welli-it.de/?item=13724

Nun ist die Frag ob  das CD Symbol  fehlt, oder es keinen CD haben sollte.

**Comment by Slimmer2** [comment]
Der CD geht 30 Sekunden
