### ISSUE TITLE
Sehne eines ausgewachsenen blauen Drachen

### ISSUE THREAD

**Issue by Rinholo** [ClassicWoW/Nefarian_1.12.1_Bugtracker#986]
http://datenbank.welli-it.de/?item=18704
Die Sehne eines ausgewachsenen blauen Drachen droppt laut Datenbank nur mit der quest (1%) von den Blaudrachen in Winterspring.
Hier in den Kommentaren ( http://wowdata.buffed.de/item/Quest/Sehne-eines-ausgewachsenen-blauen-Drachen-18704#comments ) von 2006 steht was von das ein Paladin es looten konnte und auf WoWWiki steht nichts von quest benötigt. 
( http://wowwiki.wikia.com/wiki/Mature_Blue_Dragon_Sinew ).

Vielleicht kennt sich einer aus und kann evtl. ein Kommentar abgeben ob es  nun nur mit  der Quest geht oder auch Ohne.

**Comment by Gnomorus** [comment]
Geht ohne. Droppt auch.

**Comment by Slimmer2** [comment]
Eine solche Frage gehört nicht in den bugtracker

**Comment by Rinholo** [comment]
In der Datenbank steh 1%(Quest) Entweder ist  es in der Datenbank falsch oder ingame 
für mich ist es ein dann ein Bug für den Bugtracker

**Comment by Gnomorus** [comment]
Tippe auf die Datenbank.
