### ISSUE TITLE
classic-wow.org Startseite: RESSOURCEN ÜBERSICHT kann kein Englisch

### ISSUE THREAD

**Issue by Gnomorus** [ClassicWoW/Nefarian_1.12.1_Bugtracker#987]
**Welches Verhalten wird beobachtet?**

Die RESSOURCEN ÜBERSICHT auf der classic-wow.org Seite zeigt den aktuellen Stand der Kriegsbemühungen auf Englisch an.

**Wie sollte es sich verhalten?**

Da sich classic-wow.org rühmt, ein durchweg deutschsprachiger Server zu sein, sollte man dies wohl zumindest auf der Startseite des Servers auch durchsetzen.

**Quelle**

http://www.duden.de
https://www.langenscheidt.de/

**Links (aus unserer Datenbank)**

http://www.classic-wow.org/

**Comment by Slimmer2** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/8680824/9348745/a4cbe1a4-463b-11e5-8087-2ccf45d9d1ce.PNG)
Englisch schaut bei mir anders aus

**Comment by Ghulfang** [comment]
wurde wohl bereits gefixt. bei mir wars gestern auch noch englisch

**Comment by Gnomorus** [comment]
Schnellster Bugfix EU! Top!
