### ISSUE TITLE
Stärkungszauber Sayges dunkles Schicksal des Schadens

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#988]
**Welches Verhalten wird beobachtet?**
 Gibt momentan immer 10% Dmg.

**Wie sollte es sich verhalten?**
Patch 1.9 [Quests & Reputation]

Der Stärkungszauber 'Sayges dunkles Schicksal des Schadens' erhöht jetzt nur den Schaden in einer zufällig festgelegten Reichweite von 1-10%.

http://wowwiki.wikia.com/wiki/Patch_1.9.0

**Comment by Dotox** [comment]
Kannst du bitte den Zauber verlinken? :)

**Comment by 0815Priester** [comment]
http://datenbank.welli-it.de/?spell=23768

**Comment by Dotox** [comment]
Tooltip zeigt zwar weiterhin 10% an, aber das sollte nicht weiter tragisch sein :)
