### ISSUE TITLE
Viper Sting von verschiedenen Hunter auf ein Ziel darf nicht stacken

### ISSUE THREAD

**Issue by 0815Priester** [ClassicWoW/Nefarian_1.12.1_Bugtracker#989]
**Welches Verhalten wird beobachtet?**
Viper Sting [ http://wowwiki.wikia.com/wiki/Viper_Sting ] von verschiedenen Huntern stackt auf das selbe target.

**Wie sollte es sich verhalten?**
Es sollte nicht stacken.

November 18, 2006
Having three each of warlocks and priests, and a hunter (Viper Sting does not stack) makes this fight easier, if you have the coordination together. Basics of this strategy are mana drain...
[http://www.wowwiki.com/Moam?oldid=330317]

It does not stack, the tooltip is wrong. In fact, Serpent is the only sting that does stack. Scorpid does not stack either.
[http://wow.allakhazam.com/forum.html?forum=243&mid=1142357049142101293]

**Comment by dagochen** [comment]
Hier noch der Bluepost dazu:
http://blue.cardplace.com/cache/wow-customer-service/116532.htm

Und in diversen Moam, Jeklik und anderen Bossvideos ist es auch deutlich erkennbar.
