### ISSUE TITLE
Sengender Schmerz Bedrohung

### ISSUE THREAD

**Issue by Armauskugelbob** [ClassicWoW/Nefarian_1.12.1_Bugtracker#990]
Der Zauber Sengender Schmerz des Hexenmeisters verursacht zu wenig Bedrohung.
Zwar wird im KTM ein sehr hoher Bedrohungswert angezeigt, dieser wir allerdings nicht vom Spiel übernommen. 

http://datenbank.welli-it.de/?spell=17923#taught-by-npc

Gerade für das tanken der Twins ist dieser erhöhte Bedrohungswert immens wichtig.

**Comment by Slimmer2** [comment]
Ich kann das nicht bestätigen 
Ich tanke als Hexer in BWL beim Trash die Hexenmeister und habe da die volle Aggro.

**Comment by ChichiWarrior** [comment]
Was ich bei Armauskugelbob bestätigen kann, trifft das bei feueranfälligen Trashmobs schon zu.

Bitte testen Slimmer2.

**Comment by Gnomorus** [comment]
Wie und bei welchen Mobs wurde das getestet? Interessiert mich jetzt auch.

**Comment by ChichiWarrior** [comment]
Bei den 3 kleinen feueranfälligen Trashmobs nach Firemaw, haben zumindest wir schon festgestellt, dass das KTM die Aggro "richtig" anzeigt, aber der Hexenmeister keine Aggro zieht.

Wie es bei anderen Trashmobs aussieht, keine Ahnung

**Comment by Wosser** [comment]
Wir haben es vorgestern bei Mobs in Azshara ausgetestet mit nem Warlock und nem Warri. Der Warri hat etwa 400 Aggro auf einen Mob gemacht, wir haben ausgerechnet ab wann ich Aggro ziehen müsste (auf Range bei 130%) und dann mit Searing Pain Rang 1 hochgearbeitet.
Searing Pain macht mehr Aggro als andere Spells, aber nur 1,5 pro für jeden Punkt Dmg und nicht 2, wie es sein sollte.

**Comment by Gnomorus** [comment]
K. Das ist wirklich interessant und sollte geändert werden.
