### ISSUE TITLE
(Schurke) Vorbereitung/Konzentration teils verbuggt

### ISSUE THREAD

**Issue by hennefpower** [ClassicWoW/Nefarian_1.12.1_Bugtracker#992]
Vorbereitung: Cooldowns werden nicht immer zurück gesetzt
Konzentration: Beendet oft Verstohlenheit

**Comment by Sabbaer** [comment]
Fehler melden
-Titel
Wähle einen kurzen Titel, der das Problem in wenigen Worten zusammenfasst

-Format
Eine Fehlemeldung sollte das folgende Format haben:
Welches Verhalten wird beobachtet?

Wie sollte es sich verhalten?

Schritte zur Reproduzierung

Zusätzliche Informationen (Screenshots, Videos, etc.)

Links aus unserer Datenbank
