### ISSUE TITLE
Fehler in der Datenbank AQ-Quest

### ISSUE THREAD

**Issue by DreamRogue** [ClassicWoW/Nefarian_1.12.1_Bugtracker#993]
Welches Verhalten wird beobachtet?

Hab in der Datenbank nen Fehler gefunden, wonach besagtes Item in UC droppen soll, was so nicht stimmt. Wäre dies so wären 2 Buchteile an der selben Stelle in einer Hordenstadt und keines der Teile in einer Alliestadt.

Wie sollte es sich verhalten?

Eines der Bücher sollte in Stormwind in der Bibliothek liegen.

Schritte zur Reproduzierung

Links anklicken und auf Buffed.de in den Comments gucken.

Zusätzliche Informationen (Screenshots, Videos, etc.)
so ist es: http://datenbank.welli-it.de/?object=180666
so sollte es sein: http://wowdata.buffed.de/item/Verschiedenes/Drakonisch-fuer-Dummies-21107#comments

Buch 4 liegt korrekt in Undercity

**Comment by wahaxlekuke** [comment]
Die Datenbank ist (noch) nicht aktuell. Ingame befindet sich jeweils eins der Kapitel in Stormwind und Undercity.
