### ISSUE TITLE
Leerwandler erzeugt zu viel Aggro

### ISSUE THREAD

**Issue by Wosser** [ClassicWoW/Nefarian_1.12.1_Bugtracker#994]
Hallo! Meinen Tests zufolge erzeugen sowohl Qual als auch Leiden zu viel Aggro, es scheint aber ein bisschen komplizierter zu sein...
Ich habe in Azshara Mobs mit Fluch der Schwäche gepullt, meinen Voidwalker auf passiv gestellt und ihn Leiden casten lassen, ihn dann abgestellt und bin auf Range gegangen und nen Dot hochticken lassen bis ich wieder die Aggro hatte, einmal ohne den Voidwalker zu skillen und einmal geskillt.
Ungeskillt sollte Leiden Rang 4 600 Aggro erzeugen und Qual Rang 6 395, sie machen aber über 90% mehr Aggro. Skillt man den Voidwalker sollten die beiden Spells 30% mehr Aggro erzeugen. In der geskillten Version machen die beiden Spells etwa 76% zu viel Aggro. Kann es sein, je nachdem wie der Quellcode für die Spells aussieht, dass die Grundaggro der Spells deutlich zu hoch ist, die 30% die man skillen kann aber nicht?
Anyway, der Voidwalker macht zu viel Aggro, ungeskillt ist die Diskrepanz zwischen soll und ist größer als mit geskilltem Voidwalker, ich hoffe ihr Entwickler findet heraus was da schief läuft.

Qual:
http://datenbank.welli-it.de/?spell=11775
Leiden:
http://datenbank.welli-it.de/?spell=17752
Voidwalker-Skill im Dämo-Baum:
http://datenbank.welli-it.de/?spell=18707

**Comment by Slimmer2** [comment]
Quelle wo steht wieviel Aggro die Spells machen sollen.
War beim testen Pet auf passiv? auch nach Qual bzw. Leiden?

Beim Hochleveln hatte der Leerwandler die Aggro nie halten können

**Comment by 0815Priester** [comment]
Quelle hat er doch gepostet..

Zauberdetails:
Effekt #1 	Threat
                 Wert: 600
                 Radius: 10 Meter
