### ISSUE TITLE
Belobigungsoffiziere für Ruf beim AQ Event funktionieren nicht

### ISSUE THREAD

**Issue by Taiba01** [ClassicWoW/Nefarian_1.12.1_Bugtracker#995]
Ich kann keine Belobigungsmarken gegen Ruf eintauschen.

**Comment by Gnomorus** [comment]
Na GZ! Und GZ - dieses Ticket hats in die Auswahl der nutzlosesten Tickets 2015 geschafft.

**Comment by ircfelix** [comment]
Also bei mir hats funktioniert. 10 Abzeichen haben 75 Ruf eingebracht. Hast du die bei dem reitenden General abgegeben, wo man auch 30 auf einmal abgeben kann? Dort kriegst du ja zusätzliche Kriegsbeute. Bei den Belobigungsoffizieren der einzelnen Fraktionen kriegst du für 10 Abzeichen 75 Ruf oder für ein Abzeichen 5 Ruf.

**Comment by Taiba01** [comment]
Bei meinem lvl 15 Char hats nicht funktioniert. Bei den Belobigungsoffizieren der Darkspear (neutral) erzählt er mir, das er die Belobigungszeichen gegen Ruf eintauscht, hat aber keine Möglichkeit die Belobigungsabzeichen einzutauschen. Beim Belobigungsoffizier von OG (Freundlich) dasselbe.

**Comment by Gnomorus** [comment]
Wie man leicht sieht, ist die Mindeststufe der Quests 60. Von daher geht alles mit rechten Dingen zu. Die Frage, ob die 60 richtig ist, müsstest du selbst klären. 
http://datenbank.welli-it.de/?quest=8826

**Comment by Taiba01** [comment]
Meiner Erinnerung nach ging das mit dem Ruf Classic auch als Low Level. Grad nochmal aktuell getestet: Für Marken bei den Belobigungsoffizieren geht gar nichts. Beim Reitenden General gibts lediglich Kriegsbeute.

**Comment by Haudraufinix** [comment]
Falcher NPC, die Rufnpcs stehen irgendwo in der Jeweilgen Stadt - schliess bitte das Ticket sobald du sie gefunden hast.

**Comment by Taiba01** [comment]
Ich habe die richtigen NPCs gefragt.
Der für OG steht vor dem Gebäude wo Thrall ist, der für Darkspear davon weiter rechts.

**Comment by wahaxlekuke** [comment]
http://wowwiki.wikia.com/wiki/Quest:Ten_Commendation_Signets?oldid=288676
vom 17. Oktober 2006
>  Level Obtained 
Level 60 

Die Belobigungsoffiziere bleiben aber nach Ende des Events noch stehen, du kannst die Abzeichen aufheben bis du Stufe 60 bist.
