### ISSUE TITLE
Quest: Beads for Salfa

### ISSUE THREAD

**Issue by Bladsn** [ClassicWoW/Nefarian_1.12.1_Bugtracker#996]
Welches Verhalten wird beobachtet?
Bei Abgabe von Winterfall Spirit Beads (5) erhält man lediglich 50 Ruf bei der Fraktion "Timbermaw Hold". 

Quests: 
http://datenbank.welli-it.de/?quest=8469

Wie sollte es sich verhalten?
Bei Abschluss dieser Quest erhaltet Ihr:
0 Erfahrung
75 Ruf mit der Fraktion "Timbermaw Hold"
Auch aus unserer Datenbank zu entnehmen.

Quellen: 
http://wowwiki.wikia.com/Quest:Beads_for_Salfa (Winterspring)
Patch 3.0.2 (14-Oct-2008):  Reputation award was doubled (to 300)
Patch 2.2.0 (25-Sep-2007):  Reputation award was doubled (to 150)
Wenn man von 300 die zwei Patches dividiert, sollte man nach Adam Riese auf 75 kommen.

Schritte zur Reproduzierung
Winterfall Spirit Beads (5) farmen und abgeben. 

Zusätzliche Informationen (Screenshots, Videos, etc.)
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker/issues/908 
Wurde schon mal reportet, allerdings wurden nur die Quests in Feralas angepasst.

Grüße

**Comment by Slimmer2** [comment]
Das wurde noch nicht gefixt

**Comment by Bladsn** [comment]
Anscheinend wurde was getan, weil die 2 NPC's mir auch nur 50 Ruf gegeben haben, nun allerdings 75. 
Jedoch nicht der NPC in Winterspring, deswegen mein erneuter Bugreport. 

Falls dies ein Irrtum meinerseits sein sollte, dann bitte ich dies zu entschuldigen.

**Comment by Slimmer2** [comment]
Dann müsste bei den anderen Report behoben stehen
