### ISSUE TITLE
hexer ZG robe kein bonus

### ISSUE THREAD

**Issue by einpie** [ClassicWoW/Nefarian_1.12.1_Bugtracker#997]
hi
hab die robe aus zg kompet herstelen lassen es gibt abe rkeinen bonus obwol ale 3 set teile komplet sind
http://www.pic-upload.de/view-28098611/hexer.jpg.html

pierre

**Comment by Slimmer2** [comment]
Bist du Schneider mit Skill 300?
Laut Bild nicht

**Comment by Gnomorus** [comment]
Bist du kein Schneider, dann hast du keinen Bonus.

**Comment by hraesvelgr** [comment]
whoa, win xp :o
