### ISSUE TITLE
Verzauberte Goldblutrobe - Xizk Gutstich - Feiner Goldfaden

### ISSUE THREAD

**Issue by Gallagherro** [ClassicWoW/Nefarian_1.12.1_Bugtracker#998]
Xizk Gutstich in Booty Bay rückt den benötigten feinen Goldfaden nicht raus, der nötig ist, um den Hexenmeister-Quest "Verzauberte Goldblutrobe" abzuschließen. Klicke ich auf ihn, so erscheint nur sein Handelsfenster mit Schneiderbedarf.
Über seinem Kopf schwebt ein graues Ausrufezeichen.

**Comment by Slimmer2** [comment]
Das Ausrufezeichen ist die Quest für den Faden.

**Comment by Gnomorus** [comment]
https://github.com/ClassicWoW/Nefarian_1.12.1_Bugtracker mal lesen
